### ISSUE TITLE
`conan user` - Artifactory Access Token Timeout

### ISSUE THREAD

**Issue by Mark-Hatch-Bose** [conan-io/conan#5390] opened 2019-06-22 12:50 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

Conan version 1.16.1
```
When using `conan user` in our CI with an Artifactory Access token I see an expirable token generated which only lasts for 10 minutes. It seems to be 10 minutes every time from `conan user`

Some of our projects have large amounts of dependencies and may require over 10 minutes for an `conan install` command with `-b oudated`. If the token expires within 10 minutes during the install process, it causes CI to fail.

Example:
1. `conan create . -b outdated`
2. Prebuilt packages begin to be downloaded for 5 minutes.
3. Package X needs to be rebuilt, takes 10 minutes to rebuild.
4. At this point access token expired (>10 mins elapsed)
5. Conan attempts to download packages, but token has now expired and download fails.

**Comment by lasote** [comment] 2019-06-22 13:35
Hi! Thanks for reporting.

Could you specify the Artifactory version bring used? 
Is this behavior new?
Can you confirm that you are using an access token as password?
Are you using CONAN_LOGIN_USERNAME and CONAN_PASSWORD env vars or are you calling `conan user` with the hardcoded values? Using the env vars it should try to authenticate again.

The token generated during authentication (not the access token used as password) should not expire ever actually. That is something we are trying to improve with the Artifafory team, so I'm a bit surprised reading this issue.

**Comment by Mark-Hatch-Bose** [comment] 2019-06-22 13:49
Artifactory Version 6.9.1
Not new, we currently are using real credentials as a workaround.
Yes, using access token as password `conan user <user> <access_token>`
Not using ENV vars.

Here you can see the access token, and the token that is generated.
Notice that the generated token is set to expire in 10 minutes
![image](https://user-images.githubusercontent.com/30931281/59964750-e951b580-94d2-11e9-9085-506f56d2590c.png)

**Comment by lasote** [comment] 2019-06-22 13:54
So when using real password the generated token is not expiring? Can you confirm in the artifactory interface? Thanks for you help

**Comment by Mark-Hatch-Bose** [comment] 2019-06-22 13:57
Yes, the only expirable tokens on the server appear to be the ones generated in my tests using an access token.

**Comment by lasote** [comment] 2019-06-22 14:03
Yes. I confirmed that situation. We are trying to improve the auth flow probably with refreshable tokens but it would require changes in Artifactory and Conan client so it will require time.

In the meantime you can:

1. Use env vars to authenticate automatically again when needed.
2. Use the password as you are doing.
3. Adjust the `tokens.cache.idleTimeSecs` system property on Artifactory to extend the duration of the token.

Hope it helps

**Comment by Mark-Hatch-Bose** [comment] 2019-06-22 14:37
For clarity, would #1 work for the situation described above?
This is all within the same `conan create` or `conan install` command so I don't think there is an opportunity to call `conan user` again. Maybe I'm misunderstanding what the ENV variables do. Does it re-authenticate as needed if they are declared? Even in the middle of an install of dependencies?

**Comment by lasote** [comment] 2019-06-22 15:13
Yes. For any 401 from the server it would authenticate again.

**Comment by Mark-Hatch-Bose** [comment] 2019-06-22 16:21
This was very helpful, I was able to switch to the ENV variable without issue. Unsure if you want to keep this ticket open anyway.

**Comment by lasote** [comment] 2019-06-22 16:57
Great! I will keep this open as the issue is real and should work better. Thanks!

**Comment by mindforger** [comment] 2023-03-22 10:47
i am sorry if that question seems stupid, but why is this still a thing? 

it also seems strange since i can access artifacts that are older than my last update via the reauth workaround but not to newer artifacts, which made this very much less obvious to be the actual issue at hand when facing a missing package

**Comment by memsharded** [comment] 2023-03-22 10:57
Hi @mindforger 

This issue is 4 years old, and apparently hadn't been an issue since #5611 implemented refresh tokens, probably this issue should have been closed back then.

So it would be helpful if you can do an updated report, indeed what you are commenting about being able to access some artifacts and not others is very unexpected, as tokens permissions work at the repository level, not at the artifact level. Things like: 
- Client version
- Server version
- Short explanation how to reproduce the issue, steps/commands, etc.

Maybe it is worth to create a new ticket for it.

**Comment by mindforger** [comment] 2023-03-22 11:27
i will try to obtain the informations, i am a bit low in the chain (just a curious user) and don't know how much i can disclose
conan client is 1.57.0
server is a "jfrog" and i don't know who to ask for details or what to look for :(

**Comment by mindforger** [comment] 2023-03-22 12:06
okay issue is "resolved" as the artifactory does not send a 401 or 403 liek described in the fix but a 404 even when it just times out ... so it is not a conan error

**Comment by memsharded** [comment] 2023-03-22 12:24
Ok, thanks for the follow up.

Then I think I am closing this issue as solved, but please if there is any further question or issue don't hesitate to open a new ticket.

**Closed by memsharded** 2023-03-22 12:24 UTC
Labels: type: feature, component: artifactory, stage: queue, priority: medium, complex: medium
