### ISSUE TITLE
[feature] test_package functionality specific for tools intended for build_requires

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#7132] opened 2020-06-02 09:16 UTC
``test_package`` functionality is mostly intended to test library packages, and it injects a ``requires`` to the tested package.

With the new cross-build features and contexts, it would be good to be able to inject it as a ``build_require`` instead, so it is tested as it is going to be used by other packages.

**Comment by theodelrieu** [comment] 2020-06-02 14:49
I second this, it's required to make sure toolchain packages as `android_ndk_installer` work as intended

**Comment by jgsogo** [comment] 2020-06-02 15:01
(About new xbuild model)

My two cents here. Implementing this could a little bit hard:
 * Add the generated package as a `build_require` (some syntactic sugar is enough)
 * The `profile:host` used to build the package would be the `profile:build` in this new graph (only possible if that profile runs in this _build_ machine)
 * We need another profile that will work as `profile:host` here, probably the user wants to provide his own (can we fallback to some default/autodetected profile?)

This would be a huge enhancement, it is needed for Conan Center.

**Comment by KerstinKeller** [comment] 2020-06-03 14:24
I have encountered this situation many times when packaging tools like CMake, Doxygen, ...

Usually I'd say, that a package will bei either a `build_requires` or a `requires` package (e.g. it's a tool or a library, but usually not both (except e.g. specifying `gtest` as a `build_requires` would break that assumption, but maybe you would need different terminology there, e.g. `gtest` would be a private requirement, though you guys discourage that, but different topic.)

So, with the assumption that you usually would have either a tool or a library, you could define different test folder names: `test_package` and `test_build_package` for example. The `test_package` behaves normally, but a `test_build_package` folder would assume, that that conanfile `build_requires` the respective package.
Hence, the `conan test` command could gain a `--build-context` option, that could be specified in case of `test_build_package` folder existance. 

So, it might also be worthwhile to provide the same additional argument to `conan create` that enforces a direct context switch to build the package:
`conan create --build-context --profile:build=xxx --profile:host=yyy`.

A regular `conan create --profile=xxx` will just assume native compilation, e.g. `profile:build == profile:host`, for both `conan create` and `conan test`.

These are just suggestions, I think tackling the cross build issues is not so trivial.

**Comment by jgsogo** [comment] 2020-06-03 14:38
I'd try not to use the name of the `test_package` folder, but something declared in the conanfile inside the test folder. 

Why? While reviewing packages in Conan Center I've missed many times more intensive testing: different options, different generators, consumption as `require` or `build_require`, testing different components,... Some packages compile different projects in `test_package/conanfile.py` and run more than one app to test the package, the conanfile becomes complex and not copy-pasteable. I'd love to split these tests into different `test_xxxxx` folders, so Conan can iterate all of them when running `conan create` (or at least execute one `conan test <test_xxxx> <reference>` for each `test_xxxx` folder).

**Comment by KerstinKeller** [comment] 2020-06-03 15:21
> I'd try not to use the name of the test_package folder, but something declared in the conanfile inside the test folder.

Ok, makes sense, but then how would Conan know of possible context switches? The context switch has to happen before calling Conan, or does it happens inside Conan?

> Some packages compile different projects in test_package/conanfile.py and run more than one app to test the package, the conanfile becomes complex and not copy-pasteable

I think I can image, but rather not take a look 😉 

> consumption as require or build_require, testing different components,...

Btw, are you still considering making `test_package` part of the actual package / recipe? (not binary package, but distributed next to `conanfile.py`).
If this were the case, you could say from the actual conanfile, what tests were relevant in case of a certain build

```
def test(self):
  tests.add_test_requires("test_package/generic_test") 
  if (self.options.comp1):
    tests.add_test_requires("test_package/comp1_test")
  if (self.options.tool1):
    tests.add_test_build_requires("test_package/tool1_test")
```
with
```
  conanfile.py
  test_package
    generic_test
      conanfile.py
    comp1_test
      conanfile.py
    tool1_test
      conanfile.py
```

In my option, it would be worthwile to have all `test_package` content as part of the overall "source" package, e.g. recipe, and the original conanfile can drive what needs to be tested and what doesn't.

**Comment by wdobbe** [comment] 2020-06-10 11:07
The current --profile:build and --profile:host cross compile functionality  in Conan 1.25 breaks the tools.cross_building() function that is often used in test packages to avoid running non-build arch executables. The tools.cross_building() function will return false even when Conan is cross compiling.

if not tools.cross_building(self):
            <run executable>

**Comment by wdobbe** [comment] 2020-12-22 16:15
> Usually I'd say, that a package will bei either a `build_requires` or a `requires` package (e.g. it's a tool or a library, but usually not both

I disagree here. We use several tools that have both an executable that generates source files and a runtime library that is needed to use these generated files. An example is [flatcc](https://conan.io/center/flatcc).
In order to test such a tool when cross-compiling the package being tested should be injected both as _requirement_ and as a _build_requirement_.

**Comment by AbrilRBS** [comment] 2024-01-23 14:46
Closing as solved. `v1` gained the `test_type = "explicit"` a while back in 1.44, and it's the default and only behaviour in Conan 2. This allows for the greatest flexibility of all the proposed solutions :)

**Closed as completed by AbrilRBS** 2024-01-23 14:46 UTC
Labels: type: feature, stage: queue, priority: medium, complex: low
