### ISSUE TITLE
pkg-config for dependency detection

### ISSUE THREAD

**Issue by tru** [conan-io/conan#334] opened 2016-06-19 06:27 UTC
While working on some packages I have run into a problem with some configure scripts that relies only on pkg-config to find it's dependencies (i.e. just setting CFLAGS doesn't help it find the dependency). I started by hacking in support for setting `PKG_CONFIG_PATH` in ConfigureEnvironment like:

```
diff --git a/conans/client/configure_environment.py b/conans/client/configure_environment.py
index cc67480..84953e3 100644
--- a/conans/client/configure_environment.py
+++ b/conans/client/configure_environment.py
@@ -27,6 +27,7 @@ class ConfigureEnvironment(object):
         """
         command = ""
         if self.os == "Linux" or self.os == "Macos":
+            pkgconfigpath = 'PKG_CONFIG_PATH="%s"' % ":".join(self._deps_cpp_info.lib_paths)
             libs = 'LIBS="%s"' % " ".join(["-l%s" % lib for lib in self._deps_cpp_info.libs])
             archflag = "-m32" if self.arch == "x86" else ""
             ldflags = 'LDFLAGS="%s %s"' % (" ".join(["-L%s" % lib
@@ -55,7 +56,7 @@ class ConfigureEnvironment(object):
                                                     debug, include_flags)
             include_paths = ":".join(['"%s"' % lib for lib in self._deps_cpp_info.include_paths])
             headers_flags = 'C_INCLUDE_PATH=%s CPP_INCLUDE_PATH=%s' % (include_paths, include_paths)
-            command = "env %s %s %s %s %s" % (libs, ldflags, cflags, cpp_flags, headers_flags)
+            command = "env %s %s %s %s %s %s" % (libs, ldflags, cflags, cpp_flags, headers_flags, pkgconfigpath)
         elif self.os == "Windows" and self.compiler == "Visual Studio":
             cl_args = " ".join(['/I"%s"' % lib for lib in self._deps_cpp_info.include_paths])
             lib_paths = ";".join(['"%s"' % lib for lib in self._deps_cpp_info.lib_paths])
```

and then making sure that I copied the .pc files into to the lib directory. This worked fine and the packages was now found. The problem is that the .pc file "lies" and doesn't point to the `$HOME/.conan/data/[dependency]...` path but rather to `/usr/local` or whatever the default prefix is. This lead to another problem where it picked up the wrong library (on in /usr/local instead of ~/.conan).

So now I wonder if this can be done even better. Since we have information in `package_info` about what to link and the include directories etc we could write our own `.pc` file and point it to the right directory and we could add it to ~/.conan/data/pkg-config or something and it could have a .pc file for all installed packages.

Is this something we want to do? And in that case where should this code be added, it has to be done somewhere where the final package path is resolved and that the pc file is regenerated if we get a new path.

**Comment by tru** [comment] 2016-06-19 06:27
I am willing to code it up if I get some pointers on where to add it.

**Comment by memsharded** [comment] 2016-06-19 07:57
If I got it right, the best would be to create a "pc" generator, so it would be used the same as the CMake one:

```python
class MyPackage(Conanfile):
      generators = "cmake", "nix_pc"
```
The generator would generate one (or several, one per dependency) .pc files in the current build directory, would the build find them there? I don't know very much about the .pc files, used them as consumer, but never wrote any of them.

There might be a problem with one shared storage for all pc files (like .conan/data/pkg-config), is that it doesn't handle versions, so different versions (or even different user/channel versions) of the same package, would overwrite the .pc file.

**Comment by tru** [comment] 2016-06-19 08:07
Oh that's a good point. I will give this a shot!

**Comment by tru** [comment] 2016-06-19 08:07
It will find it if we set PKG_CONFIG_PATH correctly btw.

**Comment by memsharded** [comment] 2016-06-19 08:43
Should be possible to set it before the ``build()``. Do you want me to help setting up a generator package? Do you know about them? I guess this would be a good use case.

**Comment by tru** [comment] 2016-06-19 08:46
I'll poke at it later. Probably using the txt or gcc generator as examples. The PC files are very basic and it should be easy to generate.

**Comment by memsharded** [comment] 2016-06-19 09:10
Yes, I mean, instead of using the txt or gcc, that are built-in, it might be more convenient to use an external one (versioned, released independent of the main codebase, you can keep your own tooling private easily without having to run a conan fork), like the premake one: 
- https://github.com/memsharded/conan-premake
- https://www.conan.io/source/PremakeGen/0.1/memsharded/testing

**Comment by tru** [comment] 2016-06-19 18:51
Poking around a bit I think that a generator is the right way to go forward but it seems like that code is currently assuming that you only have one file to write, `filename()` only returns one string and `content()` is expected to be written to that file.

May I suggest a slight change to the API where `content()` can return either a `string` and it works like before or it returns a `map` with `{"filename":"content"}` and that can write multiple files. Does that sound ok?

**Comment by memsharded** [comment] 2016-06-19 23:19
Sounds perfect, indeed. Today I'll be offline, but on Tuesday I can work on it, implement (should be easy) or assist with passing tests :)

**Comment by memsharded** [comment] 2016-07-07 07:47
Hi @tru!
The multi-file generator API is already working (and released in latest 0.10). Did you have a chance to try to do this .pc generator? Do you want help with it? I might try to do it too.

**Comment by tru** [comment] 2016-07-07 07:54
Sorry I haven't updated here but I am on summer vacation for a couple of weeks. I already have a working PC file generator now. It was pretty easy to do. I'll share it as soon as I am back at my office.

**Comment by memsharded** [comment] 2016-07-07 08:06
Ey, no worries, no hurries! Just wanted to know the status of this issue to assign it myself if necessary. Enjoy your holidays :)

**Comment by lasote** [comment] 2016-07-07 10:06
Yeah! forget about conan and enjoy the summer!

**Comment by memsharded** [comment] 2016-10-05 09:37
Hi @tru 

Resuming work on this issue, as I need related functionality. My current problem is:

- The opencv project I am packaging already creates a ``opencv.pc`` file at build time. It contains many libraries, as opencv itself has quite a few, plus the external dependencies, some of them complex as gtk2 (with gtk transitive dependencies too, all installed from apt-get, invoked from ``system_requirements()``.

- The orden of libraries matters for linking, not obvious, not documented for opencv.

- I can code, or copy & paste the ``opencv.pc`` libs section, but I think that a parser for ``.pc`` files could be convenient

What do you think? Interesting feature?

**Comment by memsharded** [comment] 2016-10-05 11:02
Just in case: conan 0.13.1 has introduced many improvements. One of them is that we have changed the flow of processing for ``package_info()``, now it is executed **after the package has been built or retrieved**, so ``package_info()`` has full access to the ``self.package_folder`` contents.

A good example is the new ``ConanFile.collect_libs()`` method, that obtains the current libs from the package folder, so they might not need to be defined in ``package_info()`` (they still should be if they are dependent, as link order is important, and that cannot be deduced). Similarly, an ``opencv.pc`` can be read in ``package_info()`` now, and information extracted from there.

**Comment by kent-at-multiscale** [comment] 2017-01-16 19:35
I don't think a generator is the right approach to this. The only work required by consumers is to set the environment variable `PKG_CONFIG_PATH` correctly, the rest must be done during the package build.

What we need to do is provide a helper function of some kind to be used in the `package()` method that edits the `lib/pkgconfig/*.pc` files to strip out any string matching the ${CONAN_USER_HOME} value and replace it with the literal text "`${CONAN_USER_HOME}`". This assumes that environment variable is already available when running conan. It would be nice if this helper ran automatically as part of the `package()` method, but we could just provide a helper like with `self.copy()`.

**Comment by lasote** [comment] 2017-01-17 08:24
About the @kent-at-multiscale last comments and the opened PR #868 I see some problems but I'm sure with little time we can achieve some good solution to ``pc`` files:

- I don't like too much to guess the local cache storage directory layout, maybe the app at this level should keep agnostic about the path `data/foo/.../lib/pkgconfig`. Not a big thing and possible solutions available.
- Maybe we could think about new env variables pointing to the ROOT folder of each package, the same as we do with CMake.
- There are some other issues related with ConfigureEnvironment that probably deserve a refactor.
- Agree about some helper that "fixes" the pc files.

**Comment by kent-at-multiscale** [comment] 2017-01-17 17:26
I'm currently working on my own package, trying to get the *.pc files it generates to not have system-dependent paths in them. I noticed the location of the Conan local cache that we install into is already available from the settings. The `ConanClientConfigParser` has a `storage_path` property that encapsulates the logic Conan uses for finding the local cache. That is the definitive answer, how can I get access to that property in my own conanfile? Using that property guarantees us that anything "installed" into the `conanfile.package_folder` will have that prefix for installation location-dependent paths, I just need access to it. Can anybody help me figure out how to reference it?

**Comment by kent-at-multiscale** [comment] 2017-01-17 20:39
I came up with this code to put into my `conanfile.py`, the `build` method, after `make install`.

```python
        conan_user_home = '/home/username/.conan/data'
        pkgconfig_pattern = '%s/lib/pkgconfig/*.pc' % self.package_folder
        for pkgconfig_file in glob.iglob(pkgconfig_pattern):
            _, tempname = tempfile.mkstemp()
            with open(tempname, 'w') as output:
                with open(pkgconfig_file, 'r') as input:
                    output.write('conan_user_home=${CONAN_USER_HOME}\n')
                    for line in input:
                        output.write(line)
            os.rename(tempname, pkgconfig_file)
            conans.tools.replace_in_file(pkgconfig_file, conan_user_home, '${conan_user_home}')
```

Clearly the first line needs to be customized. I would like to replace that with a call to the `storage_path` property, I just need to know where to find it. I would also like to make sure that the `${CONAN_USER_HOME}` can be expanded properly in future invocations of conan, such as when another developer installs the package I built.

The latter will possibly require edits inside of the conan tool. Can anybody help me with the former?

**Comment by lasote** [comment] 2017-02-01 14:46
So, @kent-at-multiscale, @tru  We are organizing next release and I would like to finally give some general support for pkg-config.

If I'm right there are two problems to solve:
1. Let pkg-config command or Autotools using pkgconfig macros to locate out `pc` files. This can be done manually or with ConfigureEnvironment by setting the `PKG_CONFIG_PATH` variable, as @kent-at-multiscale did in PR #868
2. Adjust the prefix variable for our dependencies to point to the real installed package route.

I've been considering several options for the prefix

1.  The parameter `--define-prefix` option used by @tru has two drawbacks, first, you need to wrap the pkg-config command with a shell script, and it's only available from pkg-config 0.29. Unexpectedly, Debian latest stable includes 0.28. **Discarded**
2. A promising environment variable `PKG_CONFIG_$PACKAGE_$VARIABLE` that allows overriding any variable in any package. But it seems it's only available at pkg-config 0.29.1 (Not even in testing for debian distributions) **Discarded**
3. In the `build()` method import the `pc` files from our dependencies and patch them with the right prefix. It would be nice if some of you could try this approach:

```
class HelloConan(ConanFile):

    ....

    def build(self):
        copied = self.copy(src=self.deps_cpp_info["Hello0"].rootpath, pattern="*.pc").execute()
        pkg_config_paths = []
        for pcfile in copied:
            replace_preffix_in_pc(pcfile, self.deps_cpp_info["Hello0"].rootpath)
            pkg_config_paths.append(os.path.dirname(pcfile))

        with tools.environment_append({"PKG_CONFIG_PATH": ":".join(pkg_config_paths)}):
            # INVOKE YOUR BUILD SYSTEM (configure, make etc)

       

def replace_preffix_in_pc(pc_file, new_preffix):
'''This method could be incorporated to the tools'''
    content = tools.load(pc_file)
    lines = []
    for line in content.splitlines():
        if line.startswith("prefix="):
            lines.append("prefix=%s" % new_preffix)
        else:
            lines.append(line)
    tools.save(pc_file, "\\n".join(lines))

```

If you think that code works we could simplify the `PKG_CONFIG_PATH` using the ConfigureEnvironment and provide the `replace_preffix_in_pc` function in tools. Maybe documenting the way to do it would be enough.
What do you think? Could anyone give it a try with a real example? @tru @kent-at-multiscale

**Comment by lasote** [comment] 2017-02-01 14:53
We could even provide a `import_and_patch_pc_files` or something like that but maybe it's too dark, the thing is the `import` code doesn't look complicated.

**Comment by tru** [comment] 2017-02-01 15:03
That's an interesting approach for sure. I don't think I have much time to experiment with this right now - but I am very curious to try it out. If you could push a branch with the right tools I might be able to try it out relatively soon.

**Comment by memsharded** [comment] 2017-02-01 15:05
Maybe an idea could be to wrap the functionality in one ``generator``, and adding such generator will automatically do both the copy and the replace_prefix tasks.

**Comment by sztomi** [comment] 2017-02-01 15:34
>The problem is that the .pc file "lies" and doesn't point to the $HOME/.conan/data/[dependency]... path but rather to /usr/local or whatever the default prefix is. This lead to another problem where it picked up the wrong library (on in /usr/local instead of ~/.conan).

The right approach here would be to set the installation prefix and use `make install` instead of manual copying. Because setting the prefix is not only about choosing a target folder for installation, this is also where `/usr/local` comes from in the .pc files (as a default value). Unless there is a bug in the software being packaged, of course.

There *is* value in providing a pkg-config generator, but replacing the .pc files from the software being packaged is fragile at best.

**Comment by lasote** [comment] 2017-02-01 15:45
> The right approach here would be to set the installation prefix and use make install instead of manual copying. 

That's the problem to solve, the installation prefix is valid only for the machine that has been generated the package, not for reusing them, where the path will be different.

**Comment by sztomi** [comment] 2017-02-01 15:55
Ah, you are right, I always forget this because I always rebuild everything.

**Comment by kent-at-multiscale** [comment] 2017-02-01 17:23
I have some prototype code to do exactly this. It is not thoroughly tested yet, but in theory it should work. I’ll try to clean it up (and strip out internal company parts) and send it out for people to see later today.

-Kent

**Comment by kent-at-multiscale** [comment] 2017-02-01 18:18
What I have here will strip the machine-specific parts of the [lib, share]/pkgconfig/*.pc files and replace them with a variable. When determining the package_info, it mines the contents of those same [lib, share]/pkgconfig/*.pc files. In this way Conan is re-using the data already embedded in the pkgconfig files generated as part of the build.

When a consuming package wants to use pkg-config --exists zlib, we run into the PKG_CONFIG_PATH version problem. We can set that in the Conan wrapping package’s package_info method, there’s a comment at the end of the attached file mentioning this. But in order for pkg-config --cflags zlib to work, we need to pass --define-variable conan_storage_path=~/.conan/data, only use the machine-specific path instead of the generic default ~/.conan/data.

I don’t see a generic all-inclusive way to fix this. Perhaps provide tools that can do a search & replace of build files to insert the --define-variable in calls to pkg-config? Or maybe we could alias pkg-config for the child process that runs the build.

The other option would be to modify/rewrite the [lib, share]/pkgconfig/*.pc files during install so they are correct for the local machine. If we do that, we would also need to modify/rewrite them during upload so that the machine-specific parts do not end up in the shared Conan repository. I don’t like this solution. But it would be pretty simple. I did not implement this in my attached sample because as I understand it, package_info runs an arbitrary number of times on the same installed package, so editing files in it seemed unwise.

-Kent
Multi-Scale Health Networks

**Comment by kent-at-multiscale** [comment] 2017-02-01 18:36
Oh, a couple key points I should highlight. For this to work, I had to do a few things:
The configure/install had to be specified to install into the Conan self.package_folder. That was key so that the generated *.pc files had the right paths in them, specifically the part that was “<package_name>/<version>/<user>/<channel>/package/<sha_id>/[bin, lib, share]” portion.
The location of the Conan storage directory had to be removed from the *.pc files. But we still needed the above part, so installing into the Conan package_folder is still mandatory.

The resulting *.pc file starts like this:
conan_storage_path=~/.conan/data
prefix=${conan_storage_path}/zlib/1.2.11-6/kent_at_multiscale/testing/package/c9d49591c9acf1080dc5587c6b43864e6e646d89

As you can see, replacing the prefix is not necessary anymore. Only substituting in the conan_storage_path for the machine, which is a constant for all packages.

-Kent

**Comment by lasote** [comment] 2017-02-02 08:16
I'm not sure about your approach:

> The location of the Conan storage directory had to be removed from the *.pc files.

Not only the storage path, if you hard code the user or the channel the recipe will be useless if anyone "conan copy" the recipe to other user or even promote the recipe to another channel "testing => stable"

I think that the "consumer" library (the one with autotools requiring the `pc` of the dependencies)  needs to adjust the "prefix" variable and point it to the roopath of the package:

 `replace_preffix_in_pc(pcfile, self.deps_cpp_info["Hello0"].rootpath)`

or whatever other places:

 `replace_preffix_in_pc(pcfile, "%s/lib/custom/location" % self.deps_cpp_info["Hello0"].rootpath)`
 
This way, It doesn't care if the package of the libraries being reused (Hello0) has adjusted the `pc` files, "me" as a consumer in the build method will adjust them.

Do you have any recipe I could use to try it? If don't, any OS library using autotools to reuse another library with pc´s?

**Comment by kent-at-multiscale** [comment] 2017-02-02 17:20
> On Feb 2, 2017, at 12:16 AM, Luis <notifications@github.com> wrote:
> 
> I'm not sure about your approach:
> 
> The location of the Conan storage directory had to be removed from the *.pc files.
> 
> Not only the storage path, if you hard code the user or the channel the recipe will be useless if anyone "conan copy" the recipe to other user or even promote the recipe to another channel "testing => stable”
> 
Isn’t this exactly the point of a dependency management system? In Maven, if I create a new version of Junit with a different version number or a different group ID, consuming packages do not pick them up unless they explicitly change their dependency to point to the new one. That’s how dependency management systems work. If I declare I depend on “zlib/1.2.11@kent_at_multiscale/stable”, then my application should continue to use that binary and nothing else, not any “*/testing” and not any “*@lasote/*”. I must opt in to a different username or channel or version.

(On the subject of using channel for promotions from release candidate to final release, that’s a completely different discussion. Right now it’s not at all useful in that capacity, but I don’t want to suggest alternatives in this thread and confuse the issue we’re actually discussing.)

As for sample code, I was working on that yesterday. It doesn’t work yet (obviously due to the missing feature we’re currently discussing) but here’s what I was thinking it should look like (missing proper handling of CONAN_USER_HOME, special-cased for zlib only):

conanfile.py:

import os

import conans


class AutomakeZlibUser(conans.ConanFile):
    """
    This tests the zlib package by building an application that links to libz.
    This uses Automake and Autoconf to build.
    """
    settings = "os", "compiler", "build_type", "arch"
    requires = "zlib/1.2.11-6@multiscalehn/stable"
    generators = "env"
    
    def build(self):
        env = conans.ConfigureEnvironment(self)
        
        pkg_config_path = os.pathsep.join(self.deps_env_info['zlib'].pkg_config_path)
        self.output.info('PKG_CONFIG_PATH=%s' % pkg_config_path)
        # TODO: use `which pkg-config` to get the full path of the executable
        pkgconfig_exec = 'pkg-config --define-variable conan_storage_path=%s' % (os.path.join(os.path.expanduser('~'), '.conan', 'data'))
        with conans.tools.environment_append({'PKG_CONFIG_PATH': pkg_config_path, 'PKG_CONFIG': pkgconfig_exec}):
            self.run('autoreconf --install', cwd=self.conanfile_directory)
            self.run('%s' % (os.path.join(os.curdir, 'configure')), cwd=self.conanfile_directory)
            self.run('make', cwd=self.conanfile_directory)
    
    def test(self):
        self.run('%s' % (os.path.join(self.conanfile_directory, 'src', 'main')))

configure.ac:

AC_PREREQ([2.69])
AC_INIT([autoconftest], [1.2.11], [kent.rosenkoetter@multiscalehn.com])
AM_INIT_AUTOMAKE([-Wall -Werror foreign])
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_FILES([Makefile src/Makefile])

# Checks for programs.
AC_PROG_CXX
#PKG_PROG_PKG_CONFIG

# Checks for libraries.
PKG_CHECK_MODULES([ZLIB], [zlib = 1.2.11])

# Checks for header files.

# Checks for typedefs, structures, and compiler characteristics.

# Checks for library functions.

AC_OUTPUT

Makefile.am:

bin_PROGRAMS = main

main_SOURCES = main.cpp
main_CFLAGS = $(ZLIB_CFLAGS)
main_LDADD = $(ZLIB_LIBS)

What do you think? I was thinking some functionality similar to what currently exists for env_info.path duplicated for PKG_CONFIG_PATH, so packages can declare what they want to append to the path and consuming packages get it for free by using ConfigureEnvironment.

-Kent

**Comment by memsharded** [comment] 2017-02-02 21:11
>Isn’t this exactly the point of a dependency management system? In Maven, if I create a new version of Junit with a different version number or a different group ID, consuming packages do not pick them up unless they explicitly change their dependency to point to the new one. That’s how dependency management systems work. If I declare I depend on “zlib/1.2.11@kent_at_multiscale/stable”

This is exactly how conan works. A package recipe defines a dependency to another given recipe, like ``zlib/1.2.11@kent_at_multiscale/stable``. That package will use that dependency. But equal to Maven, that dependency can be overriden, if downstream, the final consumer declares to use ``zlib`` in another form, like a new patch version ``zlib/1.2.12@....``, then such dependency will have priority and will be used upstream. There is a way that might avoid that overriding, is using ``private`` dependencies, but these must follow some constraints, like not being transitive in the public headers.

**Comment by kent-at-multiscale** [comment] 2017-02-02 21:25
And that’s fine, because if a consumer overrides a transitive dependency, then Conan will point to the replacing package instead, which will have the self-referential pkg-config files in it. Everything is working as intended.

**Comment by memsharded** [comment] 2017-02-02 22:20
Yes, exactly that, great.

But the issue that @lasote was describing is not related to the case that another package depending on it will have the dependency replaced, that won't happen.

The issue is when you have a package with a .pc as the one you describe with the prefix, under an ``username\channel``, lets say ``kent\testing`` and you decide to "promote" it to stable, which is basically a copy of it under the ``kent\stable`` channel. The ``conan copy``  command that does that is indeed a copy of the artifacts. If such copy is done for your package, the "promoted" copy becomes wrong, because it will contain a ``,pc`` file that points to ``kent\testing`` path instead of its own ``kent\stable`` path.

Modifying the artifacts, or the .pc while copying doesn't seem a good idea, the manifests of the packages will change and have to be artificially forced to regenerate. Fails and bugs can be introduced. The goal of the copy is precisely to "freeze" something that is working without altering it at all.

This is why it seems that something that deals with this prefix could be required on the consumer side.

**Comment by kent-at-multiscale** [comment] 2017-02-02 22:39
Ahh, I understand. Thank you for the explanation, I was not able to deduce any of that from the online docs. Is there any documentation explaining the concept of “promoting” a build as you describe? I couldn’t find any guidance at all on ways to make use of the channel parameter, I was simply treating it as an opaque identifier.

If indeed channel is intended to be used in a linear or hierarchical fashion, it is not opaque and shouldn’t be treated as such.

I guess I can change the filtering code to make use of self.username and self.channel, but as a general law of nature we cannot change the semantics of a build without re-building it. Going from testing to stable is a semantic change, it is just as disruptive as re-compiling a debug build as a release build, disabling -g, adding optimization flags, etc. Between issues like pkg-config files and @rpath issues on Mac, copying artifacts between different configurations is just problematic in the C/C++ world.

(I’m still trying to get an @rpath-enabled build of a shared library to work on my Mac. I can build the library, I just can’t get an executable to link to it. I’m still experimenting with DT_RPATH on Linux, too.)

**Comment by memsharded** [comment] 2017-02-02 23:02
I think that just the reference: http://docs.conan.io/en/latest/reference/commands.html#conan-copy

A channel name change wouldn't necessarily be a change in the semantics. In fact, one of its mains use is using it as a quality tag while promoting. Totally different from changing a build setting or option, is quite the opposite: you have a fully working package, everything is good, you are fine with it, so you just want to promote its quality, change the "testing" tag, and name it "stable", without going to hours of build and testing again, to build exactly the same binaries.

Another usage of the channel, is as a build tag, even point it to one commit. In that case, it clearly changes the package semantics, and re-build is necessary, such channel promotion (copy) doesn't make sense at all.

The issue is that we have active users using both approaches. More the first one. Forcing them to re-build for a package channel promotion would extremely annoy them, so we don't want to break their flows. On the other hand, we have to look for a solution for the PKG_CONFIG, otherwise that feature will be broken for such promotions. This happens very often, there is no single solution or absolute truth, but trade-offs that have to be done, trying to be as close to the optimum as possible for the largest number of users.

**Comment by memsharded** [comment] 2017-02-20 09:31
This need stabilizing first all the ``environment`` related things, so better move it to 0.21

**Comment by kent-at-multiscale** [comment] 2017-02-21 07:29
I have a working prototype of Conan packages that provide functional pkg-config files and other Conan packages that successfully consume those pkg-config files. I hope to put them someplace public soon so people can look at them and debate the approach I have taken. It does not meet all of the goals outlined in this thread, but it does meet some of them. (I don’t think we can actually meet all of the desired goals.)

One technical issue forced my hand. We are able to provide many paths through `PKG_CONFIG_PATH`, but we can only substitute one variable value at a time and a single invocation of pkg-config needs to resolve multiple packages. That issue forced me to use the `conan-storage-path` as the constant across packages, rather than the `prefix`. It will make sense once I get some packages cleaned up and posted publicly.

**Comment by memsharded** [comment] 2017-02-21 09:20
Ok, great, looking forward to seeing your approach, thanks for the update!

**Comment by kent-at-multiscale** [comment] 2017-03-09 07:36
I finally started uploading some packages using this to the public repo.

https://github.com/kent-at-multiscale/conan-zlib

In the `conanfile.py` for my build of zlib, I let the existing zlib build produce its `zlib.pc` file as it already does. Then in my `package_info` method, I parse the generated file to pick out the flags that should be passed on to consumer packages.

https://github.com/kent-at-multiscale/conan-zlib/blob/master/conanfile.py#L124

This is where I edit the generated `zlib.pc` to strip out anything specific to the machine.

https://github.com/kent-at-multiscale/conan-zlib/blob/master/conanfile.py#L172

This is where the `package_info` method parses the generated `zlib.pc` to get the flags consumers should use.

https://github.com/kent-at-multiscale/conan-zlib/blob/master/test_autotools/conanfile.py#L72

This is where a test packages consumes the zlib dependency. I set the `PKG_CONFIG` variable so it passes the `conan_storage_path` variable correctly for the local system. `PKG_CONFIG_PATH` is already set in the zlib package's `package_info`.

https://github.com/kent-at-multiscale/conan-zlib/blob/master/test_autotools/configure.ac#L13

Here's where the test package uses standard autoconf macros to consume the `zlib.pc` file, completely ignorant of Conan.

**Comment by kent-at-multiscale** [comment] 2017-03-09 07:40
My most interesting use of this technique so far is for a "pthreads" package that provides no binary artifacts. Instead it uses autoconf to determine what compiler flags are needed to link with pthreads, generates a `pthread.pc` file, and then parsing that file in its `package_info` method. The end result is that if a package declares a dependency on the pthreads package, when it builds it will automatically inherit the correct compiler and linker flags for both its platform and the compiler it is using. I use this so I don't have to do conditional logic when I build threaded libraries on both Mac and Linux.

**Comment by lasote** [comment] 2017-03-10 09:44
I don't fully understand the example, but I think it has a problem. If you modify files in the package folder conan will tell you that the package is corrupted if you try to re-upload those packages. right?

**Comment by lasote** [comment] 2017-03-10 12:04
Hi @kent-at-multiscale I've prepared an example of reusing `zlib` and `libpng` with their `pc` files using autotools the same way you are doing in your example. The repository autotools scripts doesn't know either about conan, just the conanfile.py importing and adjusting the `pc` profiles. Please take a look and tell me what's the problem doing it that way.

https://github.com/lasote/conan_reuse_pc

Thanks

**Comment by kent-at-multiscale** [comment] 2017-03-10 17:31
I'm not modifying files in the conan package folder after the package has been created. Before the package has been created I edit the *.pc files so their prefix is relative to a variable called "conan_storage_path", and then when consumer packages use `pkg-config` they define that variable without modifying the *.pc files themselves, or copying or moving them out of their package.

What you are doing in your example is actually very different than what I do in mine. You are importing the *.pc files into the local project and editing them. My example never imports them and never edits them after the package is created. Also, the package that provides the *.pc file also appends the correct directory to `PKG_CONFIG_PATH` so consumers automatically get a full path composed of all dependency packages that provide *.pc files.

My example is essentially these lines in the consumer package:
```python
    build_env = conans.AutoToolsBuildEnvironment(self)
    vars = build_env.vars
    vars['PKG_CONFIG'] = 'pkg-config --define-variable conan_storage_path=%s' % (conan_storage_path)
    with conans.tools.environment_append(vars):
        self.run('autoreconf --install')
        self.run('%s' % (os.path.join(os.curdir, 'configure')))
        # etc.
```

It's purely consuming, I envision the line defining the env variable `PKG_CONFIG` could be provided by a conan helper or the AutoToolsBuildEnvironment.

**Comment by kent-at-multiscale** [comment] 2017-03-10 17:48
The heavy lifting for mine happens during package creation. The build itself creates a *.pc file that looks something like this:

```text
prefix=/Users/krosenkoetter/.conan/data/zlib/1.2.11-10/multiscalehn/stable/package/b5d68b3533204ad67e01fa587ad28fb8ce010527
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: zlib
Description: zlib compression library
Version: 1.2.11

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lz
Cflags: -I${includedir}
```

The prefix is due to me building the package with `--prefix=self.package_folder` so that `make install` puts files directly into the conan package destination. This step is important.

After the `make install`, I run this code in the package method:

```python
#         conan_storage_path = conans.client.client_cache.ConanClientConfigParser.storage_path
        # TODO: Replace this with the already-configured storage path in Conan
        conan_user_home = os.getenv('CONAN_USER_HOME', '~')
        conan_storage_path = os.path.join(os.path.expanduser(conan_user_home), '.conan', 'data')
        # If there are configuration files for pkg-config, they will contain
        # hard-coded paths where the library was installed.
        # We need to remove those and replace them with a placeholder that
        # Conan can fill in on any other machine as appropriate.
        for libdir in ['lib', 'share']:
            pkgconfig_dir = os.path.join(self.package_folder, libdir, 'pkgconfig')
            if os.path.isdir(pkgconfig_dir):
                pkgconfig_pattern = os.path.join(pkgconfig_dir, '*.pc')
                for pkgconfig_file in glob.iglob(pkgconfig_pattern):
                    self.output.info('Stripping Conan storage directory (%s) from pkg-config file %s' % (conan_storage_path, pkgconfig_file))
                    _, tempname = tempfile.mkstemp()
                    with open(tempname, 'w') as output:
                        with open(pkgconfig_file, 'r') as input:
                            output.write('conan_storage_path=~/.conan/data\n')
                            for line in input:
                                output.write(line)
                    shutil.move(tempname, pkgconfig_file)
                    conans.tools.replace_in_file(pkgconfig_file, conan_storage_path, '${conan_storage_path}')
```

This edits the *.pc file so it now looks like this:

```text
conan_storage_path=~/.conan/data
prefix=${conan_storage_path}/zlib/1.2.11-10/multiscalehn/stable/package/b5d68b3533204ad67e01fa587ad28fb8ce010527
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: zlib
Description: zlib compression library
Version: 1.2.11

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lz
Cflags: -I${includedir}
```

The value `~/.conan/data` is just a placeholder, it should never get used. (In fact it's invalid.) The important point is that the prefix still points inside of the conan storage, and the conan root is now a variable. The variable is the same for all packages on a machine, but it will be different on every machine running Conan.

Finally, this is included in the package_info method:

```python
        # pkg_config_path is a custom variable we add to the existing Conan env_info
        self.env_info.PKG_CONFIG_PATH = []
        for libdir in ['lib', 'share']:
            pkgconfig_dir = os.path.join(self.package_folder, libdir, 'pkgconfig')
            if os.path.isdir(pkgconfig_dir):
                self.env_info.PKG_CONFIG_PATH.append(pkgconfig_dir)
```

That adds the package's `lib/pkgconfig` folder to the `PKG_CONFIG_PATH` that the consumer package inherits. The rest of that method is just me parsing the *.pc file to extract the compiler and linker flags so that consumer packages will still get them even if they do not use pkg-config, for example if they use cmake. That's why I created multiple test_packages. One uses autotools, one uses cmake, etc. The test packages always follow a standard template, the goal is that they should all look the same for a build tool. Then anybody who wants to use that build tool just has to follow the template, no custom code required.

https://github.com/kent-at-multiscale/conan-zlib/blob/master/test_package/conanfile.py#L34

**Comment by lasote** [comment] 2017-03-13 08:48
@kent-at-multiscale thanks so much for the detailed explanation.
I'm trying to think how conan can help/simplify the process involved with the `pc` files. I'll try to compare both ways to resolve the same problem (yours and mine), please feel free to complete/correct it:

kent-at-multiscale's way
-------------------------------

**Pros**: 
    - Clean way to reuse the packages with `pc` files
**Cons**: 
    - The package creator with the pc file has to "prepare" the pc file, If that package is not prepared, the consumer won't be able to use it.

**How conan could help**: "Helper" to patch the `pc` files in package creation.

lasote's way
----------------

**Pros** 
     - The package creator with the `pc` doesn't need to adapt the `pc` 
     - The consumer has all the needed information to adapt the imported `pc`

**Cons**: 
     - The package creator has to export the `pc` file.
     - The consumer has to import the **pc** files to a local folder. That's not very intuitive.
     - The consumer has to adapt the **pc** files to replace the path.

**How conan could help**: 
    - "Helper" to import and patch the pcs (could detect any pc packaged in the requirements)

Both ways seem to be valid, maybe it's not needed to add anything to Conan until we have more feedback.

**Comment by kent-at-multiscale** [comment] 2017-03-14 16:47
I feel that putting the burden on the package creator and not the package consumer is more consistent. Producers of packages already have to work to integrate the package with Conan, including writing the Python code in the conanfile. Consumers have minimal requirements, they can get by with only a text file and adding one hook to their existing build scripts. Since producers already are required to create a "Conan-compatible" package, also requiring a "Conan-compatible" pkg-config configuration file seems appropriate.

**Comment by lasote** [comment] 2017-03-15 11:21
@kent-at-multiscale I agree with you on that.

**Comment by lasote** [comment] 2017-08-23 15:08
Hi, all. Finally, for 0.26 release we are including something for the pc files.
The most important part is the documentation, where we review different approaches to use the pc files to get the information from our dependencies. @kent-at-multiscale The second documented approach is your way but I wanted to simplify it declaring different variable names for each dependency to avoid messing with the storage path.
The conan code only includes a new tool to patch the pc files and some tests to test the different approaches.

If any of you wants to take a look will help.

Docs:
https://github.com/conan-io/docs/pull/278
Code:
https://github.com/conan-io/conan/pull/1649

We will close this issue when 0.26 is released, any other feedback or suggestion feel free to reopen.

**Closed** 2017-08-31 15:11 UTC
Labels: enhancement, fixed
