### ISSUE TITLE
[bug] Conan migration claims settings.yml was modified when it wasn't

### ISSUE THREAD

**Issue by ArekPiekarz** [conan-io/conan#7193] opened 2020-06-13 18:01 UTC
After upgrading Conan, during migration it always says that settings.yml from older version was modified even when it doesn't differ from settings.yml from newer version.

### Environment Details
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: GCC 10.0.1
  * Conan version: 1.26.0
  * Python version: 3.8.2

### Steps to reproduce
- Install conan with `pip3 install conan==1.25.2`
- Clone example project from https://docs.conan.io/en/latest/getting_started.html#an-md5-hash-calculator-using-the-poco-libraries
- Follow instruction up to `conan install ..` (including it) to generate settings.yml
- Upgrade conan to 1.26.0 with `pip3 install conan --upgrade`
- Run `conan`

### Logs
```
WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: /home/user/.conan/settings.yml.new
WARN: ****************************************
```

**Comment by jgsogo** [comment] 2020-06-18 14:31
Hi! I can see the message the first time I run a command after installing Conan 1.26, but afterward this message doesn't show up.

Are you getting this message with every command or just once?

**Comment by ArekPiekarz** [comment] 2020-06-18 19:54
It happens once after every upgrade of Conan since a few releases, but I don't know exact one which started it. Because of that after each upgrade I have to check differences between settings and manually move files.

**Comment by jgsogo** [comment] 2020-06-22 10:35
I submitted a fix with a test in #7213. It will be released in a 1.26.1 version.

Thanks for reporting this error.

**Closed as completed by jgsogo** 2020-06-22 10:35 UTC
Labels: type: bug, stage: queue, priority: high, complex: low

**Comment by MrPointer** [comment] 2021-05-02 19:23
I think I have reproduced this in newer conan versions as well...  

My scenario is a bit different, where I have one conan version (1.36.0) on WSL, and another (1.35.0) on a docker container, both sharing the cache, mostly to save disk space. I don't want to go into detail about why I work this way, it's irrelevant to the issue.
The problem occurs whenever conan is run from the container, i.e. older version, despite not having any differences at all between the old and new settings files. Any ideas why that might happen?

**Comment by minamaged113** [comment] 2021-09-23 10:21
> I think I have reproduced this in newer conan versions as well...
> 
> My scenario is a bit different, where I have one conan version (1.36.0) on WSL, and another (1.35.0) on a docker container, both sharing the cache, mostly to save disk space. I don't want to go into detail about why I work this way, it's irrelevant to the issue.
> The problem occurs whenever conan is run from the container, i.e. older version, despite not having any differences at all between the old and new settings files. Any ideas why that might happen?

I am having a somewhat similar issue. I have conan installed locally `1.15.2`, and I am also using `1.35.1` from a docker container and allowing it to link with `~/.conan` from the main installation.

Every time I run the newer version from the docker container, I get the previously mentioned warning. Is there a possible way to reproduce it for the same version every time (i.e. on version 1.15.2)? for example by intentionally editing `settings.yml` and running some command to get that warning.

**Comment by sandeshhardikar** [comment] 2022-04-13 11:02
I still can `reproduce`  this when i switch from `conan 1.45.0` to `conan 1.47.0` , I would guess the warning `settings.yml is locally modified` is fine if it throws during the installation of conan. But it rather throws during first run of `conan`, this hurts us, especially in `ci` , when i upgrade to a particular `conan` version and then call `conan inspect --raw version packageA` 

Here is the output

`WARN: Migration: Updating settings.yml
WARN: ****************************************
WARN: settings.yml is locally modified, can't be updated
WARN: The new settings.yml has been stored in: ~/.conan/settings.yml.new
WARN: ****************************************
5.0.0`
I am actually interested only in my package version which is `5.0.0`

**Comment by memsharded** [comment] 2022-04-13 11:15
> I still can reproduce this when i switch from conan 1.45.0 to conan 1.47.0 , I would guess the warning settings.yml is locally modified is fine if it throws during the installation of conan.

The problem is installation is decoupled from application user database and packages. One single installation can have many  conan homes, for example one for every user of the machine (typically in their ``<userhome>/.conan`` folder). Or users can have different homes for different projects, with different remotes configured and different packages (like one for work, another for hobby projects). This happens relatively often.

So migrations cannot be done at Conan installation/upgrade time. They can only be done per conan home, comparing the previous Conan version stored in the ``version.txt`` file in that Conan home, with the current application one.

If you want to force the Cache to initialize/migrate before other commands, maybe you can use some of the ``conan config`` subcommands.
