### ISSUE TITLE
[bug] poco, libmysqlclient undefined reference to zlib functions

### ISSUE THREAD

**Issue by andriy-byte** [conan-io/conan#12940] opened 2023-01-20 21:18 UTC
### Environment details

* Operating System+version: windows  WSL Ubuntu 22 
* Compiler+version: g++ 11
* Conan version:  1.57.0
* Python version: 3.11

### Steps to reproduce

[requires]

angelscript/2.36.0
argparse/2.9
args-parser/6.3.2
boost/1.81.0
cryptopp/8.7.0
eigen/3.4.0
fmt/9.1.0
glm/cci.20220420
gtest/cci.20210126
imgui/cci.20220621+1.88.docking
implot/0.14
lz4/1.9.4
magic_enum/0.8.2
nlohmann_json/3.11.2
numcpp/2.8.0
opengl/system
poco/1.12.4
range-v3/0.12.0
re2/20221201
sdl/2.26.1
sfml/2.5.1
spdlog/1.11.0
sqlite3/3.40.1
sqlitecpp/3.2.1
tabulate/1.4
zlib/1.2.13
openssl/3.0.7
libmysqlclient/8.0.31

[generators]
cmake
cmake_paths
cmake_find_package

### Logs

[ 73%] Linking CXX executable ../runtime_output_directory/thr_lock
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_expand_block':
c_zlib.c:(.text+0x49): undefined reference to `inflate'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_compress_block':
c_zlib.c:(.text+0xb2): undefined reference to `deflate'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_finish':
c_zlib.c:(.text+0xd9): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xe2): undefined reference to `deflateEnd'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_init':
c_zlib.c:(.text+0x1c1): undefined reference to `inflateInit_'
/usr/bin/ld: c_zlib.c:(.text+0x22c): undefined reference to `deflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_ctrl':
c_zlib.c:(.text+0x390): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x496): undefined reference to `zError'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_write':
c_zlib.c:(.text+0x738): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x7d6): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0x851): undefined reference to `deflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_read':
c_zlib.c:(.text+0x98c): undefined reference to `inflate'
/usr/bin/ld: c_zlib.c:(.text+0xa26): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0xa83): undefined reference to `inflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_free':
c_zlib.c:(.text+0xb2b): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xb54): undefined reference to `deflateEnd'
[ 73%] Linking CXX executable ../runtime_output_directory/mf_iocache_test
collect2: error: ld returned 1 exit status
gmake[2]: *** [utilities/CMakeFiles/comp_client_err.dir/build.make:122: runtime_output_directory/comp_client_err] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1520: utilities/CMakeFiles/comp_client_err.dir/all] Error 2
/usr/bin/ld: gmake[1]: *** Waiting for unfinished jobs....
/home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_expand_block':
c_zlib.c:(.text+0x49): undefined reference to `inflate'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_compress_block':
c_zlib.c:(.text+0xb2): undefined reference to `deflate'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_finish':
c_zlib.c:(.text+0xd9): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xe2): undefined reference to `deflateEnd'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_init':
c_zlib.c:(.text+0x1c1): undefined reference to `inflateInit_'
/usr/bin/ld: c_zlib.c:(.text+0x22c): undefined reference to `deflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_ctrl':
c_zlib.c:(.text+0x390): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x496): undefined reference to `zError'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_write':
c_zlib.c:(.text+0x738): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x7d6): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0x851): undefined reference to `deflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_read':
c_zlib.c:(.text+0x98c): undefined reference to `inflate'
/usr/bin/ld: c_zlib.c:(.text+0xa26): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0xa83): undefined reference to `inflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_free':
c_zlib.c:(.text+0xb2b): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xb54): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
gmake[2]: *** [utilities/CMakeFiles/my_print_defaults.dir/build.make:106: runtime_output_directory/my_print_defaults] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1653: utilities/CMakeFiles/my_print_defaults.dir/all] Error 2
[ 73%] Built target thr_lock
[ 73%] Built target mf_iocache_test
[ 73%] Linking CXX executable ../runtime_output_directory/comp_err
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_expand_block':
c_zlib.c:(.text+0x49): undefined reference to `inflate'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_compress_block':
c_zlib.c:(.text+0xb2): undefined reference to `deflate'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_finish':
c_zlib.c:(.text+0xd9): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xe2): undefined reference to `deflateEnd'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `zlib_stateful_init':
c_zlib.c:(.text+0x1c1): undefined reference to `inflateInit_'
/usr/bin/ld: c_zlib.c:(.text+0x22c): undefined reference to `deflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_ctrl':
c_zlib.c:(.text+0x390): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x496): undefined reference to `zError'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_write':
c_zlib.c:(.text+0x738): undefined reference to `deflate'
/usr/bin/ld: c_zlib.c:(.text+0x7d6): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0x851): undefined reference to `deflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_read':
c_zlib.c:(.text+0x98c): undefined reference to `inflate'
/usr/bin/ld: c_zlib.c:(.text+0xa26): undefined reference to `zError'
/usr/bin/ld: c_zlib.c:(.text+0xa83): undefined reference to `inflateInit_'
/usr/bin/ld: /home/andriy/.conan/data/openssl/3.0.7/_/_/package/304480252b01879c8641f79a653b593b8f26cf9f/lib/libcrypto.a(libcrypto-lib-c_zlib.o): in function `bio_zlib_free':
c_zlib.c:(.text+0xb2b): undefined reference to `inflateEnd'
/usr/bin/ld: c_zlib.c:(.text+0xb54): undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
gmake[2]: *** [utilities/CMakeFiles/comp_err.dir/build.make:106: runtime_output_directory/comp_err] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1493: utilities/CMakeFiles/comp_err.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2
libmysqlclient/8.0.31:
libmysqlclient/8.0.31: ERROR: Package 'ee07977676c85caceddd59d7015f4782d0f76242' build failed
libmysqlclient/8.0.31: WARN: Build folder /home/andriy/.conan/data/libmysqlclient/8.0.31/_/_/build/ee07977676c85caceddd59d7015f4782d0f76242
ERROR: libmysqlclient/8.0.31: Error in build() method, line 242
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/andriy/.conan/data/libmysqlclient/8.0.31/_/_/build/ee07977676c85caceddd59d7015f4782d0f76242' '--' '-j12'

**Comment by memsharded** [comment] 2023-01-24 22:02
Hi @andriy-byte 

thanks for your report.

It would be necessary a couple of things to be able to investigate this further:
- Please reduce as much as possible the conanfile to reproduce this issue. Most likely most of the dependencies there can be removed and the issue would still reproduce.
- Please provide always a CMakeLists.txt, a main.cpp and the exact Conan commands that you are using in order to reproduce the issue.

Please also note that the integrations that you are using are considered legacy as they have been removed in 2.0, which is due next month. The new integrations to be used are in: https://docs.conan.io/en/latest/reference/conanfile/tools.html

**Comment by andriy-byte** [comment] 2023-01-27 16:39
@memsharded, i think is not problem with conan, problem is when conan build poco -> libmysqlclient library . I wrote ths report because i have already used poco  library in version 1.12.4 from conan but "undefined reference from zlib functions" happened for the first time

**Comment by memsharded** [comment] 2023-01-28 11:26
Then, if it might be a recipe issue, this could be moved to ``conan-center-index`` repo. But in any case, it is necessary to reduce it as much as possible, probably only ``poco``, and still the consuming code, like a CMakeLists.txt and main.cpp would be necessary to reproduce and investigate.

**Comment by memsharded** [comment] 2024-07-28 23:13
I am closing this ticket as outdated/staled.

Most likely not a Conan issue, but some issue with some recipes from ConanCenter.
It is very likely that if there were issues they have been solved since then, if not, please consider opening a ticket in ``conan-center-index`` repo.

**Closed as not planned by memsharded** 2024-07-28 23:13 UTC
