### ISSUE TITLE
[question] Getting the initial CWD in generate() and build()

### ISSUE THREAD

**Issue by naggerx** [conan-io/conan#16194] opened 2024-05-02 20:52 UTC
### What is your question?

generate() and build() and other methods are changing the current working directory. Is it possible to get the directory from where the conan command was started within these methods? Is there already an attribute?

It seems in configure() and package_id() the CWD is not yet changed. So I could grab it there for later use?!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-05-02 21:38
Hi @naggerx 

Thanks for your question.

> generate() and build() and other methods are changing the current working directory. Is it possible to get the directory from where the conan command was started within these methods? Is there already an attribute?

Not, it is not possible. This wouldn't be a gap, but this is totally intended. All methods in conanfile.py recipes must be location independent, they cannot rely on the cwd at all, that would make things non-reproducible. All paths must be relative to the recipe, and it is possible to access some files with the provided ``self.recipe_folder, ``self.source_folder``, ``self.build_folder``, etc.

> It seems in configure() and package_id() the CWD is not yet changed. So I could grab it there for later use?!

This could be mostly a leak, or unintended, and this might totally change in different situations. So it would be very discouraged (not to say forbidden) to try to access the ``cwd``.

If you describe with more detail why you want to access the ``cwd``, then we might try to give some advice. In general, files in local development flow should be relative to the above folders, and files when referenced in the cache will use the same folders, and if necessary, they should be exported with ``exports`` or ``exports_sources``.

**Comment by peddaahh** [comment] 2024-05-06 07:55
@memsharded Here for example the source is a local folder, because it's already downloaded by my CI/CD workflow. Then I call
`copy(self, '*', src=os.path.normpath(self.workflow_wd), dst=self.source_folder)`
for my source. Currently I am inserting the cwd using my workflow as a variable with sed, but it would be nice if I could access it just via conan like some `self.origin_folder` or something

**Comment by memsharded** [comment] 2024-05-06 08:00
Sorry, I still didn't fully understand it. What is the ``self.workflow_wd``? Please note that it is forbidden to use public attributes, they should always be ``self._xxx``. Where is that ``copy()`` call and what is its purpose? If it is for exporting in one of the ``export`` methods, then the recommended flow is to use the ``self.recipe_folder`` and express the location of sources relative to the ``conanfile.py``.

**Comment by peddaahh** [comment] 2024-05-06 08:07
so my source is downloaded by my workflow.. then some unittests, building etc.. is running then i want to run conan on this directory. Basically, LabVIEW PPLs (binaries like DLLs) are just wrapped into a conan package.
So I just need to copy the local folder from the machine where my workflow runs (which has already downloaded the git repo) into the conan source folder
```py
class LabVIEWBuild(ConanFile):
    name = "version_info"
    version = subprocess.getoutput('git describe --tags --always')
    _pwd = 'C:\\_work\\repos\\lv_version_info'

    # Metadata
    license = "Personal"  # Default, will be read out from lvproj below
    author = "Author"
    description = "<Description of package here>"

    # Binary config
    options = {
        "lv": ['2020'],
        "arch": ['win32', 'win64']
    }

    def generate(self):
        VirtualBuildEnv(self, auto_generate=False)
        VirtualRunEnv(self, auto_generate=False)

    def layout(self):
        _build_type = self.options.lv
        _arch = self.options.arch
        self.folders.package = os.path.join(str(_build_type), str(_arch))

    def compatibility(self):
        self.options.lv  # TODO: Check if desired is >= current

    def source(self):
        copy(self, '*', src=os.path.normpath(self._pwd), dst=self.source_folder)

    def build(self):
        lvproj = glob.glob(os.path.join(self.source_folder, "*.lvproj"))
        xml_doc = xml.dom.minidom.parse(lvproj[0])
        lic = xml_doc.getElementsByTagName('Property')
        for element in lic:
            if element.getAttribute('Name') == "TgtF_legalCopyright":
                lic = element.childNodes[0].data
        self.license = lic if lic is not None else self.license
        # self.run('sh ' + os.path.join(self.source_folder, 'lv_builder', 'run-build.sh'))
        # self.run('mv ./build/*', '${./build/*%%:*}')
        pass

    def package(self):
        copy(self, "*.lvlibp", src=os.path.join(self.source_folder, 'build'), dst=self.package_folder)
        absolute_to_relative_symlinks(self, self.package_folder)

    def deploy(self):
        copy(self, "*.lvlibp", src=self.package_folder, dst='lib')
```

**Comment by memsharded** [comment] 2024-05-06 09:09
I understand the recipe above might be a simplification for sharing, but just in case, some quick feedback:

- ``version = subprocess.getoutput('git describe --tags --always')``. Please don't do that in attribute, use the ``set_version()`` method instead.
- ``"lv": ['2020'],`` options with just 1 value are not really options, you can remove it (I guess that you will have more values there eventually)


Then, regarding your use case: this is not the recommended flow, because it will make your recipes and binaries non-reproducible. The recommended workflow is:
- Copy the sources you need into the recipe with ``exports_sources`` (attribute or method) instead, not with the ``source()`` method.
- Conan will automatically manage to copy it from the ``exports_sources`` to the ``source`` folder
- The ``export`` process will have access both to the ``self.recipe_folder`` and to the CWD


This process will guarantee that you have different recipe-revisions for different source code, which is critical for the overall behavior.

Please let me know if this clarifies the issue.

**Comment by peddaahh** [comment] 2024-05-06 10:46
Thanks for your help, it's very appreciated!
Yes this clarifies my issue, and it works as expected.

**Comment by memsharded** [comment] 2024-05-06 11:02
Ok, excellent, happy to hear that and happy to help! :)

I am closing the ticket as resolved then, don't hesitate to open new tickets for any further question. Thanks!

**Closed as completed by memsharded** 2024-05-06 11:02 UTC
Labels: type: question

**Comment by naggerx** [comment] 2024-05-07 14:00
Our own very simple use case:
- During conan-install of our tool we generate some convenience start scripts.
- We just want to print a nice log message for the user with a *relative path* to the generated script in  conanfile.generate().  So we need to calculate the relative path from user's CWD to self.generator_folder

**Comment by memsharded** [comment] 2024-05-07 15:00
@naggerx 

I am afraid this is not possible. In the ``generate()`` method there is no access to the caller ``cwd``, and it is not planned to be added. The reason is that some users will use (abuse) that, resulting in non-reproducible and broken builds, that will in turn result in new tickets, more time dedicated to support and debug the user issues, more documentation efforts to try to clarify that it shouldn't be done (that users will not read and will keep falling in that again).

> We just want to print a nice log message for the user with a relative path to the generated script in conanfile.generate(). So we need to calculate the relative path from user's CWD to self.generator_folder

This shouldn't be a major blocker, conan already allows to print absolute folders to generated files, this is already part of the Conan output:
```
conanfile.py (mypkg/0.1): Calling generate()
conanfile.py (mypkg/0.1): Generators folder: C:\Users\memsharded\conanws\kk\build\generators
conanfile.py (mypkg/0.1): CWD in generate(): C:\Users\memsharded\conanws\kk\build\generators
conanfile.py (mypkg/0.1): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (mypkg/0.1): CMakeToolchain: Preset 'conan-default' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-default
    (cmake<3.23) cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=generators\conan_toolchain.cmake  -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
conanfile.py (mypkg/0.1): CMakeToolchain generated: C:\Users\memsharded\conanws\kk\build\generators\CMakePresets.json
conanfile.py (mypkg/0.1): CMakeToolchain generated: C:\Users\memsharded\conanws\kk\CMakeUserPresets.json
```

So the absolute paths are there, and if users need to use it, copy&paste it also works good, launching the scripts with absolute paths shouldn't be an issue either. I know it doesn't look as clean as nice relative paths, but the risk of allowing the ``cwd`` seems too high at the moment for the value.
