### ISSUE TITLE
[question][suggestion] How to exchange data between all builded packages process (Related to Very slow version range resolving)

### ISSUE THREAD

**Issue by MICGRAND** [conan-io/conan#11050] opened 2022-04-19 19:57 UTC
Hello Everybody,

As many conan users, we are facing on big latency to resolve version range with conan and Artifactory (5 to 10mn and more when we have 5 or 6 levels of nested packages (~100).
Many topics exist for this issue but all workaround don't fit our way to work. (eg: https://github.com/conan-io/conan/issues/1373)

From my side, I have implemented a workaround which consists to implement a python_requires package to override requirements function. 
The first time, I save all conan search result in a file, next I load always this file and I'am solving myself the dynamic range by reading  self.requires.items. I divide by 50 the needed time, it is very incredible.
This solution could be generalised in conan to save time.

My concern is that it is a very quick and dirty workaround. So to implement a better solution, I would have 3 questions:

1) I didn't see on web any improvement on this topic . Do you have more recent solution to speed up version range resolving?

2) In place of using intermediate file for conan search result, would you have a solution to exchange "self" data between all packages used during conan create or conan install (Requirements function call)?

3) If I succeeded to overwrite requirements function for all requirement() packages, how to overload python_requires version?
My first idea was to use a python_require with a fixed version which implement my workaround to load a second python_require with its last version
Unfortunately, nested python_require doesn't work. If we want to load nested python require, first package need to declare all needed python_requires for whole system.
Any idea?

Thanks for your feedback.
Mickaël

   
- [X ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-04-19 20:21
Hi @MICGRAND 

> The first time, I save all conan search result in a file, next I load always this file and I'am solving myself the dynamic range by reading self.requires.items. I divide by 50 the needed time, it is very incredible.
This solution could be generalised in conan to save time.

I am very interested about this. Conan does already cache the server packages, to not query the server more than once. But it does it for one Conan execution, do you mean that you keep reading that file subsequent invocations? 
We did think about this approach some time ago, but it has the obvious challenges of cache, cache invalidation (one of the hardest problems in computer science :) ), so we are reluctant to follow this path.

There are good news regarding the server side issue in Artifactory, we have been helping and giving feedback to the team, and they are working for a resolution that will come hopefully soon to Artifactory next releases. That will probably definitively solve this issue. (btw, the current open ticket for this is https://github.com/conan-io/conan/issues/10298)

**Comment by MICGRAND** [comment] 2022-04-19 20:52
Hi @memsharded , 
I'm not sure that we talk about the same things. So, don't hesitate to correct me if I'm wrong.

I do only one invocation of conan (Example: conan create) but when I do this call, it  take many time to solve version range at any nested level and for whole version range packages. 
What I understood is that cache is used to store needed package but it doesn't store the latest existing version at time=0. Conan seems to do a new conan search for all required package to get the new latest version of require packages to server even if this package have already been used (So, range solved) by another required package. All these redundant requests take time when we have a lot of nested packages.

Therefore, I call conan search to retrieve all existing package version at time = 0
Next, I call conan create to solve the range myself based on this server image at time = 0

It doesn't matter of cache invalidation because we want to build an image of server at time = 0.
If new package is uploaded during the build, we'll not use it, it'll be updloaded and used in the next conan create call.

 My concern now is with  python_requires because I can't solve range version in a common package.

(FYI, I'm using conan V1.41)

**Comment by memsharded** [comment] 2022-04-19 21:44
> Conan seems to do a new conan search for all required package to get the new latest version of require packages to server even if this package have already been used (So, range solved) by another required package. All these redundant requests take time when we have a lot of nested packages.

In theory it shouldn't. Conan stores in memory this information, so not needing to query the server again for same package version range. But I will definitely re-check, if you are seeing that behavior there might be some bug in the caching system.

**Comment by memsharded** [comment] 2022-04-19 23:07
I am testing this, it seems to be working and caching things fine.
Check this test for example:

```python
class TestVersionRangeCaching:

    def test_caching(self):
        t = TestClient(default_server_user=True)

        # Use version ranges without user/channel
        t.save({"dep/conanfile.py": GenConanfile(),
                "pka/conanfile.py": GenConanfile("pkga", "1.0").with_requires("dep/[*]"),
                "pkb/conanfile.py": GenConanfile("pkgb", "1.0").with_requires("pkga/1.0", "dep/[*]"),
                "app/conanfile.py": GenConanfile("app", "1.0").with_requires("pkgb/1.0", "dep/[*]")})
        t.run("export dep dep/1.0@")
        t.run("export dep dep/1.1@")
        t.run("export dep dep/1.2@")
        t.run("export pka")
        t.run("export pkb")
        t.run("upload * -c")
        t.run("remove * -f")

        t.run("info app")
        assert "dep/1.2" in t.out
        assert str(t.out).count("dep/* versions found in 'default' remote") == 1
```
For every package name it will only query servers once.

So it doesn't seem to be that the reason of being slow, but something else. Is the server a local Artifactory repo? Are you doing a virtual with a remote proxying ConanCenter (because ConanCenter can be slow at resolving too)? Maybe if you can shared the full output of a normal graph (the slow one) resolution, that could throw some light, messages like the one in the test ``dep/* versions found in 'default' remote`` should be there indicating something

**Comment by MICGRAND** [comment] 2022-04-21 14:56
Hi @memsharded,

It's a coincidence but IT team has just installed a new version of Artifactory (6.23.41) on a new server and timing are very very better. (30 seconds in place of 5 minutes to solve all range of a complete application)

Anyway, I have activated conan logs and we can see that conan does 455 REST_API_CALL to do the complete application

To check the gain with fixed address, I took a smaller components:
153 REST_API_CALL with fixed address
306 REST_API_CALL with range address
if we consider 0.06s per call, delta is 9 seconds

Therefore, retrieving whole existing packages in server only one time and using this list locally would save 75% of time.

If you need specific logs, I let you indictae me the procedure, I'm not familiar with all conan options

**Comment by memsharded** [comment] 2022-04-21 15:16
> It's a coincidence but IT team has just installed a new version of Artifactory (6.23.41) on a new server and timing are very very better. (30 seconds in place of 5 minutes to solve all range of a complete application)

Yes, that seems a coincidence, it is possible that upgrading the version did also some optimizations in the DB, that could improve performance. But the big improvements are not released yet, and they will land in future latest 7.X version.

> Therefore, retrieving whole existing packages in server only one time and using this list locally would save 75% of time.

Based on that and from your previous comments, I think that you are indeed caching over different Conan invocations. Which is the thing that we are trying to avoid, because doing it robustly and without unexpected behaviors for the majority of users is extremely challenging. I think that when the Artifactory 7.X version that improves the performance issue over the version range resolution, this will no longer be an issue in any case.

**Comment by MICGRAND** [comment] 2022-04-21 15:30
> ... Which is the thing that we are trying to avoid, because doing it robustly and without unexpected behaviors for the majority of users is extremely challenging

I don't understand the risk. Having a complete picture of existing package at start is similar to a lock. 
Can you detail a little bit the unexpected behavior?

**Comment by memsharded** [comment] 2022-04-21 15:46
Once you cache something, in this case, the existing versions of packages in the different remotes, many things can go wrong:

- If a new package is uploaded to the server, and the cache is not invalidated and updates the new versions from the servers, then users will complain that they are not getting the expected new version, and then, it is broken.
- A certain server can remove some versions. If the cached information resolves to those, then it will be broken, and users will complain about it.
- If, in order to avoid the above, Conan needs to check the server every time, and update all the existing versions in the server, then the result is the same as not caching anything.
- Not only behavioral issues, but also implementation, such a new layer of information will add more bugs, migration issues, etc. The cache is not that trivial to implement and maintain, in the general case there can be several remotes, and the existing versions should be stored for each remotes. Remotes can be removed, and that would require syncing also the cache. The cache can go corrupt if some operation crashes or Conan is killed, producing more confusing errors.

**Comment by MICGRAND** [comment] 2022-04-22 09:31
I understand.
I would say that it is only a question of time window. Issues listed here can occur during 2 API REST call. We just decrease the occurence.
What is the probability to have these issue during 15s compared to a gain of 10s multiplied by 1000 compilations?
If we detect an issue, we have just to restart a build.  
ANyway, thanks for all your answers.

**Comment by memsharded** [comment] 2022-04-22 12:43
> I would say that it is only a question of time window. Issues listed here can occur during 2 API REST call. We just decrease the occurence.

It is conceptually very different. When executing in the same ``conan install`` call, having 2 packages with the same version range resolve to different versions, because in between the API calls one package was uploaded, is a really unwanted and unexpected thing. Users will report it as a bug. So the in-memory cache of server versions is not only for performance, it is also necessary for consistency, and achieving good results.

The opposite happens when there are subsequent invocations of ``conan install``, in different times. Users in this case will really expect that each one will be resolving to the latest available version in the range, and seeing a new version published in the server, and getting resolved an old one, because Conan is somewhat caching that in the client side, and it didn't correctly invalidate the cache, would also be a bug. In the previous case, cache invalidation is trivial, because the whole cache is being removed at every Conan invocation. 

> What is the probability to have these issue during 15s compared to a gain of 10s multiplied by 1000 compilations?
If we detect an issue, we have just to restart a build.

To be accurate, the Conan cache is already serving this purpose. If you install things in the Conan package cache, the resolution of version ranges against installing packages will be very fast, because it might not even touch the servers, if they find the packages already in the cache. You can do thousands of compilations resolving the graph to packages installed in the cache without even internet connection. So the slow resolution only happens when it is really hitting the server (the packages are not in the cache, or we are defining a explicit ``--update``). And in that case, it is really expected to get the correct thing from the server, and not something that you cached from the server some time ago.

**Comment by memsharded** [comment] 2022-07-11 11:30
This has been finally fixed. ``conan search zlib* -r=conancenter`` now works fast against ConanCenter, and so version ranges will be resolved much faster too.

Artifactory 7.41 contains the fixes, so if you are experiencing this in your own instance, please upgrade.

**Closed as completed by memsharded** 2022-07-11 11:30 UTC
Labels: component: artifactory
