### ISSUE TITLE
[bug] Compatible package failure if a package and its requirement both build_require the compatible package

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan#9398] opened 2021-08-07 03:49 UTC
Given two packages, `pkg-a` and `pkg-b` (which requires `pkg-a`), and each build_requires `doxygen/1.9.1`.

If building with `build_type=Debug`, Conan plans to use the compatible Release package for `doxygen/1.9.1`, but lists both packages in the build plan, and then complains of a missing folder.

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15.7
  * Compiler+version: apple-clang 12.0
  * Conan version: 1.39.0
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)

1. Ensure there are no local versions of `doxygen/1.9.1`
2. Clone [`https://github.com/datalogics-kam/conan-compatible-package-bug`](https://github.com/datalogics-kam/conan-compatible-package-bug).
3. `cd` to the resulting directory, and `sh -x build.sh`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
+ conan install -if doxygen doxygen/1.9.1@ --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

Installing package: doxygen/1.9.1
Requirements
    doxygen/1.9.1 from 'conan-center-virtual' - Cache
    libuuid/1.0.3 from 'conan-center-virtual' - Cache
    xapian-core/1.4.18 from 'conan-center-virtual' - Cache
    zlib/1.2.11 from 'conan-center-virtual' - Cache
Packages
    doxygen/1.9.1:8785b92de1bc6414009359573b36a2a3e1498bf2 - Cache
    libuuid/1.0.3:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache
    xapian-core/1.4.18:b8c8ad8046449d42b29a7e22012187a58389cfe3 - Cache
    zlib/1.2.11:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache

Installing (downloading, building) binaries...
libuuid/1.0.3: Already installed!
zlib/1.2.11: Already installed!
xapian-core/1.4.18: Already installed!
xapian-core/1.4.18: Appending PATH environment variable: /Users/kam/.conan/data/xapian-core/1.4.18/_/_/package/b8c8ad8046449d42b29a7e22012187a58389cfe3/bin
xapian-core/1.4.18: Appending AUTOMAKE_CONAN_INCLUDES environment variable: /Users/kam/.conan/data/xapian-core/1.4.18/_/_/package/b8c8ad8046449d42b29a7e22012187a58389cfe3/bin/share/aclocal
doxygen/1.9.1: Already installed!
doxygen/1.9.1: Appending PATH environment variable: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/8785b92de1bc6414009359573b36a2a3e1498bf2/bin
Aggregating env generators
+ conan export pkg-a
Exporting package recipe
pkg-a/0.1: The stored package has not changed
pkg-a/0.1: Using the exported files summary hash as the recipe revision: c2041fd6b2c68b3ed1b914478ef971c5
pkg-a/0.1: Exported revision: c2041fd6b2c68b3ed1b914478ef971c5
+ conan install pkg-b -if build -s build_type=Debug --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

doxygen/1.9.1: Main binary package 'afc515d88cac1e121770943bc9a5045df3a125f4' missing. Using compatible package '8785b92de1bc6414009359573b36a2a3e1498bf2'
conanfile.py (pkg-b/0.1): Installing package
Requirements
    pkg-a/0.1 from local cache - Cache
Packages
    pkg-a/0.1:ba203d82ae0020eccba7236c3748eb8f79fceaf6 - Build
Build requirements
    doxygen/1.9.1 from 'conan-center-virtual' - Cache
    doxygen/1.9.1 from 'conan-center-virtual' - Cache
    libuuid/1.0.3 from 'conan-center-virtual' - Cache
    xapian-core/1.4.18 from 'conan-center-virtual' - Cache
    zlib/1.2.11 from 'conan-center-virtual' - Cache
Build requirements packages
    doxygen/1.9.1:8785b92de1bc6414009359573b36a2a3e1498bf2 - Cache
    doxygen/1.9.1:afc515d88cac1e121770943bc9a5045df3a125f4 - Cache
    libuuid/1.0.3:d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2 - Cache
    xapian-core/1.4.18:9282a40774a88010b7c4ad6c26e9598ec76fb393 - Cache
    zlib/1.2.11:d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2 - Cache

Installing (downloading, building) binaries...
libuuid/1.0.3: Already installed!
  1 Head: main
zlib/1.2.11: Already installed!
xapian-core/1.4.18: Already installed!
xapian-core/1.4.18: Appending PATH environment variable: /Users/kam/.conan/data/xapian-core/1.4.18/_/_/package/9282a40774a88010b7c4ad6c26e9598ec76fb393/bin
xapian-core/1.4.18: Appending AUTOMAKE_CONAN_INCLUDES environment variable: /Users/kam/.conan/data/xapian-core/1.4.18/_/_/package/9282a40774a88010b7c4ad6c26e9598ec76fb393/bin/share/aclocal
xapian-core/1.4.18: Appending PATH environment variable: /Users/kam/.conan/data/xapian-core/1.4.18/_/_/package/9282a40774a88010b7c4ad6c26e9598ec76fb393/bin
xapian-core/1.4.18: Appending AUTOMAKE_CONAN_INCLUDES environment variable: /Users/kam/.conan/data/xapian-core/1.4.18/_/_/package/9282a40774a88010b7c4ad6c26e9598ec76fb393/bin/share/aclocal
doxygen/1.9.1: Already installed!
doxygen/1.9.1: Appending PATH environment variable: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/8785b92de1bc6414009359573b36a2a3e1498bf2/bin
doxygen/1.9.1: Already installed!
Traceback (most recent call last):
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/command.py", line 2220, in run
    method(args[0][1:])
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/command.py", line 523, in install
    info = self._conan.install(path=args.path_or_reference,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/conan_api.py", line 606, in install
    deps_install(app=self.app,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/manager.py", line 82, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/installer.py", line 316, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/installer.py", line 451, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/installer.py", line 560, in _handle_node_cache
    assert os.path.isdir(package_folder), ("Package '%s' folder must exist: %s\n"
AssertionError: Package 'doxygen/1.9.1:afc515d88cac1e121770943bc9a5045df3a125f4' folder must exist: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/afc515d88cac1e121770943bc9a5045df3a125f4


ERROR: Package 'doxygen/1.9.1:afc515d88cac1e121770943bc9a5045df3a125f4' folder must exist: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/afc515d88cac1e121770943bc9a5045df3a125f4
```

**Comment by franramirez688** [comment] 2021-08-09 08:01
Hi @datalogics-kam 
I've been trying to reproduce the error locally but it was impossible for me, sorry. Let me show you the output:

```
+ conan install -if doxygen doxygen/1.9.1@ --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

Installing package: doxygen/1.9.1
Requirements
    doxygen/1.9.1 from 'conancenter' - Cache
    libuuid/1.0.3 from 'conancenter' - Cache
    xapian-core/1.4.18 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Packages
    doxygen/1.9.1:8785b92de1bc6414009359573b36a2a3e1498bf2 - Cache
    libuuid/1.0.3:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache
    xapian-core/1.4.18:b8c8ad8046449d42b29a7e22012187a58389cfe3 - Cache
    zlib/1.2.11:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Cache

Installing (downloading, building) binaries...
libuuid/1.0.3: Already installed!
zlib/1.2.11: Already installed!
xapian-core/1.4.18: Already installed!
xapian-core/1.4.18: Appending PATH environment variable: /Users/franchuti/.conan/data/xapian-core/1.4.18/_/_/package/b8c8ad8046449d42b29a7e22012187a58389cfe3/bin
xapian-core/1.4.18: Appending AUTOMAKE_CONAN_INCLUDES environment variable: /Users/franchuti/.conan/data/xapian-core/1.4.18/_/_/package/b8c8ad8046449d42b29a7e22012187a58389cfe3/bin/share/aclocal
doxygen/1.9.1: Already installed!
doxygen/1.9.1: Appending PATH environment variable: /Users/franchuti/.conan/data/doxygen/1.9.1/_/_/package/8785b92de1bc6414009359573b36a2a3e1498bf2/bin
Aggregating env generators
+ conan export pkg-a
Exporting package recipe
pkg-a/0.1: The stored package has not changed
pkg-a/0.1: Exported revision: c2041fd6b2c68b3ed1b914478ef971c5
+ conan install pkg-b -if build -s build_type=Debug --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.py (pkg-b/0.1): Installing package
Requirements
    pkg-a/0.1 from local cache - Cache
Packages
    pkg-a/0.1:ba203d82ae0020eccba7236c3748eb8f79fceaf6 - Cache
Build requirements
    doxygen/1.9.1 from 'conancenter' - Cache
    libuuid/1.0.3 from 'conancenter' - Cache
    xapian-core/1.4.18 from 'conancenter' - Cache
    zlib/1.2.11 from 'conancenter' - Cache
Build requirements packages
    doxygen/1.9.1:afc515d88cac1e121770943bc9a5045df3a125f4 - Cache
    libuuid/1.0.3:d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2 - Cache
    xapian-core/1.4.18:9282a40774a88010b7c4ad6c26e9598ec76fb393 - Cache
    zlib/1.2.11:d98fae1010d1fb9e7f79a1e8a72bbf129d8660a2 - Cache

Installing (downloading, building) binaries...
libuuid/1.0.3: Already installed!
pkg-a/0.1: Already installed!
zlib/1.2.11: Already installed!
xapian-core/1.4.18: Already installed!
xapian-core/1.4.18: Appending PATH environment variable: /Users/franchuti/.conan/data/xapian-core/1.4.18/_/_/package/9282a40774a88010b7c4ad6c26e9598ec76fb393/bin
xapian-core/1.4.18: Appending AUTOMAKE_CONAN_INCLUDES environment variable: /Users/franchuti/.conan/data/xapian-core/1.4.18/_/_/package/9282a40774a88010b7c4ad6c26e9598ec76fb393/bin/share/aclocal
doxygen/1.9.1: Already installed!
doxygen/1.9.1: Appending PATH environment variable: /Users/franchuti/.conan/data/doxygen/1.9.1/_/_/package/afc515d88cac1e121770943bc9a5045df3a125f4/bin
conanfile.py (pkg-b/0.1): Applying build-requirement: doxygen/1.9.1
conanfile.py (pkg-b/0.1): Applying build-requirement: xapian-core/1.4.18
conanfile.py (pkg-b/0.1): Applying build-requirement: libuuid/1.0.3
conanfile.py (pkg-b/0.1): Applying build-requirement: zlib/1.2.11
conanfile.py (pkg-b/0.1): Generator txt created conanbuildinfo.txt
conanfile.py (pkg-b/0.1): Generator cmake created conanbuildinfo.cmake
conanfile.py (pkg-b/0.1): Aggregating env generators
conanfile.py (pkg-b/0.1): Generated conaninfo.txt
conanfile.py (pkg-b/0.1): Generated graphinfo
```

Have you tried to delete the complete doxygen-cached folder? I'm not sure what's going on, so, let's delete the cached one and the current `conan-compatible-package-bug/build/` folder created by conan in your local repo to have a "new" fresh build:

```
$ rm -rf /Users/kam/.conan/data/doxygen
$ rm -rf ./build
$ sh -x build.sh
```

**Comment by datalogics-kam** [comment] 2021-08-09 15:19
The state that triggers the bug is when there's a Release Doxygen binary but there isn't a Debug Doxygen binary. I had that state due to some local conditions, and I think I can improve the test case.

I updated the Github repo to set `doxygen:enable_search=False` so that there are no prebuilt binaries coming from CCI; also ensured that my remote list was talking to Conan Center directly, without our Artifactory in the middle.

Please make sure there are no Doxygen packages in your local cache, and try that repo. This is what I get:

```
+ conan install -if doxygen doxygen/1.9.1@ --build missing -o doxygen:enable_search=False
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
doxygen:enable_search=False
[build_requires]
[env]

doxygen/1.9.1: Not found in local cache, looking in remotes...
doxygen/1.9.1: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
doxygen/1.9.1: Downloaded recipe revision 53cc478fca12af67b4e4af0a0f360b62
doxygen/1.9.1: Compatible package ID f2de6c514c24edd6a3a3b07572e6ac4cddf245f6 equal to the default package ID
Installing package: doxygen/1.9.1
Requirements
    doxygen/1.9.1 from 'conan-center' - Downloaded
Packages
    doxygen/1.9.1:f2de6c514c24edd6a3a3b07572e6ac4cddf245f6 - Build
Build requirements
    bison/3.7.1 from 'conan-center-virtual' - Cache
    flex/2.6.4 from 'conan-center-virtual' - Cache
    m4/1.4.18 from 'conan-center-virtual' - Cache
Build requirements packages
    bison/3.7.1:ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf - Cache
    flex/2.6.4:ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf - Cache
    m4/1.4.18:801752c0480319b8e090188c566245a78e9abcf4 - Cache

Installing (downloading, building) binaries...
m4/1.4.18: Already installed!
m4/1.4.18: Appending PATH environment variable: /Users/kam/.conan/data/m4/1.4.18/_/_/package/801752c0480319b8e090188c566245a78e9abcf4/bin
m4/1.4.18: Setting M4 environment variable: /Users/kam/.conan/data/m4/1.4.18/_/_/package/801752c0480319b8e090188c566245a78e9abcf4/bin/m4
bison/3.7.1: Already installed!
bison/3.7.1: Setting BISON_ROOT environment variable: /Users/kam/.conan/data/bison/3.7.1/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf
bison/3.7.1: Appending PATH environment variable: /Users/kam/.conan/data/bison/3.7.1/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/bin
bison/3.7.1: Setting the BISON_PKGDATADIR environment variable: /Users/kam/.conan/data/bison/3.7.1/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/bin/share/bison
flex/2.6.4: Already installed!
flex/2.6.4: Appending PATH environment variable: /Users/kam/.conan/data/flex/2.6.4/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/bin
flex/2.6.4: Setting LEX environment variable: /Users/kam/.conan/data/flex/2.6.4/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/bin/flex
doxygen/1.9.1: Applying build-requirement: flex/2.6.4
doxygen/1.9.1: Applying build-requirement: bison/3.7.1
doxygen/1.9.1: Applying build-requirement: m4/1.4.18
Downloading conan_sources.tgz
doxygen/1.9.1: Configuring sources in /Users/kam/.conan/data/doxygen/1.9.1/_/_/source

doxygen/1.9.1: Copying sources to build folder
doxygen/1.9.1: Building your package in /Users/kam/.conan/data/doxygen/1.9.1/_/_/build/f2de6c514c24edd6a3a3b07572e6ac4cddf245f6
doxygen/1.9.1: Generator cmake created conanbuildinfo.cmake
doxygen/1.9.1: Generator cmake_find_package created Findflex.cmake
doxygen/1.9.1: Generator cmake_find_package created Findbison.cmake
doxygen/1.9.1: Generator cmake_find_package created Findm4.cmake
doxygen/1.9.1: Aggregating env generators
doxygen/1.9.1: Calling build()
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library fl found /Users/kam/.conan/data/flex/2.6.4/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/lib/libfl.a
-- Library y found /Users/kam/.conan/data/bison/3.7.1/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/lib/liby.a
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan: C++ stdlib: libc++
-- Found PythonInterp: /usr/bin/python (found version "2.7.16") 
-- Found FLEX: /Users/kam/.conan/data/flex/2.6.4/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/bin/flex (found version "2.6.4") 
-- Found BISON: /Users/kam/.conan/data/bison/3.7.1/_/_/package/ef2ed909580d08f58dee7d2eaa04c4b8c95b08cf/bin/bison (found version "3.7.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- Found Iconv: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/lib/libiconv.tbd  
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Success
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Failed
-- The javacc executable not found, using existing files
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    use_libc++


-- Build files have been written to: /Users/kam/.conan/data/doxygen/1.9.1/_/_/build/f2de6c514c24edd6a3a3b07572e6ac4cddf245f6/build_subfolder
[  1%] [BISON][mscgen_language] Building parser with bison 3.7.1
...lots of building stuff...
[100%] Built target doxygen
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/f2de6c514c24edd6a3a3b07572e6ac4cddf245f6/bin/doxygen
-- Installing: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/f2de6c514c24edd6a3a3b07572e6ac4cddf245f6/bin/doxyparse
doxygen/1.9.1 package(): Packaged 3 files: doxyparse, doxygen, LICENSE
doxygen/1.9.1: Package 'f2de6c514c24edd6a3a3b07572e6ac4cddf245f6' created
doxygen/1.9.1: Created package revision 61a673751f004ae0429107cc75d3eb75
doxygen/1.9.1: Appending PATH environment variable: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/f2de6c514c24edd6a3a3b07572e6ac4cddf245f6/bin
Aggregating env generators
+ conan export pkg-a
Exporting package recipe
pkg-a/0.1: A new conanfile.py version was exported
pkg-a/0.1: Folder: /Users/kam/.conan/data/pkg-a/0.1/_/_/export
pkg-a/0.1: Using the exported files summary hash as the recipe revision: a41b38bf82f9b6930dfff46d26f34848 
pkg-a/0.1: Exported revision: a41b38bf82f9b6930dfff46d26f34848
+ conan install pkg-b -if build -s build_type=Debug --build missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

pkg-a/0.1: WARN: The package pkg-a/0.1:ba203d82ae0020eccba7236c3748eb8f79fceaf6 doesn't belong to the installed recipe revision, removing folder
doxygen/1.9.1: Main binary package 'c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4' missing. Using compatible package 'f2de6c514c24edd6a3a3b07572e6ac4cddf245f6'
conanfile.py (pkg-b/0.1): Installing package
Requirements
    pkg-a/0.1 from local cache - Cache
Packages
    pkg-a/0.1:ba203d82ae0020eccba7236c3748eb8f79fceaf6 - Build
Build requirements
    doxygen/1.9.1 from 'conan-center' - Cache
    doxygen/1.9.1 from 'conan-center' - Cache
Build requirements packages
    doxygen/1.9.1:f2de6c514c24edd6a3a3b07572e6ac4cddf245f6 - Cache
    doxygen/1.9.1:c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4 - Cache

Installing (downloading, building) binaries...
doxygen/1.9.1: Already installed!
doxygen/1.9.1: Appending PATH environment variable: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/f2de6c514c24edd6a3a3b07572e6ac4cddf245f6/bin
doxygen/1.9.1: Already installed!
ERROR: Package 'doxygen/1.9.1:c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4' folder must exist: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4

Traceback (most recent call last):
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/command.py", line 2220, in run
    method(args[0][1:])
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/command.py", line 523, in install
    info = self._conan.install(path=args.path_or_reference,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/conan_api.py", line 606, in install
    deps_install(app=self.app,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/manager.py", line 82, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/installer.py", line 316, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/installer.py", line 451, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "/Users/kam/.local/pipx/venvs/conan/lib/python3.9/site-packages/conans/client/installer.py", line 560, in _handle_node_cache
    assert os.path.isdir(package_folder), ("Package '%s' folder must exist: %s\n"
AssertionError: Package 'doxygen/1.9.1:c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4' folder must exist: /Users/kam/.conan/data/doxygen/1.9.1/_/_/package/c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4
```

**Comment by datalogics-kam** [comment] 2021-08-09 15:22
In order for the bug to happen, you have to have a condition that causes this:
```
doxygen/1.9.1: Main binary package 'c69a3ecb88b6686c0f924bc689c9933e7bcbd8d4' missing. Using compatible package 'f2de6c514c24edd6a3a3b07572e6ac4cddf245f6'
```
during the `conan install` for `pkg-b`. Thats when there is not a Debug doxygen package, but there is a Relase one.


Thanks for looking at this!

**Comment by franramirez688** [comment] 2021-08-11 11:33
Finally, I was able to reproduce the error locally but I need another opinion to say if it's actually a bug or it could be a problem from `doxygen` recipe itself.

Basically, the problem is coming from the following `package_id()` implementation (https://conan.io/center/doxygen?tab=recipe):

```python
    def package_id(self):
        del self.info.settings.compiler
        # Doxygen doesn't make code. Any package that will run is ok to use.
        # It's ok in general to use a release version of the tool that matches the
        # build os and architecture.
        compatible_pkg = self.info.clone()
        compatible_pkg.settings.build_type = "Release"
        self.compatible_packages.append(compatible_pkg)
```
As you can see, the problem is coming from that line `compatible_pkg.settings.build_type = "Release"`. So, if I delete that line from my test (https://github.com/conan-io/conan/pull/9411), this one is passing OK.

So, please @memsharded, let us know your opinion about this issue 😁

**Comment by memsharded** [comment] 2022-09-20 22:28
Doing some maintenance, for some reason this issue fell through the cracks.
I have been reviewing https://github.com/conan-io/conan/pull/9411, and the test there supposed to reproduce is passing cleanly. Probably it is not an issue anymore, and was eventually fixed?

**Comment by datalogics-kam** [comment] 2022-09-20 23:13
I tried my test case repo (from the description) with the `develop` branch of Conan, and it's not reproducing the problem. Maybe it got fixed along the way?

**Comment by memsharded** [comment] 2022-09-20 23:57
> I tried my test case repo (from the description) with the develop branch of Conan, and it's not reproducing the problem. Maybe it got fixed along the way?

yes, I suspect that, because I recall some improvements around the ``compatible`` package feature. It might be worth if you could test it with your Conan release, not ``develop``. If it works, I think we can consider this fixed and close it when the test is merged, thanks!

**Comment by datalogics-kam** [comment] 2022-09-21 00:36
> It might be worth if you could test it with your Conan release, not `develop`. 

Tested it with Conan 1.52.0, and with `https://center.conan.io` rather than our Artifactory, and it still works.

**Comment by memsharded** [comment] 2022-09-21 07:26
Ok, then https://github.com/conan-io/conan/pull/9411 merged, and closing this, thanks again for reporting and for your patience :)

**Closed as completed by memsharded** 2022-09-21 07:26 UTC
Labels: type: look into, stage: triaging
