### ISSUE TITLE
[question] "Replacement" for `cmake_paths`

### ISSUE THREAD

**Issue by Jean1995** [conan-io/conan#13711] opened 2023-04-17 14:45 UTC
### What is your question?

Hi! For our software [PROPOSAL](https://github.com/tudo-astroparticlephysics/PROPOSAL), we use `conan` to fetch all dependencies. We've been using the `cmake_paths` generator so far. 

In the CMakeLists.txt of our package, we included the line

```
if (EXISTS ${CMAKE_BINARY_DIR}/conan_paths.cmake)
    include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
endif()
```

The idea is that users can either do `conan install ..` and afterwards `conan build ..` to install the package using conan, or just do `cmake ..` if they don't want to use conan at all.

With conan2, this approach is now deprecated in favor of CMakeDeps.

What is the "replacement" of the `cmake_paths` feature, and how can we achieve what we've been trying to do so far?

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-04-17 16:50
Hi @Jean1995 

the functionality of ``cmake_paths`` generator has already been implemented in Conan 1.X in ``CMakeToolchain``, you can use it even without updating to 2.0:

- Recipes should add the folders containing their cmake scripts to ``self.cpp_info.builddirs`` in their ``package_info()`` method
- ``CMakeToolchain`` will be adding those folders to the CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH, so they are automatically found. 
- No need to add ``CMakeDeps`` for this case. If you do, then it would be recommended that the recipes that package their script define the ``self.cpp_info.set_property("cmake_find_mode", "none")``

**Comment by apyvovar** [comment] 2023-05-25 16:34
Hi @memsharded 

Could you please clarify a little more regarding this issue.
In my projects, while consuming conan packages, we're highly relying on fact, that conan is launched by cmake helper file (much like https://github.com/conan-io/cmake-conan).
We're relying on `cmake_paths` generator in a similar way, as posted here by @Jean1995 .

Such approach incapsulates conan routines, so most of the teams doesn't really need to know much about how it works, this makes conan so cool for us :)
And more important, no need to manually launch anything, all works "out of the box" in any IDE as regular CMake project.

With 2.x, I assume conan must be launched before and provide cmake with ABI settings, as you suggested here as possible solution.

So my question is there any plans on supporting functionality,  similar to `cmake_paths` in a way so that it would be possible to launch conan from CMake, while consuming packages?

Thank you.

**Comment by memsharded** [comment] 2023-05-25 17:05
Hi @apyvovar 

If you are using something similar to cmake-conan, you might be interested in checking the "develop2" branch update we are working on: https://github.com/conan-io/cmake-conan/tree/develop2, that is ready for Conan 2.0. 

With the new cmake-conan approach the provider is just adding the ``generators_folder`` to the ``CMAKE_PREFIX_PATH``: https://github.com/conan-io/cmake-conan/blob/cce0a319dd09a1794d0bbbc91875fe97b86f7701/conan_provider.cmake#L229, and this is basically what you need to locate the generated xxxx-config.cmake files from ``CMakeDeps`` and everything works. Is this what you are looking for?

**Comment by apyvovar** [comment] 2023-05-25 22:34
@memsharded thank you for such quick reply.

I've seen this work and it's quite interesting. The problem is that it works with `CMakeDeps` generator, but in my case (we're using private repo) packages provide their own `xxx-config.cmake` files. So, basically, all we need is correct binaries in specified place, which makes `cmake_paths` perfect choice. 

Probably we could adapt `cmake-conan` and update the way of generating our packages, but still I'd be very grateful if there will be any more-or-less similar replacement of `cmake_paths` in foreseeable future.

Maybe, using `generators/<package>-<build_type>-<arch>-data.cmake` file alone will work, I'll give it a try. Still, even if works, IMO it looks like misuse of documented approach, so not really reliable way.

**Comment by feltech** [comment] 2023-08-16 11:31
Related to this, many (third-party) projects define/rely on CMake `Find<PackageName>.cmake` modules, which all too often define variables/targets that are not available via the CMake `<PackageName>Config.cmake` config files (whether provided by Conan or otherwise).

Ideally in those cases we just need a way to update CMake's search paths so that the Conan package cache is discoverable by custom `Find<PackageName>.cmake` modules.

The `cmake_paths` generator worked well for this.  But it's now deprecated.

`CMakeToolchain` forces `CMAKE_FIND_PACKAGE_PREFER_CONFIG`, so that any custom `Find<PackageName>.cmake` modules are skipped, causing configure/build failures.

Is there any workaround in the new v2 world?

**Comment by memsharded** [comment] 2023-08-16 13:16
Hi all,

> CMakeToolchain forces CMAKE_FIND_PACKAGE_PREFER_CONFIG, so that any custom Find<PackageName>.cmake modules are skipped, causing configure/build failures.

Modules shouldn't be skipped, they should be found and used. Only if an alternate xxx-config.cmake is found for that dependency, it will be prioritized instead. Please let us know if this is not the case.

Since the addition of ``CMakeDeps.set_property(dep, ...)`` the consumers have the full power to define what ``CMakeDeps`` is generating, if you don't want ``CMakeDeps`` to generate the config files, you can do ``deps.set_property("mydep", "cmake_find_mode", "none")`` and ``CMakeDeps`` will not generate a competing file for it, and the one inside the package would be used.

**Comment by feltech** [comment] 2023-08-16 16:52
> Modules shouldn't be skipped, they should be found and used. Only if an alternate xxx-config.cmake is found for that dependency, it will be prioritized instead. Please let us know if this is not the case.

Yeah that's the issue, that the config files are used by preference.

> Since the addition of `CMakeDeps.set_property(dep, ...)` the consumers have the full power to define what `CMakeDeps` is generating

OK nice! Wasn't aware of this (I've been crafting `conanfile.txt`s for third-party projects, but `conanfile.py`s are fine too).  It's a promising avenue, perhaps part of a solution...  

The main missing feature is how to go about augmenting (e.g. most usefully) the `CMAKE_PREFIX_PATH` to point inside the Conan cache entry for the package, so that when custom `Find<PackageName>.cmake` modules use e.g. `find_library`, the Conan cache will be searched?

Like I say, `cmake_paths` would augment the paths, without explicitly creating targets itself, which was great for this purpose.

**Comment by feltech** [comment] 2023-08-16 17:07
> The main missing feature is how to go about augmenting (e.g. most usefully) the `CMAKE_PREFIX_PATH` to point inside the Conan cache entry for the package, so that when custom `Find<PackageName>.cmake` modules use e.g. `find_library`, the Conan cache will be searched?

Ah, so is the combination of `CMakeToolchain` and `CMakeDeps` with `deps.set_property("mydep", "cmake_find_mode", "none")`  the solution?  Where `CMakeToolchain` will set up the `CMAKE_PREFIX_PATH` and `deps.set_property` can be used to suppress creating config files, so `find_package` will fall back to module mode.

I notice from the docs there's some hint it may be possible to switch off `CMAKE_FIND_PACKAGE_PREFER_CONFIG` in the `CMakeToolchain`-generated toolchain file.  That's another possible avenue.

Will have to experiment with this. Thanks!

**Comment by memsharded** [comment] 2023-08-17 22:04
> Ah, so is the combination of CMakeToolchain and CMakeDeps with deps.set_property("mydep", "cmake_find_mode", "none") the solution? Where CMakeToolchain will set up the CMAKE_PREFIX_PATH and deps.set_property can be used to suppress creating config files, so find_package will fall back to module mode.

Yes, that seems the most flexible solution that allows all potential use cases, with different priorities and needs. Note that the original package packaging the ``findxxxx.cmake`` module can define the ``self.cpp_info.set_property("cmake_find_mode", "none")`` as default, if that is the expected default for most users, and then invert the control, and require the consumers that want to consume it with the generated ``CMakeDeps`` config file to specify the ``deps.set_property("mypkg", "cmake_find_mode", "config")``.

>  notice from the docs there's some hint it may be possible to switch off CMAKE_FIND_PACKAGE_PREFER_CONFIG in the CMakeToolchain-generated toolchain file. That's another possible avenue.

Yes, the ``CMakeToolchain`` is highly configurable via ``blocks`` too, check: https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#extending-and-advanced-customization

Something like (not tested):
```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.blocks["find_paths"].values["find_package_prefer_config"] = "OFF"
    tc.generate()
```

**Comment by memsharded** [comment] 2023-12-14 14:10
I think we can close this ticket as resolved, but don't hesitate to open new tickets for any further question or issue you might have, thanks!

**Closed as completed by memsharded** 2023-12-14 14:10 UTC
Labels: type: question
