### ISSUE TITLE
early return in _install_any

### ISSUE THREAD

**Issue by kindlychung** [conan-io/conan#4008] opened 2018-11-27 10:34 UTC
This is clearly wrong, since it will install at most one required system package. 

https://github.com/conan-io/conan/blob/develop/conans/client/tools/system_pm.py#L126

**Comment by memsharded** [comment] 2018-11-27 11:05
From the docs: https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-system-requirements

> Note: This list of packages is intended for providing alternative names for the same package, to account for small variations of the name for the same package in different distros. To install different packages, one call to install() per package is necessary.

This is intended behavior, probably not the best naming/semantics, but already publicly documented and thus cannot be changed without breaking, so this can't be done. Please do a different call for each package you want to install.

**Comment by memsharded** [comment] 2018-12-03 08:21
Closing, this is documented behavior. There are plans for an improved interface to SystemPackageTool, we will take the feedback into account for it, thanks.

**Closed by memsharded** 2018-12-03 08:21 UTC
Labels: stage: triaging
