### ISSUE TITLE
'conan create' options

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2406] opened 2018-01-31 06:54 UTC
I'm trying to create a package. If it does not have `test_package` folder, options in
`conan create . user/channel -o option1=value1 -o option2=value2 ...`
apply to the package itself. But if `test_package` is present, the same command line will try to set options for test_package, not the package itself! To work around this one should use
`conan create . user/channel -o MyPackage:option1=value1 -o MyPackage:option2=value2 ...`
I think this not very correct behaviour. Don't you?

**Comment by memsharded** [comment] 2018-01-31 08:27
The correct approach for both cases is:
```
$ conan create . user/channel -o MyPackage:option1=value1 -o MyPackage:option2=value2
```
The explicit one. It should work the same in both cases, having or not a ``test_package`` folder.

The first one, using options without package scope still works for backwards compatibility and for some other cases (not conan create, but conan install) where the package name is still not defined. It shouldn't be used in general, and the docs shouldn't present it as such. So if you saw that in the docs, please tell where so we can fix it.

**Comment by db4** [comment] 2018-01-31 08:40
Thanks for explanation.  But why not to infer the package name for options if not explicitly specified? It's already inferred for reference (one can use `user/channel` instead of `MyPackage/version@user/channel`)

If not, I think `conan create` (and maybe others) should issue a warning when non-explicit option is supplied.

**Comment by memsharded** [comment] 2018-01-31 09:44
The package name is actually inferred from the conanfile.py, and this is the source of confusion. When there is not ``test_package`` the conanfile.py is the root one, that has a name that can be used.

But when there is a ``test_package`` the conanfile used is ``test_package/conanfile.py``, which doesn't have a name.

So:
```
$ conan create . user/testing -s option=value
```
is not a warning, it is the only way that you can supply options to ``test_package/conanfile.py``. Same for ``conan install``, ``conan build`` and other commands that are using a conanfile.py for consumption, and conanfile.py doesn't require to have a ``name`` attribute defined.

In any case I agree some extra logic could be added to issue a warning for those cases that could be differentiated.

**Comment by niosHD** [comment] 2019-02-05 16:57
I just stumbled across the same issue with options when I tried to create a package as shared with `-o shared=True`.

Steps to reproduce:
1. Create template with test_package: `conan new -t -s foo/0.1`
2. Add the missing shared option by modifying the `test_package/conanfile.py`.
3. Build the package: `conan create . bar/testing -o shared=True`
4. Lookup what version has been built: `conan search foo/0.1@bar/testing`

For me this yields a package with `shared=False`. Without the test_package, on the other hand, everything works as expected and I get a package with `shared=True`. (e.g., `conan new -s foo/0.1 && conan create . bar/testing -o shared=True && conan search foo/0.1@bar/testing`)

Conan Version: 1.12.1

**Comment by guiserle** [comment] 2021-07-13 15:30
I found the same problem myself today, when adding a test_package folder. I understand the reason but I kind of see it far from intuitive that you execute `conan create` on a `./conanfile.py`, but options are applied to `./test_package/conanfile.py`.

I would find easier to understand to have a separate argument for test options on conan create (for example `-to`), in a similar way to `-tbf` argument

**Comment by memsharded** [comment] 2021-07-13 17:23
@guiserle yes this is going to be changed in Conan 2.0

This ongoing work for 1.39 is related: https://github.com/conan-io/conan/pull/9267

**Comment by memsharded** [comment] 2024-01-10 23:07
This was changed in 2.0, closing as solved

**Closed by memsharded** 2024-01-10 23:07 UTC
Labels: type: feature, stage: queue, priority: medium, complex: medium
