### ISSUE TITLE
[recipe_hash] is empty after package_files execution

### ISSUE THREAD

**Issue by fjgarciao** [conan-io/conan#1361] opened 2017-06-07 09:54 UTC
Hi,
I'm trying to save a package in my conan local cache using the command ```conan package_files --force --package_folder ${folder} Adder/0.3@demo/testing```, where ${folder} contains:
```
/package
    /include/adder.h
    /lib/libadder.dylib
```
For some reason, the file "conaninfo.txt" inside the appropriate package folder in the conan local cache has an empty value in the [recipe_hash] section. Then, when I try to use this recipe in another test project the generated file "conanbuildinfo.cmake" doesn't contain a good value for property "CONAN_LIBS", which it finishes in a linking error. You can see it in line 42 in the following attached file: [conanbuildinfo.cmake.zip](https://github.com/conan-io/conan/files/1057601/conanbuildinfo.cmake.zip)

Here you can see the contents of my conan local cache for the module "Adder"
[conan_cache.zip](https://github.com/conan-io/conan/files/1057579/conan_cache.zip)

Thanks.
Best regards.

**Comment by memsharded** [comment] 2017-06-07 11:00
Hola Francisco Javier!

I think the problem is in your recipe. The info for CONAN_LIBS for consumers comes from the ``package_info()`` method of your package recipe. I see in your cache, that your recipe only contains a ``source()`` method, but no ``package_info()`` method. Actually, the ``source()`` method is not necessary if you are using the ``package_files`` command. 

Please have a look to: http://docs.conan.io/en/latest/howtos/existing_binaries.html#packaging-local-binaries. The command ``conan new --bare`` might help you. 

Please, also make sure that you understand the context and utility of the ``package_files`` command, it is intended for a very particular use case when you don't need the ``source()``, ``build()`` or ``package()`` methods, because the binaries are already pre-built outside conan. Feel free to ask if you have doubts :)

Regarding the ``recipe_hash`` that could be a minor issue, I will have a look at it. Thanks1

**Comment by memsharded** [comment] 2017-06-07 11:29
You were right, the recipe_hash was not being computed. Not a very big issue, not related to your problem with CONAN_LIBS. 

I have just submitted a fix to make sure the recipe_hash is computed and consistent with the recipe: https://github.com/conan-io/conan/pull/1362. Thanks for reporting!

**Comment by fjgarciao** [comment] 2017-06-07 12:00
Hi @memsharded,
I added the ```package_info()``` method in my recipe and it is working now.
I would suggest to add this requirement in the appropriate documentation section (http://conanio.readthedocs.io/en/latest/reference/commands/package_files.html).
Thanks.
Best regards.

**Comment by memsharded** [comment] 2017-06-07 12:25
Done: https://github.com/conan-io/docs/pull/223

**Comment by memsharded** [comment] 2017-06-17 21:18
The fix about the recipe_hash has been released in 0.24

**Closed by memsharded** 2017-06-17 21:18 UTC
Labels: bug, fixed, question
