### ISSUE TITLE
"Recipe not found" on just build package

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#5000] opened 2019-04-17 17:56 UTC
Not sure how to reproduce this as I've never seen it before. It's only happening on my CI server - not locally. I'm hoping maybe you have some brilliant idea as to why this might be failing. 

```
captain@398dc77bc9aa:/home/redlionci/tcAgentHome/work/b8265aa947a85f5b$ conan --version
Conan version 1.14.1
captain@398dc77bc9aa:/home/redlionci/tcAgentHome/work/b8265aa947a85f5b$ conan search esp32-at/1.1.3.0@wsbu/stable
Existing packages for recipe esp32-at/1.1.3.0@wsbu/stable:

    Package_ID: a803010e08c9a193a770573164b008555fd70603
        [settings]
            arch: esp32
            build_type: Debug
            compiler: gcc
            compiler.version: 5.2
        Outdated from recipe: False

    Package_ID: e0b5c2cd37d469e82fcd3376138f3aa6611cca95
        [settings]
            arch: esp32
            build_type: Release
            compiler: gcc
            compiler.version: 5.2
        Outdated from recipe: False

captain@398dc77bc9aa:/home/redlionci/tcAgentHome/work/b8265aa947a85f5b$ ls ~/.conan/data/esp32-at/1.1.3.0/wsbu/stable/export
conanfile.py  conanmanifest.txt
captain@398dc77bc9aa:/home/redlionci/tcAgentHome/work/b8265aa947a85f5b$ conan upload --force --confirm --all -r ci esp32-at/1.1.3.0@wsbu/stable
ERROR: Recipe not found: 'esp32-at/1.1.3.0@wsbu/stable'
captain@398dc77bc9aa:/home/redlionci/tcAgentHome/work/b8265aa947a85f5b$ 
```

**Comment by memsharded** [comment] 2019-04-17 18:06
Hi @DavidZemon 

Honestly no idea, seems very weird.
Might sound unrelated, but I prefer to do ``conan upload <ref> -r=remote --force --all``, in that order and with "=", it sometimes remove some inconsistencies in the command line parser.

Also, I would try to check the file permissions of the cache ``export`` folder files.
Does a ``conan get <ref>`` works correctly?

**Comment by DavidZemon** [comment] 2019-04-17 18:14
No such luck. Btw, here's the full build step, just for uploading the artifact. It is build in a previous step:

```
set -x
set -e
name=$(conan inspect . -a name | cut -d' ' -f2)
version=$(conan inspect . -a version | cut -d' ' -f2)
conan upload "${name}/${version}@wsbu/%CONAN_CHANNEL%" --remote=ci --force --all --confirm
conan remove "${name}/${version}@wsbu/%CONAN_CHANNEL%" --force
```

The `conan get <ref>` command does work and prints the recipe.

**Comment by memsharded** [comment] 2019-04-17 18:28
I can't think of anything, sorry :(

Is the failure consistent, it happens always? does it happens with every package, or only that package? Is it using docker, and works in your computer when using the same docker image and process?

If you are not able to figure out, maybe we could setup a "pair-debugging" session. Write us to info@conan.io, we could arrange something (most likely for next week, this one almost impossible). Cheers!

**Comment by DavidZemon** [comment] 2019-04-17 18:29
It is running in Docker. I'm working now to try and reproduce it in the Docker image locally.

**Comment by DavidZemon** [comment] 2019-04-17 19:27
Okay, I am able to reproduce this locally. _Hopefully_, you can reproduce the error yourself with the following commands:

```
$ git clone https://github.com/wsbu/conan-esp32-at.git
$ cd conan-esp32-at
$ docker run -it --rm --net=host -e uid=$(id -u) -e gid=$(id -g) -v ${HOME}/.conan/data:/home/captain/.conan/data -v ${HOME}/.conan/registry.json:/home/captain/.conan/registry.json -v ${HOME}/.conan/.conan.db:/home/captain/.conan/.conan.db -v `pwd`:`pwd` -w `pwd` wsbu/toolchain-esp32:v0.0.2
> conan create . foo/bar
...
...
...
> exit
$ docker run -it --rm --net=host -e uid=$(id -u) -e gid=$(id -g) -v ${HOME}/.conan/data:/home/captain/.conan/data -v ${HOME}/.conan/registry.json:/home/captain/.conan/registry.json -v ${HOME}/.conan/.conan.db:/home/captain/.conan/.conan.db -v `pwd`:`pwd` -w `pwd` wsbu/toolchain-native:v0.3.2
> conan upload esp32-at/1.1.3.0@wsbu/upload --remote=ci --all   

Python 2 will soon be deprecated. It is strongly recommended to use Python 3 with Conan:
https://docs.conan.io/en/latest/installation.html#python-2-deprecation-notice

ERROR: Recipe not found: 'esp32-at/1.1.3.0@wsbu/upload'
>
```
You'll need to replace that `--remote=ci` with something else but hopefully the rest "just works" for you.

**Comment by memsharded** [comment] 2019-04-17 20:56
Ok, I have some insights:

- The image you are providing there has conan **1.9.0** inside. 
- That conan 1.9.0 version didn't generate the metadata.json file when creating a package
- newer conan versions, like 1.14.1 does need the metadata.json file, otherwise it will think the package is not there.

Could it be that you are using different images or Conan versions? In your first post it seems you are using 1.14.1, but that is not the case for that docker image.

**Comment by DavidZemon** [comment] 2019-04-24 20:00
I've confirmed that by upgrading the esp32 docker image to Conan v1.14, the problem goes away. Thank you!

I also fixed a typo in the reproduction steps above, where i used a different user/channel in the two steps.

**Comment by memsharded** [comment] 2019-04-24 21:29
Ok, thanks for telling! Glad the issue is gone, I think we can close the issue now. Cheers!

**Closed by memsharded** 2019-04-24 21:29 UTC
Labels: stage: triaging
