### ISSUE TITLE
[bug] conan inspect throws an error in V2 mode if there is no option in the recipe

### ISSUE THREAD

**Issue by NoWiseMan** [conan-io/conan#11127] opened 2022-04-28 10:22 UTC
### Environment Details
  * OS: macOS 12.3.1
  * Xcode: 13.3.1
  * Conan: 1.47.0

### Steps to reproduce
create a recipe without an option
set the environment to enable ConanV2Mode
run `conan inspect conanfile.txt`

###
ERROR: Conan v2 incompatible: Declare 'default_options' as a dictionary

**Comment by MarcelRaad** [comment] 2022-11-07 13:46
Still happens with 1.53.0. This is the one thing preventing me to turn on Conan v2 mode for some of my Conan packages. Note that it only affects `conan inspect`, `conan create` is fine.
I'm not very familiar with Python, but maybe the issue is that unavailable attributes are set to empty strings here?
https://github.com/conan-io/conan/blob/427c310539b55681f650e049d518b88ae984c443/conans/client/conan_api.py#L313

**Comment by memsharded** [comment] 2022-11-07 23:42
Hi @MarcelRaad @NoWiseMan 

Quick question: What is the purpose of running a ``conan inspect`` over a ``conanfile.txt``? I guess it is a typo and it meant ``conanfile.py``?

Also a quick note: Since Conan 2.0 has been in alpha, the Conan v2 mode has been no longer maintained, so the set of validations and checks that it implements would be small compared to everything that Conan 2.0 alphas and betas have been providing. It is recommended to start running things against the released betas to check what could be failing, and report possible issues.

**Comment by MarcelRaad** [comment] 2022-11-08 06:39
@memsharded Yes, for me it's the recipe path with the conanfile.py.

**Comment by memsharded** [comment] 2022-11-08 08:30
@MarcelRaad I see, managed to reproduce it.
As CONAN_V2_MODE is no longer maintained, I'd like to avoid trying to fix it (too many things with higher priorities), I'd recommend:

- Start trying things with 2.0-beta
- As a workaround, declare ``default_options = {}`` in recipes to avoid it

**Comment by MarcelRaad** [comment] 2022-11-08 09:24
OK, thanks @memsharded ! It's not only for CI, but also for my developer machine, where I want to avoid multiple Conan versions and want to enable `CONAN_V2_MODE` globally to catch issues already while developing. But the workaround will do for that.

**Comment by memsharded** [comment] 2022-11-08 09:30
> and want to enable CONAN_V2_MODE globally to catch issues already while developing.

Yes, that is the thing, I don't think that CONAN_V2_MODE will capture more than 20% of the 2.0 changes, so at some point installing 2.0 (in a python virtualenv, recommended) will be the only way.

> But the workaround will do for that.

If the workaround is enough atm, then I will close this issue as "not planned", but feel free to re-open if necessary. Thanks!

**Closed as not planned by memsharded** 2022-11-08 09:30 UTC
