### ISSUE TITLE
[question] Does CMake build helper implicitly forward requirements?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#6305] opened 2020-01-07 13:42 UTC
While prototyping an end-to-end process (planned for publication soon 🤞), we stumbled upon what seems like a surprising behaviour:

* In a recipe, we have a very simple `build()` definition, as below:

```
    ...

    requires = "boost/1.70.0@conan/stable",
    generators = "cmake_paths",

    ...
    
    def build(self):
        cmake = CMake(self)
        #cmake.definitions["CMAKE_PROJECT_MyRepository_INCLUDE"] = \
        #    path.join(self.build_folder, "conan_paths.cmake")
        cmake.definitions["BUILD_tests"] = self.options.build_tests
        cmake.configure(source_folder="cloned_repo")
        cmake.build()
```

Notice how the logic that is including the generated `conan_paths.cmake` is commented out.

Yet, the build is successful, and the CMake call to `find_package(Boost REQUIRED COMPONENTS filesystem)` successfully locates Boost in the Conan cache.

Is there any implicit way the CMake helper is automatically satisfying this dependency here? This appears to be contradictory with our current understanding of how Conan should be used.

**Comment by danimtb** [comment] 2020-01-08 13:17
Normally the build helper does not perform any kind of additional adjustment to find the dependencies in the Conan cache, so the code above should fail not finding the dependencies.

Could you verify the path where cmake founds the boost libs? maybe it is taking it from ouside of the conan cache

**Comment by Adnn** [comment] 2020-01-08 13:54
Hello @danimtb, thank you for taking the time to review this question.

> Normally the build helper does not perform any kind of additional adjustment to find the dependencies in the Conan cache

This confirms our understanding, which seems like good news!

----

CMake indeed finds boost in the Conan cache.
Here is a minimal repository which produces the issues in our environemnt (macOS 10.14.6, Conan 1.20.4): https://github.com/Adnn/issue_conan-6305

It can be directly used as follows:

    git clone git@github.com:Adnn/issue_conan-6305.git
    cd issue_conan-6305/
    conan create .

In particular, we see this output from CMake configuration step

`-- Found Boost: /.../.conan/data/boost/1.70.0/conan/stable/package/2c303073418010e599da486f7108f72af5bf805b/include (found version "1.70.0") found components: filesystem`

**Comment by danimtb** [comment] 2020-01-08 15:14
Thanks a lot for the example. I tested that on my machine and getting the following error:

```
issue6305/1.0.0: Calling build()
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.18363.
-- The CXX compiler identification is MSVC 19.15.26730.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:4 (find_package)


CMake Warning at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:847 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:963 (_Boost_COMPONENT_DEPENDENCIES)
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:1622 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:4 (find_package)


CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindBoost.cmake:2048 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.70.0

  Boost include path: C:/.conan/8f2b36/1/include

  Could not find the following Boost libraries:

          boost_filesystem

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/danimtb/.conan/data/issue6305/1.0.0/_/_/build/67130b3734e619c299e68d58c18a5d18cd3ec97c/CMakeFiles/CMakeOutput.log".
issue6305/1.0.0:
issue6305/1.0.0: ERROR: Package '67130b3734e619c299e68d58c18a5d18cd3ec97c' build failed
issue6305/1.0.0: WARN: Build folder C:\Users\danimtb\.conan\data\issue6305\1.0.0\_\_\build\67130b3734e619c299e68d58c18a5d18cd3ec97c
ERROR: issue6305/1.0.0: Error in build() method, line 18
        cmake.configure()
        ConanException: Error 1 while executing cd C:\Users\danimtb\.conan\data\issue6305\1.0.0\_\_\build\67130b3734e619c299e68d58c18a5d18cd3ec97c && cmake -G "Visual Studio 15 2017 Win64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="15" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DCMAKE_INSTALL_PREFIX="C:\Users\danimtb\.conan\data\issue6305\1.0.0\_\_\package\67130b3734e619c299e68d58c18a5d18cd3ec97c" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -Wno-dev C:\Users\danimtb\.conan\data\issue6305\1.0.0\_\_\build\67130b3734e619c299e68d58c18a5d18cd3ec97c
```

It is using the *FindBoost.cmake* on my system, not the package one. Then it seems to find the path to the boost in the conan cache (it is a short path on windows)

I also tried setting CMAKE_TOOLCHAIN_FILE to use the generated conan_paths.cmake but it did not work. It seems that the package `boost/1.70.0@conan/stable` does not include the *FindBoost.cmake*. That might be an issue with the boost package.

-------------

Regarding this issue you might be interested in #5737

**Comment by Adnn** [comment] 2020-01-08 16:23
Which version of CMake are you running @danimtb ? We are on a quite recent 3.16 (should have made that a `build_requirement` ; )
You might be observing a separate issue from what was initially discussed.

But if we take a look at this line in your command output:

      Boost include path: C:/.conan/8f2b36/1/include

it might actually illustrate the initial question: even though we never provide any generator input to the `cmake build helper`, the CMake configuration step is able to locate Boost in the Conan cache.
If the build helper is not implicitly forwarding any information regarding the requirements, what could explain this behaviour?

**Comment by danimtb** [comment] 2020-01-08 16:29
I am using CMake 3.12.3 and I guess the *FindBoost.cmake* from the cmake installations find on different locations of the computer and it founds the conan's boost somehow.

You can also see the full cmake command in the log posted above, there are no additional definitions pointing to the boost location

**Comment by memsharded** [comment] 2020-01-08 16:36
Are you declaring any other generator too? (I see a trailing comma there). Because if using ``cmake_find_package_multi``, the helper is automatically appending:

```python
        if "cmake_find_package_multi" in self._conanfile.generators:
            # The cmake_find_package_multi only works with targets and generates XXXConfig.cmake
            # that require the prefix path and the module path
            definitions["CMAKE_PREFIX_PATH"] = install_folder
            definitions["CMAKE_MODULE_PATH"] = install_folder
```

**Comment by Adnn** [comment] 2020-01-08 16:53
@danimtb To make sure we understood, you mean `FindBoost.cmake` could actually find Boost in the Conan cache without any external hint? That would be interesting (and quite dangerous, how could it ever pick the right package hash when several are available?) 

@memsharded No other generators, just an habit of putting trailing commas in lists ; ) Actually, you might be interested in the minimal example at https://github.com/Adnn/issue_conan-6305

**Comment by danimtb** [comment] 2021-03-17 16:13
After no more activity on this issue, I am closing it as we never manage to reproduce it. Hope you figure out what happened there. Thank you!

**Closed by danimtb** 2021-03-17 16:13 UTC
Labels: stage: triaging, type: question
