### ISSUE TITLE
How to override dependencies on conan 2.0 

### ISSUE THREAD

**Issue by schmidjo82** [conan-io/conan#15749] opened 2024-02-26 07:59 UTC
### What is your question?

I can't find the option --require-override in conan 2.0.

At the moment, I am trying to get our packages ready for conan 2.0, but I am missing an important option on the CLI. 
We use a lot of recipes from conan-center, but we need to keep them stable over some years, so we copy them to a on local repository (the change rate is a way to high on the original side).
 
We deploy on an Linux system and need to keep some dependencies on the exact same version (options too) for specific libraries. On Conan 1.x I was using --require-override to do this. How can a achieve this on conan 2.0?  
I don't want to modify all recipes, since transient dependencies are archived by our own conan repository. 
Is that no longer possible? 
I saw the force flag in conanfile.py but is there no option on install or create command? 

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-02-26 08:34
Hi @schmidjo82 

This CLI argument was removed in Conan 2.0, it was too problematic.

There are different approaches to this:

- The process of building packages from ConanCenter from a fork is now recommended in the docs: https://docs.conan.io/2/devops/using_conancenter.html. In this case, aligning the versions on the recipes directly is the recommended way, and it allows to keep pulling from upstream in a controlled way to deal with the high change rate you mentioned. We are also in the process now of improving the ConanCenter CI to reduce the number of conflicts among other things
- Using lockfiles has largely improved in Conan 2.0. Using just 1 single file it is possible to achieve reproducible dependencies even for several configurations, and its usage is way simpler than in 1.X. This is the recommended way to achieve reproducible dependencies even when you are using your own fork but it evolves and it is necessary to be able to reproduce the dependency graph overtime even if the dependencies change.
- For **temporary** fixes of versions conflicts, the profile ``[replace_requires]`` Conan 2.0 feature can also be used. It is describe as such in https://blog.conan.io/2024/02/20/Conan-2-graph-features.html, because it shouldn't be used to permanently resolve version conflicts, instead fixing the conflicts in the recipes is the recommended approach.

**Comment by memsharded** [comment] 2024-04-11 09:12
Closing this question as responded, don't hesitate to open new tickets for any further question, thanks!

**Closed as completed by memsharded** 2024-04-11 09:12 UTC
Labels: type: question
