### ISSUE TITLE
[bug] apply_env does not correctly set environment when crossbuilding (build/host profiles)

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7737] opened 2020-09-22 13:47 UTC
Using the two-profile approach (`--profile:build`/`--profile:host`), the values from self.deps_env_info are not automatically applied to the os.environ.  I have attached a .zip to reproduce the issue.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64-bit
  * Compiler+version: n/a
  * Conan version: 1.29.2
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
[apply_env_fails_when_crossbuilding.zip](https://github.com/conan-io/conan/files/5261770/apply_env_fails_when_crossbuilding.zip)

**Comment by jgsogo** [comment] 2020-09-30 13:54
Hi, @GordonJess 

As it is stated [here](https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=deps_env_info#build-and-host-contexts) (same in the [note here](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=deps_env_info#deps-env-info)), the information from `env_info` of packages in the _host_ context is not propagated.

We didn't see the use-case where a requirement (a library we are linking with) should propagate environment variables to the consumers while they are building. We can be wrong, what kind of environment variable you need to consume while linking to another library?

Thanks!

**Comment by madebr** [comment] 2021-01-05 21:42
Hey @jgsogo,

I have a need for propagation of (environment) variables from a host requirement.

I'm currently working on conan recipes for a toolchain for the Nintendo Switch.
The core toolchain consists of 2 main recipes:
- devkitA64, which is a gcc arm64 compiler (target triplet=`aarch64-none-elf`).
  This package is to be used as a build requirement.
  It contains binutils+gcc+newlib, so should be built for the build system.
- `libnx`, which is the runtime for nintendo switch specific functions.
  This library is to be used as a host requirement. (It is built using the devkitA64 toolchain)
  It contains headers + libraries + [link script](https://github.com/switchbrew/libnx/blob/master/nx/switch.ld) + [specs file](https://github.com/switchbrew/libnx/blob/master/nx/switch.specs).

As you can see from the specs script, it contains `getenv(DEVKITPRO /libnx/switch.ld)`.
So when linking it expects an environment variable `DEVKITPRO` to the `switch.ld` linker script.
But since the `libnx` is to be used as a requirement, conan does not advance the `DEVKITPRO` environment variable from `libnx`.

**Comment by jgsogo** [comment] 2021-01-07 16:34
There is always a counterexample 😅 

So, in this example it is the host-requirement the one that provides a _link-script_ and you need to use that link-script to build/link your library/application with the `libnx` library, right?

A workaround would be to add `libnx` as a requirement but also as a build-requirement (like we already do with other packages like `protobuf`). IMO this `libnx` is more an exception than a rule and I would expect the link-script to be standardized and added to the linking tools (build-requires).

This is my personal opinion (and me trying to be lazy after some holidays), but I'd say that Conan features should focus on mainstream processes, especially if there is a _workaround_ that is also sound.

**Comment by madebr** [comment] 2021-01-07 17:03
> There is always a counterexample sweat_smile

Hehe, that's a fact of life. There is always an exception :stuck_out_tongue: 


> So, in this example it is the host-requirement the one that provides a _link-script_ and you need to use that link-script to build/link your library/application with the `libnx` library, right?

Yes.
The `devkitA64` is a general aarch64 compiler toolchain (with some patches), for which `libnx` is the one that gives specializations for the *Nintendo Switch*.


> A workaround would be to add `libnx` as a requirement but also as a build-requirement (like we already do with other packages like `protobuf`). IMO this `libnx` is more an exception than a rule and I would expect the link-script to be standardized and added to the linking tools (build-requires).

Adding libnx as a build requirement does not work as it's a cross building package.
`os`/`arch`/`compiler` of the host (=`os="Nintendo Switch" arch=armv8` does not match the build system (`os=Linux arch=x86_64`).

Adding `-specs=.../switch.specs` to `env.LDFLAGS` in my host profile would also be nice.
But I don't know how to access the location of the `libnx` recipe inside of the nintendo profile.

> This is my personal opinion (and me trying to be lazy after some holidays), but I'd say that Conan features should focus on mainstream processes, especially if there is a _workaround_ that is also sound.

Totally understandable.
Though, I think the current conan limitations are ad hoc.

A workaround I can apply right now, is to add an `libnx_installer` package that only contains the non-runtime components.

Perhaps, in honor of my issue about adding requesting autotools hooks (
https://github.com/conan-io/conan/issues/8290), maybe a hooking system for environment variables/user variables would be possible?

```python
# A default environment variable will be available when used as a build requirement:
self.env_info.VAR1 = "text"

# Setting attributes on the environment variable will extend/reduce its visibility:
self.env_info.VAR2 = "text"
self.env_info.VAR2.visibility["host"] = True  # VAR2 will now be available when used in a host context

self.env_info.VAR3 = "text"
self.env_info.VAR3.visibility["build"] = False  # VAR2 will NOT be availabe when used in a build context
self.env_info.VAR3.visibility["host"] = True  # VAR3 will now be available when used in a host context
```

IMHO, self.user_info deserves the same treatment.

**Comment by jgsogo** [comment] 2021-01-07 17:12
There is no need for a `libnx_installer` package. The same package may have different libraries/components depending on the settings. Not sure if it makes sense, but I'm sure you know how to do it, you are a master of packaging 😄 

Maybe something like this, I think it is easier to write and read:

```python
def package_info(self):
    self.env_info.VAR1 = "always available"

    if self.context == 'host':
        self.env_info.VAR2 = "only in host context"

    if self.context == 'build':
        self.env_info.VAR2 = "different value in build context"
        self.env_info.VAR3 = "only in build context"
```

**Comment by madebr** [comment] 2021-01-07 18:08
> There is no need for a `libnx_installer` package. The same package may have different libraries/components depending on the settings. Not sure if it makes sense, but I'm sure you know how to do it, you are a master of packaging smile

Thanks for the super hint!
I know how to do common things, but this is the first time I hear about `self.context`.
I guess `self.context` is a mnemonic for a way to determine the context?
It's not on https://docs.conan.io/en/latest/systems_cross_building/cross_building.html

Anyhow, I got it to work with adding the following code to the *libnx* recipe:
```python
    @property
    def _os_is_nintendo_switch(self):
        return str(self.settings.get_safe("os", "")) == "Nintendo Switch"

    def configure(self):
        if hasattr(self, "settings_target") and self.settings_target:
            self.settings.os = self.settings_target.os
            self.settings.arch = self.settings_target.arch
            self.settings.compiler = self.settings_target.compiler
            self.settings.compiler.libcxx = self.settings_target.compiler.libcxx
            self.settings.compiler.version = self.settings_target.compiler.version
            self.settings.build_type = self.settings_target.build_type
        if not self._os_is_nintendo_switch:
            raise ConanInvalidConfiguration("libnx is only available for os=Nintendo Switch")
```
I couldn't do:
```python
del self.settings.os
del self.settings.arch
del self.settings.compiler
del self.settings.build_type
```
Because otherwise, conan complained about missing packages (there is a package required for `os=Nintendo Switch` and one for `os=None`.
This feels dirty, and easily breakable.
Do you have a final hint to fix this?

**Comment by jgsogo** [comment] 2021-01-08 12:16
@madebr The `self.context` doesn't exist, it was a syntax suggestion. 

I wouldn't modify the settings in the `configure`, I'm sure it is not recommended. Let me draft the `conanfile.py`:


```python

class Recipe(ConanFile):
    settings = os, arch, compiler, build_type

    def validate(self):
        if self.settings.os not in ["Linux", "Nintendo Switch"]:
            raise ConanInvalidConfig()

    def build(self):
        if self.settings.os == "Nintendo Switch":
            # Build libnx library

    def package(self):
        if self.settings.os == "Nintendo Switch":
            # Copy libnx to package
        elif self.settings.os == "Linux":
            # Copy switch.ld to package

    def package_info(self):
        if hasattr(self, "settings_target"):
            assert self.settings.os == "Linux" and self.settings_target.os == "Nintendo Switch"
            # It is being used as a build-requires, only provide the environment variable
            self.env_info.DEVKITPRO = "path/to/switch.ld"
        else:
            assert self.settings.os == "Nintendo Switch"
            self.cpp_info.libs = ["libnx"]
            self.cpp_info.includes...

```

This is the same package generating completely different packages depending on settings. I did something similar for a working Android-NDK recipe here (https://github.com/jgsogo/conan-center-index/blob/android_ndk/recipes/android-ndk/all/conanfile.py)

**Comment by dvirtz** [comment] 2021-04-26 13:05
I've also run into this bug. I'm trying to install the `autoconf/2.69` package from ConanCenter which depends on `m4/1.4.18` which appends its `bin` folder to `PATH` in `package_info()`:

https://github.com/conan-io/conan-center-index/blob/ef9b1198c90a40a6caec1b53652f1271b1a3afd9/recipes/m4/all/conanfile.py#L109

As `env_info` is not propagated, autoconf can't find `m4`:

```
checking for GNU M4 that supports accurate traces... configure: error: no acceptable m4 could be found in $PATH.
GNU M4 1.4.6 or later is required; 1.4.16 or newer is recommended.
GNU M4 1.4.15 uses a buggy replacement strstr on some systems.
Glibc 2.9 - 2.12 and GNU M4 1.4.11 - 1.4.15 have another strstr bug.
autoconf/2.69: 
[HOOK - attribute_checker.py] pre_export(): WARN: Conanfile doesn't have 'license'. It is recommended to add it as attribute
WARN: libevent/2.1.12: requirement openssl/1.1.1g overridden by zavit/0.1.46 to openssl/1.1.1i 
WARN: libcurl/7.71.1: requirement openssl/1.1.1h overridden by aws-sdk-cpp/1.8.146 to openssl/1.1.1i 
autoconf/2.69: WARN: compiler setting should be defined.
autoconf/2.69: ERROR: Package '39b00cd714c2483c6df4fff03ea1cf80dbb8b287' build failed
```

**Comment by jsteinhofff** [comment] 2021-08-09 07:22
Same problem here when using ROS in a cross-compilation scenario. It seems it always comes up when packaging existing 3rd party stuff which mixes up content intended for build/host contexts. I dont think this too much of a special case, but rather is part of the beautiful property of conan: we can **easily** take existing stuff and wrap it as conan package and therefore extend the conanized kingdom :-D

@jgsogo could we maybe turn the question around: "why should env_info not propagate from a build_requirement in host-context/a normal requirement in host-context?"

I imagine the reason is something like "we split those two context, so now we want to keep them cleanly separate". But this got me thinking: what is actually a "context"? Why did you introduce the concept? My understanding/assumed reasoning is:

* a conan binary package is identified by its settings (beside many other things like version number)
  * it only has one set of values for it's settings
  * it does not know about in which whay it will be consumed (as requires or as build_requires)
* a conan package is either
  * only specific to the system on which the build is running, we call those build tools. Since it is only specific for the system on which the build is running, its settings should only incorporate information about this build system. Information about the system for which we are building (the host system) should not be contained.
  * specific to the system on which the build software will run ("the host system"). So therefore it's settings should be filled with values from/for this host system.
* classically, conan settings are valid/applied through the whole dependency graph. This would not allow to have both package types mixed in one graph.

The invention of the build/host context concept resolves this elegantly: you now can build up two dependency graphs and depending on which sub-graph you are in, either the build-settings or the host-settings are used.

But for my current understanding that is all about it. It is only about managing which settings are to be used to compute the package-id. The overall goal is still to build software. And independent in which context a package is included in the graph, if it provides information like environment variables, scripts, whatever, this information is there to inform the build process. The build process is not happening *in* the build context, it only resolves packages through the build context.

Did i understand this correct? Or do you really think the "context" thing is much bigger, and the build is happening "inside"? What then, are you planning to do in the host context? What is the meaning of an environment variable in the host context? Do you imagine to somehow deploy it and make it available at runtime?

**Comment by jgsogo** [comment] 2021-08-09 08:02
Hi, @jsteinhofff. I'm a bit disconnected from the current evolution of the build/host environments, build-helpers, and the new paradigm of propagating information aiming to Conan v2. I can only tell about the original conception and how it is intended to work... which is what this issue is about. Things are changing in the new versions and they are aligning towards the design for Conan v2. I encourage you to check this repository regularly (https://github.com/conan-io/tribe) and to start testing the new toolchains and utilities that are being released in the latest Conan v1.x releases to introduce those new behaviors.

---

When building C++ projects there are three main things: the build machine, the build-system, and the sources. The build-system orchestrates the things provided by the build-machine to operate on the sources and generate the final binaries. Conan can be conceived as a tool that provides sources and build instructions to the build-system (this is enclosed in recipes _living in the host context_), but also as a tool that provides binaries/information to complement the utilities provided by the build machine (recipes in the _build_ context).

With this in mind, the nature of the information provided by Conan's _build_ context cannot be different from the nature of the information already available in the build machine, mostly environment variables and executables (PATH). And the nature of the information provided by Conan's _host_ context should be just sources (locations, folders) and build instructions. 

Each of those contexts is created by recipes with a `requires` relationship (not build-requires), it is what we call a graph. Every graph can be thought of as a recipe (bottom vertex) and all its requirements, and it can be summarized in a set of environment variables, paths to libraries, executables, includes,... definitions,... When this graph is used as a `build-requires`, it propagates only the information associated to the _build_ context, when the graph is used as a `requires` of another library it propagates the include/linking information.

(In that conception, ) Conan always refers to the bottom vertex recipe in the _host_ context (`conan info <reference>`, `conan create <reference>`, `conan install <reference>`) and build-requires cannot be referenced directly, they are just requested by a recipe from the _host_ context (or by the _host_ profile). From the CLI you weren't able to refer directly to recipes in the _build_ context, you only work with the _host_, which is the main purpose of your work: generate the binaries you are trying to build.

There is somehow an exception: the family of virtualenv generators. With these generators you can extract information from the graph (always the bottom vertex recipe in the _host_ context): 
 * you can use `virtualenv` to get the information that would correspond to the _build_ context, but from the _host_ graph (this is the same information that would be propagated if the graph was used as a build-requires). For example: `conan install cmake/3.19@ -g virtualenv` will collect the environment variables and PATH to use `cmake` the way you (and Conan) would use it as a build-requires. Remember, as said before, that CLI always refers to the bottom vertex recipe in the _host_ context, so yes, here you will extract an environment variable from the _host_ context, **runtime information**.
 * `virtualbuildenv` will gather the information of the _build_ context for the recipe in the _host_ context you are referring to in the CLI. This was intended to allow you to reproduce the _build environment_ that Conan would use to build the library, that way you can activate the environment and run everything from the CLI without Conan. 
 
 ---
 
As said, please, don't forget to check https://github.com/conan-io/tribe and the new utilities in latest Conan v1.x.

Thanks!

**Comment by jsteinhofff** [comment] 2021-08-10 07:00
Hi @jgsogo , thanks for your quick response! I am not completely sure how to read it though, but i believe i understand that you mean that contexts in conan v1.x are not just what i wrote above (encapsulating a set of settings to identify packages for either build or host), but rather you also see that information provided by the packages is contained in such a context.

Your example with `conan install <reference>` is very interesting because it shows that an exported variable changes meaning depending on the use case. This is no issue as long as only one use case is relevant, but if build-tool and runtime usage (/host-specific content) are mixed like we have for 3rd party stuff, then we have no way to declare so.

Your proposal above where you distinguish both cases in `package_info()` might be a workaround, but it would require to build the package twice, once for host, once for build and i fear that in the detail you again get into trouble because also for the build side you need the right libraries for the right host system, which is then not specified in the settings.

Maybe i try to trigger a discussion about this in the tribe, sofar this was driven by design PRs from jfrog side, but if i remember correctly we can also use the mailinglist to bring our own discussions?

**Comment by jgsogo** [comment] 2021-08-10 07:29
In the generic scenario you will always have two different packages, one for the _host_ context and another for the _build_ context, because settings are different and generated binaries are different (building a library that uses protobuf will require `protobuf` package in the _build_ context to run `protoc` and also `protobuf` package in the _host_ context to link with the library). The recipe is the same, but Conan will use two packages, the _host_ context will contain the package using the _host_ settings and the _build_ context the one matching the _build_ settings.

This scenario is perfectly supported (I'll follow with the `protobuf` example): the _build_ package will provide environment to the build-system, like the PATH to `protoc` executable, while the _host_ package will provide include folders and linking information. 

Note about building all packages with one single command: Conan is capable of building in the same shot all the packages, packages in _host_ context will use the _host_ settings, while package in the _build_ context will use the _build_ settings. Conan always builds _host_.... but the _build_ settings are the _host_ ones from the perspective of a package in the _build_ context, that's why `self.settings` (which are the _host_ settings) always refers to the configuration of `this/self` package.

---

In my example, I was using the `settings_target`, which is one more layer of complexity, when you want your build-require to provide a different environment depending on the settings of the _host_ context you are building (from the perspective of the _build_ context, the _host_ context is referred to as _target_ context).

---

I know this is almost a riddle, it is hard to explain, but if you want me to I can try to rephrase and try to make it more clear.

**Comment by jsteinhofff** [comment] 2021-08-13 05:52
Hi @jgsogo i had a look at the protobuf package in conan center and i understand how/why it works when consuming it twice, once as build_requires and once as requires. Still i am not completely convinced that this approach will work for our use-cases, and i see two reasons:
* the packages we are talking about are 1 . 2 GB in size, uploading them twice with same content is really hard to my stomach :-D
* also the protoc counterpart in our example differs depending on the target system (either Linux or QNX) (at least it can differ)

The more i think about it, the more i am uncertain if we are going in the right direction. With single profile we had a quite easy to understand solution, although we had to "hack" sometimes since we couldnt describe all situations correctly. Now when trying to split build/host profile, the sentences you have to write are almost kafkaesk (i love riddles but not in my build system ;-) ) and i am still not certain we will be able to nicely model what we have at hand.

I will try to prepare some pictures to describe the situation and the options we have, maybe we could then have a separate discussion about it.

For this ticket here with conan 1.x in mind, i think i should not disturb anymore.

**Comment by jgsogo** [comment] 2021-08-13 06:30
Sure, your concrete use case might have some restrictions that make it hard/easier to approach with this perspective... but for sure we would need more details to understand it and maybe we can give some advice. I just wanted to comment about your two bullet points:

> * the packages we are talking about are 1 . 2 GB in size, uploading them twice with same content is really hard to my stomach :-D

If different configurations compute different packageIDs, there will always be two different Conan packages, this is not related to cross-building or build/host profiles. If the same packageID is valid for _build_ and _host_ contexts, there will only be one package in the cache, although there are two _pointers_ to it from the Conan graph. 

> * also the protoc counterpart in our example differs depending on the target system (either Linux or QNX) (at least it can differ)

This was one of the things I was struggling with at the beginning, but in the end, I think that the target system should be encoded into an option if the package needs to be different. Usually the build tools (like `gcc` compiler, for example) use the same binary (same packageID) to generate files (to compile) for different target settings (debug, release, shared, static,...), not always the target configuration requires a different build tool binary.... but sometimes it does, for example, if you want to build to `x86` you need multi-arch support, you need a different `gcc` binary (at least one different from the one that only generates `x64`), and this can be modeled using Conan options.

**Comment by dev-789** [comment] 2021-09-10 09:44
Also in our Project its a bigger issue i think. In the end our product is a mixture of python and libs and executables

An example could be something like
```
App -> PythonCompA -> PythonCompB
                 \-> PythonCompC
````
In PythonCompB and C we are appending to the Pythonpath to populate modules to PythonCompA. 
And here we already have a strange thing when we are using two profiles. We need to build_require the PythonCompB and C to use them in A. This actually cuts the dependency tree if we are in App as build_requires are not transitive, what makes sense as they are only required the create A. Once its available as binary package build_requires are not necessary ...
Only option i see is to hack around with user_info, or repackaging the Python content from B and C in A?

**Comment by memsharded** [comment] 2021-09-10 09:48
The new ``self.buildenv_info`` and ``self.runenv_info`` together with the new generators ``VirtualBuildEnv`` and ``VirtualRunEnv`` allows a finer control of what gets into the environment in each case. I know they are not enough documented yet, but we will soon start promoting them more, as they will become the way in 2.0. Just in case you want to start having a look at them: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html

**Comment by chausner-audeering** [comment] 2021-12-11 23:03
I have also run into a case where propagation of environment variables in the host context is desired.

The OpenVINO library provides a `setupvars.sh` script which sets various environment variables (e.g. `*_DIR` variables for CMake) that need to be set before other libraries can use it as dependency. I first tried to translate this script to `env_info` which worked well in the normal case but failed when cross-compiling using host/build profiles because `env_info` does not get propagated in this case.

At the moment, my workaround is to define the variables in `user_info`:

```python
def package_info(self):
    self.user_info.INTEL_OPENVINO_DIR = self.package_folder
    self.user_info.INTEL_CVSDK_DIR = self.package_folder
    self.user_info.InferenceEngine_DIR = os.path.join(self.package_folder, "deployment_tools", "inference_engine", "share")
    self.user_info.TBB_DIR = os.path.join(self.package_folder, "deployment_tools", "inference_engine", "external", "tbb", "cmake")
    self.user_info.ngraph_DIR = os.path.join(self.package_folder, "deployment_tools", "ngraph", "cmake")
```

Then they can be accessed by dependencies via `deps_user_info` and be injected into the environment:

```python
for var, value in self.deps_user_info["openvino"].vars.items():
    os.environ[var] = value
```

**Comment by memsharded** [comment] 2021-12-11 23:15
Hi @chausner-audeering,

Yes, I think this case will be solved too by the new environment management which is explicit and always propagated, irrespective of the host/build context. Adding the variables to ``runenv_info`` or ``buildenv_info`` will result in consumer side (via ``VirtualRunEnv`` and ``VirtualBuildEnv`` in the respective env-var activate scripts.

**Comment by memsharded** [comment] 2024-02-06 23:57
Closing this as outdated (referred to the legacy environment management). Please create new tickets as necessary regarding the new environment integrations, thanks!

**Closed as not planned by memsharded** 2024-02-06 23:57 UTC
Labels: stage: triaging
