### ISSUE TITLE
conan install says "Missing prebuilt package" even though search shows matching packages

### ISSUE THREAD

**Issue by themanwhosoldtheworld** [conan-io/conan#5127] opened 2019-05-10 14:31 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Conan version:** 1.14.5
**Compiler:** gcc
**OS:** Windows
**arch:** x86_64
**Steps:** 
Attached the conanfile.txt used for the project
**default conan settings:**
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++
compiler.exception=seh
build_type=Release
[options]
[build_requires]
[env]

`conan install ..`
Gives the following message
```
boost_package_tools/1.66.0@bincrafters/stable: Already installed!
bzip2/1.0.6@conan/stable: WARN: Can't find a 'bzip2/1.0.6@conan/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, compiler=gcc, compiler.exception=seh, compiler.version=7, os=Windows
- Options: build_executable=True, shared=False
- Dependencies:
- Package ID: 7bcb26fbb88872c62163dcfad726eb86fc9a5b8e

ERROR: Missing prebuilt package for 'bzip2/1.0.6@conan/stable'
Try to build it from sources with "--build bzip2"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

[conanfile.txt](https://github.com/conan-io/conan/files/3166829/conanfile.txt)

I tried searching for the bzip2 packages matching my settings and it showed some matches
```
$ conan search bzip2/1.0.6@conan/stable -r=all -q "arch=x86_64 AND os=Windows AND compiler=gcc AND build_type=Release AND compiler.exception=seh AND compiler.version=7"
Existing packages for recipe bzip2/1.0.6@conan/stable:

Existing recipe in remote 'conan-center':

    Package_ID: 402bf05ba0cb88a78c59efe7e90ebf2d341edad2
        [options]
            build_executable: True
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.exception: seh
            compiler.threads: posix
            compiler.version: 7
            os: Windows
        Outdated from recipe: False

    Package_ID: 6dc82da13f94df549e60f9c1ce4c5d11285a4dff
        [options]
            shared: False
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.exception: seh
            compiler.threads: posix
            compiler.version: 7
            os: Windows
        Outdated from recipe: True

    Package_ID: 8796a7e7c2d7bdba7ad775181d8b543980e7b18c
        [options]
            shared: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.exception: seh
            compiler.threads: posix
            compiler.version: 7
            os: Windows
        Outdated from recipe: True

    Package_ID: e5d344ecc5ab9a803dc6f563bd524a451dc6e6e3
        [options]
            build_executable: True
            shared: True
        [settings]
            arch: x86_64
            build_type: Release
            compiler: gcc
            compiler.exception: seh
            compiler.threads: posix
            compiler.version: 7
            os: Windows
        Outdated from recipe: False
```

What am I missing here? How can I find out which of my settings/options are not matching the settings of these packages?

**Comment by lasote** [comment] 2019-05-13 07:59
Hard to know, I noticed that your profile and the error message doesn't include `compiler.threads` setting and the most similar package found in the search (first one) have `compiler.threads: posix`.

**Comment by JessHolle** [comment] 2019-07-31 17:55
In general, it would be *very* helpful if there was a verbose mode to `conan install` that would actually show the mismatch for each available prebuilt package in the case that no match is found.  I am finding it maddening to read that there is no match -- and not being able to discern why what appear to be matches are not matches.

**Comment by lasote** [comment] 2019-08-02 06:44
> In general, it would be very helpful if there was a verbose mode to conan install that would actually show the mismatch for each available prebuilt package 

The package id of a package could be affected even for its requirements. And checking all the remote packages is expensive.
It is doable but hard, not sure how this feature should look like, a conan install with a flag causing a search in the remote for all the configurations sounds weird.

**Comment by planetmarshall** [comment] 2020-06-30 18:14
Came across this in a search so thought I'd post in case it was useful.

I recently had a particularly frustrating case and solved it as follows: 

1. Run `conan install` and check for the missing package error. At time of writing (Conan 1.26.1) it will output the requested options, settings and dependencies for the missing package.
2. Run `conan search <package> -r <remote>` and find the package id of the package you think should match
3. Run `conan get <package>:<package-id> -r <remote>`. It will output all the options and settings for that package. Compare with the requested options in (1) and find the mismatch (if there are a lot, it may be helpful to write a script to do this)

In my case, the result was an outdated dependency because i had an `override` package specified in my conanfile in order to resolve a dependency conflict. The solution was to remove the override and rebuild the upstream package.

**Comment by memsharded** [comment] 2020-06-30 21:29
Hi @planetmarshall 

Maybe for this use case, the new ``conan search <ref> --table=file.html`` can be helpful, as it will output an html that allows filtering and searching, including transitive requirements, so that can help debugging faster what is the missing binary. Have you had a look at this feature?

**Comment by planetmarshall** [comment] 2020-06-30 21:45
> Hi @planetmarshall
> 
> Have you had a look at this feature?

I haven't yet but thanks - I'll keep it in mind for future troubleshooting.

**Comment by schwaerz** [comment] 2022-03-29 16:45
I am facing the same issue currently.
There is a binary package on Artifactory matching the expected package ID. Also when pasting the profile into `file.html`, it will show the same binary package.

As there's only a handful options, it is also rather easy to spot that those options actually are identical.

In addition I copied all the settings and options for one of the packages listed in `file.table` to the command line to `conan install`. Still it would not download the package but complain about a missing binary package with a package ID which already exists and will be found by `conan search`.

Not sure how to continue. I must be missing something.

If you got any pointers about how to debug, that'd be great.

Please check the following console log:
```
$ conan search zlib/1.2.11@ --query "(os=Windows AND arch=x86 AND build_type=Debug)" -r=conan-des-eden-osbs-local
Existing packages for recipe zlib/1.2.11:

Existing recipe in remote 'conan-des-eden-osbs-local':

    Package_ID: 9ffec4a59d60a2ccf636e06ba57253e21417f01b
        [options]
            shared: False
        [settings]
            arch: x86
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 16
            os: Windows
        Outdated from recipe: False

(.venv)

$ conan install -r conan-des-eden-osbs-local -s compiler="Visual Studio" -s compiler.runtime=MDd -s compiler.version=16 -s build_type=Debug -s arch=x86 -o shared=False zlib/1.2.11@
Configuration:
[settings]
arch=x86
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
shared=False
[build_requires]
[env]

Installing package: zlib/1.2.11
Requirements
    zlib/1.2.11 from 'conan-dss-deliveries-local' - Cache
Packages
    zlib/1.2.11:9ffec4a59d60a2ccf636e06ba57253e21417f01b - Missing

Cross-build from 'Windows:x86_64' to 'Windows:x86'
Installing (downloading, building) binaries...
ERROR: Missing binary: zlib/1.2.11:9ffec4a59d60a2ccf636e06ba57253e21417f01b

zlib/1.2.11: WARN: Can't find a 'zlib/1.2.11' package for the specified settings, options and dependencies:
- Settings: arch=x86, build_type=Debug, compiler=Visual Studio, compiler.runtime=MDd, compiler.version=16, os=Windows
- Options: shared=False
- Dependencies:
- Requirements:
- Package ID: 9ffec4a59d60a2ccf636e06ba57253e21417f01b

ERROR: Missing prebuilt package for 'zlib/1.2.11'
Use 'conan search zlib/1.2.11 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=zlib'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

**Comment by schwaerz** [comment] 2022-03-29 16:59
Some additional info. Tried the following:
```
conan install -r dev -s compiler="Visual Studio" -s compiler.runtime=MDd -s compiler.version=16 -s build_type=Release -s arch=x86 -o shared=False zlib/1.2.11@ --build=missing

conan upload --all -r dev zlib/1.2.11@

conan remove zlib -f

conan install -r dev -s compiler="Visual Studio" -s compiler.runtime=MDd -s compiler.version=16 -s build_type=Release -s arch=x86 -o shared=False zlib/1.2.11@
```

Still it complains that the binary package cannot be found:

```
ERROR: Missing prebuilt package for 'zlib/1.2.11'
Use 'conan search zlib/1.2.11 --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=zlib'
```

Looks like a bug in Conan to me?
Could it be an issue that more than one remote would possibly serve the same package? Although I did specify the remote to use on the command line...

**Comment by memsharded** [comment] 2022-03-29 17:04
Hi @schwaerz 

Yes, there is definitely something weird happening there. Maybe the package is corrupted in the server side?

It might be also possible some issue if you have more than one server, but some of the below suggestions could rule that out.
Some things that I would try to investigate:

- Creating a "hello" package, with exactly the same configuration. The ``package_id`` should be identical. Upload to the server, and then try to install it the same way. Compare the server storage, maybe the ``conanmanifest.txt`` file was accidentally deleted?
- Make sure the conan cache is completely clear. Try from another computer to discard some glitch in the Conan client
- Report the Conan client version

**Comment by schwaerz** [comment] 2022-03-29 17:17
Hi @memsharded 
Thanks for the quick response.
* We tried this already on different machines (different users), even from within a docker container.
* We uploaded the package already several times, also to another repository.
* For other packages this is working fine.
* We only can see this behavior for zlib and boost.
* Same behavior after completely removing the local Conan cache (`%USERPFOFILE%/.conan/data` and `c:/.conan`)
* The Conan manifest files are all existing
* When creating the hello package, I get the same package id. However: Downloading the hello package works.
* This seems to happen only for the Windows package. The Linux package I can download without any issues.

We are using the Conan client `1.46.2`. We are using package revisions.

**Comment by memsharded** [comment] 2022-03-29 17:28
Can you elaborate a bit further also on your server setup? Which server? Any possible front (nginx or something) to the server that could be filtering something?

Also, the ``conanmanifest.txt`` I guess you looked for them both in the recipe "export" folder and in the "package" folders. Also the ``conaninfo.txt`` must exist inside the binary packages, but that seems to be right, otherwise you wouldn't get them in the search.

I am really surprised at this, so If you can make it, I can even try to jump to a zoom call to pair-debug this. Write to info@conan.io with some contact detail if you want.

**Comment by schwaerz** [comment] 2022-03-29 17:58
We are running Artifactory Enterprise Plus 7.7.3 rev 70703900, manifest is existing at both places. `conaninfo.txt` is also where it should be. No sure about the other details. But there should not be any filtering in place.
I'd be happy about a zoom call, will get in touch we you, thanks.

**Comment by schwaerz** [comment] 2022-03-30 13:47
Ok, we found something...
We had the same package in the same version with the same user and channel in different repositories, which were all configured as remotes.
In one of the repositories the binaries in question did not exist. In the other one it did. But Conan does not seem to search all repositories (probably this is even documented somewhere).

Also I cannot recall how I managed to get the error mentioned [here](https://github.com/conan-io/conan/issues/5127#issuecomment-1082134344). Maybe I did something wrong. :(

Not sure whether yesterday I just missed the information about which remote has been used, or whether it is not always shown.

As of now it looks like this is fixed for me. Thanks :)

**Comment by memsharded** [comment] 2022-03-30 16:03
> In one of the repositories the binaries in question did not exist. In the other one it did. But Conan does not seem to search all repositories (probably this is even documented somewhere).

Oh yes, this makes sense. This is known 1.X behavior, in which Conan associates the binaries to the remote it is getting the recipe by default. This is this way because Conan 1.X initially didn't have revisions, and without revisions you cannot guarantee consistency between the binaries and recipes, so it was this way.

Conan 2.0 will be able to iterate multiple remotes until finding a specific binary, as long as it belongs to the same recipe revision. That should in theory improve and avoid more of these potential issues.

Great, lets close this one now, don't hesitate to re-open or create a new one if you see further issues. Thanks!

**Closed by memsharded** 2022-03-30 16:03 UTC
Labels: type: question, type: look into, priority: low, stage: queue, complex: high

**Comment by apyvovar** [comment] 2022-03-30 16:33
Hi, @memsharded 

I'm having the similar issue. Conan `1.46.2` (currently latest) is used with Artifactory for storing private packages.
The `Missing` package error displays only on CI, when Jenkins is building packages. 
Users can execute the exaclty same `conan install ...` command successfully (with all same settings and options).
Clean reinstall of conan fixes the issue, but only for some time. After some time, random package becomes `Missing` again.
How would you recommend to find out the core problem? Is there any Jenkins and/or environment setting, which may cause such behavior?
Thanks in advance

**Comment by memsharded** [comment] 2022-03-30 16:38
Hi @apyvovar 

Not sure if this will be the same issue. In the case above, the cause was having multiple remotes, and only one of them containing the binary, so the resolution couldn't get that binary.

Do you also have multiple repos? Is the problem reproducible, in the sense that your ``conan search`` will return those binaries, but failing to install them? Probably it makes sense to create a new ticket for your case.

**Comment by christian-schmaler-snkeos** [comment] 2022-07-28 15:43
Hi, I am facing the exact same issue. Two remotes are configured, conancenter and our private artifactory installation. We needed to add prebuilt binary packages of some third_party packages (jasper, libtiff) to our private artifactory because the required configuration did not exist in conancenter. However, projects needing those packages always report the mentioned error because only conancenter is considered and there the packages with the needed configuration are not found.
Is there a suggested workaround before conan 2.0?
Thank you

**Comment by memsharded** [comment] 2022-07-28 15:47
Possible workarounds:

- First, make sure that revisions are enabled, if using multiple servers, this is recommended
- Use virtual repositories in Artifactory to aggregate, instead of aggregating in the client side
- Usage of ConanCenter directly in production is not recommended. You should at least use a remote repository, but having a copy of the ConanCenter packages in your own server is recommended. 
- Do not split binaries for the same thing in different repositories. All binaries for the same "recipe" should be in the same server (not using binaries downloaded directly from ConanCenter would help of course)
