### ISSUE TITLE
[bug] build_requires version resolution does not have override

### ISSUE THREAD

**Issue by barmaglot27** [conan-io/conan#7016] opened 2020-05-14 07:47 UTC
We follow semver for package versioning and for requires specify minor compatibility, in our requirements we have:
libA/**1.0.0+1**
in build_requires:
libB/1.0.0+1

And libB/1.0.0+1 requires a newer build of libA/**1.0.0+2**
I am getting an error asking to override libA because my conanfile and libB are conflicting!

I was investigating the order of calls and it seems like build_requires do not participate in graph resolution and gets added later on top of already built graph.
force_host_context does not affect the result - it only affects CMake generator paths.
separating build profile from host profile also makes no difference.
I also tried with older version of Conan 1.21.1 - same effect.

To make the above error go away I had to move libB from build_requires to requires (and set compatibility for it to be unrelated, so at least it does not participate in package id calculation), but it defeats the purpose - it exposes my test tools on my consumers and they have to download irrelevant stuff.

Is it possible to make requires serve as overrides for build_requires?

### Environment Details (include every applicable attribute)
  * Operating System+version: RHEL
  * Compiler+version: gcc 4.8.3
  * Conan version: 1.24.1
  * Python version: 3.7

**Comment by memsharded** [comment] 2020-05-14 12:09
Hi @barmaglot27 

Some ideas:

- ``libB/1.0.0+1`` this way of specifying version is called "build metadata" in semver. There is NO guarantee that ``libB/1.0.0+2`` resolves later than ``libB/1.0.0+1`` in a version range. Any build metadata can be used to resolve a version range.

- Definitely, build_requires do not participate in the "product" graph. They are added later, only if it is necessary to build from sources. Build-requires are private to the node that declares them, so they cannot be overridden from other nodes. 

- Moving build-requires to requires is not a good idea if they are real tools (like cmake). The opposite is also true, do not use build_requires for something that is not a tool (like a library, even if you want to hide it, or make it "private", this is not recommended)

- But build-requires can be overridden from the user profiles in ``[build_requires]`` section. This is the recommended way to go. And using profiles is the recommended approach for production anyway, please use your own profiles for production, and do not rely on the auto-detected "default" profile.

**Comment by barmaglot27** [comment] 2020-05-14 14:18
Hi, @memsharded, I was following [conan docs](https://docs.conan.io/en/latest/devtools/build_requires.html) that suggest to add testing framework in build_requires. It is our test framework based on Boost unit tests. Looks like build requirements cannot have dependencies intersecting with regular requires. Because the moment they do and there is a conflict - it cannot be resolved. That is why I was asking if it is possible to use requires to override build_requires.

**Comment by KepptnKool** [comment] 2020-05-25 13:07
I have a similar issue with autotools. Consider the following conanfile.txt
`
[requires]
zlib/1.2.11

[build_requires]
autoconf/[>=2.69 < 3]
automake/[>=1.16.1 < 2]
libtool/[>=2.4.6 < 3]
`

libtool has a dependency to automake/1.16.1. But the version range of automake resolves to 1.16.2 which results in a conflict.

The fact that build_requires are not resolved as normal requires greatly reduces the usefulness of the feature :-(.

**Comment by ohanar** [comment] 2020-10-23 17:51
This definitely seems like a bug to me (not simply a question). I just encountered this when upgrading the version of pcre we use, and running into a conflict with our build_require of swig, which still depends upon an older version of pcre. Right now there are two options to work around this:

- Downgrade our version of pcre to the version that swig uses
- Make swig a require, not build_require, and overriding pcre's version

Neither of these are the correct solution. The correct solution in this case is that swig uses a different version of pcre vs what we use -- i.e. build_requires should be an entirely independent graph and should have no relation to the requires graph.

Using split build and host profiles (at least on 1.30.2) gives the expected behavior. Unfortunately, I can't yet work in this world.

**Comment by memsharded** [comment] 2020-10-25 09:06
Thanks @ohanar for following up this issue.

Indeed, the new approach to specify a completely different graph, that will not collide with the main libraries graph is the "build" context, basically specifying a new ``build profile`` or ``build settings``, ``build options``, etc. This approach, however only works for tools that run in the build context, tools like test libraries still needs to be applied in the host context, which can be done with:

```python
def requirements(self):
      self.requires("testlib/0.1", force_host_context=True)
```
Packages in the build context only make visible environment like PATH env-var, but not things like include-dirs or libraries (as they wouldn't work, they wouldn't even exist in the host context)

The graph model will probably be one of the core changes in Conan 2.0, we will try to improve over these issues.

**Comment by vdsbenoit** [comment] 2022-04-20 16:16
Many of our projects CI went down after zlib package got upgraded to 1.2.12. I think the context was quite similar to this issue, except here we are not impacted by version ranges but by new a recipe revision.

Let's define this minimal example project : 

````python
class FooConan(ConanFile):
    tool_requires = [
        "doxygen/1.9.2"
    ]
    requires = [
        "libBar/1.0"
    ]
````

`doxygen` depends on `xapian-core`, which depends on `zlib`.
`libBar` depends on some other libs from Conan Center which depend on `zlib` too.

Until last week, everything worked, because every dependencies depended on `zlib/1.2.11`:
````
doxygen -> xapian-core -> zlib/1.2.11
libBar  -> someLib     -> zlib/1.2.11
````

However, `zlib/1.2.12` was recently introduced. Some packages from Conan-Center were re-built, with zlib/1.2.12 in their requirements while some other did not. Which led us to this situation:
````
doxygen -> xapian-core -> zlib/1.2.11
libBar  -> someLib     -> zlib/1.2.12
````

I would have liked to be able to override the build requirements in order to force using `zlib/1.2.12` with doxygen, but, as stated in this ticket, I could not. Therefore, I went the other way around and I overridden the requirements to keep on using `zlib/1.2.11`:

````python
class FooConan(ConanFile):
    tool_requires = [
        "doxygen/1.9.2",
    ]
    requires = [
        ("zlib/1.2.11@", "override"),
        "libBar/1.0"
    ]
````

@memsharded Is this the right way to do it?

Besides, how can we prevent our CI to go down due to recipe revision updates in the downstream libraries in the future? Are the lockfiles the only way to guarantee reproducible builds ? 

I submitted [a PR](https://github.com/conan-io/conan-center-index/pull/10399) to re-build `doxygen` with `zlib/1.2.12`. I also made one last week [about thrift](https://github.com/conan-io/conan-center-index/pull/10269) and I am worrying about needing to make more of them in the future. Do we need to make such kind of PRs on impacted project every time it happens? Could the impact of such rebuilds be assessed before they are performed ?

**Comment by vdsbenoit** [comment] 2022-05-09 13:14
**Edit:** Nevermind, I actually faced this issue because I had this option activated in the environment:
````bash
CONAN_ERROR_ON_OVERRIDE=1
````

---

I faced this issue again today with thrift & openssl:


<details><summary>Expand log</summary>

````bash
conan install thrift/0.13.0@ -s os=Windows -s arch=x86_64 -s compiler="Visual Studio" -s compiler.version=16
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

thrift/0.13.0: Not found in local cache, looking in remotes...
thrift/0.13.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.24k]
Downloading conanfile.py completed [11.35k]
Downloading conan_export.tgz completed [0.29k]
Decompressing conan_export.tgz completed [0.00k]
thrift/0.13.0: Downloaded recipe revision f8d3334fef75a9039a403c99ea447159
boost/1.78.0: Not found in local cache, looking in remotes...
boost/1.78.0: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.69k]
Downloading conanfile.py completed [78.97k]
Downloading conan_export.tgz completed [1.38k]
Decompressing conan_export.tgz completed [0.00k]
boost/1.78.0: Downloaded recipe revision 3bd922cb3ad6264e0c17586a8303310d
zlib/1.2.12: Not found in local cache, looking in remotes...
zlib/1.2.12: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.33k]
Downloading conanfile.py completed [5.11k]
Downloading conan_export.tgz completed [0.26k]
Decompressing conan_export.tgz completed [0.00k]
zlib/1.2.12: Downloaded recipe revision 82202701ea360c0863f1db5008067122
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.17k]
Downloading conanfile.py completed [4.42k]
Downloading conan_export.tgz completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
bzip2/1.0.8: Downloaded recipe revision b056f852bd2d5af96fc7171aadfd6c0b
openssl/1.1.1n: Not found in local cache, looking in remotes...
openssl/1.1.1n: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.18k]
Downloading conanfile.py completed [40.34k]
Downloading conan_export.tgz completed [0.29k]
Decompressing conan_export.tgz completed [0.00k]
openssl/1.1.1n: Downloaded recipe revision 2fd06475a9fcd0f93c6451c0cef16a67
libevent/2.1.12: Not found in local cache, looking in remotes...
libevent/2.1.12: Trying with 'conancenter'...
Downloading conanmanifest.txt completed [0.24k]
Downloading conanfile.py completed [6.15k]
Downloading conan_export.tgz completed [0.30k]
Decompressing conan_export.tgz completed [0.00k]
libevent/2.1.12: Downloaded recipe revision 8ebb6eed0fe94dae557f87906669e394
ERROR: libevent/2.1.12: requirement openssl/1.1.1m overridden by thrift/0.13.0 to openssl/1.1.1n
````
</details>

@memsharded @madebr what should we do in such a use case? (i.e. we do not have any power over the subdependencies)  

Overwriting the conflicting subdependency (e.g. openssl) in the `conanfile.py` of the top-level project is not an option. For instance, I want to run the CI on a commit I cannot edit. The `conan create` used to work but is not broken due to the the new openssl version and this conflict in thrift.

**Comment by leugenea** [comment] 2024-01-12 07:36
Just got the same issue but with `zlib/1.2.13` needed in direct requires (ex. `boost`) and `zlib/1.3` needed in `swig/4.1.0` in build-requires.

Moving `swig` into requires and forcing `zlib/1.2.13` explicitly fixed my problem but as @memsharded [mentioned](https://github.com/conan-io/conan/issues/7016#issuecomment-628591257) (about 4 years ago!) this is the wrong way to fix such problems.

**Comment by memsharded** [comment] 2024-01-19 08:25
I'd recommend to have a look to the new docs https://docs.conan.io/2/devops/using_conancenter.html

When using ConanCenter, new versions, changes, etc, can eventually provide some conflicts or have missing binaries. Now ConanCenter has started to use version-ranges, which means that new versions are used automatically if they fit in the ranges. So user recipes should use the same ranges if possible to avoid conflicts. Using lockfiles (they are way easier to manage in Conan 2.0) or working from your own copy of the packages (Conan 2.0 will soon be releasing more tools to manage this too) can provide immutable dependencies and way more robust builds.

**Comment by memsharded** [comment] 2024-10-06 21:52
Closing this as outdated, it seems that Conan 2 changed most of the things above.

Please create new tickets against Conan 2.X as necessary, thanks for your feedback.

**Closed as completed by memsharded** 2024-10-06 21:52 UTC
Labels: type: question
