### ISSUE TITLE
Environment variables not used in the test_package recipe

### ISSUE THREAD

**Issue by piponazo** [conan-io/conan#836] opened 2017-01-06 10:11 UTC
Hi!

I think I just discovered a bug/missing feature in the **conan test_package** command. When I use **conan test_package --env XXX=YYY** I can use that environment variable in the library recipe but not in the test_package one. 

Let's image the following scenario:

```
#recipe for library A
conan-A/conanfile.py
conan-A/test_package/conanfile.py
...
```

In both file I have some python code like this:

```
...
    def build(self):
        externals_path = os.getenv("EXTERNAL_DIR", "")
        if not externals_path:
            raise ConanException("You must provide an environment variable with the EXTERNAL_DIR path")
...
```

When conan is building the library, the EXTERNAL_DIR environment variable is used correctly. However when conan is trying to build the test_package recipe it throws the ConanException.

- Is this the expected behavior?
- Is there any way to use the env variable in the test_package?
- Could this feature be easily included if you did not think about it?

**Comment by memsharded** [comment] 2017-01-06 23:49
Yes, sounds like a bug, thanks for reporting!

**Comment by lasote** [comment] 2017-01-09 10:49
Will be available in minor version 0.18.1 (hopefully this week)

**Comment by memsharded** [comment] 2017-01-11 16:52
This fix has been released in 0.18.1, please update and re-open and report if necessary.

**Closed by memsharded** 2017-01-11 16:52 UTC
Labels: bug, fixed

**Comment by zomeck** [comment] 2017-01-23 10:45
Hi,
I have tried this in 0.18.1 if the getenv function is called from build works. However if it is called from imports I do not get it to work. 
Could it be that the bug is only fix for the build function?
Thanks

**Comment by memsharded** [comment] 2017-01-23 11:16
Hi @zomeck ,

Yes, I'd say that the environment variables are used only in build/package methods. So far, using them in the imports() method was not necessary. You might want to submit an issue with a feature request for that explaining your use case. Thanks!

**Comment by zomeck** [comment] 2017-01-23 11:30
Hi,
In my case I was trying to get some dlls I need only on run time for the test package. This is a temporary step I need to do until I migrate the full dependency tree to conan. Not sure that it is a very common use case.

**Comment by memsharded** [comment] 2017-01-23 12:50
Yes, that sounds like a good case, but that ``imports()`` would only be in the ``test_package/conanfile.py``, the question would be why do you need to condition the imports to some environment variables?

Thanks for your feedback!

**Comment by zomeck** [comment] 2017-01-23 16:27
I pass a path with the location of some dlls of a dependency in order to run the test application.
I don't want it to be a setting as these dlls might change location on different machines. As I said it is a temporary workaround until I can migrate everything to conan. If the intended behaviour is that imports does not know of the environment I can find another workaround :)

**Comment by memsharded** [comment] 2017-01-23 16:49
No, not really an "intended behavior", it is just that it was not requested before, so we always try to learn about the use cases, the reasons to do things... often there are underlying issues that have to be addressed besides the explicit "feature request".

I think that it is something that deserves to be considered, maybe it is easy to address it and it will help in the transition. Please go and open a new issue for a feature request for it. Thank you!
