### ISSUE TITLE
Windows command prompt buffers during conan test with Conan 1.18.0

### ISSUE THREAD

**Issue by brentd42** [conan-io/conan#5716] opened 2019-09-06 21:55 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

We're experiencing an issue with conan test under Windows beginning with Conan 1.18.0. We have a test_package recipe that invokes a utility to perform package validation. I believe the utility may use pipes for stdout I/O.  The utility executes the validation tests and runs for several minutes, writing test status and other diagnostic information to the console during execution.

Beginning with Conan 1.18.0, the Windows Command Prompt window now goes completely blank (with no scroll bar) and is non-responsive while the tests are executing. After completion of the tests, the buffered console output is displayed.

The issue appears to be the result of the #5190 "renames and moves"change to client/runner.py.  Specifically, an if statement changed from ...

``    if output is True and not log_filepath and self._log_run_to_output and not subprocess:``

... to ...

``    if (output is True and not self._output and not log_filepath and self._log_run_to_output
        and not subprocess):``

The new 'not self._output' clause evaluates to False (it's a ConanOutput object), so the if statement now evaluates to False and _self._simple_os_call()_ is no longer invoked. Rather, __self.pipe_os_call()_ is invoked instead resulting in the now somewhat annoying console  behavior.

Any suggestions?

**Comment by memsharded** [comment] 2019-09-08 22:46
Hi @brentd42 

It is true that some changes were done, so now only the ``self.pipe_os_call() `` is called always instead of the ``simple_os_call()``. We are having a look to what that means.

However, in the meantime, I have ran a small test, and even with the ``pipe_os_call()`` I can see continuous output of printed messages executed in the ``test_package()`` ``test()`` method. So the piping seems to be working ok. I tested it in Windows, which OS are you using? Could you please share how your calls looks like? A small reproducible example would help. Thanks!

**Comment by memsharded** [comment] 2023-12-30 23:21
This shouldn't be an issue anymore, closing as outdated

**Closed by memsharded** 2023-12-30 23:21 UTC
Labels: stage: triaging
