### ISSUE TITLE
Release version with Python 3.7 support

### ISSUE THREAD

**Issue by drrlvn** [conan-io/conan#3310] opened 2018-08-07 07:30 UTC
Latest Conan (1.6.1) requires PyYAML<3.13 which fails to install on Python 3.7. This was already fixed in #3251 but is not yet included in any release.

Please release a version (e.g. 1.6.2) with this fix included.

**Comment by memsharded** [comment] 2018-08-07 08:43
Thanks for the feedback. This is a duplicate of https://github.com/conan-io/conan/issues/3249.
As you commented, it has been fixed, and it will be released in next conan release. The only issue is that we need to setup our CI too to use Py3.7 properly. This is scheduled for next release 1.7 (later this month, we might consider doing a 1.6.2, but might be already too close to 1.7, please be patience. Thanks!)

**Closed** 2018-08-07 08:43 UTC
Labels: duplicate, fixed
