### ISSUE TITLE
conans.errors.ConanException: There was an error parsing conanbuildinfo.txt: path is on mount 'C:', start on mount 'D:'

### ISSUE THREAD

**Issue by pgrohs** [conan-io/conan#7792] opened 2020-10-02 07:33 UTC
My CI-Pipeline suddenly stops compiling my packages with the following error messages:

Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\conans\client\generators\text.py", line 163, in _loads_cpp_info
    _populate_cpp_info(dep_cpp_info, no_config_data, rootpath)
  File "C:\Python37-32\lib\site-packages\conans\client\generators\text.py", line 147, in _populate_cpp_info
    value = [os.path.relpath(it, _rootpath) for it in value]
  File "C:\Python37-32\lib\site-packages\conans\client\generators\text.py", line 147, in <listcomp>
    value = [os.path.relpath(it, _rootpath) for it in value]
  File "C:\Python37-32\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\conans\client\graph\graph_manager.py", line 409, in load_deps_info
    TXTGenerator.loads(load(info_file_path), filter_empty=True)
  File "C:\Python37-32\lib\site-packages\conans\client\generators\text.py", line 84, in loads
    deps_cpp_info = TXTGenerator._loads_cpp_info(deps_cpp_info_txt, filter_empty=filter_empty)
  File "C:\Python37-32\lib\site-packages\conans\client\generators\text.py", line 179, in _loads_cpp_info
    raise ConanException("There was an error parsing conanbuildinfo.txt: %s" % str(e))
conans.errors.ConanException: There was an error parsing conanbuildinfo.txt: path is on mount 'C:', start on mount 'D:'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./shared/conan/build.py", line 59, in <module>
    builder.run()
  File "C:\Python37-32\lib\site-packages\cpt\packager.py", line 594, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\Python37-32\lib\site-packages\cpt\packager.py", line 687, in run_builds
    r.run()
  File "C:\Python37-32\lib\site-packages\cpt\runner.py", line 134, in run
    lockfile=self._lockfile)
  File "C:\Python37-32\lib\site-packages\conans\client\conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "C:\Python37-32\lib\site-packages\conans\client\conan_api.py", line 378, in create
    test_build_folder, test_folder, conanfile_path, recorder=recorder)
  File "C:\Python37-32\lib\site-packages\conans\client\cmd\create.py", line 77, in create
    recorder=recorder)
  File "C:\Python37-32\lib\site-packages\conans\client\cmd\test.py", line 40, in install_build_and_test
    install_folder=test_build_folder, test=reference)
  File "C:\Python37-32\lib\site-packages\conans\client\cmd\build.py", line 22, in cmd_build
    deps_info_required=True, test=test)
  File "C:\Python37-32\lib\site-packages\conans\client\graph\graph_manager.py", line 105, in load_consumer_conanfile
    load_deps_info(info_folder, conanfile, required=deps_info_required)
  File "C:\Python37-32\lib\site-packages\conans\client\graph\graph_manager.py", line 423, in load_deps_info
    raise ConanException("Parse error in '%s' file in %s" % (BUILD_INFO, current_path))
conans.errors.ConanException: Parse error in 'conanbuildinfo.txt' file ...

I have updated conan to the most recent version 1.29.2. Can you please give me a hint what could be wrong?

**Comment by memsharded** [comment] 2020-10-02 09:57
This was changed in https://github.com/conan-io/conan/pull/7277, and relpaths break for code in different units.

Sounds it could be a regression, please @jgsogo have a look.

**Comment by jgsogo** [comment] 2020-10-02 10:57
Hi @pgrohs ! I've reproduced the error in https://github.com/conan-io/conan/pull/7794

The root cause of the error is that you are using an absolute path in some `cpp_info` attribute. This is quite unexpected on our side because it means that every consumer of the package needs that absolute path to exist (or be accessible) in their machine to consume the package. I understand this can be a common scenario in a company setup, where some dependencies are shared among all the developers in a remote unit, just wanted to point this out as a friendly reminder in case you can fix the recipe and use only relative directories.

Once the tests pass, we will add this patch to the required releases.

Thanks!

**Comment by jgsogo** [comment] 2020-10-02 16:20
Hi, @pgrohs , this is going to be released in version `1.30` (today/tomorrow), will you be able to upgrade or do you need `1.29.3` release?

**Comment by pgrohs** [comment] 2020-10-04 17:35
@jgsogo Thank you for the quick fix! I can upgrade to conan 1.30 as soon as it is released.

**Comment by memsharded** [comment] 2020-10-04 18:16
> @jgsogo Thank you for the quick fix! I can upgrade to conan 1.30 as soon as it is released.

Conan 1.30 due tomorrow, if no last minute issues :)

**Comment by jgsogo** [comment] 2020-10-05 09:54
Fixed in https://github.com/conan-io/conan/pull/7797, to be released in `1.30`

**Closed as completed by jgsogo** 2020-10-05 09:54 UTC
Labels: stage: triaging
