### ISSUE TITLE
[question] self.package_folder different from build() to package() step ?

### ISSUE THREAD

**Issue by selim-pousse** [conan-io/conan#13722] opened 2023-04-19 12:33 UTC
### What is your question?

Using conan 2.0.3, why the value of self.package_folder are different from build() step to package step() ?
I expected to get the same value of self.package_folder when both build() or package() functions are invoked.

### **step 1**:  conan install + build ...

```python 
  def layout(self):
    self.folders.root = ".."
    self.folders.source = "."
    self.folders.build = ".conan/build"

  def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    print(self.package_folder)
```
    
```
======== Calling build() ========
conanfile.py (myLib/4.6.1@pis/beta): Running CMake.configure()
conanfile.py (myLib/4.6.1@pis/beta): RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/home/conan/myLib/4.5.x/.conan/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/conan/myLib/4.5.x" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/conan/myLib/4.5.x/."
=> printf return **/home/user/myLib/4.5.x/.conan/build**
```

### **step 2**: conan export-pkg ...
```python
  def package(self):
    cmake = CMake(self)
    cmake.install()
    print(self.package_folder)
```
```
======== Calling package() ========
conanfile.py (myLib/4.6.1@pis/beta): Running CMake.install()
conanfile.py (myLib/4.6.1@pis/beta): RUN: cmake --install "/home/conan/myLib/4.5.x/.conan/build" --prefix "/home/user/.conan2/p/t/oseli976a55c658b4d/p"
=> printf return /home/conan/.conan2/p/t/oseli976a55c658b4d/p
```

Because of that, CMAKE_INSTALL_PREFIX is set to **/home/user/myLib/4.5.x**
I doesn't make sense for me. It shouldn't have been set to '**/home/conan/.conan2/p/t/oseli976a55c658b4d/p**'  ?

Thank for your help.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-04-19 12:48
Hi @selim-pousse 

Did you mean the ``conan build`` command? (that is different than when executing the ``build()`` method, when this runs in the cache).

When you are running ``conan build .``, this is a local command. There is no ``package_folder`` at all, because the thing is not a package yet.

Could you please provide a full ``conanfile.py`` to reproduce, and the exact Conan commands to run? Thanks!

**Comment by selim-pousse** [comment] 2023-04-19 14:40
Hi @memsharded ,

sorry for the mistake. I mean `conan build`.

Conan comand sequence:
1) `conan install /home/conan/mylib/4.5.x/.conan -o 'mybase-headers/*:header_only=True' --user pis --channel beta -pr:h aarch64-linux-gnu -pr:b x86_64-linux-musl --build missing`
2) `conan build /home/conan/mylib/4.5.x/.conan -o 'mybase-headers/*:header_only=True' --user pis --channel beta -pr:h aarch64-linux-gnu -pr:b x86_64-linux-musl`
3) `conan export-pkg -o 'mybase-headers/*:header_only=True' --user pis --channel beta /home/conan/myLib/4.5.x/.conan -pr:h aarch64-linux-gnu -pr:b x86_64-linux-musl`

Conanfile;
```python
import os
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake, cmake_layout
from conan.tools.files import copy, load
from datetime import datetime

required_conan_version = ">=2.0.0"

class MyLib(ConanFile):
  alias           = 'myLib'
  version         = "4.6.1"         # <--- set only here the Library's version !!!
  default_user    = "pis"
  default_channel = "stable"

  settings        = "os", "compiler", "build_type", "arch"
  options         = {
                      "shared": [True, False], 
                      "fPIC": [True, False], 
                      "pkg_variety": [None, "common"],
                      "hw_role": [None, "CCU", "PSC", "RAMP"]
                    }
  default_options = {"shared": True, "fPIC": True, "pkg_variety": None, "hw_role": None}
  build_policy    = "missing"

  def requirements(self):
    self.requires(f"mybase-headers/3.0.0@{self.user}/{self.channel}")

  def generate(self):
    # This generates "conan_toolchain.cmake" in self.generators_folder
    tc = CMakeToolchain(self)
    tc.variables["BUILD_TOOL"] = "CONAN"
    tc.generate()
    # This generates "ofris3-headers-config.cmake" in self.generators_folder
    deps = CMakeDeps(self)
    deps.check_components_exist = True
    deps.generate()


  def layout(self):
    # The root of the project is one level above
    self.folders.root = ".."
    # The source of the project (the root CMakeLists.txt) is the source folder
    self.folders.source = "."
    self.folders.build = ".conan/build"
    self.folders.generators = f"{self.folders.build}/generators"
  
  def export_sources(self):
    # must me exported if source isn't in the recipe folder
    copy(self, "*",       f"{self.recipe_folder}/..", self.export_sources_folder)

  def set_name(self):
    self.name = str(f"{self.alias}").lower()

  def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    print (self.package_folder)

  def package(self):
    cmake = CMake(self)
    cmake.install()
    print (self.package_folder)

  def package_info(self):
    self.cpp_info.libs = ["lib1", "lib2"]
```

**Comment by selim-pousse** [comment] 2023-04-19 14:54
**Approach 1**: `conan build `+ `conan export-pkg` 
my main trouble is that the resulting value of `CMAKE_INSTALL_PREFIX` is pointing to the wrong path, how to prevent it or control it via conan if i use the approach `conan build `+ `conan export-pkg` ? 

Log of resulting cmake comand during CMake.configure(): 
_cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/home/conan/myLib/4.5.x/.conan/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/conan/myLib/4.5.x" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/conan/myLib/4.5.x/."_



**Approach 2** : `conan create`
the approach `conan create`  (without comand `conan build + export-pkg`) works fine as expected since all my final binaries are copied on the right place of `CMAKE_INSTALL_PREFIX=/home/user/.conan2/p/t/oseli0ef8509985e65/p`.
FYI, conan comand of approach 2 :
1) `conan install /home/conan/mylib/4.5.x/.conan -o 'mybase-headers/*:header_only=True' --user pis --channel beta -pr:h aarch64-linux-gnu -pr:b x86_64-linux-musl --build missing`
2) `conan create /home/conan/mylib/4.5.x/.conan -o 'mybase-headers/*:header_only=True' --user pis --channel beta -pr:h aarch64-linux-gnu -pr:b x86_64-linux-musl`

Log of resulting cmake comand during CMake.configure(): 
_cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/home/user/.conan2/p/t/oseli8ed2cecd0a5c8/b/.conan/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/user/.conan2/p/t/oseli8ed2cecd0a5c8/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/user/.conan2/p/t/oseli8ed2cecd0a5c8/b/."_

**Comment by memsharded** [comment] 2023-04-19 22:29
Some general feedback:

- Very important: You cannot use the ``alias = xxx`` as an alias for the name. The word ``alias`` has some specific meaning to Conan. As a general rule your own attributes and methods should start with ``_``. (https://docs.conan.io/2/knowledge/guidelines.html)
- I understand that the first ``conan install`` is not necessary, as the ``conan build`` in the second step will already include that automatically.
- ``default_user``, ``default_channel`` no longer exist in 2.0. You can use ``user=`` and ``channel=`` directly in recipes
- Recall that it is not possible to use channels in 2.0 to do promotions, and thus calling something ``beta`` in the channel is probably not the best approach. It is not intended to depend on one package that has channel=beta, then change it and depend on the same channel as ``stable``. In general it is better to just forget about the channel completely (it is not mandatory in 2.0)
- ``build_policy    = "missing"`` is not recommended in general, except for some very special packages. In general, the command line `--build=missing`` should be used.

**Comment by memsharded** [comment] 2023-04-19 22:36
Regarding the issue, thanks for the detailed feedback.

It is true that in the ``build()`` method in ``conan build`` the ``package_folder`` is pointing to local folder, not to the cache. This is expected, because there is no package folder yet, it doesn't exist at all. It is not possible to point it to anywhere else, the information to do that doesn't exist. So when the conan build runs:
```
conanfile.py (pkg/0.1): Running CMake.build()
conanfile.py (pkg/0.1): RUN: cmake --build "C:\Users\memsharded\test_conan\build" --config Release
MSBuild version 17.3.1+2badb37d1 for .NET Framework
  Checking Build System
  Building Custom Rule C:/Users/memsharded/test_conan/CMakeLists.txt
  pkg.cpp
  pkg.vcxproj -> C:\Users\memsharded\test_conan\build\Release\pkg.lib
  Building Custom Rule C:/Users/memsharded/test_conan/CMakeLists.txt

FOLDER: C:\Users\memsharded\kk
```
At this stage nothing different can be done.
When ``conan export-pkg`` runs, it is able to correctly define the package_folder, so everything works:
```
conanfile.py (pkg/0.1): RUN: cmake --install "C:\Users\memsharded\test_conan\build" --config Release --prefix "C:/Users/memsharded/.conan2/p/t/pkg50cebe37c6c33/p"
-- Installing: C:/Users/memsharded/.conan2/p/t/pkg50cebe37c6c33/p/lib/pkg.lib
-- Installing: C:/Users/memsharded/.conan2/p/t/pkg50cebe37c6c33/p/include/pkg.h

FOLDER: C:\Users\memsharded\.conan2\p\t\pkg50cebe37c6c33\p
```

So yes, the package_folder is different in both stages, because of definition and scope of each stage, but this is expected, things are working correctly.

When the package is ``build()`` in the cache while ``conan create``, the package is already inside the cache, it knows where it is, it has an existing valid reference (recipe name, version, user, channel and recipe-revision), a valid ``package_id``, etc, things that don't exist at ``conan build`` step. So the ``package_folder`` there will be pointing to a folder inside the cache, this is expected too.

Does this clarify the behavior? Thanks!

**Comment by selim-pousse** [comment] 2023-04-20 04:15
First thank for your feedbacks and to take the time to clarify my errors in detail.

Regarding your statement "_When conan export-pkg runs, it is able to correctly define the package_folder, so everything works:_", I'm not sure that is enough for the approach 1 ..

As mentioned before the `CMAKE_INSTALL_PREFIX` is set during the build() step, more precisely during the cmake.configure(), and cannot be changed later on the package() step by calling again cmake.configure() otherwise I'll get a error due to the 2nd change of the `RPATH`.

here are the log detail of my usecase :
```
conanfile.py (mylib/4.6.1@pis/beta): RUN: cmake --install "/home/conan/myLib/4.5.x/.conan/build" --prefix "/home/user/.conan2/p/t/oseli1f9fa4c20217f/p"
-- Installing: /home/user/.conan2/p/t/oseli1f9fa4c20217f/p/lib/libmtrace.so
-- Installing: /home/user/.conan2/p/t/oseli1f9fa4c20217f/p/bin/lnh
-- Installing: /home/user/.conan2/p/t/oseli1f9fa4c20217f/p/bin/debug_shell
-- Creating symlinks monitor_cmd  /home/conan/myLib/4.5.x/bin/run,pglist,pgkill 
CMake Error: failed to create symbolic link '/home/conan/myLib/4.5.x/bin/run': No such file or directory
CMake Error: failed to create symbolic link '/home/conan/myLib/4.5.x/bin/pglist': No such file or directory
CMake Error: failed to create symbolic link '/home/conan/myLib/4.5.x/bin/pgkill': No such file or directory
```

As you can see, each time I use the variable `CMAKE_INSTALL_PREFIX` in my CMakeLists.txt, I get an error.  
So in order to correct my issue, I should either create 2 different recipes for each approach (1 & 2), or either readjust all my cmakefiles to not use the variable `CMAKE_INSTALL_PREFIX `for the approach 1, but I'm not sure that is the right direction ?

**Comment by memsharded** [comment] 2023-04-20 09:35
> So in order to correct my issue, I should either create 2 different recipes for each approach (1 & 2), or either readjust all my cmakefiles to not use the variable CMAKE_INSTALL_PREFIX for the approach 1, but I'm not sure that is the right direction ?

It is actually the second approach. It is not possible to depend on CMAKE_INSTALL_PREFIX, (or the final "installation path" in general even for other build systems) when building binaries that are going to be distributed to other machines. Because the binaries must be relocatable, they cannot hardcode in the executables or binaries a specific absolute path location, otherwise when the packages are uploaded to a server and are ``conan install`` installed by another user, that will be in another folder/location, and the binaries won't work. And depending on the CMAKE_INSTALL_PREFIX for the actual build of the binaries is doing exactly that. That value should only be used to do the final "copy" of the artifacts to the final location, but not for the binary building itself, and this is the reason why ``package()`` method works, by defining the new CMAKE_INSTALL_PREFIX, cmake is able to do the right copy.

This is similar as relying only on absolute RPATHs to work, this is not possible for a package manager distributing binaries, so RPATHs must be relative or other strategies like LD_LIBRARY_PATH are necessary.

**Comment by selim-pousse** [comment] 2023-04-21 03:52
That is clear, thank again for your help. 👍

**Comment by memsharded** [comment] 2023-04-21 08:05
Great, I am closing this ticket as solved, but don't hesitate to re-open or create new tickets for any further question. Thanks!

**Closed as completed by memsharded** 2023-04-21 08:05 UTC
Labels: stage: triaging
