### ISSUE TITLE
502 Bad Gateway when attempting to upload packages with versions that start with "0.0."

### ISSUE THREAD

**Issue by smspillaz** [conan-io/conan#286] opened 2016-05-30 01:22 UTC
I've noticed that there doesn't seem to be a problem when I upload a version called "master", but when I do this:

     $ conan upload tooling-cmake-util/0.0.13@smspillaz/tooling-cmake-util

I get:
```
ERROR: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by memsharded** [comment] 2016-05-30 02:29
I would say that it has nothing to do with the name, but that just by chance, it is failing due to some misbehaviour in the load balancer that was recently introduced to scale-out conan (http://blog.conan.io/2016/05/23/Scaling-out-conan.io.html). Please @lasote, could you check it?

**Comment by smspillaz** [comment] 2016-05-30 02:39
@memsharded It would seem like an odd coincidence to me. Every upload I've done under that name has failed and every upload under master has succeeded. Thanks for looking into it though 👍

**Comment by memsharded** [comment] 2016-05-30 02:56
Sure will take it into account, but odd coincidences happen :), maybe rules of balancer are url based? will check it, thanks!

**Comment by smspillaz** [comment] 2016-05-30 03:06
@memsharded Sounds like it could be that

**Comment by memsharded** [comment] 2016-05-30 05:59
The service should work now. Still don't know the issue, but should be working. Please tell otherwise, thanks!

**Comment by smspillaz** [comment] 2016-05-30 06:14
@memsharded Thanks - I'll re-run the offending build and let you know.

**Comment by smspillaz** [comment] 2016-05-30 06:33
@memsharded Seems to be fixed. Thanks!

**Comment by smspillaz** [comment] 2016-05-30 06:35
@memsharded By the way - is there an IRC, gitter or slack channel for Conan? I think this would be really beneficial to the community.

**Comment by memsharded** [comment] 2016-05-30 06:40
Nop, but I think this is a good moment to start it. I am doing a quick survey in twitter, to check the preferred way.

**Comment by smspillaz** [comment] 2016-05-30 08:31
Hum, okay this seems to have broken again.

**Comment by memsharded** [comment] 2016-05-31 07:22
Ok, please try again when possible, apparently it is fixed and should work now.

**Comment by memsharded** [comment] 2016-06-01 01:02
@smspillaz About the channel (gitter, IRC...) to communicate with the community, the quick twitter survey said 70% would like github issues. IRC would be the next with 20%. We also were not aware about the "conan" tag in stackoverflow. I'd say that with those results there is still not critical mass for an IRC channel, and github+twitter+email+SO should be fine for the moment. 
But I am not opinionated, and this cannot harm, so if you still think an IRC channel is worth, we could open it an try, time will say. What do you think?

**Comment by smspillaz** [comment] 2016-06-01 08:46
Sounds good to me! #conan on freenode?

**Comment by memsharded** [comment] 2016-06-06 06:40
This has been working fine for the last days without problems after the latest server updates. I am closing it by now, please re-open if necessary

**Comment by theirix** [comment] 2016-07-09 08:13
Hello, @memsharded . It seems error 502 is back. This morning uploads from my travis jobs failed multiple times. Is there any rate limiter for heavy travis jobs?
```
Uploading jsoncpp/1.7.3@theirix/stable
ERROR: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by memsharded** [comment] 2016-07-09 08:57
Sorry for that. No, they shouldn't fail. Are they failing all of them or just some of the uploads?

**Comment by memsharded** [comment] 2016-07-09 11:00
Systems are working again. We need to spend even more time tracking down these problems in the servers. Thanks very much for reporting!

**Comment by theirix** [comment] 2016-07-09 11:02
Great, thank you too for quick response!

**Comment by arnemertz** [comment] 2016-07-21 07:02
Getting 502 since yesterday. I managed to upload a package once, remove it again, and after that always Bad Gateway. Tried to upload the same package.

```
~ $ conan search -v
...
nlJson/2.0.1@arnemertz/testing
    Package_ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
            ()
 ~ $ conan upload nlJson/2.0.1@arnemertz/testing -r conan.io
ERROR: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

**Comment by lasote** [comment] 2016-07-21 07:37
That's strange. Systems are ok and I'm able to upload packages...

**Comment by lasote** [comment] 2016-07-21 07:39
Could you try one more time now? I've restarted all services.

**Comment by arnemertz** [comment] 2016-07-21 07:39
The package is header-only and therefore has en empty settings list - could that be an issue? The one time I managed to upload it, it had the usual settings list. I'll try with settings list again.

**Comment by lasote** [comment] 2016-07-21 07:41
I don't think so, The problem is related with the connectivity of the load balancer (nginx) and the application instances. Not an conan app issue (I think)...

**Comment by arnemertz** [comment] 2016-07-21 08:19
Upload worked this time, with the empty settings

**Closed** 2016-07-21 08:22 UTC

**Comment by theirix** [comment] 2016-08-12 10:46
Gateway started failing again with the message "502 Bad Gateway".
For example, check several jobs in a last hour: https://travis-ci.org/theirix/conan-libbson

**Comment by memsharded** [comment] 2016-08-12 14:51
We have checked them and the systems are fine, sorry for the inconvenience. Conan.io is using Amazon AWS S3 storage, with transfers (both uploads and downloads) managed directly by amazon S3. It happens that S3 sometimes fails too, we have tried to improve it, but it is out of our control. As a quick solution, please relaunch those jobs (only those jobs, fortunately travis-ci allows to do that, it is worse when something fails with appveyor, that the full build has to be relaunched. Thanks for your feedback and your patience!

**Comment by theirix** [comment] 2016-08-12 15:20
Thank you, it works now. Situation with S3 clarifies it.
