### ISSUE TITLE
Generated Find modules for CMake inappropriately use find_dependency()

### ISSUE THREAD

**Issue by glennaycock** [conan-io/conan#7248] opened 2020-06-24 22:06 UTC
I have an existing CMake/Qt application, so I am trying to integrate Conan libraries transparently, using conan_paths.

find_package( Qt5 CONFIG ... REQUIRED) doesn't satisfy some of the other transitive dependencies, so I added find_package( qt 5 MODULE REQUIRED), which works on Linux.

However, I'm getting some strange behavior on Windows (missing Qt's transitive dependencies). The same configuration works for Linux.

I previously had issues with package name case collisions on Windows.

Upon digging into the generated Find module, I found calls to find_dependency() for each of Qt's (qt::qt) transitive dependencies. According to [CMake docs](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html), this is unsuitable for Find Modules due to the call to return().

Can anyone verify that Conan's use of find_dependency in Find modules actually works correctly?

**Comment by jgsogo** [comment] 2020-06-25 08:03
Hi, @glennaycock 

We are working really hard to provide transparent CMake integration for existing projects. There are some flaws yet, but it is looking very promising (last feature added, the _toolchain_, will supersede usage of `conan_basic_setup()`). Nevertheless, in order for this transparent integration to work you need to use the CMake files generated by Conan that provide the proper targets with all the transitive requirements (using `cmake_find_package` or `cmake_find_package_multi` generator).

A recipe for `Qt` is currently under development by the community (https://github.com/conan-io/conan-center-index/pull/1759). Which one are you using right now? Maybe you should open an issue related to that recipe if something is broken, or the recipe authors can give you more information about how to use it.

`find_dependency()` inside our `FindXXXX.cmake` files has been working without any issue so far. Our files try to look only dependencies that are also part of the Conan graph, so their files are generated all together and the dependencies are always found (if not, this is a bug in Conan, something wrong happened before that stage).

Were you using Conan with the provided CMake's generators and the files generated by Conan? Can you share a step-by-step so we can reproduce the issue? 

Thanks!

**Comment by glennaycock** [comment] 2020-06-25 13:42
Javier,

I am using the CMake toolchain (via conan_paths) and cmake_find_package generators. I briefly attempted to use multi-configuration packages, but it seems some of the dependencies didn't support it. I also have some custom packages which would have to updated, so I am focusing on getting it work in single-config mode first.

I am using the Bincrafters Qt recipe for version 5.12.3 (legacy app), which I have modified to enable all the features that I need, and I am using a combination of custom and Conan-generated Find modules.

It's only when CMake tries to configure linking (on Windows) that the missing transitive targets cause the problem (see below):

> CMake Error at CMake/_sanitized_.cmake:218 (add_library):
>   Target "_sanitized_" links to target "**freetype::freetype**" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> Call Stack (most recent call first):
>  _sanitized_
>
> CMake Error at CMake/_sanitized_.cmake:218 (add_library):
>   Target "_sanitized_" links to target "**harfbuzz::harfbuzz**" but the target was
>   not found.  Perhaps a find_package() call is missing for an IMPORTED
>   target, or an ALIAS target is missing?
> Call Stack (most recent call first):
> _sanitized_
>
> CMake Error at CMake/_sanitized_.cmake:218 (add_library):
>   Target "_sanitized_" links to target "**JPEG::JPEG**" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> Call Stack (most recent call first):
>   _sanitized_
> 
> CMake Error at CMake/_sanitized_.cmake:218 (add_library):
>   Target "_sanitized_" links to target "**PNG::PNG**" but the target was not found.
>   Perhaps a find_package() call is missing for an IMPORTED target, or an
>   ALIAS target is missing?
> Call Stack (most recent call first):
>   _sanitized_
> 
> CMake Error at CMake/_sanitized_.cmake:218 (add_library):
>   Target "_sanitized_" links to target "**sqlite3::sqlite3**" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> Call Stack (most recent call first):
>   _sanitized_
> 
> CMake Error at CMake/_sanitized_.cmake:218 (add_library):
>   Target "_sanitized_" links to target "**odbc::odbc**" but the target was not
>   found.  Perhaps a find_package() call is missing for an IMPORTED target, or
>   an ALIAS target is missing?
> Call Stack (most recent call first):
>   _sanitized_

As this existing application is rather complex and I cannot share, I will try to duplicate the issue in a sample project. I built two other third-party packages that required Qt (QMake build, not CMake) without any problems.

**Comment by glennaycock** [comment] 2020-06-25 15:41
I isolated the problem to one of my custom packages. I will update results asap.

**Comment by glennaycock** [comment] 2020-06-25 20:45
@jgsogo 

Javier,

The problem is that the Conan-generated Findqt.cmake script contains the following to resolve Qt's transitive dependencies:

> # Library dependencies
>         include(CMakeFindDependencyMacro)
> 
>         if(NOT zlib_FOUND)
>             find_dependency(zlib REQUIRED)
>         else()
>             message(STATUS "Dependency zlib already found")
>         endif()
> 
> 
>         if(NOT bzip2_FOUND)
>             find_dependency(bzip2 REQUIRED)
>         else()
>             message(STATUS "Dependency bzip2 already found")
>         endif()
> 
> 
>         if(NOT OpenSSL_FOUND)
>             find_dependency(OpenSSL REQUIRED)
>         else()
>             message(STATUS "Dependency OpenSSL already found")
>         endif()
> 
> 
>         if(NOT pcre2_FOUND)
>             find_dependency(pcre2 REQUIRED)
>         else()
>             message(STATUS "Dependency pcre2 already found")
>         endif()
> 
> 
>         if(NOT double-conversion_FOUND)
>             find_dependency(double-conversion REQUIRED)
>         else()
>             message(STATUS "Dependency double-conversion already found")
>         endif()
> 
> 
>         if(NOT freetype_FOUND)
>             find_dependency(freetype REQUIRED)
>         else()
>             message(STATUS "Dependency freetype already found")
>         endif()
> 
> 
>         if(NOT harfbuzz_FOUND)
>             find_dependency(harfbuzz REQUIRED)
>         else()
>             message(STATUS "Dependency harfbuzz already found")
>         endif()
> 
> 
>         if(NOT JPEG_FOUND)
>             find_dependency(JPEG REQUIRED)
>         else()
>             message(STATUS "Dependency JPEG already found")
>         endif()
> 
> 
>         if(NOT PNG_FOUND)
>             find_dependency(PNG REQUIRED)
>         else()
>             message(STATUS "Dependency PNG already found")
>         endif()
> 
> 
>         if(NOT sqlite3_FOUND)
>             find_dependency(sqlite3 REQUIRED)
>         else()
>             message(STATUS "Dependency sqlite3 already found")
>         endif()
> 
> 
>         if(NOT odbc_FOUND)
>             find_dependency(odbc REQUIRED)
>         else()
>             message(STATUS "Dependency odbc already found")
>         endif()

The FindXXX modules generated for my custom packages do not include those, and I am unable to determine how that is generated automatically for Qt (only).

I was able to emulate the behavior in the CMake for my test app. The test files are attached, but you will have problems with my customized package recipes for Qt, Qwt, and PythonQt, which haven't been publicly published.

[conan_qt_test.zip](https://github.com/conan-io/conan/files/4833714/conan_qt_test.zip)

**Comment by jgsogo** [comment] 2020-06-26 07:19
Sorry but I don't see where the problem is. It is **more** or less standard that every `FindXXX` should populate the `xxxx_FOUND`: https://cmake.org/cmake/help/v3.3/module/FindPackageHandleStandardArgs.html. If you are using some custom `FindXXX` files for some dependencies, ensure that they are using that convention.

I need more information about:
> The FindXXX modules generated for my custom packages do not include those, and I am unable to determine how that is generated automatically for Qt (only).

 * Which are those custom packages? Are they `odbc`, `sqlite3`,...?
 * If you install the Conan Qt recipe (or a consumer) using `cmake_find_package` generator, Conan will generate `FindXXXX.cmake` files for each one of the dependencies. How are you consuming Qt recipe? Where are those files? Does CMake find generated `FindXXXX` files?

**Comment by glennaycock** [comment] 2020-06-26 18:27
@jgsogo 

Yes, Conan generates FindXXXX.cmake files for all the dependencies, including my custom packages. However, the difference is that **_ one package (PythonQt) doesn't have the find_dependency() statements as above._**

I've removed my package as a dependency for now.

**Comment by memsharded** [comment] 2023-08-25 10:44
This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!

**Closed as not planned by memsharded** 2023-08-25 10:44 UTC
Labels: stage: triaging
