### ISSUE TITLE
recipes not updating

### ISSUE THREAD

**Issue by KoHcoJlb** [conan-io/conan#2104] opened 2017-12-03 02:11 UTC
Is it a bug or a feature that if I update recipe in remote repository it's not updated in local cache when I run conan install.
What is better approach to do this if I don't want to change version because library itself not changed.

**Comment by petermbauer** [comment] 2017-12-03 02:22
there is conan install --update

**Comment by memsharded** [comment] 2017-12-03 21:08
It is a feature, it is by design. As @petermbauer points out, a ``conan install --update`` checks updates from remote repository (it is also slower than a normal ``conan install``)

**Comment by KoHcoJlb** [comment] 2017-12-04 01:12
Thanks for the help.

**Comment by lasote** [comment] 2017-12-04 08:39
I'm closing the issue but any other question or anything else, please, feel free to write again!

**Closed by lasote** 2017-12-04 08:39 UTC
Labels: question
