### ISSUE TITLE
[bug] (msvc protobuf) CMakeDeps references debug libs during release build 

### ISSUE THREAD

**Issue by PeteAudinate** [conan-io/conan#11884] opened 2022-08-16 13:06 UTC
We've started seeing this issue since 1.51.0, earlier versions work fine.

We're using VS2019 with CMakeDeps and a dependency on protobuf. Here's a minimal example showing the issue: [protobuf_test.zip](https://github.com/conan-io/conan/files/9351156/protobuf_test.zip)

We install Conan dependencies for both Release and Debug, then do a Release build:
```
mkdir build
cd build
conan.exe install ..
conan.exe install .. -s build_type=Debug
cmake .. -G 'Visual Studio 16 2019' -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
cmake --build . --config Release
```

This fails with:
```
libprotobufd.lib(arenastring.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in test_package.obj [C:\Users\Pete\projectsw\protobuf_t
est\build\test_package.vcxproj]
libprotobufd.lib(arenastring.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in test_package.obj [C:\Users\P
ete\projectsw\protobuf_test\build\test_package.vcxproj]
```

Looking at the files generated by CMakeDeps, this command seems to unconditionally add the debug library target to protobuf::libprotobuf:
```
set_property(TARGET protobuf::libprotobuf
             PROPERTY INTERFACE_LINK_LIBRARIES
             $<$<CONFIG:Debug>:${protobuf_protobuf_libprotobuf_OBJECTS_DEBUG}>
             ${protobuf_protobuf_libprotobuf_LIBRARIES_TARGETS}
             $<$<CONFIG:Debug>:${protobuf_protobuf_libprotobuf_DEPENDENCIES_DEBUG}>
             $<$<CONFIG:Debug>:${protobuf_protobuf_libprotobuf_FRAMEWORKS_FOUND_DEBUG}>
             $<$<CONFIG:Debug>:${protobuf_protobuf_libprotobuf_SYSTEM_LIBS_DEBUG}>
             APPEND)
```
Perhaps this command is missing a `$<$<CONFIG:Debug> ... >` on the `protobuf_protobuf_libprotobuf_LIBRARIES_TARGETS` line? Otherwise what's to stop it being used for a Release build?

(Adding that `$<$<CONFIG:Debug> ... >`  does seem to fix the problem).

### Environment Details (include every applicable attribute)
  * Operating System+version: Win 11
  * Compiler+version: VS 2019
  * Conan version: 1.51.0 and later
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
Using:[protobuf_test.zip](https://github.com/conan-io/conan/files/9351156/protobuf_test.zip)
```
mkdir build
cd build
conan.exe install ..
conan.exe install .. -s build_type=Debug
cmake .. -G 'Visual Studio 16 2019' -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
cmake --build . --config Release
```
### Logs (Executed commands with output) (Include/Attach if Applicable)
```

$ conan.exe install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    protobuf/3.20.0 from 'conancenter' - Cache
    zlib/1.2.12 from 'conancenter' - Cache
Packages
    protobuf/3.20.0:6b251a3d67c612ea01b0038b4c794e87a3c4fd88 - Cache
    zlib/1.2.12:3fb49604f9c2f729b85ba3115852006824e72cab - Cache

Installing (downloading, building) binaries...
zlib/1.2.12: Already installed!
protobuf/3.20.0: Already installed!
protobuf/3.20.0: Appending PATH environment variable: C:\.conan\cd71a8\1\bin
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

$ conan.exe install .. -s build_type=Debug
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.runtime=MDd
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    protobuf/3.20.0 from 'conancenter' - Cache
    zlib/1.2.12 from 'conancenter' - Cache
Packages
    protobuf/3.20.0:2c92c32af71324f0143d3738c61b80db04fc702a - Cache
    zlib/1.2.12:d057732059ea44a47760900cb5e4855d2bea8714 - Cache

Installing (downloading, building) binaries...
zlib/1.2.12: Already installed!
protobuf/3.20.0: Already installed!
protobuf/3.20.0: Appending PATH environment variable: C:\.conan\a579f3\1\bin
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.txt: Generator 'CMakeToolchain' calling 'generate()'
conanfile.txt: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.txt: Generator 'CMakeDeps' calling 'generate()'
conanfile.txt: Aggregating env generators
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo

$ cmake .. -G 'Visual Studio 16 2019' -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
-- Using Conan toolchain: C:/Users/Pete/projectsw/protobuf_test/build/conan_toolchain.cmake
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30142.1
-- The CXX compiler identification is MSVC 19.29.30142.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'protobuf::libprotobuf'
-- Conan: Component target declared 'protobuf::libprotoc'
-- Conan: Target declared 'protobuf::protobuf'
-- Conan: Target declared 'ZLIB::ZLIB'
-- Conan: Including build module from 'C:/.conan/cd71a8/1/lib/cmake/protobuf/protobuf-generate.cmake'
-- Conan: Including build module from 'C:/.conan/cd71a8/1/lib/cmake/protobuf/protobuf-module.cmake'
-- Conan: Including build module from 'C:/.conan/cd71a8/1/lib/cmake/protobuf/protobuf-options.cmake'
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Pete/projectsw/protobuf_test/build

$ cmake --build . --config Release
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Running cpp protocol buffer compiler on addressbook.proto
  Building Custom Rule C:/Users/Pete/projectsw/protobuf_test/CMakeLists.txt
  test_package.cpp
  addressbook.pb.cc
libprotobufd.lib(arenastring.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in test_package.obj [C:\Users\Pete\projectsw\protobuf_t
est\build\test_package.vcxproj]
libprotobufd.lib(arenastring.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in test_package.obj [C:\Users\P
ete\projectsw\protobuf_test\build\test_package.vcxproj]
```

**Comment by jcar87** [comment] 2022-08-17 08:07
Hi @PeteAudinate  - thanks so much for the bug report and the detailed description and diagnosis.

I believe this is a duplicate of https://github.com/conan-io/conan/issues/11852 - A fix has been identified along the lines of what you have observed, and will be part of the upcoming 1.51.3 release.

**Comment by PeteAudinate** [comment] 2022-08-17 08:11
Many thanks, that's exactly it, and the fix looks good to me as far as I can see. Sorry I didn't notice that existing issue.

**Closed as not planned** 2022-08-17 08:11 UTC
