### ISSUE TITLE
[bug] Too eager locking

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#12234] opened 2022-10-03 23:12 UTC
I spawn a few parallel tasks on a Gitpod server. Each runs `conan install` using a different profile which uses a different compiler. However, all the work is being stalled and synchronized by Conan with a message:

```cpp
catch2/3.1.0: catch2/3.1.0 is locked by another concurrent conan process, wait...
catch2/3.1.0: If not the case, quit, and do 'conan remove --locks'
```

I think it is a big limitation not to be able to do `--build missing` parallel for the same package with different configurations that results in a different package ID. Only in the case of the same package ID builds should be synchronized and queued, otherwise we are wasting so much time waiting for all the work to be done in a synchronous way.

**Comment by memsharded** [comment] 2022-10-03 23:31
This is not completely accurate. There are a bunch of tasks that are common to all different ``package_ids`` of the same package:
- All export operations
- All source operations
- All configure, requirements, etc methods, that might read from disk
- Part of the ``system_requirements`` operations

The locking should be blocking those concurrent tasks.
In any case locking in 1.X cache will no longer be improved, and Conan 2.0 cache has completely removed locking. It will be worked on in the 2.X target, and there are tickets open for it already, lets follow them.

**Comment by AbrilRBS** [comment] 2023-12-24 00:13
Thanks for your report

> It will be worked on in the 2.X target, and there are tickets open for it already, lets follow them.

Closing as duplicate of for the tracked issues

**Closed as completed by AbrilRBS** 2023-12-24 00:13 UTC
