### ISSUE TITLE
Cannot specify build numbers only in export-pkg command

### ISSUE THREAD

**Issue by progician** [conan-io/conan#2667] opened 2018-03-23 10:09 UTC
- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

# Summary

Conan recipes have a version attribute which if specified have to match the version number in the package reference during exporting, if provided. This makes it really difficult to append build number to the package version externally. The build number by nature is something coming externally to the source code therefore it is incorrect to specify them in the original recipe file. The core part of the version number however is best placed in the recipe file itself in the workflow where the recipe file is part of the source tree. This makes it really difficult to make use of the build number in the semantic versioning when in this workflow.

# Details

Using conan 1.1.1.

Given a recipe like this:

```
from conans import ConanFile, CMake
from semver import SemVer

class FantasticRecipe(ConanFile):
    name = "Fantastic"
    version = "1.0.0-pre1"
    description = "Super duper library"
    author = "Gyula Gubacsi"
    license = "None"
    url = "None"
    settings = [ "os", "arch", "compiler", "build_type" ]
    generators = "cmake"

    def build(self):
        v = SemVer(self.version, True)
        cmake = CMake(self)
        cmake.definitions["CONAN_PACKAGE_VERSION"] = str(v.major)+"."+str(v.minor)+"."+str(v.patch)
        cmake.configure()
        cmake.build()
        cmake.install()

    def package(self):
        self.copy( pattern="*", src="package", dst=".", symlinks=True )
```

1. Install and build the package
2. export it with the following command:

```
conan export-pkg -f -bf build-release . Fantastic/1.0.0-pre1+build2@progician/release
```

# Result

The `export-pkg` command will fail:

```
ERROR: Specified name/version doesn't match with the name/version in the conanfile
```

If the version attribute is removed from the recipe, the export would work, but as you see, for in-source conan recipes it makes sense to define the version of the software in a single place, and the most logical place is the conan recipe. In this particular case, I can't remove the version attribute as I use it in passing it to the CMake helper following the single definition principle.

# Workarounds

So far I have not implemented any of the workarounds detailed here, because I consider them incredibly awkward. But theoretically, the problem can be surpassed by a number ways.

For example, we could just remove the entire version attribute dependency from my recipe. It is possible to use the package version from specified in CMake, grep it out from the CMakeLists.txt by Jenkins and passing it to the `export-pkg` command. This way the version of the package would be stored in the build system, rather than the recipe. This is error prone fragile solution as it assumes certain convention adopted by the build scripts.

Another solution could be to template the recipe before use. I could write in the version attribute something like `1.0.0-pre1-@BUILD_NUMBER@` and then use sed or something similar to replace it with the environment variable BUILD_NUMBER when running the Jenkins job. This would introduce an extra step before the usual `conan install` and extra tooling for very little gain.

# Proposal

None of the above solution is satisfying for me. I would rather have a way to extend the version number of the package when calling `conan export-pkg`. I can live with extracting the current version number from the recipe with `conan info -n id` and some filtering, and passing it back as the reference when exporting expanded with the +build$BUILD_NUMBER. As the build number is an optional field in semver, I expect conan to accept this change.

Alternatively, alter the way references are passed in to conan. I should be able to write something like this:

```
conan export-pkg -bf build-release . +build123@progician/dev
```

and expect that conan will safely append the version number with having to specify the rest of the reference. By safe I mean that you have no way to alter the core version number, only up to build numbers. Personally I think this would be the easiest solution.

**Comment by memsharded** [comment] 2018-03-23 10:54
Not sure if I understood the issue, have you tried to remove ``name`` and ``version`` from the recipe itself? That should work with external assignment of:
```
conan export-pkg -f -bf build-release . Fantastic/1.0.0-pre1+build2@progician/release
```

Please try that and report. Many thanks for the feedback.

**Comment by memsharded** [comment] 2018-03-23 11:18
A nice solution could be, without requiring an extra step: 
- Define an env-var BUILD_NUMBER
- Use the following code:
```python
def get_version(version):
    bn = os.getenv("BUILD_NUMBER")
    return (version + bn) if bn else None
    
class HelloConan(ConanFile):
    name = "Hello"
    version = get_version("1.0.0")
```

So basically your command would be just:
```
BUILD_NUMBER=-pre1+build2 conan export-pkg . progician/release
```

**Comment by progician** [comment] 2018-03-23 12:35
It won't work. I actually tried it before. The problem is what is described in the docs as well: the function will be called when conan installs the package for a consumer which sets its own build number and thus breaks the dependency versioning. You can't have a non-constant version number without calling a world of trouble.

**Comment by memsharded** [comment] 2018-03-23 13:16
Are you sure? The version when a package is installed doesn't come from evaluating the version field. It is overwritten with the package meta-data. The version field is exclusively used at "export" time, once it is in the cache, it is not used.

Please make sure to try it, I have just tried it here and seems to work fine.

**Comment by progician** [comment] 2018-03-23 15:05
Actually, you are right it does work. My problem was that I didn't deal with the None gracefully. In any case, while this seems the most viable workaround, and I'm inclined to go with it for now, I still believe that the best way to go about this is in the command line rather than adding extra complexity to the recipe files.

**Comment by memsharded** [comment] 2018-03-23 15:30
Fair, I am going to leave this issue open, and request feedback from other users. Thanks!

**Comment by korvan** [comment] 2019-02-19 07:59
I have 2 scenarios, which are currently workarounded by env vars.
1) build number comes from CI server, and major/minor/subminor are stored in recipe. Workaround with getenv('BUILD_NUMBER') works, but when teammate looks to the CI page, and it's not obvious, to look for environment, until you read the recipe.
2) Some third party components come with different version format(like x.x.x.x, x.x-x etc.). Currently I reformat version in CI build scripts, but it looks more convinient to do in the recipe. This can make recipe more flexible for usage from different sources(e.g. from CI server and from local machine).

I'd like to have a step in the recipe, called before version is actually used, where it's possible to change it.
def configure_version(self):
    if check_format(self.version) == Wrong
         self.version=do_some_work(self.version)

**Comment by memsharded** [comment] 2019-02-19 09:36
Hi @korvan,

I fail to see why the above solution doesn't fit your use case:
```python
def get_version(version):
    bn = os.getenv("BUILD_NUMBER")
    return (version + bn) if bn else None
    
class HelloConan(ConanFile):
    name = "Hello"
    version = get_version("1.0.0")
```

You can implement any  logic in the ``get_version()`` function. The only thing is that it is not a method, but a module function, but the functionality you can have is the same. Please tell me, thanks for your feedback!

**Comment by memsharded** [comment] 2019-02-19 09:48
Hi @progician 

From what I have learned from users this time, having an "append" pattern for build numbers to the package version would be difficult, as I have seen many different approaches of versioning from many different teams and companies. Some would use 4 digits, other would use pre-release like strings (-alfa.123), others build numbers. Doing only the build number (+build123) won't be general enough.

The approach we are following towards this is the called "package revisions" feature. It is already merged and released but disabled (can be used activating some env-vars). The idea is:

- Every recipe has a revision number, internal, automatic and transparent. By default it is the git commit hash. Changing the recipe causes a new revision. If the recipe doesn't change, it doesnt.
- Revisions are specified as ``pkg/version@user/channel#RREV``. (RREV=recipe revision)
- By default, references not specifying a revision will fetch the last one. No need to use version ranges, and resolution should be much faster than version ranges. You can also specify exact revisions to be used.
- Every package has a revision number, internal, automatic and transparent. By default is the hash of the contents of the binary. If the binary is rebuilt and doesn't change, then the revision keeps the same.
- Package revisions are specified as ``pkg/version@user/channel#RREV:packageId#PREV`` (PREV = package revision).
- Though not implemented yet, it might be a possibility to define the PREV manually too from the command line.

The idea is that rebuilding a package because some of the dependencies changed, shouldn't produce a new recipe revision, as the recipe hasn't been modified, but it will produce a new binary package revision, because of the binary linking a new upstream dependency. You can have a look also to: https://github.com/conan-io/conan/wiki/Revisions-experimental-feature

**Comment by korvan** [comment] 2019-02-19 10:12
Hi @memsharded.
Approach with environment variable works fine. The problem is only with sharing this recipe. It's easy to copypaste reference name/version@user/branch from build log and debug/develop component locally for any platform, from any host OS.
Env var is hidden, export variable to environment is a bit different for different platforms. And build logic is splitted between recipe and CI server.

**Comment by memsharded** [comment] 2019-02-19 10:48
Thanks for the feedback @korvan 

Still cannot fully understand your suggested approach, let me summarize to check:
- The version could be defined in the command line with ``conan export . version@user/channel``.
- The recipe would also have some ``version="1.2.3"`` defined
- The recipe new method would take that ``version`` from the command line, the ``version`` from the recipe, and output a new, different version, that could be different to both? I see this a very counter-intuitive and problematic.

The thing is that developers in their machines, they wouldn't have a build number, by default, indeed the logic is splitted, the CI servers are the only ones that use build-numbers. I see this a as a feature, not an issue. So I'd use the following:

```python
from conans import ConanFile
import os

def get_version(version):
    bn = os.getenv("BUILD_NUMBER", "")
    return (version + "+" + bn) if bn else version
    
class HelloConan(ConanFile):
    name = "Hello"
    version = get_version("1.0.0")
```
That works fine, users locally they get the ``1.0.0`` version, without defining any env-var at all, and CI servers will append the build number. They can always assign manually a BUILD_NUMBER defining an env-var, but certainly this is something that should be hidden, it is an advanced thing, developers shouldn't be doing it.

What do you think? Can you please elaborate a bit further? Thanks!

**Comment by memsharded** [comment] 2023-10-07 23:59
Conan learned some time ago the ``set_version()`` method that allows read-write of the ``self.version`` attribute:
```python
def set_version(self):
      self.version = self.version or "2.0"
```
Which is exactly what was requested here, closing the ticket as solved, please report in new tickets if necessary. Thanks!

**Closed by memsharded** 2023-10-07 23:59 UTC
Labels: Feedback please!, stage: triaging
