### ISSUE TITLE
[bug][conan 2.0] Problem with ``conan download`` from Artifactory server, 500 Internal Error

### ISSUE THREAD

**Issue by antze-k** [conan-io/conan#12418] opened 2022-10-28 16:13 UTC
I have Conan 2.0.0-beta4 and self-hosted Artifactory (artifactory-cpp-ce, 7.46.9). For some reason "conan list packages" seems to be not working if used remotely, but "conan list package-revisions" does work if I know the package ID. Packages are visible in Artifactory UI.

Example:

```
>conan search -r abc
abc:
  zlib
    zlib/1.2.12@abc/conan2

>conan list recipes -r abc zlib
abc:
  zlib
    zlib/1.2.12@abc/conan2

>conan list recipe-revisions -r abc zlib/1.2.12@abc/conan2
abc:
  zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874 (2022-10-28 15:47:53 UTC)

>conan list packages -r abc zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874
abc:
  There are no packages

>conan list packages zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874
Local Cache:
  zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:3505ed85405d0910212909f45682cb32cf62aa34
    ...
  zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b
    ...

>conan list package-revisions zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b
Local Cache:
  zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b#cee0fc478a725021aaa712a8c1f0aded (2022-10-20 12:30:07 UTC)

>conan list package-revisions -r abc zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b
abc:
  zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b#cee0fc478a725021aaa712a8c1f0aded (2022-10-28 15:47:53 UTC)

```

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by antze-k** [comment] 2022-10-28 16:40
More information, this seems to be unrelated to Artifactory installation:

```
>conan list recipe-revisions -r conancenter zlib/1.2.12
conancenter:
  zlib/1.2.12#ce85b680d90f872406f83b11dcbeac36 (2022-10-19 09:19:10 UTC)
  zlib/1.2.12#c2cd5ec484e443e4f01b51ff5370fd11 (2022-10-14 11:42:21 UTC)
  zlib/1.2.12#3157a5e15f592cd81d5b3ce8fc4a4318 (2022-10-12 05:49:39 UTC)
  zlib/1.2.12#a30750797caa71bd61bd0a18189caa28 (2022-08-05 17:17:31 UTC)
  zlib/1.2.12#3b9e037ae1c615d045a06c67d88491ae (2022-05-13 13:55:39 UTC)
  zlib/1.2.12#bd533fb124387a214816ab72c8d1df28 (2022-05-09 06:59:58 UTC)
  zlib/1.2.12#82202701ea360c0863f1db5008067122 (2022-03-29 15:47:45 UTC)

>conan list packages -r conancenter zlib/1.2.12#ce85b680d90f872406f83b11dcbeac36
conancenter:
  There are no packages
```

**Comment by memsharded** [comment] 2022-10-28 17:21
Hi @antze-k 

Thanks for your report!
I think this might be the same issue as https://github.com/conan-io/conan/issues/11370, and indeed related to Artifactory in both cases, because ConanCenter doesn't fail because it doesn't contain yet Conan 2.0 binaries. But if you use the repo for docs in https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html, you will get the same error.

Could we close this one and follow conversation in https://github.com/conan-io/conan/issues/11370? Thanks!

**Comment by antze-k** [comment] 2022-10-28 18:43
Oh, sorry for not seeing that one :)

**Comment by memsharded** [comment] 2022-10-28 19:17
> Oh, sorry for not seeing that one :)

No problem, better report it even if duplicated than not reporting 😄

**Comment by antze-k** [comment] 2022-10-28 23:06
Guess I'll have to reopen this one for some clarifications. You mentioned some kind of error which is also mentioned in that issue, but I have no error, I just have an empty list of packages:

```
>conan list packages -r abc zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874
abc:
  There are no packages
```

I dug into the thing a bit and found that it goes into `conans/client/rest/rest_client_common.py`, `search_packages()` which queries the URL `http://<server>:8081/artifactory/api/conan/conan/v2/conans/zlib/1.2.12/abc/conan2/revisions/4303dad8e84d2e8733853de5b4aa2874/search` which returns `{ }` without any kind of error.

I also can't `conan download` anything, neither via full package reference, nor via wildcards. Like this:

```sh
$ conan list package-revisions -r abc zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b
abc:
  zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b#cee0fc478a725021aaa712a8c1f0aded (2022-10-28 15:47:53 UTC)

$ conan download -r abc zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b
ERROR: There are no packages matching 'zlib/1.2.12@abc/conan2#4303dad8e84d2e8733853de5b4aa2874:b5736aa1d5815ef8a63464066435f0707e7d783b'
```

Actually, my temporary debug output triggered at the same place of the code, showing that `conan download` goes the same route, calling `conans/client/rest/rest_client_common.py`, `search_packages()` which might explain why it doesn't download. What could I have been doing wrong?

Edit: the conanv2 repo DOES trigger the error, so my case definitely differs.

**Comment by memsharded** [comment] 2022-10-29 10:17
Not sure what is happening, but let me clarify a bit about ``package_ids`` in both versions, I think it can be related:

- The ``package_id`` for Conan 1.X and Conan 2.0 are different, even if they have exactly the same configuration, will result in different package_ids
- Package binaries built with 1.X and 2.0 can then be uploaded to the same server without collision
- ``conan search <recipe-ref>`` in Conan 1.X will only report binaries built with Conan 1.X, but not binaries built with 2.0. It is like binaries from 2.0 do not exist for 1.X
- ``conan list packages <recipe-ref>`` in Conan 2.0 will only report binaries built with Conan 2.0, but not binaries built with 1.X. Binaries from 1.X is like they don't exist for 2.0

Then, can you please confirm that you have created and uploaded binaries with 2.0, or are you trying to access binaries that were created with 1.X? Thanks!

**Comment by antze-k** [comment] 2022-10-29 10:26
Everything was done with Conan 2.0.0-beta4 and artifactory-cpp-ce, 7.46.9 (Docker installation, maybe the important fact that 7.46.9 is not "latest" but maybe even later than "latest"). The "repository path" in Artifactory for the mentioned package is `conan-local/abc/zlib/1.2.12/conan2/4303dad8e84d2e8733853de5b4aa2874/package/b5736aa1d5815ef8a63464066435f0707e7d783b/` (if that helps with determining if it's 1.X or 2.0 layout).

I'd like to emphasize that Conan "sees" the package with `conan list package-revisions -r abc <full package id>` but "doesn't see" with `conan download -r abc <full package id>` or `conan list packages -r abc <recipe#rrev>`.

Also, everything goes fine in the local cache. Maybe I misconfigured something in Artifactory, dunno, but it was almost the default installation.

**Comment by memsharded** [comment] 2022-10-29 10:33
> Everything was done with Conan 2.0.0-beta4 and artifactory-cpp-ce, 7.46.9 (Docker installation, maybe the important fact that 7.46.9 is not "latest" but maybe even later than "latest"). The "repository path" in Artifactory for the mentioned package is conan-local/abc/zlib/1.2.12/conan2/4303dad8e84d2e8733853de5b4aa2874/package/b5736aa1d5815ef8a63464066435f0707e7d783b/ (if that helps with determining if it's 1.X or 2.0 layout).

Yes, this doesn't help yet, because the path structure is the same, there is nothing there that is different in 1.X and 2.0.
The main difference will be inside the ``conaninfo.txt`` files inside the binaries, their structure is different in 1.X and 2.0

The critical point if that the packages there were created with Conan 2.0 ``conan create ...`` + ``conan upload``. It is not valid if those packages were created with 1.X.

> I'd like to emphasize that Conan "sees" the package with conan list package-revisions -r abc <full package id> but "doesn't see" with conan download -r abc <full package id> or conan list packages -r abc <recipe#rrev>.

Yes, this might be possible, because this listing of revisions of ``conan list package-revisions`` is not aware of the 1.X/2.0 differences, as it is just a listing of the ``index.json`` that is inside. It would be very difficult to make this command aware of this, and it is assumed that it will only be called with ``package_id`` that was returned from ``conan list packages`` command.

> Also, everything goes fine in the local cache. Maybe I misconfigured something in Artifactory, dunno, but it was almost the default installation.

Yes, the local cache is fine, it is just a pending to fix bug in Artifactory

**Comment by antze-k** [comment] 2022-10-29 10:45
> The main difference will be inside the conaninfo.txt files inside the binaries, their structure is different in 1.X and 2.0

Just if that helps, `conaninfo.txt` for the mentioned package, as it is in Artifactory:

```ini
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=190
os=Windows
[options]
minizip=False
shared=False
```

> The critical point if that the packages there were created with Conan 2.0 `conan create ...` + `conan upload`.

They were, I uninstalled Conan 1.X quite some time ago.

> Yes, the local cache is fine, it is just a pending to fix bug in Artifactory

So, you suggest that it's the same Artifactory bug as the one in #11370 (or maybe another manifestation of it)? I could check Artifactory logs, or maybe something else if you direct me. Unlike that known bug, I don't even have a workaround, because I can't `conan download` and list package IDs in the local cache, because `conan download` doesn't work as well (I'm only able to search the local cache where they were initially created).

**Comment by memsharded** [comment] 2022-10-31 00:01
I have managed to reproduce a bug, not exactly what has been reported above, for ``conan download``:

- Started from a completely empty Conan repo in Artifactory (FreeTier, but any modern Artifactory version should be same)
- With conan2 ``conan new cmake_lib -d name=hello -d version=0.1``
- ``conan create .``
- ``conan upload "hello*" -r=myrepo -c``
- ``conan remove "*" -f``

Then
```bash
$conan download hello/0.1#16434eda3b0dd870e218e270e2677b8a:2401fa1d188d289bb25c37cfa3317e13e377a351#4a92bbe70deb0c1b4582b45c82f518c3 -r=myremote

ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: myremote]
```

This is a bug we were not aware of, and definitely needs fixing together with the pending ``conan list packages`` (probably internally it is very related, because all is related to the ``conaninfo.txt`` format)

The normal installation of the package works fine:
```
$ conan install --requires=hello/0.1
```

**Comment by memsharded** [comment] 2022-10-31 00:21
Meanwhile an effective workaround could be to list the folders under the specific path, which is relatively easy to deduce for ref, under ``children->uri``:

```bash
curl http://localhost:8082/artifactory/api/storage/<repo-name>/<user>/<pkg>/<version>/<channel>/<recipe_revision>/package
curl http://localhost:8082/artifactory/api/storage/conan-local/_/libpng/1.6.37/_/0/package
{                                                                                                 
  "repo" : "conan-local",                                                                         
  "path" : "/_/libpng/1.6.37/_/0/package",                                                        
  "created" : "2022-10-26T03:53:31.481+02:00",                                                    
  "createdBy" : "admin",                                                                          
  "lastModified" : "2022-10-26T03:53:31.481+02:00",                                               
  "modifiedBy" : "admin",                                                                         
  "lastUpdated" : "2022-10-26T03:53:31.481+02:00",                                                
  "children" : [ {                                                                                
    "uri" : "/ce650d9f1f1c1c0839cf0694a55c1351ddbed859",                                          
    "folder" : true                                                                               
  } ],                                                                                            
  "uri" : "http://localhost:8082/artifactory/api/storage/conan-local/_/libpng/1.6.37/_/0/package" 
}                                                                                                ```

**Comment by antze-k** [comment] 2022-10-31 06:01
> I have managed to reproduce a bug, not exactly what has been reported above

I followed the very same steps, with the one exception of:

```
conan create . -pr:b x86_64-pc-windows-msvc.v140.MD.profile -pr:h x86_64-pc-windows-msvc.v140.MD.profile
```

because I don't use the default profile. And I got:

```
>conan download hello/0.1#16434eda3b0dd870e218e270e2677b8a:76163daaeb1bfc95d3391dbdf595047816c652ee#c5146b71d175fc898991452b820f394e -r abc
ERROR: There are no packages matching 'hello/0.1#16434eda3b0dd870e218e270e2677b8a:76163daaeb1bfc95d3391dbdf595047816c652ee#c5146b71d175fc898991452b820f394e'
```

`conan install --requires=hello/0.1 -pr:b x86_64-pc-windows-msvc.v140.MD.profile -pr:h x86_64-pc-windows-msvc.v140.MD.profile` worked fine indeed and thank you very much for the workarounds. I am not going to stop here and will try to find out what is so different in my installation and get back to you once I have more useful information.

Update: the very same happens if I copy my profile to 'default'.

**Comment by memsharded** [comment] 2022-10-31 10:22
That is interesting. It would be worth checking the specific Artifactory version, I was using the FreeTier one (typically very latest), and 7.35, but I can try to use locally your exact one. I don't think anything changed recently related to all this, but I'll try later if I can get some time, just in case.

Can you please check what happens in your case if you also use your ``default`` profile, instead of your custom one?

**Comment by antze-k** [comment] 2022-11-01 11:48
Sorry for late reply. Found the culprit:

```
>conan list packages -r abc hello/0.1#16434eda3b0dd870e218e270e2677b8a
abc:
  ERROR: 500: org.jfrog.repomd.conan.exceptions.ConanInfoException: Missing section in conaninfo.txt. [Remote: abc]
```

With this:

```json
{
  "version" : "7.46.8",
  "revision" : "74608900",
  "addons" : [ "conan" ],
  "license" : "Artifactory Community Edition for C/C++",
  "entitlements" : {
    "EVENT_BASED_PULL_REPLICATION" : false,
    "SMART_REMOTE_TARGET_FOR_EDGE" : false,
    "REPO_REPLICATION" : false,
    "MULTIPUSH_REPLICATION" : false
  }
}
```

And:

```
>conan list packages -r abc hello/0.1#16434eda3b0dd870e218e270e2677b8a
abc:
  There are no packages
```

With this (clean installation!):

```json
{
  "version" : "7.46.9",
  "revision" : "74609900",
  "addons" : [ "conan" ],
  "license" : "Artifactory Community Edition for C/C++",
  "entitlements" : {
    "EVENT_BASED_PULL_REPLICATION" : false,
    "SMART_REMOTE_TARGET_FOR_EDGE" : false,
    "REPO_REPLICATION" : false,
    "MULTIPUSH_REPLICATION" : false
  }
}
```

The same results are observable with `conan download` as well.

**Comment by antze-k** [comment] 2022-11-01 11:53
So, basically, we have error 500 bug for Artifactory 7.46.8 (and probably earlier) and empty package list bug for Artifactory 7.46.9, for both `conan download` and `conan list packages`. Guess it's either tracking both in #11370 & closing this one, or renaming the title of this one into "problems with conan download" or something.

**Comment by antze-k** [comment] 2022-11-01 11:57
Forgot to mention: this is all unrelated to the profile, happens with the default one too (actually I mentioned it in some comment edit above already).

**Comment by memsharded** [comment] 2022-11-01 15:46
Renamed the issue, as the symptoms are different, it might help to clearly identify it in its own issue.

**Comment by memsharded** [comment] 2022-11-01 15:46
Renamed the issue, as the symptoms are different, it might help to clearly identify it in its own issue.

**Comment by antze-k** [comment] 2022-11-02 15:07
Deeply sorry for the previous misinformation, Artifactory version is irrelevant to what I saw, the issue was in "virtual repository" -- just re-tested it.

When I create just "conan" local repository, I observe 500 error, like everyone else, both for `conan list packages` and `conan download`, like everyone else.

When I create "conan-local" local repository and "conan" virtual repository (linked to "conan-local"), I observe "there are no packages" response without any error.

Guess it's the same problem under the hood, so don't think it's necessary to open another issue, just letting you know to clear any possible confusion in the future.

**Comment by memsharded** [comment] 2022-11-02 15:19
> Deeply sorry for the previous misinformation, Artifactory version is irrelevant to what I saw, the issue was in "virtual repository" -- just re-tested it.

Everything is great, don't worry, thanks very much for all the detailed feedback and trying things!

**Comment by memsharded** [comment] 2023-02-03 12:45
Fixed in https://www.jfrog.com/confluence/display/JFROG/Artifactory+Release+Notes#ArtifactoryReleaseNotes-Artifactory7.52 Artifactory 7.52, closing this issue.

**Closed as completed by memsharded** 2023-02-03 12:45 UTC
Labels: component: artifactory
