### ISSUE TITLE
[bug] configure seems to be called before requirements

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#7711] opened 2020-09-14 15:48 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian 10
  * Compiler+version: N/A
  * Conan version: 1.28.0
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)

STR are in the zip.

### Logs (Executed commands with output) (Include/Attach if Applicable)

When creating `libb` (which requires `liba`):

```
Exporting package recipe
libb/0.1.0: The stored package has not changed
libb/0.1.0: Using the exported files summary hash as the recipe revision: 79bcf5c315d31f6f002e3de74ff55e3a 
libb/0.1.0: Exported revision: 79bcf5c315d31f6f002e3de74ff55e3a
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
*:shared=False
[build_requires]
[env]

ERROR: libb/0.1.0: Error in configure() method, line 21
	if self.options["liba"].shared or not self.options["liba"].shared:
	ConanException: option 'shared' doesn't exist
Possible options are []
```

There is no trace of `liba`.

[configure-bug.zip](https://github.com/conan-io/conan/files/5219561/configure-bug.zip)

**Comment by theodelrieu** [comment] 2020-09-14 15:50
This bug has been there for a while, 1.28.0 only made it visible by commit https://github.com/conan-io/conan/commit/f563439d18dacf4e7310c08c07386f95070eccfc#diff-bae39d2bdc7699f69aedb39446005cd6R75

**Comment by ericriff** [comment] 2020-09-14 18:58
Thats the intended behavior, see https://docs.conan.io/en/latest/reference/commands/creator/create.html

```
conan create executes methods of a conanfile.py in the following order:

config_options()
configure()
requirements()
package_id()
build_requirements()
build_id()
system_requirements()
source()
imports()
build()
package()
package_info()
```

**Comment by theodelrieu** [comment] 2020-09-14 21:13
Well I didn't know that, thanks for the link.

However, it means it's just not possible to perform sanity checks on requirements' options?
My use-case is to raise `ConanInvalidConfiguration` when a dependency option is incompatible with the current package options.

**Comment by ericriff** [comment] 2020-09-14 21:20
You can force the options that you want for the dependencies
```
   def requirements(self):
         self.requires("libmodbus/3.1.6@brewst/stable#5795fffb6aaf55ec80769db0780ef608")
         self.options["libA"].shared = True
```

**Comment by ericriff** [comment] 2020-09-14 21:20
You can force the options that you want for the dependencies
```
   def requirements(self):
         self.requires("libA/version")
         self.options["libA"].shared = True
```

**Comment by theodelrieu** [comment] 2020-09-15 07:35
Yeah that's not really the use-case unfortunately.

In fact, I stopped doing this kind of stuff years ago, the issue here is that 1.28.0 breaks a 2yr old recipe which RREV is manually pinpoint in our compatibility tests, so it's quite annoying to workaround...

Currently, this breaks old recipes (that were incorrect, alright, but it's still breaking them)

**Comment by jgsogo** [comment] 2020-09-17 08:43
In order to validate options from requirements you need to wait until all the graph is resolved, right now it is only possible in the `build()` method, but we are considering other alternatives: https://github.com/conan-io/conan/issues/7591

Regarding the error raised when the option is not accessible yet, it was a bug we realize and fixed in that version, those recipes were buggy, unfortunately, they were not even relying on the bug behavior, but ignoring the intention of that statement written in the recipe. I think it was really a bug and we cannot consider it a regression.

**Comment by theodelrieu** [comment] 2020-09-17 08:54
>I think it was really a bug and we cannot consider it a regression.

I agree, but I cannot upgrade Conan to 1.29.0 right now, since it breaks our CI/release process and I can't really overwrite previous recipes :(

**Comment by jgsogo** [comment] 2020-09-17 09:02
Will you be blocked forever? I'd like to think that eventually you will be able to modify those old tests/recipes, won't you?

**Comment by theodelrieu** [comment] 2020-09-17 10:00
One day we'll drop them yeah...

**Comment by jgsogo** [comment] 2020-09-17 10:46
Probably nothing to do here then, shall we close the issue?

**Closed as completed** 2020-09-17 11:58 UTC
Labels: stage: triaging
