### ISSUE TITLE
[bug] 'Manifest mismatch' error when uploading a 'cmake' package taken from 'conancenter'

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#15017] opened 2023-10-26 13:55 UTC
### Environment details

* Operating System+version: **_Windows 11 Enterprise_** (OS Version: `10.0.20348` Build `2031`)
* Compiler+version: -
* Conan version: `2.0.13`
* Python version: `3.11.6`

### Description

Hi,
We need to make some 'official' _Conan-packages_ of the **CMake** tool available from a repository on our Artifactory server (with 'official' I mean 'taken from _conancenter_'). This is because our build servers don't have direct access to 'conancenter' due to internal company policies that limit access to the Internet.
For transferring (copying) the needed packages we use sequences of `conan download` and `conan upload` commands as shown below (section **Steps to reproduce**).
This fails with a `Manifest mismatch` message (along with a final `corrupted artifacts` message) as shown below (section **Logs**).
Instead, omitting the `--check` flag the `upload` command succeeds.

Seemingly, the binary package in question is the one for `os: Macos` (package `9e5323c65b94ae38c3c733fe12637776db0119a5`).
I'm not sure whether this is a possible bug in the `upload` command or more probably some issue in the package creation itself, so I might possibly have created this bug report in the wrong place. If so, I apologize for that.

Best regards

#### PS
I tried with a few different versions of _CMake_ packages from _conancenter_, with the same result.
And I've made an attempt right now with package _make/4.2.1_, in this case without any issue.

### Steps to reproduce

```
conan download -r conancenter cmake/3.26.3
conan upload cmake/3.26.3 -r conanlocal --confirm --check
```

### Logs

```
cmake/3.26.3: Integrity checked: ok
cmake/3.26.3:522dcea5982a3f8a5b624c16477e47195da2f84f: Integrity checked: ok
cmake/3.26.3:63fead0844576fc02943e16909f08fcdddd6f44b: Integrity checked: ok
ERROR: cmake/3.26.3:9e5323c65b94ae38c3c733fe12637776db0119a5: Manifest mismatch
ERROR: Folder: C:\Users\VssAdministrator\.conan2\p\cmakee0f8cc1ef0e11\p
ERROR:     'CMake.app/Contents/Frameworks/QtCore.framework/Resources' (manifest: None, file: e58c4cf10cc7c8ef7d7167ccb641aeb4)
ERROR:     'CMake.app/Contents/Frameworks/QtGui.framework/Resources' (manifest: None, file: e58c4cf10cc7c8ef7d7167ccb641aeb4)
ERROR:     'CMake.app/Contents/Frameworks/QtPrintSupport.framework/Resources' (manifest: None, file: e58c4cf10cc7c8ef7d7167ccb641aeb4)
ERROR:     'CMake.app/Contents/Frameworks/QtWidgets.framework/Resources' (manifest: None, file: e58c4cf10cc7c8ef7d7167ccb641aeb4)
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\conan\cli\cli.py", line 172, in run
    command.run(self._conan_api, args[0][1:])
  File "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\conan\cli\command.py", line 125, in run
    info = self._method(conan_api, parser, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\conan\cli\commands\upload.py", line 102, in upload
    conan_api.cache.check_integrity(package_list)
  File "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\conan\api\subapi\cache.py", line 62, in check_integrity
    checker.check(package_list)
  File "C:\hostedtoolcache\windows\Python\3.11.6\x64\Lib\site-packages\conan\internal\integrity_check.py", line 28, in check
    raise ConanException("There are corrupted artifacts, check the error logs")
conans.errors.ConanException: There are corrupted artifacts, check the error logs

ERROR: There are corrupted artifacts, check the error logs
```

**Comment by memsharded** [comment] 2023-10-26 15:06
Hi @marausch 

Thanks for reporting.
I think this is a side issue of the CMake executable in OSX that creates some files after running the first time (those ``Resources`` files). The ``check`` is raising this discrepancy.

We need to have a look if it could be fixed in the recipe, but it can be challenging, as this is quite intrinsic on how the cmake executable behave in OSX.

There is nothing really bad, corrupted or dangerous in that CMake package at the moment, as a workaround you might skip the ``--check`` argument for this package on OSX while we have a deeper look and investigate how this can be improved.

**Comment by marausch** [comment] 2023-10-26 15:23
Hi @memsharded,

Thank you for the quick answer.
Just note that Conan packages of the **make** tool for the `os: Macos` case (at least the version I've tested)  seem not to be affected, which sounds a little bit discrepant.

**Comment by memsharded** [comment] 2023-10-26 15:25
Ok, found the root issue for this package:
- You are downloading the OSX binary in a Windows machine
- The OSX binary for CMake contains symlinks, that Windows machine cannot represent in disk. Package lost them while unzipped.
- If the binary is checked before upload, yes, it is telling that what you have in disk is not the same that was packaged, and if you uploaded it, there might be issues
- In practice, there won't because Conan will reuse the ``.tgz`` that has been cached, but the ``--check`` is checking the actual integrity of the files, not the .tgz archive

We still need to check if there could be ways to improve this, but at least this is the root cause.

**Comment by memsharded** [comment] 2023-10-26 15:26
Most likely the ``make`` package does not contain symlinks.

As a quick hint, typically "devops" operations like this one (downloading and uploading) tend to work better, faster, and more reliably on linux/osx machines.

**Comment by marausch** [comment] 2023-10-26 15:30
Yes, you are right!
I should have considered this by myself...
⁠;-P

**Comment by memsharded** [comment] 2024-07-29 23:11
Closing this ticket as outdated/resolved.

We are also working on something new, the ``install()`` method, see https://github.com/conan-io/conan/pull/16646. This can help with packages that can create or modify files at execution time. Please track that ticket if you are interested. Thanks for the feedback!

**Closed as completed by memsharded** 2024-07-29 23:11 UTC
Labels: stage: triaging
