### ISSUE TITLE
[bug] BazelDeps generator produces invalid absolute glob

### ISSUE THREAD

**Issue by AndersSundman** [conan-io/conan#16733] opened 2024-07-26 12:00 UTC
### Describe the bug

This conanfile.py
```
from conan import ConanFile
from conan.tools.google import bazel_layout

class CompressorRecipe(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "BazelDeps", "BazelToolchain"

    def requirements(self):
        self.requires("glfw/3.3.2")

    def build_requirements(self):
        self.tool_requires("cmake/3.22.6")

    def layout(self):
        bazel_layout(self)
```

Creates an invalid `BUILD.bazel` file for the `glfw` dependency `xorg`. Note: these specific libraries are just examples. I think it might be a problem for all libraries that use absolute paths.

The problem is the generated `BUILD.bazel` file that has this cc_library

```
cc_library(
    name = "xorg-uuid",
    hdrs = glob([
        "/usr/include/uuid/**",
    ]),
    includes = [
        "/usr/include/uuid",
    ],
    linkopts = [
        "-luuid",
    ],
    visibility = ["//visibility:public"],
)
```

Error message is: 
```
hdrs = glob([
Error in glob: pattern cannot be absolute
```

Bazel doesn't (afaik) support absolute globs, so the `hdrs` attribute can't be generated with a glob that takes an absolute path. 

### How to reproduce it

I'm trying this on ubuntu 22. 

Create a minimal project with the conanfile above, 

Put this in the MODULE.bazel
```
load_conan_dependencies = use_extension("//conan:conan_deps_module_extension.bzl", "conan_extension")
use_repo(load_conan_dependencies, "glfw")
``` 

and create a dummy cc_library with empty files and a `deps = ["@glfw"]` then bazel build the target and you get the error

**Comment by memsharded** [comment] 2024-07-26 14:45
Hi @AndersSundman 

Thanks for your report.

The ``xorg`` recipe is what we call a "system" recipe, just a wrapper around some existing system libraries, but not containing the libraries itself. It is possible that the BazelDeps integration is not taking system packages into account, I am assigning @franramirez688 to check this.

**Comment by franramirez688** [comment] 2024-09-02 14:43
Hi @AndersSundman 

I can't reproduce the issue. I just tried your example, and it's working fine. The `xorg` recipe is empty as it doesn't contain the library itself. Could you please provide a minimum repro case? I'm using Bazel 7.1.2 and Conan 2.7.0. I also recommend to update the requirements just in case you're using an older version:

```bash
$ conan create . --build=missing --update
```

**Comment by franramirez688** [comment] 2024-12-10 13:50
Hi @AndersSundman 

As I said above, I did not get to reproduce the issue 😢.
Does the problem persist? Or could we close this issue?

**Closed as completed** 2024-12-16 07:24 UTC
Labels: stage: triaging
