### ISSUE TITLE
Git LFS Support for SCM Attribute

### ISSUE THREAD

**Issue by pgrohs** [conan-io/conan#5392] opened 2019-06-24 08:20 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Applies to Conan 1.16.1.

I am using the ConanFile.scm attribute to get the sources of my packages from git repositories. Some of these git repositories contain large binary files I need for running the test suites. These large binaries are handled by Git LFS. It seems to be that these binaries are not fetched by the ConanFile.scm mechanism. Is there a way to enable Conan to fetch Git LFS objects?

**Comment by lasote** [comment] 2019-06-24 08:31
I've never used `git LFS` and we didn't try it with Conan. But as Conan is calling `git` to retrieve the stuff,  probably you can tell me what is missing/wrong/different and we can see how to solve it. We are doing "regular" `git clone` in most cases.

**Comment by pgrohs** [comment] 2019-06-24 11:52
The LFS download failes, but Conan is not the root cause. Sorry for the Spam.

**Comment by pgrohs** [comment] 2019-06-24 13:03
Nevertheless, it would have been very helpfull if Conan had reported, that the LFS download has failed rather an continuing without any notifcation. During my investigation of the issue i found the following in the git log:

```Error downloading object: [...] (cdf3783): Smudge error: Error downloading [...] (cdf3783a8631a946512fca657bf01be45da61984f056e79cb85d8949d92394da): batch response: Your user name must be of the form DOMAIN\user.```

But conan did not complain about it.

**Comment by lasote** [comment] 2019-06-24 13:24
Was that error happens during a `git clone`? Do you have some more info? Maybe Conan is hiding some error.

**Comment by pgrohs** [comment] 2019-06-24 13:39
I happens when I want to consume my package as dependency of another one. When I call `conan install . --build=MyPackage`, conan clones then all the source code of "MyPackage" from a TFS-hosted git-repo, what works fine except for the LFS files. There is absolutley now hint in the conan output that something went wrong.

**Comment by lasote** [comment] 2019-07-01 08:38
Thanks for the info, I'll try to reproduce ASAP

**Comment by lasote** [comment] 2019-07-01 09:32
This is weird, any error on a git command raises an exception in Conan. Could it be possible that the error, in that case, didn't return a != "0" errno?

**Comment by pgrohs** [comment] 2019-07-03 06:20
I have checked it again: on my Windows machine with git 2.21.0 the exit code is 128 in case the LFS download failes.

**Comment by lasote** [comment] 2019-07-03 07:04
I cannot find the cause, any code != 0 will raise with Conan. Maybe if you could provide longer output for the failed process I could try to guess something. Thanks

**Comment by wumo** [comment] 2019-11-08 10:39
On all operating systems, once git-lfs is downloaded, `git lfs install` must be run. If not, the large files won't be downloaded when calling `git pull`. So conan need to call `git lfs install --local` or just `git lfs pull` to download large files.

**Comment by lasote** [comment] 2019-11-11 07:07
@wumo thanks for your comment. So, after a `git clone`, a `git lfs install` should be run?

**Comment by wumo** [comment] 2019-11-11 10:20
@lasote Right. I refer to [git-lfs installation](https://github.com/git-lfs/git-lfs/wiki/Installation) for details.  Either `git lfs install` globally or `git lfs install --local` for specific repository would be fine.

**Comment by lasote** [comment] 2019-11-11 10:29
Thanks

**Comment by memsharded** [comment] 2023-01-31 09:17
``scm`` feature is being dropped in 2.0, and it already got superseded in 1.X by the new ``Git`` helper and explicit flow, documented in https://docs.conan.io/en/latest/reference/conanfile/tools/scm/git.html#example-implementing-the-scm-feature, so closing this ticket.

**Closed by memsharded** 2023-01-31 09:17 UTC
Labels: type: look into, priority: low, stage: queue, complex: low
