### ISSUE TITLE
[question] lockfile workaround: '--build=cascade' option leads to overwritten lockfiles

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7187] opened 2020-06-11 10:31 UTC
I was earlier advised to use a workaround for storing lockfiles:

> you can upload it to a generic repository associated with the reference+recipe_revision.

First, since the lockfile contents are also influenced by the profile I expect that the lockfile path should also include the 'pid', right?  (e.g. `<generic repo>/app/0.1/<rrev>/<pid>/conan.lock`)

I've been following the [How to use lockfile in CI](https://docs.conan.io/en/latest/versioning/lockfiles.html#how-to-use-lockfiles-in-ci) flow, but I'm confused about the possibility of lockfiles being overwritten in artifactory and losing the ability to reproduce builds.  And how these lockfile should fit-in to build promotion process.

for example:

1. app/0.1 (with a dependency to pkgA/0.1) is built and both the package and it's lockfile are uploaded to artifactory.
    - the package is uploaded to an 'unreviewed' repo
    - the generated lockfile is uploaded under `<generic repo>/app/0.1/<rrev>/<pid>/conan.lock` and added to the buildinfo under 'recipe' module.

2. The change passes review and is submitted.
   - artifactory 'promote build' API is used to move all of the built artifacts from the 'unreviewed' repo to a 'reviewed' repo. 

3. A developer pushes changes to pkgA, bumping version to pkgA/0.2

   - jenkins download the lockfile for app/0.1 
(using 'conan info app/0.1 -r <reviewed remote> --profile=<profile> --json info.json' to get rrev and pid for determining it's location in artifactory)

   - pkgA/0.2 is exported, updating lockfile with new version.

   - use lockfile to rebuild pkgA/0.2 and integrates downstream with `--build=cascade` option, rebuilding pkgB/0.1, pkgC/0.1 and app/0.1.

   - all packages are uploaded to the 'unreviewed' repo

   - the lockfiles are uploaded for each built package:

        ```
        <generic repo>/pkgA/0.2/<rrev>/<pid>/conan.lock
        <generic repo>/pkgB/0.1/<rrev>/<pid>/conan.lock
        <generic repo>/pkgC/0.1/<rrev>/<pid>/conan.lock
        <generic repo>/app/0.1/<rrev>/<pid>/conan.lock
        ```

    Since the package id of app did not change (pkgA is not a direct dependency to app), the original lockfile is overwritten with a new lockfile which contains the new pkgA/0.2 and which is only associated with the new build.

    Furthermore, this new lockfile will be available for use by other jobs, even though the change that produced it has not passed through the review/promotion process.

So then, I understand it that it is completely necessary to set correct `package_id_mode`s and avoid use of `--build=cascade`?  So that a new entry for lockfile will be made under artifactory.

Is my understanding here correct here, or?
Do you have any other hints for retrieving/using lockfiles?

**Comment by czoido** [comment] 2020-06-11 13:59
Hi @GordonJess,

We have some examples of this kind of flow in this organization we built for the conan ci/cd training: https://github.com/conan-ci-cd-training I'm going to refer to some parts of it for the answers. We are continuously working on it optimizing the flow but it's usable in its current state.

For storing the lockfiles, have you considered the possibility of adding the `build_name` and `build_number` to the path so that they don't get overwritten? [In this example](https://github.com/conan-ci-cd-training/libB/blob/ca42f2abceda0c95f64fe93151db48dc38c968e4/Jenkinsfile#L59-L72) we use the build `name` and `number`, the `reference` and the `profile` to store the lockfiles, so that later you can use that lockfile to make a promotion just retrieving from the generic repo the build you want to promote.

Also, we have found some issues regarding the use of build info with Conan and Artifactory  for promotions. The problem is that if you upload several times a package while you are generating new binaries you will also be attaching to the build info conanfile.py that's shared between all those multiple configurations. Later, when you want to promote one build the conanfile.py will remain with the property of the first build that uploaded it and when you try to promote maybe you'll get a message like `"Unable to find artifacts of build..." `
We are currently working to solve this issues and for some cases the promotion may work but we advise that you do the promotions [using the lockfiles directly](https://github.com/conan-ci-cd-training/products/blob/920e04c6e348ff7d890e7015cc306962f34832e3/Jenkinsfile#L126-L145) and copying the artifacts with the Artifactory API. In that example we are using the nodes marked as `modified="built"` in the lockfile to do the promotion, but maybe you want to copy everything checking previously if the artifact already existed in the target repo that would be equivalent to an Artifactory promotion with dependencies.

Regarding the `package_id_mode` I think that using a mode like `recipe_revision_mode` has the advantage of doing this flow "automatic" so that conan can decide what's missing to build each time but I don't think It's completely necessary.

Please tell me if this helps.

**Comment by DukeOfKirkcaldy** [comment] 2020-06-11 15:23
Hi @czoido,

Many thanks for your detailed response, those examples will be most helpful.

> For storing the lockfiles, have you considered the possibility of adding the build_name and build_number to the path so that they don't get overwritten?

Yes, I did think about it, but I had some problems.

I need to retrieve the lockfile when integrating lib changes.  This means I need to know the path in Artifactory where it is stored.  I can use the `conan info` command to get the `reference` and `rrev` and `package id` of the most recent package, but I am not sure how I can know which build produced it.

> We are currently working to solve this issues and for some cases the promotion may work but we advise that you do the promotions using the lockfiles directly and copying the artifacts with the Artifactory API.

Thanks for the tip.  I run into another limitation of the artifactory promote which I think this may help.  

My apps use packages from several different artifactory repos.  This works fine in the `buildinfo` and I can see all my dependencies and where they are stored.  But the artifactory 'promote build' API only supports a single `sourceRepo` and `targetRepo`.  I cannot specify per package where to copy on promotion.

**Comment by czoido** [comment] 2020-06-11 17:10
Hi @GordonJess,
Yes, if you don't use a more restrictive mode probably it's not going to be possible not to overwrite the lockfiles, if you don't want revisions to affect the package id's you can also try modes like `full_recipe_mode` or `full_version_mode` that for this case would work.
Have a look at the table with the modes here: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#versioning-schema

**Comment by DukeOfKirkcaldy** [comment] 2020-06-11 18:25
In order to make sure the lockfile is stored under a new path I would need
the `package id` to change, so I think the most restrictive mode would
solve it.

But I'd rather not have this restriction if possible.

**Comment by memsharded** [comment] 2024-01-28 22:13
This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!

**Closed as not planned by memsharded** 2024-01-28 22:13 UTC
Labels: type: question
