### ISSUE TITLE
Add non-settings properties to packages from the conanfile.py

### ISSUE THREAD

**Issue by tru** [conan-io/conan#1249] opened 2017-04-27 07:50 UTC
We have found that we wish for a property like system for our conan packages at times. These properties could be used to convey information about what exact code was used to build the package, configure options and other information that is useful when debugging issues in production, example of these properties could be:

* Link to SCM (link to github page with the commit directly)
* Slave used to build the package
* Exact configure options used to build this package
* Link to CI with the log of this current build

While some of the above could be solved with artifactory properties I think that there could be some really nice benefit of being able to set these properties dynamically and could give better visibility into what exact software is being used.

This requires the properties to be searchable or at least viewable with `conan info/search` as well.

**Comment by lasote** [comment] 2017-07-04 16:00
As I've commented in the #1477 I think that this information shouldn't be collected by Conan. An example could be Artifactory and the build_info. It's a different layer collecting data from the build itself, I think conan packages should store only data about the packages.

**Comment by Aalmann** [comment] 2017-09-13 12:29
@lasote 
In my company we are currently evaluating Conan. Imho at least the SCM details are required to make sure that "build missing" will always work. I'd like to give you a short user scenario to describe the problem (of Conan):
Assuming the CI or a user is building a "package A" from source for Windows using Visual Studio 201x. The sources itself are not exported (see below for details why it is not always the best solution to export/package the sources with the binary package). So the recipe contains an scm checkout (or in worst case nothing because it is already present because of the "other layer"). The package will then be published without explicit information about the SCM state at built-time. This package will be added and used by other packages (e.g. "package B") as requirement. This will work for VS 201x packages all the time.
Now (probably some weeks ago) a user wants to built his "package B" with VS 201y which depends on "package A". As described above there are no sources exported and there are no SCM-details.
In this case Conan will not be able to build the missing package from source.

Conclusion:
To make sure that Conan is able to always build the package from source and the result is always the same, Conan has to make sure, that the used sources are always the same. That could be reached either by exporting the sources or by providing the SCM details to the package.

The problem exporting sources:
Assuming a "user A" develops and publishes a package on Windows. Everything works as expected and everything is fine. Now "user B" will use this package and build it for Linux. This could work if "user A" has done a great c++ coding job. Will not work if there are some Windows specific implementations which has to be "ifdefed". So it could be that "user B" will now make some code changes in the extracted sources. This could be a big problem because there is no file tracking available (scm diff). That's why I would never add the sources as export but the scm reference.

**Comment by memsharded** [comment] 2017-09-13 21:28
Hi @Aalmann 

Regarding the first point, the key for SCM is that the source code will be retrieved from the ``source()`` method, something like:

```python
source_url = "https://..."
version = "1.2.3"
def source(self):
    self.run("git clone %s" % self.source_url)
    self.run("git co release/%s" % self.version)
```
So the package recipe has perfect knowledge about which source code should be retrieved, and which branch has to be used, etc.  Note that an "exact" model of this information is not required, even it might be restrictive. For example, if just one url is to be modeled, that wouldn't fit many cases in which the source tar ball is actually a different one:

```python
source_url = "https://..."
version = "1.2.3"
def source(self):
    if self.settings.os == "Windows":
          tools.download(base_url + "/winlibcode%s.zip" % self.version)
    else:
          tools.download(base_url + "/nixlibcode%s.tgz" % self.version)
```

Some users might be retrieving source code from tarballs for "release" packages, and using SCM for "develop" packages.

So regarding your first point, I agree that the SCM details are necessary, and they are always provided by the package recipe and used in the ``source()`` method.


Regarding the flow with exported sources, the key is that it starts with the checkout from SCM to fix the things. So if some package is not working for Linux because it had some definitions the process would be:

```bash
$ git clone https://.... #get the sources of the failing package
# edit sources
$ conan create ... #check the package is working
$ git add . & git commit -m "msg" & git push
```

So when a package is created or installed it is installed in the conan local cache. Those source files are never edited, they are not in the user space. The local cache, I see it as a local clean environment, where we can reproducible build things/packages, making sure it will be the same in any other machine.

There are some other commands that act locally, so in order to develop and fix your own package code, you don't need to build it in the cache, but you can do ``install`` + ``build`` in your user folder, to take advantage of your IDE, incremental compilation, etc.

Please tell me if the above makes sense, and do not hesitate to ask if you have further questions, or need help. Thanks!

**Comment by Aalmann** [comment] 2017-09-14 11:14
Hi @memsharded 

thanks for your response. 
Sure, that will work great for "released" packages, because there will be a tag or release branch which will never change again. But it could cause some problems when working on several packages at the same time in a team, where each user is responsible for one package. 
We have different teams with 5 or more developers and more than 10 packages per project. If I got it right, Conan prefers to have small packages (e.g. one lib and its headers) instead of huge (multi-)packages (e.g. like Qt which contains a lot of libraries), even if huge packages are also possible. However, assuming user A works at package A and user B works at package B which depends on A. User B normally wants to use the binary package of A. Package A is published at testing-channel or something like that, so that B can use it. But the (internal) development of A is not finished at that point, so there is no release-tag/-branch yet. Just a development built which is done with a specific commit at a development branch. Now let's say, that user B detects a problem in A and wants to fix it directly. Using only the source_url and the version will not work (no release branch present). User A could add the specific commit hash to the conan file, but this will only work if the developer always changes the hash after commit or better before publish. And now let's scale this to 10 or more packages at the same time with 5 or more developer. Sure it could be something defined in the development process, but it is error-prone if not (automatically) given by the underlying build/deployment system.
Btw. the same would happen if the CI triggers a build and publish after changes were detected. The CI would not increase the version for each build, isn't it?

So I would suggest to add a "simple" but sufficient SCM support to Conan. It only has to make sure, that the right source version is checked out and that the scm details are added to the package info. This could look like:
<pre>
...
version = "1.2.3"
scm_details = {type ="git", url="https://..." branch="feature/fency", revision ="abcd1234", directory="source", ...} # could be specific to the used scm, revision and branch does not always make sense 

def source(self):
    SCM.assureSCMDetails(self) # this could check and make sure that the right source version is checked out/branch switched, and it could be part of ConanFile (only used if scm details are given)
#    self.run("git clone %s" % self.source_url) # not needed anymore
#    self.run("git co release/%s" % self.version)

# ...

def package(self):
    SCM.setSCMDetails(self) # this would get the current scm details and probably an additional patch file (very dirty, but could be an option to make sure that the original source code including local changes can be restroed). This could also be part of ConanFile if scm is set.

</pre>

Assuming the SCM class would be part of Conan as a fundamental part and ConanFile would use it if scm_details are given, you could always make sure that the sources are matching to the binary package.

And this would not affect the tarball use case. The `source_url` can be used anymore.

I agree with you, that the local cache should be something "clean". But from the experience some developers are very "lazy" and "inventive". 
Concerning IDE (more than one source package in the same IDE): Is there already a ticket or discussion about that point?

**Comment by lasote** [comment] 2017-09-14 14:12
Sorry if I didn't understand well the problem, but what is the difference between your proposal and run `git clone` + `git reset --hard abcd1234`?

**Comment by Aalmann** [comment] 2017-09-14 16:33
The difference is the package info part where Conan collects the required information (git hash) to make sure that the checked out source code is exactly the same and that the user do not have to copy and paste the clone & reset command. Otherwise the user has to or will create a base class which does the same job. But that should be a basic part of Conan. Btw. if the recipe lives in the same repo the checkout is not required but you are unable to add the current scm information to the conanfile because this will cause another commit or a diff. So you are unable to restore the exact revision.
You are completely right if you are working just with 3 packages but handling 10 or more of them at the same time will lead to errors.

**Comment by lasote** [comment] 2017-09-15 06:50
The thing is, we cannot store that information in a built package. if the use case is that a user B needs to build a package for his missing configuration, you cannot know the SCM details because there is no package. 

In the other hand, you cannot store the details in the recipe itself because you want it to be automatic, and we cannot modify the exports directory "lively" during the source() method. Furthermore, a built package A (for settings X) can be built with some SCM checkout and a build package A (for settings Y) can be built with a different source code.

I see some value in storing the SCM information in a package, but, it cannot be used to recreate the package, it is a chicken egg problem.

Am I still missing something?

**Comment by Aalmann** [comment] 2017-09-15 11:00
This information should be part of the conaninfo.txt or conanmanifest.txt

I think one of the Conan base requirements should be / is, that one can always restore the sources used to built the binary package. Btw. there should also be a minimum Conan version information in the conaninfo to make sure that the used python code is running (the code `self.env_info.path.append(os.path.join(self.package_folder, "bin"))` only works with Conan 0.26.x but not with 0.25.x and lower)

IMHO there should be a user scm_details(given in the recipe, probably with or without revision) to be able clone/checkout the sources when the recipe lives in another repo. Then `source()` is called and because of the given user scm_details Conan does a checkout/clone etc. If the recipe lives in the same repo the scm class should handle that (e.g. by ignoring because it is already checked out or by checkout which may lead to the problem that the recipe could change in that moment). When creating the package, Conan should retrieve the "real" scm-details (revision, branch, url and either a possible diff file if there are local modifications or Conan should stop processing). These information will be written into the manifest or conaninfo file. With that information Conan will always be able to restore the exact sources which were used to build the package (assumed that there is an SCM set and used and that there is no source tarball).
If the package is then used by another user, it will be downloaded into the local cache (and not in user space). When (re)build of the package is required, Conan would check the conanfile and probably override the scm_details which are given in the manifest or info.

So I suggest to add the optional scm_details-attribute to `ConanFile` which has some restrictions, but when using it in the right way, Conan will always make sure, that the sources matches.

**Comment by Aalmann** [comment] 2017-09-15 15:13
After playing a little bit with Conan I got the chicken egg problem when calling create. 

If I got it right: When calling create the recipe is copied to the local cache and "executed" there but not in the original user directory. If there is a clone/checkout command in the source method, it will be performed etc. Probably I have to read the documentation again, because it seems to be that I did not understand all the concepts. 

But what I not understand: As @memsharded wrote:
```
$ git clone https://.... #get the sources of the failing package
# edit sources
$ conan create ... #check the package is working
$ git add . & git commit -m "msg" & git push
```
I get the sources, call create and AFTER that I add files and commit them. This can not work if the recipe is copied/exported and the package built in the local cache. I'm really confused.

**Comment by lasote** [comment] 2017-09-17 08:56
@memsharded said: "Regarding the flow with exported sources" That means the recipe and the source code in the same repository. So, when you call "create" the sources (edited locally) are exported to the local cache. In the recipes with "exports_sources" there is no `source` method.

About the general discussion of being able to know what exactly code has been used to build the package is a real problem and we understand it. The chicken-egg problem is, we can't store that information in a package because you need it to build a non-existing package. And you cannot store in the recipe, because two packages belonging to the same recipe, could have different used source code.

**Comment by memsharded** [comment] 2017-09-17 10:03
The only way would be to capture some state of the original repo, and "export" it as well, similar to conaninfo.txt, but for the initial export. That file can be loaded by the recipe when it is loaded.

**Comment by memsharded** [comment] 2023-11-29 17:28
Conan 1.X and 2.0 provide different mechanisms:

- conandata.yml, that can be updated with ``export()`` method to capture properties
- New ``metadata`` feature for both recipes and packages
- Conan artifactory commands extensions to set properties in the server side
- New ``conf`` system to define and inject any arbitrary property into recipes.

I am closing this ticket, if there are still some use cases not covered with the new features and tools, please create new tickets. Thanks!

**Closed by memsharded** 2023-11-29 17:28 UTC
