### ISSUE TITLE
[feature] Summary after install/create actions

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8526] opened 2021-02-18 08:58 UTC
Currently, no summary is shown after doing either `install` or `create` or any other function. This creates some unpleasant experience. Consider that workflow: I install some package with `conan install` and it throws me an error that some of its dependencies aren't built for my configuration. Ok, I calmly list them into the shell with `conan install something/1.2.3@ -b dep1 -b dep2 -b dep3 -b etc...`. Conan calls build for some packages, say `dep1` and `dep2` are built correctly but then it fails on building `dep3` with some compilation/linking/whatever error. I don't know if `dep1` or `dep2` are correctly built and need some pondering how to know whether are they built. I'm starting with `conan search dep1` then it outputs a bunch of packages that are exist in my local cache, then I read through logs to find out which version I've built and then I finally found it and upload correct binaries on my remote. That takes a lot of time, especially when it comes to subdependencies of my primary dependencies or overrides from my top project. I always clean up whole conan's package directory to make a "clean build" and only then I can distinct needed packages.
 It would be nice to have some summary after any kind of finish of conan install process both when it fails and when it succeeds.
 A simple list is way more informative, for example:
```
Conan summary:
something/1.2.3@
dependencies:
   dep1/0.0.1@user/stable      - force build (Success)
   dep2/0.0.2@user/unstable  - force build (Success)
   dep3/0.0.4@user/unstable  - force build (Failed)
   other_thing/1.1.1@             - Cache
```

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment] 2021-02-18 18:55
Probably it is enough to reproduce the summary we show before running other actions. The one where we list references if they are coming from the cache or they are missing... that same information with the data updated: if it was built, or maybe failed,... 

It should be easy, and for sure something to consider for Conan 2.0

**Comment by AbrilRBS** [comment] 2023-12-24 17:16
Closing as solved in Conan 2 with the [pkglist feature](https://docs.conan.io/2/examples/commands/pkglists.html) which is intended to solve this exact use-case, let us know if you have any feedback regarding it if you get to try it! Thanks!

**Closed as completed by AbrilRBS** 2023-12-24 17:16 UTC
Labels: priority: low, type: feature, stage: queue, complex: low, component: ux
