### ISSUE TITLE
[bug] Double python_requires

### ISSUE THREAD

**Issue by at185190** [conan-io/conan#8950] opened 2021-05-12 10:45 UTC
Recently we updated our pyhton_requires script from 1.0.0.1 to 1.0.0.2, now when building on Azure devops servers, we get 
Python requires
    xxx/1.0.0.2@ncraero/stable
    xxx/1.0.0.1@ncraero/stable

Which does not happen if we build locally, only happens locally if we build with dependencies built on azure servers.
We have chain of dependencies so that make sense, but what doesn't is that we can kick off first dependency on Azure it will require only 1.0.0.2, then next dependency which requires first, will suddenly require both versions even though neither source code ask for 1.0.0.1 any more.

There are some notes on documentation that package id is only affected by minor version update, would that also affect python_requires version matching? But I am not able to reproduce this locally, if I require 1.0.0.2 it will never pickup 1.0.0.1 even if 1.0.0.2 doesn't exist, which makes sense to me.

One thing we do on Azure is creating package for our pyhton_requires script, while documentation states :
python-requires should not create packages, but use export only.

Does this mean that we should not create package for it?

Also this statement confuses me a little : 
python-requires cannot use regular requires or build_requires.

We are using self.build_requires and self.requires as helper methods in our base class its working perfectly and never was an issue. Those helper methods are called from inheriting conanfile

```
    def requirements(self):
        super()._requires("abcsd", "1.1.0.1", self.default_user, self.default_channel)
```

Back to the main topic, any ideas why both .1 and .2 version of python_requires are required when its not in the code? 

### Environment Details (include every applicable attribute)
  * Operating System+version: Win/Multiple :linux distros
  * Compiler+version: Any
  * Conan version:1.32
  * Python version:1.8+

**Comment by at185190** [comment] 2021-05-12 13:34
After clearing local cache on one of our azure build machines, it was no longer requiring double version of our base class. 

I've tried to play locally with conan create for base class and see if that's causing the issue, but I was unable to reproduce it. Could this be related to number of revisions in the cache?

**Comment by danimtb** [comment] 2021-05-12 16:50
Hi @at185190,

This might be an issue if using a cache in de Azure server but I can only think about this issue happening in case you are using version ranges (maybe), or maybe it the case of package ID not affected by the minor version change. In the latter, the issue might happen if you have not rebuilt packages depending on python require `xxx/1.0.0.1@ncraero/stable`.

Regarding your questions:

> There are some notes on documentation that package id is only affected by minor version update, would that also affect python_requires version matching?

As stated in https://docs.conan.io/en/latest/extending/python_requires.html#packageid, python requires use `minor_mode` package ID by default. Not sure if `1.0.0.1` / `1.0.0.2`  is semver compliant and how conan understands this, so will have to check with an example.

> Does this mean that we should not create package for it?

Python requires recipes that should only contain python code, so there is no need to `conan create` them. A `conan export` should be enough.

> Also this statement confuses me a little :
python-requires cannot use regular requires or build_requires.

This means that you cannot expand the graph upwards from a `python-require`, but of course, you can have `build-requires` and `requires` in your "base" conanfile. In other words, you can have a base conanfile in a `python-require` that declare `requires` and `build-requires` but you cannot actually have `build-requires` or `requires` required from a `python-require` (Not sure if this clarifies something 🤣).

Anyway, if you are not able to reproduce it manually it will be hard for us to take a look at the issue but I will try to see if I can come up with a scenario that triggers this behavior.

**Comment by sd185233** [comment] 2021-05-13 10:28
Hi

I work alongside @at185190 

In relation to Azure, we use self-hosted runners so it's only us using the cache.  Looks like our version is not semver compliant - is this an issue if we are using a different package ID mode?

I believe conan export performs a subset of conan create - although conan export is enough for python requires, are there any ill consequences using create?  At the moment we use a generic template which uses create - can adjust if really required.

After looking into the modes, we believe the following options are probably most suitable for us.

default_package_id_mode=full_package_mode
default_python_requires_id_mode=full_version_mode
full_transitive_package_id=1


From some testing, I can see the modes affect the package ID created.  For example, with the default mode, resolving pkgA shows the same bin hash.

pkgA/1.0.0.1@xxx/stable:9df60ffae65bf2d9eaab4cbb18737eb7d48aad14 - Cache
pkgA/1.0.0.2@xxx/stable:9df60ffae65bf2d9eaab4cbb18737eb7d48aad14 - Cache


However, since we reference the full package in the requires, it will always resolve the package under 1.0.0.2 as we originally expected.

requires = "pkgA/1.0.0.2@xxx/stable"


So are there any circumstances where conan would pluck out the bin with the same hash for a different version?  Trying to ascertain whether or not the default package mode is a problem for us or not.  For some additional background, we have an sdk package which requires several other sdk sub packages.

**Comment by sd185233** [comment] 2021-05-13 10:52
I can see how the package mode would affect this example- 

conan copy pkgA/1.0.0.3@xxx/stable pkgA/1.0.0.4@xxx/stable

Then with the default package ID mode, pointing to pkgA/1.0.0.4@xxx/stable would work OK.  If using full_package_mode then resolving these binary packages would fail because the hash was computed with the full version and user/channel.

What other scenarios is this used in?

**Comment by sd185233** [comment] 2021-05-13 14:36
Ok, after some more testing I can see how the top level package ID is influenced based on which part of the version is updated and if the dependency is direct or indirect, which means a direct dep bin from the cache could get picked up which has been built using expected updated deps.

Not sure it's an issue for us because our build system builds all packages individually upstream to downstream on change, but I think the safest option is to use full package mode as follows - 

default_package_id_mode=full_package_mode
default_python_requires_id_mode=full_version_mode
full_transitive_package_id=1

**Comment by memsharded** [comment] 2024-02-14 22:15
I am closing this ticket as outdated.

Conan 2.0 has changed a lot the defaults for package-id-modes, being more smart and dynamic, considering executables, shared, static and header libraries, so changing the default is probably not necessary in most cases.

The python-requires doesn't seem to be an issue anymore either.

Please create new tickets as necessary for any further question or issue, many thanks!

**Closed as not planned by memsharded** 2024-02-14 22:15 UTC
Labels: type: question, stage: triaging
