### ISSUE TITLE
Stop requiring class properties on recipes

### ISSUE THREAD

**Issue by thejohnfreeman** [conan-io/conan#5410] opened 2019-06-27 15:09 UTC
Conan has the annoying requirement that some attributes *must* be given as "static" class properties instead of instance properties. If I want to lazily compute an attribute with a function, I cannot use the built-in `@property` decorator; I must write my own `@classproperty` decorator that takes advantage of an [accident of Python descriptors](https://github.com/python/mypy/issues/244) (they are intended to return *themselves* when accessed from a class instead of an instance, but I need them to return the value of the attribute). This is not Pythonic. Conan should construct the recipe object before accessing any attributes.

**Comment by memsharded** [comment] 2019-06-27 15:53
This is because there are some things, like the package name or the package version that are class attributes. An instanced ConanFile object will have defined its different values for settings, options, environment, etc, which are particular for a configuration. Until those values are not defined, it is not possible to instantiate a ConanFile object. But there are some "static" properties that are independent of the particular instance, for example the package name, version, the exports, exports_sources, etc. all of them, should be defined and accessible directly from the ConanFile class as static, because they do not use any configuration at all.

If you want to further elaborate on your use case, giving specific details of which one of the attributes you want to do that and why, we might try to think if there is some alternative for that specific attribute, otherwise this cannot be changed, it would be massively breaking.

**Comment by thejohnfreeman** [comment] 2019-06-27 16:25
Long explanation of my use case here: https://jfreeman.dev/blog/2019/06/27/trying-conan-with-modern-cmake:-packaging/

You can see how [even `name` is an "inherited" attribute](https://github.com/thejohnfreeman/autorecipes/blob/master/autorecipes/cmake.py#L165), because the base class knows how to [read it from the `CMakeLists.txt`](https://github.com/thejohnfreeman/autorecipes/blob/master/autorecipes/cmake.py#L35).

**Comment by dribeas** [comment] 2019-07-02 21:21
I also have a use case for both having some of the properties as (member) functions.  In my particular case we have a large number of repos that follow a common pattern, moreover the repository contains the dependencies in an easy to parse file.  The dependencies are in terms of *groups*.  As an example, the public repo [BDE](https://github.com/bloomberg/bde) contains a number of *[groups](https://github.com/bloomberg/bde/tree/master/groups)*. Each group has some metadata that includes other groups on which it depends, this is an example for [bal](https://github.com/bloomberg/bde/blob/master/groups/bal/group/bal.dep).  The dependencies are in terms of *groups*, not repos.

I have created a recipe that builds the whole repo (multiple groups) into binary, and a generic recipe that re-packages into smaller recipes for groups.  My build process, if it worked, would be:

```
$ conan create bde_repo  <version>@<user>/<channel> # builds binary with everything
$ for grp in  `ls groups` ; do conan export repackage $grp/<version>@<user>/<channel> ; done`
```
The problem is that for the `repackage` recipe I need to export the metadata for the *group* that it's building, as that will be used to generate the dependencies for the rest of the steps, and that's not part of the generic recipe.

I am currently working around this by defining the class properties by calling a non-member function and in there pulling the information from the environment:

```
$ for grp in `ls groups` ;
do
    PACKAGE=$grp conan export repackage $grp/<version>@<user>/<channel>
done
```

If I could define the `exports` as a member function, I would not need to use the environment as a back channel to inject which group this recipe is being exported for as I could access it through `self.name`.

**Comment by weatherhead99** [comment] 2019-07-10 07:35
I have a rough workaround for a kind of similar use case (which I can't share the exact code of but will try and write a similar example if anyone is interested), which goes something like this:

I have a conan package called "xBuildUtils" where x is the name of your project/company etc, which is a python only conan package. In this package I define a metaclass, which is able to set static class attributes based on file lookups, etc etc. That metaclass might look something like this:
```
class ProjectCppMeta(type):
    def __new__(cls,name,bases,dct):
        n = super().__new__(cls,name,bases,dct)
        n.generators = "cmake", "virtualrunenv"
        n.settings = "os", "compiler", "build_type", "arch"
        n.version = get_version()
        n.name = get_name()
        return n
```

where `get_version()` and `get_name()` are also defined in this package.

In each conan recipe I can "python_requires" this package, and then use the metaclass in my conan class:

```
pbase = python_requires("ProjectBuildUtils/0.1@me/testing")
class PackageConan(ConanFile, metaclass=pbase.ProjectCppMeta):
        def build(self):
              build_foo()
```

etc etc. This seems to work really well actually

**Comment by thejohnfreeman** [comment] 2019-07-10 16:22
I considered a metaclass as well, but decided against it because:

- It is more cumbersome for users. My solution now is just a normal base class that every beginner knows how to use. It is more difficult for me to write, but easier for my users to use, and I want my solution to do as much of the heavy lifting as possible.
- It doesn't solve the lazy evaluation problem. I don't want to do the expensive file parsing / evaluation unless needed. One can still add descriptors in a metaclass, but it offers no advantage over a regular base class.
- If someone else comes along with their own metaclass-based solution, it cannot be combined with my solution because a class can have only one metaclass.

**Comment by memsharded** [comment] 2019-07-10 17:28
Thanks very much for all the feedback, really appreciated. The pattern that I see is not that directly related to the class attributes by themselves, but related to python inheritance/extensions (and likely python_requires)

The truth is that python_requires are a very complicated feature because of the inversion of control. They need to be resolved at python parsing time, and that is very challenging. 

I agree that metaclasses come with their own challenges too. I am starting to consider and investigate some possibility to recover the inverted control, without requiring users to write metaclasses, but use metaprogramming internally. Looks challenging too, to be honest, but I think worth investigating.

**Comment by weatherhead99** [comment] 2019-07-13 23:06
as regards the complexity of a metaclass solution, I do agree it's complex, but in fact you can just provide a base class which itself has a suitably written metaclass, such that the "end user" (i.e. packager) only has to derive from a base class. This is in fact what I do internally. 

As to the "can't have two metaclasses" problem. Indeed, it's impossible without major (and nasty) hacks in python. But on the other hand, I don't see this as much of a real world problem, because unless and until there's some standardised use of a metaclass in conan itself why would you have to use someone else's metaclass? Even if other recipes use a metaclass it doesn't affect you as far as I can see.

**Comment by dribeas** [comment] 2019-07-14 22:53
@weatherhead99: the solution that I am currently using is similar, except that I use a proper base instead of a metaclass.  But you still need to figure out the name of the conan package through an ad-hoc approach.  In my case I settled for creating a config file that is also exported with the recipe.

But this should be unnecessary.  Conan supports having a recipe without a name or version and passing the name in the command line.  The values from the command line can still be accessed through `self.name` and `self.version`.  Additionally, if `exports` was a function the recipe would have greater control over *when* things are done: I can have the caller generate the configuration file and have the `exports` method "copy" it and then delete the file from the filesystem.

To me the issue with the properties is not as much the how it is rendered but rather *when* it's evaluated and what information is available to do so.  Unless I got it wrong, with the metaclass approach you still don't get access to the recipe name passed in with `conan create recipe NAME/VERSION@USER/CHANNEL`, right?

**Comment by memsharded** [comment] 2019-07-14 23:05
I'd like to summarize here the importance of non inheriting ``name`` and ``version`` fields, in any of their forms from "python-requires":

- Reproducibility is very important. Lockfiles is a very demanded feature.
- A recipe can have a python-require in the form of a version-range or using revisions, then it is able to resolve to different dependencies that can have totally different logic of building, packaging, etc.
- Thus, locking python-requires it is critical for reproducibility, and lockfiles should lock python requires (the released experimental feature in 1.17 already does that)
- The "location" of a package in a lockfile is resolved using its reference that includes "name" and "version".  Depending of such name and version, a recipe will find itself in a lockfile and after locating it will get its locked python requires, will fetch them and will be able to use them.
- It can be concluded that it is a chicken-and-egg problem: we need the name and version for resolving the correct locked python-requires that contains the rest of the logic that the recipe can reuse.
- If we wanted to use logic contained in a python-require, like a ``get_name()`` or ``get_version()`` function, then we could enter an infinite loop:
   1. The declared python-requires could be fetched to obtain a preliminary ``get_name()`` and ``get_version()`` implementation
   2. With that, the reference of the package being built could be obtained
   3. With the reference of the package, enter the lockfile to find the locked python-requires
   4. If the locked versions of the python requires are different than the previous one, fetch them, evaluate them, and re-evaluate name and version based on the new implementations of ``get_name()`` and ``get_version()``
   5 go to 2

Though in many cases the infinite loop will stop because implementation will converge to a value it is not guaranteed at all, and then I would say it is a non desired design.

It seems to me that such chicken-and-egg loop should be broken at some point, it seems that the ``name``, and ``version`` of each recipe should be something totally independent and couldn't use any reusable code from python-requires. I understand it is a small inconvenience, but relying on an eventual convergence doesn't seem the solution to me. 

Please, tell me, what do you think? Thanks for the feedback!

**Comment by thejohnfreeman** [comment] 2019-07-15 20:34
My honest opinion is that `python_requires` is a half-baked solution that is already crippled. For example, if I want to use the [`toml`](https://pypi.org/project/toml/) package in my reusable recipe (which I did), I must demand that my users install the `toml` package into their Python environment, unless and until someone creates a Conan equivalent for the same package. I don't think Conan should go down the road of repackaging all of PyPI.

Instead, I would like to see Conan use pip to install Python dependencies. Then I can package my reusable recipe for PyPI and be done with it. Conan can drop the `python_requires` then.

**Comment by weatherhead99** [comment] 2019-07-15 21:39
I personally disagree. I don't want to be dumping my random internal common conan classes etc into PyPI, so python_requires does exactly what I want.
I agree it would be nice to be _able_ to have whatever python package you want installed, but on the other hand this now requires in principle a "full" python environment for conan users, whereas at the moment it can in principle be distributed as its own binary. 
Unfortunately there isn't an importable pip API  either.

**Closed** 2023-06-25 22:27 UTC
Labels: Feedback please!, stage: triaging
