### ISSUE TITLE
[bug] Conan fails to detect dependencies already installed with apt.

### ISSUE THREAD

**Issue by MaxandreOgeret** [conan-io/conan#12627] opened 2022-11-29 10:47 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: **Ubuntu 20.04**
  * Compiler+version: **gcc 9**
  * Conan version: **Conan version 2.0.0-beta5** installed via pip.
  * Python version: **Python 3.8.10**

### Steps to reproduce (Include if Applicable)

Use `Apt(self).install(...)`

```python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake
from conan.tools.files import load, collect_libs
from conan.tools.system.package_manager import Apt

class MyApp(ConanFile):

#[...]
    APT_RUNTIME_DEPS = ["cmake"]

    def build_requirements(self):
        Apt(self).install(self.APT_RUNTIME_DEPS)
#[...]
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
$ conan install --build="*" -pr:b=default . -c tools.system.package_manager:mode=check

-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[conf]
tools.system.package_manager:mode=check

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


-------- Computing dependency graph --------
ERROR: conanfile.py (MyApp/None): Error in build_requirements() method, line 43
        Apt(self).install(["cmake"])
        ConanException: System requirements: 'cmake' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'

```

Cmake is already installed with apt:

```
$ apt policy cmake
cmake:
  Installed: 3.25.0-0kitware1ubuntu20.04.1
  Candidate: 3.25.0-0kitware1ubuntu20.04.1
  Version table:
 *** 3.25.0-0kitware1ubuntu20.04.1 500
        500 https://apt.kitware.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

```

**Comment by memsharded** [comment] 2022-11-29 11:04
Hi @MaxandreOgeret 

It seems you are using the utility in the wrong method. It should be used inside ``system_requirements()`` only, the ``build_requirements()`` method is exclusively for Conan packages dependencies. 
Please try moving it to that method.

**Comment by MaxandreOgeret** [comment] 2022-11-29 11:12
Hi @memsharded and thanks for your answer. 
The problem is still here with the edited conanfile.py:

```python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake
from conan.tools.files import load, collect_libs
from conan.tools.system.package_manager import Apt

class MyApp(ConanFile):

#[...]
    APT_RUNTIME_DEPS = ["cmake"]

    def system_requirements(self):
        Apt(self).install(self.APT_RUNTIME_DEPS)
#[...]
```

`conan install` log:

```
$ conan install --build="*" -pr:b=default . -c tools.system.package_manager:mode=check

-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[conf]
tools.system.package_manager:mode=check

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


-------- Computing dependency graph --------
Graph root
    conanfile.py (MyApp/None): /home/xxx/conanfile.py

-------- Computing necessary packages --------

-------- Installing packages --------

-------- Installing (downloading, building) binaries... --------

-------- Finalizing install (deploy, generators) --------
conanfile.py (MyApp/None): Writing generators to /home/xxx
conanfile.py (MyApp/None): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (MyApp/None): Calling generate()
conanfile.py (MyApp/None): Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
conanfile.py (MyApp/None): If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/xxx/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.py (MyApp/None): Aggregating env generators
ERROR: conanfile.py (MyApp/None): Error in system_requirements() method, line 43
        Apt(self).install(self.APT_RUNTIME_DEPS)
        ConanException: System requirements: 'cmake' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
``` 

I had a look at how Conan checks if an apt package is installed or not. And the following command gives the expected return value:

```
$ dpkg-query -W -f='${Status}' cmake | grep -q "ok installed"
$ echo $?                            
0
```

**Comment by MaxandreOgeret** [comment] 2022-11-29 11:34
The following conanfile is able to reproduce the error in a fresh `ubundu:20.04` docker container:

```python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake
from conan.tools.files import load, collect_libs
from conan.tools.system.package_manager import Apt
import re


class MyApp(ConanFile):
    name = "myapp"
    version = "0.0.0"
    license = "MIT"
    author = "Maxandre Ogeret"
    url = "n/a"
    description = "n/a"
    settings = "os", "compiler", "build_type", "arch"
    options = {}
    default_options = {}
    generators = "CMakeDeps"
    exports_sources = [
        "include/*",
        "src/*",
        "CMakeLists.txt"
    ]

    APT_RUNTIME_DEPS = ["cmake"]

    def system_requirements(self):
        Apt(self).install(self.APT_RUNTIME_DEPS)
```

Steps:
```
apt update
apt install python3-pip build-essential cmake
pip install conan --pre --upgrade
mkdir myapp && cd myapp
[paste conanfile here]
conan profile detect
conan install --build="*" -pr:b=default . -c tools.system.package_manager:mode=check
```

**Comment by MaxandreOgeret** [comment] 2022-11-29 11:35
The following conanfile is able to reproduce the error in a fresh docker container:

```python
from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMakeDeps, CMake
from conan.tools.files import load, collect_libs
from conan.tools.system.package_manager import Apt
import re


class MyApp(ConanFile):
    name = "myapp"
    version = "0.0.0"
    license = "MIT"
    author = "Maxandre Ogeret"
    url = "n/a"
    description = "n/a"
    settings = "os", "compiler", "build_type", "arch"
    options = {}
    default_options = {}
    generators = "CMakeDeps"
    exports_sources = [
        "include/*",
        "src/*",
        "CMakeLists.txt"
    ]

    APT_RUNTIME_DEPS = ["cmake"]

    def system_requirements(self):
        Apt(self).install(self.APT_RUNTIME_DEPS)
```

**Comment by czoido** [comment] 2022-11-29 11:57
Hi @MaxandreOgeret,

I think the problem is that for `Apt` the default for the check argument is `False`, I think this is something we want to change. Pleas try to do:

```
Apt(self).install(self.APT_RUNTIME_DEPS, check=True)
```

That should solve the problem

**Comment by MaxandreOgeret** [comment] 2022-11-29 12:06
Hi @czoido 
Yes, indeed `check=True` solves the issue.
 
In this case I believe that the real problem here is the misleading error message : 

> ConanException: System requirements: 'cmake' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'

Thanks for your help !

**Comment by czoido** [comment] 2022-11-29 12:10
> Thanks for your help !

Thank you for your feedback!

**Closed as completed** 2023-03-06 17:17 UTC
Labels: stage: triaging
