### ISSUE TITLE
[bug] Regression: PR #8740 breaks adding objects to link through sharedlinkflags

### ISSUE THREAD

**Issue by Vhab** [conan-io/conan#8811] opened 2021-04-15 15:39 UTC
`mimalloc/1.6.7` uses `self.cpp_info.sharedlinkflags` and `self.cpp_info.exelinkflags` to add objects to link.
(Do note, I am not the maintainer of this package, just a user)

https://github.com/conan-io/conan/pull/8740 makes a change that assumes any 'sharedlinkflags' starting with `/` is a msvc flag changes it to `-`.
This breaks absolute unix urls, like a full path to an object, by changing `/some/path.o` to `-some/path.o`.

I'm not sure if this is a regression due to the assumption made in #8740 or due to miss-use of sharedlinkflags by mimalloc. But it's regressed usage of mimalloc which previously worked.

**Comment by memsharded** [comment] 2021-04-15 17:21
Hi @Vhab 

I am not sure either it is a regression or it is an abuse of sharedlinkflags to provide something that is not a flag, but a filename. I'll check the recipe, thanks for reporting.

**Comment by memsharded** [comment] 2021-04-15 18:08
A couple of quick questions:

- This configuration of the recipe (option) is not built by default by ConanCenter, so it is difficult to know if this feature breaks or not in the CI. So far this seems a bit of abuse of the ``xxxlinkflags`` feature to provide a linkage that is not implemented in Conan. Is it possible to fallback to normal static library while we figure out? Because the right approach seems to explicitly model ``self.cpp_info.objects`` or something like that. 
- From https://github.com/microsoft/mimalloc#static-override, to link with that library object, it should be linked as the first object, I am not sure if this really works on consumers side. How are you dealing with it? How are you guaranteeing that it is the first object?

**Comment by memsharded** [comment] 2021-04-15 18:36
Furthermore, it seems the recipe ``test_package`` is not covering this case at all, so it is impossible to reproduce from the repo.

**Comment by memsharded** [comment] 2021-04-15 19:20
Lets revert that PR first: https://github.com/conan-io/conan/pull/8812, and we will take care of the issue that caused that PR later.

**Comment by elqueffo** [comment] 2021-04-15 19:28
> A couple of quick questions:
> 
> * This configuration of the recipe (option) is not built by default by ConanCenter, so it is difficult to know if this feature breaks or not in the CI. So far this seems a bit of abuse of the `xxxlinkflags` feature to provide a linkage that is not implemented in Conan. Is it possible to fallback to normal static library while we figure out? Because the right approach seems to explicitly model `self.cpp_info.objects` or something like that.

It is not possible to use a normal static library while at the same time guaranteeing that the overrides work. This has to be done using an object file.
self.cpp_info.objects would be great, but it doesn't solve the ordering problem below:

> * From https://github.com/microsoft/mimalloc#static-override, to link with that library object, it should be linked as the first object, I am not sure if this really works on consumers side. How are you dealing with it? How are you guaranteeing that it is the first object?

This is why link flags is used, because link flags come before any other object files on the commandline. It's a pretty dirty workaround, but personally i don't see any obvious other ways to do it, unless we can directly modify the object file list.

On windows builds there is a similar problem; somehow we have to guarantee the .lib for the override dll comes first on the commandline, otherwise the overrides will not actually override everything correctly. Currently i deal with this seperately in cmake by setting the linker command.

**Comment by memsharded** [comment] 2021-04-15 20:59
> self.cpp_info.objects would be great, but it doesn't solve the ordering problem below:

It seems difficult to come with an ordering definition for this. If we treat objects that could have transitive dependencies to other objects in dependencies packages, then the rule should be the same as the libs linkage order that is happening now, and objects shouldn't just go before everything else... It doesn't seem possible that we just put the objects first always.

So yes, I don't see at the moment any solution that does not look a workaround and that is general enough. Lets revert this and lets keep thinking about this. All feedback and ideas welcome.

**Comment by czoido** [comment] 2021-04-19 16:25
Closed by: https://github.com/conan-io/conan/pull/8812 merged for version 1.35.2 to be released in a couple of hours.

**Closed as completed by czoido** 2021-04-19 16:25 UTC
Labels: type: bug, stage: triaging
