### ISSUE TITLE
[question] How to resolve a collision between fixed dependency and a that is determined with a range?

### ISSUE THREAD

**Issue by mjimenofluendo** [conan-io/conan#14832] opened 2023-09-27 15:40 UTC
### What is your question?

The selection of versions when there is an accepted range generates a severe problem. For example, in the case of the compilation of the [Pango package](https://github.com/conan-io/conan-center-index/pull/17655), this package has a dependency on the libpng package that supports a range of versions of the [zlib dependency](https://github.com/conan-io/conan-center-index/blob/24e52e90d904d7fc4eec7e4633b68694c5fcde47/recipes/libpng/all/conanfile.py#L95) and selects typically the last one, which does not match the one They have neither glib nor Cairo. It does not allow the compilation to continue.

How do we solve this error by setting the version of the libpng package to a concrete version, setting the range in all libraries, and adjusting everything to the same version?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-09-27 19:29
Hi @mjimenofluendo 

Thanks for your question.

It would be important to know which Conan version do you refer to. Conan 1.X and 2.0 have different capabilities regarding version ranges and conflicts.

Conan 2.0 has some limited capabilities of not conflicting version ranges and fixed versions, when they lie in the valid version ranges, and under some circumstances and graph topologies. Conan does not have a full SAT-solver for the joint compatibility problem of finding the correct set of versions jointly compatible, because it practice it would be an intractable problem for Conan (as every hypothesis in the graph expansion requires downloading from servers, unzipping, python loading, evaluation of the recipe, and there can be a large amount of hypothesis due to multiple recipe revisions and versions for every package). But still the capabilities of Conan 2.0 have improved over 1.X, and some common scenarios will no longer conflict that used to in 1.X.

At this moment, ConanCenter is undergoing some updates to allow version ranges for some libraries like zlib, to remove the version conflicts. The problem is that ConanCenter couldn't have version ranges in the past, so some fixed versions can still be creating some conflicts. This specific zlib situation should be resolved in the following days, and other popular libraries that can cause conflicts too will also gradually converge to the same version ranges to avoid these issues.

Meanwhile, it is possible to force the versions upstream to resolve the conflicts, from your ``conanfile.py``, you can define ``override=True`` requires (over the conflicting one, if zlib is conflicting then adding ``self.requires("zlib/versionIwant", override=True)``, and that should resolve the conflicts, have you tried that?

**Comment by mjimenofluendo** [comment] 2023-09-28 10:21
Hi @memsharded,
You are welcome.

This is with version 2.0 of Conan. Basically, my problem is that the [PR](https://github.com/conan-io/conan-center-index/pull/17655) for the gst-plugins-base recipe is blocked due to issues with incompatibilities in its dependencies.
Then gst-plugins-base has two direct dependencies, libpng, which uses the range "zlib/[>=1.2.11 <2" and pango, which has a dependency called cairo which uses "zlib/1.2.13", as the libpng dependency is processed before and the latest version of zlib is 1.3 and gives a conflict problem with zlib/1.2.13 from cairo that it doesn't have a range.
IHMO, we have as possible ways: revert the change of libpng or add the same range to cairo dependency, or that Conan adapt the libpng dependency version on the fly.

**Comment by AbrilRBS** [comment] 2024-10-07 13:48
The conflicts were resolved back when, sorry that we missed circling back to it. Since then, Conan has released the [`[replace_requires]` profile feature](https://docs.conan.io/2/reference/config_files/profiles.html#replace-requires) to help deal with conflicts/overriding versions in the graph

**Closed as completed by AbrilRBS** 2024-10-07 13:48 UTC
Labels: type: question
