### ISSUE TITLE
[question] Consuming application is linked against libs inside Conan cache?

### ISSUE THREAD

**Issue by starsoup** [conan-io/conan#6768] opened 2020-03-31 14:05 UTC
Hi!

Using Conan 1.21.1
Using conan.cmake utility
Linux/Ubuntu

Now that I was finally able to create a conan package from a module + conanfile.py recipe that can be build successfully by the consuming application I noticed an unexpected result?

In the consuming cmake application I'm using the conan.cmake utility to build and install the conan package the application needs to link against.
This works fine though when investigating the application binary (which runs ok) with "ldd" command I can see that the runtime lib dependencies point to the Conan cache? Not to the exported install directory?

Is the expected behavior?

How to control the conan so that the consuming application would be linked against the exported/installed libraries instead?

```
conan_cmake_run(
    ...
    INSTALL_FOLDER <export_folder>
    ...
)
```

Also I can see that the files created by GENERATORS virtualrunenv and cmake_paths also point to paths inside the Conan cache?

How do I control Conan so that I can create a distributable application package or a distributable library i.e. no runtime dependencies pointing to Conan cache?

**Comment by memsharded** [comment] 2020-03-31 23:27
Yes, this is intended behavior. Conan is mainly designed for development time, not for deployment time. So the generators always point to the packages in the Conan cache. When you use the generators to build an application, it will be using the paths to the Conan cache to link with those libraries.

The install and mainly the ``imports()``, ``deploy()`` and ``-g deploy`` generator functionality are intended to get things copied from the cache to the user folder, but that is a post-build step. It is done after all the linking against the packages that are in the library. 

Some alternatives for the runtime could be:

- Use the local flow. Run ``conan install`` with imports/deploy, to get your dependencies and copy things locally. Point your local build to the local copy and don't rely on the generators information for the build of the final application.
- Do not use RPATHs at all, strip them from the binaries at build time, and rely exclusively on LD_LIBRARY_PATH for runtime execution.
- Use some tools to modify RPATHs directly in binary in your final bundle to point to the RPATHS of the imported artifacts.

In any case, the problem is not exclusive of Conan. Even if Conan does a copy of the libraries, to your user folder when you build your final, lets call it ``MyApp``, those libraries will be in lets say ``/home/myuser/myproject/myapp/libs/*.so``. ``MyApp`` will then contain paths to ``/home/myuser/myproject/myapp/libs/*.so``. But when you deploy your app in the servers, lets say in ``/home/mydeployuser/myapp/libs/*.so`` then, the deploy path will be different too.

The Conan ``virtualrunenv`` can help to define an environment to run the application using the libraries installed in the cache without problems, even if you deploy in a different computer with different paths.

We also have in mind a possible new step while installing Conan packages, to further automate this (as long as possible, as said above, there is no perfect solution). But that will take a very long time, surely at least Conan 2.0.

**Comment by memsharded** [comment] 2023-11-05 16:55
Conan 2.0 has introduced "deployers" that can do a local copy of the libraries to a project folder and point the generators to that copied folder: https://blog.conan.io/2023/05/23/Conan-agnostic-deploy-dependencies.html

Not that this would be recommended for all cases, still the recommended usage for most cases is to use packages from the cache. But for other cases the ``deployers`` of Conan 2.0 will allow it.

I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!

**Closed by memsharded** 2023-11-05 16:55 UTC
Labels: type: question
