### ISSUE TITLE
[bug] CONAN_LOGIN_USERNAME ignored when cached credentials exists for the remote

### ISSUE THREAD

**Issue by odormond** [conan-io/conan#7793] opened 2020-10-02 08:35 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Conan version: 1.26.0
  * Python version: 3.8.2

### Steps to reproduce (Include if Applicable)

```
$ conan user --clean
$ export CONAN_LOGIN_USERNAME=read_only_user CONAN_PASSWORD=ro_user_password
$ conan user
Current user of remote 'foo' set to: 'None' (anonymous)
$ conan upload --force --all test/1.0.0@test/stable -r=foo
1.0.0
Uploading to remote 'foo':
Uploading test/1.0.0@test/stable to remote 'foo'
Compressing conan_export.tgz completed [10 files]
Compressing conan_sources.tgz completed [20 files]
ERROR: test/1.0.0@test/stable: Upload recipe to 'foo' failed: Permission denied for user: 'read_only_user'. [Remote: foo]

ERROR: Errors uploading some packages
$ conan user
Current user of remote 'foo' set to: 'read_only_user' [Authenticated]
$ export CONAN_LOGIN_USERNAME=read_write_user CONAN_PASSWORD=rw_user_password
$ conan upload --force --all test/1.0.0@test/stable -r=foo
1.0.0
Uploading to remote 'foo':
Uploading test/1.0.0@test/stable to remote 'foo'
Compressing conan_export.tgz completed [10 files]
Compressing conan_sources.tgz completed [20 files]
ERROR: test/1.0.0@test/stable: Upload recipe to 'foo' failed: Permission denied for user: 'read_only_user'. [Remote: foo]

ERROR: Errors uploading some packages
$ conan user
Current user of remote 'foo' set to: 'read_only_user' [Authenticated]
```

Conan should check the cached credentials refers to the same user as CONAN_LOGIN_USERNAME and if not re-log-in.

**Comment by memsharded** [comment] 2020-10-02 09:53
Hi @odormond 

I would say this is not a bug, but it is as designed. From the docs:

> You can define the username for the authentication process using environment variables. Conan will use a variable CONAN_LOGIN_USERNAME_{REMOTE_NAME}, if the variable is not declared Conan will use the variable CONAN_LOGIN_USERNAME, if the variable is not declared either, Conan will request to the user to input a username.

So these variables are used in the authentication process. Once you are authenticated and got an auth token, they will not be checked at all, in the same way you are not requested interactively a user/password at every step. These variables are placeholders for user responses to an authentication challenge, not credentials. It is the responsibility of the user to log out (``conan user --clean``, this UI will improve in next Conan major version).

The reason why this shouldn't be checked becomes more evident to me, if you try to extend the rationale to the ``CONAN_PASSWORD`` env-var. If you change it after you have already authenticated, it will not be checked again to authenticate again. That would require Conan to store the password (even an encrypted version of it), in the client side, and we don't want to do that for security reasons, this is the reason we use expirable tokens.

So I'd recommend:
- Doing a ``conan user --clean`` to "log-out" when changing env-vars values
- To use the ``conan user read_write_user -p <password>`` instead of env-vars

Wdyt @czoido @jgsogo ?

**Comment by memsharded** [comment] 2024-11-25 22:59
Closing as responded back then.
If there are any questions or issues, please open a new ticket against Conan 2, thanks for your feedback.

**Closed as completed by memsharded** 2024-11-25 22:59 UTC
Labels: type: question, stage: triaging
