### ISSUE TITLE
Scopes (part 2)

### ISSUE THREAD

**Issue by SumuduLansakara** [conan-io/conan#1009] opened 2017-02-20 07:26 UTC
This issue is partly related to #331 

Say i'm exporting a package recipe. Now conan search gives this.

- mypackage/0.1.0@user/channel

I can install it locally (assume I'm building from source through conan) using following command.

- conan install mypackage/0.1.0@user/channel --build mypackage

Everything works fine up to this point. 

But it doesn't work if i try to pass a scope variable for the above install command. (no scope variable is set there)

- conan install mypackage/0.1.0@user/channel --build mypackage --scope key=value

I'm stuck here without being able to pass a flag that doesn't affect the package integrity. Can you explain this and provide any possible work around if this is the expected behavior.

**Comment by memsharded** [comment] 2017-02-23 22:50
Hi Sumudu,

First, if you are creating packages, I very strongly recommend the ``conan test_package`` functionality. You can get a fully working example with it if you do:

```bash
$ conan new Pkg/0.1@user/channel -t 
$ conan test_package
```

Then, I think the issue is that you have to specify the package you want to apply the scope to, or ALL, like:
```bash
$ conan test_package --scope mypackaeg:key=value
or
$ conan test_package --scope ALL:key=value
```
Please try it, and tell me if it works. (BTW, sorry for the delay in answering this question)

**Comment by memsharded** [comment] 2017-03-10 09:27
Hi @SumuduLansakara ,

Did you manage to try the above? Please tell me if it worked. It seems that we have nothing to do regarding this issue, so I am closing it, but please reopen or comment if necessary. Thanks!

**Closed by memsharded** 2017-03-10 09:27 UTC
Labels: question
