### ISSUE TITLE
[bug] build_policy outdated does not work with alias dependency 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6369] opened 2020-01-15 21:24 UTC
Hello,

I have two packages pkg_a and pkg_b.
For pkg_a, I have an alias `latest`: `pkg_a/latest@user/channel` that always point to the latest version of my package pkg_a.

### Scenario 1:
-  pkg_b depends on `pkg_a/1.0.0@user/channel`
- set build_policy to outdated
- build
=> works as expected: pkg_b is only rebuild if there are change in pkg_b's source code.

### Scenario 2:
-  pkg_b depends on `pkg_a/lates@user/channel`
- set build_policy to outdated
- build
=> Does not work as expected: pkg_b is always being rebuilt even if there are no changes in source code and even if the latest alias was not updated.

### Environment Details (include every applicable attribute)
  * Operating System+version: windows 10
  * Compiler+version: visual studio 2015
  * Conan version: 1.21.0
  * Python version: 3.7

**Comment by jgsogo** [comment] 2020-01-16 14:51
Hi, I'm not able to reproduce your issue, probably I'm missing some information.

 * `liba/0.1` created and available in the cache
 * `libb/0.1` (with `requires="liba/latest"`) created and available in the cache
 * an `alias` from `liba/lates` to `liba/0.1`
 * A consumer application that requires `libb/0.1`

Then, when I run `conan create . consumer --build outdate` I get the expected output:

```
Requirements
    app/version from local cache - Cache
    liba/0.1 from local cache - Cache
    libb/0.1 from local cache - Cache
Packages
    app/version:c6ea46ae8955de152effa725d6d934128d595e67 - Build
    liba/0.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    libb/0.1:c74ab38053f265e63a1f3d819a41bc4b8332a6fc - Cache
```

`libb`, as expected, is retrieved from the cache.

**Comment by boussaffawalid** [comment] 2020-01-17 10:32
@jgsogo you are right! sorry for the noise. 
I tried with a minimal example and it worked as expected.
Apparently something is wrong with my setup.

**Comment by jgsogo** [comment] 2020-01-17 10:43
Great! I'll close the issue then 👍

**Closed by jgsogo** 2020-01-17 10:43 UTC
Labels: stage: triaging
