### ISSUE TITLE
[question] Listing sources URL/hash/commit for all packages?

### ISSUE THREAD

**Issue by mvhv** [conan-io/conan#11386] opened 2022-06-03 06:54 UTC
I'm dealing with some code-clearance requirements and need to provide exact source archives and/or locked commits to satiate our licensing team. Is there a simple way to do this, or is it not supported in any official way?

So far every recipe I've encountered records a link to their source archives in `conandata.yml` so that it's avaliable in the recipe as `self.conan_data["sources"][self.version]` and then consumed by `conans.tools.get()` in `sources()`. I think this is an unofficial standard, am I correct in assuming it's unenforced?

I've written a short script that runs `conan info <conanfile_path> --paths --json <output_path>` and iterates through the output, opening the `exported_path` for each dependency and parsing the `conandata.yml` to collect the source information.

This worked for me but is there a more resilient way to do this? I'm not sure if there's any record of the calls to `conans.tools.get()` that could be used instead? I assume that would be more comprehensive but potentially noisier.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-06-03 16:10
Hi @mvhv 

Yes, using a ``conandata.yml`` file to represent location of third parties is a good place, it is documented and it is also designed with a common format, so it is easier to be read and used by other potential tools. I'd recommend to use it for locating tarballs of sources (when the recipe is not in the same repo than the source).

With regards the mechanism to visit the dependency graph and collect all the dependencies, ``conan info --json`` is good too.
There might be other alternatives, like writing some ``conanfile.py`` with a ``generate()`` method that does this. And certainly Conan 2.0 will have dedicated new tools, like the new deployers or custom commands, that are intended specifically for this purpose, and will provide you with this functionality in a more integrated and elegant way.

There are no "interceptors" or "listeners" to the ``conan.tools.get()`` methods, though we have the "downloads cache" that can actually intercept any download. We have also considered building a feature to automatically cache and register all downloads, so they are stored safely and improve reproducibility (in case the internet source dissapears, for example). This is something that is not in the roadmap at the moment, but might be resumed after 2.0 (what we call 2.X).

**Comment by AbrilRBS** [comment] 2023-12-23 23:27
Closing as solved with Conan 2 and the mentioned methods above. Feel free to reopen if needed, thanks!

**Closed as completed by AbrilRBS** 2023-12-23 23:27 UTC
Labels: stage: triaging
