### ISSUE TITLE
Is Conan server's username case-sensitive?

### ISSUE THREAD

**Issue by laohyx** [conan-io/conan#423] opened 2016-08-25 02:26 UTC
Hi
According to my experiments, conan server's username is force to lower case when logging in, but when checking permissions on uploading packages, it becomes case-sensitive.

So it results in that all user names must be lower-cased. Because logging in needs lower-case, and write_permissions is case sensitive.
This forces user to use lower case username, which is inconvenient and confusing for some teams.
But I think ignoring case when logging in, and being sensitive in checking permission is better.

**Comment by memsharded** [comment] 2016-08-25 09:07
Yes, it is possible, due to different behaviors of case in different OSs, a bug might be possible here. The intended behavior is being case-sensitive, but not allowing user accounts with same spelling but different case. In conan.io it can be handled at registration, but in conan_server, as they are created in the conf file, then it might be possible, and care has to be taken. In which OS are you running your conan_server?

Can you please clarify steps to reproduce a more specific issue?
1. Create user in server.conf, like MyUser
2. Try to upload a package for MyUser
3. It fails...

Thanks very much!

**Comment by laohyx** [comment] 2016-08-26 01:42
Thanks for replying!
My environment:
conan server: 0.11.0, on Ubuntu 14
write_permissions is empty, read_permissions is `*/*@*/*: *`


conan client:  0.11.0, on Windows 10

Steps:
1. Create user in server.conf, like **MyUser**
2. On client, if
　　　a. log in with **MyUser**, it shows "Invalid password or username"
　　　b. log in with **myuser**, it works. go to step 3.
3. Try to upload the package `Foo/0.1@MyUser/stable`. Server says permission denied. Possibly I am trying to upload with **MyUser**, instead of current **myuser**.


Thanks!

**Comment by memsharded** [comment] 2016-08-27 11:46
Thanks for reporting, I have already spotted the issue, the culprit is the underlying library conan is using for parsing server.conf files, ``ConfigParser`` which is converting things to lowercase (including user names) by default. I have submitted a PR to fix it: https://github.com/conan-io/conan/pull/434.

**Comment by laohyx** [comment] 2016-08-29 02:14
Cool, thanks!

**Comment by memsharded** [comment] 2016-08-29 08:47
@laohyx the PR has been merged, so I mark the issue as fixed. In our flow we close the issues when they are validated, so if you are able to try it because you run from sources (develop branch) the server, or you try it when next release is done, please give feedback or close the issue if everything works fine. Thanks!

**Comment by memsharded** [comment] 2016-09-02 12:46
Released in conan 0.11.1, please try and reopen if necessary

**Closed by memsharded** 2016-09-02 12:46 UTC
Labels: fixed
