### ISSUE TITLE
conan install -u not updating indirect aliases

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3947] opened 2018-11-16 11:52 UTC
- Conan Version: 1.7.4

Background:
- There exists a library `libA/1.latest@demo/test` which depends on `libB/1.latest@demo/test`
- I am building a package which depends on libA
- The libraries use `self.requires("...")` for specifying dependency

Scenario:
- I build my package
- Now libB and libA both aliases are updated to newer packages
- I do a `conan install .. -u`, it fetches new libA, but uses older libB alias

I suppose this is because I do not specify libB directly as dependency.  
Am I missing something? Or is this a bug?

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment] 2018-11-16 18:55
At first sight, I think it should work. It could be a bug, yes. We need to take a look.

**Comment by jgsogo** [comment] 2018-11-19 14:05
I've created a test for this issue, but it is working for me (`develop` branch). Is this your use case, @sunj1?

**Comment by jgsogo** [comment] 2018-11-20 11:22
Oh! Sorry, there was a typo in my test. The last checks should be agains `client2` output:

```python
        # Install project again, updated alias
        client2.run("install . -u")
        self.assertIn("me-libA >1.1<", client2.user_io.out)
        self.assertIn("me-libB >1.1<", client2.user_io.out)
```

...and then it works as expected.

**Comment by jgsogo** [comment] 2018-11-20 11:29
Testing it in `release/1.7.4`, it fails, the output from the last `conan install . -u` is: 

```
Downloading conanmanifest.txt

Downloading conanmanifest.txt

libB/1.0@lasote/testing: me-libB >1.0<
Downloading conanmanifest.txt

libA/1.latest@lasote/testing: Retrieving from remote 'myserver'...
Downloading conanmanifest.txt

Downloading conanfile.py

libA/1.1@lasote/testing: Not found in local cache, looking in remotes...
libA/1.1@lasote/testing: Trying with 'myserver'...
Downloading conanmanifest.txt

Downloading conanfile.py

libA/1.1@lasote/testing: me-libA >1.1<
Downloading conanmanifest.txt

Downloading conaninfo.txt

PROJECT: Installing /private/var/folders/yq/14hmvxm96xd7gfgl37_tnrbh0000gn/T/tmpv2ntikfzconans/path with spaces/conanfile.py
Requirements
    libA/1.1@lasote/testing from 'myserver' - Downloaded
    libB/1.0@lasote/testing from 'myserver' - Cache
Packages
    libA/1.1@lasote/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    libB/1.0@lasote/testing:8a4d75100b721bfde375a978c780bf3880a22bab - Cache

libA/1.1@lasote/testing: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'myserver' 
Downloading conanmanifest.txt

Downloading conaninfo.txt

Downloading conan_package.tgz

libA/1.1@lasote/testing: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
libB/1.0@lasote/testing: Already installed!
PROJECT: Generator txt created conanbuildinfo.txt
PROJECT: Generated conaninfo.txt

```

`libA` get updated, but `libB` stays in version `1.0`.

**Comment by jgsogo** [comment] 2018-11-20 11:56
Ok, I will recap it all, sorry for the spam. 

🤕  First of all it looks like recipe timestamp has a precission of seconds, so I need to _sleep_ the process before creating the second alias. This should be fixed.

Given that:

- `develop` works
- `release/1.9.2` works
- `release/1.8.5` works
- `release/1.7.4` works

@sunj1, could your error be related to this timestamp issue? Now I think that [the test is replicating your use case](https://github.com/conan-io/conan/compare/develop...jgsogo:issue/3947?expand=1).

Thanks!

**Comment by sunj1** [comment] 2018-11-21 05:15
Hi @jgsogo , thanks for the verification.

Could you please elaborate on the timestamp effect?

**Comment by jgsogo** [comment] 2018-11-21 15:09
Ok! Let's try it.

What was happening in my test was:

1. Create both versions of library A:
   ```
         client.run("create . libA/1.0@lasote/testing")`
         client.run("create . libA/1.1@lasote/testing")`
   ```
1. Create and upload alias for oldest version:  
   ```
        client.run("alias libA/1.latest@lasote/testing libA/1.0@lasote/testing")
        client.run("upload libA* --all --confirm -r=myserver")
   ````
   Conan will add a timestamp to this alias; this timestamp is in Unix format so the resolution is up to seconds.

1. Install the project (first time): `client2.run("install .")`

1. Create the alias for the newest version

   ```
        client.run("alias libA/1.latest@lasote/testing libA/1.1@lasote/testing")
        client.run("upload libA* --all --confirm -r=myserver")
   ````

   Once again, it will have a Unix timestamp associated, this can be happening in the same second as the one before (haven't seen it in production, but maybe it is your case).

1. Try to update the project

   ```
        client2.run("install . -u")
   ```
   This project is already using an alias, it checks for a newer one, but finds that it is in the same timestamp and it doesn't update it.

It's quite difficult to have all of this happening in the same second in a real scenario, so I'm still wondering why it happens to you, and I'm sure that your use-case should be a little different and I'm not reproducing it in my tests.

Thanks!

**Comment by sunj1** [comment] 2018-11-22 05:46
Hi @jgsogo ,

I tried to verify the issue with your example and using conan version 1.9.2  
I executed the commands manually and slowly, so timestamp can not be same for any two files.

I could see that `conan install . -u` does not fetch alias from the server if we modify the alias locally.  <-- bug  
This could probably be because timestamp of alias on server is older than timestamp of alias in local conan cache.  
```
cd libA
conan create . libA/1.0@demo/test
conan alias libA/1.latest@demo/test libA/1.0@demo/test
conan upload libA --all --confirm

cd ../libB
conan create . libB/1.0@demo/test
conan alias libB/1.latest@demo/test libB/1.0@demo/test
conan upload libB --all --confirm

conan remove libB -f
conan remove libA -f

cd ../project
conan install .

cd ../libA
conan create . libA/1.1@demo/test
cd ../libB
conan create . libB/1.1@demo/test
conan alias libB/1.latest@demo/test libB/1.1@demo/test
conan alias libA/1.latest@demo/test libA/1.1@demo/test

cd ../project
conan install . -u
```

**Comment by sunj1** [comment] 2018-11-26 05:32
Hi @jgsogo ,

Thanks for the efforts..  
The example is absolutely correct, just that the expected output should be different (if it is agreed upon).  

Since the server has alias pointing to 1.0 versions (we have uploaded 1.0 version alias only), the **expected** output of `conan install . -u` is version **1.0**, as opposed to current behavior where it is **1.1** for the library packages.  

I expect the output to contain **1.0** because I'm instructing conan to fetch alias from the server, instead of relying on the local cache.

**Comment by jgsogo** [comment] 2018-11-26 08:11
Conan will look first in the cache and then go to remotes, as it is said the `help`: `If any requirement is not found in the local cache, it will retrieve the recipe from a remote, looking for it sequentially in the configured remotes.`.

I don't know if there is a way to skip the cache so it will jump straight to the remotes. Let me ping @lasote, he will know more about this.

**Comment by lasote** [comment] 2019-02-12 06:58
Only deleting the cache entry.

**Comment by jgsogo** [comment] 2019-03-28 09:42
Hi! Given the last comments I think that Conan was working as expected, there is no way to bypass the cache.

**Closed by jgsogo** 2019-03-28 09:42 UTC
Labels: complex: medium, priority: high, whiteboard
