### ISSUE TITLE
[question] how to specify `requires`/`tool_requires` for same dependency.

### ISSUE THREAD

**Issue by mattyclarkson** [conan-io/conan#11179] opened 2022-05-05 15:12 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

How does one add a requirement for both build and runtime?

I would like to build `autoconf` so have the following:

```py
    def requirements(self) -> None:
        self.requires(f"perl/5.34.1@{self._channel}")
        self.requires(f"m4/1.4.19@{self._channel}")

    def build_requirements(self) -> None:
        self.tool_requires(f"make/4.3@{self._channel}")
        self.tool_requires(f"m4/1.4.19@{self._channel}")
        self.tool_requires(f"perl/5.34.1@{self._channel}")
```

As `perl`/`m4` is needed for both building _and_ runtime of `autoconf`. However, doing `conan info $PWD/package/autoconf` results in the following:

```
Requires:
    perl/5.34.1@mychannel/testing
    m4/1.4.19@mychannel/testing
Build Requires:
    make/4.3@mychannel/testing
```

This means that the build fails beacause `perl` and the `m4` binaries are not exposed on the `PATH` for the build.

How do I get _both_: expose the requirement to the build _and_ use the requirement at runtime.

I'm using host/build contexts with 1.47 and trying to make my recipes as Conan v2 compatible as possible.

**Comment by mattyclarkson** [comment] 2022-05-05 15:22
Thinking about this more. It actually doesn't make sense to have it as `requires`: it's a tool with a dependency on another tool.

Hence, I would expect this:

```py
    def requirements(self) -> None:
        self.tool_requires(f"perl/5.34.1@{self._channel}")
        self.tool_requires(f"m4/1.4.19@{self._channel}")

    def build_requirements(self) -> None:
        self.tool_requires(f"make/4.3@{self._channel}")
```

That doesn't work though:

```
ERROR: conanfile.py (autoconf/None): Error in requirements() method, line 37
        self.tool_requires(f"perl/5.34.1@{self._channel}")
        AttributeError: 'Package' object has no attribute 'tool_requires'
```

**Comment by memsharded** [comment] 2022-05-05 15:49
Hi @mattyclarkson 

Because ``tool_requires()`` must be inside ``build_requirements()`` method, please try that and let me know.

**Comment by mattyclarkson** [comment] 2022-05-05 18:13
If I just put them in `build_requirements` the _build_ of `autoconf` works but when I go to _use_ `autoreconf` downstream it doesn't work because the `perl` interpreter isn't available.

The dependency doesn't propagate the `perl` tool dependency.

**Comment by memsharded** [comment] 2022-05-05 21:36
Hi @mattyclarkson 

I think the issue is that I don't fully know all the necessary requirements and how those dependencies require each other.
Have you had a look to the recipes in ``conan-center-index``? There you can see for example, that it is possible to depend both as ``requires`` and ``build_requires``:

```python
def requirements(self):
        self.requires("m4/1.4.19")

def build_requirements(self):
        self.build_requires("m4/1.4.19")
```
When using the 2 profiles approach, that will mean 2 different packages in the dependency graph, one for ``m4`` in the "host" context and the other for ``m4`` in the "build" context, they might even have different ``package_id`` if there is some difference in profiles host and build.

**Comment by mattyclarkson** [comment] 2022-05-10 08:40
I'm aware I can list them both. However, the behaviour I'm getting is that the dependency is not added to both the build and host context.

---

```py
    def requirements(self) -> None:                             
        self.requires(f"perl/5.34.1@{self._channel}")           
        self.requires(f"m4/1.4.19@{self._channel}")             
                                                                
    def build_requirements(self) -> None:                       
        self.tool_requires(f"make/4.3@{self._channel}")         
        self.tool_requires(f"m4/1.4.19@{self._channel}")        
        self.tool_requires(f"perl/5.34.1@{self._channel}")      
                                                                
    @staticmethod                                               
    def dump(kind, deps) -> None:                               
        print(f"--- {kind} ---")                                
        for k, v in deps.items():                               
            print(f" - {k.ref.name}/{k.ref.version}: {k.build}")
                                                                
    def build(self) -> None:                                    
        print(self.build_requires)                              
        print(self.dump("host", self.dependencies.host))        
        print(self.dump("build", self.dependencies.build))      
        super().build()                                         
```

That results in:

```
make/4.3@gpu-build+conan/testing (build), m4/1.4.19@gpu-build+conan/testing (build), perl/5.34.1@gpu-build+conan/testing (build)
--- host ---                                                                                                                    
 - perl/5.34.1: False                                                                                                           
 - m4/1.4.19: False                                                                                                             
 - zlib-ng/2.0.6: False                                                                                                         
None                                                                                                                            
--- build ---                                                                                                                   
 - make/4.3: True                                                                                                               
None                                                                                                                            
```

As  you can see `m4`/`zlib` have been set to `build: False` in the dependency tree and are not added to the build context.

They are listed correctly in `build_requires`.

The issue is that the run environment uses the `self.dependencies.build` to create the `conanbuildinfo.txt` files that setup the `PATH` variable to point at the `bin` folders of the dependencies.

As `m4` and `perl` have `build: False` they do not get picked up by the generator and no `conanbuildinfo.txt` is created for them.

This means the build fails due to missing build tools.

I'm not really sure how this was ever intended to work:  the dependencies have the [following attributes](https://github.com/conan-io/conan/blob/1.47.0/conans/model/dependencies.py#L12):

- `build`
- `direct`
- `test`
- `visible`

`build` is used as a boolean between host context and build context so I can't see any way we can list a dependency as _both_.

I would imagine we would want a `host` boolean so that a dependency can have `host: True` *and* `build: True`.

What is happening is:

- `build_requirements` is invoked _before_ `requirements`
- `build_requirements` adds `m4`/`perl` with `build: True`
- `requirements` then overrides `m4`/`perl` with `build: False`
- `conanbuildinfo.txt` is generated from `self.dependencies.build` and misses `m4`/`perl`
- The build fails because `m4`/`perl` aren't on the `PATH` in the build environment

**Comment by memsharded** [comment] 2022-05-10 09:11
Hi @mattyclarkson 

> build_requirements is invoked before requirements

I don't think this is the case, ``build_requirements()`` is evaluated after ``requirements``

I still don't fully get the issue, probably because I still don't get the dependency graph. I think it is time to try to reproduce with a test. You can give it a try yourself, our testing framework should be relatively straightforward, you can see an example below. Or you can provide a full description of the dependencies involved, and we will try to reproduce in a test. The internals of the packages are irrelevant for this case, we only need to know the dependency graph, all package names and relations involved.

```python
def test_tool_requires():
    """Testing temporary tool_requires attribute being "an alias" of build_require and
    introduced to provide a compatible recipe with 2.0. At 2.0, the meaning of a build require being
    a 'tool' will be a tool_require."""

    client = TestClient()
    client.save({"conanfile.py": GenConanfile()})
    client.run("create . tool1/1.0@")
    client.run("create . tool2/1.0@")
    client.run("create . tool3/1.0@")
    client.run("create . tool4/1.0@")

    consumer = textwrap.dedent("""
        from conans import ConanFile
        class Pkg(ConanFile):
            tool_requires = "tool2/1.0"
            build_requires = "tool3/1.0"

            def build_requirements(self):
                self.tool_requires("tool1/1.0")
                self.build_requires("tool4/1.0")

            def generate(self):
                assert len(self.dependencies.build.values()) == 4
    """)
    client.save({"conanfile.py": consumer})
    client.run("create . consumer/1.0@")
    assert """Build requirements
    tool1/1.0 from local cache - Cache
    tool2/1.0 from local cache - Cache
    tool3/1.0 from local cache - Cache
    tool4/1.0 from local cache - Cache""" in client.out
```

**Comment by mattyclarkson** [comment] 2022-05-10 09:41
Thanks for all your help. I can have a look into creating a test case: I'm not familiar with the Conan testing framework but happy to get involved.

Quickly though, I'm curious if this modification to the test case would repro:

```py
def test_tool_requires_and_requires():
    """Testing that a tool can be both a `tool_requirement` and a `requirement`."""

    client = TestClient()
    client.save({"conanfile.py": GenConanfile()})
    client.run("create . tool1/1.0@")
    client.run("create . tool2/1.0@")
    client.run("create . tool3/1.0@")
    client.run("create . tool4/1.0@")

    consumer = textwrap.dedent("""
        from conans import ConanFile
        class Pkg(ConanFile):
            tool_requires = "tool2/1.0"
            build_requires = "tool3/1.0"

            def requirements(self):
                self.requires("tool4/1.0")

            def build_requirements(self):
                self.tool_requires("tool1/1.0")
                self.build_requires("tool4/1.0")

            def generate(self):
                assert len(self.dependencies.host.values()) == 1
                assert len(self.dependencies.build.values()) == 4
    """)
    client.save({"conanfile.py": consumer})
    client.run("create . consumer/1.0@")
    assert """Requirements
    tool4/1.0 from local cache - Cache""" in client.out
    assert """Build requirements
    tool1/1.0 from local cache - Cache
    tool2/1.0 from local cache - Cache
    tool3/1.0 from local cache - Cache
    tool4/1.0 from local cache - Cache""" in client.out
```

I can create a test case in `conans/test/integration/graph/core` but hopefully the above should repro what I'm seeing.

**Comment by mattyclarkson** [comment] 2022-05-10 10:00
OK, it reproduces on my machine with the patch in #11213

`tox -- -k test_tool_requires`

**Comment by mattyclarkson** [comment] 2022-05-11 09:52
> You should use the "build" profile and context, because this is what Conan 2.0 will always use, and is opting-in into the recommended cross-building approach.

Our command for building is:

```
conan create \
  package/autoconf 2.71@ \
  --build=missing \
  --profile:build=default \
  --profile:host=x86_64-linux.3.13.170-gnu.2.19
```

I'd think that would opt-in to the new Conan 2.0 way of building so the issue is certainly on our side, as proved by the fix you did to the test. Looks like it's on me to figure out what on Earth is going on.

**Comment by memsharded** [comment] 2022-05-11 10:27
> I'd think that would opt-in to the new Conan 2.0 way of building so the issue is certainly on our side, as proved by the fix you did to the test. Looks like it's on me to figure out what on Earth is going on.

Yes, definitely, that should certainly trigger the "build/host" contexts, and it should work.
So sure, don't hesitate to re-open or report a new issue if you find what is happening and we can help. Thanks!

**Comment by mattyclarkson** [comment] 2022-05-11 13:47
OK, found it and figured it out 🎉 

In the `test_package` we have:

```py
def build_requirements(self):
    self.tool_requires(self.tested_reference_str)
```

That was a misunderstanding when reading [the docs](https://docs.conan.io/en/latest/devtools/build_requires.html#testing-tool-requires)

What that does is adds the top level package (`autoconf`) in the `build` context.

When the dependencies in `autoconf` are resolved, they all ge put in the `build` context. This means that when the dependencies are updated they overwrite each other due to the ID for the node being calculated with the reference name and the context.

I think the [correct way to do this is](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=tested_reference_str#test-type):

```py
def requirements(self):
    self.tool_requires(self.tested_reference_str)
```

That'll put `autoconf` into the `host` context. I'm not 100% sure if that's the correct thing because the example in [here](https://docs.conan.io/en/latest/devtools/build_requires.html#testing-build-requires):

```py
    def build_requirements(self):
        self.test_requires(self.tested_reference_str)
```

I assume that `test_requires` put the reference string in the `host` context.

I'll have to look around at the best practices here for testing binaries within Conan.

@memsharded thanks for all the help, certainly learnt a lot here and it was totally on us.

It would be pretty cool if we could deny calling the `tool_requires` in `build_requirements` in the test package somehow (unless that is a valid use case...)

**Comment by memsharded** [comment] 2022-05-11 14:04
> I assume that test_requires put the reference string in the host context.

Yes, that is correct, ``test_requires`` put it in the "host" context. As the ``test_package`` is an end consumer, the effect using a regular ``self.requires()`` is identical, as ``test_requires()`` basically what they do is do not propagate downstream.

> It would be pretty cool if we could deny calling the tool_requires in build_requirements in the test package somehow (unless that is a valid use case...)

Yes, that is the issue, this is a valid use case. It is licit to do a ``test_package`` for an executable package tool to be used as ``tool_requires``, like ``cmake`` package. In this case, you want to test it as ``self.tool_requires()`` in the "build" context, because that is how it will be used later.


> @memsharded thanks for all the help, certainly learnt a lot here and it was totally on us.

No problem, very happy to help! :)

**Comment by mattyclarkson** [comment] 2022-05-11 14:19
> Yes, that is the issue, this is a valid use case. It is licit to do a `test_package` for an executable package tool to be used as `tool_requires`, like `cmake` package. In this case, you want to test it as `self.tool_requires()` in the "build" context, because that is how it will be used later.

Well, that is what we did for `autoconf` because it'll be used in the "build" context later. However, doing:

```py
def build_requirements(self) -> None:
    self.tool_requires("autoconf/2.71@")
```

In the test package totally broke the _build_ of `autoconf` because the graph no longer recognises adding the build requirements for `autoconf` into the build context.

This is because [if the node is in the transitive dependencies](https://github.com/conan-io/conan/blob/d3420d64487c127c81b934a01c22cb670078bf29/conans/client/installer.py#L623) it is not apply to the build context. However, because the tool is added in the "build" context, everything listed in both `requires`/`build_requirements` is recognised as a transitive dependency so are not applied.

In the case of `autoconf` with:

```py
    def requirements(self) -> None:
        self.requires(f"perl/5.34.1@{self._channel}")
        self.requires(f"m4/1.4.19@{self._channel}")

    def build_requirements(self) -> None:
        self.tool_requires(f"make/4.3@{self._channel}")
        self.tool_requires(f"m4/1.4.19@{self._channel}")
        self.tool_requires(f"perl/5.34.1@{self._channel}")
```

Both `perl` and `m4` are recognised as transitive in the build context because they're in `requirements`. The only thing that is applied is `make` because that isn't seen as a transitive. The build fails because `m4`/`perl` are not found in the build context.

Should it actually be like this?

```py
    def requirements(self) -> None:
        self.tool_requires(f"perl/5.34.1@{self._channel}")
        self.tool_requires(f"m4/1.4.19@{self._channel}")

    def build_requirements(self) -> None:
        self.tool_requires(f"make/4.3@{self._channel}")
        self.tool_requires(f"m4/1.4.19@{self._channel}")
        self.tool_requires(f"perl/5.34.1@{self._channel}")
```

**Comment by memsharded** [comment] 2022-05-11 15:38
I think I am a bit confused again 😅 

In Conan 1.X the ``self.tool_requires()`` inside ``requirements()`` wouldn't be valid.

It sounds like there still could be some failure mode that I am missing, do you think it would be possible to reproduce what you are commenting in the test in your PR in https://github.com/conan-io/conan/pull/11213?

**Comment by mattyclarkson** [comment] 2022-05-18 19:21
> In Conan 1.X the self.tool_requires() inside requirements() wouldn't be valid.

Yeah, I was being stupid, sorry.

> It sounds like there still could be some failure mode that I am missing, do you think it would be possible to reproduce what you are commenting

I've created what I think is a reproduction in [02aa02b9](https://github.com/mattyclarkson/conan/commit/02aa02b953c2374fcd1ee9e51ec745af4b9b1588). Haven't updated the PR but you're free to take ownership/copyright of that patch if it leads you towards a fix.

`test_tool_requires_with_test_and_tool_requires` should fail
`test_tool_requires_with_test_and_test_requires` should pass

I'm using `tox -- -s -k test_tool_requires_with_test conans/test/integration/graph/core/test_build_requires.py`

The failure I get is:

```
E           ERROR: consumer/1.0: Error in generate() method, line 16
E               assert len(self.dependencies.build.values()) == 4, tuple(d.ref for d, _ in self.dependencies.build.items())                                                                           
E               AssertionError: (tool3/1.0#f3367e0e7d170aa12abccb175fee5f97, tool2/1.0#f3367e0e7d170aa12abccb175fee5f97, tool1/1.0#f3367e0e7d170aa12abccb175fee5f97)
```

The `tool4/1.0` is missing which is lised in both `build_requirements` and `requirements` which is what were hitting.

I did go down the rabbit hole trying to debug this and ended up in [conans/client/installer.py](https://github.com/conan-io/conan/blob/5b4f1494af61ff407b20f2195764fbcfa4210444/conans/client/installer.py#L610) trying to figure out why the package listed in both functions isn't recognised as a build dependency.

The result was the when the `tool4/1.0` is added as a `build_requirement` the `requirements` get added to the `build` context with `build: False`.

What my (limited) understanding led me to think was this:

* test package adds dependency as `tool_requires`
* `build_requirements` gets invoked
* the `tool_requires` get added to the dependency graph as `(ref, "build")` (i.e. build context) with `build: True`
* `requirements` gets invoked
* the `requires` get added to the depenency graph as `(ref, "build")` (i.e. build context) with `build: False`
* because the _context_ matches, they overwrite the previous build requirements so `tool4/1.0` ends up in the `build` context with `build: False`

In the case of adding the dependency with `test_requires`, the `requirements` get added in the `host` context so do not overwrite the `build_requirements` (as the dependencies are keyed on the reference _and_ context).

I feel that there could be an easy fix 🤞 We current key on the `(ref, context)` in the dependency map. If we add what stage they came from `(ref, context, stage)` (i.e `build_requirements`/`requirements`) then have the same context for both `requirements` and `build_requirements` would not conflict.

So the map currently is keyed on `(Ref("tool4/1.0"), "build")` (which ends up getting overwritten), however, it would get added as `(Ref("tool4/1.0"), "build", "requirements")`/`(Ref("tool4/1.0"), "build", "build_requirements")`. Then the normal closures would work because we would retain the `build: True`/`build: False`.

If you want, I'd be entirely happy to have a video call to discuss and screen share the real world problem we're seeing, if that would help.

As a side note: would be nice if the code used `pathlib.Path` rather than `os.path` in v2 😄

**Comment by memsharded** [comment] 2022-05-19 14:16
Thanks for your super detailed analysis, including the 2 complete tests reproducing. That was very helpful.

One important note: In Conan 1.X, when using the ``self.tested_reference_str`` inside ``build_requirements()``, you want to add the ``test_type = "explicit"`` attribute, otherwise that tested reference will also be added as a regular requirement of the ``test_package``, and you probably don't want that.

It is true that the behavior when using the ``tool_requires`` and ``tool4`` collapses into a single "host" one when using ``tool_requires`` is incorrect. However, I have been following the same steps as you did, and thinking about what you comment:

> I feel that there could be an easy fix 🤞 We current key on the (ref, context) in the dependency map. If we add what stage they came from (ref, context, stage) (i.e build_requirements/requirements) then have the same context for both requirements and build_requirements would not conflict.

And I am afraid that this is far away from being an easy fix. It might look like that the implementation is not difficult, but actually it seems to me that this is a high risk change, and a rabbit hole fix and it would not be the best course to enter it.
As it might be workarounded by avoiding the ``test_package`` for these complex scenarios, it is most likely not worth the effort at this moment.


The good news is that this has been solved by 2.0, I have ported the tests there, check https://github.com/conan-io/conan/pull/11309, and it seems to be implementing the right behavior. It would be fantastic if you could verify that.

**Comment by mattyclarkson** [comment] 2022-05-19 15:30
> you want to add the `test_type = "explicit"` attribute

Sorry, missed that from the test. We _do_ have that on our internal test packages.

> I am afraid that this is far away from being an easy fix

Shows my lack of understanding in Conan 😅

> As it might be workarounded by avoiding the `test_package` for these complex scenarios

That's not really the issue. The issue is when the package is used by other packages a `tool_requires` it breaks in the same way as the `test_package` this makes tools that have the same tools in `requires`/`build_requires` a blocking issue in v1. We literally cannot use the tools in our package stack.

> The good news is that this has been solved by 2.0

That is good news and we want to move to Conan 2.0 (even if it is in alpha), however, as far as I know [GitLab doesn't support the v2 protocol in their package repository](https://gitlab.com/gitlab-org/gitlab/-/issues/333033) which we use 😞

That is the blocking issue with moving to Conan 2.0. I failed to even get the authentication to work.

**Comment by memsharded** [comment] 2022-06-13 10:44
Hi @mattyclarkson 

I am moving forward https://github.com/conan-io/conan/pull/11309 tests for the next 2.0-beta (to be released soon), which will close this issue. Unfortunately, I haven't managed to port back to 1.X any reasonable approach.

The only workaround that I can think now in 1.X is to do some kind of abuse of ``tool_requires``, or maybe even ``private`` dependencies. It might also be possible to do a full "embedding" of some tool (lets say that "autoconf" requires as a tool "perl", then do not model it at all, just make the autoconf ``build()`` method to download perl from somewhere and apply it on the fly), to break the dependency graph. Or even doing a "re-package" on the user side. If you want to explore this approach, please open a specific issue for it, summarizing the expected/desired dependency graph for those packages (autotoconf, m4, perl, etc)

**Comment by franramirez688** [comment] 2022-06-13 11:51
Closed by https://github.com/conan-io/conan/pull/11309

**Closed as completed by franramirez688** 2022-06-13 11:51 UTC
Labels: stage: triaging

**Comment by mattyclarkson** [comment] 2022-06-14 11:14
We're gonna move to 2.0 and live on the edge 🚀 Thanks for all the help here.

**Comment by memsharded** [comment] 2022-06-16 08:22
Great. Keep tuned for beta.1 very soon!
