### ISSUE TITLE
"deploy" generator

### ISSUE THREAD

**Issue by lasote** [conan-io/conan#4874] opened 2019-03-29 14:16 UTC
Create a builtin generator “deploy” that will copy the contents with the following structure:
```
install_folder/libA/include
install_folder/libA/bin
…
install_folder/libB/include
install_folder/libB/bin
```
The “output_folder” and the way to create a custom one should be documented also.

Look at the "deploy" project to review how many of them could be closed.

**Comment by danimtb** [comment] 2019-04-03 08:03
Duplicate of #4847

**Closed** 2019-04-03 08:04 UTC
Labels: complex: low, priority: high, stage: queue, type: feature
