### ISSUE TITLE
conan_api.py stability guarantees?

### ISSUE THREAD

**Issue by datalogics-kam** [conan-io/conan#3720] opened 2018-10-10 15:18 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Got a question here: What can we expect for `conan_api.py` stability? In the middle of fixing the `remote` to `remote_name` upload argument problem we have in some enhanced Conan code at our office, 1.8 dropped, and the `force` argument is gone.

Right now, I'm using `conan=~1.7` for a version in `Pipfile`. How closely would I have to pin things to avoid API changes? `conan=~1.8.1`? Or do I have to absolutely pin it at `conan==1.8.1`?

**Comment by memsharded** [comment] 2018-10-10 15:29
HI @datalogics-kam 

We use the patches for bug fixes and regressions. So 1.8.X should be changing anything for all X in the conan_api.py interface, unless it is a bug, which is very unlikely.

Besides that, yep, there are currently no conan_api stability guarantees, although we try not to break it badly, it may still suffer some changes. They should be big, like you saw, some new arguments, some argument renaming, or droping some argument, not like a full overhaul of it.

**Comment by datalogics-kam** [comment] 2018-10-12 14:16
Thanks for getting back to me! I'm going to set to `conan=~1.8.2` for our Conan dependency.

**Comment by uilianries** [comment] 2019-05-22 12:15
Hi! Is there any prevision for Conan API 1.0?

Maybe we could put some version (0.x) to define new changes. Actually it sounds weird, because Conan is 1.15.x, but the API, which is part of Conan, is unstable because is not documented yet.

The problem that I see is both API and Conan client are in the same project, but they are different things. Sometimes users only want to use the API, or the client, but they need to update the client, because of new features or hotfix, but they aren't sure about the API and vice versa.

Probably in the future we will have a stable version, but again the consumer only interested in the API, will need to update the entire client to have new updates. Sometimes I think both client and API should be separated things, like 2 projects, to flexibilize the versioning, but I'm not sure about this design and it will be one more python package to care about (more work to be done).

**Comment by memsharded** [comment] 2022-08-25 23:48
the python api will be released in 2.0, publicly documented, and stabilized in 2.X

**Closed by memsharded** 2022-08-25 23:48 UTC
Labels: type: question
