### ISSUE TITLE
[bug] MSVC toolchain integration is broken with short paths

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#15784] opened 2024-02-29 15:02 UTC
### Environment details

* Operating System+version: Windows 10
* Compiler+version: msvc 192
* Conan version: 1.63.0
* Python version: 3.8.10

### Steps to reproduce

- Create a minimal C++ test project
- Enable short paths with `CONAN_USE_ALWAYS_SHORT_PATHS=1`
- Run `conan create . -pr:h msvc_192 -pr:b msvc_192 --build missing`
- Run `conan copy --all pkg/1.0.0 user/channel`

I used the following profile (`msvc_192`):
```
[settings]
arch=x86_64
build_type=Debug
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=192
os=Windows
```

It seems that the `msvc` compiler generates two package folders with different hashes in the user home cache (one has a broken short path link) whereas the `Visual Studio` compiler generates only one.

### Logs

```
Copied sandbox/0.1 to sandbox/0.1@asaljo/testing
Copied sources sandbox/0.1 to sandbox/0.1@asaljo/testing
Traceback (most recent call last):
  File "C:\Users\asaljo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\conans\client\command.py", line 2225, in run
    method(args[0][1:])
  File "C:\Users\asaljo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\conans\client\command.py", line 1253, in copy
    return self._conan.copy(reference=reference, user_channel=args.user_channel,
  File "C:\Users\asaljo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\conans\client\conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "C:\Users\asaljo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\conans\client\conan_api.py", line 903, in copy
    cmd_copy(ref, user_channel, packages, self.app.cache,
  File "C:\Users\asaljo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\conans\client\cmd\copy.py", line 29, in cmd_copy
    package_copy(ref, user_channel, package_ids, cache, user_io, short_paths, force)
  File "C:\Users\asaljo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\conans\client\cmd\copy.py", line 79, in package_copy
    shutil.copytree(package_path_origin, package_path_dest, symlinks=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\.conan\\f350de\\1'

ERROR: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\.conan\\f350de\\1'
```

**Comment by memsharded** [comment] 2024-03-01 00:39
I managed to temporarily reproduce this.
Then I cleared my cache, including my short_paths cache, and now I cannot reproduce anymore.

Can you please try to also remove your cache and your short-paths cache and try again?

**Comment by jasal82** [comment] 2024-03-01 07:57
I tried multiple times with both caches cleared in between. It was always broken.

**Comment by jasal82** [comment] 2024-03-01 12:02
The problem is definitely related to that second package folder in `.conan/data/sandbox/0.1/_/_/package/`. Why is that created only in the short path mode and what is it for? If I only build one configuration, then I would expect only one package ID to be generated.

**Comment by jasal82** [comment] 2024-03-01 12:10
The additional folder contains a `.conan_link` which points to a folder in the short path cache. That target folder does not contain a `\1` subfolder which causes that error message. It only contains a `real_path.txt` with a backlink to that superfluous package folder in the normal cache.

**Comment by memsharded** [comment] 2024-03-01 18:41
I have managed to reproduce and understand what is happening.

It is an alignment of multitude of factors:

- Forcing ``CONAN_USE_ALWAYS_SHORT_PATHS=1``. It doesn't happen if this is not defined
- Using the ``compiler=msvc`` that internally does a binary compatibility to ``compiler=Visual Studio`` equivalent
- Doing the ``--build=missing`` for ``conan create``
- Doing a ``conan copy`` after all of that.

Then some possible immediate workarounds would be (just 1 of this would be enough):
- Do not force always the short-paths via env-vars, but rely on recipes to declare the ``short_paths`` attributes themselves.
- Use the ``compiler=Visual Studio`` or deactivate the internal binary compatibility with ``core.package_id:msvc_visual_incompatible=True`` in the ``global.conf`` file.
- Use ``conan create`` without the ``--build=missing``
- Avoid the ``conan copy`` altogether, at the end of the day this is not recommended anymore since quite some time now.

I am looking for an appropriate fix for this, but I have spent already many hours in this, and it doesn't look easy and might have some risk.

**Comment by jasal82** [comment] 2024-03-01 20:08
Thank you for the thorough investigation. I think it is enough to have a plausible explanation for the behavior and a suitable workaround. Disabling VS/MSVC compatibility seems to be the best solution in our context.

**Comment by memsharded** [comment] 2024-03-01 20:10
> Thank you for the thorough investigation. I think it is enough to have a plausible explanation for the behavior and a suitable workaround. Disabling VS/MSVC compatibility seems to be the best solution in our context.

Sounds good, thanks for the feedback.

I have come up with a 1 line change potential solution, it is passing tests, but I am analyzing other possible risks and impact of the change beyond the tests. I'll report on Monday about progress.

**Comment by fischjo3SICKAG** [comment] 2024-03-08 06:49
I've tried one of the suggested workarounds. Calling `conan config set core.package_id:msvc_visual_incompatible=True` followed  by calling `conan create ...` still creates two package folders. I cannot exclude that I did something wrong/different, but checking my command line calls and cache did not offer any further clue to me. Could anyone try this workaround too?

**Comment by jasal82** [comment] 2024-03-08 08:16
The setting must go into the `global.conf` file, then it's working fine. I'm wondering why there is no CLI interface for setting `global.conf`, something like `conan config set --global`.

**Comment by fischjo3SICKAG** [comment] 2024-03-08 08:18
@jasal82 Thanks for your help! Now workaround works as expected.

**Comment by jasal82** [comment] 2024-03-08 08:31
Unfortunately this setting cannot be applied in profiles (why is that?), so it is a global opt-out. But we don't want to opt-out globally, we just want to fix our pipeline and the local build scripts. Since there is also no CLI way of setting/unsetting we cannot dyamically set it as a workaround.

Removing `conan copy` is not an option without a viable alternative. There is also no indication in the 1.63 documentation that the command is deprecated. Short paths are required and we cannot set them from the recipe since it is a pipeline workaround. And `--build missing` must be kept as well for different reasons.

@memsharded So we are back to square one and are now waiting for your patch, which will hopefully work.

**Comment by jasal82** [comment] 2024-03-18 08:24
@memsharded Any update here?

**Comment by jasal82** [comment] 2024-04-02 08:56
We are now setting the flag globally and accepting a rebuild for all packages. This means that a fix is no longer necessary.

**Comment by memsharded** [comment] 2024-04-15 09:45
Thanks for the update and the effort @jasal82, very appreciated.

Closing the ticket then (solved in Conan 2)

**Closed as completed by memsharded** 2024-04-15 09:45 UTC
