### ISSUE TITLE
[bug] add possibility to override default_options

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#11487] opened 2022-06-20 08:42 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Any
  * Compiler+version: Any
  * Conan version: 1.49.0
  * Python version: Any

### Steps to reproduce (Include if Applicable)
relates to https://github.com/conan-io/conan-center-index/pull/11154
Please, try to build a recipe from this MR:
cd recipes/sentry-native/all
conan create . sentry-native/0.4.17@test/test
conan inspect sentry-native/0.4.17@test/test

**Comment by memsharded** [comment] 2022-06-21 07:49
Overriding options assignment from downstream is working now in 2.0. Adding a test in https://github.com/conan-io/conan/pull/11497 that verifies this explicitly.

**Comment by AndreyMlashkin** [comment] 2022-06-21 07:56
The issue is about default_options. Options override works in conan 1.49.0 as well

**Comment by memsharded** [comment] 2022-06-21 08:08
Yes, that is true. 
But what is the issue then? Why settings the options is not enough? At the end, the ``default_options`` are only used to initialize the value of the options, if setting the option value works, what is the problem?

**Comment by AndreyMlashkin** [comment] 2022-06-21 08:15
Take a look at the related issue.
Sentry uses different backends:
crashpad, breakpad and inproc. Some of them are only available on Linux, some on Windows and some on Android.
It is much more convinient to have a recipe, that has valid default options, rather then force user to override them.

**Comment by memsharded** [comment] 2022-06-21 08:19
But the user is not forced to override them. The ``config_options()`` and setting ``self.options.backend = "crashpad"`` does the work fine, and the option has different values for different platforms, without user needing to override them. It is validated in the test in https://github.com/conan-io/conan/pull/11497, if nothing specified from downstream it has the right value.

If it is for the output of ``conan inspect``, that would be irrelevant, because ``conan inspect`` does not use profiles and it does not evaluate settings and options, so neither the ``default_options`` nor the ``options`` values can be conditioned on different settings for ``conan inspect``.

**Comment by AndreyMlashkin** [comment] 2022-06-21 08:57
Android can only use inproc backend. If you're compiling sentry for Android, you are forsed to override backend to inproc.

What I haven't mentioned is that in my proprietary recipe, I override (hardcode) sentry backend. But my override in a dependent recipe does not have an effect, as sentry hardcodes it to another value, which seems to have higher priority.

**Comment by memsharded** [comment] 2022-06-21 13:04
> What I haven't mentioned is that in my proprietary recipe, I override (hardcode) sentry backend. But my override in a dependent recipe does not have an effect, as sentry hardcodes it to another value, which seems to have higher priority.

This is exactly what I meant. This should have been fixed by Conan 2.0, because we changed this priority. It would be good to reproduce and capture in a explicit test.

**Comment by memsharded** [comment] 2022-06-21 13:41
I have been able to reproduce the failure in Conan 1.X, and updated the test in https://github.com/conan-io/conan/pull/11497.

It is true, in Conan 1.X, the definition of options of dependencies in recipes has higher priority than the downstream. This has been fixed in 2.0.

**Comment by AndreyMlashkin** [comment] 2022-06-22 10:45
@memsharded is there any plan to allow overriding default options in conan 1.x.x or conan 2?
sentry recipe really needs this feature, as there is no other way to build upstream logic with conan otherwise: 

https://github.com/getsentry/sentry-native#:~:text=README.md-,Official%20Sentry%20SDK%20for%20C%2FC%2B%2B,Supports%20Sentry%2020.6.

![image](https://user-images.githubusercontent.com/3842441/175010784-32d8a6fe-1639-4046-a1e6-79880775081f.png)

**Comment by memsharded** [comment] 2022-06-22 12:17
Hi @AndreyMlashkin 

Conan 1.X and Conan 2.0 allow overriding options, and conditionally set ``self.options.backend=xxx`` inside ``config_options()``. That is good enough to implement all the behaviors regarding the initial values of ``options``. It is not necessary to override ``default_options``, because ``default_options`` doesn't exist in the Conan model. You cannot do ``self.default_options["..."]`` in your ``build()`` or ``package()`` method, because those values are irrelevant, and not reflect any real value. The only thing that exists is the ``self.options``, and ``default_options`` is a simple mechanism to initialize the ``self.options`` values. But ``config_options()`` can define those values too perfectly, conditioned to settings.

The only problem that exists is in Conan 1.X, the overriding priority from downstream. As the test contained in https://github.com/conan-io/conan/pull/11497 proves it, this is fixed in Conan 2.0, and it will be possible to implement any default initial values in recipes with ``self.options.backend=xxx``, with the right overriding as necessary from dowstream.

**Comment by AndreyMlashkin** [comment] 2022-06-22 13:10
I can change this ticket from [bug] to [Feature Request], but it will stay about the same: allowing to override default options. Include it to conan model, if needed (I am not so familiar with conan-client implementation).

Default options are indeed not relevant in build() or package().

Maybe it does not fit to the current architechture and you don't want to implement it, as it would look ugly and not fitting, but from perspective of conan-recipes developer and user, I think, this would be a useful feature to have

**Comment by memsharded** [comment] 2022-06-22 13:18
We need to understand the value proposition beyond "overriding default options". What problem is being solved here? Can you provide a very simple, unittest, similar to #11497, that illustrate the need for this? Why overriding options values is not enough? It is not that we don't want to consider it, is that we don't see at all why this is necessary. You agree that ``Default options are indeed not relevant in build() or package().``, if they are not relevant, what is the use case?

**Comment by memsharded** [comment] 2022-07-08 08:31
This has been closed by test in https://github.com/conan-io/conan/pull/11497, for Conan 2.0. Overriding options from downstream consumers will now always be possible and have priority.

**Closed as completed by memsharded** 2022-07-08 08:31 UTC
Labels: stage: triaging
