### ISSUE TITLE
Linux package upload makes Windows one outdated from recipe

### ISSUE THREAD

**Issue by db4** [conan-io/conan#2997] opened 2018-06-05 15:28 UTC
I have a package that is built by Gitlab CI for Linux/Windows and then uploaded to an internal Artifactory Community Edition server (6.0.1 if it matters). The problem is that when the Linux package is uploaded , the Windows one becomes outdated from recipe and vice versa. Looks like it's due to different line endings in `conanfile.py` (Windows CI uploads it with CRLF while Linux CI with only LF). Is it a bug or just some misconfiguration?

**Comment by memsharded** [comment] 2018-06-05 15:30
No, conan does not change any line ending at all. You need to make sure that when you checkout the recipe sources, you are consistent with line endings. I'd suggest going LF (Linux) always, in all platforms, specially now that it is supported by all editors.

**Comment by db4** [comment] 2018-06-06 09:32
Thanks for the explanation. I've set `core.autocrlf=input` for Windows Git and now all problems are gone. But I still think that EOL normalization of the recipe by conan on export (like Git does) would be quite useful.

**Comment by db4** [comment] 2018-06-06 11:49
> The thing is that normalization is not as easy as it seems, for example for files without extensions.

When conan detects if a package is outdated from recipe, only `conanfile.py` is involved, right? Why not  to always normalize `conanfile.py` to LF on export?

> I am a believer that all text files should normalize to LF

I agree absolutely. The problem is that CRLF (core.autocrlf=true) is default for Windows git. In my case I had to rebuild two Windows docker images with `git config --system core.autocrlf input`. It is not always possible if you use prebuilt CI infrastructure.

**Comment by lasote** [comment] 2018-06-06 12:00
| When conan detects if a package is outdated from recipe, only conanfile.py is involved, right? Why not to always normalize conanfile.py to LF on export?

No, any exported file is checked also.

**Comment by memsharded** [comment] 2018-06-10 21:14
Exactly, the problem is not the conanfile.py, but other possible files that could be in ``exports`` or ``exports_sources``. Files without extensions or files that even with a recognizable extension, modifications are not desired (some data files, for example)

**Comment by danimtb** [comment] 2018-06-20 14:31
I have opened and issue in the docs repo to include this as an answer (probably in FAQ section) conan-io/docs#690

**Comment by tonka3000** [comment] 2018-06-25 13:38
Hey @memsharded ,

I have the same problem from time to time, and i mostly solve it via „all to LF“, but I think it would be great to have an opt-in feature to control the hashing of the exported files including conanfile.py . If this feature is turned on (maybe an definition of an varible is enough), the conanfile writer has to define exatcly which file (fnmatch filter)he/she wants to be independent of the lineending.

Example:
...
name = „test“
exports_sources_ignore_lineending = „myfile*.py“, „*.txt“

Greetings

Tonka

**Comment by danimtb** [comment] 2018-07-10 15:20
would you mind adding your solution to https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine @liberforce? That would be very helpful for other users! 😀

**Comment by liberforce** [comment] 2018-07-11 13:37
Thanks for the link. I'm still trying to get things sorted out, as there are different use cases to consider. If I get anywhere near a final solution, I'll propose the solution.

**Comment by atrelinski** [comment] 2019-10-25 01:14
Could You update https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine by listing which files impact recipe hash?

I've added "conanfile.py text eol=lf" in .gitattributes and the same for all other files listed in "exports" and "exports_sources" in conanfile.py and for all files that may impact any of them. Unfortunately that didn't help.

Finally I had to change to "* text eol=lf" which is very not nice solution.

I really appreciate your help in that matter

**Comment by atrelinski** [comment] 2019-11-02 20:30
Hi @memsharded 
Thanks for Your help.
I confirm that helps.
LICENSE file was not in "exports" neither "exports_sources", but created on the fly in package() method.
Indeed it was mentioned in conanmanifest.txt which helps very much.

Could You update https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine that recipe hash is calculated from files listed in conanmanifest.txt and outdating can be easily prevented by listing those files in .gitattributes by adding "<file from conanmanifest.txt> text eol=lf" for each file?

**Comment by memsharded** [comment] 2019-11-02 21:25
Hi @atrelinski 

Glad that it clarified something. 
I have submitted PR https://github.com/conan-io/docs/pull/1473, if you want to have a look and see if it will help to other users. I have added also the global .git/config solution as well, I think it is simpler and more robust to changes/additions in recipes.

**Comment by atrelinski** [comment] 2019-11-06 19:57
@memsharded 
Change is perfect!
Really professional when additionally proposing solution for the problem!
Thank You

**Comment by memsharded** [comment] 2019-11-12 09:15
Closed by https://github.com/conan-io/docs/pull/1473

**Closed by memsharded** 2019-11-12 09:15 UTC
Labels: type: feature
