### ISSUE TITLE
[bug] Conan fails to download pcre package sources because of "sslv3 alert handshake failure"

### ISSUE THREAD

**Issue by Knitschi** [conan-io/conan#6801] opened 2020-04-06 12:04 UTC
I want to install/build the `pcre/8.41` package on a Debian system and conan seems to fail when it tries to download the source package.

`
pcre/8.41: Configuring sources in /home/knitschi/.conan/data/pcre/8.41/_/_/source
ERROR: Error downloading file https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.41.tar.gz (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))'
`

When I search the internet for the problem it mostly leads to posts that state that this is either an openssl misconfiguration or an openssl bug and in most cases it is sugested to update openssl. However, when I use execute `wget https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz` the download works just fine. 

I think, that this is not really a conan bug, but rather a problem of my system configuration, but I am not sure, what exactly I need to upgrade or where I can change the openssl configuration that is used by conan. 

I would appriciate some hints on where to start looking for the problem.

### Environment Details
  * Operating System+version: Debian 9.8 (stretch)
  * Compiler+version: Gcc 6.3
  * Conan version: 1.24
  * Python version: 3.5.3
  * OpenSSL version: 1.1.0j-1~deb9u1

### Logs 

````
knitschi@DevDebian9:~/dev/BuildCPFAssistant$ conan install -pr Sources/CIBuildConfigurations/ConanProfile-Gcc-debug -if Conan/Gcc-debug Sources --build=missing
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=6.3
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
pcre/8.41: WARN: Package is corrupted, removing folder: /home/knitschi/.conan/data/pcre/8.41/_/_/package/9a5ea7ba05754d0941f422940e73aa8a0713973e
conanfile.txt: Installing package
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
    pcre/8.41 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:2175c272cb152e98eb888b3337a069e8687fc1e7 - Cache
    pcre/8.41:9a5ea7ba05754d0941f422940e73aa8a0713973e - Build
    zlib/1.2.11:6e4a80503669881633a370290b60a1a852920b76 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
zlib/1.2.11: Already installed!
pcre/8.41: WARN: Build folder is dirty, removing it: /home/knitschi/.conan/data/pcre/8.41/_/_/build/9a5ea7ba05754d0941f422940e73aa8a0713973e
pcre/8.41: WARN: Trying to remove corrupted source folder
pcre/8.41: WARN: This can take a while for big packages
pcre/8.41: Configuring sources in /home/knitschi/.conan/data/pcre/8.41/_/_/source
ERROR: Error downloading file https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.41.tar.gz (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))'
Waiting 5 seconds to retry...
ERROR: pcre/8.41: Error in source() method, line 49
        tools.get(**self.conan_data["sources"][self.version])
        ConanException: Error downloading file https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz: 'HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.41.tar.gz (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))'
````

**Comment by memsharded** [comment] 2020-04-08 22:11
Hi @Knitschi 

A couple of questions:
- Does it happen with other packages too? Or it is just this one package, downloading from this specific server?
- Could you try a "pure python" download of that file? Something like:
```python
import requests
r = requests.get("https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz")
open('pcre.tar.gz', 'wb').write(r.content)
```

**Comment by Knitschi** [comment] 2020-05-02 10:48
Sorry for the late response

> Does it happen with other packages too? Or it is just this one package, downloading from this specific server?

I removed my ~/.conan/data directory to force conan to re-download source package. Then I used `conan install ... --build=*` to force a re-build of all packages that the qt package requires.
The conan output then contained output like `Downloading bzip2-1.0.8.tar.gz completed [791.04k]` for other packages before conan runs into the trouble with the pcre package. So downloading from other servers seems to work.

> Could you try a "pure python" download of that file? Something like: ...

I am getting the same error when trying to download the file via python only:
```
knitschi@DevDebian9:~/dev/BuildCPFAssistant$ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> r = requests.get("https://ftp.pcre.org/pub/pcre/pcre-8.41.tar.gz")
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.41.tar.gz (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='ftp.pcre.org', port=443): Max retries exceeded with url: /pub/pcre/pcre-8.41.tar.gz (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))
```
But with the information that conan uses requests to download the source archives I can do some further googeling and see if there are any known problems there.

**Comment by Knitschi** [comment] 2020-05-16 16:53
I worked around the problem by upgrading to Debian 10 (buster). This solved at least the download problem for the pcre package.

**Comment by xahon** [comment] 2021-01-29 17:49
Very unpleasant workaround. I can't upgrade to debian 10 because i have to develop on specific distro
Is there a solution by now?

**Comment by xahon** [comment] 2021-01-29 17:50
@memsharded your code throws the same error for me

**Comment by memsharded** [comment] 2021-01-30 21:50
Hi   @xahon 

If the simple python code with ``requests`` direct download fails, it seems that there is nothing we could do from Conan code, it is not a Conan bug, the underlying infra is not working. I cannot think of other solutions rather than:

- Upgrading debian 10
- Reporting to pcre project about this. It seems their ssl certificates or something are also problematic
- Downloading manually the files from ftp.pcre.org, putting a copy elsewhere and pointing the recipes there.

Any other alternatives or ideas?

**Comment by hanusek** [comment] 2021-12-02 19:19
I have a similar problem:
```
pcre/8.45: Configuring sources in /root/.conan/data/pcre/8.45/_/_/source
ERROR: Error downloading file https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2: 'HTTPSConnectionPool(host='sourceforge.net', port=443): Max retries exceeded with url: /projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))'
Waiting 5 seconds to retry...
ERROR: pcre/8.45: Error in source() method, line 92
	destination=self._source_subfolder, strip_root=True)
	ConanException: Error downloading file https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2: 'HTTPSConnectionPool(host='sourceforge.net', port=443): Max retries exceeded with url: /projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))'

```

**Comment by memsharded** [comment] 2021-12-03 01:08
@hanusek please check the other comment, seems same issue: https://github.com/conan-io/conan/issues/9695

**Comment by SlavaMelanko** [comment] 2022-02-15 18:01
Encountered to the same error today on Windows

Fix was easy - removed `%USER%\.conan\data\pcre` and started from the beginning. No issue anymore

**Comment by AbrilRBS** [comment] 2024-04-22 07:41
Alongside the proposed solutions here, I'd like to also add that Conan 2 has added a few features to help with this:
* The [backup source feature](https://docs.conan.io/2/devops/backup_sources/sources_backup.html) allows you to backup your sources to ensure future reproducibility of builds
* The `tools.files.download:verify` conf can be set to `False` in those cases where it makes sense to avoid system configuration issue (But ensure this makes sense security wise for your specific case!)

Either way, closing as solved in Conan 2, thanks everyone for your input! :)

**Closed as completed by AbrilRBS** 2024-04-22 07:41 UTC
