### ISSUE TITLE
cmake generator produces invalid conanbuildinfo.cmake when there are multiple CPPFLAGS

### ISSUE THREAD

**Issue by kent-at-multiscale** [conan-io/conan#950] opened 2017-02-03 16:20 UTC
I have a package (GoogleTest) that is passing more than one flag to its consumers via `cpp_info.cppflags`. In the generated conanbuildinfo.cmake, the line `set(CONAN_CXX_FLAGS_GOOGLETEST "-DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_LINKED_AS_SHARED_LIBRARY=1")` causes CMake to issue a compilation command of the form:

```make
/longest_path/c++    -isystem /longer_path/include  -stdlib=libc++ -O3 -DNDEBUG -fPIE   "-Wall -Werror -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_LINKED_AS_SHARED_LIBRARY=1" -std=c++11 -o CMakeFiles/main.dir/main.cpp.o -c /long_path/main.cpp
```

It looks like the CMakeFiles/main.dir/flags.make file contains:

```make
CXX_FLAGS =  -stdlib=libc++ -O3 -DNDEBUG -fPIE   "-Wall -Werror -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_LINKED_AS_SHARED_LIBRARY=1" -std=c++11
```

I believe the fix is to remove the double quotes from the generated CMake `set` command.

**Comment by kent-at-multiscale** [comment] 2017-02-03 16:20
This probably applies to all the CMake `set` commands that get used as parameter lists.

**Comment by memsharded** [comment] 2017-02-03 17:01
Are you passing the flags as a list?

```python
self.info.cpp_flags = ["myflag1", "myflag2"]
```

**Comment by kent-at-multiscale** [comment] 2017-02-03 17:47
Yes, I am passing them as a list, not a single string.

**Comment by memsharded** [comment] 2017-02-03 17:58
Quick question: in which way the compilation is failing, what messages are output? I am a bit surprised this hasnt been an issue so far.

**Comment by kent-at-multiscale** [comment] 2017-02-03 18:01
/longest_path/c++    -isystem /longer_path/include  -stdlib=libc++ -O3 -DNDEBUG -fPIE   "-Wall -Werror -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_LINKED_AS_SHARED_LIBRARY=1" -std=c++11 -o CMakeFiles/main.dir/main.cpp.o -c /long_path/main.cpp

I thought it was pretty obvious. It's "all -Werror -DGTEST_USE_OWN_TR1_TUPLE=1 -DGTEST_LINKED_AS_SHARED_LIBRARY=1" is not a valid warning, only in esoteric language. I fixed it on my local system, so I'd have to undo all my fixes to re-create it.

**Comment by memsharded** [comment] 2017-02-03 18:09
Ok, clear, thanks!

**Comment by memsharded** [comment] 2017-02-22 17:17
Fixed and merged to develop, will be released in 0.20. Testing (running from source devleop branch) very welcome.

**Comment by memsharded** [comment] 2017-02-28 00:51
This has been released in 0.20, closing the issue, feedback on the issue appreciated or re-open if necessary. Thanks!

**Comment by memsharded** [comment] 2017-02-28 10:46
Hi @kent-at-multiscale,

It seems that changing this broke some things. My PR in https://github.com/conan-io/conan/pull/1044 adds a new test and in such test, there are no quotes.

I need your feedback here, to debug what could be happening in your case and where the quotes come from:
- Are you using old cmake or ``conan_basic_setup(TARGETS)`` with modern cmake targets?
- Where are the ``--Wall`` and ``-Werror`` flags coming from? I can see them in the output, but not the input.
- If you had a fully reproducible example, that would be helpful.

Thanks very much for your help.

**Comment by kent-at-multiscale** [comment] 2017-02-28 17:54
I will work on reproducing this issue as soon as I have the time. Right now I've worked around it, none of the packages I am working with currently have more than one flag.

**Comment by memsharded** [comment] 2017-02-28 17:59
Ok, thanks for telling. We will be most likely reverting this behavior tomorrow in a minor 0.20.1, as it is breaking the builds from other users, and the provided tests show good behavior so far. You should be able to try to reproduce it with either 0.19.3 or 0.20.1. Looking forward your feedback, thanks again.

**Comment by kent-at-multiscale** [comment] 2017-02-28 18:00
Acknowledged, revert it and fix everybody else. When (or if) I reproduce it again I’ll provide functioning code.
--
Kent Rosenkoetter
Software Developer
Multi-Scale Health Networks

E-mail is not encrypted. Never include protected health information (PHI) in an e-mail.

**Comment by memsharded** [comment] 2017-02-28 18:04
Sure, thanks. I will re-open, remove "fixed" label in case someone else has the issue, and schedule it for 0.21, to make sure we track this.

**Comment by memsharded** [comment] 2017-03-10 09:25
Hi @kent-at-multiscale. Any progress with this? Did the problem ever reproduce? Time is moving, and I would like to make sure we kill this issue in next 0.21. Thanks!

**Comment by kent-at-multiscale** [comment] 2017-03-10 17:00
Yes, I have reproduced it a few times. I will work on getting an example case into GitHub hopefully this weekend.

**Comment by memsharded** [comment] 2017-03-10 17:24
That would be fantastic, thanks! Looking forward.

**Comment by kent-at-multiscale** [comment] 2017-03-10 18:33
https://github.com/kent-at-multiscale/cmake-multiple-flags-bug

**Comment by memsharded** [comment] 2017-03-10 23:57
Great, thank you. I have make a first try, but failed due to some path issues. Might be an issue of the development branch. Will check both things during the weekend.

**Comment by memsharded** [comment] 2017-03-12 21:17
Been able to reproduce and fix it. It happens to be that the IMPORTED INTERFACE target properties, are expecting a list, not a string, while the regular cmake variables for CXX_FLAGS, etc., are ok with strings. I did a conversion and everything seems ok, in this PR: #1096 

If you could from sources in that branch, that would help. In any case, we will add this to the next release, will try to release a RC with enough time, so people can try in advance and make sure we don't introduce regressions.

Thanks very much for your help, really useful!

**Comment by memsharded** [comment] 2017-03-21 16:11
Hi @kent-at-multiscale, I hope we have finally killed this bug. Please upgrade to 0.21 and check if possible. Thanks!

**Closed by memsharded** 2017-03-21 16:11 UTC
Labels: bug, fixed

**Comment by kent-at-multiscale** [comment] 2017-03-21 23:23
I have updated to Conan 0.21 and tested my bug repo, and the bug is fixed. Thank you!

**Comment by memsharded** [comment] 2017-03-22 08:36
Excellent! Thanks to you for reporting, tracking and testing.
