### ISSUE TITLE
ERROR: 'settings.compiler.cppstd' doesn't exist for 'apple-clang'

### ISSUE THREAD

**Issue by agurtovoy** [conan-io/conan#5128] opened 2019-05-11 22:38 UTC
Conan version 1.15.0
Mac OS X 10.14.4 build 18E226

When I ran `conan install ..` in my build folder, I get:

```
build $ conan install ..
ERROR: 'settings.compiler.cppstd' doesn't exist for 'apple-clang'
'settings.compiler' possible configurations are ['libcxx', 'version']
```
Here's my default profile:

```
build $ conan profile show default
Configuration for profile default:

[settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=10.0
compiler.libcxx=libc++
compiler.cppstd=17
build_type=Release
[options]
[build_requires]
[env]
```

Changing `compiler.cppstd` to `cppstd` works, but generates this warning:

```
build $ conan install ..
/Users/user/.virtualenvs/env1/lib/python3.7/site-packages/conans/client/settings_preprocessor.py:28: UserWarning: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd'
  warnings.warn("Setting 'cppstd' is deprecated in favor of 'compiler.cppstd'")
```

**Comment by Johnnyxy** [comment] 2019-05-12 20:53
Hi there,
with version 1.15.0 there was a change to set the C++ standard based on the compiler instead of a general setting. Have a look at the changelog for version 1.15.0 ([see here](https://docs.conan.io/en/latest/changelog.html#may-2019)).

```Feature: Add compiler.cppstd setting (mark cppstd as deprecated) ...```

So using the ```compiler.cppstd``` is future proof at the moment.

To fix your problem you have to check your ```settings.yml``` ([see docs here](https://docs.conan.io/en/latest/reference/config_files/settings.yml.html)). With some Conan updates the ```settings.yml``` gets updated. Sometimes an update cannot be made so Conan creates a new file named ```settings.yml.new```. If you never made any changes to your original file then just delete the current ```settings.yml``` and remove the ```.new``` extension of the other one. This should provide your Conan with the current version 1.15.0 default values.

Or you could just delete the ```settings.yml``` and Conan will create a default one.

**Comment by agurtovoy** [comment] 2019-05-13 01:35
@Johnnyxy Yep, I read the changelog, which is why I'm using `compiler.cppstd` :). 

I did indeed discover that I have both `~/.conan/settings.yml` and `~/.conan/settings.yml.new`, and doing `cp ~/.conan/settings.yml.new ~/.conan/settings.yml` did fix the issue. Thanks!

**Comment by agurtovoy** [comment] 2019-05-13 01:36
I never touched `~/.conan/settings.yml` before this, though, so not sure why it failed to upgrade.

**Comment by memsharded** [comment] 2019-05-13 07:22
Hi @agurtovoy 

Thanks very much for reporting. Yes, it could be a case of a migration that couldn't be executed (custom settings.yml), and then requiring that subsetting in the code. We are investigating, will update as soon as possible.

**Comment by Johnnyxy** [comment] 2019-05-13 07:51
@memsharded 
hi, I saw this behaviour multiple times with Conan-settings.yml-updates. 
On my dev machine it was never a problem as I have a customized ```settings.yml```. But I on other "just conan users/clients" machines with default ```settings.yml``` there where sometimes unsuccessful migrations of new default values like in this case.

So it is already an older issue but maybe it did not emerge that often as the most Conan users are mostly using the default values anyway.

**Comment by memsharded** [comment] 2019-05-13 07:56
Yes, @Johnnyxy you are right. The thing with the settings.yml is that it is difficult to evolve it, and migrate it, when users introduced custom settings. It has been this way since the beginning, and we don't see any good way to improve it, besides trying to be careful for new introduced settings, and internal usage of those settings, try to be fail-safe, keep working even if they are not defined.

**Comment by memsharded** [comment] 2019-05-13 09:28
Ok, I have been reviewing this, and checking if something could be improved. My conclusions:

- This is totally expected behavior, the profile is defining ``compiler.cppstd`` and the ``settings.yml`` didn't define it
- That error can't be removed, it is very dangerous and will lead to inconsistent and buggy behavior (including wrong binary IDs), letting pass some definition in the profile without validation.
- That error is therefore good, totally wanted.
- What it is inconvenient is that the migration was not able to add the ``compiler.cppstd`` subsetting. I agree with that, but it is not possible, at least in the short term to do that, as replacing the user custom ``settings.yml`` would be equally (or even more) destructive and inconvenient.
- The only possible way to improve this would be a smarter algorithm to update ``settings.yml``. As @Johnnyxy commented, the all-or-nothing current approach is far from perfect. This would require a big effort, to implement some kind of merge strategy over the yaml values, and in any case, it will be impossible to get it perfect, as there will always be conflicts and other reasons. This is why this effort hasn't been done yet, seems like the ratio value/effort is low. I will rethink this, and create a new issue to track that if it makes sense, but at first thought, seems a bit unlikely.

I have added a test in https://github.com/conan-io/conan/pull/5130, to consolidate this behavior. That PR will close this issue. 

Thanks very much for reporting and the feedback!

**Closed** 2019-05-13 10:09 UTC
Labels: stage: review

**Comment by agurtovoy** [comment] 2019-05-13 18:05
@memsharded Thanks for the prompt reply! I know you have no way of verifying it, but I never touched my `settings.yml` until I ran into this, so there might be an issue lurking there. 

One possible way to improve the diagnostics here would be to detect the presence of a failed `settings.yml` upgrade and issue a warning on every error that can be traced back to settings. E.g., in my case, instead of what I got, it'd be something like this:

```
build $ conan install ..
ERROR: 'settings.compiler.cppstd' doesn't exist for 'apple-clang'
'settings.compiler' possible configurations are ['libcxx', 'version']

Your custom ~/.conan/settings.yml appears to be behind; please review the newer version at ~/.conan/settings.yml.new and add any missing settings to your current configuration.
```

Or you could introduce a version specifically for the settings file, bump it every time you introduce a new setting, and make conan issue a warning if it's using the older version of the file.

Just my 2c, thanks again!

**Comment by memsharded** [comment] 2019-05-16 16:00
Hi @agurtovoy 

You might have had that issue, because in previous versions there was an issue with the migrations of the settings, that could have failed even for not modified settings.yml. That has been fixed, hopefully it doesn't happen again.
Thanks again for the feedback!

**Comment by daravi** [comment] 2019-06-05 06:22
Not sure if there is a way to check if that is the case for me or not but I also see that my settings.yml file was touched last when I first installed conan but it is giving a `settings.yml is locally modifie` warning when migrating. Maybe have a default settings updated by and managed by conan, and a settings file for overriding the default settings managed by the user?

**Comment by memsharded** [comment] 2019-06-06 17:57
> Maybe have a default settings updated by and managed by conan, and a settings file for overriding the default settings managed by the user?

We have considered this a few times, but it results in the same problem as trying to update the file: the need to be able to smartly merge 2 yaml files in a single one. This is a complicated problem, it seems that some library might help (https://yaml.readthedocs.io/en/latest/overview.html), but merges are difficult by definition, and they will never be perfect. So it seems a big investment for a small improvement and even in that case will not address all cases. This is the reason that so far we have preferred to keep them totally dumb, and failing to the safe side of not modifying/destroying user information. We might revisit this after conan 2.0, but at the moment not a priority. Thanks very much for the suggestion!

**Comment by agurtovoy** [comment] 2019-06-06 22:59
@memsharded IMHO, if conan just showed a warning about a failed `settings.yml` upgrade/the need to merge the settings **when a user runs into an issue** (rather just once on upgrade), it'd eliminate a lot of frustration around this area.
