### ISSUE TITLE
[bug] `conan profile detect` does not detect `compiler.update` for `msvc`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#13329] opened 2023-03-05 10:28 UTC
### Environment details

* Conan version: 2.0.1

### Steps to reproduce

The set of C++ features supported in the MSVC compiler with each new compiler update improves a lot. `validate()` method often will require not just a major compiler version but also at least a specific update version to work correctly on the MSVC compiler (i.e. `mp-units` requires at least 192.8 to compile). By default, `conan profile detect` does not set the update number in the profile, which is a big issue:
- builds with different updates may have a different ABI (Because they will have to use workarounds on earlier versions where C++ specific feature is not supported)
- on the CI like GitHub Actions, it is hard to track which compile update is the current one, so setting it for the build should not be hardcoded in the GitHub-related scripts

**Comment by memsharded** [comment] 2023-03-05 10:59
Hi @mpusz 

I am afraid that this is intentional. Adding the update to the ``profile detect`` would explode the number of combinations that ConanCenter and users have to build and deal with

> builds with different updates may have a different ABI (Because they will have to use workarounds on earlier versions where C++ specific feature is not supported)

Yes, they might have different ABI, but the model in general works very well with forward versions, 99% of the cases is good, this cannot default for the exception case, but for a balanced case

> on the CI like GitHub Actions, it is hard to track which compile update is the current one, so setting it for the build should not be hardcoded in the GitHub-related scripts

Yes, users that will want to detail the ABI compatibility down to the update, will have to specify the update themselves, because as explained above, defaulting to detail the update will be a very bad default for ConanCenter packages and many users

**Comment by mpusz** [comment] 2023-03-05 15:41
Can't it be somehow handled by the `compatibility.py`? I mean that the update would be detected but maybe ignored for most packages? This would however allow using it in `validate()` and other places if needed.

**Comment by memsharded** [comment] 2023-03-05 15:53
Default ``compatibility.py`` cannot explode the configurations to validate either, as the resolution of binaries is linear in the number of hypothesis to check. Needing to check like 10 different updates for every binary will make the resolution of binaries much slower (it would multiply by the number of cppstd configurations to check), so this is not a possibility at the moment. At some point we will try to design and implement a v3 protocol with servers that could resolve this faster, but it will take time. 

I'd suggest that you document that it is necessary to have the latest update of the compiler (I think this is similar to what we do in ConanCenter), and that should be a pragmatic solution, it has worked very well in ConanCenter for a long time.

**Comment by memsharded** [comment] 2024-01-10 10:56
Closing this as not a bug, the default profile detect will not add the ``compiler.update`` for msvc.

https://github.com/conan-io/conan/pull/15435 might make available the update detection via ``detect_api`` for users wanting to automate that in their profiles

**Closed as completed by memsharded** 2024-01-10 10:56 UTC
Labels: type: question
