### ISSUE TITLE
[feature] Please add self.run CONAN_PRINT_RUN_COMMANDS override?

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#6752] opened 2020-03-27 17:48 UTC
We use `CONAN_PRINT_RUN_COMMANDS` as a default in our dev and build setups.  It is indispensable.

But recently we ran into a cute bug with a test_package for a recipe:

https://github.com/conan-io/conan-center-index/blob/11c5700e3c874adde083c1bb250e21bd1de21bc6/recipes/cmake/all/test_package/conanfile.py#L16

because: 

```
self.run("cmake --version", output=output, run_environment=True)
```

Contained more than the test writer was expecting, namely the CONAN_PRINT_RUN_COMMANDS output:

> ['', '----Running------', '> cmake --version', '-----------------', 'cmake version 3.17.0', '', 'CMake suite maintained and supported by Kitware (kitware.com/cmake).', '']

I'd like to be able to keep CONAN_PRINT_RUN_COMMANDS but turn it off in this specific `self.run()` invocation so that the output is unadorned.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2020-03-28 23:20
Hi @michaelmaguire 

This is not a bug, the behavior is as expected. The commands introduced in ``self.run()`` are added to the output, as requested. 

Is it really a big issue? I guess that you are trying to obtain and check the cmake version, but most likely the same regex that was used to get the version, keeps working too, even if there is one line more.

Have you tried ``CMake.get_version()`` static method? Maybe in a ``RunEnvironment()`` if you need it? (https://docs.conan.io/en/latest/reference/build_helpers/run_environment.html)

It will give you the version, as a Version object. It seems it might simplify your code.

**Comment by michaelmaguire** [comment] 2020-03-30 08:37
> This is not a bug, the behavior is as expected.

I understand the current feature is not a bug, which is why I raised this as a [feature]. 

>  but most likely the same regex that was used to get the version, keeps working too, even if there is one line more.

It fails on Windows.

> Have you tried CMake.get_version() static method? Maybe in a RunEnvironment() if you need it?

This recipe is the recipe that builds CMake.  The recipe creator was trying to run the newly built CMake executable as a part of their test_package.

**Comment by jgsogo** [comment] 2020-04-01 14:21
I'd prefer to change the `test_package/conanfile.py` to handle this situation than to add an extra argument and ignore the user asking for `CONAN_PRINT_RUN_COMMANDS`.

[Here in the package](https://github.com/conan-io/conan-center-index/blob/master/recipes/cmake/all/test_package/conanfile.py
) it should be easy, something like:

```python
value = str(output.getvalue())

# Look for the line, or...
for line in value.split('\n'):
    if 'cmake version' in line:
        cmake_version = line
        break
else:
    raise Something
````

```python
value = str(output.getvalue())

# ... or use a regex (pseudocode, not tested!)
m = re.match(r'.*cmake version (\d+\.\d+\.\d)+.*', value)
if m:
     cmake_version = m.groups(q)
```

You can contribute a PR to ConanCenter with a change like this one or just open an issue there and someone will make the changes.

wdyt? Or do you think it would be useful to have that argument somewhere else?

Thanks!

**Comment by madebr** [comment] 2020-06-12 22:28
I think this is a bug instead of a feature because the configuration parameter `print_run_commands` can break a otherwise working recipe.
I propose 2 ways to fix this:
1. Add a parameter to `self.run`, named `print_run_cmd=None` that will print the run command. (None=config, True=print, False=no print).
This change can make the behavior of `self.run` more or less similar to `subprocess.check_call`.
2. See https://github.com/conan-io/conan/blob/b963b4de22108f329521284f1d55793520e74983/conans/client/runner.py#L53:L56
Only print the run command when `output.isatty()` is `True`-ish.
This will probably not work when the output log is saved to a log, or tested on CI.

**Comment by ytimenkov** [comment] 2020-08-24 08:48
Generally "logging" should be redirected to stderr rather than stdout, this is a normal practice for the most tools, because stdout is used for "normal" data flow (think of shell's `+x` option).

The problem is that recipe author is totally unaware of such behavior and it may break other user in a pretty nasty way (think for example getting revision from git using "porcelain" format which will be polluted by conans output).

**Addition** (after some thoughts): Alternatively those messages should be logged using outer `info` logger, not into the output variable which one gets from `.run()` call.

**Comment by jgsogo** [comment] 2020-08-24 08:57
We are already working in the CLI 2.0 and that's the place where we will take care of these issues (if we feel like they could break some existing behavior).  There is some work already done and more ongoing: logging to stderr, only actual output to stdout,...

**Comment by memsharded** [comment] 2023-05-31 17:22
Conan 2.0 completely changed the output, with new "log levels" for Conan, and new confs to control the tools build output, and always printing the ``run()`` commands, closing this ticket as outdated.

**Closed by memsharded** 2023-05-31 17:22 UTC
Labels: stage: triaging
