### ISSUE TITLE
[bug] build_requirements are skipped on conan create . --build missing

### ISSUE THREAD

**Issue by lucabonifacio** [conan-io/conan#11374] opened 2022-06-01 16:01 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio VS2008, VS2015, VS2017, VS2019
  * Conan version: 1.48.1
  * Python version: 3.9.6

### Steps to reproduce
Let's assume this conanfile.py:
```python
from conans import ConanFile

class DemoConan(ConanFile):
    name = "demo"
    version = "0.0.0"
    settings = "os", "compiler", "build_type", "arch"

    def requirements(self):
        self.requires("boost/1.72.0@")

    def build_requirements(self):
        self.build_requires("catch2/2.13.9@")
```
By calling
```bash
conan create .
```

the build-requirements are installed. 
```
demo/0.0.0: Forced build from source
Installing package: demo/0.0.0
Requirements
    boost/1.72.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    demo/0.0.0 from local cache - Cache
    zlib/1.2.12 from 'conancenter' - Cache
Packages
    boost/1.72.0:37050c911e5419517ec6e0761c16c6e262b3e2a3 - Cache
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
    demo/0.0.0:031f3e634eb2c9302789dfaa70370c3f4ed5009c - Build
    zlib/1.2.12:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
Build requirements
    catch2/2.13.9 from 'conancenter' - Cache
Build requirements packages
    catch2/2.13.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
```

Instead, by calling
```bash
conan create . --build missing
```

the build-requirements are **not** installed.

```
Installing package: demo/0.0.0
Requirements
    boost/1.72.0 from 'conancenter' - Cache
    bzip2/1.0.8 from 'conancenter' - Cache
    demo/0.0.0 from local cache - Cache
    zlib/1.2.12 from 'conancenter' - Cache
Packages
    boost/1.72.0:37050c911e5419517ec6e0761c16c6e262b3e2a3 - Cache
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache
    demo/0.0.0:031f3e634eb2c9302789dfaa70370c3f4ed5009c - Cache
    zlib/1.2.12:3fb49604f9c2f729b85ba3115852006824e72cab - Cache
```

In my opinion, the behavior with the flag `--build missing` is not correct. I would not expect any difference for the build-requirements.

**Comment by memsharded** [comment] 2022-06-01 16:30
Hi @lucabonifacio 

This is by design. The ``--build=missing`` is telling that it will only build from sources those binaries that are missing. All the necessary binaries, including the ``demo`` one, are found in the cache, so no necessary to build anything from source. 

Then ``build_requirements`` is a special type of requirement that is only necessary when building from source, at "build" time. As nothing is being built from source, the ``build_requirements`` are not downloaded.

If you want to make sure ``demo`` is being built, the command line should specify ``--build=missing --build=demo``.

**Comment by AbrilRBS** [comment] 2024-12-17 11:30
Closing as solved as we didn't hear back from you, please feel free to reopen/create a new issue if more help is ever needed, thanks!

With Conan 2, unnecessary binaries are skipped by default, and a new conf was introduced in Conan 2.9, `tools.graph:skip_build`, to control expansion of tool_requires

**Closed as not planned by AbrilRBS** 2024-12-17 11:30 UTC
Labels: type: question
