### ISSUE TITLE
[feature] cmake presets generator

### ISSUE THREAD

**Issue by stefaneicher** [conan-io/conan#10101] opened 2021-11-29 22:10 UTC
Would it make sense to create a cmake presets generator?
https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html

We use the vitualenv generator and in vscode run the activate.sh to setup the environment. But in clion this does not work.
I would like to get a cmake idiomatic solution in which a cmake integration of any ide integrates seamless.
Cmake toolchaain is currently not a option since we have multiple packages in the repo and use workspaces during development that only work with the cmake generator.

**Comment by memsharded** [comment] 2021-11-29 22:18
Hi @stefaneicher 

The issue is that Conan by default should support cmake 3.15: https://github.com/conan-io/tribe/pull/4

While it could make sense to add later another generator for this functionality, at the moment we should focus on 1 canonical integration. This will be ``CMakeDeps`` and ``CMakeToolchain``, beware that the other generators will be removed in 2.0.
Workspaces are not production ready, we are working on improving the editables as a foundation for future workspaces, you should be checking the ``layout()`` functionality for it too. 

In any case, with the new functionalities it is now easier to create extensions. You can surely create a new block for ``CMakeToolchain`` with the new "blocks" functionality, or a new generator that creates such presets, it would be something like:
- Create a python_requires with a new CMakePresetsGenerator with a single ``generate()`` method
- Use that python_requires in your recipes, and add it to your ``generate()``

**Comment by KerstinKeller** [comment] 2021-11-30 16:24
@stefaneicher we implemented our own CMake Presets generator internally and it works great! You have a very transparent, identical workflow on all platforms, for all developers.
There is one catch tough: the last time I checked, the CMakePresets.json file needs to be located *next* to the main CMakeLists.txt file. Which means, either you have to generate it in your source directory (which is of course uncool, because generated files should be in a different location).
The other options (which we use), is to *also*  generate a "new" main CMakeLists.txt file, which includes the original top level CMake file.

```
cmake_minimum_required(VERSION 3.20)

project(libA)
# We also generate a few other things
add_subdirectory(D:/libA libA)
```

**Comment by stefaneicher** [comment] 2022-01-13 09:34
Thanks @KerstinKeller and @memsharded for your answers! In the meantime in the new clion release I can run a script and therefore call the generated [activate.sh](https://docs.conan.io/en/latest/reference/generators/virtualenv.html) script. 

https://www.jetbrains.com/clion/whatsnew/

![image](https://user-images.githubusercontent.com/1171777/149303581-04876025-83af-42ea-a609-987b5a4067f8.png)

**Comment by puetzk** [comment] 2022-02-04 17:23
> The issue is that Conan by default should support cmake 3.15: https://github.com/conan-io/tribe/pull/4

Moving my comment from https://github.com/conan-io/conan/issues/10515#issuecomment-1030182784 over here, since it seems like a better place. 

I'm not sure that supporing a minimum of 3.15 is necessarily a blocker; it really just means conan.tools.cmake.CMake can't use `cmake --preset`, not that it couldn't use the [CMakePresets.json](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) format (and parse the JSON itself for the generator argument/variables dictionary/apply_env/etc) instead of defining its own conanbuild.conf file format. To an older CMake that is unaware of CMakePresets.json, that looks just like conan doing its own thing as it currently does; to anyone using IDEs and newer CMake it would serve a nice ulterior motive.

In fact, the [IDE Integration Guide](https://cmake.org/cmake/help/v3.22/guide/ide-integration/index.html#presets) explicitly endorses this sort of thing, saying 

> The --preset= option is intended only as a convenient frontend for command line users, and should not be used by the IDE.

and 

> For example, if a preset named ninja specifies Ninja as the generator and ${sourceDir}/build as the build directory, instead of running:
> `    cmake -S /path/to/source --preset=ninja`
> 
> the IDE should instead calculate the settings of the ninja preset, and then run:
> `    cmake -S /path/to/source -B /path/to/source/build -G Ninja`

And they give schemas/test cases for doing your own parsing. If conan's helper object did this (interfacing as they recommend an IDE should), that ought to be a stable integration and would make this compatible with older CMake (while also getting the benefits for newer IDEs).

**Comment by memsharded** [comment] 2022-02-15 13:10
We are going to explore how the presets.json interface could be directly used by Conan in cmake 3.15, following suggestions from https://github.com/conan-io/conan/issues/10515#issuecomment-1030263360

**Comment by memsharded** [comment] 2022-03-14 19:04
Related: https://github.com/conan-io/conan/pull/10770#discussion_r826287592, needs to store another variable ``CMAKE_MAKE_PROGRAM`` for Mingw

**Comment by memsharded** [comment] 2022-03-30 14:59
We are changing the CMakeToolchain to generate (also, besides the toolchainfile) a CMakePresets.json file in 1.47 in https://github.com/conan-io/conan/pull/10903

The presets file will be generated atm in the ``generators_folder``, so might need to be copied to root if necessary.
But I think with that PR we can close this issue, and open new more specific tickets to keep improving this initial implementation. 

Feedback will be very welcome!

**Closed as completed by memsharded** 2022-03-30 14:59 UTC
Labels: type: look into
