### ISSUE TITLE
[bug] conan fails to resolve build_require's requirement range

### ISSUE THREAD

**Issue by apyvovar** [conan-io/conan#15107] opened 2023-11-15 13:39 UTC
### Environment details

* Operating System+version: macOS
* Compiler+version: apple-clang
* Conan version: 2.0.13
* Python version: 3.11.4

Consider the following piece of conanfile of `myPkg`:
```
    def requirements(self):
        self.build_requires("package_A/1.4.10")
        self.build_requires("package_B/3.14.1")
```
The recipe of `package_B` contains
```
    def requirements(self):
        self.requires("package_A/[>=1.4.10 <2.0.0]")
```

New version of `package_A` is introduced - `1.4.11`.
Now `myPkg` fails to build without any changes to conanfile.

Looks like, here is the situation, where `build_requires` version of `package_A` (1.4.10) conflicts with resolved `requires` range of `package_B` - 1.4.11. I expected, that `build_requires` version should be overriden (resolved) to 1.4.10, as it requested explicitly.

IMO, is such case, requirements of `pacakge_B` should be treated as `build_requirements` of `myPkg`, as `package_B` itself was requested as `build_require`. And resolved correctly.

Conan exits with error:
```
ERROR: Runtime Error: Could not process 'pacakge_B/3.14.1' with 'package_A/1.4.11'.
```

**Comment by memsharded** [comment] 2023-11-16 00:55
Hi @apyvovar 

Thanks for your report.
I have tried to reproduce, without success. This is the test that implements your case:
```python
def test_build_requires_error():
    c = TestClient()
    c.save({"pkga/conanfile.py": GenConanfile("pkga"),
            "pkgb/conanfile.py": GenConanfile("pkgb", "0.1").with_requires("pkga/[>=1.4.10 <2.0.0]"),
            "app/conanfile.py": GenConanfile("pkg", "0.1").with_tool_requires("pkga/1.4.10")
                                                          .with_tool_requires("pkgb/0.1")})
    c.run("create pkga --version 1.4.10")
    c.run("create pkgb")
    c.run("install app")

    c.run("create pkga --version 1.4.11")
    c.run("install app")
```
It passes without problems (In Conan 2.0.14, please update to the latest, just in case).
Please check the test, and let us know what could be missing there that could be special in your case.

**Comment by apyvovar** [comment] 2023-11-16 22:37
Hello, @memsharded 

Could you give any insight (or, possibly, manual) on how to set up my system to run this test.
Currently, I've encountered the following error:

```
  File "/opt/homebrew/lib/python3.11/site-packages/conans/test/utils/tools.py", line 43, in <module>
    from conans.test.assets import copy_assets
ModuleNotFoundError: No module named 'conans.test.assets'
```

Regarding the issue itself:
I don't know if it's important, but I've noticed, that your test cast contains `with_tool_requires` call, whereas in my case the problem is with `build_requires`.

I've tested with latest conan (2.0.14), and the outcome is the same.

If it helps, here's a little more log info:
```
======== Computing dependency graph ========
Graph root
    conanfile.py (myPkg/1.30.1): <path>
Build requirements
    package_B/3.14.1#d20931aa536e0e8f8bd9dfbb6ad0daa2 - Cache
    package_A/1.4.10#f9f2bb02eb97494d9f419580418fc46f - Cache
    package_A/1.4.11#48a17737b09aba8297eb3f7867aa6a09 - Cache
Python requires
    conan_utils/2.0.0#80e3c350c9a3fc40ee2249e6c985bab6 - Cache
    conan_utils/2.1.0#08bc7cf5b82a8b0bfaf917c81bc1efb0 - Cache
Resolved version ranges
    package_A/[>=1.4.10 <2.0.0]: package_A/1.4.11
ERROR: Runtime Error: Could not process 'package_B/3.14.1' with 'package_A/1.4.11'.
```

As you can see, `resolved version` of `package_A` is 1.4.11, while it's is explicitly requested 1.4.10 as `build_require` in `myPkg`'s conanfile.

Thank you

**Comment by memsharded** [comment] 2023-11-17 09:15
> from conans.test.assets import copy_assets

I am very confused here. This is part of the tests, this shouldn't even be installed in site-packages. Maybe something was corrupted from previous installs or something, it might be worth doing a clean install.

> I don't know if it's important, but I've noticed, that your test cast contains with_tool_requires call, whereas in my case the problem is with build_requires.

You need to use ``tool_requires`` for tools in Conan 2.0. From https://docs.conan.io/2/reference/conanfile/attributes.html?highlight=build_requires#build-requires

> [build_requires](https://docs.conan.io/2/reference/conanfile/attributes.html?highlight=build_requires#id17)
build_requires are used in Conan 2.0 to provide compatibility with the Conan 1.X syntax, but their use is discouraged in Conan 2 and will be deprecated in future 2.X releases. Please use tool_requires instead of build_requires in your Conan 2 recipes.


I think you are hitting some of the limitations of the legacy ``build_requires`` syntax, please try changing them.

**Comment by apyvovar** [comment] 2023-11-17 11:47
> I think you are hitting some of the limitations of the legacy build_requires syntax, please try changing them.

I've changed all `build_requires` entries to `tool_requires` in all recipes, but, unfortunately, the result is the same.
Temporarily, I could use `requires` instead of `tool_requires` for problematic packge, but still I think the issue should be investigates.

> I am very confused here. This is part of the tests, this shouldn't even be installed in site-packages. Maybe something was corrupted from previous installs or something, it might be worth doing a clean install.

I'm actually doing nothing unusual here. If it helps, I'm on M1 Pro Macbook with python installed via homebrew. No venv. Reinstalling conan doesn't help.
Maybe you need more info?

Also, I still haven't found the proper way to run the test, which you provided above. 
I've added `from conans.test.utils import tools` explicitly so that `TestClient()` can be found
I found it like this
```
➜  pwd
/opt/homebrew/lib/python3.11/site-packages
➜  grep -r TestClient .
./conans/test/utils/tools.py:class TestClient(object):
./conans/test/utils/tools.py:class TurboTestClient(TestClient):
./conans/test/utils/tools.py:        super(TurboTestClient, self).__init__(*args, **kwargs)
Binary file ./conans/test/utils/__pycache__/tools.cpython-311.pyc matches
```

Thank you

**Comment by memsharded** [comment] 2023-11-17 11:58
> I've changed all build_requires entries to tool_requires in all recipes, but, unfortunately, the result is the same.
Temporarily, I could use requires instead of tool_requires for problematic packge, but still I think the issue should be investigates.

No, this shouldn't be necessary, and it would be incorrect and problematic, it should be possible with ``tool_requires``


> I'm actually doing nothing unusual here. If it helps, I'm on M1 Pro Macbook with python installed via homebrew. No venv. Reinstalling conan doesn't help.
Maybe you need more info?

Yes, how are you running the tests? The process would be as in https://github.com/conan-io/conan#contributing-to-the-project, but relatively simple:

- clone the project
- install the requirements with ``pip install`` (better in a virtualenv)
- run ``pytest ... `` to the path to the test that you want to run. 

Conan doesn't (and shouldnt) need to be installed from brew or pip for running tests


So, I think we still need some way to reproduce this, yes, we need to investigate this. My test above is passing, so knowing what would be the difference with your code is the key. The error message that you are reporting might be related to ``run=xxx`` trait, are you changing something there, or plain ``tool_requires`` as in the test?

**Comment by apyvovar** [comment] 2023-12-18 14:14
Hello, @memsharded 

I'm sorry for late replies, I didn't have an opportunity to run tests and unfotrunately, the issue is still here for me in conan 2.0.14. I'll try to do it ASAP. 
~~just wanted to add, that I've encountered somehow similar issue, that is may be somehow connected - https://github.com/conan-io/conan/issues/15293~~
upd: issue is not related

**Comment by apyvovar** [comment] 2023-12-18 18:02
Hi again @memsharded 

I was finally able to run the test, which you've provided before, and I can confirm, that it indeed passes. But, unfortunately, in my "real" conanfile the problem still persist.

Is there anything, that I could log or test?

**Comment by apyvovar** [comment] 2023-12-18 18:26
I've also noticed even more weird behavior here:
If I change order of tool_requirements in `conanfile.py`: from 
```
    def requirements(self):
        self.tool_requires("package_A/1.4.10")
        self.tool_requires("package_B/3.14.1")
```
to
```
    def requirements(self):
        self.tool_requires("package_B/3.14.1")
        self.tool_requires("package_A/1.4.10")
```

I get the whole different error:
```
ERROR: Version conflict: myPkg/1.0.0-> package_A/1.4.10, myPkg/1.0.0-> package_A/1.4.11.
```

Please, help to investigate what's possibly wrong with my conanfile or this is actually conan bug

**Comment by memsharded** [comment] 2023-12-18 21:44
I have a quick question, how do you have packages with uppercase? Conan 2.0 doesn't allow them, are you using the escape conf for it?

Then, it seems you have something more in your ``package_b`` and ``package_a`` recipes, but without being able to reproduce, then I am afraid I have no idea of what could be happening. I have tried to reverse the order in the unit-test and it keeps working correctly. 

A possibility to create a repro case is to take the project and aggresively strip down everything that is not related. Version conflicts happen before building, so all ``source()``, ``build()``, ``package()``, ``package_info()`` and ``package_id()`` can most likely be safely removed and the issue would probably keep happening.

**Comment by apyvovar** [comment] 2023-12-18 23:11
> I have a quick question, how do you have packages with uppercase? 

We don't have package with uppercase letters in names.

The following archive contains reproducible (on my machine) example of the issue. Please, take a look. 
[conan_error_demo.zip](https://github.com/conan-io/conan/files/13709292/conan_error_demo.zip)

**Comment by memsharded** [comment] 2023-12-18 23:38
Some quick feedback: The ``pkg_sources_root_dir = os.environ.get('CI_CONAN_PACKAGE_SOURCE_DIR')`` can be quite problematic. It basically violates the principle that recipe version to source code should be a 1:1 unique relationship, that correctly affects the "recipe-revision" when the source changes. The source must also be immutable for all possible configurations of a package, and for a given version and revision. And this is not the case for usage.

Read in https://docs.conan.io/2/knowledge/guidelines.html

> All input sources must be common for all binary configurations: All the “source” inputs, including the conanfile.py, the conandata.yml, the exports and exports_source, the source() method, patches applied in the source() method, cannot be conditional to anything, platform, OS or compiler, as they are shared among all configurations. Furthermore, the line endings for all these things should be the same, it is recommended to use always just line-feeds in all platforms, and do not convert or checkout to crlf in Windows, as that will cause different recipe revisions.

> Sources used in recipes must be immutable. Once a recipe is exported to the Conan cache, it is expected that the sources are immutable, that is, that retrieving the sources in the future will always retrieve the exact same sources. It is not allowed to use moving targets like a git branch or a download of a file that is continuously rewritten in the server. git checkouts must be of an immutable tag or a commit, and download()/get() must use checksums to verify the server files doesn’t change. Not using immutable sources will be undefined behavior.

It should also be explained in the reference of the ``source()`` method and other places of the docs.

**Comment by apyvovar** [comment] 2023-12-18 23:58
> It basically violates the principle that recipe version to source code should be a 1:1 unique relationship, that correctly affects the "recipe-revision" when the source changes

Yes, I'm aware, it's not great decision, but the reason for that in our case is:
- sources should not be uploaded to Artifactory, because it may be quite space-consuming
- we have lots of private conan packages within one git repository etc.

Still, we are maintaining the 1:1 unique relationship source rule by other restrictions - each pacakge can have only one revision per version, package of same version can't be rebuilt etc. (all of our packages are privte, we can do so)

Do you think this may be the reason of the problem? I intuitively thought the problem was related to version resolution mechanism.

**Comment by memsharded** [comment] 2023-12-19 00:01
Another quick feedback/question: What is the meaning of ``tool_requiring`` a shared-lib? This doesn't have any sense, and tool-requiring libraries is also explicitly discouraged in the docs. ``tool_requires`` is for applications. Changing some of those ``package_types`` to ``application`` will make it work.


Note: the reason my test above doesn't conflict is because of the ``package_type``, as the test didn't specify it.

**Comment by memsharded** [comment] 2023-12-19 00:05
> sources should not be uploaded to Artifactory, because it may be quite space-consuming

There are other ways to do it, see for example: https://docs.conan.io/2/examples/tools/scm/git/capture_scm/git_capture_scm.html#examples-tools-scm-git-capture

But thanks for clarifying where you come from, that explains the issue, and it is true that history is always important.

> Still, we are maintaining the 1:1 unique relationship source rule by other restrictions - each pacakge can have only one revision per version, package of same version can't be rebuilt etc. (all of our packages are privte, we can do so)

Ok, of course, if you can guarantee that each change in the source code automatically gets a new version, always, then it wouldn't be a problem. Thanks for the clarification.

> Do you think this may be the reason of the problem? I intuitively thought the problem was related to version resolution mechanism.

No, not related, but I thought it was relevant enough to highlight the potential problems

**Comment by apyvovar** [comment] 2023-12-19 00:31
> What is the meaning of tool_requiring a shared-lib? 

I guess, this was migrated from 1.x package, which contain executable, that requires the library, but doesn't intend to propagate it downstream. 
And yes, now that I'm thinking of it, it doesn't really make a lot of sense to me as well. Looks like the fix for me would be to review all recipes for correct dependency requirements.

Still, maybe this case would be an example for additional fool checks here?

**Comment by apyvovar** [comment] 2023-12-19 01:50
I actually do have one relatively valid example here.

Let's assume, that `pkg_c` here provides some helper tools. And for some reason it requires certain version of `pkg_a`.
Changing package type of `pkg_c` to "application" or "build-scripts" doesn't solve the issue, as far as I can see.

The only workaround is to remove explicit `tool_require` of `pkg_a`. Isn't it something, that should work?

**Comment by memsharded** [comment] 2023-12-19 08:29
> Let's assume, that pkg_c here provides some helper tools.

If ``pkg_c`` provide helper tools, it will be consumed as a ``tool_requires`` itself. And if it requires somehow shared libraries from ``pkgb`` and ``pkga``, those will be regular ``requires``, not ``tool_requires``. ``pkgc``->(tool-require)->``pkga`` means that pkgc needs ``pkga`` to build itself, but its consumers will not need it in any way.

> The only workaround is to remove explicit tool_require of pkg_a. Isn't it something, that should work?

The solution is not dropping the ``tool_requires``, but converting that to a ``requires``. Because all of this is not only about the initial version conflicts, if things are not in the right context, there can be problems later.

**Comment by apyvovar** [comment] 2023-12-19 10:59
> If pkg_c provides helper tools, it will be consumed as a tool_requires itself.

I looked more into it. In my case `pkg_c` provides helpers tools _along with_ some other libraries. So the intention is to use this package as regular `require` to get some shared libraries and ability to execute helper. That's why it has "shred-library" type.

The logic behind it was, that `tool_requires` we need to build that helper executable, but we don't wan't to propagate it upstream.
Other dependencies are `requires`, as expected (I just omitted them in example). They just happened not to need all libraries, that helper tool needs.

**Comment by memsharded** [comment] 2023-12-19 13:46
> I looked more into it. In my case pkg_c provides helpers tools along with some other libraries. So the intention is to use this package as regular require to get some shared libraries and ability to execute helper. That's why it has "shred-library" type.

This sounds like the ``protobuf`` case, please have a look to https://docs.conan.io/2/examples/graph/tool_requires/using_protobuf.html

In short, if you want to use something as a build-tool, it must be used as ``tool_requires``. If you also need libraries, that must be a ``requires``, but those can be 2 different dependencies, 2 different nodes in the dependency graph. This becomes more evident when there is cross-building, why a single package can't be used for both applications and libraries

**Comment by memsharded** [comment] 2024-12-22 23:28
I am closing this ticket as responded/staled. But please don't hesitate to re-open or create new tickets for any further question or issue you might have. Thanks for your feedback.

**Closed as completed by memsharded** 2024-12-22 23:28 UTC
Labels: stage: triaging
