### ISSUE TITLE
[bug] injected version of root package in test_package conflicts with version of build_requires in shared config

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#7607] opened 2020-08-27 22:20 UTC
Conan version 1.26.0 on Windows Server 2012 R2.

My team uses a shared `conan config install type --git` repo which is used by our dev and build infrastructure.

In a profile fragment included in all our conan profiles, we state:

```
[build_requires]
cmake/3.17.0@bloomberg/stable
```

This has provided us with some great enforcement of common build tools.  So far so good.

Today I went to try to use our build machine to build a new version 3.18.2 of cmake using (basically) this recipe for CMake: https://github.com/conan-io/conan-center-index/tree/master/recipes/cmake/3.x.x 

I got the following error:

```
[build_requires]
*: cmake/3.17.0@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable, cmake/3.17.0@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable, cmake/3.17.0@bloomberg/stable, strawberryperl/5.30.0.1@bloomberg/stable
[env]

ERROR: Conflict in :
    '' requires 'cmake/3.17.0@bloomberg/stable' while 'cmake/3.18.2@bloomberg/stable (test package)' requires 'cmake/3.18.2@bloomberg/stable'.
    To fix this conflict you need to override the package 'cmake' in your root package.
```

I get that there's a conflict because our shared build config states everyone should use `cmake/3.17.0` and I'm trying to build cmake itself ("quis custodiet ipsos custodes?") but I don't understand what the recommended fix is in this case.  This *is* the "root" package.

Is it telling me I need to mention build_requires=cmake/3.18.2@bloomberg/stable in the recipe for cmake itself?

I know I could fiddle with my profiles to temporarily remove cmake from the build_requires in our common profile fragment, but such fiddling is frowned upon on our blessed build machines.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by michaelmaguire** [comment] 2020-08-27 22:45
Relevant comments from cpplang #chef:

> Hipony 7 minutes ago
> It fails in the test_package, because it depends on the cmake that was created and the one in your profile.
> You can either:
> 
> 0. Report a graph bug, to figure out what's the intended behaviour.
> 1. Not run test_package specifically for the cmake package.
> 2. Have a separate config (or profile) for tools.

> Michael  1 minute ago
> Thanks.  It feels like not running the test_package here would be a little evil -- why have a test_package at all then for cmake if we aren't going to run it.
> I note the test package doesn't explicitly set a requires or a build_requires on cmake, so this feels a bit like a bug.
> Having a separate profile for tools is effectively the work-around I suggested originally, but feels "dirty" to me. ;-)


> Hipony:unicorn_face:  9 minutes ago
> Tbqh, test_package is more like a suggestion other than the rule. It's good manners to have it, but I wouldn't mind if it's skipped. It's used only on conan create only for the current configuration, not any other one.
> The test_package is injected into requires with the exported package, which is an implicitly "explicit" behaviour. And the build_requires comes from the user profile, which is also an expected behaviour somewhat.
> white_tick
> eyes
> raised_hands
> 

> Michael  < 1 minute ago
> Thanks. These two conflicting expected behaviours feel like a bug to me.

**Comment by memsharded** [comment] 2020-08-27 23:04
Hi @michaelmaguire 

Have you tried the ``&!`` syntax? https://docs.conan.io/en/latest/devtools/build_requires.html?#declaring-build-requirements

With 
```
[build_requires]
&!: cmake/...
```
means apply the build requirements to all packages except the consumer (cmake) one.

**Comment by michaelmaguire** [comment] 2020-08-27 23:11
Thanks, @memsharded .  I'm reading the documentation now, but I'm not understanding what the consumer conanfile will be in the context of all of the other things that profile will be used to build.

"The special case of a consumer conanfile (without name or version)"

I'm not sure I understand how it's safe to assume the only consumer conanfile we'll ever use in our build system will be CMake?

**Comment by memsharded** [comment] 2020-08-27 23:34
Yes, you are right, this will not work for building cmake itself. At the moment I dont see any other way to build cmake without temporarily removing the ``[build_requires]`` from the profile.

We need to think about this problem. It is somehow between a bug and a non-feature. As defined now is basically by design:
- We don't allow cycles in dependencies. 
- Cycles are defined by package names, excluding versions.
- Then bootstrapping a recipe (making it depend on a previous version of itself) is not possible.
- Then the failure when applying the build-requires in the profile is totally logic and expected.

There could be 2 different lines of action, not necessarily mutually exclusive, to address this:

- Define a negative pattern in profiles, something like:
```
*!cmake: cmake/3.7.... # means all packages except those who match ``cmake``
```
- Think about the bootstrapping case, check if the cycle constraint could be relaxed for build requires (this would certainly be more difficult and require more time).

**Comment by michaelmaguire** [comment] 2020-08-27 23:39
Cool.  I'm happy to work around it.  Just wanted to understand if there was a better way I was missing.

**Comment by jgsogo** [comment] 2020-08-28 07:19
Hi! While this is not possible using one profile because there is only one context in the graph and there can be only one version of the same package in the same graph, **the new approach with the two profiles handles this situation properly**: 

Assume we already have `cmake/3.17.0@bloomberg/stable` ready (it has been compiled without CMake, _causa efficiens_), and your _host_ profile injects `cmake/3.17.0@bloomberg/stable` as a build-requires to every package being created. Using two profiles:

```
conan create <cmake_recipe.py> cmake/3.18.2@bloomberg/stable --profile:host=profile_host --profile:build=profile_build
```

Conan will generate a graph with two contexts: the host context will contain the _virtual test-package_ package, `cmake/3.18.2` and its dependencies; while the _build_ context will be populated with `cmake/3.17.0` and its dependencies.

---

This is the output in my machine with toy recipes:

## Using one profile (it fails):

```
⇒  conan create cmake.py cmake/3.18@ --profile=profile.txt
Exporting package recipe
cmake/3.18: The stored package has not changed
cmake/3.18: Using the exported files summary hash as the recipe revision: 7af6e3d50548649852fe14431dcc84ec 
cmake/3.18: Exported revision: 7af6e3d50548649852fe14431dcc84ec
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
*: cmake/3.17
[env]

cmake/3.18: Forced build from source
ERROR: Conflict in :
    '' requires 'cmake/3.17' while 'cmake/3.18 (test package)' requires 'cmake/3.18'.
    To fix this conflict you need to override the package 'cmake' in your root package.
```

## Using two profiles (it works)

```
⇒  conan create cmake.py cmake/3.18@ --profile:host=profile.txt --profile:build=default    
Exporting package recipe
cmake/3.18: The stored package has not changed
cmake/3.18: Using the exported files summary hash as the recipe revision: 7af6e3d50548649852fe14431dcc84ec 
cmake/3.18: Exported revision: 7af6e3d50548649852fe14431dcc84ec
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
*: cmake/3.17
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=11.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

cmake/3.18: Forced build from source
cmake/3.17: Forced build from source
cmake/3.18 (test package): Installing package
Requirements
    cmake/3.18 from local cache - Cache
Packages
    cmake/3.18:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build
Build requirements
    cmake/3.17 from local cache - Cache
Build requirements packages
    cmake/3.17:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Build

Installing (downloading, building) binaries...
cmake/3.17: Copying sources to build folder
cmake/3.17: Building your package in /Users/jgsogo/.conan/data/cmake/3.17/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cmake/3.17: Generator txt created conanbuildinfo.txt
cmake/3.17: Calling build()
cmake/3.17: WARN: This conanfile has no build step
cmake/3.17: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
cmake/3.17: Build folder /Users/jgsogo/.conan/data/cmake/3.17/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cmake/3.17: Generated conaninfo.txt
cmake/3.17: Generated conanbuildinfo.txt
cmake/3.17: Generating the package
cmake/3.17: Package folder /Users/jgsogo/.conan/data/cmake/3.17/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cmake/3.17: Calling package()
cmake/3.17: WARN: This conanfile has no package step
cmake/3.17 package(): WARN: No files in this package!
cmake/3.17: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
cmake/3.17: Created package revision 7dbf15279a00e503c5aeee38e4868f1b
cmake/3.18: Applying build-requirement: cmake/3.17
cmake/3.18: Copying sources to build folder
cmake/3.18: Building your package in /Users/jgsogo/.conan/data/cmake/3.18/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cmake/3.18: Generator txt created conanbuildinfo.txt
cmake/3.18: Calling build()
cmake/3.18: WARN: This conanfile has no build step
cmake/3.18: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' built
cmake/3.18: Build folder /Users/jgsogo/.conan/data/cmake/3.18/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cmake/3.18: Generated conaninfo.txt
cmake/3.18: Generated conanbuildinfo.txt
cmake/3.18: Generating the package
cmake/3.18: Package folder /Users/jgsogo/.conan/data/cmake/3.18/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
cmake/3.18: Calling package()
cmake/3.18: WARN: This conanfile has no package step
cmake/3.18 package(): WARN: No files in this package!
cmake/3.18: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
cmake/3.18: Created package revision 7dbf15279a00e503c5aeee38e4868f1b
cmake/3.18 (test package): Applying build-requirement: cmake/3.17
cmake/3.18 (test package): Generator txt created conanbuildinfo.txt
cmake/3.18 (test package): Generated conaninfo.txt
cmake/3.18 (test package): Generated graphinfo
Using lockfile: '/Users/jgsogo/dev/conan/tmp/tmp/test_package/build/2bc8106945851b08eb05f1bfc5b18e6ec3a0ede9/conan.lock'
Using cached profile from lockfile
cmake/3.18 (test package): Calling build()
cmake/3.18 (test package): WARN: This conanfile has no build step
cmake/3.18 (test package): Running test()
```

**Comment by memsharded** [comment] 2020-08-28 08:47
> Conan will generate a graph with two contexts: the host context will contain the virtual test-package package, cmake/3.18.2 and its dependencies; while the build context will be populated with cmake/3.17.0 and its dependencies.

Does this approach works without ``test_package``? I recall having issues while trying this, maybe is it because I didn't have a ``test_package`` in my example?

**Comment by jgsogo** [comment] 2020-08-28 09:06
Yes, it works without the `test_package`. Same _host_ and _build_ contexts are created.

The thing we cannot do right now is to test the package just built (`cmake/3.18`) as a build-requires of the recipe in `test_package/conanfile.py`. I mean, in this scenario we would have this graph:

![image](https://user-images.githubusercontent.com/1406456/91542239-d0863080-e91d-11ea-80f3-64963c4c4bb9.png)

And if we write:

```python

class TestPackage(ConanFile):
   # This is the recipe in `test_pacakge/conanfile.py`

   def test(self):
      if not tools.cross_building(self.settings):
          output = StringIO()
          self.run("cmake --version", output=output, run_environment=True)
```

The `cmake` that is found by the OS is the executable from the build-requires (it is added to the PATH). This is expected, as you cannot run your _host_ packages in your _build_ machine (in a general scenario). We need to develop some feature https://github.com/conan-io/conan/issues/7132  to be able to test a package as a build-requires.

**Comment by michaelmaguire** [comment] 2020-08-28 09:23
Just an FYI: Specifying a 2nd profile as suggested in https://github.com/conan-io/conan/issues/7607#issuecomment-682370857 isn't really a desirable option for us as assumes an interactive session and would require a change to our CI Jenkinsfile.  

In the end the simplest work-around was the original "fiddle with my profiles to temporarily remove cmake from the build_requires in our common profile fragment", and then once new CMake built, add (the new) CMake back in to our shared profile.  Not horrible as an upgrade process.

**Comment by jgsogo** [comment] 2020-08-28 13:25
Sure, it requires some changes, but our plan is to make the two-profiles approach the default for Conan 2.0, and we are trying to know if it fits every use-case, if we are going to break something too much... 

---

(Now the speculative part) If two-profiles are the default, and we don't want the user to write always the `--profile:build=xxxx`, then it makes sense to assume `--profile:build=DEFAULT_PROFILE` in every call. The profile provided by the user references the _host_ context (Conan is compiling packages for _host_), and Conan is always running in the _build_ context using the _autodetected profile_ (it is where build-requires run too).

This way, every line like:

```
conan create <path> <ref> --profile=profile
``` 

would become

```
conan create <path> <ref> --profile:host=profile --profile:build=DEFAULT_PROFILE
```

I'm afraid migration to Conan 2.0 won't be as straightforward... but this is one of the big improvements we might be able to introduce without breaking the command-line (a different history is if it breaks some recipe or builds).

---

I think there is not much to say about this issue, is there any other thing we can help you with? Shall we close the issue?

Thanks!

**Comment by memsharded** [comment] 2024-04-12 12:13
this was solved in Conan 2, closing ticket, thanks!

**Closed as completed by memsharded** 2024-04-12 12:13 UTC
Labels: stage: triaging
