### ISSUE TITLE
[bug] Error building poco 1.10.1 using gcc (cygwin)

### ISSUE THREAD

**Issue by sumitpatel74** [conan-io/conan#7571] opened 2020-08-20 14:07 UTC
Error building poco 1.10.1 using gcc (cygwin)

### Environment Details (include every applicable attribute)
 [settings]
os=Windows
os.subsystem=cygwin
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7.4
compiler.exception=seh
compiler.libcxx=libstdc++11
compiler.threads=posix
build_type=Release
[options]
[build_requires]

[env]

### Steps to reproduce (Include if Applicable)
conan install .. --profile
 gcc --build=openssl --build=poco

### Logs (Executed commands with output) (Include/Attach if Applicable)

ERROR: poco/1.10.1: Error in build() method, line 162
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 157
        self._cmake.configure(build_dir=self._build_subfolder, source_dir=os.path.join("..", self._source_subfolder))
        ConanException: Error 1 while executing cd build_subfolder && cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN
_LOCAL_CACHE="ON" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="7.4" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCO
NAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++11" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\supatel\.conan\data\poco\1.10
.1\_\_\package\0ec44feb6e947400ef2f37d8bd7f4c955cd16344" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBE
XECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_D
ATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DCXX_14="OFF" -DENABLE_APACHECONNECTOR="OFF" -DENABLE_C
PPPARSER="OFF" -DENABLE_CRYPTO="ON" -DENABLE_DATA="ON" -DENABLE_DATA_MYSQL="OFF" -DENABLE_DATA_ODBC="OFF" -DENABLE_DATA_POSTGRESQL="OFF"
 -DENABLE_DATA_SQLITE="ON" -DENABLE_ENCODINGS="ON" -DENABLE_JSON="ON" -DENABLE_JWT="ON" -DENABLE_MONGODB="ON" -DENABLE_NET="ON" -DENABLE
_NETSSL="ON" -DENABLE_NETSSL_WIN="ON" -DENABLE_PAGECOMPILER="OFF" -DENABLE_PAGECOMPILER_FILE2PAGE="OFF" -DENABLE_PDF="OFF" -DENABLE_POCO
DOC="OFF" -DENABLE_REDIS="ON" -DENABLE_SEVENZIP="OFF" -DENABLE_TESTS="OFF" -DENABLE_UTIL="ON" -DENABLE_XML="ON" -DENABLE_ZIP="ON" -DFORC
E_OPENSSL="ON" -DPOCO_UNBUNDLED="OFF" -DPOCO_STATIC="ON" -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP="True" -Wno-dev ..\source_subfolder

**Comment by memsharded** [comment] 2020-08-20 15:27
Hi @sumitpatel74 

Could you please post too the lines above that error? it should contain the actual cmake or compilation error messages.
It is possible that this is an issue of the Poco recipe, not Conan, but let's see that message.

**Comment by sumitpatel74** [comment] 2020-08-20 16:42
CMake Error at C:/cmake-3.18.1-win64-x64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  version "1.1.1g")

**Comment by jgsogo** [comment] 2020-08-20 17:40
Hi! This is probably something to fix in the recipe itself, we don't run cygwin in conan-center-index, and it is impossible for the contributors to test every recipe with every configuration.

Some questions before moving this issue to conan-center-index:
 * Given your configuration and your options, is `openssl` recipe being installed and the corresponding file `FindOpenSSL.cmake` generated in the build folder?
 * Is Conan able to find the rest of the dependencies?

And about your environment:
 * Did you install Python and Conan inside Cygwin or are you using the Conan installed in Windows from the Cygwin console?

Any other information would be appreciated. Thanks!

**Comment by sumitpatel74** [comment] 2020-08-20 18:32
Given your configuration and your options, is openssl recipe being installed and the corresponding file FindOpenSSL.cmake generated in the build folder?
-- No do not see FindOpenSSL.cmake file in the build folder
 
Is Conan able to find the rest of the dependencies?
Conan is able to download source and build log4cplus just fine in the current setup

And about your environment:

Did you install Python and Conan inside Cygwin or are you using the Conan installed in Windows from the Cygwin console?

-- Python/Conda is installed on Windows outside of cygwin.

Also, conan has downloaded source for openssl and successfully built it in the local cache..

OUTPUT:
(protobuf_performance) C:\Users\supatel\CLionProjects\position_service\protobuf_performance\cmake-build-debug>conan search openssl
Existing package recipes:

openssl/1.1.1g

**Comment by jgsogo** [comment] 2020-08-21 07:18
Thanks. I see different issues here:

 * `OpenSSL` is requested by the `poco` recipe but it is not included in the requirements. The `FindOpenSSL.cmake` file is not generated. This is an issue to be reported to conan-center-index repository. Can you share the full output you get when running `conan install poco/1.10.1@ --profile=<your-profile> --build=poco`?

 * Using _native_ Windows installation of Conan inside Cygwin is problematic. The Python it uses is the Windows one and some functions doesn't return the same they will if using the _native_ Cygwin Python installation. Here there are some issues related to the Conan home directory (https://github.com/conan-io/conan/issues/6751), but there might be others as it is not exhaustive.

   This can be also the root cause of the other failure, if some Python function returns a value as if it were running in Windows while the input configuration in your profile is linux-gcc. Full output from the command would be very useful

**Comment by Garanyan** [comment] 2020-09-23 15:25
Same problem on Linux.
I updated ```cmake``` to version ```3.14.5``` and it worked.

**Comment by memsharded** [comment] 2024-02-06 23:36
Closing this ticket as outdated. Since then both the poco recipe and Conan have evolve a lot, better close and open a new updated ticket if necessary, thanks!

**Closed as not planned by memsharded** 2024-02-06 23:36 UTC
Labels: stage: triaging
