### ISSUE TITLE
[bug] Faulty package-id comparison for build_requires when using lockfiles

### ISSUE THREAD

**Issue by frank-schmidtner** [conan-io/conan#11749] opened 2022-08-01 15:36 UTC
The problem occurs when trying to build a build requirement C from a lock file with the "--build-require" argument provided and using a dependency graph like this

A.requires(B)
A.build_requires(C)

B.requires(C)

C.requires(D)

This dependency graph results in a lockfile with two entries for C and D, each once in the host and once in the build context. But in [graph_lock.py](https://github.com/conan-io/conan/blob/develop/conans/model/graph_lock.py#L518-L520) it will search only for the first occurence of a dependency reference in the lock graph which is in the host context. Later on, it will compare the package id of that node in the lock graph with the computed package_id which considers the --build-require context leading to an error stating that the package ids do not match.

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: gcc 8
  * Conan version: 1.51.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
see my [minimal example](https://github.com/frank-schmidtner/conan_minimal_example2)

### Logs (Executed commands with output) (Include/Attach if Applicable)
Expected output:

```
Using lockfile: '/home/sfr7ba/repos/conan_minimal_example2/deps_lockfile.lock'
Configuration (profile_host):
[settings]
arch=armv8.3
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
[options]
[build_requires]
[env]

ERROR: 'sub_sub_package/1.0.0@test/test' package-id 'af0fbc5eb7376a4b9749db37a5c402b36d452909' doesn't match the locked one '8259f0ca51d6e5de1ae227eda55edb4a8cf7bcd2'
```

**Comment by memsharded** [comment] 2022-08-15 09:36
Hi @frank-schmidtner 

Sorry for the delay in the response. Thanks for the detailed report. 
However, I think I am missing something. What is ``external_prebuild_package_mock``? It is not in the repo, and it doesn't seem related to the rest of the code, maybe it is a mistake in the readme?

**Comment by memsharded** [comment] 2022-08-15 21:39
I am trying to reproduce with a unit-test based on your repo, but so far this is working fine:

```python
def test_lock_requires():
    c = TestClient()
    c.save({"common/conanfile.py": GenConanfile("common", "1.0").with_settings("os"),
            "tool/conanfile.py": GenConanfile("tool", "1.0").with_settings("os")
                                                            .with_requires("common/1.0"),
            "lib/conanfile.py": GenConanfile("lib", "1.0").with_settings("os")
                                                          .with_requires("common/1.0"),
            "consumer/conanfile.py":
                GenConanfile("consumer", "1.0").with_settings("os")
                                               .with_requires("lib/1.0")
                                               .with_build_requires("tool/1.0")})
    c.run("export common")
    c.run("export tool")
    c.run("export lib")
    # cross compile Linux->Windows
    c.run("lock create consumer/conanfile.py -s:h os=Linux -s:b os=Windows --build")
    print(c.load("conan.lock"))
    c.run("install tool/1.0@ --build=missing --lockfile=conan.lock "
          "--lockfile-node-id=3 --build-require")
    print(c.out)
```

**Comment by frank-schmidtner** [comment] 2022-08-16 06:36
Hi @memsharded 

thank you for your answer and sorry also for my late response. Regarding the `external_prebuild_package_mock`: I am sorry. this was from earlier tries and I seem to have overseen it while cleaning up the example. I adapted the Readme now and reran everything following it and I can still reproduce the error on my machine.

I also tried the commands you're using in your unit test on my machine (via cmd line) and they result in the same error message. What I noticed is, that you provide `3` as lockfile-node-id, which in my lockfile is the id of the `common` package, although you are building the `tool` package. Is this on purpose or do you have a different lockfile where id 3 equals the id for the `tool` package? (If I try on my machine it doesn't matter wether I use id 3 or 4, but fail with the same error). Here's my lockfile content for comparison:

```
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "consumer/1.0.0@test/test",
    "options": "",
    "requires": [
     "1"
    ],
    "build_requires": [
     "4"
    ],
    "path": "consumer/conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "lib/1.0.0@test/test",
    "options": "",
    "package_id": "bd68c14ae3107589becea9b965a722c1767504ec",
    "requires": [
     "2"
    ],
    "context": "host"
   },
   "2": {
    "ref": "tool/1.0.0@test/test",
    "options": "",
    "package_id": "886cc5f6b80fc17c88706881c35e61847abe5287",
    "requires": [
     "3"
    ],
    "context": "host"
   },
   "3": {
    "ref": "common/1.0.0@test/test",
    "options": "",
    "package_id": "2d5685a99e2ff5a0d2b054bb1fbfa46781f8a46a",
    "context": "host"
   },
   "4": {
    "ref": "tool/1.0.0@test/test",
    "options": "",
    "package_id": "ac11f5c4c3a9857550a5a3e5d14d9063d5cd1867",
    "requires": [
     "5"
    ],
    "context": "build"
   },
   "5": {
    "ref": "common/1.0.0@test/test",
    "options": "",
    "package_id": "f79253a95d359552cebcdb75632170b4bacaf62a",
    "context": "build"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++\ncompiler.version=8\nos=Linux\nos_build=Linux\n[options]\n[build_requires]\n[env]\n",
 "profile_build": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++\ncompiler.version=8\nos=Windows\nos_build=Linux\n[options]\n[build_requires]\n[env]\n"
}
```

**Comment by memsharded** [comment] 2022-08-16 07:50
Hi @frank-schmidtner 

Yes, there is something slightly different: the ``tool`` package appears to be 2 times in the lockfile, one in the "build" context, and another in the "host" context. I only get one, in the "build" context, because I am using it as a ``build_require``, and I am using both "build" and "host" profiles in my command, so it shouldn't be in the host context. Is it possible that you have some extra ``requires`` to the ``tool`` package somewhere that I am missing?

**Comment by frank-schmidtner** [comment] 2022-08-16 08:07
@memsharded yes, there's a difference in the dependency graph, now I see it. `lib` should have a require to `tool` not to `common`

**Comment by memsharded** [comment] 2022-08-16 08:11
> @memsharded yes, there's a difference in the dependency graph, now I see it. lib should have a require to tool not to common

Ok, I will change the test and see what happens. Would you mind explaining what is ``tool`` in your real case? Why in one case it is a ``tool_require`` and in the other case it is a ``require``? Is it kind of protobuf package?

**Comment by memsharded** [comment] 2022-08-16 08:13
Managed to reproduce it with this test:
```python
def test_lock_requires():
    c = TestClient()
    c.save({"common/conanfile.py": GenConanfile("common", "1.0").with_settings("os"),
            "tool/conanfile.py": GenConanfile("tool", "1.0").with_settings("os")
                                                            .with_requires("common/1.0"),
            "lib/conanfile.py": GenConanfile("lib", "1.0").with_settings("os")
                                                          .with_requires("tool/1.0"),
            "consumer/conanfile.py":
                GenConanfile("consumer", "1.0").with_settings("os")
                                               .with_requires("lib/1.0")
                                               .with_build_requires("tool/1.0")})
    c.run("export common")
    c.run("export tool")
    c.run("export lib")
    # cross compile Linux->Windows
    c.run("lock create consumer/conanfile.py -s:h os=Linux -s:b os=Windows --build")
    print(c.load("conan.lock"))
    c.run("install tool/1.0@ --build=missing --lockfile=conan.lock "
          "--lockfile-node-id=4 --build-require")
    print(c.out)
```

**Comment by memsharded** [comment] 2022-08-16 08:20
Bad news, is that this seems quite challenging to fix in 1.X scope.

Good news is that this is already working in 2.0, this ported test passes:
```python

def test_lock_requires():
    c = TestClient()
    c.save({"common/conanfile.py": GenConanfile("common", "1.0").with_settings("os"),
            "tool/conanfile.py": GenConanfile("tool", "1.0").with_settings("os")
                                                            .with_requires("common/1.0"),
            "lib/conanfile.py": GenConanfile("lib", "1.0").with_settings("os")
                                                          .with_requires("tool/1.0"),
            "consumer/conanfile.py":
                GenConanfile("consumer", "1.0").with_settings("os")
                                               .with_requires("lib/1.0")
                                               .with_build_requires("tool/1.0")})
    c.run("export common")
    c.run("export tool")
    c.run("export lib")
    # cross compile Linux->Windows
    c.run("lock create consumer/conanfile.py -s:h os=Linux -s:b os=Windows --build=*")
    print(c.load("consumer/conan.lock"))
    c.run("install --tool-requires=tool/1.0 --build=missing --lockfile=consumer/conan.lock ")
    print(c.out)
```

**Comment by frank-schmidtner** [comment] 2022-08-16 10:41
@memsharded tool is a logging lib that we're using both in host and build context.

**Comment by memsharded** [comment] 2022-08-16 15:41
How are you using such library in the build context? Because if it is a library, it might not be able to be linked if build!=host, for example, if it is a cross-build scenario.

**Comment by frank-schmidtner** [comment] 2022-08-16 16:41
I am afraid I don't understand your question. We have sth like

```
consumer.requires(host_lib)
consumer.build_requires(tool)

host_lib.requires(logging_lib)

tool.requires(logging_lib)

logging_lib.requires(common)
```

So in the end we have two executables, `consumer` (in host context) and `tool` (in build context)  which use functions of the `logging_lib` to log debug/info/etc. messages. As we do compile `logging_lib` twice, once for build and once for host context, there should not be a problem with linking, should it?

**Comment by memsharded** [comment] 2022-08-16 16:58
Ok, I see now, thanks. The graph you are describing is slightly different to the one reflected in the test, still the problem would be the same, so the test captures the underlying issue, all good.

Bad news is that I have been trying for a couple of hours to fix this in 1.X and all I got is a couple of messy branches breaking more than they solve. I'll keep you posted.

**Comment by memsharded** [comment] 2022-11-29 13:58
I have tried again, put some good hours, still nothing reasonable that won't break all...

**Comment by memsharded** [comment] 2024-01-28 22:40
Sorry we didn't find a solution back then.

This referred to old Conan 1.X lockfiles. Lockfiles have been fully revamped in Conan 2.0, I am closing this ticket as outdated, please create new tickets referring to the new lockfiles for any further question or issue. Thanks!

**Closed as not planned by memsharded** 2024-01-28 22:40 UTC
Labels: stage: triaging
