### ISSUE TITLE
Resolved dependencies are not the same if a package needs to be built

### ISSUE THREAD

**Issue by dkgs** [conan-io/conan#3523] opened 2018-09-11 09:26 UTC
Hello,

Using conan 1.7.0 (changelog don't show any modification about this problem for 1.7.3) on ubuntu 18.04.

I've encountered the following use case ([conan_dep.tar.gz](https://github.com/conan-io/conan/files/2370339/conan_dep.tar.gz)):

PackageC is independent and a shared lib
PackageB is a static lib and requires PackageC as public
PackageA is a dynamic, requires PackageB as private and PackageC as public

UseOfA requires PackageA as public

I would expect that in the buildinfo constructed by conan when I make a conan install of UseOfA that build info of PackageA and PackageC are available.

**When I install UseOfA:**
If all my packages are in my local repository info about PackageC are missing.
If the PackageA is missing from my repository and the recipe is on the server, installing with build missing provides all info I need.
[other test] If the PackageA is missing from my repository and the binary is on the server, info about PackageC are missing.

**To test it:**
You can untar the archive and run test.sh, it will create two build folder: build_problem and build_ok and then you can compare conanbuildinfo.txt the check the differences.

Regards,

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment] 2018-09-11 10:28
I was able to reproduce it, indeed a bug in the model of private dependencies. Seems complex to fix but we are on it.

It doesn't seem a regression, up to my knowledge, but a long standing bug in privates (which are not very recommended, unless strictly necesssary, so they are not used that much, that could be the reason the bug was there for some time). I'd like to ask about the urgency, if it is not that critical, we could fix it in conan 1.8, otherwise, please tell and we will check what can be done. Thanks for reporting it!

**Comment by dkgs** [comment] 2018-09-11 11:46
Not critical, because there are workaround.

Switching the order of the dependencies in PackageA, putting the public first (if that's not a problem) works.
At worst, you can always switch private to public.

**Comment by memsharded** [comment] 2018-09-17 08:28
It has been fixed in #3525, it will be released in conan 1.8 (you could try it now from sources, develop branch).

**Closed** 2018-09-17 08:27 UTC
Labels: bug
