### ISSUE TITLE
Mismatch between environment variables in profile and in virtualenv

### ISSUE THREAD

**Issue by absassi** [conan-io/conan#1287] opened 2017-05-15 17:56 UTC
When using a profile that declares some enviroment variables required for building, such as `CPPFLAGS`, these variables appear only in `activate.sh`, but the `cpp_info` of requirements (which will have non-empty `CPPFLAGS` if some package added anything to `self.cpp_info.defines`) appear only in `activate_build.sh`.

It is impossible to active both environments properly, since they set the variables, instead of appending to them. But the ideal solution would be for Conan to generate a single complete definition of the variable (at least for `virtualbuildenv`).

`virtualrunenv` doesn't suffer from this issue because it prepends to the variables it exports.

Also, I fail to understand the distinction between `virtualenv` and `virtualbuildenv`. I know they are different and how both are defined - the documentation is clear about that - but I cannot see when I should use one or the other, it looks like we always should use both when building using an external build system (otherwise, I wouldn't even need to use these generators). Shouldn't they be merged?

**Comment by lasote** [comment] 2017-05-16 08:44
Hi @absassi,

The `virtualbuildenv` set the variables that `AutoToolsBuildEnvironment` and `VisualStudioBuildEnvironment`set, based on the settings and the `cpp_info` object of the requires.

The `virtualenv` is only setting the variables from the `env_info` object.
They are separated because the idea is to concatenate them if needed, but maybe you don't want to mess with your external build system variables because you are only setting some PATH to your internal tools or whatever.

But you are right, the env variables like CPPFLAGS will be overridden if you declare them as environment variables in a profile, for example. But the problem is how to know when to concatenate and when not to concatenate. The variables could have been set in the shell and probably you want to override them, or maybe the variable is not a list and can't be appended.

I don't know if it's suitable for you but maybe you could have `build_requires` that set `self.cpp_info.cppflags` instead if environment variables in a profile declaring build flags.  That way it will be taken into account in the `virtualbuildenv` generator.

**Comment by absassi** [comment] 2017-05-16 12:43
Hi @lasote, I still can't imagine a case where I want to set some variables that will affect the build but not all of them (unless there is a bad usage of them somewhere else).

Maybe I'm still missing the case when should one use `virtualenv` but not `virtualbuildenv`. The example for [`env_info`](http://docs.conan.io/en/latest/reference/conanfile/methods.html#env-info) is [installer packages](http://docs.conan.io/en/latest/howtos/create_installer_packages.html#create-installer-packages), which makes sense: some toolchain requirement exporting the variables to use it, exactly the same case for `[env]` in profile - and both are used in `virtualenv`. However, these variables must be applied to the environment in order to build (and Conan does that when calling `build()`). The problem is, if the build step (it doesn't matter if called from within `build()` or externally using a virtual envs) also needs to apply to the environment the `cpp_info` variables (like `AutoToolsBuildEnvironment`), they might override the tool variables (profile or requirement's `env_info`). This is same same case for sourcing `activate.sh` and then `activate_build.sh`.

I don't know what's the implication in CMake of always exporting `cpp_info` variables instead of just the `env_info` ones. For Autotools, the distinction doesn't make sense.

About concatenation, I think it is standard practice to always concatenate compiler flags. This will also open Conan to receive flags from environment, which is nice when using `conan build`, since these variables are the usual way to integrate one build system into another.

All flags are lists, but Conan will need to have some intelligence about the list separator. Usually, variables with command flags use spaces, while those with paths use system-specific separators (`:` or `;`).

In my case, `build_requires` wouldn't make sense, since the flags are to select which cross-compiler/architecture I'm using. I used `CPPFLAGS` as an example because anyone of them suffers from the same issue, but I'm actually using:

* Profile: `CC`, `CXX` and `CFLAGS` (things like `-mcpu=cortex-m4`)
* From requirements: `CPPFLAGS` (`cpp_info.includedirs`), `CXXFLAGS` (`cpp_info.cppflags`), `LIBS` (`cpp_info.libs`) and `LDFLAGS` (`cpp_info.exelinkflags` and `cpp_info.libdirs`)

It is just a mere coincidence that those flags are different, there could be any intersection. But even this way, `activate_build.sh` has a `CFLAGS=""` (instead of using profile's flags or `CFLAGS="$CFLAGS "`), but doesn't have any reference to `CC` and `CXX`.

Thanks.

**Comment by lasote** [comment] 2017-05-17 08:21
I understand all you are telling, it's just a matter of architecture, the `env_info` variables are managed as environment variables, it doesn't matter if you write FOO or CXXFLAGS, conan doesn't make any distinction, just declares the environment variable. We really want to keep it like this.

I was thinking and I have a possible fix for that. The `AutoToolsBuildEnvironment` and the `virtualbuildenv` could look first to the known environment variables like CXXFLAGS, CFLAGS etc and concatenate the those values to the obtained from `cpp_info`. That way the env variables will keep being only env variables but the "specialized" collaborators will know about the environment variables related with the build.

That way if you activate both environments, the `virtualbuildinfo` will override your flags but will already contain the values from the environment.

WDYT?

**Comment by absassi** [comment] 2017-05-17 19:53
It seems good for me. Thanks.

Just for the record, I've tried the following workaround for this issue: create a new package with `options: {cflags: "ANY"}` and setting `self.cpp_info.cflags` in `package_info`. It almost worked, but then I've found #1296.

**Comment by lasote** [comment] 2017-05-18 12:54
Ok! thanks for the feedback. We will study it for 0.24, if it's a reasonable development like it seems we will solve it that way.

**Comment by lasote** [comment] 2017-06-09 08:31
Hi @absassi I'm reviewing this issue and It should work from `0.22.0`. Could you confirm the version?

**Comment by lasote** [comment] 2017-06-09 08:46
Forget my last comment, I reproduced the issue.

**Comment by memsharded** [comment] 2017-07-19 16:25
Fixed and released in 0.25

**Closed by memsharded** 2017-07-19 16:25 UTC
Labels: enhancement, fixed
