### ISSUE TITLE
The content of cpp_info.resdirs is not used

### ISSUE THREAD

**Issue by sansuiso** [conan-io/conan#1000] opened 2017-02-16 11:27 UTC
Hi,

I'm trying to create a recipe for a library that installs some resource files (tabulated data required for later computation) in a specific folder. I've added this folder to the `cpp_info` field using:

    self.cpp_info.resdirs = ['share/mylib']

However, when I have a look at the `conanbuildinfo.cmake` file generated during the `test_package` command, I can't find any cmake variable whose name would be related to resources, nor any variable that would contain `'share/mylib'`.

Browsing quickly through `conan`'s source code, I couldn't find much information about `resdirs` and I fear it might be unused.

Am I searching in the wrong place / direction, or is it an issue inside `conan`?

Thanks for providing us with your tool!

**Comment by memsharded** [comment] 2017-02-16 12:02
Nop, you are right, there is a bug, and the ``resdir`` is not propagated correctly. We have some ongoing improvements for next release 0.20, so I'll check that this is added properly.

Thanks very much for reporting this!

**Comment by sansuiso** [comment] 2017-02-16 12:38
You're welcome. Kudos for being so recative!

**Comment by memsharded** [comment] 2017-02-20 12:45
This has been merged to develop in https://github.com/conan-io/conan/pull/975 and will be released in 0.20:

**Comment by memsharded** [comment] 2017-02-28 00:49
Released and available in conan 0.20, please upgrade and report if necessary.

**Closed by memsharded** 2017-02-28 00:49 UTC
Labels: bug, fixed

**Comment by sansuiso** [comment] 2017-02-28 20:57
Thanks! I will upgrade this week and let you know how it went.

**Comment by sansuiso** [comment] 2017-03-14 10:52
Ok, I could finally upgrade to 0.20.3 and test my recipe code. The fix worked perfectly. Thanks guys!

**Comment by memsharded** [comment] 2017-03-14 12:09
Great to know, thanks for telling!

**Comment by lockyer** [comment] 2020-02-16 00:37
I think this might be broken again.

I'm setting `self.cpp_info.resdirs = ['src/assets']` in my `package_info` method of my library and when I try to output it in the `build` method of my application like this:
`self.output.warn(self.deps_cpp_info.resdirs)`
or
`self.output.warn(self.deps_cpp_info.res_paths)`

 I just get empty `[]`

I also tried outputting the `${CONAN_RES_DIRS}` variable in the `CMakeLists.txt` of my application and that also comes out blank.

I've tried in Conan version 1.21.2 and 1.22.2

**Comment by memsharded** [comment] 2020-02-17 16:12
Hi @lockyer 

Do you think it is a regression, did it work in previous Conan versions?

Can you please check the folders of your package, and check if the directory of your package ``src/assets`` actually have some assets inside? Go to the conan cache, navigate down to the package folder. Ask if you have any question.

By default, Conan exclude empty folders from the generators, as they were causing errors in some build systems. If your package folder actually has files, the variable shouldn't be empty. 

Please check and tell me. Thanks!

**Comment by lockyer** [comment] 2020-02-21 02:30
sorry, first time trying to use this feature! looks like that was the issue, I had the path slightly wrong so it wasn't finding any files. Thanks for your help!

**Comment by memsharded** [comment] 2020-02-21 09:58
No problem @lockyer, happy to help!
