### ISSUE TITLE
[question] Specifying env variables without propagating to dependencies.

### ISSUE THREAD

**Issue by marausch** [conan-io/conan#2819] opened 2018-04-27 14:21 UTC
The documentation explains that environment variables defined with option _-e_ of conan's _install_ command "will be defined before the build step in all the packages".
Is there a way to limit the defined variable to only the project we are installing the dependencies for, e.g. something like _-e self:SOME_VAR="SOME_VALUE"_?
If the project is a package itself, then replacing _self_ with its package-name works indeed, but what if the project is a consumer only?
This is not an issue, since a name can be defined even if it is otherwise not necessary...

**Comment by lasote** [comment] 2018-04-28 08:56
I understand, you would need something like `-e PROJECT:var=value`. It is not currently implemented, maybe we should review it because if I'm not wrong an unscoped option or setting only applies to the project, otherwise the env applies globally when it is unscoped. Right @memsharded? The issue is that it would be breaking behavior if we change it.

**Comment by marausch** [comment] 2018-04-30 07:44
_> something like -e PROJECT:var=value_
Yes, you have simply put the keyword `PROJECT` where I've written `self`. Could even be `-e :var=value` without any need for an additional keyword (currently the colon is ignored in this case).
Let's describe what I'm doing:
- the main project has package `dep` as dependency;
- I want to define an environment variable for the project only (it should not exist for `dep`);
- I assign package name `cons` to the project, even if it is a consumer only;
- now I can do `$ conan install . -e cons:var=value`.

This works, `var` exist when the project is built, and does not exist when rebuilding `dep` from source douring installation.
What I'm asking is if its possible to avoid the need of the additional package name `cons`.

**Comment by lasote** [comment] 2018-05-03 08:29
No, there is no other way to do it currently. I'm tagging this issue to see if we can review how is it doing in options and settings and do the same with env vars.

**Comment by memsharded** [comment] 2018-05-03 11:47
Seems a reasonable request. There is a way to specify options for the consumer project (unscoped), so it seems logical to be able to do the same for env-vars.

**Comment by memsharded** [comment] 2023-10-08 00:34
The ``-e`` cli arg has been removed in 2.0, and the recommended approach is using ``[buildenv]`` in profiles, closing this ticket as outdated, please create new tickets if necessary for any further question or request.

**Closed by memsharded** 2023-10-08 00:34 UTC
Labels: type: look into, type: feature
