### ISSUE TITLE
[bug] conan2 conanfile.txt options ignored for test_requires dependencies

### ISSUE THREAD

**Issue by zabereer** [conan-io/conan#14280] opened 2023-07-12 16:10 UTC
### Environment details

* Operating System+version:  RHEL 8.6
* Compiler+version: gcc 11
* Conan version: 2.0.7
* Python version: 3.11.0

### Steps to reproduce

1. create new directory with `conanfile.txt` containing:
```
[test_requires]
benchmark/1.8.0
[options]
benchmark/*:enable_lto=True
```
2. make sure no benchmark in local cache by `conan remove --confirm benchmark`
3. from that directory run `conan install .`
4. check cache what you got with `conan list 'benchmark/*:*'` and notice package options has `enable_lto: False`

That is surprising to me and not really what I want.
If I modify `conanfile.txt` to have `[requires]` instead of `[test_requires]` then I get an LTO benchmark.

(and before I forget, thank you for amazing work on conan2).

**Comment by memsharded** [comment] 2023-07-12 21:28
Hi @zabereer 

Thanks for your report.
We are aware that this won't work this way, and it is by design, for ``tool_requires``.
But maybe for ``test_requires`` it should/can work. We need to check it, we will have a look, thanks for the details to reproduce.

In the meantime, you can do:
- Define a ``conanfile.py`` instead of a ``txt``
- Define ``test_requires("benchmark/version", options={<key>: <value>})``

That guarantees that the option is passed to the dependency.
You might also define it in the profile or in command line, and I think that should work too.


> (and before I forget, thank you for amazing work on conan2).

Thanks very much! 🙂

**Comment by zabereer** [comment] 2023-07-17 07:53
Thank you @memsharded , I will use the workaround for now.

**Comment by memsharded** [comment] 2023-07-29 17:16
Fixed in https://github.com/conan-io/conan/pull/14340 for next 2.0.10

**Closed as completed** 2023-07-29 17:15 UTC
Labels: stage: triaging
