### ISSUE TITLE
[bug] cmake link options treated as files with cmake_find_package generator

### ISSUE THREAD

**Issue by srnwk** [conan-io/conan#8703] opened 2021-03-25 16:01 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: MSVC 19.28
  * Conan version: 1.34.1
  * Python version: 3.9.1

### Steps to reproduce
Install siglost/1.2.0:
```sh
conan install sigslot/1.2.0 -g cmake_find_package_multi
```
Consume Pal::Sigslot via cmake:
```cmake
find_package(PalSigslot REQUIRED)
target_link_libraries(example PRIVATE Pal::Sigslot)
```
Configure & build:
```sh
cmake -G Ninja -B build . && ninja -C build
```
### Logs
```
ninja: error: '/OPT:NOICF', needed by 'bin/example.exe', missing and no known rule to make it
```

sigslot/1.2.0 declares a link option `/OPT:NOICF`.
When using the cmake_find_package_multi generator or cmake_find_package,
that gets added verbatim to the INTERFACE_LINK_LIBRARIES property of the declared target.

Since it doesn't start with `-`, it's treated as a library name by cmake instead of a linker flag,
and with the Ninja generator, cmake ends up generating something like: `build bin\example.exe: ... \OPT$:NOICF ...`
leading to the error shown above.

With cmake 3.13+ INTERFACE_LINK_OPTIONS could be used to avoid this, but for earlier versions I'm not sure.
cl.exe, link.exe etc. will accept flags with `-` instead of `/` as well, so this could be used as a workaround in the recipe,
but IIRC this is entirely undocumented...

**Comment by SpaceIm** [comment] 2021-03-30 23:12
It could also be protected with double quotes for CMake: `self.cpp_info.components["_sigslot"].exelinkflags.append("\"/OPT:NOICF\"")`
But I don't know if it would be a good solution for non-CMake generators.

**Comment by memsharded** [comment] 2021-03-31 09:41
I have been able to reproduce:

- Using quotes doesn't help, (at least CMake 3.15)
- Using -/OPT:NOICF with the ``-`` works, and without quotes.

**Comment by memsharded** [comment] 2021-03-31 09:43
This is surprising it has not been raised before. Apparently the ``-`` is necessary for the CMake generators, and I have submitted a potential fix in https://github.com/conan-io/conan/pull/8740, but we need to carefully analyze if it could be breaking somehow.

**Comment by memsharded** [comment] 2021-04-06 08:00
Closed by https://github.com/conan-io/conan/pull/8740 ,will be in 1.35.1

**Comment by memsharded** [comment] 2021-04-19 13:44
Sorry, the fix for this had to be reverted in https://github.com/conan-io/conan/pull/8812. It was breaking other existing use cases.

The most immediate fix for this might be to change the ConanCenter recipe to define ``-OPT:REF`` flag instead of ``/OPT:REF``, as it seems the msvc linker will accept it, and it will be good for cmake as well.

**Comment by memsharded** [comment] 2021-05-26 15:14
I see the recipe still contains
```python
        if self.settings.os == "Windows":
            if self.settings.compiler in ("Visual Studio", "clang"):
                self.cpp_info.components["_sigslot"].exelinkflags.append('/OPT:NOICF')
```

So apparently, it has not been changed yet. This was contributed by @madebr, do you know if it is possible to just change it to:
```python
        if self.settings.os == "Windows":
            if self.settings.compiler in ("Visual Studio", "clang"):
                self.cpp_info.components["_sigslot"].exelinkflags.append('-OPT:NOICF')
```
And it will be good for different generators, including cmake and visual?

**Comment by madebr** [comment] 2021-05-26 15:26
The `/OPT:NOICF` comes from here:
https://github.com/palacaze/sigslot/blob/19a6f0f5ea11fc121fe67f81fd5e491f2d7a4637/CMakeLists.txt#L25-L30
I think it should only be applied for `self.settings.compiler == "Visual Studio"`.

**Comment by memsharded** [comment] 2021-05-27 17:03
I am checking this again, and so far it seems unsolvable from the Conan side.

If a recipe can contain something like:

```
self.cpp_info.exelinkflags.append('/OPT:NOICF')
self.cpp_info.exelinkflags.append('/path/to/someobject')
```

Then, it becomes virtual impossible to differentiate them apart.

The only possible solution I see is recipes explicitly changing to:
```
self.cpp_info.exelinkflags.append('-OPT:NOICF')
self.cpp_info.exelinkflags.append('/path/to/someobject')
```

But I would like to make sure this is the way to go, and it will not break users in other ways (e.g. other generators?) 
Any feedback here @SpaceIm @madebr ? Thanks!

**Comment by memsharded** [comment] 2021-06-25 10:13
We still don't know what can be done here (besides a new model for binary objects in cpp_info), nothing we can fix atm, so I am moving this to 1.39, lets see if we get feedback about this.

**Comment by lasote** [comment] 2021-07-09 07:31
I was reading all this and I'm wondering if for Conan 2.0 (not now because I assume we cannot break again the users using a directory in `sharedlinkflags` or `exelinkflags`) we should disambiguate them by using a [PurePath("/foo/bar")](https://docs.python.org/3/library/pathlib.html) when declaring a path so we can have a bit more information and improve the dirty job of preparing the data for CMake. It might be useful in other situations.

**Comment by memsharded** [comment] 2021-08-13 14:30
Related https://github.com/conan-io/conan/issues/5159

**Comment by lasote** [comment] 2021-08-16 10:12
Auto related? @memsharded

**Comment by memsharded** [comment] 2021-08-19 22:46
Yes, sorry, I think I meant https://github.com/conan-io/conan/issues/5159

**Comment by lasote** [comment] 2021-08-31 10:05
**Note:**  Supporting object files won't fix this issue because it would require replacing the "/" to "-" as we did, but it would break again all the people using these flags to point to object files (we cannot force to use the new feature yet). So this issue will be solved probably on Conan 2.0 when we force the users to use the new feature to declare object files and we introduce the replacement again.

**Comment by lasote** [comment] 2021-09-02 07:26
Related: https://github.com/conan-io/conan-center-index/pull/6083/files#r663360956

**Comment by memsharded** [comment] 2021-10-05 07:37
We have started the path to alleviate this issue in https://github.com/conan-io/conan/pull/9520, which is creating a explicit model for OBJECTS, and that will allow to treat link flags more consistently. This can't still be done without breaking right now, will need to wait until Conan 2.0, where we could break.

**Comment by memsharded** [comment] 2023-02-21 00:17
I have been having a look at this to prepare for 2.0, some updates:

- ConanCenter recipes no longer define ``cpp_info.xxxxflags`` with ``/``.
- The fix in https://github.com/conan-io/conan/pull/8740 basically consisted in doing a replace, unconditionally. If that is all it is going to do, I think it is best that recipes fixes the flag format in origin, and not the consumer trying to fix a bad declaration from an upstream recipe.

So I think I am going to close this, but it this becomes an issue again, please re-open or create a new ticket.

**Closed as completed by memsharded** 2023-02-21 00:17 UTC
Labels: type: bug, stage: triaging
