### ISSUE TITLE
Conan and CI Pipelines

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#308] opened 2016-06-08 07:10 UTC
CI Tools like [Go](https://www.go.cd/) or [Jenkins](https://jenkins.io/doc/pipeline/) allow to define CI with multiple components depending on each other. Components are ordered in Pipelines, if a component at the beginning of the Pipeline is built successfully, all depending components are built. Everything builds with the latest version.

![Build Pipeline](https://www.go.cd/assets/images/blog/deploy-now/continuous_delivery_security_testing_pipeline.png)

The workflow for one component is as follows:
1. CI triggers build
2. Gather all depending packages from central server
3. Build component
4. Run tests
5. Publish component to central server
6. CI triggers next component

This workflow should be realizable with Conan, however after reading #15 and #101 I'm not sure what the best way is:
1. I could push the newly built component to `ComponentA/HEAD@Foobar/CI`. Conan then would not be able to detect that the version on the central server is newer than the local and not update the dependency (am I right?)
2. I could use the revision/sha as a version identifier like `ComponentA/r1234@Foobar/CI`. But this would mean that all depending components need to have their requires modified after the build of a dependency ran through.

Asked in another way: Is there a way of defining "Always use the latest version" as a requirement? Do other developers have this issue?

Sorry if this question overlaps with the above mentioned issues #15 and #101 (and problably others?). I wanted to explicitly ask for the usecase of CI pipelines and wasn't sure where this fits in best.

**Comment by memsharded** [comment] 2016-06-08 08:41
Totally legit issue about pipelines, thank you. Not sure that the CI approach for the whole project would be the most practical. We are doing some CI for some projects, and our approach to CI for large projects is per-component, not as a whole project, otherwise it becomes intractable, you know, "divide and conquer".

So when we have a project with many libs, lets say (-> reads depend on), and a final application (A):

A -> B -> C
A -> D
A -> E -> C

We launch CI for each component when its code changes, every commit to libC will generate a CI build, it will build the project, create conan packages and upload conan packages to the conan server.

When a commit is done to component B, it is fired in CI. Component B has a dependency (defined in requires in conanfile) towards a version of C, which must exist in the conan server. The CI retrieves required packages for B, builds B, uploads packages of B to conan server.

Conan is not a CI manager, so it doesn't take care of firing CI for downstream dependencies when one changes. It would be like having a CI automatically firing with a Java dependency from MavenCentral is upgraded or a Pip pakage from PyPI is upgraded. 

Anyway, I think it can be easily automated in the CI server. Related to #101, that issue is practically solved, I was waiting for some feedback to close it. Updates to existing packages (with the same version and channel), are already informed by "conan info". So you could run "conan info" in your projects in your CI, to discover which one needs to be rebuilt due to a change in dependencies.

Regarding issue #15, I am still not sure that the "latest" version is the best approach for CI either, as it will lead to non-repeatibility. Have all libs in your dependency graph depend on other libs to the latest version, and you have almost no package management, as versions are not stored. The idea is to move versions forward and switch versions as necessary. Packages can evolve from testing->...->rc1->rcX.->stable, and you can track individual failures in the dependency graph. When you have the full graph, in which all the libs point to "latest", and one upstream dependency, the latest version breaks everything, how do you recover?

I think the best could be to provide information helpers about dependencies, maybe an improved "conan info" that can be queried automatically and provides a more machine-readable format, would be useful.

Just sharing some thoughts and experiences, willing to go deeper into the CI pipelines issue and provide better support for it.

**Comment by monsdar** [comment] 2016-06-08 09:43
I think you mixed up libC in your example? Either way I guess I know what you meant. We use Pipelines because we would like to test if libB and libC are still working with a freshly committed version of libA. This way CI is telling us if we have issues in related components.

Conan does not need to trigger the next builds or something like that, this is what Go and Jenkins are there for.

Sounds good with #101, I guess this would then allow us to use the `CompA/HEAD@Foobar/CI` approach. However I share your opinion on using the same version for multiple builds. In one of the issues it is mentioned to have version ranges like `1.0.X` or `>1.0.0` available for requirements - I guess that way it is possible to have continuous versioning while dependent components can build with the latest version.

**Comment by memsharded** [comment] 2016-06-08 12:42
Ok, yes, I understand your use case too. Without doubt it is something that we developers want to be automated, and agree that the CI (Go, Jenkins) are there to configure it. Probably conan will have to improve some of its information tools, so it can provide useful info to CI, please open such specific issue for such feature request when you need it.

Will try to prioritize again the versions issue, it is something that we want to address, but (fortunately) we are always very busy to do, as it might require a large effort. Thanks again for your feedback!

**Comment by monsdar** [comment] 2016-08-26 15:57
I'll try the HEAD approach during the next week. My idea is that each component is built with HEAD of the dependencies, the CI system would trigger components that depend on my component.

If there is a need for a stable version one can always export and upload a package with a specific version.

**Comment by xlk3099** [comment] 2017-03-16 06:13
Hi, memsharded,

> We launch CI for each component when its code changes, every commit to libC will generate a CI build, it will build the project, create conan packages and upload conan packages to the conan server.

I have a CI like this: fetch project source -> build according to different settings -> run unit tests -> deploy. 
I want to integrate conan in the CI, so it would like: fetch project source -> build project according to different settings -> run unit tests -> build conan packages -> run conan tests -> upload to remote server.

From conan docs, there are two ways to create a conan package: install or test_package. If my local cache is empty. It would do "fetch source -> build" again, which is duplication. I want to avoid this duplication. Is there a easy way to create package from current project build directory?

I am also considering embrace conan fully into my CI process. e.g. 
`fetch -> build -> test-> deploy` to `conan source -> conan build-> conan test-> conan package -> conan upload`.

But the problem is with "conan build-> conan test", as running "conan build ." will generate a build in my current project directory but not in my local conan cache. Thus I am not able to create a package later. Is there a way to generate a build in the conan local cache?

**Comment by memsharded** [comment] 2017-03-16 09:40
Hi @xlk3099 

We are currently considering simplifying the UX for creating packages from pre-compiled binaries, which seems the use case that you are describing.

But the truth is that even if we make such easier, that is not the recommended flow, because it can be error prone and not easily reproducible. The main purpose of building the package in the local conan cache, is that it is a reproducible process, in which the configuration (settings and options) that affect the  resulting binary are much controlled, then more likely to produce the correct compatible binary. Also if some other user wants to enforce building the package from sources for their dependencies, they can just do it with ``--build``. If your main packaging model is packaging from your user build folder, that will allow to create binaries just for you.

As a tip, I would say that the vast majority of users using conan in production, they are actually building conan package binaries in CI servers, not in a local developer machine. The commands you are describing ``conan source``, ``conan build``, ``conan package`` are mostly tools for debugging, and developing locally. I'd say that there are 2 development modes:

- When you are actively editing the code of a package, modifying it, testing the package recipe.... The project is open in your user folder. You ``install`` the dependencies, then use your build system or IDE, edit, develop, run test, everything local in your folder. You can also debug your package recipe with the local conan commands (source, build, package). But please take into account that these commands are not intended for actually creating real packages. They are testing/debug helpers.

- When the package source code seems ready, everything look good, then the package is introduced in the system, and a clean build is done. This can be done in two ways:
  - Locally: with a ``export`` + ``install`` or a ``test_package``. In this case, it is true, a clean build will be fired, to be sure that the process is reproducible. 
  - Remote: pushing the package recipe to a remote repo, it will fire a CI job, that will typically build binaries, not only for one configuration, but probably for different OS, compilers, etc.

Said that, if you still want to put your local binaries into the package, without rebuilding it would be quite simple. Just write a ``build()`` method that instead of firing a build, will copy your binaries:
```python
def build(self):
      shutil.copytree("/home/user/path/to/your/binaries", ".")
```
Then if you are packaging for different configurations, like for different architectures, you have to take it into account:
```python
def build(self):
      if self.settings.arch == "x86":
           shutil.copytree("/home/user/path/to/your/binaries/32", ".")
      else:
           shutil.copytree("/home/user/path/to/your/binaries/64", ".")
```
or

```python
def build(self):
      shutil.copytree("/home/user/path/to/your/binaries", ".")

def package(self):
      if self.settings.arch == "x86":
           self.copy("*", src="32")
      else:
           self.copy("*", src="64")
```

The possible feature that we are considering is creating packages for precompiled binaries. It won't matter if they have been created with ``conan build``, or if they are just closed-source third parties that you want to package. As long as they are in user space and have not been created by conan, they are precompiled binaries, no guarantees of reproducibility.

Please tell me if this makes sense, or if you have any further question.

**Comment by xlk3099** [comment] 2017-03-16 17:31
Hi, @memsharded ,
Thanks for the detailed explanation. That helps.

> When the package source code seems ready, everything look good, then the package is introduced in the system, and a clean build is done. This can be done in two ways:
> 
> Locally: with a export + install or a test_package. In this case, it is true, a clean build will be fired, to be sure that the process is reproducible.
> Remote: pushing the package recipe to a remote repo, it will fire a CI job, that will typically build binaries, not only for one configuration, but probably for different OS, compilers, etc.

According to your said, if I am correct, so typically there shall be two repos, one repo for my project source code, another for conan recipe, and similarly two CI as well.

What you said makes sense to me, the 2nd CI(creating conan packages) better to be triggered only when the source code is for release. 

I propsose `conan source -> conan build-> conan test-> conan package -> conan upload` as conan reminds me the way maven handles Java dependencies. And in my case, I am the owner of a project so I want to have multiple packages(at least for different common settings) available immediately after I submit a code change.(I was trying to combine the two repos into one, by putting the conan recipe into my project-source code repo) I think using one CI actually makes sense in some scenarios, especially as conan is becoming more popular, it would be good if we can keep the recipe inside the project itself and only one CI is required.

**Comment by memsharded** [comment] 2017-03-16 22:37
Not really, you can also have the recipe in the source repo, check: http://docs.conan.io/en/latest/packaging/packaging.html#packaging-from-the-source-project

So typically 1 CI is perfect. It depends on your approach and workflows, having a separate repo for the recipe or have it in the source repo, it is up to you, but in either case, 1 CI job is fine (it will fetch the recipe to fire the build of the package). Some conan users have a repo with all the conan recipes, and then a separate source repo for each package, and building many packages (with transitive dependencies) when one code change is pushed. Feel free to contact us in our email if you prefer to chat to comment on  these issues.

**Comment by ytimenkov** [comment] 2018-01-10 09:00
> Asked in another way: Is there a way of defining "Always use the latest version" as a requirement? Do other developers have this issue?

I'm just researching conan now, but when I worked with CI pipelines before what really was needed is to consume not "the latest" version of dependency but "the version from previous stage of pipeline".

This is not the same, as single build chain (graph) can run in parallel from different branches and pipeline may stall for any amount of time (even include related manual steps).

For example, I do a new feature which includes changes in some library which is later consumed by some backend code (which also needs to be modified) which is later deployed to some staging environment and integration tests are ran against it. And I want to do it before I merge my changes to the upstream branch(es). The integration tests stage knows nothing about new changes, it just consumes what it is told to use, propagated from upstream.

The trick is to write recipes in such way that dependencies' versions (and/or user/channel) can be overridden by CI (e.g. via environment variables, command line options, etc), and I think conan has everything in place for this.

**Comment by jgsogo** [comment] 2018-09-12 13:41
Marking it as `obsolete`. It seems to me that all doubts are solved and we can close this issue.

**Comment by CAMOBAP795** [comment] 2019-03-10 19:17
I have one more CI related question:

Most of CI provide own cache mechanism, and in context of building heavy c++ libraries (especially for both debug and release modes) it may save time

From other side there is restriction for total cache size (for example on bitbucket CI it's 1Gb)

I have tried to cache only packages and skip caching build directory with object files:
 - `~/.conan/data/*/*/*/*/export`
 - `~/.conan/data/*/*/*/*/package`
 - `~/.conan/repository.json`

But conan still rebuilds everything from scratch

Any suggestions what need to be cached to omit 'cold' run?

**Comment by jgsogo** [comment] 2019-03-11 14:41
Hi! I would explore the _hack_ the other way around: cache all the folders but `build`, `export_source` and `source` folders... there are more files in the Conan cache that are actually used.

You can use the comman `conan remove --build --src [--force] *` to get rid of all the `build` and `source` folders.

**Comment by CAMOBAP795** [comment] 2019-03-11 16:25
@jgsogo thanks you so much! works like a charm

**Comment by jgsogo** [comment] 2019-03-11 16:47
Great!

**Closed by jgsogo** 2019-03-11 16:47 UTC
Labels: obsolete
