### ISSUE TITLE
[question] Missing include directories

### ISSUE THREAD

**Issue by damian-tomczak** [conan-io/conan#14071] opened 2023-06-12 11:08 UTC
### What is your question?

Hi,

I'm refactoring my lib for using conan and I have com the the point where I have no idea what could went wrong.
At least I'm begging for the ideas how can I debug this.

---
Main observation
My lib uses docker image with light weight linux and fetchcontent as the previous method of adding dependencies, due to the time of compiling I have moved to the conan.

When I want to set up project with raw docker container it throws compiling errors about lack of headers files (seems every dependency haven't been included [when I'm adding them manually by target_include_directories, linker doesn't complain so the problem is probably only with including directories {the dependency's dir I'm getting by printing ${fmt_INCLUDE_DIR}}]).

When I'm doing the same with .devcontainer.json by vscode it also throws the same errors BUT ONLY FIRST TIME, when I'm doing again "rebuild container" the project is compiling fine WITHOUT any errors.
---

Conan is already installed on the docker image and the setup of the project looks this way
```
conan profile detect --force
conan install . --output-folder=build --build=missing
```
First compilation on docker container with vscode as the wrapper and every n time on docker container without vscode and rebuilding it:
```
[build] In file included from [CONFIDENTIAL]/test_printable.cpp:6:
[build] [CONFIDENTIAL]printable.h:8:10: fatal error: fmt/format.h: No such file or directory
[build]     8 | #include <fmt/format.h>
```

I beg for the help how can I debug it, because I doubt if someone would know the answer for it.
If something is misunderstand let me know because I have no doubt this is very milky.

conanfile.py:
```py
class MyPackage(ConanFile):
    name = "MyPackage"
    version = "1.0"
    settings = "os", "compiler", "build_type", "arch"
    exports_sources = "*"
    generators = "CMakeDeps"
    requires = [
        "fmt/8.0.1",
       ...]

    def generate(self):
        tc = CMakeToolchain(self)
        tc.generate()

    def build(self):
        cmake = CMake(self)
        cmake.configure({})
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

    def package_info(self):
        self.cpp_info.components["comp1"].libs = ["comp1"]
        self.cpp_info.components["comp1"].requires = ["fmt::fmt"]
        self.cpp_info.components["comp1"].set_property("cmake_target_name", "comp1")

        self.cpp_info.components["comp2"].libs = ["comp2"]
        self.cpp_info.components["comp2"].requires = ["comp1"]
        self.cpp_info.components["comp2"].set_property("cmake_target_name", "comp2")

```
```cmake
find_package(fmt REQUIRED)

project(comp1)
add_library(comp1 STATIC)

target_link_libraries(${PROJECT_NAME} PUBLIC
    fmt::fmt #the same is with "fmt"
)
```

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-06-12 11:47
Hi @damian-tomczak 

The ``find_package()`` cannot happen before ``project()``, but after it. This might be the cause why the first pass it doesn't find it, but once the project is configured, second pass might find it. Can you please try moving it?

Also, in the general case avoid using the output-folder in ``conan install . --output-folder=build``, but instead use a ``layout()`` definition.

**Comment by damian-tomczak** [comment] 2023-06-12 11:57
> Hi @damian-tomczak
> 
> The `find_package()` cannot happen before `project()`, but after it. This might be the cause why the first pass it doesn't find it, but once the project is configured, second pass might find it. Can you please try moving it?
> 
> Also, in the general case avoid using the output-folder in `conan install . --output-folder=build`, but instead use a `layout()` definition.

Okay I have come to the conclusion that the problem isn't really with the case described above but overall approach.
Because I did a simple project that is based on package_info example from examples2 and there is also a problem with fmt:
```
user@ubuntu:~/Desktop/components/falcon/build$ make
[ 25%] Building CXX object ai/CMakeFiles/ai.dir/src/ai.cpp.o
/home/detok/Desktop/components/falcon/ai/src/ai.cpp:3:10: fatal error: fmt/format.h: No such file or directory
    3 | #include <fmt/format.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```
https://github.com/damian-tomczak/conan-test
Could you take a look on it?

```
cd falcon
conan install . --output-folder=build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake ..
```

**Comment by memsharded** [comment] 2023-06-12 12:14
You are building in Debug type, but you didn't specify that at conan install time:

```bash
conan install . --output-folder=build -s build_type=Debug
....
```
Otherwise, it installed the Release dependencies, but by default the build will expect Debug dependencies.

**Comment by damian-tomczak** [comment] 2023-06-12 12:48
WORKS THANK YOU VERY MUCH <3

**Closed as completed** 2023-06-12 12:48 UTC
