### ISSUE TITLE
Conan generators do not generate specific files

### ISSUE THREAD

**Issue by sandybhat16** [conan-io/conan#15448] opened 2024-01-12 09:42 UTC
### Conan generators do not generate specific files

Hi,

I am trying to create a package from pre-built binaries by following the doc [here](https://docs.conan.io/2/tutorial/creating_packages/other_types_of_packages/package_prebuilt_binaries.html).

I am able to create the package but when I install it using CMakeDeps generators, I do not get specific files that contain configs, path to include dir, etc. Is there anything additional that is required from what I have already done?

Below is my conan recipe:

```
from conan import ConanFile
from conan.tools.files import copy
import os
import shutil

class BoostRecipe(ConanFile):
    name = "boost"
    version = "1.71.0"

    # Optional metadata
    license = "xxx"
    author = "xxx"
    #url = "xxx"
    description = "C++ interface to the boost library."
    
    settings = "os", "compiler", "build_type", "arch"
    
    #exports_sources = "*.hpp", "*.lib"
    
    def layout(self):
        _os = str(self.settings.os).lower()
        _arch = str(self.settings.arch).lower()
        self.folders.build = os.path.join("win32-MSVC19")
        self.folders.source = self.folders.build
        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["lib"]

        
    def package(self):
        local_include_folder = os.path.join(self.source_folder, self.cpp.source.includedirs[0])
        local_lib_folder = os.path.join(self.build_folder, self.cpp.build.libdirs[0])
        copy(self, "*.hpp", local_include_folder, os.path.join(self.package_folder), keep_path=True)
        copy(self, "*.lib", local_lib_folder, os.path.join(self.package_folder), keep_path=True)
        
    def package_info(self):
        self.cpp_info.libs = ["boost"]
```

and I run the command

`conan install . -g CMakeDeps -of "C:\generated\Debug"`

But I get only the below files.

![image](https://github.com/conan-io/conan/assets/143775835/522a2396-7603-4234-b3f2-56f59ebb2b91)

I am expecting something like below:

![image](https://github.com/conan-io/conan/assets/143775835/147b909c-9ca3-4153-9bb7-af602f45b0ef)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-01-12 11:01
You are writing a recipe for boost, you are not requiring boost.
``CMakeDeps`` generate files for your dependencies, not for yourself. If you want to depend on boost:
- do not call your recipe ``name = "boost"``
- Add a ``requires = "boost/version"``

**Comment by sandybhat16** [comment] 2024-01-15 17:05
Thank you for your response @memsharded . That makes sense.

Alright, as per your suggestion I did change the recipe and called my package "custom". Now the generator generates the files. However I get an error when I run the CMake. 

New Recipe:

```
from conan import ConanFile
from conan.tools.files import copy
import os
import shutil

class CustomRecipe(ConanFile):
    name = "custom"
    version = "1.71.0"

    # Optional metadata
    license = "xxx"
    author = "xxx"
    #url = "xxx"
    description = "xxx"
    
    settings = "os", "compiler", "build_type", "arch"
    build_policy = "never"
    
    def layout(self):
        _os = str(self.settings.os).lower()
        _arch = str(self.settings.arch).lower()
        root_folder = os.path.join("win32-MSVC19_test") if self.settings.arch == "x86" else os.path.join("win64-MSVC19_test")        
        self.folders.build = root_folder
        self.folders.source = self.folders.build
        self.cpp.source.includedirs = ["include"]
        self.cpp.build.libdirs = ["lib"]

        
    def package(self):
        local_include_folder = os.path.join(self.source_folder, self.cpp.source.includedirs[0])
        local_lib_folder = os.path.join(self.build_folder, self.cpp.build.libdirs[0], "debug") if self.settings.build_type == "Debug" else os.path.join(self.build_folder, self.cpp.build.libdirs[0], "release")
        
        copy(self, "*.hpp", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.ipp", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.h", local_include_folder, os.path.join(self.package_folder, "include"), keep_path=True)
        copy(self, "*.lib", local_lib_folder, os.path.join(self.package_folder, "lib", str(self.settings.build_type).lower()), keep_path=True)
        
    def package_info(self):
        self.cpp_info.libs = ["custom"]
```


CMake Error:

> Install finished successfully
> 
> Conan: Target declared 'custom::custom'
> CMake Error at generated/Debug/cmakedeps_macros.cmake:67 (message):
>   Library 'custom' not found in package.  If 'custom' is a system library,
>   declare it with 'cpp_info.system_libs' property
> Call Stack (most recent call first):
>   generated/Debug/custom-Target-debug.cmake:24 (conan_package_library_targets)
>   generated/Debug/customTargets.cmake:26 (include)
>   generated/Debug/custom-config.cmake:16 (include)
>   Helper.cmake:231 (find_package)
>   myModule/CMakeLists.txt:18 (SetLibAndIncludePathForConanPackage)
> 
> 
> Configuring incomplete, errors occurred!

**Comment by memsharded** [comment] 2024-01-15 17:56
Hi @sandybhat16 

Sorry, without your ``CMakeLists.txt`` is impossible to know what could be happening. Please share your ``CMakeLists.txt``.
In order to reproduce please share:
- Your ``conanfile``
- Your ``CMakeLists.txt``
- The ``conan install`` command that you are doing, with its output
- The ``cmake`` command that you are doing with its output

Please do not attach images for the output, but copy and past it as text.

Also, some further feedback, it seems that you can simplify your ``layout()`` + ``package()`` method, if you are not building with Conan (but you kind of are building with Conan, because you ``conan install`` first to install dependencies). So why wouldn't you use the ``build()`` method to fully automate the Conan package creation instead of relying on ``conan export-pkg``?

**Comment by sandybhat16** [comment] 2024-01-16 08:12
Hi @memsharded ,

Thanks for the feedback. Will look into it.

I am attaching the cmake(compact version just for testability) and the conan file.
[CMakeLists.txt](https://github.com/conan-io/conan/files/13947139/CMakeLists.txt)
[CustomRecipe.txt](https://github.com/conan-io/conan/files/13947140/CustomRecipe.txt)

The conan install is called within the cmake file.

Conan command used to create a package:
`conan export-pkg CustomRecipe.py -s arch=x86 -s build_type=Debug`

Below is the output from cmake:

> CMake Warning (dev) in CMakeLists.txt:
>   No project() command is present.  The top-level CMakeLists.txt file must
>   contain a literal, direct call to the project() command.  Add a line of
>   code such as
> 
>     project(ProjectName)
> 
>   near the top of the file, but after cmake_minimum_required().
> 
>   CMake is pretending there is a "project(Project)" command on the first
>   line.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> CMake Warning (dev) in CMakeLists.txt:
>   cmake_minimum_required() should be called prior to this top-level project()
>   call.  Please see the cmake-commands(7) manual for usage documentation of
>   both commands.
> This warning is for project developers.  Use -Wno-dev to suppress it.
> 
> Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19045.
> 
> ======== Input profiles ========
> Profile host:
> [settings]
> arch=x86
> build_type=Debug
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Debug
> compiler.version=193
> os=Windows
> 
> 
> Profile build:
> [settings]
> arch=x86_64
> build_type=Release
> compiler=msvc
> compiler.cppstd=14
> compiler.runtime=dynamic
> compiler.runtime_type=Release
> compiler.version=193
> os=Windows
> 
> 
> 
> ======== Computing dependency graph ========
> 
> Graph root
>     cli
> Requirements
>     custom/1.71.0#d6bf8fc5c46e26da14b9a30b730af04d - Cache
> 
> ======== Computing necessary packages ========
> 
> Requirements
>     custom/1.71.0#d6bf8fc5c46e26da14b9a30b730af04d:42c6268614e0ef436ecf9816be8e285e6ce58797#a81b07676b74c67d9147a7f2fa3de138 - Cache
> 
> 
> ======== Installing packages ========
> 
> custom/1.71.0: Already installed! (1 of 1)
> 
> 
> ======== Finalizing install (deploy, generators) ========
> 
> cli: Writing generators to C:/Users/myuser/Documents/Work Related/conan/CmakeConan\generated\Debug\
> 
> cli: Generator 'CMakeDeps' calling 'generate()'
> 
> cli: Generating aggregated env files
> cli: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
> 
> Install finished successfully
> 
> Conan: Target declared 'custom::custom'
> CMake Error at generated/Debug/cmakedeps_macros.cmake:67 (message):
>   Library 'custom' not found in package.  If 'custom' is a system library,
>   declare it with 'cpp_info.system_libs' property
> Call Stack (most recent call first):
>   generated/Debug/custom-Target-debug.cmake:24 (conan_package_library_targets)
>   generated/Debug/customTargets.cmake:26 (include)
>   generated/Debug/custom-config.cmake:16 (include)
>   CMakeLists.txt:14 (find_package)
> 
> 
> Configuring incomplete, errors occurred!

**Comment by memsharded** [comment] 2024-01-16 08:57
I am afraid I still can't reproduce, because I don't have a way to create your ``custom`` package, and the error is:

> Library 'custom' not found in package.

It is very likely that your ``conan export-pkg CustomRecipe.py -s arch=x86 -s build_type=Debug`` is failing to correctly package things, because the paths are incorrect or something like that.

Do not try to use a package until you have checked that the package is correctly created. The recommended way to work would be something:

- Start with something simple, that works. Recommended to start with the ``conan new cmake_lib -d name=custom -d version=0.1``
- Try the ``conan build . `` + ``conan export-pkg .`` flow. See how the first step correctly build the library and the second one ``export-pkg`` the library
- As commented above this is not even recommended. If you are actually building things, the ``conan create .`` will be more robust, reproducible and better in the majority of cases. Add the ``build()`` method and use ``conan create .`` instead of ``build + export-pkg``. I am just introducing this as a help to understand things
- From there, start modifying little by little the ``conanfile.py`` to package your library. Make sure that every ``conan export-pkg .`` command the ``test_package`` functionality keeps working.


Then, when you know that your package is correct, you can try to use it from other recipes.
Here, please:
- Avoid using custom ``execute_process(COMMAND conan install --requires=${Custom_Package_name}/${Custom_Version}`` and use the ``conan_provider.cmake`` from ``cmake-conan`` integration. 
- Do not introduce custom Conan things into your ``CMakeLists.txt``.
- Do not rely on custom ``--output-folder/-of``, use ``layout()`` to define location of folders.
- Do not pass ``REQUIRED PATHS ${Debug_Output_Folder}`` to the ``find_package()`` explicitly, it will be very problematic for other configurations
- Do not use ``include_directories("${${Custom_Package_name}_INCLUDE_DIR}")`` and ``link_directories("${${libName}_LIBRARIES}")``. Use ``target_link_libraries(...   custom::custom)`` instead

**Comment by memsharded** [comment] 2024-04-11 10:02
Closing this ticket as responded, don't hesitate to create new tickets for any further question, thanks!

**Closed as completed by memsharded** 2024-04-11 10:02 UTC
Labels: type: question
