### ISSUE TITLE
[conan_export.tgz.dirty] Situational corrupt file compression of large content

### ISSUE THREAD

**Issue by carobins** [conan-io/conan#6504] opened 2020-02-10 18:46 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 Build 1903
  * Build Agent: Azure DevOps
  * Conan version: 1.22.0
  * Python version: 3.7.5

### Steps to reproduce (Include if Applicable)
**Situation 1:** Running conan upload through an Azure DevOps Build Pipeline fails to compress large content, concluding in a **conan_export.tgz.dirty** file. We are attempting to compress a folder that is 1.57GB and contains many files (will share exact number of files later).

**Situation 2:** When rerunning the same conan upload through PowerShell on this same build machine (not through Azure DevOps), the upload succeeds (conan_export.tgz). 

**Verification of Bug:**
We rolled back the build machine to 1.20.5 and the upload was succeeding again on the build machine through Azure DevOps. Rolling back to 1.20.5 was somewhat arbitrary. We did not test any in between versions. However I assume this issue may have started at 1.22.0 with the introduction of the new --parallel feature if this in fact affects compression.

**Comment by memsharded** [comment] 2020-02-10 22:15
Hi @carobins 

Thanks very much for the report. It seems this is a duplicate of https://github.com/conan-io/conan/issues/6330, and is already fixed, to be release in next 1.22.1 (maybe even backported to 1.21.3)

If you happen to have the output to terminal, that would help to try to figure out some other apparently minor detail we are still investigating.

**Closed** 2020-02-10 22:15 UTC
Labels: duplicate
