### ISSUE TITLE
Build Matrix for options

### ISSUE THREAD

**Issue by LazyArch** [conan-io/conan#6162] opened 2019-12-01 00:25 UTC
Hi,
I'm new to conan, and trying to find my way. Here is my scenario:

I have a Utils library that I cant to upload as a package, it is built using CMake. The library has a matrix of config options, some are already set up using profiles for different compilers etc, essentially all of the "settings" that are default.

Now I also have about 20 options that I need to set in the conanfile.py, that are set in CMake to configure the binary. This is also working already.

What I am missing here, is a method for Conan to build a matrix of these settings before the package is exported to Artifactory. I've googled myself to death, and the best I can come up with is Bincrafters, but this limits me to a single option, and all of the settings.

Am I missing something silly, or do I have to manually iterate through the options to generate the different binaries?

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2019-12-01 12:50
Have you had a look to the conan-package-tools project? https://github.com/conan-io/conan-package-tools. Together with the conan-docker-tools might help.

**Comment by LazyArch** [comment] 2019-12-02 10:44
I have had a look, it led me to Bincrafters. But they have the same underlying methodology of creating a build matrix of settings, and not of options. The only option that is supported is one for Shared when building the lib.

**Comment by memsharded** [comment] 2019-12-02 13:29
Hi @LazyArch 

Ok, but in any case, I think this request makes sense as an external too, not in the Conan client:

- Many times build are distributed, not even running in the same machine
- Better error management, failure policies control: should I stop all builds if one fails, should I resume..?
- More control over custom logic: I need to generate the combinations of these options, but excluding certain variants, and only when in combination with this certain set of settings.

The ideal input for Conan is pre-configured profiles. Those can be easily generated with some scripting, but after they are generated, you can use them in a more structured way, as you need to give them names, and can use them in CI, developer machines, etc. Note that profiles can ``include()`` others and can also be composed in the command line too.

**Comment by LazyArch** [comment] 2019-12-02 13:37
Hi @memsharded 
That was what I leaning to, just wanted to check if I may have missed something in the meantime. 
I'll have to script the generation of our profiles, as I also don't see an easy way of passing the options to the `build()` step in conanfile.py.

**Comment by memsharded** [comment] 2019-12-02 14:38
Hi @LazyArch 

I am not sure what you mean. You can directly use options in your build() as:

```python
def build(self):
     if self.options.myoption == "myvalue":
         # do something
```

Remember you can use options in the command line, in combinations with profiles, if you want to combine them (command line options have priority over profile defined options). Also, options are intended to model binary-definition configuration. Different values of the options mean that different binaries are generated and managed. Is that your use case?

**Comment by LazyArch** [comment] 2019-12-02 15:24
> Also, options are intended to model binary-definition configuration. Different values of the options mean that different binaries are generated and managed. Is that your use case?
That it is.

But I seem to be getting confused. Our CI workflow is as such:
```

conan, *_ = Conan.factory()

conan.config_install(CONAN_CONFIG,
                     verify_ssl=False)

conan.install(path=str(source_dir),
              profile_name=args.profile,
              install_folder=str(build_dir),

conan.build(conanfile_path=str(source_dir),
            build_folder=str(build_dir))

conan.export_pkg(conanfile_path=str(source_dir),
                 name=args.name,
                 user='user',
                 channel='channel',
                 build_folder=str(build_dir),
                 force=True)

```
As I understand:

- conan.install() Installs all of the dependencies of the recipe as well as their options. **But is it possible to also set the options of the package being built?**
To clarify, I am building LibU, that depends on LibC. I need to set options for LibC to download the correct package, but I also need to set options for LibU to use when it is built.

- conan.build() - This builds LibU

- conan.export_pkg() - This packages LibU

**Comment by memsharded** [comment] 2019-12-02 15:34
> But is it possible to also set the options of the package being built?

No, but when you do the ``export-pkg`` in that moment YES, the options you specify are the options used for that package. 

The issue is that you are doing an "out-of-cache" build, and for that case you are the responsible of building locally correctly with the options that you care about for that package being built. The goal is that the final package should be identical if you built it with ``conan create -o mypkg:myoption=myvalue`` or with ``conan install`` + ``conan export-pkg -o mypkg:myoption=myvalue``.

Please let me know if this clarifies it a bit.

**Comment by AbrilRBS** [comment] 2024-02-06 22:55
Closing as solved as we didn't hear back from you and the proposed solution works. Thanks a lot for your question :)

**Closed by AbrilRBS** 2024-02-06 22:55 UTC
Labels: stage: triaging
