### ISSUE TITLE
Package creation fails with missing prebuilt package of self when requiring editable package

### ISSUE THREAD

**Issue by luke-elwood** [conan-io/conan#5834] opened 2019-09-27 14:39 UTC
Conan Version 1.18.5 on Linux Mint 18.2. 

Using this simple recipe 

```
from conans import ConanFile, tools
import os, platform

class ASGARD(ConanFile):
  name = "ASGARD"
  version = "1.7.2"
  exports_sources = "asgard.pro", "src/*", "asgard.qrc", "icons/*"
  settings = "os", "compiler", "arch", "qt_version"
  options = {"shared": [True, False]}
  default_options = {"shared": False}

  def build_requirements(self):
    self.build_requires("OEI_DataParser/[>=2.0]@elwood/stable")

  def requirements(self):
    if not self.options.shared:
      self.requires("OEI_DataParser/[>=2.0]@elwood/stable")

  def build(self):
    self.output.info("Build")
```
If the package OEI_DataParser/2.1.7@elwood/stable has been set to editable on my local machine then 
Running `conan create conanfile.py ASGARD/1.7.2@elwood/test`
Returns `ERROR: Missing prebuilt package for 'ASGARD/1.7.2@elwood/test` 

The OEI_DataParser dependency is an internal library that is used in many of our projects and is installed as editable as I am adding changes for another project. I switched back to build a new version of the ASGARD library and met with this error until I removed the OEI_DataParser as editable after which the ASGARD library builds fine. The OEI_DataParser library has no other dependencies in it. I would expect conan to be able to create the package while leaving OEI_DataParser in editable mode, or at least not give an error message saying package creation depends on itself. 

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment] 2019-09-30 13:36
I cannot reproduce the issue. The error is `ERROR: Missing prebuilt package for 'ASGARD/1.7.2@elwood/test` doing a `conan create` of ASGARD?

**Comment by luke-elwood** [comment] 2019-09-30 15:38
Yes, The error lists the package being created (ASGARD) as being missing and to rerun the command with the --build ASGARD option as long as the dependency is editable. Removing the package from editable mode fixes it and reinstating the dependency as editable breaks it again. 

I've now tried to recreate the issue in a simple test case with no luck. Is there any other logs I can provide from the create that fails?

**Comment by lasote** [comment] 2019-10-07 06:34
Any information would be useful if you have the complete output of the `conan create` for example.

**Comment by memsharded** [comment] 2024-01-08 09:00
Closing this as staled. Furthermore, editables have greatly improved since then, Conan 2.0 even allows to ``conan create`` an editable package, including the ``test_package`` of it.

**Closed by memsharded** 2024-01-08 09:00 UTC
Labels: stage: triaging
