### ISSUE TITLE
[proposal] keep_build is just skipping `build` step. Also need a flag to really keep build folder. 

### ISSUE THREAD

**Issue by ctin** [conan-io/conan#3401] opened 2018-08-27 12:32 UTC
## environment
* MacOS High Sierra 10.13.6
* conan version `1.6.1`

## requirements
As c++ developer sometimes I need to use incremental build. I.e. if my project is really big, and I found tiny bug and wanna fix it and re-run `conan create`. Right now, while build folder is clearing on each `conan create` call - I need to wait for a while to compile all of my sources. 
I searched docs and found `keep_build` flag, which is `Do not remove the build folder in local cache`. 
This is what i want! 
Tried this flag and actually found that `build` command is skipped with message
```
Won't be built as specified by --keep-build
```
Well, I need different behavior to run `build` command but keep `build folder` unchanged. 
To skip `build` command you need a new flag like `--skip-build`.

## some explanation details
With `--keep-build` flag I am expecting next behavior:
* First I am running `conan create . ` for my project. This command will copy sources, may be run CMake or somthing else;
* if last build has some errors, I wanna change my sources and run ` conan create . --keep-build`. This command will copy the sources (with new fixes), and run build for already created folders. So unchanged files will not be rebuilt and I will get much more less compilation time!
* instead I have message `won't be built as specified by --keep-build`

Actually proposal:
* use --keep-build as it described in [docs](https://docs.conan.io/en/latest/reference/commands/creator/create.html), just to keep build folder;
* if skip build step is required - add new command for it.

**Comment by memsharded** [comment] 2018-08-27 21:45
Hi @ctin 

The ``--keep-build`` is not intended for code changes, it was intended for package creators, who might change something in the packaging recipe, specifically the ``package()`` method, that might be iterated a couple of times until everything is packaged correctly.

Have you had a look to the local development workflow? For changing code and incremental builds, you probably want this flow, in which you develop and test the package, including using incremental builds, in your local user space, not in the local cache. Please have a look to: https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html Thanks!

**Comment by memsharded** [comment] 2023-02-22 23:33
``--keep-build`` has been fully dropped in 2.0.
For testing build, the local flow ``conan install`` + ``conan build`` + ``conan export-pkg`` should be used, but ``--keep-build`` no longer a thing, closing the issue.

**Closed by memsharded** 2023-02-22 23:33 UTC
