### ISSUE TITLE
[bug] pre_package and post_package HOOKS and get_env_context_manager

### ISSUE THREAD

**Issue by ShuangLiu1992** [conan-io/conan#10279] opened 2022-01-06 00:28 UTC
Not exactly a bug but more about when 
```
    hook_manager.execute("pre_package", conanfile=conanfile, conanfile_path=conanfile_path,
                         reference=ref, package_id=package_id)

    hook_manager.execute("post_package", conanfile=conanfile, conanfile_path=conanfile_path,
                         reference=ref, package_id=package_id)
```
are executed in https://github.com/conan-io/conan/blob/develop/conans/client/conanfile/package.py

These two hooks are inside `with layout.set_dirty_context_manager(pref):` of installer.py and when post_package is called, the package isn't in a fully usable state as auxiliary files are not generated yet.

Suppose I want to create a hook that upload a package immediate after it's been packaged, `context_manager` will also mark it dirty and prevent me from doing so.

For example `conan_cmd.upload([f"{reference}:{package_id}", "--remote", CONAN_REMOTE_NAME])` will result in
```
Upload package to REMOTE failed: Package reference:package_id is corrupted, aborting upload.
Remove it with 'conan remove reference -p=package_id'
```

Inside the current post_package hook, somehow if I call `conan reference:package_id upload --all`, the .dirty file is ignored and auxiliary files are correctly generated and the newly created package will be uploaded.
But I'm not confident it's 100% doing the expected thing and it is wasting time checking not just the newly packaged binary but all binaries of this reference.

I think user will expect when the post_package is called the packaging process is fully over,

so is it possible to move at least post_package to https://github.com/conan-io/conan/blob/develop/conans/client/conanfile/installer.py?
```
  with layout.set_dirty_context_manager(pref):
      pref = self._build_package(node, output, keep_build, remotes)
 hook_manager.execute("post_package", conanfile=conanfile, conanfile_path=conanfile_path,
                         reference=ref, package_id=package_id) # fields extracted from node
```

Alternatively can we add a different hook outside of layout.set_dirty_context_manager(pref):? For example `package_finished`... 

If this is acceptable I will make a PR.
@memsharded @lasote

**Comment by lasote** [comment] 2022-01-10 09:00
Hi, about moving the "post_package", regarding [this](https://github.com/conan-io/conan/pull/5647) shouldn't be done because it might be used to alter the package contents.

About introducing a `package_finished`, at first sight, I don't see why not if we document both methods properly at https://docs.conan.io/en/latest/extending/hooks.html

**Comment by memsharded** [comment] 2022-07-08 15:41
One important clarification: Calling ``conan`` from a running ``conan`` instance is not supported behavior, and it will not be supported behavior in 2.0 either. Conan application itself should not be called from any Conan code, not recipes, not hooks, not plugins(Conan 2.0), not deployers (Conan 2.0). Making Conan "re-entrant" would imply an big increase in complexity in many places, not worth the effort.

So the recommended approach, for this particular flow would be:

- This hook seems that it really wouldn't make sense in developer machines, because uploading every single local package creation while developers work, would be a mess. Plus it also means that developers can upload packages, which is typically not the case.
- If the feature is intended for CI, there are better ways to automate this:
   - Use some of the generated files, like ``json`` output of Conan commands.
   - Have the CI read the json files
   - Use that information to do the upload


Conan 2.0 also implements custom user commands, so users will be able to implement a ``create_and_upload`` command if they want to (and the CI could just call that command).

But in the meantime, we would need some other evidence and use cases for such a hook extension point to be added

**Comment by memsharded** [comment] 2022-07-27 11:15
Closing this. This is not a bug, but expected behavior, and OP didn't follow up the above recommendations and discussion.

**Closed as not planned by memsharded** 2022-07-27 11:15 UTC
Labels: stage: triaging
