### ISSUE TITLE
[bug] transitive dependencies headers and libs are not propagated

### ISSUE THREAD

**Issue by WBurzynski** [conan-io/conan#15814] opened 2024-03-05 15:52 UTC
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: GCC 11.4
* Conan version: 2.0.17
* Python version: 3.12.1

### Steps to reproduce

1. clone repos: https://github.com/WBurzynski/minimal_example_lib and https://github.com/WBurzynski/minimal_example_consumer
2. create package from minimal_example_lib
```
cd minimal_example_lib
conan install . --build=missing -s build_type=Debug -of <output path>
conan create . --build=missing
```
cd minimal_example_consumer
3. consume package from minimal_example_consumer
```bash
cd minimal_example_consumer
conan install . --build=missing -s build_type=Debug -of cmake-build-debug/conan
```
4. Build `minimal_example_consumer` project. I used CLion for this, but same thing happens when just using CMake:
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=<output path>/build/Debug/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW
cmake --build . --target minimal_example_consumer
```

Expected outcome:
Package and its dependencies will be consumed correctly.

What happeded:
Transitive dependencies require explicit setting of include directories and linking in cmake, despite setting in `conafile.py` in `requirements(self)` `self.requires(lib, transitive_headers=True, transitive_dependencies=True)`

Description:
I was migrating internal library to at my company to conan 2.0. The library itself works fine, but transitive dependencies were not propagated correctly. I found possible solution in https://github.com/conan-io/conan/issues/13308 and https://github.com/conan-io/conan/issues/13856 but this did not work for me. I still have to manually add each dependency to `target_include_directories`  and `target_link_libraries`. I prepared dummy repos to demonstrate issue:
https://github.com/WBurzynski/minimal_example_lib
https://github.com/WBurzynski/minimal_example_consumer

**Comment by memsharded** [comment] 2024-03-05 16:49
Hi @WBurzynski 

Thanks for your detailed report.

Some quick feedback: the ``find_package()`` should use ``CONFIG``, not ``CONFIGS``, not sure, probably it doesn't matter, but worth checking.

I have run a first try in my system, Windows/MSVC, and I cannot see errors in ``#includes``, are they expected to happen? Or should I comment the ``target_include_directories(minimal_example_consumer PUBLIC ${minimal_example_INCLUDE_DIR}
${fmt_INCLUDE_DIR})`` so it fails? (just in case, in my case it will fail with a linking error, not a ``#include`` one.

Do you know if this fails the same in every platform?
Does it fail the same in Release and Debug?

It would be fantastic to be able to simplify this and get rid of the ``boost`` dependency, reproduce it only with ``fmt``, as ``boost`` is too heavy, it takes a while to build (it didn't have a binary for my configuration)

**Comment by WBurzynski** [comment] 2024-03-05 17:11
@memsharded Hello and thank you for quick response.

> should I comment the target_include_directories(minimal_example_consumer PUBLIC ${minimal_example_INCLUDE_DIR} ${fmt_INCLUDE_DIR}) so it fails?

yes

> Do you know if this fails the same in every platform?

We do not target windows. Tomorrow I'll test on NVidia Orin (which is  arm64v8).

> Does it fail the same in Release and Debug?

yes

> It would be fantastic to be able to simplify this and get rid of the boost dependency, reproduce it only with fmt, as boost is too heavy, it takes a while to build (it didn't have a binary for my configuration)

I wanted in my example two separate libs to have different dependencies for different components, i guess choice of boost was unfortunate. I commented out boost, so now it should build faster.

**Comment by memsharded** [comment] 2024-03-05 21:34
I managed to reproduce, and I think I was able to identify the issue.

The ``self.components["b"].requires = ["fmt::fmt"]`` is missing. The recipe is only defining the intra-package dependencies, but when defining components it is also necessary to define the requires to other packages or components of other packages, in this case ``fmt``.

It took me a lot to identify the issue and it was mostly because the too many levels of indirection. This recipe was complex to debug and understand. I'd recommend a more flat, explicit and compact (less jumps) recipe, even if it implies a bit more of repetition. Like:
```python
def package_info(self):
        for component in self._enabled_components:
            self.cpp_info.components[component.name].libs = component.libs
            self.cpp_info.components[component.name].requires = component.requires
```
Also the abstraction of the ``Component`` class might be more necessary if there are a lot of components in the recipe. For just a few, like 3-5, it is probably better just to be explicit, and encode things directly in the ``package_info()`` method.

**Comment by WBurzynski** [comment] 2024-03-11 10:28
seems like cleaning up conanfile and adding `requires` to like you suggested did the trick. I still have rectify cicd issues, but i belive they are unrelated to this particular problem

**Comment by memsharded** [comment] 2024-03-11 10:40
> I still have rectify cicd issues, but i belive they are unrelated to this particular problem

Then maybe lets close this issue as solved. You can always open a new issue for any further question or problem. Thanks!

**Comment by WBurzynski** [comment] 2024-03-15 11:38
No, thank you for support.

**Closed as completed** 2024-03-15 12:17 UTC
Labels: type: question
