### ISSUE TITLE
Shared folder for packages

### ISSUE THREAD

**Issue by tobyas** [conan-io/conan#180] opened 2016-02-26 11:08 UTC
This is a feature suggestion. Having a shared folder for a package could allow package to allow data between them. This could allow them to share equal elements between them. Common use case would be header files, since they only need to be accessible once per version. This would remove wasted disk space and improve the speed of creating a new package since the headerfiles would be shared. E.g. boost has 100mb of header files which are duplicated in each package.

**Comment by memsharded** [comment] 2016-02-29 01:47
Hi @tobyas,

Thanks for the suggestion, but it seems that so far this has not been a problem at all for real production usage with conan, as both disk and bandwith are really, really cheap. 100Mb is not a big issue, even if duplicated among a few packages, so it might be a bit of premature optimization. Source files are retrieved just once to create packages, and everything is zipped for download/upload performance, so the bandwitdh (download time) is very small compared with typical build processes time.

If it was a simple feature, we could consider it now, but it seems it isn't. The issue is that it is not always true that headers are shared among different package configurations, as there are many build processes that actually generate header files. That's why current conan approach handles compiled packages as isolated, even if sometimes a lot of headers files might be duplicated: it is the only way to ensure correctness (without adding extra complexity for the user). 

At this stage we are far more concerned about correctness than about optimizing performance. We ourselves are heavy users of conan, and we generate ourselves hundreds of compiled packages for libraries as boost, and these issues are not significant yet. We would like to implement this feature request, but our resources are limited, and we have to carefully chose and prioritize issues, so I would recommend closing this issue, until it becomes an actual problem.

Please tell me what you think, maybe I missed some other important point. Thanks very much for your feedback and your suggestion!

**Comment by tobyas** [comment] 2016-02-29 09:43
Hi,

I agree if this takes too much time to implement, then closing it is the way to go. Though maybe place it on a nice-to-have-list?

 I noticed it being a little bit annoying when I created a package which didn't build, but only copied already existing lib files. Making changes to the package and "building" it again took a more time than I expected, having a shared folder would reduce the time. If you have to build the package this probably becomes a nonissue, since actually building it should take more time anyway. Still actually having duplicate data still seems to be a bit messy. Of course it is not in any way a critical feature.

**Comment by lasote** [comment] 2016-03-11 16:42
You can use the "package" command to copy again the files from the corresponding build folder. I really think that this shared folder will hard the flow and that is error prone. I agree that all the tries you need until you make a complete and working conan package could be big, and that we can improve this process but I think the shared folder is not the right way.

**Comment by memsharded** [comment] 2016-11-29 11:41
Conan has evolved a lot since this issue. The duplication of headers files, even in large packages is not a big issue, and it provides more advantages than disadvantages, mainly a clear separation and isolation of the code in the different stages of the package process, and make it more robust under corner cases (not very often, but they happen), like packages modifying/creating header files at build time, different for different compilation options, so the headers cannot be shared among different binaries.

Furthermore, conan has already provided tools, like commands to execute partial processes, or the ability to work in the user space first before creating packages, that should reduce the failures and time required to create new packages.

So I think this issue can be closed, it would be a nice to have, but the complexity introduced in code and UX would be too much for a so far (and now there are many more conan users) unnecessary optimization. Thanks again for the feedback!

**Closed by memsharded** 2016-11-29 11:41 UTC
Labels: wontfix
