### ISSUE TITLE
conan profiles

### ISSUE THREAD

**Issue by laxmij-cmd** [conan-io/conan#15171] opened 2023-11-24 09:40 UTC
### What is your question?

Hi,

1. Is it mandatory to have profiles in ~/.conan2 dir? I was trying 
![image](https://github.com/conan-io/conan/assets/111378770/52bee7a4-825b-4e75-b0c4-2190f3d1bc7e)

by placing default profile in different dir other than ~/.conan2, it didn't work. 

2. When I created profile with name as myprofile as given in https://docs.conan.io/2.0/reference/config_files/profiles.html
![image](https://github.com/conan-io/conan/assets/111378770/0b134c62-2b67-4c6f-95a4-de166226a7a3)

![image](https://github.com/conan-io/conan/assets/111378770/25d44b21-42d0-4200-891c-35a16b61303b)

commands do not work. Error is

ERROR: the default build profile <~/.conan2/profiles/default' doesn't exist.
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>

It works only when I specify both --profile:build and --profile:host 
which is different from what is provided in help of conan profile

Please let me know if I am missing something here.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment] 2023-11-24 11:16
Hi @laxmij-cmd thanks a lot for your question.

Conan profiles are searched in order in a few places:
1. Relative to your current working directory
2. In the `<CONAN_HOME>/profiles` folder

So what you're seeing is a consecuence of the first point - it's looking for the profile in a place you're not expecting it to. If you pass any paths, they will be relative to where you've run Conan from.

But as you pointed out, both the docs and the Conan client help might be a bit misleading, I'll take a look into improving both :)

**Comment by laxmij-cmd** [comment] 2023-11-24 16:23
I am still not very clear:
1. when I provide complete path like conan install . <complete path>, should it not search profile in the <complete path>?
2. How does value of <CONAN_HOME> is set as I couldn't find it anywhere in the env?

**Comment by laxmij-cmd** [comment] 2023-11-24 16:35
rewriting 1 as some words got missed when saved:
when I provide complete path like conan install . <absolute-path>, should it not search profile in the  <absolute-path>?

**Comment by laxmij-cmd** [comment] 2023-11-24 16:35
absolute path is getting missed from conan install .

**Comment by laxmij-cmd** [comment] 2023-11-24 16:37
e.g 

cd def
conan install . /abc/xyz/conan/profiles/myprofile

Why conan doesn't search in above mentioned path?

**Comment by laxmij-cmd** [comment] 2023-11-24 16:38
I do not want to create .conan2 dir rather want to refer profiles from user defined dir

**Comment by AbrilRBS** [comment] 2023-11-30 14:16
Hi, sorry for the delay.

I just tested locally and running `conan install . -pr=/absolute/path/to/profile` works fine for me.
If you can share the logs of the commands you are running, that might help us solve your issue :)

**Comment by AbrilRBS** [comment] 2024-03-05 13:45
We didn't hear from you in a while, closing this, but please feel free to reopen/create new issues should you have any other questions!

**Closed as completed by AbrilRBS** 2024-03-05 13:45 UTC
Labels: type: question

**Comment by andrewerf** [comment] 2024-06-07 18:57
> I just tested locally and running `conan install . -pr=/absolute/path/to/profile` works fine for me.

It probably works for you because you have a default profile. Try to delete or rename the default profile and use some other profile with `-pr` flag. I was able to reproduce the problem, at least on windows with the following output:

```
You need to create a default profile (type 'conan profile detect' command)
or specify your own profile with '--profile:build=<myprofile>
```

**Comment by memsharded** [comment] 2024-06-08 09:05
Hi @andrewerf 

If you have detailed reproducible steps, it would be better to report them in a new issue, with the exact steps to reproduce, as you can see we were not able to reproduce it with the details above, and as this one is already closed, and it would be necessary to clarify more things, like the current Conan version, plus enough details. Many thanks!
