### ISSUE TITLE
[bug] TestClient module no longer usable from Conan 1.32.0

### ISSUE THREAD

**Issue by maikelvdh** [conan-io/conan#8247] opened 2020-12-22 09:27 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version:
  * Conan version: 1.32.0
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
Create a python file with `from conans.test.utils.tools import TestClient` 

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from conans.test.utils.tools import TestClient
  File "/usr/local/pkg/lib/python3.7/site-packages/conans/test/utils/tools.py", line 38, in <module>
    from conans.test.assets import copy_assets
ModuleNotFoundError: No module named 'conans.test.assets'
```

**Comment by memsharded** [comment] 2020-12-22 09:56
Hi @maikelvdh 

I am afraid that test resources are private, and cannot be imported from the outside. ``TestClient`` should never be imported. The fact that ``TestClient`` was available was an infortunate leak, because another Conan project (conan-package-tools) was using it, but that has been removed.

I don't think this is a bug, and most likely future Conan versions will completely remove the test scope from the python package.  If you would like to have access to that (at your own risk), you should be cloning Conan sources.

**Comment by jgsogo** [comment] 2020-12-24 10:46
I'm closing this issue. Not a bug and I think it doesn't require any further action. Feel free to open it again if you need something from us when rewriting those tests.

**Closed as completed by jgsogo** 2020-12-24 10:46 UTC
