### ISSUE TITLE
[bug] markdown - package is downloaded just to generate .md file

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10967] opened 2022-04-05 09:24 UTC
it would be nice to skip download of the package, and just generate a markdown based on the recipe (`conanfile.py` and it's `package_info` method).
there are some quite a big packages (e.g. LLVM) that may take several gigabytes literally.
it takes a time, traffic to download and extract these large packages just to generate a markdown file. it also wastes a disk space significantly.
related to https://github.com/conan-io/conan/issues/10965

### Environment Details (include every applicable attribute)
  * Operating System+version:
  * Compiler+version:
  * Conan version:
  * Python version:

**Comment by memsharded** [comment] 2022-08-31 14:29
This is a core behavior, and nothing can be done atm. Markdown generator, as every other generator, works on the ``cpp_info`` filled by ``package_info()`` of the dependencies. ``package_info()`` only executes against downloaded binaries (as it can contain ``collect_libs()`` and other stuff that will fail without the downloaded binary).

So this is not a bug, but expected behavior, and it cannot be changed.

**Comment by memsharded** [comment] 2023-12-01 13:50
markdown generator removed anyway in 2.0, closing ticket

**Closed as completed by memsharded** 2023-12-01 13:50 UTC
Labels: type: question

**Comment by SSE4** [comment] 2023-12-01 16:11
@memsharded what's the replacement?

**Comment by memsharded** [comment] 2023-12-01 16:58
None, we just generate the information in the backed for conan.io/center

**Comment by SSE4** [comment] 2023-12-01 19:54
> None, we just generate the information in the backed for conan.io/center

and for user?
