### ISSUE TITLE
[question] Conan integration in large Autotools project 

### ISSUE THREAD

**Issue by acevdev** [conan-io/conan#10927] opened 2022-03-30 12:22 UTC
Hi,
We have a large project with many dependencies and we want to migrate them to conan. This project is being compiled to several targets and we are using GNU Autotools to build the project. We have a custom build system and we can't rely on the conan build step (Autotools build helpers). 

Our build system roughly follows next steps:
1) autoreconfig -i
2) ./configure
3) make

In order to integrate conan, we've added as generator the conan AutotoolsDeps so we can execute the script and have the compile variables exported. This way, the integration of conan in our build system stays as follows:

1) autoreconfig -i 
2) conan install .
3) source conanautotoolsdeps.sh
4) ./configure
5) make

Everything works fine in small examples, but we find some issues related with our large project. This project relies on other internal static libraries that, at linking time, require flags defined by the conanautotoolsdeps.sh (technicaly: dependencies of that static library are defined on the main project). When linking, the order of LIBS is important. In our case the exported LIBS of conanautotoolsdeps, which should be appended to LIBS and not preppended,  interferes with our project LIBS.

My questions are:
1) How Autotools integration usually works with conan? 
2) Is there any way to do the integration without the need of Autotools build helpers or wrappers?
3) With the exported variables conanautotoolsdeps, any idea on how to control the order of LIBS flags? once these are combined with the project flags

Many thanks in advance.
Best regards,
acevdev

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-03-30 13:09
> How Autotools integration usually works with conan?

The previous Autotools integration has been working for a long time, and used widely in open source and enterprise settings. It is now being replaced by the AutotoolsDeps integration (and AutotoolsToolchain), which is much better architectured, but it is true that this is relatively new, and it needs to be matured and stabilized a bit more.

> Is there any way to do the integration without the need of Autotools build helpers or wrappers?

Of course. For dependency information you can use the ``PkgConfigDeps`` if you prefer to try a ``pkg_config`` based approach.
Or you can access the dependencies information in your ``generate()`` method and do whatever you want there, store them in an environment, save a script, generate any other file with the syntax that you want... Then, if you plan to reuse that in multiple recipes, you can put it in a ``python_requires`` and reuse it everywhere.

> With the exported variables conanautotoolsdeps, any idea on how to control the order of LIBS flags? once these are combined with the project flags

It seems there are 2 different things here:
- It seems there can be a bug in the relative order of LIBS by ``AutotoolsDeps`` for large graphs. In that case you should do nothing, but this should be fixed. I am marking this as such and pending to reproduce and fix it if true.
- Then the relative order in which the LIBS from ``AUtotoolsDeps`` are added to the current build, before or after the existing LIBS. I am checking the code, and it seems "LIBS" are appended and not prepended. It would be great if you could elaborate a bit more and clarify what is the exact behavior.

**Comment by acevdev** [comment] 2022-04-04 11:20
Hi again, 

> The previous Autotools integration has been working for a long time, and used widely in open source and enterprise settings. 

With the previous Autotools integration, do you mean by using the "make" generator? If so, we were previously trying to build by using the Makefile generated by the make generator, but unfortunately, when trying to include this conan Makefile to our Makefile, a couple of errors are shown: "blank line following trailing backslash" and variables " must be set with '=' before using '+='". We could code an intermediate script to succesfully include the conan Makefile, but we wondered if there is a cleaner way to make use of the dependencies.

>For dependency information you can use the PkgConfigDeps if you prefer to try a pkg_config based approach.

Our issue is that we need Autotools to consume this dependency information, and so far we didn't find a direct way to do it with the pc files provided by pkg_config generator.

**Regarding to the LIBS order**, our problem is not related with the LIBS order generated by AutotoolsDeps. At linking time, our internal static library has a dependency defined on the main project, and misses the link to it due to the order, since the conanautotoolsdeps LIBS is placed before our project LIBS.

**Comment by lasote** [comment] 2022-04-12 09:07
> With the previous Autotools integration, do you mean by using the "make" generator? 

No, we meant the `AutoToolsBuildEnvironment` that is being replaced by the `AutotoolsToolchain` and  `AutotoolsDeps`/`PkgConfigDeps`

> Regarding to the LIBS order, our problem is not related with the LIBS order generated by AutotoolsDeps. At linking time, our internal static library has a dependency defined on the main project, and misses the link to it due to the order, since the conanautotoolsdeps LIBS is placed before our project LIBS.

I don't get why it misses the link due to the order, if LIBS values are `-lyour_library -ldep_from_conan -ldep2_from_conan` two thoughts:

- Looks like makes sense to specify first the deps from the dependencies in case `your_library` needs something from the dependencies.
- Even if `-lyour_library` is at the last position (evaluated latest) why is it missed? 

An example would be great.

**Comment by acevdev** [comment] 2022-04-27 11:58
Hi again and sorry for the late reply,

We finally fixed it thanks to your comment on specifying the deps of the dependencies, although we had to repeat a flag because of this internal static library which has a dependency defined on the main project.
In a nutshell, our final LIBS order looks like:
`-ldep_from_conan -ldep_from_conan2 ... -linternallib -ldep_from_conan `

The exported LIBS of conanautotoolsdeps need to be appended because we execute the `AutotoolsDeps `script as a final step before `./configure`.

Creating a so specific example would take us a long time. Anyways, thank you both very much for the replies :)

**Comment by memsharded** [comment] 2022-04-27 12:17
Hi @acevdev 

Great, thanks for reporting, happy that you found a solution.

Just wanted to keep you updated, we have been actively developing the new Autotools integration, and a bunch of changes will land in next 1.48:
- https://github.com/conan-io/conan/pull/11114 might add ``-Wl,-rpath`` flags (``flags.extend(["-Wl,-rpath -Wl,{}".format(libdir)])``
- https://github.com/conan-io/conan/pull/11054 ensures the linking order is the correct one defined by the topological order of the dependency graph
- https://github.com/conan-io/conan/pull/11063 adding PKG_CONFIG_PATH for improving the integration AutootoolsToolchain<->PkgConfigDeps
- https://github.com/conan-io/conan/pull/10978 added new ``conan new --template=autotools_lib`` (and ``autotools_exe``) templates for easier getting started and reproduction of issues. It also added an ``autoreconf`` helper method

We hope that these help keep improving this integration.
I think this issue might be closed then? Feel free to report any further issue as a new ticket. Thanks!

**Closed as completed** 2022-04-28 08:41 UTC
Labels: type: bug, stage: triaging
