### ISSUE TITLE
[bug] dependency options not applied to current recipe (ConanFile)

### ISSUE THREAD

**Issue by Johnnyxy** [conan-io/conan#4784] opened 2019-03-20 13:26 UTC
Hi there,

I am using Boost as dependency in a recipe. I have to switch with between ```boost:header_only=True``` and ```boost:header_only=False```.

While working on my code suddenly the ```options``` of build_dependencies specifically from boost are not applied to the ```options``` of my recipe.

I found out that if I do a ```conan install``` and ```conan build``` everything works.
But using ```conan create``` does not.

conan create: ```self.options["boost"].header_only``` ->does not exist
conan install/build: ```self.options["boost"].header_only``` ->exists

Have a look at the minimal example in the attachment. It shows with two seperate calls [create, (install, build)] that the ```build(self)``` cannot detect the boost options anymore.

Hopefully I did nothing wrong. :)

Best regards...

[conan_hello_world.zip](https://github.com/conan-io/conan/files/2988338/conan_hello_world.zip)

**Comment by danimtb** [comment] 2019-03-20 16:23
Hi @Johnnyxy and thanks a lot for reporting.

I have been able to reproduce your example. Here it is a test showing the bug:

```
    def create_options_test(self):
        boost_conanfile = textwrap.dedent("""
        from conans import ConanFile

        class package(ConanFile):
            name            = "boost"
            version         = "1.69.0"
            options = {"header_only": [True, False]}
            default_options = {"header_only": False}
        """)
        client = TestClient()
        client.save({"conanfile.py": boost_conanfile})
        client.run("create . conan/stable")
        client.run("create . conan/stable -o boost:header_only=True")

        consumer_conanfile = textwrap.dedent("""
        from conans import ConanFile

        class package(ConanFile):
            name = "first"
            version = "0.0.0"

        def build_requirements(self):
            self.build_requires("boost/1.69.0@conan/stable")

        def build(self):
            self.output.info("build require option: %s" % self.options["boost"].header_only)
        """)
        client.save({"conanfile.py": consumer_conanfile})
        client.run("install . lasote/stable -o boost:header_only=True")
        client.run("build .")
        self.assertIn("conanfile.py (first/0.0.0@lasote/stable): build require option: True",
                      client.out)
        client.run("create . lasote/stable -o boost:header_only=True")
        self.assertIn("first/0.0.0@lasote/stable: build require option: True", client.out)
```

**Comment by danimtb** [comment] 2019-03-20 17:09
This was also happening in Conan 1.12.3

**Comment by memsharded** [comment] 2019-04-28 23:27
I can explain a little bit this behavior, not sure that this is a bug:

- Options of build-requires are removed from the normal options when the graph is being processed.
- They are removed because options do affect the package_id, and by definition, build-requires do not affect the binary package_id at all, so their options cannot be part of the package_id computation.
- They do not fail in the local flow ``install`` + ``build`` because in that case the package_id is not being computed, because it is not really a package.

So if we want to have a consistent behavior, then, it is possible that the way to go is to remove that option also in the ``build`` command, so it will always print ``None``. Put it in other words: if build_requires cannot affect the binary package_id, they cannot affect the build, so if the ``build()`` method is using a build_requires option different value to do different things, it is something that will fail later: when the package is already built, and the build-require is no longer retrieved, it will produce a different package_id and then raise a package not found error! So the conclusion should be that by definition the ``build()`` shouldn't contain a reference to its build_requires (including the build-requires options).

Maybe if you could elaborate more what kind of logic you are implementing, we could further discuss this issue. Maybe it is not a build-require, but another type of dependency? (even one that does not exist in conan yet, it is a topic that we are discussing recently).

**Comment by Johnnyxy** [comment] 2019-04-29 10:43
Hi there,
I have a preprocessor macro that influences the usage of Boost in my C/C++ code:
```c++
#ifdef MY_BOOST_HEADER_ONLY
    code that does somthing with header_only libs
#else
    code that does somthing else like invoking std functions
#endif
```

To provide CMake with that macro I am checking in ```def build(self)``` if a dependency to boost exists and if the option ```self.options["boost"].header_only``` is set or not. The scenario exists that Boost is an optional dependency and does not be "build_required" at all.
```python
def build(self):
    ...
    cmake = CMake(self)
    if ("boost" in self.deps_cpp_info.deps):
        if (self.options["boost"].header_only):
            cmake.definitions["MY_BOOST_HEADER_ONLY] = 1
    ...
```

**Comment by Johnnyxy** [comment] 2019-05-02 07:25
@memsharded 
I have been thinking about your remarks. In fact the ```build_requires``` influences the build but not necessarily the ```package_id```.
My built code can use std-headers, boost-headers (header_only) or boost-headers-and-libs (static linkage).
Now none of these dependencies influence the ```package_id``` in any way as there is no runtime dependency (conan: ```requires```).

But at build time I have to find out if there is a boost dependency and what its options (```header_only```) are.
I could use the normal recipe options for that. But I was thinking that this would be redundant information as the build dependencies already specifiy what they are and how they are configured.
```python
class MyLib(ConanFile):
    ...
    options = {"use_boost": [None, True, "header_only"]}
    ...
```

**Comment by jgsogo** [comment] 2019-05-31 08:59
This is just my personal opinion, and we do know that in these things related to the graph model some of us have slightly different opinions and it is great to hear all the possible feedback from our users, especially those of you who have demonstrated great knowledge of Conan and are concerned about these topics.

I tend to think that a `build_require` should be only for sources/packages/tools that don't affect the final package: not the behavior, nor the ABI, neither the API,... everything should be the same regardless of the options of settings given to these build requires. I'm thinking about tools like CMake, libraries that are only used for testing (gtest, catch2,...),... those are not part of the final libraries.

If we are talking about a header-only library that won't be exposed through the API or the ABI of the final library, we could think about it as a build require, but from my point of view I would consider it `require - private`. Although it is a header only, it can still have information in the `cpp_info` that could affect its headers (preprocessor definitions) and in the end will affect my package and produce different binaries (I want it to have different package_id).

So I agree with memsharded that the way to go is to remove these options (coming from a `build_require`) from the local workflow so it behaves the same as the `conan create` one.

cc/ @madebr (#5243)

**Comment by memsharded** [comment] 2024-06-03 18:35
This was changed some time ago in Conan 2, including specific host/build profile options, using ``default_build_options`` in recipes to target specifically the tool-requires, etc.

I am closing the ticket as outdated, please don't hesitate to create new tickets for any further question, thanks!

**Closed by memsharded** 2024-06-03 18:35 UTC
Labels: type: bug, stage: queue, priority: medium, complex: medium
