### ISSUE TITLE
[question] Install latest version (or version range) from local recipes index

### ISSUE THREAD

**Issue by fschoenm** [conan-io/conan#17403] opened 2024-12-03 10:41 UTC
### What is your question?

In my CI, I use a `local-recipes-index` remote, from which I want to build the latest version of my packages. If I have a "normal" remote, I can do that with
```
$ conan install --requires pkg/[] -b missing
```
However, that doesn't seem to work with a local index:
```
$ conan list -r local-recipes *
Found 1 pkg/version recipes matching * in local-detectors
local-recipes
  attribute-processing-api
    attribute-processing-api/2.3.1@user/stable
$ conan install --requires attribute-processing-api/[]@user/stable -r local-recipes
[...]
======== Computing dependency graph ========
Graph root
    cli
ERROR: Package 'attribute-processing-api/[]@user/stable' not resolved: Version range '' from requirement 'attribute-processing-api/[]@user/stable' required by 'None' could not be resolved.
```

It seems, version ranges in general are not supported for local recipe indexes, even though `conan list` can determine all the versions in the remote.

Is this expected behavior? If yes, how would I go and build all the latest versions of my packages in that case. I don't really want to specify the explicit version in multiple places as that would be quite error-prone/easy to forget.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by fschoenm** [comment] 2024-12-03 13:09
@AbrilRBS I just saw your PR and just wanted to clarify that the issue has nothing to do with an "empty" version range. If I use `[*]` or `[>2]` (or another version range), the behavior is the same.

**Comment by AbrilRBS** [comment] 2024-12-03 13:17
Hi @fschoenm thanks for your question.

A few things to note here, as locally I'm not able to reproduce with a similar case in Conan 2.9. I've tried a very similar setup to yours locally, and I can't get this error to pop up

- An empty version range works as a deprecated feature, ideally you'd use `[*]`.
- You're running `--requires attribute-processing-api/[]@user/stable`, but in the reduced logs I see `attribute-processing-api/[]@trs/stable`, a different user/channel. What's your whole dependency graph like?

**Comment by fschoenm** [comment] 2024-12-03 13:26
@AbrilRBS 

> You're running --requires attribute-processing-api/[]@user/stable, but in the reduced logs I see attribute-processing-api/[]@trs/stable, a different user/channel. What's your whole dependency graph like?

Sorry, that was a copy & paste mistake. The user/channel is the same everywhere. There also are no other dependencies.

Are you saying, you can install version ranges from a local recipe index? Have you tried packages with a user/channel? Because that seems to be what breaks it for me. If I try with a local conan-center-index clone, it works but as soon as I add user/channel to a recipe, it fails:

```
$ conan list -r local-cci zstd*
Found 4 pkg/version recipes matching zstd* in local-cci
local-cci
  zstd
    zstd/1.5.0@oss/stable
    zstd/1.5.2@oss/stable
    zstd/1.5.5@oss/stable
    zstd/1.5.6@oss/stable
$ conan install --requires 'zstd/[*]@oss/stable' -r local-cci --envs-generation false
[...]
======== Computing dependency graph ========
Graph root
    cli
ERROR: Package 'zstd/[*]@oss/stable' not resolved: Version range '*' from requirement 'zstd/[*]@oss/stable' required by 'None' could not be resolved.
```

**Comment by AbrilRBS** [comment] 2024-12-03 21:05
Yes, I see - Trying it now again I'm in fact able to reproduce this with an empty conan cache, thanks for the report :)

**Comment by memsharded** [comment] 2024-12-05 15:15
Closed by https://github.com/conan-io/conan/pull/17408 for next Conan 2.11

**Closed as completed** 2024-12-05 15:15 UTC
