### ISSUE TITLE
Conan migrates settings back and forth always overwriting my settings with defaults

### ISSUE THREAD

**Issue by ytimenkov** [conan-io/conan#2718] opened 2018-04-05 12:13 UTC
As suggested in documentation I've created my own `settings.yml` file which I apply using `conan config install` (thanks for this useful feature).

However it happens that I may have slightly different conan versions (1.2.0 and 1.2.1 in my case) depending on how I run conan (machine-wide or user-local).

Every time I run different version of conan it just wipes my setting and replaces them with default ones, which is annoying.

I see that conan has logic to not overwrite settings always, I think it just needs to be tuned, or provide an option to forbid migration completely.

**Comment by memsharded** [comment] 2018-04-05 13:04
Yes, the truth is that the migrations are not prepared to have 2 different versions of conan running against the same local cache. 

Also, I don't see an obvious solution, other than using exactly the same versions or configuring different conan caches for them (CONAN_USER_HOME for the machine-wide and the user-local environments). Lets try to have a look.

**Comment by olivren** [comment] 2018-04-12 10:01
I have almost the same issue. We add our custom key in `settings.yml`, that we use in all our recipes, and it gets removed every time I upgrade to a new conan version.

My suggestion is to introduce a new file, `custom_settings.yml`, that will never be modified by conan. The full settings dict would be the union of the content of `settings.yml` and `custom_settings.yml`.

**Comment by memsharded** [comment] 2018-04-12 22:10
Thanks for the feedback, @olivren 

The issue with your suggestion is that it is not possible to "union" such things, what happens if you have in one:
`    gcc: [1, 2, 3]`
and in the other
`    gcc: [ 2, 3, 4]`

Then it is necessary to merge. But with merge it also comes merge conflicts... It is bit more of a challenge that it seems. Are you aware of the ``conan config install`` command? Have you considered using it to re-install your own settings.yml?

**Comment by olivren** [comment] 2018-04-15 14:47
Well, the union seems very well defined, to me. That would be `gcc: [1, 2, 3, 4]`. But maybe I missed some subtelty here, there may be some constraints that I don't know about. Anyway, in my use case I just introduced a new custom key with two values, `product: [mp, cw]`. It is the setting we use when we need to compile a package a bit differently for the two products we develop.

I learned about `conan config install` thanks to this Github issue. My understanding is that it replaces completely a Conan configuration with the one we provide. I am not quite comfortable with that, as I find it useful for new versions of Conan to update their config files accordingly. I wrote some python code that reads the `settings.yml` file using the `yaml` module, then adds my custom key, and finally writes the file back to disk. I run it as the first step of my build system, and it works well enough to ensure this custom key exists. (Also, this script ensures that our private Conan server is a known remote). The problem is when we use Conan in other situations. For example, a `pip install --upgrade conan` followed by `conan create [...]` will fail with an error 'unrecognized setting key "product"'.

**Comment by ytimenkov** [comment] 2018-04-15 15:55
@olivren If you read and write config, won't something like `conan config set` work? (Instead of custom scripts)

**Comment by olivren** [comment] 2018-04-15 16:12
Does it work for `settings.yml` ?

**Comment by ytimenkov** [comment] 2018-04-16 07:36
@olivren My bad :slightly_frowning_face: Shouldn't reply from phone w/o access to sources thinking about something completely different...

Although there are commands for updating configuration and profiles.

**Comment by memsharded** [comment] 2018-04-16 07:48
@olivren 

I don't think it is so well defined, because to be accurate it is not an union. If the second had [2, 3, 4], it means, that the user wanted to remove "1" from their setting. Installing back 1 in the available settings might not be what they want. 

The solution to this would be a merge, like in code, with insertions and deletions.

``conan config install`` works for settings.yml, but there is no command to edit entries in the file, ``conan config set`` only applies to conan.conf. I strongly believe that managing the settings via ``conan config install`` might be the most reproducible and convenient way.

**Comment by olivren** [comment] 2018-04-16 08:29
I see. I did not think about the need to remove some values from `settings.yml`. But is there a use case where someone would need to do that? Recipes can restrict at will the settings values they allow, so I don't see any harm in having too much things in `settings.yml`.

**Comment by memsharded** [comment] 2018-04-16 08:46
Yes, I also think so, I don't really see a reason to remove settings, but there are users doing such thing.

**Comment by memsharded** [comment] 2018-04-16 12:50
I would need more evidence for that feature, as it would introduce some extra complexity and IMHO the benefit is not that big, comparatively speaking:
- For teams, and sharing custom settings.yml, the ``conan config install`` is still needed, extra efforts in keeping local changes is not worth in this case, as all you want to do is to make sure the custom ``settings.yml`` from upstream are installed
- If the pain are the conan upgrades, overwriting the previous ``settings.yml``, I think this would be the thing to fix. Some things that could be tried:
  - Don't do automatic migrations anymore
  - Try to do the automatic merge, assisted by the user, when there are new default settings.

The result would be the same, like a merged settings, but not automatically at every conan command, but just once, automated or assisted at conan upgrades.

**Comment by ytimenkov** [comment] 2018-04-16 13:06
> the pain are the conan upgrades, overwriting the previous settings.yml
That's me! :smile: 

I guess teams using custom `settings.yml` do this on purpose and quite conscious about what they're doing and about upgrades of Conan.

Won't easy fix be allowing to opt out from automatic migrations via config setting?

**Comment by olivren** [comment] 2018-04-16 14:04
The pain is definitely that the custom changes to `settings.yml` are lost on conan upgrade. Not doing automatic migrations seems like a dead end, as each release of Conan adds useful new compiler versions and platforms and so on. Automatic merges are tricky, and if you are nervous about adding extra complexity then it certainly is a non starter.

There is a design choice I am curious about, actually. You chose to list all the available settings in a dedicated file, and to error out whenever an unknown settings value is encountered in a conanfile. My best guess to explain this design choice, is that this allows you to uniformize the Conan package ecosystem around a common set of settings, and also to prevent typo mistakes. I wonder: did you ever consider allowing dynamic settings, in addition to these "official" settings? That would remove a lot of use cases for which we need to modify `settings.yml` today (including my use case of a new "product" key).

As an example, Conan could consider any settings key or value that starts with an underscore to be legal, even if not present in `settings.yml`. I could then use `settings = 'os', '_product'` and `if self.settings._product == '_mp'` in my recipes, without changing `settings.yml`.

I realize I may be deviating from the original topic. Sorry about that.

**Comment by memsharded** [comment] 2018-04-16 15:36
>  My best guess to explain this design choice, is that this allows you to uniformize the Conan package ecosystem around a common set of settings, and also to prevent typo mistakes. 

Yes, this is exactly the reason, to uniformize, so same configurations always create the same package binary IDs (the hash of settings + options + requires). Also, to be able to implement some build helpers like ``CMake``, etc, which can internally try to do ``if self.settings.compiler == "Visual Studio"``, and things like that, that otherwise would be impossible.

> As an example, Conan could consider any settings key or value that starts with an underscore to be legal, even if not present in settings.yml. I could then use settings = 'os', '_product' and if self.settings._product == '_mp' in my recipes, without changing settings.yml.
I realize I may be deviating from the original topic. Sorry about that.

Actually, it is an interesting idea, we should consider something in this line. For values, it is not a big issue, as you can already use the "ANY" value for settings. But to define new settings on the fly, could be. Not sure if it might be just delaying or even masking (making later debugging more difficult) the issues, or could be a valid approach, but worth thinking about it.

**Comment by memsharded** [comment] 2018-04-16 15:38
@ytimenkov 
> Won't easy fix be allowing to opt out from automatic migrations via config setting? 

Yes, exactly, this could be an easy partial fix that could be provided. Not a long term solution, not valid for teams, but some users might find it convenient for their personal use.

**Comment by Lnk2past** [comment] 2018-06-12 14:52
I wanted to bump this to the top because I think this needs a little more attention.

In our CI pipeline we need to make sure that all of our build boxes get our modified settings.yml, which at this point is purely additive; removing items from settings.yml has proven more a headache than anything else due to how Conan treats references to values in recipes.

I still think there should be a second file that is used specifically for unions. A union is a well defined operation, [1,2,3] U [2, 3, 4] = [1, 2, 3, 4]. If a user explicitly removed element value 1, then perhaps they would not use this additional file. Seems like an easy opt-out for users that wish to control settings.yml more hands-on.

To summarize I think the following should be considered:
- introduce ```additional_settings.yml```
- conan should perform a union on ```settings.yml``` and ```additional_settings.yml```
- conan will maintain its current logic for handling the creation and overwriting of ```settings.yml```
- conan will not provide any logic for ```additional_settings.yml```

This I think makes it very easy to opt-out (simply do not create/populate ```additional_settings.yml```). Users that have simply added more values to their settings can now just maintain their own additional settings in their source control and distribute as needed.

For my use case this makes maintaining and upgrading conan versions across our network much simpler. We would not need to worry about keeping our settings and conan's settings in sync.

e.g. perhaps all we would really need to maintain would be the following:

```
compiler:
    gcc:
        version: ["8.1"]
build_type: ["CustomRelType"]
```
and Conan would do the rest.

**Comment by memsharded** [comment] 2018-06-12 15:08
The automatic migration when there are custom settings has already been removed. Custom settings.yml shouldn't be a problem anymore.

So it seems what you propose is too much of a complexity. Assuming that the custom file will be distributed with ``conan config install``, the procedure for the configuration manager would be:

- Get the default settings.yml
- Add gcc version 8.1 and CustomRelType build_type to it
- Done

Now the ``conan config install`` will install that custom settings.yml, and it will not be removed, replaced or changed by conan anymore. Getting updates of latest versions from conan is not necessary at all, in fact, they will mostly be useless without defining new profiles to use them. And if new profiles are being added to the ``conan config install``, then updating the custom ``settings.yml`` with the steps above is easy too. It is also a very sparse operation, if anything it would be changed every few months, by just 1 person, and can be done in a few minutes.

I strongly prefer the simplicity of just 1 settings.yml file, what you have there is what it is used, instead of an in-memory merge that would be more fragile, difficult to debug, understand and maintain.

**Comment by Lnk2past** [comment] 2018-06-12 15:19
Sorry, it is my own fault for not being up-to-date on my conan installations; I will read though the change logs to see what else has been missed on my end.

Perhaps this thread is to be closed then?

**Comment by memsharded** [comment] 2018-06-12 15:41
@Lnk2past No problem!! :)

The changelogs are usually long, and it is easy that this change can pass unnoticed. 
Sure, do check first that once you have your custom settings.yml, they are not removed anymore (that can be forced changing the <userhome>/.conan/version.txt contents to a previous version. And if everything is good, yes, I guess this could be closed.

When in doubt, conan prefers not to mess with user files, you and other users were right that this was at least annoying, so it was removed. Thanks for the feedback!

**Comment by Lnk2past** [comment] 2018-06-12 16:37
Custom settings are no longer removed and a .new file was created. Thank you for all of the information.

**Comment by memsharded** [comment] 2018-06-12 16:56
Great, thanks for telling! I think this issue could be closed then. Cheers!

**Closed by memsharded** 2018-06-12 16:56 UTC
Labels: look into
