### ISSUE TITLE
[question] how to check if remote package is up to date

### ISSUE THREAD

**Issue by conradjones** [conan-io/conan#5983] opened 2019-10-28 11:29 UTC
Apologies if i have missed the info in the documentation. 

Given I have the source of the conan package locally i would like to be able to determine if the package on the remote server is up to date, obviously the only info that can be used to determine this is the conanfile.py and any inline sources, if the remote package is not up to date build it.

I've been hacking various bits together calling conan internals from python like get_recipe_manifest and get_package_manifest, which I have working, but I'm still not 100 % sure what I should be comparing against what, and that maybe I missing something and there is a sensible way to do this. especially as i'm heavily breaking hyram's law here.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by Johnnyxy** [comment] 2019-11-27 13:50
Hi there,
you could manually create a hash value over the (source) files you want to be significant and add this hash value to the package-id. In turn this means the Conan package-id changes if the hash of the source changes. Every time the hash of the source file changes, a different package-id is calculated and then it can or cannot be matched to a stored package.

Generate hash value (loop over your files and create the hash in any way you want) only if no source hash has been provided as Conan option.
```python
class Recipe:
    options = {'source_hash': "ANY"}
    default_options = {'source_hash': None}

    def configure(self):
        ...    
        if (not self.options.source_hash):
            self.options.source_hash = YOUR_FUNCTION_THAT_CALCULATES_THE_HASH(...)
        ...
```
This will add the ```source_hash``` value to the structure which is used to calculate the Conan package-id.

**Comment by conradjones** [comment] 2019-11-27 17:14
interesting idea thanks, I'll have a look at that.

**Comment by lasote** [comment] 2019-12-04 08:06
@conradjones @Johnnyxy Have you checked the [revisions](https://docs.conan.io/en/latest/versioning/revisions.html) feature? Might it help?

**Comment by Johnnyxy** [comment] 2019-12-04 08:19
@lasote 
It seems this feature does fullfil the requested functionality. 

The followup question is, how can Conan know the revision/hash of the source used to produce a package? From the SCM feature it can, but if the feature is not used does Conan use the files placed in the ```sources``` folder of the recipe?

If so, this would raise the question what if there are no files provided by the ```source``` step and someone does the whole "get-sources-build-sources" in the ```build``` step. Then there won't be any files to hash in the sources folder.
There would have to be a way to specify the files for the revision calculation.

**Comment by lasote** [comment] 2019-12-04 08:28
Well, typically if you are downloading external sources you do it doing a git checkout of a commit/tag or downloading a zip from a specific URL. As the URL or the commit changes, the recipe revision will change, and the binaries associated with the recipe revision will be different.

**Comment by Johnnyxy** [comment] 2019-12-04 08:54
Ok ... corner case ... for a hypothetical scenario:

```python
def build(self):
    ...
    tools.get("http://abc.com/def.zip")
    ...
```

If the content of the ZIP changes, Conan will not detect that, thus the revision will not change caused by different source files.

**Comment by lasote** [comment] 2019-12-04 09:45
You can get the file specifying a checksum, e.g: `tools.get("http://url/file", md5='d2da0cd0756cd9da6560b9a56016a0cb')` In that case, if the zip changes, the recipe will be broken, and to fix it (consciously) you have to change the hash and the recipe revision will change.

**Comment by Johnnyxy** [comment] 2019-12-04 09:59
Yes this would help for deterministic builds with specific code "versions". As the thread creator asked in the end the question is solved :).

I have a followup question:
What if in my described case the code should automatically use some "latest" source from a generic archive-filename but still get different revisions to be save that changed source would change the revision (automatically)?
```python
tools.get("http://url/project-latest.zip")
```

**Comment by lasote** [comment] 2019-12-04 10:05
In that case, there is no support for revisions, but I would say it is not a good practice.

**Comment by AbrilRBS** [comment] 2024-04-22 09:21
Closing as solved in Conan 2 with the linked PR, which shows that Conan 2 will generate new revisions when the sources change, no need to change anything recipe-wise!

**Closed** 2024-04-22 09:21 UTC
Labels: stage: triaging
