### ISSUE TITLE
[bug] `conan install ..` does not generate files in current working directory

### ISSUE THREAD

**Issue by bdegreve** [conan-io/conan#13242] opened 2023-02-26 14:03 UTC
### Environment details

* Operating System+version: Windows 10 22H2
* Compiler+version: msvc 193
* Conan version: 2.0.0
* Python version: 3.11.0

### Steps to reproduce

1. Clone a project into a source directory, for example C:\source, so that C:\source\conanfile.py exists.
2. Create a build directory, for example C:\build: `mkdir C:\build`
3. change current working directory `cd /D C:\build`
4. `conan install ..\source`

With Conan 1.x, the build files like conanbuildinfo.txt or conan_toolchain.cmake would be generated in the current working directory, in this example in C:\build.

With Conan 2.0, these files are generated in the source directory containing the conanfile.py, in this example C:\source. This feels unexpected with regard to what a working directory should be.

**Comment by memsharded** [comment] 2023-02-26 19:39
Hi @bdegreve 

Thanks for your question.
There are a few files that are no longer generated at all in 2.0: ``conanbuildinfo.txt``, ``conaninfo.txt``, ``graph_info.json`` for example, are no longer generated.

Then, in 2.0, it is also important the current ``layout``. This concept has already been introduced in 1.X, and it is the recommended way to define the relative location of files when you do a ``conan install``. As the ``conanfile.py`` is located relative to some build scripts, the location of the generated files relative to the build scripts is necessary ,and this is what can be modeled in ``layout()``. The idea is that it doesn't matter anymore from where you call the ``conan install``, but the result will always be the same, files in the same location.

You can for example experiment with the ``conan new cmake_lib -d name=pkg -d version=1.0``, and type ``conan install .``, it will not pollute the current directory, because the ``cmake_layout()`` specifies the ``generators_folder`` where to put files

**Comment by bdegreve** [comment] 2023-03-05 16:33
Hi @memsharded , thanks for the info. Do you have advice on how to best handle following scenario.

Before, I created several build subdirectories in one source tree, to test different compilers or settings, or different Python versions, on the same source tree.  For example, I may have had build-vs2019, build-vs2022, build-python310, build-python311, ...  In each of them, I performed `conan install .. -pr <profile>` + `conan build .. --configure`

With `cmake_layout`, this build tree seems now predetermined by the conanfile.  Do you have any suggestions on how to achieve something similar as above?

**Comment by memsharded** [comment] 2023-03-05 23:51
Yes, there is now a built-in feature for this purpose the conf ``tools.cmake.cmake_layout:build_folder_vars`` can provide the different settings and options that will be part of the folder name that will be created. This already exists in Conan 1.X

In Conan 2.0 it is also possible to define it in the recipes, without defining a ``conf``, something like:

```python
 def layout(self):
                self.folders.build_folder_vars = ["settings.os", "options.shared"]
                cmake_layout(self)
```

It is true that this doesn't manage the variability of the Python interpreter.
For manual definition of other folders you might want to use the ``--output-folder`` argument. It sounds like a mixture of both approaches would be good:
- Different compilers, versions, options, etc could be managed built-in by the ``build_folder_vars``
- The external arguments like Python interpreter could be managed with the ``--output-folder``

**Comment by the-homeless-god** [comment] 2023-06-23 20:24
Still waiting for help & fix...

Now @bdegreve the solution is `brew install conan@1` or `pip install conan@1.59`

**Comment by memsharded** [comment] 2023-06-23 23:04
Hi @the-homeless-god 

This is not a bug, so it won't be fixed. The current behavior has been explained above, those files are not generated in Conan 2.0 and they will not be generated. The ``layout()`` method (also existing in 1.X) allows defining the destination of some files like the generated .cmake files.

If you want to obtain some of the information that was existing in files like ``conanbuildinfo.txt`` is possible to obtain it with the ``--format=json`` argument that exists in different commands like ``conan install`` and ``conan create``.

I am closing this ticket as responded, but don't hesitate to open new tickets for any further question that you might have. Thanks!

**Closed as completed by memsharded** 2023-06-23 23:04 UTC
Labels: type: question
