### ISSUE TITLE
[question] How do you get DLL file names in CMake?

### ISSUE THREAD

**Issue by flatline** [conan-io/conan#12957] opened 2023-01-23 18:26 UTC
### What is your question?

I've tried using the various CMake generators as well as the CMakeDeps and CMakeToolchain generators in conan 1.55. I've also played around with the conan 2.0 beta releases but have not examined their cmake output as closely; however they seem to have the same issue.

In the module-*.cmake generated files, there is a call to `add_library(<Target> INTERFACE IMPORTED)`. According to the [docs](https://docs.conan.io/en/latest/reference/generators/cmake.html) the imported conan targets are always designated as INTERFACE targets.

The immediate problem I'm trying to solve is how to add the necessary `install` directives to take the imported target libraries (*.dll, *.so) and package them with my software. On Windows, conan is only providing paths to the .lib files and not to the .dll files. For a shared library I would expect these to be imported as `SHARED` targets instead of `INTERFACE` and have the `IMPORTED_LOCATION` set with the info generated by conan so I can grab the library files directly.

Is there a way to get the .dll file locations from conan without rewriting the cmake template? I feel like I'm missing an important last-mile step here of packaging the conan cmake targets.

As an added bonus I would like to stage the .dll files for runtime and debugging purposes, on a per-configuration basis, but I cannot see a good way to do that presently without overriding the `generate` method and doing a `copy` in the conanfile. There, I have access to all the `cpp_info` data for each dependency. If there were a place to pass this into the generators and have them make use of them, that would also be acceptable.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-01-23 19:26
Hi @flatline 

I think this might be a duplicate of https://github.com/conan-io/conan/issues/12654, please check.

This is a known issue, and a challenging one to solve at the moment. Conan creates UNKNOWN or INTERFACE targets, because it does not have enough information to know the library type. And also the real libraries are indirectly included. We are trying to improve that, but that will be a longer time effort. Some improvements have been already done in Conan 2.0, which will label internal targets with the right type, so it will work.

In the meantime, the recommended approach is to use some Conan tools:

- To collect dlls, it can be done with a conanfile.py recipe with a ``generate()`` method that iterates over ``self.dependencies`` and calls ``copy(self, "*.dll", ...)``. this is in Conan 1.X
- Conan 2.0 has a mechanism designed for this: the ``deployers``. At the moment there are ``full_deploy`` and ``direct_deploy`` built-ins, but there will be likely more, and "runtime_deploy", to collect exes and dlls seems very likely. It is also possible to create user custom deployers easily, with your own logic, and that can be reused with ``conan config install`` and applied to any package and dependency graph, without needing to modify recipes.

**Comment by flatline** [comment] 2023-01-23 21:45
Thanks, yes, I think #12654 describes the same fundamental issue. I will note that the workaround [here](https://github.com/conan-io/conan/issues/12654#issuecomment-1351401060) is not sufficient for the cmake `install` directive. There is a chance that the interface library (.lib) filename does not match the runtime library name (.dll). With this approach we are left grabbing every dll by convention. I can leave a comment on that ticket as well ;)

**Comment by memsharded** [comment] 2023-01-23 22:54
Yes, please, lets follow up on https://github.com/conan-io/conan/issues/12654, and I will close this ticket as duplicated, thanks!

> will note that the workaround https://github.com/conan-io/conan/issues/12654#issuecomment-1351401060

Yes, but that is the best that Conan can do, as it doesn't have enough information. Only the build system have it, and often it is impossible to extract it after the build with robustness. So Conan would need to rely on further ``cpp_info`` definitions, probably ``cpp_info.set_property()``

**Closed as not planned by memsharded** 2023-01-23 22:54 UTC
Labels: stage: triaging
