### ISSUE TITLE
Login error after changing remote adress for existing remote name

### ISSUE THREAD

**Issue by MTomBosch** [conan-io/conan#11303] opened 2022-05-19 09:17 UTC
We are currently in the phase of migrating from one Artifactory instance to another one.
To make the migration as transparent as possible for the developers and our pipelines we have not introduced new remote names but kept the current remote names and just change the target address. After setting up the updated remotes we sporadically get login 403 errors in our pipelines with following error message: This request is blocked due to recurrent login failures, please try again in 15 seconds. We do not understand why we get this error since locally we cannot reproduce the error and also in the pipeline we can only sporadically get it.

The build machines running pipelines are doing the following:

- Via conan config install get the remotes (remote names are the same for the new remote but the target address has changed)
- Log out of current repos (if there is a login cached somehow) via: conan user --clean
- Source a sh script that sets the user/password env variables that sets per remote name a user/pw pair
- Login to the conan repos using conan user -p -r <repo remote name>
- Do Conan install ...

Important to know is that the same build machine is switching between the old and new Conan repo (via the conan config install and the sourcing of different user/pw env vars) depending on the pipeline job that is executed. Hint: On such build machine can only run one pipeline job at a time so concurrency is not an issue.

I have the feeling that the cached auth key could be an issue here but I am not sure. Any ideas on this issue?

Thank you

**Comment by memsharded** [comment] 2022-05-19 10:28
> I have the feeling that the cached auth key could be an issue here but I am not sure. Any ideas on this issue?

Yes, could be related, and unfortunately as you described, this might be a challenging issue to reproduce and fix.

Quick question, why are you doing both setting the env-vars and then ``conan user -p`` login? The idea of the env-vars for user/password is that they replace the need for an active login. And if you do the login, then you don't need the env-vars? Am I missing something here?

**Comment by MTomBosch** [comment] 2022-05-19 11:22
> > I have the feeling that the cached auth key could be an issue here but I am not sure. Any ideas on this issue?
> 
> Yes, could be related, and unfortunately as you described, this might be a challenging issue to reproduce and fix.
> 
> Quick question, why are you doing both setting the env-vars and then `conan user -p` login? The idea of the env-vars for user/password is that they replace the need for an active login. And if you do the login, then you don't need the env-vars? Am I missing something here?

The "conan user -p login" takes the credentials from the env vars to do the login since we have disabled interactive mode. 

Maybe the conan user -p is not required, I can try it out. But due to the fact that I cannot reproduce it easily I am not sure if this really helps.

I was hoping that someone says "I know this problem, it is because of ...".

Nevertheless thanks for the reply.

**Comment by MTomBosch** [comment] 2022-05-19 11:34
In the Conan docs it says that the auth key (after successful login) is saved in an internal db. Is it known where this db file is located? If it is in the Conan user home then using per pipeline job a dedicated user home might help to resolve this problem.

**Comment by memsharded** [comment] 2022-05-19 13:06
> In the Conan docs it says that the auth key (after successful login) is saved in an internal db. Is it known where this db file is located? If it is in the Conan user home then using per pipeline job a dedicated user home might help to resolve this problem.

Yes, it is stored in a sqlite database ``.conan.db`` inside the cache home folder, typically in your ``<userhome>/.conan`` folder. I also think having a different CONAN_USER_HOME per job would help, if you can try that, please check it.

**Comment by MTomBosch** [comment] 2022-05-19 19:58
OK. I was expecting that file too to store the auth key but during testing I could not see a changed date of the file after using a new password. Maybe I did something wrong here. In the end it does not matter much because we found the root cause:
Due to some internal concurrency/race condition issues we really used the wrong password (old pw for new remote). But after setting the correct password and trying to login we ran into the problem described here: https://github.com/conan-io/conan/issues/11303.

Maybe you know how long the expiry date of a wrong password/login data by when a new login is tried (see linked issue for details).

Anyway thanks a lot for trying to help. At least I now know a few things more about the authentication of Conan.

**Comment by memsharded** [comment] 2022-05-22 22:17
>In the end it does not matter much because we found the root cause:
Due to some internal concurrency/race condition issues we really used the wrong password (old pw for new remote). But after setting the correct password and trying to login we ran into the problem described here: https://github.com/conan-io/conan/issues/11303.

Happy to know you found the root issue!

> Maybe you know how long the expiry date of a wrong password/login data by when a new login is tried (see linked issue for details).

It seems you are linking this same issue? :) Did you intend to link another one I guess?

**Comment by AbrilRBS** [comment] 2024-12-17 12:05
Closing as solved as we didn't hear back from you, feel free to reopen/create a new issue if needed, thanks!

**Closed as completed by AbrilRBS** 2024-12-17 12:05 UTC
Labels: stage: triaging
