### ISSUE TITLE
Conan 1.16.0 broke cmake_multi RelWithDebInfo

### ISSUE THREAD

**Issue by bfierz** [conan-io/conan#5372] opened 2019-06-19 08:43 UTC
Hi,

The recent bugfix to #5131 broke our usage of using Release packages for RelWithDebInfo when using cmake_multi. This now requires to rebuild every package when we want to use RelWithDebInfo.
There shouldn't be a point of providing different release packages for external dependencies when RelWithDebInfo is only used for the development of a product.

Is there a way to use Release builds for RelWithDebInfo?

Best regards

**Comment by lasote** [comment] 2019-06-19 09:10
Yes, we consider it was a bug, the use case you describe (totally legit and common) cannot justify the previously mixed targets that the `cmake_multi` was creating.

You can override the build_type only for the "consumer" package only, for example:

`conan create . user/channel -s OpenSSL:build_type=RelWithDebInfo`

It would retrieve the OpenSSL deps for RelWithDebInfo but build the rest of the packages for Release (Default profile). The generator will generate a "release" file, but containing the OpenSSL package for RelWithDebInfo.

Let me know if it works correctly

**Comment by bfierz** [comment] 2019-06-19 09:47
So, the conanfile.py of an application would need to override the build type of each required package in case of its build_type being RelWithDebInfo, similar to what is described here?
https://github.com/conan-io/conan/issues/3228#issuecomment-405621786

I can see it working, however, this is then a major breaking change.

**Comment by lasote** [comment] 2019-06-19 12:12
No, it is not needed, you can install the dependencies for `Release` and build the application for `RelWithDebInfo` only scoping the setting: `conan create . user/channel -s OpenSSL:build_type=RelWithDebInfo`

**Comment by bfierz** [comment] 2019-06-19 12:22
I don't really see how this can be integrated into Cmake. Given your conan.cmake integration script how would this implementation change in cause of building the application with RelWithDebInfo but Release dependencies:

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
	message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
	file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake" "${CMAKE_BINARY_DIR}/conan.cmake")
endif()
include(${CMAKE_BINARY_DIR}/conan.cmake)
conan_cmake_run(
	REQUIRES
		ffmpeg/4.0.2@bincrafters/stable
		glew/2.1.0@bincrafters/stable
		glfw/3.2.1@bincrafters/stable
		imgui/1.63@bincrafters/stable
	BASIC_SETUP
	CMAKE_TARGETS
)

**Comment by lasote** [comment] 2019-06-19 12:31
So, you are using the `cmake_conan` project, that's a different story. I would need @memsharded help with that.

**Comment by Johnnyxy** [comment] 2019-06-19 12:37
To pass the settings with ```cmake_conan``` the following should do the trick:
```cmake
conan_cmake_run(
	REQUIRES
		ffmpeg/4.0.2@bincrafters/stable
		glew/2.1.0@bincrafters/stable
		glfw/3.2.1@bincrafters/stable
		imgui/1.63@bincrafters/stable
	SETTINGS
		ffmpeg:build_type=Release
		glew:build_type=Release
		glfw:build_type=Release
		imgui:build_type=Release
	BASIC_SETUP
	CMAKE_TARGETS
)
```

**Comment by bfierz** [comment] 2019-06-19 13:01
@Johnnyxy thank you for the hint. However, it will always take Release even for Debug builds (not only for RelWithDebInfo).
@lasote In this case, I probably need to defer to using the conanfile.py (cmake_conan should be able to do that) which allows doing checks upon install. That should work.

I'll try and see if I can formulate an issue over at https://github.com/conan-io/cmake-conan/issues and in the meantime try something like
```
if not self.build_type == "Debug":
  self.settings["Dependency"].build_type = "Release"
```

**Comment by Johnnyxy** [comment] 2019-06-19 13:18
Yes you are right, I did overlook this.
What you can do until maybe a fix is made for such a case: ```use a profile```

Create a [profile](https://docs.conan.io/en/latest/reference/profiles.html#profiles) file:
```yaml
include (default)

[settings]
ffmpeg:build_type=Release
glew:build_type=Release
glfw:build_type=Release
imgui:build_type=Release
```
```cmake
conan_cmake_run(
	REQUIRES
		ffmpeg/4.0.2@bincrafters/stable
		glew/2.1.0@bincrafters/stable
		glfw/3.2.1@bincrafters/stable
		imgui/1.63@bincrafters/stable
	RELWITHDEBINFO_PROFILE "FULLPATH_TO_YOUR_PROFILE"
	BASIC_SETUP
	CMAKE_TARGETS
)
```

**Comment by memsharded** [comment] 2019-06-20 06:13
I think that it might be possible something like this:

```cmake
if(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set(DEPS_TYPE Release)
else()
    set(DEPS_TYPE Debug)
endif()

conan_cmake_run(REQUIRES ...
                              BUILD_TYPE DEPS_TYPE)
```

As the ``conan_cmake_run()``, is called for installing dependencies, but is not defining the current build type for the current build, no need to define per-package settings.

I think with this approach, the users they have the power to decide. In the previous, buggy behavior, the users were forced always into the Release packages. There are users that actually want to have RelWithDebInfo dependencies too, and they were basically blocked. With this approach, the consumer freely decide: "Ey, I am RelWithDebInfo, but I want my dependencies to be in Release mode"

Please tell if the above helps. Thanks!

**Comment by bfierz** [comment] 2019-06-20 11:47
@memsharded I don't think this solution makes sense in a multi-configuration setup. The CMake build type is evaluated at configuration time, which is too early. In order to check against a certain configuration, generator expressions need to be used in multi-configuration environments, e.g. Visual Studio Generator.

**Comment by memsharded** [comment] 2019-06-20 19:13
@bfierz yes, that is true, for the cmake_multi case it won't work.

I have been investigating a few possibilities, and I think that the correct approach might not be in the build helpers and generators, but in the model. It might be possible (though it seems complex) to change the cmake generator, and with some cmake magic to allow to configure that behavior. But the problem is that users using the visual_studio generator will be broken. And the system should work the same if possible for all build systems.

So the whole idea behind this is basically that the binaries built for "Release" model are also compatible with the "RelWithDebInfo" mode, and some users might want to avoid building binaries for the later, and just reuse the ones for Release. This can be achieved adding to the package recipes something like:

```python
# in all packages
def package_id(self):
     if self.settings.build_type == "RelWithDebInfo":
           self.info.settings.build_type = "Release"
```

This will make it work for any configuration, system, and also if using single-config and multi-config approaches. 

I keep investigating other possibilities in the cmake_multi generator, but so far it looks extremely complicated.

**Comment by bfierz** [comment] 2019-06-21 09:14
@memsharded I was thinking a bit more about the issue and I am now really confused about having RelWithDebInfo as a build type. Conan packages so far would usually only have debug and release as settings. Something like debug information would be handled using options.

It seems like supporting RelWidhDebInfo as a build_type makes things a lot more complicated.

**Comment by Johnnyxy** [comment] 2019-06-21 09:30
@bfierz 
RelWithDebInfo is a quite useful build_type. For example if I want to have debug informations of my Software but have to run it on a standard e.g. Windows installation where no debug informations are available for the C runtime, etc.

With RelWithDebInfo build type I can specify all relevant settings/options for compilers etc. to include debug informations for my software but link it against ```release C runtime``` to able to let it run on a standard os installation.

E.g. on Windows the runtime binaries (dll,lib) with debug informations and symbol files (pdb) are not allowed to be redistributed. The standard Windows installation does not provide a C runtime with debug informations. Thus you cannot run a normal debug build on a Windows where not e.g. Visual Studio is installed or the debug informations are availabe by other means.

**Comment by acgetchell** [comment] 2019-06-21 13:47
+1 on usefulness of RelWithDebInfo.

**Comment by k0zmo** [comment] 2019-06-24 17:50
Also, the default configuration Microsoft calls Release in Visual Studio is really a RelWithDebInfo in case of CMake - in both MSVC's Debug and Release you get debug symbols. CMake's Release build type is somehow useless if your application crashes and you are left with no debug information to diagnose the problem.

**Comment by bfierz** [comment] 2019-06-24 18:06
@k0zmo, you are making a good point.
Assuming your application wants to have different build types other than the defaults in CMake. If there is no way to remap the build types it will try an build all the dependencies using the new build_type.

**Comment by Johnnyxy** [comment] 2019-06-24 21:08
@k0zmo 
What the heck is this cr*p? Release == RelWithDebInfo?

I never used this CMake feature of Visual Studio because it hides a good portion of stuff that happens behind the scenes. A collegue uses this and when he has any problems while compiling, the log does not show any actual compiler commands which are used, etc. So to diagnose a problem while compiling this is problematic.
Maybe there is a switch that VS prints them out, but at the moment I this is just a ```quick-and-dirty```-feature.

The build types
---------------
Normally the build types of Visual Studio are similar to Conan's profiles. Just settings the IDE composes to an actual compiler invocation. 
The ```Release``` build type consists of linking against release runtime, using optimizations and omitting any debug informations.
The ```Debug``` build type links against debug runtime, no optimizations and with debug informations.
The ```RelWithDebInfo``` build type is a mix of ```Release``` and ```Debug```, link against release runtime, no optimizations and with debug informations.
One can freely modify this in the project settings, e.g. add debug informations or change the optimizations of the ```Release``` build type. But if what you have shown is a default of Visual Studio's CMake "configuration" then this would justify a big slap to the MS guy who came up with this.

**Comment by k0zmo** [comment] 2019-06-24 21:43
It's the reality. Since the dawn of ages in both VS's Debug and Release configurations/build types you get debug symbols. Don't need to take my words for granted - just create new project and check `C/C++/General/Debug Information Format` and `Linker/Debugging/Generate Debug Info settings`. You also get LTCG/LTO in Release build by default (which you don't with CMake's defaults) but that's a different topic.

CMake's `RelWithDebInfo` is not a mix of CMake's `Release` and `Debug`. It's optimized build (`-O2` in GCC or `/O2` in MSVC) with additional debug symbols generated. These options are orthogonal to each others. FWIW I think that what's currently in VS is sane and perfectly fine. I really don't need a build with no way to diagnose why it crashed or behaved that way. Thus `Release` build type in CMake is useless for me and I never use it for my own builds.

Regarding the Visual Studio's CMake integration - I have exactly the same feelings. It's hard to diagnose the problems when they show up. It's way better to simply generate vcxproj.

**Comment by Johnnyxy** [comment] 2019-06-24 22:16
Yes I was wrong, in the past I did modify the optimizations away and did full debug builds for my ```RelWithDebInfo```. That was the reason for my false assumption. :)

**Comment by bfierz** [comment] 2019-12-12 14:55
I finally got around thinking more about it. The point is not whether RelWithDebInfo is useful or not, but rather what is the expected behavior.
Most recipes out in the wild will distinguish only between debug and non-debug. So adding more release types will not add any value to the generated artifacts. Any further configuration happens through options, rather than settings.

In case of setting up a cmake project using conan to manage the dependencies will contain somewhere a call to conan install. With the cmake generator this is not an issue and it will map whatever build-type you request to the build-type you are currently building. The user controls the mapping. If I wanted to use conan build-type Debug with cmake RelWithDebInfo, I would be free to do so.

In the multi generator world, this is different. The user loses control over the mapping and is required to use the mapping provided by the generator. Basically, we need a way to configure this mapping when choosing the generator. Ideally, the multi-generator wouldn't anything about build types, but would create any mapping that the user requires. This would also remove the implied dependency on the predefined cmake configuration types. Writing a cmake script to explicitly use these configuration names just makes it harder to extend.

So going back to the original behavior is also not the ideal solution. A much better solution would be a more customizable cmake_multi generator. Is it possible to pass arguments to the generator through the commandline? If so, we could generate the set of possible mappings.

**Comment by memsharded** [comment] 2019-12-12 14:59
This can be related to https://github.com/conan-io/conan/issues/6219? 

cc / @jgsogo

**Comment by memsharded** [comment] 2019-12-12 15:00
> So going back to the original behavior is also not the ideal solution. A much better solution would be a more customizable cmake_multi generator. Is it possible to pass arguments to the generator through the commandline? If so, we could generate the set of possible mappings.

Not yet, but this has been considered in the past (we even had a PR implementing it). cc/ @lasote

**Comment by sztomi** [comment] 2019-12-12 15:37
Yes please, parameters for generators would be welcome. The one aspect I don't see mentioned here is that in this case, conan makes assumptions about the settings one uses; and even though there is a default set of settings, it's also possible to customize them, so it should at least be possible to opt in to a different "conan build_type -> CMAKE_BUILD_TYPE" mapping. For example, to customize it:

```
$ conan install . -g cmake_multi -s build_type=Release -p CMAKE_BUILD_TYPE=RelWithDebInfo
```

(hopefully that example is clear in the intention)^

**Comment by jgsogo** [comment] 2019-12-12 15:48
Going down the road of this kind of mappings, CMake provides a built-in feature: https://cmake.org/cmake/help/latest/prop_tgt/MAP_IMPORTED_CONFIG_CONFIG.html

**Comment by bfierz** [comment] 2020-01-08 10:52
@memsharded

In our setup, we are packaging multiple build_types into a single package on windows. This means that the package_info call for quite some packages looks like this:
```python
def package_info(self):
    if self.settings.os == "Windows":
        self.cpp_info.release.libs = ['imgui']
        self.cpp_info.debug.libs = ['imguid']
    else:
        self.cpp_info.libs = ['imgui']
```

When using the CMake generator (single and multi), it will not find the libraries when trying to build with RelWithDebInfo.

I realize that this setup is not ideal, however, the change of how the build types are forwarded broke a lot of recipes for us. I am not sure how often this type of packaging is used, but if so, it makes it even harder to support arbitrary build types.

**Comment by bfierz** [comment] 2020-01-10 21:47
@jgsogo, thank you for the quick-note about imported configs. I sketched a small function, which recursively runs through a list of conan package targets and remaps all the configurations.

```
function(remap_target TGT)
	set_target_properties(${TGT}
		PROPERTIES
			MAP_IMPORTED_CONFIG_MINSIZEREL Release
			MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
	)

	get_target_property(CONAN_IMPORT_TARGETS ${TGT} INTERFACE_LINK_LIBRARIES)
	list(FILTER CONAN_IMPORT_TARGETS INCLUDE REGEX CONAN_PKG::.+)

	foreach(IMPORTED_TARGET ${CONAN_IMPORT_TARGETS})
		remap_target(${IMPORTED_TARGET})
	endforeach()
endfunction()
```

It works at least in simple Visual Studio setups and allows to post-process the generated conan cmake integration.

**Comment by pepsiman** [comment] 2020-04-09 12:18
```
foreach(TGT ${CONAN_TARGETS})
   set_target_properties(${TGT}
               PROPERTIES
                       MAP_IMPORTED_CONFIG_MINSIZEREL Release
                       MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release
       )
endforeach()
```

**Comment by memsharded** [comment] 2023-03-18 22:52
``cmake_multi`` deprecated in 1.X in favor of CMakeDeps, removed in 2.0, closing as outdated.

**Closed by memsharded** 2023-03-18 22:52 UTC
Labels: stage: triaging
