### ISSUE TITLE
[bug] <imgui> missing dependency from conan repo of <allegro5>

### ISSUE THREAD

**Issue by SamuelMarks** [conan-io/conan#8763] opened 2021-04-06 07:49 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 11.1 (20C69)
  * Compiler+version: Apple clang version 12.0.0 (clang-1200.0.32.29)
  * Conan version: 1.35.0
  * Python version: 3.9.2

Searched with `conan search --remote='conan-center' 'allegro*'`… so I guess it could be in another remote?

#### `conanfile.txt`
```ini
[requires]
imgui/1.82

[generators]
cmake
```

#### `CMakeLists.txt `
```cmake
cmake_minimum_required(VERSION 3.2)
project(pp VERSION 0.0.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 14)
set(src src/main.cpp)

include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()

add_executable(${PROJECT_NAME} ${src})
target_include_directories(${PROJECT_NAME} PRIVATE ${CONAN_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${CONAN_LIBS})
```

#### `src/main.cpp`
https://raw.githubusercontent.com/ocornut/imgui/6a161b8/examples/example_allegro5/main.cpp
(rename `#include "allegro5/allegro.h"` to `#include <allegro5/allegro.h>`)

### Logs (Executed commands with output) (Include/Attach if Applicable)

```sh
$ mkdir build && conan install ..
$ cmake ..
$ cmake --build .
[ 50%] Building CXX object CMakeFiles/pp.dir/src/main.cpp.o
/tmp/imgui4/src/main.cpp:6:10: fatal error: 'allegro5/allegro.h' file not found
#include <allegro5/allegro.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/pp.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/pp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by czoido** [comment] 2021-04-06 08:51
Hi @SamuelMarks,
This is not a bug, what is happening is that you don't have allegro requirement in your _conanfile_. To this date there's no recipe for the allegro library in conan center (besides the command line search with conan you can search available libraries in [conan.io/center](https://conan.io/center/)).
We have a list of some libraries that would be nice to add to Conan here: https://github.com/conan-io/conan-center-index/issues/621 and allegro is between them. We are adding new libraries everyday (to this day we have more than 817 different libraries). Also, you could try to [contribute the recipe in conan-center-index ](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md). There's an amazing community of people contributing recipes and willing to help others trying to add new libraries for Conan.

**Comment by SamuelMarks** [comment] 2021-04-06 08:52
Yeah I was afraid that's the case

Will see what I can do in the future RE contributing it

**Comment by czoido** [comment] 2021-04-06 09:05
> 
> Will see what I can do in the future RE contributing it

That would be great, if you want to contribute you can request access to the EAP here: https://github.com/conan-io/conan-center-index/issues/4 and also note that you can also open an issue in conan-center-index to request for the library: https://github.com/conan-io/conan-center-index/issues/new/choose

**Comment by czoido** [comment] 2021-04-07 08:51
I'm closing the issue as it seems solved. Please feel free to reopen or open another issue if you have further questions.

**Closed as completed by czoido** 2021-04-07 08:51 UTC
Labels: type: question

**Comment by SamuelMarks** [comment] 2021-04-10 09:45
Same error with [nuklear](https://github.com/Immediate-Mode-UI/Nuklear) with https://conan.io/center/nuklear:

### `CMakeLists.txt`
```cmake
cmake_minimum_required(VERSION 3.0)
cmake_policy(SET CMP0048 NEW)
project(pp VERSION 0.0.0 LANGUAGES C)

set(src src/main.c)

if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake"
                  "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(REQUIRES Catch2/2.6.0@catchorg/stable
                BASIC_SETUP)
conan_cmake_run(REQUIRES nuklear/4.06.1
                BASIC_SETUP)

add_executable(${PROJECT_NAME} ${src})
target_include_directories(${PROJECT_NAME} PRIVATE ${CONAN_LIBS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${CONAN_LIBS})

```

### `sh`
```sh
$ cmake -DCMAKE_BUILD_TYPE=Debug ..
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=apple-clang;-s;compiler.version=12.0
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.35.0

-- Conan executing: /usr/local/bin/conan install . -s build_type=Debug -s compiler=apple-clang -s compiler.version=12.0 -g=cmake
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

Catch2/2.6.0@catchorg/stable: Not found in local cache, looking in remotes...
Catch2/2.6.0@catchorg/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
Catch2/2.6.0@catchorg/stable: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    Catch2/2.6.0@catchorg/stable from 'conan-center' - Downloaded
Packages
    Catch2/2.6.0@catchorg/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download

Installing (downloading, building) binaries...
Catch2/2.6.0@catchorg/stable: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
Catch2/2.6.0@catchorg/stable: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Catch2/2.6.0@catchorg/stable: Downloaded package revision 0
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- This project seems to be plain C, using 'AppleClang' compiler
-- Current conanbuildinfo.cmake directory: /tmp/nuklear1/build
-- Conan: Automatic detection of conan settings from cmake
-- Conan: Settings= -s;build_type=Debug;-s;compiler=apple-clang;-s;compiler.version=12.0
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
-- Conan: Version found Conan version 1.35.0

-- Conan executing: /usr/local/bin/conan install . -s build_type=Debug -s compiler=apple-clang -s compiler.version=12.0 -g=cmake
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    nuklear/4.06.1 from 'conan-center' - Cache
Packages
    nuklear/4.06.1:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
nuklear/4.06.1: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- This project seems to be plain C, using 'AppleClang' compiler
-- Current conanbuildinfo.cmake directory: /tmp/nuklear1/build
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/nuklear1/build
/tmp/nuklear1/build $ cmake --build .
[ 50%] Building C object CMakeFiles/pp.dir/src/main.c.o
/tmp/nuklear1/src/main.c:3:10: fatal error: 'allegro.h' file not found
#include <allegro.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/pp.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/pp.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ericLemanissier** [comment] 2021-04-15 12:20
@SamuelMarks there does not seem to be a conan package for allegro, so you can probably request it on https://github.com/conan-io/conan-center-index/issues

This should not prevent using imgui nor nuklear, because allegro is not needed for these packages
