### ISSUE TITLE
[bug] Package revision on remote never seems to match local export.

### ISSUE THREAD

**Issue by joessu** [conan-io/conan#5933] opened 2019-10-17 21:00 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: ubuntu 16.04
  * Compiler+version: N/A
  * Conan version: 1.19.2
  * Python version: 3.5.2 

### Steps to reproduce (Include if Applicable)
upload a package revision to a remote

Machine 1 -----
conan export sub-folder user/channel
conan install --build missing recipe-that-depends-on-sub-folder
(subfolder-package) gets built
conan upload "*" --all
conan search package --revisions -r remote
sha-result-1 (13:47 ...)

Machine 2 -----
do an export of the same recipe and sources, check the revision
conan export sub-folder user/channel
conan install conan install --build missing recipe-that-depends-on-sub-folder
(package gets build because sha doesnt match)
conan search package --revisions
sha-result-2

for me the shas are different

I noticed in a package conan manifest and a export conan manifest the contents are different even though the files are the same. The export manifest has export_source prepended to every path, where the package manifest does not.

I don't know how the internals of revision shas work, but if the manifest is provided as any input, this could be an issue.

EDIT: The sha during export is different than the sha after it is created, this could be the issue, and maybe i am using this incorrectly, but i was expecting to be able to export the same contents and be able to generate a similar sha that was uploaded already by a different machine.

test/1.1.1@yoda/stable: A new conanfile.py version was exported
test/1.1.1@yoda/stable: Folder: /root/.conan/data/test/1.1.1/yoda/stable/export
test/1.1.1@yoda/stable: Using the exported files summary hash as the recipe revision: 49271fa4ca17130d436585c1a6697617 
test/1.1.1@yoda/stable: Exported revision: 49271fa4ca17130d436585c1a6697617

...
test/1.1.1@yoda/stable: Package '25d9f92c21940167f7866667cec3453054ed62ff' created
test/1.1.1@yoda/stable: Created package revision 9ab6718d3022a29bcea0e1846360c0f6

**Comment by memsharded** [comment] 2019-10-17 22:28
Just to be clear, is the recipe revision which is different? Then, only the ``export`` is necessary to reproduce, the rest is unnecessary.

The fact that the package revision is different after building, is normal, because in C++ the builds are not reproducible by default (https://blog.conan.io/2019/09/02/Deterministic-builds-with-C-C++.html)

Could you please clarify that the export, the recipe revision is indeed different? The most common cause for this is a different CRLF in the git checkout.

**Comment by joessu** [comment] 2019-10-18 15:23
So we use a docker and a CI machine to build our packages and they have an md5 sum that is generated every build from Artifactory that is then used by a later project and consumed. So i can guarantee that our builds are indeed deterministic. Also, I am less concerned with Recipe Revisions and Package Revisions (i understand i did confuse them above), and more concerned with build=missing always building the package even when the CI has uploaded packages, which seemingly have the same contents, to the server. On the same machine the sha is always the same.

I will double check the docker and see if maybe the timestamps are wrong or something.

**Comment by joessu** [comment] 2019-10-18 16:26
So we build with linux Docker (linux, qnx, android), and mac and windows. Mac finishes first, so the sha on the remote matches the sha i can generate with mac. the shas from conan packages on the other platforms don't match mac, thus never match the remote. Even when the exported recipe revision matches a remote revision on mac, it STILL builds the local package after an export. I would expect mac to compare its exported recipe revision, see the matched one on the remote, and then pull. Is this correct?

**Comment by AlexandrePTJ** [comment] 2020-04-28 07:39
Hi, I do have the same problem, did you find a solution ?

**Comment by memsharded** [comment] 2023-12-30 23:31
>  It does appear to be working correctly when keep source is not in the log.

``--keep-source`` has been removed in 2.0, closing this ticket as outdated

**Closed by memsharded** 2023-12-30 23:31 UTC
Labels: stage: triaging
