### ISSUE TITLE
[UX] Get rid of traceback output on `authenticate` error

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#5262] opened 2019-05-30 21:42 UTC
To help us debug your issue please explain:
Conan Version: 1.15.1

Hi!

Since last weekend I've updated some packages to support Clang 8 and MSVC 16, when requested by any user. However, OpenSSL is failing when trying to upload MSVC 16:

These logs are from today:

https://ci.appveyor.com/project/ConanCIintegration/conan-openssl/builds/24895637/job/x7697tjf26k60kbd#L5356
https://ci.appveyor.com/project/ConanCIintegration/conan-openssl/builds/24895637/job/nvq8ey2e4rtglqfq#L7449

And there are more from last weekend.

Or Bintray is unstable now, or something is not working when multiple packages are being uploaded at same time. Could we avoid this error using some retry mechanism?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment] 2019-05-31 09:17
Hi! `conan upload...` already have retry arguments, maybe you should consider using them in conan-package-tools... about the bintray issue, I will tag it, but usually those are temporary problems very hard to trace, reproduce and solve 😞

**Comment by uilianries** [comment] 2019-05-31 19:03
Following the stack trace, actually the error occurs before uploading, when authenticating ... 

CPT by default tries to upload 3x, but there is no mechanism preventing login retry on API. So I see two options:

- Wrapping authenticate step in CPT with try except, retrying when necessary
- Add retry parameter to conan_api.authenticate

**Comment by jgsogo** [comment] 2019-06-03 10:04
You are right, @uilianries, it is about the `conan_api.authenticate` function. I also agree with the PR, I think the retry should go in CPT, there is no need for an additional argument in Conan CLI to retry this operation.

Anyway, I'll keep this open and labeled as bug because we need to get rid of the nasty traceback and output a meaningful error to the user.

**Comment by lasote** [comment] 2019-09-30 13:02
Is this still a real issue? I cannot checks the linked appveyor to see the stacktrace generated. @jgsogo could you provide more info to reproduce/fix?

**Comment by jgsogo** [comment] 2019-09-30 17:17
Now I get a meaninful error:


```
Remote 'jgsogo' username: jgsogo
Please enter a password for "jgsogo" account: 
ERROR: Wrong user or password
Remote 'jgsogo' username: jgsogo
Please enter a password for "jgsogo" account: 
ERROR: Wrong user or password
Remote 'jgsogo' username: jgsgo
Please enter a password for "jgsgo" account: 
ERROR: Wrong user or password
ERROR: Too many failed login attempts, bye!. [Remote: jgsogo]
```

We might have already fixed it, I'll close the issue while there is no evidence.

**Closed by jgsogo** 2019-09-30 17:17 UTC
Labels: complex: low, good first issue, priority: medium, stage: queue, type: bug, type: ux
