### ISSUE TITLE
"Manually-specified variables were not used by the project" using the cmake_find_package generator

### ISSUE THREAD

**Issue by kkaja123** [conan-io/conan#5816] opened 2019-09-25 20:45 UTC
When using the `cmake_find_package` generator, CMake returns the following warning:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
    CONAN_COMPILER
    CONAN_COMPILER_VERSION
    CONAN_CXX_FLAGS
    CONAN_C_FLAGS
    CONAN_EXPORTED
    CONAN_IN_LOCAL_CACHE
    CONAN_LIBCXX
    CONAN_SHARED_LINKER_FLAGS
```
In my conanfile.py, I've enabled the generators `"cmake_find_package", "compiler_args", "json"`.

In the build step:
```
cmake = CMake(self)
# Set some project-specific CMake variable definitions
cmake.configure()
cmake.build
```
This is the standard CMake usage as seen at [conan docs - cmake_find_package](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html#in-a-conanfile-py).

If I add the "cmake" generator (even though I don't need it), it solves some of the unused variables, but not all of them.

The changes to my `CMakeLists.txt` are the following:
```
include("${CMAKE_BINARY_DIR}/conanbuildinfo.cmake")
# conan_basic_setup(NO_OUTPUT_DIRS) I would prefer NO_OUTPUT_DIRS, but I wanted to prove that the standard implementation still results in the warnings
conan_basic_setup()
```
The following CMake warning is reported:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR
```

These variables are set in `conans/client/build/cmake_flags.py`, yet I don't know where they would be used.

Obviously, Conan should be avoiding generating CMake warnings. There are two problems. One is that the `cmake_find_package` generator causes these warnings and most cannot be eliminated without including the `cmake` generator. The second problem is that even the `cmake` generator and implementation does not resolve *all* of the warnings.

OS: Windows 10
Conan version: 1.18.5
CMake version: 3.14.1

**Comment by memsharded** [comment] 2019-09-25 21:17
Hi @kkaja123 

please note that in the docs, loading ``conanbuildinfo.cmake`` and doing ``conan_basic_setup()`` is not done. It is not really necessary if the ``cmake_find_package`` generator is being used (though some functionality, like the compiler checks is lost). I'd also recommend to have a look to the ``cmake_find_package_multi`` generator, it is a bit more powerful.

We are aware of those warnings, and currently working on it, trying to implement an improved integration with cmake via toolchains (https://github.com/conan-io/conan/issues/5737). With it, this would be fixed, please follow the progress there (it will take some time, it is more complex than it seems at first sight). Thanks!

**Comment by kkaja123** [comment] 2019-09-25 21:32
@memsharded 

Thank you very much for the information. Best of luck with the toolchain implementation.

I am a bit confused about your comment regarding the docs for `cmake_find_package`. As far as I can tell, the docs don't load `conanbuildinfo.cmake` and execute `conan_basic_setup()` because `cmake_find_package` **does not generate** `conanbuildinfo.cmake`. That's why it is perplexing that `cmake_find_package` causes all of those variables to become unused but the generator doesn't have anything that *would* use those variables (like the `cmake` generator does for the `CONAN_...` variables).

Anyways, I'll be patiently waiting for the improved integration with CMake. 😄

**Comment by memsharded** [comment] 2019-09-25 22:14
It is not the generator, those variables are injected by the ``CMake`` build helper in the command line invocation in the ``build()`` method. Such helper does not differentiate among generators, and it passes all the information it has from itself and the environment as command line arguments. The problem is that there is nothing in the CMakeLists.txt that uses them, and thus the warning. 
The idea is that such CMake helper will no longer be that "active", and will be much simpler, passing most of its functionality to toolchain files. Thanks for the feedback!

**Comment by memsharded** [comment] 2023-03-15 22:59
``cmake_find_package`` generator deprecated in 1.X, removed in 2.0, closing this issue as outdated

**Closed by memsharded** 2023-03-15 22:59 UTC
Labels: priority: low, stage: queue, complex: high, component: Build
