### ISSUE TITLE
System Package manager should not update package index if CONAN_SYSREQUIRES_MODE=verify

### ISSUE THREAD

**Issue by kutschkem** [conan-io/conan#3142] opened 2018-06-29 15:47 UTC
Currently the SystemPackageManager.update() performs an update (which needs sudo rights!) if CONAN_SYSREQUIRES_MODE is anything else than "disabled". "verify" should also not update, I think.

**Comment by memsharded** [comment] 2018-06-29 15:48
This might be a duplicate, and fixed in conan 1.5. Have you already updated? Thanks!

**Comment by memsharded** [comment] 2018-06-29 15:49
Duplicate of https://github.com/conan-io/conan/issues/3047, fixed in conan 1.5

**Comment by kutschkem** [comment] 2018-06-29 15:53
I am literally looking at the code in develop branch. The [last commit](https://github.com/conan-io/conan/commit/41331c7dae6b2b34b8f0edf98b4507c1b24e930a) which changed the file disabled update() for CONAN_SYSREQUIRES_MODE="disabled", but not for "verify". Please reopen.

**Comment by memsharded** [comment] 2018-06-29 16:12
But for verification the update is implicit, isn't it? Users using the "verify" mode need to update first in order to correctly run such verification.

**Comment by kutschkem** [comment] 2018-07-02 14:54
Hmm the verification checks that packages are locally installed. I think update updates the indexes of remote package sources. If that is correct they are unrelated.

**Comment by memsharded** [comment] 2018-07-02 16:59
Yes, you are right, sorry I misunderstood. This should be fixed, thanks for reporting!

**Closed** 2018-07-06 10:29 UTC
Labels: bug, in review
