### ISSUE TITLE
[bug] requirements() executed after configure() in v1.28

### ISSUE THREAD

**Issue by helmesjo** [conan-io/conan#7501] opened 2020-08-05 11:40 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.28
  * Python version: 3.3.7

### Steps to reproduce (Include if Applicable)
conanfile.py with:
```
# ...
    def requirements(self):
        print("1")
    def configure(self):
        print("2")
# ...
```

**Expected output:**
```
1
2
```

**Actual output:**
```
2
1
```

This worked correctly before version 1.28. Now it's no longer possible to change options for dynamically added dependencies.

## NOTE
It works correctly if I instead use `configure_options()` (then the order is correct). Did I misuse `configure()` before, or was this change unintentional?

**Comment by memsharded** [comment] 2020-08-05 11:48
Hi @helmesjo 

This is not a bug, this is expected and documented behavior. Check for example: https://docs.conan.io/en/latest/reference/commands/consumer/install.html, there it explains the evaluation order explicitly.

It doesn't matter in which order they are declared in the recipe, the evaluation order is always the same, and first the ``configure()`` is called, then the ``requirements()``. It has been this way since the very beginning, I don't think this has changed.

**Comment by helmesjo** [comment] 2020-08-05 12:03
Yeah declaration order obviously doesn't affect it, but pretty sure it changed for 1.28 because one of my recipes just started failing after updating. 
But ok, then I'll just fix my recipe. 
Thanks! 🙂

**Comment by memsharded** [comment] 2020-08-05 12:11
Please let us know about the failure, and what has changed. I am quite sure the evaluation order didn't change in a long time, so the failure might be something else. If you have something that can be reproduced more thoroughly we could have a look. Thanks!

**Comment by helmesjo** [comment] 2020-08-06 07:56
@memsharded 
The issue mentioned here was solved by just following the documentation that you provided (using `configure_options()` instead of `configure()`).

Though I'm seeing something else that appears to be a new issue with my builds, [related to rpaths](https://travis-ci.org/github/helmesjo/conan-magnum/jobs/715326618#L1946-L1950). Since it's indirectly caused by a dependency, I'm not sure if it's related to conan per se ([magnum](https://github.com/helmesjo/conan-magnum) depends on [corrade](https://github.com/conan-io/conan-center-index/blob/master/recipes/corrade/all/conanfile.py), but I'm not sure if corrade has changed). But maybe you've seen similar before and can give a hint? If not I'll probably just create another issue and close this. 

Thanks!

**Comment by memsharded** [comment] 2020-08-06 08:10
Yeah, this seems unrelated, better close this issue and open a new one.

What I have been checking is that you are using the Conan default libstdc++, sometimes if some package (corrade?) is not following the inputs and forcing or hardcoding something in the build scripts, the resulting binary would be linked against libstdc++11, and then the linker might discard it, or something like that. But no clear idea at the moment, so better investigate it in its own issue. Thanks!

**Closed as completed** 2020-08-06 08:32 UTC
Labels: type: question
