### ISSUE TITLE
[bug] with multiple remotes, sometimes Conan uses the wrong one

### ISSUE THREAD

**Issue by Lizabeth-Roberts-Bose** [conan-io/conan#6668] opened 2020-03-12 12:39 UTC
This one is short and sweet and I hope easy to reproduce. Basically, if you have two remotes set up but you, and you are logged in to both via `conan user`, but you only have permissions to view packages on one remote, it will use the wrong remote. 

If I have two remotes set up, `remote1` and `remote2`
If you do something like `conan blah -r remote1` but you don't have correct access permissions on remote1, Conan seems to be falling back and using remote2. This behaviour would be fine if I did not specify to use a a remote but since I passed `-r` is it intended behaviour to use a different remote? 

What's actually worse about this bug is that in the log output, it shows as downloading stuff from the correct remote but that's is definitely not where it's getting stuff from in my testing. 

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 16
  * Conan version: 1.20.5
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)
1. Set up two remotes
2. Log in and autheticate to BOTH but ensure that one remote does not have the correct permissions to view packages. Also ensure that the same package name exists in both, but that they are actually different packages. 
3. Try running `conan install -r remote1` where the remote is the one without correct access permissions
4. Proffit

**Comment by memsharded** [comment] 2020-03-12 17:13
Are you using revisions enabled?

**Comment by Daniel-Roberts-Bose** [comment] 2020-03-12 17:19
> Are you using revisions enabled?

Yes

**Comment by czoido** [comment] 2020-03-13 08:28
Hi @Daniel-Roberts-Bose,
Thanks a lot for reporting and for the detailed instructions on how to reproduce it. 

- When you are running the `conan install` do you have the package you are installing already installed in the local cache?
- In that case, what happens if you remove the packages in the local cache and try installing again from `remote1`?
- Could you please share the output when doing `conan install -r remote1`?

**Comment by Daniel-Roberts-Bose** [comment] 2020-03-13 16:20
Let me answer each question on its own:

>When you are running the conan install do you have the package you are installing already 
> installed in the local cache?
The package is no in local cache before the install

> Could you please share the output when doing conan install -r remote1?
I cant share all the output verbatim because it contains some confidential stuff, and the output is probably 1000 lines long so is there a specific bit of output you are looking for?

I think I should add some additional clarifications however.
1. I am using version ranges to install the package `self.requires("zlib/[>=0.0.1]@blah/blah")`
2. The actual package that seems to be failing to resolve is not the package at the top level. We have a lot of nested requirements such as PkgA requires PkgB that requires PkgC that requires PkgD and so on... It appears to be failing on some of the intermediate packages and not the top level one

The output you listed above is also not what I am seeing. I am instead seeing something along the lines of success logs, but its downloaded the wrong package from the wrong remote. To give a more concrete example I am basically seeing this:

PkgA version 1.2.3 exists in remote 1
PkgA version 1.2.5 exists in remote 2

I have logged into both remotes, but dont have permissions on remote 2 so I cant actually access PkgA version 1.2.5. I run `conan install -r remote2` and it outputs logs something like this:
```
➜ conan install conanfile.py -r remote2

Installing package: zlib/1.2.3
Requirements
    zlib/1.2.3 from 'remote2' - Download
Packages
    zlib/1.2.3:xyz123 - Download
```
__NOTE__
This isnt exact output from my logs, I simply threw some example logs together similar to what I am seeing :)

**Comment by memsharded** [comment] 2024-12-29 23:49
Conan 2 completely changed how remotes are managed and dependencies are resolved in them, so closing this ticket as outdated (most likely solved by Conan 2).
Please re-open or create a new ticket if necessary, thanks for your feedback.

**Closed by memsharded** 2024-12-29 23:49 UTC
Labels: stage: triaging
