### ISSUE TITLE
[question] Version Range produce unexpected results; incompatible pre-release (falsely) considered

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan#10146] opened 2021-12-08 12:55 UTC
In order to have an easier time managing package versions in my application, I decided to introduce the version ranges for my package requirements. But as it turns out, I somehow struggle to find the correct version range expression that satisfies my needs.

## Example
My application consists of one library `consumerA` that does depend only on one library `component`.
Over time, the developers of `component` have released a few versions until now:
```
* 1.1.2
* 1.2.0-alpha
* 1.2.0
* 1.3.0-alpha (later discontinued, since breaking changes had to be made to allow this feature)
* 2.0.0-alpha
* 2.0.0
```

Back then when I started with the development of `consumerA`, the version of `component` I coded against was `1.1.2`.
Since then, I did not actively follow the changes going on in `component`, meaning the `1.1.2` is the only version I know that exists.
Features introduced in `>1.2` are not relevant to my code, though they may be relevant for other libraries (e.g. `consumerB` depends on `1.3.0-alpha`).

Now as the author of `consumerA` I would like to depend on a version of `component` that is "at least compatible with `1.1.2`".
According to [semantic versioning](https://semver.org/) and this [cheat sheet](https://devhints.io/semver), a neat expression I could use is `^1.1.2` which corresponds to `>=1.1.2 <2.0.0`.

## Expectation

I now have two expectations:
1. without pre-releases, the version should resolve to `1.2.0` --> **works**
2. with pre-releases, the version should resolve to `1.3.0-alpha` --> **resolves to `2.0.0-alpha`?!?!?**

Am I missing a very crucial part of information, that a major breaking pre-release is actually considered non-breaking (like `1.999999.99999`)?
If so, how could I limit the range to a version sure less than major `2` without knowing the exact latest `1.x` version?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-12-08 22:20
Hi @dornbirndevelops 

yes, this could be a bug in the third party library that we are using for version ranges. Can you clarify what exact expression you are using? ``[^1.1.2, prereleases=True]``?

We have changed the lib already in 2.0, and we are embedding the computation of version ranges, I am going to check there we are doing the right thing.

**Comment by memsharded** [comment] 2021-12-08 23:33
Indeed a tricky one, I have submitted a PR for 2.0 in https://github.com/conan-io/conan/pull/10149.

The issue is that a pre-releases is semantically lower than the upper bound of a caret version:

``^1.1.2`` => ``>=1.1.2 && <2.0.0``, but ``2.0.0-alpha1`` is lower than ``2.0.0``.

My proposal is to change the upper bound of a caret to ``2.0.0-``.

**Comment by memsharded** [comment] 2021-12-08 23:46
Unfortunately, for 1.X.

```python
        result = satisfying(["2.0.0-pre"], "^1.1.2, include_prerelease=True", output)
        self.assertEqual(result, "2.0.0-pre")
```
This cannot be solved in 1.X, because the code is in node-semver.
You might however do the following expression to explicitly discard 2.0.0- prereleases

```python
result = satisfying(["2.0.0-pre"], "^1.1.2 <2.0.0-, include_prerelease=True", output)
        self.assertIsNone(result, "2.0.0-pre")
```

That, is ``requires = "pkg/[^1.1.2 <2.0.0-, include_prerelease=True]@user/channel"``

**Comment by dornbirndevelops** [comment] 2021-12-09 06:33
> yes, this could be a bug in the third party library that we are using for version ranges. Can you clarify what exact expression you are using? `[^1.1.2, prereleases=True]`?

I saw in the documentation, that conan uses this `semver` package for it, which is why I wrote a small test to figure out the expression that fits my needs.

```python
from semver import max_satisfying

def determine_version(versions, expression, loose, include_prerelease):
    version=max_satisfying(versions, expression, loose, include_prerelease)
    print(f'{expression = }, {loose = }, {include_prerelease = } --> {version = }')

def test_determination(versions, expression, loose):
    determine_version(versions, expression, loose, False)
    determine_version(versions, expression, loose, True)

versions = ['1.1.2','1.2.0-alpha','1.2.0','1.3.0-alpha','2.0.0-alpha','2.0.0']

# (consumer) developer intention
# min required version: '1.1.2' (client uses major api 1 + features from 1.1) --> 1.1.2 is known to the consumer
# expected (desired) outocme wo. prerelease: '1.2.0'
# expected (desired) outcome w. prerelease: '1.3.0-alpha'

loose = False

for expression in [
'~1.1.2', # is >=1.1.2 <1.2.0
'^1.1.2', # is >=1.1.2 <2.0.0
]:
    test_determination(versions, expression, loose)
    print('')
```

The conan version range equivalent including prereleases would be:
`^1.1.2, include_prerelease=True`

**Comment by dornbirndevelops** [comment] 2021-12-09 06:39
> Indeed a tricky one, I have submitted a PR for 2.0 in #10149.
> 
> The issue is that a pre-releases is semantically lower than the upper bound of a caret version:
> 
> `^1.1.2` => `>=1.1.2 && <2.0.0`, but `2.0.0-alpha1` is lower than `2.0.0`.
> 
> My proposal is to change the upper bound of a caret to `2.0.0-`.

yes, that would make sense.

**Comment by dornbirndevelops** [comment] 2021-12-09 06:49
For 1.X, I will substitute `^1.1.2` with `>=1.1.2 <2.0.0-`
and `~1.1.2` with `>=1.1.2 <1.2.0-` respectively.

@memsharded as a small addition to your proposal:
the upper bound generally seems to be a bit broken for the `~` as well. (see test output below)
```
expression = '~1.1.2', loose = False, include_prerelease = True --> version = '1.2.0-alpha'
```

**Comment by memsharded** [comment] 2021-12-09 12:34
You mean in Conan 1.X, right @dornbirndevelops ?

Because I have added a test for 2.0 here, to make sure tilde is also covered, seems to work fine: https://github.com/conan-io/conan/pull/10151/files

**Comment by memsharded** [comment] 2021-12-09 13:30
Merged https://github.com/conan-io/conan/pull/10151, I guess we are ready for 2.0, and nothing else to do in 1.X (besides applying the condition explicitly in your recipes)? Can we close this issue then? Thanks.

**Closed as completed** 2021-12-09 14:25 UTC
Labels: stage: triaging
