### ISSUE TITLE
[bug] Cannot create package containing python_requires

### ISSUE THREAD

**Issue by franzlst** [conan-io/conan#6156] opened 2019-11-28 15:23 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: OSL42
  * Compiler+version: non used
  * Conan version: tested with 1.19.3 and 1.20.4
  * Python version: 3.6

### Steps to reproduce (Include if Applicable)

I have exported the package `python-dist/1.2.0@stei_fn/snapshot` both locally and on a remote.

In the conanfile of my other package `rafcon/0.14.2`, I do
```python
from conans import python_requires
if not hasattr(python_requires, "_remotes"):  # just for debugging
    import traceback
    traceback.print_stack()
python_dist = python_requires("python-dist/1.2.0@stei_fn/snapshot")

class MyConanFile(ConanFile):
    # ...
```

Now I call `conan create . "rafcon/0.14.2@stei_fn/snapshot"`

### Logs (Executed commands with output) (Include/Attach if Applicable)

I added `traceback.print_stack()` so that you can see where the error comes from. This is the output I get:

```
Exporting package recipe
Linter warnings
[...]
rafcon/0.14.2@stei_fn/snapshot exports_sources: Copied [...]
rafcon/0.14.2@stei_fn/snapshot: The stored package has not changed
rafcon/0.14.2@stei_fn/snapshot: Using the exported files summary hash as the recipe revision: ba2507222d52974815e07a9a359d0e93 
rafcon/0.14.2@stei_fn/snapshot: Exported revision: ba2507222d52974815e07a9a359d0e93
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.flags=-march=core2 -mssse3 -mfpmath=sse -pthread
compiler.libcxx=libstdc++
compiler.version=4.8
os=Linux
os.distribution=osl42
os_build=Linux
[options]
[build_requires]
[env]
AR=gcc-ar-4.8
CC=gcc-4.8
CFLAGS=-march=core2 -mssse3 -mfpmath=sse -pthread
CPP=cpp-4.8
CXX=g++-4.8
CXXFLAGS=-march=core2 -mssse3 -mfpmath=sse -pthread
NM=gcc-nm-4.8
RANLIB=gcc-ranlib-4.8
[wrapper commands]
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/command.py", line 2040, in main
    error = command.run(args)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/command.py", line 1911, in run
    method(args[0][1:])
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/command.py", line 355, in create
    lockfile=args.lockfile)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/conan_api.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/conan_api.py", line 353, in create
    test_build_folder, test_folder, conanfile_path, recorder=recorder)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/cmd/create.py", line 57, in create
    recorder=recorder)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/manager.py", line 46, in deps_install
    False, update, remotes, recorder)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/graph_manager.py", line 182, in load_graph
    graph_lock=graph_lock)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/graph_manager.py", line 280, in _load_graph
    graph_lock)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/graph_builder.py", line 38, in load_graph
    processed_profile, graph_lock)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/graph_builder.py", line 134, in _load_deps
    remotes, processed_profile, new_reqs, new_options, graph_lock)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/graph_builder.py", line 155, in _handle_require
    remotes, processed_profile, graph_lock)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/graph_builder.py", line 335, in _create_new_node
    lock_python_requires=lock_python_requires)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/loader.py", line 149, in load_conanfile
    conanfile_class = self.load_class(conanfile_path, lock_python_requires)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/loader.py", line 41, in load_class
    _, conanfile = parse_conanfile(conanfile_path, self._python_requires)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/loader.py", line 258, in parse_conanfile
    module, filename = _parse_conanfile(conanfile_path)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/loader.py", line 293, in _parse_conanfile
    loaded = imp.load_source(module_id, conan_file_path)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/volume/conan_cache/stei_fn/.conan/data/rafcon/0.14.2/stei_fn/snapshot/export/conanfile.py", line 13, in <module>
    traceback.print_stack()
ERROR: Error loading conanfile at '/volume/conan_cache/stei_fn/.conan/data/rafcon/0.14.2/stei_fn/snapshot/export/conanfile.py': Unable to load conanfile in /volume/conan_cache/stei_fn/.conan/data/rafcon/0.14.2/stei_fn/snapshot/export/conanfile.py
KeyError: python-dist/1.2.0@stei_fn/snapshot

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/loader.py", line 293, in _parse_conanfile
    loaded = imp.load_source(module_id, conan_file_path)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/volume/conan_cache/stei_fn/.conan/data/rafcon/0.14.2/stei_fn/snapshot/export/conanfile.py", line 14, in <module>
    python_dist = python_requires("python-dist/1.2.0@stei_fn/snapshot")
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/python_requires.py", line 72, in __call__
    python_req = self._look_for_require(reference)
  File "/opt/python/osl42-x86_64/python3/default/lib/python3.6/site-packages/conans/client/graph/python_requires.py", line 46, in _look_for_require
    remotes=self._remotes)
AttributeError: 'ConanPythonRequire' object has no attribute '_remotes'
```
So the package is successfully exported (where `python_requires` is executed correctly), but during the creation, the remotes are not set for `python_requires`, which it why it fails.

Is there an issue with my conanfile or is this a bug?

I have seen #5140, but that issue is fixed.

**Comment by memsharded** [comment] 2019-11-28 16:28
Hi @franzlst 

I have tried to reproduce the issue with the following test:

```python
    def traceback_error_test(self):
        # https://github.com/conan-io/conan/issues/6156
        client = TestClient()
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . tool/0.1@user/testing")

        reuse = textwrap.dedent("""
            from conans import ConanFile, python_requires
            if not hasattr(python_requires, "_remotes"):  # just for debugging
                import traceback
                traceback.print_stack()
            python_dist = python_requires("tool/0.1@user/testing")
            
            class MyConanFile(ConanFile):
                pass
            """)
        client.save({"conanfile.py": reuse}, clean_first=True)
        client.run("create . pkg/0.1@user/testing")
        self.assertIn("pkg/0.1@user/testing: Created package ", client.out)
```

It is working fine, it doesn't fail. There must be something in the python-require conanfile.py, that it is making it fail. What could it be? What is inside that recipe? Transitive requires or something like that? Could you please share more details? Thanks!

**Comment by franzlst** [comment] 2019-12-04 08:23
OK I found the root cause of the issue:

In the conanfile of `python-dist/1.2.0@stei_fn/snapshot` (the "tool"), I export a script: ` exports = "conan_utils.py"`. Within this script I have the following two lines:
```python
conan_api, _, _ = Conan.factory()
result = conan_api.search_recipes("python-dist/*@tools/stable", remote_name="rmc-conan-libs")
```
These lines are not within any function, thus they are executed when the file is imported. When I omment out the search command, I can create my package.

Now you have to decide whether what I do is ugly and should not be supported or whether it is a Conan bug :-)

**Comment by memsharded** [comment] 2019-12-04 09:36
Hi @franzlst 

Yes, I think what you are doing seems a bit crazy. If I understood correctly, you are trying to use the Conan (undocumented, unpublished) python API **inside** a recipe that is a python-require of another, to do a search for recipes in a hardcoded ``remote-name``. 

If I understood it correctly, yes, I think you are abusing 2 o 3 different Conan things and also implementing a couple of anti-patterns 😄 

Using the conan python api from recipes should not be used. It sounds it will never be a supported use case.

Maybe, if you try to example the problem that you are trying to solve with that, we could think of what would be the best approach with current tooling, or if maybe it makes sense to propose some new functionality. Could you please elaborate and explain with more detail it?

**Comment by franzlst** [comment] 2019-12-04 09:52
I guess what I want to do boils down to dynamically set the available values for an option that depend on what packages are existing.

So we have a Conan package "python-dist", providing a bunch of python packages (replacing the set of python packages provided by openSUSE Leap). Regularely, new releases of this package are created. For other packages (here `rafcon`), I want the user to be able to specify on which python-dist version to depend on. Therefore I need to query which python-dist versions are existing, to dynamically make them available as options (using `config_options()`).

At the end, the problem is a bit more complex (although probably not relevant here). Different version of python-dist provide different Python packages. We want to manage all out Python dependencies with Conan (no PyPI). Therefore, I also need to find out, which Python packages are provided by python-dist, to add required Python depencies not provided by python-dist dynamically as further requirement (using `requirements()`).

**Comment by memsharded** [comment] 2019-12-04 10:32
I think I start to understand, but still would like more details.

So you have:
```
python_dist/1.0@franz/stable
python_dist/1.1@franz/stable
python_dist/1.2@franz/stable
.....
```
Each one is packaging some python functionality, I think the details of the origin (pip SUSE, or whatever) are irrelevant for this case, aren't they?

Then you have your consumer recipes:

```python
tools = python_requires("python_dist/1.1@franz/stable")
class Pkg(ConanFile):
     ...
```

But I don't clearly understand how the version is made available dynamically through options. 

> We want to manage all out Python dependencies with Conan (no PyPI).

Question, you don't want to use PyPI or you don't want to use ``pip``? Different things, need to understand, because ``pip`` sounds more simple for this use case.

> Therefore, I also need to find out, which Python packages are provided by python-dist,

This could be just some information provided by the python_requires package, not clear why the dynamic search via the conan api.


Also, we are going to merge important changes in ``python_requires`` feature (https://github.com/conan-io/conan/pull/5804/files). The current way will not be removed yet ,but it will be in the future. Lets try to come up with something that makes sense.

**Comment by franzlst** [comment] 2019-12-04 10:35
> Each one is packaging some python functionality, I think the details of the origin (pip SUSE, or whatever) are irrelevant for this case, aren't they?

Yes!

**Comment by franzlst** [comment] 2019-12-04 11:04
> Each one is packaging some python functionality, I think the details of the origin (pip SUSE, or whatever) are irrelevant for this case, aren't they?

Yes!

> But I don't clearly understand how the version is made available dynamically through options.

Ah right, dynamically _adding_ options is not possible (feature request), just removing ones. So I add the options like this:
```python
tools = python_requires("python_dist/1.1@franz/stable")
python_dist_version = tools.get_python_dist_versions()
class Pkg(ConanFile):
    [...]
    options = {
         "python_version": ["2", "3"],
         "python_dist_version": list(map(str, python_dist_versions.keys()))
    },
    default_options = {"python_version": "2", "python_dist_version": str(max(python_dist_versions.keys()))}
```
> Question, you don't want to use PyPI or you don't want to use pip? Different things, need to understand, because pip sounds more simple for this use case.

Our projects need to work without internet access. Therefore, we want every PyPI package to be available as Conan package (there is an automated conversion).

>>    Therefore, I also need to find out, which Python packages are provided by python-dist,

>This could be just some information provided by the python_requires package, not clear why the dynamic search via the conan api.

The Python packages provided by python-dist depend on the version of python-dist.

**Comment by memsharded** [comment] 2019-12-04 11:19
> Our projects need to work without internet access. Therefore, we want every PyPI package to be available as Conan package (there is an automated conversion).

But you can have your own private PIP registry in Artifactory, in the same way you have Conan repositories. You will work without internet access, but with pip.

**Comment by franzlst** [comment] 2019-12-04 11:40
> But you can have your own private PIP registry in Artifactory, in the same way you have Conan repositories. You will work without internet access, but with pip.

Yes, we thought abou that, but then we cannot manage dependencies of a Conan package to these Python packages.

**Comment by memsharded** [comment] 2021-12-04 16:14
I think this issue has become obsolete with the new python_requires (declared as class attribute), the new ``python_requires_extend()``, and the ``init()`` method to be able to define inheritance specific behaviors. So I am closing this issue, please open new ones for feedback about the new ``python_requires``, thanks.

**Closed by memsharded** 2021-12-04 16:14 UTC
Labels: stage: triaging
