### ISSUE TITLE
Changes in exported conanfile.py are not reflected because outdated conanfile.pyc is used

### ISSUE THREAD

**Issue by mschmid** [conan-io/conan#1551] opened 2017-07-27 08:38 UTC
When fixing bugs in my recipes the following bug occured several times now:
After exporting a changed conanfile.py, I had to delete my local conan cache to see those changes in the workflow because otherwise still the outdated existing conanfile.pyc is used. Is there any fix for this?

**Comment by memsharded** [comment] 2017-07-27 09:39
Not sure about this issue, cannot replicate here.
Maybe the default behavior should be clarified: when ``export``ing package recipes, the package binaries existing in the local cache are not removed by default. This is done, because it is very annoying to have all the binaries, even for other configurations, even for small changes in the recipe, while developing, testing and debugging packages. 

Is it possible, that you are reusing previously created binaries? In that case, you don't need to remove the whole cache, only the specific package. If not, could you please help with a reproducible example of this behavior? Thanks!

**Comment by mschmid** [comment] 2017-08-07 07:38
This issue happened while restructuring my recipes.
I tried to reproduce this and was not successful. I will provide a minimal working example as soon as I encounter this issue again.

**Comment by memsharded** [comment] 2017-08-07 08:30
Ok, good. Then, please let me close this issue by now, as it doesn't require action from our side. As soon as you can have a working example to reproduce or any further details that help to debug this, please re-open the issue and we will have a look. Thanks!

**Closed by memsharded** 2017-08-07 08:30 UTC
