### ISSUE TITLE
Conan optional requirement

### ISSUE THREAD

**Issue by danielhalati** [conan-io/conan#1900] opened 2017-10-17 07:00 UTC
I've searched for this and I did not find anything. Take a look at the following scenario:

I have to build a static library which uses zlib and libarchive and I want to guard the archive functionality with a preprocessor macro. The static library doesn't need to link to zlib and libarchive to compile.

So I would like to have an optional requirement for zlib and libarchive and if these libraries are found, inside conanbuildinfo.cmake ZLIB_FOUND and LIBARCHIVE_FOUND variables to be set to TRUE otherwise to FALSE.

This is a snippet from my CMakeLists.txt file

if(${ZLIB_FOUND}  AND ${LIBARCHIVE_FOUND})
    add_definitions(-DARCHIVER_FUNCTIONS)
else()
    message(STATUS "Notice: " ${_this} " will build without ARCHIVER_FUNCTIONS")
endif()

So keep in mind that I don't want to link here. Only the executable will link to zlib and libarchive.

**Comment by memsharded** [comment] 2017-10-17 09:59
Even if the static library doesn't require the dependencies to link, it still anyways require the packages to be installed, and depend on them, so the headers of those libraries are included.

Indeed, conditional dependencies are possible using a ``requirements()`` method (check the docs), but I am not sure that is what you want.  Also, doing a ``target_link_libraries(your_lib ${CONAN_LIBS})`` is totally harmless, it has no effect for such static library.

Also, I am missing some info, I don't know what the ARCHIVER_FUNCTIONS are doing. Could you please provide a bit more context of what are you doing, what is failing, steps to reproduce, etc? Thanks for the feedback!

**Comment by danielhalati** [comment] 2017-10-17 12:27
For some libraries, I only compile some of the source files only if I find some certain library. I want inside the CMakeLists.txt file to have some variables for my found libraries so I can check them and add some compile definitions.

ARCHIVER_FUNCTIONS is a macro which gets added from CMakeLists.txt file if libarchive and zlib are present.

In my case, if I don't find the libraries I disable the code from the static library and I compile without zlib and libarchive. I also disable the includes to the header files.

#5.Source/header files
file(GLOB _HEADERS include/*.h )
file(GLOB _SOURCES source/*.cpp source/*.c)

#6.Libraries search
set(USE_LIBARCHIVE "no")
set(USE_ZLIB "no")

if(WIN32)
    GENERIC_FIND(archive_static "INCLUDES:archive.h;archive_entry.h")
    if(archive_static_FOUND)
        set(USE_LIBARCHIVE "yes")
    endif(archive_static_FOUND)
else()
    GENERIC_FIND(archive "INCLUDES:archive.h;archive_entry.h")
    if(ARCHIVE_FOUND)
        set(USE_LIBARCHIVE "yes")
    endif(ARCHIVE_FOUND)
endif(WIN32)


if(WIN32)
    GENERIC_FIND(zlibstatic)
    if(zlibstatic_FOUND)
        set(USE_ZLIB "yes")
    endif(zlibstatic_FOUND)
else()
    GENERIC_FIND(z)
    if(Z_FOUND)
        set(USE_ZLIB "yes")
    endif(Z_FOUND)
endif(WIN32)

if(${USE_LIBARCHIVE} STREQUAL "yes" AND ${USE_ZLIB} STREQUAL "yes")
    add_definitions(-DARCHIVER_FUNCTIONS)
else()
    message(STATUS "Notice: " ${_this} " will build without ARCHIVER_FUNCTIONS")
endif()

#7.Library/executable
add_library(${_this} STATIC ${_HEADERS} ${_SOURCES})

GENERIC_FIND is a function which searches for the libraries.

**Comment by memsharded** [comment] 2017-10-17 12:44
Ok, I get it, but still don't understand what we are trying to achieve. With conan, you are in control if the dependencies are retrieved or not, it is not something that you have to check or find. If you ``require`` zlib and libarchive, then, you will get cmake variables with the include paths, lib names, etc, for them. You don't need to find them, they will be there, because they have been retrieved by conan, in a certain path in the conan cache.

What is your conanfile? I guess you are using the cmake generator and including conanbuildinfo.cmake, right? The moment you include that file, you have the variables, and you know the dependencies are there.

**Comment by danielhalati** [comment] 2017-10-17 14:32
I want my cmake file to be flexible. I want to compile my library even if when zlib and libarchive are not available. This way I can run my library code on some dsp platform where I can't compile zlib and libarchive.  In the current situation I search for the libraries locally on my machine and because I don't have I disable some code. 

With conan I would like to be able to compile a certain library with some dependencies only on some specific architectures. On arm and dsp I need to disable some code.

**Comment by memsharded** [comment] 2017-10-17 14:46
OK, that makes sense. Probably what you want is something like:

```python

class Pkg(ConanFile):

    def requirements(self):
        if self.settings.arch == "x86":
              self.requires("zlib/....")
              self.requires("libarchive/....")

    def build(self):
        cmake = CMake(self)
        if self.settings.arch == "armv7":
              cmake.definitions["DISABLE_SOMETHING"] = "ON"
        cmake.configure()
        ....
```

Then in your CMakeLists you can do things like:
```cmake
if (EXIST ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    conan_basic_setup()
    set(USING_CONAN_DEPENDENCIES True)
endif()

if(USING_CONAN_DEPENDENCIES AND CONAN_INCLUDE_DIRS_ZLIB)
    #ZLIB is there, retrieved by conan
else()
   ...
endif()
```

**Comment by danielhalati** [comment] 2017-10-17 15:21
I  understand your concept but I am not using conan to build my own libraries. I have another python script that calls cmake using different toolchain files depending on the architectures.

I only want to you use conan to pack 3rd party libraries. My libraries should only retrieve the packages from conan and use them.

**Comment by memsharded** [comment] 2017-10-17 15:41
Still, the inclusion ``${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)`` is necessary to use conan dependencies, isn't it? Then you know you have installed them. 
How are you calling ``conan install``, with a conanfile.txt? I might still be missing something from your flow.

**Comment by danielhalati** [comment] 2017-10-17 17:04
I have a python script which calls conan install and the cmake configure with some specific arguments and cmake build. I am including conanbuildinfo.cmake in my CMake file. 

The question now I think is can I add requirements inside conanfile.txt based on architectures ?

**Comment by memsharded** [comment] 2017-10-17 20:35
No, conanfile.txt is very simple, no conditionals. But you can perfectly use a conanfile.py with a ``requirements()`` method that will do that. No need to implement the other methods, like build(), or package(), you can use conanfile.py for consuming only.

**Comment by danielhalati** [comment] 2017-10-17 20:36
I Will try and see what it comes out. Thank you for your replies.

**Comment by danielhalati** [comment] 2017-10-18 05:52
Can you help me with the copying of the requirements in some user-defined space? I cannot get it working

`


    def requirements(self):
        if self.settings.arch != 'c6000':
            self.requires('zlib/1.2.8@wenglor/stable', private=True, override=False,)
            self.requires('libarchive/3.1.900a@wenglor/stable', private=True, override=False)
            
    def imports(self):
        #self.copy(".", "*", "archives")
`

**Comment by memsharded** [comment] 2017-10-18 08:23
Can you please provide more info, that is not enough. Some comments:

- You don't need to specify private, or override at all. Don't use private=True unless you have very solid reasons and know very well what that means
- Your ``imports()`` seems wrong, it is commented, but in any case, it starts with the pattern: ``self.copy("*", ....)```
- When reporting issues for help, please try to provide more info. "I cannot get it working" is not really useful, try to explicitly say what is failing. Copy & paste the output, too.

**Comment by danielhalati** [comment] 2017-10-18 08:27
I have a conanfile.py file which implements the requirements method and I want to copy the binaries from all the requirements in some folder.

self.copy is commented because it does not work for me yet

**Comment by memsharded** [comment] 2017-10-18 09:09
Could you please uncomment it, correct it as suggested, run it, and provide the full output?

**Comment by danielhalati** [comment] 2017-10-19 06:27
This is my  conanfile.py:

> from conans import ConanFile, CMake, tools,os
> class libwcryptConan(ConanFile):
>     name = "libwcrypt"
>     version = "1.0.0"
>     license = "<Put the package license here>"
>     url = "<Package recipe repository url here, for issues about the package>"
>     description = "<Description of Zlib here>"
>     settings = "os", "compiler", "build_type", "arch"
>     options = {"shared": [True, False]}
>     default_options = "shared=False"
>     generators = "cmake"
> 
>     def requirements(self):
>         if self.settings.arch != 'c6000':
>             self.requires('zlib/1.2.8@user/stable')
>             self.requires('libarchive/3.1.900a@user/stable')
>             
>     def imports(self):
>         self.copy("*.a", "", "libtest")
> 

This is the output:

> I.Conan step ...
> conan install /home/user/Desktop/Projects/wKeygen-x86_64-Linux/libwcrypt -s build_type=Debug -s arch=x86_64 -s os=Linux --profile /home/user/Desktop/Toolchain/scripts/../profiles/x86_64-Linux
> PROJECT: Installing /home/user/Desktop/Projects/wKeygen-x86_64-Linux/libwcrypt
> Requirements
>     libarchive/3.1.900a@user/stable from local
>     zlib/1.2.8@user/stable from local
> Packages
>     libarchive/3.1.900a@user/stable:2d84021f0b0fd0c50232dba4d5995e54f9ccfce2
>     zlib/1.2.8@user/stable:2d84021f0b0fd0c50232dba4d5995e54f9ccfce2
> 
> libarchive/3.1.900a@user/stable: Already installed!
> zlib/1.2.8@user/stable: Already installed!
> PROJECT: Generator cmake created conanbuildinfo.cmake
> PROJECT: Generated conaninfo.txt

**Comment by memsharded** [comment] 2017-10-19 13:10
Github can properly show code, dont use quoting, but use proper syntax highlight. I have updated your above comment you can check.

There is an error in your ``imports()`` method, use:

```python
    def imports(self):
        self.copy("*.a", src=".", dst="libtest")
        # or just
        self.copy("*.a", dst="libtest")
````

**Comment by birsoyo** [comment] 2017-11-06 20:20
I also needed optional requirements. I think all I need is a non failing `self.requires`.
```python
def requirements(self):
    self.requires('name/version@user/channel', optional=True) # returns true (always?) and never fails.
```
Here is my use case:
I have an app that uses a library that you need to register to download hence I can't create a public conan package for it. So my application's source code has a recipe that will create the conan package if the builder of my application downloads that binary distribution to a known location. But my app can build and run without it. 

And my _workaround_ is:
In my application's conanfile.py:
```python
    def requirements(self):
        if self._is_available('name'): # I wish conan did this so we don't have to :).
            self.requires(f'name/version@user/channel')

    def _is_available(self, name): # This is not very robust but it works for now (i.e. no version matching etc)!
        r = subprocess.getoutput(f'conan search --raw {name}/*')
        return len(r) > 0
```
C++ side, just uses new `__has_include` (C++17)  to test for the existence of the library. Hopefully I won't need to make more complex decisions.

**Comment by memsharded** [comment] 2017-11-06 21:46
I think the most recommended and clean way would be to use an ``option`` for it, you are yourself defining it as "optional" :)  Something like:

```python

class Pkg(ConanFile):
    ...
    options = {"use_name": [True, False]}
    default_options = "use_name=False"

    def requirements(self):
          if self.options.use_name:
                self.requires("name/version....")
```

It is very important to keep control and knowledge of what is happening. If it is conditioned to the possible fetching of it from a remote, it could happen a temporary connection error, that there was a typo in the package version.... many errors, that could go unnoticed because of that approach. You certainly want to define that you want to use it:

```bash
$ conan install . -o App:use_name=True
```
You can manage this also easily in profiles. 
Please tell me if this makes sense. Thanks!

**Comment by birsoyo** [comment] 2017-11-06 21:55
It makes perfect sense. I can't try it right now but I don't see any reason why 'option' won't work for my case.
Thanks.

**Comment by memsharded** [comment] 2017-11-06 22:04
Good, let me know how it goes, and if you have further questions. Cheers!

@danielhalati I guess that the above fix of  your ``imports()`` method worked, so I think we can close this issue now, but please re-open or submit a new one for any question.

**Closed by memsharded** 2017-11-06 22:04 UTC
Labels: question
