### ISSUE TITLE
[bug] conan create complains about missing settings.compiler.exceptions, settings.compiler.threads after updating to conan 2.0

### ISSUE THREAD

**Issue by sveitech** [conan-io/conan#13190] opened 2023-02-22 21:21 UTC
### Environment details

* Operating System+version: Linux
* Conan version: 2.0
* Python version: 3.10

### Steps to reproduce

Custom package at work, which works fine in conan 1.59, cannot build under conan 2.0.

Complains about missing settings.compiler.threads, settings.compiler.exception. These fields are not generated automatically by "conan profile default" either, and I cannot find any documentation on what to set in these fields.

Using this guide: https://docs.conan.io/en/1.46/conan.pdf, I tried filling in the fields with values and the build proceeds succesfully.

- "conan profile default" should set these fields in the default profile, if they are required
- The conan documentation should state what values are expected of these fields.

**Comment by sveitech** [comment] 2023-02-22 21:28
It was a misunderstanding on my part. For whom it may concern:

The fields in .conan2/settings.yml file seems to be "enforced" now. If the gcc entry contains settings for exception, thread, they must be present in the profile now, otherwise an error is thrown.

**Comment by memsharded** [comment] 2023-02-22 21:51
Hi @sveitech 

Thanks for your report.
The fields in settings.yml are not necessarily enforced in 2.0. But probably the issue is that the syntax slightly changed, it was standardized to be standard yml. Now settings that admit not being defined are like:
```yml
mysetting: [null, "value1", "value2"]
```
With the ``null`` yaml value.
Could you please check that?

**Comment by sveitech** [comment] 2023-02-23 10:23
That did the trick! Thank you :)

**Comment by memsharded** [comment] 2023-02-23 11:28
Perfect! Thanks for telling.
Closing this issue as solved, but don't hesitate to open new ones for further questions.

**Closed as completed by memsharded** 2023-02-23 11:28 UTC
Labels: stage: triaging
