### ISSUE TITLE
Infinite recursion while building dependency graph

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#3293] opened 2018-07-30 16:00 UTC
Hello, 

I'm having an infinite recursion when running `conan install`, here is a screenshot by @SSE4 that shows it:

![image 1](https://user-images.githubusercontent.com/15652306/43408618-1848b788-9422-11e8-9b07-45dca26b8a3d.png)

To reproduce the issue:

* git clone https://github.com/theodelrieu/playground --branch conan_workspace
* cd playground && mkdir build && cd build && conan install .. -if=.

I'm using Conan 1.6.1, but had the issue with Conan 1.6.0.

Here are some other error messages I got before clearing my local cache:

>ERROR: maximum recursion depth exceeded in comparison.

>/Users/theo/.conan/data/boost_container/1.66.0/bincrafters/stable/export/conanfile.py: Error while initializing options. maximum recursion depth exceeded while getting the str of an object
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by theodelrieu** [comment] 2018-07-30 16:01
Note that my project uses Conan workspaces, it might be linked to the issue.

**Comment by lasote** [comment] 2018-07-30 21:25
I can reproduce the issue, there is some kind of recursions with the build requires, the `mgs_test_helpers/0.1@mgs/testing` package and the modular boost packages, but I can't see why...

**Comment by theodelrieu** [comment] 2018-07-30 21:37
I did reset to 2-3 previous commits and had the same issue

Removing all my cache triggers the issue with catch2 as well.

**Comment by theodelrieu** [comment] 2018-07-31 07:47
Ok it seems to be a regression in 1.5.0, using Conan 1.4.5 works fine.

**Comment by theodelrieu** [comment] 2018-08-01 15:37
Well guess what, I indeed had a cyclic build_requirement, I found a workaround, so I guess this issue can be closed?

**Comment by SSE4** [comment] 2018-08-01 15:42
I suppose it's much better if conan detects cyclic requirements and prints error, instead of going into infinite loop (hang)

**Comment by memsharded** [comment] 2018-08-01 18:33
Conan already detects loops/cyclic requirements, but only in the regular dependencies, not in build-requires. That could be much more complex, because the application of build-requires is recursive. But lets have a look if it is possible, plelase don't close the issue yet @theodelrieu and thanks for reporting!

**Comment by memsharded** [comment] 2018-09-17 09:04
I have been checking a solution for this, and at the moment the solution seems very complex for the value (better error message) and the frequency users are firing this error. Also, the solutions that I have researched have some risk, in the sense that they could fire false positives of loops in case some private build-requires have some configuration that makes them using a different binary that already exists, as opposed to having to recurse infinitely. I am proposing to close this issue, if it happens to be something that bites other users regularly, we will consider again. Thanks!

**Closed by memsharded** 2018-09-17 09:04 UTC
Labels: enhancement, look into
