### ISSUE TITLE
[build system] Using toolchains and tools by invoking cmake instead of conan build

### ISSUE THREAD

**Issue by pepe82sh** [conan-io/conan#2956] opened 2018-05-30 15:44 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

## Versions
- Microsoft Windows 10 Pro - 10.0.16299 Build 16299
- Conan 1.3.3
- Cmake 3.10.3
- arm-none-eabi-gcc 4.9.3
- CLion 2018.1

## Setup
I am in an embedded environment and use the cross compiling facilities provided by conan. Specifically I deploy the toolchain (compiler and cmake toolchain) in a conan package and set `self.env_info.CONAN_CMAKE_TOOLCHAIN_FILE` accordingly.

## Problem to be solved
I use CLion like suggested [here](https://docs.conan.io/en/latest/integrations/clion.html). CLion will use `cmake` to build the project, and it is not possible to use `cmake build` for that purpose or use virtualenv. This might still work in most environments, but not when I need a specific toolchain. Even defining the toolchain manually does not solve the problem, as the compiler is not in `PATH`.

## Suggested solution
Rather than using `conan build` to set `PATH` correctly and invoke `cmake` with `-DCMAKE_TOOLCHAIN_FILE=...`, it should be possible to outsource that into `conanbuildinfo.cmake`:

    set(ENV{PATH} "C:\\Path\\to\\package\\bin;$ENV{PATH}")
    set(CMAKE_TOOLCHAIN_FILE "C:/Path/to/toolchain.cmake")

This way the `PATH` and toolchain are set even when using `cmake`, and calling `conan build` isn't a necessity anymore.

## Limitations of suggested solution
This only seems to work when the `project()` function is called after `include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)` and before `conan_basic_setup()`

**Comment by pepe82sh** [comment] 2018-05-31 07:42
I just tried conan 1.4 and the cmake_paths generator. That one would be more than enough for my usecase, but I have no chance of using the toolchan file. I propose the following:

- Add a variable `CONAN_MODULE_PATH` that you use to set `CMAKE_MODULE_PATH` and `CMAKE_PREFIX_PATH` (instead of hard copy the paths twice)
- Add a variable `CONAN_CMAKE_TOOLCHAIN_FILE` that has the toolchain file

`CONAN_MODULE_PATH` would allow to iterate through all module paths and add them to the `PATH` like that:

```
foreach(MODULE_PATH ${CONAN_MODULE_PATH})
	set(PATH_SEPARATOR ":")
	if(WIN32)
		set(PATH_SEPARATOR ";")
		string(REPLACE "/" "\\" MODULE_PATH ${MODULE_PATH})
	endif()
	set(ENV{PATH} "${MODULE_PATH}bin${PATH_SEPARATOR}$ENV{PATH}")
endforeach()
```

That part could even be provided outside conan, as long as `CONAN_MODULE_PATH` exists.

Same goes for `CONAN_CMAKE_TOOLCHAIN_FILE`. One could set `CMAKE_TOOLCHAIN_FILE` himself, as long as `CONAN_CMAKE_TOOLCHAIN_FILE` exists.

This solution would be as unintrusive as possible and could fix my problem.

**Comment by memsharded** [comment] 2018-05-31 09:54
Hi @pepe82sh 

Thanks for the detailed feedback.

I am not sure if I understood the issue completely.
Just in case, do you now about the conan ``virtualenv``? The flow with it would be to activate the virtualenv after the ``conan install`` and before calling ``cmake ...``, so the environment variables would be there, no need to have cmake defining them.

In any case, I think there might be a use case here that needs more investigation, will have a look.

**Comment by pepe82sh** [comment] 2018-05-31 10:54
Hi @memsharded 

I do know about virualenv and was able to use it when there is no IDE involved. Unfortunately I can't get CLion to run cmake inside the virtualenv. The CLion-Way to do such thing is to put it inside the CMakeLists.txt, and run `cmd /c enable.bat` as an external process. That doesn't work, because it'll run inside its own cmd process and the environment will be gone after the command finished.

I am not a python person, but I forked conan in order to make better suggestions (didn't commit anything so far). From what I can see my problem boils down to "I need the environment variables inside cmake without calling `conan build`". There are 2 ways to achieve that:

1. The non intrusive way
For each environment variable, we add a `CONAN_ENV_VARNAME` variable inside cmake. That wouldn't hurt anyone, and give the opportunity to use them in special cases like mine.

2. The more sophisticated way
We set each environment variable inside cmake using `$ENV{VARNAME}`. That might become interesting with lists like `PATH`, where you could add items twice when invoking `conan build`. From what I see that could be solved by adding another variable via `conan build` and test if that is set before setting the environment within cmake.

In any case `CONAN_CMAKE_TOOLCHAIN_FILE` is special, as it is not only an environment variable, but something that should be transformed to `CMAKE_TOOLCHAIN_FILE` inside cmake. That'd reqire either a special treatment by conan, or by the user. Nonetheless there would be **a** solution for my problem however it is approached.

**Comment by pepe82sh** [comment] 2018-05-31 11:48
I just figured that I can write my own generator based on cmake_paths and provide that as a package. That should enable me to fix all my problems without the need of changes in conan and should be the cleanest solution for everyone involved. I'll leave this open and paste the generator I came up with once I'm finished. Shouldn't take long though.

**Comment by lasote** [comment] 2018-05-31 11:59
Hi @pepe82sh. I understand the issue. I think your idea of a generator that sets the `env` and include the toolchain declared in `CONAN_CMAKE_TOOLCHAIN_FILE` could work. 

I'm a little worried about the `cmake_paths` generator, that would change the simple scope it was designed for, a better name for the generator now could be `cmake_toolchain`, because the principal use case is to be used as a toolchain in the command line. 

Let me think about it and try it, and of course, if you write a generator tell me, it has general interest I think.

**Comment by lasote** [comment] 2018-06-01 07:11
Hi! Thanks for sharing. We will discuss it and if we agree we will introduce the generator to the Conan code base for 1.5.

**Comment by lasote** [comment] 2018-06-01 10:34
By the way, I've been playing with [CMAKE_PROJECT_\<PROJECT-NAME\>_INCLUDE](https://cmake.org/cmake/help/v3.11/variable/CMAKE_PROJECT_PROJECT-NAME_INCLUDE.html#variable:CMAKE_PROJECT_%3CPROJECT-NAME%3E_INCLUDE)
variable as an alternative to `CMAKE_TOOLCHAIN_FILE`, this do not solve the current issue, but just for let you know that you could kind of inject two different toolchain files.

**Comment by pepe82sh** [comment] 2018-06-01 12:30
Thanks @lasote! That is an interesting feature indeed that I didn't know about! Don't know if I'll need it yet, but definitely nice to know!

**Comment by puetzk** [comment] 2018-06-21 16:22
This feels like a feature that would be a very good fit for https://github.com/conan-io/cmake-conan as well...

**Comment by lasote** [comment] 2018-06-25 13:10
We have been thinking about the `$ cmake` vs `conan build` and we think it deserves a deeper analysis. The env vars is only a part of the problem, (thanks for bringing it to the surface), but all the vars adjusted in the `CMake()` build helper (and other build helpers) are not applied only using cmake. We are delaying this until we find a better global approach to solve it.

**Comment by AndreyNautilus** [comment] 2018-07-16 12:52
I have a similar issue: cmake's `CMAKE_CXX_STANDARD` variable is not set by `conanbuildinfo.cmake` when I try to build my package locally with `conan install` followed by `cmake` calls:
```
conan install . -s cppstd=11
cmake .
cmake --build .
```
The build fails with the reason: c++11 features are not enabled.

If I use conan commands only, everything works fine:
```
conan install . -s cppstd=11
conan build .
```
but I don't want to run the whole `build` method, I want to build just a small bit of my project.

Using pure `cmake` after `conan install` could be handy if you don't want to test the `build` method, but you only want to force a recompilation (to test that you don't have a syntax errors for example) during development.

Here is a minimal example of what I mean
[conan-cxx-test.tar.gz](https://github.com/conan-io/conan/files/2197607/conan-cxx-test.tar.gz)

**Comment by memsharded** [comment] 2018-07-16 14:55
Thanks @AndreyNautilus for the feedback.
Yes, what you report is totally aligned with this issue, definitely something that should be improved.

**Comment by pepe82sh** [comment] 2018-12-31 00:13
BTW: I improved the example for a generator to a point where I think it should be complete (Environment and flags sent when Cmake is called). It's not fully tested, but I'd appreciate any thoughts from you guys. [link](https://github.com/pepe82sh/ConanCmakeToolchainGenerator/blob/master/conanfile.py)

**Comment by peter-moran** [comment] 2019-03-10 18:55
@pepe82sh I've tested your [ConanCmakeToolchainGenerator](https://github.com/pepe82sh/ConanCmakeToolchainGenerator) for my own project, and it was exactly what I needed. It would be awesome to see it packaged with Conan.

**Comment by jgsogo** [comment] 2019-10-17 09:46
There is a POC ongoing about toolchains: https://github.com/conan-io/conan/pull/5919

**Comment by peter-moran** [comment] 2021-08-09 21:17
Is this satisfied by https://docs.conan.io/en/1.32/creating_packages/toolchains/cmake.html?

**Comment by jgsogo** [comment] 2021-08-10 08:00
It should be. I'm closing this issue as it is based on old implementations that have been superseded by new toolchains. 

Issues and feedback (always more than welcome) should relate to these new helpers.

Thanks!

**Closed by jgsogo** 2021-08-10 08:00 UTC
Labels: type: look into, to do, priority: high, complex: medium, component: Build
