### ISSUE TITLE
conan new could generate license file

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#1216] opened 2017-04-18 11:16 UTC
Hi!

`conan new` really helps to create a new project from scratch. Some parameters, as *url* and *license* are optional, by default.  
Could be possible implement a new parameter to solve more popular licenses and download the license file from https://opensource.org/licenses.

E.g.
    `conan new --license=mit foobar/0.1.0@uilianries/testing`

This statement could result:
```
foobar/
    ├── conanfile.py
    └── LICENSE.md
```

Where, *conanfile.py* will receive `license = "MIT"`, and *LICENSE.md* will be downloaded from https://opensource.org/licenses/MIT.

When is not possible connect to download, only *license* property is filled in *conanfile.py*.

**Comment by memsharded** [comment] 2017-04-18 12:48
The license for the packaged source code doesn't need to be downloaded to the package recipe. It will be naturally downloaded in the ``source()`` method, and the package creator can ``package()`` it. A couple of notes:
- The license of the package recipe, the one that could be in the package recipe repo, is not necessarily the same as the source code one. I can write a recipe that will download and package some GPL library from github, and the package recipe can be covered by an MIT license. There is no actual connection (like linking) between the package recipe and the final package, besides the package recipe containing an URL pointing to the source repo.
- The ``license`` field of the ConanFile is meta-information about the library being packaged, not the current recipe.
- There will be many licenses that will not be covered by built-in licenses, like MIT
- Even for the same "MIT" license, the copyright holder changes. It is impossible to deduce the copyright holder.

**Comment by uilianries** [comment] 2017-04-18 13:36
Good points, I will try explain my question.

I agree, for recipes that build a third-party project is not necessary download the license, the same is already integrated into the target project.  So, `--license=` won't help.

However, for a new whole project from scratch, using `conan new`, we could use:  

    `$ conan new --test --sources foobar/0.1.0@baz/testing`

Now, we have a minimal project tree with *test_package* and source files. Now we can include the license manually, as next step. For this case, the license field in *conanfile.py* and *LICENSE.md* file could be included automatically as the same.

The holders in *LICENSE.md* file should be filled by developer, as present in all files at https://opensource.org/licenses.

I just thought about popular licenses, for open source projects. Currently, I'm using some **NDA** license, so I can't use a default *LICENSE.md*, but I can use `license = "NDA"` in *conanfile.py*

**Comment by memsharded** [comment] 2017-04-18 14:14
Still sounds a bit out of scope, trying to automate too much will lead to a more complex UI and UX, more code to maintain and document, etc. And without covering 100% of cases, it sounds like many edge cases and special considerations, for something that just take a 0.01% of the time to create packages.

For me the issue is solved, as my flow is:

- Create github repo, with default README and LICENSE. Github will manage to create the license for me!
- git clone myrepo
- $ conan new MYpkg/0.12...  --test
- modify recipe
- $ conan test_package
- git add . & git commit -m "mymsg"
- git push => fire CI to create packages

**Closed** 2017-04-18 15:43 UTC

**Comment by memsharded** [comment] 2017-04-18 15:51
Great, thanks :)
