### ISSUE TITLE
[question] How to avoid building tests when installing package?

### ISSUE THREAD

**Issue by Holt59** [conan-io/conan#14747] opened 2023-09-15 07:43 UTC
### What is your question?

Is there a way to configure a package so that:

1. When I build it or install it locally (`conan install .` / `conan build .`), the tests are built by default (unless `tools.build:skip_test` is set to `true`),
2. When I use the package as a dependency, and the package has to be built because no binary are found, the tests are not build?

I cannot disclose the full `conanfile.py` but that's basically what I use right now:

```python
class MyPackageConan(ConanFile):
    name = "my-package"

    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}
    generators = "CMakeDeps", "CMakeToolchain"
    package_type = "library"

    exports_sources = (
        "src/*",
        "include/*",
        "tests/*",
        "CMakeLists.txt",
        "Version.cmake",
    )

    def set_version(self):
        content = load(self, "Version.cmake")
        major, minor, patch = (
            re.search(r"{}_VERSION\s+([0-9]+)".format(t.upper()), content).group(1)
            for t in ("major", "minor", "patch")
        )
        self.version = f"{major}.{minor}.{patch}"

    def requirements(self):
        self.requires("...", transitive_headers=True)
        self.test_requires("catch2/[^3.4.0]")

    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC

    def validate(self):
        check_min_cppstd(self, 17)

    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        CMake(self).install()

    def test(self):
        CMake(self).test()

    def package_info(self):
        self.cpp_info.libs = ["my-package"]
        self.cpp_info.set_property("cmake_target_name", "my::package")
```

In CMake, I conditionally build the test based on `BUILD_TESTING`, so setting `tools.build:skip_test=true` locally avoid building the tests.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-09-15 18:17
Hi @Holt59 

Thanks for your question.

I think the issue is a small misunderstanding of the ``test()`` method. It is exclusively intended for the ``test_package/conanfile.py`` to test the package is correct, but not to run unit-tests. In regular recipes like this one, the ``test()`` method is never called.

The correct syntax is adding it in the ``build()`` method as:
```python
def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.test()
```
The definition of the ``tools.build:skip_test=True`` will inhibit the building of the test, and it will also inhibit running the tests, but if I understood correctly, this is already working fine for you?

So the answer to the question, is that defining ``tools.build:skip_test=true```avoids building the tests, which is what you want, isn't it? I am not sure if I am missing something, please let me know.

**Comment by Holt59** [comment] 2023-09-15 18:25
@memsharded Sorry, the `def test()` is an old thing from the past that I should remove and is probably irrelevant here.

My question is that currently, if I have `my-package` as a requirement in another project and I do a `conan install .`, this will fetch the sources for `my-package` (assuming there is no binary package) and build them locally, including the tests (because `BUILD_TESTING` is defaulted to `ON` by `CTest`), which I don't want. 

Is there a way to not build the test in this case (i.e., `conan install .` from a project requiring the library) but still build it when developing the package locally (without having to specify something manually)?

**Comment by memsharded** [comment] 2023-09-15 18:34
I see.
The default when binaries are not found is actually failing with an error, and it requires explicit ``conan install . --build=missing`` to specify that you want to build dependencies from sources if binaries not found.

It is true that the current approach at this moment is explicitly specifying it, like:
```bash
conan install . --build=missing -c tools.build:skip_test=true
```

The Conan configuration can be done per-package, so the following should also be possible:
```bash
conan install . --build=missing -c tools.build:skip_test=true -c &:tools.build:skip_test=false
```
Where the ``&`` means the current consumer conanfile


If the problem is the default, there are 2 different cases:
- Recipes from ConanCenter shouldn't be an issue, because they have mostly hardcoded not running the tests
- For your own recipes, you might change the default, and do something like:
```python
def generate(self):
     tc = CMakeToolchain(self)
     tc.cache_variables["BUILD_TESTING"] = self.conf.get("user.myteam:run_test", "OFF")
     tc.generate()

def build(self):
     ... 
     if self.conf.get("user.myteam:run_test"):
        cmake.test()
```
Then for your recipe, you basically never build or run tests, unless you explicitly define the default.

If the issue is the command line, maybe you want to put those conf values directly in the profile or in the ``global.conf``?

**Comment by Holt59** [comment] 2023-09-15 18:47
@memsharded Thanks for the answer. This looks like a very complex process for something that simple (I doubt people expected to build tests when specifying `build=missing` on `conan install`).

What you proprose with `user.myteam:run_test` does not look like a solution - Outside from the fact that it'd require every developer of `my-package` to modify there `global.conf` (less than ideal), this conflicts if I am working on both `my-package` itself and a project that depends on `my-package`, which will always be the case (for me).

Is there no way of differentiating between a build as a dependency (from a `conan install . --build=missing`) and a build for the package it self (`conan build .`)?

**Comment by memsharded** [comment] 2023-09-15 21:53
> This looks like a very complex process for something that simple (I doubt people expected to build tests when specifying build=missing on conan install).

The thing is that in most cases it is not expected that developers need to do ``--build=missing``, but that the necessary binaries have already been created and are available, that is one of the points of using a package manager. For CI machines, it is irrelevant, adding the ``

> Is there no way of differentiating between a build as a dependency (from a conan install . --build=missing) and a build for the package it self (conan build .)?

There is another point of view, specially if using CMake, that developers calling ``conan build .`` is not a common flow either, but instead using ``conan install`` + ``cmake ...``. So doing ``conan install .`` (you can have the ``skip_test=True`` in your global.conf), for the dependencies, avoiding building tests, and calling ``cmake``, ``ctest`` or running the RUN_TEST target from the IDE might be good ways to enable and run the tests.

In any case putting the following in your profile or in your global.conf:
```
tools.build:skip_test=true
&:tools.build:skip_test=false
```
I think that it could achieve the behavior that you want, skipping the tests for dependencies, but building and running them for your current package, isn't it? I am not sure what I am missing here.

**Comment by Holt59** [comment] 2023-09-16 06:52
@memsharded Thanks for the answer, I cannot check today but I'll check the `global.conf` fix when I get a chance to.

**Comment by PeteAudinate** [comment] 2023-09-17 15:32
We also prefer a self-contained "in-recipe" solution to detect whether the package is being built as the main package or as a dependency. Instead of needing a custom conf variable, we solved this with a recipe option:
```python
    options = {"unit_tests": {True, False}}
    default_options = {
        # Run unit tests for this package, but not for its dependencies
        "*:unit_tests": False,
        "unit_tests": True,
    }

    def package_id(self):
        # Don't let running unit tests affect the package_id
        del self.info.options.unit_tests
```
Then a `conan create . --build=missing` will build and run unit tests for the specified package, but not for any of its dependencies. The "correct" behaviour by default, but overridable if needed, and no conf setup necessary outside the package.

**Comment by PeteAudinate** [comment] 2023-09-17 15:33
Any feedback on this approach welcome :-)

**Comment by memsharded** [comment] 2023-09-17 17:23
I think the approach is not bad @PeteAudinate, it it is working for you, that is one of the things we try with Conan, to offer enough flexibility to users that want to do this kind of thing. 

I personally think that it adds some extra lines to recipes that are not that necessary, because it is possible to achieve the same via ``conf``. It is important to notice that there will be some other lines in the recipe that defines how the ``options.unit_test`` affects the build system to actually do the test skipping.

Adding 2 lines to your ``global.conf`` also provides same level of control, if users want to override that behavior, doing ``-c xxx`` in the command line also allows to define what they want.

**Comment by memsharded** [comment] 2023-09-17 17:25
I am adding a test in https://github.com/conan-io/conan/pull/14759, to show that the above suggestion works (it will close this issue when merged, but please comment, re-open or create a new ticket for any further question you might have, thanks!)

**Comment by PeteAudinate** [comment] 2023-09-17 19:45
Ah, you're right, that does make the recipe cleaner. Thanks for pointing this out! I also only just noticed `build:skip_test` is nicely documented in https://docs.conan.io/2/tutorial/creating_packages/build_packages.html?highlight=skip_test#build-and-run-tests-for-your-project.

As an aside, we do still need `if can_run(self):` conditionals in the recipe to prevent tests from being built and run during cross-compilation. Is there a reason that Conan doesn't automatically skip the tests when cross-compiling too?

**Comment by memsharded** [comment] 2023-09-17 21:12
This is a good question. ``can_run`` was born in order to run or not the executables defined in ``test_package/conanfile.py`` ``test()`` method, not for the unit-tests execution within the ``build()`` method. And it has that explicit "can_run" semantics, because there are platforms that can run executables for another architecture that have been cross-built (like OSX).

I think it is decoupled from the tests, also because there are cases in which tests can also be cross-built, even if they cannot be directly executed by Conan, but we have heard about cases in which a hook or something might take those tests and run them elsewhere.

It is a good point, if ``tools.build.cross_building:can_run`` should also be used to automatically skip the execution of tests (not really the building, its semantics don't cover that much). I tend to think that they belong to different responsibilities in different parts of the recipes, but I'll do a quick check with the team too to see what they think.

**Comment by memsharded** [comment] 2023-09-19 12:47
I have shared this with the team. 
It seems we are comfortable current separation between ``skip_test`` and ``can_run`` responsibilities, and it provides enough flexibility for the different use cases.

We will just introduce a note with small example in the docs, for the case:
```python
def build(self):
    cmake = CMake(self)
    cmake.configure()
    cmake.build()
    if can_run(self):
         cmake.test()
```
For the unusual scenario when we want to build tests but we cannot run them because we are cross-building.

Closing this as solved, thanks all for your feedback! (Don't hesitate to open new tickets for any new questions)

**Closed as completed by memsharded** 2023-09-19 12:47 UTC
Labels: type: look into, stage: triaging

**Comment by PeteAudinate** [comment] 2023-09-19 13:38
That sounds fine to me, thanks for following up.

**Comment by Ahajha** [comment] 2023-11-07 11:37
For anyone looking for another solution: I have a very similar conanfile to what is shown at the top, I've done something like this:
```python
from conan import ConanFile
from conan.tools.cmake import CMake, cmake_layout

class CMakeTemplateConan(ConanFile):
    name = "cmake_template"
    # ...
    settings = "os", "compiler", "build_type", "arch"
    generators = "CMakeToolchain", "CMakeDeps"

    exports_sources = [
        "CMakeLists.txt",
        "include/*",
        "source/*",
    ]

    def requirements(self):
        self.requires(...)

    def layout(self):
        cmake_layout(self)

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
    
    def package(self):
        cmake = CMake(self)
        cmake.install()
    
    def package_info(self):
        self.cpp_info.libs = ["foo"]
```
Then in CMake, I do:
```cmake
cmake_minimum_required(VERSION 3.15)
project(cmake_template)

include(CTest)

add_library(foo STATIC)
target_include_directories(foo PUBLIC include)
target_sources(foo
PUBLIC
    "include/cmake_template/lib.h"
PRIVATE
    "source/lib.cpp"
)

install(DIRECTORY include/ DESTINATION include)
install(TARGETS foo DESTINATION lib)

if (EXISTS test/CMakeLists.txt)
    add_subdirectory(test)
endif()
```
The key item being the `EXISTS test/CMakeLists.txt`. When building locally with CMake, the `test` directory exists, so it will build the tests. When building the package, it does not include the test directory, so it does not (cannot) build them.

**Comment by omeralon6746** [comment] 2024-05-22 06:59
> Hi @Holt59
> 
> Thanks for your question.
> 
> I think the issue is a small misunderstanding of the `test()` method. It is exclusively intended for the `test_package/conanfile.py` to test the package is correct, but not to run unit-tests. In regular recipes like this one, the `test()` method is never called.
> 
> The correct syntax is adding it in the `build()` method as:
> 
> ```python
> def build(self):
>         cmake = CMake(self)
>         cmake.configure()
>         cmake.build()
>         cmake.test()
> ```
> 
> The definition of the `tools.build:skip_test=True` will inhibit the building of the test, and it will also inhibit running the tests, but if I understood correctly, this is already working fine for you?
> 
> So the answer to the question, is that defining ``tools.build:skip_test=true```avoids building the tests, which is what you want, isn't it? I am not sure if I am missing something, please let me know.

@memsharded 

Are you sure skip_test=True will inhibit the building of the tests? maybe it depends on the build system (I'm using meson)?

On meson.build when building test executable, I just use the executable() method and then the test() method.

on the conanfile I call meson.build() and meson.test().

When invoking `conan build . -c tools.build.skip_test=True`, the tests aren't running but the test binary is indeed built.
Is there a clean conan-way to prevent the test executable building?

**Comment by memsharded** [comment] 2024-05-22 08:14
This is the code of ``Meson.test()``:

```python
    def test(self):
        """
        Runs ``meson test -v -C "."`` in the build folder.
        """
        if self._conanfile.conf.get("tools.build:skip_test", check_type=bool):
            return
```

It seems:

- You are misspelling the ``conf``, it is not ``tools.build.skip_test``, but ``tools.build:skip_test```, note the ":"
- You are using Conan 1, if you were using Conan 2, it will detect the misspelled ``conf`` and give you an error?

It is true that apparently in Meson there is no standard way of inhibiting the build of tests, so this should be something manual in the recipe. If you are aware of some standard way of doing that, please create a new ticket and we will add it
