### ISSUE TITLE
[bug] Package not found when using Compiler Any

### ISSUE THREAD

**Issue by crazydef** [conan-io/conan#8676] opened 2021-03-19 15:50 UTC
Hi,

I've recently been setting up Conan with our Azure DevOps based build system.  Everything has gone through (relatively) smoothly on Windows, but I've hit a road block on our Linux builds.

On Linux we don't generally care whether a library has been built with GCC or Clang, as long as they're using the same runtime library (libc++ Vs libstdc++).  I couldn't figure out how to set this up in the settings for the consumer, so I decided to work from the other end and remove `[compiler]` from the conanfile settings when building the package (we have full control over all build processes so at this stage it seemed like the easiest option):

`settings = "os", "build_type", "arch"`

So now on our JFrog server I have a package uploaded with the following properties:

![image](https://user-images.githubusercontent.com/22217579/111804161-1ad9f980-88d0-11eb-97c3-71430f63b22e.png)

However, Conan is unable to resolve this when attempting to fetch the package:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

libjpeg/9.3@3dv/stable: Not found in local cache, looking in remotes...
libjpeg/9.3@3dv/stable: Trying with 'CogsDev'...
Downloading conanmanifest.txt
Downloading conanfile.py
libjpeg/9.3@3dv/stable: Downloaded recipe revision d6eb47ebfa8b1fc8fd5aa96ec4744893
Installing package: libjpeg/9.3@3dv/stable
Requirements
    libjpeg/9.3@3dv/stable from 'CogsDev' - Downloaded
Packages
    libjpeg/9.3@3dv/stable:24647d9fe8ec489125dfbae4b3ebefaf7581674c - Missing

Installing (downloading, building) binaries...

ERROR: Missing binary: libjpeg/9.3@3dv/stable:24647d9fe8ec489125dfbae4b3ebefaf7581674c
libjpeg/9.3@3dv/stable: WARN: Can't find a 'libjpeg/9.3@3dv/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86_64, build_type=Release, os=Linux
- Options: 
- Dependencies: 
- Requirements: 
- Package ID: 24647d9fe8ec489125dfbae4b3ebefaf7581674c

ERROR: Missing prebuilt package for 'libjpeg/9.3@3dv/stable'
```

Am I missing something blindingly obvious here?

**Comment by memsharded** [comment] 2021-03-19 20:20
Hi @crazydef 

The key is this line: 
```
libjpeg/9.3@3dv/stable: Downloaded recipe revision d6eb47ebfa8b1fc8fd5aa96ec4744893
```
As you can see, this is installing a different revision than the one that you are displaying in Artifactory. 
Whenever you change something in the recipe, or the source code, a new recipe revision is generated, and requires to build new binaries for it. It seems that you modified things, but didn't rebuild binaries, please check that. It is possible that one of the things that could produce this unexpectedly is different line endings CRLF in different systems (specially Windows). Make sure to use always the same one (.gitattributes in the repo helps).

Let me know if this helps, thanks!

**Comment by crazydef** [comment] 2021-03-22 10:31
Before I rebuild libjpeg, I'm deleting all existing revisions from the server.  So the only versions present are the latest.  (Debug and Release.)  Basically the revision hashes displayed in the above image are the only revisions available.

I don't think the line endings should be affecting anything.  I'm both building and consuming the library on Linux (both DevOps hosted build machines).  (And if that is the problem I would argue that's a bug in Conan - choice of line endings shouldn't make any difference to how an application behaves.)

Perhaps you can explain where the recipe revision (d6eb47ebfa8b1fc8fd5aa96ec4744893) that it can't find is coming from?  There is clearly no revision with that hash on the server.

To clarify, I delete all revisions from the server.  Rebuild the libjpeg packages.  And then attempt to consume them in a different DevOps hosted build (on a machine that should be a clean OS image for every build).

**Comment by memsharded** [comment] 2021-03-22 10:45
By the way, I wanted to clarify, there are other means besides erasing the compiler info. For example you can force the settings per-package if you want, lets say that you build it with clang:

```
[settings]
compiler=gcc
compiler.version=6.1
libjpeg:compiler=clang
libjpeg:compiler.version=7.2
....
```

I am not sure about that revision, but it is clearly coming from the server. Don't you have any server setup, like a virtual repository, aggregating a remote repository, or any other configuration, so that revision could be coming from it?
Can you make sure that at the first level (not the package_id, just below ``libjpeg/9.3/stable`` there is not such a folder? Can you please collapse the first level and double check? Thanks!

**Comment by crazydef** [comment] 2021-03-22 10:54
Here's the complete hierarchy for that library:
![image](https://user-images.githubusercontent.com/22217579/111978856-ae940b80-8b04-11eb-89d9-1ee94f7ec19f.png)

The revisions with three packages in them are for Windows (with three build configurations).  There are two top level revisions because new ones keep being created when I push changes to the git repository and I've stopped cleaning them out for now.

The other revision (the one in the middle with two packages) are the Debug and Release linux builds.

When trying to use libjpeg, it's still trying to fetch a non-existent package:

```
libjpeg/9.3@3dv/stable: Downloaded recipe revision 1aa4e1e7c453fb8c4c4b657e756803df
Installing package: libjpeg/9.3@3dv/stable
Requirements
    libjpeg/9.3@3dv/stable from 'CogsDev' - Downloaded
Packages
    libjpeg/9.3@3dv/stable:8e6304b6ad31b530c81dcec12707f6abe98f2a1f - Missing

Installing (downloading, building) binaries...

ERROR: Missing binary: libjpeg/9.3@3dv/stable:8e6304b6ad31b530c81dcec12707f6abe98f2a1f
```

(Note:  I've gone the other way now and am forcing clang 10 into the packages when I'm creating them.  I'm not using Conan to build anything - I'm just packaging prebuilt binaries.)

**Comment by memsharded** [comment] 2021-03-22 16:47
Hi @crazydef 

I think there is some misunderstanding with the revisions. Revisions are implicit versions. Consider it as an addition to the explicit version. But every revision it is a completely different entity.

When you build packages for Linux, Windows, and other configurations, you should build all of them with the same revision. Consider the equivalent of building 3 binaries for Windows for ``libjpeg/9.3.rev1``, then 2 binaries for Linux for a different thing called ``libjpeg/9.3.rev2``, and finally 3 more binaries for Windows for ``libjpeg/9.3.rev3``. Whenever you are doing one install, a given recipe revision will be resolved first. Then binaries will be fetched from that revision.

When a recipe or source changes, the binaries for those changes (revision) should be built. The previous binaries built from previous revisions are no longer valid, because they belong to different original sources. Please make sure you do not change recipe or sources while moving from one platform to another to build binaries.

Please let me know if this clarify how revisions work. Thanks!

**Comment by crazydef** [comment] 2021-03-25 11:54
I am building all packages from the same source code.

I build on Windows and Linux from the same repository, and get two revisions at the root of the package tree.  I build them again (from the exact same source code) and I get new packages appearing in lower levels of the tree:

![image](https://user-images.githubusercontent.com/22217579/112468890-18acea80-8d69-11eb-944f-b1286af78584.png)

(And when I have more than one package deeper in the tree, Conan fails to fetch any of those versions and so I have to delete them all and rebuild from scratch.)

**Comment by memsharded** [comment] 2021-03-25 13:19
> I build on Windows and Linux from the same repository, and get two revisions at the root of the package tree. I build them again (from the exact same source code) and I get new packages appearing in lower levels of the tree:

This happens when there is something else, like git checkout different CRLF in Windows and Linux. That means that the source code is not exactly the same, they are different files, with different characters inside, even if it is the same commit, and they produce different revisions. It is very important to check that, and a nice solution is using ``.gitattributes`` in the repo, to make sure the line endings are always the same. Could you please check that? Thanks!

**Comment by crazydef** [comment] 2021-03-25 13:35
Then that's a bug in Conan.  Software shouldn't produce different results based on line endings of text files.  :)  If you're hashing files to determine content, you should be stripping all white space and hashing the actual content of the file.

I can try to work around this with .gitattributes, but it should really be fixed properly in my opinion.

Which files are used for generating these revision numbers?

**Comment by memsharded** [comment] 2021-03-25 14:21
> Then that's a bug in Conan. Software shouldn't produce different results based on line endings of text files.

I wish this were true :)

We have seriously consider this, and actually I have implemented this. And it was a nightmare. Let me give one example: User ``exports_sources="Instructions.txt"``. That is a text file with the app instructions. Conan strips all line endings and computes revision=rev1. Now user realizes this is horrible, the app is printing all the instructions as a single line, because they did a mistake and the file should have had CRLF instead of LF. Now they fix the file to have the correct line endings, but Conan keeps generating exactly the same revision, and as it is the same revision, it skips building binaries, so nothing gets fixed.

We have also had problems with different line endings in build systems scripts that are picky about those line endings (spaces, tabs, etc). 

It could be argued that Conan needs a mechanism to define which files have which line endings and needs to be normalized and which not. That would end in a poor, incomplete implementation of the git crlf management.

So software definitely produces different results depending on different line endings, and this is the reason Conan should and will not try to be smart about those line endings, specially when this is already brilliantly implemented in the tool that is managing those files in the first place (git).

**Comment by crazydef** [comment] 2021-03-25 14:42
To be honest, that sounds way better to me.  :)  I would much prefer explicit versioning as specified in the conanfile.  If I haven't changed the version number, the old package just gets overwritten.  (As long as there's a way to force an upload and overwrite.)  That's essentially what I have right now anyway.  At the moment, I'm just packaging third party libraries for our build scripts to consume and I really don't care or want multiple revisions of each one.  (Which is why I'm currently having to go in and delete everything before a new build takes place.  Once everything has been setup initially, *then* I can just rely on updates to the version number to control newer builds of a library.)

Similarly for packages being consumed by another application I'm involved in, there's only ever going to be a single revision for each version because those version numbers are tightly controlled and updated for each release.

Revisions (in my mind) are just an extra layer of complexity trying to solve the problem of lazy developers.  Which is an impossible problem to solve.  :)

**Comment by memsharded** [comment] 2021-03-25 15:37
> Revisions (in my mind) are just an extra layer of complexity trying to solve the problem of lazy developers. Which is an impossible problem to solve. :)

We also thought the same, and for the last 5 years, this has been the default mode, not using revisions. But in this time we have  learnt a lot not only about lazy developers, but the whole devops world and some known best practices in package management in other ecosystems that have been more mature than C/C++. One of them is package immutability by default. It is not only about developers being lazy, but also about human errors that will happen sooner or later, machine errors that will happen sooner or later, and about the possibility of being more efficient, rebuilding only when necessary but at the same time being certain that you won't skip rebuilding something that is necessary to rebuild (which is basically achieved with ``default_package_id_mode=recipe_revision_mode``). 

Note that without using revisions, the above case of different CRLF in different systems translates to a ``package binary outdated`` problem, and results in package binaries being marked as outdated with respect to the recipe, which means: "I have a binary here that I don't know how it was build, I won't be able to rebuild it again" and that had mechanisms like ``--build=outdated`` to mitigate, which all of it is basically delaying the enforcement of consistency guarantees.

I agree that it adds some complexity for some cases, but as always in SW engineering, everything "depends" and everything is a trade-off. In this case we have decided to go for the immutability and reproducibility of using revisions (and this will be hardcoded in Conan 2.0, it has been already discussed with the tribe (https://conan.io/tribe.html)), even if it adds some complexity, is a better solution for a majority of cases and users.

**Comment by crazydef** [comment] 2021-03-26 12:30
Yeah, I realise I'm not going to change anybody's mind here.  But that never stopped me from having a good old grumble in the past.  :)

Anyway, back to the problem at hand...  I finally had time to revisit this, and can confirm setting up .gitattributes to force conanfile.py to always use LF does indeed fix the issue.

At least, it's fixed one of the issues.  I suspect the remaining problems, though, are all my own doing.  :)

**Comment by memsharded** [comment] 2021-03-26 13:46
> Yeah, I realise I'm not going to change anybody's mind here. But that never stopped me from having a good old grumble in the past. :)

We change our minds often, but in many cases too, we also have a lot of scars of having been there many times in the past, tried different things, struggled, going back and forth...  But even in the case we would not change our mind, the feedback is very welcomed, we really need to hear that too, so please keep coming those good old grumbles! :) :) :) 

> Anyway, back to the problem at hand... I finally had time to revisit this, and can confirm setting up .gitattributes to force conanfile.py to always use LF does indeed fix the issue.

Great to know, happy that it is solved.

> At least, it's fixed one of the issues. I suspect the remaining problems, though, are all my own doing. :)

Ok, then I think we can close this issue at this moment, but please let us know if you have any further questions or issues. Thanks!

**Closed as completed by memsharded** 2021-03-26 13:46 UTC
Labels: stage: triaging
