### ISSUE TITLE
`conan create` doesn't always get a fresh copy of the source

### ISSUE THREAD

**Issue by liberforce** [conan-io/conan#3084] opened 2018-06-21 09:14 UTC
I had modified the conan recipe for googletest to fetch a branch of my own fork of googletest, and tried to compile it with `conan create`. The build failed because of C++ syntax errors on the code I had changed, so I changed the source, commited the changes, and pushed the code. 

However, when running `conan create` again to generate a package from my modified version of googletest, I realized that it wasn't fetching the newest sources. Of course, I wasn't using `--keep-source` nor `--keep-build`. This is what I tried:

- changing the sources on the git repo again → didn't work
- changing the timestamp of the recipe by editing it, adding a character then removing it, then saving the file → didn't work
- adding some dummy code to the recipe so it has a new checksum → worked !

This is a problem. Even if the recipe didn't change, it may depend on a repository whose code has changed. By not using any `--keep-*` option, I expect the source to be cloned everytime, not just when the recipe changes, otherwise it completely breaks a continuous integration flow.

Using Conan 1.4.4 on Windows 2016 Server

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment] 2018-06-21 09:37
Hi @liberforce and thanks for reporting.

As described in the [package development flow](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html),
`conan create` is one of the last steps to be done when creating a new package for your library.

Not fetching sources every time you do `conan create` is an optimization for large source code downloads that make the creation process slow.
Normally source code retrieval in the recipe will be fixed to a specific git commit or version download.
Checking out a branch is not a good practice if you want to reproduce the package creation and not recommended for CI flows.

I agree this might not be very intuitive at the beginning but I consider the fact of assuming that sources has not changed if recipe didn't change is quite reasonable.

**Comment by liberforce** [comment] 2018-06-21 11:32
> Not fetching sources every time you do conan create is an optimization for large source code downloads that make the creation process slow.

This need is already covered by `--keep-source`.

Forcedly fetching the sources is not. If an optimization is needed, you should provide a way to `git clean` and update the sources instead of cloning. If you're afraid people with large source codebase do a mistake, then don't clean by default and add something like `--update-source` or `--no-keep-source` option, but you can't expect people to change their recipe when only the source changed.

> Checking out a branch is not a good practice if you want to reproduce the package creation and not recommended for CI flows.

You can't put a specific commit in a recipe if you're trying to do CI either, unless you use a templating system to change the recipe on-the-fly. I'd very much prefer conan freezing the revisions for me as that's a very common use case. And that's what it starts doing with the SCM helper.

> I agree this might not be very intuitive at the beginning but I consider the fact of assuming that sources has not changed if recipe didn't change is quite reasonable.

I disagree here. A recipe should change as infrequently as possible, to avoid unnecessary work. It should be modified only if _what_ is done changed (dependencies or imports), and not on what it  applies. When the package is built successfully, the exported recipe should contain the commit that was used.

**Comment by memsharded** [comment] 2018-06-21 14:10
> This need is already covered by --keep-source. Forcedly fetching the sources is not.

Not really. The ``--keep-source`` is to not remove the sources even when the recipe is changing, and doing the export.

> If an optimization is needed, you should provide a way to git clean and update the sources instead of cloning. 

If you don't need the "caching" of the source, the answer is very simple. Do the thing directly in the ``build()`` method. The logic and semantics of the ``source()`` method is exactly that: it will only run once, for all the builds, and it will cache the sources, unless something change in the recipe. We did not invent this behavior: it was the desired behavior and flow users wanted from very early in conan, and so far hasn't been a problem, for most users, it is the way they want it to be. There are other things that needs improvement, and we keep working and iterating on them, like the SCM feature. But this behavior is not one of them.

> A recipe should change as infrequently as possible, to avoid unnecessary work. It should be modified only if what is done changed (dependencies, imports, etc.), and not on what it applies.

This is how you think things should be. Many other users are doing frequent changes to their recipes, while their create their recipes, and not touching the code at all. Maybe, if you are doing several builds and rebuilds in the local cache, with sources changes, etc., that could mean that you need to use the developer flow instead.

**Comment by liberforce** [comment] 2018-06-21 16:41
> The `--keep-source` is to not remove the sources even when the recipe is changing, and doing the export.

```
 -k, -ks, --keep-source
                        Do not remove the source folder in local cache. Use
                        this for testing purposes only
```

This doesn't mention changes in the recipe. The good semantics behind `--keep-source` that were self-explanatory now feel clunky with such exceptions to the rule. You should not have to think to the implementation to know how something works, the interface should be enough.

> If you don't need the "caching" of the source, the answer is very simple.

I need the caching too. The caching makes sense when fetching a tarball or a tag of a big library, like boost. It's just that when I need the caching, I can use `--keep-source`, whereas currently I'd need to delete the source by hand.

>  Do the thing directly in the build() method.

Again, getting sources in something called `build()`, when there's already a method called `source` to get the sources feels wrong. I know we already had this talk about the unit tests, but if `build()` is about making the package, then you have a `source()` method because those are different things.

Words have a meaning, and if you change their meaning to fit some other purpose, it increases the learning curve as it paves the way for incomprehension between people trying to communicate on how to use your product. I know I may look annoying and nitpicking on this stuff, option names, method names, etc., but that's because it helps making a tool that is easy to use.

> This is how you think things should be. Many other users are doing frequent changes to their recipes, while their create their recipes, and not touching the code at all.

Sure, that's a frequent use case too. But when doing CI, you also need to produce packages when the source changed and the recipe did not. You need to perform incremental builds whenever possible, because you want the latest version of every component. You need to follow reverse dependencies to rebuild the whole stack if a low level package changed.

Sure, I could pre-process the recipe to change the commit hash when the source has changed, leading to `source()` getting the source for me, but that looks ugly to me, as conan already knows about the source, and the `source()` method has so much flexibility that it would be a PITA to make sure all the recipes are written the right way for this to work.

> Maybe, if you are doing several builds and rebuilds in the local cache, with sources changes, etc., that could mean that you need to use the developer flow instead.

About the "developer flow", the main flow advertised  in the documentation is called the [local development flow](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html), I suppose that's what you're talking about. 

Now the problem is that it gives a link to the bincrafters blog, and I had already read their articles about the packaging flows. Their last blog post about it talks about the [Conan Package Flow](https://bincrafters.github.io/2018/02/27/Updated-Conan-Package-Flow-1.1/). Which uses `conan create` all the way, and recommends that for out-of source packaging, which is what I started doing after reading that post.

But this seems in contradiction with what the [documentation](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html) says:

> The local workflow encourages users to do trial-and-error in a local sub-directory relative to their recipe

What I understand is that the bincrafters [changed their workflow](https://bincrafters.github.io/2017/11/10/Updated-Conan-Package-Flow/), then [changed back](https://bincrafters.github.io/2018/02/27/Updated-Conan-Package-Flow-1.1/). Both workflows are very different, however conan documentation only link to the root of the blog, making the different flows and when using them is relevant unclear. I chose the one fitting out-of-tree, because I'm just evaluating conan for now, and that seamed less intrusive.

I suppose what you call "developer flow" is what is explained in the rest of that documentation page, and corresponds to what bincrafters advertised for [in-source packaging](https://bincrafters.github.io/2017/11/10/Updated-Conan-Package-Flow/). I'll see if that fits my needs. I'm not sure however, as I wanted to use the local repository as a cache to make incremental builds easier.

Last remark about the worflows: giving them a formal name, sharing that with the bincrafters, and using the names consistently would make things clearer. I may not be the only one having a hard time taming the beast on using Conan with CI.

**Comment by solvingj** [comment] 2018-10-12 23:56
I agree with @liberforce point here, particularly with recipes which have conventional `source()` methods or `exports_sources`.  With regard to the `scm` feature, I think that specifically tries to intelligently cache and that seems fine to me, so my comment here does not apply to that. 

I was surprised at some point when Conan behavior changed so that `source()` method is not executed every time by default.  The reason we proposed the `--keep-source` method on the `conan create` command was because, at that time, `conan create` on a recipe with a `source` method always wiped out my sources and got them fresh every time, there was no caching.   I didn't know other users were asking for `source` to be implicitly cached, and I missed the notice that the behavior changed. 

I also agree that what we have now is a mismatch.  We have a mechanism for the user to control this behavior, but that mechanism is a `--keep-source`, and now implicitly keep source, and don't have a mechanism to `--clean-source`.   

This is a problem for me personally in enterprise packaging.  We're currently using out-of-tree builds because indeed it's less intrusive and the local-development flow doesn't make sense to me.  During trial-and-error, i want my builds cleaned and i have to do `conan remove` to get rid of them. The good news is that the Conan team has said they are aware of these and other related challenges, and are actively working on them.  My hope is that SCM will solve this problem for us.  I haven't gotten to give it a good try yet because we're on SVN.  Hopefully soon.

**Comment by AndreyMlashkin** [comment] 2020-06-30 06:33
I have an option "Branch" in my recipe, which is used in source method. Of course with the new caching behavior, this feature may not work, as all options used in source (). This does not feel right and is not reflected in documentation.

**Comment by memsharded** [comment] 2020-06-30 10:52
Hi @AndreyMlashkin 

Let me clarify: Use of settings and options in the ``source()`` method is deprecated. CONAN_V2_MODE will raise an error for them. It will soon be removed. Whatever is in the ``source()`` method should be completely generic to all different settings, options and configurations. Whatever is specific for a branch or configuration should be managed in the ``build()`` method.

It is clearly explained in the documentation with a note highlighting it:
https://docs.conan.io/en/latest/reference/conanfile/methods.html#source

**Comment by memsharded** [comment] 2023-08-25 11:07
This was solved some time ago, with revisions in 1.X, and also restricting variability in the ``source()`` method. Closing this ticket, thanks for the feedback, don't hesitate to open new tickets as necessary, thanks!

**Closed by memsharded** 2023-08-25 11:07 UTC
