### ISSUE TITLE
Optimize CompleteFlowTest

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#4230] opened 2019-01-05 01:23 UTC
That test is slow, it builds some things.
It is parameterized:

```python
    @parameterized.expand([(True, ), (False, )])
    def reuse_test(self, complete_urls):
        test_server = TestServer(complete_urls=complete_urls)`
```
Taking 2 x 20 secs (Windows) to run.

I would say that such ``complete_urls`` is a detail of the TestServer, could probably be tested somewhere else, in a fast test instead, and leave this simplified to just one server configuration.

**Comment by lasote** [comment] 2019-01-08 07:54
This is a task, the issue is defined enough to be in the queue, not in triaging, as it doesn't require special attention until it is assigned to a release. Move it again to triaging to be able to assign it to me is a trick ;)

**Comment by memsharded** [comment] 2019-01-08 09:44
No, that wasn't my intent. When I realized that I really didn't fully understand the ``complete_urls`` in the server, I wanted you to triage if this was an issue, probably it wasn't.

**Comment by lasote** [comment] 2019-01-08 10:36
Ok!. So I investigated a little. That parameter is to simulate the [host_name](https://docs.conan.io/en/latest/uploading_packages/running_your_server.html?highlight=host_name) from the server, it is not recommended since 1.1. because the server is able to return relative paths that are enough for the client.

So yes, It could be tested somewhere else where it is not building real stuff.  We could even deprecate this as a valid server configuration, but better to wait to 2.0, no rush. I'll create another one for that.

**Closed** 2019-01-08 15:19 UTC
Labels: complex: low, priority: medium, stage: review, type: engineering
