### ISSUE TITLE
[bug] conan upload --list errors on empty recipe list

### ISSUE THREAD

**Issue by n-morales** [conan-io/conan#14203] opened 2023-06-30 14:40 UTC
### Environment details

* Operating System+version:
Manjaro Linux 23.0.0

* Compiler+version:
N/A

* Conan version:
Conan version 2.0.7

* Python version:
Python 3.11.3

### Steps to reproduce

1. Create a list file as follows (can be generated from something like `conan list --graph install_graph.json --graph-binaries build --format json`)
```json
{
  "Local Cache": {}
}
```
2. conan upload --remote foo --list list.json
3. Conditional check fails: https://github.com/conan-io/conan/blob/release/2.0/conan/cli/commands/upload.py#L84-L85

Note that I believe this should work since some automation workflows in CI may result in an empty list if a specific package was just cached and `--graph-binaries build` is set in the list command. I think the conditional check listed below should probably only error if the `--list` argument was not provided.

### Logs

```
$> conan upload --remote foo --list list.json
ERROR: No recipes found matching pattern 'None'
```

**Comment by AbrilRBS** [comment] 2023-06-30 15:41
Hi @n-morales, thanks a lot for your report and taking the time to diagnose the error!

What you describe seems like a valid use case to me, if you would like to contribute a PR now that you have checked the code, we can discuss it there, but no worries if not :)
(I can't promise it would get merged if the team thinks otherwise of the error, but the discussion is at least worth having, so thanks for bringing it up!)

**Comment by memsharded** [comment] 2023-07-03 23:27
I think that for automation purposes, allowing an empty list makes sense. So this could be changed, and relaxed for the ``--list`` argument. It sounds that an info/warning message would be useful, I'd add it too.

So @n-morales would you like to contribute it as you as @RubenRBS suggested? Otherwise, please tell us and we will do it, no problem at all. Thanks!

**Comment by n-morales** [comment] 2023-07-03 23:29
@RubenRBS @memsharded I could do it -- do you have suggestions for where I should be putting a unit test for it?

**Comment by memsharded** [comment] 2023-07-03 23:38
Probably https://github.com/conan-io/conan/blob/release/2.0/conans/test/integration/command_v2/test_combined_pkglist_flows.py#L9 is the best, as it contains other ``upload --list`` tests. But no need to reuse the fixture with previous data,

**Closed as completed** 2023-07-09 23:37 UTC
Labels: stage: triaging

**Comment by johnmcfarlane** [comment] 2026-07-22 08:37
Hi, quick follow-up. 

What if `conan upload --remote my-repo '*'` is issued when there are 0 recipes that match? I'm seeing this in my own automated workflow. The program is special-casing 0 here and failing a command that worked exactly as intended. I see no flag to work around this. In my case I get an almost-identical message:

> ERROR: No recipes found matching pattern '*'

It appears that the program is trying to be helpful, but in an effort to make things easier, it is introducing complexity and incorrectness. Is it worth opening a separate issue? Thanks

**Comment by memsharded** [comment] 2026-07-22 09:34
Yes, it might be better to create a new separate issue, as this one is closed.

> What if conan upload --remote my-repo '*' is issued when there are 0 recipes that match? I'm seeing this in my own automated workflow. The program is special-casing 0 here and failing a command that worked exactly as intended. I see no flag to work around this. In my case I get an almost-identical message:

Please elaborate a bit more about this. You mean applying that command on a completely blank cache? Nothing was installed, nothing was created? Why the pipeline would try to upload over that empty cache? Or is it a shell expansion issue, because the quotes should be double quotes, use ``"*"`` instead of ``'*'``?

**Comment by johnmcfarlane** [comment] 2026-07-22 12:29
> Yes, it might be better to create a new separate issue, as this one is closed.

Thanks. I'll do that.

> Why the pipeline would try to upload over that empty cache?

In the case that the number of packages built was _N_, then _N_ packages would be uploaded. On occasion, _N_ might be zero.

> Or is it a shell expansion issue, because the quotes should be double quotes, use "*" instead of '*'?

`'*'` and `"*"` both yield the same result, when run from the script, or from a bash prompt.
