### ISSUE TITLE
[question] Is modifying properties of a dependency allowed/supported? Where should it be done?

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#12357] opened 2022-10-21 00:32 UTC
I'm creating conan recipes for external projects. So it would be nice to avoid patches where I can.

A certain project I'm packaging uses names for the CMake modules that are different then conan's default.
It uses `jansson` as a dependency, which does not set a certain `cmake_file_name`.
Because of this, conan will generate `janssonConfig.cmake`, generating the `jansson::jansson` target.
But the projects expect `JanssonConfig.cmake`, creating `Jansson::Jansson` (the project contains a `FindJansson.cmake` module.

In the recipe, I can fix this by donig:
```python
    def generate(self):
        if self.options.with_jansson:
            self.dependencies["jansson"].cpp_info.set_property("cmake_file_name", "Jansson")
            self.dependencies["jansson"].cpp_info.set_property("cmake_target_name", "Jansson::Jansson")
            self.dependencies["jansson"].cpp_info.set_property("cmake_module_file_name", "Jansson")
            self.dependencies["jansson"].cpp_info.set_property("cmake_module_target_name", "Jansson::Jansson")
        deps = CMakeDeps(self)
        deps.generate()
```

But it's not clear to me whether this is allowed by conan.
Also, I hope this modification of the jansson properties remain local to my recipe, and won't bubble out to dependencies.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-10-21 07:52
Hi @madebr 

This has been documented in: https://docs.conan.io/en/latest/reference/conanfile/dependencies.html

> All the information is read only. Any attempt to modify dependencies information is an error and can raise at any time, even if it doesn’t raise yet.

It is true that Conan hasn't implemented defensive measures to avoid it, but it could do it at any time. This behavior will never be allowed, because it opens the door to a whole set of problems like conflicts (2 or more different packages competing for changing the same value of a common dependency).

**Comment by madebr** [comment] 2022-10-21 13:52
Thanks for pointing me to the documentation.

Though, I think modifying properties for specific projects is useful, just make sure the change remains local.
Perhaps provide projects with objects that are copy-on-write?

When packaging external projects, this possibility is useful to avoid patches.
See https://github.com/conan-io/conan-center-index/pull/13650 where I did this to avoid patches/`replace_in_file`.

**Comment by memsharded** [comment] 2022-10-21 14:48
> Though, I think modifying properties for specific projects is useful, just make sure the change remains local.
Perhaps provide projects with objects that are copy-on-write?

While you see it as changes remaining locally, tons of users will read that code as actually modifying the dependency property (or any other attribute, including includedirs, name, version, license... tons of things are exposed in this interface), and expecting it to behave like that. I don't think this is something to be addressed with some code to allow it, I think this is architectural, and dependencies information should be always strictly read-only

> this possibility is useful to avoid patches.

I think this is still more dangerous than beneficial, if the consumer is wrong, then it needs to be fixed. Otherwise, it would be the equivalent of hot fixing a dependency library by applying a binary patch on the library binary, instead of submitting a patch to the library source code. Because it also needs to be viral, it is not only that ``self.dependencies["libmicrohttpd"].cpp_info.set_property("cmake_file_name", "MHD")`` is added to your project, but it would also be needed to the dependants on your project.

**Comment by madebr** [comment] 2022-10-21 15:22
> While you see it as changes remaining locally, tons of users will read that code as actually modifying the dependency property (or any other attribute, including includedirs, name, version, license... tons of things are exposed in this interface), and expecting it to behave like that. I don't think this is something to be addressed with some code to allow it, I think this is architectural, and dependencies information should be always strictly read-only

People should read the code as modifying the properties of the dependencies, not modifying something globally.
You should of course be careful with what properties you modify.
Even modifying the version might be useful when some project expects a different version scheme (a far stretch, but possible).

> I think this is still more dangerous than beneficial, if the consumer is wrong, then it needs to be fixed. Otherwise, it would be the equivalent of hot fixing a dependency library by applying a binary patch on the library binary, instead of submitting a patch to the library source code. Because it also needs to be viral, it is not only that `self.dependencies["libmicrohttpd"].cpp_info.set_property("cmake_file_name", "MHD")` is added to your project, but it would also be needed to the dependants on your project.


When the consumer is wrong, then nothing will break.
Because the consumer itself uses the wrong name, it will keep working.
Other dependencies in the build tree will still use the original name.
Dependants of the "incriminating" recipe will also see the original name.
Because the changes are local, dependants will see the original properties and `CMakeDeps` will use the original names.

You're right this feature potentially being used for "hot-fixing" dependency information. But bad code always exists.

In libmicrohttpd's case, no official cmake config files are made available
So it's the wild west for its dependencies.
You can't expect projects to conform to conan's assumption that projects should use `libmicrohttpd` as `find_package(libmicrohttpd)`.

We have 2 choices: patch the sources or patch conan's dependency information.
I believe patching conan's information is the easiest and user friendliest way to do this.
In either ways, the change remains local.

**Comment by memsharded** [comment] 2022-10-21 16:30
I think there is a third choice (thanks @jcar87!), that would be much better: if the problem is that we want to allow recipes to patch the behavior of the target names or some other property while generating cmake files, the interface should clearly express that intention, so something like:

```python
def generate(self):
    cmake = CMakeDeps(self)

    cmake.name_alternatives["jansson"] = "Jansson" # overrides the name of the generated files to this
    cmake.target_aliases["jasson::jansson'] = ["Jansson::Jansson"] 
```

This satisfies all needs:
- The changes are clearly and naturally local, they only apply to a local object
- There is no risk of destroying upstream data information

**Comment by madebr** [comment] 2022-10-21 16:42
Yes, applying the changes to `CMakeDeps` makes more sense.
As we want to only change the output files of `CMakeDeps`, and not the dependency tree.

**Comment by memsharded** [comment] 2022-10-21 18:54
Ok, then I think we can close this question, responded as no, modifying dependencies information is not allowed, and we can spin a new ticket for this CMakeDeps configuration

**Closed as completed by memsharded** 2022-10-21 18:54 UTC
Labels: type: question
