### ISSUE TITLE
[bug] Conanfile self.dependencies.items() is empty when overriding versions in the top package.

### ISSUE THREAD

**Issue by devlpr** [conan-io/conan#16339] opened 2024-05-24 23:50 UTC
### Describe the bug

conanfile.dependencies.items() is empty if I override versions in the top level conanfile.py. When I do not override, the list is populated and I can iterate the dependencies just fine.

### How to reproduce it

```
def requirements(self):
        self.requires("sdk/0.2.3@ai/release", override=True)
        self.requires("clock-synchronizer/1.0.4@ai/release", override=True)
```
 Obviously your package names will be different, but it doesn't seem to matter.

Then check the dependency list. 

`        print("CONAN DEPS SIZE IS", len(self.dependencies.items()))
`

I am in Conan 1.64. The reported size of the above is zero when we override packages. 

We are moving to Conan 2 as fast as we can, but it's a lot of work because we have a lot of packages.
Is there some workaround or patch you can provide to get us through until we get to Conan 2? Right now this is really a deal-breaker for us.

**Comment by memsharded** [comment] 2024-05-25 19:13
Hi @devlpr 

Thanks for your report.

I am not sure this is a bug, but intended and expected behavior. The ``override=True`` are not real dependencies, they are just a definition of a version change upstream, but it doesn't create a direct dependency from the caller to the required package. 

I am not sure why this would be a problem, if you can please elaborate. This has worked always the same in Conan 1 and Conan 2, the behavior is exactly the same, so I don't fully understand why this would be a problem in the upgrade.

**Comment by devlpr** [comment] 2024-05-26 04:32
We have not moved to Conan 2 yet. This is in Conan 1. The problem is that when we go to release, we run some operations on each package. When overriding versions, the list is empty, so we can't do those operations. So we can't use overrides. But sometimes we can't resolve versions, so we need overrides. It's a catch 22.

I think our expectation of an override is that the dependency tree is walked and when an overridden package is found, it simply uses the version in the override. It's overriding a dependency. So even if the override itself isn't a real dependency the actual dependencies should still act the same. By overriding, we aren't removing them. But that is how it's acting currently.

**Comment by memsharded** [comment] 2024-05-26 16:39
Then if I understood correctly what you want is:

```
def requirements(self):
        self.requires("sdk/0.2.3@ai/release", force=True)
        self.requires("clock-synchronizer/1.0.4@ai/release", force=True)
```
This will work both in Conan 1 and Conan 2, overriding the upstream dependencies versions in both cases and being a direct dependency and listed in ``self.dependencies`` in both cases. Can you please give it a try and let me know?


An extra recommendation, just in case: overrides and forces are recommended only as temporary workarounds to upstream conflicts and version issues in the graph. The recommended and stable approach is to fix those issues in the recipes upstream

**Comment by devlpr** [comment] 2024-05-26 21:00
Interesting. I will try this ASAP. I don't think we tried this yet. Thank you for this. If it works I owe you a beer!

As for overrides and forces, it's a long story how we got here, but I will say that we know better and we are trying to remedy our situation as soon as possible. With that fix, we are moving to Conan 2 so we can pick up the latest and greatest, and perhaps even contribute if needed.

**Comment by memsharded** [comment] 2024-05-26 22:06
> Interesting. I will try this ASAP. I don't think we tried this yet. Thank you for this. If it works I owe you a beer!

Always happy to help, just keep me posted, if this works that is the best for me too :)

> As for overrides and forces, it's a long story how we got here, but I will say that we know better and we are trying to remedy our situation as soon as possible. With that fix, we are moving to Conan 2 so we can pick up the latest and greatest, and perhaps even contribute if needed.

One of the cool features in Conan 2 is the new ``[replace_requires]`` that also allows to temporarily fix conflicts without modifying ``conanfile.py`` recipes, so after fixing the upstream issues, it is not necessary to change the recipes again.

**Comment by devlpr** [comment] 2024-05-31 06:53
Ok, it didn't really work for us. It seems like the use of version ranges and force=True don't work well together. Even though I force it, it seems to be respecting the versions in the dependency packages.

**Comment by memsharded** [comment] 2024-05-31 07:55
> Ok, it didn't really work for us. It seems like the use of version ranges and force=True don't work well together. Even though I force it, it seems to be respecting the versions in the dependency packages.

What do you mean? Also in which Conan version? The way version ranges are resolved is also different in Conan 2. It would be good to have a small reproducible example of code that we can use to understand the issue.

**Comment by devlpr** [comment] 2024-06-20 23:40
Hey guys. It's tough to put together a good example of this, plus we are moving to Conan 2 right now. If we see the behavior with Conan 2 I will report it there. It may be more fruitful.

**Comment by memsharded** [comment] 2024-06-21 07:50
Sounds good, keep us posted. As this ticket doesn't require action from us at this moment, I am closing it (we are trying to do more house-keeping with tickets, to help us prioritize support and development), but please re-open when you get new feedback, or you can create new tickets as necessary. Thanks!

**Closed as completed by memsharded** 2024-06-21 07:50 UTC
