### ISSUE TITLE
CMAKE_CXX_STANDARD variables not populated

### ISSUE THREAD

**Issue by markfoodyburton** [conan-io/conan#8464] opened 2021-02-08 15:27 UTC
Hi, I have a trivial hello world.
My conanfile.txt is trivial with a cmake generator, I have a cmake with just the
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
lines in it, and the minimal cmake project and add_executable directives.
Running conan install generates the conanbuildinfo.cmake, but that does NOT include the CONAN_CMAKE_CXX_STANDARD variables, and hence the C++ standard isn't handled.
I'm using conan 1.32.1
Am I missing something obvious?

**Comment by markfoodyburton** [comment] 2021-02-08 15:56
I believe this is a problem with using conanfile.txt rather than a full .py file. Perfectly OK with this limitation, but would be good to document it.

**Comment by solvingj** [comment] 2021-02-09 02:06
I do not believe there should be a difference between `.txt` and `.py` in this case.  Can you please provide your full `conanfile.txt`, along with the generated `conanbuildinfo.cmake`?  We should be able to diagnose it fairly easily with that information.

**Comment by markfoodyburton** [comment] 2021-02-09 09:52
For the conanfile.py
```
from conans import ConanFile, CMake

class TestConan(ConanFile):
   settings = "os", "compiler", "build_type", "arch"
   generators = "cmake"

   def build(self):
       cmake = CMake(self)
       cmake.configure()
       cmake.build()
```

For conanfile.txt
```
[requires]
[generators]
  cmake
```

Running conan build with the py file, sets the CONAN_CMAKE_... variables

```
$ conan build . --build-folder build
Using lockfile: '/home/thomas/test_conan_bis/build/conan.lock'
Using cached profile from lockfile
conanfile.py
: Calling build()
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Conan setting CPP STANDARD: 17 WITH EXTENSIONS OFF
-- Conan: Compiler GCC>=5, checking major version 7
-- Conan: Checking correct version: 7
-- Conan: C++ stdlib: libstdc++11
-- Configuring done
-- Generating done
-- Build files have been written to: /home/thomas/test_conan_bis/build
[100%] Built target example
```

The issue is that we can't run conan build with a .txt file:

```
$ conan build . --build-folder build
ERROR: Conanfile not found at /home/thomas/test_conan/conanfile.py
```

Hence, as far as I can tell, unless I am missing a way to run conan, you can't use conan to set the CMAKE_... variables while using a .txt file.

**Comment by memsharded** [comment] 2021-02-09 11:01
This is the main difference: the ``build()`` method, and what it has inside is adding a bunch of logic and variables on the fly, that cannot be easily reproduce with a pure consumer conanfile.txt. 

This is the main reason we are moving to the new toolchains and generators like CMakeDeps and CMakeToolchain, which goal is to make the native build identical to the ``conan build`` or ``conan create`` builds.

**Comment by solvingj** [comment] 2021-02-09 11:30
Specifically, it's the CMake() helper class adding those variables , not the generator.

**Comment by markfoodyburton** [comment] 2021-02-09 11:34
Thanks both

So, for now, if you want to use the cmake build environment, and specifically need support for the cmake flags (e.g. CXX_STANDARD et al), then you are advised to use a conanfile.py and run conan build. This may change in the future.

Is that about right?

**Comment by solvingj** [comment] 2021-02-09 21:05
Yes it seems so.

**Comment by klaussnd** [comment] 2021-06-18 10:58
> Specifically, it's the CMake() helper class adding those variables , not the generator.

Is this behaviour on purpose or is it by accident? I guess that this is the reason that the workflow
```
conan build
```
is not identical to
```
conan install
cmake
make
```
for the above minimal example? 

> This is the main reason we are moving to the new toolchains and generators like CMakeDeps and CMakeToolchain, which goal is to make the native build identical to the conan build or conan create builds.

Does that mean that in a future Conan release, the two workflows I outlined above would behave the same, i.e. all information are written by the generator?

**Comment by solvingj** [comment] 2021-06-19 02:26
> > Specifically, it's the CMake() helper class adding those variables , not the generator.
> 
> Is this behaviour on purpose or is it by accident? 

On purpose (which is to say it was the original design). 

> I guess that this is the reason that the workflow ...  is not identical to ... for the above minimal example?

Yes.

> Does that mean that in a future Conan release, the two workflows I outlined above would behave the same, i.e. all information are written by the generator?

Yes.

1.  There are some additional wrinkles to be aware of though. If there are any `build_requires` or `environment variables` variables set in the profile, or if there are any `build_requires` in any recipes in the graph, then precisely reproducing `conan build` of that graph outside of Conan will require the caller to use Conan's `virtualbuildenv` generators in the shell in which `cmake` and `make` are called.

2.   Inside the `build()` method, the `CMake` helper will typically do something more sophisticated than just run `cmake`. For example, various paths may be passed as arguments, it's all up to the recipe.  The helper does not currently go "the final step", and "generate/write" the `cmake` command it runs to disk as a script or something.  Thus users will have to manually compose their CLI call to `cmake` to perfectly mimic the `CMake` helper if they want to get identical results. In most cases this should be relatively easy.  However, we have previously discussed the idea of creating "build script generators", and then having the `build()` method just run that script.  I for one think the possibility should get more discussion.

**Comment by klaussnd** [comment] 2021-06-30 07:52
Thanks a lot for clarifying that @solvingj 

> > Does that mean that in a future Conan release, the two workflows I outlined above would behave the same, i.e. all information are written by the generator?

> Yes.

About which time frame are we talking here approximately? Conan 2.0 or earlier?

**Comment by memsharded** [comment] 2024-11-25 22:35
The new ``CMakeToolchain`` generator solved this long time ago, closing as solved.

Please report new tickets against Conan 2 if necessary, thanks for your feedback.

**Closed as completed by memsharded** 2024-11-25 22:35 UTC
Labels: type: bug, stage: triaging
