### ISSUE TITLE
[question] Set specific remotes to only pull recipes

### ISSUE THREAD

**Issue by wbehrens-on-gh** [conan-io/conan#14216] opened 2023-07-03 16:58 UTC
### What is your question?

Kinda the opposite of `conan upload --only-recipe`, is there a way in the `remotes.json` file to only pull the recipes from a specific remote but not the binaries? like the following.
```json
{
   "remotes": [
      {
         "name": "conancenter",
         "url": "https://center.conan.io",
         "use_binaries": false,
         "verify_ssl": true,
      }
   ]
}
```
The environment I'm working in we'd like to use the recipes from conan center but due to other requirements must build all 3rd party libraries on our machines. This way we wouldn't be repeating work  other then what's required.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment] 2023-07-03 23:40
Hi @wbehrens-on-gh thanks a lot for your question. I think we can look at this from a different angle:

> The environment I'm working in we'd like to use the recipes from conan center but due to other requirements must build all 3rd party libraries on our machines. This way we wouldn't be repeating work other then what's required

The recommended approach in working with CCI at an enterprise level is to fork the whole repo, and upload to your private remote all the packages you depend on (and that your CI systems might build)

This gives you control and reproducibility on your end over what gets built, what changes you accept as valid for your recipes when syncing the forks after due diligence, lets you have recipe patches to support any custom configuration that CCI might not provide, and avoids the issue of having "recipe only" remotes

Is this something you have thought about? Did you discard it for any reason? I would like to know more if possible, thanks!

**Comment by wbehrens-on-gh** [comment] 2023-07-18 17:28
> Is this something you have thought about? Did you discard it for any reason? I would like to know more if possible, thanks!

This is how we we're first attempting to handle the issue but ran into two issues
1. We aren't a large organization and cannot dedicate the resources it would take to maintain something like the entirety cci.
2. I was the main person maintaining this setup and the team I'm working with is very good at finding "creative" workarounds to problems in our codebase and it seemed that having all the package recipes available was too much temptation despite me trying to warn that it would cause issues in the future.

A less then ideal solution I've found is using artifactory remote repositories to create a read-only local cache then in our jenkins builds always use `--build="*"`. This is less then ideal because it will ALWAYS build from source even if a pre-built package is present in our own remote from a previous build and I see a future where someone changes that to `--build=missing` unknowingly without reading the comments.

**Comment by memsharded** [comment] 2023-07-18 18:01
> We aren't a large organization and cannot dedicate the resources it would take to maintain something like the entirety cci.

But this is exactly what you are requesting, to not use the binaries from ConanCenter, but build your own binaries? Am I missing something? It doesn't mean that you have to build the whole ConanCenter, just the binaries you need, of course. And you build them just once, put them in Artifactory and then all would be good.

**Comment by wbehrens-on-gh** [comment] 2023-07-18 18:27
When I say maintain I mean the actual recipes, we can handle the building part. What I'm looking for is a way to have `--build="*"` behavior but only if a package is coming from conancenter

**Comment by memsharded** [comment] 2023-07-18 20:58
> When I say maintain I mean the actual recipes, we can handle the building part. What I'm looking for is a way to have --build="*" behavior but only if a package is coming from conancenter

Yes, of course you don't need to maintain the recipes. 
The recommended flow is:

- Fork ``conan-center-index`` repo
- Define a list of the packages and versions that you want, like ``mypkgs.lst``
- Have a simple script that ``export`` your list, then build them, then upload them to your artifactory

You can find a simple ``mybuild.py`` script in https://github.com/memsharded/conan-center-index/tree/mycustom. This script is already very efficient, as the ``--build=missing`` guarantees that it will not rebuild unnecessarily. 

This approach is being successfully used by many Conan users, as it has many advantages:
- Full control over the inputs. Total robustness, it is impossible that changes in ConanCenter breaks your build, only you have control over the updates of recipes
- Total customization. If you need a patch, a new version, an update... you can apply it in your fork, and have it immediately, no need to wait for it being merged upstream
- Quite simple to implement. Very understandable and reproducible by developers locally, without infrastructure, easy to debug.
- No unnecessary builds, you make sure both that your binaries are yours, and that no waste of resources or CI happens because rebuilding from sources again.

**Comment by AbrilRBS** [comment] 2024-03-05 09:55
For 2.1 we've added a filter for which recipes can be pulled from specific remotes, which should help with enforcing security policies in specific cases. Closing as solved for now, as we feel that filtering binaries is not a use-case we want to define :)

**Closed as completed by AbrilRBS** 2024-03-05 09:55 UTC
Labels: type: question
