### ISSUE TITLE
[bug] creating a lockfile from a base lockfile removes the captured recipe revision

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7595] opened 2020-08-25 14:48 UTC
Seems that the recipe revision captured in a base lockfile is removed in a derived lockfile.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 64-bit
  * Conan version: 1.28.1
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
Create a base lockfile for libb:
```
cd libb
conan lock create ../conanfile.py --user=user --channel=testing --lockfile-out=locks/libb_deps_base.lock --base

{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@Concepts/master",
    "requires": [
     "1"
    ],
    "path": "..\\..\\conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@Concepts/master#4db4bd6d3caf115878c1b5088ff3f2b350e1bc12",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4"
}
```

Capture the recipe revision:
```
conan export .. libb/0.1@user/testing --lockfile=locks/libb_deps_base.lock --lockfile-out=locks/libb_base.lock

{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@Concepts/master#4b567f0b7da05e50b926541cdc75cc03eb98a97d",
    "options": "",
    "requires": [
     "1"
    ],
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@Concepts/master#4db4bd6d3caf115878c1b5088ff3f2b350e1bc12",
    "options": "",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4"
}
```
Derive a config lockfile from it:
```
conan lock create ../conanfile.py --user=user --channel=testing --lockfile=locks/libb_base.lock --lockfile-out=locks/libb_release.lock --build=missing

{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "libb/0.2@Concepts/master",
    "options": "",
    "requires": [
     "1"
    ],
    "build_requires": [
     "2"
    ],
    "path": "..\\..\\..\\conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "liba/0.1@Concepts/master#4db4bd6d3caf115878c1b5088ff3f2b350e1bc12",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "prev": "73e4a53bd04fdf5a3ffbb57baf31e9fb",
    "context": "host"
   },
   "2": {
    "ref": "cmake_installer/3.15.3@conan/stable#0",
    "options": "",
    "package_id": "60b04a80ac4dd5c23f1acffacc679e9902e636e5",
    "prev": "0",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4",
 "profile_host": "[settings]\nadk=[>=4.0.0]\narch=tricore\narch_build=x86_64\nbuild_type=Release\ncompiler=tasking-tricore\ncompiler.flavor=ctc\ncompiler.version=v6.2r2p2\nos_build=Windows\npbl_*:compiler=tasking-tricore\npbl_*:compiler.version=v6.2r1\n[options]\n[build_requires]\n*: cmake_installer/3.15.3@conan/stable\n[env]\n"
}
```

**Comment by memsharded** [comment] 2020-08-25 22:19
Hi @GordonJess 

I have had a look to this issue and I would say this is by design.

When you are creating the final config lockfile, you are passing the path to the local pkgb ``conanfile.py``. As this file is not a package yet, it cannot have a revision. The "exported" revision is not used, and discarded, because you are not referencing it.

have you tried?:

```bash
conan lock create --reference=libb/0.2@Concepts/master --lockfile=locks/libb_base.lock --lockfile-out=locks/libb_release.lock --build=missing
```

I am adding a test in https://github.com/conan-io/conan/pull/7592 that covers this, seems to work fine.

**Comment by DukeOfKirkcaldy** [comment] 2020-08-26 07:36
Hi @memsharded,

Ah, yeah that makes sense.  I tried your suggestion but I get the following error:

```
ERROR: Attempt to modify locked libb/0.2@Concepts/master#4b567f0b7da05e50b926541cdc75cc03eb98a97d to libb/0.2@Concepts/master#4b567f0b7da05e50b926541cdc75cc03eb98a97d
```

**Comment by memsharded** [comment] 2020-08-26 08:25
Hi @GordonJess 

Can you please verify again? I have tried to obtain that ``Attempt to modify locked libb``, but no success. You have the ``lose_rrev_test`` in https://github.com/conan-io/conan/pull/7592/files if you want to compare the commands, just in case I am missing something.

**Comment by DukeOfKirkcaldy** [comment] 2020-08-26 08:58
Hi @memsharded,

I checked again.

It seems the `conan lock create` command works fine and I can confirm that the derived lockfiles have the revision info.

It is the subsequent `conan create` commands which use the derivied lockfile which fails and causes the above error message.

```
conan create .. libb/0.2@Concepts/master --lockfile=locks/libb_release.lock
```

**Comment by memsharded** [comment] 2020-08-26 11:02
I have added the subsequent ``conan create`` to the test, still passing. I have also checked the code, and it seems the only possibility is that ``libb`` already had a ``prev`` defined, but in your above lockfile it doesn't seem the case. Not sure what to try next. I am running from my branch, but the other changes seems completely unrelated, and I have run the test from develop branch and still passes.

Could you please post your lockfile when you changed the command and used ``--reference`` instead? Maybe that helps.

**Comment by DukeOfKirkcaldy** [comment] 2020-08-26 11:41
Hi @memsharded,

You're right, the lockfile used by the failing `conan create` has `prev` already defined.  It is added when deriving the lockfile from the base.

Can you try make a test with `conan config set general.default_package_id_mode=full_package_mode`?

**Comment by memsharded** [comment] 2020-08-26 11:46
Yes, the test is already using ``full_package_mode``: https://github.com/conan-io/conan/pull/7592/files#diff-ed93571a10c6758448fb4aacc488583aR186

**Comment by DukeOfKirkcaldy** [comment] 2020-08-26 11:49
Sorry, I meant `package_revision_mode`.

**Comment by memsharded** [comment] 2020-08-26 11:50
Same result with ``package_revision_mode``

It would be very interesting to track down where that ``prev`` comes from:
- First, you capture a "base" lockfile, it shouldn't have ``prev``
- Then, with the ``export`` only the ``rrev`` should be added, still no ``prev``
- When capturing the full config lockfile, the thing might be that ``--build=missing`` is not defining that ``libb`` should be built, and there is already a binary there in the cache that is valid, and thus the ``prev`` is being captured. Maybe adding ``--build=libb/0.1@...``?

**Comment by DukeOfKirkcaldy** [comment] 2020-08-26 12:34
Thanks!  Can confirm adding the build policy for the package works.

Seems I already had a package in the cache which was determined to be compatible due to the `build_type` setting being missing from the recipe.  This locked the package in the lockfile and quite rightly didn't allow me to rebuild it.

**Comment by memsharded** [comment] 2020-08-26 14:18
Excellent. This issue can be closed, behavior is checked in tests. Thanks for the feedback!

**Closed as completed by memsharded** 2020-08-26 14:18 UTC
Labels: type: question
