### ISSUE TITLE
Cannot have two different remotes with identical URL

### ISSUE THREAD

**Issue by cleeland** [conan-io/conan#1430] opened 2017-06-23 18:54 UTC
I tried adding a new remote using the same URL as an existing remote and received an error that the first remote already exists with the same URL.

Is there a design reason why I can't have multiple remotes with the same URL?

**Comment by lasote** [comment] 2017-06-23 21:39
Because a remote with the same URL is the same remote. Right? Why do you want to add it twice?

**Comment by memsharded** [comment] 2017-06-23 22:29
It will unnecessarily duplicate the time to look for dependencies when installing and the package not in that repo. Also, the tracking of the origin of the packages in the registry.txt file is by name. It makes easier managing the file.

**Comment by cleeland** [comment] 2017-06-26 15:04
> Why do you want to add it twice?
Because I have two conceptual remotes, though sometimes they are hosted at the same URL depending on deployment context.

> tracking of the origin of the packages in the registry.txt file is by name. It makes easier managing the file.
by "name" you mean "short name", right, not the URL?

> It will unnecessarily duplicate the time to look for dependencies when installing and the package not in that repo.

That just sounds like an unfortunate side-effect rather than a reason not to permit it.

**Comment by memsharded** [comment] 2017-06-26 23:18
> Because I have two conceptual remotes, though sometimes they are hosted at the same URL depending on deployment context.

Could you please elaborate it further. AFAIK, with both conan_server and Artifactory, it is not possible to have 2 different repos in the same URL, so it will be just one, and then makes sense that it is only addressable by one URL and one remote name. What do you mean with "two conceptual remotes"? And how do you merge them when you put them in the same URL?

> That just sounds like an unfortunate side-effect rather than a reason not to permit it.
It is not a side effect, it might be the cause that this check is in place. It is more common to inadvertently/incorrectly add a remote twice because not realizing that you already have it declared, than wanting to use 2 different names for the same remote. It is very, very, very common that users request protection against this type of mistakes (which later confuses and annoys them), so it is likely that this feature comes from users feedback.

**Comment by lasote** [comment] 2017-06-27 07:18
> Because I have two conceptual remotes, though sometimes they are hosted at the same URL depending on deployment context.

That sounds like a bad network configuration

**Comment by cleeland** [comment] 2017-06-27 14:05
Suppose I am a company and I have multiple products. For various reasons, it makes sense to have a conan remote for each product because conceptually they are distinct.  Those products are created and managed by distinct groups within my organization, so I want each group to manage and tend to their own server, so each remote have different URLs.  A group should only have write/upload permission to its repository.

Now I want to deploy.  The outside world shouldn't have to know "how the sausage is made" (how things are organized inside my enterprise).  Moreover, maybe I don't WANT them to know, and from the outside world's perspective all products just come from a single organization (the larger enterprise).  Thus, a single repository.  But the remote names are part of the recipe and dependencies (as you've pointed out), so I need to leave the distinct remotes but map each of them to the same externally-visible repository.

**Comment by cleeland** [comment] 2017-06-27 14:07
> It is more common to inadvertently/incorrectly add a remote twice because not realizing that you already have it declared, than wanting to use 2 different names for the same remote.

That sounds like a reason to have a check but not completely disallow.  Offer a `--force` option that allows the user to say "yes, I really do mean to do this"

**Comment by lasote** [comment] 2017-06-27 14:13
It still looks tricky to me. I don't know how and why a remote configuration should be shared with the external world.

**Comment by lasote** [comment] 2017-06-27 14:35
Yes, through the installation of a command tool called conan client. Are you redistributing the conan client? Maybe I don't understand the problem.

**Comment by lasote** [comment] 2017-06-27 14:46
If I've understood well, you want to distribute a custom remote configuration to the external world, right? and the remote configuration will have a duplicated entry?? I think the external world will think that maybe there is something wrong with the configuration, hopefully, they will realize that it's just a dirty trick to hide an internal implementation detail. 

But what I can't understand, why don't you adjust the remote configuration for deploy? It's just a plain text, and you can control it with the `conan remote` command.

**Comment by floriansimon1** [comment] 2020-03-02 19:45
I'm facing problems due to this technical choice. Let's see what you think about my use case. I'm writing automation to automatically publish recipes to a "staging" conan remote. When certain commits are made, the recipes are promoted from channel/testing to channel/stable automatically. There will be two remotes to back that automation in the future, and the remotes are controlled by configuration files. For testing purposes, I'd love to be able to deploy to and from the same repo, but the conan command-line tool does not support my use case. Is that a use case you think is worth supporting in any way?

The duplicate package lookup issue is easily mitigated by not performing two checks to the same remote, and by indicating on the command-line that a check will be skipped because it's duplicated.

Thanks for your attention.

**Comment by memsharded** [comment] 2020-03-03 16:56
Hi @floriansimon1 

>  When certain commits are made, the recipes are promoted from channel/testing to channel/stable automatically.

This is something that we are learning might not be the best practice. It is much better, and a general Devops principle, to manage packages as immutable. So instead of that, we are leaning to managing different remotes, and using promotions of packages from remote to remote to indicate different stages of maturity.

Regarding your feedback I am afraid I don't fully understand your use case yet. When you are "deploying", I guess you mean uploading, you only specify 1 remote to upload packages, so you can use the remote name that you want to define that. No need to have 2 different remotes names for the same URL. Could you please elaborate a bit further?

**Comment by cleeland** [comment] 2020-03-03 17:09
I think it's fine if you want to suggest that as a best-practice, but cross the line when you actively cripple the tool.

I've yet to see a reason why this shouldn't be allowed other than "we don't think it makes sense".  The fact of the matter is that you defined the model used by conan, and the *model* itself permits this sort of thing.  Other tooling that uses remotes (e.g., git) does not restrict someone from defining multiple remote names that end up referencing exactly the same URL and there is absolutely no reason why your tool should restrict a user from doing the same.

"Tools, not rules."

**Comment by floriansimon1** [comment] 2020-03-03 18:25
> Hi @floriansimon1
> 
> > When certain commits are made, the recipes are promoted from channel/testing to channel/stable automatically.
> 
> This is something that we are learning might not be the best practice. It is much better, and a general Devops principle, to manage packages as immutable. So instead of that, we are leaning to managing different remotes, and using promotions of packages from remote to remote to indicate different stages of maturity.

First constraint: our product consuming Conan packages is not allowed to build any Conan recipe, because that takes way too much CI time. Second constraint: our QA people need to be able to build our product with the testing dependencies to validate our work. Therefore, we have to push our Conan packages to some temporary space.

That's where our testing channel on a testing remote comes into play. While a feature on our product is still a pull request, and when it introduces new packages on which nobody depends, we just push a package named user/testing in our testing remote. Why is the /testing part important? Because our automation could have bugs, and if I saw a testing package in our production remote, I'd know I can safely delete it, whereas if the name was just /stable, I'd lose that guarantee.

Production packages **are** immutable in our architecture, but our testing packages are just, well, testing packages. You can do whatever with them. Remove them, update them, you name it. No need to make them immutable - they could be broken or missing some things. We need the flexibility to change them as we see fit.

While packages are in testing space, you can write pull requests on our product that consumes them, and let the QA team/code reviewers inspect your work. As soon as these pull requests land in the mainline, there's CI machinery that copies the testing packages from the testing remote to a production remote, on the stable channel, without you having to do anything.

I just finished writing that machinery, and it's surprisingly simple. For testing purposes, I wanted to use the testing remote for both the test environment *and* the make-believe production environment because I did not want to pollute the production remote. In my organization, you need to request permission everytime you delete something from the production remote. So that's my use case: testing my automation.

> Regarding your feedback I am afraid I don't fully understand your use case yet. When you are "deploying", I guess you mean uploading, you only specify 1 remote to upload packages, so you can use the remote name that you want to define that. No need to have 2 different remotes names for the same URL. Could you please elaborate a bit further?

I could have one remote name - but the fact that Conan failed on me made me lose some time. When the problems are so easily avoided - why not fix them? How many other use cases will this help cover? What does that limitation otherwise bring us? It is my opinion that Conan would be better without that particular opinion baked in. I suppose I'm not the first one caught off-guard, and I won't be the last.

Let me finish by stating that I know you don't guys don't owe us anything, and that I'm very appreciative of the collective work that brought Conan to life. My intention is just to share a suggestion to improve it.

Protip for anyone in the same situation: just changing the scheme from HTTP to HTTPS works fine if your remote supports it. So I was able to test my work in the end, but I had to rely on a hack.

**Comment by memsharded** [comment] 2020-03-04 09:13
Hi @floriansimon1 

Just a quick note: We don't do things arbitrarily or try to force users into our very opinionated practices without any reason. Actually I think it is quite the opposite, and we have a solid track record providing as much value and flexibility to Conan users based on their feedback and not our assumptions.

As an exercise, I have checked from where this constraint come from:

- https://github.com/conan-io/conan/issues/854

The thing is that Conan also manages credentials for the remotes. Those credentials were internally stored by URL, not by remote name. This introduced in practice a variety of bugs, because credentials are set by remote name, not by URL, and we couldn't quickly fix that without breaking the ``conan user`` command, that was already widely used. So we decided that forcing a 1:1 relation between remote name and remote url was a good enough solution at the moment. I found later users managing many remotes found it also useful, to not accidentally add twice the same remote. 

Trying to remove this constraint now will open again those bugs. I have never been opposed to this, but we always have to balance the implications, and this is why I am always asking about the use cases. What you think it is very obvious to you, might be actually the opposite for other Conan users. We spend literally thousands of hours reading user feedback, in Github, in emails, in conferences, in Slack...

I am going to assign this for Conan 2.0, which will start soon and there we will be able to re-design this without risks.

Regarding the user/channel changes with ``conan copy``, what I wanted to clarify is the following: that changes only the "reference" of the package. But packages still contain internally some information, like ``conaninfo.txt`` that will still point to dependencies in the wrong channel. That information is displayed in the ``search`` command, in Artifactory... and will cause confusion, because you can see "production" packages that appear to have dependencies on "testing" packages which will be a disaster. We are considering to remove the "conan copy" command in Conan 2.0, you might still be able to use channels, but you might need to re-build the package for the new channel.

Thanks for the feedback!

**Comment by floriansimon1** [comment] 2020-03-04 13:08
Thank you for the time you took to answer.

Quick question about "conan copy" - if I don't depend on testing packages I'm fine (until conan copy is removed)? Or is there something else I don't know?

Also, you say it will be a disaster. I wonder in what practical ways? Is it just the dependencies that will be in testing or will there be more to it?

**Comment by memsharded** [comment] 2020-03-05 09:04
> Quick question about "conan copy" - if I don't depend on testing packages I'm fine (until conan copy is removed)? Or is there something else I don't know?

That is mostly it, that dependencies information is stuck in the older channel. If a package has not dependencies, then it should be ok.

> Also, you say it will be a disaster. I wonder in what practical ways? Is it just the dependencies that will be in testing or will there be more to it?

I mean that depending on "testing" packages in production would be a disaster. This might not happen, but developers and admins will panic everytime they do a search in the production repositories, or navigate in Artifactory and see that their packages declare to be depending on "testing" packages.

> The reason I'm asking is because maybe the docs should mention why it should not be used and that would be a good first contribution from me ;)

Yes, this is something that we are learning now while we do progress defining better CI flows, and trying to standardize on some common best practices. So we didn't update the docs yet. But if you could do a contribution to the docs explaining a bit about this caveat of ``conan copy``, that would be very appreciated! :)

**Comment by memsharded** [comment] 2023-02-11 22:03
Conan 2.0 allowed this some beta releases ago, now about to be final released this month. https://github.com/conan-io/conan/pull/13101 is just adding a test to validate it and add a warning, so closing this.

**Closed by memsharded** 2023-02-11 22:03 UTC
Labels: type: look into, type: feature
