### ISSUE TITLE
[Artifactory] Record build-requires dependencies

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#1699] opened 2017-09-01 23:05 UTC
Currently, it appears that Artifactory is only informed of the runtime dependencies (i.e., "requires") for a given package. It would be nice if the build dependencies ("build-requires" as well as "requires" marked "private") were also recorded in Artifactory metadata. This would allow for automated triggering of downstream CI systems when a dependency is updated. (I can monitor packages reported as build dependencies and then trigger a build when I see a build depdency change.)

Does this use case make sense/is there another way to handle this use case?

**Comment by memsharded** [comment] 2017-09-02 12:25
The idea is that build_requires don't change the binaries built with them, otherwise they would need to be modeleded somewhat in the package ID hash, so not sure about the need to fire the re-building.

But I agree that it would be interesting to have the information of build_requires captured somewhere, not sure exactly where and how, but lets consider this. Thanks!

**Comment by mpdelbuono** [comment] 2017-09-02 15:14
Ah, that's an interesting viewpoint, and it makes sense. I had been using build_requires for required code generators. However, maybe it's more correct to use a private "requires" dependency instead. (Regardless, that does not appear to be captured in Artifactory right now either. It appears only public "requires" are recorded.)

**Comment by memsharded** [comment] 2017-09-02 17:11
Yes, maybe. Depends, if the code output by the code generator doesn't change, just the generator itself, then it is not required. However, I wouldn't be afraid of using normal requires for code generators, it might be slightly less efficient, because they will be retrieved, but it is also easier to keep consistency and continuous upgrade dependencies for public requirements. As usual, a trade-off, just don't discard them.

**Comment by markgalpin** [comment] 2018-02-23 16:50
In theory, build-info should provide all information required to reproduce a build.  At the moment we're not really getting that far because of the difference in build models.  This will impact both build_requires and profile information that is not currently being captured.

**Comment by memsharded** [comment] 2018-06-28 15:16
Hi @mpdelbuono 

Not yet in Artifactory, but small step towards it. Conan 1.5 computes and shows in the graph the build_requires. They can even be computed (without using them) with ``conan info --dry-build=xxxx``

**Comment by wizardsd** [comment] 2020-08-05 09:51
I have another good case for this feature for CI and artifactory. For example, when you build a shared library (*.so, *.dll, etc), you declare public requirements in `requires` field (i.e. if your library depends on Qt on public *.h file) and declare private requirements in `build_requires` (i.e. if your library uses `libfoobar` internally) because users of your library don't need the `libfoobar` to link with your library. It will be nice to make such dependencies visible to CI service, because when something is committed to `libfoobar` CI service must rebuild the shared library too.

**Comment by memsharded** [comment] 2023-03-06 11:54
Conan 2.0 builds the whole graph, always, including build_requires. So it will be easier to track, store in lockfiles, etc.
The Artifactory build-info has not been maintained, and won't work out of the box with Conan 2.0, that effort will be done in https://github.com/conan-io/conan-extensions, closing this ticket.

**Closed by memsharded** 2023-03-06 11:54 UTC
Labels: type: look into, type: feature, component: artifactory
