### ISSUE TITLE
[feature] Use common file format for configuration

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan#6526] opened 2020-02-11 17:23 UTC
Hi!

On the last week, during a talk, people asked me why Conan uses multiple file formats (yaml, ini, json) for its configuration. For instance, workspace uses conanws.yml, however the layout file uses .ini format.

Conan settings file is yaml, but conan.conf is .ini.

I would suggest a file format which is popular, built-in parser for python, friendly for human editing and easily extensible: [TOML](https://github.com/toml-lang/toml). It looks .INI, but with steroids.

I can say the JSON output is not a problem, because most of time it is used for parsing.

It can be adopted for Conan 2.0, as it requires a big effort and will break users.

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2020-02-11 18:23
Notes:

- In ``settings.yml`` we use the "links" feature to inherit/extend data, it would be ugly to have a format that doesn't implement this.
- I'd suggest a bit of research of how the final formats look like, I like TOML, but for some cases (lists of dicts, IIRC), it can be really ugly, it would be worse than what we have today.

So I am in favor of unifying formats when/if possible, I also like TOML, but we need to consider, maybe yaml is better for our use case.

**Comment by uilianries** [comment] 2020-02-11 18:34
Indeed, TOML dictionary is a bit ugly when compared to yaml.

https://github.com/toml-lang/toml#keys

**Comment by jgsogo** [comment] 2020-02-21 15:53
Having a look at TOML, it has two important caveats:
 1. no stable release yet: they'll try to not break current 0.5.0 when releasing 1.0
 2. no specification
 3. no anchors/links to reproduce what we are doing right now in `settings.yml` for the intel compiler.

Probably, number 3 forces us to choose YAML or XML (with XSLT), AFAIK those are the only two languages where we can create a link to another _node_ in the document and extend it.... and given that XML is not a trendy one, probably the obvious choice would be YAML.

**Comment by uilianries** [comment] 2020-02-21 16:12
So I vote for YAML.

**Comment by tru** [comment] 2020-03-04 08:40
I really really dislike YAML, I also really dislike XML.

I am a simple man - have you guys considered to just have the configuration in python? This is easy to implement and maybe the simplest case looks "worse" than YAML - but it's insanely more configurable and most of the time it doesn't look bad.

All the discussions we have in profiles about concating and variable substitution would be solved by just allowing the profiles to be .py files.

I think it's worth considering.

I would also NOT switch the INI format for YAML. God I hate YAML. 😉

**Comment by memsharded** [comment] 2020-03-04 09:55
Good point. Yes, I have thought about profiles in python. My main concern there is users displacing too much logic to a single "default" profile that would in practice evaluate to very different profiles depending on the platform. But certainly an option to be considered.

**Comment by jgsogo** [comment] 2020-03-04 10:21
As a hacker I love the idea, but as a CI guy looking for reproducibility and sanity in a complex world...

A `.py` file will contain logic (we know it), it will depend on the platform and environment variables, then the profile will evaluate to different things depending on the developer's machine, `conan config install xxxx -pr=mycompany_profile` will no longer be deterministic. And, what will happen if we do the same with `remotes.json`, or the `settings.yml` file (this issue is about moving everything to the same format)? :see_no_evil: :bomb: 

I know it's a problem of how you use Conan and not Conan itself, but I'd need to see a strong necessity for it.

**Comment by uilianries** [comment] 2020-03-04 13:57
> I really really dislike YAML, I also really dislike XML.

I have to agree, I don't like YAML too, and XML has tokens ... 

We could use python for configuration, but a rule must be followed: no conditions or logic are allowed in the configuration files. It must be simple, otherwise, it will be hell, having several behaviors due to the configuration file.

**Comment by memsharded** [comment] 2020-03-04 15:05
> We could use python for configuration, but a rule must be followed: no conditions or logic are allowed in the configuration files. It must be simple, otherwise, it will be hell, having several behaviors due to the configuration file.

It is impossible to control this. Users will always explore all possibilities https://www.hyrumslaw.com/, and if it is python, it will be almost impossible to ban that. And if no conditions or logic are allowed, wouldn't that be almost json files?

**Comment by tru** [comment] 2020-03-04 15:09
I see your point for sure. Let me ponder a bit more. I need to find a way to limit the spread of YAML over the world! 😉

**Comment by jgsogo** [comment] 2020-03-04 15:54
![image](https://user-images.githubusercontent.com/1406456/75897229-89b8f180-5e38-11ea-952f-d4bea20884c4.png)

:rofl: :rofl: :rofl:

**Comment by tru** [comment] 2020-03-06 10:35
The more I think about this the more I think the profiles especially should be in a dumb as possible format and we should use some kind of template / generator system to generate them. Then store the profiles in such a way that they can be exactly the same if you want to get reproducibility.

I could write that kind of generator / template system myself but I wonder if it would beneficial for the conan community to have a common format for that as well? I am thinking in terms of jinja etc.

That means that I guess YAML would be enough for the profiles - but I would not add additional features on top of it - I would keep it "dumb" and then allow some kind of generation to be smart.

What do you guys think?

**Comment by jgsogo** [comment] 2020-03-06 11:25
I'm a truly big fan of Jinja2, you don't have to convince me ;D I'd vote to run Jinja2 over any input file before actually reading it, and document the arguments provided to those templates. More or less the same I would propose for the outputs like generators, toolchains, CMake files,...

But it would be the same, the door is open to run logic before parsing the profiles (it is not the same as a python file, but still some logic). I'm not sure if it'd be a little bit insane to open that possibility just because we don't want to write a couple of profiles (maybe this should be strange to Conan and it is about an external script that loops over the templates and generates Conan profiles)

**Comment by tru** [comment] 2020-03-06 12:19
>  I'm not sure if it'd be a little bit insane to open that possibility just because we don't want to write a couple of profiles

Yeah this is a discussion we had internally - should we write them all out instead? But we landed that this is actually pretty bad as well - we have 56 profiles right now - some of them have a lot of overlap (think debug vs release profiles etc) and maintaining them manually is not great either.

I think the best way to handle this is to not have conan run jinja automatically when it's executed - there is very little reason to have this generated runtime.

I would suggest something like:
* Run `conan-make-profiles` that takes jinja templates and output static profiles
* store the static profiles in our git repo etc
* have revisions optionally be based on the hash of the profile used

This would make the maintenance much easier and have the reproducibility you want.

**Comment by tru** [comment] 2020-03-06 12:19
This is probably what we are going to do now instead of concating profiles etc - but the question is if `conan-make-profiles` should be a community tool or a plex tool.

**Comment by uilianries** [comment] 2020-03-06 19:07
Well, so I think the least worst is YAML.

The year is 2020, we supposed to have flying cars, but we can't have a simple  good configuration file format.

**Comment by memsharded** [comment] 2020-03-08 23:59
I understand both pains. I don't love yaml to be honest. Using python for this will bring its own problems, same for using jinja templates.

If we are talking about a tool that generates profiles offline, then this already has some overlap with ``conan-package-tools``. A big part of that functionality is to generate the different profiles (then the other part is to build for them, use docker, etc)

**Comment by bugproof** [comment] 2020-09-26 21:06
It would be good if `conanfile.txt` used some format  too instead of .txt. I would personally vote for TOML. Cargo (rust package manager) uses it too.  If not possible, YAML or JSON. TOML looks more closely like current conanfile.txt so I think it will be easier to migrate.

vcpkg uses json e.g. https://vcpkg.readthedocs.io/en/latest/specifications/manifests/ but it never meant to be a configuration format in the first place (e.g. it doesn't originally support comments)

With a common file format it would be easier for others to create tools or commands e.g. `conan add <packagename>` that would automatically add the dependency to e.g. `conan.toml` or `conan.json`

https://pypi.org/project/toml/
TOML specification: https://toml.io/en/v1.0.0-rc.2

**Comment by memsharded** [comment] 2021-06-23 16:57
@tru we have merged #9147, that supports jinja2 templating for profiles. This allows not only to read env-vars, or platform configuration, but also to manipulate them, join, conditionals, fors, etc. I think it is very powerful.

But that takes us to the main question, and the transition to Conan 2.0:

- It is simply too much work to introduce new formats for profiles, settings, conf, etc during Conan 1.X to prepare to the transition to Conan 2.0 that would use only the new format.
- If Conan 2.0 needs introduces the new format, it will still to maintain the old one, so not an evident advantage.

We have many other, much higher priorities that this relatively small UX improvement. Lets keep the current formats for Conan 2.0, and beyond, I am closing this at the moment, we can always re-open in the future in 2.X when the core 2.0 has stabilized.

**Closed by memsharded** 2021-06-23 16:57 UTC
Labels: complex: high, priority: high, stage: queue, type: feature
