### ISSUE TITLE
Uploading multiple PackageIds concurrently causes collision within conan-server

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4843] opened 2019-03-26 19:45 UTC
This has been discussed in #4698. Seems as if concurrent uploads of the same PackageId to the conan-server can cause a collision under certain circumstances.

**Comment by danimtb** [comment] 2019-03-27 12:51
This might be a duplicate of #3624

Please follow conversation there

**Closed by danimtb** 2019-03-27 12:51 UTC
