### ISSUE TITLE
[bug] Timeouts uploading large packages to Artifactory

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#10911] opened 2022-03-28 19:00 UTC
Not sure what specifically causes it, but would love to know if possible, and if so how to work around the problem.

On the client side, it seems like the upload completes, then 3 minutes later the request times out:
```
2022-03-28T18:20:45.5757918Z Uploading package 1/1: c37b72a856a3a472e507edcc5b9e7a477dd0c3a9 to '***redacted***'          [0m
2022-03-28T18:20:45.5946725Z 
...
2022-03-28T18:31:53.9083875Z Uploading conan_package.tgz :  99%|#########9| 3.77G/3.79G [01:04<00:00, 92.0MB/s]
2022-03-28T18:31:54.0079369Z Uploading conan_package.tgz :  99%|#########9| 3.77G/3.79G [01:04<00:00, 93.1MB/s]
2022-03-28T18:31:54.1162492Z Uploading conan_package.tgz : 100%|#########9| 3.78G/3.79G [01:04<00:00, 98.7MB/s]
2022-03-28T18:31:54.1164185Z Uploading conan_package.tgz : 100%|#########9| 3.79G/3.79G [01:04<00:00, 96.4MB/s]
2022-03-28T18:31:54.1164743Z                                                                                   
2022-03-28T18:31:54.1166293Z 
2022-03-28T18:31:54.1167084Z Uploaded conan_package.tgz -> Installer/220328.4216+ee6a6afb@ci/branch_releases_22.03.28:c37b [3978144.30k]
2022-03-28T18:34:54.4232074Z [1m[31mERROR: HTTPSConnectionPool(host='conan.ci.eng.***redacted***.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/files/***redacted***/Installer/220328.4216+ee6a6afb/branch_releases_22.03.28/0/package/c37b72a856a3a472e507edcc5b9e7a477dd0c3a9/0/conan_package.tgz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.ci.eng.***redacted***.com', port=443): Read timed out. (read timeout=60.0)",))[0m

```

On the Artifactory side:
```
2022-03-28 18:31:54,129 [http-nio-8081-exec-9] [INFO ] (o.a.e.UploadServiceImpl:399) - Deploy to 'conan-local:redacted/Installer/220328.4216+ee6a6afb/branch_releases_22.03.28/0/package/c37b72a856a3a472e507edcc5b9e7a477dd0c3a9/0/conan_package.tgz' Content-Length: 4073619764
2022-03-28 18:32:54,836 [http-nio-8081-exec-9] [ERROR] (o.a.a.c.r.ArtifactoryService:542) - Failed to read stream: java.io.EOFException: Unexpected EOF read on the socket
org.jfrog.storage.binstore.ifc.ClientInputStreamException: Failed to read stream: java.io.EOFException: Unexpected EOF read on the socket
	at org.jfrog.storage.binstore.ifc.ClientStream.read(ClientStream.java:36)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1158)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:878)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1135)
```

Note the timestamps: the upload completes at 18:31:54 from the client side, and `Deploy` action on the server side begins at the same time. The server then errors out a minute later, with the client sitting for another 2 minutes before seeing an error.

This seems to only happen with very large packages, and only in about 70-80% of the cases (e.g. if we retry enough times it will succeed). How can it be fixed?

**Comment by mhahn-sighthoundlabs** [comment] 2022-03-28 19:51
I can see that perhaps the fronting nginx's timeout is too small now?

```
	location / {
		client_max_body_size 4000m;
		client_body_timeout 1800s; # Default is 60, May need to be increased for very large uploads
		try_files $uri @conan;
	}
```

**Comment by memsharded** [comment] 2022-03-28 23:40
I would recommend trying a couple of things:

- To run the same, same package, against a local Artifactory instance (you can easily grab an ArtifactoryCE) running in the same computer. Trying to rule out possible client side issues.
- Try and report the same upload in different platforms Linux, Windows, Mac. Does it happens in all of them? More or less with same frequency?
- If you are not managing the Artifactory, talk to the team maintaining it. It could have some configuration on the server side, or in the front (Nginx or whatever) that could limit some resource, size, memory bandwidth, or something like that

**Comment by w3sip** [comment] 2022-03-28 23:45
What does the `Deploy` stage do? Does it simply copy the resulting package, or is there a more elaborate processing, that involves uncompressing and reading the contents?
I wonder if something like this happens:
- package uploads, but the HTTP request is still outstanding, sitting idle, waiting for server response
- server receives the archive, but takes > 60s to process it
- the client, after sitting idle for 60s gives up, and drops the connection
- the server treats it as client-side error

Pure conjecture (I haven't looked at the code), but given the timing of log messages seems possible?

**Comment by memsharded** [comment] 2022-03-28 23:56
> What does the Deploy stage do? Does it simply copy the resulting package, or is there a more elaborate processing, that involves uncompressing and reading the contents?

Up to my knowledge the Deploy stage should be relatively cheap. The compressed uploaded files don't need to be read at all, because the information that is needed goes in the uncompressed conaninfo.txt, and that is easy and fast to parse.
But I am not an Artifactory expert. If you are JFrog customers, I'd suggest filing a support ticket directly against Artifactory.

Some of the above suggestion would help in anyway to discard those things. In a local instance you should be able to see the Deploy time too and see if it is relevant or not.

**Comment by gitsang** [comment] 2024-09-19 09:01
I also encountered the same situation. I used Traefik to proxy the Nexus repository and added a middleware to audit request. I observed that sometimes the Conan client sends a Content-Length > 0 but does not transmit any body data.

**Comment by memsharded** [comment] 2024-09-19 15:58
Hi @gitsang 

This would look like a completely different issue, as this ticket was reporting about Artifactory timeouts, and you are using Nexus. If there is some issue with the Conan client it would be necessary to report a new ticket reporting against a local ArtifactoryCE instance (you can download it for free in our downloads page). Thanks!


@w3sip did you manage to do some of the above checks trying to understand possible causes? Did you ever filed a ticket to JFrog? Thanks for the feedback.

**Comment by w3sip** [comment] 2024-09-19 16:54
@memsharded - to be honest, drawing a blank on how we've resolved it. I think it was a combination of modifying our build process to keep the size of the packages down, and raising some timeouts in both Conan client and Artifactory. But no memory of specifics at this point, sorry.

**Comment by memsharded** [comment] 2024-09-19 22:24
No prob, thanks very much for the feedback!
I am closing this at the moment, as we cannot reproduce from here, but if it happens again, please create a new ticket and we will investigate. Thanks!

**Closed as not planned by memsharded** 2024-09-19 22:24 UTC
