### ISSUE TITLE
Windows installer doesn't launch on windows 10

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#54] opened 2015-12-21 08:16 UTC
Maybe it's related to the anti-virus software, but it's something to look at. I tried launching the installer three times and it didn't work. When shutting down the system, an error message prompted from the installer.

**Comment by memsharded** [comment] 2015-12-21 11:03
Antivirus software? The MS one included with Win10? Could you please try to disable it for a minute while you install the installer, just to check? I don't have a Win10 here to try, sorry. Any further info about this issue would be useful, thanks!

**Comment by lasote** [comment] 2015-12-21 16:12
I tried in Win10 without problems.

**Comment by Klaim** [comment] 2015-12-29 17:26
Same here, not problem when installed either by pip or installer.

**Comment by memsharded** [comment] 2015-12-29 23:24
Hi @Klaim what do you mean that no problem when installed by *installer*. I think that the actual problem is with the Win installer, right? Can you have a look at the win process manager (not sure yet about the interface to it in Win10), just to check if the installation process is hanged up by some windows process, the antivirus, etc. Also if you have any other antivirus besides the Win10 bundled one. Sorry, but so far I don't know yet how to debug this problem, it works for me in Win7 (Microsoft Security Essentials as antivirus), and @lasote was able to install in Win10 without problems.

My Win7 is "bullying" XD me to upgrade to 10, so I guess I will have to do it soon, hopefully it happens to me too, so I am able to investigate it properly.

Thanks very much for reporting, please use the pip package meanwhile.

**Comment by Klaim** [comment] 2015-12-29 23:31
Sorry I was not clear at all: I meant that I did not see any problem when in tried to install conan (the first public one) either via pip or via the installer. I don't know what is the problem with @Manu343726 case but I suspect that something is indeed blocking the installer's activity.
That or the installer prompted a window which was hidden.

I'll try the installer again now, I have another fresh install.

**Comment by Klaim** [comment] 2015-12-30 00:00
I tried again the installer, no problem.

**Comment by memsharded** [comment] 2015-12-30 00:33
Ok, excellent, @Klaim, thanks, glad it works. @Manu343726, could you please try again and check possible hanged up processes? Also, if you could tell us a bit more about your Win10, if you are using some AV... any clue that could help to reproduce the problem.

**Comment by Manu343726** [comment] 2015-12-30 01:18
Hi, I have tried again and it seems to be antivirus software related. I will try to make a fresh Windows 10 install in a VM to confirm this.

**Comment by memsharded** [comment] 2016-01-18 17:02
Manu, any news on this issue, or may I close this issue? Thanks!

**Comment by memsharded** [comment] 2016-02-05 09:23
Hi @Manu343726 , no news about this issue, and no other user has reported any  problem with the installer. I am closing the issue, please re-open if you find this problem again, thanks!

**Closed by memsharded** 2016-02-05 09:23 UTC
