### ISSUE TITLE
[question] several recipes in one conan.py ?

### ISSUE THREAD

**Issue by raffienficiaud** [conan-io/conan#3551] opened 2018-09-14 07:24 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Hi,

I am still new to conan since yesterday :) I again have a naive question. This time it is related to the organization of several versions of conan recipes, and I am trying to discover a nice and dead simple way to organize all this. 

Currently, what we are doing when we upgrade a conan recipe is the following:

1. we bump the version of the recipe
    ```
    class OpenCVConan(ConanFile):
       name = 'OpenCV'
       version = '3.4.2-0'
    ```
    becomes
    ```
    class OpenCVConan(ConanFile):
       name = 'OpenCV'
       version = '3.4.2-1'
    ```

1. then after review, we tag the repo containing the conan file with this new rev of the conan recipe
1. we update the consumers to
    1. checkout the proper tag
    1. consume this new version of the conan recipe

We are safe for reproducing a specific version of the final product. However, git tags and conan versions are redundant, and propagating an upgrade from upstream involves many changes in the dependency chain that are, IMO, difficult to handle. 

The difficulty comes from some design decision in the sense that each `conanfile.py` contains one and only one recipe at a specific revision. Checking the history of the different versions is made difficult by the fact that I do not see all the possible revs of the recipe. Also, since only one specific revision is exposed to the consumer in the repository, the semantic versioning - as a consumer - is made difficult.

What I was thinking is the following, and I was wondering if this is supported by conan. Say again I have the opencv recipe, that lies in `some-repo/opencv`. The `conanfile.py` would be something like this

```
# some-repo/opencv/conanfile.py
class OpenCVConan_342_0(ConanFile):
   name = 'OpenCV'
   version = '3.4.2-0'

class OpenCVConan_342_1(ConanFile):
   name = 'OpenCV'
   version = '3.4.2-1'

class OpenCVConan_475_0(ConanFile):
   name = 'OpenCV'
   version = '4.7.5-0'
```

Each specific revision would be immutable, and refactoring and code reuse would be eased (but carefully undertaken). As a consumer, I would see all the revisions of OpenCV in one place, and the change/upgrade of version would be easily promoted in the dependency chain.

This is a bit involving the features exposed there: https://docs.conan.io/en/latest/howtos/python_code_reuse.html#sharing-a-python-module without the need to split things in several files: all the recipes are in self contained file. If the file grows, then we can consider splitting it into several files. 

So, my question is: is this supported by conan already, in the sense that several revs will be exposed to the consumer? Is it a promoted practice or an interesting choice for managing a growing number of revisions? 

Thank you for your time,
Raffi

**Comment by memsharded** [comment] 2018-09-14 07:42
Hi @raffienficiaud 

I think these are closely related, but different questions. Let me comment on several things, including ongoing work:

- There is ongoing work on automatic revisioning. This means that the version remains inmmutable, but for every change in the recipe, or rebuild of the binaries, you get a new revision (which will be tagged by the git commit, or by the hash of the recipe contents, for example). This revisions accumulate in the server instead of overwriting (which is the default current behavior, if you keep the same version and do a ``conan upload`` without ``--no-overwrite``. In that way, builds will be reproducible down to the revision level. This should help with intensive CI re-builds.

- If it is just the version number you are bumping, but the rest of the recipe is the same, then you don't need to change the version in the recipe. Leave the ``version`` undefined and specify it in the command line (or CI), with ``conan create . Pkg/version@user/channel``.

- If you have logic that you want to automatically deduce the version from the branch name, a text file, or any other source, you can do it. Check this how-to: https://docs.conan.io/en/latest/howtos/capture_version.html#

Please tell me if these pointers help.

**Comment by raffienficiaud** [comment] 2018-09-14 09:38
Hi @memsharded ,

Thank you again for your quick reply. I am not sure to understand fully your reply, please let me explain further on your second bullet. 

Not only the version number is changed: the recipe changes as well, which may have consequences on the way the final binaries are built. For instance, 
* I removed the libtiff generation from the opencv recipe to make it optional. This may have an impact on consumers of the version `3.4.2-0` (new one being `3.4.2-1` ...) of this recipe since they need to handle a new option. 
* If I add Android support, but current consumers do not want to take the risk of sourcing something that is not very well tested, then they will stick to their `3.4.2-0`

OTOH, I want both version to be visible somehow, and consumers pick the one that they need/require. I also do not want to force them to update their repo to a specific version that discards all the previous ones. This is why I thought having them in the same `conanfile.py` would be a good solution. 

What do you think? Also, if this is supported, how would the tests refer to one specific version? The current layout is
```
test_package
  | conanfile.py
  | CMakeLists.txt (optional)
```
and in `test_package/conanfile.py`, we have this:
```
class OpenCVTest(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def imports(self):
        pass

    def test(self):
        pass
```

Is something like the following possible?
```
class OpenCVTest_342_0(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    requires = 'OpenCV/3.4.2-1@user/stable'

# this test will check that libtiff is properly pulled/required by OpenCV
# TIFF files should always be supported
class OpenCVTest_342_1(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"
    requires = 'OpenCV/3.4.2-1@user/stable'
    default_options = "OpenCV:tiff_support=True"
```

Thanks!
Raffi

**Comment by memsharded** [comment] 2020-08-27 23:26
Hi @raffienficiaud 

It has been a while since this issue. In this time we have learned the following:

- The model 1 conanfile - 1 package works quite well, it is clear and quite manageable.
- Typically, for your own recipes, they evolve in parallel with the code, in branches in source control. They are versioned, diffed, and merged in the same way as the source code is.
- It is possible to maintain a recipe that works for multiple versions. This is what we do right now in conan-center-index (https://github.com/conan-io/conan-center-index), which contain possibly much more difficult recipes that proprietary packages. 
- The utilities that have been built in this time, like hooks and conandata.yml, as well as maturing python_requires to extract common code, makes the maintenance of recipes easier.

So I would say we should keep with this approach, and several recipes at the same time in one conanfile.py shouldn't be allowed.
I am closing this issue by now, but please let me know if this makes sense and if you have any further question. Thanks!

**Closed by memsharded** 2020-08-27 23:26 UTC
Labels: type: question

**Comment by raffienficiaud** [comment] 2020-08-29 08:12
Thank you @memsharded for coming back to this. My experience of conan has also evolved since back then and I completely agree with you that there are means, as you mentioned, to address the issue.

Thanks you for your work!
