### ISSUE TITLE
[bug] invalid action for conan --version comman

### ISSUE THREAD

**Issue by blacksideOfMoon** [conan-io/conan#15782] opened 2024-02-29 11:32 UTC
### Environment details

Linux RHEL7
g++-8 (GCC) 8.4.0
Conan 2.0.13
Python 3.11.2

### Steps to reproduce

Create a database with Conan 2.1.0 on a shared folder
Move to a second system

Issue "conan --version" to get information on the current Conan version number (no other action)
=> Shared database is "downgraded" and hence destroyed:

WARN: Downgrading cache from Conan 2.1.0 to 2.0.13
Conan version 2.0.13

### Logs

$> conan --version
WARN: Downgrading cache from Conan 2.1.0 to 2.0.13
Conan version 2.0.13

**Comment by memsharded** [comment] 2024-02-29 11:47
Hi @blacksideOfMoon 

Thanks for your report.

I think this is expected, not a bug. The Conan cache is not designed to be shared please check https://docs.conan.io/2/knowledge/guidelines.html.

It is true that if there is no concurrency and strictly sequential access, it is possible to use the same cache from different Conan installation, but that at least should be using the same Conan version. There is a ``version.txt`` file in the cache (internal implementation detail, do not modify) that controls the Conan version for that cache, and if the Conan version changes, Conan can apply migrations both upgrades and downgrades.

**Comment by memsharded** [comment] 2024-03-08 15:34
The ticket https://github.com/conan-io/conan/issues/15840 will gather Conan cache concurrency. Still sharing a cache from different Conan versions will not be supported, it is basically impossible taking into account that there can be migrations up&down in the package cache.

Lets close this question as solved, but please open a new ticket if you have any other question. Thanks!

**Closed as completed by memsharded** 2024-03-08 15:34 UTC
Labels: type: question
