### ISSUE TITLE
[question] AutoToolsBuildEnvironment: rpath in LIBS?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#7133] opened 2020-06-02 12:13 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Does `AutoToolsBuildEnvironment` add `-Wl,-rpath="${libdir}"` in `LIBS` or `LDFLAGS` env var?

I've some issues for building `GDAL` as a shared lib with all dependencies also shared (there are something like 36 dependencies and transitive dependencies when everything is enabled).

It seems that the only directories added to rpath are those that have been captured by pkg config in GDAL's `configure.ac` (and manually added to `LIBS` if lib found).
Indeed, in pkg config generated files, I can see rpath in `Libs`, but it seems to be missing in global `LIBS`. But unfortunately, for most dependencies `GDAL` doesn't rely on pkg config.

https://github.com/conan-io/conan-center-index/pull/1722#issuecomment-637411674

Mmhh, on Linux with gcc, `self.output.info(AutoToolsBuildEnvironment(self, win_bash=tools.os_info.is_windows).vars)` for GDAL recipe gives:

```python
{
  'CPPFLAGS': '-I/home/spaceim/.conan/data/libtool/2.4.6/_/_/package/3b58f91cf243d00a450e8872166407e180480ab7/include -I/home/spaceim/.conan/data/json-c/0.13.1/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/libgeotiff/1.6.0/_/_/package/b98da5872f20ea44b4bee207c62cc0999cf6fc00/include -I/home/spaceim/.conan/data/flatbuffers/1.12.0/_/_/package/cbf3700a07e77fc094c00feba083e4a770f80834/include -I/home/spaceim/.conan/data/libpq/11.5/_/_/package/b41504ad1f472e62778f70021ee8af3f00b5d265/include -I/home/spaceim/.conan/data/cfitsio/3.470/_/_/package/160c0f76fcf1ad0d80837054bc0d59a5f4068208/include -I/home/spaceim/.conan/data/cfitsio/3.470/_/_/package/160c0f76fcf1ad0d80837054bc0d59a5f4068208/include/cfitsio -I/home/spaceim/.conan/data/libpng/1.6.37/_/_/package/160c0f76fcf1ad0d80837054bc0d59a5f4068208/include -I/home/spaceim/.conan/data/libgta/1.2.1/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/charls/2.1.0/_/_/package/cbf3700a07e77fc094c00feba083e4a770f80834/include -I/home/spaceim/.conan/data/giflib/5.1.4/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/hdf4/4.2.15/_/_/package/f7e594c78b86a0e3a59e1577eaee065cc6253934/include -I/home/spaceim/.conan/data/hdf4/4.2.15/_/_/package/f7e594c78b86a0e3a59e1577eaee065cc6253934/include/hdf4 -I/home/spaceim/.conan/data/hdf5/1.12.0/_/_/package/26f6d135a27fbe9802a9c9a126e5a9d5a18e614f/include -I/home/spaceim/.conan/data/hdf5/1.12.0/_/_/package/26f6d135a27fbe9802a9c9a126e5a9d5a18e614f/include/hdf5 -I/home/spaceim/.conan/data/jasper/2.0.16/_/_/package/970470e4087993e8b7c39313c180523776344fe0/include -I/home/spaceim/.conan/data/openjpeg/2.3.1/_/_/package/a1950b72e5ff2a8f82c543261a8720ef6d6fedce/include -I/home/spaceim/.conan/data/openjpeg/2.3.1/_/_/package/a1950b72e5ff2a8f82c543261a8720ef6d6fedce/include/openjpeg-2.3 -I/home/spaceim/.conan/data/libmysqlclient/8.0.17/_/_/package/2c4e520c152e1168e21f99cd13d84de04adbaabc/include -I/home/spaceim/.conan/data/xerces-c/3.2.2/_/_/package/cbf3700a07e77fc094c00feba083e4a770f80834/include -I/home/spaceim/.conan/data/libkml/1.3.0/_/_/package/33355a379b7549f4419a99e8d32853996de9a232/include -I/home/spaceim/.conan/data/odbc/2.3.7/_/_/package/10eefcce5d33c2e916cc374479b859fc7d035a04/include -I/home/spaceim/.conan/data/libxml2/2.9.10/_/_/package/3209e3d694b93935209e34721c93868ff0c2b291/include -I/home/spaceim/.conan/data/libxml2/2.9.10/_/_/package/3209e3d694b93935209e34721c93868ff0c2b291/include/libxml2 -I/home/spaceim/.conan/data/pcre/8.41/_/_/package/6509b45e2b1d7170f6067f254d7bc425769ad2df/include -I/home/spaceim/.conan/data/geos/3.8.1/_/_/package/5ebede979d200907e8167dc1e744cb66e7d859b2/include -I/home/spaceim/.conan/data/qhull/7.3.2/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/openexr/2.4.0/_/_/package/bcbf8c37b4d22c640b812bd710553febb7aeb3c3/include/OpenEXR -I/home/spaceim/.conan/data/openexr/2.4.0/_/_/package/bcbf8c37b4d22c640b812bd710553febb7aeb3c3/include -I/home/spaceim/.conan/data/proj/7.0.0/_/_/package/4765e01d8575d0d0b70a1fb8097968942268f709/include -I/home/spaceim/.conan/data/libiconv/1.16/_/_/package/2af715f34a7c8c2aeae57b25be0a52c4110dc502/include -I/home/spaceim/.conan/data/expat/2.2.9/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/boost/1.72.0/_/_/package/524ea35a8120baabdde02483add58d81bf541327/include -I/home/spaceim/.conan/data/minizip/1.2.11/_/_/package/15aa8f6db439be60f9c27a4867ad9e97da3ccc6c/include -I/home/spaceim/.conan/data/minizip/1.2.11/_/_/package/15aa8f6db439be60f9c27a4867ad9e97da3ccc6c/include/minizip -I/home/spaceim/.conan/data/uriparser/0.9.3/_/_/package/73963db13054a591c83d6c62de5593cc06016751/include -I/home/spaceim/.conan/data/libtiff/4.1.0/_/_/package/3d5f027b26eab5706cd0c17ef15451e62e078516/include -I/home/spaceim/.conan/data/sqlite3/3.31.1/_/_/package/5484afa79415ecf27e813998b4b500256dac1d93/include -I/home/spaceim/.conan/data/libcurl/7.70.0/_/_/package/dde811b31a1f6ebea031882d8636c96a6a24a771/include -I/home/spaceim/.conan/data/bzip2/1.0.8/_/_/package/5d54a70bb533a8690c393758cc17500c2c89e984/include -I/home/spaceim/.conan/data/zlib/1.2.11/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/xz_utils/5.2.4/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/libjpeg/9d/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/jbig/20160605/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/zstd/1.4.5/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -I/home/spaceim/.conan/data/libwebp/1.1.0/_/_/package/c86c0ee2a89aa153eca800434f7e9ec8ca1e7944/include -I/home/spaceim/.conan/data/openssl/1.1.1g/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/include -DHAVE_BZIP2 -D_GLIBCXX_USE_CXX11_ABI=1 -DGEOS_INLINE -DH5_BUILT_AS_DYNAMIC_LIB -DH4_BUILT_AS_DYNAMIC_LIB -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=1',
  'CXXFLAGS': '-m64 -O3 -s -fPIC',
  'CFLAGS': '-m64 -O3 -s -fPIC',
  'LDFLAGS': '-m64 -L/home/spaceim/.conan/data/libtool/2.4.6/_/_/package/3b58f91cf243d00a450e8872166407e180480ab7/lib -L/home/spaceim/.conan/data/json-c/0.13.1/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/libgeotiff/1.6.0/_/_/package/b98da5872f20ea44b4bee207c62cc0999cf6fc00/lib -L/home/spaceim/.conan/data/flatbuffers/1.12.0/_/_/package/cbf3700a07e77fc094c00feba083e4a770f80834/lib -L/home/spaceim/.conan/data/libpq/11.5/_/_/package/b41504ad1f472e62778f70021ee8af3f00b5d265/lib -L/home/spaceim/.conan/data/cfitsio/3.470/_/_/package/160c0f76fcf1ad0d80837054bc0d59a5f4068208/lib -L/home/spaceim/.conan/data/libpng/1.6.37/_/_/package/160c0f76fcf1ad0d80837054bc0d59a5f4068208/lib -L/home/spaceim/.conan/data/libgta/1.2.1/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/charls/2.1.0/_/_/package/cbf3700a07e77fc094c00feba083e4a770f80834/lib -L/home/spaceim/.conan/data/giflib/5.1.4/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/hdf4/4.2.15/_/_/package/f7e594c78b86a0e3a59e1577eaee065cc6253934/lib -L/home/spaceim/.conan/data/hdf5/1.12.0/_/_/package/26f6d135a27fbe9802a9c9a126e5a9d5a18e614f/lib -L/home/spaceim/.conan/data/jasper/2.0.16/_/_/package/970470e4087993e8b7c39313c180523776344fe0/lib -L/home/spaceim/.conan/data/openjpeg/2.3.1/_/_/package/a1950b72e5ff2a8f82c543261a8720ef6d6fedce/lib -L/home/spaceim/.conan/data/libmysqlclient/8.0.17/_/_/package/2c4e520c152e1168e21f99cd13d84de04adbaabc/lib -L/home/spaceim/.conan/data/xerces-c/3.2.2/_/_/package/cbf3700a07e77fc094c00feba083e4a770f80834/lib -L/home/spaceim/.conan/data/libkml/1.3.0/_/_/package/33355a379b7549f4419a99e8d32853996de9a232/lib -L/home/spaceim/.conan/data/odbc/2.3.7/_/_/package/10eefcce5d33c2e916cc374479b859fc7d035a04/lib -L/home/spaceim/.conan/data/libxml2/2.9.10/_/_/package/3209e3d694b93935209e34721c93868ff0c2b291/lib -L/home/spaceim/.conan/data/pcre/8.41/_/_/package/6509b45e2b1d7170f6067f254d7bc425769ad2df/lib -L/home/spaceim/.conan/data/geos/3.8.1/_/_/package/5ebede979d200907e8167dc1e744cb66e7d859b2/lib -L/home/spaceim/.conan/data/qhull/7.3.2/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/openexr/2.4.0/_/_/package/bcbf8c37b4d22c640b812bd710553febb7aeb3c3/lib -L/home/spaceim/.conan/data/proj/7.0.0/_/_/package/4765e01d8575d0d0b70a1fb8097968942268f709/lib -L/home/spaceim/.conan/data/libiconv/1.16/_/_/package/2af715f34a7c8c2aeae57b25be0a52c4110dc502/lib -L/home/spaceim/.conan/data/expat/2.2.9/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/minizip/1.2.11/_/_/package/15aa8f6db439be60f9c27a4867ad9e97da3ccc6c/lib -L/home/spaceim/.conan/data/uriparser/0.9.3/_/_/package/73963db13054a591c83d6c62de5593cc06016751/lib -L/home/spaceim/.conan/data/libtiff/4.1.0/_/_/package/3d5f027b26eab5706cd0c17ef15451e62e078516/lib -L/home/spaceim/.conan/data/sqlite3/3.31.1/_/_/package/5484afa79415ecf27e813998b4b500256dac1d93/lib -L/home/spaceim/.conan/data/libcurl/7.70.0/_/_/package/dde811b31a1f6ebea031882d8636c96a6a24a771/lib -L/home/spaceim/.conan/data/bzip2/1.0.8/_/_/package/5d54a70bb533a8690c393758cc17500c2c89e984/lib -L/home/spaceim/.conan/data/zlib/1.2.11/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/xz_utils/5.2.4/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/libjpeg/9d/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/jbig/20160605/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/zstd/1.4.5/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib -L/home/spaceim/.conan/data/libwebp/1.1.0/_/_/package/c86c0ee2a89aa153eca800434f7e9ec8ca1e7944/lib -L/home/spaceim/.conan/data/openssl/1.1.1g/_/_/package/43210353fd7084c5b95e27c1675921b6024a3e6d/lib',
  'LIBS': '-ljson-c -lgeotiff -lflatbuffers -lpgcommon -lpq -lcfitsio -lpng16 -lgta -lcharls -lgif -lmfhdf -lxdr -lhdf -lhdf5_hl_cpp -lhdf5_hl -lhdf5_cpp -lhdf5 -ljasper -lopenjp2 -lmysqlclient -lxerces-c -lxerces-c-3.2 -lkmlregionator -lkmlconvenience -lkmlengine -lkmldom -lkmlxsd -lkmlbase -lodbc -lodbccr -lodbcinst -lltdl -ldl -lxml2 -lm -lpcreposix -lpcre -lgeos_c -lgeos -lqhull -lIlmImf-2_4 -lIlmImfUtil-2_4 -lIlmThread-2_4 -lIex-2_4 -lIexMath-2_4 -lImath-2_4 -lHalf-2_4 -lproj -liconv -lcharset -lexpat -lminizip -luriparser -ltiffxx -ltiff -lsqlite3 -lcurl -lbz2 -lz -llzma -ljpeg -ljbig -lzstd -lwebpmux -lwebpdemux -lwebpdecoder -lwebp -lssl -lcrypto -lrt -lm -ldl -lpthread'
}
```

So, nothing related to `-Wl,-rpath="${libdir}"` while pkg config files generated by conan genarator add those values.
For example, here is `cfitsio.pc` generated by conan:

```
prefix=/home/spaceim/.conan/data/cfitsio/3.470/_/_/package/160c0f76fcf1ad0d80837054bc0d59a5f4068208
libdir=${prefix}/lib
includedir=${prefix}/include
includedir3=${prefix}/include/cfitsio

Name: cfitsio
Description: C library for reading and writing data files in FITS (Flexible Image Transport System) data format
Version: 3.470
Libs: -L${libdir} -lcfitsio  -lm  -Wl,-rpath="${libdir}"
Cflags: -I${includedir} -I${includedir3}
Requires: zlib
```

**Comment by SpaceIm** [comment] 2020-06-04 09:42
I add to use this trick to make it work:
https://github.com/conan-io/conan-center-index/blob/6e1a766406f610a1c3394e247036ef35cff07270/recipes/gdal/all/conanfile.py#L588

(there is also another trick in this code related to https://github.com/conan-io/conan/issues/7109)

```python
        # Some tricks in LDFLAGS env variable
        env_build_vars = self._autotools.vars
        if self.settings.os == "Linux":
            # Inject lib directories in rpath in case of shared dependencies
            rpath = ""
            for libdir in self.deps_cpp_info.libdirs:
                rpath += " -Wl,-rpath=\"{}\"".format(libdir)
            env_build_vars["LDFLAGS"] = env_build_vars["LDFLAGS"] + rpath
            # Inject -stdlib=libc++ for clang with libc++
            if self.settings.compiler == "clang" and self._stdcpp_library == "c++":
                env_build_vars["LDFLAGS"] = "-stdlib=libc++ " + env_build_vars["LDFLAGS"]

        with tools.chdir(configure_dir):
            self._autotools.configure(args=args, vars=env_build_vars)
        return self._autotools
```

**Comment by Artalus** [comment] 2020-06-04 10:09
My 5 cents  from my understanding of http://www.kaizou.org/2015/01/linux-libraries.html (Ctrl+F to `Doing it the right way`) and tinkering with https://github.com/bincrafters/conan-x11 and https://github.com/bincrafters/conan-qt .

There seems to be an "approach" in Linux buildsystems, that when some C is built `-lB`, and B was built with `-lA`, then it is not necessary for C to also use `-lA`. Linker (that usually relies on everything installed in the same path, ofen `/usr/lib`) will look intl `libB.so`, see `DT_NEEDED` entry for `libA.so`, detect it in some default path, and happily link against it too.

However in this case, if your B is not located in default search paths, then providing `-L/path/to/libdir` won't help with resolving A, you'd have to also provide `-rpath-link=/path/to/libdir` so the "secondary" dependency would also be found.

It also seems that Conan's approach is fundamentally different from the one most Linux libs expect.  Instead of single `/path/to/libdir` Conan provides `/path/to/A/dir` and `/path/to/B/dir`. Thus even if the library buildsystem is written in such way that it correctly handles `-rpath-link`, it won't help it much, since it'd actually need `-L/path/to/B/dir -rpath-link=/path/to/A/dir`.

From my experience, this seems to be the problem with X11 libraries. Example: `xkbcommon` requires `xcb`. `xcb` is linked against `xau`. However, `xcb`'s pkgconfig does not provide such info, considering `xau` a private dependency. Then, since these three libraries are currently provided as separate libraries, there will be three separate paths to search for `.so` files. If something requires `xkbcommon`, it will successfully link against it, and against `xcb`, but will fail to link against `xau`, since there won't be `-lxau` neigher `-rpath-link=/path/to/xau/`, only `-L/path/to/xau` from Conan.

So it seems to me that the problem is somewhat wider then AutoToolsBuildEnviroment. I can suppose that mayhaps Conan should always provide `-Wl,-rpath-link` along with `-L`.

**Comment by SpaceIm** [comment] 2020-06-04 13:51
It appears that for the specific case of GDAL:
- By default, GDAL build system relies on libtool
- First it builds the big library `libgdal.la`, intended to be linked into executables.
- In one file included by its makefiles, it defines a variable (CONFIG_LIBS) intended to be used for executables link. If using libtool, this variable doesn't contain $(LIBS). So it relies on inter-dependency of libtool (I'm not familiar with this, but I guess that `libgdal.la` should contain everything that is needed).

For some reason, if dependencies of libgdal are shared, it breaks.

Unconditionally adding $(LIBS) to this variable solved everything, no need to add `-rpath` or `-rpath-link`.

**Closed as completed** 2020-06-12 17:52 UTC
