### ISSUE TITLE
Migrating the recipe to Conan 2.0, getting an error in the Ninja generator

### ISSUE THREAD

**Issue by ujjwal1002** [conan-io/conan#15076] opened 2023-11-09 00:29 UTC
### What is your question?

Hi,

I am really new to the Conan developer framework,I wish to migrate my recipe to Conan 2, not sure how I can use Ninja with CMake, could you please help?

I am getting the following error

*********************************************************
Recipe 'conanfile.py (InterviewPrep/1.1.0)' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: conanfile.py (InterviewPrep/1.1.0): Error in build() method, line 59
        cmake.build()
        ConanException: Error 1 while executing

-------------------------------------------------------------------------------------------------------
conanfile.py
-------------------------------------------------------------------------------------------------------

```python
from conan import ConanFile
from conan.tools.cmake import CMake,CMakeToolchain,CMakeDeps,cmake_layout

from functools import lru_cache


class InterviewPrepConan(ConanFile):
    name = "InterviewPrep"
    version = "1.1.0"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of Mylib here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False],}
    default_options = {"shared": False, "fPIC": True} # if shared is true, we would have this as a shared library
    
    generators="CMakeDeps","CMakeToolchain"
    exports_sources = (
        "CMakeLists.txt"
    )
    no_copy_source = True
    #The below method would be triggered iff you unset the no_copy_source variable
    #def export_source(self):
    #    self.copy("*")
    
#    def build_requirements(self):
#        self.build_requires("C:\DevSoft\Ninja\ninja-win")
    #def layout(self): # run this after adding cmake install code
        #cmake_layout(self,src_folder=self.source_folder)
    def test_requirements(self):
        self.test_requires("gtest/1.12.1")
    @property
    @lru_cache(1)
    def _cmake(self):
        cmake = CMake(self)
        if self.options.coverage:
            cmake.definitions["COVERAGE"]=True
        return cmake
    def build_requirements(self):
        self.requires("boost/1.79.0")
        self.requires("systemc/2.3.3")
        self.requires("magic_enum/0.8.1",override=True)
        self.requires("dlib/19.24")
        self.requires("hdf5/1.13.1")
        self.requires("xtensor/0.24.2")
        ##self.requires("SystemCVerification/2.0.1@minres/stable")
    def config_options(self):
        if self.settings.os == "Windows":
            del self.options.fPIC
    def generator(self): #Preprocessor
        tc = CMakeToolchain(self)
        tc.generate()
        CMakeDeps(self).generate() #creates findBoost.cmake

    def build(self):
        cmake = CMake(self,generator='Ninja')
        cmake.configure(source_folder=self.source_folder)
        cmake.build()
        cmake.test(build_dir=self.build_folder,output_on_failure=True)
        # Explicit way:
        # self.run('cmake %s/hello %s'
        #          % (self.source_folder, cmake.command_line))
        # self.run("cmake --build . %s" % cmake.build_config)

    def package(self):
        self._cmake.install()
    def package_id(self):
        self.info.requires["systemc"].full_package_mode()
    def package_info(self):
        self.cpp_info.libs = ["hello"] 
```
### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-11-09 00:39
Hi @ujjwal1002 

Thanks for your question. 
There are a few issues in your code:

- The ``def generator(self): #Preprocessor`` is incorrect. The method is called ``generate()``
- Also, you shouldn't be using ``self.requires("boost/1.79.0")`` inside ``build_requirements()`` method, but inside ``requirements()`` method.
- Don't use ``@lru_cache(1)``,  or the method ``_cmake`` property, this is not necessary at all.
- It is very likely that recipe will not work if you are not exporting the source code, .cpp etc, together with the CMakeLists.txt ``exports_sources``
- You probably don't need ``full_package_mode`` in Conan 2.0, as the package_id computation is better.
- The ``build()`` method seems wrong, all helpers receiving unexisting arguments, that will fail.

I suggest starting from the recipe that works ``conan new cmake_lib -d name=pkg -d version=0.1`` and iterate step by step to adapt it to your code, adding one dependency at a time too.

**Comment by ujjwal1002** [comment] 2023-11-09 00:44
Thank You @memsharded , I will start with what you've proposed. Thanks.

**Comment by ujjwal1002** [comment] 2023-11-09 01:59
HI @memsharded 

I followed your advice and it seems I am still not able to get a hang of it, my build system is still using MSVC instead of Ninja

Any suggestions on what I should change in the build process?


here's my profile, conanfile.py and the rest are the same as the default generated after conan new cmake_lib -d name=pkg -d version=0.1
------------------
[settings]
    os=Windows
    arch=x86_64
    compiler=gcc
    compiler.version=9.2
	compiler.cppstd=17
    compiler.libcxx=libstdc++11
    build_type=Debug
	general.cmake_generator=Ninja
[options]

------------------

**Comment by memsharded** [comment] 2023-11-09 10:59
This profile is incorrect:
```
[settings]
os=Windows
arch=x86_64
compiler=gcc
compiler.version=9.2
compiler.cppstd=17
compiler.libcxx=libstdc++11
build_type=Debug
general.cmake_generator=Ninja
```
You are adding an old-style configuration that was intended for ``conan.conf`` in the profile. This no longer exist.
You should be using new confs. Check them with:
- ``conan config list``
- https://docs.conan.io/2/reference/config_files/global_conf.html

**Comment by AbrilRBS** [comment] 2024-05-08 11:52
Closing as we didn't hear back from you in a while, please feel free to reopen/create a new issue should you have any more questions, thanks! :)

**Closed as completed by AbrilRBS** 2024-05-08 11:52 UTC
