### ISSUE TITLE
Best method to support visual studio 2008 with conan

### ISSUE THREAD

**Issue by sturmf** [conan-io/conan#1697] opened 2017-09-01 15:34 UTC
I unfortunately need to support builds with Visual Studio 2008 and would like to use conan for dependencies with those projects.

As far as I understand the visual_studio generator only creates props files that can be consumed by Visual Studio 2010 and upwards?

Therefore my question, what would be the best way to support this combination?

**Comment by lasote** [comment] 2017-09-01 16:11
The first step will be to understand how Visual Studio 2008 is able to import from a file the include directories, library directories, lib names etc. Then, if a property file or similar is suitable, understand the format and write a generator for it.

**Comment by memsharded** [comment] 2017-09-01 19:27
The process would be exactly the same as the current generator, generating a ``conanbuildinfo.props`` file, just the XML has a different syntax.

**Comment by SSE4** [comment] 2017-09-02 10:11
@sturmf you also can try to use CMake, which is able to generate Visual Studio 2008 solutions (or even 2005, 2003, etc)

**Comment by sturmf** [comment] 2017-09-04 16:25
Hi, thanks for the tips, I now created this pull request for a simple vs 2008 generator. So I guess this issue here can be closed and everything else can be discussed in the pull request?

https://github.com/conan-io/conan/pull/1704

**Comment by memsharded** [comment] 2017-09-04 16:47
No, the issue is good open, until it is released. So the flow is:
- Issue open, until the feature is totally released.
- When a PR is accepted, the issue is marked as fixed
- When the release including the PR commits is released, the issue is closed.

Thanks!

**Closed** 2017-09-20 20:25 UTC
Labels: enhancement, fixed
