### ISSUE TITLE
Invalid path to dependency

### ISSUE THREAD

**Issue by krojew** [conan-io/conan#748] opened 2016-12-09 07:53 UTC
Hi,
I cannot seem to make conan properly define the library path for built dependency. Suppose there's no prebuilt package for my configuration, so I use --build when installing:

conan install --build DependencyName

conan properly builds everything and the resulting library is in ~/.conan/data/.../build/HASH/libDependncyName.so

But when I then try to build the project:

conan build

The library path is set to ~/.conan/data/.../package/HASH/lib instead of ~/.conan/data/.../build/HASH and the build fails. I see there's no way to manually override this from the cli. Or am I missing something?

**Comment by memsharded** [comment] 2016-12-09 10:19
Hi @krojew ,

I would need more data about your setup. If you could share please:
- The conanfile.py of the DependencyName
- The conanfile.py of the consumer (the one you run build())
- The output of both commands

If public, github link is ok. If not public, you can also send privately by email.

The resulting library of the install should be in a similar path, but replacing "build" => "package". Maybe something is missing in your recipe package() method, but I'd need to have a look.  Thanks for your feedback!

**Comment by krojew** [comment] 2016-12-09 10:22
The library I wish to build is https://gitlab.com/CxxProf/cxxprof_preloader and the dependency is Pluma/1.1@monsdar/testing. I simply run conan install --build which builds Pluma without any errors, and then conan build, which in turn sets invalid lib path to Pluma and the build fails.

**Comment by memsharded** [comment] 2016-12-16 09:16
Thanks for telling, I am checking it right now.

**Comment by memsharded** [comment] 2016-12-16 09:31
It works for me, with both workflows, both building locally, as you explain, and as a package. My setup is Win10, VS14u4, Release, 64 bits:

```bash
$ git clone https://gitlab.com/CxxProf/cxxprof_preloader.git
$ cd cxxprof_preloader
$ conan install --build
$ conan build
```

Also, as a package:
```bash
$ git clone https://gitlab.com/CxxProf/cxxprof_preloader.git
$ cd cxxprof_preloader
$ conan export user/channel
$ conan install cxxprof_preloader/1.1.1@user/channel --build
```

have you fixed something recently? Can you please verify the above steps? Also, if still failing please copy the output here. Thanks!

**Comment by krojew** [comment] 2016-12-16 09:37
Just checked and got this output:

> git clone https://gitlab.com/CxxProf/cxxprof_preloader.git
> Cloning into 'cxxprof_preloader'...
> remote: Counting objects: 49, done.
> remote: Compressing objects: 100% (29/29), done.
> remote: Total 49 (delta 21), reused 39 (delta 16)
> Unpacking objects: 100% (49/49), done.
> Checking connectivity... done.
> ~$ cd cxxprof_preloader
> ~/cxxprof_preloader$ ~/.local/bin/conan install --build
> WARN: config() has been deprecated. Use config_options and configure
> Requirements
>     Pluma/1.1@monsdar/testing from conan.io
> Packages
>     Pluma/1.1@monsdar/testing:5f1f71e5f81572eb63e3ce82c8c876a9e189d77b
> 
> Pluma/1.1@monsdar/testing: Installing package 5f1f71e5f81572eb63e3ce82c8c876a9e189d77b
> Pluma/1.1@monsdar/testing: WARN: Forced build from source
> Pluma/1.1@monsdar/testing: Building your package in /home/krojew/.conan/data/Pluma/1.1/monsdar/testing/build/5f1f71e5f81572eb63e3ce82c8c876a9e189d77b
> Pluma/1.1@monsdar/testing: Copying sources to build folder
> Pluma/1.1@monsdar/testing: Generated cmake created conanbuildinfo.cmake
> -- The C compiler identification is GNU 6.2.0
> -- The CXX compiler identification is GNU 6.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Configuring done
> -- Generating done
> CMake Warning:                                                                                                                                                                                                                                                                                                              
>   Manually-specified variables were not used by the project:                                                                                                                                                                                                                                                                
>                                                                                                                                                                                                                                                                                                                             
>     CONAN_COMPILER                                                                                                                                                                                                                                                                                                          
>     CONAN_COMPILER_VERSION                                                                                                                                                                                                                                                                                                  
>     CONAN_LIBCXX                                                                                                                                                                                                                                                                                                            
>                                                                                                                                                                                                                                                                                                                             
>                                                                                                                                                                                                                                                                                                                             
> -- Build files have been written to: /home/krojew/.conan/data/Pluma/1.1/monsdar/testing/build/5f1f71e5f81572eb63e3ce82c8c876a9e189d77b                                                                                                                                                                                      
> Scanning dependencies of target Pluma                                                                                                                                                                                                                                                                                       
> [ 16%] Building CXX object CMakeFiles/Pluma.dir/Pluma-1.1/src/Pluma/DLibrary.cpp.o                                                                                                                                                                                                                                          
> [ 33%] Building CXX object CMakeFiles/Pluma.dir/Pluma-1.1/src/Pluma/Dir.cpp.o                                                                                                                                                                                                                                               
> [ 50%] Building CXX object CMakeFiles/Pluma.dir/Pluma-1.1/src/Pluma/Host.cpp.o                                                                                                                                                                                                                                              
> [ 66%] Building CXX object CMakeFiles/Pluma.dir/Pluma-1.1/src/Pluma/PluginManager.cpp.o                                                                                                                                                                                                                                     
> [ 83%] Building CXX object CMakeFiles/Pluma.dir/Pluma-1.1/src/Pluma/Provider.cpp.o                                                                                                                                                                                                                                          
> [100%] Linking CXX shared library libPluma.so                                                                                                                                                                                                                                                                               
> [100%] Built target Pluma                                                                                                                                                                                                                                                                                                   
>                                                                                                                                                                                                                                                                                                                             
> Pluma/1.1@monsdar/testing: Package '5f1f71e5f81572eb63e3ce82c8c876a9e189d77b' built                                                                                                                                                                                                                                         
> Pluma/1.1@monsdar/testing: Build folder /home/krojew/.conan/data/Pluma/1.1/monsdar/testing/build/5f1f71e5f81572eb63e3ce82c8c876a9e189d77b                                                                                                                                                                                   
> Pluma/1.1@monsdar/testing: Generated conaninfo.txt                                                                                                                                                                                                                                                                          
> Pluma/1.1@monsdar/testing: Generated conanbuildinfo.txt                                                                                                                                                                                                                                                                     
> Pluma/1.1@monsdar/testing: Generated conanenv.txt                                                                                                                                                                                                                                                                           
> Pluma/1.1@monsdar/testing: Generating the package                                                                                                                                                                                                                                                                           
> Pluma/1.1@monsdar/testing: Package folder /home/krojew/.conan/data/Pluma/1.1/monsdar/testing/package/5f1f71e5f81572eb63e3ce82c8c876a9e189d77b                                                                                                                                                                               
> Pluma/1.1@monsdar/testing package(): Copied 1 '.inl' files: Pluma.inl                                                                                                                                                                                                                                                       
> Pluma/1.1@monsdar/testing package(): Copied 6 '.hpp' files                                                                                                                                                                                                                                                                  
> Pluma/1.1@monsdar/testing: Package '5f1f71e5f81572eb63e3ce82c8c876a9e189d77b' created                                                                                                                                                                                                                                       
> PROJECT: Generated cmake created conanbuildinfo.cmake                                                                                                                                                                                                                                                                       
> PROJECT: Generated conaninfo.txt                                                                                                                                                                                                                                                                                            
> ~/cxxprof_preloader$ ~/.local/bin/conan build
> Project: WARN: conanbuildinfo.txt file not found in /home/krojew/cxxprof_preloader
> It is recommended for this command
> You can generate it using 'conan install -g txt'
> Project: WARN: conanenv.txt file not found in /home/krojew/cxxprof_preloader
> It is recommended for this command
> You can generate it using 'conan install -g env'
> -- The C compiler identification is GNU 6.2.0
> -- The CXX compiler identification is GNU 6.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Conan C++ stdlib: libstdc++
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/krojew/cxxprof_preloader
> Scanning dependencies of target cxxprof_preloader
> [ 50%] Building CXX object CMakeFiles/cxxprof_preloader.dir/src/CxxProfPreloader.cpp.o
> [100%] Linking CXX shared library libcxxprof_preloader.so
> /usr/bin/ld: cannot find -lPluma
> collect2: error: ld returned 1 exit status
> CMakeFiles/cxxprof_preloader.dir/build.make:94: polecenia dla obiektu 'libcxxprof_preloader.so' nie powiodły się
> make[2]: *** [libcxxprof_preloader.so] Błąd 1
> CMakeFiles/Makefile2:67: polecenia dla obiektu 'CMakeFiles/cxxprof_preloader.dir/all' nie powiodły się
> make[1]: *** [CMakeFiles/cxxprof_preloader.dir/all] Błąd 2
> Makefile:127: polecenia dla obiektu 'all' nie powiodły się
> make: *** [all] Błąd 2
> ERROR: Error 512 while executing cmake --build .

**Comment by memsharded** [comment] 2016-12-16 09:47
For what I am seeing, it seems the Pluma package might be failing to ``package()`` properly. Moving to Linux to check it, thanks for reporting!

**Comment by memsharded** [comment] 2016-12-16 10:40
Yes, it looks like that the Pluma package is only prepared for Windows, so it was failing in linux. I have submitted a PR to the package creator with linux support (and test_package too): https://github.com/monsdar/pluma-cmake/pull/1

In case the package creator is busy and might take a while to merge it, if you want to create your own package for Pluma, that is fairly easy, you could try from my recipe, ask for help if necessary.

**Comment by krojew** [comment] 2016-12-16 10:55
Maybe it would be a good idea to add some flags to conan to force specific lib dir for a given package?

**Comment by memsharded** [comment] 2016-12-16 11:25
Not sure what you mean about the "specific dir" for a given package, could you please elaborate a bit further. Thanks!

**Comment by krojew** [comment] 2016-12-16 11:29
In this specific example, the only way to work around the problem is either to fix the dependency either by the author or manually. It would be better to just be able to specify a flag or configuration variable for conan, to make it look for the library in a specific directory. If I know a library was created but resides in an incorrect directory, I could in a fast and convenient way simply tell conan to look there.

**Comment by memsharded** [comment] 2016-12-16 11:44
No, that is not the problem. The issue is not the library being in another folder, the problem is that in Linux, the library is not packaged at all. It is built, but lately ignored. It cannot be linked from the build directory, because that directory will not exist when compiling using the precompiled package.

Even if the library was in a wrong folder in the package, that is not a big issue for the consumer, of course you can consume it, just by adding the proper name or path inside your build (e.g. cmake) script, not necessary to add flags to conan. Example:

- The package creator has made a mistake:

```python
def package_info(self):
     self.cpp_info.libs = ["MyLibX"]  # But the lib name is actually MyLib
```

Instead of using ``${CONAN_LIBS}`` in cmake, which will be an error because it will be ``MyLibX``, just do:

```cmake
target_link_libraries(myapp PRIVATE MyLib)
````

**Comment by krojew** [comment] 2016-12-16 13:34
From a purely pragmatic point of view, that leaves us in a bit of a problematic situation:

1. A project requires cmake and conan to be built.
1. One of its dependencies is built by conan, but it's packaging is broken.
1. The only way to fix this is to either fix the dependency or not use conan.

The question then becomes is using conan worth it in such situations? If it's easier (but not necessarily better) to not use it at all, I think that's a core conan issue, given that the dependency builds and the project might also build without it.

**Comment by memsharded** [comment] 2016-12-16 14:14
I think that any other package manager in the world, if a package is broken, it is broken, there is probably no way to use it. There are several degrees of "broken", it is totally possible that there are bugs in the source code that define the package, so it never gets built. It might have a totally broken package recipe.

My explanation above explains that even if the packaging might have bugs, and it is broken, it is still very possible to consume the package from downstream, without having to modify the dependency. Maybe I didn't explain it properly, but the code above shows that you can actually consume a broken package. Similar examples could be done for consuming a broken package regarding to the paths where artifacts are stored within the package.

You can mix dependencies from conan and other origins. Of course if the project only has 1 dependency, and the package existing in conan.io is broken, it is not worth to use conan at all. But if a project has 20 dependencies and 1 is broken, just dont use that one, you can still consume it from your system as always, and use the other 19 dependencies from conan.

There are two very different things here:

- One is conan, the core package manager. It can have issues, problems, and bugs. And can certainly be improved. It is the dev tool, like git
- Other thing are the conan packages existing in conan.io, that are created by the community and they vary in quality. The tools is not responsible to address any possible problem that the packages might have, exactly the same as if git doesn't have to fix the bugs or problems that repos in github might have. If a conan package, or a github repository is broken, then it should be fixed, contributed with a PR, forked, or whatever

Actually, to be clear, the most heavy usage of conan is not in the public domain, not using conan.io. It is done by companies, using in-house hosted conan_server, when they have full control of their builds, so this is usually not a problem, if a package is broken, it gets fixed.

**Comment by monsdar** [comment] 2016-12-17 12:53
Hey guys, creator of CxxProf here.

I made the packages for CxxProf and its dependencies a while ago to test out Conan. I did not intend to create fully-featured packages, that's also the reason why they're still under `monsdar/testing` (emphasis on `testing`. I was only working on my Windows machine, so it's not surprising that Linux support is lacking.

This is of course not a problem of Conan itself. It's simply the fact that I did not create more polished package recipes. CxxProf is OSS and a hobby project of mine. If there's no time to do stuff, then I need to set my priorities. To be honest I wasn't aware that CxxProf is really in use - nice to see that :)
 
@krojew feel free to contribute fixes for the packages either on [Github](https://github.com/monsdar/pluma-cmake) (for things like Pluma, Sqlite3cc etc) or [Gitlab](https://gitlab.com/CxxProf) (for CxxProf itself).

**Comment by krojew** [comment] 2016-12-17 12:59
@monsdar unfortunately, I had to give up on using cxxprof and create my own profiling framework because of the build issues. Nevertheless, I encourage you to keep working on it since it seems to be a very useful library.

**Comment by monsdar** [comment] 2016-12-17 13:04
That's sad to hear... Will you make your profiling framework available as OSS? Do you plan on supporting Conan?

You notice that something's obviously not working right when people invent their own solutions because the existing solutions aren't usable because of the build system -.-

**Comment by krojew** [comment] 2016-12-17 13:08
I'm actually thinking about releasing it. It's similar to cxxprof although with some more features and a Qt gui.

And I do agree - if the cost of doing something from the ground up is lower than fixing a package in a build system - something is very wrong.

**Closed** 2018-06-29 11:21 UTC
