### ISSUE TITLE
[bug] Error preparing cmake for multi-configuration use: Duplicate preset: "conan-default"

### ISSUE THREAD

**Issue by schwaerz** [conan-io/conan#14979] opened 2023-10-19 18:16 UTC
### Environment details

* Operating System+version: Win11 22H2
* Compiler+version: msvc17 193
* Conan version: 2.0.13
* Python version: 3.11.1
* CMake 3.27.7

### Steps to reproduce

First, please ensure to have Conan 2.0.13 and a recent CMake in the path.

Then, just run `./reproduce.sh` from the attached [hello world example](https://github.com/conan-io/conan/files/13046233/hello-world.zip). It will:

1. Install the attached conan config
2. Install dependencies using the debug profile
3. Install dependencies using the release profile
4. call `cmake --preset conan-default`

### Logs

```
$ ./reproduce.sh 
Copying file windows to C:\Users\schwaerz\.conan2\profiles
Copying file windows_x86 to C:\Users\schwaerz\.conan2\profiles
Copying file windows_x86_msvc17 to C:\Users\schwaerz\.conan2\profiles
Copying file windows_x86_msvc17_debug to C:\Users\schwaerz\.conan2\profiles
Copying file windows_x86_msvc17_release to C:\Users\schwaerz\.conan2\profiles

======== Input profiles ========
Profile host:
[settings]
arch=x86
build_type=Debug
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Debug
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.py (HelloWorld/1.2.3.4): C:\repositories\hello-world\conanfile.py

======== Computing necessary packages ========

======== Installing packages ========

======== Finalizing install (deploy, generators) ========
conanfile.py (HelloWorld/1.2.3.4): Writing generators to C:\repositories\hello-world\build-debug\conan      
conanfile.py (HelloWorld/1.2.3.4): Generator 'CMakeToolchain' calling 'generate()'
conanfile.py (HelloWorld/1.2.3.4): WARN: Toolchain: Ignoring fPIC option defined for Windows
conanfile.py (HelloWorld/1.2.3.4): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (HelloWorld/1.2.3.4): Preset 'conan-default' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-default' if using CMake>=3.23
conanfile.py (HelloWorld/1.2.3.4): If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:\repositories\hello-world\build-debug\conan\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
conanfile.py (HelloWorld/1.2.3.4): CMakeToolchain generated: CMakePresets.json
conanfile.py (HelloWorld/1.2.3.4): CMakeToolchain generated: ..\..\CMakeUserPresets.json
conanfile.py (HelloWorld/1.2.3.4): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (HelloWorld/1.2.3.4): Generating aggregated env files
conanfile.py (HelloWorld/1.2.3.4): Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']       
Install finished successfully

======== Input profiles ========
Profile host:
[settings]
arch=x86
build_type=Release
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.py (HelloWorld/1.2.3.4): C:\repositories\hello-world\conanfile.py

======== Computing necessary packages ========

======== Installing packages ========

======== Finalizing install (deploy, generators) ========
conanfile.py (HelloWorld/1.2.3.4): Writing generators to C:\repositories\hello-world\build-release\conan    
conanfile.py (HelloWorld/1.2.3.4): Generator 'CMakeToolchain' calling 'generate()'
conanfile.py (HelloWorld/1.2.3.4): WARN: Toolchain: Ignoring fPIC option defined for Windows
conanfile.py (HelloWorld/1.2.3.4): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (HelloWorld/1.2.3.4): Preset 'conan-default' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-default' if using CMake>=3.23
conanfile.py (HelloWorld/1.2.3.4): If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=C:\repositories\hello-world\build-release\conan\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
conanfile.py (HelloWorld/1.2.3.4): CMakeToolchain generated: CMakePresets.json
conanfile.py (HelloWorld/1.2.3.4): CMakeToolchain generated: ..\..\CMakeUserPresets.json
conanfile.py (HelloWorld/1.2.3.4): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (HelloWorld/1.2.3.4): Generating aggregated env files
conanfile.py (HelloWorld/1.2.3.4): Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']       
Install finished successfully

CMake Error: Could not read presets from C:/repositories/hello-world:
Duplicate preset: "conan-default"
```

**Comment by memsharded** [comment] 2023-10-19 21:34
Some quick feedback:

- ``set(CMAKE_CXX_STANDARD 14)`` in the ``CMakeLists.txt`` is not great, as it hardcodes the cppstd. Even if you pass ``compiler.cppstd=17`` to Conan and it defines it in the CMake toolchain, the hardcoded value will still force 14
- For Conan 2.0 it is necessary to define ``compiler.cppstd`` in the profiles, please make sure to define it.

Then, the error seems to be because you are using ``basic_layout(self)`` instead of ``cmake_layout(self)``. If you want to have a multi-config layout, you need to use the ``cmake_layout(self)``, as the basic one is not multi-config.

**Comment by schwaerz** [comment] 2023-10-20 09:02
Ah, thanks for the insight and quick feedback. Will try ASAP. 👍

**Comment by schwaerz** [comment] 2023-10-20 09:23
Everything works as expected when using `cmake_layout` :)

Thanks for the quick support 👍

**Comment by memsharded** [comment] 2023-10-20 10:41
Ok, excellent, thanks for the feedback!

Closing this ticket as not a bug, resolved.

**Closed as completed by memsharded** 2023-10-20 10:41 UTC
Labels: type: question
