### ISSUE TITLE
[bug] corrupt artifactory package ?

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#8539] opened 2021-02-22 21:01 UTC
```
CMake Error: The source directory "/home/luminar/.conan/data/ceres-solver/1.13.0/_/_/build/1ce849fddb6e45c13e3eae2053dbdd5fd92de535" does not appear to contain CMakeLists.txt
```

I get this error reproducible when running `rm -rf ~/.conan/data/* /tmp/conan_download_cache/ && conan install ceres-solver/1.13.0@ -b ceres-solver -r luminar`. Note the `-r luminar`, our private Artifactory.

When using `-r conan-center`, it works without error.

The recipes and packages get uploaded to the Artifactory whenever a CI is ran through succesfuly, via `conan upload "*" --all --confirm --parallel --remote luminar`, and my impression is, that somehow the upload moved some corrupt packages to Artifactory?

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04 and Win10
  * Compiler+version: gcc 7 and msvc of VS19
  * Conan version: 1.33.1
  * Python version: 3.9 and 3.6.9

### Steps to reproduce (Include if Applicable)
only happens on private repo 😞 

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
C:\Python39\Scripts\conan.exe install ceres-solver/1.13.0@ -b ceres-solver -r luminar                             
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ceres-solver/1.13.0: Forced build from source
Installing package: ceres-solver/1.13.0
Requirements
    ceres-solver/1.13.0 from 'luminar' - Cache
    eigen/3.3.8 from 'conan-center' - Cache
Packages
    ceres-solver/1.13.0:6fbc4fb986f91680a0076262c273deb96eba56d6 - Build
    eigen/3.3.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
eigen/3.3.8: Already installed!
ceres-solver/1.13.0: WARN: Build folder is dirty, removing it: C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
ceres-solver/1.13.0: Copying sources to build folder
ceres-solver/1.13.0: Building your package in C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
ceres-solver/1.13.0: Generator cmake created conanbuildinfo.cmake
ceres-solver/1.13.0: Calling build()
CMake Error: The source directory "C:/Users/florianb/.conan/data/ceres-solver/1.13.0/_/_/build/6fbc4fb986f91680a0076262c273deb96eba56d6" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ceres-solver/1.13.0:
ceres-solver/1.13.0: ERROR: Package '6fbc4fb986f91680a0076262c273deb96eba56d6' build failed
ceres-solver/1.13.0: WARN: Build folder C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
ERROR: ceres-solver/1.13.0: Error in build() method, line 125
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 119
        self._cmake.configure()
        ConanException: Error 1 while executing cd C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6 && cmake -G "Visual Studio 16 2019" -A "x64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP24" -DCONAN_C_FLAGS="/MP24" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\package\6fbc4fb986f91680a0076262c273deb96eba56d6" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DLIB_SUFFIX="" -DGFLAGS="False" -DBUILD_EXAMPLES="False" -DBUILD_TESTING="False" -DBUILD_DOCUMENTATION="False" -DCUSTOM_BLAS="True" -DGLOG_PREFER_EXPORTED_GLOG_CMAKE_CONFIGURATION="False" -DEIGENSPARSE="True" -DSUITESPARSE="False" -DLAPACK="False" -DCXSPARSE="False" -DMINIGLOG="True" -DCMAKE_DISABLE_FIND_PACKAGE_TBB="True" -DTBB="False" -DOPENMP="False" -DEIGEN_PREFER_EXPORTED_EIGEN_CMAKE_CONFIGURATION="False" -DGFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION="False" -DCXX11_THREADS="False" -DCXX11="False" -DSCHUR_SPECIALIZATIONS="True" -DMSVC_USE_STATIC_CRT="False" -Wno-dev C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
```

**Comment by memsharded** [comment] 2021-02-22 22:38
I am trying to reproduce this, I did the same and uploaded the built package to my private Artifactory instance, and it worked when I downloaded and rebuilt from the Artifactory. So couldn't reproduce and I have no idea what it could be.

Maybe getting a copy of what is in the server for inspection could help (specifically what is in the ``export`` folder of the server. Maybe it could be a bug of the ``--parallel`` upload? If so it might be difficult to reproduce, please try not to overwrite that server one until getting a backup copy.

**Comment by blackliner** [comment] 2021-02-23 14:55
Alright, here are all the files of this package:
![image](https://user-images.githubusercontent.com/23190927/108861324-63630780-75ef-11eb-9b0e-8b8a918f4f4e.png)

[ceres.zip](https://github.com/conan-io/conan/files/6029665/ceres.zip)

**Comment by solvingj** [comment] 2021-02-23 22:10
When a package is installed with the Conan client and scheduled for build ,  `conan_export.tgz` and `conan_sources.tgz` are extracted into the `exports` and `exports_sources` folders respectively.  Then, all files from both of those directories are copied into the `build`  directory just before the build.  You can either download and expand the two `tgz` files manually, or you can look in your cache into the `exports` and `exports_sources` folders if you have them installed.

**Comment by memsharded** [comment] 2021-02-24 00:00
I have checked your tgz files and they seem correct.

I am seeing some unexpected lines here:
```
ceres-solver/1.13.0: WARN: Build folder is dirty, removing it: C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
ceres-solver/1.13.0: Copying sources to build folder
```

This is a symptom that something went wrong previously, and Conan is trying to remove the previous files, but maybe it is still using and outdated source folder. Can you please make sure that your cache is clean?. Remove there the ``ceres`` folder, or do a ``conan remove ceres* -f``, or use a new cache and type again the ``conan install ceres... --build=ceres -r=myremote`` to see what happens.

**Comment by blackliner** [comment] 2021-02-24 19:43
I always purged the download cache as well as conan/data, on both Windows and Linux
```
PS C:\src\LumPDK> rmdir C:\tmp\conan_download_cache\

Confirm
The item at C:\tmp\conan_download_cache\ has children and the Recurse parameter was not specified. If you continue, all children will be removed with the item. Are you sure you want to continue?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
PS C:\src\LumPDK> conan remove ceres* -f
PS C:\src\LumPDK> dir C:\Users\florianb\.conan\data\c*


    Directory: C:\Users\florianb\.conan\data


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2/20/2021   8:02 PM                catch2
d-----         2/20/2021   7:49 PM                commonapi
d-----         2/20/2021   7:49 PM                commonapi-someip
d-----         1/16/2021  12:47 AM                cppzmq


PS C:\src\LumPDK> C:\Python39\Scripts\conan.exe install ceres-solver/1.13.0@ -b ceres-solver -r luminar
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

ceres-solver/1.13.0: Retrieving from server 'luminar'
ceres-solver/1.13.0: Trying with 'luminar'...
Downloading 6ed46b7c923e1d2bf96ec926329dd5dd69ca86a239a7d045abb4efd1643b69d2 completed [0.44k]
Downloading 100462938b2ec693ae1b5344d88b514a10f5f081bc950a78104f724a1e68b82f completed [8.39k]
Downloading 75f7103a38a8d58010dbba3bbfb996629c2216733c859eea2177b68b445a76d7 completed [0.24k]
Decompressing conan_export.tgz completed [0.00k]
ceres-solver/1.13.0: Downloaded recipe revision dbb568d25cf4f175d3d45fc48766d3af
ceres-solver/1.13.0: Forced build from source
Installing package: ceres-solver/1.13.0
Requirements
    ceres-solver/1.13.0 from 'luminar' - Downloaded
    eigen/3.3.8 from 'conan-center' - Cache
Packages
    ceres-solver/1.13.0:6fbc4fb986f91680a0076262c273deb96eba56d6 - Build
    eigen/3.3.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache

Installing (downloading, building) binaries...
eigen/3.3.8: Already installed!
ceres-solver/1.13.0: Configuring sources in C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\source
Downloading 793ab794a0480e2804fbd1078b574c7e00d78c8e1c851eda587cde5ca9223f48 completed [3502.71k]

ceres-solver/1.13.0: Copying sources to build folder
ceres-solver/1.13.0: Building your package in C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
ceres-solver/1.13.0: Generator cmake created conanbuildinfo.cmake
ceres-solver/1.13.0: Calling build()
CMake Error: The source directory "C:/Users/florianb/.conan/data/ceres-solver/1.13.0/_/_/build/6fbc4fb986f91680a0076262c273deb96eba56d6" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ceres-solver/1.13.0:
ceres-solver/1.13.0: ERROR: Package '6fbc4fb986f91680a0076262c273deb96eba56d6' build failed
ceres-solver/1.13.0: WARN: Build folder C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
ERROR: ceres-solver/1.13.0: Error in build() method, line 125
        cmake = self._configure_cmake()
while calling '_configure_cmake', line 119
        self._cmake.configure()
        ConanException: Error 1 while executing cd C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6 && cmake -G "Visual Studio 16 2019" -A "x64" -DCONAN_LINK_RUNTIME="/MD" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP24" -DCONAN_C_FLAGS="/MP24" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\package\6fbc4fb986f91680a0076262c273deb96eba56d6" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DLIB_SUFFIX="" -DGFLAGS="False" -DBUILD_EXAMPLES="False" -DBUILD_TESTING="False" -DBUILD_DOCUMENTATION="False" -DCUSTOM_BLAS="True" -DGLOG_PREFER_EXPORTED_GLOG_CMAKE_CONFIGURATION="False" -DEIGENSPARSE="True" -DSUITESPARSE="False" -DLAPACK="False" -DCXSPARSE="False" -DMINIGLOG="True" -DCMAKE_DISABLE_FIND_PACKAGE_TBB="True" -DTBB="False" -DOPENMP="False" -DEIGEN_PREFER_EXPORTED_EIGEN_CMAKE_CONFIGURATION="False" -DGFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION="False" -DCXX11_THREADS="False" -DCXX11="False" -DSCHUR_SPECIALIZATIONS="True" -DMSVC_USE_STATIC_CRT="False" -Wno-dev C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6
```

**Comment by memsharded** [comment] 2021-02-24 19:50
What is in the ``Building your package in C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\build\6fbc4fb986f91680a0076262c273deb96eba56d6`` folder after that fails? And what in the ``C:\Users\florianb\.conan\data\ceres-solver\1.13.0\_\_\source`` folder?

Could you please share a copy of those folders (like zipping those folders and sharing)?. This is really surprising, the CMakeLists.txt is there in the .tgz, I am not sure why it will not be in the folder, and why it only fails in your case.

**Comment by blackliner** [comment] 2021-02-24 19:56
This is the whole `C:\Users\florianb\.conan\data\ceres-solver`
[ceres-solver.zip](https://github.com/conan-io/conan/files/6038522/ceres-solver.zip)

**Comment by blackliner** [comment] 2021-02-24 20:02
And this is the same directory (without binaries) after succesfully running `C:\Python39\Scripts\conan.exe install ceres-solver/1.13.0@ -b ceres-solver -r conan-center`:
[ceres-solver.zip](https://github.com/conan-io/conan/files/6038552/ceres-solver.zip)

**Comment by blackliner** [comment] 2021-03-01 09:45
@memsharded did you get a chance to look at the files?

**Comment by blackliner** [comment] 2022-06-28 20:21
A year later, I had some support calls with JFrog engineers, and they found some irregularities on their end that could explain this issue. I will update the bug once we figure out what exactly the issue is.

**Comment by memsharded** [comment] 2022-06-28 21:05
Thanks for following up. That means that it is not something from the Conan side, maybe we could close this issue?

**Comment by blackliner** [comment] 2022-06-28 21:07
It might be related to the missing transactional upload from the conan side (where only parts of the package are uploaded, but for example sources.tgz was not).

https://github.com/conan-io/conan/issues/6870

**Comment by jfaust** [comment] 2022-08-17 18:02
@blackliner any new information on this? We're seeing the exact same thing.

**Comment by jfaust** [comment] 2022-08-17 18:25
Upgraded our artifactory CE server and it seems to be working now

**Comment by blackliner** [comment] 2022-08-17 21:10
@jfaust the frequency this occured decreased over the last 2 month, but I am not sure what the reason for this was. Very probable a JFrog issue.

**Closed as completed** 2022-08-17 21:10 UTC
Labels: stage: triaging
