### ISSUE TITLE
Database is locked exception

### ISSUE THREAD

**Issue by jjcp** [conan-io/conan#683] opened 2016-11-22 18:16 UTC
I get the following error message when trying to run `conan` on Windows 10  (installed via pip)

```
Traceback (most recent call last):
  File "c:\users\myuser\appdata\local\programs\python\python36\lib\site-packages\conans\client\store\sqlite.py", line 20, in init
    statement.execute("PRAGMA auto_vacuum = INCREMENTAL;")
sqlite3.OperationalError: database is locked
```

The error occurs on line `838` on file `client/command.py` when it tries to run: `remote_manager = instance_remote_manager(client_cache)` after the `try - except` block. 
It looks like the line is either unnecessary (it seems to work when I comment it out) or the previous `remote_manager` (instanced on line `825`) should be `closed` on a `finally` block after the except.

Let me know if you need more information.
Thanks.

**Comment by memsharded** [comment] 2016-11-22 20:22
Hi Juan,

Could you give a little more context to this error? It appears just at the very first command after installing? How did you get to this error?

As a workaround, you can try removing the database (from ``.conan/.conan.db``), it is just some temporary data you are safe removing and it should be regenerated after next conan invocation.

It is true that so far we have CI for python 2.7-3.5, maybe using py36 has some issue with it. You might also try downgrading your python installation (of course virtualenvwrapper is recommended).

Thanks very much for reporting!

**Comment by jjcp** [comment] 2016-11-23 00:23
Hello,

Yes, the error comes up right after installing `conan` via pip (commenting out that line fixes the issue, as far as I can tell). There is no `.db` file anywhere to be found.
Just in case it might be related, I tried installing `conan` using the installer from the web, but it Segfaults when it tries to install any dependency (I tried it in a VM and in a real windows install on another machine)

Thanks.

**Comment by memsharded** [comment] 2016-11-23 09:03
I have been able to reproduce the error. It is something related to Python 3.6, which is still in beta, and not intended for production.

Conan runs fine from python 2.7 to 3.5, I'd suggest installing any stable Python 2.7 or 3.5 (if you are using both 3.6 and 2.7/3.5, you can easily have both of them simultaneously with virtualenv - virtualenvwrapper).

**Comment by memsharded** [comment] 2016-11-23 09:07
About the error with the installer from the web, could you please reproduce the exact commands after the installation, and also copy here the full output? Thanks!

**Comment by jjcp** [comment] 2016-11-23 16:23
Here's all the info necessary to reproduce the crash under windows.

```
C:\Users\jjcp\atest\build
λ cat ..\conanfile.py
from conans import ConanFile, CMake


class Conan(ConanFile):
    settings = 'os', 'compiler', 'build_type', 'arch'
    requires = (
        'Poco/1.7.3@lasote/stable',
    )
    generators = (
        'cmake',
        'env',
        'txt',
    )
    # default_options = ()

    def imports(self):
        self.copy('*.dll', dst='bin', src='bin')  # From bin to bin
        self.copy('*.dylib*', dst='bin', src='lib')  # From lib to bin

    def build(self):
        cmake = CMake(self.settings)
        self.run('cmake "%s" %s' % (self.conanfile_directory,
                                    cmake.command_line))
        self.run('cmake --build . %s' % cmake.build_config)

C:\Users\jjcp\atest\build
λ conan install ..
Poco/1.7.3@lasote/stable: Not found, looking in remotes...
Poco/1.7.3@lasote/stable: Trying with 'conan.io'...
 << Crashes here >>
C:\Users\jjcp\atest\build
λ
```

**Comment by memsharded** [comment] 2016-11-23 17:26
Sure, we'd love to improve the Windows installer, but it has limitations beyond our reach. For example it can be detected as malware by some AVs. Nothing to do there. Windows 10 can complain as non trusted, and getting the certificates and everything would be too much.

Another issue is that the bundled python interpreter is not full, as bundled by pyinstaller. That means that when you use some python module that has not been bundled in your recipe, it will fail, while it works on a regular python installation.

So these are important caveats, and solving them is not in our hands.

On the other hand, I am sorry to hear that you had trouble installing python and pip in windows, I do it very often and it seems a very straightforward thing, just downloading the python installer and running it, everything can be done in 2 minutes, what problems did you have with it?

**Comment by jjcp** [comment] 2016-11-23 21:07
Oh I see, that's sad :( 
My problems stemmed from the fact that it's been a long time since I last used Windows for anything :P so when I run the python installer it didn't even ask me to set python in the PATH nor did it install `pip` alongside it (I had to use a `get_pip` script) .... Maybe I just used the wrong installer :D
It would be great if we could tell users: 'Hey just install this thing (python installer link) open a terminal and run `pip install conan`' and done (Again, maybe it already is that easy to install `python / pip` and I just had bad luck :D )

**Comment by memsharded** [comment] 2016-11-25 19:35
Not able to reproduce the crash on windows. Maybe you have an AV and is messing with conan?
If everything goes smoothly with pip package, I'd suggest attaching to it, and maybe this issue could be closed?

**Comment by jjcp** [comment] 2016-11-25 20:03
Hm, I tried disabling Windows Defender and it still crashes.
This is mostly a clean Windows 10 install on VirtualBox.

---
I just tried installing version 0.14.1 and this is what I get:
```
λ conan install ..
Poco/1.7.3@lasote/stable: Not found, looking in remotes...
Poco/1.7.3@lasote/stable: Trying with 'conan.io'...
WARN: A new conan version (v0.15.0) is available in current remote. Please, upgrade conan client to avoid deprecation.
Downloading conanmanifest.txt
[==================================================]
Downloading conanfile.py
[==================================================]
Downloading conan_export.tgz
[==================================================]
OpenSSL/1.0.2h@lasote/stable: Not found, looking in remotes...
OpenSSL/1.0.2h@lasote/stable: Trying with 'conan.io'...
WARN: A new conan version (v0.15.0) is available in current remote. Please, upgrade conan client to avoid deprecation.
Downloading conanmanifest.txt
OpenSSL/1.0.2h@lasote/stable: WARN: Unable to connect to conan.io=https://server.conan.io
ERROR: All remotes failed
```

It doesn't crash but it doesn't install anything either.

**Comment by memsharded** [comment] 2016-11-26 10:00
Yeah, Windows Defender is not a problem, I work on Windows with it enabled without issues. 
I'd say that you might be experiencing some connectivity issues due to the Virtual Machine. It doesn't make sense at all that it installs the first package - Poco (try running ``conan search``), but it fails in the download of the second one - OpenSSL.

If I understood correctly, this crash is from the Win installer or from the pip package too?

**Comment by jjcp** [comment] 2016-11-28 13:13
The pip version works fine, it's the version from the installer that fails.
It seems you are having difficulties reproducing this bug, you may try installing Windows 10 64bits 
( https://www.microsoft.com/en-us/software-download/windows10ISO ) in VirtualBox and try with that.

**Comment by memsharded** [comment] 2016-11-28 16:50
We have identified the source issue, a misconfiguration in the machine that generates the installer. Thanks very much for your help. Conan 0.16 will be released tomorrow, hopefully this will be fixed. 

Still encourage the pip package, stick to it if possible! :)

**Comment by memsharded** [comment] 2016-11-29 10:46
Conan release 0.16 is out, it fixes the issue, so closing it, but please reopen if necessary.
The failures about using python 3.6 are still open, but lets wait until it is released.

**Closed by memsharded** 2016-11-29 10:46 UTC
Labels: fixed
