### ISSUE TITLE
[question] Is there a command to list all components of a specific package? 

### ISSUE THREAD

**Issue by dotChris90** [conan-io/conan#13429] opened 2023-03-13 15:35 UTC
### What is your question?

Sorry i ask maybe sth stupid. But 

I would like to know if there is a command to list all components of a package. 

Reason : 
- i often have the problem, that i dont know what components are inside a package but i need them inside a cmakefile e.g. find_package(boost::filesystem REQUIRED)

I ask this because currently the only way i know is : 
- create a tmp conan + CMake Project with dependency {pkg_name}/{pkg_version} 
- conan install
- look for the "*-Target-release.cmake" file
- use the name of the "*-Target-release.cmake" as find_package in your CMakeFile.txt
- conan build 
- see the console output like : 
![2023-03-13_16h34_57](https://user-images.githubusercontent.com/33638852/224750642-f16db65b-c24d-4a1a-a2bc-91e6796d1f41.png)

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-03-13 15:42
Hi @dotChris90 

Thanks for your question.
The components of a package, as other things are specific per-configuration so they need the graph to be evaluated to be able to compute them.
With Conan 2.0 you might be able to get them with ``conan graph info ... --format=json``, inside the ``cpp_info`` you will see the components. The serialized json is still under the "experimental" label, but we will be working on it to stabilize it.
We also have the "markdown" deployer, that we will probably contribute it soon to the ``conan-extensions`` new repo, that can generate a more human friendly output of such components.

**Comment by dotChris90** [comment] 2023-03-14 14:50
At least for boost/1.81.0 i have my doubts ^^' if i see the output. 
I cannot see the components 

![2023-03-14_15h48_48](https://user-images.githubusercontent.com/33638852/225039166-fb8eb05c-d812-4077-962c-c37d78a416e4.png)

But may i ask : is this because recipes need to be updated to conan 2.0? So it is "future behaviour" ? 
If you tell me - currently not visible but in future it is - i am also willing to close ticket :D

**Comment by memsharded** [comment] 2023-03-14 15:17
Uhm, you are right, this is unexpected. We need to have a look to this, thanks for reporting it.

**Comment by memsharded** [comment] 2023-03-28 21:12
I have been checking this, and it doesn't seem a bug anymore, but expected behavior:

- The ``package_info()`` method, that defines the ``components`` in the general case, only executes when the binary exists and is installed in the cache
- This happens because ``package_info()`` often needs to have access to the package itself to return its information, for example, calling ``self.cpp_info.libs = collect_libs(self)`` to get the library names directly from the binary package.
- ``conan graph info`` only computes the dependency graph, but it does not download, retrieves, or build the binaries, so it doesn't have the concept of "binaries", and then it cannot call the ``package_info()`` method

Then, the only way to list components of a package is via ``conan install ... --format=json > graph.json``. The resulting ``graph.json`` will contain the definition of components inside ``cpp_info``.

**Comment by memsharded** [comment] 2023-03-30 14:59
Hi @dotChris90 

I am closing this ticket as solved, the way to list components from a specific package is with ``conan install ... --format=json`` will contain such information. 
If there is any further question, please re-open or file a new ticket. Many thanks for the feedback!

**Closed as completed by memsharded** 2023-03-30 14:59 UTC
Labels: type: question
