### ISSUE TITLE
Option in conanfile.txt is not being used when resolving dependencies or installing packages

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#2512] opened 2018-02-22 17:20 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.0.4 Linux or Mingw

## To reproduce:

First clone https://github.com/sourcedelica/conan_option_bug

1. `./create.sh` to create packages in local cache
2. `./install.sh` to run `conan install` for a test consumer

When installing you will get the error:

```
ERROR: cob-common/0.1@eric/test: Incompatible requirements obtained in different evaluations of 'requirements'
    Previous requirements: [cob-caf/0.1@eric/test, cob-zmq/0.1@eric/test]
    New requirements: [cob-caf/0.1@eric/test]
```

## Description of the problem

`cob-common` has two options: `use_caf` (default=`True`) and `use_zmq`
(default=`False`).

`cob-client` requires `cob-common`.

`cob-service` requires `cob-common` with `use_zmq=True`.

The `test` consumer requires `cob-common`, `cob-client` and
`cob-service`. In its `conanfile.txt` it sets `cob-common:use_zmq=False`.

There is an error on installation because there is a conflict between
`cob-client` (`cob-common:use_zmq=False`) and `cob-service`
(`cob-common:use_zmq=True`). However, `conanfile.txt` should be resolving
the conflict by forcing `cob-common:use_zmq=False`. So there should be
no error. You should also be able to override the conflict by passing
`cob-common:use_zmq=False` on the command line.

The bug appears to be that the option from `conanfile.txt` is not being
used. You can see this happening by doing the following:

1. Edit `cob-common/conanfile.py`
2. Comment out the `requirements()` method.
3. `conan create . eric/test`
5. `cd ../test/build`
6. `conan install ..`

You will get an error like:

```
cob-common/0.1@eric/test: WARN: Can't find a 'cob-common/0.1@eric/test' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Debug, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=6.2, os=Windows
- Options: use_caf=True, use_zmq=True
```

As you can see, it is not using the `cob-common:use_zmq=False` option
from `conanfile.txt`.

**Comment by lasote** [comment] 2018-02-22 17:54
Have you tried instead of setting the options of the `cob-common` in the configure() to set them as default options?

```default_options = "cob-common:use_zqm=False"```

I'm honestly not sure if the `configure` doing `self.options['cob-common'].use_zmq = True` will have priority, and I don't know if it is documented. Maybe @memsharded knows more about it. 
If you can try it, it will help.

**Comment by sourcedelica** [comment] 2018-02-22 19:31
My initial approach (tagged as `rev1`) was based on the [Conditional settings, options and requirements](http://conanio.readthedocs.io/en/latest/mastering/conditional.html) manual page.

I tried using `default_options` and pushed the changes to the reproducer Github repo (tagged as `rev2`).

Now, depending on the value of the `cob-common:use_zmq`  option I set in `conanfile.txt`, I either get:

```
ERROR: cob-common/0.1@eric/test: cob-client/0.1@eric/test tried to change cob-common/0.1@eric/test option use_zmq to False
but it was already assigned to True by None
```
or
```
ERROR: cob-common/0.1@eric/test: Incompatible requirements obtained in different evaluations of 'requirements'
    Previous requirements: [cob-caf/0.1@eric/test, cob-zmq/0.1@eric/test]
    New requirements: [cob-caf/0.1@eric/test]
```

It seems that when using `default_options` in the downstream recipes I also need to create the packages tagged with the upstream options.  For example, I need to create `cob-client` with `-o cob-common:use_zmq=True`.  Is that expected?  

Thanks,

**Comment by sourcedelica** [comment] 2018-02-22 19:45
One other thing, I'd like to be able to use the `cob-client:use_zmq_transport` option to be able to dynamically set the `cob-common:use_caf` and `use_zmq` options.

**Comment by lasote** [comment] 2018-02-22 19:49
I would need to debug it and see if I can understand what is happening. Will report back asap. If we confirm a bug we will try to solve it for the coming 1.1.

**Comment by memsharded** [comment] 2018-02-23 09:10
I have had a look. Changing cob-service to:

```python
class CobConan(ConanFile):
    name = 'cob-service'
    version = '0.1'
    description = 'cob-service'
    exports_sources = '*.cpp', '*.h', 'CMakeLists.txt'
    url = 'https://github.com/sourcedelica/conan_option_bug.git'
    license = 'none'
    settings = 'os', 'compiler', 'build_type', 'arch'
    generators = 'cmake'
    default_options = "cob-common:use_zmq=True", "cob-common:use_caf=True"

    #NO CONFIGURE
```

It works.

The issue is that you are trying to install incompatible dependency graphs. On one side, the dependency graph of ``cob-service`` always require ``cob-common`` to use both zmq and caf. This is hardcoded in the recipe ``configure()`` mehtod. On the other side, ``cob-client`` tries to use one or the other, but not both at the same time. This always conflict in ``cob-common``. Changing that to use ``default_options`` instead of ``configure()`` solves the conflict, but I suspect that you really need ``cob-service`` to use ``cob-common`` linking with both zmq and caf, so that might not be a solution.

It seems to me that the ``conanfile.txt`` that requires both might not be the best approach, but to do separate installs of ``cob-service`` and ``cob-client``.

**Comment by sourcedelica** [comment] 2018-02-23 13:07
Thanks, I'll try it out.

The `test/conanfile.txt` represents the unit tests for the whole subsystem including `cob-common`, `cob-client` and `cob-service`.  The test executable needs to link in all of these.

`conanfile.txt` currently resolves conflicts in dependency versions.  For example, if both `util/0.1@eric/test` and `util/0.2@eric/test` were in the dependency graph doing a `conan install` would result in a conflict error.  But it you explicitly list `util/0.2@eric/test` in `conanfile.txt` then that version will be used.

Similarly that is what I was expecting to see for options.  In this case `cob-common:use_zmq=True` and `cob-common:use_zmq=False` were in the dependency graph resulting in a conflict.  I was expecting that explicitly listing `cob-common:use_zmq=True` in `conanfile.txt` would resolve the conflict.

To do this you could take all of the options that were provided explicitly (either in `conanfile.txt` or on the command line) and when constructing the dependency graph and reading recipes, override any default values of explicitly provided options.

**Comment by memsharded** [comment] 2018-02-23 14:29
> To do this you could take all of the options that were provided explicitly (either in conanfile.txt or on the command line) and when constructing the dependency graph and reading recipes, override any default values of explicitly provided options.

This is how it is working right now. The thing is that ``configure()`` is overwriting the options propagation and forcing them, leading them to conflict. I do not recommend to do that, except some extreme cases, and typicall, setting ``default_options`` should be good for most cases. Please try that and report. Thanks!

**Comment by sourcedelica** [comment] 2018-02-23 15:13
I tried as you suggested (this is the `rev2` tag of my reproducer repo), and get this now:

```
$ ./install.sh
ERROR: cob-common/0.1@eric/test: cob-client/0.1@eric/test tried to change cob-common/0.1@eric/test option use_zmq to False
but it was already assigned to True by None
```

I also tried commenting out the `configure()` method in `cob-client` (tagged as `rev3` in my reproducer repo) and now I get this:

```
cob-client/0.1@eric/test: WARN: Can't find a 'cob-client/0.1@eric/test' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Debug, compiler=gcc, compiler.libcxx=libstdc++, compiler.version=6.2, os=Windows
- Options: use_zmq_transport=False, cob-common:use_caf=True, cob-common:use_zmq=True
```
If I build `cob-client` with `-o cob-common:use_zmq=True` then I can finally install using `test/conanfile.txt`.   

However, commenting out `cob-client`'s `configure()` is not a long term solution for me, as I need to use the `cob-client:use_zmq_transport` option.

**Comment by memsharded** [comment] 2023-12-20 19:18
The propagation of ``options`` has been fully changed in Conan 2.0, now options never conflict, they will overwrite with a depth-first priority. If some recipe cannot work with some dependencies options values, it should raise in ``validate()`` to protect against it, but there is no way recipes can have highest precedence anymore wrt their consumers or users. Closing the ticket as outdated.

**Closed by memsharded** 2023-12-20 19:18 UTC
