### ISSUE TITLE
Resolve 'requires' version in exported conanfile.py

### ISSUE THREAD

**Issue by GordonJess** [conan-io/conan#5414] opened 2019-06-27 19:06 UTC
To investigate bugs in built packages, we'd like to be able to recreate the environment in which they were built.  Something like `conan install` followed by `conan source`.  

Using the `scm` attribute to get the exact commit works well for the latter command, but there is still  uncertainty of retrieving the exact same versions of dependencies are when running `conan install`.

To solve this, perhaps the version numbers in the 
conanfile.py can be replaced with a fixed version before exporting it to the Conan cache.

**Comment by GordonJess** [comment] 2019-06-28 05:29
I was knocking something up in the post-export hook and came to the issue of how to deal with dependencies that are inherited by common code shared through 'python requires'.  Of course this would be fine if the recipe referenced by 'python requires' also has it's 'requires' version range patched with explicit versions, but then perhaps I am missing the point of using version ranges altogether!

How do others typically deal with this?  Seems like a common use-case.

**Comment by jgsogo** [comment] 2019-06-28 08:59
Hi, your use case is something we are aware of and we are currently developing a `graphlock` feature (https://github.com/conan-io/conan/pull/5412) to be able to gather (and reuse) all the information about the requirements used to generate a binary. This new feature, together with [the revisions](https://docs.conan.io/en/latest/mastering/revisions.html) one and a strong package id mode should make it possible to fully reproduce a build.

All of these are marked as experimental features because we may change some implementation details or the command line interface if needed, but the functionality is something we do want to have in Conan and keep as stable as possible. Feel free to test them and provide any feedback about them.

There is still some extra information like the machine-id or environment variables that Conan won't grab and associate with the package by default (environment variables could contain passwords or sensible information), but those should be easy to gather in the CI system using a hook and writing them to a file, or storing it as properties if the server has that capability.

**Comment by GordonJess** [comment] 2019-06-28 10:38
Excellent, good to know!

Would you able to estimate when this feature might be available?

**Comment by jgsogo** [comment] 2019-06-28 11:31
#5412 is planned for `v1.17` and, unless we find some issue important enough with the current implementation, it will be released probably next week.

**Comment by memsharded** [comment] 2023-11-29 22:29
Solved long time ago with lockfiles (recommended Conan 2.0 ones)

**Closed by memsharded** 2023-11-29 22:29 UTC
Labels: type: question
