### ISSUE TITLE
ignoring all folders that have .git in them even if the .git is not at the end of the path

### ISSUE THREAD

**Issue by ysmaoui** [conan-io/conan#8608] opened 2021-03-05 10:42 UTC
This implementation
https://github.com/conan-io/conan/blob/a5c994186014c9cd29529ad64baecf15215f0182/conans/client/conf/config_installer.py#L133
causes the following issue

if a path of the config folder contains ".git" even not at the end of the path, it will be ignored

for example this path will be ignored

"/this/is/a/path.git/to/the/config/folder"

**Comment by czoido** [comment] 2021-03-05 11:29
Hi @ysmaoui,
Thanks a lot for reporting, this is a duplicate of https://github.com/conan-io/conan/issues/8594
We have a test to reproduce the issue: https://github.com/conan-io/conan/pull/8605
Please, let's continue the discussion there. I'm closing this one.

**Closed as completed by czoido** 2021-03-05 11:29 UTC
Labels: duplicate
