### ISSUE TITLE
[bug] incomplete dangerous dependency resolution in Conan

### ISSUE THREAD

**Issue by pcapdump** [conan-io/conan#7368] opened 2020-07-16 15:49 UTC
Conan dependancy resolution seems to be incomplete.
I configured `conanfile.txt` as follows:

[requires]
boost/1.69.0
wt/4.3.1

And `Conan` happily installed both libraries, although `Wt` was built with `boost-1.73.0` as seen at https://conan.io/center/wt/4.3.1/?user=_&channel=_&revision=&os=Linux&tab=config

The application build ended with linkage error:

``
/bin/ld: /root/.conan/data/boost/1.69.0//_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_thread.a(thread.o): relocation R_X86_64_PC32 against undefined hidden symbol `_ZTCN5boost10wrapexceptINS_21thread_resource_errorEEE0_NS_16exception_detail10clone_implINS3_19error_info_injectorIS1_EEEE' can not be used when making a shared object
/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: [../../Makefile.rules:191: some.so] Error 1
``

And this was a luck the issue revealed at this stage.
In a bad case, the linkage could have passed successfully, but memory could have been corrupted at runtime in sporadic cases.

Isn't `Conan` expected to display an error message about libraries incompatibility and bail out?

I'm not a Conan expert so please forgive me if I'm missing some configuration steps.

### Environment Details
  * Operating System+version: Centos8
  * Compiler+version: gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)
  * Conan version: 1.27.0
  * Python version: 3.6.8

**Comment by Minimonium** [comment] 2020-07-16 16:39
Hi, the issue is the old resolution default strategy that's scheduled to be fixed in the next major version. 

You can try to change the `# full_transitive_package_id = 0` to 1 in the `conan.conf`:
https://docs.conan.io/en/latest/reference/config_files/conan.conf.html

Additionally, consider `package_revision_mode` for the package_id_mode for a more strict tree (much more builds, be aware).

**Comment by memsharded** [comment] 2020-07-16 16:41
Hi @pcapdump 

Thanks for submitting this issue.

This is a known result of the default ABI compatibility model of Conan, which is ``semver_direct_mode``. This was an assumption that was very early built in Conan, and assumed that the packages would be compatible at the major version, following semver. Unfortunately this is certainly not a safe default for C++ linkage, but it was too late to change the default.

It is not a version conflict, as the dependency resolution mandates that if you, as a consumer, define ``boost/1.69``, that will override the dependencies upstream, and wt will be forced to use ``boost/1.69`` even if it was built with another boost version. This was requested by users, as the expected behavior when they were declaring something explicitly in their consumer conanfiles is that such declaration was respected. In that sense, Conan always prioritizes the "bottom consumer" or last input, to always give control and power to the user. In this case, irrespective of what ``wt`` declares, if the consumer declares ``boost/1.69``, that declaration has the capacity to override the upstream.

To improve over this, Conan provides other package_id modes, and a better one would be ``full_version_mode``. This will force in this case to rebuilt a binary for ``wt`` when it is linked with boost/1.69 instead of 1.73. You can change the package_id_mode in your ``conan.conf``: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#changing-the-default-package-id-mode

The inconvenient about that is that as ConanCenter packages were built with ``semver_direct_mode``, you will not have pre-built binaries for them, and you will need to build from sources. 

So the alternatives are:

- Force the build from sources of wt, locally, with ``conan install . --build=wt``, that will force to be built against boost/1.69
- Change the ``default_package_id_mode``. That will guarantee correct ABI compatibility at your defined level. It will need building from sources the binaries (you probably want to store them in your own server to avoid rebuilding)

**Comment by memsharded** [comment] 2020-07-16 17:06
BTW, this is something that most likely will change in Conan 2.0, when we are able to break and change the defaults.

**Comment by pcapdump** [comment] 2020-07-17 14:07
> You can try to change the `# full_transitive_package_id = 0` to 1 in the `conan.conf`:
> https://docs.conan.io/en/latest/reference/config_files/conan.conf.html

Thanks for reply,

I tried removing /root/.conan.
Then I did:

$ conan config set general.full_transitive_package_id=1

And then ran build.
Nothing changed...
Same error as above.

We don't have conan.conf as we use https://github.com/conan-io/cmake-conan.
But the above should be equivalent, shouldn't it?

After build I do

$ conan config get general.full_transitive_package_id
1

Therefore, the option didn't change during the build.

**Comment by Minimonium** [comment] 2020-07-17 15:52
Aha, my bad, seems like I misunderstood the intent of the `full_transitive_package_id`. After rereading the docs I've got that it's the issue of breaking the chain of transitive requirements by header-only libraries, instead of a global package_id_mode fix. 

So yes, a solution would be to change the `package_id_mode` as @memsharded suggested.

**Comment by pcapdump** [comment] 2020-07-17 16:10
@Minimonium , @memsharded ,

Unfortunately, `package_id_mode` doesn't change anything too:

$ conan config get general.default_package_id_mode
full_version_mode

I see warning `WARN: wt/4.3.1: requirement boost/1.73.0 overridden by your conanfile to boost/1.69.0 `

But the build continues...

Full log when both `general.full_transitive_package_id` and `package_id_mode` options are set:

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

boost/1.69.0: Not found in local cache, looking in remotes...
boost/1.69.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.69.0: Downloaded recipe revision 0
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.11: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
bzip2/1.0.8: Downloaded recipe revision 0
wt/4.3.1: Not found in local cache, looking in remotes...
wt/4.3.1: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
wt/4.3.1: Downloaded recipe revision 0
openssl/1.1.1g: Not found in local cache, looking in remotes...
openssl/1.1.1g: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
openssl/1.1.1g: Downloaded recipe revision 0
sqlite3/3.31.1: Not found in local cache, looking in remotes...
sqlite3/3.31.1: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
sqlite3/3.31.1: Downloaded recipe revision 0
libmysqlclient/8.0.17: Not found in local cache, looking in remotes...
libmysqlclient/8.0.17: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libmysqlclient/8.0.17: Downloaded recipe revision 0
libpq/11.5: Not found in local cache, looking in remotes...
libpq/11.5: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libpq/11.5: Downloaded recipe revision 0
libunwind/1.3.1: Not found in local cache, looking in remotes...
libunwind/1.3.1: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libunwind/1.3.1: Downloaded recipe revision 0
xz_utils/5.2.4: Not found in local cache, looking in remotes...
xz_utils/5.2.4: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
xz_utils/5.2.4: Downloaded recipe revision 0
catch2/2.11.0: Not found in local cache, looking in remotes...
catch2/2.11.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
catch2/2.11.0: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    boost/1.69.0 from 'conan-center' - Downloaded
    bzip2/1.0.8 from 'conan-center' - Downloaded
    catch2/2.11.0 from 'conan-center' - Downloaded
    libmysqlclient/8.0.17 from 'conan-center' - Downloaded
    libpq/11.5 from 'conan-center' - Downloaded
    libunwind/1.3.1 from 'conan-center' - Downloaded
    openssl/1.1.1g from 'conan-center' - Downloaded
    sqlite3/3.31.1 from 'conan-center' - Downloaded
    wt/4.3.1 from 'conan-center' - Downloaded
    xz_utils/5.2.4 from 'conan-center' - Downloaded
    zlib/1.2.11 from 'conan-center' - Downloaded
Packages
    boost/1.69.0:7068ed10403246f8331cfec6288fde7b48f7bc8a - Download
    bzip2/1.0.8:a5875aed3fc7ae8dd0488f7e5e99acbc480d721d - Download
    catch2/2.11.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    libmysqlclient/8.0.17:d0971ea66a27756acbf4cd00b51dd89e43beda0f - Download
    libpq/11.5:7272758eb3859d8cadc85d3af3bb16905c17893d - Download
    libunwind/1.3.1:b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0 - Download
    openssl/1.1.1g:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Download
    sqlite3/3.31.1:5840d0ed3c1de62f1130f4d884d2083129209657 - Download
    wt/4.3.1:988bcff65a71e414b3f2cedd0dea0b6364dd0fcc - Download
    xz_utils/5.2.4:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Download
    zlib/1.2.11:1d877a3df840030e6a8abb74c5ffb9088d08b47a - Download

Installing (downloading, building) binaries...
bzip2/1.0.8: Retrieving package a5875aed3fc7ae8dd0488f7e5e99acbc480d721d from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
bzip2/1.0.8: Package installed a5875aed3fc7ae8dd0488f7e5e99acbc480d721d
bzip2/1.0.8: Downloaded package revision 0
catch2/2.11.0: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
catch2/2.11.0: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
catch2/2.11.0: Downloaded package revision 0
openssl/1.1.1g: Retrieving package 1d877a3df840030e6a8abb74c5ffb9088d08b47a from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
openssl/1.1.1g: Package installed 1d877a3df840030e6a8abb74c5ffb9088d08b47a
openssl/1.1.1g: Downloaded package revision 0
sqlite3/3.31.1: Retrieving package 5840d0ed3c1de62f1130f4d884d2083129209657 from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
sqlite3/3.31.1: Package installed 5840d0ed3c1de62f1130f4d884d2083129209657
sqlite3/3.31.1: Downloaded package revision 0
xz_utils/5.2.4: Retrieving package 1d877a3df840030e6a8abb74c5ffb9088d08b47a from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
xz_utils/5.2.4: Package installed 1d877a3df840030e6a8abb74c5ffb9088d08b47a
xz_utils/5.2.4: Downloaded package revision 0
zlib/1.2.11: Retrieving package 1d877a3df840030e6a8abb74c5ffb9088d08b47a from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
zlib/1.2.11: Package installed 1d877a3df840030e6a8abb74c5ffb9088d08b47a
zlib/1.2.11: Downloaded package revision 0
boost/1.69.0: Retrieving package 7068ed10403246f8331cfec6288fde7b48f7bc8a from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
..boost/1.69.0: Package installed 7068ed10403246f8331cfec6288fde7b48f7bc8a
boost/1.69.0: Downloaded package revision 0
libmysqlclient/8.0.17: Retrieving package d0971ea66a27756acbf4cd00b51dd89e43beda0f from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
libmysqlclient/8.0.17: Package installed d0971ea66a27756acbf4cd00b51dd89e43beda0f
libmysqlclient/8.0.17: Downloaded package revision 0
libpq/11.5: Retrieving package 7272758eb3859d8cadc85d3af3bb16905c17893d from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
libpq/11.5: Package installed 7272758eb3859d8cadc85d3af3bb16905c17893d
libpq/11.5: Downloaded package revision 0
libunwind/1.3.1: Retrieving package b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0 from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
libunwind/1.3.1: Package installed b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0
libunwind/1.3.1: Downloaded package revision 0
wt/4.3.1: Retrieving package 988bcff65a71e414b3f2cedd0dea0b6364dd0fcc from remote 'conan-center' 
Downloading conanmanifest.txt
Downloading conaninfo.txt
Downloading conan_package.tgz
.wt/4.3.1: Package installed 988bcff65a71e414b3f2cedd0dea0b6364dd0fcc
wt/4.3.1: Downloaded package revision 0
sqlite3/3.31.1: Appending PATH env var with : /root/.conan/data/sqlite3/3.31.1/_/_/package/5840d0ed3c1de62f1130f4d884d2083129209657/bin
boost/1.69.0: LIBRARIES: ['boost_wave', 'boost_container', 'boost_contract', 'boost_exception', 'boost_graph', 'boost_iostreams', 'boost_locale', 'boost_log', 'boost_program_options', 'boost_random', 'boost_regex', 'boost_serialization', 'boost_wserialization', 'boost_coroutine', 'boost_fiber', 'boost_context', 'boost_timer', 'boost_thread', 'boost_chrono', 'boost_date_time', 'boost_atomic', 'boost_filesystem', 'boost_system', 'boost_type_erasure', 'boost_log_setup', 'boost_math_c99', 'boost_math_c99f', 'boost_math_c99l', 'boost_math_tr1', 'boost_math_tr1f', 'boost_math_tr1l', 'boost_stacktrace_addr2line', 'boost_stacktrace_backtrace', 'boost_stacktrace_basic', 'boost_stacktrace_noop', 'boost_unit_test_framework']
boost/1.69.0: Package folder: /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generator cmake created conanbuildinfo.cmake
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
WARN: wt/4.3.1: requirement boost/1.73.0 overridden by your conanfile to boost/1.69.0 
-- Conan: Loading conanbuildinfo.cmake
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library wttest found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwttest.a
-- Library wtdbopostgres found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwtdbopostgres.a
-- Library wtdbosqlite3 found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwtdbosqlite3.a
-- Library wtdbomysql found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwtdbomysql.a
-- Library wtdbo found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwtdbo.a
-- Library wthttp found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwthttp.a
-- Library wt found /root/.conan/data/wt/4.3.1/_/_/package/988bcff65a71e414b3f2cedd0dea0b6364dd0fcc/lib/libwt.a
-- Library boost_wave found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_wave.a
-- Library boost_container found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_container.a
-- Library boost_contract found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_contract.a
-- Library boost_exception found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_exception.a
-- Library boost_graph found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_graph.a
-- Library boost_iostreams found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_iostreams.a
-- Library boost_locale found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_locale.a
-- Library boost_log found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_log.a
-- Library boost_program_options found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_program_options.a
-- Library boost_random found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_random.a
-- Library boost_regex found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_regex.a
-- Library boost_serialization found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_serialization.a
-- Library boost_wserialization found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_wserialization.a
-- Library boost_coroutine found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_coroutine.a
-- Library boost_fiber found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_fiber.a
-- Library boost_context found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_context.a
-- Library boost_timer found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_timer.a
-- Library boost_thread found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_thread.a
-- Library boost_chrono found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_chrono.a
-- Library boost_date_time found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_date_time.a
-- Library boost_atomic found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_atomic.a
-- Library boost_filesystem found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_filesystem.a
-- Library boost_system found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_system.a
-- Library boost_type_erasure found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_type_erasure.a
-- Library boost_log_setup found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_log_setup.a
-- Library boost_math_c99 found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_math_c99.a
-- Library boost_math_c99f found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_math_c99f.a
-- Library boost_math_c99l found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_math_c99l.a
-- Library boost_math_tr1 found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_math_tr1.a
-- Library boost_math_tr1f found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_math_tr1f.a
-- Library boost_math_tr1l found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_math_tr1l.a
-- Library boost_stacktrace_addr2line found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_stacktrace_addr2line.a
-- Library boost_stacktrace_backtrace found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_stacktrace_backtrace.a
-- Library boost_stacktrace_basic found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_stacktrace_basic.a
-- Library boost_stacktrace_noop found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_stacktrace_noop.a
-- Library boost_unit_test_framework found /root/.conan/data/boost/1.69.0/_/_/package/7068ed10403246f8331cfec6288fde7b48f7bc8a/lib/libboost_unit_test_framework.a
-- Library sqlite3 found /root/.conan/data/sqlite3/3.31.1/_/_/package/5840d0ed3c1de62f1130f4d884d2083129209657/lib/libsqlite3.a
-- Library mysqlclient found /root/.conan/data/libmysqlclient/8.0.17/_/_/package/d0971ea66a27756acbf4cd00b51dd89e43beda0f/lib/libmysqlclient.a
-- Library pq found /root/.conan/data/libpq/11.5/_/_/package/7272758eb3859d8cadc85d3af3bb16905c17893d/lib/libpq.a
-- Library pgcommon found /root/.conan/data/libpq/11.5/_/_/package/7272758eb3859d8cadc85d3af3bb16905c17893d/lib/libpgcommon.a
-- Library unwind found /root/.conan/data/libunwind/1.3.1/_/_/package/b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0/lib/libunwind.a
-- Library unwind-coredump found /root/.conan/data/libunwind/1.3.1/_/_/package/b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0/lib/libunwind-coredump.a
-- Library unwind-generic found /root/.conan/data/libunwind/1.3.1/_/_/package/b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0/lib/libunwind-generic.a
-- Library unwind-ptrace found /root/.conan/data/libunwind/1.3.1/_/_/package/b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0/lib/libunwind-ptrace.a
-- Library unwind-setjmp found /root/.conan/data/libunwind/1.3.1/_/_/package/b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0/lib/libunwind-setjmp.a
-- Library unwind-x86_64 found /root/.conan/data/libunwind/1.3.1/_/_/package/b5c9223ad1e6cb3c93cf7140433a2c5bc0912aa0/lib/libunwind-x86_64.a
-- Library z found /root/.conan/data/zlib/1.2.11/_/_/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib/libz.a
-- Library bz2 found /root/.conan/data/bzip2/1.0.8/_/_/package/a5875aed3fc7ae8dd0488f7e5e99acbc480d721d/lib/libbz2.a
-- Library ssl found /root/.conan/data/openssl/1.1.1g/_/_/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib/libssl.a
-- Library crypto found /root/.conan/data/openssl/1.1.1g/_/_/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib/libcrypto.a
-- Library lzma found /root/.conan/data/xz_utils/5.2.4/_/_/package/1d877a3df840030e6a8abb74c5ffb9088d08b47a/lib/liblzma.a
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: {cut}
-- Conan: Compiler GCC>=5, checking major version 8
-- Conan: Checking correct version: 8
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: {cut}
-- Conan: Compiler GCC>=5, checking major version 8
-- Conan: Checking correct version: 8

**Comment by Minimonium** [comment] 2020-07-17 16:20
@pcapdump Could be a different name
```
[general]
default_package_id_mode=full_package_mode
```
From https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html#changing-the-default-package-id-mode

**Comment by pcapdump** [comment] 2020-07-20 14:25
It was my mistake, I changed the conan config for userA and built by userB.
That's why it the config option didn't apply.
Thanks!

**Comment by pcapdump** [comment] 2020-07-21 09:18
@Minimonium ,

is it possible to make Conan treat warnings as errors?

I see this Conan message:

```
WARN: wt/4.3.1: requirement boost/1.73.0 overridden by your conanfile to boost/1.69.0
```

If we stopped Conan build on such warnings, it would have solved our problem...

**Comment by Minimonium** [comment] 2020-07-21 11:36
@pcapdump Conan emits quite a lot of warnings, the whole output system needs an overhaul. It wouldn't work well to make them treated as an error, simply because the system doesn't imply that. 
Even more, overrides are normal behaviour, you can't error on something that the user explicitly asked to do. The warning is informational in there, but it's getting lost because Conan emits tons of output generally so people don't pay attention to it.

**Comment by memsharded** [comment] 2024-09-04 22:37
Dependency resolution was overhauled in Conan 2 with new behaviors.
Closing as outdated.

**Closed as not planned by memsharded** 2024-09-04 22:37 UTC
Labels: stage: triaging
