### ISSUE TITLE
[question] automatic PATH prepending with the "bin" folder is disabled in conan 2.0 ?

### ISSUE THREAD

**Issue by todorico** [conan-io/conan#13353] opened 2023-03-07 08:19 UTC
### What is your question?

Hi ! Recently I tried using Conan 2.0 on the recipes I maintain to be compatible with both 1.x and 2.x. However, there was a difference that I wasn't expecting. Unlike Conan 1.x, the bin folder wasn't automatically prepended to the PATH variable in Conan 2.x. It forces me to add buildenv_info / runenv_info to a lot of my recipes. Is this the intended behavior ? I couldn't find any reference to this behavior in the "Conan migration guide to 2.0".

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-03-07 10:39
Hi @todorico 

No, this is definitely not expected, we would need more details to reproduce.
The ``bin`` folder of ``tool_requires`` should be automatically added to PATH in the consumers, automatically injected by the implicit ``VirtualBuildEnv`` usage (no need to even declare it).

There was a bug when using MesonToolchain, that has been fixed in https://github.com/conan-io/conan/pull/13346. If you were using MesonToolchain, then that could be the cause. If not, please report how to reproduce this. Thanks!

**Comment by todorico** [comment] 2023-03-25 12:50
Hi @memsharded,

After further investigation, I realized that I must have made a mistake in my initial report. I have been unable to reproduce the issue that I reported earlier, and the problem seems to have been resolved on its own. Therefore, I believe that this issue can now be closed.

Thank you for your time and effort in helping me resolve this issue. Your assistance is greatly appreciated!

**Comment by memsharded** [comment] 2023-03-26 21:58
Happy that the issue has been resolved :) closing the ticket.

Glad to help!

**Closed as completed by memsharded** 2023-03-26 21:58 UTC
Labels: stage: triaging
