### ISSUE TITLE
[bug] self.options.get_safe does not exist inside export() function

### ISSUE THREAD

**Issue by volviq** [conan-io/conan#10688] opened 2022-03-01 16:03 UTC
The documentation says in https://docs.conan.io/en/latest/reference/conanfile/attributes.html: 
"Values from options can be retrieved after they are assigned. For options that belong to the same recipe, the value can be retrieved in any method to run logic conditional to their values. "
Due to this description I would expect, the options can also be accessed inside the export() function.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 11
  * Compiler+version: (irrelevant)
  * Conan version: 1.44.0
  * Python version: Python 3.6.5

### Steps to reproduce (Include if Applicable)
# Create a conanfile with options:

options = {"doit": ["true", "false"]}

# access the option within export():
```
def export(self):
    isit = self.options.get_safe("doit")
```
throws an error (see below).

Exactly the same inside 
```
 def package(self):
    isit = self.options.get_safe("doit")
```
works without error.
### Logs (Executed commands with output) (Include/Attach if Applicable)
throws the error:
```
 conan create . myapp/testing --profile=gcc -o doit=true
Exporting package recipe
DemoApp/0.1@myapp/testing: Calling export()
ERROR: DemoApp/0.1@myapp/testing: Error in export() method, line 41
        vardir = self.options.get_safe("doit")
        AttributeError: 'dict' object has no attribute 'get_safe'
```

**Comment by memsharded** [comment] 2022-03-01 16:09
Hi @volviq 

This is not a bug in Conan, but expected. Instead it is a bug in the docs. The thing is that the ``export()`` method was added very recently, before those docs were written. The docs need to be updated to reflect that.

A couple of details about export:

- export flow cannot be conditioned on options, settings or other stuff. The exported thing should always be identical, in all platforms and for all systems
- this applies to both exports and exports_sources, both as attributes and also as methods
- Even the line feed must match, so the generated recipe revision is the same for the same inputs. To guarantee that, it is recommended to ensure the git checkout CRLF is defined to always the same invariant LF, irrespective of OS (even in Windows, all modern editors support LF without problems)
- Recall: ``export`` is for things that the recipe, and only the recipe needs, and ``exports_sources`` are for source code and other things necessary for the build.

**Comment by memsharded** [comment] 2022-05-16 10:23
Not a bug, question closed as responded

**Closed as completed by memsharded** 2022-05-16 10:23 UTC
Labels: type: question

**Comment by volviq** [comment] 2022-10-07 07:32
so the doc won't be fixed?

**Comment by memsharded** [comment] 2022-10-07 08:18
But isn't the docs correct? It clearly says ``Values from options can be retrieved after they are assigned``. The ``export`` process does not take any argument, not options, not settings. The options are not assigned, so they cannot be checked. No examples there use it in ``export()`` method. What would be your recommended fix?
