### ISSUE TITLE
[question] How to manage hotfixes of libraries using Conan 1.x recipes versioned with sourcecode?

### ISSUE THREAD

**Issue by thegwydd** [conan-io/conan#15521] opened 2024-01-24 16:29 UTC
### What is your question?

Hi conan team, 

Our project consists of ~60 repositories. Some are library projects and some applications that depends on libraries using conan and conan.cmake integration.
Each repository keeps sourcecode, conanfile.py and CMakeLists.txt and uses release branches in order to be able to easily release hotfixes (several customers use same product but at different versions)
All conanfile.py in repository are for Conan 1.x version

We're looking into moving to Conan 2.0 but I have a doubt.

If we update all recipes and then we move to Conan 2.x, we loose the ability to create hotfixes on old releases because on our machines we will have Conan 2.x installed but when checking out old source versions, every recipe will be in Conan 1.x format.

In this case, what's the best strategy to avoid being killed by breaking changes?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-01-24 17:12
Hi @thegwydd 

Thanks for your question.

> If we update all recipes and then we move to Conan 2.x, we loose the ability to create hotfixes on old releases because on our machines we will have Conan 2.x installed but when checking out old source versions, every recipe will be in Conan 1.x format.

The way to move forward is to move simultaneously with both 1.X and 2.0 for a while. There is a joint syntax that is simultaneously compatible with 1.X and 2.0, so it is possible to build 1.X and 2.0 binaries and put them in the same server repo without breaking the other version, because they have different ``package-ids``. Then, dropping 1.X and moving with 2.0-only syntax is done when you are confident you will not have much issues for the 1.X ones.

Of course there will always be a risk that you want to go back in time to a 1.X recipe only. From the client side it shouldn't be a big issue, just install the 1.X version that you want and re-build as you did before. Maybe the issue is only in the final deployment/release part?

Please let me know if this helps a bit with the issue or you have any further questions.

**Comment by thegwydd** [comment] 2024-01-25 07:02
Thank you @memsharded ,

so I can use modify current recipes to use 1.x and 2.x common syntax and then switch to 2.x later.

I guess your solution works but after moving to 2.x we still need to install Conan 1.x on developer machines every time a hotfix is needed (of course, only for hotfixes on old branches that still use 1.x recipes)

What about conan server (conans)? Does it support 1.x and 2.x packages simultaneusly?

**Comment by memsharded** [comment] 2024-01-25 10:59
> so I can use modify current recipes to use 1.x and 2.x common syntax and then switch to 2.x later.

yes, exactly, this is how it is recommended to do it, first update recipes while in 1.X to make them jointly compatible, then start to build also with 2.0, same packages and versions, and finally (and later) drop 1.X

> I guess your solution works but after moving to 2.x we still need to install Conan 1.x on developer machines every time a hotfix is needed (of course, only for hotfixes on old branches that still use 1.x recipes)

Yes, for old branches that is inevitable, the goal is try to reduce it as much as possible. Using Python virtualenvs to be able to install Conan 1.X and Conan 2 side-by-side is recommended.

> What about conan server (conans)? Does it support 1.x and 2.x packages simultaneusly?

Yes, both ``conan_server`` and the free ArtifactoryCE allow to use the same server, including the same repository to host simultaneouly packages from Conan1.X and Conan 2.0. The same recipe with the same recipe-revisions (Conan 1.X must have revisions enabled) will contain all binaries, but with different ``package_ids``. Conan 1.X ``conan search`` will list binaries built with Conan 1.X and Conan 2.0 ``conan list`` will list binaries built with Conan 2.0 only. 

For production usage beyond a few developers, I'd recommend the free ArtifactoryCE, it is faster and more powerful than the conan_server, and it is free too.

**Comment by memsharded** [comment] 2024-09-28 11:16
Closing as responded, but please don't hesitate to re-open or create new tickets for any further questions. Thanks for your feedback.

**Closed as completed by memsharded** 2024-09-28 11:16 UTC
Labels: type: question
