### ISSUE TITLE
[question] How to solve 'unix_path_package_info_legacy' is not defined error?

### ISSUE THREAD

**Issue by huchchas** [conan-io/conan#13847] opened 2023-05-08 20:12 UTC
### What is your question?

I am trying to use log4cxx with Conan 1.57. When I add 'log4cxx/0.12.1' in conanfile.txt I get the following error:

`
ERROR: libtool/2.4.7: Error in package_info() method, line 239
	self.env_info.ACLOCAL_PATH.append(unix_path_package_info_legacy(self, libtool_aclocal_dir))
	NameError: name 'unix_path_package_info_legacy' is not defined
`

If I remove 'log4cxx/0.12.1' from the conanfile everything works just fine. 

I am very new to Conan so any help would be greatly appreciated.

Thanks.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by AbrilRBS** [comment] 2023-05-08 20:35
Hi @huchchas thanks for your question, I can try to help you in this :)

This is a weird one, because if you are getting this error it means that you _are_ running at least 1.57, [which is the version that introduced that function](https://docs.conan.io/en/1.59/changelog.html#id23), or else you'd see a different error telling you that you need a newer Conan version, [as the recipe correctly identifies itself as needed 1.57 at the very least](https://github.com/conan-io/conan-center-index/blob/master/recipes/libtool/all/conanfile.py#L14)

Can you update to the latest Conan version, see if that changes anything? (If you want to stay in the v1 branch, make sure to ask for 1.59.0 specifically or your package manager might get v2 for you)

**Comment by huchchas** [comment] 2023-05-08 20:58
Hi @RubenRBS! Thank you for your reply. 

I just tested with 1.59. Unfortunately, I got the same error.

**Comment by huchchas** [comment] 2023-05-08 21:01
I just confirmed with a team member that they don't even have libtool in there ".conan/data" directory. So it must be coming from log4cxx along with all the other dependencies such as apr, apr-util, autoconf, automake etc.

**Comment by AbrilRBS** [comment] 2023-05-09 00:32
Let me try to repro locally and I'll get back to you :)

**Comment by AbrilRBS** [comment] 2023-05-09 12:58
Hi. Can you tell me the following information? I'm unable to repro locally:

* OS version:
* Output of running:
  * `conan --version`
  * `conan search "*"`
* The install command you are running and its output.
* The `conanfile.txt` you are using 

If you can't share some of the above, please try to create a small reproducible case so that we can find out what's going wrong :)

**Comment by AbrilRBS** [comment] 2023-05-29 01:50
Hi @huchchas, friendlt ping :)

Any update on the repro?

**Comment by AbrilRBS** [comment] 2023-08-21 22:17
Closing due to lack of follow-up, please feel free to reopen should you find yourself with the same problem again, thanks! :)

**Closed as not planned by AbrilRBS** 2023-08-21 22:17 UTC
Labels: type: question
