### ISSUE TITLE
[feature] cmake_paths generator should append Conan paths to CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH rather than set those variables

### ISSUE THREAD

**Issue by oliora** [conan-io/conan#6969] opened 2020-05-06 21:32 UTC
It is not rare when CMAKE_MODULE_PATH and/or CMAKE_PREFIX_PATH are passed to CMake via command line or set by CMake initial cache script or modified by some other CMake script. It will be more friendly to other CMake scripts and more in-line with expected workflow around CMAKE_MODULE_PATH and/or CMAKE_PREFIX_PATH variables if cmake_paths generator appends Conan paths to aforementioned variables rather than sets them.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment] 2020-05-07 08:21
We try to have all the dependencies managed by Conan, but from time to time it is needed to use dependencies that are already in the system. 👍

**Comment by jgsogo** [comment] 2020-05-12 08:25
According to #6970, then this is no longer an issue. Did you open the issue because something was not working as expected? Do you have any minimum reproducible example?

**Comment by KerstinKeller** [comment] 2020-05-12 11:20
I guess you are doing a  `set(CMAKE_MODULE_PATH conan/path/one;conan/path/two;${CMAKE_MODULE_PATH})`, however it might be more readable to to `list(PREPEND CMAKE_MODULE_PATH conan/path/one conan/path/two`).
😄

**Comment by memsharded** [comment] 2023-11-29 23:15
``cmake_paths`` superseded by ``CMakeToolchain``, closing this ticket as outdated.

**Closed as completed by memsharded** 2023-11-29 23:15 UTC
Labels: type: feature, stage: in-progress
