### ISSUE TITLE
[question] How to handle source() in local build workflow

### ISSUE THREAD

**Issue by jasal82** [conan-io/conan#15497] opened 2024-01-22 21:18 UTC
### What is your question?

I've run into a problem with the Conan 2.0 migration. Most of our Conan packages adhere to the "conanfile in source repository" pattern. The current CI pipeline uses the local build workflow (for different reasons), and it also unconditionally runs `conan source`, because some third-party packages required it and our own packages used the `scm` attribute, so they didn't care. Now I tried to replace `scm` with the `export()`/`source()` pattern as described in the migration guide, but this fails in the local build workflow because `source()` cannot checkout the sources (we're using the local workflow and obviously `export()` was never run).

What is the correct way to handle this? Should I detect the local build workflow context somehow and skip the `source()` step? I tried to enclose the clone block in `if self.recipe_folder != self.source_folder`, but it seems that Conan 1.x calls `export()` as part of the `conan source` command which makes the export fail in local builds where the repository is not pristine (which happens all the time during local development). Is there a new pattern for local build workflow that I missed in the documentation?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-01-22 22:48
Seems duplicate of https://github.com/conan-io/conan/issues/15498, closing

**Closed as not planned by memsharded** 2024-01-22 22:48 UTC
Labels: duplicate
