### ISSUE TITLE
[bug]UnicodeEncodeError: 'charmap' codec can't encode character when setting CONAN_LOG_RUN_TO_FILE

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6696] opened 2020-03-17 15:27 UTC
I have some ctests that prints some japanese characters. 
When I set `CONAN_LOG_RUN_TO_FILE`, conan fail to write output the log file.

If I unset `CONAN_LOG_RUN_TO_FILE` the issue disappeared.

I narrowed down the issue to this line: 
https://github.com/conan-io/conan/blob/develop/conans/client/runner.py#L100

### Environment Details (include every applicable attribute)
  * Operating System+version: windows server 2016
  * Compiler+version: visual studio 2015
  * Conan version: 1.22.2
  * Python version: 3.7

### Logs (Executed commands with output) (Include/Attach if Applicable)

`14:31:58  Traceback (most recent call last):
14:31:58    File "build.py", line 9, in <module>
14:31:58      builder.run()
14:31:58    File "C:\Python37\lib\site-packages\cpt\packager.py", line 533, in run
14:31:58      self.run_builds(base_profile_name=base_profile_name)
14:31:58    File "C:\Python37\lib\site-packages\cpt\packager.py", line 625, in run_builds
14:31:58      r.run()
14:31:58    File "C:\Python37\lib\site-packages\cpt\runner.py", line 127, in run
14:31:58      update=self._update_dependencies)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
14:31:58      return f(api, *args, **kwargs)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\conan_api.py", line 364, in create
14:31:58      test_build_folder, test_folder, conanfile_path, recorder=recorder)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\cmd\create.py", line 57, in create
14:31:58      recorder=recorder)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\manager.py", line 68, in deps_install
14:31:58      graph_info=graph_info)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 308, in install
14:31:58      self._build(nodes_by_level, keep_build, root_node, graph_info, remotes, build_mode, update)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 332, in _build
14:31:58      self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 398, in _handle_node_cache
14:31:58      pref = self._build_package(node, output, keep_build, remotes)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 442, in _build_package
14:31:58      pref = builder.build_package(node, keep_build, self._recorder, remotes)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 222, in build_package
14:31:58      raise exc
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 208, in build_package
14:31:58      self._build(conanfile, pref, build_folder)
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 134, in _build
14:31:58      raise exc
14:31:58    File "C:\Python37\lib\site-packages\conans\client\installer.py", line 123, in _build
14:31:58      conanfile.build()
14:31:58    File "C:\Python37\lib\contextlib.py", line 130, in __exit__
14:31:58      self.gen.throw(type, value, traceback)
14:31:58    File "C:\Python37\lib\site-packages\conans\errors.py", line 40, in conanfile_exception_formatter
14:31:58      raise ConanExceptionInUserConanfileMethod(msg)
14:31:58  conans.errors.ConanExceptionInUserConanfileMethod: pmi_qt_common/3.7.615-gcbbd2440@pmi/PR-717: Error in build() method, line 394
14:31:58  	self.run("ctest --no-compress-output -T Test", run_environment=True)
14:31:58  	UnicodeEncodeError: 'charmap' codec can't encode character '\u5bbf' in position 88: character maps to <undefined>`

**Comment by jgsogo** [comment] 2020-03-18 16:04
Hi! I'm pretty sure that it would be enough to open the file in `encoding="utf-8"` [here](https://github.com/conan-io/conan/blob/develop/conans/client/runner.py#L66):

```python
import io
io.open("<filename>", "w", encoding="utf-8"):
```

...but first I need to reproduce the issue

**Comment by jgsogo** [comment] 2020-03-18 16:41
@boussaffawalid , can you run this line?

```
python -c 'import locale; print(locale.getpreferredencoding())'
```

It will print the default encoding for your machine, which is the one it is using Python in `open(...)` by default... probably, that's the reason of your failure.

**Comment by memsharded** [comment] 2020-03-18 18:29
Need double quotes in my machine (Windows, cmder terminal):

```bash
$ python -c "import locale; print(locale.getpreferredencoding())"
cp1252
```

**Comment by jgsogo** [comment] 2020-03-18 18:33
Yes, probably with that encoding you will also get UnicodeEncodeErrors for characters outside it (Japanese ones for sure). In MacOS it is `utf-8` and Conan can write them to the file.

It should be safe to open the file using `utf-8` encoding and it will avoid some of these issues.

**Comment by boussaffawalid** [comment] 2020-03-18 20:24
@jgsogo here is the output

```
python -c "import locale; print(locale.getpreferredencoding())"
cp1252
```

Note that we enforce utf-8 encoding by setting the environment variable `PYTHONIOENCODING`
`export PYTHONIOENCODING=UTF-8`

**Comment by jgsogo** [comment] 2020-03-19 08:34
According to the docs that environment variable applies only to stdin/stdout/stderr (https://docs.python.org/3/using/cmdline.html).

I'm going to make a PR changing the io.open, nothing should break.

**Comment by memsharded** [comment] 2023-11-29 23:03
CONAN_LOG_RUN_TO_FILE removed in 2.0, closing as outdated

**Closed by memsharded** 2023-11-29 23:03 UTC
Labels: stage: triaging
