### ISSUE TITLE
[bug] MSBuild.build does not use arch argument to set vcvars

### ISSUE THREAD

**Issue by madebr** [conan-io/conan#6403] opened 2020-01-22 17:59 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio (2017)
  * Conan version: 1.21.1
  * Python version: 3.8.0

### Steps to reproduce (Include if Applicable)

Use recipe of cc65 at https://github.com/conan-io/conan-center-index/pull/719
The Visual Studio solution only supports `x86`.

Run:
```
conan create . cc65/2.18@ -s arch_build=x86
```

The output contains:
```
----Running------
> set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC/Auxiliary/Build/vcvarsall.bat" x86_amd64 && devenv "source_subfolder\src\cc65.sln" /upgrade && msbuild "source_subfolder\src\cc65.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="Win32" /m:8 /p:PlatformToolset="v141" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\conan_build.props"
```

Even though I asked `MSBuild.build` to use the `x86` architecture.
There should be no `x86_amd64` in there.

### Logs (Executed commands with output) (Include/Attach if Applicable)

<details><summary>Output of conan create . cc65/2.18@ -s arch_build=x86</summary>
<p>

```
>conan create . cc65/2.18@ -s arch_build=x86
[HOOK - conan-center.py] pre_export(): [DEPRECATED GLOBAL CPPSTD (KB-H001)] OK
[HOOK - conan-center.py] pre_export(): [REFERENCE LOWERCASE (KB-H002)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE METADATA (KB-H003)] OK
[HOOK - conan-center.py] pre_export(): [HEADER_ONLY, NO COPY SOURCE (KB-H005)] OK
[HOOK - conan-center.py] pre_export(): [FPIC OPTION (KB-H006)] OK
[HOOK - conan-center.py] pre_export(): [VERSION RANGES (KB-H008)] OK
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] Total recipe size: 6.6337890625 KB
[HOOK - conan-center.py] pre_export(): [RECIPE FOLDER SIZE (KB-H009)] OK
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] exports: None
[HOOK - conan-center.py] pre_export(): [EXPORT LICENSE (KB-H023)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE FOLDER (KB-H024)] OK
[HOOK - conan-center.py] pre_export(): [META LINES (KB-H025)] OK
[HOOK - conan-center.py] pre_export(): [CONAN CENTER INDEX URL (KB-H027)] OK
[HOOK - conan-center.py] pre_export(): [CMAKE MINIMUM VERSION (KB-H028)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - RUN ENVIRONMENT (KB-H029)] OK
[HOOK - conan-center.py] pre_export(): [CONANDATA.YML FORMAT (KB-H030)] OK
[HOOK - conan-center.py] pre_export(): [TEST PACKAGE - NO IMPORTS() (KB-H034)] OK
[HOOK - conan-center.py] pre_export(): [NO AUTHOR (KB-H037)] OK
Exporting package recipe
cc65/2.18 exports: File 'conandata.yml' found. Exporting it...
cc65/2.18 exports: Copied 1 '.yml' file: conandata.yml
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] Saving conandata.yml: {'sources': {'2.18': {'url': 'https://github.com/cc65/cc65/archive/V2.18.tar.gz', 'sha256': 'd14a22fb87c7bcbecd8a83d5362d5d317b19c6ce2433421f2512f28293a6eaab'}}}
[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] New conandata.yml contents: sources:
  '2.18':
    sha256: d14a22fb87c7bcbecd8a83d5362d5d317b19c6ce2433421f2512f28293a6eaab
    url: https://github.com/cc65/cc65/archive/V2.18.tar.gz

[HOOK - conan-center.py] post_export(): [CONANDATA.YML REDUCE (KB-H031)] OK
cc65/2.18: The stored package has not changed
cc65/2.18: Exported revision: 7045933103910257b3d6604910d45cf1
Configuration:
[settings]
arch=x86_64
arch_build=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

cc65/2.18: Forced build from source
cc65/2.18 (test package): Installing package
Requirements
    cc65/2.18 from local cache - Cache
Packages
    cc65/2.18:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Build
Build requirements
    make/4.2.1 from 'conan-center' - Cache
Build requirements packages
    make/4.2.1:b2fcbc60b3bee75023a4f7934cadb723eec550bd - Cache

Cross-build from 'Windows:x86' to 'Windows:x86_64'
make/4.2.1: Already installed!
make/4.2.1: Creating CONAN_MAKE_PROGRAM environment variable: C:\Users\maarten\.conan\data\make\4.2.1\_\_\package\b2fcbc60b3bee75023a4f7934cadb723eec550bd\bin\gnumake.exe
[HOOK - conan-center.py] post_package_info(): [CMAKE FILE NOT IN BUILD FOLDERS (KB-H019)] OK
cc65/2.18: Applying build-requirement: make/4.2.1
cc65/2.18: WARN: Build folder is dirty, removing it: C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd
cc65/2.18: Copying sources to build folder
cc65/2.18: Building your package in C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd
cc65/2.18: Generator txt created conanbuildinfo.txt
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] 'fPIC' option not found
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
cc65/2.18: Calling build()

----Running------
> set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC/Auxiliary/Build/vcvarsall.bat" x86_amd64 && devenv "source_subfolder\src\cc65.sln" /upgrade && msbuild "source_subfolder\src\cc65.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="Win32" /m:8 /p:PlatformToolset="v141" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\conan_build.props"
-----------------
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.18
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'

Microsoft Visual Studio 2017 Version 15.0.28307.960.
Copyright (C) Microsoft Corp. All rights reserved.
Upgrading project 'common'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'cc65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'ca65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'ar65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'ld65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'cl65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'da65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'co65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'grc65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'od65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'sp65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'sim65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
Upgrading project 'chrcvt65'...
        Configuration 'Debug|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.
        Configuration 'Release|Win32': no platform toolset upgrade required. Platform Toolset is 'v141'.

Migration completed successfully, but some warnings were detected during migration.
For more information, see the migration report:
C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\UpgradeLog.htm
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  abend.c
  addrsize.c
  alignment.c
  assertion.c
  bitops.c
  chartype.c
  check.c
  cmdline.c
  coll.c
  cpu.c
  debugflag.c
  exprdefs.c
  fileid.c
  filepos.c
  filestat.c
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\cmdline.c(129): error C2220: warning treated as error - no 'object' file generated [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\cmdline.c(129): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
  filetime.c
  filetype.c
  fname.c
  fp.c
  gentype.c
  hashfunc.c
  hashtab.c
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\fname.c(55): error C2220: warning treated as error - no 'object' file generated [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\fname.c(55): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\fname.c(84): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
  intptrstack.c
  intstack.c
  matchpat.c
  mmodel.c
  print.c
  searchpath.c
  segnames.c
  shift.c
  strbuf.c
  strpool.c
  strstack.c
  strutil.c
  target.c
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\strbuf.c(82): error C2220: warning treated as error - no 'object' file generated [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\strbuf.c(82): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\strbuf.c(247): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
  tgttrans.c
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\strbuf.c(294): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\strbuf.c(428): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
  version.c
  xmalloc.c
  xsprintf.c
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xmalloc.c(108): error C2220: warning treated as error - no 'object' file generated [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xmalloc.c(108): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(194): error C2220: warning treated as error - no 'object' file generated [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(194): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(319): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(322): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(355): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(356): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(357): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(358): warning C4267: '=': conversion from 'size_t' to 'long', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\xsprintf.c(629): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\searchpath.c(70): error C2220: warning treated as error - no 'object' file generated [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
c:\users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common\searchpath.c(70): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\source_subfolder\src\common.vcxproj]
cc65/2.18:
cc65/2.18: ERROR: Package 'b2fcbc60b3bee75023a4f7934cadb723eec550bd' build failed
cc65/2.18: WARN: Build folder C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd
ERROR: cc65/2.18: Error in build() method, line 84
        self._build_msvc()
while calling '_build_msvc', line 51
        msbuild.build(os.path.join(self._source_subfolder, "src", "cc65.sln"),
        ConanException: Error 1 while executing set "VSCMD_START_DIR=%CD%" && call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC/Auxiliary/Build/vcvarsall.bat" x86_amd64 && devenv "source_subfolder\src\cc65.sln" /upgrade && msbuild "source_subfolder\src\cc65.sln" /p:Configuration="Release" /p:UseEnv=true /p:Platform="Win32" /m:8 /p:PlatformToolset="v141" /verbosity:minimal /p:ForceImportBeforeCppTargets="C:\Users\maarten\.conan\data\cc65\2.18\_\_\build\b2fcbc60b3bee75023a4f7934cadb723eec550bd\conan_build.props"
```

</p>
</details>

**Comment by madebr** [comment] 2020-01-23 21:47
Hello @memsharded 

I probably forgot to mention some important points.

The program I am trying to package is an installer package.
Which means it has `settings = "arch_build", "os_build", "compiler"`. (It needs some special handling for Visual Studio)
The visual studio solution has only support for x86 (no x86_64 or arm).
Because x86 and x86_64 are compatible, I want to alias `arch_build=x86` and `arch_build=x86_64` when using Visual Studio.

It's important that the binaries inside an installer package with a certain `arch_build` and `os_build` are built with that settings. For example when one is cross compiling.
That's why I want to force `arch` and `os` to be the same as `arch_build` and `os_build`.

I've been told by @uilianries  that my issue might be the same as #5004.

In the mean time, I've been able to solve my problem by creating a mocked settings object which has the `arch_build` and `os_build` attributes copied to `arch` and `os`.
This solution will prevent cases where a x86-installer contains x86_64 binaries and vice versa.
This can be seen inside the `_mock_settings` function in conan-io/conan-center-index#719

**Comment by memsharded** [comment] 2020-01-24 12:22
Hi @madebr 

Now I start to understand, thanks, I was missing that information of cross-building.
Certainly, you are being biten by a lack of settings model for cross-building. We are aware of this, but it is very complicated, and it will take some time to fix it.
Also, it is possible that conan-center-index is not prepared yet to build and host these special packages, so some bumps might be expected.

So I am not sure it is a bug of the MSBuild helper. It seems it is doing what it is being told to do, the problem is there is no proper way to specify what to do based on the current settings model. I have checked in the codebase if it is possible to change it, but seems impossible without breaking other users, so we will need to wait.

In the meantime, your solution looks ok. I would also try to use the ``platforms`` argument, it is a dictionary mapping architectures that will overwrite the internal one, so that might be use to re-define behavior as well, and that might simplify a bit your code.

**Comment by memsharded** [comment] 2023-08-25 11:12
This ticket seems outdated, using the legacy ``MSBuild`` integration.
The new tools to use are https://docs.conan.io/2/reference/tools/microsoft.html, closing this ticket as outdated, thanks for the feedback!

**Closed by memsharded** 2023-08-25 11:12 UTC
Labels: stage: triaging
