### ISSUE TITLE
[bug] cannot export local repo when using scm with auto

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7033] opened 2020-05-16 00:36 UTC
When source and conanfile.py in the same repo and using scm to automatic detect the version/revision, `conan export` fails when the repo is NOT dirty.

### Environment Details
  * Ubuntu 19.10
  * Conan version 1.25.1
  * Python 3.7.5

### Steps to reproduce (Include if Applicable)
create a git repo with conanfile.py like following:
```
class MesonTestConan(ConanFile):
    name = "test1"
    description = "a test project for meson build libs"
    topics = ("conan", "multimedia", "video", "audio", "broadcasting", "framework", "media")
    url = "https://example.com"
    license = "MIT"
    settings = "os", "arch", "compiler", "build_type"

    _source_subfolder = "source_subfolder"
    _build_subfolder = "build_subfolder"
    generators = "pkg_config"
    _src_subfolder = 'actual_src'
    scm = {
        'type': 'git',
        'version': 'auto',
        'url': 'auto',
        'revision': 'auto',
        'subfolder': _source_subfolder
    }
```
commit everything make sure git repo is NOT dirty.

Then 
```
conan export ./ test1/0.1@test/test
```
We will have error:
```
Exporting package recipe
INFO  :runners.py     [85]: Calling command: git -c http.sslVerify=true status --porcelain > "/tmp/tmplanvw9e1" [2020-05-16 02:18:28,168]
INFO  :runners.py     [88]: Return code: 0 [2020-05-16 02:18:28,171]
INFO  :runners.py     [96]: Output: in file:
                            stdout: None
                            stderr:b'' [2020-05-16 02:18:28,171]
INFO  :runners.py     [85]: Calling command: git -c http.sslVerify=true remote -v > "/tmp/tmp2ik8kofe" [2020-05-16 02:18:28,174]
INFO  :runners.py     [88]: Return code: 0 [2020-05-16 02:18:28,176]
INFO  :runners.py     [96]: Output: in file:
                            stdout: None
                            stderr:b'' [2020-05-16 02:18:28,177]
ERROR: Repo origin cannot be deduced
```
When the repo is dirty: for example create a comment in the conanfile.py but do not commit it. Then export actually works:
```
test1/0.1@test/test: WARN: There are uncommitted changes, skipping the replacement of 'scm.url' and 'scm.revision' auto fields. Use --ignore-dirty to force it. The 'conan upload' command will prevent uploading recipes with 'auto' values in these fields.
INFO  :runners.py     [85]: Calling command: git -c http.sslVerify=true remote -v > "/tmp/tmp073gs1ru" [2020-05-16 02:19:28,843]
INFO  :runners.py     [88]: Return code: 0 [2020-05-16 02:19:28,846]
INFO  :runners.py     [96]: Output: in file:
                            stdout: None
                            stderr:b'' [2020-05-16 02:19:28,846]
INFO  :runners.py     [85]: Calling command: git -c http.sslVerify=true rev-parse --show-toplevel > "/tmp/tmpxammezrw" [2020-05-16 02:19:28,849]
INFO  :runners.py     [88]: Return code: 0 [2020-05-16 02:19:28,851]
INFO  :runners.py     [96]: Output: in file:conan_test/test1
                            
                            stdout: None
                            stderr:b'' [2020-05-16 02:19:28,851]
test1/0.1@test/test: SCM: Getting sources from folder: conan_test/test1
test1/0.1@test/test: A new conanfile.py version was exported
test1/0.1@test/test: Folder: /conan_home/.conan/data/test1/0.1/test/test/export
test1/0.1@test/test: Exported revision: 6e78cba55d28b1877f5665edc9a3f6e8
```

**Comment by memsharded** [comment] 2020-05-17 20:40
Hi @braindevices 

I am having a look at this, I think it is expected behavior:

- When the repo is dirty, the ``"auto"`` in ``scm`` will be ignored, as it wouldn't contain reproducible data. Then it works. You should be able to read warning messages in the output, and if you try to upload the package, it will fail, because the ``scm`` contains the ``auto`` tags, not replaced. This flow was requested by users to be able to create packages locally with uncommitted sources, to try things.
- If the repo is not dirty, the ``"url": "auto"`` will try to obtain the URL of the ``origin`` git remote. Even if you init + commit all the changes, if there is no ``origin`` defined that allows to do a remote clone, it will error. 

Is that your case? Do you have a ``origin`` remote defined in git that can be auto-detected?

**Comment by braindevices** [comment] 2020-05-18 11:34
@memsharded I do not have origin in remote. But I think the behaviour is not expected. When there is no origin, I think one would expect that the auto is resolved to None. 

Another thought about the behaviour when the repo has origin. Why it is necessary to clone from origin? It is very often to have local repo that we do not want to push to any remote yet. During export, all we want to do is to export the necessary file from local repo to .conan/data. Even when the repo is not dirty, we still have commits which are not pushed. Normally we want export local commits, which is not pushed, to .conan instead of using origin. And we should not automatically upload unless explicitly specified.

**Comment by memsharded** [comment] 2020-05-18 11:51
Hi @braindevices 

>Another thought about the behaviour when the repo has origin. Why it is necessary to clone from origin? It is very often to have local repo that we do not want to push to any remote yet.

It only clones when it is not local (i.e. when building it as a dependency, not with ``conan create``), otherwise it copies the code from the user cloned repo. So in case you are doing ``conan create`` it will never clone from origin.

> Even when the repo is not dirty, we still have commits which are not pushed. Normally we want export local commits, which is not pushed, to .conan instead of using origin. And we should not automatically upload unless explicitly specified.

This is exactly the behavior, Conan copies the local commits. But it will not update the ``revision: auto`` to the commit in case the repo is dirty, because it will not be reproducible.


So I understand it is mainly a UX problem, if the repo is fully committed, but it has no origin, it raises an error, instead of allowing to locally build the package, and keep it the equivalent as dirty. I think this could be improved, what do you think @jgsogo ?

**Comment by braindevices** [comment] 2020-05-18 13:26
@memsharded @jgsogo I think the simplest way to fix this, is allow auto deduce to None when origin is missing. The revision can still stably obtained in this case so not entirely dirty situation.

**Comment by jgsogo** [comment] 2020-05-18 15:25
I think it is ok if we maintain the `url=auto` for this use case too (IMHO, `None` would add an extra bit of information, but it'd make it more complex and it information we don't need in the cache). Conan will allow exporting the recipe, but it will block the upload. While exporting we can output the proper message.

**Comment by memsharded** [comment] 2020-05-18 16:30
This is assigned for 1.27, but as I see  #7048 already opened if it is good on time, we might add it for 1.26. it would need some new test (or maybe some minor fix to some existing test) to capture the correct behavior, please @braindevices ask for help if you need with the PR. Thanks for contributing it!

**Closed as completed** 2020-05-26 12:17 UTC
Labels: type: bug, priority: low, stage: in-progress, complex: low
