### ISSUE TITLE
Conan + CMake not adding include dirs to 'Additional Include Directories' field Visual Studio

### ISSUE THREAD

**Issue by jamezmoran** [conan-io/conan#13713] opened 2023-04-18 06:12 UTC
[Environment]
Windows 11
Visual Studio 2019
conan version 2.0.4

I'm building a relatively simple project and pulling in SDL and GLEW, and generating a VS2019 solution using CMake + Conan.  I'm depending on these libraries like so:
![image](https://user-images.githubusercontent.com/6832121/232687411-7e58136a-4ed7-4016-99dd-0045b1e6c851.png)

The only problem is that although the project builds fine when I manually type out the dependencies header filenames, they don't show up in the drop down menu that visual studio gives when I start to include (in this case, trying to include SDL.h):
![image](https://user-images.githubusercontent.com/6832121/232685797-68f7956e-f4c3-4f4e-9beb-7a1059920392.png)

This is pretty annoying, and gets in the way of just including stuff from those libraries. I figured out that the reason it does this is because for whatever reason the include dirs are not being entered into the 'Additional Include Directories' field in the project preferences, although they are in the command line:
![image](https://user-images.githubusercontent.com/6832121/232686348-1e6ac898-de8b-4190-b547-0dbbc30d8556.png)
![image](https://user-images.githubusercontent.com/6832121/232686452-bc664f01-d5e5-471b-a787-1453e383b544.png)

Manually copying the directory from the command line string into that field allows the drop-down to open up:
![image](https://user-images.githubusercontent.com/6832121/232686696-dd0c3fb1-2e9a-45cd-a59c-8db6907adc06.png)

Is there any way to get these directories into those specific fields? I didn't have any issues when I had SDL checked out in a submodule and building as a subdirectory inside cmake, and then linking against the relevant SDL2 targets. Can something be done here in the general case too?

Thanks!

**Comment by memsharded** [comment] 2023-04-18 09:19
Hi @jamezmoran 

Thanks for your question.

I am trying to reproduce the issue, this is what I am doing:
- ``conan create cmake_lib -d name=pkg -d version=0.1`` to create a project
- Add ``requires = "zlib/1.2.13`` to ``conanfile.py``
- Add ``find_package(ZLIB)`` and ``target_link_lbiraries`` to ``CMakeLists.txt``:
```cmake

find_package(ZLIB)

add_library(pkg src/pkg.cpp)
target_include_directories(pkg PUBLIC include)
target_link_libraries(pkg ZLIB::ZLIB)
```
- ``conan build . --build=missing -s compiler.version=192``
- open generated ``build/pkg.sln`` solution in VS2019
- Switch to ``Release`` config

IDE now understand zlib, can navigate to it, autocompletes, etc.

No idea why it is not working in your case, if you could try the above and see if it works for you, and if it does, share your project (like the ``conanfile.py``, the actual command used to install the dependencies, the terminal output, etc), that could help a bit.

**Comment by jamezmoran** [comment] 2023-04-18 18:14
Thanks for the fast response! Glad to know it's not expected, my repo is at https://gitlab.com/jamezmoran/nonameengine, it's super simple so shouldn't be a trouble. I tried to strip it down a bit and nuked my build folder just incase, still doesn't show the headers in the drop down unfortunately. My command is `conan build . --build=missing`

**Comment by memsharded** [comment] 2023-04-18 21:37
It works in my case. After a couple of minor tweaks (remove the GameLoop source from CMakeLists and downgrade the requirs to CMake 3.25), I do the ``conan build . --build=missing`` I open the .sln project, switch to ``Release`` and the headers are correctly parsed, I can open the files in the IDE and the drop down works:

![Untitled](https://user-images.githubusercontent.com/15367152/232910758-12ec1b60-a96b-4b3e-b516-f999f6598cb2.png)

**Comment by memsharded** [comment] 2023-04-18 21:40
VS 2022, Community, Version 17.3.3, just in case.

**Comment by jamezmoran** [comment] 2023-04-20 06:06
Ok so I just installed VS 2022 and this now works on that version. Weird, it just wasn't cooperating at all on 2019. Thanks for the help!

**Comment by memsharded** [comment] 2023-04-20 08:23
I think there are some glitches in the interaction between different modern CMake versions and different VS versions, not that related to Conan, I have seen navigating.

So it seems we can close this issue (but don't hesitate to re-open or create a new ticket for any further question), thanks!

**Closed as completed by memsharded** 2023-04-20 08:23 UTC
Labels: stage: triaging

**Comment by dxli** [comment] 2023-08-25 21:06
I always got this, "header not found". For example, trying to run example2:
```cmd
echo on
git clone https://github.com/conan-io/examples2.git
pushd examples2\tutorial\consuming_packages\conanfile_py
conan profile detect --force
conan install . --output-folder=build --build=missing
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
cmake --build .
popd
```
but I ran into an error saying the package (ZLIB) header not found:
_
C:\Users\didi\dev\examples2\tutorial\consuming_packages\conanfile_py\build>cmake --build .
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/Users/didi/dev/examples2/tutorial/consuming_packages/conanfile_py/CMakeLists.txt
  main.c
C:\Users\didi\dev\examples2\tutorial\consuming_packages\conanfile_py\src\main.c(5,10): fatal  error C1083: Cannot open
include file: 'zlib.h': No such file or directory [C:\Users\didi\dev\examples2\tutorial\consuming_packages\conanfile_py
\build\compressor.vcxproj]_

The complete commands and output is also attached: 
[conan_headers.txt](https://github.com/conan-io/conan/files/12443479/conan_headers.txt)

**Comment by memsharded** [comment] 2023-08-27 09:47
Hi @dxli 

It seems you are using the wrong commands, as it seems you are in Windows - Visual studio and that is "multi-config" build system. If you check the docs in https://docs.conan.io/2/tutorial/consuming_packages/build_simple_cmake_project.html, it tells to use:

```
$cmake .. -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake
$ cmake --build . --config Release
```

In Visual Studio:
- You don't pass ``-DCMAKE_BUILD_TYPE=xxx`` in the configure step
- You pass ``--config Release`` in the build step

**Comment by Dhananjay-JSR** [comment] 2023-10-07 18:50
`In Visual Studio:`

`You don't pass -DCMAKE_BUILD_TYPE=xxx in the configure step`
`You pass --config Release in the build step`

this fixed the issue for me, but I am now confused because DCMAKE_BUILD_TYPE=Release does the same work as --config Release , so it shouldn't be having issue in first place

EDIT :-

oh man , building on Linux is much more simpler than on Windows , Just got to know that VS Solution doesn't support build-type configuration while generating SLN project, you have to provide them during build process manually

**Comment by memsharded** [comment] 2023-10-07 20:16
Yes, @Dhananjay-JSR that is the issue, VS is multi-configuration, that means that the build_type can only be defined at "build" time, not at "configure" time (generating the VS project). Not related to Conan really, this is how cmake and VS works.

**Comment by shdwjk** [comment] 2024-07-13 15:13
I was having this same issue.  In my case, the missing piece was that if you run cmake with `--config Release`, you must also manually select `Release` in the Configuration dropdown in Visual Studio because it is the only one that will be set up to link to the libraries from Conan.

**Comment by memsharded** [comment] 2024-07-14 18:12
Yes, @shdwjk if you want to switch from Debug to Release in the IDE, then the recommendation is to do the ``conan install`` for both configurations first.
