### ISSUE TITLE
[feature] extand build requirements to support more cross-compile

### ISSUE THREAD

**Issue by Mingyiz** [conan-io/conan#7582] opened 2020-08-24 02:17 UTC
In cross-compiling cases, some package need the tools of itself. This scenario has been described in [conan docs - Build and Host contexts](https://docs.conan.io/en/latest/devtools/build_requires.html?highlight=build%20requirement#build-and-host-contexts) the  `protobuffer` package is what I said. And [Bincrafters ICU](https://github.com/bincrafters/conan-icu/blob/testing/66.1/conanfile.py) is another example for ARM building on X86 Linux building machine.

My  thought is to extend (may  be split part of current build requirement functionality) build-tools part to avoid current conflicts on settings.os/settings.os_build, settings.arch/settings.arch_build. 

For example. The   [GLib](https://github.com/conan-io/conan-center-index/tree/master/recipes/glib) is widely used as library and as GNome tool during building. When working as a compiling tool, its setting's os_build/os_arch should be should be corresponding package's  os/arch. Currently these info can be set in package_id, but now we could not handle this in one package since I don’t know whether it is used as a compilation tool or a link library (previous bincraft will create xxx_installer for building tools). Also, the current executable path information is written in package_info, which my not work well on cross-compiling.

I am not sure the thought is too big, any feedback I'd glad to discuss.

- [Y] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2020-08-24 07:52
Hi @Mingyiz 

If I understood this correctly, this is not a feature request for Conan tool, but a feature request to recipes in ConanCenter https://github.com/conan-io/conan-center-index (by the way your GLib link was broken).

Yes, there is a plan to move recipes in ConanCenter to the new cross-build model with contexts, but it will take some time, it is not that easy, and it will require all ConanCenter users, which is a ton to move to that new cross-build model, which is relatively new and experimental, so it will certainly break many ConanCenter users.

Please confirm that you are talking about changes in recipes and I will transfer this to the conan-center-index repo.

**Comment by jgsogo** [comment] 2020-08-24 08:42
Hi, @Mingyiz 

Packages in ConanCenter are moving in the other direction, there aren't `xxx_installer` packages anymore and settings `os_build/arch_build` are being removed from recipes. Recipes like `protobuf`, `icu` and many others contain libraries and executables and the only way to build them and use them as dependencies (libraries to link) and build tools (executables to run in a cross-building scenario) is to use the new approach with the two profiles, which requires adding the same reference as requirement and build-requirements. 

This new model with the two profiles works pretty well, and supersedes most of the problems we had with the old `os_build/arch_build` settings, but it is totally true that recipes prepared for this new model don't work well in a cross-building scenario that tries to use the old model with a single profile.

Have you tried to use the new approach with the two profiles? Did you find any issue?

Thanks for your feedback.

**Comment by Mingyiz** [comment] 2020-08-25 08:54
Hi, @jgsogo 
Just now, I have tried the two profiles approach on [VS2019 with x86 and x86_64 cross-building](https://github.com/Mingyiz/conan-experimental-feature-investigation/tree/master/cross-building/split-profiles), it works. Thanks for you advice, I believe my thoughts has been supported after with this new conan experimental feature. I will do my farther work on the real cross-building with the two-profiles method.

@memsharded Thanks for your explaining, this ticket can be closed, I would open new  recipes related issue on ConanCenter if met problem on two-profile approach.

**Comment by jgsogo** [comment] 2020-08-25 09:04
If the problem is very specific to a recipe open the issue there, if you feel like you have found some corner case or issue related to the two-profiles, or something that could be explained better or anything we can learn from your experience, please open the issue here (in `conan-center-index` we can't read every message)... every feedback about the feature will be more than welcome.

Thanks!

**Comment by Mingyiz** [comment] 2020-08-26 06:49
@jgsogo 
I found some problem in test_package, normally we not define options in test_package/conanfile.py. but if we still do so in two-profiles an error will bee occured. this can be reproduced with my test [VS2019 with x86 and x86_64 cross-building split-profiles](https://github.com/Mingyiz/conan-experimental-feature-investigation/tree/master/cross-building/split-profiles),



```
$ cd toolset
$ create . -pr:h ../profiles/vs2019-x86_64 -pr:b ../profiles/vs2019-x86_64

Exporting package recipe
toolset/1.0.0 exports_sources: Copied 1 '.txt' file: CMakeLists.txt
toolset/1.0.0 exports_sources: Copied 2 '.c' files: libtoolset.c, toolset.c
toolset/1.0.0 exports_sources: Copied 1 '.h' file: libtoolset.h
toolset/1.0.0: The stored package has not changed
toolset/1.0.0: Exported revision: fc5a1ea3cabea274f1328b63c7ae57dc
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

toolset/1.0.0: Forced build from source
toolset/1.0.0 (test package): Installing package
Requirements
    toolset/1.0.0 from local cache - Cache
Packages
    toolset/1.0.0:3fb49604f9c2f729b85ba3115852006824e72cab - Build

Installing (downloading, building) binaries...
toolset/1.0.0: Copying sources to build folder
toolset/1.0.0: Building your package in C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
toolset/1.0.0: Generator cmake created conanbuildinfo.cmake
toolset/1.0.0: Calling build()
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.25.28614.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- This project seems to be plain C, using 'MSVC' compiler
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY
    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_DATAROOTDIR
    CMAKE_INSTALL_INCLUDEDIR
    CMAKE_INSTALL_LIBDIR
    CMAKE_INSTALL_LIBEXECDIR
    CMAKE_INSTALL_OLDINCLUDEDIR
    CMAKE_INSTALL_SBINDIR


-- Build files have been written to: C:/Users/mingyi/.conan/data/toolset/1.0.0/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab
ÓÃÓÚ .NET Framework µÄ Microsoft (R) Éú³ÉÒýÇæ°æ±¾ 16.5.0+d4cbfca49
°æÈ¨ËùÓÐ(C) Microsoft Corporation¡£±£ÁôËùÓÐÈ¨Àû¡£

  Checking Build System
  Building Custom Rule C:/Users/mingyi/.conan/data/toolset/1.0.0/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/src/CMakeLists.txt
  libtoolset.c
  libtoolset.vcxproj -> C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\lib\libtoolset.lib
  Building Custom Rule C:/Users/mingyi/.conan/data/toolset/1.0.0/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/src/CMakeLists.txt
  toolset.c
C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\src\toolset.c(9,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\toolset.vcxproj]
C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\src\toolset.c(10,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\toolset.vcxproj]
C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\src\toolset.c(11,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\toolset.vcxproj]
C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\src\toolset.c(12,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\toolset.vcxproj]
C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\src\toolset.c(13,5): warning C4996: 'sprintf': This function or variable may be unsafe. Consider using sprintf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\toolset.vcxproj]
C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\src\toolset.c(15,19): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\toolset.vcxproj]
    ÕýÔÚ´´½¨¿â C:/Users/mingyi/.conan/data/toolset/1.0.0/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/lib/toolset.lib ºÍ¶ÔÏó C:/Users/mingyi/.conan/data/toolset/1.0.0/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/lib/toolset.exp
  toolset.vcxproj -> C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab\bin\toolset.exe
  Building Custom Rule C:/Users/mingyi/.conan/data/toolset/1.0.0/_/_/build/3fb49604f9c2f729b85ba3115852006824e72cab/src/CMakeLists.txt
toolset/1.0.0: Package '3fb49604f9c2f729b85ba3115852006824e72cab' built
toolset/1.0.0: Build folder C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\build\3fb49604f9c2f729b85ba3115852006824e72cab
toolset/1.0.0: Generated conaninfo.txt
toolset/1.0.0: Generated conanbuildinfo.txt
toolset/1.0.0: Generating the package
toolset/1.0.0: Package folder C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab
toolset/1.0.0: Calling package()
toolset/1.0.0 package(): Packaged 1 '.exe' file: toolset.exe
toolset/1.0.0 package(): Packaged 1 '.h' file: libtoolset.h
toolset/1.0.0 package(): Packaged 2 '.lib' files: libtoolset.lib, toolset.lib
toolset/1.0.0 package(): Packaged 1 '.exp' file: toolset.exp
toolset/1.0.0: Package '3fb49604f9c2f729b85ba3115852006824e72cab' created
toolset/1.0.0: Created package revision 76aa1be55594dea2ce7af867886776ae
toolset/1.0.0: Append tool-set path C:\Users\mingyi\.conan\data\toolset\1.0.0\_\_\package\3fb49604f9c2f729b85ba3115852006824e72cab\bin
toolset/1.0.0 (test package): Generator cmake created conanbuildinfo.cmake
toolset/1.0.0 (test package): Generator txt created conanbuildinfo.txt
toolset/1.0.0 (test package): Generated conaninfo.txt
toolset/1.0.0 (test package): Generated graphinfo
Using lockfile: 'D:\github.com\mingyiz\conan-experimental-feature-investigation\cross-building\split-profiles\toolset\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb/conan.lock'
Using cached profile from lockfile
toolset/1.0.0 (test package): Calling build()
ERROR: toolset/1.0.0 (test package): Error in build() method, line 14
        cmake = CMake(self)
        ConanException: option 'shared' doesn't exist
Possible options are []
```

**Comment by memsharded** [comment] 2024-11-25 22:33
Sorry this was not followed up back then.

Now this ticket is quite outdated, closing as outdated. Everything has changed since then:
- New recipes in ConanCenter
- New cross-build model
- New Conan 2, with new build system integrations and generators.
Please report new tickets against Conan 2 if necessary, thanks for your feedback.

**Closed as not planned by memsharded** 2024-11-25 22:33 UTC
Labels: stage: triaging
