### ISSUE TITLE
[feature] Automatic virtualenv/virtualrunenv application

### ISSUE THREAD

**Issue by aleksa2808** [conan-io/conan#8748] opened 2021-03-31 19:08 UTC
Hi,
would it be possible to somehow apply (or at least reapply) the `virtualenv`/`virtualrunenv` `activate_run` scripts when a `conan install` command is ran? The scenario I have in mind specifically is a situation where you would change the version of some dependencies and rebuild, but the LD_LIBRARY_PATH variable would stay the same since it seems easy to forget running `deactivate_run` + `activate_run` every time.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-04-11 22:23
Hi @aleksa2808 

This seems very unlikely, actually impossible as far as I know.
The problem is that Conan runs as a python subprocess. Everything that runs under a subprocess cannot change the environment of the parent process. This is exactly the same reason why Conan itself cannot activate an environment, only generate the file, but it is the user that needs to call the generated file. The best you could do to minimize this, if you do this very often, is to create some script in your system that do something like:

```bash
source deactivate_run.sh
conan install <path> <profile> <settings> # This could be forwarded
source activate_run.sh
```
This seems very particular for each user case, and in any case it still will be a shell script, it cannot be a Conan command. So I am afraid that this is something that we can't do at all.

**Comment by aleksa2808** [comment] 2021-04-30 17:00
Hey, sorry for the late reply.

I see, what you said makes sense. I opened this issue because it's sometimes troublesome to explain to new Conan users why we need virtualrunenv/imports and the need to reapply the env vars complicates it further. One other addition that comes to mind which could simplify this would be something like a `conan run` which bootstraps the environment, I'm not sure if this topic was discussed before.

Anyway, this isn't too much of a bother and with what you said in mind, I think there's no quick solution for this. So if you ask me this issue can be closed for now.

**Comment by jakefhyde** [comment] 2021-05-14 02:45
I agree that it's not an issue for now, but I am curious as to what can be done configuration wise for package consumer. For example, I'm building a few packages from source and have created `conanfile.py` files for them (hoping to get them into the conan-center), one of them being `tmux`. I'm currently using a method that manually requires me to put each package in my path at once (so I can have an entry somewhere in my `.zshrc` for each of my executable conan dependencies (`ninja`, `cmake`, `tmux`, `cppcheck`, etc.) via 
```
mkdir -p $HOME/.dotfiles/.venv
# virtualenv
cd $HOME/.dotfiles/.venv
for f in ncurses/6.2; do 
    cd $HOME/.dotfiles/.venv && mkdir -p $f && cd $f && conan install $f@ -g virtualenv && source ./activate.sh; 
done

# virtualrunenv
cd $HOME/.dotfiles/.venv
for f in ncurses/6.2 tmux/3.2 cppcheck/2.4.1; do 
    cd $HOME/.dotfiles/.venv && mkdir -p $f && cd $f && conan install $f@ -g virtualrunenv && source ./activate_run.sh; 
done
cd $HOME
```
but I'm curious as to what other methods may be preferred, as this also ends up running every time I enter tmux (also considering writing a `virtualenvwrapper` integrated utility to do this per `virtualenv`). At least in this example, an application like tmux has both `virtualenv` and `virtualrunenv` dependencies (`LD_LIBRARY_PATH` and `TERMINFO`) which could probably be maintained better than my little script

**Comment by memsharded** [comment] 2023-12-22 01:14
These generators are legacy, superseded by ``VirtualXXXEnv`` ones, and removed in 2.0. Closing this ticket as outdated, thanks!

**Closed as not planned by memsharded** 2023-12-22 01:14 UTC
Labels: stage: triaging
