### ISSUE TITLE
[question/bug?] Problems building anything on arch=x86 under windows

### ISSUE THREAD

**Issue by EugenMayer** [conan-io/conan#6796] opened 2020-04-04 17:04 UTC
Hello,

i have proper builds of qt and qca using arch=x86_64 under windows, but when using arch=x86 both build fail with the same reason.

Both are build under windows10, visual-studio 2019 - you see the flags below.

Scanning bincrafters i hardly find anything build for arch x86 (as QT/QCA are not either - so my question, is that broken entirely under windows / discourage / impossible what so ever?

Thank you!

QT
```
2020-04-04T16:34:33.9455698Z ##[section]Starting: build
2020-04-04T16:34:33.9632616Z ==============================================================================
2020-04-04T16:34:33.9632987Z Task         : Bash
2020-04-04T16:34:33.9633303Z Description  : Run a Bash script on macOS, Linux, or Windows
2020-04-04T16:34:33.9633614Z Version      : 3.163.1
2020-04-04T16:34:33.9633869Z Author       : Microsoft Corporation
2020-04-04T16:34:33.9634486Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2020-04-04T16:34:33.9634928Z ==============================================================================
2020-04-04T16:34:34.8753357Z Generating script.
2020-04-04T16:34:34.8755804Z [command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc -c pwd
2020-04-04T16:34:34.8756134Z /d/a/_temp
2020-04-04T16:34:34.8756261Z 
2020-04-04T16:34:34.8757228Z ========================== Starting Command Output ===========================
2020-04-04T16:34:34.8758720Z [command]"C:\Program Files\Git\bin\bash.exe" --noprofile --norc /d/a/_temp/dbeb0ba8-01a5-4155-afe3-cf26422a20c9.sh
2020-04-04T16:34:34.8759211Z ensure MSBuild is in path
2020-04-04T16:34:34.8759427Z starting build
2020-04-04T16:34:34.8759722Z Cloning into 'C:/Users/VSSADM~1/AppData/Local/Temp/qt.GGOiMk3pt'...
2020-04-04T16:34:36.3759109Z Building Qt in '/tmp/qt.GGOiMk3pt/build'
2020-04-04T16:34:37.2719340Z Exporting package recipe
2020-04-04T16:34:37.2743525Z qt/5.14.1@kwconan/stable exports: File 'conandata.yml' found. Exporting it...
2020-04-04T16:34:37.2951068Z qt/5.14.1@kwconan/stable exports: Copied 1 '.yml' file: conandata.yml
2020-04-04T16:34:37.2951943Z qt/5.14.1@kwconan/stable exports: Copied 1 '.conf' file: qtmodules.conf
2020-04-04T16:34:37.2952391Z qt/5.14.1@kwconan/stable exports: Copied 5 '.diff' files
2020-04-04T16:34:37.3060527Z qt/5.14.1@kwconan/stable: The stored package has not changed
2020-04-04T16:34:37.3077504Z qt/5.14.1@kwconan/stable: Exported revision: 71c025e0a722b588c7db4b72539c7cdf
2020-04-04T16:34:37.3078269Z Configuration:
2020-04-04T16:34:37.3078512Z [settings]
2020-04-04T16:34:37.3078686Z arch=x86
2020-04-04T16:34:37.3078852Z arch_build=x86
2020-04-04T16:34:37.3079034Z build_type=Release
2020-04-04T16:34:37.3079257Z compiler=Visual Studio
2020-04-04T16:34:37.3079453Z compiler.runtime=MD
2020-04-04T16:34:37.3079663Z compiler.version=16
2020-04-04T16:34:37.3079839Z os=Windows
2020-04-04T16:34:37.3080025Z os_build=Windows
2020-04-04T16:34:37.3080194Z [options]
2020-04-04T16:34:37.3080377Z qca:shared=True
2020-04-04T16:34:37.3080555Z qt:opengl=no
2020-04-04T16:34:37.3080747Z qt:qttools=True
2020-04-04T16:34:37.3080925Z qt:shared=True
2020-04-04T16:34:37.3081116Z qt:with_fontconfig=True
2020-04-04T16:34:37.3081340Z qt:with_harfbuzz=False
2020-04-04T16:34:37.3081543Z qt:with_libalsa=False
2020-04-04T16:34:37.3081761Z qt:with_libjpeg=False
2020-04-04T16:34:37.3081958Z qt:with_libpng=True
2020-04-04T16:34:37.3082166Z qt:with_mysql=False
2020-04-04T16:34:37.3082358Z qt:with_odbc=False
2020-04-04T16:34:37.3082572Z qt:with_openal=False
2020-04-04T16:34:37.3082767Z qt:with_pcre2=True
2020-04-04T16:34:37.3082967Z qt:with_pq=False
2020-04-04T16:34:37.3083154Z qt:with_sdl2=False
2020-04-04T16:34:37.3083593Z qt:with_sqlite3=False
2020-04-04T16:34:37.3083788Z [build_requires]
2020-04-04T16:34:37.3083949Z [env]
2020-04-04T16:34:37.3084076Z 
2020-04-04T16:34:42.5183795Z qt/5.14.1@kwconan/stable: Forced build from source
2020-04-04T16:34:42.5212574Z msys2/20190524: Not found in local cache, looking in remotes...
2020-04-04T16:34:42.5213850Z msys2/20190524: Trying with 'conan-center'...
2020-04-04T16:34:42.7124987Z Downloading conanmanifest.txt
2020-04-04T16:34:42.9089176Z Downloading conanfile.py
2020-04-04T16:34:43.0881044Z Downloading conan_export.tgz
2020-04-04T16:34:43.2886107Z msys2/20190524: Downloaded recipe revision 0
2020-04-04T16:34:43.4979072Z 7zip/19.00: Not found in local cache, looking in remotes...
2020-04-04T16:34:43.4979976Z 7zip/19.00: Trying with 'conan-center'...
2020-04-04T16:34:43.6838750Z Downloading conanmanifest.txt
2020-04-04T16:34:43.8631622Z Downloading conanfile.py
2020-04-04T16:34:44.0410050Z Downloading conan_export.tgz
2020-04-04T16:34:44.2275732Z 7zip/19.00: Downloaded recipe revision 0
2020-04-04T16:34:44.5156373Z lzma_sdk/9.20: Not found in local cache, looking in remotes...
2020-04-04T16:34:44.5162914Z lzma_sdk/9.20: Trying with 'conan-center'...
2020-04-04T16:34:44.6907222Z Downloading conanmanifest.txt
2020-04-04T16:34:44.8768698Z Downloading conanfile.py
2020-04-04T16:34:45.0590097Z Downloading conan_export.tgz
2020-04-04T16:34:45.2575656Z lzma_sdk/9.20: Downloaded recipe revision 0
2020-04-04T16:34:45.3123753Z make/4.2.1: Not found in local cache, looking in remotes...
2020-04-04T16:34:45.3124973Z make/4.2.1: Trying with 'conan-center'...
2020-04-04T16:34:45.4901245Z Downloading conanmanifest.txt
2020-04-04T16:34:45.6774644Z Downloading conanfile.py
2020-04-04T16:34:45.8600034Z Downloading conan_export.tgz
2020-04-04T16:34:46.0742635Z make/4.2.1: Downloaded recipe revision 0
2020-04-04T16:34:46.4528625Z WARN: libxml2/2.9.9: requirement libiconv/1.15 overridden by gettext/0.20.1@bincrafters/stable to libiconv/1.16 
2020-04-04T16:34:46.4617539Z ERROR: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20190524' which is an ancestor too
2020-04-04T16:34:46.5309458Z 
```

QCA

```
ensure MSBuild is in path
starting build
Cloning into 'C:/Users/VSSADM~1/AppData/Local/Temp/qca.9CytBkXAs'...
Building QCA in '/tmp/qca.9CytBkXAs/build'
Exporting package recipe
qca/2.2.1@kwconan/stable exports: Copied 2 '.patch' files: qca_relative_imported_include_path.patch, qca_target_file_for_configuration.patch
qca/2.2.1@kwconan/stable: A new conanfile.py version was exported
qca/2.2.1@kwconan/stable: Folder: D:\a\1\.conan\data\qca\2.2.1\kwconan\stable\export
qca/2.2.1@kwconan/stable: Exported revision: 49a56e0abee20e00d4a3bb96f2ccd62ddd8b8b7f
Configuration:
[settings]
arch=x86
arch_build=x86
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
qca:shared=True
qt:opengl=no
qt:qttools=True
qt:shared=True
qt:with_fontconfig=True
qt:with_harfbuzz=False
qt:with_libalsa=False
make/4.2.1: Downloaded recipe revision 0
WARN: libxml2/2.9.9: requirement libiconv/1.15 overridden by gettext/0.20.1@bincrafters/stable to libiconv/1.16 
ERROR: Loop detected: 'lzma_sdk/9.20' requires 'msys2/20190524' which is an ancestor too
```

**Comment by memsharded** [comment] 2020-04-04 19:51
Hi @EugenMayer 

From what I see, this might be mostly an issue of the Qt recipe you are using, isn't it?
It seems you are having a loop in your requirements, which might come from a conditional requirement that depends on the architecture only. We would need to have a look to those recipes in order to help. Of course a simplified case, with very simple "hello world" recipes would be very helpful to sort out if it is a Conan issue, a recipe issue or what could it be.

**Comment by bugproof** [comment] 2020-04-06 17:05
conan is acting crazy... I was building my project fine and suddenly it stopped working and it's trying to build libiconv even despite I don't use it and it fails building it.

```
conanfile.txt: Installing package
Requirements
    gtest/1.8.1@bincrafters/stable from 'conan-center' - Cache
    imgui/1.75 from 'conan-center' - Cache
    libiconv/1.15 from 'conan-center' - Cache
    openal/1.19.1 from 'conan-center' - Cache
    sdl2/2.0.10@bincrafters/stable from 'bincrafters' - Cache
    toml11/3.1.0 from 'conan-center' - Cache
    zlib/1.2.11@conan/stable from 'conan-center' - Cache
Packages
    gtest/1.8.1@bincrafters/stable:11cd7482b8e2ac950facc1e612d53be84acedae7 - Cache
    imgui/1.75:29d1f4003b3f7143826ef1988625574513d526ce - Cache
    libiconv/1.15:29d1f4003b3f7143826ef1988625574513d526ce - Build
    openal/1.19.1:7b67ea8a8298b2c22e3896c8cb83cc30002fb75b - Cache
    sdl2/2.0.10@bincrafters/stable:be856ea8d644734bdae7a530f6488801ab8b7b43 - Build
    toml11/3.1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    zlib/1.2.11@conan/stable:29d1f4003b3f7143826ef1988625574513d526ce - Cache
```

**Comment by memsharded** [comment] 2020-04-06 17:15
Hi @bugproof 

Sorry, I don't see how your comment is related to this issue. It doesn't seem related at all, or I am missing a lot of information. I would suggest to submit a new Github issue with details instructions how to reproduce the problem you are reporting.

**Comment by EugenMayer** [comment] 2020-04-06 17:24
@memsharded well i mean this is the official QT recipe of https://github.com/bincrafters/conan-qt - i would not really consider them to be new to conan, nor to QT or the build process. What do you think?

**Comment by bugproof** [comment] 2020-04-06 17:31
@memsharded I realized it's fault of SDL2 recipe, libiconv fails to build on windows.

**Comment by memsharded** [comment] 2020-04-06 20:57
Regarding the recipes in https://conan.io/center/, please let me clarify one thing:

The packages automatically created from the conan-center-index repo: https://github.com/conan-io/conan-center-index/ are the ones without the ``@user/channel`` part. The current efforts by the community are largely focused on these new packages, and the old ones (including user/channel), will hopefully be migrated to the new system. 

The new build service in conan-center-index integrates a bunch of improvements, much more automatic quality checks, and it can build new binaries for new compiler versions when they are released.

**Comment by memsharded** [comment] 2020-04-06 20:58
> @memsharded I realized it's fault of SDL2 recipe, libiconv fails to build on windows.

@bugproof Please report in https://github.com/conan-io/conan-center-index/ if libiconv doesn't build on Windows, so it can be fixed.

**Comment by memsharded** [comment] 2024-11-25 22:45
Closing this ticket as outdated, this conversation refers to packages other than the new ones in ConanCenter.
Also, Conan has changed a lot since then, including a major Conan 2 release almost 2 years ago.

If there are any questions or issues, please open a new ticket against Conan 2, thanks for your feedback.

**Closed as not planned by memsharded** 2024-11-25 22:45 UTC
