### ISSUE TITLE
conan test_package may force rebuild of dependee

### ISSUE THREAD

**Issue by sixten-hilborn** [conan-io/conan#1366] opened 2017-06-08 06:58 UTC
For instance I've created two packages, `foo` and `foobar`, where foo depends on foobar.
Using `test_package` command will force a rebuild of foobar even if the binaries are there (I suspect it's because foobar starts with "foo"):

    ~/foo$ conan test_package .
    ...
    foobar/0.1@hilborn/stable: WARN: Forced build from source

**Comment by memsharded** [comment] 2017-06-08 09:54
Yes, confirmed, this is because of ``foo`` is translated to a pattern, that finally matches foobar.
Trying to find a fix.

**Comment by memsharded** [comment] 2017-06-17 21:11
Released in 0.24

**Closed by memsharded** 2017-06-17 21:11 UTC
Labels: bug, fixed
