### ISSUE TITLE
[question] Revision handling 

### ISSUE THREAD

**Issue by mh-ka** [conan-io/conan#11267] opened 2022-05-16 15:12 UTC
Hello there,

I have a few questions regarding revisions:
- Can the revision feature be disabled in artifactory itself or is this purely set on client side?
- Can package versions with revisions be consumed by a client after deactivating the revision feature? Or will conan strictly separate between package versions with and without revisions?
- Can a package version have both a non-revisioned folder called "0" and revisioned folders with hash names? And how can these be cleaned up safely in artifactory?

Regards,
M

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-05-16 15:22
> Can the revision feature be disabled in artifactory itself or is this purely set on client side?

It is enabled purely on client side, Artifactory always support revisions.

> Can package versions with revisions be consumed by a client after deactivating the revision feature? Or will conan strictly separate between package versions with and without revisions?

They can, technically, but it can get a bit messy. The recommendation is that moving to use revisions should be uniform, and all-in, do not mix with and without revisions in general.

> Can a package version have both a non-revisioned folder called "0" and revisioned folders with hash names? And how can these be cleaned up safely in artifactory?

Yes, it can. But the issue is about what is understood as "latest". Because the "0" revision can also become latest, but that is a bit weird for clients with revisions enabled. So storage-wise it will not break, and Artifactory will keep working, but the revision you get installed in the client depending on if using revisions or not using them could be sometimes a bit unexpected or non-intuitive.

**Comment by mh-ka** [comment] 2022-05-16 16:29
Thank you for your answers.

- By default, conan revisions are disabled on the client?
- If at lease one client activates revisions and uploads a revision, every consumer of this package version will automatically have to activate revisions? Or what is the exact trigger for conan to start displaying the message "[...]only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1[...]"?

The reason I am asking is that the message delivered by conan for revision activation only gives information about the remote, e.g. https://gitter.im/Worldforge/Lobby?at=61671d24cd4972068b463f1c -> _The remote at 'https://artifactory.ogenvik.org/artifactory/api/conan/conan' only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1 or set 'general.revisions_enabled = 1' at the 'conan.conf'_

**Comment by memsharded** [comment] 2022-05-16 17:07
> By default, conan revisions are disabled on the client?

Yes, they are disabled, because of the stability commitment (check https://docs.conan.io/en/latest/introduction.html#stable), revisions had to be introduced as an opt-in feature

> If at lease one client activates revisions and uploads a revision, every consumer of this package version will automatically have to activate revisions? Or what is the exact trigger for conan to start displaying the message "[...]only works with revisions enabled. Set CONAN_REVISIONS_ENABLED=1[...]"?

Not necessarily. I think other clients might still use that package revision. The message that are you seeing happen when "virtual" and "remote" repositories are used in Artifactory. Those repository types need to have revisions enabled, because it is the only way to achieve consistency while aggregating packages from different repositories. So this message comes from the server special repo type, it is not because of different clients connecting to it.

**Comment by mh-ka** [comment] 2022-05-17 12:59
Thanks, this info is very helpful :-)

**Closed as completed** 2022-05-17 12:59 UTC
Labels: type: question, stage: triaging
