### ISSUE TITLE
[question] How to add/change a require in lock file properly

### ISSUE THREAD

**Issue by refactorTractor** [conan-io/conan#8331] opened 2021-01-13 15:02 UTC
In our project we have a `conanfile.txt` recipe, and for each build configuration we have a lock file. We have a few dependency management scenarios that raise issues, and we do not seem to find a good description anywhere on how to do them.
- updating a dependency version
- adding a new dependency
- removing a dependency

We've been trying to do this by adding/changing the dependency in the recipe, then using some command to update the lock files, but this has proven beyond our understanding.

`conan install` will throw an error that one of the dependencies in the lock file is missing or superfluous.
`conan lock create` using an input lock file, will throw an error, that the lock file does not contain the package named in the recipe.
`conan lock create` without an input lock file but then calling `conan lock update` will also throw an error due to dependency mismatch.

Could you please provide me with a definitive guide of doing these simple steps? I'm sorry, I feel these are so basic, yet I couldn't find any documentation that clearly states how such use-cases can be accomplished without manually editing or replacing the lock file. Or is it intended for lock files to be manually replaced with new ones when dependencies change?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-01-17 23:27
Hi @AGreat1 

First, let me comment that lockfiles have been improving in the last releases, please let us know the version that you are running, and if not latest, I would strongly suggest to upgrade Conan.

The reference guide for what can be done with lockfiles is in https://docs.conan.io/en/latest/versioning/lockfiles.html. If you check the notes there, you can see that there are working examples in https://github.com/conan-io/examples, which can be reproduced completely. That would be a good starting point, have you had a chance to try them?

Lockfiles should never be manually edited, that is correct. For the cases you are commenting, I think we should go one by one, discussing them in detail and steps to reproduce. Sometimes it is just that it is necessary to specify ``--user`` and ``--channel`` if the conanfile is local, for example. Please let me know about the above first, thanks!

**Comment by refactorTractor** [comment] 2021-01-20 17:15
Hi!

I now updated to 1.33.0. I was not familiar with this description of lock files. It wasn't so sophisticated at about 1.22.x when our project joined the ride. Anyway, I now created a base lock file, and started creating configuration-specific locks. I just got a new RREV for openssl, so it must be built. Following [this](https://docs.conan.io/en/1.32/versioning/lockfiles/evolving.html#unlocking-packages-with-build) I created the lock file, issuing this command: `conan lock create --reference=openssl/1.1.1f@ISW/MachineAgent --build=openssl --lockfile=conan.locks\win32\Debug\new.lock --lockfile-out=conan.locks\win32\Debug\openssl.lock -r captain-siemens` .

This was the output of that command:
```
openssl/1.1.1f@ISW/MachineAgent: Forced build from source
openssl/1.1.1f@ISW/MachineAgent: WARN: Build-require 'strawberryperl' cannot be found in lockfile
openssl/1.1.1f@ISW/MachineAgent: WARN: Build-require 'nasm' cannot be found in lockfile
Requirements
    openssl/1.1.1f@ISW/MachineAgent from local cache - Cache
Packages
    openssl/1.1.1f@ISW/MachineAgent:e747a90c1701255809c1a88942f4da4f1c5f0c23 - Build
Build requirements
    nasm/2.14 from 'captain-siemens' - Cache
    strawberryperl/5.30.0.1 from 'captain-siemens' - Cache
Build requirements packages
    nasm/2.14:45b43bcd991ec89baf1eb618b595ca3227a3cf0b - Missing
    strawberryperl/5.30.0.1:456f15897172eef340fcbac8a70811f2beb26a93 - Download

Generated lockfile: ******\thirdparties\conan.locks\win32\Debug\openssl.lock
```

This was the generated lock file:

```{
 "graph_lock": {
  "nodes": {
   "2": {
    "ref": "openssl/1.1.1f@ISW/MachineAgent#e6f838a970051ec34893b909fca36a17",
    "options": "386=False\ncapieng_dialog=False\nenable_capieng=False\nno-ec2m=True\nno_asm=False\nno_async=False\nno_bf=False\nno_cast=False\nno_des=False\nno_dh=False\nno_dsa=False\nno_dso=False\nno_hmac=False\nno_md5=False\nno_mdc2=False\nno_rc2=False\nno_rsa=False\nno_sha=False\nno_sse2=False\nno_threads=False\nopenssldir=None\nshared=False\nwith_rand_seed_devrandom=False\nxp_compatible=False",
    "package_id": "e747a90c1701255809c1a88942f4da4f1c5f0c23",
    "build_requires": [
     "11",
     "12"
    ],
    "context": "host"
   },
   "11": {
    "ref": "strawberryperl/5.30.0.1#3cf9ed4bb8c4d2a22a9f3f0735788478",
    "options": "",
    "package_id": "456f15897172eef340fcbac8a70811f2beb26a93",
    "prev": "8762274745d3e959a2aa10b871975b04",
    "context": "host"
   },
   "12": {
    "ref": "nasm/2.14#deaa38d665d7a31d71c67acf7e5c98ca",
    "options": "",
    "package_id": "45b43bcd991ec89baf1eb618b595ca3227a3cf0b",
    "context": "host"
   }
  },
  "revisions_enabled": true
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86\narch_build=x86_64\nbuild_type=Debug\ncompiler=Visual Studio\ncompiler.runtime=MDd\ncompiler.version=16\nos=Windows\nos_build=Windows\n[options]\n[build_requires]\n[env]\n"
}
```

then I issued `conan install openssl/1.1.1f@ISW/MachineAgent -r captain-siemens --build missing --lockfile=conan.locks\win32\Debug\openssl.lock --lockfile-out=conan.locks\win32\Debug\openssl_built.lock`

I received the following error message: `ERROR: Build-require 'strawberryperl' cannot be found in lockfile`
This, as seen above, is not true. Have I found a bug here?

**Comment by refactorTractor** [comment] 2021-01-21 08:55
I found the reason for the problem. As seen in the above lock file, nasm was missing the appropriate binary package, so it needed to be built. I saw this, that's why at the install command I specified build=missing too. I didn't anticipate that nasm itself also depended on strawberryperl. Once I created the lock file in this manner `conan lock create --reference=openssl/1.1.1f@ISW/MachineAgent --build=openssl --build nasm --build strawberryperl --lockfile=conan.locks\win32\Debug\new.lock --lockfile-out=conan.locks\win32\Debug\openssl.lock -r captain-siemens` I got a dependency tree the same as above, except a node "13" was added that was identical to "11". (If you ask me that is a bug. Why can't nasm's build require point to "11" also?). Anyway, now the install command worked. I'm continuing down the workflow, and share any problems if/when encountered.

**Comment by refactorTractor** [comment] 2021-01-21 15:28
Ok, so I encountered the following:
I update one of our custom dependency recipes, so I export it using `conan export`, then I would like to use this in our main project, so I call `conan lock create --reference=reactor/2.2@ --build reactor --lockfile=conan.locks\base.lock --lockfile-out=conan.locks\reactor_update.lock -u`.
In this case conan immediately goes to the server and downloads the revision that has been uploaded to our artifactory, and replaces the local revision with the old one on the server, when I'd expect conan to favor the local version which is new. Also I'm not sure whether I should be using `conan lock update` to merge back the changed/newly built package?

**Comment by Davidbrcz** [comment] 2022-04-25 15:14
Hello

Is there any update at this issue ? We are currently surveying conan lockfiles and this issue has arisen up in one of our demo use cases: bump a single library to bring a bugfix in a already built application. while tryong to keep all the other dependencies as constant as possible.   

So far, we have been unable to achieve this with lockfiles. We are thinking of writing some code to transform the lockfile into explicit requirements in the conanfile to bypass this issue.  

Is there a better option ? 
Thanks.

**Comment by memsharded** [comment] 2022-04-25 15:17
Hi all.

yes, we have added ``conan lock add`` command to Conan 2.0 (this is almost undoable in 1.X scope). We are also writing a extended proposal for the Tribe about the lockfiles for 2.0, explaining the whole new approach. It is important to highlight that even if this will be possible with this command in 2.0, the underlying principle that the things added to the lockfile should fit inside defined ``requires`` is still valid. Lockfiles cannot allow full overriding of a requires outside of its valid range. But for all the purpose of bumping and trying versions or recipe revisions within the valid declared range, this new way will enable this flow.

**Comment by technic** [comment] 2023-01-19 03:52
Usually package manager has update command which accepts package name as an argument. This command leaves the lock file mostly untouched, and only the given package is updated to the latest version satisfying version ranges or semver requirements. If newer version of this package has new upstream dependencies then they are also added or updated.

Is something like this possible in conan2?
The workaround for conan1 I see the following:

- remove all conan packages from the local cache
- install the old lockfile. So, global state cache which might have been altered by other actions while working on different packages or projects is brought back in sync with the current lockfile.
- export or download the new package you want to use.
- recreate the lockfile.

Is there a better way?

**Comment by memsharded** [comment] 2023-01-19 11:09
Hi @technic 

I think it is possible with the new lockfiles yes.
You can have an existing lockfile for a big dependency graph, and you want to try to upgrade some dependency in the middle of the graph. You can still do that, and update the lockfile with the new version. For example:
```bash
conan install --requires=mypkg/[>1 <2] --lockfile=conan.lock --lockfile-out=conan.lock
```
This will resolve the ``mypkg`` to the latest in the range, keeping all of its dependencies existing in the lockfile locked (or failing if for some reason the latest ``mypkg`` version added some new dependencies not in the lockfile, unless you pass ``--lockfile-partial`` to allow these new deps to be added to the lockfile), and finally updating ``conan.lock`` with the new version.

Now the lockfile will contain 2 versions the new one and the previous one. The lockfile can be used for the dependencies of ``mypkg`` too, if the new version fits in their range, it will be resolved to it, otherwise the lockfile will still work locking the previous versions. With this mechanism it is possible to evaluate if a version bump really affects the consumers or it is discarded by the version ranges of the consumers. 

Typically this process happens when the new version of the package is created, the updated lockfiles are computed for it, so they can be used to validate if this version integrates cleanly in the downstream consumers, it fails to integrate or it is not used and discarded by version ranges of the consumers.

**Comment by technic** [comment] 2023-01-19 16:05
Hi, thanks for the answer!

Great, this is exactly the scenario I had in mind. This is also related to the discussion about having version ranges we had in some other thread https://github.com/conan-io/conan/issues/12729. In order to do what you explained above, i.e. to try whether updating somelib inside big dependency graph of someapp will work, do I need to have version ranges everywhere? And there was also a question about adopting things from cci, where no version ranges are present, what to do in this case?

There is a similar scenario, which is described here (still conan v1):
https://docs.conan.io/en/1.57/versioning/lockfiles/evolving.html#evolving-lockfiles
In this case the app.lock file containing libb/1.0 in the dependency graph is used for enforcing dependencies when building libb/1.1. This seems to work also only when libb is using version ranges.

I can also imagine an alternative solution where I bump versions using regular expressions to modify conanfile.py.  In the second case I can think of a script to collect versions and options from the lockfile and put it as `--require-override` and `-o` arguments for the `conan create` command.

In the end, what I want to see, is weather I can have somewhat semi-automated propagation of upstream dependencies to downstream consumers. So when the upstream is updated and passes self tests we try to propagate it down the graph for our app1, app2, etc products. While pipelines are green we do automated check-ins, if they are red we open a ticket and responsible team should adjust to the updates. Do you think it is a good idea to do such thing?

**Comment by memsharded** [comment] 2023-01-19 16:34
> of someapp will work, do I need to have version ranges everywhere?

To automatically be able to upgrade to some changes in the dependencies, without having to modify your own ``requires = `` it is necessary to either use version ranges, or use automatic "recipe revisions". It is likely that revisions provide a good way for CI, as it is implicit, it doesn't produce conflicts (2 different developers doing a PR to the same package with same version bump). 

All the CI process is almost identical in both cases (version ranges and revisions), and the same concepts apply.
This is probably worth having a look: https://github.com/conan-io/conan/blob/develop2/conans/test/integration/lockfile/test_ci.py. These are the tests we use to validate such a CI approach in which a dependency in the middle of a graph is modified, simulating several scenarios (multiple configurations, paralellizing builds, etc). We will properly convert it into examples and docs, but it might take some time, in the meantime, those tests could be a good info.

> I can also imagine an alternative solution where I bump versions using regular expressions to modify conanfile.py. In the second case I can think of a script to collect versions and options from the lockfile and put it as --require-override and -o arguments for the conan create command.

This is "manual lockfiles". Versions are locked because they are explicitly pinned in the recipes, and evolution is done via changes in recipes (via regex or whatever) instead of changes in lockfiles. The main issue with this approach is that the explicit changes in recipes induce a revision change in such recipes, forcing a re-build of all its binaries, even if the changes in the upstream dependencies didn't necessarily require it.

> In the end, what I want to see, is weather I can have somewhat semi-automated propagation of upstream dependencies to downstream consumers. So when the upstream is updated and passes self tests we try to propagate it down the graph for our app1, app2, etc products. While pipelines are green we do automated check-ins, if they are red we open a ticket and responsible team should adjust to the updates.

Absolutely. This is what we call the "package pipeline" and the "products pipeline". A "package pipeline" builds just one package in isolation, checks the local changes. A "products pipeline" checks if such a new package version/revision affects somehow to the products we are maintaining, if they need rebuilds or not to integrate those changes, and if they break or not due to those changes. If the pipeline is red there are two possibilities:
- The package changes require a major version bump, so it goes outside of the valid version ranges of the consumers, so nothing breaks. Then consumers will need to change explicitly their ``requires=``, then fix their code
- We wait until we do some other fixes to the source code to the consumers packages so they get ready to absorb the new package changes without breaking.

**Comment by technic** [comment] 2023-01-19 19:18
Thanks for this nice and detailed answer. ~I didn't get the part about automatic recipe revisions, what are they? But I maybe can find it out after examine your test_ci file.~

Upd: Ok, with the revisions we just edit recipes but don't bump versions. I think it will be hard to understand from the logs, from conan search results and so on what version we are actually using. For packages iterating fast some incremental counter based on git-describe in the "pre release" semver part looks more transparent.

Is there any chance to setup something similar with conan1?If not then I think waiting until conan2 is out and experimenting a bit with beta can be a good strategy.

**Comment by memsharded** [comment] 2023-01-20 11:06
> Upd: Ok, with the revisions we just edit recipes but don't bump versions. I think it will be hard to understand from the logs, from conan search results and so on what version we are actually using. For packages iterating fast some incremental counter based on git-describe in the "pre release" semver part looks more transparent.

Yes, exactly that is the purpose, to be able to do incremental changes, quickly, for development and iteration without bumping versions.

> Is there any chance to setup something similar with conan1?If not then I think waiting until conan2 is out and experimenting a bit with beta can be a good strategy.

In conan 1 it migth be challenging, there are lockfiles but some of the operations above are at the very least tricky, and rough edges are expected. In any case 2.0 is finally due next month, so maybe worth waiting.

**Comment by technic** [comment] 2023-01-24 11:20
So, then there is one open question remained from the discussion above. It is related to the cci recipes. As wrote in another issue we have edges in the dependency graph like this:

```
patched cci A <- cci B <- company C <- app
```

In the cci conan recipes does not have version ranges. So if I use recipe B from cci without modifications it will likely have dependency to kind of arbitrary version of A. As I understand it will often be the latest version of A at the moment the recipe B was edited. The complication comes because we use our own patched version of library A. Currently we have it as an override inside the conanfile of the app, i.e. `A/1.0` put to the requires of app, which forces B to use version 1.0 of library A. This works even when the recipe B requires A/1.1. However, when I use the lock file of the app to build recipe B or recipe C the override does not happen and the version of A/1.1 is used. We didn't yet prepared a patch for 1.1, so it fails to find it. I tried it with conan1, but based on your explanation the same behavior will be in conan2. One way to make it work, as you explained above, is to use version ranges for recipe B.

I think the strategy in cci is what you have called "manual lockfiles". Then I see to ways: 1) we follow the "manual lockfiles" approach and downgrade version of A in the recipes to `A/1.0` in our fork. 2) We edit recipes in our fork to use version ranges. 
What do you think?

In addition, I don't want to use version ranges just to be able to make overrides easy. This is more concern for company packages, than for open source libraries. Having version ranges puts additional responsibilities for developers that they follow semver, but for company packages the goal is often to evolve fast. So when we bump version of C from 1.1.0 to 1.1.1 we can run a pipeline for all consumers D to check that they still work with updated version and no minor version bump should have been done. Otherwise (as you explained) the C version should be upgraded to 1.2.0 instead. On another hand, when I make changes in D I don't want to care weather it still works with older versions of C, so I need to bump version range for C in the conanfile of D... Does not look much different from "manual lockfiles".

**Comment by memsharded** [comment] 2023-01-24 13:45
> In the cci conan recipes does not have version ranges. So if I use recipe B from cci without modifications it will likely have dependency to kind of arbitrary version of A. As I understand it will often be the latest version of A at the moment the recipe B was edited. The complication comes because we use our own patched version of library A. 

This is exactly the purpose of revisions. When you patch recipe A, even if you don't bump the version, it will still get a new automatic recipe revision, different to the previous one. Recipe revisions can also be explicitly used in dependents, like ``requires = "pkga/version#revision2"``, and more importantly, it resolves to the latest revision by default (kind of like version ranges, but restricted to the pinned version), and it can also be fully reproducible with lockfiles.

Did you have revisions in mind for this?

**Comment by technic** [comment] 2023-01-24 16:44
Revisions don't help in this case. I want to depend on version 1.0 + patch, but the recipe depends already on 1.1, and I don't have a patch for 1.1 yet, so it is not in my conan repository. The recipe B expects A/1.1 to be in the conan repository because it is already in the cci. I think I have no choice but to change recipe B in my fork.

**Comment by memsharded** [comment] 2023-01-24 23:17
> Revisions don't help in this case. I want to depend on version 1.0 + patch, but the recipe depends already on 1.1, and I don't have a patch for 1.1 yet, so it is not in my conan repository. The recipe B expects A/1.1 to be in the conan repository because it is already in the cci. I think I have no choice but to change recipe B in my fork.

Ok, yes, I thought that the patches, versions, etc were moving forward, not lagging behind the versions in C3i fork.
Yes, it is right, you need to modify the dependants on your fork to point to the one that you want.
An important note: I think that once some packages for ConanCenter are being forked and built, it is strongly recommended to build the whole chain from the fork, and not mix locally built binaries for some dependencies and reuse other binaries for other dependencies, specially if they alternate in the chain. Once a dependency is built locally, all of its dependents should also be built locally from the fork, and not reused from ConanCenter.

**Comment by memsharded** [comment] 2024-11-25 23:09
Closing as responded back then. Please create new tickets against latest Conan 2.X if necessary, thanks for your feedback.

**Closed as completed by memsharded** 2024-11-25 23:09 UTC
Labels: stage: triaging
