### ISSUE TITLE
[bug] Conan install fails after updating to 1.35.0

### ISSUE THREAD

**Issue by SpiderCh** [conan-io/conan#8741] opened 2021-03-31 10:05 UTC
### Environment Details (include every applicable attribute)
  * OS: Windows 7 SP1, MacOS 11.2.3
  * Compiler: MSVC 19.28.29337.0, clang 5.0, clang 11.0
  * Conan: 1.35.0
  * Python version: 3.8.2, 3.9

### Steps to reproduce (Include if Applicable)
Install conan 1.35.0. Try to call conan install.

### Logs (Executed commands with output) (Include/Attach if Applicable)

$ conan install path_to_conanfile -if install_path -pr your_profile
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=clang
compiler.libcxx=libc++
compiler.version=5.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

Traceback (most recent call last):
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/command.py", line 2164, in run
    method(args[0][1:])
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/command.py", line 500, in install
    info = self._conan.install(path=args.path_or_reference,
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/conan_api.py", line 598, in install
    deps_install(app=self.app,
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/manager.py", line 57, in deps_install
    deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/graph/graph_manager.py", line 116, in load_graph
    root_node = self._load_root_node(reference, create_reference, profile_host, graph_lock,
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/graph/graph_manager.py", line 158, in _load_root_node
    root_node = self._load_root_consumer(path, graph_lock, profile_host, root_ref)
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/graph/graph_manager.py", line 185, in _load_root_consumer
    conanfile = self._loader.load_consumer(path, profile,
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/loader.py", line 203, in load_consumer
    conanfile = self.load_named(conanfile_path, name, version, user, channel,
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/loader.py", line 128, in load_named
    conanfile, _ = self.load_basic_module(conanfile_path, lock_python_requires, user, channel)
  File "/usr/local/Cellar/conan/1.35.0/libexec/lib/python3.9/site-packages/conans/client/loader.py", line 88, in load_basic_module
    result = conanfile(self._output, self._runner, display, user, channel, self._requester)
TypeError: __init__() takes 6 positional arguments but 7 were given

**Comment by czoido** [comment] 2021-03-31 10:37
Hi @SpiderCh,

Thanks a lot for reporting.

A couple of questions:
- Is that possible that you upgraded conan while other conan process was running?
- Could this be related to old `*.pyc` files for conan remaining? Could you try deleting those files and running again or maybe running in a new virtual environment to check if this happens?

**Comment by SpiderCh** [comment] 2021-03-31 11:11
Hello @czoido 

> Is that possible that you upgraded conan while other conan process was running?

No, there were definitely no conan process running when update happend.

>Could this be related to old *.pyc files for conan remaining? Could you try deleting those files and running again or maybe running in a new virtual environment to check if this happens?

I removed all conan folders and data from both machines(mac and win) and made clean install but problem still there.

**Comment by SpiderCh** [comment] 2021-03-31 11:22
Well sorry for inconvenience, but i found problem. We are using conanfile.py files and we actually receive six input parameters.

`def __init__(self, output, runner, display, user, channel)`

Looks like i miss this change in release changelog.

**Comment by ostjean** [comment] 2021-03-31 14:26
We are having the same issue. We make use of the constructor, which had those 6 parameters. At first glance, I can't see anything in the 1.35 changelog that clearly indicates that the conanfile constructor changed.

This is quite a problem because this breaks absolutely ALL published packages that we have, and we can't simply change the conanfile and call it a day because that will affect only new packages to publish, it won't change the ones that are already published. There's no way we can manually edit about a 100 versions to update the published conanfile. This completely breaks backward compatibility and forces us to block conan to the previous version.

**Comment by czoido** [comment] 2021-03-31 15:14
Hi @ostjean,
I'm very sorry to hear that, this can't be considered a Conan bug. The constructor of the conanfile should not be called directly

**Comment by memsharded** [comment] 2021-03-31 15:30
I am submitting this for 1.35.1 as an exception, this shouldn't be taken as a regression or a bug:

- The constructor ``__init__()`` of conanfile is not documented, so changes in it cannot violate the compatibility and the not breaking promise. If we cannot do changes to internal implementation details then we would need to stop Conan development completely. Please re-read from https://docs.conan.io/en/latest/introduction.html#stable:

 > Only documented features are considered part of the public interface of Conan. Private implementation details, and everything not included in the documentation is subject to change.

- As a recommendation to be more future proof in Python APIs (this is not a recommendation to keep using the ``ConanFile.__init__()`` method), please be aware that you can define your ``__init__(self, ...., *args, **kwargs)`` arguments (and make sure to forward them to ``super()``) to account for changes in method arguments.

Please fix that asap, even if this PR is merged and released in 1.35.1, there is no guarantee that future Conan versions will not revert this, as in fact the change in #8746 is both ugly and dangerous for us, just assigning it outside the constructor, so this will need to be fixed.

**Comment by ostjean** [comment] 2021-03-31 15:57
I see... we started our development when conan was at like 1.17 and there was pretty much nothing else than the `__init__` that could allow us to do our common configuration on both the producer and consumer side (we use one conanfile template for all our projects).

Is there anything that is common now on both side that runs at the very beginning, other than the constructor, on install, export and package? Is there something we can do on our side that wouldn't force us to go through all published packages (and so tons of git commits) to update them, or is there an easy way that I'm not seeing to update published conanfiles?

**Comment by memsharded** [comment] 2021-03-31 16:24
Hi @ostjean 

It would be very useful to understand your use case for overriding the ``__init__()`` constructor on the conanfile, and also a bit more detail about that conanfile template that you are using. How are you actually using it as a base? It seems not a ``python_requires``, is maybe some Python package installed at the pip-system level? Because now there is the ``init()`` method (check https://docs.conan.io/en/latest/reference/conanfile/methods.html#init), that can be used to define some logic, specifically for the case of inheriting from a class in ``python_requires``, not sure if this method could help.

**Comment by ostjean** [comment] 2021-03-31 18:53
We don't do anything too fancy with the conanfile.py. However it is unconventional and we've customized a lot of things to fit our needs, so we know that if we do something too weird, it's our problem. We mainly heavily modified the settings and the profiles, the conanfile.py is not too weird.

We have toolchains for different embedded platforms in docker images. We have a base docker image that all toolchains use that installs conan and installs the configuration. We put the conanfile.py in `$CONAN_USER_HOME/.conan`, and from cmake or other build systems we call `conan install` at configure and `conan export-pkg` at post build. We always point to the single common conanfile.py in the .conan. We don't use options or compilers or anything because it's all set in the profile, and there is one profile per toolchain. Of course, that means that conan doesn't get updated until the next time we modify the toolchains. We've noticed this because some devs have updated their local conan (we can replicate the toolchain setup locally) and problems started happening.

Because we didn't want devs to have to code python, we use conanfile.txt in the projects to define the dependencies (that is all we need). However, when installing dependencies, we noticed that it was pulling only the direct dependencies in the conanfile.txt and not the indirect dependencies. The way we managed to solve that is by exporting the conanfile.txt (we're adding the export in the constructor) and then in the `requirements` method we read and parse the conanfile.txt. That's a bit unorthodox, but it works for us. I've seen the new export method, but that didn't exist back then.

The other, maybe weirder thing we do is that we have different project types (can't be more precise unfortunately) that package different sets of files, and some are platform agnostic requiring us to set the `settings` attribute to `None`. So in the constructor, we detect the project type (based on the content of the project directory), and we set an attribute to it. We also set `settings` to `None` based on the type. Then, in `package` we take the proper files based on the attribute value. Of course, because we can't access the original project when doing `conan install`, we export a file with the project type in it for that purpose.

That's about it. We need the project type logic because we use one conanfile.py for everything, we need to export some files to have the necessary info when installing dependencies. And that's because we use one conanfile.py (and also one cmake / other buildsystem script) to fit all our needs.

We have a private artifactory server, because we strictly cannot use any third-party libraries as part of our product (other than system libraries already included in the OS of course) because of safety requirements and such, so we don't use any public repositories. Also, we have requirements on traceability and access to old versions for a long time, so we need to be careful to not make the older versions unusable.

In this scenario, if we were to fix for new packages only, we'd be unable to mix the latest packages with any of the already published packages; or if we do update every package recipe to use the newer functions and we end up having to use an older toolchain (for whatever reason, debugging for example) it would fail because older conan didn't have those functions. Of course, if the simplest solution would be for us to replace `>=` with `==` in our requirements.txt, it could be a valid solution considering we are not using new conan features because of that compatibility concern...

**Comment by memsharded** [comment] 2021-04-05 12:43
https://github.com/conan-io/conan/pull/8746 has been merged and will be in 1.35.1, but please be aware this is a temporary workaround and will be reverted in future release.

> We put the conanfile.py in $CONAN_USER_HOME/.conan, and from cmake or other build systems we call conan install at configure and conan export-pkg at post build. We always point to the single common conanfile.py in the .conan. We don't use options or compilers or anything because it's all set in the profile, and there is one profile per toolchain. Of course, that means that conan doesn't get updated until the next time we modify the toolchains. We've noticed this because some devs have updated their local conan (we can replicate the toolchain setup locally) and problems started happening.

This sounds also like problematic approach, and I would strongly encourage to have a look to ``python_requires`` and start adopting them. That will help with code reuse, and control of when it is necessary to rebuild as versions evolve, etc.

**Closed as completed by memsharded** 2021-04-05 12:43 UTC
Labels: type: engineering, stage: triaging, complex: low
