### ISSUE TITLE
[bug] Cannot use boost with conan 2.0.0-beta2

### ISSUE THREAD

**Issue by LukeSkyw** [conan-io/conan#11973] opened 2022-08-28 09:34 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 22.04.1 LTS
  * Compiler+version: gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  * Conan version: 2.0.0-beta2
  * Python version: 3.10.4

### Steps to reproduce (Include if Applicable)
In a you conanfile.py:
```python
from conan import ConanFile

class Pkg(ConanFile):
    requires = "boost/1.79.0"
```
Then, in your cli:
```bash
conan build .
```

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
~/test# conan build .

-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=11
os=Linux


-------- Computing dependency graph --------
Graph root
    conanfile.py: /root/test/conanfile.py
Graph error
    Package 'boost/1.79.0' not resolved: boost/1.79.0: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/e6104104a89815c3/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/e6104104a89815c3/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/e6104104a89815c3/e/conanfile.py", line 7, in <module>
    from conans import tools
ImportError: cannot import name 'tools' from 'conans' (/usr/local/lib/python3.10/dist-packages/conans/__init__.py)


-------- Computing necessary packages --------
ERROR: Package 'boost/1.79.0' not resolved: boost/1.79.0: Cannot load recipe.
Error loading conanfile at '/root/.conan2/p/e6104104a89815c3/e/conanfile.py': Unable to load conanfile in /root/.conan2/p/e6104104a89815c3/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.conan2/p/e6104104a89815c3/e/conanfile.py", line 7, in <module>
    from conans import tools
ImportError: cannot import name 'tools' from 'conans' (/usr/local/lib/python3.10/dist-packages/conans/__init__.py)
```

**Comment by memsharded** [comment] 2022-08-28 21:08
Hi @LukeSkyw 

This is expected, and not a bug in Conan 2.0-beta
Recipes in ConanCenter have not been upgraded yet to 2.0-beta, this is an ongoing effort. If you read the 2.0 docs, like in https://docs.conan.io/en/2.0/tutorial/consuming_packages/build_simple_cmake_project.html

> In this example, we will retrieve the CMake Conan package from a Conan repository with packages compatible with Conan 2.0. To run this example successfully you should add this remote to your Conan configuration (if did not already do it) doing: conan remote add conanv2 https://conanv2beta.jfrog.io/artifactory/api/conan/conan --index 0

(it is likely that boost is still not there in that experimental repository)

**Comment by LukeSkyw** [comment] 2022-08-29 06:16
@memsharded thanks for the quick response. Indeed I figured it was a little early. May I suggest adding a mention in https://docs.conan.io/en/latest/conan_v2.html about that problem? This is the first documentation I found when looking for Conan 2 help.

Is there an equivalent "conan center" for v2? This documentation https://docs.conan.io/en/2.0/introduction.html points to the current center which contains the incompatible packages.

Finally, is there a way to participate in this effort? It should not be that hard to convert boost recipe to 2.0 syntax, so maybe the community can help.

**Comment by AbrilRBS** [comment] 2023-03-16 00:40
Hi, thanks for your input, sorry we didn't get back to you sooner, lots of things needed to be done for 2.0. Hopefully you found your way to the [ConanCenter Index](https://github.com/conan-io/conan-center-index) repository where all the recipes live and where the community is welcomed to contribute. With Conan 2 out now, [the PR adding compatibility for it](https://github.com/conan-io/conan-center-index/pull/16222) has been progressing steadily and we hope to have it soon :tm:. I'll close this issue and track the progress in the CCI PR itself :)

**Closed as not planned by AbrilRBS** 2023-03-16 00:40 UTC
Labels: type: question
