### ISSUE TITLE
What causes error message: ERROR: <pkg-name> 'settings.arch' value not defined?

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3367] opened 2018-08-17 16:16 UTC
Conan 1.6.1

Hi,

We have a structure like the following (simplified):

PkgA requires PkgB
PkgB requires PkgC

PkgA has no settings attribute
PkgB has _settings = "os", "compiler", "build_type", "arch"_
PkgC has no settings attribute

if we run (for PkgA):
```
conan install PkgA-recipe -if <build dir>
conan build PkgA-recipe -bf <build dir> -sf <src folder>
conan export-pkg PkgA-recipe dev/test -bf <build dir>
```

we get the error _ERROR: PkgB 'settings.arch' value not defined_. The output from conan suggests that the _conan export-pkg_ command successfully exporting the package, but failed before the package() method is called.

if we run (for PkgA):
`conan create PkgA-recipe dev/test`

it works fine.

To stop the error for the local build we added _settings = "os", "compiler", "build_type", "arch"_ to PkgA but we don't understand why this was required.

Any guidance on what we may have done wrong?

**Comment by memsharded** [comment] 2018-08-17 16:25
It might be a bug, thanks for reporting, we are going to investigate.

**Comment by memsharded** [comment] 2018-08-17 16:33
Reproduced, certainly unexpected behavior, labeling as bug and trying to fix it for 1.7

**Comment by memsharded** [comment] 2018-08-27 13:34
Hi @keithrob91 

I have been working on this, but is more complex than expected. Will continue working for 1.8, but don't have time in conan 1.7. 

In the meantime, please use one of the following workarounds:
- Add the ``settings`` to the header only recipe, as you did. Remember to add ``self.info.header_only()`` to the ``package_id()`` of your header only recipe conanfile.py
- Use a normal ``conan create`` to package the header only. It will be very fast too, and the recipe will be extremely simple. ``conan export-pkg`` actually only makes full sense if you are creating binaries outside of the conan-cache, but for header only it is not a thing.

**Comment by keithrob91** [comment] 2018-08-29 10:37
OK, thank you for update. We've gone for the first option

**Comment by memsharded** [comment] 2018-10-17 08:59
Hi @keithrob91 

We are proposing the following solution in https://github.com/conan-io/conan/pull/3768

The information stored in the ``conan install`` in *conaninfo.txt* is not enough for all cases. So we are allowing to specify the profile also in the ``conan export-pkg``. It will be released in conan 1.9. With that fix, you will be able to remove the hacks from your conanfile.py recipe.

We will also try to propose a new mechanism, so the information captured at ``conan install`` is more complete, but that would be breaking now, so it is planned for conan 2.0 https://github.com/conan-io/conan/issues/3769

**Comment by keithrob91** [comment] 2018-10-17 11:52
Isn't the -pr argument already accepted for `conan export-pkg` (1.8.2)? I'm a little confused!

**Comment by danimtb** [comment] 2018-10-17 12:18
Not yet. It is a change big enough to be in next 1.9 release, not in the 1.8.2 patch.

You can see the PR with the changes https://github.com/conan-io/conan/pull/3768 for 1.9 milestone

**Comment by keithrob91** [comment] 2018-10-17 13:28
`conan help export-pkg` reports -pr as an option though (in 1.8.2)?

**Comment by keithrob91** [comment] 2018-10-18 16:31
Oh I see.  My only comment then is that the documentation did not make that clear.

Thank you for the information and updating me on the fix.

**Closed** 2018-10-19 08:52 UTC
Labels: bug, in review

**Comment by ManuelMeraz** [comment] 2019-04-19 23:42
> `--profile` options is used currently only when there is no _conaninfo.txt_ file present in the installation directory. For example, if you run the local commands and then try to `conan export-pkg`, it will use the info in the conaninfo.txt.
> 
> The PR mentioned before changes that behavior to **always** use the profile or settings if specified.

This should be added to the documentation. I read through the profile section and it's not mentioned. 
I was wondering why I was getting issues with my settings not being set even though I have a conanfile.py in my project.

**Comment by memsharded** [comment] 2019-04-20 23:41
Hi @ManuelMeraz 

Do you mean that the last paragraph of https://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html is not clear enough of this behavior?

This section is however getting a partial re-write in https://github.com/conan-io/docs/pull/1232. Maybe you could please check that PR and see if it is more clear now, or if that PR could be further improved to account for this. Thanks!

**Comment by jgsogo** [comment] 2019-04-23 10:33
Hi @ManuelMeraz, please have a look at the attached PDF file, I've rendered it for you from the PR #1232. Let me know if the text describing the command and/or the note at the end is clear enough or it can be improved somehow, thanks:

[conan_export_pkg.pdf](https://github.com/conan-io/conan/files/3107060/conan_export_pkg.pdf)

![image](https://user-images.githubusercontent.com/1406456/56574500-aacb7780-65c3-11e9-9762-8870263f0922.png)

**Comment by ManuelMeraz** [comment] 2019-04-23 21:03
Sorry for the late response. 

That wasn't exactly my problem, and mostly it was due to my ignorance probably.

My problem was in my project I had a `conanfile.py` that I wanted to use, and I wanted to create "profiles" that had slightly different settings, but it would still use the settings in my conanfile, except the settings changed in my new profile. Such as compiling with a specific version of clang. I wanted to keep them within a hidden `.profles` directory so I could use them with travis.

Example:
``` conan install --install-folder build --build --profile ./my_profile```

In my mind this would:
1. Configure my cmake inside the folder called build
2. Build from source
3. Use the profile settings in `my_profile` and override the settings that are changed in my conanfile

In `my_profile` I would only have something like
```
[settings]
compiler = clang
compiler.version = 6.0
compiler.libcxx = libstdc++11
```

Because I wanted to use `clang` to compile my code, and not `gcc`. 

This was not how this works, what happens is that only the `my_profile` is used, and `conanfile.py` is completely ignored. I would get an error something like:
`settings.arch no set`

Which confused me.

So, to get the behavior I needed, I needed to create my own profiles and put them in `~/.conan/profiles`, which seemed to do the trick. 

It was not so simple to figure out how to compile with clang.

**Comment by jgsogo** [comment] 2019-04-24 09:03
Hi, @ManuelMeraz!

See your issue, do you know you can compose profiles or even pass several of them to the same command? 

Take a look at [Profile includes](https://docs.conan.io/en/latest/reference/profiles.html?highlight=profile#profile-includes), if your profile is defined in the file `my_profile` (in your local folder) it can include a _default_ one:

```ini
include(default)
[settings]
compiler = clang
compiler.version = 6.0
compiler.libcxx = libstdc++11
```

and also at [profile composition](https://docs.conan.io/en/latest/reference/profiles.html#profile-composition), you can pass several profiles to the same command:

```
conan install ....  -pr=default -pr=my_profile
```

**Comment by ManuelMeraz** [comment] 2019-04-25 19:04
Yes! I knew about that, but the way you just showed me in that exampled makes it very clear that it is perfect for my use case. I can do what I was doing, I just need to include the default one and those settings will then be defined. Perfect. That is exactly what I needed :). Thank you.
