### ISSUE TITLE
[bug] openssl1.0.2u broke due to none type in path

### ISSUE THREAD

**Issue by zjufish** [conan-io/conan#11856] opened 2022-08-12 07:33 UTC
build_info.py L147,

ef _filter_paths(self, paths):
146 abs_paths = [os.path.join(self.rootpath, p)
147 if not os.path.isabs(p) else p for p in paths]
148 if self.filter_empty:
149 return [p for p in abs_paths if os.path.isdir(p)]
150 else:
151 return abs_paths

should not the L147 be :
if not os.path.isabs(p) else p for p in paths if p]

we have openssl package broke on this, after i applied the patch it seems to work. for some reason, p is None in one case with openssl/1.0.2u.

the error looks like:
File "/somepath/python3.8/site-packages/conans/model/build_info.py", line 147, in
if not os.path.isabs(p) else p for p in paths]
File "/somepath/rh-python38/root/usr/lib64/python3.8/posixpath.py", line 62, in isabs
s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType

can u confirm if this is bug or sth else?

**Comment by czoido** [comment] 2022-08-12 07:41
Hi @zjufish,

Thanks for reporting, could you please specify which Conan version are you using?
I suspect that may be related with some changes in Conan 1.50, could you check if that happens for Conan<1.50 ?

Thanks a lot.

**Comment by zjufish** [comment] 2022-08-12 07:41
happened with 1.48 as well. same code. build_info.py. tried both 1.48 and 1.51

**Comment by czoido** [comment] 2022-08-12 07:43
Hi @zjufish,

Are you using a custom openssl1.0.2u recipe or the one from Conan Center? Could you provide some output before the fail?

Thanks!

**Comment by zjufish** [comment] 2022-08-12 07:46
im using openssl 1.0.2u from our artifactory. We have jobs to sync all packages from conan.io so in theory they should be the same.  this package is uploaded 2 years ago and nobody touchs it since.  it was working on last week.  the error i put in the bug description is all the error msgs i see. 

i feel conan should check if p is a valid path before using it. however i dont know why NoneType is passed as a path. 

`{"recipe": {"revision": "dc61c2f345531987114db0ea84a75653", "remote": "artifactory-virtual", "properties": {}, "checksums": {"conan_export.tgz": {"md5": "55f40f00bed380363821e39053b40179", "sha1": "ac55a30f323c75720e3275597c008912d6610e66"}, "conanmanifest.txt": {"md5": "dd6f887e75815250a3c67770f2987484", "sha1": "0aee1c7341469084dd8143fbb9afa4efccf2ecef"}, "conanfile.py": {"md5": "3785b8fcdf83aa75905f866765aa3d71", "sha1": "b883ae81a29ce637d154a42051343ae94c924488"}}}, "packages": {"c20edffba53b2d244d9def5d03f335faec22d9d4": {"revision": "1dae7699b4a04afa6cd4d4673879f8d9", "recipe_revision": "8cd1fea41bf2a0f9854257b25461137b", "remote": null, "properties": {}, "checksums": {}}, "bee3131bcf75718bde43aabd94a226862943e634": {"revision": "0e1496437eee6c3a2d78ab53ef6830c3", "recipe_revision": "672d65c5e547fbfbbbd33a17001ba5d0", "remote": null, "properties": {}, "checksums": {}}, "72cfc9cc955a3481dbad38803f5e0433f500a6f0": {"revision": "778a3890206a0a45b3d29f9d4da981bb", "recipe_revision": "672d65c5e547fbfbbbd33a17001ba5d0", "remote": null, "properties": {}, "checksums": {}}, "56d1d9c0fee4b2d5e45d5c7ca9973063e0e231ca": {"revision": "69dd3a5b55bfd9fa7744d8115eb0a6fe", "recipe_revision": "672d65c5e547fbfbbbd33a17001ba5d0", "remote": null, "properties": {}, "checksums": {}}, "c4663d032679809c5e6e0db9250a96cf35c43c5e": {"revision": "bf58a1f0edb1831d63483499878dde0a", "recipe_revision": "dc61c2f345531987114db0ea84a75653", "remote": null, "properties": {}, "checksums": {}}, "7e7f00749763444a06b0844fd91f7990e5cedbaa": {"revision": "08afadf3eda2e20a5fe1578011c64aef", "recipe_revision": "dc61c2f345531987114db0ea84a75653", "remote": null, "properties": {}, "checksums": {}}}}`

**Comment by czoido** [comment] 2022-08-12 08:00
@zjufish,

Is a simple `conan install openssl/1.0.2u@ ` failing? Or the fail happens when you consume openssl from another recipe?
Could you provide the `conanfile` for the consumer of the recipe?

Thanks!

**Comment by zjufish** [comment] 2022-08-12 08:02
conan install openssl/1.0.2u is one of my required dependences and failed in installation. however i didnot see this failure last week and nobody touched this package for 2 years.

**Comment by czoido** [comment] 2022-08-12 08:11
@zjufish,

Does executing this in the command line work?

```
conan install openssl/1.0.2u@
```

Also, do you think you could copy the conanfile.py you are using for consuming so maybe we can reproduce the issue?

**Comment by zjufish** [comment] 2022-08-12 08:17
sorry i cannot share our conanfile.py. conan install openssl/1.0.2u@ complains about missing complier stuff. 
all i know is the line i patched can fix that.  im not exactly sure why it worked last week when nobody touches this package for 2yr. i also tried reinstall conan 1.44/1.48/1.51. all failed on NoneType path. i think whatever it is, conan might want to check if p is a path string.

**Comment by czoido** [comment] 2022-08-12 09:20
Hi @zjufish,

I can't reproduce the exact same issue. I tried to consume the openssl package in different ways but it always has all folders attributes set in the cpp_info and there are no None's that make it fail. I guess it makes sense to check that the paths in the cpp_info are not None when the filter is invoked. I'm adding this for the next release.

Thanks for reporting.

**Comment by zjufish** [comment] 2022-08-12 14:08
thank u. 1.52 right?

**Comment by czoido** [comment] 2022-08-12 14:25
> thank u. 1.52 right?

yes, 1.52

**Comment by zjufish** [comment] 2022-08-12 15:03
awesome. appreciate it.

**Comment by gureedo** [comment] 2022-08-16 13:55
I have the same issue.
I'm using debian 11, python 3.9, conan 1.51.2, openssl/1.0.2u.
OpenSSL is direct dependency of my project.
Command `conan install openssl/1.0.2u@` fails with the same error.

```
openssl/1.0.2u: Generated conaninfo.txt
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/command.py", line 380, in create
    info = self._conan.create(args.path, name=name, version=version, user=user,
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 388, in create
    create(self.app, ref, graph_info, remotes, update, build_modes,
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/cmd/create.py", line 72, in create
    install_build_and_test(app, test_conanfile_path,
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/cmd/test.py", line 35, in install_build_and_test
    deps_install(app=app,
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/manager.py", line 83, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/installer.py", line 317, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/installer.py", line 464, in _build
    self._handle_node_cache(node, keep_build, processed_package_refs, remotes)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/installer.py", line 557, in _handle_node_cache
    pref = self._build_package(node, output, keep_build, remotes)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/installer.py", line 600, in _build_package
    pref = builder.build_package(node, keep_build, self._recorder, remotes)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/installer.py", line 230, in build_package
    prev = self._package(conanfile, pref, package_layout, conanfile_path)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/installer.py", line 171, in _package
    TXTGenerator(conanfile).content)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/generators/text.py", line 240, in content
    deps = DepCppTXT(cpp_info)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/generators/text.py", line 42, in __init__
    super(DepCppTXT, self).__init__(cpp_info)
  File "/home/user/.local/lib/python3.9/site-packages/conans/client/generators/text.py", line 22, in __init__
    for p in cpp_info.res_paths)
  File "/home/user/.local/lib/python3.9/site-packages/conans/model/build_info.py", line 199, in res_paths
    self._res_paths = self._filter_paths(self.resdirs)
  File "/home/user/.local/lib/python3.9/site-packages/conans/model/build_info.py", line 146, in _filter_paths
    abs_paths = [os.path.join(self.rootpath, p)
  File "/home/user/.local/lib/python3.9/site-packages/conans/model/build_info.py", line 147, in <listcomp>
    if not os.path.isabs(p) else p for p in paths]
  File "/usr/lib/python3.9/posixpath.py", line 62, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by czoido** [comment] 2022-08-17 12:37
Finally it looks like the root of the error was a mistake in the Conan recipe. This should fix that: https://github.com/conan-io/conan/pull/11893

**Comment by lasote** [comment] 2022-08-17 13:45
Closed by https://github.com/conan-io/conan/pull/11893

**Closed as completed by lasote** 2022-08-17 13:45 UTC
Labels: priority: medium, complex: low
