### ISSUE TITLE
[feature] Allow scm revision_mode even on dirty repository

### ISSUE THREAD

**Issue by paorho** [conan-io/conan#14715] opened 2023-09-11 17:25 UTC
### What is your suggestion?

Please add an option to export-pkg command and eventually other commands involved to allow scm revision_mode even on dirty repository, like conan v1 does.
In ours CI we have the need to build the same artifacts with both conan v1 and conan v2; the CI process add files and modify template files to add build info. 

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-09-11 17:55
Hi @paorho 

Thanks for your suggestion. 

I think this might be a duplicate of https://github.com/conan-io/conan/issues/14416. Please check it, and if correct, please comment there (and close this one, we can track the other one better). I will increase a bit its priority for some of the next 2.0.X releases, lets see if possible.

**Comment by paorho** [comment] 2023-09-12 08:17
Hi  @memsharded ,

Thanks for the prompt reply.

Same use case, yes: new and modified files into the root folder of the project.
If you think it's better to close this issue and continue the indicated one,
I will do it with pleasure, adding some other info about our CI scenario.

We use Gitlab as source repository and CI manager and Artifactory to store the result.
The CI processes c++, java and shell projects, using a lot of bash and python scripts.
For the c++ projects the conan v1 commands still used:
conan install, conan build, conan export-pkg, conan upload,
implemented in different scripts to perform the prepare, check, build and finalize steps of the CI;
migrate to conan create command it's hard to think.
The CI process collects build info sent by e-mail and inserted into the built artifact, postgresql db and Confluence pages.

In this scenario an option to add to the conan commands is easy to implement into the scripts.

The expected result in Artifactory is, like conan v1 commands do:
https://xyz.artifactory.it/artifactory/webapp/#/artifacts/browse/tree/General/group/subgroup/project/version/branch/fd98bd4e834e7400133f21f44e42c7c2e4d9cf70
where fd98bd4e834e7400133f21f44e42c7c2e4d9cf70 is the project's commit hash pushed to GitLab generating the CI pipeline.

**Comment by memsharded** [comment] 2023-09-13 00:14
Yes, please, lets centralize discussion in https://github.com/conan-io/conan/issues/14416., closing this one, let's follow up there. Thanks!

**Closed as completed by memsharded** 2023-09-13 00:14 UTC
Labels: duplicate, stage: triaging
