### ISSUE TITLE
Conan install with option '--update' results warnings

### ISSUE THREAD

**Issue by sneik555** [conan-io/conan#6468] opened 2020-02-04 14:08 UTC
Hi,

I called `conan install . -p vs2017_static -r nexus --update` and I have warnings like:
`WARNING:files.py       [100]: can't decode.... ` 
Then I see that whole package was downloaded from nexus.
For small packages it's not big issue, but downloading conan_package.tgz for openCV took 6 minutes.

My questions: 

- Is it because I'm using nexus for storing my packages? (Unfortunately, I cannot use Artifactory or anything else :( )
- How exactly `--update` option should work? Which data from server should be downloaded?

Full logs:
[openCVInstallWithUpdate.log](https://github.com/conan-io/conan/files/4153778/openCVInstallWithUpdate.log)

**Comment by memsharded** [comment] 2020-02-04 15:47
Hi @sneik555 

It seems that the ``conan_sources.tgz`` might be corrupted or something. 
Please tell the OS, Conan version, Python version that you are using in your client.

With that information is difficult to reproduce. I would suggest the following:
- Try running a local server, just for debugging. It could be the integrated ``conan_server`` (it is already installed with the client), or Artifactory CE, which is free too.
- Upload the same package that is showing such warnings, clean your local cache (``conan remove * -f``) and install again from that remote.

Also, make sure the commands you are using. In the trace, it seems that it is trying to get the ``conan_sources.tgz`` which is unnecessary for normal installation of binaries, that do not require to be built from sources.

Let us know how it goes. It might be worth reporting to the Nexus Conan plugin, so they can have a look. Also about the download that took 6 minutes, it shouldn't be the case. You can try installing some packages like boost from conan.io/center, to see if the long times you are experiencing are due to the server side or to the client side.

**Comment by sneik555** [comment] 2020-02-04 16:07
Hi,
OS - Windows, build for Visual Studio 2017, toolset 14.16
Conan version 1.21.1
Python 3.8.1

I will try to reproduce it as you wrote and give some feedback as soon as possible.

**Comment by sneik555** [comment] 2020-02-06 11:58
Hi **@memsharded** 

I checked `conan install --update` on local naxus and local artifactory.
Results:
[nexus_local.log](https://github.com/conan-io/conan/files/4164881/nexus_local.log)
[artifactory_local.log](https://github.com/conan-io/conan/files/4164883/artifactory_local.log)
I see that something is not ok with nexus plugin for conan. On artifactory only conanmanifest's are downloaded - on nexus nothing changed.

I already report a [bug](https://github.com/sonatype-nexus-community/nexus-repository-conan/issues/94).

**Comment by memsharded** [comment] 2024-01-24 00:35
This was a nexus bug, closing as it is outside of our scope to fix

**Closed by memsharded** 2024-01-24 00:35 UTC
Labels: stage: triaging
