### ISSUE TITLE
[SCM][Feature] Add scm.revision as "setting"

### ISSUE THREAD

**Issue by mietzen** [conan-io/conan#5367] opened 2019-06-18 06:46 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

This is loosely related to #3052

We have conan recipes inside the repo and are using the scm-feature. The development recipes are always pointing to `"revision": "auto"`. Our "latest" dev recipe has the version `master` and all our feature branch dev recipes have also the version `master`. To handle the different branches i added a option: https://github.com/conan-io/conan/issues/5234#issuecomment-502961513

So far I'm happy with this workflow. But now I would like to build new branches even if they are not uploaded to the conan-repository or are checked out locally, by just doing something like:

```
conan install some-pkg/master@user/testing -s scm.revision="feature/new-stuff" --build=missing
```

**Use-Case:** 
A colleague is working on a dependency of my pkg and I just want to test it locally without building it on our CI-Sever and uploading it to the conan-repository.

**What is working already:**
Checkout my colleagues branch and execute `conan create .` 

But I think `conan install`  would by the more elegant way.

**Comment by lasote** [comment] 2019-06-18 11:31
I like better to do the checkout + `conan create`, that is simple and explicit. But if you are using an option to model the branch, and the recipe is uploaded to a repository couldn't you do:

`conan install some-pkg/master@user/testing -o scm_branch="feature/new-stuff" --build=missing`

By the way, have you considered using the [package revisions feature](https://docs.conan.io/en/latest/mastering/revisions.html)? Setting the [revision mode](https://docs.conan.io/en/latest/reference/conanfile/attributes.html#revision-mode-attribute) to `scm` you will get "automatic" versions of a package by using the `commit` and you could avoid using the "master" for the version and keep a real versioning system.

To get the latest revision of a recipe, you don't have to do anything, just `conan install some-pkg/1.23@user/testing --update` and it will retrieve the latest revision.

We are currently working on lock files to "freeze" the dependencies of a project, so, having all the revisions stored, you can reproduce any build, but still not released.

I don't know exactly your current flow (and CI jobs), but at first sight, it feels that should be a better way for the feature branches rather than using an option. Why do you need to upload these feature branches packages to the repository?, I assume that is the reason you introduced an option. 

It would be great if you could describe how are you implementing your CI and dev flow. We are also currently trying to implement something and start suggesting some best practices etc. For example: 
- What happens in the CI when a colleague opens a Pull Request.
- What happens when merged,  
- How you manage to promote to "master or release" the development packages of your project etc
- Any other insight.

Thanks so much for your feedback in advance!

**Comment by mietzen** [comment] 2019-06-19 06:51
Some best practices would be great, I'm working in a small company < 30 Developers and am responsible for CI since 4 month. Before i started, there were huge misunderstandings about what conan is for and how to use it. It was used as some kind of deploy tool rather than as package manager. And was bloated with lots of "helper classes", which mostly got obsolete with newer conan versions. Also all recipes are stored in a central repo, with recipes for every version and the master branch.
So for the last 4 month I'm refactoring conan recipes, trying to keep them as simple as possible.
I'm grateful for every input on howto make them even simpler.

> By the way, have you considered using the package revisions feature? Setting the revision mode to scm you will get "automatic" versions of a package by using the commit and you could avoid using the "master" for the version and keep a real versioning system.

I've seen this feature, today some of these "helper classes" are still blocking me from updating conan to >1.12. But hopefully in the next month I'm able to update. And yes this branch option would be obsolete then. But I think it still would be nice to not only see the commit hash, as mentioned in #5234 

> I don't know exactly your current flow (and CI jobs), but at first sight, it feels that should be a better way for the feature branches rather than using an option. Why do you need to upload these feature branches packages to the repository?, I assume that is the reason you introduced an option.

We often have triangular dependencies:

``` 
   A
 ⭧   ⭦
B  ⭢  C
``` 

Often with three different persons working on A, B, C. Therefore we have an internal conan repo where all dev-pkg of the different branches get pushed to. So if someone working in project B has some fixes/changes which are not ready for release, but wants the persons in project A and C to try them out he builds his branch and pushes it to the internal repo. 
Writing this I think the better way would be to make small changes and small release. 

> * What happens in the CI when a colleague opens a Pull Request.

Today nothing automated, some one is picked for a code review.

> * What happens when merged,

On merges to the master branch, the branch is build on our jenkins server

> * How you manage to promote to "master or release" the development packages of your project etc

To get a stable release, we'll create a tag, copy the master recipe and point it to the taged commit. Then it will be build in testing channel go through functional and GUI tests. If passed it will get it channel changed to stable and will be released.

> * Any other insight.

Where i want to go:

* clean conan files without any "helper classes"
* use conan mainly to control cmake (all our projects are c++), I will look into cmake_find_package later this year
* conan build recipes in source code repo root, conan test recipes in test folders

**Comment by lasote** [comment] 2019-06-19 15:39
Thanks so much for the info!

> To get a stable release, we'll create a tag, copy the master recipe and point it to the taged commit. Then it will be build in testing channel go through functional and GUI tests. If passed it will get it channel changed to stable and will be released.

In which point do you change the dependencies to depend on "master" just before changing from testing to master you change the requirements to master too?

**Comment by memsharded** [comment] 2023-03-15 22:58
I think this issue is outdated, cause ``scm`` was deprecated in 1.X and removed in 2.0, so closing, please open new tickets if necessary.

**Closed by memsharded** 2023-03-15 22:58 UTC
Labels: stage: triaging
