### ISSUE TITLE
[bug] conan copy fails

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#7736] opened 2020-09-22 10:36 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: any
  * Compiler+version: any
  * Conan version: 1.29.0
  * Python version: any

### Steps to reproduce (Include if Applicable)
conan copy qt/5.15.1@bincrafters/stable qt/5.15.1@companyname+core+dependency/testing

### Logs (Executed commands with output) (Include/Attach if Applicable)
$ conan copy qt/5.15.1@bincrafters/stable qt/5.15.1@companyname+core+dependency/testing
ERROR: The reference has too many '@'

I want to store some built configuration in gitlab registry. To push there, I need to override username and channel. conan copy command fails for me

**Comment by uilianries** [comment] 2020-09-22 18:25
Hello @AndreyMlashkin that's not a bug, but the expected behavior. I see the UX doesn't help, but if read the [documentation](https://docs.conan.io/en/latest/reference/commands/misc/copy.html) or running `conan copy --help` you will see that you shouldn't repeat the package name and version. Thus, you should run:

     conan copy qt/5.15.1@bincrafters/stable companyname+core+dependency/testing

**Comment by memsharded** [comment] 2020-09-22 22:20
Also please note that ``conan copy`` might be deprecated in Conan 2.0, as user/channel based promotions (copy) has some undesired side effects and breaks package immutability, so user/channel will be immutable in the future. It is likely that the only way to change packages from user/channel will be to do a new ``conan create``. 

The main reason is because recipes can be conditional to user/channel. Changing them without re-evaluation the recipe can leave it in a broken, inconsistent state. cc/ @steve-abrams

**Comment by memsharded** [comment] 2020-09-23 20:01
The UX has been fixed in https://github.com/conan-io/conan/pull/7741, and will be released in next Conan 1.30, so this can be closed.

**Closed as completed by memsharded** 2020-09-23 20:01 UTC
Labels: component: ux
