### ISSUE TITLE
[RFC] command for directly executing a command in a virtualenv

### ISSUE THREAD

**Issue by niosHD** [conan-io/conan#2461] opened 2018-02-12 17:53 UTC
I recently started to provide our cross compilation toolchain via conan and it works well so far. However, one feature I am really missing is the possibility to get really fast into a certain environment. What I basically want is something like an `env` command  where I can provide a profile and/or some references and I end up in a shell with the correct environment. (The name `env` is of course just a strawman.)

Usage would then look something like
* `conan env -pr custom-toolchain` or
* `conan env mingw_installer/1.0@conan/stable cmake_installer/3.10.0@conan/stable`.

Given that there is already the virtualenv generator which provides everything that is needed to implement this feature I do not expect it to be too difficult. What do you guys think of the functionality? Is it generally useful enough to be included into conan?

**Comment by lasote** [comment] 2018-02-12 20:44
I think in NIX systems probably is not possible because to modify the shell environment you have to run a `source xxx` command.
Furthermore,  I understand your need and it's ok, but I think it could be implemented with a simple script outside Conan, not sure about introducing that use case in the Conan codebase.

**Comment by memsharded** [comment] 2018-02-12 21:55
Also in Windows. As you are running as a python subprocess, you cannot change the environment of the parent. There might be some very dirty tricks like messing with the registry, but very risky, so if something goes wrong, the system might become "dirty". So I think an intermediate ".bat" script that can be directly activated in the cmd is necessary too, and that cannot be activated by conan so its changes remain for subsequent commands.

**Comment by niosHD** [comment] 2018-02-13 00:12
I think you understood me wrong, let me try to clarify. I do not intend to change the environment of the parent process and AFAIK it is also not really possible under Linux. However, that is not needed. It is sufficient that a process can alter its own environment which is then propagated to sub-processes. Like I wrote in the titel, the original motivation was to start a new shell with the correct environment. (In case Yocto is known, similar to what `bitbake -c devshell <target>` is doing.)

As lasote wrote, a simple script can implement this functionality. In fact, for my regular toolchains, I have scripts like the following in the root directory of the installations:
~~~bash
#!/bin/bash

baseDir=$(dirname `readlink -f -- $0`)

# export toolchain specific paths
export PATH="${baseDir}/bin:${PATH}"
export LD_LIBRARY_PATH="${baseDir}/lib:${LD_LIBRARY_PATH}"

# setup toolchain specific prompt and zsh config
export TOOLCHAIN_NAME="ARM-NONE-EABI"
export ZDOTDIR="${baseDir}/zsh_dotdir"

# possibly more configurations

# launch a new interactive shell with this environment
zsh
~~~

The interesting part here is that these scripts perform more or less the same task as sourcing `activate.sh` from the virtualenv generator followed by an actual command. Of course I could still keep scripts like this also for the toolchains installed via conan. However, it feels kind of silly to keep them around given that conan has enough information to implement the same functionality on the fly for arbitrary toolchains.

Furthermore, now that I think about, by making the actually called binary at the end configurable, this feature can be generalized even further. The result would be something like `conan exec` which simply executes a given command in the specified environment. Think of something like `conan exec -r cmake_installer/3.10.0@conan/stable cmake` which then runs cmake 3.10 via conan instead of the cmake from the system. My initially proposed functionality would be just another example like `conan exec -pr custom-toolchain zsh`.

Sorry for the long post but I hope that I could clarify what I have in mind. Is the generalized `exec` approach something which is suited for the inclusion into conan?

**Comment by memsharded** [comment] 2018-02-13 09:47
Yes, it clarifies a little, but I still fail to see how this could work. In ``$ conan exec``, that ``conan`` is already a python subprocess, and it is not possible to change that. I don't know how to launch a new interactive shell from python, I don't think it is possible, any suggestions? Thanks!

**Comment by niosHD** [comment] 2018-02-13 10:16
Maybe I did not understand you correctly but what is the problem with simply starting another subprocess? Something like the following should do the job.

~~~python
import os

# Extend environment with the same information that is used
# in the virtualenv generator.
os.environ["PATH"] = "/opt/tmp/install/llvm-trunk/bin:" + os.environ["PATH"]

# Run an arbitrary command
os.system("bash")
~~~

**Comment by memsharded** [comment] 2018-02-13 12:08
Oh! So you meant to keep the original "conan" python process alive and being the parent of the children new shell. Got it.

Now I wonder which would be the shell to be launched. "cmd" in windows? But I am in a cmder terminal, and then I will lose my cmder functionality. It cannot be assumed that I will have or I want to use "bash". Same for linux environments, so I guess it should be something configurable, but it might be difficult to get it right for most users. Another thing about activating the environments via generated scripts is that they can be easily composed, you can sequentially install tools and activate the environments. With the proposed approach I guess you need a nested chain of conan-bash-conan-bash processes.

Also I have some concerns regarding resources. One of the things that allows conan to work is that every command starts and finishes, releasing resources. Not only in terms of memory (what happened if conan used lots of memory to download, unzip and install some package), but also in handles. It is not that unusual that the python process won't release some handles that easily (specially in Windows), so subsequent calls will find those resources blocked. Letting the python process die, really helps with releasing them.

So, while I understand the proposed improvement, it seems to me a bit excessive on the implementation  possible corner cases, but mainly on future maintenance and specially support we would have to provide for those corner cases.

**Comment by niosHD** [comment] 2018-02-13 13:51
Well, keeping the original conan process alive is the easiest thing I could think of and I am confident that this works across all platforms that conan targets. However, if we manage to implement the same behavior in a clean way by replacing the original conan process (for example via `os.execvp`) I would also be fine with that.

Regarding what should be launched, if we go with the `conan exec` idea instead of the originally proposed `conan env` this is no issue at all since the user has to specify what command he wants to execute. Launching a shell is then just a special case where the user specifies sh, or bash, or fish, or zsh, or cmd, or ... to be launched.

As you noted, at least with the `os.system` implementation, it is possible to create deeply nested conan-bash-... chains. However, I do not anticipate very deep nesting for standard use cases and I did not plan to stop any user from harming himself by misusing this feature.

On the other hand, your concerns regarding resource consumption are more alarming for me. Especially if handles are indeed not properly freed by python. However, I think it is best to actually try it in order to find out if it is an issue in practice.

My takeaway message from this discussion so far is that you guys are principally not opposed to something like `conan exec` given that it does not introduce too much maintenance burden. I think I will have to provide a prototype implementation next such that we can discuss the merits, costs, and problems more concretely. Thank you for the feedback so far. Further comments are of course still welcome!

**Comment by niosHD** [comment] 2018-02-23 13:22
I provided a WIP implementation of the `conan exec` feature in #2516. Please give it a try and tell me what you think.

**Comment by aucampia** [comment] 2019-12-19 15:32
@lasote @niosHD 

I made this: https://gitlab.com/xadix/xonan - which has since bitrotted - but it did this on top of conan using non public APIs (which is why it stopped working).

I think if the API can be extended slightly then this use case can be provided as an addon in a similar way I did it there. I will try fix it to work with more recent version of conan so it is possible to run and see how it works, but the summary:

You run this:

```bash
xadix.xonan exec groovy_prebuilt/2.5.6@xadix/default -- java -version
```

Then of you have groovy_prebuilt/2.5.6@xadix/default - it will be used - otherwise it will build it and then it will basically exec `java -version` with environment set up based on this package.

I would like to support many other cases - and support options etc (this just uses default options) - but if you are interested in this functionality I think we should try and get the APIs for this implemented and move from there.

**Comment by memsharded** [comment] 2019-12-20 18:27
Hi @aucampia 

Thanks for sharing this. While I understand the simplicity of the oneline command, the problem is that it will easily lead to many extensions and requests for generalization:

- I need to activate more than 1 package, so now N packages need to be specified
- Define settings, options, environment variables... (everything you need to set for ``conan install``, because at the end, you need to install that package/s)
- I want to have control over what is build and not. Building from sources by default goes against many users policies, as a lack of binary means something is broken, and dependencies shouldn't build from sources by default. So add ``--build`` logic to the question.
- What "generator" to use? For many cases and packages the ``virtualrunenv`` could be enough. But you might need to activate some of the custom env-vars that some package define, then you need ``virtualenv``. Then use both always? That can inject unwanted binaries/config in your environment
- It is convenient to be able to setup the environment for IDEs and other tooling, not only for a command.

Now add the above to the complexity of wanting to run conan itself (one of the very popular use cases) inside of a environment defined by some conan packages. Now you have a mess of arguments repeated before and after the --, not elegant. Also, many times you probably want to run several commands in the environment not just one, and having to repeat the same command line params again and again is not the best either.

So, even the oneliner is nice for some cases, we are suggesting the more general and flexible approach:

```bash
$ conan install ...... # can use reference or conanfiles to install, that generates env files
$ activate the environment
$ run your things
$ deactivate
```

We are introducing changes to the virtualenvs generators, simplifying them (last changes, already merged, dumps envs to files that are later used in activate scripts, not directly in scripts), and we will keep improving them for better activation/deactivation, nested environments, etc. There is still tons of work to do here, and I think we need to focus on this first, we can't spread more, as we are already very over capacity and our backlog and roadmap is full. Thanks very much for the suggestions and the feedback!

**Comment by memsharded** [comment] 2024-01-10 23:07
Closing this as not planned.

Conan 2.0 offers the custom commands framework, and it will be providing an stable Python ConanAPI too, that will allow this kind of extensibility if desired.

**Closed by memsharded** 2024-01-10 23:07 UTC
