### ISSUE TITLE
Canceling the download process of dependencies

### ISSUE THREAD

**Issue by Kretsch0** [conan-io/conan#1412] opened 2017-06-21 07:53 UTC
I installed a package and pressed strg + c. The result was to have a incomplete package. 

* a conan search did not show the package
* the folder structure exists but not all files. Some. Some libs were missing.
* a conan install ( without --update ) worked to the point where the linking starts
    * it looks correct but linking wasn't possible .. because some libs were missing

So.. If the user did a mistake and quit the progress, like me strg + c, it results to unspecified behavior. Would be great if there is a better solution... So conan should check the consistency of the package after downloading.

**Comment by memsharded** [comment] 2017-06-21 21:22
We have already added some checks, for example when the sources download is interrupted.
The problem is that this is basically impossible to achieve this completely. Possibly, some parts could be made more robust, but making the program to have a consistent state irrespective of the point it is killed, it is almost impossible. Considering that everything is in files, there is no DB, for convenience and transparency for the user.

> So conan should check the consistency of the package after downloading.

But this is precisely the problem, if the download or unzip is interrupted, you cannot check the consistency. So the solution would be to add checks everytime a package is consumed, which would be an extra overhead. Would it need to check the checksums? That is really slow, not possible. If checking only the existence of the conaninfo.txt, it is possible that other files haven't been extracted yet...

I am afraid this would be a huge effort to gain just a minor improvement in robustness. 
And I know that it is not the most elegant solution, bu if something goes wrong, I just run a ``conan remove "*" -f`` to wipe my local cache, I will waste some minutes to re-download packages, but it always work. 

Would like the opinion of @lasote here.

**Comment by lasote** [comment] 2017-06-23 15:54
Maybe a "dirty" file created before the download starts and removed at the end. If the process is unexpectedly closed, the next time you are going to use a package you will first check if the "dirty" file is there. I'm not telling that it is an easy fix, probably the install flow is complex and not has a single entry point... but we could take a look.

**Comment by memsharded** [comment] 2022-08-25 22:49
we added long time ago .dirty flags in different parts ofthe process to identify and clean incomplete things. Closing this as implemented.

**Closed by memsharded** 2022-08-25 22:49 UTC
