### ISSUE TITLE
[bug] conan info fails for recipie with python_requires and build_id

### ISSUE THREAD

**Issue by schletti2000** [conan-io/conan#6562] opened 2020-02-18 18:28 UTC
### Environment Details 
  * OS: Tested on Ubuntu 18.04 and Windows 10
  * Conan version: 1.22.2
  * Python version: 3.6.8

### Steps to reproduce

Create a [simple base recipe](https://docs.conan.io/en/latest/extending/python_requires.html#extending-base-classes) and export it:
`./test/base_pkg/conanfile.py:`
```python
from conans import ConanFile

class MyBase(object):
    def source(self):
        self.output.info("My cool source!")
    def build(self):
        self.output.info("My cool build!")
    def package(self):
        self.output.info("My cool package!")
    def package_info(self):
        self.output.info("My cool package_info!")

class PyReq(ConanFile):
    name = "pyreq"
    version = "0.1"
```

`python-require` the base package (python_requires is enough to reproduce the error) and set a build_id:
`./test/my_pkg/conanfile.py:`
```python
from conans import ConanFile

class MyPkgConanFile):
    python_requires = "pyreq/0.1@user/channel"
    python_requires_extend = "pyreq.MyBase"

def build_id(self):
    pass
```

Now export the base package, and run `conan info .` in `./test/my_pkg/conanfile.py`. This should yield the error: 
`ERROR: 'minor_mode' is not a known package_id_mode`

### Possible fix (1.22.2):
```diff
--- /a/conans/model/info.py 
+++ /b/conans/model/info.py 
@@ -351,8 +351,8 @@
             self._refs = None

     def copy(self):
-        # For build_id() implementation
-        return PythonRequiresInfo(self._refs, self._default_package_id_mode)
+        # For build_id() implementation - get ConanFile ref from PythonRequiresInfo ref
+        return PythonRequiresInfo([py_req_info._ref for py_req_info in self._refs], self._default_package_id_mode)

     def __bool__(self):
         return bool(self._refs)
```

### Stack trace (excerpt)
1. `Command.info (conans/client/command.py:706)`:
```python
    self._outputer.info(deps_graph, only, args.package_filter, args.paths)
    #    ^^^^^^^^^
    # The graph only fails when called with the CommandOutputer
```

2. `CommandOutputer.info (conans/client/conan_command_output.py:211`

3. `build_id (conans/client/installer.py:39)`:
```python
if hasattr(conan_file, "build_id"):
        # construct new ConanInfo
        build_id_info = conan_file.info.copy() #<--
        #                               ^^^^^^
        # Fails if info contains a PythonRequiresInfo
```

4. `PythonRequiresInfo.copy (conans/model/info.py:425)`

5. `PythonRequiresInfo.copy (conans/model/info.py:355)`:
```python
class PythonRequiresInfo(object):

    def copy(self):
        return PythonRequiresInfo(self._refs, self._default_package_id_mode) #<--
        #This should pass self._refs._ref, which is the ConanFileReference
        #self.ref
```

6. `PythonRequireInfo.__init__ (conans/model/info.py:349)`:

7. `PythonRequireInfo.__init__ (conans/model/info.py:288)`:
```python
    try:
      getattr(self, default_package_id_mode)() #<--
      #Fails because self is a PythonRequiresInfo object, instead of a ConanFileReference
```

**Comment by memsharded** [comment] 2020-02-18 23:51
Thanks very much for your detailed report and your investigation.
You are right, this is a bug, I have submitted a PR with it in https://github.com/conan-io/conan/pull/6563, planning to merge and release it for next Conan 1.23 release.

**Comment by memsharded** [comment] 2020-02-18 23:53
BTW, your fix was correct, do not hesitate next time to submit a PR yourself, we can always try with tests, etc if necessary.

**Comment by schletti2000** [comment] 2020-02-19 13:48
Thank you! Will do a PR next time but how can I be sure if its a bug or just incorrect usage?

**Comment by memsharded** [comment] 2020-02-19 14:01
Well, in this case you know it because you tracked down in the codebase and detected that an argument was being passed with the wrong type. 
Also, that kind of "default" setup shouldn't probably fail, there were no much space for "being a feature". If not a bug, we will close it, but if it is, we can help contributing tests, etc., and you get the acknowledgement as contributor to Conan, which is deserved if you actually put the effort!

**Closed** 2020-02-21 16:11 UTC
Labels: type: bug
