### ISSUE TITLE
[bug] Unable to override requirements

### ISSUE THREAD

**Issue by anderson-dev** [conan-io/conan#10905] opened 2022-03-28 15:43 UTC
Whether I `--require-override`, or simply use `self.requires("myPkg/1.0")\nself.requires("myPkg/1.0.1", override=True)`, it always results in error:
```
ERROR: conanfile.py (my-app/None): Error in requirements() method, line 46
        self.requires(f"myPkg/1.8.0@{self.user}/{self.channel}", override=True)
        ConanException: Duplicated requirement myPkg/1.8.26 != myPkg/1.8.0@xenotran/stable
```

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 20H2
  * Compiler+version: N/A
  * Conan version: 1.45.0
  * Python version: 3.10.0

### Steps to reproduce (Include if Applicable)
1. create an msbuild recipe
2. specify a specific version of a dependency using `self.requires`
3. specify a different version using `conan install . user/channel --require-override` or `self.requires(x, override=True)`

**Comment by anderson-dev** [comment] 2022-03-31 23:10
Am I misunderstanding the intended behavior of this feature? Is it only for indirect dependency overrides?

**Comment by lasote** [comment] 2022-04-01 06:44
I cannot reproduce the issue, could you provide a simple example in a zip or explain the recipes you have and the relation between them?

**Comment by anderson-dev** [comment] 2022-04-02 16:47
Reproduceable Examples

Example 1: `conan install . --require-override boost/1.77.0` doesn't seem to override `boost/1.75.0`
```
1. git clone https://github.com/anderson-dev/troubleshooting-conan.git
1. cd require-override
1. conan install . --require-override boost/1.77.0
```

Example 2: explicitly specifying `self.requires("boost/1.77.0", override=True)` doesn't seem to override `boost/1.75.0` either
```
1. git clone https://github.com/anderson-dev/troubleshooting-conan.git
1. cd require-override
1. git checkout explicit-override
1. conan install .
```

**Comment by lasote** [comment] 2022-04-04 07:29
Thanks for the examples, now I have been able to reproduce it. We have to investigate a bit further, I checked that the issue is with the `requirements(self)` method, using `requires` attribute works fine, but I'm not sure this is expected or if there is any limitation with the `requirements(self)` method and ``--require-override``.

This is a failing test to help figuring out:

```
    def test_install_cli_override_requirements_method(self, client):
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . zlib/1.0@")
        client.run("create . zlib/2.0@")
        client.save({"conanfile.py": GenConanfile().with_requirement("zlib/1.0")})
        client.run("install . --require-override=zlib/2.0")
        assert "zlib/2.0: Already installed" in client.out
```

I'm tagging this to `look-into` and assigning it to the next release. 
Thanks for reporting.

**Comment by boussaffawalid** [comment] 2022-04-15 13:20
this is the same issue as https://github.com/conan-io/conan/issues/11030
I tried this fix https://github.com/conan-io/conan/pull/10046/files and it resolved the issue.

**Comment by memsharded** [comment] 2022-04-28 12:03
We have finally decide to go a different way with the overrides, for Conan 2.0, already implemented there for next alpha7. It will be possible to define overrides for "host" and "build" (even "python") requires, by defining those in a lockfile with the ``conan lock add`` command, then passing the lockfile, as long as the defined thing fits in the defined version range. That is, the definition of the ``requires`` need to be consistent if it is expected to really be re-defined.

**Comment by boussaffawalid** [comment] 2022-04-28 23:28
@memsharded the current implementation of `--require-override` in conan 1.x works perfectly when used with `conan create` but it does not work with `conan install`, so the behavior is not consistent.

As I mentioned before https://github.com/conan-io/conan/pull/10046/files fixed the issue.

We were waiting for the `--require-override` for a very long time now and it is unfortunate that we cannot use it as we still far from upgrading to conan 2.x

* is it possible to merge this fix above for conan 1.0 just to have something that works until we upgrade, I'm trying to avoid maintaining a conan fork for just this fix.
* If not, is there any side effects of the fix above, I'm currently using a fork of conan with this fix in production and did not notice any problem so far.

**Comment by anderson-dev** [comment] 2022-05-02 18:19
@memsharded I understand focus is on 2.0 but this is a regression for 1.x. Please at least change the [documentation ](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#require-override) to reflect that this feature will no longer be supported in 1.x so folks can plan to either use the 2.0 alpha, a custom fork using @boussaffawalid's fix, or a custom cascaded option-based override in order to support CI what-if scenarios (which is my current Plan B)

**Comment by CJCombrink** [comment] 2022-05-04 06:54
This would also be useful for us in our Jenkins "nightly builds", still using conan 1.0.

That way we can do a test build against newer/other versions as part of regular CI to do some risk mitigation/planning.

**Comment by lasote** [comment] 2022-05-04 07:23
> I understand focus is on 2.0 but this is a regression for 1.x. Please at least change the [documentation ](https://docs.conan.io/en/latest/reference/commands/consumer/install.html#require-override)to reflect that this feature will no longer be supported in 1.x

@anderson-dev  Sorry but this never worked in 1.X and it is an experimental feature, so it is not a regression: https://docs.conan.io/en/latest/reference/commands/creator/create.html#require-override

> That way we can do a test build against newer/other versions as part of regular CI to do some risk mitigation/planning.

@CJCombrink Please note that in Conan 2.X the way to do this is using lockfiles, but, very important, lockfiles will never allow overriding a "fixed" requirement, only if the specified reference has a version range (or the lock is locking the recipe revision). So it won't be possible to have a require to `zlib/1.2.11` and say, "let's try to see what happens with `zlib/1.2.12`".  If you want to do that you will need to specify a version range or you need to change the fixed reference to `zlib/1.2.12` in every consumer.

**Comment by CJCombrink** [comment] 2022-05-04 07:43
> but, very important, lockfiles will never allow overriding a "fixed" requirement

Ok thanks this is useful information. Our current implementation is:
```
...
options = {"nightly": [True, False]}
...
if not self.options.nightly:
    self.requires("some_lib/0.2.15")
else:
    self.requires("some_lib/[>0.0.0]")
```

I was hoping we could get past this logic in the conanfile and extract the override to the CI setup.
Seems like this would still be the best solution even for conan 2.0

PS: I know this is not the correct place for this discussion, is there perhaps a better place to discuss better solutions or a proper feature request. There are a lot of issues on the matter and it seems like it is a feature many users want, that is sort of solved with the `--require-override` CLI argument but will be lost completely again in conan 2.0

**Comment by lasote** [comment] 2022-05-04 09:14
That work flow should be improved with lockfiles & Conan 2.0. We are finishing the implementation for 2.0 right now. But basically, the lock files are now a very simple json with lists of references, I think in your case you might be able to generate a `conan.lock` file, even committing it to the repository, and always if the dependency is open to be upgraded, declare it with a version range. 

The lockfile will make sure that the same version is always taken automatically (if the lockfile is there it is used automatically) unless you change (there is also a `conan lock add <ref>`) your lockfile to upgrade it. Take also into account that being a json is easily parseable and also Conan 2 will provide a useful Conan Python API and a way to declare custom user commands to create/customize any behavior you need.

**Closed as completed** 2022-05-11 07:17 UTC
Labels: type: bug, type: look into
