### ISSUE TITLE
[bug] toolchain file: CMAKE_GENERATOR_PLATFORM regression in 1.36.0?

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#8893] opened 2021-04-28 14:55 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019 + Ninja generator
  * Conan version: 1.36.0
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)

- add a basic toolchain file in `conanfile.py`:

  ```python
  from conans import ConanFile, tools
  from conan.tools.cmake import CMakeToolchain


  class TestConan(ConanFile):
  ...
      def generate(self):
          tc = CMakeToolchain(self)
          tc.generate()
  ...
  ```

- install some external libraries with this conanfile:
  ```
    mkdir build
    cd build
    conan install .. -g cmake_find_package -g cmake_find_package_multi
  ```

- call CMake on a basic top CMakeLists with this toochain file and Ninja generator:
  `cmake .. -DCMAKE_TOOLCHAIN_FILE=<path to toolchaine file> -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -G Ninja`

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
[cmake] Not searching for unused variables given on the command line.
[cmake] Using Conan toolchain through d:/projects/test/build/msvc2019_x64_x64_Release/conan_generators/conan_toolchain.cmake.
[cmake] CMake Error at CMakeLists.txt:2 (project):
[cmake]   Generator
[cmake] 
[cmake]     Ninja
[cmake] 
[cmake]   does not support platform specification, but platform
[cmake] 
[cmake]     x64
[cmake] 
[cmake]   was specified.
[cmake] 
[cmake] 
[cmake] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
[cmake] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[cmake] -- Configuring incomplete, errors occurred!
```

This issue was fixed in 1.33.0 I think: https://github.com/conan-io/conan/issues/7485. At least It was working in conan 1.35

**Comment by memsharded** [comment] 2021-04-28 15:56
Hi @SpaceIm 

Thanks for the feedback, but it seems this is not a bug, it is this way by design. The ``CMakeToolchain`` requires to know the CMake generator when it runs. Because what happens will be different based on it. For example, it might need a conanvcvars.bat to define the Visual environment for a successful build, which is not needed for ``Visual Studio`` generators. Please have a look at https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html#cmaketoolchain.

We are working in the UX, but you might try doing ``CMakeToolchain(self, generator="Ninja")`` at the moment.

**Comment by SpaceIm** [comment] 2021-04-28 16:02
I understand, but it seems odd to have to hardcode generator in its conanfile based on a build system detail of consumers, it should work for all generator handled by CMake. It means that I can't use toochain feature in an agnostic CMakeLists, and it forces all consumers to use Ninja. Maybe I miss the main use case of toolchain file.

**Comment by memsharded** [comment] 2021-04-28 16:17
> I understand, but it seems odd to have to hardcode generator in its conanfile based on a build system detail of consumers, it should work for all generator handled by CMake. It means that I can't use toochain feature in an agnostic CMakeLists, and it forces all consumers to use Ninja. Maybe I miss the main use case of toolchain file.

Yes, I agree! This is the UX part that is missing at the moment. The key idea is that the generator needs to be know at install time, so it might be something like this:

```bash
$ conan install .. -c tools.cmake.cmaketoolchain:generator=Ninja
$ cmake .. -DCMAKE_TOOLCHAIN_FILE=<path to toolchaine file> ... -G Ninja
```

We still need to implement this, so at the moment the only way to define it is via the constructor of CMakeToolchain. We will try hard to provide this in next 1.37. The main problem is that there are few things that depend on the generator in the toolchain and generate() step:

- The definition (or not) of the vcvars environment
- Definition (or not) of the platform
- Definition (or not) of the toolset, the compiler, and compiler version

So we needed to start introducing some changes, like the ``conanbuild.json`` file, which is kind of a CMake presets (but for 3.15), that contains some information like the CMake generator or the CMake toolchain file name, and generating the ``conanvcvars.bat`` file from ``CMakeToolchain.generate()``.

**Comment by SpaceIm** [comment] 2021-04-28 16:21
Understood, it makes total sense.

**Comment by memsharded** [comment] 2021-05-27 15:38
https://github.com/conan-io/conan/pull/8899/files added Conan configuration for CMakeToolchain selection of CMake generator, which seems to be resolving this issue. This will be in 1.37.

**Closed as completed by memsharded** 2021-05-27 15:38 UTC
Labels: type: feature
