### ISSUE TITLE
conan export-pkg command not passing --version to the recipe with Conan 2.2.3

### ISSUE THREAD

**Issue by sharadupadhyaya** [conan-io/conan#16223] opened 2024-05-08 13:02 UTC
### What is your question?

I was using Conan 2.0.0 and conan export-pkg --version "xyz" was working fine with version passed from command.
Recently started using latest Conan version 2.2.3. With this conan export-pkg command is not passing the --version value to the recipe. When I printed the version in recipe it shows None.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-05-08 13:19
Hi @sharadupadhyaya 

I am afraid I cannot reproduce. I have tried locally and this seems to work correctly.
Please provide:
- A full ``conanfile.py`` that allows to reproduce the issue.
- The exact command you are typing
- The full output of the command

**Comment by sharadupadhyaya** [comment] 2024-05-08 13:45
Please see the example attached.
I am using attached conanrecipe.py that uses a python-require package.
[test.tar.gz](https://github.com/conan-io/conan/files/15249802/test.tar.gz)

Command to create the python-require package:
`conan create test/testmodule.py`
Command to reproduce the issue:

`conan install conanrecipe.py --version 1.0+0`

`conan export-pkg --version 1.0+0 conanrecipe.py `
Output:
None
ERROR: conanfile.py: Invalid configuration: Version not passed

**Comment by sharadupadhyaya** [comment] 2024-05-08 13:56
Above works fine with Conan2.0.0.

**Comment by sharadupadhyaya** [comment] 2024-05-08 14:09
This worked till Conan 2.0.11, started failing from Conan2.0.12.

**Comment by memsharded** [comment] 2024-05-08 14:40
Thanks very much, that really helped to reproduce the issue. It was being caused by the ``python-requires`` inheritance.
I am having a look to provide a fix.

**Comment by memsharded** [comment] 2024-05-08 15:01
I am proposing a fix for this in https://github.com/conan-io/conan/pull/16224

Indeed, the addition of some checks back then caused this issue. Please note from https://docs.conan.io/2/introduction.html

> Only the latest released patch (major.minor.patch) of every minor version is supported and stable.

So as this behavior was already in latest 2.0.17, it cannot be considered a regression, but a regular bugfix. 
Still I am assigning this to the next patch release 2.3.1, so it can be released as soon as possible.

Thanks very much for reporting!

**Comment by sharadupadhyaya** [comment] 2024-05-08 15:15
Thanks, I will wait for patch release 2.3.1.

**Comment by memsharded** [comment] 2024-05-09 08:10
Closed by https://github.com/conan-io/conan/pull/16224, it will be in next 2.3.1

**Closed as completed by memsharded** 2024-05-09 08:10 UTC
Labels: stage: triaging

**Comment by memsharded** [comment] 2024-05-17 07:22
2.3.1 is out

**Comment by sharadupadhyaya** [comment] 2024-05-22 16:37
Thanks Conan-Io/Conan
