### ISSUE TITLE
[bug] #5713 allows inconsistent builds

### ISSUE THREAD

**Issue by klaussnd** [conan-io/conan#6344] opened 2020-01-13 16:54 UTC
Since issue #5713 has been merged, inconsistent configurations don't generate an error anymore.
Example:
App A depends on B==2.0.0 and C==1.0.3
B==1.0.3 depends on C[>=1.1.0]
This is inconsistent, because the version requirement of B on C is broken by A's request. Accepting it without throwing an error is problematic, because it can hide problems. Version ranges state strict requirements and violating them, even with exact dependencies versions, introduces possible problems. We had a case where the final app crashed because the inconsistency was not reported as error. I think this behaviour should be configurable, and the default should be to throw an error on encountering inconsistencies. This will help developers to spot problems, but still allows to ignore them if you really know what you are doing. In my experience, in the majority of the cases those inconsistencies show you real problems.

### Environment Details (include every applicable attribute)
  * This is a general issue independent of Operating system and Python version.
  * Conan version: >= 1.20.0

**Comment by memsharded** [comment] 2020-01-13 18:30
Hi @klaussnd 

Thanks for your feedback. 

This was considered a bug in the dependency resolution, as defined in the "Bugfix" Changelog in https://github.com/conan-io/conan/pull/5713

One of the design principles of Conan is that the end consumer should be able to define what they want. In this case if ``App``, explicitly require the fixed ``C==1.0.3``. It means that C 1.0.3 will be used upstream. Exactly in the same way that if B defines ``C==1.1.0``. This is strict version overriding. It doesn't make much sense that the downstream can completely overwrite C==1.1.0 and it cannot overwrite C>=1.1.0. This is why this was considered a bug and fixed.

If you want to get version-range checks, then the downstream should be defined as a version range, so App should be declaring something like ``LibC/[1.0.3]``. This will raise the incompatible version error. 

In this way, both behaviors can be satisfied (it is important to note that https://github.com/conan-io/conan/pull/5713 was implemented by users feedback too, they were reporting that the overriding was broken and not working properly), and it makes sense to use strict versioning when you want strict overriding and version ranges syntax when version ranges resolution is intended.

**Comment by klaussnd** [comment] 2020-01-13 19:03
Hi @memsharded
Thank you for your explanation.
If you want to pin the dependencies to have reproducible builds, at some point you must select strict versions (we do it in a lock file). But then this triggers the new behaviour that we are not notified of inconsistencies, which makes it easy to miss problems. How can I pin versions and still be notified of possible problems? This is why I suggested making that optional in my initial comment. If you have another solution, I am happy to hear about it.

**Comment by memsharded** [comment] 2020-01-13 19:17
> If you want to pin the dependencies to have reproducible builds, at some point you must select strict versions (we do it in a lock file). But then this triggers the new behaviour that we are not notified of inconsistencies, which makes it easy to miss problems.

I am not sure what you mean here. If you are using a lockfile, this will force the exact same versions that are defined in the lockfile. There are no questions of inconsistencies, there is no version-range resolution when using lockfiles. Instead, the versions used in the lockfile are always used. By definition, resolving a lockfile (at least a complete one), can never have conflicts, for example, because otherwise you wouldn't have been able to generate that lockfile in the first place. Could you please clarify a bit more? Thanks!

**Comment by klaussnd** [comment] 2020-01-14 14:54
You can get inconsistent lockfiles, for example, if some of your dependencies are buggy and have incorrect requirements, or if you need to adjust the lockfile manually, maybe because you cannot use the newest available version of a certain dependency for some reason. It is helpful to spot such inconsistencies as soon as possible.

**Comment by memsharded** [comment] 2020-01-14 15:31
Hi @klaussnd 

Lockfiles should not be modified, manually adjusting the lockfile shouldn't be done. A lockfile is a snapshot of a dependency graph, if something in the graph changes, you need to capture a new lockfile, this is the only possibility to keep things working. The whole purpose of lockfiles is reproducibility, changing a lockfile manually is a violation of its core concept. Dependency definition and resolution should be done in conanfiles recipes, please do not use lockfiles to try to define dependencies.

**Comment by symtor** [comment] 2020-01-14 16:22
Hi @memsharded ,

I'm skipping the points regarding lockfiles here, since how the consumer defines their dependencies should not matter.

> One of the design principles of Conan is that the end consumer should be able to define what they want. In this case if `App`, explicitly require the fixed `C==1.0.3`. It means that C 1.0.3 will be used upstream. Exactly in the same way that if B defines `C==1.1.0`. This is strict version overriding. It doesn't make much sense that the downstream can completely overwrite C==1.1.0 and it cannot overwrite C>=1.1.0. This is why this was considered a bug and fixed.

I generally welcome the idea of allowing the end consumer to choose what dependencies they want. Whether the dependency is version-ranged (`[C==1.1.0]`, `[C>=1.1.0]`) or not (`C==1.1.0`) should not make a difference. My and @klaussnd 's main issue is that this behavior is the default: Overriding a dependency is inherently unsafe (B clearly states that it requires C>=1.1.0). There may be situations where the consumer knows exactly what they are doing, and does manual checks, so overriding is safe. In the more common case, the override will appear by accident (e.g. a new version of B being published that has new requirements for C). If the consumer doesn't read the CI logs very carefully, such a change will go unnoticed, and may cause harm at runtime (as it did in our case).

> If you want to get version-range checks, then the downstream should be defined as a version range, so App should be declaring something like `LibC/[1.0.3]`. This will raise the incompatible version error.

I don't see how it is practical to differentiate between `LibC/1.0.3` and `LibC/[1.0.3]`. Do I understand correctly that `LibC/1.0.3` will always be overridden, and `LibC/[1.0.3]` cannot be overridden? This violates above design principle of Conan (give choice to the end consumer), and does not feel intuitive to me.

To me, a more intuitive solution would be to never allow overriding, unless the user explicitly expresses their desire when defining a requirement (as in `self.requires('libC/[1.0.3, override=True]@conan/stable`).

**Comment by memsharded** [comment] 2020-01-14 16:26
> To me, a more intuitive solution would be to never allow overriding, unless the user explicitly expresses their desire when defining a requirement (as in self.requires('libC/[1.0.3, override=True]@conan/stable).

Just in case, there is a configuration exactly for this: ``error_on_override``. Please check: https://docs.conan.io/en/latest/reference/config_files/conan.conf.html?highlight=error%20override

**Comment by memsharded** [comment] 2020-01-14 16:27
> I don't see how it is practical to differentiate between LibC/1.0.3 and LibC/[1.0.3]. Do I understand correctly that LibC/1.0.3 will always be overridden, and LibC/[1.0.3] cannot be overridden? 

Actually the opposite: defining ``libC/1.0.3`` strictly overrides the upstream, but ``LibC/[1.0.3]`` will define 1.0.3 upstream, but as it is a range, it will check for validation within other ranges.

**Comment by symtor** [comment] 2020-01-15 08:32
> Just in case, there is a configuration exactly for this: `error_on_override`. Please check: https://docs.conan.io/en/latest/reference/config_files/conan.conf.html?highlight=error%20override

Yes, the `error_on_override` mechanism is a step in the right direction. We cannot use it right now, because in our setup the app uses explicit versions (`libB/2.0.0`, `libC/0.0.14`) whereas some of the libraries use version ranges. This results in a warning
```
WARN: libB/2.0.0@conan/stable: requirement libC/[>=0.0.12]@conan/stable overridden by appA/1.2.3 to libC/0.0.14@conan/stable
```
which would be treated as an error (even though it's not). But if I understand you correctly, changing the app's requirements to `libB/[2.0.0]`, `libC/[0.0.14]` would cause the desired behavior (failure if the version ranges cannot be resolved). Is this correct?

What if some of the dependencies use version ranges, some don't?

**Comment by memsharded** [comment] 2024-10-09 18:11
Closing as outdated, all graph resolution, lockfiles, overrides have changed in Conan 2.
Please create new tickets against Conan 2 as necessary, thanks for your feedback.

**Closed by memsharded** 2024-10-09 18:11 UTC
Labels: stage: triaging
