### ISSUE TITLE
[question] Doing Feature Builds with conan2

### ISSUE THREAD

**Issue by lstoffer** [conan-io/conan#16358] opened 2024-05-29 07:18 UTC
### What is your question?

Hi! I have a question regarding a possible feature build workflow with conan 2.

Some background information:
To test our software we work with issues and create a separate installer for every of this issue where only the changes made for this issue are merged. We call this a feature build and use this feature build installers for our testing.

In conan 1 we used users and channels to create packages specially for this feature build installers. For example `studio/9999.0.0-alpha.4@dev/XY-ab`, where `XY-ab` is the identifier of the issue.
Since it is no longer recommended to use user and channel to distinguish between different packages the question basically is what would be the right way to achieve the same we had with user and channels in conan 2? 

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-05-29 09:11
Hi @lstoffer 

Thanks for your question.

This is still pending to document properly, sorry about that, but the good news is that we have already started.

The overall recommendations would be:

- Packages must be immutables, they cannot change, that is the reason why the changes ``conan copy`` was removed in Conan 2
- The way to implement "stages" in a build is having different server repos, lets call them "build" and "develop" for example.
- The "develop" repo is the one used by developers and regular CI.
- When a feature build (a Pull Request for example) is done, it uploads things to the "build" repo, so it doesn't break other developers or CI
- Only when the things are good, the packages are "promoted", that is they are copied from "build" to "develop" repo. This can be done or example with one of the commands we have in the extensions repo ``conan art:promote``.

We will be documenting the CI processes and good practices in the following months.

**Comment by lstoffer** [comment] 2024-05-29 11:18
Thank you very much for your reply.
I am not sure if this actually solves the problem I am facing. Since there may be multiple different pull requests that are ongoing that might have different dependencies, I still have to distinguish between the different pull request packages in the build repository.

The reason for that is that the builds for those are developed completely independent form each other. So if one pull request does a change to a library `lib` and another pull request does another change to this `lib` they have to be distinguishable such that the final feature build for one of the two feature builds uses exactly the `lib` with the changes from this feature build.

**Comment by memsharded** [comment] 2024-05-29 14:47
>  Since there may be multiple different pull requests that are ongoing that might have different dependencies, I still have to distinguish between the different pull request packages in the build repository.

Every PR will be doing different changes to the recipes. These changes can include a explicit change in the recipe ``version = xxx`` field, but even if they don't, they will already automatically generate a new identifier that is unique to their changes: the ``recipe-revision``

The ``recipe-revision`` allows to explicitly refer to a specific revision, you can do it directly in ``[requires]`` like ``pkg/version#recipe_revision1``, or in conanfile.py ``self.requires()`` too. But they also allow to be defined in ``lockfiles``, the intended mechanism to implement reproducibility (and isolation of builds). This mechanism is better because it doesn't require explicit changes to consumer recipes to change requires, it allows per-package changes easily, and it achieves reproducibility over time. Furthermore, the lockfile mechanism is already necessary the minute there are builds that need to build in different platforms (distributed builds), because otherwise there are risks of race conditions (this is inherent to package management and distributed builds, not specific to Conan).

**Comment by lstoffer** [comment] 2024-05-30 05:46
I am still not sure if I completely understand. How can I find the recipe-revision that is needed. Is there a way to specify a specific recipe such that it can be found automatically? So for example that the recipe contains the ID of the pull request?

**Comment by memsharded** [comment] 2024-05-30 08:21
> I am still not sure if I completely understand. How can I find the recipe-revision that is needed. Is there a way to specify a specific recipe such that it can be found automatically? So for example that the recipe contains the ID of the pull request?

In general, the information flow is in the other direction, the PR knows which recipe revision it is creating. It will be generating lockfiles and storing them somewhere, so things can be reproduced. But in general not naming packages after the PullRequest ID.

A counter example would be a PR that does a change in the repo README (when the README is not part of the package). This change doesn't produce a new version or a new recipe revision at all, and it needs no build or creating a package at all. Conan knows that via the recipe-revision, so it doesn't need to create a new binary from a new build from source just because there was a PR to the repo.

If you still want to do something like that, even if possibly not the best recommended, you can use the build metadata part of the version, that would be a way more standard versioning mechanism, like ``mypkg/1.2.3+pr.123``. This allows resolving to the latest pull request ID when using version ranges too, or being addressed explicitly. But note that having the PR ID in the version or anywhere in the name still doesn't necessarily help: For example, a PR can have multiple commits, and it will be building every commit, until CI is green and reviewers are happy. For every commit, there will still be changes to the recipe and the code, producing a different package each time. Now the PR-ID is not enough to identify the package, because there will be multiple recipe-revisions for the same ``1.2.3+pr.123`` version, one per commit that changes something relevant.

**Comment by lstoffer** [comment] 2024-05-30 11:10
Ok I see. So if I have an automated tool that creates the packages for my PRs i will have to add the specific revision that gets created for the PR into a lockfile for that PR and store this lockfile somewhere.

Just one more question. If I have `lib a`, `lib b` and `lib c` that get used by proj a and `lib b` depends on `lib a`. Could I use one lockfile for the `proj a` and also use the same lockfile to build the lib b separately. Meaning that there are more dependencies in the lockfile than what is actually needed to build lib b. Or would I have to create a separate lockfile for every library?

**Comment by memsharded** [comment] 2024-05-30 11:55
> Just one more question. If I have lib a, lib b and lib c that get used by proj a and lib b depends on lib a. Could I use one lockfile for the proj a and also use the same lockfile to build the lib b separately. Meaning that there are more dependencies in the lockfile than what is actually needed to build lib b. Or would I have to create a separate lockfile for every library?

It is not a problem that the lockfile contains more dependencies that are actually needed, and what you suggest is possible, and actually recommended. You can apply the lockfile that you create for your "consuming" ``proja`` (what we typically call a "product"), and apply that lockfile while building packages in the graph that are to be used later by ``proja``. This is not only recommended, but almost mandatory to do when doing distributed builds, to guarantee that all built packages align on the versions and revisions used of the dependencies, so when you get down to ``proja`` everything works.

**Comment by lstoffer** [comment] 2024-06-05 08:08
Thank you very much once again.

When trying to implement your suggestions I came up with one additional question. If we create a feature branch we want to use the same version for the package as the version the develop branch has at the point where we branched off with the feature branch for the feature.
E.g. the latest commit on the develop branch has the package `lib/1.2.3-alpha.1` I want to create packages `lib/1.2.3-alpha.1-SW-XXXX` for the feature packages. The problem with this is that if I have the package `lib/1.2.3-alpha.1-SW-XXXX` in my local cache and want to build the develop (not the feature branch) the package `lib/1.2.3-alpha.1-SW-XXXX` gets taken instead of `lib/1.2.3-alpha.1`. As far as I understand semantic version I think the `lib/1.2.3-alpha.1-SW-XXXX` should not be taken if it is not explicitly selected by the lockfile since `lib/1.2.3-alpha.1-SW-XXXX` is a smaller semantic version than `lib/1.2.3-alpha.1`. Am I just wrong or is there any other way I can name the packages for the feature build such that they are only taken if explicitly selected by the lockfile?

![Untitled-2023-06-20-0737](https://github.com/conan-io/conan/assets/56252793/e13f407c-ea5f-4c4b-8a18-3ab02e265ccf)

**Comment by memsharded** [comment] 2024-06-05 08:57
Sorry, do you mean that even if you have in your lockfile ``lib/1.2.3-alpha.1``, as-is, it will still pick the ``lib/1.2.3-alpha.1-SW-XXX`` version instead? Can you please confirm this?

If that is the case, that could be a bug or at least unmodeled behavior. The problem could be the abuse of the ``-``, that in semver has some special meaning, which is  "pre-release". Nesting it in an existing prerelease is not recommended, a better syntax could be ``lib/1.2.3-alpha.1.SW.XXXX``.

**Comment by lstoffer** [comment] 2024-06-05 09:02
No sorry this behaviour happens only if I try to do it without a lockfile.
The idea is that I only use the lockfiles for the feature build and work without lockfiles for the "normal" builds.

**Comment by memsharded** [comment] 2024-06-05 10:00
I see, now I see what you mean.

I have checked the code, and ``1-SW-XXXX`` is being taken as a string, not as a pre-release of the pre-release, and this is semantically and alphabetically greater than ``1``, so this ordering of versions is totally expected.

Note that your commits graph is also quite explicit about it. The ``1-SW-XXXX`` is indeed newer than ``1``, not older. I guess that in your case you could do something like use the previous ``0`` version and create a ``0-SW-XXX``, but I don't think that a versioning mechanism or schema should name a newer state of source code with an older version of the previous source code, this breaks the basics of versioning. So I think your problem is kind of different.

I think it is fair that if a developer installs/create a newer version ``1-SW-XXXX`` in their machine, this will be the default used. It is totally expected, it is a later/more modern commit than the one with ``1``, so this should be the default resolved. Note that for the package manager there is no distinction of what "branch" you want to build, and having both packages in the cache, it will naturally resolve to the latest. Because the opposite will happen, what if the developer want to actually test the other branch and not "develop"? How would they be able to test it? They won't be able to do it, unless they force it with a lockfile, but this is a bit unnatural.

If the developer doesn't want to use the latest version, then the alternatives could be:
- ``conan remove */1.2.3-alpha1-*`` (not tested) to remove those newer packages
- To use a lockfile that represents the ``develop`` state and locks the version to the older develop one.
- If the "develop" branch wouldn't be a pre-release already, this could be managed easier by using the ``core.version_ranges:resolve_prereleases`` conf.
- Make sure that indeed the branch versions are older, using like a ``0-SW-XXXX`` version. Not great from the versioning point of view, but if forcing them via lockfiles, it should work.

The assumption about using lockfiles only for "feature branches" doesn't match the essence of lockfiles: they are a time-snapshot mechanism, based on time/version ordering. It is not possible to use it only for feature branches, because they will typically be newer than the stable or "develop" branch.

**Closed as completed** 2024-06-07 09:00 UTC
Labels: type: question
