### ISSUE TITLE
[question] conan(2.0.5) upload fails to upload with SSL errors

### ISSUE THREAD

**Issue by maitrey** [conan-io/conan#13975] opened 2023-05-26 11:50 UTC
### What is your question?

Dear Conan Folks,

I have a platform and variant agnostic package.
The recipe is as follows:
```
from conan import ConanFile
from conan.tools.files import copy
import os


class  ToolsService(ConanFile):
    name = 'toolsservice'
    exports_sources = "conf/cx.yaml", "src/*"
    description = "Application that runs a service"
    version = "1.0.0"
           
    def package(self):
        copy(self, "*.py", self.source_folder, os.path.join(self.package_folder), keep_path=False)

    def package_info(self):
        self.buildenv_info.define_path("TOOLS_ENV", os.path.join(self.package_folder))
```
I use conan: **2.0.5**
Command that I use to create the package is:
conan create . --user autosar --channel bringupconan2
And upload command that fails with:
conan upload toolsservice/0.0.0-dev.4@autosar/bringupconan2 -r autosar-local --confirm 
Uploading package 'toolsservice/0.0.0-dev.4@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb:da39a3ee5e6b4b0d3255bfef95601890afd80709#8cb3f334cdde9ab160778af89e9d9e01'
  -> conan_package.tgz
  -> conaninfo.txt
  ERROR: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)
  Waiting 5 seconds to retry...
  ERROR: 
  Error uploading file: conaninfo.txt, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)'
  -> conanmanifest.txt
  ERROR: Execute upload again to retry upload the failed files: conaninfo.txt.

I noticed that the conaninfo.txt is 0 bytes.
Has something changed with conan-2.0.5 how platform and variant agnostic packages shall be build?
Could someone please help?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-05-26 11:58
Hi @maitrey 

I am failing to see the whole output, and why the upload of the recipe wouldn't fail, but it would fail the upload of the package.

Can you please create a new package with a new name or version, and then upload it, and share the whole output?

Also you need to specify your server details. I'd recommend downloading an ArtifactoryCE in your local machine and trying things locally too, that is usually useful to investigate network and client-server communication issues.

**Comment by maitrey** [comment] 2023-05-26 12:15
It does upload the package but fails to upload conaninfo.txt which is 0bytes. 
I tried the same command on the command line and here is the output:
```
E:\J\work\toolsservice_bringupconan2>conan upload toolsservice/0.0.0-dev.4@autosar/bringupconan2 -r autosar-local --confirm  --force
Checking which revisions exist in the remote server
Recipe 'toolsservice/0.0.0-dev.4@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb' already in server, forcing upload
Package 'toolsservice/0.0.0-dev.4@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb:da39a3ee5e6b4b0d3255bfef95601890afd80709#8cb3f334cdde9ab160778af89e9d9e01' already in server, forcing upload
Preparing artifacts to upload
Uploading artifacts
Uploading recipe 'toolsservice/0.0.0-dev.4@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb'
Uploading package 'toolsservice/0.0.0-dev.4@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb:da39a3ee5e6b4b0d3255bfef95601890afd80709#8cb3f334cdde9ab160778af89e9d9e01'
ERROR: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)
Waiting 5 seconds to retry...
ERROR:
Error uploading file: conaninfo.txt, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)'
ERROR: Execute upload again to retry upload the failed files: conaninfo.txt. [Remote: autosar-local]
```
I think its related to conaninfo.txt being 0 bytes. Why it is 0 bytes that I donot know yet.

**Comment by maitrey** [comment] 2023-05-26 12:24
I think it fails here : https://github.com/conan-io/conan/blob/release/2.0/conans/client/rest/file_uploader.py#L83   
I see that the file size is calculated but not used:
 file_size = os.stat(abs_path).st_size

**Comment by memsharded** [comment] 2023-05-26 12:33
I have just tried uploading a package with 0 bytes conaninfo.txt and it works fine. (Artifactory Cloud)

So the problem should be somewhere else. Can you please detail what server are you using? Can you also try with a local ArtifactoryCE instance to be able to know if it is a client issue or a network thing? We have seen similar things when there are company vpns/proxys or the like.

**Comment by maitrey** [comment] 2023-05-26 12:46
We use artifactory in the cloud. I have to read a bit as I have not used local ArtifactoryCE instance. Is there an easy documentation to set it up or try it ?

**Comment by maitrey** [comment] 2023-05-26 12:49
Another funny thing is it did upload the package except the conaninfo.txt.
If I use it in the consumer package , I get :
ERROR: Corrupted toolsservice/0.0.0-dev.4@autosar/bringupconan2:da39a3ee5e6b4b0d3255bfef95601890afd80709 in 'autosar-local' remote: no conaninfo.txt

**Comment by memsharded** [comment] 2023-05-26 13:42
It can be download from conan.io downloads page and there are docs here: https://docs.conan.io/2/tutorial/conan_repositories/setting_up_conan_remotes/artifactory/artifactory_ce_cpp.html. I typically use the windows .zip, and it is basically unzipping and double-click on a launcher.

**Comment by maitrey** [comment] 2023-06-06 07:05
Sorry for not replying so far as I was on holidays. I will try this today. 
One more important point is for any other package the upload works fine its only for the platform and variant agnostic package(simple package containing scripts without any settings) where I donot specify any build or host profile it fails:
conan create . --user autosar --channel bringupconan2

**Comment by maitrey** [comment] 2023-06-06 09:54
I tried the artifactory edition and on the web ui:
{
  "errors" : [ {
    "status" : 500,
    "message" : "Cannot invoke \"org.artifactory.opentracing.ArtifactoryTracer.startSpanOnCurrentThread(String, java.util.Map)\" because \"this.artifactoryTracer\" is null"
  } ]
}
And on the command line with artifactory.bat:
2023-06-06T09:50:06.718Z ←[1;33m[jfac ]←[0;39m ←[31m[WARN ]←[0;39m [7b746860f2aa910f] [o.j.c.ExecutionUtils:177      ] [jf-common-pool-1    ] - Retry 570 Elapsed 4.76 minutes failed: Registration with router on URL http://localhost:8046 failed with error: UNAVAILABLE: io exception. Trying again

**Comment by maitrey** [comment] 2023-06-06 10:53
Also, when I add -vvv , I see the following errors:
E:\J\workspace\toolsservice_feature_bringupconan2>conan upload -vvv toolsservice/0.0.0-dev.8@autosar/bringupconan2 -r autosar-local --confirm 
12:45:49  c:\tools\python\python36\lib\site-packages\requests\__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
12:45:49    RequestsDependencyWarning)
12:45:49  Checking which revisions exist in the remote server
12:45:49  Preparing artifacts to upload
12:45:49  Compressing recipe sources...
12:45:49  conan_sources.tgz compressed in 0.02299952507019043 time
12:45:49  Compressing package...
12:45:49  conan_package.tgz compressed in 0.01572275161743164 time
12:45:49  Uploading artifacts
12:45:49  Uploading recipe 'toolsservice/0.0.0-dev.8@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb'
12:45:49  -> conan_sources.tgz
12:45:49  -> conanfile.py
12:45:49  -> conanmanifest.txt
12:45:49  Upload toolsservice/0.0.0-dev.8@autosar/bringupconan2 in 2.0459935665130615 time
12:45:49  Uploading package 'toolsservice/0.0.0-dev.8@autosar/bringupconan2#4a9e99a83db6a4028785154fa37f7bdb:da39a3ee5e6b4b0d3255bfef95601890afd80709#8cb3f334cdde9ab160778af89e9d9e01'
12:45:49  -> conan_package.tgz
12:45:49  -> conaninfo.txt
12:45:49  ERROR: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)
12:45:49  Waiting 5 seconds to retry...
12:45:49  ERROR: 
12:45:49  Error uploading file: conaninfo.txt, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)'
12:45:49  -> conanmanifest.txt
12:45:49  ERROR: Execute upload again to retry upload the failed files: conaninfo.txt. [Remote: autosar-local]
12:45:49  Traceback (most recent call last):
12:45:49    File "c:\tools\python\python36\lib\site-packages\conan\cli\cli.py", line 171, in run
12:45:49      command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
12:45:49    File "c:\tools\python\python36\lib\site-packages\conan\cli\command.py", line 134, in run
12:45:49      info = self._method(conan_api, parser, *args)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conan\cli\commands\upload.py", line 58, in upload
12:45:49      conan_api.upload.upload(package_list, remote)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conan\api\subapi\upload.py", line 47, in upload
12:45:49      executor.upload(package_list, remote)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\cmd\uploader.py", line 225, in upload
12:45:49      self.upload_package(pref, prev_bundle, remote)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\cmd\uploader.py", line 245, in upload_package
12:45:49      self._app.remote_manager.upload_package(pref, cache_files, remote)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\remote_manager.py", line 40, in upload_package
12:45:49      self._call_remote(remote, "upload_package", pref, files_to_upload)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\remote_manager.py", line 205, in _call_remote
12:45:49      return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\rest\auth_manager.py", line 41, in call_rest_api_method
12:45:49      ret = getattr(rest_client, method_name)(*args, **kwargs)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client.py", line 76, in upload_package
12:45:49      return self._get_api().upload_package(pref, files_to_upload)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client_common.py", line 211, in upload_package
12:45:49      self._upload_package(pref, files_to_upload)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client_v2.py", line 111, in _upload_package
12:45:49      self._upload_files(files_to_upload, urls)
12:45:49    File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client_v2.py", line 138, in _upload_files
12:45:49      % ", ".join(failed))
12:45:49  conans.errors.ConanException: Execute upload again to retry upload the failed files: conaninfo.txt. [Remote: autosar-local]
12:45:49  
[Pipeline] }
12:45:49  ERROR: script returned exit code 1

**Comment by maitrey** [comment] 2023-06-06 12:16
Hi @memsharded 
Also, I noticed that with conan-1.56, the **conaninfo.txt** for such a package contains:
[settings]


[requires]


[options]


[full_settings]


[full_requires]


[full_options]


[recipe_hash]
    1a96ae26c1133677ab0b5ad2256f0871

[env]

while for 2.x it has absolutely no content.
Another colleague tried a similar package in another conan repo but client is in Linux and there it hangs at upload.
My use-case for this package is on Windows.

**Comment by sandeshhardikar** [comment] 2023-06-06 13:44
Hello ,

I have a similar case with a package containing no settings , its just that my `conan upload` process hangs forever , even though the binary package upload is successful and the `conaninfo.txt` file is missing . 
Environment : ubuntu 20.04
conan version : 2.0.6
Here are the steps
```
# Creates a package with no settings
conan new basic
conan create .
# This command hangs forever , but the package is available in artifactory
$ conan upload -vvv pkg/1.0 -r my-remote
Checking which revisions exist in the remote server
Preparing artifacts to upload
conan_package.tgz compressed in 0.00026297569274902344 time
Uploading artifacts
Uploading recipe 'pkg/1.0#b4c41cddd96b5279e7c5d422a2a4e53d'
Upload pkg/1.0 in 3.5732409954071045 time
Uploading package 'pkg/1.0#b4c41cddd96b5279e7c5d422a2a4e53d:da39a3ee5e6b4b0d3255bfef95601890afd80709#0ba8627bd47edc3a501e8f0eb9a79e5e'

# Now I edit the recipe to contain settings
conan create . -s:arch=x86_64
# Upload works
conan upload -vvv pkg/1.0 -r my-remote
```

So the only problem i see is `While uploading a package with no settings the conan upload command hangs`

One more hint : When i terminate the hanging `conan upload` command and call it again it detects that package is already present and uptodate and terminates successfully .

**Comment by memsharded** [comment] 2023-06-06 14:00
Oh, one more thing. It is important to have an updated Artifactory instance. It is not that it should crash, I don't know why could be causing those 500 internal errors, but there are some small functionality that requires Artifactory 7.52 for correct displaying of binaries, see https://jfrog.com/help/r/jfrog-release-information/artifactory-7.52.0-cloud

I think there could be different issues in this thread, but please if you could check and report (and update if relevant) the Artifactory versions, that could be a hint.

**Comment by maitrey** [comment] 2023-06-07 10:39
Hi @memsharded ,
Artifactory instance that we use is:  **7.49.10** 
Python version that we use is:  **3.6.5**
OS: Windows
I am wondering why the SSL errors occur only on platform and variant agnostic packages. :( 
I am adding here my repository so that you can see my code: https://github.com/maitrey/testtools 
And i create using: python build.py
And my default profile looks like this:
```
[settings]
os=Windows
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=14
compiler.runtime=dynamic
compiler.version=192
```

**Comment by maitrey** [comment] 2023-06-08 00:18
Do I need to create new artifactory repos when moving to conan-2.x from 1.x?

**Comment by maitrey** [comment] 2023-06-16 04:17
hi @memsharded , We have started a JFrog Support call on this topic as we tried couple of trials none of them are working.

**Comment by memsharded** [comment] 2023-06-16 10:33
Sorry for the late reply

> Do I need to create new artifactory repos when moving to conan-2.x from 1.x?

No, exactly the same repos can be used for Conan 1.X and Conan 2.0. The exact same recipe (if modernized correctly) can be used for both Conan 1.X and 2.0, and the binaries generated with both versions are different and mutually exclusive. That means, for example that ``conan list *:*`` in Conan 2.0 will only list binaries generated with Conan 2.0. In this way, the binaries do not collide and they can coexist in the same repositories, so that will make the upgrades easier.

> Artifactory instance that we use is: 7.49.10

I think it is Artifactory 7.52 or 7.53 that contains the latest fixes necessary for full Conan 2.0 compatibility. Previous Artifactory versions can and will work in most cases, it is mostly the "listing of binaries" that fails for 2.0 packages. It is possible that you are unveiling some possible bug here. I'd strongly recommend to try with an updated Artifactory.

> we tried couple of trials none of them are working.

You tried with some "Artifactory latest version trials", and it still failed?

**Comment by maitrey** [comment] 2023-06-16 13:19
I have not yet tried with latest Artifactory versions. But i added some debug statements in file_uploader.py and it seems to fail at the point:
```
 def _upload_file(self, url, abs_path,  headers, auth, display_name):
        file_size = os.stat(abs_path).st_size
        file_name = os.path.basename(abs_path)
        description = "Uploading {}".format(file_name)
        post_description = "Uploaded {}".format(
            file_name) if not display_name else "Uploaded {} -> {}".format(file_name, display_name)
        print("Display name is:", display_name)
        # self._output.info(description)
        with open(abs_path, mode='rb') as file_handler:
            try:
                print("*****************************")
                print("url is:", url)
                print("SSL is:", self._verify_ssl)
                print("Data is:", file_handler)
                print("Headers is:", headers)
                print("Auth is:", auth)
                print("*****************************")
                response = self._requester.put(url, data=file_handler, verify=self._verify_ssl,
                                               headers=headers, auth=auth)
                print("Response is :", response)

                self._handle_400_response(response, auth)
                response.raise_for_status()  # Raise HTTPError for bad http response status
                return response
            except ConanException:
                print ("***conan exception**")
                raise
            except Exception as exc:
                print("Second exception")
                raise ConanException(exc)
```
And the print from this is as below:
```
conan upload -vvv testtools/2.0.0 -r=autosar-local
Checking which revisions exist in the remote server
Preparing artifacts to upload
Uploading artifacts
Uploading recipe 'testtools/2.0.0#6c53d44250e14f5b2a7a4a476d0d54ee'
-> conan_sources.tgz
-> conanfile.py
-> conanmanifest.txt
Upload testtools/2.0.0 in 9.368763208389282 time
Uploading package 'testtools/2.0.0#6c53d44250e14f5b2a7a4a476d0d54ee:da39a3ee5e6b4b0d3255bfef95601890afd80709#373685ae3dc05270695739f37b31dd06'
-> conan_package.tgz
-> conaninfo.txt
ERROR: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)
Waiting 5 seconds to retry...
ERROR:
Error uploading file: conaninfo.txt, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:833)'
-> conanmanifest.txt
ERROR: Execute upload again to retry upload the failed files: conaninfo.txt. [Remote: autosar-local]
Headers is : {'X-Checksum-Sha1': 'c6c38674b3350ad5fe0d5649bc3d5a39c7492a42'}
Display name is: None
*****************************
Response is : <Response [201]>
url is: https://artifactory.com/artifactory/api/conan/autosar-local/v2/conans/testtools/2.0.0/_/_/revisions/6c53d44250e14f5b2a7a4a476d0d54ee/files/conan_sources.tgz
SSL is: True
Data is: <_io.BufferedReader name='C:\\Users\\User\\.conan2\\p\\testtc8cad1d2a2ded\\d\\conan_sources.tgz'>
Headers is: {'X-Checksum-Sha1': 'c6c38674b3350ad5fe0d5649bc3d5a39c7492a42', 'User-Agent': 'Conan/2.0.6 (Windows 10; Python 3.6.5; AMD64)'}
Auth is: <conans.client.rest.rest_client_common.JWTAuth object at 0x0000021A8EB31160>
*****************************
Headers is : {'X-Checksum-Sha1': '2a5d124fe2eab3262c02d27754c6aa9e9c09b63b'}
Display name is: None
*****************************
Response is : <Response [201]>
url is: https://artifactory.com/artifactory/api/conan/autosar-local/v2/conans/testtools/2.0.0/_/_/revisions/6c53d44250e14f5b2a7a4a476d0d54ee/files/conanfile.py
SSL is: True
Data is: <_io.BufferedReader name='C:\\Users\\User\\.conan2\\p\\testtc8cad1d2a2ded\\d\\conanfile.py'>
Headers is: {'X-Checksum-Sha1': '2a5d124fe2eab3262c02d27754c6aa9e9c09b63b', 'User-Agent': 'Conan/2.0.6 (Windows 10; Python 3.6.5; AMD64)'}
Auth is: <conans.client.rest.rest_client_common.JWTAuth object at 0x0000021A8EB31160>
*****************************
Headers is : {'X-Checksum-Sha1': '747767b1d1cbf2c8035f5f89617cbefc0c6409eb'}
Display name is: None
*****************************
Response is : <Response [201]>
url is: https://artifactory.com/artifactory/api/conan/autosar-local/v2/conans/testtools/2.0.0/_/_/revisions/6c53d44250e14f5b2a7a4a476d0d54ee/files/conanmanifest.txt
SSL is: True
Data is: <_io.BufferedReader name='C:\\Users\\User\\.conan2\\p\\testtc8cad1d2a2ded\\d\\conanmanifest.txt'>
Headers is: {'X-Checksum-Sha1': '747767b1d1cbf2c8035f5f89617cbefc0c6409eb', 'User-Agent': 'Conan/2.0.6 (Windows 10; Python 3.6.5; AMD64)'}
Auth is: <conans.client.rest.rest_client_common.JWTAuth object at 0x0000021A8EBBF048>
*****************************
Headers is : {'X-Checksum-Sha1': '27f6669e37fe40a34eb8c7c4150690f642ea2f1b'}
Display name is: None
*****************************
Response is : <Response [201]>
url is: https://artifactory.com/artifactory/api/conan/autosar-local/v2/conans/testtools/2.0.0/_/_/revisions/6c53d44250e14f5b2a7a4a476d0d54ee/packages/da39a3ee5e6b4b0d3255bfef95601890afd80709/revisions/373685ae3dc05270695739f37b31dd06/files/conan_package.tgz
SSL is: True
Data is: <_io.BufferedReader name='C:\\Users\\User\\.conan2\\p\\b\\testt6e0edd475a433\\d\\conan_package.tgz'>
Headers is: {'X-Checksum-Sha1': '27f6669e37fe40a34eb8c7c4150690f642ea2f1b', 'User-Agent': 'Conan/2.0.6 (Windows 10; Python 3.6.5; AMD64)'}
Auth is: <conans.client.rest.rest_client_common.JWTAuth object at 0x0000021A8EB97358>
*****************************
Headers is : {'X-Checksum-Sha1': 'da39a3ee5e6b4b0d3255bfef95601890afd80709'}
Display name is: None
Second exception
Display name is: None
Second exception
Headers is : {'X-Checksum-Sha1': '38aec9fa2e97db80c648491b1c7bb06cbb4e7d06'}
Display name is: None
*****************************
Response is : <Response [201]>
url is: https://artifactory.com/artifactory/api/conan/autosar-local/v2/conans/testtools/2.0.0/_/_/revisions/6c53d44250e14f5b2a7a4a476d0d54ee/packages/da39a3ee5e6b4b0d3255bfef95601890afd80709/revisions/373685ae3dc05270695739f37b31dd06/files/conanmanifest.txt
SSL is: True
Data is: <_io.BufferedReader name='C:\\Users\\User\\.conan2\\p\\b\\testt6e0edd475a433\\d\\conanmanifest.txt'>
Headers is: {'X-Checksum-Sha1': '38aec9fa2e97db80c648491b1c7bb06cbb4e7d06', 'User-Agent': 'Conan/2.0.6 (Windows 10; Python 3.6.5; AMD64)'}
Auth is: <conans.client.rest.rest_client_common.JWTAuth object at 0x0000021A8EB97FD0>
*****************************
Traceback (most recent call last):
  File "c:\tools\python\python36\lib\site-packages\conan\cli\cli.py", line 172, in run
    command.run(self._conan_api, self._commands[command_argument].parser, args[0][1:])
  File "c:\tools\python\python36\lib\site-packages\conan\cli\command.py", line 134, in run
    info = self._method(conan_api, parser, *args)
  File "c:\tools\python\python36\lib\site-packages\conan\cli\commands\upload.py", line 58, in upload
    conan_api.upload.upload(package_list, remote)
  File "c:\tools\python\python36\lib\site-packages\conan\api\subapi\upload.py", line 47, in upload
    executor.upload(package_list, remote)
  File "c:\tools\python\python36\lib\site-packages\conans\client\cmd\uploader.py", line 225, in upload
    self.upload_package(pref, prev_bundle, remote)
  File "c:\tools\python\python36\lib\site-packages\conans\client\cmd\uploader.py", line 245, in upload_package
    self._app.remote_manager.upload_package(pref, cache_files, remote)
  File "c:\tools\python\python36\lib\site-packages\conans\client\remote_manager.py", line 41, in upload_package
    self._call_remote(remote, "upload_package", pref, files_to_upload)
  File "c:\tools\python\python36\lib\site-packages\conans\client\remote_manager.py", line 206, in _call_remote
    return self._auth_manager.call_rest_api_method(remote, method, *args, **kwargs)
  File "c:\tools\python\python36\lib\site-packages\conans\client\rest\auth_manager.py", line 41, in call_rest_api_method
    ret = getattr(rest_client, method_name)(*args, **kwargs)
  File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client.py", line 76, in upload_package
    return self._get_api().upload_package(pref, files_to_upload)
  File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client_common.py", line 211, in upload_package
    self._upload_package(pref, files_to_upload)
  File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client_v2.py", line 111, in _upload_package
    self._upload_files(files_to_upload, urls)
  File "c:\tools\python\python36\lib\site-packages\conans\client\rest\rest_client_v2.py", line 138, in _upload_files
    % ", ".join(failed))
conans.errors.ConanException: Execute upload again to retry upload the failed files: conaninfo.txt. [Remote: autosar-local]
```

Another info:
When I use python-3.10.6 I **donot see** this SSL Unknbown Protocol error and packages are uploaded. 
I noticed that the openssl versions are different in them.
Python-3.6.5 uses: OpenSSL 1.0.2
Python-3.10.6 uses: OpenSSL 1.1.1
I use Windows , I should not forget to mention this.

**Comment by memsharded** [comment] 2023-06-16 14:26
Uhm, the python version detail is interesting.
I am using myself Python-3.6.8 in Windows, and seems to be working fine, though I haven't found anything relevant in the changelogs, not sure if something could have changed. In any case, the recommendation is to use the very latest patch of each version, so maybe it would be worth also trying to upgrade to 3.6.15

**Comment by maitrey** [comment] 2023-06-19 03:51
I took a fresh machine and installed python-3.10.6. This version uses openssl version 1.1.1. The upload works on the client from this machine and now it works on any other client(with python-3.6.5) as well. I donot know how it is resolved but it works now.

**Comment by memsharded** [comment] 2023-06-19 07:00
Thanks for following up and reporting. 
For some reason it seem there was something weird with the OpenSSL version that comes with Python. And a fresh installation can make it work, so it seems a bit out of the scope for Conan, there is little that we can do there, except recommending a fresh installation when we see something similar. So I am closing this ticket.

Thanks very much for all the feedback!

**Closed as completed by memsharded** 2023-06-19 07:00 UTC
Labels: type: question

**Comment by maitrey** [comment] 2023-06-19 07:02
Thanks @memsharded for all the help but I could not explain myself why it worked now and not before. :( :(

**Comment by memsharded** [comment] 2023-06-19 07:06
Yes, it seems one of those weird bugs, very difficult to reproduce, more related to system and setup and not the app itself (those are typically orders of magnitude more challenging to diagnose), and that a clean thing removes it... could be a small corruption in the original setup or something like that, but who knows...

**Comment by sandeshhardikar** [comment] 2023-06-19 11:43
Continuing from my [comment](https://github.com/conan-io/conan/issues/13975#issuecomment-1578798859) .
I have refined observation , the `conan upload` command hangs for package with empty `conaninfo.txt` . So i would not say that ~~conan upload fails for me with no settings~~ , but rather fails with the package which generates empty `conaninfo.txt` . @memsharded .  could you please check if this usecase makes sense.

My environment : 

Environment : ubuntu 20.04
conan version : 2.0.6
python version : 3.8.10

**Comment by memsharded** [comment] 2023-06-19 12:06
Can you please @sandeshhardikar report what is your Artifactory server version? And if it is not >7.52, then can you please update and try again?

**Comment by sandeshhardikar** [comment] 2023-06-20 03:04
@memsharded : Artifactory server version we use is `7.49.10` , Unfortunately updating to `>7.52` wouldnt be so quick , since lot of teams use this instance and we need to request a central CI team to get this done. I will update here once I try it out .
