### ISSUE TITLE
[bug] SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by DDkuang** [conan-io/conan#9769] opened 2021-10-09 08:04 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version:Ubuntu 20.04
  * Compiler+version: gcc 10.3.0
  * Conan version: 1.40.1
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)
1. conan search "protobuf*" -r conancenter

### Logs (Executed commands with output) (Include/Attach if Applicable)
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

**Comment by DDkuang** [comment] 2021-10-09 08:21
Use http://curl.haxx.se/ca/cacert.pem to replace .conan/cacert.pem and conan search succeeds.
Please ignore the pull request.

**Comment by DDkuang** [comment] 2021-10-09 08:23
https://github.com/conan-io/conan/pull/9696

**Comment by memsharded** [comment] 2021-10-11 07:51
Hi @DDkuang 

Yes, this was a duplicate of https://github.com/conan-io/conan/issues/9695, was solved in 1.40.3 and with a ``conan config install`` new repo for older versions. I think this can be closed, thanks!

**Closed as completed by memsharded** 2021-10-11 07:51 UTC
Labels: duplicate
