### ISSUE TITLE
Question about new requires/build_requires behavior in 1.13.0

### ISSUE THREAD

**Issue by brianembry** [conan-io/conan#4715] opened 2019-03-11 16:36 UTC
I have a package that depends on libcurl (https://github.com/bincrafters/conan-libcurl).  libcurl defines a `requires` of OpenSSL.  My package also depends on OpenSSL (set as a build_requires), but the versions aren't in sync.

In 1.12.0 I got this warning, and build proceeds
`libcurl/7.61.1@jenkins/stable requirement OpenSSL/1.0.2o@jenkins/stable overridden by your conanfile to OpenSSL/1.0.2p@jenkins/stable`

In 1.13.0, I now get this, and build stops.
```
ERROR: Conflict in libcurl/7.61.1@jenkins/stable
    Requirement OpenSSL/1.0.2o@jenkins/stable conflicts with already defined OpenSSL/1.0.2p@jenkins/stable
    To change it, override it in your base requirements
```

I'm guessing this was caused by https://github.com/conan-io/conan/pull/4514 

I'm aware of the "indeterminism" you were fixing here.  I'm wondering what is the proper way to "conan" now when we have multiple packages with the same dependency and trying to keep them in sync.

https://github.com/conan-io/conan/issues/3949#issuecomment-470088890
```
The logical way to define the dependencies when this happens and the transitive dependencies of the build_requires shouldn't affect the consumer package is to also convert those transitive dependencies to build_requires themselves.
``` 
So does that mean in our above example libcurl should move to a build_requires?

**Comment by memsharded** [comment] 2019-03-11 17:01
Hi @brianembry 

First I'd like to understand your graph. How is it possible that your package only "build_requires" OpenSSL? "build_requires" are intended for build tools, testing frameworks... something like OpenSSL probably shouldn't be a build_require. If it is indeed a build_require, it could perfectly be bumped to the matching version. build_requires should not affect the final binary at all, as they are not hashed in the package_id. The idea is that you could use the cmake of your system or the cmake of a conan package, with the same result.

Moving libcurl to build_requires won't fix it, because the transitive dependency will still conflict. The solution, if they were not libraries being linked into the consuming package could be:

package-(build_require)->libcurl->(build_require)->openssl1
package-(build_require)->openssl2

This would work, as the transitive build_require will be isolated. Still seems a little bit of abuse of build_requires feature.

If it is not a build_requires, then the solution would be to define matching versions, either in the recipes, or override them explicitly (``override=True``) downstream. 

Please let me know if this helps. Thanks!

**Comment by brianembry** [comment] 2019-03-11 17:55
I was thinking build_requires were 'required for build' and a requires was to indicate required for build & use.

My package outputs a exe with OpenSSL statically linked, so OpenSSL is only required for build and thus a 'build_requires'.  Maybe I've been misusing it.

requires with override=True appears to work. Nobody consumes this particular package this package so doesn't really matter for me, but I would think the above usecase would be correct? maybe not.  Thanks for the clarification!

**Comment by memsharded** [comment] 2019-03-11 20:33
Yes, there a couple of details there:

- build-requires do not affect the binary package-ID, by definition. Unless you are providing your means, or controlling it otherwise, you might get  wrong binaries, i.e., you change the OpenSSL version you are linking, and you still get the same binary package-ID, and then not re-building a new binary (unless, as I said, you are forcing the rebuild)
- If your package is an executable, then it might make a bit more sense, in the sense that linkage requirements do not need to be propagated downstream to consumers of the executable (I guess the issue is that you are using that executable as a build_requires in turn for other purposes). The same issue could be tried if you were creating a shared library that links and embeds the static library. It might not be necessary to propagate the transitive static linkage, but it is totally possible that the headers are included transitively and thus it might need to be propagated to consumers.

The real issue is that in Conan there is no specific "do not propagate downstream" requirement specifier. It is something that we will likely implement in future improvements in how the graph is processed. Until then, yes, you are good to use "build_requires" for your executables, as long as you know what is happening and you control the re-build of the packages when necessary.

**Comment by Lawrencemm** [comment] 2019-03-13 04:55
@memsharded 
I was under the same impression as @brianembry about build_requires. I'm guessing this is a common misconception so it might use a better name as an alias and then eventual deprecation of the old name.

Is there an issue open for improving this? Would be nice to be able to specify requirements that aren't transitive but do affect the binary package hash.

**Comment by memsharded** [comment] 2019-03-13 14:12
Hi @Lawrencemm 

Yes, there is a project https://github.com/conan-io/conan/projects/8 which purpose is to gather items related to the graph model.

**Comment by memsharded** [comment] 2020-11-20 14:38
Hi @Lawrencemm 

We will likely be changing the graph model in Conan 2.0 for making it possible for build_requires to affect the ``package_id`` hash.

In the meantime, as a workaround https://github.com/conan-io/conan/pull/8076 shows that adding a dummy "python_requires" to recipes that point to the build_require, can achieve the same result (as new ``python_requires`` can affect the ``package_id``), maybe that workound is useful.

**Comment by memsharded** [comment] 2023-11-29 22:00
Conan 2.0 (and Conan 1.X with the 2 profiles build/host approach) has improved over this. I think we can close this ticket as solved, please create new ones if necessary.

**Closed by memsharded** 2023-11-29 22:00 UTC
Labels: type: feature, stage: queue, priority: medium, complex: high
