### ISSUE TITLE
[bug] conan install AttributeError: object has no attribute 'install_folder'

### ISSUE THREAD

**Issue by Arghnews** [conan-io/conan#7576] opened 2020-08-21 17:58 UTC
In a directory with a `conanfile.py` as follows:

```py
from conans import ConanFile, CMake, tools

class BlaOConan(ConanFile):
    name = "blaO"
    version = "0.1"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of BlaO here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    generators = "cmake"

    def configure(self):
        cmake = CMake(self)

    #  def build(self):
        #  pass
```

On Ubuntu. Running:
```sh
rm -rf build/ && mkdir build/ && cd build/ && conan install ..
```

Results in output:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: conanfile.py (blaO/0.1): Error in configure() method, line 15
	cmake = CMake(self)
	AttributeError: 'BlaOConan' object has no attribute 'install_folder'
```

The behaviour is unchanged whether or not I add the `-if` or `--install-folder` arguments to `conan install` with a parameter that is the install folder. Ie these all produce the same output as above:

```sh
conan install .. -if .
conan install .. --install-folder install
```

My actual problem is I need to pass to CMake `CONAN_DISABLE_CHECK_COMPILER` in order to try and build the `fmt` library  from source for a project using emscripten. Currently the CMake conan helper is complaining of a compiler version mismatch. Passing `cmake.definitions["CONAN_DISABLE_CHECK_COMPILER"] = True` in the `build` method does not change; my understanding is this is because this is processed after building the dependencies which is too late. I believe it must be passed in the `configure` method. However when I try to add the `configure` method to a relatively barebones `conanfile.py` like the above, I'm running into this error.

I would be appreciative if someone could answer:
- Why this happening and what it means
- How come I have not run into this problem until now. I have been using conan a reasonable amount, I'm surprised I haven't come across this before
- How to fix this

Thanks for reading! My apologies if I'm being dumb and have missed something obvious.

Ubuntu 18.10, conan 1.28.1

Edit:

So after more reading/digging it seems that I've wrongly made the assumption that the Conanfile `configure` method was the place to call CMake's configure step, when actually CMake's configure and build steps should both be called in the `build` method of the Conanfile subclass.

The conan `configure` method is only for editing/processing conan settings/options and instantiating the CMake build helper in there just seems like an error, although unfortunately the error message is just something that happens to fail - the install_folder not being defined.

Perhaps the error message could be improved? Although perhaps this is a rare issue as only I seem to have been confused by it. Otherwise I believe this can be closed.

**Comment by memsharded** [comment] 2020-08-23 20:20
Hi @Arghnews 

Thanks for your detailed report and explanations.

Indeed, the cause is that you are trying to instantiate a ``CMake()`` object in the ``configure()`` method, and at that time the ``install folder`` does not exist yet, because that depends on the ``package_id`` and the package id needs the full settings and options evaluated, which only happens after the graph is fully built. And ``configure()`` is computed while the graph is being computed upstream.

I agree it would be desired to have a better error message, but it is difficult to diagnose this condition. We are right now considering how to improve the access to built-in tools, including the build helpers. Check https://github.com/conan-io/conan/issues/7105 and associated pull requests. This would be an extra feature request, that consist on enabling/disabling access to tools based on context (in this case, the ``CMake()`` build helper would only be available in the ``build()`` and ``package()`` methods. I am going to annotate this request in that thread, and then closing this one, lets follow conversation there. Thanks again!

**Closed as completed by memsharded** 2020-08-23 20:20 UTC
Labels: stage: triaging
