### ISSUE TITLE
[bug] [workspaces] workspace install fails on imports() (1.37)

### ISSUE THREAD

**Issue by MiSo1289** [conan-io/conan#9116] opened 2021-06-16 11:34 UTC
### Environment Details
  * Operating System+version: reproduced on debian/bullseye and archlinux
  * Conan version: 1.37+
  * Python version: 3.9.2
  * Default conan configuration and profile

### Steps to reproduce
- Clone [this workspace](https://github.com/MiSo1289/conan-workspace-bug) - Bare workspace with 2 projects created by `conan new` that reproduces the error. I simply added an `imports()` method to one conanfile. The issue does not occur with conan 1.36 and earlier.
- Run `conan workspace install . -if cmake-build-debug`

### Logs

```
Traceback (most recent call last):
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/command.py", line 2176, in run
    method(args[0][1:])
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/command.py", line 1818, in workspace
    self._conan.workspace_install(args.path, args.settings_host, args.options_host,
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/conan_api.py", line 523, in workspace_install
    installer.install(deps_graph, remotes, build, update, graph_info.profile_host,
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/installer.py", line 316, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/installer.py", line 438, in _build
    self._handle_node_editable(node, profile_host, profile_build, graph_lock)
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/installer.py", line 519, in _handle_node_editable
    copied_files = run_imports(conanfile)
  File "/home/miso/.local/lib/python3.9/site-packages/conans/client/importer.py", line 76, in run_imports
    mkdir(conanfile.imports_folder)
  File "/home/miso/.local/lib/python3.9/site-packages/conans/util/files.py", line 287, in mkdir
    if os.path.exists(path):
  File "/usr/lib/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by DanielRibeiroMaciel-TomTom** [comment] 2021-07-06 08:13
Did you find any workarounds @MiSo1289

**Comment by MiSo1289** [comment] 2021-07-06 09:08
> Did you find any workarounds @MiSo1289

At the moment, my workaround is reverting to 1.36.0

**Comment by DanielRibeiroMaciel-TomTom** [comment] 2021-07-06 09:20
Yeah same for me. Ok thanks.

**Comment by spoofedex** [comment] 2021-07-08 09:35
A colleague of mine made a trivial workaround that seems to work for me. It may or may not work for all cases, so use at your own risk.

in conans/client/importer.py, in run_imports, change:
```
def run_imports(conanfile):
    if not hasattr(conanfile, "imports"):
        return []
    mkdir(conanfile.imports_folder)
```

To:
```
def run_imports(conanfile):
    if not hasattr(conanfile, "imports"):
        return []
    if not conanfile.imports_folder:
        return []
    mkdir(conanfile.imports_folder)
```

**Comment by burgerkiller79** [comment] 2021-07-08 11:22
We also encountered this issue in our workspace installs. Unfortunately, the change above prevents the import call, as it just returns.

We currently apply a workaround using the following code in conans/client/installer.py, in _handle_node_editable:

I changed lines 515-520 (1.38.0) from:

```
                save(os.path.join(build_folder, BUILD_INFO), TXTGenerator(conanfile).content)
                output.info("Generated %s" % BUILD_INFO)
                # Build step might need DLLs, binaries as protoc to generate source files
                # So execute imports() before build, storing the list of copied_files
                copied_files = run_imports(conanfile)
                report_copied_files(copied_files, output)
```
to:

```
                save(os.path.join(build_folder, BUILD_INFO), TXTGenerator(conanfile).content)
                output.info("Generated %s" % BUILD_INFO)
                # Build step might need DLLs, binaries as protoc to generate source files
                # So execute imports() before build, storing the list of copied_files
                if conanfile.imports_folder is None:
                    # if the imports_folder is None we just use the build_folder
                    conanfile.imports_folder = build_folder
                copied_files = run_imports(conanfile)
                report_copied_files(copied_files, output)
```

To get around this issue, I've also tried to use the new layout() method in the conanfile and specify the folders there. But the current code in _handle_node_editable just overwrites my folders with base_path (lines 466 to 469). 

This prevents out-of-source builds or builds with custom folders for workspaces completely, or am I missing something?

**Comment by bkarpati** [comment] 2021-07-12 15:32
We also encountered this issue while trying to build packages via our conan workspace, getting the exact same error.

#### Environment Details

* Operating System+version: Windows 10
* Conan version: 1.37/1.38
* Python version: 3.7.5
* Default conan configuration and profile

As suggested, reverted back to v1.36 for now as it seems to be unaffected.

**Comment by memsharded** [comment] 2021-07-17 20:03
Hi all, thanks for reporting and following up.

I managed to reproduce this, thanks for the details to help reproducing, and I have submitted a fix for this in https://github.com/conan-io/conan/pull/9281, in case you would like to try it running from my source branch, to make sure it works in your project.


This is targeted for 1.39, but could be considered a regression, please let us know if you can directly jump to 1.39 or need it in previous versions (it is some work to backport and do releases, but we will do it if necessary).

**Comment by burgerkiller79** [comment] 2021-07-17 23:25
Thank you for investigating the issue. Your commit fixes the error, however, in our case we are facing a problem with the build and imports folders.

We are using the old mechanism with layout files specified in a workspace yml. The path for each editable points to the recipe directory and each editable has its layout file.

In the layout files, we specify source_folder as "." (being the same as the one which contains the recipe) and a build_folder relative to the recipe path directory to achieve an out-of-source build, for example "../../Build/{{reference.name}}".

In 1.35.2 the resulting build_folder path was used for placement of the conanbuildinfo, manifest, etc and also for imports commands. This is also the case in the change that I've mentioned above.

With your commit, the build info files and imports are placed into the source_folder next to the recipe and it seems that the build_folder is not used anymore.

Is this intended and if so, how can I adapt the layout files such that the build info files and imports are placed again into the build_folder?

**Comment by burgerkiller79** [comment] 2021-07-18 12:22
So after some more debugging, I think I've narrowed it down to the call to run_imports in installer.py:
[https://github.com/memsharded/conan/blob/ad4dc8610dd23818b10587dcf287d2a702ba79aa/conans/client/installer.py#L522](url)

In 1.35 for example, the call was: `copied_files = run_imports(conanfile, build_folder)`
which you've changed in a later version to `copied_files = run_imports(conanfile)`. 
In the new version, you use the imports_folder as the destination for imports within the `run_imports` function, which by your commit is initialized to the `base_path`.

So what I think could be missing here is to set the imports_folder to the build_folder for the old mechanism.

**Comment by memsharded** [comment] 2021-07-18 20:55
Hi @burgerkiller79 

You are right, I have changed my PR with your suggestion, I hope it would be ok now, please check again. Thanks!

**Comment by burgerkiller79** [comment] 2021-07-18 22:32
Hi @memsharded, it works perfectly.
Thanks a lot :) !

**Closed as completed** 2021-07-19 09:20 UTC
Labels: type: bug

**Comment by bkarpati** [comment] 2021-07-19 11:05
Thanks for picking this up so quickly. I can also confirm that packages can be imported from the workspace once again with the fix.

And to answer your question, moving to `1.39` should be no problem for us.
