### ISSUE TITLE
overcome windows path limit on create

### ISSUE THREAD

**Issue by Gbd199** [conan-io/conan#7487] opened 2020-08-04 07:42 UTC
https://github.com/conan-io/conan/blob/dd258e0aec228cdc59efc46dea624519998d221d/conans/util/files.py#L250-L252

If the path length is above the Windows standard path limit of 260 or so, the rmtree call fails to remove the directory, which later raises an exception when conan tries to create it again to copy the sources into.
After some digging around I found this workaroung for python when it comes to removing long pathed directories, by using the '\\\\?\\' prefix.

So my suggestion is something like that,

```
modified_path = r'\\?\ '.strip() + path if platform.system() == "Windows" else path
shutil.rmtree(modified_path, onerror=_change_permissions) 
```

Please tell me what you think before I submit an official PR.

**Comment by memsharded** [comment] 2020-08-04 07:46
Hi @Gbd199 

It is not clear what you mean. please file a complete issue, detailing what fails, the error message, the files and commands to reproduce.

**Comment by Gbd199** [comment] 2020-08-04 08:07
Adding some of the sources of my 'digging around':
https://stackoverflow.com/questions/28491219/removing-and-listing-directories-above-the-character-limit
https://www.burgaud.com/path-too-long
https://bugs.python.org/issue18199
https://github.com/nerdvegas/rez/issues/436
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#maximum_path_length

**Comment by memsharded** [comment] 2020-08-04 08:18
Hi @Gbd199 

Still not an issue report, please provide:

- Conan version, Python version.
- Conanfiles and conan commands to reproduce your issue
- Output of the commands
- Are you using the ``short_paths`` feature?
- Have you enabled the Windows long paths at the system level?

Thanks

**Comment by Gbd199** [comment] 2020-08-04 10:25
Unfortunately I cannot provide all of those, since my working station has no internet access... 
But I'll try to describe the issue as thoroughly as I can, and how I arrived at it. I hope this will be enough, since the problem is not conan specific, but more of a python trick to cover an edge case.

Conan version: 1.19.1
Python version: 3.5.1

**How I arrived at it, and some errors**
I'm adding the ability in my team to compile using cmake on WSL. CMake has this thing where its build artifacts conatin the directories tree, making the path of the artifacts themselves almost double.
So when I call conan create, it tries to remove the previous build directory before creating it again. The files.py's rmdir function gets called which calls pytohn's native rmtree. rmtree, upon encountring a file with a long path fails with:

> *** WindowsError: [Error 3] The system cannot find the path specified: "some path that is more than 260 characters"

but rmdir ignores this error:
https://github.com/conan-io/conan/blob/dd258e0aec228cdc59efc46dea624519998d221d/conans/util/files.py#L254-L255

So the build directory in the cache is not deleted and conan continues as normal, and when conan tries to create it, it fails:

> [Winerror 183] Cannot create a file when that file already exists: ....
> Error copying sources to build folder

I assume the issue can be reproduced with any build system that creates long pathed artifacts, so it's not specific to my CMake on WSL case.

**To answer your other questions:**
-  I'm not using short_paths, this should solve my issue but I do not want to change the way my team works with conan just because of this issue.
-  Obviosuly enabling the Windows long path feature would solve the issue, but my group policy does not allow that, and I assume other users might have the same issue.

I hope this is enough, and once again making it clear the issue is not in conan but in windows. And if we can apply this trick to prevent users from having to play with the registry just to enable long paths(which is not always possible such as in my case), then why not.

Sincerely yours,
REA

**Comment by memsharded** [comment] 2020-08-04 17:00
Hi @Gbd199 

Thanks very much for your explanation, now it seems that it starts to make more sense.

I am still struggling to understand how you can get long paths if the long paths are not supported by the OS (you confirmed you didn't enabled them). A long path should never hit the ``rmtree`` call, because it is basically impossible to create it in the first place, it will error earlier. Maybe is it something related to the WSL? Does the WSL support long paths internally even if the Windows host doesn't support them? Can you reproduce the case outside of the WSL?

Regarding the ``short_paths``, you might just define it in the recipes, it will not change at all how your team works, and this has only effect in Windows, other OSs simply disregard it. It can also be configured in *conan.conf* ``use_always_short_paths`` without modifying recipes, maybe that helps.

**Comment by Gbd199** [comment] 2020-08-05 06:56
Ok so I've done some testing.
At first I wanted to say that the paths being generated successfuly despite being too long is not that surprising since any tool can apply the trick I mentioned to suprass that limitation.
But, as I tried to run the CMake build using the 'Visual Studio'(MSVC) toolchain instead of the WSL one, it did fail saying it cannot generate/find some files(it didn't say it's due to them being too long pathed but that must have been the reason since it worked just fine in shorter pathed locations).
So your assumption that WSL is the one allowing all that is correct. But as I said before, any build tool or generator could decide to apply some trick to overcome it in many different ways, so we can't put all the blame on WSL.

As for the short_paths, I did not know about the 'use_always_short_paths' so thanks for that, but still I would prefer to overcome the limitation instead of applying configuration changes.

Again, from my prespective this change has no harm and only might help prevent future inconveniences for other users, that might force them to play with the registry, use short_paths or apply tricks of their own.
But I unerstand if you don't think it's an appropriate change since it's not conan's fault but more of a very specific edge case, and since conan does offer ways to overcome the issue. So I'm leaving the decision up to you @memsharded.

**Comment by Gbd199** [comment] 2020-11-08 13:11
@memsharded can you please address the issue? 
It became relevant once again in my team, and as I stated before using short paths or removing the limitation through the registry is not possible for us. The fix is simple and non damaging.
thanks

**Comment by memsharded** [comment] 2020-11-08 18:47
Hi @Gbd199 

We have got some more reports from users lately, that they tried to avoid the path length limitations in Windows, enabling them at the Windows system level, but then consistently failing to work because limitation in the build systems, compilers or other tools that will not work with long paths.

Overall, it seems that you should be using different caches. WSL is a Linux subsystem and you shouldn't use that cache from Windows native. There are different things there, as file locks, database access, that will be OS specific and will have undefined behavior if used from different systems. For example, the short-paths implementation completely relies to be running on Windows, so it can be dangerous to use that feature in that way (and many Conan recipes in ConanCenter rely on this, because they have long paths). The Conan cache is not designed to be shared, not even the same OS, so definitely not between different OSs. I would strongly suggest to consider this.

Also, it seems we are really hitting something similar to Hyrum's law, and recently, no matter what we change, but the likelihood that someone out there is depending on some detail of the previous behavior is reaching 1, and we will be breaking them. I am fine, if you want to submit a exploratory PR and this can be used to discuss with the team and analyze risks, but I cannot guarantee that it will be merged.

**Comment by memsharded** [comment] 2024-09-04 22:32
Conan cache in Conan 2 uses a different system, and ``short_paths`` feature has been completely removed. It is the responsibility of the user to enable long paths at the system level in Windows if there are still paths that will be larger than the standard limit.

Closing this ticket as outdated.

**Closed as not planned by memsharded** 2024-09-04 22:32 UTC
Labels: stage: triaging
