### ISSUE TITLE
[bug] Stacking editable packages don't have a revision

### ISSUE THREAD

**Issue by luke-elwood** [conan-io/conan#6064] opened 2019-11-12 15:22 UTC
Conan version: 1.20.3

I have uploaded a recipe for LibA, LibB and App, where App depends on LibB and LibB requires and build_requires LibA. When making changes to LibA and testing in App I want to set LibA to editable and then set LibB to editable as well so that I can build the changes into LibB and include the changes in App. However when running conan install on App I get 

```
Version ranges solved
    Version range '>=1.0' required by 'conanfile.txt' resolved to 'LibB/1.1.1@elwood/stable' in local cache
    Version range '>=1.0' required by 'LibB/1.1.1@elwood/stable' resolved to 'LibA/1.1.1@elwood/stable' in local cache
    Version range '>=1.0' required by 'LibB/1.1.1@elwood/stable' resolved to 'LibA/1.1.1@elwood/stable' in local cache

conanfile.txt: Installing package
Requirements
    LibA/1.1.1@elwood/stable from user folder - Editable
    LibB/1.1.1@elwood/stable from user folder - Editable
Packages
    LibA/1.1.1@elwood/stable:bd41d6960c74b8b55bb9d01c8d1724907962aa67 - Editable
    LibB/1.1.1@elwood/stable:Package_ID_unknown - Unknown

Traceback (most recent call last):
  File "conan\conans\client\command.py", line 1938, in run
  File "conan\conans\client\command.py", line 478, in install
  File "conan\conans\client\conan_api.py", line 81, in wrapper
  File "conan\conans\client\conan_api.py", line 558, in install
  File "conan\conans\client\manager.py", line 68, in deps_install
  File "conan\conans\client\installer.py", line 308, in install
  File "conan\conans\client\installer.py", line 328, in _build
AssertionError: Installer should receive RREV always

ERROR: Installer should receive RREV always
```
And when I try it with my real packages I am prompted to try to install with ` --build LibB ` which builds a new revision of LibB and puts it in my cache and then fails to finish the install with the same error "missing package for LibB try conan install --build LibB" 

I've included my basic LibA, LibB and App conanfiles here

**Comment by luke-elwood** [comment] 2019-11-12 15:26
```
from conans import ConanFile, tools
import os, platform

class LibA(ConanFile):
    name = "LibA"
    version = "1.1.1"
    build_policy = "missing"
    exports_sources = "src/*"
    settings = "os", "compiler", "arch"
    generators="qmake"

```
```
from conans import ConanFile, tools
import os, platform

class LibB(ConanFile):
	name = "LibB"
	version = "1.1.1"
	build_policy = "missing"
	exports_sources = "src/*"
	settings = "os", "compiler", "arch"
	generators="qmake"

	def build_requirements(self):
		self.build_requires("LibA/[>=1.0]@elwood/stable")

	def requirements(self):
		self.requires("LibA/[>=1.0]@elwood/stable")
```
```
[requires]
LibB/[>=1.0]@elwood/stable
```

conan install works if I create the libraries first in my local cache.
If I then add either one of the libraries editable with ~"conan editable add ../A/ LibA/1.1.1@elwood/stable" the install still works. 
If I then add the second editable reference the install will fail as shown above.

**Comment by evandrocoan** [comment] 2019-12-18 13:30
I also got this error: `ERROR: Installer should receive RREV always`, I fixed it by deleting my `~/.conan` directory. I think it was because I had canceled my conan build once with `Ctrl+C`.

**Comment by jastich** [comment] 2023-09-03 14:11
This still appears to be an issue in 1.60.1

**Comment by memsharded** [comment] 2023-09-03 17:07
Hi all.

Sorry this was not responded back then, sometimes the activity in the repos is so high, that not all tickets can be responded and some fall through the cracks.

I am trying to reproduce the above scenario, but I can't make it fail. This is one of the tests that I am using:
```python
    def test_transitive_editables_build(self):
        c = TestClient()
        libb = textwrap.dedent("""\
            from conan import ConanFile
            class LibB(ConanFile):
                name = "libb"
                version = "0.1"
                build_policy = "missing"
                settings = "os", "compiler", "arch"

                def build_requirements(self):
                    self.build_requires("liba/[>=0.0]")

                def requirements(self):
                    self.requires("liba/[>=0.0]")
            """)
        c.save({"liba/conanfile.py": GenConanfile("liba", "0.1"),
                "libb/conanfile.py": libb,
                "app/conanfile.txt": "[requires]\nlibb/0.1"})
        c.run("editable add liba liba/0.1")
        c.run("editable add libb libb/0.1")
        c.run("install app --build=*")
        print(c.out)
        # Try also with 2 profiles
        c.run("install app -s:b os=Windows --build=*")
        print(c.out)
```
If you could please provide more details to reproduce, that would help.

**Comment by memsharded** [comment] 2023-09-07 10:48
@jastich any feedback? Any hint to be able to reproduce this would be helpful

**Comment by jastich** [comment] 2023-09-08 16:46
Hi @memsharded - Sorry for missing your earlier message.

I'll try to reproduce on my end with some code that I can share.

As a note, I think we see this same `ERROR: Installer should receive RREV always` message when attempting to use an editable package that has not been built.  Not sure if that is a clue.

Additionally - we are using the strictest package ID mode.  Our `conan.conf` contains:
`default_package_id_mode = package_revision_mode`
Could this be related?

**Comment by jastich** [comment] 2023-09-08 16:54
I removed my `default_package_id_mode = package_revision_mode` from `conan.conf` and the error went away.  Restored the configuration and immediately the `conan install` started failing again.

**Comment by jastich** [comment] 2023-09-08 17:05
**/conan-editable/pkgA/conanfile.py**
```python
from conan import ConanFile

class PkgA(ConanFile):
    name = 'pkgA'
    version = '0.1'
    settings = 'os', 'compiler', 'arch'
```

**/conan-editable/pkgB/conanfile.py**
```python
from conan import ConanFile

class PkgB(ConanFile):
    name = 'pkgB'
    version = '0.1'
    settings = 'os', 'compiler', 'arch'
    requires = 'pkgA/0.1@user/test'
```

**/conan-editable/pkgC/conanfile.py**
```python
from conan import ConanFile

class PkgC(ConanFile):
    name = 'pkgC'
    version = '0.1'
    settings = 'os', 'compiler', 'arch'
    requires = 'pkgB/0.1@user/test'
```

Demo (with `default_package_id_mode = package_revision_mode`):

```
/conan-editable/pkgC$ conan --version
Conan version 1.60.1
/conan-editable$ cd pkgA        
/conan-editable/pkgA$ conan editable add . pkgA/0.1@user/test
Reference 'pkgA/0.1@user/test' in editable mode
/conan-editable/pkgA$ cd ../pkgB
/conan-editable/pkgB$ conan editable add . pkgB/0.1@user/test
Reference 'pkgB/0.1@user/test' in editable mode
/conan-editable/pkgB$ cd ../pkgC
/conan-editable/pkgC$ conan install . pkgC/0.1@user/test
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (pkgC/0.1@user/test): Installing package
Requirements
    pkgA/0.1@user/test from user folder - Editable
    pkgB/0.1@user/test from user folder - Editable
Packages
    pkgA/0.1@user/test:e801f43e27415e3a4e75088b12fb8f03fe1e7fdf - Editable
    pkgB/0.1@user/test:Package_ID_unknown - Unknown

Installing (downloading, building) binaries...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/conans/client/command.py", line 2216, in run
    method(args[0][1:])
  File "/usr/local/lib/python3.8/dist-packages/conans/client/command.py", line 523, in install
    info = self._conan.install(path=args.path_or_reference,
  File "/usr/local/lib/python3.8/dist-packages/conans/client/conan_api.py", line 93, in wrapper
    return f(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/conans/client/conan_api.py", line 609, in install
    deps_install(app=self.app,
  File "/usr/local/lib/python3.8/dist-packages/conans/client/manager.py", line 95, in deps_install
    installer.install(deps_graph, remotes, build_modes, update, profile_host, profile_build,
  File "/usr/local/lib/python3.8/dist-packages/conans/client/installer.py", line 317, in install
    self._build(nodes_by_level, keep_build, root_node, profile_host, profile_build,
  File "/usr/local/lib/python3.8/dist-packages/conans/client/installer.py", line 454, in _build
    assert ref.revision is not None, "Installer should receive RREV always"
AssertionError: Installer should receive RREV always

ERROR: Installer should receive RREV always
```

Then commented out `default_package_id_mode` in `conan.conf` and tried again, and it worked:

```
/conan-editable/pkgC$ conan install . pkgC/0.1@user/test
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.py (pkgC/0.1@user/test): Installing package
Requirements
    pkgA/0.1@user/test from user folder - Editable
    pkgB/0.1@user/test from user folder - Editable
Packages
    pkgA/0.1@user/test:e801f43e27415e3a4e75088b12fb8f03fe1e7fdf - Editable
    pkgB/0.1@user/test:98432f60cad9f3e4afff5402201cdd375811237a - Editable

Installing (downloading, building) binaries...
conanfile.py (pkgC/0.1@user/test): Generator txt created conanbuildinfo.txt
conanfile.py (pkgC/0.1@user/test): Aggregating env generators
conanfile.py (pkgC/0.1@user/test): Generated conaninfo.txt
conanfile.py (pkgC/0.1@user/test): Generated graphinfo
```

Is this a bug, or a limitation of the `package_revision_mode`?

**Comment by jastich** [comment] 2023-09-08 17:09
I'll add that a `conan install . pkgB/0.1@user/test` in the `pkgB` directory works properly regardless of the `default_package_id_mode` configuration.

**Comment by memsharded** [comment] 2023-09-11 06:36
Thanks for the feedback.

> default_package_id_mode = package_revision_mode

Yes, it seems this could be the root cause.

As a side recommendation, this mode has been removed in Conan 2.0, no longer supported, because it was considered ill-formed. It tried to solve the lack of binary model while in Conan 1.X, but this was not the right way to approach the problem, and ``package_revision_mode`` introduced a lot of complexities and issues. The summary is more or less:
- A package binary should never have more than 1 ``package_revision``. If it has more than 1 it means that it was unnecessarily re-built from source, and the fact that some C++ builds are not deterministic created a new binary, which is in practice identical to the previous one.
- Cases where ``package_revision_mode`` tried to address changes in the environment are not well formed. If something changes, it has to be known by Conan, via model. Either adding settings, changing settings values, options, or versions in the upstream dependencies.

Conan 2.0 maintains ``package revisions`` for traceability and security (checksums), but no longer implements ``package_revision_mode``. The modes in 2.0 are now more dynamic, differentiating between embedding and non-embedding cases, and using ``full_mode`` (recipe-revision + package-id) as the highest mode.

I'll have a look to the test with that info and let you know, thanks!

**Comment by memsharded** [comment] 2023-09-11 06:51
Submitting a potential fix in https://github.com/conan-io/conan/pull/14711 (can't guarantee that it will be moved forward and merged, because changing things in 1.X is often too risky)

**Comment by jastich** [comment] 2023-09-11 15:27
Thanks so much!

**Comment by czoido** [comment] 2023-09-13 06:17
Closing this as https://github.com/conan-io/conan/pull/14711 was merged and may fix it, but please feel free to reopen if needed.

**Closed by czoido** 2023-09-13 06:17 UTC
Labels: stage: triaging
