### ISSUE TITLE
fPIC

### ISSUE THREAD

**Issue by Halmoni100** [conan-io/conan#14308] opened 2023-07-15 23:47 UTC
### Environment details

* Operating System+version: Ubuntu 22.04
* Compiler+version: gcc 12.1
* Conan version: 2.0.8
* Python version: 3.10

Referring to commit 2af05b5: Why is fPIC automatically disabled when setting shared in the conanfile options?  This was a sneaky change that took a while to discover and presented an instability between Conan versions.

I still need fPIC enabled in order for the cmake toolchain to properly set the fPIC option.

**Comment by memsharded** [comment] 2023-07-17 13:57
Hi @Halmoni100 

Thanks for your report.

> Why is fPIC automatically disabled when setting shared in the conanfile options? This was a sneaky change that took a while to discover and presented an instability between Conan versions.

Conan 2.0.X patch releases main purpose is to stabilize the major Conan 2.0 release, that is a very big one. One of the most important aspects of the stabilization is to make sure that the right defaults are defined. In this regard, the removal of ``fPIC`` option when ``shared=True`` is a massively accepted and spread behavior. All recipes in ConanCenter do it (many hundreds of them, header-only libs won't define the ``shared`` option). It is already part of the ``conan new`` templates, and it is documented as such.

Sorry that it introduced some instability in your update, I'd like to understand better why this happened. When you define ``shared=True``, is it possible to still have ``fPIC=False`` and it will work? How would that be possible? If it is not possible, then maybe the reason is that this is also expected behavior. One of the main purposes of ``options`` is defining a different binary with a different ``package_id``. If an option cannot take more than one value, then the idea is that it shouldn't be an option. 

In Conan 2.0 design, if a recipe needs some flag activated for some reason when ``shared=True``, that would typically be a responsibility of the build system scripts, not Conan. Conan can define the ``CMAKE_POSITION_INDEPENDENT_CODE`` to ``ON`` or ``OFF`` when it is variable, but if for some reason, it is not an input configuration, not something that can really be set by the user (otherwise it doesn't work), then it should be defined inside the ``CMakeLists.txt``. It is also possible that a recipe explicitly patches or provide build system variables (via ``CMakeToolchain`` in ``generate()``) that inject or define that behavior, as a helper if the build system is more difficult to patch.

If you could please provide a bit more detail of the libraries configuration, the build, the CMake build scripts and the set-up, that would help understanding. Like, do you have something hardcoded like ``add_library(mylib STATIC ...)`` that will force a library to be static even if ``shared=True`` (that will define ``BUILD_SHARED_LIBS``)? Thanks!

**Comment by Halmoni100** [comment] 2023-07-17 16:17
I was not aware since I have not looked at recipes in the conancenter.  If the idea is that "if shared=True, then fPIC=True", therefore fPIC should not be set, then I think there should be clear documentation on this behavior.  In my opinion I think having the main program alter expected behavior with hidden custom paths-- esp. without warning-- is not great design from the user's point of view.

**Comment by jcar87** [comment] 2023-07-17 16:51
Hi @Halmoni100 - thank you for your reply.

I believe what you mention is already in our documentation, unless I'm missing something:
https://docs.conan.io/2/reference/conanfile/methods/configure.html?highlight=fpic#configure

> Likewise, for a package containing a library, the fPIC option really only applies when the library is compiled as a static library, but otherwise, the fPIC option doesn’t make sense, so it should be removed:

We're happy to amend or clarify the documentation if this is not sufficiently clear. 

Irrespective of Conan, the notion in other build tools is that shared libraries imply generating position independent code:
* CMake will do so by default for `SHARED` targets, as per their [documentation](https://cmake.org/cmake/help/latest/prop_tgt/POSITION_INDEPENDENT_CODE.html#prop_tgt:POSITION_INDEPENDENT_CODE)  - in these instances, Conan specifying it was rather redundant
* In versions of Ubuntu 16.10 or newer,  the compiler _itself_ (as distributed in the Ubuntu repositories) is set up to produce position independent code by default, rather than requiring a explicit flag, as per https://wiki.ubuntu.com/SecurityTeam/PIE. This is part of overall security measures that other distros have also adopted, and generally in most modern distros I'd expect `-fPIC` to be the default behaviour (also see https://stackoverflow.com/a/41311959) 

I'm surprised you've had issues, given that the defaults outside of Conan on modern distros is to already emit position independent code - if you could provide more details (steps to reproduce and logs with both versions of Conan, before and after the change), I'm happy to look into this

**Comment by Halmoni100** [comment] 2023-07-17 17:13
Thanks for clarifying the default fpic behavior of build tools and compilers, I wasn't totally aware.

The issue is actually about matching the actual hashing behavior of conan with its expected behavior.  The hidden custom path of removing fpic produces a different hash, so I was very confused when this changed and was having build problems when synchronizing conan packages.

Yes I don't think the documentation is very clear given the fact that the behavior is a priori unexpected.

**Comment by Halmoni100** [comment] 2023-07-17 17:16
My personal preference would be to revert to the old expected option behavior and emit an error when (shared == True and fPIC == False)

**Comment by jcar87** [comment] 2023-07-17 19:07
Hi @Halmoni100, thanks for clarifying. I'm afraid doing what you suggest may not be possible either, that is, emit an error when shared=True and fpic is still an option and it still false. On some platforms / cpu architectures this may be perfectly valid, that is, it would create a shared library and that is not relocatable and would be loaded to a fixed location within the process virtual memory space. Thus, it may be perfectly valid to generate such a combination, should the recipe maintainer choose to enable that by retaining the fpic option when shared=True. It may be unusual these days, but it's not an impossible combination

**Comment by stefanpantic-pdftools** [comment] 2023-07-19 14:25
Hi, seems to me that setting `shared=True` now makes `fPIC` not be present in my `conaninfo.txt` (which is breaking builds which try to pull in prebuilt packages).

```
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[options]
codesign=False
shared=True
[requires]
core_libraries/1.0.4@pdftools/latest#025be94add86487ef3790b739b7fe456c5c85beb:f6e0b4a21cf3ae27e0745e6b0279d60caad892d6
freetype/2.13.0#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:86cf2aaf09db1f47714d5719ce286c33bc95f168
lcms/2.14#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a
libheif/1.13.0#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:3cecab561cc0804160711a745ba1cf9629e5887c
libjpeg/9e#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a
libpng/1.6.39#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:fb96bbad889a4e3110d04195c852e29a5445b303
libxml2/2.10.3#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:649a8618ee511e83cccb2b3eb7226ed3874d1df6
openssl/3.1.0#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:ec2659c38f979b21fe2b9d5ac7af1da973e1c558
zlib/1.2.13#ae7d9893156acc4e8d2b0c66026c7d7dfe2ba542:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a

```

even though this is my recipe options:

```
options = {
    "shared": [True, False],
    "fPIC": [True, False],
    "codesign": [True, False],
}
default_options = {
    "shared": True,
    "fPIC": True,
    "codesign": False,
}
```

and `config_options`:
```
def config_options(self):
    if self.settings.os == "Windows":
        del self.options.fPIC
```

and I have `*:fPIC=True` in my profiles so removing that would cause me to have to rebuild 200+ packages.

**Comment by memsharded** [comment] 2023-07-19 14:45
This will be reverted in 2.0.9 asap (likely tomorrow morning), making it opt-in

**Comment by czoido** [comment] 2023-07-19 19:05
Closing this as https://github.com/conan-io/conan/pull/14320 was merged to release branch and is going to be released very soon in 2.0.9

**Closed as completed by czoido** 2023-07-19 19:05 UTC
Labels: stage: triaging

**Comment by czoido** [comment] 2023-07-20 05:57
Hi @Halmoni100, @stefanpantic-pdftools please try 2.0.9 that has already been out for a few hours, things should behave like in 2.0.7, we made this an opt-in using the `implements` class attribute: https://docs.conan.io/2/reference/conanfile/attributes.html#implements

**Comment by stefanpantic-pdftools** [comment] 2023-07-20 09:39
@czoido will test today, I'll let you know if it works as before. Thanks for the quick fix!

**Comment by stefanpantic-pdftools** [comment] 2023-07-20 15:03
@czoido works as before, thanks.

**Comment by Halmoni100** [comment] 2023-07-20 18:05
I'll test it today

**Comment by Halmoni100** [comment] 2023-07-20 18:54
So far no issues I will post again if there is one.  Thanks!
