### ISSUE TITLE
tools.collect_libs() doesn't respect self.cpp_info.libdirs

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#3488] opened 2018-09-05 16:44 UTC
Fedora is putting 64bit libraries in `lib64/` not in `lib/`.

The collect_libs tool should look out for an existing `lib64` directory to collect all libs.

**Comment by Croydon** [comment] 2018-09-05 16:51
I'm starting to realize that this is an issue in several places.

`self.cpp_info.libdirs` might be better to default to `lib, lib64` instead of only `lib`.

Otherwise every single recipe needs this special treatment.

**Comment by Croydon** [comment] 2018-09-05 16:55
Yet another thought: Why is tools.collect_libs not simply using self.cpp_info.libdirs?

**Comment by lasote** [comment] 2018-09-05 19:02
I think this is a duplicate of #3369. Also assigned for take a look for the next release.

**Comment by Croydon** [comment] 2018-09-05 19:09
Seems mostly a duplicate, yes.

But maybe it should be also an issue that tools.collect_libs() doesn't seem to respect self.cpp_info.libdirs?

**Comment by weatherhead99** [comment] 2018-09-05 23:28
as mentioned on the other issue, this isn't a duplicate. At least, it solves the same problem but I believe there are subtle differences in the consequences of these two different ways of solving it.

**Closed** 2018-09-25 08:33 UTC
Labels: in review

**Comment by Croydon** [comment] 2018-10-06 06:59
I don't believe that the changes are totally covering the issue.

`AutoToolsBuildEnvironment` and `tools.collect_libs()` may behave now in the expected way when `self.cpp_info.libdirs` has the correct values, but we still need to set in every single recipe manually the value of `self.cpp_info.libdirs` to at least `lib` and `lib64` to cover operating systems who are putting the libs into lib64. Shouldn't this become the default for `self.cpp_info.libdirs`?

**Comment by danimtb** [comment] 2018-10-06 11:01
Not really, we have fixed the folder outputs of the build helpers to stick them to the Conan default layout. After Conan 1.8 output libdir will be "lib" folder for the `AutoToolsBuildEnvironment` helper, so no need to have lib64 as default in `self.cpp_info.libdirs`

**Comment by Croydon** [comment] 2018-10-06 20:03
> After Conan 1.8 output libdir will be "lib" folder for the AutoToolsBuildEnvironment helper, so no need to have lib64 as default in self.cpp_info.libdirs

This only helps when the AutoToolsBuildEnvironment are used. I run into the problem while building with CMake.

**Comment by weatherhead99** [comment] 2018-10-07 00:39
actually this is almost certainly a property of a "badly written" cmake file (in quotes because such a definition is very hard to come up with). If your cmake buildsystem respects the value of the CMAKE_INSTALL_LIBDIR value, then it will install libraries into the "lib" folder, because conan sets that value when using the cmake build helper. If, however, for example the cmake file uses "include(GNUInstallDirs)" (regarded by many as a good idea, and I'm not totally arguing against that), then on some distros this will cause installation into lib64 anyway. Alternatively, quite a few cmake files (most culprits I've come across are very "windows centric" ones), simply manually override installation directories directly, and these will have to either be patched, or the files (very carefully, respecting issues like rpath, any exported cmake config file locations paths, etc etc etc) moved after installation.

**Comment by danimtb** [comment] 2018-10-07 15:35
@Croydon Note there is also a PR open setting this parameters for the CMake helper aslo https://github.com/conan-io/conan/pull/3599
