### ISSUE TITLE
[feature] Expose `is_apple_os` & `to_apple_arch` in `conan.tools.apple`

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#11865] opened 2022-08-14 18:13 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

`is_apple_os` is widely used in conan-center-index (almost 10% of recipes), it prevents their full migration to conan v2.

**Comment by lasote** [comment] 2022-08-18 06:26
The usage of `to_apple_arch` is way lower than `is_apple_os`, but we have indeed assigned to `1.52` to take a look at it.

**Comment by pgeler** [comment] 2022-08-19 11:22
wish is_apple_os can be addressed differently than breaking those 10% 🤦

**Comment by jcar87** [comment] 2022-08-19 11:27
> wish is_apple_os can be addressed differently than breaking those 10% 🤦

Hi @pgeler  - we are making every effort to prevent breakages for both Conan and Conan Center users during the staggered transition to Conan 2. If you could kindly provide a report of issues caused by the the lack of `is_apple_os` in the `conan.tools.apple`, I'll make sure to address this swiftly.

**Comment by pgeler** [comment] 2022-08-19 11:40
@jcar87 it did break packages in 1.51.3 this one is an example https://github.com/conan-io/conan-center-index/pull/12335, I was struggling around last night

**Comment by jcar87** [comment] 2022-08-19 12:57
Hi @pgeler - thank you. Apologies for the inconvenience, after noticing the issue with a small number of recipes we have moved to correct this - it should now work properly even on Conan 1.51.3. Please let us know if this is not the case.

**Comment by memsharded** [comment] 2022-08-24 08:57
https://github.com/conan-io/conan/pull/11915 merged, will be in 1.52

**Closed as completed** 2022-08-24 08:57 UTC
