### ISSUE TITLE
[question] cmake_find_package_multi: folder for xxx-config.cmake files 

### ISSUE THREAD

**Issue by alex-700** [conan-io/conan#8643] opened 2021-03-13 17:53 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

When somebody uses `cmake_find_package_multi` generator `conan` generates several (for every dependency) `.cmake` files and put them into the build directory. Is there some option to change the destination folder for these files from `${CMAKE_BINARY_DIR}` to some custom one (e.g. `${CMAKE_BINARY_DIR}/conan-cmake-configs`)?

If there is no such option, this issue can be perceived like a [feature] one. :)

Thanks in advance!

**Comment by memsharded** [comment] 2021-03-14 20:45
Hi @alex-700 

Have you tried the ``conan instal ... --install-folder=somefolder``? That will put those files inside such folder.
The issue is that this is only ok as a consumer, for local development. If you want later to create a package for it, then by default the generated files will be in a different location, and that will be problematic.

The good news is that we are working on that. @lasote is building some proposal like https://github.com/conan-io/conan/pull/8554, that could define a ``generators_folder`` specifically to define this.

**Comment by memsharded** [comment] 2023-08-25 10:50
This issue was reporting the legacy CMake integration, which has been superseded by the new one in Conan 1.X https://docs.conan.io/1/reference/conanfile/tools.html, and removed in Conan 2.0: https://docs.conan.io/2/reference/tools/cmake.html. Closing this ticket as outdated.

Please update to use the modern CMake integration, and please don't hesitate to open new tickets as necessary. Thanks!

**Closed as not planned by memsharded** 2023-08-25 10:50 UTC
Labels: priority: low, type: feature, stage: in-progress, complex: medium, component: Build
