### ISSUE TITLE
[question] How to tell conan to just use the prebuilt tool, not try to build it?

### ISSUE THREAD

**Issue by Sebastian-Setzer** [conan-io/conan#11570] opened 2022-07-04 15:37 UTC
I've got a conanfile.txt that contains these lines:
```
[tool_requires]
cmake/3.23.2
```
and there exists a prebuilt package here: https://conan.io/center/cmake
Which is available for Windows, built with Visual Studio 15.
cmake/3.23.2:0a420ff5c47119e668867cdb51baff0eca1fdb68

When I run `conan install .. -pr:h=default_host -pr:b=default`, conan tries to build it, instead of using the prebuilt one. I assume that is because my default compiler is not Visual Studio 15, so it doesn't match. Building fails with this error message:
```
cmake requires a compiler that supports at least C++11
```
which I could probably fix by adding the right flags to turn on C++11 support. But I don't really want to do that, I'd like to use the prebuilt package instead.

How can I tell conan: "_For tools, I don't care which compiler it was built with, if there is a prebuilt one for Windows x86_64, use it!_"?

I was hoping that commenting out the compiler parts in default_host would do the trick, but it didn't:
```
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
#compiler=Visual Studio
#compiler.version=10
#build_type=Release
[options]
[build_requires]
[env]
```

**Comment by Sebastian-Setzer** [comment] 2022-07-04 15:50
Would the `cmake` package creator have to follow the advice here: https://docs.conan.io/en/latest/creating_packages/existing_binaries.html#downloading-and-packaging-pre-built-binaries

But as a consumer of the package, I've got no chance?

**Comment by jcar87** [comment] 2022-07-04 16:24
Hi @Sebastian-Setzer  - thanks for raising this issue. We are currently investigating this as there could be an issue with the CMake recipe itself.

In the meantime, and to answer your questions and hopefully unblock you:

* Conan 2 will support defining custom compatibility plugins, see [here](https://docs.conan.io/en/2.0/whatsnew.html?highlight=compatibility#compatibility-py), which I believe could cover the use case you are describing of telling Conan to follow custom compatibility rules.

* In your particular case, with Conan 1.x, you can add a line in _build_ profile to override the compiler version when requesting `cmake` as a `tool_requires`, for example:
```
cmake:compiler.version=15
```

Please note that it would have to be the _build_ profile to contain this override, rather than the host one, you can read more about the contexts [here](https://docs.conan.io/en/1.46/devtools/create_installer_packages.html#using-the-tool-packages-in-other-recipes).

In the meantime, will continue investigating a potential issue with the CMake recipe itself, thanks for reporting this!

**Comment by Sebastian-Setzer** [comment] 2022-07-05 16:24
Thanks, that helped a lot - I even learned something (howto scope profile settings to a package). It works now.
I only had to add another line: `cmake:compiler.runtime=MT`. Easy to find by checking with what the precompiled package was built.

Then, I had the same issue with ninja (because my default profile now didn't have any compiler related settings anymore, except for cmake).
But there, it's a different matter. Slightly nicer, but more surprising: I need to configure the compiler in the profile, and I must configure valid values (conan even tells me which values are valid) ... but then those values don't seem to matter at all.
I could even configure `apple-clang` and I still got:
`ninja/1.11.0: Already installed!`

> In the meantime, will continue investigating a potential issue with the CMake recipe itself,

Looking forward to the solution... maybe I can learn something for my own recipes.

**Comment by Sebastian-Setzer** [comment] 2022-07-12 10:18
When I call `conan create ... --build`, this as well forces a rebuild of the tools. So then, I've got the same problem again, that building cmake fails (because I haven't got things set up for that).

Does that mean that I should try to avoid `--build` and use `--build=outdated`, which does what I want provided I change the recipe everytime anything in my package changes - which I should do anyway, because it needs a new version number?

**Comment by memsharded** [comment] 2022-07-12 12:43
Hi @Sebastian-Setzer 

> When I call conan create ... --build, this as well forces a rebuild of the tools

Yes, in general, rebuilding all the dependencies is not expected. ``--build`` (or ``--build=*``) should probably be used only in extreme cases. The recommendation would be:

- Use the default, ``conan create`` that will only build the current package. It is assumed that pre-compiled binaries for the dependencies should be there. In production environments with your own packages, this should be the default, as those binaries should have been created by CI already
- For some cases, where some binaries might be missing, for example if using packages from ConanCenter, but using a different configuration, the recommended flow could be:
   - Use ``conan install .... --build=missing`` to install the dependencies in your project first. 
   - Build locally (as a consumer only), check that everything works. 
   - When everything ready, check the package creation with ``conan create``. No need to specify build packages, because they were built before
- The ``outdated`` only makes sense when not using revisions, and it has been removed in Conan 2.0, probably shouldn't be used anymore.

**Comment by WernerWessely** [comment] 2022-07-12 13:07
I am faced with a similar, maybe quite straight forward problem and I just cant figure it out:
I have a project P which has normal library 'requires' A and B. It also has a 'build_requires' of tool X. A and B export all their sources at creation so they can be built anytime locally with the 'conan install --build ...' command. I would like for the developer working on P to simply be able to build his project and all its (transitive) library 'requires' for when he needs to debug without having to list them all in the install command.

The problem is that if he simply does something like 'conan install --build=*...' all the build_requires, like tool X will also be built which is not ideal. I could perhaps try to make sure that all tool recipes set the build_policy to never but that would not be possible for 3 party tools which we dont package ourselves.

Any idea what would be the best workflow to simply say please build the whole project from source except the build_requires? Surely this must be a use case that comes up quite a bit? Thanks a lot for all the work you guys do on Conan, its really an amazing tool.

**Comment by memsharded** [comment] 2022-07-12 15:40
Thanks for your kind words @WernerWessely 

The question would be: why do you want to rebuild all your "host" dependencies, but not the "build" ones? Why would you like to rebuild all your "host" dependencies anyway? Many of the Conan features are oriented to avoiding unnecessary rebuilds. If you have app->libd->libc->libb->liba, and only a change in libc happens, then it is not necessary to rebuild libb and liba.

Even more, depending on the change of libc, it might not be necessary to build at all libd, for example. Conan does have some model for this, and Conan 2.0 will have even more, allowing very efficient "build only what is really necessary to rebuild" (see for example https://www.youtube.com/watch?v=kKGglzm5ous)

The problem with unnecessary rebuilds is not only the extra build time. But the artifacts might be slightly different (because C++ builds not always deterministic), and they will waste some server storage, create a new package revision that is really unwanted and won't work nicely with some other constraints as locking, or the now not recommended ``package_revision_mode``.

The ``build_policy = "never"`` is not a good idea, that is mostly for packaging pre-compiled binaries, but it won't work nicely for this use case.

Regarding your question, I am afraid that is there is no way of specifying "rebuild everything but not the build-requires". If for some exceptional case I had to workaround this, I guess I would try something like, ``--build=zlib* --build=cascade``. Or maybe, as the ``tool_requires`` are typically very few of them, specify the negation, something like ``--build=* --build=!cmake* --build=!mytoolchain``

**Comment by WernerWessely** [comment] 2022-07-13 04:28
@memsharded Mmm the usecase of looking for the source of a bug in all your host deps and thus wanting to conveniently build them all in the cache for debugging does not seem exceptional to me. But alright, I will find a solution based on whats possible. Thanks!

**Comment by memsharded** [comment] 2022-07-13 11:34
> Mmm the usecase of looking for the source of a bug in all your host deps and thus wanting to conveniently build them all in the cache for debugging does not seem exceptional to me. But alright, I will find a solution based on whats possible. Thanks!

That might be an interesting use case, but based on user feedback so far, our understanding was that the users didn't want to build all of them, because many times that is intractable, takes many hours. And they start doing a explicit ``--build=pkg1``, when they need to step into pkg1 debugging, and they will keep repeating that for every dependency they need to debug further upstream in the dependencies. Maybe for relatively small projects that build in a reasonable time, it could make sense.


I'd like to comment, regarding the debugging experience, and for "print" driven debugging lovers (I like it), it might be interesting the use of ``editable`` packages. With the new build system integrations like CMakeToolchain, CMakeDeps, and ``layout()``, having packages in ``editable`` mode is easier, and you can debug locally the dependency as well, in a normal development experience.

**Comment by WernerWessely** [comment] 2022-07-14 08:46
> > Mmm the usecase of looking for the source of a bug in all your host deps and thus wanting to conveniently build them all in the cache for debugging does not seem exceptional to me. But alright, I will find a solution based on whats possible. Thanks!
> 
> That might be an interesting use case, but based on user feedback so far, our understanding was that the users didn't want to build all of them, because many times that is intractable, takes many hours. And they start doing a explicit `--build=pkg1`, when they need to step into pkg1 debugging, and they will keep repeating that for every dependency they need to debug further upstream in the dependencies. Maybe for relatively small projects that build in a reasonable time, it could make sense.
> 
> I'd like to comment, regarding the debugging experience, and for "print" driven debugging lovers (I like it), it might be interesting the use of `editable` packages. With the new build system integrations like CMakeToolchain, CMakeDeps, and `layout()`, having packages in `editable` mode is easier, and you can debug locally the dependency as well, in a normal development experience.

Yeah, the way I will recommend it to our devs is basically if you want to debug your host deps:
1) Find which ones you have for your debug config:
`conan info -n None -pr profile-dbg .`
2) Install and build the ones you need with e.g.:
`conan install -pr profile-dbg -b libssh libssh/0.8.9@`
(or put into editable mode)
3) Build and debug

Looking forward to what kind of cooler workflows will perhaps arrive with Conan 2!

**Comment by memsharded** [comment] 2022-07-14 09:01
Great, I think this sounds reasonable at the moment.

I am closing this questions as responded, but don't hesitate to re-open or create a new one with further questions or feedback if necessary!

**Closed as completed by memsharded** 2022-07-14 09:01 UTC
Labels: stage: triaging
