### ISSUE TITLE
[question] git.get_url_and_commit() contains credentials

### ISSUE THREAD

**Issue by SamsonBox** [conan-io/conan#13404] opened 2023-03-10 07:55 UTC
### What is your question?

Hi! I have a question regarding the `git.get_url_and_commit()` function. We are going to migrate our own packages to conan 2.0 and we used the conan scm attribute to capture the repository url and revision. For the 2.0 packages we are going to use the `git.get_url_and_commit()` functions which works fine for local builds. But we use a GitLab-Ci to build and deploy a certain version. Within the CI-run the `git.get_url_and_commit()` function now extracts the URL with the credentials of the acount (running the job) in it (e.g. https://user:password@mygitlabserver.mydomain.com). So now we have to remove the credentials in every recipe, but  I think this should be solved in the  `git.get_url_and_commit()` function. I think nobody will publish credentials in a conan packet.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-03-10 08:18
Hi @SamsonBox 

Thanks for your report.
I think this might be a duplicate of https://github.com/conan-io/conan/issues/13338?

Please have a look and if so, we can close this ticket and follow that one (it has a "look into", which means preliminary investigatation, for next 2.0.2)

**Comment by SamsonBox** [comment] 2023-03-10 08:50
@memsharded, yes. You are right. The proposed solution, to provided an option to strip out credentials out of the box, is exaclty what we would need. Sorry for the duplicate issiue. Shall I close it?

**Comment by memsharded** [comment] 2023-03-10 09:05
No prob! Lets follow up in the other ticket.

**Closed as completed by memsharded** 2023-03-10 09:05 UTC
Labels: duplicate
