### ISSUE TITLE
[bug] MSBuild calls devenv by default, even if not available

### ISSUE THREAD

**Issue by UnderSampled** [conan-io/conan#7606] opened 2020-08-27 20:25 UTC
### Environment Details
  * Operating System+version: Windows Server 2019
  * Compiler+version: Visual Studio 2017 Build Tools 15.9.2.0
  * Conan version: 
  * Python version: 3.7.0

### Steps to reproduce
On a system with only Visual Studio build tools installed, run a Conan build using the MSBuild build helper using the default setting for upgrade_project (Defaults to true)

Because Visual Studio build tools does not install devenv, this setting will fail the build. Disabling the setting (explicitly setting it to false) allows it to succeed.

**Comment by memsharded** [comment] 2020-08-28 08:54
Hi @UnderSampled 

I am not sure this is a bug, but instead by design. Conan tries to provide a consistent behavior. Running one thing or another different one based on the existence of a tool in the system is a bit fragile, and this is the reason the default behavior assumes that it exists and will error otherwise, and there is an opt-out to not use it.

We are now starting a new approach of integrating with the build systems, using toolchain files and trying to simplify what the build helpers do. I agree that maybe it makes sense to change the default, and only use ``/devenv upgrade`` when users explicitly opt in to use it. But we cannot change this default now in the current build helper, it will change in the new toolchain one.

**Comment by memsharded** [comment] 2020-09-21 20:45
This is the ongoing work around the toolchain for MSBuild: https://github.com/conan-io/conan/pull/7674

The build helper is not addressed yet, but it will be in following iterations. It will not run /devenv by default, unless explicitly requested. If it is explicitly requested, then, /devenv must be installed in the system.

**Comment by memsharded** [comment] 2020-10-26 13:17
Hi @UnderSampled 

The new helper that is going to be released together with the toolchain will not call devenv by default: https://github.com/conan-io/conan/pull/7941
In fact it is not even implemented yet, it might be added later (opt-in? opt-out?) depending on users feedback.

**Closed as completed** 2020-10-30 00:05 UTC
Labels: stage: queue, stage: triaging, priority: medium, complex: medium, component: Build
