### ISSUE TITLE
[bug] [windows] virtualrunenv: The input line is too long

### ISSUE THREAD

**Issue by Artalus** [conan-io/conan#9565] opened 2021-09-08 20:36 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows
  * Compiler+version: MSVC 142
  * Conan version: 1.34.1
  * Python version: 3.8

### Steps to reproduce (Include if Applicable)
Use conanfile with lots of dependencies.
<details>
  <summary>*conanfile.txt*</summary>

```
[requires]
glib/2.68.3
openssl/1.1.1i

aeron/1.31.2
ags/6.0
alac/cci.20121212
andreasbuhr-cppcoro/cci.20210113
argtable3/3.2.0
arcus/4.9.1
argtable2/2.13
arrow/2.0.0
amqp-cpp/4.3.11
atk/2.36.0
assimp/5.0.1
aws-c-event-stream/0.1.5
aws-c-common/0.4.25
backward-cpp/1.5
argon2/20190702
baical-p7/5.6
bdwgc/8.0.4
bliss/0.73
aws-sdk-cpp/1.8.130
box2d/2.4.1
aws-checksums/0.1.5
asmjit/cci.20210306
butteraugli/cci.20190319
asyncplusplus/1.1
botan/2.18.1
brotli/1.0.9
boost/1.76.0
capstone/4.0.2
cargs/1.0.0
c-ares/1.17.1
cgns/3.4.1
chipmunk2d/7.0.3
cassandra-cpp-driver/2.15.3
celero/2.6.0
ccfits/2.5
cgltf/1.9
cfitsio/3.490
cmp/19
ceres-solver/2.0.0
cjson/1.7.14
charls/2.1.0
civetweb/1.14
clipper/6.4.2
cppbenchmark/cci.20201029
cnpy/cci.20180601
cppserver/1.0.0.0
cpp-optparse/cci.20171104
corrade/2020.06
cpu_features/0.6.0
cppunit/1.15.1
cppcommon/cci.20201104
cunit/2.1.3
crc32c/1.1.1
cspice/0066
cpprestsdk/2.10.18
cwalk/1.2.5
cryptopp/8.5.0
dav1d/0.8.1
date/3.0.1
dcmtk/3.6.6
duktape/2.5.0
double-conversion/3.1.5
cpr/1.6.2
docopt.cpp/0.6.3
```  
</details>

Install binaries for that conanfile:
```
> conan install conanfile.txt -if conan-vc142 -s os=Windows -s compiler.version=16 -s build_type=Release -o *:shared=True -g virtualrunenv -r conan-center
```

Call created environment bat:
```
> conan-vc142/activate_run.bat
The input line is too long.
```

---

The problem is in `PATH=` env variable that gets filled with paths to every `bin/` directory containing `.dll` files from installed libraries. `activate_run.ps1` does not have this problem:

```
PS Y:\> .\conan-vc142\activate_run.ps1
(conanrunenv) PS Y:\>
```

**Comment by memsharded** [comment] 2021-09-08 22:41
Yes, this is right. Windows has so many annoying limitations:

- The env-var lenght is limited to 32k chars in theory, but all env-vars together.
- The ``set VAR=VALUE`` also has a limit in size
- The command line also has a character limit.
- The PATH env-var seems that might have some extra specific limits

There are some ongoing things that will help with this, like the cache of 2.0 that will always have shorter paths.
We could also define or use some other (short) variable, like CNC (ConanCache) that could be used to shorten the variable.

But still, when there are so many dependencies, and all of them must contribute their folder to the PATH so .dlls are found, it seems that the limit will be eventually hit.


Anyone, any idea how this issue could be solved/mitigated?

**Comment by Artalus** [comment] 2021-09-09 08:02
> The env-var lenght is limited to 32k chars in theory, but all env-vars together.

This is sad :(
  The `environment_run.bat.env` from example above contains line `PATH=Y:\.conan\data\aeron\1.31.2\_\_\package\23e7c7685d71ba680d0dc79f577c375c54f37a06\bin;......;%PATH%` of length 23,517 chars alone...
  If there is sum-total  limit though, it might be useful to generate only `PATH=` for Windows: currently there are also `DYLD_LIBRARY_PATH` and `LD_LIBRARY_PATH` in said file too.

`short_paths` helps to an extent. With this option, the above `environment_run.bat.env` shortens to `PATH=Y:\.conan\a3e9f9\1\bin;......%PATH%` of length 6,542. However in some CI setups the short paths will become longer, see #7995.

If we decide to not rely on Batch alone, then theoretically Conan could also generate some `activate.py`, whose purpose would be to run something like:
```python
os.environ['PATH'] = 'Y:\.conan\......' + os.environ['PATH']
os.system("cmd")
```
Then `activate.bat` would call said py file, and inside it's newly created cmd you could run your build systems, creating a process tree like:
```
cmd.exe
+ python.exe activate.py
  + cmd.exe
    + cmake.exe
```

I also believe that Conan should at least warn the user with Bold Red Letters during generation, "_Your `PATH=` variable is longer than 8k characters, `activate.bat` won't work, consider using `activate.ps1` or `short_paths` feature_". Just in case.

**Comment by memsharded** [comment] 2021-09-09 08:13
I agree, that could be at least some quick wins:

- Avoid creation of the other variables in Windows
- Warn if length is above a threshold

I'd also encourage to test and validate this in the new ``VirtualBuildEnv``, ``VirtualRunEnv`` and ``Environment`` utilities. They are still experimental, but working great and they will replace the others (while the others there is risk of breaking things if we start changing things at this low level).

**Comment by Artalus** [comment] 2021-09-09 08:22
I kinda feel this trio is slightly out of discussed scope - they are used in package recipes; there Python rules instead of Batch and the main problem (`set` / `cmd` input limitation) seemingly does not exist at all. My consideration was about the generators used by developers in their CLI workflow.

Am I missing something? We've been kinda frozen in stasis with regards to Conan developments for past couple of years :)

**Comment by memsharded** [comment] 2021-09-09 08:31
I am not sure what you mean. I was suggesting that if we are going to do potentially breaking changes, we'd better try them first in these new generators, which will be the one replacing the others in Conan 2.0. These are generators that users can already use in CLI workflow with ``conan install . -g VirtualBuildEnv``, and its usage can be enabled by default with ``tools.env.virtualenv:auto_use=True`` new ``[conf]`` item.

**Comment by Artalus** [comment] 2021-09-09 08:50
Oops! Sorry, search got me to [VirtualRunEnv](https://docs.conan.io/en/latest/reference/conanfile/tools/env/virtualrunenv.html?highlight=virtualrunenv) page and I missed the line about "_calling conan install will generate a conanrunenv .bat or .sh script_" - so I thought this was only a `conan.tools.env.VirtualRunEnv` class to be used in recipes, without bindings to CLI. ^^"

**Comment by SSE4** [comment] 2021-09-09 11:37
few things we may try to improve (e.g. delay failure):

1. use intermediate variables to shorter the command line, e.g. instead of:
```
PATH=Y:\.conan\data\aeron\1.31.2\_\_\package\23e7c7685d71ba680d0dc79f577c375c54f37a06\bin;......;%PATH%
```
generate something like:
```
PATH=%AERON_BIN%;......;%PATH%
```

2. use MS-DOS [8.3 names](https://en.wikipedia.org/wiki/8.3_filename), e.g.:
```
PATH=Y:\.conan\data\aeron\1.31.2\_\_\package\23e7c7~1\bin;......;%PATH%
```

3. make local symlinks/junctions for the long directories (similar to short paths)

system-wide solution - `LongPathsEnabled` registry key, see https://github.com/python/cpython/commit/beb0f1d425458ef9cb18a4eb2b4ffe87aeb2662b

**Comment by memsharded** [comment] 2021-10-05 11:11
https://github.com/conan-io/conan/pull/9678 this a first step to start reducing this issue impact. Just a start, we will keep trying other strategies to keep reducing this.

**Comment by tapia** [comment] 2021-10-20 10:14
@Artalus have you tried Conan 1.41, which includes the fix that @memsharded mentioned? Did it solve your problem?

**Comment by Artalus** [comment] 2021-10-21 16:43
I have not yet, but the mentioned fix was simply about removing extra envvars. The original problem comes from a single envvar being too long - AFAIK this is yet to be changed.

**Comment by tapia** [comment] 2021-11-17 17:13
@Artalus I've been looking further into this (thanks @memsharded for the test!), and it doesn't have an easy fix. I tried composing the PATH variable through intermediate variables, as @SSE4 suggested, but windows "replaces" the intermediate variables with their content, so I get the `The input line is too long` error no matter how I compose `%PATH%`. There's not a lot we can do about it in the short term.

A way to try to override the problem is using a shorter Conan cache directory path. Yours is already pretty short (`Y:\.conan\`), but try making it even shorter (`Y:\.c\` or even `Y:\c\` maybe?). It won't really solve the problem, but maybe it's enough for you.

It looks that powershell doesn't have this environment variables length problem, so I'm going to see if we can go that way, and I'll keep you posted.

**Comment by Artalus** [comment] 2021-11-18 08:14
TY for looking into this. FWIW, I think PowerShell simply does not have that limitation at all, because it uses other mechanisms than `set X=...` to setup envvars. For us the real solution was "abandon cmd, use powershell, it's 2021 ffs".

In the thread above I theorized about providing additional generator that could've setup environment through python - via `os.environ['PATH'] += ...` for example - and then launch a new instance of `cmd.exe` with all variables available. This seems to me like a useful feature for those who do not have PowerShell at their disposal or would like to stay within cmd's boundaries. But if for example someone calls another `set PATH=%PATH%;...` after using `activate.bat`, it would in no way alleviate their pain, since the PATH is already too long.

Another approach would be to ditch whole "`virtualenv` populates PATH with multiple paths" approach altogether, and instead invent some `deploy_virtualenv` generator - that would copy or symlink all the DLLs into a single directory, and then append only said directory to PATH.

But my tastes are rather singular, and other users might not understand such features - so maybe it is worth to conduct some research first :)

**Comment by tapia** [comment] 2021-11-30 11:53
I've updated the virtualenv generators to create a powershell script, as well as the .bat script (#10049 will be available in the 1.43 release).

Now we have to figure out the best way to use this in the future. PowerShell scripts can't be the default, because it's possible that the Windows security settings won't allow users to execute powershell scripts.

**Comment by memsharded** [comment] 2022-04-22 16:12
I have bad news. We thought that we were hitting the .bat limits even before the PATH length limit. 
After moving https://github.com/conan-io/conan/pull/10037 to the new ``powershell`` environment generator, it happens that it is still failing. The information still overflows for env-vars too long, even if using powershell (check ``-c tools.env.virtualenv:powershell=True`` in the test).

So this cannot be solved by the ``VirtualRunEnv`` only, but the information that is added to env-vars has to be kept short.
Conan 2.0 will help to this with different approaches:

- The cache paths will be shorter in general, typically much shorter, around 50% or 30% of the Conan 1.X paths. That will reduce many cases
- The ``visibility`` over environment that is propagated to the downstream consumer will also be much better. Isolation of dependencies hidden above a shared library for example will not necessarily propagate their ``bin`` directories to the consumer, if they aren't shared libraries too. That can reduce in practice a lot the length of the paths.
- The new deployers mechanism, with ``--deploy=mydeployer`` might be able to help for some cases, and recollection of DLLs, for example, will be something straightforward with deployers, which might be used as an alternative for those cases. Also the ``copy()`` tool has been made that it can be used in ``generate()`` method if an explicit copy of dependencies is desired, directly in the recipes.

It seems that from our side we cannot do more for this problem, it is an intrinsic limitation of environment variables in Windows OS, so I think this issue can be closed, and we will wait to see the final impact in 2.0 after its goes live, and how the above things mitigate this.

**Comment by memsharded** [comment] 2022-04-25 12:12
https://github.com/conan-io/conan/pull/10037 has been merged. As there is nothing else we can do about this issue, I am closing this at the moment, and as said above, Conan 2.0 will most likely alleviate this further.

**Closed as completed by memsharded** 2022-04-25 12:12 UTC
Labels: type: look into, stage: triaging, whiteboard
