### ISSUE TITLE
Problem with resolving OpenSSL version using version ranges mechanism

### ISSUE THREAD

**Issue by mnowy** [conan-io/conan#1791] opened 2017-09-22 16:33 UTC
I have recently updated conan from version 0.24 to 0.27
Now I have problem with downloading OpenSSL package using version ranges [~=1.0.2] mechanism.
Here is example of my conanfile.py:
```
from conans import ConanFile

class Test(ConanFile):
    requires = "OpenSSL/[~=1.0.2]@conan/stable"
    generators = "qmake", "txt"
    default_options = "OpenSSL:shared=True"

    settings = {"os": ["Windows", "Linux", "Macos"],
                "compiler": {"Visual Studio": {"version": None, "runtime": None},
                            "gcc": {"version": None},
                            "apple-clang": {"version": None}},
                "arch": ["x86", "x86_64"],
                "build_type": ["Release", "Debug"]}
```

After calling command: `conan install` I receive an error: `ERROR: The version in '~=1.0.2' from requirement 'OpenSSL/[~=1.0.2]@conan/stable' could not be resolved`

On conan 0.24 everything was running fine. Were there any changes with version ranges mechanism? I've checked with changelog and I couldn't find anything about that.

**Comment by zacklj89** [comment] 2017-09-22 18:42
I recently updated from 0.26.1 to 0.27 as well, and our projects cannot resolve some version ranges with wildcards. When we downgrade to 0.26.1, everything works as intended. 

Our packages were created using >0.25, so I'm confused as to what is happening as well.

**Comment by mpdelbuono** [comment] 2017-09-22 19:51
There was a change due to #1743 - I wonder if this is related

**Comment by mpdelbuono** [comment] 2017-09-22 20:02
It looks like conan-center's version of OpenSSL is 1.0.2l as opposed to 1.0.2. This doesn't seem to fit semver specification. Unfortunately I'm not really sure what the right way to rectify this is. 1.0.2-l seems wrong because it's not prerelease, and 1.0.2+l is wrong because the "l" would not affect the version selection. 

I think this fits into a weird area of "you want to use semver semantics but your package doesn't follow the semver specification". It was nice that conan was able to deduce the appropriate version before, but it seems like it was probably closer to "undefined behavior that was working well".

Probably the "correct" thing to do is to define package_id() such that the appropriate version is selected. This is unfortunate because consumers all have to have this implemented independently. Perhaps it would be nice if a package could specify how its version scheme works, so that it can be used by dependent packages (rather than the dependent packages all implementing their own logic).

**Comment by memsharded** [comment] 2017-09-22 20:06
Yes, conan does not implement version range checking, but relies on an external third party. Conan 0.27 has upgraded to the third-party library ``node-semver==0.2.0`` version which solved several issues, and updated compliance with the current semver specification. Some expressions that could obtain results were actually not according to the specification, so indeed the update might have changed behavior regarding this.

I would need if you could send me the version ranges expressions, as well as the versions they should match, I will try to add them to the test suite and analyze what could be happening and how to fix. 

@mnowy in the case of ``OpenSSL/[~1.0.2]`` it might be a bit weird, as you are specifying the full x.y.z version, and the "approx" might provide less digits I think (have to check it)

Yes, I agree with @mpdelbuono analysis, I think it was more in the area of "lucky undefined behavior". Maybe other options are also possible, like dependency overriding (it is not necessary to specify a range of versions, as the new versions can always be specified by the downstream consumer, with "override")

cc @lasote

**Comment by zacklj89** [comment] 2017-09-22 20:50
Our packages are deployed in a manner of appending a build number to them. The packages worked before by having something in the conanfile like "package/[1.0.*]" and the version of the package on artifactory would be 1.0.1-buildnumber. I don't think that this was following semver originally. If we want to continue with this workflow, should we just lock down conan to 0.26.1?

**Comment by mpdelbuono** [comment] 2017-09-22 21:13
I'm surprised to hear that 1.0.1-nnn isn't working for you. In fact, I myself intend to move to that format as well. There's even [a test case for that format](https://github.com/conan-io/conan/blob/develop/conans/test/model/version_ranges_test.py#L25). What's happening when you use that format? Is there also a 1.0.1 (without a -buildnumber)? If so, that version would be selected over 1.0.1-nnn because the - indicates prerelease and the lack of a - indicates stable.

**Comment by zacklj89** [comment] 2017-09-22 21:31
We only have packages with build numbers appended to them. There aren't any "stable" packages on the remote, only packages in the form of X.Y.Z-nnn.

The test cases look like there was already a stable package released, and semver resolved the package to be the stable one. In our case, there is no stable one. Also, the other test cases have a letter appended, then a number. If we need to start deploying packages in the form X.Y.Z-a.nnnn, that can be easily done.

**Comment by mpdelbuono** [comment] 2017-09-22 22:10
Interesting. It looks like the * operator (as well as several others) aren't behaving the way I would expect. This is probably also in the third-party library. I added some tests in my fork in  3a66cdc2f013b3dcba7e1ea260348a7f9cf22980 - they are currently failing. I think that this describes your expected behavior, right @zacklj89 ?

**Comment by memsharded** [comment] 2017-09-22 22:16
Remember that pre-releases are not included in the ranges by the specification, so it is necessary to specify ``1.0.2-`` with the trailing slash, to include pre-releases.

**Comment by zacklj89** [comment] 2017-09-22 22:36
@mpdelbuono that looks like the behavior I'm expecting. @memsharded In our conanfile we tried different permutations of operators for ranges, including 0.1.0-*, and they all seem to not be able to resolve the version.

**Comment by mnowy** [comment] 2017-09-25 09:28
So is there any solution now to get most recent version of OpenSSL package automatically?
I think that fixing version of OpenSSL package in conanfile is not an option. 
I have a lot of independent libraries that are using OpenSSL and every OpenSSL update would be very time consuming operation because I would have to edit conanfile in every single library.

**Comment by lasote** [comment] 2017-09-26 14:26
Maybe we could upload a [conan alias](http://conanio.readthedocs.io/en/latest/reference/commands/alias.html?highlight=alias) pointing to the latest openssl, then you only need to point to the alias version (1.0.2).

**Comment by mnowy** [comment] 2017-09-27 05:35
Oh, I didn't know [conan alias](http://conanio.readthedocs.io/en/latest/reference/commands/alias.html?highlight=alias) functionality earlier.
I think it'll do the trick.
Let's try.

**Comment by claasd** [comment] 2017-09-28 06:48
Same problem here, with a version `4.2.2-pre` being not found by `[~4.2.2]`. This is valid according to SemVer 2.0. 
```
conan install .
ERROR: The version in '~4.2.2' from requirement 'cppzmq/[~4.2.2]@cab/extern P' could not be resolved
```
```
conan search cppzmq
Existing package recipes:

cppzmq/4.2.1@cab/extern
cppzmq/4.2.2-pre@cab/extern
```

**Comment by memsharded** [comment] 2017-09-28 14:04
>Same problem here, with a version 4.2.2-pre being not found by [~4.2.2]. This is valid according to SemVer 2.0.

Are you sure? We were checking the spec, and also the official node implementation, which should be quite compliant with the spec. Pre-releases (indicated by a -) should be never found by a range unless explicitely stated, with something like ``4.2.2-`` This makes sense to me, otherwise, it will make all users always be using the latest pre-releases instead of the latest stable version.

**Comment by claasd** [comment] 2017-09-28 14:13
I meant 4.2.2-pre is a valid name according to semver 2.0.
the spec does not tell what version ranges should find, only the precedence when searching. It states the pre-release versions have a lower precedence (http://semver.org/#spec-item-9 and http://semver.org/#spec-item-11) than stable versions.

So if I put [~4.2.2], I would get 4.2.2 if it exists, and 4.2.2-pre if no stable release exists vor that number.

I am not sure how this should be handled, but the current situation brakes many working projects for us.

**Comment by memsharded** [comment] 2017-09-28 14:24
Yes you are right. We were checking against the node semver, and it didn't behave that way I think. Will check asap if there is some way to fix it.

**Comment by memsharded** [comment] 2017-09-28 14:24
Assigned to 0.28, but we might try to do a minor too if can come up with some solution.

**Comment by mpdelbuono** [comment] 2017-09-28 15:05
This commit also caught my eye. I believe conan's goal is to be compatible with both Python 2.x and 3.x. I don't think node-semver is incompatible with 2.x (at least I haven't found a reason it isn't) but its prospects for the future aren't high.

https://github.com/podhmo/python-semver/commit/b42e9896e391e086b773fc621b23fa299d16b874

**Comment by lasote** [comment] 2017-09-29 00:00
I've uploaded `OpenSSL/1.0.2@conan/stable` as an alias of `OpenSSL/1.0.2l`.
@mnowy Please, tell me if it works.

**Comment by memsharded** [comment] 2017-10-01 16:19
I am having a look at this. The python-semver library used matches the node-semver library, which in turns adds some clarifications and implements some policies that the very brief semver specification does not explain: https://docs.npmjs.com/misc/semver

According to this, it totally makes sense that the tests proposed by @mpdelbuono fail, expressions as ``>1.1`` or  ``1.1.*`` should not match pre-releases. Note that these expressions are intended for the majority of users that are willing to use an stable release. So ``>1.1`` can match ``1.1.1``, ``1.2.0``, etc., but should never match a ``1.2.2-alpha.3``. Otherwise, a simple expression like ``>1.1`` would be most of the time retrieving unstable dependencies, which are only intended to be tested by a few users.

I would understand the possibility by @claasd, that if a patch version is specified, and there are no others, then the pre-release could be used. i.e. ``~1.2.3`` could match ``1.2.3-alpha.3`` if no stable version of ``1.2.3`` or newer is available. I think that if ``1.2.4`` is available, it should be the one returned.

Please feedback, I will submit an issue to the python-semver repo, to see if this make sense.

**Comment by memsharded** [comment] 2017-10-01 18:57
@claasd, would changing the expression to something like: ``[~4.2.2-]`` instead of ``[~4.2.2]`` be a possibility?

**Comment by mnowy** [comment] 2017-10-02 09:40
@lasote Alias `OpenSSL/1.0.2@conan/stable` seems to be a good workaround.
I'll use that solution to resolve other problems in my internal conan repo that are connected with changes (semver lib) made in conan 0.27.

Thank you for help.

**Comment by memsharded** [comment] 2017-10-02 14:20
I am checking this again, adding some more tests, might be possible to add a workaround:

- It is possible to internally add ``-`` to the expressions, i.e. ``~1.2.3 => ~1.2.3-``, so it will be able to detect pre-releases
- The tests I am running only detect preleases of the form: ``1.2.3-pre.1``, ``1.2.3-alpha``, etc, but it is not able to match versions of the form: ``1.2.3-123``. Is this an issue? @claasd how are your versions regarding this pre-release field?

**Comment by claasd** [comment] 2017-11-01 10:14
Hi, sorry for the late response.
The Syntax [~4.2.3-] works for me. If a 4.2.3-pre is the only accessible version, i get it. I also get the 4.2.2 for [~4.2.2-]. So no problem here. Still need to test if I will get the 4.2.3 if there is one, and not the 4.2.3-pre,

**Comment by claasd** [comment] 2017-11-01 10:22
Just for info, with conan 0.26.1 for  [~4.2.2-] i get 4.2.3-pre. but also for [~4.2.2], I get 4.2.3-pre, so there are bugs in the old node-semver.

**Comment by memsharded** [comment] 2017-11-01 23:44
I have added a test in #1977 that checks what you said. Everything seems good:

```python
        result = satisfying(["4.2.2", "4.2.3-pre"], "~4.2.3-", output)
        self.assertEqual(result, "4.2.3-pre")
        result = satisfying(["4.2.2", "4.2.3-pre", "4.2.4"], "~4.2.3-", output)
        self.assertEqual(result, "4.2.4")
```
Feel free to suggest more.

Yes, in old node-semver implementation there were some bugs related to pre-releases. But with current version after reported upstream, they seem to have gone, haven't they?

**Comment by claasd** [comment] 2017-11-02 07:12
The case I am concerned about is:
```python
result = satisfying(["4.2.2", "4.2.3-pre", "4.2.3"], "~4.2.3-", output)
self.assertEqual(result, "4.2.3")
```

thanks!

**Comment by memsharded** [comment] 2017-11-02 08:55
Sure, that is good, added exactly to the test in the PR.

**Closed** 2017-11-21 18:08 UTC
Labels: bug, fixed

**Comment by mmatrosov** [comment] 2018-01-23 10:38
What is the simplest way to test if a specific conan reference matches specific range of conan references? I tried node-semver from the command line, but it does not understand neither square brackets, nor commas. On the docs page http://docs.conan.io/en/latest/mastering/version_ranges.html I see that commas are used instead of spaces - ok. But what do square brackets stand for?

**Comment by memsharded** [comment] 2018-01-23 11:18
The square brackets are the way to specify conan that is a version range. Otherwise, versions are plain strings, they can be whatever you want them to be (up to limitations of length and allowed characters). So conan can retrieve "1.0.2a" without problems for OpenSSL. 

The process to manage plain versions vs version-ranges is also different. The second one requires a "search" in the remote, which is orders of magnitude slower than direct retrieval of the reference (plain versions), so take it into account if you plan to use it for very large projects.

**Comment by mmatrosov** [comment] 2018-01-23 14:09
Thanks for the info! Now it is clear. It would be if this info was somehow reachable from the doc page that I referenced.

**Comment by mmatrosov** [comment] 2018-01-23 14:17
Hm, one more question. We have a recipe for `curl`, which references `openssl` using a version range `openssl/[>1.0.2a,<1.1.0]@aligntech/testing`. I believe that according to your description this version range is incorrect, since `1.0.2a` is not a valid semver. However, conan seems to be working ok with it:

    curl/7.52.1@aligntech/testing requirement openssl/[>1.0.2a,<1.1.0]@aligntech/testing overriden by your conanfile to openssl/1.0.2k@aligntech/testing
    Version range '>1.0.2a,<1.1.0' required by 'curl/7.52.1@aligntech/testing' valid for downstream requirement 'openssl/1.0.2k@aligntech/testing'

So conan was able to decide that `1.0.2k` fits into range `>1.0.2a,<1.1.0`. How did it do that?

**Comment by memsharded** [comment] 2018-01-23 16:04
Good, I have updated http://docs.conan.io/en/latest/mastering/version_ranges.html to include the above clarifications.

**Comment by memsharded** [comment] 2018-01-23 16:07
Regarding ``openssl/[>1.0.2a,<1.1.0]@aligntech/testing`` the thing is that it might be a bit of undefined behavior, and could depend on the implementation of the library. Maybe if you use ``[>1.0.2a, <1.0.2z]`` it will not work as expected. I wouldn't expect to be always respecting the alphabetical order (this could be python implementation specific, typically dict ordering is different in different OSs).

**Comment by mmatrosov** [comment] 2018-01-23 19:56
If you wouldn't expect to be always respecting the alphabetical order, how can you say that `[>1.0.2a, <1.0.2z]` will not work as expected? This relies on alphabetical order. Also, is this behavior documented somewhere? I did not find any proper documentation for this "loose" mode.

**Comment by memsharded** [comment] 2018-01-24 10:36
That is what I mean, probably not expressing myself well, language issues :)

I am saying that ``[>1.0.2a, <1.0.2z]`` is not a valid expression. It shouldn't be used, and it shouldn't be documented. The fact that it might work for some concrete example, as the one you posted above, doesn't mean it should be used, as it is undefined behavior and might fail in other contexts.

**Comment by mmatrosov** [comment] 2018-01-25 10:18
> as it is undefined behavior and might fail in other contexts.
Wow. I kind of got used to UB in the world of C++, because it has a reason to exist. But having UB in such a simple thing as semver?.. As a developer I would expect any behavior to be well-defined - it should either be compared following a specified rules, or fail with a clear error. What do you think?

**Comment by memsharded** [comment] 2018-01-25 10:37
Yes, yes, there is space for improvement here. I am just stating the current state, most of the behavior comes from the used library. To be accurate, it is more a non-deterministic output than undefined behavior, but I think we understand the issue. 
I have opened a dedicated issue to look into it: https://github.com/conan-io/conan/issues/2377

**Comment by mmatrosov** [comment] 2018-01-25 11:03
Ok, thank you!

**Comment by probonopd** [comment] 2018-02-25 10:26
> I think this fits into a weird area of "you want to use semver semantics but your package doesn't follow the semver specification".  

Relevant discussion in https://github.com/openssl/openssl/issues/5042
