### ISSUE TITLE
[bug] cmake in (profile) build_requires result in openssl conflict error

### ISSUE THREAD

**Issue by wdobbe** [conan-io/conan#9003] opened 2021-05-26 10:53 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: OpenSuse Linux Leap 15.2
  * Compiler+version: gcc 10.2.1
  * Conan version: 1.36.0
  * Python version: 3.6.12

### Steps to reproduce (Include if Applicable)
I have the following build_requirements in my profile:

```
[build_requires]
ninja/1.10.2
cmake/3.20.0
```

In my top level recipe I have the following requirements:

```
def requirements(self):
        self.requires("zlib/1.2.11")
        self.requires("qt/5.15.2")
        self.requires("openssl/1.1.1k")
        if self.options.doc:
            self.requires("doxygen/1.8.20")
```

When calling conan install on this recipe Conan prints the following conflict:
```
ERROR: Conflict in cmake/3.20.0:
    'cmake/3.20.0' requires 'openssl/1.1.1j' while 'qt/5.15.2' requires 'openssl/1.1.1k'.
    To fix this conflict you need to override the package 'openssl' in your root package.
```

This looks like a bug to me because openssl is already overridden in the root package recipe.

When I downgrade the openssl requirement in my top level recipe to openssl/1.1.1j Conan no longer reports a conflict error.

### Logs (Executed commands with output) (Include/Attach if Applicable)

wdobbe@linux-wdobbe:~/build/qtftp> conan install ~/crdata/git/qtftp/
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
*: ninja/1.10.2, cmake/3.20.0
[env]
CC=/usr/bin/gcc-10
CXX=/usr/bin/g++-10
ERROR: Conflict in cmake/3.20.0:
    'cmake/3.20.0' requires 'openssl/1.1.1j' while 'qt/5.15.2' requires 'openssl/1.1.1k'.
    To fix this conflict you need to override the package 'openssl' in your root package.

**Comment by wdobbe** [comment] 2021-05-27 18:30
On a different machine the error is different:

`ERROR: Loop detected in context host: 'cmake/3.20.0' requires 'openssl/1.1.1k' which is an ancestor too`

**Comment by jellespijker** [comment] 2021-07-31 22:14
Any news on this? 
```
conan install /mnt/projects/ultimaker/cura/pynest2d -if=/mnt/projects/ultimaker/cura/pynest2d/cmake-build-release -pr=cura_release.jinja --update --build=missing -pr:b cura_release.jinja
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
*: cmake/[>=3.16.2]
[env]
[conf]
tools.cmake.cmaketoolchain:find_package_prefer_config=True
Configuration (profile_build):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++
compiler.version=11
os=Linux
os_build=Linux
[options]
[build_requires]
*: cmake/[>=3.16.2]
[env]
[conf]
tools.cmake.cmaketoolchain:find_package_prefer_config=True
SIP/4.19.25@riverbankcomputing/testing: Not found in local cache, looking in remotes...
SIP/4.19.25@riverbankcomputing/testing: Trying with 'conan-center'...
SIP/4.19.25@riverbankcomputing/testing: Trying with 'ultimaker'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
SIP/4.19.25@riverbankcomputing/testing: Downloaded recipe revision 0
libnest2d/4.10.0@ultimaker/testing: Not found in local cache, looking in remotes...
libnest2d/4.10.0@ultimaker/testing: Trying with 'conan-center'...
libnest2d/4.10.0@ultimaker/testing: Trying with 'ultimaker'...
Downloading conanmanifest.txt
Downloading conanfile.py
libnest2d/4.10.0@ultimaker/testing: Downloaded recipe revision 0
clipper/6.4.2: Not found in local cache, looking in remotes...
clipper/6.4.2: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
clipper/6.4.2: Downloaded recipe revision 0
boost/1.70.0: Not found in local cache, looking in remotes...
boost/1.70.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.70.0: Downloaded recipe revision 0
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.11: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
bzip2/1.0.8: Downloaded recipe revision 0
libbacktrace/cci.20210118: Not found in local cache, looking in remotes...
libbacktrace/cci.20210118: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
libbacktrace/cci.20210118: Downloaded recipe revision 0
nlopt/2.7.0: Not found in local cache, looking in remotes...
nlopt/2.7.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
nlopt/2.7.0: Downloaded recipe revision 0
cmake/3.20.4: Not found in local cache, looking in remotes...
cmake/3.20.4: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
cmake/3.20.4: Downloaded recipe revision 0
openssl/1.1.1k: Not found in local cache, looking in remotes...
openssl/1.1.1k: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
openssl/1.1.1k: Downloaded recipe revision 0
b2/4.5.0: Not found in local cache, looking in remotes...
b2/4.5.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
b2/4.5.0: Downloaded recipe revision 0
ERROR: Loop detected in context build: 'openssl/1.1.1k' requires 'cmake/3.20.4' which is an ancestor too
```

**Comment by franramirez688** [comment] 2021-08-03 10:51
Hi @wdobbe 
I've been trying to reproduce the issue but it was impossible 😢 
By the way, are you facing the issue yet?
If yes, I was wondering if you have tried to pass the `build_requires` only as part of the build profile. What I mean is:

**build_profile.txt**
```
[build_requires]
ninja/1.10.2
cmake/3.20.0
```

Now, running the command:

```
$ conan install . -pr:b build_profile.txt
Configuration (profile_host):
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

Configuration (profile_build):
[settings]
[options]
[build_requires]
*: ninja/1.10.2, cmake/3.20.0
[env]
```

I don't know if it could solve the issue but if you still face it, please, let us know and wait for @memsharded's opinion about it 😉

**Comment by franramirez688** [comment] 2021-08-03 11:09
Hi @jellespijker

We'd need more information here: your recipe, Conan version, OS, etc.
I can see you're using the same profile for `host` and `build` ones but do you really need it? I mean, let us know more about your needs to understand completely your case. It could be related to the other one but we have to be sure.
Thanks!

**Comment by jellespijker** [comment] 2021-08-03 21:05
Hi @franramirez688 
Profile of both host and build are slightly different depending on the recipes see the Jinja profiles in this repo https://github.com/jellespijker/conan-config/tree/main/profiles
It occurs on the recipes in these repo's 
https://github.com/Ultimaker/libArcus/tree/dep_manager
https://github.com/Ultimaker/CuraEngine/tree/dep_manager which are usually build first for the main project which is Cura https://github.com/Ultimaker/Cura/tree/dep_manager . 
Cura consists of multiple dependencies which are combinations of C++, pure Python and SIP bound C++ libraries.
It only happens when I start completely fresh. When I removed all recipes and artifacts locally and on my remote. It also only occurs on Linux (Manjaro) with the GCC compiler (11) I haven't tested it with Clang on Linux. Windows Visual Studio 2019 and MacOS Clang both compile without this issue.

I tried with just the build requirements in the profile, recipe and always the same results.

My plan is to basically setup a full blown development environment for Cura and CuraEngine and it's python & C++ repositories.
See the readme in this project https://github.com/jellespijker/conan-um 

I wrote a generator that creates a Pycharm.xml.run configuration with all the correct environmental variables in place. This in combination with a virtual python environment and the pip download depencies would allow you to run Cura from source. I have managed to cut down the setup time for a new developer from a day to 5 minutes with Conan (love it).

The full dependency tree can be found in my conan-um repo. See the readme. This is a hobby/weekend project in which I'm trying to convince my colleagues of the benefits of using Conan. I personally think Conan could be beneficial for Ultimaker and Cura because we have some technical dept on our build servers. 

Specifing the build requirements and allowing these to be build with the help of Conan would circumvent some constrains of our current build server which is currently very difficult to update to something like CMake 3.16 for instance. Which will be one of my main arguments.

But yeah then it would actually have to do that without something like this happening. It could very well be a cyclic dependency that I have introduced since I am working on 8 repo's on three different systems with 3 different programming languages at the time and CMakeLists.txt that consists of variables and targets.

As a work around I will first do an install command of OpenSLL so it is build for the current setup.

**Comment by franramirez688** [comment] 2021-08-04 07:29
Thanks a lot for your comment @jellespijker 
Those projects look quite interesting and you have done a great job with the conanfile-recipes 👏 
Given your explanation, I definitely think it's a problem related to the graph resolution for your current configuration (it looks like a beautiful corner-case) and it's something that @memsharded will have to look into.

**Comment by czoido** [comment] 2021-09-01 09:47
Hi @jellespijker,
As I can see in your log, you are adding as `build_require` _cmake_ for both _build_ and _host_ profiles, that will add it as a `build_require` for all the dependencies and I think that's causing a loop. Could you please try to remove _cmake_ as `build_requires` from your _build_ profile and check if that solves your issue?

**Comment by jellespijker** [comment] 2021-09-09 06:12
Hi @czoido Sorry for the late response, the notification got buried under a lot of other notification. I tried your suggestion and that fixes it indeed. Thank you for your help.

**Comment by czoido** [comment] 2021-09-09 06:20
Hi @jellespijker,
I'm very glad that it solved your issue. I'll close this now but pleas feel free to reopen or open more issues if you have any question about this or other topics.

**Closed as completed by czoido** 2021-09-09 06:20 UTC
Labels: type: look into, component: graph
