### ISSUE TITLE
[bug] PATH is populated with non-existing directories

### ISSUE THREAD

**Issue by db4** [conan-io/conan#7598] opened 2020-08-26 10:25 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Conan version: 1.28.1
  * Python version: 3.8.3

### Steps to reproduce
Consider the following consumer `conanfile.py`:
```
from conans import ConanFile, tools
import os

class TestConan(ConanFile):
    requires = "zlib/1.2.11@conan/stable"

    def build(self):
        with tools.run_environment(self):
            print("PATH=%d, %s" % (len(os.environ["PATH"]), os.environ["PATH"]))
```
with Conan 1.27.1 I had:
```
C:\Work\conan-test>conan build .
Using lockfile: 'C:\Work\conan-test/conan.lock'
Using cached profile from lockfile
conanfile.py: Calling build()
PATH=313, ;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\NuGet;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\Program Files\TortoiseSVN\bin;;C:\Git\cmd
```
and now with Conan 1.28.1:
```
C:\Work\conan-test>conan build .
Using lockfile: 'C:\Work\conan-test/conan.lock'
Using cached profile from lockfile
conanfile.py: Calling build()
PATH=434, C:/Users/ContainerAdministrator/.conan/data/zlib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\bin;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\NuGet;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\Program Files\TortoiseSVN\bin;;C:\Git\cmd
```
Note `C:/Users/ContainerAdministrator/.conan/data/zlib/1.2.11/conan/stable/package/6cc50b139b9c3d27b3e9042d5f5372d327b3a9f7\bin` added to the path. This is done for every required package. This directory does not exist so it's completely useless. But even worse, it easily overflows system PATH that cannot exceed 8192 chars on Windows (see also https://github.com/conan-io/conan/issues/7587)

**Comment by memsharded** [comment] 2020-08-26 11:19
Reproduced different behavior with:

```python
class TestConan(ConanFile):
    requires = "zlib/1.2.11@conan/stable"

    def build(self):
        print("DEPS_CPP_INFO: ", self.deps_cpp_info["zlib"].bin_paths)
```

Seems non-empty paths are being added now

**Comment by memsharded** [comment] 2020-08-26 11:36
Regression apparently introduced by: https://github.com/conan-io/conan/pull/7277

**Comment by jgsogo** [comment] 2020-08-26 12:22
I've added a fix to the test provided in the PR, it should revert this change.

**Comment by jgsogo** [comment] 2020-08-26 13:18
One more question, @db4 , I understand this is not failing because a _path_ doesn't exist but because of the Windows PATH length limitation, right? 

Do you need a minor asap or can you wait until next week (1.29 is planned for next week)?

Thanks!

**Comment by db4** [comment] 2020-08-26 13:35
@jgsogo,

> One more question, @db4 , I understand this is not failing because a _path_ doesn't exist but because of the Windows PATH length limitation, right?

In my case PATH becomes enormously big (~10kb with 1.28 instead of ~6kb with 1.27), so `cmd.exe` fails to run anything.

> Do you need a minor asap or can you wait until next week (1.29 is planned for next week)?

Well, I can wait - I already downgraded Conan locally (including CI scripts)

**Comment by memsharded** [comment] 2020-08-27 15:45
Closed by https://github.com/conan-io/conan/pull/7599

**Closed as completed by memsharded** 2020-08-27 15:45 UTC
Labels: type: bug, stage: in-progress, priority: high, complex: medium
