### ISSUE TITLE
Regression to 1.7.0 conan crash on startup on centos7/python 3.4

### ISSUE THREAD

**Issue by brianembry** [conan-io/conan#3434] opened 2018-08-30 00:11 UTC
On a completely clean centos7 (python 3.4), python2.7 appears to work fine.

Issue not seen with 1.6.0, tried to get a better traceback, but having issues there.

```
[brian@centos7 ~]$ pip3 install conan 
<snip>
[brian@centos7 ~]$ conan
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2861, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2695, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/conan", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3140, in <module>
    @_call_aside
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3126, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3153, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 640, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 941, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 836, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2639, in requires
    dm = self._dep_map
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2863, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2896, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2893, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/lib/python3.4/site-packages/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'implementation_name' is not defined
```

**Comment by lasote** [comment] 2018-08-30 07:59
Would you mind to paste also the output of the `pip3 install conan` to see the installed dependencies?

**Comment by lasote** [comment] 2018-08-30 10:53
I used a fresh docker centos 7 image, installing python 3.4 and pip. Conan runs perfectly.

**Comment by brianembry** [comment] 2018-08-30 13:28
I just reproduced in docker by doing this.. not sure if using epel matters?
```
$ docker pull centos:7
$ docker run -it centos:7 /bin/bash
$ yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
$ yum update
$ yum install python34 python34-pip
$ pip3 install conan
$ conan <crash from above>
```
pip3 log
```
# pip3 install conan
Collecting conan
  Downloading https://files.pythonhosted.org/packages/c9/93/77350ecca5be2db3bff5ebef4d99ff94dd51287ea0d2163c481a5545f7f4/conan-1.7.0.tar.gz (682kB)
    100% |################################| 686kB 2.5MB/s
Collecting PyJWT<2.0.0,>=1.4.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/93/d1/3378cc8184a6524dc92993090ee8b4c03847c567e298305d6cf86987e005/PyJWT-1.6.4-py2.py3-none-any.whl
Collecting requests<3.0.0,>=2.7.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
    100% |################################| 92kB 4.0MB/s
Collecting colorama<0.4.0,>=0.3.3 (from conan)
  Downloading https://files.pythonhosted.org/packages/db/c8/7dcf9dbcb22429512708fe3a547f8b6101c0d02137acbd892505aee57adf/colorama-0.3.9-py2.py3-none-any.whl
Collecting PyYAML<3.14.0,>=3.11 (from conan)                                                                                                                                                                                                                                      Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |################################| 276kB 5.9MB/s
Collecting patch==1.16 (from conan)
  Downloading https://files.pythonhosted.org/packages/da/74/0815f03c82f4dc738e2bfc5f8966f682bebcc809f30c8e306e6cc7156a99/patch-1.16.zip
Collecting fasteners>=0.14.1 (from conan)
  Downloading https://files.pythonhosted.org/packages/14/3a/096c7ad18e102d4f219f5dd15951f9728ca5092a3385d2e8f79a7c1e1017/fasteners-0.14.1-py2.py3-none-any.whl
Collecting six>=1.10.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting node-semver==0.2.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/51/ff/cef31b5db35ebd626b3b6ddc1c66d80bef6293a8e44165aa50103a0a9e1b/node_semver-0.2.0-py3-none-any.whl                                                                                                                     Collecting distro<1.2.0,>=1.0.2 (from conan)
  Downloading https://files.pythonhosted.org/packages/b0/55/29bfd4d4d4149e860ed01aa446108eb17b240997b746c06a2d0c8ce04f69/distro-1.1.0-py2.py3-none-any.whl
Collecting pylint>=1.9.3 (from conan)
  Downloading https://files.pythonhosted.org/packages/6e/c2/1e97c238877b6a86562d32297eb33a6670b6220e8ec0ca85f67b66dc893f/pylint-2.1.1-py3-none-any.whl (737kB)
    100% |################################| 747kB 2.4MB/s
Collecting future==0.16.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |################################| 829kB 2.3MB/s
Collecting pygments<3.0,>=2.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |################################| 849kB 2.3MB/s
Collecting astroid>=1.6.5 (from conan)
  Downloading https://files.pythonhosted.org/packages/19/92/6f6d3591c429dbdb31c18d8476ba1af08d5973d7cc09f66346109e9de7fb/astroid-2.0.4-py3-none-any.whl (172kB)
    100% |################################| 174kB 8.2MB/s
Collecting deprecation<2.1,>=2.0 (from conan)
  Downloading https://files.pythonhosted.org/packages/dd/06/aed49f13984c4acfcd67d699b2a0e96fefd2f9c700ce88a43120eb0363e2/deprecation-2.0.5.tar.gz
Collecting bottle<0.13,>=0.12.8 (from conan)
  Downloading https://files.pythonhosted.org/packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz (70kB)
    100% |################################| 71kB 12.8MB/s
Collecting pluginbase<1.0,>=0.5 (from conan)
  Downloading https://files.pythonhosted.org/packages/6e/f4/1db0a26c1c7fad81a1214ad1b02839a7bd98d8ba68f782f6edcc3d343441/pluginbase-0.7.tar.gz (40kB)
    100% |################################| 40kB 2.8MB/s
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 9.9MB/s
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl (147kB)
    100% |################################| 153kB 9.3MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |################################| 143kB 3.9MB/s
Collecting idna<2.8,>=2.5 (from requests<3.0.0,>=2.7.0->conan)
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
    100% |################################| 61kB 12.5MB/s
Collecting monotonic>=0.1 (from fasteners>=0.14.1->conan)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/1f/2c/22eee714d7199ae0464beda6ad5fedec8fee6a2f7ffd1e8f1840928fe318/isort-4.3.4-py3-none-any.whl (45kB)
    100% |################################| 51kB 10.5MB/s
Collecting mccabe (from pylint>=1.9.3->conan)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting typed-ast; python_version < "3.7" and implementation_name == "cpython" (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/e5/4a/9b8c7f30f7a3c1b6ff7b9046368d9a73c584d7d40be4c66f9d3b42c93788/typed_ast-1.1.0-cp34-cp34m-manylinux1_x86_64.whl (723kB)
    100% |################################| 727kB 2.6MB/s
Collecting lazy-object-proxy (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/fd/80/825b2c8d828a8fcae14f6e6c19eeefda649462e9e95894a184b53913e79e/lazy_object_proxy-1.3.1-cp34-cp34m-manylinux1_x86_64.whl (55kB)
    100% |################################| 61kB 13.1MB/s
Collecting typing; python_version < "3.5" (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/4a/bd/eee1157fc2d8514970b345d69cb9975dcd1e42cd7e61146ed841f6e68309/typing-3.6.6-py3-none-any.whl
Collecting wrapt (from astroid>=1.6.5->conan)
  Downloading https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
Collecting packaging (from deprecation<2.1,>=2.0->conan)
  Downloading https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->deprecation<2.1,>=2.0->conan)
  Downloading https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 10.2MB/s
Installing collected packages: PyJWT, urllib3, certifi, chardet, idna, requests, colorama, PyYAML, patch, six, monotonic, fasteners, node-semver, distro, typed-ast, lazy-object-proxy, typing, wrapt, astroid, isort, mccabe, pylint, future, pygments, pyparsing, packaging, d
eprecation, bottle, pluginbase, conan
  Running setup.py install for PyYAML ... done
  Running setup.py install for patch ... done
  Running setup.py install for wrapt ... done
  Running setup.py install for future ... done
  Running setup.py install for deprecation ... done
  Running setup.py install for bottle ... done
  Running setup.py install for pluginbase ... done
  Running setup.py install for conan ... done
Successfully installed PyJWT-1.6.4 PyYAML-3.13 astroid-2.0.4 bottle-0.12.13 certifi-2018.8.24 chardet-3.0.4 colorama-0.3.9 conan-1.7.0 deprecation-2.0.5 distro-1.1.0 fasteners-0.14.1 future-0.16.0 idna-2.7 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 monotonic-1.5 nod
e-semver-0.2.0 packaging-17.1 patch-1.16 pluginbase-0.7 pygments-2.2.0 pylint-2.1.1 pyparsing-2.2.0 requests-2.19.1 six-1.11.0 typed-ast-1.1.0 typing-3.6.6 urllib3-1.23 wrapt-1.10.11
You are using pip version 8.1.2, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
I did try updating pip as well, doesn't seem to matter.

**Comment by lasote** [comment] 2018-08-30 14:55
Installing pip like this makes it work:

```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.4 get-pip.py
pip install conan
```

**Comment by r2d2leboss** [comment] 2018-09-10 16:13
I can reproduce the same error using Debian 8 and Ubuntu 14.04 using docker images. It worked fine until Conan 1.6.x.

**Comment by memsharded** [comment] 2018-09-11 10:48
Thanks for the feedback @r2d2leboss 

Have you tried the above pip install commands too?
```bash
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.4 get-pip.py
pip install conan
```

It seems it is a weird system/pip/conan-pip-dependencies combination, but cannot figure out. Someone has a docker image that could share to reproduce it?

**Comment by brianembry** [comment] 2018-09-11 13:36
I included the docker steps above
```
$ docker pull centos:7
$ docker run -it centos:7 /bin/bash
$ yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
$ yum update
$ yum install python34 python34-pip
$ pip3 install conan
$ conan <crash from above>
```

**Comment by memsharded** [comment] 2018-09-11 15:36
Thanks @brianembry for copying it, didn't realize that was the failing, as the trace pasted was looking good (sorry, reading too fast).

I have managed to make it work, in that docker image, using the instructions from @lasote:

```bash
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.4 get-pip.py
pip install conan
```
Then, it seems it could be a bug with the pip3 from python3.4 of that distro, that raises with some of the conan dependencies that have been upgraded this release.

**Comment by r2d2leboss** [comment] 2018-10-01 08:36
Thanks @memsharded and @lasote. However, this tip no longer works with Ubuntu 14.04 for 2 days (I guess something changed recently)

Here is a Dockerfile to reproduce the issue:

``` Dockerfile
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get install -y --no-install-recommends python-software-properties software-properties-common curl python3-setuptools
RUN curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && \
    python3 /tmp/get-pip.py && \
    python3 -m pip install --upgrade pip
RUN python3 -m pip install --upgrade pyOpenSSL && \
    python3 -m pip install conan
RUN conan user
```

**Comment by lasote** [comment] 2018-10-01 08:56
I confirm the issue and I have to admit that I haven't a clue about how to solve it. Something weird with pip + python 3.4

**Comment by raulbocanegra** [comment] 2018-10-16 16:18
It happens also in CentOS 6.0 with rh-python35 from software collections, fixed by installing rh-python36.

**Comment by VladasZ** [comment] 2018-11-01 12:29
Same issue while building my project on travis-ci. Ubuntu 14.04.3
```
 sudo pip3 install conan
Downloading/unpacking conan
  Downloading conan-1.9.0.tar.gz (734kB):              Downloading conan-1.9.0.tar.gz (734kB): 734kB downloaded
  Running setup.py (path:/tmp/pip_build_root/conan/setup.py) egg_info for package conan
    
Downloading/unpacking PyJWT>=1.4.0,<2.0.0 (from conan)
  Downloading PyJWT-1.6.4-py2.py3-none-any.whl
Downloading/unpacking requests>=2.7.0,<3.0.0 (from conan)
  Downloading requests-2.20.0-py2.py3-none-any.whl (60kB):             Downloading requests-2.20.0-py2.py3-none-any.whl (60kB): 60kB downloaded
Downloading/unpacking colorama>=0.3.3,<0.4.0 (from conan)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Downloading/unpacking PyYAML>=3.11,<3.14.0 (from conan)
  Downloading PyYAML-3.13.tar.gz (270kB):              Downloading PyYAML-3.13.tar.gz (270kB): 270kB downloaded
  Running setup.py (path:/tmp/pip_build_root/PyYAML/setup.py) egg_info for package PyYAML
    
Downloading/unpacking patch==1.16 (from conan)
  Downloading patch-1.16.zip
  Running setup.py (path:/tmp/pip_build_root/patch/setup.py) egg_info for package patch
    
Downloading/unpacking fasteners>=0.14.1 (from conan)
  Downloading fasteners-0.14.1-py2.py3-none-any.whl
Downloading/unpacking six>=1.10.0 (from conan)
  Downloading six-1.11.0-py2.py3-none-any.whl
Downloading/unpacking node-semver==0.2.0 (from conan)
  Downloading node_semver-0.2.0-py3-none-any.whl
Downloading/unpacking distro>=1.0.2,<1.2.0 (from conan)
  Downloading distro-1.1.0-py2.py3-none-any.whl
Downloading/unpacking pylint>=1.9.3 (from conan)
  Downloading pylint-2.1.1-py3-none-any.whl (737kB):              Downloading pylint-2.1.1-py3-none-any.whl (737kB): 737kB downloaded
Downloading/unpacking future==0.16.0 (from conan)
  Downloading future-0.16.0.tar.gz (824kB):              Downloading future-0.16.0.tar.gz (824kB): 824kB downloaded
  Running setup.py (path:/tmp/pip_build_root/future/setup.py) egg_info for package future
    
    warning: no files found matching '*.au' under directory 'tests'
    warning: no files found matching '*.gif' under directory 'tests'
    warning: no files found matching '*.txt' under directory 'tests'
Downloading/unpacking pygments>=2.0,<3.0 (from conan)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB):              Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB): 841kB downloaded
Downloading/unpacking astroid>=1.6.5 (from conan)
  Downloading astroid-2.0.4-py3-none-any.whl (172kB):              Downloading astroid-2.0.4-py3-none-any.whl (172kB): 172kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2517, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2514, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'implementation_name' is not defined
Storing debug log for failure in /home/travis/.pip/pip.log
The command "sudo pip3 install conan" failed and exited with 2 during .
```

Works with:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3.4 get-pip.py
pip install conan
```

**Comment by erikzenker** [comment] 2018-11-04 09:45
I see the same issue using conan on **travis ci** using dist trusty. The proposed solution works in a virtualenv:

**Comment by lasote** [comment] 2018-11-05 07:07
Thanks all for writing how to solve it, it will help the users suffering the same issue. 
Do we all agree that it looks like a `pip` bug? I would like to solve it but I don't know how. If someone has some idea it would be very welcome.

**Comment by erikzenker** [comment] 2018-11-05 09:52
It is hard to say. The code triggering the error was changed three years ago (https://github.com/pypa/setuptools/commit/a718819d2849196e902808301c9a95724510c5c1#diff-81de4a30a55fcc3fb944f8387ea9ec94R2837). Before the change some markerlib was used, which could be buggy.

The error says "implementation_name" was not found which is nowadays equal to `sys.implementation.name` or empty if sys is not available. Did something changed in the conan package in this area? 

Can we say when the regression was introduced? @brianembry opened the issue on August 30th. So maybe there was a commit which introduced this regression. Maybe, an additional ci stage should be introduced reproducing this issue to prevent this regression in the future.

**Comment by Nacromances** [comment] 2018-11-08 21:22
Hi 
I have the same issue on centos 7.5, I found it strange that using virtualenv everything works fine

**Comment by lasote** [comment] 2019-01-09 15:13
I have added a note in the installation documentation here: https://docs.conan.io/en/latest/installation.html#known-installation-issues-with-pip

I think we cannot do more in our side, so I'm closing the issue. Thanks all for reporting and helping! :+1:

**Closed by lasote** 2019-01-09 15:13 UTC
Labels: stage: triaging
