### ISSUE TITLE
[bug] GDAL does not work with with_jpeg=libjpeg-turbo

### ISSUE THREAD

**Issue by roedhaetten** [conan-io/conan#12412] opened 2022-10-27 17:58 UTC
It is not possible to install gdal with options with_jpeg=libjpeg-turbo and
libtiff:jpeg=libjpeg-turbo. gdal uses cmake_find_package as generator, and expects "Findlibjpeg-turbo.cmake" to be created. However, this is only created by libjpeg-turbo with the cmake_find_package_multi generator.

I propose adding cmake_find_package_multi as generator for gdal:

```
diff --git a/recipes/gdal/post_3.5.0/conanfile.py b/recipes/gdal/post_3.5.0/conanfile.py
index fe440e544..d03de4e51 100644
--- a/recipes/gdal/post_3.5.0/conanfile.py
+++ b/recipes/gdal/post_3.5.0/conanfile.py
@@ -16,7 +16,7 @@ class GdalConan(ConanFile):
 
     settings = "os", "arch", "compiler", "build_type"
 
-    generators = "cmake", "cmake_find_package"
+    generators = "cmake", "cmake_find_package", "cmake_find_package_multi"
```

### Environment Details
  * Operating System: Ubuntu 20.04 x86_64
  * Compiler: gcc 9.4.0, g++ 9.4.0
  * Conan version: 1.52.0
  * Python version: 3.8.10

### Steps to reproduce:
conan install gdal/3.5.1@ -o with_jpeg=libjpeg-turbo -o libtiff:jpeg=libjpeg-turbo --build=missing

### Logs
Log too long, so attached it as file.
[conan_log.txt](https://github.com/conan-io/conan/files/9882045/conan_log.txt)

**Comment by SpaceIm** [comment] 2022-10-27 19:32
duplicate of https://github.com/conan-io/conan-center-index/issues/13818. Feel free to submit a PR in conan-center https://github.com/conan-io/conan-center-index/pulls to add `cmake_find_package_multi`.

**Comment by roedhaetten** [comment] 2022-10-27 21:06
> duplicate of [conan-io/conan-center-index#13818](https://github.com/conan-io/conan-center-index/issues/13818). Feel free to submit a PR in conan-center https://github.com/conan-io/conan-center-index/pulls to add `cmake_find_package_multi`.

Sorry. Didn't see that one.
But now I did! Thanks. https://github.com/conan-io/conan-center-index/pull/13821

**Comment by jcar87** [comment] 2022-10-28 07:44
Hi @roedhaetten  - thanks for reporting this issue and for your contribution to Conan Center. I will be closing this issue since it is a duplicate of https://github.com/conan-io/conan-center-index/issues/13818. If there's anything we assist with, please reach out!

**Closed as completed by jcar87** 2022-10-28 07:44 UTC
