### ISSUE TITLE
AutoToolsBuildEnvironment: support custom configure command

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4915] opened 2019-04-05 09:06 UTC
currently, `AutoToolsBuildEnvironment` helper has method `configure()`, which always invokes hard-coded `configure` command. it works for 99% of projects, however, there are some exceptions:

- ICU uses `runConfigureICU` script
- OpenSSL uses `Configure` (NOTE capital C)
- TensorFlow uses `configure.py`
- Emscripten recommends to use `emconfigure` wrapper

I suggest to add new parameter `configure_command`, with default `configure` (as currently)

To help us debug your issue please explain:

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ ] I've specified the Conan version, operating system version and any tool that can be relevant.
- [ ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment] 2019-04-05 09:44
Could you explain why for that 1% missing you cannot call `self.run("whatever")` what do you need exactly to be "calculated" from the build helper? I can imagine that a `configure.py` will need different input parameters.

**Comment by SSE4** [comment] 2019-04-05 09:50
I may use `self.run`, but I will need to repeat all logic to calculate gnu triplets. PKG_CONFIG_PATH, prefix, win_bash, subsystem.
if some parameters aren't supported (like gnu triplets), I always may supply `False` to skip em.

**Comment by lasote** [comment] 2019-04-05 09:58
I see. Thanks. We will think about it.

**Comment by lasote** [comment] 2019-04-05 10:06
Note: We might consider providing the `configure command`, similar to the `command_line` from ``CMake``` build helper as @danimtb suggested at some point, instead to call it manually. 

But it would have some other difficulties, the environment variables to be applied should be also considered, and also the configure command is obviously not the same as the make command, so maybe too many commands/envs to play with. 

Might be easier the suggested approach by @SSE4

**Comment by SSE4** [comment] 2019-06-27 14:22
addition: `OpenSSL` uses `Configure` (NOTE: upper-case `C`), and it's impossible to use it with `AutoToolsBuildEnvironment` because of this right now

**Comment by uilianries** [comment] 2019-06-27 15:12
is it not same thing using [tools.vcvars-command()](https://docs.conan.io/en/latest/reference/tools.html#tools-vcvars-command)?

```
autotools = AutoToolsBuildEnvironment()
command = autotools.configure_command().replace("configure", "Configure")
self.run(command)
```

**Comment by bmanga** [comment] 2021-11-08 13:08
Any updates on this?
I can't properly build gmp for webassembly if the `configure` command is not prefixed by `emconfigure`.
Also, a `CONAN_CONFIGURE_PROGRAM` env variable would be necessary I think.

**Comment by memsharded** [comment] 2021-11-08 13:15
Hi @bmanga 

No, this is not planned. ``AutoToolsBuildEnvironment`` has entered the deprecation path, no new changes will be done unless very important bugs.

If you want this feature, then you should be reporting it against the new integration, in this case the ones in https://docs.conan.io/en/latest/reference/conanfile/tools/gnu.html. These will be the ones that will remain in Conan 2.0. At the moment ConanCenter recipes haven't migrated to it, so reports should be done with a minimal reproducible case ("hello world" examples, like the one created by ``conan new hello/0.1 --template=cmake_lib``).

Closing this issue, because this feature will not be implemented in ``AutoToolsBuildEnvironment``. Thanks for commenting!

**Closed by memsharded** 2021-11-08 13:15 UTC
Labels: type: look into, priority: low, stage: queue, complex: low
