### ISSUE TITLE
[workspace] development flow does not call build method

### ISSUE THREAD

**Issue by denwi248** [conan-io/conan#5315] opened 2019-06-07 14:32 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version 1.14.3
OS: Ubuntu 16.04

I have a conan package which manipulates in the build method the CMakeLists.txt file:
```
def build(self):
    cmake = CMake(self)
        if self.should_configure:
            # add something to the CMakeLists.txt file 
            cmake.configure(defs=self.cmake_arguments)
        if self.should_build:
            cmake.build()
```

This works perfectly in the normal package development workflow. But the current workspace workflow does not call the build method. This is why building the project does not work.

So my current workaround is to call `conan build .` in the package build folder, so that the changes are written to the CMakeLists.txt file and then call the normal `cmake --build.` in the workspace root build folder.

Another option would be to manipulate the CMakeLists.txt file in the `configure` method, because this is called during the workspace workflow. But I does not like that because it is definitely a build configure step(OK I does not like the 'manipulate CMakeLists.txt file' either, but currently there is no other option).

**Comment by jgsogo** [comment] 2019-06-07 15:01
Hi @denwi248. There are some flaws related to the workspaces and we are working hard to make it a really useful feature (IMHO, this is one of the coolest features of Conan).

As you have realized, the methods defined in a recipe of a package included in a workspace are not called when installing the workspace. The idea behind workspaces is that you already have the package available in the local folder, you have your sources ready and you are able to build it; then you have a layout file and now you start to use workspaces. So, right now this is expected behavior, and my suggestion is that you keep running the local command before creating the workspace (I wouldn't move your code to the `configure` function).

In the future it would be nice to request only the local path for a package and Conan could take care of executing local commands to prepare the workspace (related to https://github.com/conan-io/conan/issues/4837).

Btw, there is ongoing work related to workspaces in #5314, although nothing related to your pain, I'm sorry.

**Comment by denwi248** [comment] 2019-06-19 13:05
Hi @jgsogo . 
I played around with the workspace feature and followed your advise to make the workspace able to build first on my own:
> The idea behind workspaces is that you already have the package available in the local folder, you have your sources ready and you are able to build it; 

I did that by calling _conan build_ for every workspace module. One downside is that every dependency is rebuilded several times which takes a lot of unnecessary time in my workspace with up to 80 modules.

I then tried to build my workspace again which worked successfully until my workspace root is build. There 'make' does not to find a rule to make the dependency targets:
 `make[1]: *** No rule to make target '../modules/Blib/build-Release/CMakeFiles/Blib.dir/all', needed by '../build-Release/CMakeFiles/Clib.dir/all'.  Stop.
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

I looked into the make file and the error comes from targets with relative or absolute exported names:
```# All Build rule for target.
../build-Release/CMakeFiles/Clib.dir/all: ../modules/Alib/build-Release/CMakeFiles/Alib.dir/all
../build-Release/CMakeFiles/Clib.dir/all: ../modules/Blib/build-Release/CMakeFiles/Blib.dir/all
        $(MAKE) -f ../build-Release/CMakeFiles/Clib.dir/build.make ../build-Release/CMakeFiles/Clib.dir/depend
	$(MAKE) -f ../build-Release/CMakeFiles/Clib.dir/build.make ../build-Release/CMakeFiles/Clib.dir/build
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --progress-dir=/home/z630471/work/conan_ticket/self/CMakeFiles --progress-num=5,6 "Built target Clib"
.PHONY : ../build-Release/CMakeFiles/Clib.dir/all
```

and the exported targets:
``` # Include target in all.
all: /home/z630471/work/conan_ticket/modules/Blib/build-Release/CMakeFiles/Blib.dir/all

.PHONY : all
```
when they match, I can successfully build the workspace root. I then looked into my workspace yaml file:
```
editables:
  Alib/master@john/stable:
    path: modules/Alib
  Blib/master@john/stable:
    path: modules/Blib
  Clib/master@john/stable:
    path: .
layout: layout_gcc
root: Clib/master@john/stable
workspace_generator: cmake
```
And as you can see my workspace root is in someway special. I then moved my workspace root into the modules folder, so it is identical to the other modules. I can then successfully build the workspace.

So that seems to be a bug for me and such a workspace layout should be supported.

By the way, I also tried to generate a 'Ninja' build structure with the original workspace layout and with that I' also able to build the workspace successfully. So it seems to be a problem with the combination Conan/CMake/Make.

I can also upload this minimal workspace example to reproduce the problem.

**Comment by jgsogo** [comment] 2019-06-20 08:03
Yes, please, it would be really helpful to have the example available. Also, I will consider adding your layout to the test suite.

Thanks!

**Comment by memsharded** [comment] 2019-06-20 13:56
Tip: Using ``if self.should_build`` and ``if self.should_configure`` is NOT necessary if you are using the builtin build helpers as ``CMake``. They already have the check internal in the ``cmake.configure()`` and ``cmake.build()`` methods. You can simplify your code there.

**Comment by denwi248** [comment] 2019-06-21 07:12
[conan_ticket.tar.gz](https://github.com/conan-io/conan/files/3313363/conan_ticket.tar.gz)
here it is.
@memsharded thank's for the tip

**Comment by jgsogo** [comment] 2019-06-21 14:26
Hi @denwi248, I'm having a look at your project and in fact it is failing with `MakeFiles`, but not if I generate the project using CMake for an IDE like Xcode.

I'm also able to reproduce the error without any Conan, just with `CMakeLists.txt` files. I've uploaded the minimum set of files to this repo: https://github.com/jgsogo/issue-5315-makefiles (just run `build.sh`). The problem disappears if I set the build folders to a place included in the subtree of the CMAKE_BINARY_DIR.

It looks like an issue related to MakeFiles and/or CMake generator mixing absolute and relative paths. I need to think if we can detect this situation when building the workspace to warn the user about it, but it can be difficult.

**Comment by memsharded** [comment] 2023-03-20 23:38
Conan ``editables`` already call ``build()`` method in Conan 2.0 with ``--build=editable``. Closing this ticket as solved.

Workspaces were removed in 2.0, but the plan is to resume work on them in the 2.X roadmap.
Please track progress in https://github.com/conan-io/conan/issues/12466.

**Closed by memsharded** 2023-03-20 23:38 UTC
Labels: stage: triaging
