### ISSUE TITLE
Changes to Version for better semver support of 0.x versions

### ISSUE THREAD

**Issue by claasd** [conan-io/conan#926] opened 2017-01-30 10:08 UTC
Hi,

Semver allows version number beyond X.Y.Z. It allows version numbers like X.Y.Z-aaaa+bbb.
When I have an version 0.2.0, i may have 0.2.0-build66. When calculating dependencies, conan puts the following requires:
```ini
[requires]
    MyPkg/1.Y.Z
    MyPre/0.2.0-build66
```

I would like to get any 0.2.0 version, independent of the suffix.
Suggested change:
Add a method to allow for patch-level dependencies:
```python
def patch(self):
        self_list = self.as_list
        v0 = str(self_list[0]) if len(self_list) > 0 else "0"
        v1 = str(self_list[1]) if len(self_list) > 1 else "0"
        v2 = str(self_list[2]) if len(self_list) > 2 else "0"
        return Version(".".join([v0, v1, v2]))
```

and change the `stable`method:
```python
def stable(self):
        """ same as major, but as semver, 0.Y.Z is not considered
        stable, so return patch level
        """
        if self.as_list[0] == 0:
            return self.patch()
        return self.major()
```

The result would be
```ini
[requires]
    MyPkg/1.Y.Z
    MyPre/0.2.0
```

Would this solve my problem? Or would this look for a specific version without suffix?

I currently use the following snippet in ALL of our packages, as we may break API with minor releases (also 0.x version).
```python
for req_name in self.requires:
            requirement = self.info.requires[req_name]
            requirement.version = requirement.full_version.bugfix()
```

What do you guys think?

Best,
Claas

**Comment by memsharded** [comment] 2017-01-30 10:44
I think we might have broken your packages in one of the latest merged PR: https://github.com/conan-io/conan/pull/915/files :(

We are just trying to improve the UI for these things. Quick question, where does the ``bugfix()`` come from? It doesn't seem a conan method.

**Comment by claasd** [comment] 2017-01-30 10:57
That was a copy paste error, `bugfix` is the same as the proposed `patch`. I meant `minor()`.

I use the 18.1 version, not the master. I don't think anything is broken, I just need a different behavior ;-).

Best,
Claas

**Comment by claasd** [comment] 2017-01-30 10:58
Adapting to the new package_id is not an issue.

**Comment by memsharded** [comment] 2017-01-30 11:00
The new ``package_id()`` is not a big issue, we will keep the old ``conan_info()`` for backwards compatibility. But we just renamed the ``full_version`` to ``full_version_mode``.

I am having a look, and adding ``patch`` might introduce an alias to ``full_version``.

**Comment by memsharded** [comment] 2017-01-30 11:15
BTW, if you are using ``build66``, shouldn't it be ``+build66`` instead of ``-build66``?

**Comment by lasote** [comment] 2017-01-30 11:16
`full_version` field as the whole specified version string still exist. 
But there was another `full_version()` method (not working because of the repeated name) that has been renamed to `full_version_mode()`

**Comment by memsharded** [comment] 2017-01-30 11:18
Implemented the ``patch()`` but regarding your definition of ``stable``, I think that maybe the ``build`` meta information (denoted with +) has to be excluded, but probably the ``pre-release`` information, should be included for 0.X versions, what do you think?

**Comment by claasd** [comment] 2017-01-30 11:59
mh, not sure. We use the buildXX explicit to always get the newest build of a component. if I use +buildXX (wich conan does not allow by the way), it is not taken into account when calculating the newest version.

I also would be happy if this would be configurable (globally).

**Comment by memsharded** [comment] 2017-01-30 12:00
I have just done a PR #927 that manages the "+build" semver metadata as defined by semver, please have a look.

**Comment by claasd** [comment] 2017-01-30 12:47
Looks good. Just one CR: Rename the `build(self)` to `metadata(self)`, according to semver (http://semver.org/#spec-item-10)

Best,
Claas

**Comment by memsharded** [comment] 2017-01-30 13:45
According to it, I named it ``build``, it always refer to it as ``Build metadata``. Maybe just be explicit and use ``build_metadata``?

However my biggest concern right now (and I'd like to move it fast, to get it into tomorrow release) is that re-defining ``stable`` method will be breaking change for existing packages using it. Any suggestion? What is your current pattern for ``stable`` usage? I didn't get it from your snipped above, it seems you are using just ``minor()``?

**Comment by claasd** [comment] 2017-01-30 14:03
Currently, stable is used automatically, resulting in above described problems and workarounds. 
I think the breaking change dos not affect a lot of packages, as most use the X.Y.Z versioning scheme. 
The behavior changes if the following is true:
* 0.x Release
* Versioning scheme with more than X.Y.Z (e.g. X.Y.Z.1, X.Y.Z-testing) OR non-semver versioning scheme (e.g. 1.0-alpha)

**Comment by memsharded** [comment] 2017-01-30 14:08
https://www.conan.io/search?q=*%2F0.*
:( :(

**Comment by claasd** [comment] 2017-01-30 14:40
It's ok for me know to revert the stable to the old behavior.
I will think of a good solution for this in the meantime.

**Comment by memsharded** [comment] 2017-01-30 15:13
Good, reverted to old in: https://github.com/conan-io/conan/pull/927
Still an improvement, with caching, compiling regex once, and patch/build/pre functionality. 

Lets keep the issue open then, looking forward your ideas.

**Comment by claasd** [comment] 2017-02-06 09:30
Hi,

Currently, I can define how the dependencies affect my build (http://docs.conan.io/en/latest/reference/conanfile.html#package-id). 
However, I might not know how the ABI compatibilities of my requirements are (Especially true for 0.X versions)
My idea is that a package might define it's ABI version compatibility itself. 
Idea: add a optional field 
```python
 version_compatibility = 'SEMVER'
```
possibles values: SEMVER (default), MAJOR, MINOR, PATCH, FULL.

It can still be overwritten by other packages, but would give package developers the power to define if they follow semver for ABI (maybe even for 0.X version) or if the break SEMVER, and how.

What do you think?

**Comment by memsharded** [comment] 2017-02-06 10:05
I am just writing a blog post for this. The issue is that semver is not enough in C/C++, and the behavior cannot be defined by the package itself, but it has to be defined by the consumer of the package (``package_id()``). Because both the usage (in headers, in implementation) and the linkage used by the consumer totally changes it.

As the "stable" current policy was not good for you, and we cannot change it without breaking many 0.X packages, maybe we can add some default policies, implemented as helper methods in the consumer ``package_id()`` that could ease the task, something like:

```python
def package_id(self):
     self.info.header_only()  # this ensure to clear settings, options and requires (self is header only)
     # or
     self.info.requires.all_patch()  # apply a patch() policy to all dpendencies
```

This shouldn't be difficult, and we might try to get it into 0.20.

**Comment by claasd** [comment] 2017-02-06 12:05
for me it probably would be ok to have 
```python
self.info.requires.all_minor()
```
but the others should be there to.
Let me know when your blog post is ready, we can use it as base for further disussions on the subject.

**Comment by memsharded** [comment] 2017-02-20 09:29
Just moved this issue to 0.21, 0.20 is absolutely packed now. We didn't have time to publish the post (I will keep you updated when we publish it), and it seemed this is not very critical and could wait, sorry about that. But please tell us if otherwise.

**Comment by memsharded** [comment] 2017-03-15 16:27
@claasd: The blog post I told about: http://blog.conan.io/2017/03/14/Devops-and-Continouous-Integration-Challenges-in-C-C++-Projects.html

**Comment by memsharded** [comment] 2017-03-21 09:27
The wanted behavior can be done now with a oneliner ``patch_mode``: https://github.com/conan-io/conan/pull/1108/files#diff-ad5a49c412af716e005ab2566e436a5cR194

**Closed** 2017-03-21 15:59 UTC
Labels: fixed
