### ISSUE TITLE
During packaging self.copy() does not keep links

### ISSUE THREAD

**Issue by NingyuShi** [conan-io/conan#643] opened 2016-11-07 21:12 UTC
All links become real files, is there an option to keep links as original way?

**Comment by memsharded** [comment] 2016-11-08 00:23
I think this is a duplicate of https://github.com/conan-io/conan/issues/204#issuecomment-256895043, could you please check it. If duplicated, please close and follow conversation in that one. Thanks!

**Closed** 2016-11-08 19:15 UTC
Labels: duplicate
