### ISSUE TITLE
[bug] Reuploading package to another remote while original remote disabled causes an error

### ISSUE THREAD

**Issue by xahon** [conan-io/conan#8680] opened 2021-03-21 18:35 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 (also applicable to linux)
  * Compiler+version: MSVC 16
  * Conan version: 1.34.1
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
1. Download (conan install) some package from any remote (for example from conan-center)
2. Disable that remote
3. Upload the package to your custom remote
4. Error

### Logs (Executed commands with output) (Include/Attach if Applicable)
> ERROR: \<package\>: Upload recipe to '\<my remote\>' failed: Remote '\<original remote\>' is disabled

**Comment by memsharded** [comment] 2021-03-21 19:56
Hi @xahon 

This is not a bug, but expected if the package has sources:

- Sources ``conan_export_sources.tgz`` are only downloaded when it is necessary to build from sources. This was a feature request, users didn't want to pay for the cost of fetching it if not necessary
- ``conan upload`` will not upload an incomplete package. Before uploading it must fetch the ``conan_export_sources.tgz``
- If the remote is disabled it will be blocked.

Solutions:
- Force fetching the source with ``conan download <ref>``.
- Do not disable the remote until you have uploaded to your own remote.
- Run a ``conan upload --skip-upload`` should fetch the sources, prepare the upload, but do not actually upload. Then disable the remote and finally run ``conan upload`` again without skipping the upload.

**Comment by xahon** [comment] 2021-08-05 13:32
`conan upload --skip-upload` looks weird and misleading. What it does? 
Conan download fetches all possible packages, is there a way to fetch only recipe for the package? (Ok, there's `-re` option)

**Comment by xahon** [comment] 2021-08-05 13:33
And i also have to remove a package before issuing an `upload` command

**Comment by memsharded** [comment] 2021-08-05 23:12
> conan upload --skip-upload looks weird and misleading. What it does?

Prepare the upload, do everything that is done before uploading, but skipping the upload: zipping the ``conan_package.tgz``, for example. Also some checks, consistency etc.

> Conan download fetches all possible packages, is there a way to fetch only recipe for the package? (Ok, there's -re option)

Yes, the --recipe option

> And i also have to remove a package before issuing an upload command

No idea what you mean, you don't need to remove a package before issuing an ``upload``, if you remove the package, you will not be able to upload it.

**Comment by AbrilRBS** [comment] 2024-04-22 12:07
Closing as answered, thanks!

**Closed as completed by AbrilRBS** 2024-04-22 12:07 UTC
Labels: type: question, stage: triaging
