### ISSUE TITLE
[question] How can I find all system requirements?

### ISSUE THREAD

**Issue by daravi** [conan-io/conan#9472] opened 2021-08-24 13:18 UTC
I created https://github.com/conan-io/conan-center-index/issues/6945, but now I am thinking it would be more appropriate here:

Hello,

I use Conan to manage the dependencies of my project. To ship my project, I need to add the system requirements in my dependency graph to my RPM requirements, so that when the RPM is installed, the system package manager (in my case DNF) installs those dependencies.

Currently, the way I have tried to do this is to search through my Conan cache for `system_requirements`, and then check each case one by one if it applies to my specific consumer's options/settings. This is a cumbersome and error prone approach. I was wondering if there is a way I can find system requirements from Conan, because Conan probably knows all the system requirements at the time of `conan install`.

I know that the list returned by Conan may not be what I would use as my RPM requirements because:
1- These are development packages, whereas I would only need the non-devel versions for runtime.
2- Some packages might only be needed for compilation and not for runtime

However, I think this would greatly simplify the process as I would get a definitive initial list (assuming all recipes correctly list their system_requirements), that I can further process for runtime dependencies.

**Comment by memsharded** [comment] 2021-08-25 11:24
Hi @daravi 

It seems that Conan does not have this information at the moment. The issue is that there is no explicit model for the system_requirements, it is just a method that can run something, and it can use some helpers like ``SystemPackageTool`` to assist in the process, but what it is installed is only a result of executing that code, but Conan doesn't get this information.

I think a possible way to try to improve would be:

- Do not hardcode system requirements in the recipe, but use ``conandata.yml`` to define them 
- Use a nested structure to define different system requirements for different platforms, and this can also be leveraged to define runtime-only (not that Conan will use it, but way easier to represent, maintain and collect it from a single source of truth)
- Make ``system_requirements()`` method to read from ``conandata.yml`` and execute it.

This would be a first step, from there, some convention/standardization could be considered, and maybe making them (after some evaluation) available via ``conan info`` or something like that. But honestly, at the moment this seems a bit further away, I'd suggest starting with the above steps to start gathering experience about the approach.

**Comment by memsharded** [comment] 2023-12-01 13:32
This has been addressed in Conan 2.0, it is possible to collect system requirements in json output with graph info .  --format=json, it reports and serializes to the json the system-requirements, and it also follows the different conf that affects the system requirements.

Closing this as solved and implemented in Conan 2.0, please try it and feedback welcome!

**Closed as completed by memsharded** 2023-12-01 13:32 UTC
