### ISSUE TITLE
Error on conan upload (need more than 1 value to unpack)

### ISSUE THREAD

**Issue by olivren** [conan-io/conan#2064] opened 2017-11-22 17:16 UTC
There is a library I packaged, and for which the command `conan upload` fails with the error message
```
ERROR: need more than 1 value to unpack
```
I was able to trace the error using pdb:

```
(Pdb) where
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/bdb.py(400)run()
-> exec cmd in globals, locals
  <string>(1)<module>()
  /home/demo/opt/python/Python-2.7.14-install/bin/conan(11)<module>()
-> sys.exit(run())
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/conan.py(6)run()
-> main(sys.argv[1:])
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/command.py(1275)main()
-> error = command.run(args)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/command.py(1152)run()
-> method(args[0][1:])
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/command.py(898)upload()
-> skip_upload=args.skip_upload, integrity_check=args.check)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/conan_api.py(67)wrapper()
-> return f(*args, **kwargs)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/conan_api.py(724)upload()
-> retry_wait, skip_upload, integrity_check)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/cmd/uploader.py(46)upload()
-> integrity_check=integrity_check)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/cmd/uploader.py(74)_run_upload()
-> integrity_check)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/cmd/uploader.py(80)_upload()
-> self._check_recipe_date(conan_ref)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/cmd/uploader.py(117)_check_recipe_date()
-> remote_recipe_manifest = self._remote_proxy.get_conan_digest(conan_ref)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/proxy.py(307)get_conan_digest()
-> result = self._remote_manager.get_conan_digest(conan_ref, remote)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/remote_manager.py(129)get_conan_digest()
-> return self._call_remote(remote, "get_conan_digest", conan_reference)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/remote_manager.py(252)_call_remote()
-> return getattr(self._remote_client, method)(*argc, **argv)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/rest/auth_manager.py(31)wrapper()
-> ret = func(self, *args, **kwargs)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/rest/auth_manager.py(140)get_conan_digest()
-> return self._rest_client.get_conan_digest(conan_reference)
  /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/client/rest/rest_client.py(112)get_conan_digest()
-> return FileTreeManifest.loads(contents[CONAN_MANIFEST])
> /home/demo/opt/python/Python-2.7.14-install/lib/python2.7/site-packages/conans/model/manifest.py(77)loads()->None
-> filename, file_md5 = md5line.split(": ")
(Pdb)  p text
u'1506333117\nconan_helpers/.hg/00changelog.i: 721c93a8a9238620123d3bcfa670ce56\nconan_helpers/.hg/branch: de2b14ae7499f90736fc4a92327553a5\nconan_helpers/.hg/cache/branch2-base: 100a7c2b8458fe6dd44d7d5cb3bb0cbf\nconan_helpers/.hg/cache/checkisexec: d41d8cd98f00b204e9800998ecf8427e\nconan_helpers/.hg/cache/checklink: d41d8cd98f00b204e9800998ecf8427e\nconan_helpers/.hg/cache/checklink-target: d41d8cd98f00b204e9800998ecf8427e\nconan_helpers/.hg/cache/checknoexec: d41d8cd98f00b204e9800998ecf8427e\nconan_helpers/.hg/cache/rbc-names-v1: c21f969b5f03d33d43e04f8f136e7682\nconan_helpers/.hg/cache/rbc-revs-v1: 76737942af9d49110889e892f76210b3\nconan_helpers/.hg/cache/storehash/5fb968472365: 7a72c6410a3676fccdde36c440ff9331\nconan_helpers/.hg/dirstate: c962f127da08094b52da225b18507f87\nconan_helpers/.hg/hgrc: a02be988ff1ababc3f735a887eb79005\nconan_helpers/.hg/requires: 8cc62f69fc51b10dd964d7423dc72f31\nconan_helpers/.hg/store/00changelog.i: a8be7cb9be6e0266204c41df2f276832\nconan_helpers/.hg/store/00manifest.i:'
```

As you can see, the last line in `text` ends with a colon and does not have an hashsum that follows it. This is what makes the call to `split` fail. I checked on my Conan server, and the content of the file `conanmanifest.txt` is indeed the same as `text`.

It is probably not a good idea for me to export the content of a `.hg` directory (Mercurial repo) in the first place, but I don't expect it to break conan.

**Comment by memsharded** [comment] 2017-11-22 17:55
I think this problem might be related to concurrency, at least I heard once about a similar error. Is it possible that you uploaded the same package concurrently to conan_server? If the manifests are very large, which can happen if exporting the .hg directory, then, the chances this is corrupted in conan_server are slightly higher. 
There is already a check in conan codebase that excludes ``.git`` folder from exports, automatically. Maybe it makes sense to exclude also ``.hg`` too.

**Comment by olivren** [comment] 2017-11-23 08:32
No there is no chance I uploaded the same package concurrently. I am the only one working on it and I always upload sequentially. The manifest is not large, here is the `conanmanifest.txt` I have on my local cache (this is after a `conan test_package`, I don't know if the original file used for the upload was truncated in the first place):

```
1506333627
conan_helpers/.hg/00changelog.i: 721c93a8a9238620123d3bcfa670ce56
conan_helpers/.hg/branch: de2b14ae7499f90736fc4a92327553a5
conan_helpers/.hg/cache/branch2-base: 100a7c2b8458fe6dd44d7d5cb3bb0cbf
conan_helpers/.hg/cache/checkisexec: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/cache/checklink: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/cache/checklink-target: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/cache/checknoexec: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/cache/rbc-names-v1: c21f969b5f03d33d43e04f8f136e7682
conan_helpers/.hg/cache/rbc-revs-v1: 76737942af9d49110889e892f76210b3
conan_helpers/.hg/cache/storehash/5fb968472365: 121b20b53c82ee9fb7bcfff5315693cf
conan_helpers/.hg/dirstate: c962f127da08094b52da225b18507f87
conan_helpers/.hg/hgrc: a02be988ff1ababc3f735a887eb79005
conan_helpers/.hg/requires: 8cc62f69fc51b10dd964d7423dc72f31
conan_helpers/.hg/store/00changelog.i: a8be7cb9be6e0266204c41df2f276832
conan_helpers/.hg/store/00manifest.i: 1d27d5c84d0e19f442cdbfc94cfe81a3
conan_helpers/.hg/store/data/____init____.py.i: da690c4c0c38a3b65bdfc1fe87544446
conan_helpers/.hg/store/data/bin/pdbstr.exe.d: dc29ecf4320576874634a3105e2ead5c
conan_helpers/.hg/store/data/bin/pdbstr.exe.i: ff91beabea2e8d2afb7c5c06603bd7e5
conan_helpers/.hg/store/data/bin/srctool.exe.i: 84f165589b37c3144eb29762fc33c569
conan_helpers/.hg/store/data/conan__helpers.py.i: 0cd4a5a1d8a4b717b7659cee0c474b96
conan_helpers/.hg/store/data/conanfile.py.i: 4803663be15479c8b975d773355bc15c
conan_helpers/.hg/store/data/helpers.py.i: 211232e04d3b29ad59b277ef8856e6a9
conan_helpers/.hg/store/data/test__package/conanfile.py.i: 3f45513a5b5bcb6bb589db5b135c763e
conan_helpers/.hg/store/data/~2ehgignore.i: 5b12ded104ba827224497b3f3325937b
conan_helpers/.hg/store/data/~2ehgtags.i: 8a99e3664470a55ee742e0683c3ccccc
conan_helpers/.hg/store/fncache: 67cb83d9a76ace87e4f332965bb49af3
conan_helpers/.hg/store/phaseroots: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/store/undo: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/store/undo.backup.phaseroots: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/store/undo.backupfiles: 26ab0db90d72e28ad0ba1e22ee510510
conan_helpers/.hg/store/undo.phaseroots: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/undo.bookmarks: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/.hg/undo.branch: c21f969b5f03d33d43e04f8f136e7682
conan_helpers/.hg/undo.desc: 97bcaf8bb3ff919b11a37853a2e96a9c
conan_helpers/.hg/undo.dirstate: c962f127da08094b52da225b18507f87
conan_helpers/.hgignore: a1fa93265f65ea775d244c4d4df01f1a
conan_helpers/.hgtags: 00582d0b7db41b58ea54dd72ee19245d
conan_helpers/__init__.py: d41d8cd98f00b204e9800998ecf8427e
conan_helpers/bin/pdbstr.exe: b149781a4bb99b9bc028889c1f8ff2bf
conan_helpers/bin/srctool.exe: 0584716e4e28c8cd8a3873829309aa66
conan_helpers/helpers.py: 72d47f6d9fd6ba0896dc37ea65584c7f
conanfile.py: ab4e3e94bed866befd2dc9b5c8d18109
hg_recipe_info.json: 8c069e87ceff874ff5dddc9af04d429f
```

**Comment by memsharded** [comment] 2017-11-23 09:27
Yes, it seems the original file was truncated, but so far I don't know what could happen. 

Is there a way it can be reproduced? Or even if it happens randomly, what would be the process to have more chances to see it? Does it happen even the first time you upload, or after several uploads? Did it happen in other packages, or only that one with mercurial?
Thanks very much for your feedback!

**Comment by olivren** [comment] 2017-11-23 10:28
The mercurial directory is a subrepository that I use and that I export in all of my packages (I have about 40 libraries packaged now). It contains python code that is shared by all my packages.

I already saw this exact same problem a few weeks ago, only one time I think, but I did not investigate at the time.

I have 146 distinct packages on the server (there are multiple versions for each library). I checked quickly, and they all seem to have a complete `conanmanifest.txt` , apart from the problematic one.

Most of my packages are built and binary packaged on Linux and Windows, but this specific package is Linux only. It was uploaded using `conan upload` without the `--all` argument.

**Comment by olivren** [comment] 2017-11-23 12:58
By the way, the workaround to my problem is to `conan remove` the package.

**Comment by olivren** [comment] 2017-11-23 14:55
`conan upload --force` would have probably worked, too.

**Comment by memsharded** [comment] 2017-12-17 21:03
Hi @olivren 
I wanted to follow-up this issue. Did it happen again? Were you able to capture more info? Here, I did a couple of tests with mercurial, and were not able to reproduce the issue. Thanks!

**Comment by olivren** [comment] 2017-12-17 21:26
Hi. It did not happen again, but I'm not packaging new libs these days. I 
don't have more info, unfortunately.

**Comment by memsharded** [comment] 2017-12-17 22:38
Ok, thanks for telling, no problem. Let's wait then at the moment. Please report if you package new libs and it happens again. Cheers

**Comment by lasote** [comment] 2018-06-29 10:33
I'm closing this issue, please feel free to reopen if the issue happens again. Thanks for reporting.

**Closed by lasote** 2018-06-29 10:33 UTC
Labels: bug, look into, to do
