### ISSUE TITLE
[bug] CONAN_LINK_RUNTIME does not get set

### ISSUE THREAD

**Issue by thvdburgt** [conan-io/conan#7702] opened 2020-09-11 13:38 UTC
The CMake definition CONAN_LINK_RUNTIME does not seem to get set as defined here: https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#definitions .

### Environment Details
  * Conan version: 1.29.0
  * Python version: 3.8.1
  * CMake version: 3.18.2

### Steps to reproduce/Logs

Using the following:
```
> conan profile show release
Configuration for profile release:

[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=14
compiler.runtime=MD
build_type=Release
[options]
[build_requires]
[env]
```
**conanfile.py**
``` python
from conans import ConanFile, CMake

class ExampleConan(ConanFile):
    name = "example"
    generators = "cmake"
    settings = "os", "compiler", "arch", "build_type"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```
**CMakeLists.txt**
``` cmake
cmake_minimum_required(VERSION 3.18)

include(${CMAKE_CURRENT_BINARY_DIR}/conanbuildinfo.cmake)

project(test)
conan_basic_setup(TARGETS)

message(STATUS "CONAN_LINK_RUNTIME = ${CONAN_LINK_RUNTIME}")
```
and running 
`> conan install --install-folder build --profile release .`
then
`> cmake -G "Visual Studio 14 2015 Win64" -B build .`

I get the following output
```
> cmake -G "Visual Studio 14 2015 Win64" -B build .
-- Selecting Windows SDK version  to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: C:/dev/test/build
-- CONAN_LINK_RUNTIME =
-- Configuring done
-- Generating done
-- Build files have been written to: C:/dev/test/build
```
I'd expect CONAN_LINK_RUNTIME to be set to "MD", but it is empty/not set as you can see.
This also has consequences for `conan_set_vs_runtime` in `cmake_common.py`.

**Comment by ghost** [comment] 2020-12-30 01:03
The variable CONAN_SETTINGS_COMPILER_RUNTIME seems to be defined properly

**Comment by memsharded** [comment] 2020-12-30 09:47
Hi @thvdburgt @ricardo-barracuda 

Sorry this issue took so long to be responded, it was buried in notifications.

This is a very well known issue of the build helpers. The documented behavior in https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#definitions  is right, this is not a bug. The CONAN_LINK_RUNTIME is injected by the ``CMake()`` build helper in the ``build()`` method. If you are calling ``cmake`` directly, you don't get it defined.

This is one of the main reasons we are already changing the integration paradigm to the new ``generate()`` and toolchains files. The old ``CMake`` helper will be replaced for this new one.

Please check the docs in:
- https://docs.conan.io/en/latest/reference/conanfile/tools.html
- https://docs.conan.io/en/latest/creating_packages/toolchains.html

It is still a bit early/experimental, but our biggest focus and effort right now, so totally recommended to start learning and trying them.

As this is not a bug that we could solve (behavior is as documented, and the CONAN_LINK_RUNTIME cannot be defined if not calling the ``build()`` method, I am closing this issue now, but please don't hesitate to open new issues for any further question or clarification. Thanks!

**Closed as completed by memsharded** 2020-12-30 09:47 UTC
Labels: stage: triaging
