### ISSUE TITLE
[bug]     from conan.tools.files import rename ModuleNotFoundError: No module named 'conan'

### ISSUE THREAD

**Issue by skyhhh666** [conan-io/conan#11046] opened 2022-04-19 08:50 UTC
cd build
conan install .. --profile=default --build=missing   
### Environment Details (include every applicable attribute)
  * Operating System+version:Win10 
  * Compiler+version: compiler.version=16
  * Conan version:1.29.0
  * Python version:3.8.5
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=16
build_type=Release
### Steps to reproduce (Include if Applicable)
cd build
conan install .. --profile=default --build=missing   

### Logs (Executed commands with output) (Include/Attach if Applicable)
ERROR: boost/1.73.0: Cannot load recipe.
Error loading conanfile at 'C:\Users\21403\.conan\data\boost\1.73.0\_\_\export\conanfile.py': Unable to load conanfile in C:\Users\21403\.conan\data\boost\1.73.0\_\_\export\conanfile.py  
  File "c:\python38\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\21403\.conan\data\boost\1.73.0\_\_\export\conanfile.py", line 1, in <module>
    from conan.tools.files import rename
ModuleNotFoundError: No module named 'conan'

thanks

**Comment by memsharded** [comment] 2022-04-19 20:31
Hi @skythj 

This is not a bug. You are using an older Conan version (1.29) that has not implemented this tool yet (that version is like 2 years old). If you are using an older version, select that version in the bottom-left corner of the docs.

So unless there is something else, I think we can close this ticket, thanks.


Edit: Also, if you are using packages from ConanCenter, like ``boost/1.73.0`` is a package from ConanCenter, you should be using latest Conan version, as per the stability policy in: https://docs.conan.io/en/latest/introduction.html#stable

> This means that public repositories, like ConanCenter, assume the use of the latest version of the Conan client, and using an older version may result in failure of packages and recipes created with a newer version of the client.

**Closed as completed by memsharded** 2022-04-19 20:31 UTC
Labels: type: question

**Comment by skyhhh666** [comment] 2022-04-20 01:31
@memsharded 
ok , thanks, i updated 1.49,then  solved this problem, but i have a question, conan 2.0+ compiler doesn't have Visual Studio?

**Comment by memsharded** [comment] 2022-04-20 07:15
> conan 2.0+ compiler doesn't have Visual Studio?

conan 2.0 has ``msvc`` compiler. Conan 1.X also provides it, in order to allow a smoother upgrade. You need to use the new build system integrations first (``from conan.tools.cmake`` for example) and then switch to ``msvc``
