### ISSUE TITLE
Projects generated with mismatching runtime library

### ISSUE THREAD

**Issue by Enhex** [conan-io/conan#2147] opened 2017-12-12 19:49 UTC
I didn't touch any runtime configuration, thus the following is the default behavior.
The following happens to me when using the CMake generator to generate Visual Studio 2017 projects.

When using `conan create`, both `Debug` and `Release` configurations are generated with `/MD`. (bug?)

on the other hand, when using `conan install` projects are generated with `/MDd` for `Debug` and `/MD` for `Release`.

I use `conan create` to create packages for dependency libraries, and `conan install` to create executable project solution that consumes such dependency libraries.
This means I get a mismatch between the runtime libraries in `Debug`: dependency libraries use `/MD` while the executable uses `/MDd`, and the build fails.

`cmake_multi` generator can be used as a workaround, though this is still broken behavior with the `cmake` generator.

**Comment by memsharded** [comment] 2017-12-12 20:42
Thanks for raising this issue.
Could you please tell which configuration are you using? Are you using profiles? The default profile? Can you please copy your profile here? 
Also, which is the command line you are using in the conan create? Does it happens if you specify explicitly ``-s compiler.runtime=MDd`` for the debug creation?

Also, please make sure you are running latest conan (0.29.2). Thanks!

**Comment by Enhex** [comment] 2017-12-12 20:59
I'm using Conan 0.29.2 via pip.

I'm using Conan's default profile:
```
[build_requires]
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=15
build_type=Release
[options]
[scopes]
[env]
```

In the `conan create` I'm not specifying any settings.
It defaults to `Release`, and note that CMake still generates Debug configuration in VS (with both `create` and `install` commands).

I didn't try to create a separate build using `build_type=Debug`, so I'm not sure if `-s compiler.runtime=MDd` is relevant. However I did try to see what `conan create` does with `build_type=Debug` and it does use `/MDd` for both Release and Debug VS configurations.

**Comment by memsharded** [comment] 2017-12-12 21:39
> It defaults to Release, and note that CMake still generates Debug configuration in VS (with both create and install commands).

Are you doing a single-config package or a multi-config package? The default is just one configuration, so it seems you are just building the Release package, not the Debug one. In any case, the VS solution that is created is hidden in the local cache you typically don't access it at all, it is even considered temporary and not usable.

Maybe it would be good to set up a reproducible example. Could you please put something in a git repo, with detailed steps to reproduce. Or if the default ``conan new Hello/0.1 -s`` is good to test, then only the steps to reproduce. I think we can concentrate on the ``conan create``, the install could be addressed later, when we are sure creation is ok.

**Comment by Enhex** [comment] 2017-12-13 09:17
> Are you doing a single-config package or a multi-config package? The default is just one configuration, so it seems you are just building the Release package, not the Debug one.

That means that the generated executable project's Debug configuration still links against the Release libraries?

Here's a minimal reproducible example using `conan new`'s `Hello` library:
https://github.com/Enhex/conan_runtime_mismatch
It includes `conan-create.bat` and `conan-install.bat` to show what Conan commands are used.

**Comment by memsharded** [comment] 2017-12-13 10:06
Yes, that is true, this is what happens:
- You are creating just the default package for hello library, the Release one
- You are installing the same package, with the Release binary
- You are creating a VS project (outside of conan, with cmake ``cmake ../ -G "Visual Studio 15 Win64"``). This project has 2 configurations. Switch first to release configuration in your IDE to build, because you installed Release dependencies

If you want to build both Debug and Release configurations, you might want to first build those two flavors of the package:
```bash
$ conan create user/testing #default is release, but you can explicit -s build_type=Release
$ conan create user/testing -s build_type=Debug
```

Then, to consume those two different binaries, there are different ways to work with conan:
- Switch your dependencies. When you switch your build_type in your VS IDE, you go to the terminal and type ``conan install -s build_type=xxxx``. It will be very fast, because the dependencies are cached.
- You can install the dependencies in different subfolders, and use them, have different debug-release environments. Check: http://docs.conan.io/en/latest/manage_deps/workflows.html
- You can use the ``cmake_multi`` generator, that allows to install both configurations and switch directly in the IDE: http://docs.conan.io/en/latest/integrations/cmake/cmake_multi_generator.html


This (the single-config packages) approach is the most popular one (by large) but is not the only one. You can also create multi-config packages that will contain both debug and release artifacts in the same package. Please check: http://docs.conan.io/en/latest/packaging/package_info.html#n-configs-1-package

Please have a look to those pointers, and do not hesitate to ask if you have further questions. Thanks!

**Comment by Enhex** [comment] 2017-12-13 10:29
If `cmake` generator only generates single valid Release/Debug VS configuration, perhaps the other invalid one should be removed to avoid confusion?

**Comment by memsharded** [comment] 2017-12-13 11:04
The thing with the generated ``conanbuildinfo.cmake`` is that it tries to follow what we think it is an important design criteria: including it with ``include(.../conanbuildinfo.cmake)`` does not and should not change your build configuration at all. All it does is to declare some CONAN_XXX variables, and also define some helpful macros, that you can later call. If you removed it from one of those macros, then the workflow might be more inconvenient, as you are force to close the IDE, as you cannot switch build type (it has been removed), then go to terminal, conan-install the other build_type, then reopen the IDE again. 

Also, the ``cmake_multi`` generator is just a composition of 2 ``cmake`` generated files, so both release/debug configurations can be valid at the same time, even if a given file is only valid for one given configuration.

**Comment by wpalfi** [comment] 2017-12-18 12:29
Hi,

I just wanted to create a similar issue. We are also using Visual Studio 2017 and want to switch now to the recommended single-config approach. Having invalid VS configurations is confusing and a pitfall.

My solution was to add this to CMakeLists.txt:

```CMake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
if(CONAN_SETTINGS_BUILD_TYPE STREQUAL "Debug")
    set(CMAKE_CONFIGURATION_TYPES Debug)
else()
    list(REMOVE_ITEM CMAKE_CONFIGURATION_TYPES Debug)    
endif()    
```

I can
- switch build type with `conan install -s build_type=xxxx`
- cmake manually or just build ZERO_CHECK
- Visual Studio detects the changes and switches the configuration automatically, no need to close and reopen

Any better way to achieve that? I think it would make sense to set CMAKE_CONFIGURATION_TYPES in conan_basic_setup(), at least optional.

For convenience, switching conan install can be done with Visual Studios "External Tools" feature:
![grafik](https://user-images.githubusercontent.com/18048248/34106046-001c6794-e3f7-11e7-9845-8678de9262a5.png)

**Comment by wpalfi** [comment] 2018-01-12 12:13
@memsharded What about a CONAN_CONFIGURATION_TYPES variable? Then conan would not change the build confiugration, but my solution would be much shorter:

```CMake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
set(CMAKE_CONFIGURATION_TYPES ${CONAN_CONFIGURATION_TYPES})
```

**Comment by memsharded** [comment] 2023-12-31 00:40
Closing as outdated, this should be solved in new integrations

**Closed by memsharded** 2023-12-31 00:40 UTC
