### ISSUE TITLE
Consider creating a RPM package for standalone conan

### ISSUE THREAD

**Issue by kepam** [conan-io/conan#2772] opened 2018-04-17 15:46 UTC
Hi,
We can see that there is standalone deb package for Conan.
Would you consider creating also standalone RPM package?

We would like to start using Conan on our production boxes. To do that we need have a way to install Conan to boxes that do not have access to the internet, and do not have access to pip.

We are working on rhel/centos machines so to install Conan to multiple boxes we need to have RPM package. Obviously, the best way would be if the package would be in epel. But if it's not possible we would be happy to just have the package in any repo.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment] 2018-04-17 16:58
Yes, we would consider it. I think some other users would benefit from it.

The only issue about this is time. Currently we are fully committed for the next releases, so this won't be possible at least in a few months.

The good news is that if you already know how to create RPM packages for your platform, it should be relatively easy, you could use the pyinstaller code existing here: https://github.com/conan-io/conan/blob/develop/pyinstaller.py and create the RPMs yourself. Calling:

```bash
$ python pyinstaller.py
```

would manage to create the standalone install. You can zip it and unzip in the target machines if you want, or bundle it in an RPM. If you want to try and need help, don't hesitate to ask. Thanks!

**Comment by jagauthier** [comment] 2021-02-12 16:23
I'm wondering if this was ever completed.

**Comment by ivzhh** [comment] 2021-02-12 22:45
I have a [RPM spec for Fedora](https://github.com/ivzhh/conan-rpm/blob/main/conan.spec), but the Python library versions do not match with the package Fedora have:

```
Error: 
 Problem: conflicting requests
  - nothing provides (python3.9dist(deprecation) < 2.1 with python3.9dist(deprecation) >= 2) needed by conan-1.33.1-1.fc35.noarch
  - nothing provides (python3.9dist(patch-ng) < 1.18 with python3.9dist(patch-ng) >= 1.17.4) needed by conan-1.33.1-1.fc35.noarch
  - nothing provides python3.9dist(node-semver) = 0.6.1 needed by conan-1.33.1-1.fc35.noarch
(try to add '--skip-broken' to skip uninstallable packages)
```
`deprecation` is exactly `2.1`, `patch-ng` is `1.17.2`, and `node-semver` is `0.8.0` on Fedora 34 right now.

**Comment by uilianries** [comment] 2021-02-12 23:16
Not yet, but we have Debian version, which can be convert using Alien: 

```bash
$ wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_33_1.deb
$ sudo alien -r conan-ubuntu-64_1_33_1.deb
$ sudo rpm -i conan-ubuntu-64_1_33_1.rpm
```

I didn't check if it works, usually solving dependencies with Alien is a big problem.

Please, take a look on Download page: https://conan.io/downloads.html

**Comment by dpgraham4401** [comment] 2021-10-17 23:58
Is anyone actively working on this?

**Comment by memsharded** [comment] 2021-10-18 08:20
Hi all,

It has not been prioritized yet, the issue is still open, but it doesn't seem there has been enough people interested to make it to the top priorities. At least from the maintainers side, we will most likely not work on this at least until Conan 2.0 is GA, too many things on our plate at the moment...

**Comment by dpgraham4401** [comment] 2021-10-18 13:16
Hi @memsharded If it's ok with everyone, I'd like to take a stab at this. 

Full disclosure, this would be my first time maintaining a fedora package but I've been learning how and looking for a package worth the effort to maintain for a few months now.

**Comment by memsharded** [comment] 2021-10-18 14:20
Sure @dpgraham4401, thanks very much for offering to contribute.

We already have the ``pyinstaller.py`` in the root of the repo. I think the best would be to have it in its own repo (your own one, and link it here), we need to put a central place where to put this stuff, we also have it on our side a bit messy.

**Comment by memsharded** [comment] 2023-10-08 00:40
We are now releasing Conan stand-alone executables for Linux in https://conan.io/downloads, so RPM packages would be mostly unnecessary/overkill?

**Comment by memsharded** [comment] 2023-11-29 17:41
I am closing this, at the moment an RPM package is not planned.

We keep working on releasing executables, self-contained zipped folder and 1-file executables, and we will keep expanding on approaches for other convenient ways for installation of Conan in Linux, it seems the next planned step is to add a script based installation, very popular nowadays. I think creating a RPM from the self-contained executables should be relatively straightforward for users that are forced to use RPM inside their infra.

**Closed by memsharded** 2023-11-29 17:41 UTC
Labels: type: feature
