### ISSUE TITLE
KeyError: 'time'

### ISSUE THREAD

**Issue by DavidZemon** [conan-io/conan#4895] opened 2019-04-02 16:11 UTC
I've been hitting this error intermittently for a long time and I can't seem to reliably reproduce it locally. I can't figure out what's causing it. Do you have any idea where I should even start looking? Is it possible that this `time` attribute didn't exist on older versions of Conan?

The following error occurs inside the `wsbu/toolchain-native:v0.3.1` Docker image, which is based on Ubuntu 18.04 and is using Conan v1.11.2. The host is also 18.04 but was upgraded to Conan v1.14.1 today (I've seen the error before today but can't pinpoint the first time). The host and Docker image share many Conan files/folders. The mounted volumes are:

```
--volume "/home/captain/.conan/.conan.db:/home/captain/.conan/.conan.db"
--volume "/home/captain/.conan/data:/home/captain/.conan/data"
--volume "/home/captain/.conan/registry.json:/home/captain/.conan/registry.json"
```

And the error that is causing me the headaches:

```
[10:10:20] :		 [Step 1/2] Python 2 will soon be deprecated. It is strongly recommended to use Python 3 with Conan:
[10:10:20] :		 [Step 1/2] https://docs.conan.io/en/latest/installation.html#python-2-deprecation-notice
[10:10:20] :		 [Step 1/2] 
[10:10:20] :		 [Step 1/2] Exporting package recipe
[10:10:21] :		 [Step 1/2] Linter warnings
[10:10:21] :		 [Step 1/2]     WARN: Linter. Line 34: self.build_requires is not callable
[10:10:21] :		 [Step 1/2] iodb/2.2.1@wsbu/stable exports: Copied 1 '.txt' file: version.txt
[10:10:21]W:		 [Step 1/2] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[10:10:21]W:		 [Step 1/2] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[10:10:21]W:		 [Step 1/2] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[10:10:21]W:		 [Step 1/2] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[10:10:21]W:		 [Step 1/2] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[10:10:21]W:		 [Step 1/2] /bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
[10:10:21] :		 [Step 1/2] iodb/2.2.1@wsbu/stable: Revision deduced by 'auto': f5b06687262d64b70d41a5241c5fea2130e9844d
[10:10:21] :		 [Step 1/2] iodb/2.2.1@wsbu/stable: A new conanfile.py version was exported
[10:10:21] :		 [Step 1/2] iodb/2.2.1@wsbu/stable: Folder: /home/captain/.conan/data/iodb/2.2.1/wsbu/stable/export
[10:10:21] :		 [Step 1/2] Configuration:
[10:10:21] :		 [Step 1/2] [settings]
[10:10:21] :		 [Step 1/2] arch=x86_64
[10:10:21] :		 [Step 1/2] arch_build=x86_64
[10:10:21] :		 [Step 1/2] build_type=Release
[10:10:21] :		 [Step 1/2] compiler=gcc
[10:10:21] :		 [Step 1/2] compiler.libcxx=libstdc++11
[10:10:21] :		 [Step 1/2] compiler.version=7
[10:10:21] :		 [Step 1/2] os=Linux
[10:10:21] :		 [Step 1/2] os_build=Linux
[10:10:21] :		 [Step 1/2] platform=x86_64
[10:10:21] :		 [Step 1/2] [options]
[10:10:21] :		 [Step 1/2] [build_requires]
[10:10:21] :		 [Step 1/2] [env]
[10:10:21] :		 [Step 1/2] 
[10:10:22] :		 [Step 1/2] Traceback (most recent call last):
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 1427, in run
[10:10:22] :		 [Step 1/2]     method(args[0][1:])
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/command.py", line 297, in create
[10:10:22] :		 [Step 1/2]     test_build_folder=args.test_build_folder)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 87, in wrapper
[10:10:22] :		 [Step 1/2]     return f(*args, **kwargs)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/conan_api.py", line 380, in create
[10:10:22] :		 [Step 1/2]     test_build_folder, test_folder, conanfile_path)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/create.py", line 41, in create
[10:10:22] :		 [Step 1/2]     test_build_folder=test_build_folder)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/cmd/test.py", line 42, in install_build_and_test
[10:10:22] :		 [Step 1/2]     keep_build=keep_build)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/manager.py", line 76, in install
[10:10:22] :		 [Step 1/2]     self._recorder, None)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_manager.py", line 141, in load_graph
[10:10:22] :		 [Step 1/2]     processed_profile=processed_profile)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_manager.py", line 232, in _load_graph
[10:10:22] :		 [Step 1/2]     profile_build_requires, recorder, workspace, processed_profile)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_manager.py", line 202, in _recurse_build_requires
[10:10:22] :		 [Step 1/2]     processed_profile)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_manager.py", line 224, in _load_graph
[10:10:22] :		 [Step 1/2]     graph = builder.load_graph(root_node, check_updates, update, remote_name, processed_profile)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_builder.py", line 39, in load_graph
[10:10:22] :		 [Step 1/2]     processed_profile)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_builder.py", line 99, in _load_deps
[10:10:22] :		 [Step 1/2]     processed_profile)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/graph_builder.py", line 242, in _create_new_node
[10:10:22] :		 [Step 1/2]     check_updates, update, remote_name, self._recorder)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/proxy.py", line 28, in get_recipe
[10:10:22] :		 [Step 1/2]     result = self._get_recipe(conan_reference, check_updates, update, remote_name, recorder)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/graph/proxy.py", line 48, in _get_recipe
[10:10:22] :		 [Step 1/2]     metadata = self._client_cache.load_metadata(reference)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/client/client_cache.py", line 308, in load_metadata
[10:10:22] :		 [Step 1/2]     return PackageMetadata.loads(text)
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/model/package_metadata.py", line 88, in loads
[10:10:22] :		 [Step 1/2]     ret.recipe = _RecipeMetadata.loads(data.get("recipe"))
[10:10:22] :		 [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/conans/model/package_metadata.py", line 33, in loads
[10:10:22] :		 [Step 1/2]     ret.time = data["time"]
[10:10:22] :		 [Step 1/2] KeyError: 'time'
[10:10:22] :		 [Step 1/2] 
[10:10:22] :		 [Step 1/2] ERROR: 'time'
[10:10:23]W:		 [Step 1/2] Process exited with code 1
```

**Comment by memsharded** [comment] 2019-04-02 16:52
I think that is an issue exclusively of an older version, it has been addressed in later versions with:

```python
        ret.time = data.get("time")
```
So it shouldn't fail anymore.
If the caches are not fully isolated to be using the same Conan version, that could be the issue.

cc/ @lasote

**Comment by reneme** [comment] 2019-04-25 15:37
We naïvely created a `.conan` directory that is shared among short-lived docker containers in our CI. As we rebuilt the docker image today for testing purposes, we started seeing this issue sporadically. Apparently our older docker image contains an older version of conan, that has trouble with the entries created by the newer version in the shared `.conan` directory during testing. Since we switched all our builds to the new docker image, the issue seems to be gone.

**Comment by DavidZemon** [comment] 2019-06-22 02:09
I upgraded all of our Docker images and CI infrastructure to 1.16.0 shortly after it was released (whenever that was... a month ago ish?) and I haven't run into this issue in quite a while. Whatever the problem was, I'd say it's safe to say we're past it.

Btw... I'm sure this isn't the "right" place to post this, but I think it's as good as anywhere and you can move it elsewhere if you'd like. As you know, I've run into a lot of issues building Conan packages on our CI server, and one of the reasons for that has been mis-matched Conan versions between the CI server and the Docker images it is using (because I try to reuse the Conan cache, rather than letting it get deleted at the end of a build). So, today and yesterday I worked through the latest upgrade problem and the result is the following script, which runs at the beginning of every Conan-related build:

```sh
if [[ -f conanfile.py ]] ; then
  set -ex
  remotes_count=$(conan remote list | wc -l)
  if [[ 0 == "${remotes_count}" ]] ; then
    conan remote add ci %ARTIFACTORY_URL%
  elif [[ 1 != "${remotes_count}" ]] ; then
    # Shouldn't have more than one remote. Remove all data and all remotes and start over.
    conan remove -f "*"
    remote_names=$(conan remote list --raw | cut -d' ' -f1)
    for remote_name in ${remote_names} ; do
      conan remote remove "${remote_name}"
    done
    conan remote add ci %ARTIFACTORY_URL%
  fi
  conan user -c
  conan user -r ci -p %CONAN_PASSWORD% teamcity
fi
```

In this case, we're expecting exactly one Conan remote to exist, because we're now taking advantage of virtual Conan repositories in Artifactory (THANK YOU FOR IMPLEMENTING THIS!), but the ideas shown in the above script could be easily enough adapted to anyone else's use case that might have more than one Conan remote.

The latest bug I ran into was because the previous version of the above script basically did a `conan remote remove && conan remote add && conan user`, but that set all existing packages in cache as `{remote: null}` which then resulted in errors, so I had to ensure that any time we did a `conan remote remove`, we also did a full cache clear.

**Comment by danimtb** [comment] 2019-07-12 07:22
Hi @DavidZemon,

Glad you had the original issue solved and that you are taking advantage of the Artifactory Virtual repositories! 😄 

Regarding the new issue with `{remote: null}`, this is a common operation performed in the packages metadata so the packages are downloaded from the same remote in subsequent ``conan install`` calls.

Please, if you still experience this issue I'd suggest you to close this issue (as the original problem was solved, and open a new one explaining the errors you commented and the commands to reproduce them. It would be much easier for us to track it down that way.

Thanks a lot 😄

**Comment by memsharded** [comment] 2023-06-25 22:14
This issue is now very outdated with Conan 2.0, that has changed all that involved code, closing the issue.

**Closed by memsharded** 2023-06-25 22:14 UTC
Labels: Feedback please!, stage: triaging
