### ISSUE TITLE
[RFC] Package recipe declare remotes to auto-add for requirements

### ISSUE THREAD

**Issue by jinq0123** [conan-io/conan#1567] opened 2017-08-04 03:38 UTC
I created a gRPC package `gRPC/1.4.2@jinq0123/stable` and uploaded it to bintray `https://api.bintray.com/conan/jinq0123/test`. My grpc_cb library requires this gRPC package. How can I write this requirement in conanfile.py?
```
class grpccbConan(ConanFile):
    url = "https://github.com/jinq0123/grpc_cb"
    # How to require a package on https://api.bintray.com/conan/jinq0123/test ?
    requires = "gRPC/1.4.2@jinq0123/stable"
```
Or how to upload `gRPC/1.4.2@jinq0123/stable` to conan-center?

**Comment by memsharded** [comment] 2017-08-04 08:08
The package requirements declaration is decoupled from the origin. This is a typical orthogonal design, the same as the ``#include``s, they say what they need, but it is the build system the one providing the include-paths to find them, so the same code can work in different computers.

So, in the package recipe, you cannot specify a remote, because that would break that decouple and users wouldn't be able to use the remotes they want. A typical approach in conan is users copying and storing packages in their own remotes (like in-house remotes, so they don't depend on external infrastructure).

To use the packages from your remote, you need to add such remote:

```bash
$ conan remote add myremote https://api.bintray.com/conan/jinq0123/test 
```

You have more details about it in: http://docs.conan.io/en/latest/packaging/bintray/move.html

**Comment by jinq0123** [comment] 2017-08-04 12:22
Whatever the design, orthogonal or non-orthogonal, it must be designed to make the usage simple.

In the `#include` case, `conan` makes it simple to set the include path. Without `conan`, I must set the include path for every dependency library.

And there can be some tool to make conan remote management simple, for example, using
```
conan install . --auto_add_remote
```
to add remote temporary for library that missed in the current remote list.

I suggest to set a default remote in connanfile.py, like:
```
class GrpccbConan(ConanFile):
    requires = "[https://api.bintray.com/conan/jinq0123/test] gRPC/1.4.2@jinq0123/stable"
```

**Comment by memsharded** [comment] 2017-08-04 14:34
I am not sure that users would like remotes being added on the fly.
But I am open to this suggestion, lets see what other users think about it.

**Comment by promgamer** [comment] 2018-04-19 10:16
I'm trying to set up a CI environment for our project (that uses conan) and I think this would be a good feature.

Right now, I've phase on the CI which adds the remotes we need, which is OK, I guess. Thing is, when we try to have incremental builds (for fast CI), adding a remote that already exists gives an error, which makes the build fail.

**Comment by memsharded** [comment] 2018-04-19 11:15
@promgamer I think your suggestion is more in the line of the latest suggestion of https://github.com/conan-io/conan/issues/2618, which is a ``--force`` flag, though there are some things to polish there. Please follow conversation there.

In any case, I'd like to suggest that for CI (and for developers) to use the ``conan config install`` feature, with a ``remotes.txt`` file, that will completely redefine remotes. Even for incremental builds, it is fine, it should be a very fast operation, and it ease the task of better reproducible environments.

**Comment by matthew-d-jones** [comment] 2018-07-27 11:30
What about the ability to add a suggested remote for each required package? If the package is not found in current configured remotes then Conan could at least return the suggested remote in the error.
I currently keep a list of remotes to configure in the README for each of my projects, the problem is that this can easily get out of sync with the real requirements of the conanfile. If suggested remotes could be added to the conanfile then at least everything is defined in one place.

**Comment by memsharded** [comment] 2018-07-27 11:51
Hi @matthew-d-jones 

Yes, that would be related to what is described in https://github.com/conan-io/conan/issues/2091.
Still we believe it shouldn't be in the conanfiles, but in another file, though transitivity has to be considered.

**Comment by groovyd** [comment] 2018-10-01 20:40
We have run up against this issue a number of times mostly because people have stewn about a bunch of repos they expect everyone to add to their registry and then sometimes they have same named and version forks of other packages that are not always actually producing the same binaries for whatever reason.  In this case it is hard to pin down the problem but it would be very nice if you could force conan to pull certain requirements from hard-coded repos in the conanfile itself as suggested by the op.  While it is true this then places non-orthogonal aspects into recipes it can solve the user's problem without requiring them to construct private repos with further copies of said packages which only further inflates the issue for everyone else.  The only way to fix this is for everyone to use the exact same registry of repos in the exact same order.

**Comment by Maddimax** [comment] 2019-04-13 11:28
Allowing requires to specify the remote is something I wish for as well.

**Comment by ruipacheco** [comment] 2019-06-24 10:06
+1

**Comment by muzammil360** [comment] 2020-11-25 10:57
+1. I am trying to push a package to gitlab and it gives me the error that username is too long. (should be less than 51 char). Now for gitlab, I have to add a new project based remote. If only I can add it in conanfile, it will make my life simpler. But now I need to manually add that remote everytime I try to pull this. Furthermore, a new user in team will have no idea why he can't pull it unless he really knows what's happening.

**Comment by memsharded** [comment] 2020-11-25 11:10
Hi all

This is a long standing request, and we have learned a lot since then. We have learned from many companies having projects with thousands of packages, and from open source users.

We can conclude that putting the remote information into recipes is a bad idea. It completely breaks possible ownership of packages (the flow that ``conan download`` + ``conan upload`` a package, to store a copy of it in your own repository, to isolate your builds, is an extremely popular flow). Packages should be able to be moved between repositories without problems. The "promotion" mechanism of package is a best practice is package management and devops, and this feature will violate it.

So I am going to close this feature request as "wont fix".

This doesn't mean that other approaches are possible. Of course the ``conan config install`` is the best current resource, it is extremely convenient and easy to manage, and it can manage and define remotes easily. This means, that you can easily have a "remotes.txt" file in your repo and do ``conan config install remotes.txt``.

**Closed by memsharded** 2020-11-25 11:10 UTC
Labels: Feedback please!, type: feature
