### ISSUE TITLE
aborting conan may result in corrupted package

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#2508] opened 2018-02-22 02:37 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

if press Ctrl-C / Ctrl-Break at the right timing, more specifically, during the `Downloading conan_package.tgz` message, you will get corrupted conan package.
conan will not attempt to re download package, and will think package is installed until you explicitly remove it by `conan remove -f packege_name/*`

conan 1.0.4
Windows 10

- remove package, e.g. `conan remove -f OpenSSL/*`
- run some command to create package depending on OpenSSL, like `conan create . bincrafters/testing`
- press Ctrl-C during the `Downloading conan_package.tgz` message
- run again `conan create . bincrafters/testing`
- check out %USERPROFILE%\.conan\data\OpenSSL directory for the corrupted package

**Comment by memsharded** [comment] 2018-02-22 08:30
I think this might be a duplicate of https://github.com/conan-io/conan/issues/1003.

Please check and close this one if true, follow up conversation there. Thanks!

**Closed** 2018-02-22 08:58 UTC
Labels: duplicate
