### ISSUE TITLE
[bug] Ninja + VS2019 + CMake uses GNU compiler

### ISSUE THREAD

**Issue by stefan-gavranovic** [conan-io/conan#6477] opened 2020-02-06 00:57 UTC
### Environment Details
  * Windows 10 V1809
  * Compiler+version: VS2019 v16.4.3
  * Conan version: 1.20.5
  * Python version: 3.7

### Steps to reproduce 
I am having issue creating package using Ninja generator with VS2019. Creating simple `Hallo World` example  fails to use VS compiler and instead detects GNU compiler that is installed on my system. 

```bash
conan new Hello/0.1 -t

conan create . demo/testing
```

Content of my default profile: 
```yaml
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
```

I assume this issue is connected to #6447

### Logs (Executed commands with output) (Include/Attach if Applicable)

```bash 
λ conan create . demo/testing

Exporting package recipe
Hello/0.1@demo/testing: A new conanfile.py version was exported
Hello/0.1@demo/testing: Folder: C:\Users\master\.conan\data\Hello\0.1\demo\testing\export
Hello/0.1@demo/testing: Exported revision: 63cc37eddccf71c6881f09ba08f90a4a
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
CONAN_CMAKE_GENERATOR=Ninja
Hello/0.1@demo/testing: Forced build from source
Hello/0.1@demo/testing (test package): Installing package
Requirements
    Hello/0.1@demo/testing from local cache - Cache
Packages
    Hello/0.1@demo/testing:3fb49604f9c2f729b85ba3115852006824e72cab - Build

Hello/0.1@demo/testing: Configuring sources in C:\Users\master\.conan\data\Hello\0.1\demo\testing\source
Cloning into 'hello'...
Hello/0.1@demo/testing: Copying sources to build folder
Hello/0.1@demo/testing: Building your package in C:\Users\master\.conan\data\Hello\0.1\demo\testing\build\3fb49604f9c2f729b85ba3115852006824e72cab
Hello/0.1@demo/testing: Generator cmake created conanbuildinfo.cmake
Hello/0.1@demo/testing: Calling build()
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.4.4
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Check for working C compiler: D:/ProgramData/chocolatey/bin/gcc.exe
-- Check for working C compiler: D:/ProgramData/chocolatey/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/ProgramData/chocolatey/bin/c++.exe
-- Check for working CXX compiler: D:/ProgramData/chocolatey/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: called inside local cache
-- Conan: Adjusting output directories
-- Conan: Using cmake global configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
CMake Error at ../conanbuildinfo.cmake:500 (message):
  Incorrect 'Visual Studio'.  Toolset specifies compiler as 'MSVC' but CMake
  detected 'GNU'
Call Stack (most recent call first):
  ../conanbuildinfo.cmake:139 (conan_check_compiler)
  CMakeLists.txt:5 (conan_basic_setup)


-- Configuring incomplete, errors occurred!
See also "C:/Users/master/.conan/data/Hello/0.1/demo/testing/build/3fb49604f9c2f729b85ba3115852006824e72cab/CMakeFiles/CMakeOutput.log".
Hello/0.1@demo/testing:
Hello/0.1@demo/testing: ERROR: Package '3fb49604f9c2f729b85ba3115852006824e72cab' build failed
Hello/0.1@demo/testing: WARN: Build folder C:\Users\master\.conan\data\Hello\0.1\demo\testing\build\3fb49604f9c2f729b85ba3115852006824e72cab
ERROR: Hello/0.1@demo/testing: Error in build() method, line 29
        cmake.configure(source_folder="hello")
        ConanException: Error 1 while executing cd C:\Users\master\.conan\data\Hello\0.1\demo\testing\build\3fb49604f9c2f729b85ba3115852006824e72cab && cmake -G "Ninja" -DCONAN_LINK_RUNTIME="/MD" -DCMAKE_BUILD_TYPE="Release" -DCONAN_EXPORTED="1" -DCONAN_IN_LOCAL_CACHE="ON" -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="16" -DCONAN_CXX_FLAGS="/MP8" -DCONAN_C_FLAGS="/MP8" -DBUILD_SHARED_LIBS="OFF" -DCMAKE_INSTALL_PREFIX="C:\Users\master\.conan\data\Hello\0.1\demo\testing\package\3fb49604f9c2f729b85ba3115852006824e72cab" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -Wno-dev C:\Users\master\.conan\data\Hello\0.1\demo\testing\build\3fb49604f9c2f729b85ba3115852006824e72cab\hello
```

**Comment by memsharded** [comment] 2020-02-06 08:40
Hi @stefan-gavranovic 

I think this is a duplicate of https://github.com/conan-io/conan/issues/6447. Please check it, and close this issue if true and follow up on that one. 

You can define CC=cl.exe and CXX=cl.exe in your profile file to make it work.

**Comment by stefan-gavranovic** [comment] 2020-02-06 09:03
Hi @memsharded 

Declaring CC=cl.exe and CXX=cl.exe did help. The only difference to the #6447 issue is the use of environment variable in the profile instead of:
`cmake = CMake(self, generator="Ninja")` 
in the `conanfile.py` but I guess it is the same thing. 
I will close this issue. 
Thanks a lot.

**Closed** 2020-02-06 09:03 UTC
Labels: stage: triaging

**Comment by memsharded** [comment] 2020-02-06 09:48
> in the conanfile.py but I guess it is the same thing.

Yep, the same thing. Lets continue in the other issue, thanks!
