### ISSUE TITLE
[feature] AutotoolsToolchain should support install_args analogous to make_args for consistency.

### ISSUE THREAD

**Issue by System-Arch** [conan-io/conan#12494] opened 2022-11-08 18:41 UTC
Hi @czoido, Hi @memsharded 

Thank you for quickly addressing the primary issue in #12470.  This feature request captures the second suggestion proffered there:
 

> Some Makefiles don't do well with parallel execution (-j > 1) during the install phase, and thus it would be nice if AutotoolsToolchain supported an additional attribute called "install_args" analogous to "make_args" as the only place one can disable parallel execution today is via make_args and that affects both the "make" and "install" Autotools methods.

If one tries to specify -j1 via autotools.install(args=["-j1"]), they suffer two consequences:

1. The -j1 has no effect because the resulting make invocation has both -j1 and -jN and the latter wins.
2.  The default DESTDIR value is lost unless it is explicitly added to the args value.

Thanks

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by System-Arch** [comment] 2022-11-08 18:47
Here's how this is currently documented:

> This generator will also generate a file called conanbuild.conf containing two keys:
> 
> configure_args: Arguments to call the configure script.
> make_args: Arguments to call the make script.
> autoreconf_args: Arguments to call the autoreconf script.

and I am suggesting that it read:

> This generator will also generate a file called conanbuild.conf containing four keys:
> 
> configure_args: Arguments to call the configure script.
> make_args: Arguments to call the make script with when invoking the default target
> install_args: Arguments to call the make script with when invoking the install target
> autoreconf_args: Arguments to call the autoreconf script.

**Comment by SpaceIm** [comment] 2022-11-09 18:20
Possible duplicate of https://github.com/conan-io/conan/issues/12296

**Comment by czoido** [comment] 2022-11-10 12:16
Hi @System-Arch , @SpaceIm 

I have opened https://github.com/conan-io/conan/pull/12505 to address this issue

**Comment by czoido** [comment] 2022-11-10 12:20
> Here's how this is currently documented:
> 
> > This generator will also generate a file called conanbuild.conf containing two keys:
> > configure_args: Arguments to call the configure script.
> > make_args: Arguments to call the make script.
> > autoreconf_args: Arguments to call the autoreconf script.
> 
> and I am suggesting that it read:
> 
> > This generator will also generate a file called conanbuild.conf containing four keys:
> > configure_args: Arguments to call the configure script.
> > make_args: Arguments to call the make script with when invoking the default target
> > install_args: Arguments to call the make script with when invoking the install target
> > autoreconf_args: Arguments to call the autoreconf script.

This is documenting that these variables are passed from the `AutotoolsToolchain` to the `Autotools` build helper, but `install_args` can't be modified in `AutotoolsToolchain` so it's not included in that file and that's why there are only three keys in the file.

**Comment by System-Arch** [comment] 2022-11-10 17:24
Hi @czoido,

Yes, I was using the doc as a way of suggesting the addition of an extra key for install_args, however, your alternative of allowing -j1 to be passed in via args addresses my original use case and, in fact, aligns with what I originally tried/expected as a solution. It was only when my args -j1 value was ignored that I dug into the implementation of autotools.install() and autotools.make(). Thanks

**Closed as completed** 2022-11-15 21:55 UTC
