### ISSUE TITLE
[bug] download sources for corrupted conan recipes

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#7795] opened 2020-10-02 10:16 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: any
  * Compiler+version: any
  * Conan version: 1.28.*; 1.29.2
  * Python version: 3.8.5

### Steps to reproduce (Include if Applicable)
Happens sporadically, when local recipe cache is corrupted
conan install pcre/8.41@ -r conan-center -pr debug --build outdated -u

### Logs (Executed commands with output) (Include/Attach if Applicable)

conan install pcre/8.41@ -r conan-center -pr debug --build outdated -u
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=Visual Studio
compiler.cppstd=14
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
*:fPIC=True
[build_requires]
[env]

bzip2/1.0.8: WARN: Can't update, no package in remote
bzip2/1.0.8: Package is up to date
zlib/1.2.11: WARN: Can't update, no package in remote
zlib/1.2.11: Package is up to date
pcre/8.41: WARN: Package is corrupted, removing folder: C:\Users\malas\.conan\data\pcre\8.41\_\_\package\bc41b64ba6c37efe48137d2bb0b024f3d580dc29
Installing package: pcre/8.41
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
    pcre/8.41 from 'conan-center' - Cache
    zlib/1.2.11 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:cc781f9bb12181ae8241d49eb8f67780d0c9e108 - Cache
    pcre/8.41:bc41b64ba6c37efe48137d2bb0b024f3d580dc29 - Build
    zlib/1.2.11:402cf37ea699030d7c8abcaa214949592ce22e9b - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
zlib/1.2.11: Already installed!
pcre/8.41: WARN: Build folder is dirty, removing it: C:\Users\malas\.conan\data\pcre\8.41\_\_\build\bc41b64ba6c37efe48137d2bb0b024f3d580dc29
ERROR: The 'pcre/8.41' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.

This bug was reported in
https://github.com/conan-io/conan-center-index/issues/3032
https://github.com/conan-io/conan-center-index/issues/3067

**Comment by memsharded** [comment] 2020-10-15 14:16
Hi @AndreyMlashkin 

I have been trying the last days to reproduce this or to understand how this is possible, but no success so far.
As it was pointed in conan-io/conan-center-index#3067, some hints:

```
bzip2/1.0.8: WARN: Can't update, no package in remote
bzip2/1.0.8: Package is up to date
zlib/1.2.11: WARN: Can't update, no package in remote
zlib/1.2.11: Package is up to date
```
This means that it is not finding bzip2 or zlib in ConanCenter, which  shouldn't be happening, bzip2 and zlib are always there. 
Is it possible that you have been changing or re-defining the ``conan-center`` remote to point elsewhere? Did you add or remove remotes at some point? are you using any other remote?

**Comment by AndreyMlashkin** [comment] 2020-10-17 11:45
Indeed, I have a private repository in artifactory, which I am deleting from time to time to test something from scratch.

Unfortunately, I also couldn't find a pattern, when an error occurs to reproduce it.

**Comment by AndreyMlashkin** [comment] 2020-12-11 08:33
I have this bug again, this time I haven't switched the servers

PS E:\sources\build_debug_studio> **conan install bzip2/1.0.8@ -u -r conan-center**
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

bzip2/1.0.8: WARN: Can't update, no package in remote
Installing package: bzip2/1.0.8
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Cache

Installing (downloading, building) binaries...
bzip2/1.0.8: Already installed!
PS E:\sources\build_debug_studio> **conan install bzip2/1.0.8@ -u -r conan-center --build bzip2**
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

bzip2/1.0.8: Forced build from source
Installing package: bzip2/1.0.8
Requirements
    bzip2/1.0.8 from 'conan-center' - Cache
Packages
    bzip2/1.0.8:d16a91eadaaf5829b928b12d2f836ff7680d3df5 - Build

Installing (downloading, building) binaries...
ERROR: 404: Not Found. [Remote: conan-center]
The 'bzip2/1.0.8' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.


PS E:\sources\build_debug_studio> **cd E:\conan\bzip2\1.0.8\_\_**
PS E:\conan\bzip2\1.0.8\_\_> **dir**


    Directory: E:\conan\bzip2\1.0.8\_\_


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       12/10/2020  10:21 PM                dl
d-----       12/10/2020  10:22 PM                export
d-----       12/10/2020  10:22 PM                locks
d-----       12/10/2020  10:22 PM                package
d-----       12/11/2020   9:21 AM                build
-a----       12/10/2020  10:22 PM              0 metadata.json.lock
-a----       12/10/2020  10:22 PM            946 metadata.json

**Comment by Fefer-Ivan** [comment] 2020-12-11 12:04
We have encountered the same or similar bug. It appeared after we added conan.conf with general.revisions_enabled = 1 to support our artifactory (but it can be reproduced only using conan-center).

$ python3 --version
Python 3.6.9
$ conan --version
Conan version 1.32.0

Here are our steps to reproduce: 

0. Remove .conan to have a clear conan installation.
1. Install snappy/1.1.8 package in your conan installation. We use `conan install --build=missing conanfile.txt` with conanfile.txt attached to this comment. It should be successful.
2. Replace .conan/data/snappy directory with one attached to this comment. This directory is snappy directory from when we encountered that bug. It is a result of some valid conan calls, but we were not able to reproduce how exactly it arrived to it's current state.
3. Add general.revisions_enabled = 1 to your conan.conf. We use `conan config install conan.conf` with conan.conf attached to this comment.
4. Try installing snappy/1.1.8 again.
5. You should get following logs: 
```
snappy/1.1.8: WARN: Package binary is corrupted, removing: 50a5030bbbb13ae56bc4be41915ecd48549cb895
conanfile.txt: Installing package
Requirements
    snappy/1.1.8 from 'conan-center' - Cache
Packages
    snappy/1.1.8:50a5030bbbb13ae56bc4be41915ecd48549cb895 - Build
 
Installing (downloading, building) binaries...
snappy/1.1.8: WARN: Build folder is dirty, removing it: /home/ivanfefer/.conan/data/snappy/1.1.8/_/_/build/50a5030bbbb13ae56bc4be41915ecd48549cb895
ERROR: 404: Not Found. [Remote: conan-center]
The 'snappy/1.1.8' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```
6. If you set general.revisions_enabled to 0, everything will be fine.

[conanfile.txt](https://github.com/conan-io/conan/files/5678990/conanfile.txt)
[snappy.zip](https://github.com/conan-io/conan/files/5678991/snappy.zip)
[conan.conf.txt](https://github.com/conan-io/conan/files/5678998/conan.conf.txt)

**Comment by floriansimon1** [comment] 2021-01-20 17:41
I faced the same issue with `glslang/8.13.3559#7f2991c495da698a6669984099df0866`. I downloaded it from `conan-center`, built my binaries and tried to upload them back to our own Artifactory server. When trying to upload them, Conan gives me the following error:

```
Uploading to remote 'xxx':
Uploading spirv-headers/1.5.3 to remote 'xxx'
ERROR: spirv-headers/1.5.3: Upload recipe to 'xxx' failed: The 'spirv-headers/1.5.3' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

We do also have `CONAN_REVISIONS_ENABLED` set to 1. Let me know if I can give you more details to help you reproduce the issue.

`spirv-header` is a dependency of `glslang`.

**Comment by floriansimon1** [comment] 2021-01-27 13:02
We got this again today:
```
Uploading to remote 'xxx':
Uploading fmt/7.1.3 to remote 'xxx'
ERROR: fmt/7.1.3: Upload recipe to 'xxx' failed: The 'fmt/7.1.3' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

Like spirv-header, fmt is also the dependency of a dependency. Is that why this fails?

**Comment by dfontenot** [comment] 2021-09-05 05:58
Running into this issue when trying to install di/1.2.0. I have `CONAN_REVISIONS_ENABLED=1` since my conanfile for my project uses a dependency from bincrafters which requires this setting.

If I set revisions enabled in the conan config:
```
di/1.2.0: WARN: Package binary is corrupted, removing: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Installing (downloading, building) binaries...
di/1.2.0: WARN: Build folder is dirty, removing it: /home/david/.conan/data/di/1.2.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: 404: Not Found. [Remote: conancenter]
The 'di/1.2.0' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

Slightly different error message if I don't set that config value but I pass in CONAN_REVISIONS_ENABLED=1 env var
```
di/1.2.0: WARN: Build folder is dirty, removing it: /home/david/.conan/data/di/1.2.0/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
ERROR: 404: Not Found. [Remote: conancenter]
The 'di/1.2.0' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

The 404 is really strange because it definitely exists
```
$ conan search 'di/*' -r=all
Existing package recipes:

Remote 'conan-center':
di/1.1.0
di/1.2.0
Remote 'conancenter':
di/1.1.0
di/1.2.0
```

**Comment by celonymire** [comment] 2021-09-23 05:15
Same issue here...
```
❯❯❯ conan install .. --build
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=10
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

brotli/1.0.9: Forced build from source
conanfile.txt: Installing package
Requirements
    brotli/1.0.9 from 'conancenter' - Cache
Packages
    brotli/1.0.9:c6817f477abe7e9a917b102f37dc1fd0c2d95f50 - Build

Installing (downloading, building) binaries...
brotli/1.0.9: WARN: Build folder is dirty, removing it: C:\Users\Sam Huang\.conan\data\brotli\1.0.9\_\_\build\c6817f477abe7e9a917b102f37dc1fd0c2d95f50
ERROR: 404: Not Found. [Remote: conancenter]
The 'brotli/1.0.9' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.
```

**Comment by anderson-dev** [comment] 2022-04-06 17:31
We're seeing this issue creep up more and more as well.
```
conan config install remotes.txt # defines both center.conan.io & our private repo url
conan config install global.conf # defines default build host
conan config install conan.conf # enables revisions
```
is being called every restore via our custom build scripts to ensure that all of our devs have connection to our private artifactory, enable revisions, and enable default build host.

`conan remove` offending recipe and trying again seems to work but I get a call from a dev puzzled as to what is going on and it seems to be happening more and more often.

Maybe my info here gives a little more insight into what may be causing these recipes to become corrupted

**Comment by heilkn** [comment] 2022-07-15 09:09
Dear conan team, I can confirm that we my colleagues and I are facing the same issue. It would be 
great if the software could deal with that situation without requiring user interaction.

My current workaround is to manually delete all flagged packages and rerun conan until it passes, but this is very annoying.

Kind regards

Konstantin

**Comment by tmoonlight** [comment] 2022-07-22 13:04
Mark. Such an annoying problem.

**Comment by andreya108** [comment] 2023-08-08 07:10
I agree very annoying!
Why not download missing sources automatically with --build=missing? Or make special cli option allowing it...

**Comment by memsharded** [comment] 2023-08-08 08:15
Hi all,

Thanks all for the feedback. Not sure if everyone in this thread is referring to the same issue. If it is:

> ERROR: The 'pcre/8.41' package has 'exports_sources' but sources not found in local cache.
Probably it was installed from a remote that is no longer available.

This is not a bug. It is totally expected and it happens when the remote that contains the *exported* sources (not the original sources downloaded from the internet, but the files that were exported together with the conanfile.py as sources) have not been downloaded and it is necessary to upload the files to another server and the original remote has been removed from the list of remotes, then it is physically impossible to download those files. The normal http ``dowload(..., url)`` files are always downloaded when ``--build=missing``, and the exported sources are always downloaded, as the ``remote`` containing them is defined and hasn't been deleted.

As it is not clear anymore what the issue could be in those cases, and the original issue is from 3 years ago and more than 30 versions ago, and there is also a major 2.0 release, I am closing this ticket.

If you are experiencing this issue, I'd encourage to submit a new ticket explaining the details and providing clear steps to reproduce it. Thanks very much!

**Closed as completed by memsharded** 2023-08-08 08:15 UTC
Labels: stage: triaging
