### ISSUE TITLE
[bug] Strange CI issue with test packages

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#8744] opened 2021-03-31 13:16 UTC
I have just encountered a very strange CI issue in our build.
The error output is:
```
14:19:18  hdf5/1.8.21@user/stable: WARN: Forced CMake build type ('Debug') different from the settings build type ('None')
14:19:18  hdf5/1.8.21@user/stable: WARN: Forced CMake build type ('Release') different from the settings build type ('None')
14:19:18  ERROR: Something failed while testing 'hdf5/1.8.21@user/stable' test_package after it was built using the lockfile. Please report this error: 'NoneType' object has no attribute 'name'
14:19:18  Command 'conan create --lockfile conan.lock packages/hdf5/all hdf5/1.8.21@user/stable' has failed
```
What we do is to build a set of packages that are required when users want to build our apps.
Locally, it works just fine. But on the CI, there is no `build` folder created inside the `test_package` folder, and the whole behavior seems strange. Also there is obviously no build output.

This is the test_package recipe:

```
from conans import ConanFile, tools, CMake


class Hdf5TestConan(ConanFile):
    settings = "os", "compiler", "arch"
    generators = "cmake_paths"
    build_requires = "cmake/[>= 3.14.0]@user/stable"
    cmake = {}
    python_requires = "helper/0.0.5@user/stable"

    def build(self):
        if not self.settings.arch == 'armv8':
            for build_type in ["Debug", "Release"]:
                self.cmake[build_type] = CMake(self, build_type=build_type)
                self.cmake[build_type].definitions["CMAKE_TOOLCHAIN_FILE"] = self.python_requires["helper"].module.setup_toolchain_file()
                self.cmake[build_type].configure(build_folder=self.build_folder + "/" + build_type)
                self.cmake[build_type].build()

    def test(self):
        if not self.settings.arch == 'armv8':
            for build_type in ["Debug", "Release"]:
                self.cmake[build_type].test()
```
All our test_packages are more or less the same and we never had problems there. Only difference now is that we're passing the lockfile to the `conan create` command.

I am really at loss, because I cannot reproduce the error locally. Any conan settings that could influence the behavior? Any ideas / thoughts are highly appreciated!

**Comment by KerstinKeller** [comment] 2021-04-01 12:28
We're really at loss here, and any help is highly appreciated.
All Conan installations have been update to latest 1.35.0.
It is not due to the specific `test_package`, after removing the `hdf5` test alltogether, it now fails when creating / testing the next package in queue.

The workflow which the CI is using:
```
conan lock create path/to/app.py --build outdated --profile some_profile
conan lock build-order conan.lock --json=build_order.json
# then for each reference in build_order.json
conan create --lockfile conan.lock packages/path/to/ref ref/1.8.21@user/stable'
```
Executing this on CI fails, but locally on my PC, tests are executed just fine. On CI it fails with 
```
14:19:18  ERROR: Something failed while testing 'hdf5/1.8.21@user/stable' test_package after it was built using the lockfile. Please report this error: 'NoneType' object has no attribute 'name'
```
I do not know where / why the behavior local vs CI could be different. Configs should be the same, basically everything should be the same.

Also, the approach described above worked fine, when there was maybe only 1 reference in the `build_order.json` file. We now decided we wanted to move all packages to a new `user/channel`, and thus want to rebuild all required packages from scratch.
Still I don't know why it would work in one, but not the other case.

**Comment by memsharded** [comment] 2021-04-12 13:32
Hi @KerstinKeller 

Sorry for the delay in responding. I am having a look. So far it seems challenging, which was kind of expected if you couldn't reproduce it locally and only in CI, should be a weird bug.

Maybe if you could apply this patch in the CI Conan app, and run it, it will show more information:
```diff
diff --git a/conans/client/cmd/create.py b/conans/client/cmd/create.py
index a4aba6862..ae947da15 100644
--- a/conans/client/cmd/create.py
+++ b/conans/client/cmd/create.py
@@ -62,6 +62,8 @@ def create(app, ref, graph_info, remotes, update, build_modes,
                                        update, build_modes=None,
                                        test_build_folder=test_build_folder, recorder=recorder)
             except Exception as e:
+                import traceback
+                print(traceback.format_exc())
                 raise ConanException("Something failed while testing '%s' test_package after "
                                      "it was built using the lockfile. Please report this error: %s"
                                      % (str(ref), str(e)))
```

Is this possible, can you run this in CI?

**Comment by KerstinKeller** [comment] 2021-04-12 14:45
Hi @memsharded,
please see the attached trace:
```
16:42:51  Traceback (most recent call last):
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\cmd\create.py", line 61, in create
16:42:51      install_build_and_test(app, test_conanfile_path, ref, graph_info, remotes,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\cmd\test.py", line 26, in install_build_and_test
16:42:51      deps_install(app=app,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\manager.py", line 57, in deps_install
16:42:51      deps_graph = graph_manager.load_graph(ref_or_path, create_reference, graph_info, build_modes,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\graph\graph_manager.py", line 118, in load_graph
16:42:51      deps_graph = self._resolve_graph(root_node, profile_host, profile_build, graph_lock,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\graph\graph_manager.py", line 249, in _resolve_graph
16:42:51      deps_graph = self._load_graph(root_node, check_updates, update,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\graph\graph_manager.py", line 362, in _load_graph
16:42:51      self._recurse_build_requires(graph, builder, check_updates, update, build_mode,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\graph\graph_manager.py", line 343, in _recurse_build_requires
16:42:51      _recurse_build_requires(br_all, profile_build_requires)
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\graph\graph_manager.py", line 321, in _recurse_build_requires
16:42:51      nodessub = builder.extend_build_requires(graph, node, br_list, check_updates,
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\client\graph\graph_builder.py", line 94, in extend_build_requires
16:42:51      graph_lock.lock_node(node, build_requires, build_requires=True)
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\model\graph_lock.py", line 517, in lock_node
16:42:51      locked_id = self._match_relaxed_require(require.ref)
16:42:51    File "C:\Users\jenkinsuser\AppData\Roaming\Python\Python38\site-packages\conans\model\graph_lock.py", line 587, in _match_relaxed_require
16:42:51      if (ref.name == root_ref.name and ref.user == root_ref.user and
16:42:51  AttributeError: 'NoneType' object has no attribute 'name'
```
Is there any other information that I can provide?

**Comment by memsharded** [comment] 2021-04-12 16:57
This is good info, many thanks. I am following the trace back and trying to understand what could be failing. It is clear that build-requires in the test-package play an important role, I am trying to write a test.

**Comment by memsharded** [comment] 2021-04-12 17:56
I am trying a few things, but so far unable to reproduce it locally. Adding these to extra lines to the output might help:

```diff
diff --git a/conans/model/graph_lock.py b/conans/model/graph_lock.py
index bbdf27d47..faf623655 100644
--- a/conans/model/graph_lock.py
+++ b/conans/model/graph_lock.py
@@ -582,8 +582,10 @@ class GraphLock(object):
             version_range = version[1:-1]

         if version_range:
+            print("BUG_TRACE: Matching version_range for", ref)
             for id_, node in self._nodes.items():
                 root_ref = node.ref
+                print("BUG_TRACE: root_ref ", root_ref, node.path)
                 if (ref.name == root_ref.name and ref.user == root_ref.user and
                         ref.channel == root_ref.channel):
                     output = []
```

I keep investigating.

**Comment by memsharded** [comment] 2021-04-12 18:12
Also capturing and sharing the lockfile used in the ``conan create`` and that is producing the error will help. If it is private information, you can email it to info@conan.io

**Comment by KerstinKeller** [comment] 2021-04-12 19:55
These are the additional outputs:
```
21:52:24  BUG_TRACE: Matching version_range for cmake/[>= 3.14.0]@user/testing
21:52:24  BUG_TRACE: root_ref  None path\to\master\conanfile.py
```

I guess that must be the a build-requires of the test package.

**Comment by memsharded** [comment] 2021-04-13 08:08
I have reproduced the issue, and working on a fix for next 1.36.
In the meantime, to have your CI working, I suggest skipping the ``test_package`` with:

```
conan create --lockfile conan.lock packages/path/to/ref ref/1.8.21@user/stable --test-folder=None
```

As you are doing a "build-ordered" build, it is unlikely that broken packages will go undetected, as they are always consumed by downstream builds.

**Comment by KerstinKeller** [comment] 2021-04-13 08:21
Cool thanks for the feedback. We have disabled the tests as you described for now...

**Comment by memsharded** [comment] 2021-04-15 11:34
https://github.com/conan-io/conan/pull/8793 merged, this will be released in 1.36

**Closed as completed** 2021-04-15 11:33 UTC
Labels: type: bug

**Comment by KerstinKeller** [comment] 2021-04-23 11:57
@memsharded do you have a time plan for the 1.36 release? We already broke at least three if our packages because of tests not being executed (and found out the hard way in consumer builds not working any more), so we'd really like to be able to turn testing back on as soon as possible.

**Comment by memsharded** [comment] 2021-04-23 14:00
Hi @KerstinKeller 

Conan 1.36 will be released next week, most likely Tuesday or Wednesday, if nothing unexpected happens.
