### ISSUE TITLE
Removing a remote doesn't remove upstream entries from the registry

### ISSUE THREAD

**Issue by drussel** [conan-io/conan#3115] opened 2018-06-26 16:36 UTC
When you `conan remote remove` a remote, it leaves behind entries in the registry.txt referencing that remote as the upstream for packages. Then Conan will fail in hard to understand ways when trying to use those packages (since it is looking for a remote that no longer exists). It seems like the right thing to do is to delete those entries.

**Comment by memsharded** [comment] 2018-06-26 16:48
That would be a bug, indeed. The implemented behavior is that ``conan remote remove`` removes those entries, and this is tested in the test suite. Could you please provide some reproducible steps to do so?

**Comment by drussel** [comment] 2018-06-26 16:58
Has it always been that way or did it change in some (recentish) version? We dropped one of our remotes recently and had problems on a bunch of machines. We only figured out about the registry.txt containing upstream references at the end of cleaning it up, and so don't have a very good understanding of what failed when.

I'll see if I can reproduce it.

**Comment by drussel** [comment] 2018-06-26 17:05
Worked when I tried locally. So maybe it was due to old versions of conan being around.

Perhaps close the ticket and now that I understand about the file and that it is supposed to work, I'll be able to provide better info if we encounter it again,.

**Comment by memsharded** [comment] 2018-06-26 17:09
> Has it always been that way or did it change in some (recentish) version?

No, this hasn't change recently, should have worked the same even before conan 1.0

> So maybe it was due to old versions of conan being around.

Well, if it was a very old conan version, that could be the reason. Another possibility is that you had several concurrent works using the registry.txt file. Not all conan operation can work concurrently, specially those like removals shouldn't be executed concurrently with build operations.

Good, I will close this at the moment by merging the proposed PR. Thanks!

**Closed** 2018-06-26 17:09 UTC
Labels: in review
