### ISSUE TITLE
Generator for Conan

### ISSUE THREAD

**Issue by colinbrownec** [conan-io/conan#400] opened 2016-08-03 21:45 UTC
I am trying to set up my workflow to use a combination of CMake and Conan for dependency management. This is working fantastically except that my projects now requires Conan to be built.

This is fine, except that I'm not sure how to have Conan build a package that uses Conan.

In my project's `build` function,

``` python
cmake = CMake(self.settings)
self.run('mkdir build')
self.run('cd build && conan install ..')
self.run('cd build && cmake %s ../project' % cmake.command_line)
self.run('cd build && cmake --build . --target install %s' % cmake.build_config)
```

The `conan install ..` will drop any options the parent project has, dropping back to the defaults in `conan.conf`.

Is there a Conan generator similar to the CMake generator? 

If not I think a generator sounds appropriate and would be really simple to create and could try it myself.

My suggested solution would be something like,

``` python
cmake = CMake(self.settings)
conan = Conan(self.settings)
self.run('mkdir build')
self.run('cd build && conan install .. %s' conan.command_line)
self.run('cd build && cmake %s ../project' % cmake.command_line)
self.run('cd build && cmake --build . --target install %s' % cmake.build_config)
```

**Comment by memsharded** [comment] 2016-08-03 23:08
I think the issue is that you do not need to run the ``conan install`` inside your project ``build()`` method. Running ``conan install`` over your project conanfile.py, will install the requirements and generate (remember to set cmake generator) conanbuildinfo.cmake with the settings and options you want. They will be cached in the ``conaninfo.txt`` file, so when you afterwards run ``conan build`` it will use the settings and options to execute your project ``build()`` method.

Actually most packages with ``test_package`` work that way, they typical build method is just:

```python
def build(self):
        cmake = CMake(self.settings)
        self.run('cmake "%s" %s' % (self.conanfile_directory, cmake.command_line))
        self.run("cmake --build . %s" % cmake.build_config)
```
The internals of the ``conan test_package`` command are very simple, basically a ``conan install`` followed by a ``conan build``.

Please try that, and if not successful, tell me and we could setup a simple project in github with it. Thank you!

**Comment by Blubbz0r** [comment] 2016-08-04 08:29
Just as reference, since I was trying to do the same thing and the closed issue might have some more helpful details: #347.

**Comment by colinbrownec** [comment] 2016-08-04 21:27
So here is my actual problem (this has turned into more of a question than an issue...)

I see that `conan install` is not neccassary, and a `conanbuildinfo.cmake` is generated. My problem is I guess I don't know how to reference it.

My `source()` is a simple `git clone` so my conan build folder looks like
```
64e793d55116d7ff6a1ba115dd066987bceaddc0
|-- build
|-- project
|   |-- src
|   +-- CMakeLists.txt
|-- conanbuildinfo.cmake
+-- conanfile.py
```

I think I see two solutions. 

1. Create another simple `CMakeLists .txt` to live in the root folder that will import conan and include the `CMakeLists.txt` in `project`.

2. Move `conanbuildinfo.cmake` to `project/conanbuildinfo.cmake` in the top of the `build` function.

Is there a more preferred way to do this?

**Comment by colinbrownec** [comment] 2016-08-04 22:05
This what I am currently doing, my solution number 2 requires much less code. I've modified my `build()` function to look like.
``` python
self.run('mkdir build')
shutil.copy('conanbuildinfo.cmake', 'build')
self.run('cd build && cmake %s ../project' % cmake.command_line)
self.run('cd build && cmake --build . --target install %s' % cmake.build_config)
```

I feel like this does not fit very nicely with the rest of Conan. I don't think the user actually needs to move around files generated by Conan, so this seems a little awkward. I would still be interested in a different solution.

**Comment by memsharded** [comment] 2016-08-04 22:43
Just a quick question, about your sources() of your project doing a clone. If you are working on it, i.e. developing your project, it is not very convenient to have sources() cloning it. You can put the conanfile.py in your project too. 

On the other hand, I agree, it shouldn't be necessary to move conan generated files, I am having a look into it, will setup an example project to work with.

**Comment by memsharded** [comment] 2016-08-04 23:03
I have setup an example project: https://github.com/memsharded/example_build
It seems that you are doing an out-of-source build (which is perfect, is the way to go), so I have added steps in the repo README for an out of source build:

- The ``conan install`` generates the conanbuildinfo.cmake in the current directory. 
- The build also execute in the current directory (but can be pointed to the source directory, as the conan install or as cmake would do)

Maybe the thing is to use ``self.conanfile_directory`` inside the recipe, so cmake references easily to the project dir? Please check it and tell me if this is what you need. Thank you!

**Comment by colinbrownec** [comment] 2016-08-05 16:42
Thanks for the help so far.

My problem is different from yours in that my project is also a dependency for other projects. I believe the simplest way to replicate my problem is to add a `test_package`.

I've made a minimal example of my own problem: https://github.com/colinbrownec/conan-problem

It also might be worth taking a step back to describe how I am hoping to use Conan.

I am hoping to use Conan to contain build instructions and pre-build binaries for other developers to pull. I want to keep all source code in Git so that Conan doesn't need to manage source files and I can still control source access with Git. Ideally the only export will be the `conanfile.py`

This has led me to have a simple
```
def source(self):
  self.run('git clone repourl --branch branchname')
```

I believe the way I am trying to set up Conan is part of this problem, as I also had trouble turning my libraries into Conan packages, because I would need to keep updating the Git tag on the server for my `build` function to pull any code I changed (I would also need to do a `conan remove <package>` since Conan would think it already had up-to-date source code).

**Comment by memsharded** [comment] 2016-08-05 17:11
Using just conanfile.py as exported and keeping all code in github repos is perfectly fine.

Maybe you want to have a look to the (just released in 0.11) ``build_policy`` feature: http://docs.conan.io/en/latest/conanfile_py.html?highlight=build_policy#build-policies

Maybe setting it to ``always`` and using a branch instead of a tag, will have the effect of always getting the latest source code from git.

I will check your example project asap, thanks for doing it!

**Comment by memsharded** [comment] 2016-08-05 23:33
Hi, I have done a PR: https://github.com/colinbrownec/conan-problem/pull/1

I propose the following:

- The CMakeLists can be simplified, as the handling of BUILD_SHARED_LIBS is exactly what cmake does by default if the type of the library is not specified
- No moving of conanbuildinfo.cmake is necessary. Please note that when the package is built inside the local conan cache, it is already in a build folder. Exactly in a folder build/sha1, being the sha1 the identifier of the binary package being built, which is unique for each combination of settings and options. So the conanbuildinfo.cmake is in the root of that folder, and that root can be directly used to build, no necessary to create an extra "build" subfolder. It is true that such folder contains a full copy of the source code. This is because some projects actually modify or generate source code, so we don't want to destroy the clean sources retrieved.
- Of course you can create the "build" subfolder if you want, and I think that in that case, it is perfectly legal to move the ``conanbuildinfo.cmake``, and see no reason not to do it, or any way it could be problematic.
- It is not necessary to ``import`` the static libraries. They are found in the local cache without problems. The only problem are the dynamic libraries, and mainly in Windows (not in linux), as they are needed in runtime (where conan has no control), so they must be located in the system path or inside the executable folder. The ``imports`` can do that, copy the dlls from the local cache to the current project binary dir. There is a new way from conan 0.11, is to use virtualenv, so the path to the binaries and dlls is added in a virtualenv that can be activated and deactivated.
- If you have the conanfile.py inside your project, it is very weird to clone the repo you are in. There are two ways to create packages, and you are using the in-source one. For that one, it is much better to store the source code (make a snapshot) into the package recipe, with the ``exports=src/*...`` feature. Cloning a repo is the way to go when the conanfile is in a different repo than the source code.

The proposed solution works equally fine for the ``conan test_package`` command, but also for local development:

``` cmd
git clone https://github.com/colinbrownec/conan-problem
mkdir conan-problem-build && cd conan-problem-build
conan install ../conan-problem
conan build ../conan-problem
```

This is very convenient, you can develop locally (without exporting the package to the local cache), open your IDE, build, debug, run tests... when everything is fine, then it is time to export & create the package.

Please, have a look to the PR, and tell me what you think. Thank you!

**Comment by colinbrownec** [comment] 2016-08-08 22:36
Thanks for the CMake tips!

I would like to focus on the last point. This is exactly what I am trying to avoid, or at least, the end result of the Conan server actually containing a copy of the source code.

What I am trying to do is admittedly dumb for a package manager. I want to disable the option to build from the remote, and only allow the user to pull pre-build packages. Only project maintainers / build tools can upload new binaries.

This is what I was previously accomplishing by requiring the `source()` command to be

**Comment by memsharded** [comment] 2016-08-09 14:38
Yes, I agree, then I will highly recommend having the conan package recipe outside the source repo. Have a separate repo for it, that is definitely the way to go. Then use the ``source()`` method to ``git clone`` the sources, which can be of course protected and allowed only to certain people. 

Having the package recipe outside the source repo has other advantages, as a better management of versions, once you freeze the source repo version with a tag, you can iterate and commit the package recipe as many times as necessary, as it sometimes happen that a recipe is incomplete, a library flag is forgot...

The main inconvenient would be for the maintainers/developer of an intermediate package, that both depends on existing packages and other packages depend on them, for that, the package maintainers might need to do the ``git clone`` of the recipe, that in turn would ``git clone`` the source, but working on that source, commiting and pushing changes to that sources is not that intuitive. Is this the problem? Have I understood it properly? Please tell me, so we can think about it, let's try to improve the workflows if necessary. Thanks again for your feedback!

**Comment by colinbrownec** [comment] 2016-08-16 14:11
I have updated my projects so that I now have two Conan files. One resides in the project directory, and another in a repository that contains multiple Conan files for different internal projects (I'll call this the export directory).

This works great except I don't like the duplicated code. The `test_package` folders are exactly the same, and the project and export directory Conanfiles are *almost* the same.

#### Getting the source files
##### Project Directory
``` python
exports = 'CMakeLists.txt', 'src/*'
```
##### Export Directory
``` python
def source(self):
  self.run('git clone {repository} --branch {branch}')
```

#### Building the project
##### Project Directory
``` python
self.run('cmake %s %s %s' % (self.conanfile_directory, cmake.command_line, args)
```
##### Export Directory
``` python
self.run('cmake %s/{project} %s %s' % (self.conanfile_directory, cmake.command_line, args)
```

Does it sound like I am heading in the correct direction?

I still don't quite understand how to have a project both require Conan and supply a Conan library.

**Comment by colinbrownec** [comment] 2016-08-16 14:46
I can partially combine the two files

``` python
export_directory = os.getenv('EXPORT') is not None

username = os.getenv('CONAN_USERNAME', 'colinbrownec') if export_directory else 'colinbrownec'
channel  = os.getenv('CONAN_CHANNEL', 'testing')       if export_directory else 'stable'

class ConanProject(Conan):
  exports = ('src/*', 'CMakeLists.txt') if not export_directory else None
```

But using an environment variable in the build step would get tricky and so I guess I don't think environment variables are good solution.

**Comment by memsharded** [comment] 2016-08-16 21:53
Sorry, but maybe I don't understand,. I am not saying that it is bad, it sounds as a good workaround, but I don't get the full picture, and I totally agree that the duplication should be avoided:

- So you have 2 conanfiles, the one inside the project is the one for working in your user space when you are developing the package code, and the separate one in the "export" is for actually creating the package? Did I understand this right?

- The "EXPORT" env variable is for detecting if you are working in the user space (developing) or as a package?

I suspect that there is something in conan that should be improved and that we could improve to avoid this duplication. Can you please confirm also that the problem you are trying to avoid is the one I suggested in the above comment? Please tell me and we'll have a look, thanks!

**Comment by colinbrownec** [comment] 2016-08-16 23:42
Your previous comment about `git clone`ing in the source method creating problems for development is spot on. I am currently using your suggestion to create two Conanfiles. This is working great and I think I could stop here.

My issue is that now the entire `test_package` directory is duplicated, and the Conanfiles differ by only a few lines.

I think there should be a way to distinguish a "from conan export" and "from download / clone".

My `EXPORT`  environment variable post was attempting to solve combine these files outside on Conan, but I think Conan needs to manage this flag.

I've updated the code below to hopefully make it more clear

``` python
from_git = os.getenv('FROM_GIT') is not None

username = os.getenv('CONAN_USERNAME', 'colinbrownec') if not from_git else 'colinbrownec'
channel  = os.getenv('CONAN_CHANNEL',  'testing')      if not from_git else 'stable'

class ConanProject(Conan):
  exports = ('src/*', 'CMakeLists.txt') if not from_git else None
```

**Comment by memsharded** [comment] 2016-08-17 20:51
Excellent. I am glad that you have a working solution. The problem is clear now, I agree this needs something, so we will think about it, try to come up with an improvement. Thanks very much for all your feedback.

**Comment by memsharded** [comment] 2016-08-17 21:17
Just a side idea, if one of the problems of storing the code together with the recipe in a "snapshot" is potential source code security, could a cipher be a solution? Maybe it is something that could be considered, the keys could be environment variables, or locally stored in files, but never in any remote. Package snapshots will be encrypted on upload and decrypted on download.
Another thing to consider wrt to security would be that of debug packages, which could contain source code information, symbols, etc.

**Comment by memsharded** [comment] 2018-02-25 22:01
I think this issue finds a proposal for a better solution in: https://github.com/conan-io/conan/issues/2371.

So I am temptatively closing this issue, please follow conversation in the other one (or comment here or re-open issue if it is not really related). Thanks!

**Closed by memsharded** 2018-02-25 22:01 UTC
