### ISSUE TITLE
Version_Range with Prerelease does not get resolved correctly

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4882] opened 2019-03-31 07:47 UTC
The following package reference: `foobar/1.0.0-abcdefg@user/channel` does not get resolved by the following dependency: `foobar/[>=1.0.0, include_prerelease=True]@user/channel`. It works by depending on `foobar/[>0.9.9, include_prerelease=True]@user/channel` though.

I extended the `version_ranges_graph_test.py` to cover this: [gist](https://gist.github.com/monsdar/72bc745f860324c849ba2345ecef6fb2)
* Extended Line 43 to contain a prerelease-version
* Added test `test_prerelease_range` that tries to resolve that prerelease.

Only reason for this could be that a Prerelease-version is considered "smaller" than a normal version, therefore it is not resolved by >1.0.0. I think this is counterintuitive though, as I set `include_prerelease=True` explicitly, therefore asking for any version of 1.0.0, even prerelease versions.

Let me know if this is really a bug. If it isn't perhaps it needs to be documented in a better way.

**Comment by lasote** [comment] 2019-03-31 08:00
I think the current behaviourt might make sense, from the semver docs:

```
... Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.
```
So for me, the sense of your expression `foobar/[>=1.0.0, include_prerelease=True]@user/channel` is to match any pre-release major than 1.0.0, but `1.0.0-alpha` is not major than `1.0.0` so that expression would mean to include `1.0.1-alpha`, for example.

**Comment by monsdar** [comment] 2019-03-31 08:06
Figured the same, but found it counter-intuitive. The name of the parameter `include_prerelease` makes it seem like it's also including prerelease versions of 1.0.0 - therefore it should find 1.0.0-abcdefgh.

Better to have that discussed and documented somewhere I guess. Even if it's just this issue.

**Comment by lasote** [comment] 2019-03-31 08:30
Sure. The docs should be completed.

**Comment by lasote** [comment] 2019-04-02 09:04
I think we should close this issue because for me is a documentation issue. Thanks for your help!

**Comment by stefanbuettner** [comment] 2020-08-14 15:07
Hey there,

@sebastianriedel and I also found the current behavior unintuitive.

After writing the stuff below I continued browsing in the [python-semver repo](https://github.com/podhmo/python-semver) and found this issue https://github.com/podhmo/python-semver/issues/37 and pull request https://github.com/podhmo/python-semver/pull/40 which seem to switch to our expected behavior. But let me elaborate our view:

Consider the following versions: `1.2.0-rc.1`, `1.2.0`, `2.0.0-rc.1`, and `2.0.0`

Currently, the version ranges resolve to
Range definition | Versions
---|---
`[~=1, include_prerelease=True]` | `1.2.0-rc.1`, `1.2.0`, `2.0.0-rc.1`
`[~=2, include_prerelease=True]` | `2.0.0`

Our expected behavior would be
Range definition | Versions
---|---
`[~=1, include_prerelease=True]` | `1.2.0-rc.1`, `1.2.0`
`[~=2, include_prerelease=True]` | `2.0.0-rc.1`, `2.0.0`

In my opinion the documentation update in https://github.com/conan-io/docs/pull/1411 doesn't clarify the current behavior enough. In our expected case, version `2.0.0-rc.1` still strictly precedes `2.0.0` but is associated with version `2.0.0`. From the documentation it's not clear that `2.0.0-rc.1` is included in the version 1 range `[~=1, include_prerelease=True]`.

Now consider start developing version `2.0.0` of a library with a completely redesigned API. You make a pre-release `2.0.0-rc.1`. This breaks packages with a dependency of the form `[~=1, include_prerelease=True]` since all of a sudden the dependency with an incompatible API will be resolved.

The SemVer specification [sais](https://semver.org/#spec-item-9):
> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–

According to the specification, the pre-release has an _associated normal version_ which would be `2.0.0` for `2.0.0-rc.1` wouldn't it? I would not associate version `1.y.z` with `2.0.0-rc.1`.

Furthermore I don't think that the fact that the API might still change from a pre-release to the normal release should be so surprising. It's a pre-release after all. And you would acknowledge this by deliberately including `include_prerelease=True` to the range specification.
Moreover, I find it less surprising than a package breaking which depends on the previous version but includes the pre-releases.

Just some thoughts from our side.

Cheers,
Stefan

**Comment by stefanbuettner** [comment] 2020-10-06 22:11
@lasote is it worth reopening this issue and discuss a little bit more?

**Comment by memsharded** [comment] 2020-10-06 22:28
Hi @stefanbuettner 

Sorry that this was not noticed. Yes, I agree this is a bit counter-intuitive, let's at least reopen and have a look when possible.

**Comment by Pro** [comment] 2021-01-13 17:10
@memsharded same issue here. I was just thinking about releasing a `2.0.0-rc1` package, but this would not work as expected.
So probably I will use the approach to release it as `2.0.0@user/rc` instead of `2.0.0@user/stable`.

**Comment by memsharded** [comment] 2021-12-14 00:42
We have taken ownership of version ranges resolution, dropping the external node-semver dependency, and implementing a more flexible version resolution (allowing any number of digits, for example, and allowing letters too easily). This is already implemented in 2.0, and released in 2.0.0-alpha1, (and will get more improvements released in 2.0.0-alpha2 very soon, specifically those described above with pre-releases. Those are already available in ``develop2`` branch). So I think this issue can be closed, feedback after alpha2 is released will be very welcome, thanks!

**Closed by memsharded** 2021-12-14 00:42 UTC
Labels: type: question, type: look into

**Comment by irwineffect** [comment] 2022-10-04 16:08
Is there any chance this might also get fixed in conan 1.x?

**Comment by memsharded** [comment] 2022-10-04 16:17
Hi @irwineffect 

No, this would be breaking behavior, it is not possible in 1.X scope, sorry.
