### ISSUE TITLE
[enhancement] support for multiple compiler' options in default profile

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan#3504] opened 2018-09-07 10:32 UTC
Hello,

Consider the below default profile
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=7.1
compiler.libcxx=libstdc++
compiler.sanitize=None
build_type=Release
[options]
[build_requires]
[env]
```

In a multiple compilers environment, it would be nice to specify something like:
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
build_type=Release
[options]
[build_requires]
[env]

[compiler.gcc]
compiler.version=7.1
compiler.libcxx=libstdc++

[compiler.newgcc]
compiler.version=7.5
compiler.sanitize=address
```

We can see that the `gcc` compiler has an option **libcxx** which is not present for `newgcc` compiler.
This way, we could avoid passing two different profiles.

The main reason to suggest this is because the `conan create` workflow breaks while removing compiler settings using `configure()` method (as indicated at: https://github.com/conan-io/conan-package-tools/issues/258)

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment] 2018-09-07 10:49
Thanks for the suggestion. I think the problem is not well defined. Which compiler settings will it use in case of having 2 of them defined? Please note that the profiles, and ``conan install`` are not even conditioned to the existence of the compiler in the current machine. Or what happens if you have both compilers installed in the machine? The purpose of the profiles is to be an independent definition of configuration, irrespective of the machine installed tools.

**Comment by sunj1** [comment] 2018-09-07 10:57
> Which compiler settings will it use in case of having 2 of them defined?

I have mentioned under `[settings]` that `compiler=gcc`. Then it can refer to `[compiler.gcc]`. Is it fine this way?

>  Or what happens if you have both compilers installed in the machine?

I have both the compilers installed. I need to build with different sets of settings, which may be non-existent for different compilers.
Currently, I remove the settings in `configure()` method after checking name of compiler, but which seems to be incompatible with `conan create` way (as mentioned in the referred issue for CPT).

**Comment by memsharded** [comment] 2018-09-07 11:01
Not sure if I am understanding this issue. If you are using ``compiler=gcc``, then you will always be using the gcc 7.1 with libstdc++. Then the ``newgcc`` what it is used for?

**Comment by sunj1** [comment] 2018-09-07 11:10
Yes, by default I will be using `compiler=gcc`.
But when building multiple packages, I would need to specify `conan install . -s compiler=newgcc` as well.
Now, this should automatically take default configs from `[compiler.newgcc]`.
If it does not, then I will need to use either different profiles for different compilers, or `configure()` method as a workaround.
P.S. Not sure how it was handled in the older conan version `0.X`, because it worked fine there and there was no error for having extra sub-settings which do not exist for the chosen compiler.

**Comment by memsharded** [comment] 2018-09-07 11:34
> If it does not, then I will need to use either different profiles for different compilers

Yes, this is definitely the way to go. This is not a workaround, it is the recommended practice. Profiles can be partially reused with the ``include(other_profile)`` instruction in case you don't want to repeat things in different profiles. It is strongly recommended to use different profiles for such different configurations. Partially overriding profiles with command line settings should be a very occasional/testing thing, and changing compiler is a major thing to deserve having its own profile.

**Comment by LeeRuns** [comment] 2020-04-13 17:46
What if i want to pull down an external library that from a remote, and the remote "requires gcc" but I want to compile my library with clang.  Can i use gcc to compile the external library into shared objects then use clang for everything else (ie compile the shared objects into my library)

**Comment by memsharded** [comment] 2024-04-12 12:02
@LeeRuns 

Sorry this was not responded back then.

yes, you can use per-package settings: https://docs.conan.io/2/reference/config_files/profiles.html#profile-patterns to define different settings for different packages. You can leverage the profiles ``jinja`` syntax for more power in your profiles.

It is also possible to define a global "compatibility.py" binary compatibility strategy: https://docs.conan.io/2/reference/extensions/binary_compatibility.html to fallback to binaries compiled with a different compiler.


I am closing this ticket as staled and the proposed enhancement not planned, the current model has proved good so far. Thanks for the feedback, don't hesitate to open new tickets for any further question.

**Closed by memsharded** 2024-04-12 12:02 UTC
