### ISSUE TITLE
[question] Run only unit tests while developing

### ISSUE THREAD

**Issue by blackk-foxx** [conan-io/conan#12096] opened 2022-09-12 23:22 UTC
My question is related to #11898, but mine focuses on developer usage rather than CI.  As a developer, I would like to run only the unit tests during my code/test/debug/refactor development cycle.  But when I'm ready to create a package for testing with other packages, I would like to run all of the tests.  

One way to accomplish this would be to add a `develop` boolean option to my recipe that appropriately filters the tests to run, and do `conan install` with `-o develop=True` to set up my development environment.  When I want to create a package for testing, I would run `conan create`, and it would run all the tests because the `develop` option would be `False` in that case.  Any suggestions on how to make such a usage model work without me having to remember to add `-o develop=True` when I run `conan install`?  In other words, how can I have `develop` default to `True` for `conan install` and `False` for `conan create`?

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-09-13 00:08
Hi @blackk-foxx 

A couple of quick hints:
- You don't want to use an option, if the final package binaries are not different (which typically shouldn't be for tests, unless for some unusual reason you are also packaging the tests themselves), because then you would need to remove the option in ``package_id``
- You can probably better use a ``conf``, that you can set both in your command line ``-c`` and profiles.
- With a ``conf``, same as options you can define the semantics you want, but it is true that the semantics for the conf will remain the same between a ``conan install`` and a ``conan create``, and this is on purpose, as the rationale for this was that by default conan should do exactly the same for create and for install, to have better reproducibility. You still need one of them to be specified. As ``conan create`` typically happens more in CI than in developer machines, I'd recommend to let the ``conan create`` be the one that specifies the conf value, and not the ``conan install`` that developers use more often

Finally, Conan 2.0 will provide a framework for creating custom commands, you will be able to define your own ``create`` command if you want it, changing the semantics, or actually injecting the ``conf`` that you want.

**Comment by blackk-foxx** [comment] 2022-09-13 16:53
Thank you for the quick response, @memsharded!  I will try the `conf` approach you recommend.  

Now for a follow-up question, please:  How do I get `conans.CMake.test` to run a subset of tests?  With CMake, I can assign one or more labels to tests, and when I run the `ctest` command I can choose which label(s) I want to include in the test run.  But `conans.CMake.test` doesn't run `ctest`; it runs `cmake --build <builddir> --target test`.  I'm using conan version 1.52.0.

**Comment by memsharded** [comment] 2022-09-13 17:02
Well, the ``cmake.test()`` wrapper is just a very thin layer, I think you can easily do something like ``self.run("ctest ...")`` to run the tests that you want, have you considered that?

**Comment by blackk-foxx** [comment] 2022-09-13 17:25
I have, but I wonder what might be missed by doing that.  In other words, why does `cmake.test()` not already run `ctest`?

**Comment by blackk-foxx** [comment] 2022-09-15 16:47
@memsharded, I tried your recommended approach, and it worked very well -- thanks!  But I'm still curious as to why `cmake.test()` runs `cmake --build <builddir> --target test` instead of `ctest`.

**Comment by memsharded** [comment] 2024-12-18 18:39
Sorry this was not followed up back then @blackk-foxx 

Some updates:

- Now ``cmake.ctest()`` also exists, calling ``ctest`` directly. ``cmake.test()`` keeps calling the test target
- Some new built-in standard configurations exists to skip buiding and executing the tests, and even for completely dropping ``test_requires``:
  ```python
    $ conan config list test
    tools.build:skip_test: Do not execute CMake.test() and Meson.test() when enabled
    tools.graph:skip_test: (Experimental) Do not expand test_requires. If building it might need 'tools.build:skip_test=True'
```

I am closing the ticket as solved, please don't hesitate to create new tickets for any further question or issue. Thanks for the feedback!

**Closed as completed by memsharded** 2024-12-18 18:39 UTC
Labels: type: question
