### ISSUE TITLE
[bug] conan graph build-order no longer works when binaries are missing

### ISSUE THREAD

**Issue by vorpaladin** [conan-io/conan#17057] opened 2024-09-24 15:48 UTC
### Describe the bug

Conan version tested: 2.7.1
Conan version when "graph build-order" is known to have last worked as expected: 2.3.2
OS: Debian 6.1

I have a top-level project that directly requires two other projects.  These in turn depend on other projects and so on.  All self.requires statements in all of my conanfile.py files down the project hierarchy set lib and header transitivity to True.

Starting from a clean Conan cache where all of my project's recipes have been exported but no packages have been built, I get a full build order JSON file for the entire dependency tree with the following command run in my top-level project directory when using conan 2.3.2:

conan graph build-order . -f json --order-by recipe > out.json

When I run this under 2.7.1, the JSON file contains info about the 2 direct requirements only and an error is reported:

======== Computing the build order ========
ERROR: There are some error(s) in the graph:
    - baldur/4.1.240924144311@vali/stable:0c9a84355fd222bd52338826b09c5a8229fcd717: Missing binary
    - tyr/4.1.240924144311@vali/stable:0c9a84355fd222bd52338826b09c5a8229fcd717: Missing binary

The more verbose error using -vtrace is:

======== Computing the build order ========
Traceback (most recent call last):
  File "/home/conan/.pyenv/lib/python3.12/site-packages/conan/cli/cli.py", line 193, in run
    command.run(self._conan_api, args[0][1:])
  File "/home/conan/.pyenv/lib/python3.12/site-packages/conan/cli/command.py", line 187, in run
    sub.run(conan_api, parser, *args)
  File "/home/conan/.pyenv/lib/python3.12/site-packages/conan/cli/command.py", line 208, in run
    self._dispatch_errors(info)
  File "/home/conan/.pyenv/lib/python3.12/site-packages/conan/cli/command.py", line 104, in _dispatch_errors
    raise ConanException(info["conan_error"])
conans.errors.ConanException: There are some error(s) in the graph:
    - baldur/4.1.240924144311@vali/stable:0c9a84355fd222bd52338826b09c5a8229fcd717: Missing binary
    - tyr/4.1.240924144311@vali/stable:0c9a84355fd222bd52338826b09c5a8229fcd717: Missing binary

ERROR: There are some error(s) in the graph:
    - baldur/4.1.240924144311@vali/stable:0c9a84355fd222bd52338826b09c5a8229fcd717: Missing binary
    - tyr/4.1.240924144311@vali/stable:0c9a84355fd222bd52338826b09c5a8229fcd717: Missing binary

If this behavior is intentional, is there a way to work around it and get a complete build-order JSON file without having to build packages or binaries?

### How to reproduce it

I will develop an example for reproducing the issue if necessary, but since it will take several hours of my company's time I'd prefer to avoid it.

**Comment by memsharded** [comment] 2024-09-24 16:47
Hi @vorpaladin 

Thanks for your feedback.

This was an intended fix in Conan 2.6 in https://github.com/conan-io/conan/pull/16415, declared as a bugfix.

It was declared a bugfix because:

- Other ``conan`` commands raises the same exception for the same input conditions, like ``conan create/build/graph info``. If there is a missing or an invalid binary these commands will raise an error and return an exit-code different to 0
- The resulting ``build-order.json`` returned by ``conan graph build-order`` if it contains ``invalid`` or ``missing`` packages cannot be used for building because it is incomplete, the graph computation might have skipped necessary dependencies that will make it fail if trying to build some of the ``missing`` ones (the ``invalid`` will raise always)

This can be solved in different ways:

- the ``build-order.json`` is still created when the exception is raised. I have just tested it. It shouldn't be used at all to try to build, but it is there.
- The correct approach is to define the right ``--build`` policies that you want to use, in exactly the same way as if you would be building things automatically with ``conan install --build=missing``, for example. In this case, your command should be something like:
```
conan graph build-order . --build=missing -f json --order-by recipe > out.json
```
This will guarantee that the necessary packages are marked as ``binary: Build`` and also that the graph computation is complete enough so when those packages to build are being built, their dependencies will already be available.

Please try adding ``--build=missing`` and let us know if this helps.

**Comment by vorpaladin** [comment] 2024-09-24 18:24
Thank you for the prompt response.  I added --build=missing to the command:

`conan graph build-order . --build=missing -f json --order-by recipe > out.json`

This changed the error from "Missing binary" to "Invalid configuration".  The JSON file produced is still the same one I got before, which only contains the top-level direct requirements and not the build order.

I moved down the tree to one of my lower level projects and found that it no longer builds.  It looks like something else has changed that is breaking some of my builds.  This issue could be cascading up to break graph behavior.  I will investigate further on my end and report back.

**Comment by memsharded** [comment] 2024-09-24 20:56
> This changed the error from "Missing binary" to "Invalid configuration". The JSON file produced is still the same one I got before, which only contains the top-level direct requirements and not the build order.

I think it is possible that it was the same behavior already in previous versions. Can you please try with the ``--build=missing`` in the previous ``2.3.2`` version? I think nothing has changed there, maybe the behavior was just there, there was some invalid configuration hidden behind one of the "missing binaries", and adding the ``--build=missing`` just unveils that.

> I moved down the tree to one of my lower level projects and found that it no longer builds. It looks like something else has changed that is breaking some of my builds. This issue could be cascading up to break graph behavior. I will investigate further on my end and report back.

Regarding the ``graph build-order`` the only thing that has really changed is that it now raise an error, to indicate that the resulting ``build-order.json`` is not "buildable", but otherwise it should work the same. Maybe it is another thing, so please, sure, let me know if you manage to get more information. Many thanks for your feedback!

**Comment by memsharded** [comment] 2024-10-09 08:54
Hi @vorpaladin 

Any feedback here? Did you manage to try with the ``--build=missing`` in the previous version?

Thanks for the feedback.

**Comment by vorpaladin** [comment] 2024-10-14 15:53
After digging into this further, I've found another issue that could be contributing to the build-order problem.  As of 2.4.0, transitive dependencies are no longer working for consuming components.  They worked as expected with the previous version of 2.3.2.  The transitive dependencies no longer appear as dependencies in the conan graph and the include path for dependencies specified with transitive_headers=True is not included in compile statements.  When I add dependencies in with explicit self.requires statements rather than relying upon transitivity, my builds work again.

I would hate to lose the maintenance advantages of transitivity.  My project has over 20 components and I prefer not having to duplicate all requirements in every conanfile.py.  Looking at the release notes for 2.4.0 I do not see anything that I would expect to break transitivity.  I've confirmed that the problem exists all the way up to 2.8.0.

**Comment by memsharded** [comment] 2024-10-14 16:02
Thanks for the feedback @vorpaladin 

That seems it could be a completely unrelated issue, and it looks it would deserve its own independent ticket, with probably a new discussion and steps to reproduce. Could you please create a new ticket for it, with the details?

I think that if the behavior of Conan 2.8 that raises an exception when there is a ``Binary: Missing`` in the build-order would have been clarified, and it would be a correct "bug-fix", so we might be able to close this ticket and follow up in the new one. Thanks!

**Comment by vorpaladin** [comment] 2024-10-16 18:25
I have discovered the root cause of the cascade of failures across all of our builds.  The problem is the interpretation of "vendor" was changed in 2.4.0 to be a boolean value indicating whether or not dependencies should be hidden.  We had "vendor" set to the name of our organization in all of our conanfile.py files.  This string is interpreted as True in boolean context, which fire-walled all of our components off from each other, breaking transitivity.  I lost most of a week chasing this.  "vendor" is a bad name for the a dependency hiding feature.  Something like "black_box" or "hide_dependencies" would be much clearer.

**Comment by memsharded** [comment] 2024-10-16 20:42
The ``vendor=True`` didn't change in 2.4, it was introduced/defined in Conan 2.4 for the first time: https://docs.conan.io/2/devops/vendoring.html

>  We had "vendor" set to the name of our organization in all of our conanfile.py files.

If you were using ``vendor = "string"`` for your own things, it seems that this wouldn't be allowed, please check:

- https://docs.conan.io/2/knowledge/guidelines.html (``Recipes reserved names``). Note this doc contains other important guidelines, and we will keep updating it in the future, if you haven't checked it yet, please have a look.
- https://docs.conan.io/2/reference/conanfile.html (the ``Important`` green box there). This is not really new, it has been there since Conan 1 too https://docs.conan.io/1/reference/conanfile.html#conanfile-py


So please re-check other possible attributes or methods that you might be using without ``_``, because these could be problematic in the future too.

**Closed as completed** 2024-10-17 18:40 UTC
