### ISSUE TITLE
[Feature request] Arch Linux package

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#21] opened 2015-12-06 21:26 UTC
As in #12, having a package for arch would be great. We can use the ubuntu/debian package as I did with biicode https://github.com/biicode/packages/tree/master/archlinux

**Comment by memsharded** [comment] 2015-12-07 23:39
Why use the ubuntu/debian package? It is not simpler to just package it from source? Just asking, dont know about the archlinux format.

**Comment by Manu343726** [comment] 2015-12-07 23:42
ArchLinux PKGBUILDs are just bootstrapping descriptors, with the usual `get -> configure -> build -> install` pipeline. I suggested using the debian package since it's a way to get rid of maintaining another bootstrapping script. Just rely on the already-maintained .deb package and you are done.

**Comment by memsharded** [comment] 2015-12-08 00:11
Ok, thanks for the clarification. Let's go with that approach then.

**Comment by lasote** [comment] 2015-12-28 16:03
Do you still want an Arch package or its enough with pip package?

**Comment by Manu343726** [comment] 2015-12-28 22:59
The pip install works, but having a package specific for the distro has some advantages. For example, users receive notifications whenever a new version is released, the client is updated during a system update, etc. 

Of course this is not an urgent feature, but something to keep in mind. Also I would like to hear more arch users opinions.

**Comment by malikkirchner** [comment] 2016-02-03 09:06
+1 using arch, would like to see an aur package for conan

**Comment by gaborbernat** [comment] 2016-03-06 16:04
+1 using arch, any approach is good :+1: more important is the existence of it.

**Comment by koval4** [comment] 2016-06-19 11:52
+1 using arch, I don't use pip and I don't want to install it just for conan, separate package are better option

**Comment by memsharded** [comment] 2016-06-19 12:06
Ok, lets try to move this forward. @Manu343726, you know how to do it, could you please provide me with some pointers on how to do this Arch package? Thanks!

**Comment by tivek** [comment] 2016-08-20 02:41
Here's a bit of progress. I made a basic PKGBUILD for the latest release of conan. Please take a look: https://github.com/tivek/conan-aur I'm also working on a conan-git version that tracks master, but I would first like to resolve the following issues.

conan's package builds from the PKGBUILD above, but it doesn't run cleanly because library requirements are very tight:

1. We require `requests>=2.7.0, <2.8.0`, but Arch currently ships 2.10.0.
2. Similarly, we require `boto>=2.38.0, <2.39.0`, but Arch ships 2.42.0.

I did not have the time to test if conan runs ok when version requirements for requests and boto are removed.

(Oh and as a byproduct of all this tinkering `python-fasteners` and `python-patch` are now also on AUR!)

**Comment by lasote** [comment] 2016-08-20 07:30
Hi @tivek! Thanks very much. I'll try to update those requirements and see if it broke something.
I think it should be ok. I'll open a PR and if everything is OK will be available in the next release.

**Comment by tivek** [comment] 2016-08-21 01:49
Thank you for running the check with Arch's library versions.

I have pushed the PKGBUILD for conan 0.11.0 to AUR. It is patched with the current requirements.txt and works ok on my system. Feedback is of course welcome!

Next I hope to get the PKGBUILD for develop branch up and running.

**Comment by memsharded** [comment] 2016-08-21 18:45
No, of course not, it is perfectly fine, thanks very much for doing this task! 

I have search in the archlinux index, and not able to find it. Can you point out some tips how to install and use this package? Which would be the preferred way, pacman, yaourt? We may twit about it, maybe get more feedback. We would also like to add the instructions/link in our downloads web page.

I don't know the burden of creating new ArchLinux packages for new conan releases, which we are doing aprox between 2 weeks and 1 month; it might be possible to automate the task.

Thanks very much again.

**Comment by tivek** [comment] 2016-08-22 00:17
You are welcome, I am scratching my own itch as well. :)

> I have search in the archlinux index, and not able to find it.

The PKGBUILD recipe for conan is not in the main repositories but in the Arch User Repository: https://aur.archlinux.org/packages/conan/ Currently I (username suridaj) am listed as package maintainer. I can add conan developers as co-maintainters or give you ownership of the package if you wish.

> Can you point out some tips how to install and use this package? Which would be the preferred way, pacman, yaourt? We may twit about it, maybe get more feedback. We would also like to add the instructions/link in our downloads web page.

conan has a few AUR dependencies (python-patch, python-fasteners and python-monotonic) and pacman will not download them on its own. An AUR helper is the quickest way to get conan and all its dependencies, eg.:
`$ yaourt -S conan`
or
`$ pacaur -S conan`
In the download page maybe you can put something like this:
> Arch Linux: From AUR
> `$ yaourt -S conan` or equivalent with other AUR helpers
> Go to AUR (link to https://aur.archlinux.org/packages/conan/)

but I don't know if we should advertise yaourt or any other particular AUR helper. We Arch users can be pretty opinionated. :)

> I don't know the burden of creating new ArchLinux packages for new conan releases, which we are doing aprox between 2 weeks and 1 month; it might be possible to automate the task.

Now that we have a working PKBGUILD it is very easy to maintain and I would stay with manual packaging for a couple of versions.

**Comment by tivek** [comment] 2016-08-22 16:27
Package for the develop branch is here: https://aur.archlinux.org/packages/conan-git/

**Comment by memsharded** [comment] 2016-08-23 18:30
Excellent, thank you! I have twitted it (do you have a twitter account?), lets see if we get some extra feedback.
Yes, I agree with not being opinionated. Lets put the link, and then maybe both the yaourt and pacaur options. 
I think it is not necessary to give us access to the ownership, let see how it goes, and if after a couple of versions we want to automate the task, we will talk about it.

**Comment by tivek** [comment] 2016-08-24 10:33
OK for AUR helper commands and the package ownership.

Now that conan and conan-git packages are up I will keep them current on AUR. Again, feedback is most welcome  - @Manu343726, @malikkirchner, @gaborbernat, @koval4 if you try it out please let me know.

My twitter account: https://twitter.com/tomivek

**Comment by koval4** [comment] 2016-08-30 12:29
Looks like PKGBUILD missing some dependencies:
`resolving dependencies...`
`warning: cannot resolve "python-patch=1.16", a dependency of "conan"`
`warning: cannot resolve "python-fasteners>=0.14.1", a dependency of "conan"`
`:: The following package cannot be upgraded due to unresolvable dependencies:
      conan`
I've added `'python-patch' 'python-fasteners'` to makedepends and everything was installed successfully.

**Comment by tivek** [comment] 2016-08-30 21:18
Thanks, I'm going to test it and update the PKGBUILDs.

**Comment by tivek** [comment] 2016-08-31 10:14
@koval4, did you use makepkg or an AUR helper?

> ```
> resolving dependencies...
> warning: cannot resolve "python-patch=1.16", a dependency of "conan"
> warning: cannot resolve "python-fasteners>=0.14.1", a dependency of "conan"
> :: The following package cannot be upgraded due to unresolvable dependencies: conan
> ```

This error is caused by dependencies which do not reside in repositories. This means makepkg and pacman do not know how to get them, a common issue when installing an AUR package which depends on other AUR packages.

I am not sure why adding python-patch and python-fasteners to makedepends helped. Cannot reproduce, I still get the same error. In fact, makedepends should not list any packages which are already in depends as they are all included implicitly ([see wiki](https://wiki.archlinux.org/index.php/PKGBUILD#makedepends)).

One way around the AUR-depending-on-AUR issue is to install the dependencies manually. The other is to use an AUR helper like pacaur that can pull and build them for you.

**Comment by tivek** [comment] 2016-08-31 10:18
On a different note, I see 0.11.1 is released on pypi but there is no release zip here on github. Do you plan to add it? As the PKGBUILD downloads from github I thought I'd ask here.

**Comment by memsharded** [comment] 2016-08-31 10:36
Maybe @lasote forgot to push the tags

**Comment by lasote** [comment] 2016-08-31 10:43
Done! thanks.

**Comment by tivek** [comment] 2016-08-31 12:33
Thank you. The new PKGBUILDs for conan 0.11.1 and conan-git are up on AUR.

**Comment by lasote** [comment] 2016-09-02 08:48
Hi @tivek I'm not an arch linux user, just followed the AUR instructions to install a package and I get the problems with the mentioned fasteners and python patch:

warning: cannot resolve "python-patch=1.16", a dependency of "conan"
warning: cannot resolve "python-fasteners>=0.14.1", a dependency of "conan"

It should work?

**Comment by tivek** [comment] 2016-09-02 10:09
Hi @lasote. Did you pull the package manually from AUR and build it with makepkg? If so, it is normal that makepkg/pacman does not know how to download python-patch and python-fasteners. These two are not in the official repos but live in AUR (packaged by me for conan :) ) So download, build and install python-patch and python-fasteners before conan.

If on the other hand you use an AUR helper such as pacaur, it should automagically just work. Please try it, eg. get pacaur and do `pacaur -S conan` as a user with sudo capabilities.

**Comment by memsharded** [comment] 2016-09-02 21:07
Just merged docs from @lasote in https://github.com/conan-io/docs/pull/66, so I understand that this is already fixed, and we can close it again. Thanks @tivek and @lasote!

**Closed by memsharded** 2016-09-02 21:07 UTC
Labels: enhancement, look into
