### ISSUE TITLE
[bug] `python_requires_extend` in base class should extend base class but extends sub class

### ISSUE THREAD

**Issue by bazizsafi** [conan-io/conan#10511] opened 2022-02-03 21:16 UTC
I stumbled upon a little quirk in the implementation of `python_requires_extend`. I am not sure whether it is worthy to be called a bug, but I think it is unintuitive at the least.

Let's say that we have a `ConanFile` subclass `ProjectBaseConanFile` which serves as the base class for some project variants with their classes `VariantAConanFile`, `VariantBConanFile`, `VariantCConanFile`.

Instances of these `VariantXConanFile` classes have the following inheritance hierarchy (packages ommitted):

```
<object>
<class 'ConanFile'>
<class 'ProjectBaseConanFile'>
<class 'VariantXConanFile'>
```

Now, let's say that we have a new company-wide Conan base class `CompanyConanFile` and we want to use `python_requires` and `python_requires_extend` in all of our `ConanFile` implementations (including `ProjectBaseConanFile`) to inject `CompanyConanFile` as their respective base class.

### Issue description
When we now set `python_requires_extend = "companyconan.CompanyConanFile"` in `ProjectBaseConanFile`, then Conan currently injects `CompanyConanFile` as the base class of `self.__class__`, so at this position:

```
<object>
<class 'ConanFile'>
<class 'ProjectBaseConanFile'>
<class 'CompanyConanFile'>      <-- injected here
<class 'VariantXConanFile'>     <-- self
```

But that means that the *custom* implementations of `ProjectBaseConanFile` would be overridden by the *default* implementations of `CompanyConanFile` when in fact it should be the other way around.

### Expected behavior / workaround
You could work around this and inject the base class at the expected location by adding the following to the `ProjectBaseConanFile` class:

```python
class ProjectBaseConanFile(ConanFile):
    python_requires = "companyconan/0.1@Company/stable"
    # Intentionally commented-out, injection done manually in init()
    # python_requires_extend = "companyconan.CompanyConanFile"

    def init(self):
        CompanyConanFile = self.python_requires["companyConan"].module.CompanyConanFile
        ProjectBaseConanFile.__bases__ = (CompanyConanFile,) + ProjectBaseConanFile.__bases__
```
(Workaround deduced from here)
https://github.com/conan-io/conan/blob/ebed0370c439a8274c2992ee41e424438eebd455/conans/client/graph/python_requires.py#L103

This injects `CompanyConanFile` at the correct position:

```
<object>
<ConanFile>
<CompanyConanFile>      <-- injected here
<ProjectBaseConanFile>
<VariantXConanFile>     <-- self
```

### Environment Details
  * Operating System+version: macOS Catalina 10.15.7
  * Compiler+version: Apple clang version 12.0.0 (clang-1200.0.32.29)
  * Conan version: 1.43.0
  * Python version: 3.9.9

**Comment by memsharded** [comment] 2022-02-03 23:48
Hi @bazizsafi 

Thanks for the detailed report.
I am trying to reproduce, but I am missing something, because the behavior seems correct, this test is passing:

```python
def test_transitive_extend():
    # https://github.com/conan-io/conan/issues/10511
    client = TestClient()
    company = textwrap.dedent("""
        from conan import ConanFile
        class CompanyConanFile(ConanFile):
            name = "company"
            version = "1.0"

            def msg1(self):
                return "company"
            def msg2(self):
                return "company"
        """)
    project = textwrap.dedent("""
        from conan import ConanFile
        class ProjectBaseConanFile(ConanFile):
            name = "project"
            version = "1.0"

            python_requires = "company/1.0"
            python_requires_extend = "company.CompanyConanFile"

            def msg1(self):
                return "project"
        """)
    consumer = textwrap.dedent("""
        from conan import ConanFile
        class Base(ConanFile):
            name = "consumer"
            version = "1.0"
            python_requires = "project/1.0"
            python_requires_extend = "project.ProjectBaseConanFile"
            def generate(self):
                self.output.info("Msg1:{}!!!".format(self.msg1()))
                self.output.info("Msg2:{}!!!".format(self.msg2()))
            """)
    client.save({"company/conanfile.py": company,
                 "project/conanfile.py": project,
                 "consumer/conanfile.py": consumer})
    client.run("export company")
    client.run("export project")
    client.run("install consumer")
    assert "conanfile.py (consumer/1.0): Msg1:project!!!" in client.out
    assert "conanfile.py (consumer/1.0): Msg2:company!!!" in client.out
```

I think it reproduces your described scenario, what is missing?

**Comment by bazizsafi** [comment] 2022-02-04 12:59
Hi @memsharded

Thanks for the quick response!

I noticed that in the test _all_ inheritance is done via `python_requires_extend`. In the original code the inheritance of `VariantXConanFile` from `ProjectBaseConanFile` is done via actual subclassing:
```python
class VariantXConanFile(ProjectBaseConanFile):
```
Only the new `CompanyConanFile` is exported to our company repository and injected via `python_requires_extend`.

I owe you an apology because I failed to mention this crucial difference. I am sorry! I should have created a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) right from the start.

So I took your test code, manually created the files, changed class `Base` to directly subclass `ProjectBaseConanFile` (along with all necessary changes to import from a folder), and was able to reproduce the issue.

The following test should exhibit the issue and thus the first `assert` should fail:

```python
def test_transitive_extend_with_subclass():
    # https://github.com/conan-io/conan/issues/10511
    client = TestClient()
    company = textwrap.dedent("""
        from conan import ConanFile
        class CompanyConanFile(ConanFile):
            name = "company"
            version = "1.0"

            def msg1(self):
                return "company"
            def msg2(self):
                return "company"
        """)
    project = textwrap.dedent("""
        from conan import ConanFile
        class ProjectBaseConanFile(ConanFile):
            name = "project"
            version = "1.0"

            python_requires = "company/1.0"
            python_requires_extend = "company.CompanyConanFile"

            def msg1(self):
                return "project"
        """)
    consumer = textwrap.dedent("""
        import sys
        sys.path.append('base')
        from conanfile_base import ProjectBaseConanFile
        class Base(ProjectBaseConanFile):
            name = "consumer"
            version = "1.0"
            def generate(self):
                self.output.info("Msg1:{}!!!".format(self.msg1()))
                self.output.info("Msg2:{}!!!".format(self.msg2()))
            """)
    client.save({"company/conanfile.py": company,
                 "consumer/base/conanfile_base.py": project,
                 "consumer/conanfile.py": consumer})
    client.run("export company")
    client.run("install consumer")
    assert "conanfile.py (consumer/1.0): Msg1:project!!!" in client.out
    assert "conanfile.py (consumer/1.0): Msg2:company!!!" in client.out
```

I also made the crosscheck, exported the project base class, and replaced the subclassing in my code with injection via `python_requires_extend`.
I confirm that if _all_ inheritance is done via `python_requires_extend` then the issue does _not_ occur.

So you came up with a way more elegant workaround, nice! ;-)

**Comment by memsharded** [comment] 2022-02-04 13:54
I see, thanks for effort in reproducing!

Indeed, the system was not designed to mix both inheritance approaches, both direct/local and ``python_requires_extend``.

> I also made the crosscheck, exported the project base class, and replaced the subclassing in my code with injection via python_requires_extend.
I confirm that if all inheritance is done via python_requires_extend then the issue does not occur.

Then, do you think that it is worth to try to fix this, or do you really pretend to move the "ProjectBaseConanFile" to a real ``python_requires`` instead of a local copy? Because it doesn't seem easy, trying to change the order of the ``python_requires_extend`` easily leads to ton of 

```
E           TypeError: Cannot create a consistent method resolution
E           order (MRO) for bases ConanFile, MyConanfileBase
```
errors, and the logic to be able to deduce where the ``python_requires_extend`` class should be inserted reads a bit complicated/fragile at least, not sure if possible at all. What do you think?

**Comment by bazizsafi** [comment] 2022-02-04 16:38
Putting in some effort is the least one can do when using OSS for free. We all have to thank you.

> Indeed, the system was not designed to mix both inheritance approaches, both direct/local and `python_requires_extend`.

That is good to know. I'm not sure if this information is present somewhere in the latest documentation. In any case I'd advocate for adding it to [Extending Conan > Python requires > Extending base classes > Limitations](https://docs.conan.io/en/latest/extending/python_requires.html#limitations), maybe even including a link to this issue.

Unfortunately, I am fairly new to Python, so I know way too little to give a meaningful answer to the question whether it's worth trying to fix this. When I saw the [implementation of `python_requires_extend`](https://github.com/conan-io/conan/blob/ebed0370c439a8274c2992ee41e424438eebd455/conans/client/graph/python_requires.py#L103) I thought instead of just checking whether the `conanfile` instance has the attribute `python_requires_extend` set, one would have to iterate over all the classes in the inheritance tree of the `conanfile` instance and keep track which of these classes has the attribute `python_requires_extend` set to which "to-be-injected-class", then insert the to-be-injected-classes in the correct location in the inheritance tree and in the correct order. I have no clue if that is even feasible, or maybe even already happening, let alone how to gracefully manage invalid constellations, duplicates, and the like.

In my case the fact that I have two working workarounds to choose from is enough. I just wanted you guys to know and maybe keep it in mind when you are working on this (still experimental!) feature.

Thank you, @memsharded!

**Comment by memsharded** [comment] 2022-02-07 16:07
Thanks for the feedback!. I am proposing https://github.com/conan-io/docs/pull/2393 to close this issue with documentation, because I have researched a little bit more about the possibility of handling this, and it seems overly complicated and fragile for the value. The recommendation will be to not mix both inheritance approaches.

**Comment by bazizsafi** [comment] 2022-02-08 08:19
Cool! I consider this issue closed then.

**Comment by memsharded** [comment] 2022-02-08 11:14
Closed by https://github.com/conan-io/docs/pull/2393

**Closed as completed by memsharded** 2022-02-08 11:14 UTC
Labels: stage: triaging
