### ISSUE TITLE
[question] private vs public requirement 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#8561] opened 2021-02-26 09:48 UTC
Hello,

I use conan to build a **windows** application, and I have a confusion regarding private conan requirement, are they analogic to cmake private linking?

Here is the situation: 
* Tensorflow and zlib are shared library 
* MyLib links tensorflow and zlib privatetly ( Final application must not link them )
* Mylib is a conan package package that create multiple libraries. 

Now the challenge:

### If I define zlib and tensorflow as public conan requirements
The linking information will propagate to `Final application` and I ended up with my `Final application` linking both Tensorflow and zlib which I dont want to.

### If I define zlib and tensorflow as private conan requirements
The linking information will not propagate to `Final application` which is the appropriate behavior. **However** `Final application` does not know about Tensorflow and zlib anymore but they are still needed as we need the DLLs as runtime deps.
 
Any suggestion how to fix this ? 

![image](https://user-images.githubusercontent.com/7117696/109282053-5592c980-781d-11eb-9e8d-9171f71f8c9e.png)

**Comment by PengolodhGoedath** [comment] 2021-02-26 13:35
Have you tried repackaging the DLLs inside MyLib (i.e. MyLib contains both DLLs in its binary directory)?

**Comment by boussaffawalid** [comment] 2021-02-27 13:07
Actually, We wanna avoid, Our dependency graph is more much complicated and I just made this example to explain the situation. 

For example:
*  We have many libraries that depends on a qt package, and it does not make sense to include all qt dlls in all our libraries. Ultimately, the final application should collect qt dlls from qt package and not from all libraries that uses qt.
* If two libraries uses two different versions of qt, the final application won't work as dlls may not be compatible, for that we need the conan requirement to be **public** so that we can catch this conflict.

**Comment by SpaceIm** [comment] 2021-03-07 13:51
> regarding private conan requirement, are they analogic to cmake private linking?

No, private conan requirements are not propagated, they are not as smart as CMake private/public/interface mechanism.

The only case I see where you can safely use private conan requirement is:
the recipe builds a shared lib, and its "private" dependency is static or header-only (as well as all its own dependencies, recursively)

**Comment by boussaffawalid** [comment] 2021-03-09 00:10
Does it make sense to add an ability to specify non transitive deps to the conan requires method.
Something like:
```
self.requires("zlib/1.2@drl/testing", private=False, override=False, transitive=True)
```
Ultimately all deps should be public, but there should be a way to define non transitive deps as currently all public deps are
transitive.

**Comment by PengolodhGoedath** [comment] 2021-03-09 06:12
Is `MyLib` a shared library (DLL)? If not, then the final application will have to link against its dependencies, otherwise it likely won't work as intended.

With that out of the way, if `MyLib` is indeed a shared library, then there is no reason for the final application to link against its dependencies (unless the final application uses them directly).

In either case, whether to link or not, it's the responsibility of the next layer down (the build system, CMake?), not conan. You can have everything as public dependencies in conan (so you have the DLLs available) and still not link against transitive dependencies (as linking isn't conan's job).

For more help, we would need more information about your setup.

---

In conan, every dependency is transitive - if you build all dependencies from source. This can sometimes be hidden by providing precompiled binaries for dependencies, but at the basic level I can always say `conan install . --build all` to force build everything from source.

**Comment by boussaffawalid** [comment] 2021-03-09 08:14
We use conan cmake/cmake_multi generators with `TARGETS` for simplicity so that we only link against against one target `CONAN_PKG::<PKG-NAME>`. However this is problematic as:
* `CONAN_PKG::<PKG-NAME>` define all shared conan dependencies as transitive dependencies by defining the cmake property `INTERFACE_LINK_LIBRARIES`.
* Some of our packages defines multiple libraries and sometime we don't want to link against all of them 

I don't know if this is a limitation of cmake/cmake_multi generators! Besides that cmake/cmake_multi generators doesn't support [conan components](https://docs.conan.io/en/latest/creating_packages/package_information.html#using-components)
Maybe we need to switch to a different generator

**Comment by memsharded** [comment] 2024-12-30 00:44
Closing this ticket as outdated. Conan 2 provided new mechanisms to control visibility and propagation. Also the generators reported here were deprecated time ago and completely removed in Conan 2. 
Please create new tickets if necessary, thanks for the feedback.

**Closed as completed by memsharded** 2024-12-30 00:44 UTC
