### ISSUE TITLE
[question] How to debug package_id calculation/check to what is available on server?

### ISSUE THREAD

**Issue by iiknd** [conan-io/conan#9607] opened 2021-09-15 07:51 UTC
Hi,

we have a conan package(s) available on server built with --profile=abc built by our CI system.
The package's recipe uses: self.info.requires.package_revision_mode()

> These dependency graphs cannot be built in a single invocation, because they are **intended for CI systems**, in which a package creation/built is called for each package in the graph.

We exclude certain options from the package_id which we control:

```
def package_id(self):
    rm_list = ["foo", "bar", ....]
    for item in rm_list:
        if item in self.info.options:
            delattr(self.info.options, item)
```

Also, we have two options (showing one here for simplicity) which contain delimeter separated list of arguments.
We filter out certain arguments which we do not want to affect the package_id:

```
    if hasattr(self, "option_x"):
        # e.g. option_x="a b c d" -> option_x="a c"
        self.option_x = filter_arguments(self.option_x)
```

The reason for excluding these specific options from package_id is that our CI uses those options for the builds
(for example sccache) but these options have no real effect on the binary compatibility _and_ the consumers probably won't use these options in their environment -> we still want to make it possible for the consumers to install the pre-built binaries from the server.

I tried to install the package from the server using the same --profile=abc --build=missing (or --build=never) but it forces the build from sources locally.

Is there something I'm missing in the package_id calculation? Is there any ways to debug/trace where exactly the check fails?
I've compared the conaninfo.txt from the server for the given --profile=abc and the conaninfo.txt that was produced from my local build and they are identical except for the "option_x" which is filtered.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment] 2021-09-16 06:41
Hi,

Is the `option_x` excluded from the package_id or not? In case it is, it shouldn't appear in the `conaninfo.txt` file.
If it is not excluded and has a different value, it would justify why it doesn't find the package, because the package_id will change with a different value of the option (filtered vs not filtered)

To debug, what I would do first is to compare the computed package_id generated on the server and the local one, it should appear in the traces when building or checking the server to download the binary.  You can also run a `conan info . --profile=abc` to know the `ID`. Then if the ID is equal to the built at the server, there might be an error whereby the client cannot download the package (missing? remote configuration? different recipe revision?). If the ID is different, something is wrong in the `configure` method where you remove the options.

It is difficult to know, if you could provide an example to reproduce I can check.

**Comment by iiknd** [comment] 2021-09-17 08:23
> Is the option_x excluded from the package_id or not?

Contents (string) of the option_x value are filtered.

An example to demonstrate the case:

```
[options]
option_x = "foo;bar;sccache;foo2;bar2"  # used by the CI and binaries uploaded to server
```

In the recipe:

```
def package_id(self):
    self.info.options.option_x = filter_func(self.info.options.option_x)
```

After the build the conaninfo.txt shows correctly:

```
[options]
option_x = "foo;bar;foo2;bar2"

```
i.e. the binary compatible part was removed, i.e. the "sccache" in this example should not affect the binary compatibility.

EDIT:

I was able to get this working afterall i.e. to install the binaries locally from the server with a profile where I have:

```
[options]
option_x = "foo;bar;foo2;bar2"  # sccache not included, which was used by the CI
```

I think my local cache was not in sync (the filtering is implemented in python_requires package).
Using "--update" along with the install command did the job I think.

I think this ticket can be closed now, but one remaining question about the package_id checksum calculation.
Is there a difference in checksums for these variations:

```
[options]
option_x=""
option_x=''
option_x=
```

**Comment by lasote** [comment] 2021-09-20 06:14
`option_x=` could correspond to a `None` that is different from an empty string but I'm not sure how `option_x=""` and `option_x=''` could be dumped to the `conaninfo.txt`. If the value is different the ID is different, but as far as I know, the empty string is always the same.

**Comment by lasote** [comment] 2021-09-20 06:15
I'm closing the issue, We can still discussing any doubt about that, I will receive the notifications.

**Closed as completed by lasote** 2021-09-20 06:15 UTC
Labels: stage: triaging
