### ISSUE TITLE
[suggestion] Semver based ABI compatibility is a bad default

### ISSUE THREAD

**Issue by ilmola** [conan-io/conan#6270] opened 2019-12-21 21:29 UTC
Lets say that libA version 1.0.0 has an inline function "foo()".

LibB version 1.0.0 depends on libA\[~1.0.0].

An application depends on libB\[~1.0.0].

A bug is fixed from the function "foo()" and version 1.0.1 of libA is released.

The application is rebuild. It will get the new version of libA, but Conan uses the pre-build version of libB which has inlined function "foo()" and the bug remains.

This seem to be a very dangerous default behaviour as it makes it impossible to fix any bugs in inline functions, macros or templates without incrementing the major version.

There may be rare exceptions to this, but as most libraries have inline functions, macros or templates this is a bad default.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2019-12-22 10:18
Hi @ilmola 

Yes, thanks for telling, we are aware of this issue. This is why the ``default_package_id_mode`` configuration was defined: https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html?#changing-the-default-package-id-mode

The default cannot be changed, because that will be breaking, according to the 1.0 policy: https://docs.conan.io/en/latest/introduction.html#stable. The default package-id mode will surely change in Conan 2.0.

**Comment by danimtb** [comment] 2019-12-23 09:45
I think this is a duplicate of https://github.com/conan-io/conan/issues/3762

**Comment by memsharded** [comment] 2019-12-23 10:45
Yes, I think this conversation can be followed there, thanks!

**Closed by memsharded** 2019-12-23 10:45 UTC
Labels: stage: triaging, type: question
