### ISSUE TITLE
[question] Explicit setting propagating to dependencies

### ISSUE THREAD

**Issue by theodor96** [conan-io/conan#8834] opened 2021-04-20 16:52 UTC
Looking at the [`conan install` documentation](https://docs.conan.io/en/latest/reference/commands/consumer/install.html), it seems that if I want to specify a specific setting to apply to only one package, I would say:

`conan install -s mypackage:arch=x86 .`

Which kind of works fine. Except when `mypackage` has its own dependencies (that it declares as `requires = ...` in its recipe). When Conan installs those dependencies, it will take the profile settings instead of propagating the `arch=x86` setting that I explicitly specified for `mypackage` and which I expected to propagate to its dependencies.

Is this by design, am I doing it wrong, or it is some kind of bug?

**Comment by memsharded** [comment] 2021-04-20 20:37
Hi @theodor96 

This is by design, settings do not propagate, they should be defined at the profile level, for all packages. Settings are mostly intended for project-wide configuration. If the transitive dependencies also have the same settings, why not defining ``-s arch=x86`` for all packages?

One common use case is having different settings for build tools (build-requires in the build context) and for the host libraries. Using ``--profile:build=myprofilebuild --profile:host=myprofilehost`` will allow defining different settings for each context, could this be the use case you are interested in?

**Comment by theodor96** [comment] 2021-04-20 21:15
Oh, I see. I was fearing this might be it.

You're almost right, I do have sort of a build tool (actually a testing tool, but which is never going to be needed by the actual consumers of my library) so I guess I could use different profiles for the tool and for my libraries' dependencies.

But how can I say for example, `--profile:build=my_build_profile.txt` and have `my_build_profile.txt` identical to the user's `default` profile, except for the settings which I intend to customize? It wouldn't be very feasible to just version control the profile because that way it could potentially be very different from the `default`, right?

To answer your question -- why not define `-s arch=x86` for all packages -- because only the tool (and by transitivity, its deps) require `x86`. For the rest of my actual dependencies, I want to take whatever's in the `default` profile.

**Comment by memsharded** [comment] 2021-04-20 21:37
> But how can I say for example, --profile:build=my_build_profile.txt and have my_build_profile.txt identical to the user's default profile, except for the settings which I intend to customize? 

Profiles can be included, for example you can have:
**mybuildprofile**
```
include(default)
[settings]
arch=x86
```
This will override the architecture defined in ``default`` with x86. 
It is also very recommended to manage all your profiles in a git repo and use ``conan config install`` to install them in the conan cache, and maintain your team and CI servers, etc, all synced with same profiles. Actually the "user" profile should not be the default auto-detected one for production. It is recommended that you explicitly define and maintain your profile for your supported platforms, and do not rely on Conan profile auto-detection.

**Comment by theodor96** [comment] 2021-04-20 22:59
While version controlling the profiles is definitely out of scope (at least for now and at least for what I'm currently trying to do), it definitely sounds good to have in the future. We're currently relying on the auto detection as you inferred.

I'll try the inclusion thing and hope it all works out nicely for the time being.

Thanks for helping me out.

**Comment by memsharded** [comment] 2024-07-19 17:35
Closing as responded back then. Please create new tickets for any further question, thanks for the feedback!

**Closed as completed by memsharded** 2024-07-19 17:35 UTC
Labels: stage: triaging
