### ISSUE TITLE
[bug] CMake append_vcvars=False still loads vcvars into environment

### ISSUE THREAD

**Issue by awakecoding** [conan-io/conan#6608] opened 2020-03-02 16:19 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2019
  * Conan version: 1.22
  * Python version: 3.7.4

### Steps to reproduce (Include if Applicable)

When using the CMake tool with the 'Ninja' generator on Windows with MSVC, calling cmake.run() *always* results in loading vcvars (calling vcvarsall.bat + modifying the environment including the PATH). While this can be very helpful as a default behaviour, I wish to explicitly avoid polluting the environment before calling CMake because I have my own toolchain file that makes its own detection and works fine without requiring to be executed within an MSVC developer command-prompt environment.

Looking at the documentation, it looks like a new append_vcvars parameter was added in 1.22 (https://docs.conan.io/en/1.22/reference/build_helpers/cmake.html#constructor) to control this default behaviour. However, it appears that the CMake conan tool will modify the environment in all cases even if append_vcvars=False. I absolutely need to disable loading the vcvars because it is causing issues down the line in my build system: my cmake scripts call cargo to build Rust code, and because the vcvars are loaded, they get picked up by the Rust compiler, and this breaks the compilation of certain crates like proc-macro2 when using the 64-bit MSVC toolchain to target 32-bit Windows.

Here is the relevant part of code causing the issue:
https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake.py#L222

The expected behaviour would be that append_vcvars=False *never* loads the vcvars, even partially.

**Comment by memsharded** [comment] 2020-03-03 13:34
Hi @awakecoding 

I understand the point, but in this case this is not a bug. The docs https://docs.conan.io/en/latest/reference/build_helpers/cmake.html#constructor clearly define the ``append_vcvars`` semantics as a priority thing, pre-pend vs append.

Then, this shouldn't be changed, as it would clearly be breaking behavior. 

What could be done is to add another opt-in argument that would just disable this behavior. This should be easy, no-risk. It is also possible the direction in which build-helpers will evolve for Conan 2.0, they will be doing less, and the environment might be managed differently.

Conan 1.23 is very close, we don't have the time to add it, but if you would like to submit a PR yourself, then, it might have a chance. Otherwise, I will leave it as a "good first issue" feature request. Thanks!

**Comment by awakecoding** [comment] 2020-03-03 14:23
I managed to make it work by explicitly unsetting a couple of environment variables (VCINSTALLDIR, LIB, LIBPATH, INCLUDE) that are set by loading the vcvars. I understand append_vcvars=False does not mean disabling the appending of vcvars, but just controlling if they are either prepended or appended. In this case, would you rather add another option to disable loading the vcvars entirely? I would be happy with an environment variable + constructor parameter. 

The current code will unconditionally load the vcvars when using MSVC on Windows with the Ninja generator, which leaves no space for taking over the control of loading the vcvars outside of conan.

**Comment by memsharded** [comment] 2020-03-03 15:42
> In this case, would you rather add another option to disable loading the vcvars entirely? I would be happy with an environment variable + constructor parameter.

Yes, yes, totally, that was I was suggesting above. Sorry if it wasn't clear with "What could be done is to add another opt-in argument that would just disable this behavior. ". What I wanted to say is:

- Add an opt-in argument to CMake constructor, with the meaning ``dont_apply_vcvars=False``. 
- If user set ``dont_apply_vcvars=True``, then, the code in ``def _run()`` that calls vcvars is skipped.

**Comment by nick-schultz** [comment] 2022-02-05 00:16
What's the status of this ticket?  I'm trying to accomplish something similar, except I am distributing the build tools via `[tool_requires]` in a build profile (compiler, cmake, ninja, etc..)

**Comment by memsharded** [comment] 2022-02-07 16:52
Hi @nick-schultz 

This build-system integration is being superseded by the new ``CMakeToolchain``, etc, that also includes a whole new model of the environment. Please have a look to: https://docs.conan.io/en/latest/reference/conanfile/tools/env.html. This will be solutions that will survive in 2.0 (already in alpha stage), the others will be removed.

With this, users and recipes have total control of what environments are used by tools, as the ``CMake`` tool no longer has logic associated to that, but everything happens in the ``generate()`` method. Please have a look to the new integrations, and better to submit a new ticket. Thanks!

**Comment by memsharded** [comment] 2023-11-29 22:55
Closing this ticket as outdated, please check new integrations like CMakeToolchain and report against them if necessary, thanks!

**Closed by memsharded** 2023-11-29 22:55 UTC
Labels: priority: low, type: feature, good first issue, stage: queue, complex: low, component: Build
