### ISSUE TITLE
[bug] CMakeDeps: Malformed generator expression set in imported target property

### ISSUE THREAD

**Issue by hadi-rahimi** [conan-io/conan#13976] opened 2023-05-26 14:16 UTC
### Environment details

* Windows 11
* Visual Studio 2022
* Conan 2.0.5
* Python 3.8.10
* CMake 3.26.0-rc3

#### Description
I'm having a problem in my project, which I could reproduce in a simple C++ HelloWorld CMake project (attached).
The project uses CMakeDeps and CMakeToolchain generators.

When reading INTERFACE_COMPILE_OPTIONS property of an imported target in CMake, it contains malformed generator expression:
 `$<$<CONFIG:Debug>:$<$<COMPILE_LANGUAGE:CXX>:>`
 whereas it should be:
 `$<$<CONFIG:Debug>:$<$<COMPILE_LANGUAGE:CXX>:>>`

My CMakeLists.txt file:
```
cmake_minimum_required(VERSION 3.26)
project(HelloWorld)

find_package(fmt REQUIRED)

# Print interface compile options
get_target_property(x fmt::fmt-header-only INTERFACE_COMPILE_OPTIONS)
foreach(y ${x})
    message("${y}")
endforeach()

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE fmt::fmt-header-only)
```
#### Steps to reproduce:
1. Download [helloworld.zip](https://github.com/conan-io/conan/files/11575217/helloworld.zip) and extract the source code.
2. Run build.bat in project root in cmd.exe.
3. Find the generator expression printed in output.
#### Output:
Output log contains the following line:
`$<$<CONFIG:Release>:$<$<COMPILE_LANGUAGE:CXX>:>`
#### Expected:
`$<$<CONFIG:Release>:$<$<COMPILE_LANGUAGE:CXX>:>>`

### Logs

```
D:\dev\helloworld>build.bat

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=msvc
compiler.cppstd=17
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=193
os=Windows


======== Computing dependency graph ========
Graph root
    conanfile.py: D:\dev\helloworld\conanfile.py
Requirements
    fmt/9.1.0#44302d39c5a4bf7de8a39adc50bb4568 - Cache

======== Computing necessary packages ========
Requirements
    fmt/9.1.0#44302d39c5a4bf7de8a39adc50bb4568:da39a3ee5e6b4b0d3255bfef95601890afd80709#23660355cc67a81c3b47d66bb487e3ef - Cache

======== Installing packages ========
fmt/9.1.0: Already installed! (1 of 1)
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'cpp_info.names' used in: fmt/9.1.0

======== Finalizing install (deploy, generators) ========
conanfile.py: Writing generators to D:\dev\helloworld\build
conanfile.py: Generator 'CMakeDeps' calling 'generate()'
conanfile.py: Generator 'CMakeToolchain' calling 'generate()'
conanfile.py: CMakeToolchain generated: conan_toolchain.cmake
conanfile.py: Preset 'conan-default' added to CMakePresets.json. Invoke it manually using 'cmake --preset conan-default' if using CMake>=3.23
conanfile.py: If your CMake version is not compatible with CMakePresets (<3.23) call cmake like: 'cmake <path> -G "Visual Studio 17 2022" -DCMAKE_TOOLCHAIN_FILE=D:\dev\helloworld\build\conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW'
conanfile.py: CMakeToolchain generated: CMakePresets.json
conanfile.py: CMakeToolchain generated: ..\CMakeUserPresets.json
conanfile.py: Generating aggregated env files
conanfile.py: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
Install finished successfully
-- Using Conan toolchain: D:/dev/helloworld/build/conan_toolchain.cmake
-- Conan toolchain: C++ Standard 17 with extensions OFF
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.35.32217.1
-- The CXX compiler identification is MSVC 19.35.32217.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Component target declared 'fmt::fmt-header-only'
$<$<CONFIG:Release>:$<$<COMPILE_LANGUAGE:CXX>:>
$<$<COMPILE_LANGUAGE:C>:>>
-- Configuring done (3.3s)
-- Generating done (0.0s)
-- Build files have been written to: D:/dev/helloworld/build
MSBuild version 17.5.1+f6fdcf537 for .NET Framework

  1>Checking Build System
  1>Building Custom Rule D:/dev/helloworld/CMakeLists.txt
  main.cpp
  HelloWorld.vcxproj -> D:\dev\helloworld\build\Release\HelloWorld.exe
  1>Building Custom Rule D:/dev/helloworld/CMakeLists.txt
```

**Comment by memsharded** [comment] 2023-05-26 15:49
Hi @hadi-rahimi 

Thanks for reporting. I am not sure this is a bug.

You say that the expression is ``$<$<CONFIG:Debug>:$<$<COMPILE_LANGUAGE:CXX>:>``, which seems to have some imbalance in the <>. But it is not, the expression is: ``$<$<CONFIG:Release>:$<$<COMPILE_LANGUAGE:CXX>:>$<$<COMPILE_LANGUAGE:C>:>>``, it is a single expression that has a line break in it. 

Apparently the line break does not affect CMake evaluation of the expression, it is your printing of it that is splitting it into pieces. I have just tested and it seems that the different compile options for C and CXX flags is working fine. Could you please double check it?

**Comment by hadi-rahimi** [comment] 2023-05-30 10:09
Hi,
Thank you for looking into my problem. Yes, that's broken into two parts by an extra semicolon inserted.  As I inspected, that's because `fmt_COMPILE_OPTIONS_RELEASE` is a list as can be seen in `fmt-release-x86_64-data.cmake`:
```
# COMPOUND VARIABLES
set(fmt_COMPILE_OPTIONS_RELEASE
    "$<$<COMPILE_LANGUAGE:CXX>:${fmt_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${fmt_COMPILE_OPTIONS_C_RELEASE}>")

```
I guess CMake has appended it to the interface compiler options by enclosing it in double quotes like this:
`list(APPEND INTERFACE_COMPILE_OPTIONS "$<$<CONFIG:Release>:${fmt_COMPILE_OPTIONS_RELEASE}>")`
`list(APPEND INTERFACE_COMPILE_OPTIONS "$<$<CONFIG:Debug>:${fmt_COMPILE_OPTIONS_DEBUG}>")`
and as it's a list, an extra semicolon is inserted into the string, which breaks INTERFACE_COMPILE_OPTIONS into two parts:

So in target_data.py I updated the template, and changed the list into a single string. Changed the line from:
```
set({{ pkg_name }}_{{ comp_variable_name }}_COMPILE_OPTIONS{{ config_suffix }}
    "$<$<COMPILE_LANGUAGE:CXX>:${fmt_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${fmt_COMPILE_OPTIONS_C_RELEASE}>")
```
into:
```
string(CONCAT {{ pkg_name }}_{{ comp_variable_name }}_COMPILE_OPTIONS{{ config_suffix }}`
    "$<$<COMPILE_LANGUAGE:CXX>:${fmt_COMPILE_OPTIONS_CXX_RELEASE}>"
    "$<$<COMPILE_LANGUAGE:C>:${fmt_COMPILE_OPTIONS_C_RELEASE}>")
```
This fixes the problem and works, but as long as `fmt_COMPILE_OPTIONS_CXX_RELEASE` and `fmt_COMPILE_OPTIONS_C_RELEASE` are empty.

But what if they are not empty, which means they have some compiler options inside, seperated by semicolons?
I haven't inspected that yet.

**Comment by memsharded** [comment] 2023-05-30 11:06
> But what if they are not empty, which means they have some compiler options inside, seperated by semicolons?
I haven't inspected that yet.

This is what I was testing. I did some builds for ``main.c`` and ``main.cpp`` with different options defined for ``cflags`` and ``cxxflags``, and each build was correctly getting the matching flags. This is why I was commenting that the feature seems to be working correctly, that is the intent of the feature and seems to be working fine.
If we are going to propose some changes there, it would be good to have a real reproducible case, with actual building and checking that the build is getting the right options, better than just printing/message.

**Comment by memsharded** [comment] 2024-12-22 23:52
Closing as staled, this was not followed up.

In any case, this might be resolved by the new "incubating" CMakeDeps, see https://docs.conan.io/2/incubating.html.

Please create new tickets for any further question.

**Closed as completed by memsharded** 2024-12-22 23:52 UTC
Labels: stage: triaging
