### ISSUE TITLE
Error 401 getting packages from conan-center

### ISSUE THREAD

**Issue by cadubentzen** [conan-io/conan#3046] opened 2018-06-14 01:28 UTC
To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Using Conan version 1.4.4, on Arch Linux and installed via pip, I get this error when trying to download conan packages:

```
ERROR: Error 401 downloading file https://api.bintray.com/conan/conan/conan-center/v1/files/pocoproject/Poco/1.9.0/stable/export/conanmanifest.txt. [Remote: conan-center]
```

It also happened with zlib. Running `conan search Poco/1.9.0@pocoproject/stable` also yields this:
```
ERROR: Recipe not found: Poco/1.9.0@pocoproject/stable
```

I basically tried the `Getting started` tutorial and got stuck in this step.

**Comment by danimtb** [comment] 2018-06-14 08:23
Hi @cadubentzen 

`conan search` performs a search in your conan cache instead of in remotes. Please check this seccion in the getting started: https://docs.conan.io/en/latest/getting_started.html#searching-packages

Regarding the connection issue this seems to be a random issue as this seems to work from my side: Could you please try again?

Thanks!

**Comment by memsharded** [comment] 2018-06-14 10:59
Other debug tips:

- Are you behind a proxy?
- Can you just paste https://api.bintray.com/conan/conan/conan-center/v1/files/pocoproject/Poco/1.9.0/stable/export/conanmanifest.txt in your browser and see if it is able to download the file?

Please try those and report. Thanks!

**Comment by cadubentzen** [comment] 2018-06-19 00:05
Hi @danimtb and @memsharded! Thanks for the quick replies and sorry for my long delay.

I just checked here again and no luck so far.

> conan search performs a search in your conan cache instead of in remotes. Please check this seccion in the getting started: https://docs.conan.io/en/latest/getting_started.html#searching-packages

Sorry I was confused. Checked here and `conan search "zlib*" -r=conan-center` works, but `conan install` doesn't.

> Are you behind a proxy?

No.

> Can you just paste https://api.bintray.com/conan/conan/conan-center/v1/files/pocoproject/Poco/1.9.0/stable/export/conanmanifest.txt in your browser and see if it is able to download the file?

My browser downloads it just fine.

I reinstalled it via AUR and still no luck :/

**Comment by cadubentzen** [comment] 2018-06-25 23:09
No luck with that either :/ Do you know any Arch user and they had some trouble? Thanks!

**Comment by memsharded** [comment] 2018-06-26 17:16
@tivek is doing a great job creating and maintaining the Arch conan packages. I think @Manu343726 is also an Arch user. Maybe they have some idea.

I would say that might be related to the python-requests library (could be worth that  you output here the exact versions of the python packages installed for conan), that might be adding some headers or is old, or something, and bintray is denying access. I guess that you have tried with different packages, and the result is always the same.

**Comment by tivek** [comment] 2018-06-26 23:42
I cannot reproduce the issue with Conan from AUR on up-to-date Arch or from PyPI installed inside a clean Python 3 virtual environment.

@cadubentzen, how exactly did you install conan using pip? System-wide, pip install --user, inside a virtual environment?

**Comment by cadubentzen** [comment] 2018-06-26 23:53
Hi @tivek! I had installed with `pip install --user`and AUR,  but now that you said I also tried with a clean Python 3 venv, but the same error ocurred.

**Comment by tivek** [comment] 2018-06-28 17:36
This does not sound like a settings problem, but just to be sure... could you try moving ```~/.conan``` somewhere safe and have a fresh start? Or maybe run AUR Conan as a new user?

**Comment by CMLivingston** [comment] 2018-09-10 18:27
Hello all,
Conan 1.7.3 client now prompts the user to authenticate against conan-center. Is this issue still relevant/considered a bug?

**Comment by memsharded** [comment] 2018-09-10 21:46
Hi @CMLivingston 

Can't reproduce this behavior. I am testing with conan 1.7.3. Make sure:

```bash
$ conan user --clean
$ conan install zlib/1.2.11@conan/stable -r=conan-center
```
That still prompts for authentication?

**Comment by cadubentzen** [comment] 2018-09-10 21:51
Since the time I reported the issue, I already switched distros, so I can't test easily if the original issue is still reproducible.

**Comment by CMLivingston** [comment] 2018-09-10 22:47
Yes. These credentials log me into https://bintray.com/ successfully, however the client gives me the following issue:
```
[tw-mbp-clivingston ~]$ conan -v
Conan version 1.7.3
[tw-mbp-clivingston ~]$ conan user --clean
[tw-mbp-clivingston ~]$ conan install zlib/1.2.11@conan/stable -r=conan-center
zlib/1.2.11@conan/stable: Not found, retrieving from server 'conan-center'
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
ERROR:
Waiting 0 seconds to retry...
ERROR:
Waiting 0 seconds to retry...
Please log in to "conan-center" to perform this action. Execute "conan user" command.
If you don't have an account sign up here: https://bintray.com/signup/oss
Remote 'conan-center' username: clivingston
Please enter a password for "clivingston" account:
ERROR: Wrong user or password
Remote 'conan-center' username: clivingston
Please enter a password for "clivingston" account:
ERROR: Wrong user or password
Remote 'conan-center' username: clivingston
Please enter a password for "clivingston" account:
ERROR: Wrong user or password
ERROR: Failed requirement 'zlib/1.2.11@conan/stable' from 'PROJECT'
ERROR: Too many failed login attempts, bye!. [Remote: conan-center]
```
This also fails to authenticate:
```
[tw-mbp-clivingston ~]$ conan user clivingston -p
Please enter a password for "clivingston" account:
ERROR: Wrong user or password. [Remote: conan-center]
```
Does conan-center in particular require any additional credentials or permissions of some sort? My creds here are for bintray as indicated by https://bintray.com/signup/oss.

**Comment by memsharded** [comment] 2018-09-10 23:00
This is very weird. It should (and it seems so on my side) allow anonymous usage.

- Which OS?
- Is it possible that you are behind a proxy or something that could be injecting headers?
- Can you do a ``conan search zlib* -r=conan-center``?
- It seems that you are in OSX. How did you installed conan? Might be an issue of the https python libraries, failing, could you please try installing it from ``pip`` instead of ``brew``?

Thanks!

**Comment by CMLivingston** [comment] 2018-09-10 23:06
One of our engineers found that this was happening due to an overly broad default entry in ~/.netrc. Removing the default cleared up the issue and allowed for anonymous usage again. Thanks for the quick responses and sorry for the false alarm!

**Comment by memsharded** [comment] 2018-09-11 10:39
Hi all!

No problem @CMLivingston , great to help, glad that you found and solved the issue.

As @cadubentzen moved to another distro, we don't have further feedback from other Arch users, besides @tivek, that couldn't reproduce, I am going to close this issue at the moment, but feel free to re-open or comment if the problem appears again. Thanks!

**Closed by memsharded** 2018-09-11 10:39 UTC

**Comment by ruipires** [comment] 2019-09-20 14:30
I am experiencing this exact issue, but running on Debian 9.
Installed conan on a venv, and it requests password when retrieving OpenSSL (other packages seem OK).

> conan install ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=6
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

cpprestsdk/2.10.14@bincrafters/stable: Not found in local cache, looking in remotes...
cpprestsdk/2.10.14@bincrafters/stable: Trying with 'conan-center'...
cpprestsdk/2.10.14@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt: 100%|##########| 166/166 [00:00<00:00, 10.6kB/s]
Downloading conanfile.py: 100%|##########| 9.57k/9.57k [00:00<00:00, 7.23MB/s]
Downloading conan_export.tgz: 100%|##########| 761/761 [00:00<00:00, 939kB/s]
Decompressing conan_export.tgz: 2.23kB [00:00, 420kB/s]
cpprestsdk/2.10.14@bincrafters/stable: Downloaded recipe revision 0
OpenSSL/1.1.1c@conan/stable: Not found in local cache, looking in remotes...
OpenSSL/1.1.1c@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 58.0/58.0 [00:00<00:00, 21.5kB/s]
Downloading conanfile.py: 100%|##########| 28.7k/28.7k [00:00<00:00, 975kB/s]
OpenSSL/1.1.1c@conan/stable: Downloaded recipe revision 0
zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 296/296 [00:00<00:00, 272kB/s]
Downloading conanfile.py: 100%|##########| 8.74k/8.74k [00:00<00:00, 9.90MB/s]
Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 953kB/s]
Decompressing conan_export.tgz: 2.24kB [00:00, 990kB/s]
zlib/1.2.11@conan/stable: Downloaded recipe revision 0
websocketpp/0.8.1@bincrafters/stable: Not found in local cache, looking in remotes...
websocketpp/0.8.1@bincrafters/stable: Trying with 'conan-center'...
websocketpp/0.8.1@bincrafters/stable: Trying with 'bincrafters'...
Downloading conanmanifest.txt: 100%|##########| 121/121 [00:00<00:00, 84.9kB/s]
Downloading conanfile.py: 100%|##########| 2.36k/2.36k [00:00<00:00, 2.74MB/s]
websocketpp/0.8.1@bincrafters/stable: Downloaded recipe revision 0
boost/1.69.0@conan/stable: Not found in local cache, looking in remotes...
boost/1.69.0@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 303/303 [00:00<00:00, 219kB/s]
Downloading conanfile.py: 100%|##########| 37.3k/37.3k [00:00<00:00, 24.2MB/s]
boost/1.69.0@conan/stable: Downloaded recipe revision 0
boost/1.69.0@conan/stable: WARN: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd', please update your recipe.
bzip2/1.0.6@conan/stable: Not found in local cache, looking in remotes...
bzip2/1.0.6@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 163/163 [00:00<00:00, 136kB/s]
Downloading conanfile.py: 100%|##########| 2.21k/2.21k [00:00<00:00, 2.12MB/s]
Downloading conan_export.tgz: 100%|##########| 766/766 [00:00<00:00, 992kB/s]
Decompressing conan_export.tgz: 2.24kB [00:00, 1.18MB/s]
bzip2/1.0.6@conan/stable: Downloaded recipe revision 0
spdlog/1.3.1@bincrafters/stable: Not found in local cache, looking in remotes...
spdlog/1.3.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 166/166 [00:00<00:00, 201kB/s]
Downloading conanfile.py: 100%|##########| 1.93k/1.93k [00:00<00:00, 2.11MB/s]
Downloading conan_export.tgz: 100%|##########| 764/764 [00:00<00:00, 935kB/s]
Decompressing conan_export.tgz: 2.24kB [00:00, 1.02MB/s]
spdlog/1.3.1@bincrafters/stable: Downloaded recipe revision 0
fmt/5.3.0@bincrafters/stable: Not found in local cache, looking in remotes...
fmt/5.3.0@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 166/166 [00:00<00:00, 164kB/s]
Downloading conanfile.py: 100%|##########| 2.99k/2.99k [00:00<00:00, 1.43MB/s]
Downloading conan_export.tgz: 100%|##########| 758/758 [00:00<00:00, 986kB/s]
Decompressing conan_export.tgz: 2.22kB [00:00, 937kB/s]
fmt/5.3.0@bincrafters/stable: Downloaded recipe revision 0
Catch2/2.9.2@catchorg/stable: Not found in local cache, looking in remotes...
Catch2/2.9.2@catchorg/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt: 100%|##########| 1.36k/1.36k [00:00<00:00, 105kB/s]
Downloading conanfile.py: 100%|##########| 909/909 [00:00<00:00, 688kB/s]
Downloading conan_export.tgz: 100%|##########| 891/891 [00:00<00:00, 746kB/s]
Decompressing conan_export.tgz: 2.61kB [00:00, 154kB/s]
Catch2/2.9.2@catchorg/stable: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    Catch2/2.9.2@catchorg/stable from 'conan-center' - Downloaded
    OpenSSL/1.1.1c@conan/stable from 'conan-center' - Downloaded
    boost/1.69.0@conan/stable from 'conan-center' - Downloaded
    bzip2/1.0.6@conan/stable from 'conan-center' - Downloaded
    cpprestsdk/2.10.14@bincrafters/stable from 'bincrafters' - Downloaded
    fmt/5.3.0@bincrafters/stable from 'conan-center' - Downloaded
    spdlog/1.3.1@bincrafters/stable from 'conan-center' - Downloaded
    websocketpp/0.8.1@bincrafters/stable from 'bincrafters' - Downloaded
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    Catch2/2.9.2@catchorg/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    OpenSSL/1.1.1c@conan/stable:008f1a2b119556f550c1109663570e0f5040c13f - Download
    boost/1.69.0@conan/stable:16227604e1a14c8dcad4488915fe62fb570c8dd7 - Download
    bzip2/1.0.6@conan/stable:09e3a4c43285997784a5fcaefa367cb780af2032 - Download
    cpprestsdk/2.10.14@bincrafters/stable:906e5335b4b1221491fb35bd98e53195c6bb47be - Missing
    fmt/5.3.0@bincrafters/stable:d0ec62fc032e5a10524fa454546aa1bdbb22baf8 - Download
    spdlog/1.3.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    websocketpp/0.8.1@bincrafters/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download
    zlib/1.2.11@conan/stable:f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb - Download

Catch2/2.9.2@catchorg/stable: Retrieving package 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 0.98k/0.98k [00:00<00:00, 828kB/s]
Downloading conaninfo.txt: 100%|##########| 150/150 [00:00<00:00, 166kB/s]
Downloading conan_package.tgz: 100%|##########| 127k/127k [00:00<00:00, 2.93MB/s]
Decompressing conan_package.tgz: 143kB [00:00, 4.33MB/s]
Catch2/2.9.2@catchorg/stable: Package installed 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
Catch2/2.9.2@catchorg/stable: Downloaded package revision 0
bzip2/1.0.6@conan/stable: Retrieving package 09e3a4c43285997784a5fcaefa367cb780af2032 from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 395/395 [00:00<00:00, 445kB/s]
Downloading conaninfo.txt: 100%|##########| 444/444 [00:00<00:00, 446kB/s]
Downloading conan_package.tgz: 100%|##########| 98.1k/98.1k [00:00<00:00, 4.48MB/s]
Decompressing conan_package.tgz: 114kB [00:00, 2.80MB/s]
bzip2/1.0.6@conan/stable: Package installed 09e3a4c43285997784a5fcaefa367cb780af2032
bzip2/1.0.6@conan/stable: Downloaded package revision 0
fmt/5.3.0@bincrafters/stable: Retrieving package d0ec62fc032e5a10524fa454546aa1bdbb22baf8 from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 1.07k/1.07k [00:00<00:00, 499kB/s]
Downloading conaninfo.txt: 100%|##########| 525/525 [00:00<00:00, 218kB/s]
Downloading conan_package.tgz: 100%|##########| 150k/150k [00:00<00:00, 4.69MB/s]
Decompressing conan_package.tgz: 166kB [00:00, 1.75MB/s]
fmt/5.3.0@bincrafters/stable: Package installed d0ec62fc032e5a10524fa454546aa1bdbb22baf8
fmt/5.3.0@bincrafters/stable: Downloaded package revision 0
zlib/1.2.11@conan/stable: Retrieving package f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 352/352 [00:00<00:00, 393kB/s]
Downloading conaninfo.txt: 100%|##########| 428/428 [00:00<00:00, 506kB/s]
Downloading conan_package.tgz: 100%|##########| 92.0k/92.0k [00:00<00:00, 26.4MB/s]
Decompressing conan_package.tgz: 108kB [00:00, 14.5MB/s]
zlib/1.2.11@conan/stable: Package installed f7e573cb501ccfc49e9e4d84de886bc1ef2e6ebb
zlib/1.2.11@conan/stable: Downloaded package revision 0
OpenSSL/1.1.1c@conan/stable: Retrieving package 008f1a2b119556f550c1109663570e0f5040c13f from remote 'conan-center'
Downloading conanmanifest.txt: 100%|##########| 6.22k/6.22k [00:00<00:00, 3.71MB/s]
Downloading conaninfo.txt: 100%|##########| 1.27k/1.27k [00:00<00:00, 1.22MB/s]
Please log in to "conan-center" to perform this action. Execute "conan user" command.
If you don't have an account sign up here: https://bintray.com/signup/oss
Remote 'conan-center' username: ^CYou pressed Ctrl+C!
OpenSSL/1.1.1c@conan/stable: ERROR: Exception while getting package: 008f1a2b119556f550c1109663570e0f5040c13f
OpenSSL/1.1.1c@conan/stable: ERROR: Exception: <class 'SystemExit'> 3
OpenSSL/1.1.1c@conan/stable: WARN: Trying to remove package folder: /home/thanos/.conan/data/OpenSSL/1.1.1c/conan/stable/package/008f1a2b119556f550c1109663570e0f5040c13f
ERROR: Exiting with code: 3

> conan --version
Conan version 1.18.4

**Comment by danimtb** [comment] 2019-09-20 15:23
For anyone experiencing the issue above, please comment on #5780. Thanks!

**Comment by sschuberth** [comment] 2021-08-24 10:22
> One of our engineers found that this was happening due to an overly broad default entry in ~/.netrc.

Does that mean `conan search` actually honors `.netrc` entries? Because in my tests it did not, I had to use `conan user` instead for authentication. I also couldn't find any official docs either on whether `conan` supports `.netrc` or not.

**Comment by memsharded** [comment] 2021-08-24 10:33
Hi @sschuberth 

Conan is using the ``requests`` library for communication: https://docs.python-requests.org/en/master/user/authentication/

> If no authentication method is given with the auth argument, Requests will attempt to get the authentication credentials for the URL’s hostname from the user’s netrc file. The netrc file overrides raw HTTP authentication headers set with headers=.
If credentials for the hostname are found, the request is sent with HTTP Basic Auth.

Conan will not use this, or at least it is unsupported and undocumented so far, but I guess there is some possibility that the netrc could have some unexpected usage.

**Comment by sschuberth** [comment] 2021-08-24 10:47
So, to clarify once more: When you say

> Conan will not use this

then "this" refers to the feature of the underlying `requests` library to parse a `netrc` file, effectively meaning that `conan` does *not* (officially / fully) support authentication via a `netrc` file, correct?

**Comment by memsharded** [comment] 2021-08-24 11:58
Yes, correct.

**Comment by sharadupadhyaya** [comment] 2024-04-08 14:29
> Yes, correct.

Hi @memsharded, I understood that Conan doesn't support authentication through .netrc file, but 'default' entry .netrc file is impacting Conan's communication with remote. This seems like an issue.
If I try Conan on my host where I have .netrc with default entry that I use for authenticating other services like jira, gitlab, confluence etc. I need to remove this default entry for Conan to work.

**Comment by memsharded** [comment] 2024-04-08 15:04
Hi @sharadupadhyaya 

This issue was closed, if there is still an issue maybe it is good to open a new one.
Please detail the issue, ``netrc`` says:

> netrc Authentication
If no authentication method is given with the auth argument,

But Conan connection to remote is actually passing an ``auth`` object, so this shouldn't be an issue unless no auth is provided by Conan. Is it the auth with Conan remotes to fetch Conan packages? Is it the download of sources from other non-Conan repos from Conan recipes ``source()`` method?

**Comment by sharadupadhyaya** [comment] 2024-04-08 15:16
Thanks @memsharded for quick response.
I am authenticating Conan remote (Artifactory repository) using "conan login" command.
I am getting issue with "conan install" if a default entry is present in .netrc on my host.

`ERROR: Error 400 downloading file <path>/conan_package.tgz`

Works fine if I remove default entry from .netrc, but it is needed to authenticate other services like jira, confluence etc.

**Comment by memsharded** [comment] 2024-04-08 15:23
But ``netrc`` entry ``https://artifactory.arm.com`` is only for Artifactory, not fo jira or confluence, isn't it?

**Comment by sharadupadhyaya** [comment] 2024-04-08 15:55
The entry I have in .netrc is:
`default login <username> password <password>`

Artifactory authentication for Conan I did using:
`conan remote login -p <API Key from Artifactory login> <remote name> <user name>`

But the conan install is impacted by above default entry.
Works fine if I remove the default entry from .netrc.

**Comment by memsharded** [comment] 2024-04-08 17:57
> default login <username> password <password>

having a single default credentials for all applications wouldn't be enough for many cases that requires different credentials for different applications and domains. This is why ``.netrc`` provides the ``machine_name`` field, to be able to define to which applications it applies. It is not that Conan should completely ignore it, is is possible that some users have Artifactory behind some front like nginx with its own auth that is provided with ``.netrc`` or something. So I think that providing a more detailed ``.netrc`` would be the recommended approach.

**Comment by pankajkushwahaspam** [comment] 2024-04-10 09:58
@memsharded : Thanks for the response.
I am also facing similar problem.

The solution doesn't fit in my case practically.

I have 15 remote hosts. 5 use different login/passwords.
10 use the same login/passwords.

The solution suggests that I should create 15 entries in ".netrc" while with default only 6 are required and it's easier to maintain.

**Comment by memsharded** [comment] 2024-04-10 17:00
I have been having a look to the "python-requests" code internals.
This doesn't seem something that can easily be changed from the outside.

The rationale seems to be that if there is a ``.netrc`` file, it will be honored, and it has to be correct, same as other applications.
If some credentials are applied to the artifactory server because there is a "default" one, then the credentials should be used, this is exactly what the ``.netrc`` file defined, why should it be ignored by Conan (or python-requests in this case)?

> 10 use the same login/passwords.

the fact that completely different domains use the same login/password seems just accidental in your case. This probably won't be the same for most other users, as security recommends to use different passwords for different applications (and URLs patterns)

The Artifactory URL would be just one more URL to be managed at the same level as other URLs.


In any case, this discussion is just what the python-requests opinion seems to be, there is actually little we can do from the Conan side, not possible to modify that as it is outside of our reach and scope and inside the python-requests internal implementation.

**Comment by pankajkushwahaspam** [comment] 2024-04-11 09:43
ok..thanks.
Just to clarify the "10 use the same login/passwords." is coming from our internal "One Login" policy.
These are our internal domains supporting "One Login" and hence don't need separate logins.

Thanks for the clarification though and looking into it.

**Comment by sharadupadhyaya** [comment] 2024-04-11 14:59
Thanks @memsharded for clarifying this.
