### ISSUE TITLE
[question] Unable to set local dependencies to MSBuild in conanfile.py

### ISSUE THREAD

**Issue by RReymann** [conan-io/conan#2595] opened 2018-03-12 13:29 UTC
Hello,

I am currently using Conan.io 1.1.1 on Windows Server 2K12 with Visual Studio 2010 (I know ..) and I trying to compile a project thru MSBuild. The specificity of the VS solution is the use of an internal static library containing quite all the business logic and a executable linked with this internal library. 

Please find below a snippet of code for the build function in conanfile.py:

```python                
        msbuild = MSBuild(self)
        msbuild.build_env.include_paths.append("E:/BankCppLib")
        msbuild.build_env.include_paths.append("%s/Src" % self.source_folder)
        msbuild.build_env.include_paths.append("%s/Src/Lib" % self.source_folder)
        
        # Setting the project lib path dependencies       
        msbuild.build_env.lib_paths.append("E:/BankCppLib/%s" % self.settings.build_type)
        
        self.output.info(vars(msbuild.build_env))        
        
        msbuild.build(sln_file, targets)
```  

While the definition of build include paths is working fine, I am not able to define the path for internal library with **msbuild.build_env.lib_paths**. 

Is there any issue on your side ? 
If not could you please advice the best way for including local project dependencies ?

Cheers
Renaud

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment] 2018-03-12 15:50
Hi, sorry I don't understand what the issue is.

> I am not able to define the path for internal library with msbuild.build_env.lib_paths.

Could you specify what's the problem? it is not locating the internal library? raising some error...

You could also try to package the internal library as a different conan package and require it from the current recipe. If the internal library is already built you can use the `conan export-pkg` command with a very simple recipe to build it: http://docs.conan.io/en/latest/reference/commands/creator/export-pkg.html

**Comment by memsharded** [comment] 2018-03-12 16:20
Can you  please describe a little more, what do you want to do with:

```
 msbuild.build_env.include_paths.append("E:/BankCppLib")
```
Are you hardcoding the dependency to something in your system? I guess this is another library, different to the one that you are trying to package, right? Why aren't you considering to create a package for  "BankCppLib" itself?

Thanks for your feedback!

**Comment by RReymann** [comment] 2018-03-12 16:36
Hi,

Sounds my previous post was unclear for you. 

I have one VS solution including one project building an executable file.
This project has one internal dependency (i.e in the same VS solution) with is another project building this time a static library (i.e .lib). 

By building my exe project thru MSBuild, I have to specify my include folders for this project. This is done with `msbuild.build_env.include_path.append("xxx")`. That's working fine :)

I did the same logic for lib_paths but this time my executable project does not link:  
         `LINK : fatal error LNK1181: cannot open input file BankCppLib_mmt.lib`

Considering this internal library like any other external dependencies sounds for me a bit overkill due to the fact that it is only used locally.

I hope my explanation was clear this time :-)

Cheers
RRE

**Comment by memsharded** [comment] 2018-03-12 16:56
So if you are only creating 1 package, I think there is some misunderstanding about how it works. The information that you are trying to add belongs to information of the package dependencies, i.e. the information of other packages than your current package depends on. The information from the current package doesn't come from conan, but is usually encoded in the build system. 

Also, avoiding absolute paths, they should always be relative.

**Comment by RReymann** [comment] 2018-03-13 08:20
Thanks for the answer. I agree with you concerning build system but MSBuild is part of the overall build system even if it is a build tool.

**Comment by memsharded** [comment] 2022-08-25 23:04
This integration has been superseded by https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html, closing.

**Closed by memsharded** 2022-08-25 23:04 UTC
