### ISSUE TITLE
[bug] XcodeDeps using full package reference in case of package with components leads to invalid xcconfig setup

### ISSUE THREAD

**Issue by maikelvdh** [conan-io/conan#12089] opened 2022-09-12 10:41 UTC
XcodeDeps generated setup is incorrect in case you are referencing to a full package in the requires section of cpp_info object, whilst the referenced package might be sliced into further subcomponents.

Either the `conan_<dependency>_<dependency>.xcconfig` should be produced additionally, or it should be referenced in the `include` reference as `conan_<dependency>.xcconfig`. 

Unless it might be expected that consumer will have to switch to utilization of components, but then an error should be thrown when full package reference is utilised within cpp_info requirement context.

### Environment Details (include every applicable attribute)
  * Operating System+version: n/a
  * Compiler+version: n/a
  * Conan version: 1.52
  * Python version: 3.9

### Steps to reproduce (Include if Applicable)
```
diff --git a/conans/test/functional/toolchains/apple/test_xcodedeps_components.py b/conans/test/functional/toolchains/apple/test_xcodedeps_components.py
index 2a50ab1e0..9b0d13c2a 100644
--- a/conans/test/functional/toolchains/apple/test_xcodedeps_components.py
+++ b/conans/test/functional/toolchains/apple/test_xcodedeps_components.py
@@ -1,3 +1,4 @@
+import glob
 import os
 import platform
 import textwrap
@@ -136,7 +137,7 @@ def test_xcodedeps_components():
         self.cpp_info.libs = ["chat"]
         self.cpp_info.includedirs.append("include")
         self.cpp_info.libdirs.append("lib")
-        self.cpp_info.requires.append("network::client")
+        self.cpp_info.requires.append("network::network")
     """

     cmakelists_chat = textwrap.dedent("""
@@ -146,7 +147,7 @@ def test_xcodedeps_components():
         add_library(chat src/chat.cpp include/chat.h)
         target_include_directories(chat PUBLIC include)
         set_target_properties(chat PROPERTIES PUBLIC_HEADER "include/chat.h")
-        target_link_libraries(chat network::client)
+        target_link_libraries(chat network::network)
         install(TARGETS chat)
         """)

@@ -184,9 +185,9 @@ def test_xcodedeps_components():
     client.run("install chat/1.0@ -g XcodeDeps --install-folder=conan -s build_type=Debug "
                "--build=missing")
     chat_xcconfig = client.load(os.path.join("conan", "conan_chat_chat.xcconfig"))
-    assert '#include "conan_network_client.xcconfig"' in chat_xcconfig
-    assert '#include "conan_network_server.xcconfig"' not in chat_xcconfig
-    assert '#include "conan_network_network.xcconfig"' not in chat_xcconfig
+    assert '#include "conan_network_network.xcconfig"' in chat_xcconfig
+    assert os.path.isfile(os.path.join(client.current_folder, "conan", "conan_network.xcconfig"))
+    assert os.path.isfile(os.path.join(client.current_folder, "conan", "conan_network_network.xcconfig"))
     host_arch = client.get_default_host_profile().settings['arch']
     arch = "arm64" if host_arch == "armv8" else host_arch
     client.run_command("xcodegen generate")
```

**Comment by czoido** [comment] 2022-09-12 14:11
Hi @maikelvdh,

Thanks a lot for reporting and the information to reproduce.
I'll add this as a look-into for 1.53 to discuss with the team what to do in these cases. I'm not sure wether we should error in the cpp_info itself or in the generator. Other generators like CMakeDeps would accept to declare that network::network as a dependency but would generate valid information anyway. Probably this is something we have to consider not just for XcodeDeps but for the other generators.
In the meantime, for the case of the test, declaring the valid components you depend on would be the recommended way of doing it.

To summarize the problem:

- You have a network/1.0 package that has several components: network::client, network::server
- You require in the cpp_info from other package network trying to require all the components but with the syntax:
`self.cpp_info.requires.append("network::network")` 
- You expect that doing that all components are required by the package, but instead of that the XcodeDeps generator tries to include the conan_network_network.xcoconfig that is not generated

In fact you can require a `self.cpp_info.requires.append("network::notexisting")` and no error is raised so at least that should be fixed.

**Comment by czoido** [comment] 2022-09-12 14:32
I was checking how CMakeDeps does this and looks like it explicitly allows doing something like `self.cpp_info.requires.append("network::network")` but errors for `network::nonexistent` so probably we want to make XcodeDeps work the same way. I'll check if I can add that feature in a PR for 1.53

**Comment by maikelvdh** [comment] 2022-09-13 06:58
Thanks a lot for the elaboration @czoido! After discussion with @memsharded last week I raised this ticket to spawn a further discussion about the expected behavior in such case. As you mentioned we can indeed switch on our side to make sure components are used throughout the graph consistently, but it would be really good for more complex graphs to identify as early as possible the desired usage.

**Closed as completed** 2022-09-21 11:50 UTC
Labels: type: feature
