### ISSUE TITLE
Implement checker for Visual Studio runtime

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#2436] opened 2018-02-06 16:36 UTC
Unfortunately it still happens from time to time and it is difficult to detect and workaround the different build systems.

Have a look if calling dumpbin could check this thing, and report accordingly, specially to package creators.

**Comment by memsharded** [comment] 2018-02-12 16:57
Possibly an  idea would be a ``conan verify`` command (experimental) that checks things without messing with existing flow.

**Comment by danimtb** [comment] 2018-12-04 16:58
I think this will follow the hook implementation and it is duplicate of #1115

**Closed** 2018-12-04 16:58 UTC
Labels: duplicate, type: feature
