### ISSUE TITLE
[bug] cannot login to Artifactory with ldap user

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#16361] opened 2024-05-29 09:25 UTC
Hello,

We have setup [JFrog Artifactory Community Edition (CE)](https://conan.io/downloads.html) as a conan server, and everything is working as expected. 

I can login conan using both password and authentication token, the two commands bellow are working fine:
```
conan user -p <password>  -r <remote> <artifactory user>
conan user -p <token>  -r <remote> <artifactory user>
```

Now we wanted to integrate Artifactory with LDAP. We were able to achieve this. LDAP users can login to artifactory UI and they have the correct access permissions. 

However, ldap users are not able to authenticate using conan client.

### Using ldap user/password
```
export CONAN_LOGGING_LEVEL=10
export CONAN_TRACE_FILE=/tmp/file.txt

$ conan user -p <password> -r pmi-conan-dev <ldap user>
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 10:05:55,378]
DEBUG :tracer.py      [156]: CONAN_API: authenticate(remote_name=pmi-conan-dev,password=**********,skip_auth=False) [2024-05-29 10:05:55,383]
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 10:05:55,384]
DEBUG :tracer.py      [156]: CONAN_API: get_remote_by_name() [2024-05-29 10:05:55,385]
DEBUG :rest_client_common.py[160]: REST: ping: https://artifactory.mydomaine.io/artifactory/api/conan/pmi-conan-dev/v1/ping [2024-05-29 10:05:55,387]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.ForbiddenException'> [2024-05-29 10:05:55,965]
ERROR: {
  "errors" : [ {
    "status" : 403,
    "message" : "Login has failed. Due to Incorrect username/password or locked user."
  } ]
}. [Remote: pmi-conan-dev]

```

```
$ cat /tmp/file.txt
{"_action": "COMMAND", "name": "authenticate", "parameters": {"password": "**********", "remote_name": "pmi-conan-dev", "skip_auth": false}, "time": 1716973568.049424}
{"_action": "COMMAND", "name": "get_remote_by_name", "parameters": {}, "time": 1716973568.051203}
{"_action": "REST_API_CALL", "duration": 0.5636980533599854, "headers": {"User-Agent": "Conan/1.64.0 (Darwin 23.4.0; Python 3.11.9; x86_64)", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1716973568.6168919, "url": "https://artifactory.mydomaine.io/artifactory/api/conan/pmi-conan-dev/v1/ping"}
{"_action": "EXCEPTION", "class": "ForbiddenException", "message": "{\n  \"errors\" : [ {\n    \"status\" : 403,\n    \"message\" : \"Login has failed. Due to Incorrect username/password or locked user.\"\n  } ]\n}. [Remote: pmi-conan-dev]", "time": 1716973568.618357}
```

### Using ldap user/ token
```
$ conan user -p <token> -r pmi-conan-dev <ldap user>
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 10:19:27,359]
DEBUG :tracer.py      [156]: CONAN_API: authenticate(remote_name=pmi-conan-dev,password=**********,skip_auth=False) [2024-05-29 10:19:27,365]
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 10:19:27,366]
DEBUG :tracer.py      [156]: CONAN_API: get_remote_by_name() [2024-05-29 10:19:27,366]
DEBUG :rest_client_common.py[160]: REST: ping: https://artifactory.mydomaine.io/artifactory/api/conan/pmi-conan-dev/v1/ping [2024-05-29 10:19:27,368]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.ForbiddenException'> [2024-05-29 10:19:27,982]
ERROR: {
  "errors" : [ {
    "status" : 403,
    "message" : "Login has failed. Due to Incorrect username/password or locked user."
  } ]
}. [Remote: pmi-conan-dev]
```

```
$ cat /tmp/file.txt
{"_action": "COMMAND", "name": "authenticate", "parameters": {"password": "**********", "remote_name": "pmi-conan-dev", "skip_auth": false}, "time": 1716974367.3648572}
{"_action": "COMMAND", "name": "get_remote_by_name", "parameters": {}, "time": 1716974367.366566}
{"_action": "REST_API_CALL", "duration": 0.6113801002502441, "headers": {"User-Agent": "Conan/1.64.0 (Darwin 23.4.0; Python 3.11.9; x86_64)", "X-Client-Anonymous-Id": "**********", "X-Client-Id": ""}, "method": "GET", "time": 1716974367.98036, "url": "https://artifactory.mydomaine.io/artifactory/api/conan/pmi-conan-dev/v1/ping"}
{"_action": "EXCEPTION", "class": "ForbiddenException", "message": "{\n  \"errors\" : [ {\n    \"status\" : 403,\n    \"message\" : \"Login has failed. Due to Incorrect username/password or locked user.\"\n  } ]\n}. [Remote: pmi-conan-dev]", "time": 1716974367.983583}
```

### Environment details
OS: Macos
Python version:  3.12.3
Conan version: 1.64.0
Artifactory version: 7.63.10

**Comment by memsharded** [comment] 2024-05-29 14:07
Hi @boussaffawalid 


Thanks for your feedback.

I am afraid this wouldn't be a bug, but this is intended behavior. Conan client does not provide LDAP authentication, but it uses Artifactory passwords or tokens. The fact that Artifactory server itself can auth against an LDAP compatible server doesn't imply that the client can do it.

This wouldn't be a planned feature, I think this would be extra complex and it wouldn't depend only on the client side, but it also needs coordinated efforts and doing changes in the server side that are way beyond what we can approach.

The only thing that might happen at some point is a Conan client plugin that allows to inject user and password/token by running some python script that the user provides, so if you are able to access with a script your LDAP server and obtain there a user & password/token that the Conan client can send to Artifactory and Artifactory will accept, we can consider it.

Otherwise, I would recommend closing this ticket as not planned.

**Comment by boussaffawalid** [comment] 2024-05-29 14:52
@memsharded thank you for the detailed answer. 
I'm confused! conan does not need to provide LDAP authentication, it should not actually care about the authentication mechanism of artifactory.

I think you misunderstood my problem. Artifactory itself support ldap and we configured it with ldap so that we dont have to create all users manually in artifactory. Please check attached images.

<img width="1474" alt="ldap" src="https://github.com/conan-io/conan/assets/7117696/797e0889-8b85-4488-a53b-010532492f7c">

<img width="1428" alt="token" src="https://github.com/conan-io/conan/assets/7117696/6e9a3cdf-4cb5-44b6-9796-fa8d7184e24c">

--------

### Updates
After more debugging I found out that artifactory was locking my user due to multiple failed attempts,
<img width="1333" alt="lock_user" src="https://github.com/conan-io/conan/assets/7117696/bc535edf-b3e3-4a8e-b110-f39965c4c7d2">

**I've disabled locking users in artifactory, and I was able to login using a password but not a token.**

## I can login with password
```
$ conan user -p  <password>  -r pmi-conan-dev wboussafa
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 15:43:02,341]
DEBUG :tracer.py      [156]: CONAN_API: authenticate(remote_name=pmi-conan-dev,password=**********,skip_auth=False) [2024-05-29 15:43:02,344]
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 15:43:02,345]
DEBUG :tracer.py      [156]: CONAN_API: get_remote_by_name() [2024-05-29 15:43:02,345]
DEBUG :rest_client_common.py[160]: REST: ping: https://artifactory.myserver.io/artifactory/api/conan/pmi-conan-dev/v1/ping [2024-05-29 15:43:02,347]
DEBUG :rest_client.py [58]: REST: Cached capabilities for the remote: ['complex_search', 'checksum_deploy', 'revisions', 'matrix_params'] [2024-05-29 15:43:02,904]
DEBUG :rest_client_common.py[94]: REST: Authenticate to get access_token: https://artifactory.myserver.io/artifactory/api/conan/pmi-conan-dev/v1/users/authenticate [2024-05-29 15:43:02,905]
Changed user of remote 'pmi-conan-dev' from 'None' (anonymous) to 'wboussafa'
```
 

## I cannot login with token
```
$ conan user -p  <token>   -r pmi-conan-dev wboussafa
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 15:44:49,733]
DEBUG :tracer.py      [156]: CONAN_API: authenticate(remote_name=pmi-conan-dev,password=**********,skip_auth=False) [2024-05-29 15:44:49,736]
DEBUG :conan_api.py   [176]: INIT: Using config '/Users/walid/.conan/conan.conf' [2024-05-29 15:44:49,737]
DEBUG :tracer.py      [156]: CONAN_API: get_remote_by_name() [2024-05-29 15:44:49,737]
DEBUG :rest_client_common.py[160]: REST: ping: https://artifactory.myserver.io/artifactory/api/conan/pmi-conan-dev/v1/ping [2024-05-29 15:44:49,739]
DEBUG :rest_client_common.py[30]: REST ERROR: <class 'conans.errors.AuthenticationException'> [2024-05-29 15:44:50,696]
DEBUG :rest_client_common.py[94]: REST: Authenticate to get access_token: https://artifactory.myserver.io/artifactory/api/conan/pmi-conan-dev/v1/users/authenticate [2024-05-29 15:44:50,696]
ERROR: Wrong user or password. [Remote: pmi-conan-dev]
```

Now after logging in with password again, I tired to perform a conan search but it keeps asking me to authenticate
<img width="815" alt="Screenshot 2024-05-29 at 3 50 34 PM" src="https://github.com/conan-io/conan/assets/7117696/3bc8e9c5-8220-44e2-9bad-f1eac6c2e27a">

**Comment by memsharded** [comment] 2024-05-29 15:21
Oh, if it is just that the token is not working that might be something else.

I have just tried with my ArtifactoryCE, uploading using the token generated in the SetMeUp instruction works fine for me.
So I suspect it might be some other thing, maybe the users that are being created by LDAP do not have actual permissions to create the auth tokens.

**Comment by boussaffawalid** [comment] 2024-05-29 15:30
I have no issues as well for users created directly in artifactory.
The issue only happen for artifactory users coming from LDAP.

I can login using users from ldap but conan keeps asking for credentials whenever I run conan search command
<img width="815" alt="Screenshot 2024-05-29 at 3 50 34 PM" src="https://github.com/conan-io/conan/assets/7117696/f6cadc65-5ec0-41ec-99ec-824926184b94">

Again, in the example above, the `wboussafa` user was not created directly in artifactory!  it is a LDAP user

**Comment by memsharded** [comment] 2024-05-29 16:14
Does it still fail for other operations, like ``install`` or ``download``? Or only the ``search``?

In any case seems some issue in the Artifactory side.
We don't have much control over that here, in general it is better to report it to JFrog directly whenever possible.  If not I can try to report that internally to see what is possible.

**Comment by boussaffawalid** [comment] 2024-05-30 08:36
it fail for `install` and `download` command as well!
Sure, I will open an artifactory issue for this

**Comment by boussaffawalid** [comment] 2024-05-30 09:03
@memsharded these commands works with ldap user

`jfrog rt search --spec=test.aql --url  https://artifactory.myserver.io/artifactory   --user=wboussafa --password=mypassword`

` curl https://artifactory.myserver.io:443/artifactory/pmi-conan-dev/pmi/cairo/1.17.2-g870264d/PR-51/index.json  -u "wboussafa:mypassword"`

`wboussafa` is an ldap user

**Comment by memsharded** [comment] 2024-05-30 10:28
I have also reported it internally. If you have any public link to share to a report, please post it here too. Thanks.

**Comment by boussaffawalid** [comment] 2024-05-30 13:52
Im not able to find where to report an artifactory bug.

**Comment by memsharded** [comment] 2024-05-30 14:55
> Im not able to find where to report an artifactory bug.

I'll try to follow up internally.

**Comment by memsharded** [comment] 2024-06-12 11:31
I keep monitoring the internal ticket, still no news.

**Comment by boussaffawalid** [comment] 2024-06-12 12:33
thanks for the update, Im keeping an eye on this ticket as well

**Comment by memsharded** [comment] 2024-07-01 12:00
Hi @boussaffawalid 

Version ``Artifactory version: 7.63.10`` is relatively old. This is the one we link in the Conan download page for consistency, because the ``docker`` installer is no longer working for newer versions, but can you please try updating to something like 7.77.5?

**Comment by boussaffawalid** [comment] 2024-07-01 12:20
@memsharded I tired with `7.84.12` and still the same issue
![Screenshot 2024-07-01 at 1 18 49 PM](https://github.com/conan-io/conan/assets/7117696/e2e1b0c7-b4e3-4191-8e5c-5b972dea8c28)

**Comment by memsharded** [comment] 2024-07-01 17:40
Hi @boussaffawalid 

I have been getting some internal feedback.

It is not clear at all how you are getting to the screen in which you can generate a Conan token. LDAP users only operate with password, and the ``SetMeUp`` screen when a user comes from LDAP does not provide the token generation functionality, and it only displays instructions how to operate with password. So your screen above showing the token operations for an LDAP created user is unexpected and we couldn't reproduce it here.

Could you please provide a bit more step-by-step screens of the configuration for that latest Artifactory version?

It would also be useful to have screens from the ``Users`` list, showing the current user, also clarify the permissions of the LDAP-created users, I guess they are not admins, but just to verify. 

Also if the ``Disable internal password: When set, user's password is cleared which means that only external authentication is allowed (for example via an LDAP server).`` is set or not.

**Comment by boussaffawalid** [comment] 2024-07-01 20:47
@memsharded 

I've upgraded to latest version: `Conan edition license 7.84.16 rev 78416900`

---
Something was fixed in latest artifactory version  😄 

- Ldap users that logged in from browser can also login using conan client
- Ldap users that never logged in using browser cannot login using conan client

I guess a user needs to login first from browser now so that the user get created in the artifactory 

---
**Screenshots of my settings.** 


<img width="1250" alt="ldap-config-test" src="https://github.com/conan-io/conan/assets/7117696/a4841648-a53a-40be-8336-c940e97fb296">

<img width="1266" alt="group-settings" src="https://github.com/conan-io/conan/assets/7117696/e4e3d3aa-694b-405f-8b3a-b3e2328981d6">



<img width="1275" alt="list-of-users" src="https://github.com/conan-io/conan/assets/7117696/b9a68d90-dbb9-43e8-bfc0-ec63289e688c">

<img width="1254" alt="ldap-group-permission" src="https://github.com/conan-io/conan/assets/7117696/0e3fca28-d57d-4a24-9c4b-82825124cf31">

<img width="1333" alt="ldap-user-settings" src="https://github.com/conan-io/conan/assets/7117696/0fa26c8c-6705-4a56-a798-f9c33fca9cdc">


----

<img width="1466" alt="1-logged-using-ldap-user" src="https://github.com/conan-io/conan/assets/7117696/2b4da589-3d86-4de4-a553-ed07d793aafc">
<img width="1485" alt="2-setup-client" src="https://github.com/conan-io/conan/assets/7117696/b4b72a7a-0be1-410a-8543-1ac11c0317b9">
<img width="1125" alt="3-login-from-conan-client" src="https://github.com/conan-io/conan/assets/7117696/7937ff4c-ed26-440f-9a23-7f29d52427ce">

**Comment by memsharded** [comment] 2024-07-02 13:15
Thanks very much for the feedback.

It seems the issue could be related to transient users defined in LDAP. When a user is only defined in LDAP but not in Artifactory yet, it is a transient user, it is not yet in the Artifactory DB, and as such the tokens cannot be validated against the user or group. The situation after login in the WebUI and creating an artifactory user for that LDAP user is different.

The problem might be addressed by configuring the LDAP group settings. 
A group with the same name should be defined both in LDAP and Artifactory, and the LDAP group settings should map their correspondence. In this case it seems you are using ``ldap-dev-group``, so the same group should be defined in LDAP, with the users associated to it, and Artifactory should define the correspondence to the Artifactory internal ``ldap-dev-group`` 

Then for transient users, if the "Auto-create-user" and the "Assign user to group" is automatically configured to assign it to the above group, it should be able to assign the ldap user to the group and the permissions should work. 

Please try that and let us know.

**Comment by boussaffawalid** [comment] 2024-07-03 08:23
Thank you for the details.
I was not able to get ldap group settings to work in artifactory, after a lot of debugging I found this in artifactory `access-service.log`

`Search Ldap groups only supported for Pro license`

It seems like ldap groups does not work for Artifactory OSS.  
This issue can be closed I guess!

**Comment by memsharded** [comment] 2024-07-03 11:52
> Search Ldap groups only supported for Pro license

Ok, that would explain it. This kind of more advanced auth integrations and other features that are associated to more enterprise deployments and usage are usually expected to be part of the pro versions.

Thanks very much for the feedback and follow up!

**Closed as completed by memsharded** 2024-07-03 11:52 UTC
Labels: component: artifactory
