### ISSUE TITLE
Error "Cannot upload corrupted package" sometimes happens with short_path enabled 

### ISSUE THREAD

**Issue by KindDragon** [conan-io/conan#919] opened 2017-01-27 22:43 UTC
Error "Cannot upload corrupted package" sometimes happens with short_path enabled after previous build failed
```
Uploaded conan recipe 'grpc/1.0.1@*****/stable' to 'amazon': http://****************/
Uploading package 1/2: 63da998e3642b50bee33f4449826b2d623661505

Checking package integrity...                                         ERROR: Cannot upload corrupted package 'grpc/1.0.1@merlin-ext/stable:63da998e3642b50bee33f4449826b2d623661505'
```
Path `c:\Users\WinBuilder\.conan\data\grpc\1.0.1\*****\stable\package\63da998e3642b50bee33f4449826b2d623661505` file `.conan_link` contains reference to `C:/.conan\qzqonq\1`, but `C:\.conan\qzqonq` doesn't contain folder `1`

**Comment by memsharded** [comment] 2017-02-03 16:12
Can you please elaborate what you mean with "previous build failed", what would be the previous steps/output before the upload failure?

**Comment by KindDragon** [comment] 2017-02-03 16:40
IDK and cannot reproduce it anymore

**Comment by memsharded** [comment] 2017-02-03 17:00
Bad news :(
I have tried to force a couple of failures, but still not able to reproduce. I will close the issue by now, please re-open if happens again or have more feedback about it. Thanks!

**Closed by memsharded** 2017-02-03 17:00 UTC

**Comment by osechet** [comment] 2017-06-17 16:53
I get the same error here: https://travis-ci.org/osechet/conan-protobuf/jobs/244000499
The context: for another library (gRPC), I need several Protobuf packages that are not available in bintray's repo. I decided to build them with travis and appveyor and publish in my bintray repo. To do so I forked memshared/conan-protobuf and adapted it to work with bintray. After pushing these modifications, I get the error.

**Comment by memsharded** [comment] 2017-06-18 15:46
Hi @osechet 

I am having a look at this, trying to understand. First thing is that it is not related to ``short_paths`` at all, if it happens in Linux, as the short-paths feature does not have any effect at all in Linux.

Then, the critical error is the mismatch between the package manifests when the package was created and the current package folder at the time of upload. The relevant message is:

```bash
WARN: Mismatched checksum 'bin/.libs/lt-protoc' (manifest: None, file: a5af685d3ba9d9e6dce3dd24e860a47a)
```
It means that there is a file, called ``bin/.libs/lt-protoc`` that is there in the package folder, but for some reason it does not appear in the manifest (None). Does this make sense to you? Any idea about this specific file? Maybe checking in the other succesful upload of the other package, download the final conanmanifest.txt and check it about its content.

Also, does it happens always the same? In the same package? Have you tried to relaunch the build? Thanks for the feedback.

**Comment by osechet** [comment] 2017-06-18 19:43
> it is not related to short_paths

Yes, sorry I didn't really noticed this issue was also referring to `short_path`.

> Does this make sense to you?

Not really, I don't really know the Protobuf package. As I said I just wanted to use it for another package. I will investigate to better understand.

> does it happens always the same?

Yes, I restarted the travis build several times and I always got the same error.

**Comment by memsharded** [comment] 2017-06-18 20:38
OK, as it happened to you while trying to upgrade the Protobuf package, I will try the same, lets see what happens.

**Comment by memsharded** [comment] 2017-06-18 22:25
Ok, at least I have found the guilty: https://groups.google.com/forum/#!topic/protobuf/td5odsTOOnw

It seems that it is a file generated by the shared library is executed. That is why it doesn't appear in the package manifest, and it generates an error while trying to upload: it is trying to upload something that might be broken, with a locally generated file.

I am having a look, trying to figure out a way to workaround this

**Comment by memsharded** [comment] 2017-06-18 22:35
I think I have found a workaround. ``protoc`` is called from the test_package, and it is using the package CMake macros, which default to the package ``protoc`` executable. As this executable is already imported to user space, it is easy to run it instead of the package one with:

```cmake
set(Protobuf_LIBRARY ${CONAN_PROTOBUF_ROOT})
find_package(Protobuf)

# REDEFINE the path to PROTOC
set(PROTOBUF_PROTOC_EXECUTABLE ${CMAKE_BINARY_DIR}/bin/protoc)

message(${PROTOBUF_PROTOC_EXECUTABLE})
protobuf_generate_cpp(PROTO_SRCS PROTO_HDRS ${PROTOS})
```

The really good solution should be to decouple protoc in a different package, so it can be statically linked, always (which is the way it is distributed by google, btw).

**Comment by osechet** [comment] 2017-06-19 08:32
I created an issue for this in the package repo to continue the discussion.
