### ISSUE TITLE
RPATH OSX Trouble

### ISSUE THREAD

**Issue by Milerius** [conan-io/conan#5011] opened 2019-04-20 12:15 UTC
Conan version: 1.14.1
OS: OSX Mojave
Compiler: clang-8

I read carefully issue: #3996

step to reproduce: build a binary on osx with sfml package with option sfml:shared=True

but for me is not working on osx....

output of otool -l with this approach:
```
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name libsfml-graphics.2.5.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 2.5.1
compatibility version 2.5.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name libsfml-window.2.5.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 2.5.1
compatibility version 2.5.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name libsfml-system.2.5.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 2.5.1
compatibility version 2.5.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name /usr/local/opt/llvm/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.0.0
compatibility version 1.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1252.250.1
compatibility version 1.0.0
Load command 17
          cmd LC_RPATH
      cmdsize 40
         path @executable_path/../lib (offset 12)
Load command 18
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 280616
 datasize 2288
Load command 19
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 282904
 datasize 48
```

if you launch the program you will immediatly get: 
```
dyld: Library not loaded: libsfml-graphics.2.5.dylib
  Referenced from: /Users/milerius/Documents/C++/nephtys/cmake-build-debug/bin/./nephtys-sfml-graphics-test
  Reason: image not found
[1]    69455 abort      ./nephtys-sfml-graphics-test
```

```CMake
##! Conan
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS KEEP_RPATHS)

if (APPLE)
        set(CMAKE_INSTALL_RPATH "@executable_path/../lib")
    else ()
        set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
    endif ()

    if (UNIX)
        set(CMAKE_BUILD_WITH_INSTALL_RPATH ON)
    endif ()
```

Dylib are in the directory lib and binaries in directory bin:

```
➜  cmake-build-debug git:(roman_dev_osx) ✗ exa --tree lib bin
bin
├── nephtys-sfml-graphics-test
└── nephtys_launcher.app
   └── Contents
      ├── Frameworks
      │  └── Noesis.dylib
      ├── Info.plist
      ├── MacOS
      └── Resources
lib
├── libsfml-graphics.2.5.1.dylib
├── libsfml-graphics.2.5.dylib -> libsfml-graphics.2.5.1.dylib
├── libsfml-graphics.dylib -> libsfml-graphics.2.5.dylib
├── libsfml-system.2.5.1.dylib
├── libsfml-system.2.5.dylib -> libsfml-system.2.5.1.dylib
├── libsfml-system.dylib -> libsfml-system.2.5.dylib
├── libsfml-window.2.5.1.dylib
├── libsfml-window.2.5.dylib -> libsfml-window.2.5.1.dylib
└── libsfml-window.dylib -> libsfml-window.2.5.dylib
```

**Comment by lasote** [comment] 2019-04-22 09:49
Sorry I didn't see this issue before answering here: https://github.com/conan-io/conan/issues/3996#issuecomment-485104406

As the conclusion, I think the issue is that the `CMakeLists.txt` from the `sfml` package is doing `conan_basic_setup()` so the binaries in that packages are not affected by the consumer adjustments where you are trying to adjust the relative `rpath`.

I'm adding this issue to the `Build helpers` project, because It might be worth it to think if we should allow somehow changing globally how the rpath of the libraries should be when `--build missing` from the consumer. To discuss, that would mean that the `rpath` adjustments should be a `setting` or a known `option`? Probably not, but take into account that we will be changing the binaries.

**Comment by Milerius** [comment] 2019-04-22 10:05
Well an option can be a good idea, if we have the possibility to let the choice for the user is great

**Comment by memsharded** [comment] 2023-11-29 22:07
This ticket refers to the legacy ``cmake`` generator, that has been superseded in 1.X and removed completely in 2.0. Closing it as outdated.

**Closed by memsharded** 2023-11-29 22:07 UTC
Labels: stage: triaging, whiteboard
