### ISSUE TITLE
[bug] sqlite3/3.45.0 build failure

### ISSUE THREAD

**Issue by xiaoshenxian** [conan-io/conan#16917] opened 2024-09-01 08:08 UTC
### Describe the bug

sqlite3/3.45.0 build failed with debug flag.

## Env
Win10, Conan 2.2.2

## Description

conan command
`conan install . --output-folder=build --build=missing --settings=build_type=Debug`

## Debug

![image](https://github.com/user-attachments/assets/ea8cc563-2b9c-47fa-96f9-fa8b3b954ec1)

It said that there are special characters in `...\b\src\shell.c(26338,35)`.

I checked the file, the line 26338 is `static const char *zBomUtf8 = "\xef\xbb\xbf﻿";` which tails with invisible characters.

Copy the original text (better with the quotes) into python got below:

![image](https://github.com/user-attachments/assets/8a157417-a4f0-4715-979a-017d9582e095)

Seems they fogot to remove the unicode text after convert it to ascii.

This is a bug in sqlite src code. But I cannot access them, can anyone help to fix this?

**Comment by memsharded** [comment] 2024-09-01 16:06
Hi @xiaoshenxian 

Thanks for your report.

I am not sure what could be the issue, but this is not failing or reproducing here.
I have just tried:
```
conan install --requires="sqlite3/3.45.0" --build=sqlite* -s build_type=Debug
```
and it builds fine in my Windows machine.

I suspect it could be something related to special encodings in your machine, or there could be some interaction between the system encoding, CMake, Visual Studio..., so it might be a bit challenging to reproduce.
Maybe the first thing to do is to reproduce without Conan, if you suspect it could be an issue in sqlite source code, then to report to the project, but I also suspect it is a bit unlikely that the sqlite source code contains such a bug and hasn't been detected yet, so maybe there is some other solution, something to change in the system configuration.

**Comment by xiaoshenxian** [comment] 2024-09-02 00:52
Hi @memsharded 

Thank you for your reply.

It is indeed related to encoding. But I think the encoding is not the root cause. As I mentioned, the line 26338 of the sqlite src code shell.c seems going to save the Bom string of utf8, which is `"\ufeff"`, and can be encoded to ascii as `"\xef\xbb\xbf"`. However, the src code is actually `"\xef\xbb\xbf" + "\ufeff"`, in which the later one is invisible. That's why when I copy the string from the src code (also the one with quote in my previous post) to python shows a "square" character. I am guessing if they made a duplicate Bom there, since if we regard  `b"\xef\xbb\xbf"` as binary and decode it to utf8 string will get exactly `"\ufeff"` as shown below. This also appear in sqlite latest [src](https://www.sqlite.org/src/zip/sqlite.zip). Also, if I delete the last invisible character from the src code shell.c, the things goes well.

![image](https://github.com/user-attachments/assets/8d9cc3f9-929d-45b0-a1e1-dda733f06c32)

There is only one place I made an encoding setting. I added `add_compile_options("/utf-8" "/EHsc")` in the cmake file. I am not sure if it can help to reproduce.

**Comment by memsharded** [comment] 2024-09-02 08:03
> There is only one place I made an encoding setting. I added add_compile_options("/utf-8" "/EHsc") in the cmake file. I am not sure if it can help to reproduce.

Where did you do this change? In the ``sqlite3`` source code it is not possible, because it doesn't use ``CMakeLists.txt``, can you please clarify this?. And what happens if you remove this line?

**Comment by xiaoshenxian** [comment] 2024-09-04 09:28
I added `add_compile_options("/utf-8" "/EHsc")` in my own project's root CMakeLists.txt, the same folder of the conanfile.txt. I don't know if conan use this file or not.

For the sqlite3 src, I noticed that Conan downloads the source code to `~\.conan2\p\sqlit...\s\src\shell.c`, and then compiles and builds the binary to `~\.conan2\p\b\sqlit...`. So I modify the former one before conan builds the binary. Then it works well.

**Comment by memsharded** [comment] 2024-09-04 10:06
> I added add_compile_options("/utf-8" "/EHsc") in my own project's root CMakeLists.txt, the same folder of the conanfile.txt. I don't know if conan use this file or not.

No, that is not used at all when doing a ``conan install .``, that is only installing (and building if necessary) the dependencies, but your current ``CMakeLists.txt`` is used only when building your project.

> For the sqlite3 src, I noticed that Conan downloads the source code to ~\.conan2\p\sqlit...\s\src\shell.c, and then compiles and builds the binary to ~\.conan2\p\b\sqlit.... So I modify the former one before conan builds the binary. Then it works well.

Files in the Conan cache shouldn't be manually modified. The approach if necessary should be to do patches in the ``conanfile.py`` recipe,  but that would require modifying the ``sqlite3`` conanfile.py file. This can be done, because you have all the recipes in ConanCenter in ``conan-center-index`` Github repo, so you can do a fork and build it from there.

Still, this sounds unexpected, sqlite3 should be able to build without patching its source code, there might be something else to configure in the system. It would be recommended first to reproduce without Conan, just the most simple steps downloading and building sqlite3 from source, and if it can be easily reproduce, then report to the project.

**Comment by xiaoshenxian** [comment] 2024-09-05 09:14
Yes you are right. In general, the Conan cache shouldn't be touch.

However, I really have no more clue how to reproduce it. Maybe it is related to the Window codec?

Nevertheless, there is indeed an invisible character, the utf8 bom, exists at line 26338 in the `~\.conan2\p\sqlit...\s\src\shell.c`. This can be easily checked. Can we start from here? Maybe we can ask someone working in sqlite3 to confirm this.

**Comment by memsharded** [comment] 2024-09-05 09:38
If this is a sqlite3 issue, which I honestly doubt it is, the way to go would be:

- First investigate with other platforms, for example use a virtual machine, WSL, docker, or similar technology to use some other machine
- First search https://sqlite.org/forum/forum for similar issues
- https://www.sqlite.org/howtocompile.html, do a build of sqlite3 from source following their instructions
- Do the build both in the virtual machine (it should succeed), then in your machine (see the failure).
- If it fails, post a question in the forum first: https://sqlite.org/forum/forum
- In that question, report all details, the Windows machine, version, encoding, the used compilers with versions. Report full output of the compilation with clear errors.
- Report even the terminal you are using, the encoding of the terminal, etc
- Report the comparison between the succesful build in the other machine and the failing one.

It is very likely that in this process you might learn where the issue is, maybe some configuration in the terminal.
I am not saying that it is impossible that sqlite3 has a bug, but this project is massively used around the world, so it is very unlikely that it will have some bug like this one that hasn't been reported yet.

**Comment by xiaoshenxian** [comment] 2024-09-05 12:44
Thank you very much for your advices. I really don't want to create an account on sqlite forum.. A good news is it works well in building release. This only happens when I set `build_type=Debug`. It also works well when I modified the source code during debug. I'll let it go. Just leave the information here in case others encounter the same problem.

**Comment by memsharded** [comment] 2024-09-05 16:24
Thanks for the feedback.

I am closing the ticket as this doesn't look like a Conan issue, and there is no action needed from us at the moment.

You can always re-open or create a new ticket if further questions, issues or needs happen. Thanks for your feedback!

**Closed as completed by memsharded** 2024-09-05 16:24 UTC
