### ISSUE TITLE
[bug] conan info -u Update not working

### ISSUE THREAD

**Issue by climblinne** [conan-io/conan#6294] opened 2020-01-03 09:30 UTC
When I use `conan info myproj -u` the update is not working.

### Environment Details (include every applicable attribute)
  * Operating System+version: Win 10
  * Compiler+version: VS15
  * Conan version: 1.21
  * Python version: 3.7

### Steps to reproduce (Include if Applicable)
I have the following requirement in `myproj`:
```
self.requires(f"my_lib/[>=1.0.0-dev <2.0.0-dev]@demo/testing")
```
In my local cache I already have the following version of the lib:
```
my_lib/1.0.0-dev.9+master.g311c6d2@demo/testing
```
and on my Artifactory:
```
my_lib/1.0.0-dev.12+master.ga60ae0b@demo/testing
```

`conan info myproj -u` always tries to use the old version, which is not working anymore (because I changed a dependency, not an conan issue!).
Normally, it should load the new version from Artifactory, like `conan create ... -u` does.

**Comment by czoido** [comment] 2020-01-03 15:45
Hi @climblinne,
I've been able to reproduce that behavior. It looks like the update argument is not being passed correctly so it never checks the remote for new versions.
Thanks a lot for reporting!

**Comment by memsharded** [comment] 2020-01-03 16:12
The ``conan info`` command, as designed, is not intended to install updates, only to report about them. It might update the recipe, but the binaries are never installed or updated. Probably the full output of ``conan info`` will show information about the "updateable" possibility of the binary. This behavior has been this way from the beginning, I don't think this is a bug, so it needs some clarification.

**Comment by czoido** [comment] 2020-01-03 17:24
I think that @memsharded is right and It's not a bug, but maybe the behavior is a little confusing.
The reason why the result of the `info` command and the `create` command is different is that the `create` command will first search for versions in the remotes and resolve the version range with those versions from the remotes then from that resolved version search for the latest. On the other side the `info` command will first resolve the version range and when the range is resolved, search for a new version of the resolved version in the remote...
So in one case, the `--update ` affects the version range and in the other, it does not.
I think that we should clarify this in the documentation or decide if they should behave the same way affecting the range resolution or not. We'll give it a thought.
Thanks a lot.

**Comment by memsharded** [comment] 2020-01-03 18:00
This should be in any case considered for 2.0, as this behavior seems to not be very clear.

**Comment by climblinne** [comment] 2020-01-03 20:54
In my case I just get an error message:

```
ERROR: Version range '~1.3.0-dev' required by 'mylib/1.0.0-dev.9+master.g311c6d2@demo/testing' not valid for downstream requirement 'another_lib/1.6.0+master.g47513ff@demo/testing'
```

So there is no report of the update, because I get already an error message before the update check.

How can the build order be correctly generated, when the files are not up to date. For myself only the mechanism of  `conan create -u` make sense and the other one could lead to error. Yes, there is only the need to update the recipe.

**Comment by petermbauer** [comment] 2020-01-09 14:12
I ran into the same issue today when using `conan info --build=missing -u` before `conan install` to find out whether a certain dependency would need to be built or not.
Maybe it is possible to add a "`--really-update`" flag for the "expected" behavior while maintaining backwards compatibility?

**Comment by climblinne** [comment] 2020-01-10 06:21
I think the idea from @petermbauer would really help. That would solve the problem.

**Comment by memsharded** [comment] 2023-02-17 21:31
Closed by https://github.com/conan-io/conan/pull/13157 for 2.0

**Closed by memsharded** 2023-02-17 21:31 UTC
Labels: type: look into, stage: queue
