### ISSUE TITLE
"conan upload" should support MSYS shell

### ISSUE THREAD

**Issue by annulen** [conan-io/conan#644] opened 2016-11-09 18:44 UTC
Rationale: MSYS uses separate home path, so all packages built in MSYS shell end up in other .conan directory than those built with cmd.exe. While it's certainly possible to run conan in cmd.exe with `CONAN_USER_HOME` pointing to MSYS home, it's adding unnecessary hassle.

Currently upload doesn't work in MSYS shell: password is entered in a plain view instead of silenced (I guess conio API is used which is not supported here), and upload doesn't start.

**Comment by memsharded** [comment] 2016-11-09 20:23
About the password issue, it might be difficult to solve, as conan is not directly handling that itself, but a third party library. We might have a look at its internals, but maintaining a modified fork of it could be troublesome. This can be workarounded running ``conan user`` with password in a cmd console, and the token will be cached for running from MSYS (once the paths issue is solved).

Certainly if MSYS is using a different home, this is undesired, marking that as bug, lets see how can we fix it. Same about the upload don't starting, no idea why, will have a look. Thanks very much for reporting these problems.

**Comment by annulen** [comment] 2016-11-09 21:54
One possible way to handle this issue is to make a feature request in that third party library

**Comment by memsharded** [comment] 2016-11-09 22:30
Just checked, it happens that I was wrong, it is not a third party but python itself. So anything there would be in the best case slow, and require more work than a third party. This might be related (https://bugs.python.org/issue25834)

**Comment by annulen** [comment] 2016-11-09 22:59
Well, if this is fixed in the next Python release you can ship official Windows binaries with it and that would be enough

**Comment by memsharded** [comment] 2016-11-10 10:03
I have been able to submit a PR: https://github.com/conan-io/conan/pull/651. I have been trying locally and it works, been able to use the normal path (C:/Users...), playing at the same time with a normal cmd console, build packages, test_packages, search packages and upload to a remote. So I guess that most of the issue was because of the wrong paths.

I was not able to reproduce the password issue, password is correctly hidden in my MSYS terminal (standard one installed with mingw-get)

**Comment by annulen** [comment] 2016-11-10 10:06
>So I guess that most of the issue was because of the wrong paths.
Yes, having shared `.conan` will solve the problem

>I was not able to reproduce the password issue, password is correctly hidden in my MSYS terminal 
I was using terminal preinstalled with MSYS2

**Comment by memsharded** [comment] 2016-11-27 22:21
I think this issue can be mostly labeled as fixed, it will be released in 0.16. If the visible password is still an issue, a new one could be submitted, but most likely to python project, as it is a core python issue, conan is doing nothing but using such functionality.

**Comment by memsharded** [comment] 2016-11-29 10:49
Released in 0.16

**Closed by memsharded** 2016-11-29 10:49 UTC
Labels: bug, fixed
