### ISSUE TITLE
[bug] libtool/2.4.7: Cannot load recipe

### ISSUE THREAD

**Issue by paulross80** [conan-io/conan#13128] opened 2023-02-14 20:13 UTC
### Environment details

`uname -a`
`Linux gotham 6.0.19-3-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Jan 18 07:57:11 UTC 2023 x86_64 GNU/Linux`
`g++ --version`
`g++ (GCC) 12.2.1 20230111`
`conan --version`
`Conan version 2.0.0-beta9`
`python3 --version`
`Python 3.10.9`

### Steps to reproduce

conanfile.py:

`from conan import ConanFile

class AppRecipe(ConanFile):

    settings = 'os', 'compiler', 'build_type', 'arch'
    generators = 'CMakeToolchain', 'CMakeDeps'

    def requirements(self):
        self.requires('sdl/[>2.26.0 <3.0]')

    def layout(self):
        compiler_name = self.settings.get_safe('compiler')
        build_type = self.settings.get_safe('build_type', default='Debug')
        arch = self.settings.get_safe('arch')

        self.folders.build = f'{compiler_name}-{build_type}-{arch}'
        self.folders.generators = 'build'
`

### Logs

Command:
`conan install . --build missing`

Conan Output:
`
-------- Input profiles --------
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu20
compiler.libcxx=libstdc++11
compiler.version=12
os=Linux

-------- Computing dependency graph --------
Graph root
    conanfile.py: /home/paul/Programming/proyectos/Papa_Conan2/conanfile.py
Requirements
    libalsa/1.2.7.2#ae1c73738bf26edee0ef3cb1009ef2e3 - Cache
    libiconv/1.17#7f5704761b99aeddacadf5c7904ffbaa - Cache
    sdl/2.26.1#32151611eb9c727574c4bc7ccef817cc - Cache
Resolved version ranges
    sdl/[>2.26.0 <3.0]: sdl/2.26.1
Graph error
    Package 'libtool/2.4.7' not resolved: libtool/2.4.7: Cannot load recipe.
Error loading conanfile at '/home/paul/.conan2/p/f6d8508ff5cad850/e/conanfile.py': Unable to load conanfile in /home/paul/.conan2/p/f6d8508ff5cad850/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/paul/.conan2/p/f6d8508ff5cad850/e/conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/home/paul/Programming/proyectos/Papa_Conan2/venv/lib/python3.10/site-packages/conans/__init__.py)

ERROR: Package 'libtool/2.4.7' not resolved: libtool/2.4.7: Cannot load recipe.
Error loading conanfile at '/home/paul/.conan2/p/f6d8508ff5cad850/e/conanfile.py': Unable to load conanfile in /home/paul/.conan2/p/f6d8508ff5cad850/e/conanfile.py
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/paul/.conan2/p/f6d8508ff5cad850/e/conanfile.py", line 1, in <module>
    from conans import AutoToolsBuildEnvironment, ConanFile, tools
ImportError: cannot import name 'AutoToolsBuildEnvironment' from 'conans' (/home/paul/Programming/proyectos/Papa_Conan2/venv/lib/python3.10/site-packages/conans/__init__.py)`

**Comment by memsharded** [comment] 2023-02-14 21:46
Hi @paulross80 

Thanks for your report.
This is not a bug in Conan, but a ConanCenter recipe that has not been updated to be 2.0 ready yet. 
Updating recipes to 2.0 is an ongoing effort, so far the efforts are being done on the most downloaded recipes: https://github.com/conan-io/conan-center-index/issues/12888

You can see there that libtool is still not ready. I am closing this issue, please follow up in the conan-center-index repo for progress on this.

**Closed as completed by memsharded** 2023-02-14 21:46 UTC
