### ISSUE TITLE
[bug] Workspace install fails with package_revision_mode()

### ISSUE THREAD

**Issue by domfellner** [conan-io/conan#8544] opened 2021-02-23 10:53 UTC
If I set some package's package id mode to package_revision_mode() in a workspace environment, then the workspace install step fails.

Use case: We need the binary management to be strict and traceable in our company and at the same time allow workspace usage for convenient development. 

I saw that the workspace feature will be _dramatically re-designed_ on the road to Conan 2.0 (see https://github.com/conan-io/conan/issues/8531), but my issue might still be of interest and solved easily as there is already special binary treatment for editable packages. I'd also be quite happy to help solving the issue with a PR if you could provide some guiding. The workspace feature is already a very helpful feature.

### Environment Details
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2015
  * Conan version: 1.33.1
  * Python version: 3.8.2

### Steps to reproduce

1. Checkout https://github.com/conan-io/examples
2. Add package_id() method to features/workspace/cmake/hello/conanfile.py containing:
`def package_id(self):
    self.info.requires.package_revision_mode()`
3. Run features/workspace/cmake/build.bat

### Additional info

- Everything works fine with `self.info.requires.recipe_revision_mode()`
- I found that there is special treatment for editable binaries in the source code which seems not to apply in a workspace environment: https://github.com/conan-io/conan/blob/54fd723bddc41d2ad7d4e6f59896fb6b7727b004/conans/client/installer.py#L434
- I tried hardcoding the binary to be BINARY_EDITABLE and this indeed solved the issue at first sight. 
- My knowledge of the inner mechanisms of Conan are not sufficient to provide a solution. Maybe you can hint what the proper approach could be and I could try it and create a PR?

### Logs (Executed commands with output)

`$ conan workspace install ../conanws_vs.yml`

Requirements
    chat/0.1@user/testing from user folder - Editable
    hello/0.1@user/testing from user folder - Editable
    say/0.1@user/testing from user folder - Editable

Packages
    chat/0.1@user/testing:74c51757df6a8ef72a96771ca8265394a1335e1b - Editable
    hello/0.1@user/testing:Package_ID_unknown - Unknown
    say/0.1@user/testing:63da998e3642b50bee33f4449826b2d623661505 - Editable

Installing (downloading, building) binaries...
say/0.1@user/testing: Generator cmake_multi created conanbuildinfo_release.cmake
say/0.1@user/testing: Generator cmake_multi created conanbuildinfo_multi.cmake
say/0.1@user/testing: Generator cmake created conanbuildinfo.cmake
say/0.1@user/testing: Generated conaninfo.txt
say/0.1@user/testing: Generated graphinfo
say/0.1@user/testing: Generated conanbuildinfo.txt

Traceback (most recent call last):
  File "\*\*\*\venv\lib\site-packages\conans\client\command.py", line 2115, in run
    method(args[0][1:])
  File "\*\*\*\venv\lib\site-packages\conans\client\command.py", line 1801, in workspace
    self._conan.workspace_install(args.path, args.settings_host, args.options_host,  
  File "\*\*\*\venv\lib\site-packages\conans\client\conan_api.py", line 94, in wrapper
    return f(api, *args, **kwargs)
  File "\*\*\*\venv\lib\site-packages\conans\client\conan_api.py", line 522, in workspace_install
    installer.install(deps_graph, remotes, build, update, keep_build=False,
  File "\*\*\*\venv\lib\site-packages\conans\client\installer.py", line 308, in install
    self._build(nodes_by_level, keep_build, root_node, graph_info, remotes, build_mode, update)
  File "\*\*\*\venv\lib\site-packages\conans\client\installer.py", line 438, in _build
    assert ref.revision is not None, "Installer should receive RREV always"
AssertionError: Installer should receive RREV always

ERROR: Installer should receive RREV always

**Comment by danimtb** [comment] 2021-03-10 17:37
Hi @domfellner and sorry for the delay in answering this issue.

Thanks a lot for providing a reproducible example to check this. I can confirm the issue.
After a first debug in the source code, I can't tell the reason why those binaries are not processed correctly. Probably the package ID missing from the graph is the cause.

Unfortunately, the workspaces feature is lacking some support in the package id modes and it is not being actively maintained. We are working towards improving editable packages and layouts first as there are still some pending issues in this area in order to make them stable. Workspaces feature sits on top of editables and the layout and we cannot tell when this issue could be addressed right now ad we are focusing our efforts on the development of Conan 2.0 right now.

Thanks a lot for reporting.

**Comment by memsharded** [comment] 2023-03-20 23:47
``package_revision_mode`` has been completely removed in 2.0, because it was too problematic in many aspects, and also ill-conceived, supporting only badly defined scenarios. Closing this as oudated.

**Closed as completed by memsharded** 2023-03-20 23:47 UTC
Labels: type: bug, stage: queue
