### ISSUE TITLE
[QUESTION] Could not run in parallel 2 the same receipt

### ISSUE THREAD

**Issue by redradist** [conan-io/conan#17423] opened 2024-12-05 20:17 UTC
### What is your question?

When I run the following receipt 2 parallel version for different build_type (Debug and Release):
```python
import os
import shutil
from copy import copy

from conan import ConanFile
from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout, CMakeDeps
from conan.tools.scm import Git


class HackRFRecipe(ConanFile):
    name = "hackrf"
    version = "v2024.02.1"
    package_type = "library"

    # Optional metadata
    license = "MIT"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of hackrf package here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False], "fPIC": [True, False]}
    default_options = {"shared": False, "fPIC": True}

    def source(self):
        git = Git(self)
        self.output.info(f"Start cloning hackrf ...")
        git.clone(url="git@github.com:greatscottgadgets/hackrf.git", target=".")
        git.checkout("v2024.02.1")

    def config_options(self):
        if self.settings.os == "Windows":
            self.options.rm_safe("fPIC")

    def configure(self):
        if self.options.shared:
            self.options.rm_safe("fPIC")

    def layout(self):
        cmake_layout(self)

    def generate(self):
        deps = CMakeDeps(self)
        tc = CMakeToolchain(self)
        self.output.info(f"Start generate ...")
        deps.generate()
        tc.generate()

    def build(self):
        cmake = CMake(self)
        self.output.info(f"Start build ...")
        cmake.configure(build_script_folder=f"./host")
        cmake.build()

    def package(self):
        cmake = CMake(self)
        cmake.install()

        shutil.copy(f"{self.build_folder}/libhackrf/src/libhackrf.a", f"{self.package_folder}/lib")
        shutil.copy(f"{self.build_folder}/libhackrf/src/libhackrf.dylib", f"{self.package_folder}/lib")

    def package_info(self):
        self.cpp_info.libs = ["hackrf"]
        self.cpp_info.libdirs = [f"{self.package_folder}/lib"]

        # Set rpath for dynamic library (optional, for macOS/Linux)
        if self.settings.os in ["Macos", "Linux"]:
            self.cpp_info.system_libs = ["dl", "pthread"]  # Add system dependencies if necessary
```

I got the following version:
```console
  File "<frozen os>", line 227, in makedirs
FileExistsError: [Errno 17] File exists: '~/.conan2/p/hackr12c3fc84faf65/s'
```
and other strange errors, but when I run single version at the time all works fine

How to run in parallel this receipt for different build types ??

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-12-06 23:44
Hi @redradist 

It is known that the Conan 2 cache is not concurrent by design, see https://docs.conan.io/2/knowledge/guidelines.html

It doesn't mean that it will not be implemented, it is in our roadmap, but it will still take some time. This is the ticket you want to track: https://github.com/conan-io/conan/issues/15840

As a quick hint, you can try to reduce the race conditions by:
- Do a unique ``conan graph info`` with ``-c tools.build:download_source=True``, to force the retrieval of recipes and sources
- Then try to launch the build of the parallel packages

I am closing this ticket as duplicated, please follow the other ticket to get updates about progress when it starts to happen. Thanks for the feedback.

**Closed as not planned by memsharded** 2024-12-06 23:44 UTC
Labels: duplicate

**Comment by redradist** [comment] 2024-12-07 22:43
> Hi @redradist
> 
> It is known that the Conan 2 cache is not concurrent by design, see https://docs.conan.io/2/knowledge/guidelines.html
> 
> It doesn't mean that it will not be implemented, it is in our roadmap, but it will still take some time. This is the ticket you want to track: #15840
> 
> As a quick hint, you can try to reduce the race conditions by:
> 
>     * Do a unique `conan graph info` with `-c tools.build:download_source=True`, to force the retrieval of recipes and sources
> 
>     * Then try to launch the build of the parallel packages
> 
> 
> I am closing this ticket as duplicated, please follow the other ticket to get updates about progress when it starts to happen. Thanks for the feedback.

@memsharded Thanks for explanaition.

How to do this trick `conan graph info` with `-c tools.build:download_source=True` for `cmake-conan` ?

**Comment by memsharded** [comment] 2024-12-08 21:43
> How to do this trick conan graph info with -c tools.build:download_source=True for cmake-conan ?

cmake-conan would require to modify the ``conan_provider.cmake`` dependency provider and add the call to ``conan graph info`` there. How is ``cmake-conan`` being called concurrently? As this is a developer flow thing, we don't know of use cases that run it in parallel.

**Comment by redradist** [comment] 2024-12-09 06:44
> How is `cmake-conan` being called concurrently? As this is a developer flow thing, we don't know of use cases that run it in parallel.

For 2 different configurations Debug and Release in Clion IDE.
Clion IDE calls 2 configuration process for Debug and Release in parralel

**Comment by memsharded** [comment] 2024-12-09 09:52
Have you tried the CLion plugin? It builds on top of the cmake-conan, and it is supposed to avoid these concurrency issues.

**Comment by redradist** [comment] 2024-12-09 09:59
> Have you tried the CLion plugin? It builds on top of the cmake-conan, and it is supposed to avoid these concurrency issues.

No, I use `conan_provider.cmake` directly ...

If this is such simple workaround, then why you cannot implement it directly in `conan` and later to remove and implement it properlly ??
