### ISSUE TITLE
[question] including a .pri file as part of the conanbuildinfo.pri file

### ISSUE THREAD

**Issue by jandrewmc** [conan-io/conan#3897] opened 2018-11-01 17:51 UTC
To help us debug your issue please explain:

I'm in the process of creating conan packages from some libraries developed with Qt.  Some of my dependents require a .pri file to be included from a dependency.  It would be really useful if the conanbuildinfo.pri file had a way to add a statement such as: include(x.pri).  Am I just missing this or is it something that isn't supported by the qmake generator?
something like

Edit:
I'm not sure why it ended up cutting off.  I was just hoping there was a way to setup the conanfile.py to have a statement such as:

    def package_info(self):
        self.cpp_info.include("x.pri", "x is included")

that would translate into the conanbuildinfo.pri as:
    include("x.pri") {
        message("x is included")
    }

I just thought it was a common enough workflow that it was already implemented and I just missed it.  I could add the include statement to the project and all the dependencies that require the .pri file but i was trying to avoid that.  I was looking into writing my own generator but again i was trying to see if this was a supported workflow that I had missed.

- [X] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).

- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
Centos 7
Conan 1.8.4
qmake

- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment] 2018-11-01 23:35
Hi @jandrewmc 

Maybe your issue is incomplete? Seems last sentence is unfinished. 

The issue is not clear, why not doing the `` include(x.pri)`` directly in the consumer file? There is no need that it is in the ``conanbuildinfo.pri`` file. 

In any case you can create your own generator relatively easy: https://docs.conan.io/en/latest/howtos/custom_generators.html#dyn-generators

**Comment by danimtb** [comment] 2018-11-20 12:39
Hi @jandrewmc,

As you may now, Conan is able to work with any build system and this is achieve with the abstraction done in `package_info()` method inside each recipe and the `generators`.

The package info method should include any relevant information for consumers and do not include information specific to a build system in particular. This information is then provided to generators to great a file that could be used in a different build system if desired.

Following this concepts, your suggestion should not be possible as it breaks the design principles of Conan. However, maybe the current `qmake` generator responsible for creating the *conanbuildinfo.pri* is missing some information from dependencies needed for your project.

If you need some help with this please post here a minimal example and I could guide you on how to convert those packages or fill all the useful the information in ``package_info()``

Hope it helps 😄

**Comment by danimtb** [comment] 2018-11-23 10:29
I forgot to add the link to the docs on how to use the *conanbuildinfo.pri* file: https://docs.conan.io/en/latest/integrations/qmake.html You can find some examples there and more detailed information.

I am closing this as solved but please feel free comment with any doubts you may have. Thanks 😄

**Closed by danimtb** 2018-11-23 10:29 UTC
Labels: Feedback please!, stage: triaging, type: question

**Comment by danimtb** [comment] 2018-11-23 14:06
Sorry, I forgot to mention that there is actually a way of referencing your build strips: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#cpp-info

You will have to use the ``builddirs`` in your `package_info()`  and package you build script in the `package() method`. Something similar to this:

```
    def package(self):
        self.copy(*.pri", ".", "build_scripts")

    def package_info(self):
       self.cpp_info.buiddirs = ["build_script"]
```

Then, that value would be accessible in another dependent recipe through the `self.deps_cpp_info["upstream"].build_paths` object.
