### ISSUE TITLE
[question] Upload is skipping a package with a different hash

### ISSUE THREAD

**Issue by sd185233** [conan-io/conan#8427] opened 2021-02-02 10:12 UTC
We are investigating using Conan and have forked our 3rd party deps so we can build and host on our remote.  For Ninja, the recipe has the following settings (this is from the bincrafters version).  settings.compiler is being removed from package_id.  

settings = "os_build", "arch_build", "compiler"

I believe we should probably be using split build and host profiles, but this should still work right?  Ninja is being used on Linux builds and Android builds cross compiled on Windows.  

After clearing the remote, creating then uploading all, search on the remote returns this - 
![image](https://user-images.githubusercontent.com/69502342/106584732-74fc4680-653e-11eb-83fa-cffb4fa29f7d.png)

Then build from another OS and upload all, search then returns this (single package, was expecting two)- 
![image](https://user-images.githubusercontent.com/69502342/106584897-a412b800-653e-11eb-8547-dcd32087f46c.png)

If we try an upload with --no--overwrite all, we can see the package is skipped, even though the hash of the package on the remote is different.
![image](https://user-images.githubusercontent.com/69502342/106585166-f18f2500-653e-11eb-8e4a-b37499f78581.png)

Why is the package not being added?  Are we doing something fundamentally wrong here?

**Comment by sd185233** [comment] 2021-02-02 12:06
OK, I don't think this is anything to do with the *_build settings.  The same issue is occurring for all our packages (using os, arch etc).  Issue seems to be appearing after starting to use user/channel - clear remote, search returns nothing, build on one OS and upload, search returns the package OK, build on another OS and upload and instead of both packages for each OS being available, only one package exists.

**Comment by memsharded** [comment] 2021-02-02 13:07
Hi @sd185233 

Just to make sure, please tell:
- Which Conan version are you using.
- Which server are you using and which version of the server.
- Have you enabled revisions or not?

If this is a problem, I think it should be possible to reproduce with an almost empty recipe, that contains only the settings definitions. Please let me know if you can reproduce with such a recipe, and if you could detail a bit more what are the exact commands you are using, that would help. Thanks!

**Comment by sd185233** [comment] 2021-02-02 14:06
-Conan version - 1.33.0
-Server - JFrog Artifactory...not sure of the version
-Revisions are enabled

Tried with a minimal recipe - 
```
from conans import ConanFile

class TestConan(ConanFile):
    name = "test"
    version = "1.0.0"
    description = "test"
    license = "Apache-2.0"
    url = "https://test.com"
    homepage = url
    settings = "os", "arch_build", "compiler"
    generators = "cmake"
    topics = ("conan", "test")
    default_user= "us"
    default_channel = "ch"

    def build(self):
        pass
        
    def package(self):
        pass

    def package_info(self):
        pass
```


Commands used:
conan remove "test*" --force
conan create . -pr Windows_x64_Release
conan upload "test*" --all -r our_remote --confirm
conan search "test/1.0.0@us/ch" -r our_remote   <-- returns 1 package, OK

conan remove "test*" --force
conan create . -pr Linux_x64_Release
conan upload "test*" --all -r our_remote --confirm
conan search "test/1.0.0@us/ch" -r our_remote <-- returns 2 packages, OK

Everything appears to be working as expected.  Trying to figure out why we are not seeing the same behaviour with our openssl and ninja packages.  I'll keep digging...

**Comment by memsharded** [comment] 2021-02-02 14:16
Some ideas:

- Check changing the settings to use ``os_build``.
- By default, the os_build and arch_build are removed from package_id. They can be optionally added back. But the package_id in this case should be identical, not different. Check the recipes ``package_id()`` methods

**Comment by sd185233** [comment] 2021-02-02 14:27
Changed to os_build then created and upload for Windows - search returned one package (guessing because recipe changed?).  Created linux package and uploaded and two appear in search OK.  Tried multiple times and it appears to be OK.  

I didn't change package_id to add os_build, but hashes appear to be different still...

![image](https://user-images.githubusercontent.com/69502342/106613777-78a1c480-6562-11eb-8742-8328929ccf89.png)

Looking at the Ninja recipe, it uses exports_sources - could it be anything to do with this?  
exports_sources = ["CMakeLists.txt", "*.patch", "source/*"]

**Comment by sd185233** [comment] 2021-02-02 14:37
I think this is maybe the issue...Both builds have a different file summary hash so when we go to upload the package from the other job, the recipe has changed and only the package for that recipe revision shows (like what I saw above after changing the recipe).

![image](https://user-images.githubusercontent.com/69502342/106615518-6cb70200-6564-11eb-87cf-c7fcc005f7de.png)


Maybe we are not understanding how this recipe should work, but think we are getting closer.

**Comment by memsharded** [comment] 2021-02-02 14:43
Yes, that could be it. If the recipe changes somehow, any file, even CRLF of files (different git checkout policies in different platforms), it will create a new recipe revision. Binaries belong to a given revision, the one that was actually used to build that binary. New changes that induce a new recipe revision will need to build their own binaries.

Make sure the recipe revision matches for both binaries.

**Comment by sd185233** [comment] 2021-02-02 15:05
Looks like that's the issue.  The exact same revision from git built on two different machines gives the following - 

Windows / Android (Windows machine)
zlib/1.2.11: Using the exported files summary hash as the recipe revision: 5c6879bc1e538066293201d2734fbc86 
zlib/1.2.11: Exported revision: 5c6879bc1e538066293201d2734fbc86

CentOS
zlib/1.2.11: Using the exported files summary hash as the recipe revision: 018a3e599ab72fd981569afac2e6a29e 
zlib/1.2.11: Exported revision: 018a3e599ab72fd981569afac2e6a29e

So packages only show for whichever OS was last to run.  Unless we cross build everything on the same OS, how can this work?   What is included in the "exported files summary hash"?  Could line endings be ignored?  Is this customisable?

The scm attribute is being used for our own packages - will this suffer from the same issue?

When dependencies are resolved, without referencing a specific revision, is there any way to have Conan look back previous revisions (for the same recipe version) to see if there are any matching binaries?

**Comment by sd185233** [comment] 2021-02-02 15:36
OK, so using the scm attribute instead of export_sources results in the same issue.

![image](https://user-images.githubusercontent.com/69502342/106623264-56ad3f80-656c-11eb-8b22-922d5256e970.png)

This feels like a bit of a showstopper :(

**Comment by sd185233** [comment] 2021-02-02 15:41
Aha, so if we use revision_mode "scm" along with the scm attribute, it works :)  I guess that's the route we will need to go down.

**Comment by memsharded** [comment] 2021-02-02 15:58
Hi @sd185233 

So it is typically one of 2 things:

- The different line feeds CRLF vs LF in different platforms. This can be solved by adjusting the way git checkouts (.gitattributes or git config). It is a good idea that git always checkout all files with same line feed in all platforms. CRLF is not really needed in Windows anymore

- It could be some conditional on the export or something that makes it difference between different platforms. This is a bad idea, a recipe should have exactly the same files exported into it in every system, because that will be reused later in different platforms to build from source.

Like 90% of times is the first one. Using ``revision_mode=scm`` uses the git commit as a revision instead of the contents. This is nice, but need to make sure that the repo is clean, not modified files, etc. otherwise it might block the upload.

**Comment by sd185233** [comment] 2021-02-02 16:08
OK, we will check our git settings and try to enforce that for consistency.  Will prob go with the scm rev mode for our stuff in the first instance.  

Thanks for the help!

**Comment by memsharded** [comment] 2021-02-02 18:41
Good. I'll close this questions as responded, but feel free to comment, re-open or open a new ticket if you have any further question or issue. Thanks!

**Closed as completed by memsharded** 2021-02-02 18:41 UTC
Labels: stage: triaging
