### ISSUE TITLE
[bug] imports(): files are not copied

### ISSUE THREAD

**Issue by Linux13524** [conan-io/conan#7969] opened 2020-10-29 13:55 UTC
My goal is to re-package files (configs) from a dependency with my application:

If I run `self.copy("*", dst="bin", src="res")` in the `imports` method, the log shows that files are copied (`app/0.1.0 imports(): Copied 1 '.txt' file: config.txt`), but the files are not at the specified destination. Subdirectories are created though. I created a minimal example that shows the problem. Am I missing anything?

### Environment Details
  * Operating System+version: Fedora 32
  * Compiler+version: gcc 10.2.1
  * Conan version: 1.30.0
  * Python version: 3.8.6

### Steps to reproduce
[example.zip](https://github.com/conan-io/conan/files/5458695/example.zip)

```
# unzip example.zip && cd conan_test
# cd library
# conan create . 
# cd ../application
# conan create . 
```

### Logs
```
 conan create .  app/0.1.0
Exporting package recipe
app/0.1.0: The stored package has not changed
app/0.1.0: Using the exported files summary hash as the recipe revision: 5b122c98b00ea2ed4937593895dec289 
app/0.1.0: Exported revision: 5b122c98b00ea2ed4937593895dec289
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

app/0.1.0: Forced build from source
Installing package: app/0.1.0
Requirements
    app/0.1.0 from local cache - Cache
    libA/0.1.0 from local cache - Cache
Packages
    app/0.1.0:45a54338de2fedec64ff1a7e85e6b6d3d70c62d7 - Build
    libA/0.1.0:6189bce1110de95c7ad3a77a486a51bf13b7e3d1 - Cache

Installing (downloading, building) binaries...
libA/0.1.0: Already installed!
app/0.1.0: Configuring sources in /home/lkloeckner/.conan/data/app/0.1.0/_/_/source
app/0.1.0: Copying sources to build folder
app/0.1.0: Building your package in /home/lkloeckner/.conan/data/app/0.1.0/_/_/build/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7
app/0.1.0: Generator txt created conanbuildinfo.txt
app/0.1.0 imports(): Copied 1 '.txt' file: config.txt
app/0.1.0: Calling build()
app/0.1.0: WARN: This conanfile has no build step
app/0.1.0: Package '45a54338de2fedec64ff1a7e85e6b6d3d70c62d7' built
app/0.1.0: Build folder /home/lkloeckner/.conan/data/app/0.1.0/_/_/build/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7
app/0.1.0: Generated conaninfo.txt
app/0.1.0: Generated conanbuildinfo.txt
app/0.1.0: Generating the package
app/0.1.0: Package folder /home/lkloeckner/.conan/data/app/0.1.0/_/_/package/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7
app/0.1.0: Calling package()
app/0.1.0 package(): WARN: No files in this package!
app/0.1.0: Package '45a54338de2fedec64ff1a7e85e6b6d3d70c62d7' created
app/0.1.0: Created package revision ad67cc4f34eeb914e2c0550b5f232fe4

 tree ~/.conan/data/app/0.1.0/_/_/build/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7 
/home/lkloeckner/.conan/data/app/0.1.0/_/_/build/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7
├── bin
│   └── configs
├── conanbuildinfo.txt
├── conan_imports_manifest.txt
└── conaninfo.txt

 tree ~/.conan/data/app/0.1.0/_/_/package/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7 
/home/lkloeckner/.conan/data/app/0.1.0/_/_/package/45a54338de2fedec64ff1a7e85e6b6d3d70c62d7
├── conaninfo.txt
└── conanmanifest.txt
```

EDIT:
Running the same copy in `imports` in a test_package, does copy the files as expected.

**Comment by Ext3h** [comment] 2020-11-03 10:40
Can confirm on different OS, with different package

Operating System+version: Windows 10
Compiler+version: Visual Studio 15
Conan version: 1.30.0
Python version: 3.8.6

Files are listed, but no files are copied.
Subdirectories for any of the listed files are created at the destination.

**Comment by Ext3h** [comment] 2020-11-03 10:42
Duplicate of  #7856, was fixed in 3.0.2

**Comment by memsharded** [comment] 2020-11-03 11:04
~~Might be related to https://github.com/conan-io/conan/issues/7990~~

Update: No, it doesn't seem related

**Comment by memsharded** [comment] 2020-11-03 11:12
Hi @Linux13524 

Yes, when the package is created in the cache, the imports are copied, they are used, and later they are removed. This was done to avoid a common accidental re-packaging of dependencies.

If you want to keep the imports, you should declare in your recipe (https://docs.conan.io/en/latest/reference/conanfile/attributes.html?#keep-imports):

```python
class Pkg(ConanFile):
    keep_imports = True
```

(this might change in Conan 2.0, and make this imports mechanism behavior in the cache more explicit)

Please try that and let us know. Thanks!

**Comment by Linux13524** [comment] 2020-11-03 11:19
Hi @memsharded!

`keep_imports = True` does the trick. Thanks a lot!

**Comment by memsharded** [comment] 2020-11-03 12:00
Thanks for reporting, and sorry for the delay in answering. 

I think this can be closed now, don't hesitate to open new tickets for further questions. Cheers!

**Closed as completed by memsharded** 2020-11-03 12:00 UTC
Labels: type: question

**Comment by ixtrader** [comment] 2020-12-22 10:08
Maybe removal of the files can be logged. 
Created Folders are not removed.
