### ISSUE TITLE
VS2017 recognized as gcc 4.9

### ISSUE THREAD

**Issue by madduci** [conan-io/conan#994] opened 2017-02-15 18:39 UTC
Step to reproduce:

- Fresh install of Windows 10 (build 1607 - Jan 2017)
- VS2017 RC Professional with Visual C++ and Universal Windows Platform toolkits
- Python installed from chocolatey (3.6)
- Conan installed using pip, build 0.19.1

On first usage, conan detects that I have gcc 4.9 (!!!) installed on my system.
Plus, settings.yml is disappeared from the .conan folder in my %USER% path.

**Comment by memsharded** [comment] 2017-02-15 22:17
That is pretty amazing. Unable to reproduce from here.
It is true that VS2017 is not detected by default from conan, but that is not a big issue, you can always edit and add it to ``conan.conf``. (BTW, the ``settings.conf`` never existed, it is either ``conan.conf`` or ``settings.yml``, which one has dissapeared?)

What is really weird is that it is detecting gcc 4.9. Can you just run a ``$ gcc --version`` or ``$ which gcc`` in your terminal?

Thanks very much for reporting!

**Comment by madduci** [comment] 2017-02-16 16:50
@memsharded sorry the `settings.yaml` is missing.

Well, it was unexpected: `cmd.exe` states on `gcc --version` that:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Michele>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=C:/Strawberry/c/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.2/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-shared --enable-static --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --enable-sjlj-exceptions --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-mpfr=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-mpc=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-isl=/opt/build/prerequisites/x86_64-w64-mingw32-static --with-cloog=/opt/build/prerequisites/x86_64-w64-mingw32-static --enable-cloog-backend=isl --with-pkgversion='x86_64-posix-sjlj, built by strawberryperl.com project' CFLAGS='-O2 -pipe -I/opt/build/x86_64-492-posix-sjlj-rt_v402/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' CXXFLAGS='-O2 -pipe -I/opt/build/x86_64-492-posix-sjlj-rt_v402/mingw64/opt/include -I/opt/build/prerequisites/x86_64-zlib-static/include -I/opt/build/prerequisites/x86_64-w64-mingw32-static/include' CPPFLAGS= LDFLAGS='-pipe -L/opt/build/x86_64-492-posix-sjlj-rt_v402/mingw64/opt/lib -L/opt/build/prerequisites/x86_64-zlib-static/lib -L/opt/build/prerequisites/x86_64-w64-mingw32-static/lib '
Thread model: posix
gcc version 4.9.2 (x86_64-posix-sjlj, built by strawberryperl.com project)

```

**Comment by memsharded** [comment] 2017-02-16 17:10
Aha! So there were actually one gcc 4.9 in the path! :) :)

So, then, I'd say this is not such an issue. A different thing is that VS2017 could be automatically detected (not sure how, as it doesn't set env-vars as it used to do), in that case, the issue could change the title. Thanks!

**Comment by madduci** [comment] 2017-02-16 17:41
yeah pardon, I hadn't time to run even gcc --version and watch for it. Just tried to install conan on Win10 and gcc got detected before MSVC. Is it normal that settings.yml is disappeared?

**Comment by memsharded** [comment] 2017-02-16 18:06
It might not be created until is needed. Try running some install and tell me. I guess a failed migration could remove it, but I'd say in your case it was not a migration, it was a blank machine.

**Comment by memsharded** [comment] 2017-03-24 08:58
Hi @madduci 
I think there is no action from our side in this issue, I am going to close it, but please re-open or comment if you need something or have further feedback. Thanks!

**Closed by memsharded** 2017-03-24 08:58 UTC

**Comment by madduci** [comment] 2017-03-24 11:56
I've seen that in the final release of VS2017 the bug is disappeared. Sorry for not updating the issue, I've had it only under the Beta and RC phase. thanks anyway

**Comment by memsharded** [comment] 2017-03-24 12:23
Thanks for telling :)
