### ISSUE TITLE
meson: add dependencies to PKG_CONFIG_PATH by default

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#4574] opened 2019-02-20 12:24 UTC
currently (as for conan 1.12.3), meson build helper doesn't add add any dependencies to the `PKG_CONFIG_PATH`, so it doesn't discover their *.pc files as well. for instance, in the `GStreamer` recipe I have to write:
```
        glib_pc = os.path.join(self.deps_cpp_info["glib"].rootpath, "lib", "pkgconfig")
        pkg_config_paths = [glib_pc, self.source_folder]
        ...
        meson.configure(build_folder=self._build_subfolder,
                        source_folder=self._source_subfolder,
                        pkg_config_paths=pkg_config_paths,
                        defs=defs)
```
otherwise, it doesn't add find GLib's pkg-config files (like `gio.pc`).

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment] 2019-02-20 17:25
This is the expected behavior of the pkg_config_paths attribute as the helper only looks for pc files in the installation folder (to use the ones generated by the ``pkg_config`` generator

**Comment by danimtb** [comment] 2019-02-27 10:38
could you please explain a little bit more? I think this is the intended behavior

**Comment by danimtb** [comment] 2019-02-28 16:40
Yesterday I was doing some tests and found that the helper was working properly with the `pkg_config` generator:

```
$ ls
conanfile.py  hello.cpp  meson.build
C:\Users\danimtb\test_meson
(py37-conan_sources) λ cat conanfile.py
from conans import ConanFile, Meson
class KrilliaConan(ConanFile):
    settings = "os", "compiler", "build_type", "arch"
    requires = "gtest/1.8.1@bincrafters/stable"
    generators = "pkg_config", "ycm"
    default_options = {"gtest:shared": True}
    def imports(self):
        self.copy("*.dll", dst="bin", src="bin") # From bin to bin
        self.copy("*.dylib*", dst="bin", src="lib") # From lib to bin
    def build(self):
        meson = Meson(self)
        meson.configure()
        meson.build()
        meson.test()

$ cat meson.build
project('hello',
        'cpp',
        version : '0.1.0'
        )
library('hello',
        ['hello.cpp'],
        dependencies: [dependency('gtest')]
        )
C:\Users\danimtb\test_meson
(py37-conan_sources) λ cat hello.cpp
#include <gtest/gtest.h>
int main()
{
    return 0;
}

$ mkdir build

$ conan install . -if build\
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=15
os=Windows
os_build=Windows
[options]
[build_requires]
*: pkg-config_installer/0.29.2@bincrafters/stable
[env]
PATH=[kk]
conanfile.py: Installing package
Requirements
    gtest/1.8.1@bincrafters/stable from 'conan-center' - Cache
Packages
    gtest/1.8.1@bincrafters/stable:a35f8fa327837a5f1466eaf165e1b6347f6e1e51 - Cache
Build requirements
    pkg-config_installer/0.29.2@bincrafters/stable from 'bincrafters' - Cache
Build requirements packages
    pkg-config_installer/0.29.2@bincrafters/stable:456f15897172eef340fcbac8a70811f2beb26a93 - Cache
gtest/1.8.1@bincrafters/stable: Already installed!
pkg-config_installer/0.29.2@bincrafters/stable: Already installed!
conanfile.py: Applying build-requirement: pkg-config_installer/0.29.2@bincrafters/stable
conanfile.py: Generator pkg_config created pkg-config_installer.pc
conanfile.py: Generator pkg_config created gtest.pc
conanfile.py: Generator ycm created conan_ycm_extra_conf.py
conanfile.py: Generator ycm created conan_ycm_flags.json
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
conanfile.py imports(): Copied 4 '.dll' files: gmock.dll, gmock_main.dll, libwinpthread-1.dll, gtest.dll

$ conan build . -if build\ -bf build
WARN: Hook '%CONAN_USER_HOME%/.conan/hooks/conanio/hooks/attribute_checker.py' not found in C:\Users\danimtb\.conan\hooks folder. Please remove hook from conan.conf or include it inside the hooks folder.
WARN: Hook 'C.py' not found in C:\Users\danimtb\.conan\hooks folder. Please remove hook from conan.conf or include it inside the hooks folder.
conanfile.py: Running build()
PC PAAATHS C:\Users\danimtb\test_meson\build
c:\users\danimtb\conan_sources\conans\util\fallbacks.py:9: UserWarning: Provide the output argument explicitly to function 'conans.client.tools.win.vcvars_command'
  warnings.warn("Provide the output argument explicitly{}".format(fn_str))
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
The Meson build system
Version: 0.49.2
Source dir: C:\Users\danimtb\test_meson
Build dir: C:\Users\danimtb\test_meson\build
Build type: native build
Project name: hello
Project version: 0.1.0
Native C++ compiler: cl (msvc 19.15.26730)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: C:\Users\danimtb\.conan\data\pkg-config_installer\0.29.2\bincrafters\stable\package\456f15897172eef340fcbac8a70811f2beb26a93\bin\pkg-config.EXE (0.29.2)
Dependency GTest found: YES 1.8.1
Build targets in project: 1
Found ninja-1.8.2 at 'C:\cmder\ninja.EXE'
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
ninja: Entering directory `C:\Users\danimtb\test_meson\build'
[2/2] Linking target hello.dll.
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.8.7
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
ninja: Entering directory `C:\Users\danimtb\test_meson\build'
[0/1] Running all tests.
No tests defined.
```

The original comment of this issue it is using the *.pc* packaged by a dependency which can be done exctaly in the way exposed but it is not the recommended way. Please use the `pkg_config` generator for that: https://docs.conan.io/en/latest/integrations/pkg_config_pc_files.html#approach-5-use-the-pkg-config-generator

Closing this but feel free to comment/reopen in case I am missing something. Thanks!

**Closed by danimtb** 2019-02-28 16:40 UTC
Labels: Feedback please!, stage: triaging

**Comment by SSE4** [comment] 2019-02-28 16:42
okay, thanks a lot for the investigation, @danimtb
