### ISSUE TITLE
User name cannot start with a number in 0.22.1

### ISSUE THREAD

**Issue by GrimSqueaker** [conan-io/conan#1224] opened 2017-04-19 10:48 UTC
Server: 0.22.1
Client: 0.21.2

When doing a `conan search -r $SERVERNAME` I get the error message:
```
ERROR: '3rdparty' is an invalid name. Valid names should begin with alphanumerical characters, '_' and '-'.. [Remote: xxx]
```

We have recipes like boost/1.51@3rdparty/legacy

**Comment by memsharded** [comment] 2017-04-19 12:50
Sorry for that, it seems some regressions were introduced while refactoring some code. The minor 0.22.1 was also due to this issue. Will check asap, and produce a new minor release to fix it.

**Comment by memsharded** [comment] 2017-04-19 21:25
I have opened a minor release branch fixing this: https://github.com/conan-io/conan/pull/1228
It will be released tomorrow as 0.22.2.

**Comment by memsharded** [comment] 2017-04-20 07:33
Hi! Conan 0.22.2 has been released. Please upgrade and report. Thanks!

**Comment by GrimSqueaker** [comment] 2017-04-20 11:11
Upgraded to 0.22.2 and Conan accepts "3rdparty" as a user name.
Thank you.

**Comment by memsharded** [comment] 2017-04-20 11:17
Excellent. Thanks for telling!

**Closed by memsharded** 2017-04-20 11:17 UTC
