### ISSUE TITLE
[question] Do I need Visual Studio installed in order to use the msbuild toolsets

### ISSUE THREAD

**Issue by KingKiller100** [conan-io/conan#13491] opened 2023-03-21 15:54 UTC
### What is your question?

Conan version: 1.59.0
OS: Window 10 Pro

Hi,

My projects uses MSVC++ 141_xp toolsets via VS 2017 to build my packages. 

I have updated to VS IDE 2022 for improved features, performance and backward compatibility with the VS 2017 builds tools and toolsets. I have now uninstalled VS 2017 to save storage space.

I have found that removing the VS 2017 IDE has stopped my builds. VS 2022 allows me to install old toolsets so I have installed the VS 2017 build tools i.e. v141_xp toolset that my project requires. 

Conan still fails to build my project.

I assumed that using the new generators and MSBuild helper from `conan.tools.microsoft` would allow us to use MSBuild with the required toolsets and build tools, without needing the Visual Studio IDE installed.

Is there a way for conan build using MSBuild helper and generators without needing Visual Studio installed?

Could the issue be in my profile file?

```bash
# release.profile
[build_requires]
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
compiler=Visual Studio
compiler.version=15
compiler.toolset=v141_xp
build_type=Release
compiler.runtime=MT
[options]
[env]
CONAN_DISABLE_STRICT_MODE=1
[conf]
tools.microsoft.msbuild:verbosity=Normal
```

Please let me know.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-03-21 16:11
Hi @KingKiller100 

Thanks for your report. 
Could you please provide a bit more of detail of what is failing? Maybe the full output could help.
Also, if the issue could be reproduced with something you can share, like the recipes or some small project, or maybe with the ``conan new hello/0.1 -m=msbuild_lib`` template, that would also help a lot.

**Comment by KingKiller100** [comment] 2023-03-21 17:57
This is the error message I get when attempting to install or build a package using the profile mentioned earlier.

Error message

```bash
ERROR: conanfile.py (game/1.2.1-alpha.93+git.3c282e6): Error in generate() method, line 44
        tc.generate()
        ConanException: VS non-existing installation: Visual Studio 15
```

**Comment by KingKiller100** [comment] 2023-03-21 18:02
@memsharded  This happens with any conanfile.py that utilizes the profile

**Comment by memsharded** [comment] 2023-03-21 21:43
I think I understand better now, thanks for the feedback.
Indeed the ``MSBuildToolchain`` does not implement using older toolsets in more modern IDEs installations.

We need to to have a look at this, thanks.

**Comment by memsharded** [comment] 2023-03-21 22:32
I was wrong, ``MSBuildToolchain`` defines the toolset, and the environment and IDE to be used is defined by ``vcvars``.

I am adding this test, and it works:
```python

@pytest.mark.skipif(platform.system() != "Windows", reason="Requires Windows")
def test_msbuild_lib_template_toolsets():
    client = TestClient()
    client.run("new hello/0.1 --template=msbuild_lib")
    # Local flow works
    settings = [("compiler", "Visual Studio"),
                ("compiler.version", "16"),
                ("compiler.toolset", "v141"),
                ("compiler.runtime", "MD"),
                ("build_type", "Release"),
                ("arch", "x86_64")]

    # Build the profile according to the settings provided
    settings = " ".join('-s %s="%s"' % (k, v) for k, v in settings)
    # Create works
    client.run(f"create . {settings}")
    print(client.out)
    assert "hello/0.1: Hello World Release!" in client.out
    assert "hello/0.1: _MSC_VER191" in client.out

    settings = [("compiler", "Visual Studio"),
                ("compiler.version", "16"),
                ("compiler.toolset", "v140"),
                ("compiler.runtime", "MD"),
                ("build_type", "Release"),
                ("arch", "x86_64")]

    # Build the profile according to the settings provided
    settings = " ".join('-s %s="%s"' % (k, v) for k, v in settings)
    # Create works
    client.run(f"create . {settings}")
    print(client.out)
    assert "hello/0.1: Hello World Release!" in client.out
    assert "hello/0.1: _MSC_VER190" in client.out
```
As you can see, it is able to build both previous v141 (191) and v140 (190) with the same IDE (VS 2019).

The test works with the ``conan new hello/0.1 -m=msbuild_lib`` template, maybe you can give it a try and check?

**Comment by db4** [comment] 2023-03-23 11:26
A related question: is `msvc` compiler expected to find the proper toolset from a newer VS installation (Conan 2.x)? Say, I have VS 2022/v141 toolset installed but `-s compiler=msvc -s compiler.version=192` gives `VS non-existing installation: Visual Studio 16`

**Comment by memsharded** [comment] 2023-03-23 12:10
It seems that it is not implemented that way, with the ``MSBuild`` integration, the settings would be: ``-s compiler=msvc -s compiler.version=193 -s compiler.toolset=v141``. But I think I understand what you mean, and that an implementation similar to the fallback that ``CMakeToolchain`` is doing would be better, I am having a look.

**Comment by memsharded** [comment] 2023-03-23 12:16
It seems it is implemented:
```
-s compiler.version=191 -c tools.microsoft.msbuild:vs_version=17
```
Would use the compiler.version 191, adding the ``PlatformToolset`` ``v141``, but using VS2022 as IDE. 
This would be the equivalent to ``-c tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022`` for CMake.

Could you please give it a try?

**Comment by db4** [comment] 2023-03-23 13:02
Yes, adding `-c tools.microsoft.msbuild:vs_version=17` does the job. I wasn't aware of this option and thought you searched the necessary toolset among all installed Visual Studios. But this way is also acceptable. Thank you!

**Comment by memsharded** [comment] 2023-03-23 13:22
The rationale in 2.0 is that things are more explicit defined in ``conf`` by user, and less automatically-autodetected. This is the same that was applied for ``CMakeToolchain``, it will not decide the VS version different to the compiler default searching all installed ones, it will expect users defining ``tools.cmake.cmaketoolchain:generator``.

Keeping the ticket open, waiting for @KingKiller100 feedback about https://github.com/conan-io/conan/issues/13491#issuecomment-1478681475

**Comment by KingKiller100** [comment] 2023-03-24 14:22
[#13491 comment](https://github.com/conan-io/conan/issues/13491#issuecomment-1478681475)'s test works with conan v1.59.0. 
This explains why my issue is occurring. With the compiler set to `Visual Studio`, it seems you've allowed us to use whatever toolset is available as long as we have the matching version of the IDE. That means the problem I'm facing may be due to the IDE version not being installed even though the toolset is present

**Comment by KingKiller100** [comment] 2023-03-24 14:32
> It seems it is implemented:
> 
> ```
> -s compiler.version=191 -c tools.microsoft.msbuild:vs_version=17
> ```
> 
> Would use the compiler.version 191, adding the `PlatformToolset` `v141`, but using VS2022 as IDE. This would be the equivalent to `-c tools.cmake.cmaketoolchain:generator=Visual Studio 17 2022` for CMake.
> 
> Could you please give it a try?

Would changing our profiles so that the compiler setting is set to `msvc` and add `tools.microsoft.msbuild:vs_version=17` be the proper solution?
Would this allow us to target VS build tools without requiring the whole IDE to be installed too?

Can you confirm if the profile rewrite below would give us the behaviour we want?

```bash
# release.profile
[build_requires]
[settings]
os=Windows
os_build=Windows
arch=x86
arch_build=x86_64
compiler=msvc
compiler.version=191
compiler.toolset=v141_xp
compiler.cppstd=17
compiler.runtime_type=Release
compiler.runtime=static
build_type=Release
[options]
[env]
CONAN_DISABLE_STRICT_MODE=1
[conf]
tools.microsoft.msbuild:verbosity=Normal
tools.microsoft.msbuild:vs_version=17
```

**Comment by KingKiller100** [comment] 2023-03-24 15:07
Side Note: in the settings of the `msvc` compiler, what is the `update` setting meant to represent?

**Comment by KingKiller100** [comment] 2023-03-27 16:53
@memsharded are you still there?

**Comment by memsharded** [comment] 2023-03-31 10:21
> Side Note: in the settings of the msvc compiler, what is the update setting meant to represent?

The ``update`` is the last digit of the ``msvc`` compiler version. It is opt-in, because by default ignoring it works quite well, for ConanCenter for example, assuming users move always forward in the updates and not backwards. It can be defined by users in profiles if you want a more accurate tracking of the exact update you are using and you want to ensure binary rebuilds for new compiler updates (within the same msvc version)

**Comment by memsharded** [comment] 2023-03-31 10:28
Regarding the profile, yes I think that works.
I have tried it:
```
conan new pkg/0.1 -m=msbuild_lib
conan create . -pr=profile
```
(the os_build and arch_build can be dropped already)

And I got this:
- ``Visual Studio 2022 Developer Command Prompt v17.3.3`` Running VS 17 as defined by the conf
- ``Building solution configuration "Release|x86"`` => it used the ``arch=x86`` setting
- ``error MSB8020: The build tools for v141_ xp (Platform Toolset = 'v141_xp') cannot be found`` because I don't have it installed
- The ``compiler.version`` will result in the final ``package_id`` (if you ``conan search pkg/0.1@``, it should be listed there)

I am closing this ticket as solved, but please let me know, don't hesitate to re-open or create new tickets if you have any further question.

**Closed as completed by memsharded** 2023-03-31 10:28 UTC
Labels: stage: triaging
