### ISSUE TITLE
[bug]  abseil_LIBS_RELEASE and protobuf_LIBS_RELEASE are EMPTY in generated XXX-Platform-data.cmake issuing in linking problems

### ISSUE THREAD

**Issue by tofDou** [conan-io/conan#16898] opened 2024-08-28 14:38 UTC
### Describe the bug

On a **Ubuntu 24** machine, with **Conan version 2.5.0**, I tried to setup a CMake project to test a gRPC server using protobuf and protoc generation.

My `conanfile.txt` is as follows:
```
[requires]
spdlog/1.14.1
cli11/2.4.2
bitserializer/0.70
grpc/1.65.0

[tool_requires]
protobuf/5.27.0

[test_requires]
gtest/1.14.0

[generators]
CMakeDeps
CMakeToolchain

[options]
bitserializer*:with_rapidyaml=True
*:shared=True
# desactive default options
grpc*:csharp_plugin=False
grpc*:node_plugin=False
grpc*:objective_c_plugin=False
grpc*:php_plugin=False
grpc*:ruby_plugin=False
# active default options
grpc*:cpp_plugin=True
grpc*:python_plugin=True

[layout]
cmake_layout

```

In the generated file (ie `absl-release-x86_64-data.cmake` or `protobuf-release-x86_64-data.cmake`)
the `XXX_LIBS_RELEASE` variable is empty whereas it is not the case for other packages like GRPC for exemple (all these packages use the notion of components).

Then using the pre-formated targets grpc::grpc or forcing protobuf::protobuf (and also component targets like protobuf::libprotobuf) in a target_link_libraries results in no library added to the linking command line:

```cmake
target_link_libraries(${GRPC_SERVER_LIB_TARGET} PUBLIC grpc::grpc)
target_link_libraries(${SIMULATOR_SERVER_TARGET} PUBLIC ${GRPC_SERVER_LIB_TARGET})
# or target_link_libraries(${SIMULATOR_SERVER_TARGET} PUBLIC ${GRPC_SERVER_LIB_TARGET} protobuf::XXX)
```

```log
[ 87%] Linking CXX executable BMS_Simulator_Server
/opt/install_rc/cmake-3.30.0-rc3-linux-x86_64/bin/cmake -E cmake_link_script CMakeFiles/BMS_Simulator_Server.dir/link.txt --verbose=1
/usr/bin/c++ -m64 -O3 -DNDEBUG -m64 CMakeFiles/BMS_Simulator_Server.dir/src/mainServer.cpp.o -o BMS_Simulator_Server   -L/home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib  -L/home/tof/.conan2/p/b/absei5cef6c44c3692/p/lib  -L/home/tof/.conan2/p/b/libsy2f345f32edb5b/p/lib  -L/home/tof/.conan2/p/b/libcaaadc757bf0341/p/lib  -L/home/tof/.conan2/p/b/libmo092499fd84eba/p/lib  -L/home/tof/.conan2/p/b/libxc4d74024af5f64/p/lib  -L/home/tof/.conan2/p/b/libse2d3528530cc26/p/lib  -L/home/tof/.conan2/p/b/pcre2be2b6e16a0331/p/lib  -L/home/tof/.conan2/p/b/zlib7f0e3a347313f/p/lib  -L/home/tof/.conan2/p/b/bzip25ccc74aa4b32d/p/lib  -L/home/tof/.conan2/p/b/lz46472f89e3c0cb/p/lib  -L/home/tof/.conan2/p/b/xz_ut9bc9b6301f4e6/p/lib  -L/home/tof/.conan2/p/b/zstd6292665721569/p/lib  -L/home/tof/.conan2/p/b/re236652c2b2dbb2/p/lib  -L/home/tof/.conan2/p/b/c-are41784da5741f4/p/lib  -L/home/tof/.conan2/p/b/opens969015a444a9d/p/lib  -L/home/tof/.conan2/p/b/proto0762bdf7e39f6/p/lib  -Wl,-rpath,/home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib:/home/tof/.conan2/p/b/absei5cef6c44c3692/p/lib:/home/tof/.conan2/p/b/libsy2f345f32edb5b/p/lib:/home/tof/.conan2/p/b/libcaaadc757bf0341/p/lib:/home/tof/.conan2/p/b/libmo092499fd84eba/p/lib:/home/tof/.conan2/p/b/libxc4d74024af5f64/p/lib:/home/tof/.conan2/p/b/libse2d3528530cc26/p/lib:/home/tof/.conan2/p/b/pcre2be2b6e16a0331/p/lib:/home/tof/.conan2/p/b/zlib7f0e3a347313f/p/lib:/home/tof/.conan2/p/b/bzip25ccc74aa4b32d/p/lib:/home/tof/.conan2/p/b/lz46472f89e3c0cb/p/lib:/home/tof/.conan2/p/b/xz_ut9bc9b6301f4e6/p/lib:/home/tof/.conan2/p/b/zstd6292665721569/p/lib:/home/tof/.conan2/p/b/re236652c2b2dbb2/p/lib:/home/tof/.conan2/p/b/c-are41784da5741f4/p/lib:/home/tof/.conan2/p/b/opens969015a444a9d/p/lib:/home/tof/.conan2/p/b/proto0762bdf7e39f6/p/lib:/home/tof/WorkSpace/BMS_Sim/build/Release libBMS_Simulator_Server_Lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpcpp_channelz.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc++_reflection.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc++_error_details.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc++_alts.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc++.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc++_unsecure.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc_authorization_provider.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libupb_textformat_lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libupb_json_lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc_unsecure.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libupb_message_lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgrpc_plugin_support.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libutf8_range_lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libupb_mem_lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libupb_base_lib.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libgpr.so /home/tof/.conan2/p/b/grpc9927a72cc6d62/p/lib/libaddress_sorting.so -lm -lrt -ldl -lpthread
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::MessageLite::SerializeToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::internal::AddDescriptors(google::protobuf::internal::DescriptorTable const*)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `void google::protobuf::internal::InternalMetadata::DoClear<google::protobuf::UnknownFieldSet>()'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::internal::ZeroFieldsBase::~ZeroFieldsBase()'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `descriptor_table_google_2fprotobuf_2fempty_2eproto'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `void google::protobuf::internal::InternalMetadata::DeleteOutOfLineHelper<google::protobuf::UnknownFieldSet>()'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::Message::CheckTypeAndMergeFrom(google::protobuf::MessageLite const&)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::internal::WireFormat::InternalSerializeUnknownFieldsToArray(google::protobuf::UnknownFieldSet const&, unsigned char*, google::protobuf::io::EpsCopyOutputStream*)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::Arena::Allocate(unsigned long)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `vtable for google::protobuf::Empty'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::internal::TcParser::FastV32S1(google::protobuf::MessageLite*, char const*, google::protobuf::internal::ParseContext*, google::protobuf::internal::TcFieldData, google::protobuf::internal::TcParseTableBase const*, unsigned long)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::Message::GetMetadataImpl(google::protobuf::MessageLite::ClassDataFull const&)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::internal::TcParser::GenericFallback(google::protobuf::MessageLite*, char const*, google::protobuf::internal::ParseContext*, google::protobuf::internal::TcFieldData, google::protobuf::internal::TcParseTableBase const*, unsigned long)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::MessageLite::ParseFromZeroCopyStream(google::protobuf::io::ZeroCopyInputStream*)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::Message::kDescriptorMethods'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::internal::AssignDescriptors(google::protobuf::internal::DescriptorTable const*)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::io::EpsCopyOutputStream::EnsureSpaceFallback(unsigned char*)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `typeinfo for google::protobuf::Message'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::MessageLite::SerializeWithCachedSizesToArray(unsigned char*) const'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::MessageLite::InitializationErrorString[abi:cxx11]() const'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `void google::protobuf::internal::InternalMetadata::DoMergeFrom<google::protobuf::UnknownFieldSet>(google::protobuf::UnknownFieldSet const&)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::Empty::Empty(google::protobuf::Arena*)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `typeinfo for google::protobuf::io::ZeroCopyInputStream'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::Message::MaybeComputeUnknownFieldsSize(unsigned long, google::protobuf::internal::CachedSize*) const'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `google::protobuf::io::ZeroCopyOutputStream::WriteAliasedRaw(void const*, int)'
/usr/bin/ld: libBMS_Simulator_Server_Lib.so: undefined reference to `typeinfo for google::protobuf::io::ZeroCopyOutputStream'
collect2: error: ld returned 1 exit status
gmake[3]: *** [CMakeFiles/BMS_Simulator_Server.dir/build.make:116: BMS_Simulator_Server] Error 1
gmake[3]: Leaving directory '/home/tof/WorkSpace/BMS_Sim/build/Release'
gmake[2]: *** [CMakeFiles/Makefile2:159: CMakeFiles/BMS_Simulator_Server.dir/all] Error 2
gmake[2]: Leaving directory '/home/tof/WorkSpace/BMS_Sim/build/Release'
gmake[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/BMS_Simulator_Server.dir/rule] Error 2
gmake[1]: Leaving directory '/home/tof/WorkSpace/BMS_Sim/build/Release'
gmake: *** [Makefile:189: BMS_Simulator_Server] Error 2
```

**Comment by memsharded** [comment] 2024-08-28 23:50
Hi @tofDou 

Thanks for your feedback.

I think this is expected. Both ``protobuf`` and ``abseil`` are not direct dependencies of the consumer application, and they are also shared libraries as you specified.

As such, they do not have to be directly linked. Doing such would be "over-linking". Only the direct dependencies have to be linked. Conan defines the data in the ``xxx-data.cmake`` files accordingly, defining the "LIBS" for the direct dependencies, and for the transitive dependencies only the ``INTERFACE_LINK_DIRECTORIES``.

If there are linking errors, it might be a different reason. Do you think that you could reduce the above to the bare minimum (probably using only ``grpc`` as dependency) and also provide a minimal CMakeLists.txt and the exact commands to reproduce, so we could investigate what could be happening? Also please confirm if you are using packages from ConanCenter. Thanks!

**Comment by memsharded** [comment] 2024-08-30 08:01
This could be a recipe issue, related with https://github.com/conan-io/conan-center-index/issues/24806

**Comment by memsharded** [comment] 2024-08-30 08:24
I am investigating this, but I am not able to reproduce, see https://github.com/conan-io/conan-center-index/issues/24806#issuecomment-2320465580, it would be great if you could provide a minimal reproducible case. Thanks!

**Comment by memsharded** [comment] 2024-09-04 08:41
Hi @tofDou 

This was an issue in the ``grpc`` recipe that has already been fixed in ConanCenter in https://github.com/conan-io/conan-center-index/pull/25087

Can you please update to the latest revision of ``grpc`` (you can ``conan remove grpc* -c`` or use ``--update``) and let us know?

**Comment by memsharded** [comment] 2024-09-24 22:33
I am closing this ticket as resolved, but please @tofDou don't hesitate to create new tickets for any further question or issue that you might have. Thanks for your feedback!

**Closed as completed by memsharded** 2024-09-24 22:33 UTC
Labels: answered
