### ISSUE TITLE
[bug]: conan 1.x: generate() is not called when conan build is invoked

### ISSUE THREAD

**Issue by MichalCermakx** [conan-io/conan#16238] opened 2024-05-10 22:49 UTC
### Describe the bug

Hi,

I know Conan 1 is legacy, but I have not migrated to it, because I need some missing features - for example https://github.com/conan-io/conan/issues/15840.
I am using the most recent version of 1.x line - 1.64.0 and trying to use the code that works in both 1.x and 2.x.

Recently, I found, that when I call standalone commands (conan install, conan build, conan create), there is a different behavior related to generate() method.
In 2.x, generate is called in all 3 cases. In 1.x **conan build does not** call generate().

Conan2 callstack:
![image](https://github.com/conan-io/conan/assets/67799654/7979eee0-ddef-4f08-bbfe-8407d5373058)
Conan1.64 callstack - it does not break in generate method, but goes directly to build:
![image](https://github.com/conan-io/conan/assets/67799654/24b153c3-c9e3-44ec-ab64-f9603eeddb75)

Is there a CLI switch that would push Conan to call generate? Or some other way?

**Comment by memsharded** [comment] 2024-05-11 00:04
Hi @MichalCermakx 

Thanks for your report.

This is not a bug, this was totally by design in Conan 1.X. ``conan build`` doesn't call install or generate at all.
If you want to call ``generate()``, you need to call ``conan install`` before the ``conan build``, and that will call ``generate()``.

**Comment by MichalCermakx** [comment] 2024-05-11 01:36
Thank you James for the answer.

I might be abusing generate() for activities it is not intended for. I understand, it should be doing preparation before the build, which typically results in artifacts on disk. But I am collecting information about dependency packages (Accessible only during generate()) and storing it into self Python variable. Therefore, calling install before will not help me.
Anyway, thank you for the answer, I understand Conan 1 is legacy, and will not get any major updates.

**Comment by memsharded** [comment] 2024-05-12 09:40
> Anyway, thank you for the answer, I understand Conan 1 is legacy, and will not get any major updates.

Yes, having ``conan build`` do a full graph computation, to be able to call ``generate()`` in Conan 2 was one of the many big changes that require a major breaking version, this was a very large change, impossible to do in Conan 1, not now because of the legacy, but it was already impossible to do before, because it would be too complex and most likely quite breaking.

> I might be abusing generate() for activities it is not intended for. I understand, it should be doing preparation before the build, which typically results in artifacts on disk. But I am collecting information about dependency packages (Accessible only during generate()) and storing it into self Python variable. 

Yes, the way it is intended to work (and I think even documented) is to store that information in files, and have ``build()`` method to read those files if necessary. No state should be transferred via Python variables among those methods.

> for example https://github.com/conan-io/conan/issues/15840.

Regarding the cache concurrency, it was not even very good in Conan 1.X, it was partly supported, but there were still issues. I think that even if you have to use separate caches for concurrent jobs, migrating to Conan 2 might be better. If you require packages directly from ConanCenter, please note that the updates for Conan1 packages there will be stopped in the following months.

I am closing this ticket as resolved, this was intended behavior, I think it was clarified. Do not hesitate to open new tickets for any further question, thanks for the feedback!

**Closed as completed by memsharded** 2024-05-12 09:40 UTC
Labels: type: question

**Comment by MichalCermakx** [comment] 2024-05-13 16:13
> > Anyway, thank you for the answer, I understand Conan 1 is legacy, and will not get any major updates.
> 
> Yes, having `conan build` do a full graph computation, to be able to call `generate()` in Conan 2 was one of the many big changes that require a major breaking version, this was a very large change, impossible to do in Conan 1, not now because of the legacy, but it was already impossible to do before, because it would be too complex and most likely quite breaking.

Understand. I can implement a workaround of dumping information I need (via pickle or yaml/json) into file during generate() and read this during the build(). Now, I know passing info via self-variable is impossible, and I am not missing anything.

> > I might be abusing generate() for activities it is not intended for. I understand, it should be doing preparation before the build, which typically results in artifacts on disk. But I am collecting information about dependency packages (Accessible only during generate()) and storing it into self Python variable.
> 
> Yes, the way it is intended to work (and I think even documented) is to store that information in files, and have `build()` method to read those files if necessary. No state should be transferred via Python variables among those methods.
> 
> > for example #15840.
> 
> Regarding the cache concurrency, it was not even very good in Conan 1.X, it was partly supported, but there were still issues. I think that even if you have to use separate caches for concurrent jobs, migrating to Conan 2 might be better. If you require packages directly from ConanCenter, please note that the updates for Conan1 packages there will be stopped in the following months.

The reason why I want this is, that I develop a simple GUI for my team members. It has "Install", "Build", "Cancel" buttons and a couple of other options for the configuration of a local build. This is hiding Conan CLI syntax from them. It is similar to GIT GUI clients. Not everybody likes the command line.
In our environment, developers can cancel conan during installation/downloading packages from Artifactory. Also, the Artifactory connection is not absolutely stable; sometimes we see a connection drop/connection full error. Even conan1 dirty cache mechanism might not be fully polished, I have only rarely seen a case when I would need to remove a package via CLI or face any other corrupted cache issue. With conan2, this is much more often.

> 
> I am closing this ticket as resolved, this was intended behavior, I think it was clarified. Do not hesitate to open new tickets for any further question, thanks for the feedback!

Thank you, I really appreciate your feedback!
