### ISSUE TITLE
[bug] Rendering error while importing Jinja profile templates that use one of the provided context module (detect_api, platform, os, ...)

### ISSUE THREAD

**Issue by todorico** [conan-io/conan#17426] opened 2024-12-06 09:04 UTC
### Describe the bug

Environment details:
OS: Windows
Conan Version: 2.10.1

**Profile: default.variables**
{% set arch = detect_api.detect_arch() %}
{% set build_type= "Release" %}
{% set os = detect_api.detect_os() %}

**Profile: default**
{% import "default.variables" as default %}

[settings]
arch={{ default.arch }}
build_type={{ default.build_type }}
os={{ default.os }}

Description:

When using `{% import "default.variables" as default %}` There is a Jinja rendering error if the imported `default.variables` use one of the provided python module (detect_api, platform, os, ...). In my case, the following error is printed using the command: `conan profile show`:

`ERROR: Error while rendering the profile template file 'C:\Dev\Tools\Conan\profiles\default'. Check your Jinja2 syntax: 'detect_api' is undefined`

### How to reproduce it

Just use my profiles and run `conan profile show`

**Comment by memsharded** [comment] 2024-12-08 21:30
Hi @todorico 

Thanks for your report.

I'd say that you are missing the ``with context`` specifier in your template, please check https://jinja.palletsprojects.com/en/stable/templates/#import-context-behavior

**Comment by todorico** [comment] 2024-12-09 06:46
Hi @memsharded,

You are perfectly right! Thank you for pointing out that specific paragraph in the friendly manual! 😄 

I was surprised to learn that the context was not automatically propagated between profiles. Do you think it would be helpful to include this clarification in the Conan documentation?

**Comment by memsharded** [comment] 2024-12-09 09:50
> I was surprised to learn that the context was not automatically propagated between profiles. Do you think it would be helpful to include this clarification in the Conan documentation?

Probably too much, we could keep expanding the Conan docs to cover all jinja documentation! 😅 
As this is a pure jinja thing, I think it is fine as-is, covered by the jinja docs.

I'd say that we can close this ticket as not a bug, isn't it? Thanks for the feedback.

**Comment by todorico** [comment] 2024-12-09 10:04
That works for me. Thank you for your response!

**Closed as completed** 2024-12-09 10:05 UTC
Labels: type: question, answered
