### ISSUE TITLE
[question] set_property(deplib,cmake_build_modules,xxx) using in CMakeDeps

### ISSUE THREAD

**Issue by hiiizxf** [conan-io/conan#14429] opened 2023-08-05 08:52 UTC
### What is your question?

Hi, I have question regarding
When I using dep.set_property(deplib,cmake_build_modules,xxx) in CMakeDeps, the deplib_BUILD_MODULES_PATHS_DEBUG is still None(cpp_info of of deplib's recipe had not  set_property(cmake_build_modules,xxx). 
Is dep.set_property(deplib,cmake_build_modules,xxx) in CMakeDeps not support?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-08-07 10:50
Hi @hiiizxf 

Yes, in theory all properties are supported and can be overriden by the consumer side ``CMakeDeps``.
Note, however that using the raw variables is not supported, those are internal implementation details. The generated target is what should be used, and the modules should be injected in the cmake paths to be found or directly included for usage, no need to really inspect the variables. I guess that you are reporting it as a sympton/investigation of why it is failing, but not trying to use it directly.

One of the reasons why the _DEBUG variable is empty is because you are installing with ``Release`` build type. The variables match the build type of the consumer, not the build type of the dependency.

**Comment by hiiizxf** [comment] 2023-08-07 11:21
Thank you for your reply.
I‘ve tryed to use it decrity. Because there is several libs that my target rely on, who's cpp_info contain 'cpp_info.build_modules["cmake_find_package"] 'but not 'cpp_info.set_property("cmake_build_modules", [“cmake config file path”])'. Also I'm trying to figure out why it is failing, when I learn this section: https://docs.conan.io/1/reference/conanfile/tools/cmake/cmakedeps.html#set-property 
Now I've added 'cpp_info.set_property("cmake_build_modules"' to these libs now.

**Comment by memsharded** [comment] 2023-08-07 12:28
``cpp_info.build_modules["cmake_find_package"]`` is deprecated and 1.X only. Which Conan version are you using?  Please always provide the Conan version when reporting.

**Comment by hiiizxf** [comment] 2023-08-08 01:40
I'm using conan v1.56.0.

**Comment by memsharded** [comment] 2023-08-08 08:22
I think that the consumer CMakeDeps ``.set_property`` should also work.
If you have already added it in the dependencies recipes, I guess it is no longer an issue, and this ticket can be closed, please close it.

If you would still like to see this fixed, please provide more details with something (conanfile.py recipes, minimal) that we can reproduce.

Many thanks!

**Closed as completed** 2023-08-08 09:48 UTC
Labels: stage: triaging
