### ISSUE TITLE
[feature] Support CMake OBJECT libraries

### ISSUE THREAD

**Issue by bemehiser** [conan-io/conan#9438] opened 2021-08-17 15:31 UTC
Add `cmake_find_package` and `cmake_find_package_multi` support for CMake `OBJECT` libraries.

CMake allows the creation of [`OBJECT` libraries](https://cmake.org/cmake/help/latest/command/add_library.html#object-libraries) (as contrasting with `STATIC` and `SHARED`). These `OBJECT` libraries consist of a lot of compiled object files which haven't been linked into a library or binary.

```
add_library(example_obj_lib OBJECT
        include/alib.h
        src/alib.c)

target_include_directories(example_obj_lib
        PUBLIC
        include)
```

These libraries can then be linked into other libraries directly without needing to recompile the objects. This is particularly useful when creating SDK libraries, where multiple libraries' objects' symbols can be combined into a single static library, so a single library binary can be passed to other developers with all relevant symbols.

```
add_library(example_sdk STATIC
        $<TARGET_OBJECTS:example_obj_lib>
        include/example.h
        src/example.c)

target_link_libraries(example_sdk
        PUBLIC
        include
       $<TARGET_PROPERTY:example_obj_lib,INTERFACE_INCLUDE_DIRECTORIES>)
```

As a developer of both `example_obj_lib` and `example_sdk`, I would like to be able to package `example_obj_lib` `OBJECT` libraries via Conan, and generate CMake Find scripts with those `OBJECT` libraries in my `example_sdk project`.

- [*] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-08-19 22:49
I don't think this is a specific CMake object libraries, but it seems this would be a duplicate of this one: https://github.com/conan-io/conan/issues/5159 (and related to https://github.com/conan-io/conan/issues/8703), and what needs to be done is:
- To explicitly model "objects" in packages, besides "libs" and "exes"
- To make build helpers and generators to handle this information for consumers.

Can we close this one as duplicate and track it in https://github.com/conan-io/conan/issues/5159?

**Comment by memsharded** [comment] 2023-03-15 23:06
``CMakeDeps`` added support for this long time ago, closing.

**Closed as completed by memsharded** 2023-03-15 23:06 UTC
Labels: stage: triaging
