### ISSUE TITLE
[bug] Conan search fails to use queries and wildcards

### ISSUE THREAD

**Issue by jperezminguez** [conan-io/conan#6171] opened 2019-12-02 14:11 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Debian GNU/Linux 9
  * Compiler+version:
  * Conan version: Client 1.20.0 + Artifactory
  * Python version: 3.5.3

### Steps to reproduce (Include if Applicable)

- Implement a package (for example myfw) 
- Add an option (for example configA)
- Optionally you can create another one for config=configB
- Create a package for the channel myProject
- Upload packages to the remote server (remote-server in the example)
- Execute the following conan search:
conan search "myfw/*@myProject/*" -q'config=configA'  -r remote-server

- Error happens and message shown:
ERROR: -q parameter only allowed with a valid recipe reference as search
pattern. e.g. conan search MyPackage/1.2@user/channel -q "os=Windows"

**Comment by memsharded** [comment] 2019-12-02 14:34
Hi @jperezminguez 

This doesn't seem a bug, the error message is reporting the behavior. The query argument is to search for binaries of a given package reference. You cannot search at the same time with wildcards, which is a search for recipe references, and use the query which is specific for binaries of a given recipe. So this is totally intended behavior. The main reason for this behavior is that the query argument is already heavy for a single reference, there is no way it can scale in a reasonable way for multiple references.

**Comment by jperezminguez** [comment] 2019-12-02 15:47
Well, if I can get a proper list with the client version 1.7.4 but with the client 1.20.X it triggers an error, seems reasonable to think this is a bug

**Comment by memsharded** [comment] 2019-12-02 23:47
The error message was introduced because that command was already broken in 1.7.4, but it silently ignored erroneous and non-sense input:

```bash
conan search zlib/1.2.11@conan/* -r=conan-center -q="os="Random""
Existing package recipes:

zlib/1.2.11@conan/stable
```
Conan was never able to perform a query over wildcard references, the fact that it was possible to input a random string and Conan didn't error was the real bug. That was fixed and now a clear error message is given.

**Comment by jperezminguez** [comment] 2019-12-03 11:31
OK. I get it. Thanks!

**Comment by memsharded** [comment] 2019-12-03 11:41
Great. If this is not a bug then, I am going to change the title and close it as solved.
Do not hesitate to open more issues for further questions or reports. Thanks!

**Closed by memsharded** 2019-12-03 11:41 UTC
Labels: stage: triaging
