### ISSUE TITLE
ConanException: Error 255 while executing perl ./Configure "conan-Release-Linux-armv8-gcc-11" no-shared --prefix=/ --openssldir="/etc/ssl" no-unit-test threads PERL=perl no-tests --release --libdir=lib -fPIC no-md2

### ISSUE THREAD

**Issue by way4sahil** [conan-io/conan#16063] opened 2024-04-10 14:42 UTC
### Describe the bug

conan install openssl/1.1.1t@ --build=missing -pr=rededger_owa5x

Configuration:

[settings]

arch=armv8

arch_build=x86_64

build_type=Release

compiler=gcc

compiler.libcxx=libstdc++11

compiler.version=11

os=Linux

os_build=Linux

[options]

openssl:shared=False

qt:gui=False

qt:qtwebsockets=True

qt:shared=True

qt:widgets=False

qt:with_icu=False

qt:with_mysql=False

qt:with_sqlite3=False

[build_requires]

*: toolchain-aarch64-rededgers/3.0

[env]

PERL=/usr/bin/perl

PERL5LIB=/usr/lib/x86_64-linux-gnu/perl/5.34.0:/usr/lib/x86_64-linux-gnu/perl-base

openssl:CROSS_COMPILE=

[buildenv]

target=OWA5X

openssl:CROSS_COMPILE=""

openssl/1.1.1t: Applying build-requirement: toolchain-aarch64-rededgers/3.0

openssl/1.1.1t: Copying sources to build folder

openssl/1.1.1t: Building your package in /home/ihn8kor/.conan/data/openssl/1.1.1t/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b

openssl/1.1.1t: Generator txt created conanbuildinfo.txt

openssl/1.1.1t: Calling generate()

openssl/1.1.1t: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior

openssl/1.1.1t: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior

openssl/1.1.1t: Aggregating env generators

openssl/1.1.1t: Calling build()

openssl/1.1.1t: Apply patch (portability): TVOS and WatchOS don't like fork()

openssl/1.1.1t: gen_info = {'CFLAGS': ['-fPIC', '-O3'], 'CXXFLAGS': ['-fPIC', '-O3'], 'DEFINES': ['NDEBUG'], 'LDFLAGS': []}

openssl/1.1.1t: using target: conan-Release-Linux-armv8-gcc-11 -> linux-aarch64

openssl/1.1.1t: my %targets = (

    "conan-Release-Linux-armv8-gcc-11" => {

        inherit_from => [ "linux-aarch64" ],

        cflags => add("-fPIC -O3"),

        cxxflags => add("-fPIC -O3"),

        defines => add(["NDEBUG"]),

        includes => add(),

        lflags => add(""),

        

        

        

        cc => "aarch64-fslc-linux-gcc  -mcpu=cortex-a53 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/ihn8kor/.conan/data/toolchain-aarch64-rededgers/3.0/_/_/toolchain/sysroots/cortexa53-fslc-linux",

        cxx => "aarch64-fslc-linux-g++  -mcpu=cortex-a53 -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/ihn8kor/.conan/data/toolchain-aarch64-rededgers/3.0/_/_/toolchain/sysroots/cortexa53-fslc-linux",

        ar => "aarch64-fslc-linux-ar",

        ranlib => "aarch64-fslc-linux-ranlib",

        

    },

);

openssl/1.1.1t: ['"conan-Release-Linux-armv8-gcc-11"', 'no-shared', '--prefix=/', '--openssldir="/etc/ssl"', 'no-unit-test', 'threads', 'PERL=perl', 'no-tests', '--release', '--libdir=lib', '-fPIC', 'no-md2']

./Configure: Perl lib version (5.34.0) doesn't match executable '/home/ihn8kor/.conan/data/toolchain-aarch64-rededgers/3.0/_/_/toolchain/sysroots/x86_64-fslcsdk-linux/usr/bin/perl.real' version (5.34.1) at /usr/lib/x86_64-linux-gnu/perl/5.34.0/Config.pm line 62.

Compilation failed in require at ./Configure line 14.

BEGIN failed--compilation aborted at ./Configure line 14.

openssl/1.1.1t: 

openssl/1.1.1t: ERROR: Package '115c8fa606e08a868a5ec8073c26c1a096c7263b' build failed

openssl/1.1.1t: WARN: Build folder /home/ihn8kor/.conan/data/openssl/1.1.1t/_/_/build/115c8fa606e08a868a5ec8073c26c1a096c7263b/build-release

ERROR: openssl/1.1.1t: Error in build() method, line 723

	self.run(f'{self._perl} ./Configure {args}')

	ConanException: Error 255 while executing perl ./Configure "conan-Release-Linux-armv8-gcc-11" no-shared --prefix=/ --openssldir="/etc/ssl" no-unit-test threads PERL=perl no-tests --release --libdir=lib -fPIC no-md2

**Comment by memsharded** [comment] 2024-04-10 15:34
Hi @way4sahil 

Thanks for your report.

It seems you are cross-building, isn't it?
If you are cross building you should be using the 2 profiles approach, please check: https://docs.conan.io/2/tutorial/consuming_packages/cross_building_with_conan.html (this is COnan 2 docs, but same build/host profiles approach is recommended for Conan 1 cross-builds)

Also, for reporting an issue against the Conan client, it is recommended to:

- First try your setup with a simple project, like ``conan new template``. This is because it could be a specific COnanCenter recipe issue, not a Conan issue. Using a simple project to reproduce helps.
- Use first native builds, to make sure things are aligned. 
- Then move to cross-build, make sure to fully specify both profiles.

It is also strongly recommended at least to use the latest Conan 1.64 version, please make sure to report your Conan version too.

**Comment by memsharded** [comment] 2024-07-26 16:30
I am closing this ticket as staled and not followed up.
Please re-open or create new tickets for any further question, thanks!

**Closed as not planned by memsharded** 2024-07-26 16:30 UTC
