### ISSUE TITLE
[bug] The root path is applied twice for editable packages

### ISSUE THREAD

**Issue by fredizzimo** [conan-io/conan#14079] opened 2023-06-13 12:24 UTC
### Environment details

Conan release/2.0 branch

### Steps to reproduce

https://github.com/conan-io/conan/pull/13983 tries to fix editable packages with a root. But the fix does not quite work, since root is applied twice for the main node.

This can be seen by changing the test to
```python
def test_editable_folders_root():
    """ Editables with self.folders.root = ".." should work too
    """
    c = TestClient()
    sub1 = textwrap.dedent("""
        from conan import ConanFile

        class Pkg(ConanFile):
            name = "pkg"
            version = "0.1"
            def layout(self):
                self.folders.root = ".."
                self.folders.build = "mybuild"
                self.cpp.build.libdirs = ["mylibdir"]

            def generate(self):
                self.output.info(f"PKG source_folder {self.source_folder}")
        """)
    sub2 = textwrap.dedent("""
        from conan import ConanFile

        class Pkg(ConanFile):
            requires = "pkg/0.1"
            def generate(self):
                pkg_libdir = self.dependencies["pkg"].cpp_info.libdir
                self.output.info(f"PKG LIBDIR {pkg_libdir}")
        """)
    c.save({"sub1/conanfile.py": sub1,
            "sub2/conanfile.py": sub2})
    c.run("editable add sub1")
    c.run("install sub2")
    libdir = os.path.join(c.current_folder, "mybuild", "mylibdir")
    assert f"conanfile.py: PKG LIBDIR {libdir}" in c.out
    assert f"conanfile.py: PKG source_folder {c.current_folder}" in c.out
```
The source folder becomes the parent of `c.current_folder` and the test fails. 

The same thing can be observed when changing root to `root` for example, then all the paths gets `root/root` instead of just `root`

Here's the explanation of what happens:

https://github.com/conan-io/conan/blob/4f97fead0961fb1725c13dacbf2b2a70be5fb964/conans/client/installer.py#L349 calls `set_base_folders`, which already sets the root as can be seen here https://github.com/conan-io/conan/blob/4f97fead0961fb1725c13dacbf2b2a70be5fb964/conans/model/layout.py#L77-L78, so it gets applied twice.

When I was trying to fix the bug before I saw the fix in https://github.com/conan-io/conan/pull/1398 I just commented out the following lines (I have no idea why they would need to be there, and they caused the root to be set back to the wrong value)
https://github.com/conan-io/conan/blob/4f97fead0961fb1725c13dacbf2b2a70be5fb964/conans/client/installer.py#L362-L365

Another thing that seems to work is to move https://github.com/conan-io/conan/blob/4f97fead0961fb1725c13dacbf2b2a70be5fb964/conans/client/installer.py#L347-L348 down below the `set_base_folders` call.

But I wonder if that's really correct, should the root really be the same for all the nodes? I don't know the codebase and the Conan internals well enough to answer that.

**Comment by AbrilRBS** [comment] 2023-06-16 15:09
Hi @fredizzimo thanks a lot for your report, we appreciate it (Doing such a good investigation on your part proved extremely useful in tracking the issue down too 🫶)

You were spot on with the root cause too! I have simplified the code a bit and will add some more tests to this section before merging :)

**Comment by memsharded** [comment] 2023-06-19 16:03
Closed by https://github.com/conan-io/conan/pull/14109, will be in 2.0.7 soon, thanks again for reporting!

**Closed as completed** 2023-06-19 16:03 UTC
Labels: type: bug
