### ISSUE TITLE
[question] Failure to install when cached package "does not belong"

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan#7310] opened 2020-07-03 18:43 UTC
I am trying to understand the failure that occurred in my CI pipeline. zlib recipe was out of data and removed but conan did not attempt to download the new copy.

Is this the expected behavior? 

- zlib/1.2.11: WARN: The package zlib/1.2.11:8cf01e2f50fcd6b63525e70584df0326550364e1 doesn"t belong to the installed recipe revision, removing folder
- zlib/1.2.11:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache
- zlib/1.2.11: Already installed!
- FileNotFoundError: [WinError 2] The system cannot find the file specified: "C:\\Users\\chris\\.conan\\data\\zlib\\1.2.11\\_\\_\\package\\8cf01e2f50fcd6b63525e70584df0326550364e1"

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

```
"C:\Program Files\Conan\Conan/conan.exe" install .. -s build_type=Debug -s arch=x86_64 
    Configuration:
    [settings]
    arch=x86_64
    build_type=Debug
    compiler=Visual Studio
    compiler.runtime=MDd
    compiler.version=15
    os=Windows
    os_build=Windows
    [options]
    [build_requires]
    [env]
    
    WARN: restinio/0.6.8: requirement fmt/6.2.1 overridden by your conanfile to fmt/6.2.1 
    WARN: restinio/0.6.8: requirement boost/1.73.0 overridden by your conanfile to boost/1.72.0 
    WARN: restinio/0.6.8: requirement openssl/1.1.1g overridden by your conanfile to openssl/1.1.1g 
    WARN: cpprestsdk/2.10.16: requirement openssl/1.1.1g overridden by your conanfile to openssl/1.1.1g 
    WARN: cpprestsdk/2.10.16: requirement boost/1.72.0 overridden by your conanfile to boost/1.72.0 
    WARN: websocketpp/0.8.2: requirement openssl/1.1.1g overridden by cpprestsdk/2.10.16 to openssl/1.1.1g 
    WARN: websocketpp/0.8.2: requirement boost/1.72.0 overridden by cpprestsdk/2.10.16 to boost/1.72.0 
    WARN: spdlog/1.6.1: requirement fmt/6.2.0 overridden by your conanfile to fmt/6.2.1 
    WARN: jwt-cpp/0.4.0: requirement openssl/1.1.1g overridden by your conanfile to openssl/1.1.1g 
    zlib/1.2.11: WARN: The package zlib/1.2.11:8cf01e2f50fcd6b63525e70584df0326550364e1 doesn"t belong to the installed recipe revision, removing folder
    conanfile.txt: Installing package
    Requirements
        boost/1.72.0 from "conan" - Cache
        bzip2/1.0.8 from "conan" - Cache
        catch2/2.12.2 from "conan" - Cache
        cpprestsdk/2.10.16 from "conan" - Cache
        expected-lite/0.4.0 from "conan" - Cache
        fmt/6.2.1 from "conan" - Cache
        http_parser/2.9.4 from "conan" - Cache
        jwt-cpp/0.4.0 from "conan" - Cache
        openssl/1.1.1g from "conan" - Cache
        optional-lite/3.2.0 from "conan" - Cache
        picojson/1.3.0 from "conan" - Cache
        rapidjson/cci.20200410 from "conan" - Cache
        restinio/0.6.8 from "conan" - Cache
        spdlog/1.6.1 from "conan" - Cache
        string-view-lite/1.3.0 from "conan" - Cache
        variant-lite/1.2.2 from "conan" - Cache
        websocketpp/0.8.2 from "conan" - Cache
        zlib/1.2.11 from "conan" - Cache
    Packages
        boost/1.72.0:bd64070aa46efcf1bcda1ffb7171f017d4104661 - Cache
        bzip2/1.0.8:5c382ca84120276840c8074ab1851697636fb8ae - Cache
        catch2/2.12.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        cpprestsdk/2.10.16:8f0fae4fa79d3b017d6385ce0aa833f2959903df - Cache
        expected-lite/0.4.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        fmt/6.2.1:8cf01e2f50fcd6b63525e70584df0326550364e1 - Download
        http_parser/2.9.4:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache
        jwt-cpp/0.4.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        openssl/1.1.1g:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache
        optional-lite/3.2.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        picojson/1.3.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        rapidjson/cci.20200410:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        restinio/0.6.8:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        spdlog/1.6.1:c050e480af3d7cbf81418c9d89b0421477687f7a - Download
        string-view-lite/1.3.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        variant-lite/1.2.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        websocketpp/0.8.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
        zlib/1.2.11:8cf01e2f50fcd6b63525e70584df0326550364e1 - Cache
    
    Cross-build from "Windows:None" to "Windows:x86_64"
    bzip2/1.0.8: Already installed!
    catch2/2.12.2: Already installed!
    expected-lite/0.4.0: Already installed!
    fmt/6.2.1: Retrieving package 8cf01e2f50fcd6b63525e70584df0326550364e1 from remote "conan" 
    Downloading conanmanifest.txt
    Downloading conaninfo.txt
    Downloading conan_package.tgz
    fmt/6.2.1: Package installed 8cf01e2f50fcd6b63525e70584df0326550364e1
    fmt/6.2.1: Downloaded package revision 0e117ad001cae260d8d248d0bdc6d1be
    http_parser/2.9.4: Already installed!
    openssl/1.1.1g: Already installed!
    optional-lite/3.2.0: Already installed!
    picojson/1.3.0: Already installed!
    rapidjson/cci.20200410: Already installed!
    string-view-lite/1.3.0: Already installed!
    variant-lite/1.2.2: Already installed!
    zlib/1.2.11: Already installed!
    Traceback (most recent call last):
      File "conan\conans\client\command.py", line 1969, in run
      File "conan\conans\client\command.py", line 482, in install
      File "conan\conans\client\conan_api.py", line 81, in wrapper
      File "conan\conans\client\conan_api.py", line 564, in install
      File "conan\conans\client\manager.py", line 68, in deps_install
      File "conan\conans\client\installer.py", line 308, in install
      File "conan\conans\client\installer.py", line 332, in _build
      File "conan\conans\client\installer.py", line 426, in _handle_node_cache
      File "conan\conans\client\installer.py", line 485, in _call_package_info
      File "contextlib.py", line 81, in __enter__
      File "conan\conans\client\tools\files.py", line 25, in chdir
    FileNotFoundError: [WinError 2] The system cannot find the file specified: "C:\\Users\\chris\\.conan\\data\\zlib\\1.2.11\\_\\_\\package\\8cf01e2f50fcd6b63525e70584df0326550364e1"
    
    ERROR: [WinError 2] The system cannot find the file specified: "C:\\Users\\chris\\.conan\\data\\zlib\\1.2.11\\_\\_\\package\\8cf01e2f50fcd6b63525e70584df0326550364e1"
```

**Comment by memsharded** [comment] 2020-07-05 22:52
Hi @prince-chrismc 

I have been trying to reproduce this, but no success. Whenever the package folder is removed, it is marked as ``missing`` or is retrieved from the server. A couple of questions:

- Which Conan version are you running?
- Is it possible that you have mixed using revisions and not using revisions? If you start using revisions, maybe you want to clear the cache first.

If you could provide some more context, something that we could reproduce here, that would help a lot. Thanks!

**Comment by prince-chrismc** [comment] 2020-07-06 12:09
This has happened once to my knowledge after 1000s of builds. 

> * Which Conan version are you running?

1.22 ( which may be apart of the problem ) However updating the production build images is still an uphill battle :pray: 

Our first deployment was using revisions. It was a hard requirement since packages being uploaded to CCI have a delay... Not that our version is far behind there's recipes we do not support.

Typically I would have assumed it was a antivirus problem but since the client actually logged what it was trying to do it seems very odd.

**Comment by memsharded** [comment] 2020-07-06 12:41
Ok, thanks for the feedback @prince-chrismc 

I have tried moving my tests to reproduce to 1.22 release, but still seems to be working ok there too. 

What I have been checking is the source code flows, trying to imagine scenarios. It is possible that if after a ``shutil.rmtree()`` of a directory, if the immediate ``os.path.exists()`` of that directory returns true, because of the OS handling the resource still open or something like that, the above could happen. Is the only possibility I can see so far.

If that was it, at the moment it seems this would be very challenging to reproduce, and it might be unlikely that it will happen again. Maybe knowing your python version could help. I am considering making it explicit in the code, but not sure if the effort is really worth.

**Comment by prince-chrismc** [comment] 2020-07-06 14:15
> Maybe knowing your python version could help. I am considering making it explicit in the code, but not sure if the effort is really worth.

This is using the MSI installer, I am not sure what version that would be built with.

> What I have been checking is the source code flows, trying to imagine scenarios.

I looks like its the install that may have an issue, When a corrupted package is detected ( perhaps in the `--update` sequence ) it's not correctly replaced. This sounds like a fairly uncommon path so perhaps that where this issue comes from?

**Comment by memsharded** [comment] 2020-07-06 15:01
> I looks like its the install that may have an issue, When a corrupted package is detected ( perhaps in the --update sequence ) it's not correctly replaced. This sounds like a fairly uncommon path so perhaps that where this issue comes from?

Yes, I managed to fire the case that "package doesn't belong to revision" with that flow, with the install with ``--update``. 

This seems related: https://stackoverflow.com/questions/49809471/overwrite-directory-with-shutil-rmtree-and-os-mkdir-sometimes-gives-access-is-d

**Comment by memsharded** [comment] 2020-07-06 16:55
Some progress. I have made this to fail in Windows:

```python
mydir = tempfile.mkdtemp(suffix='conans')
d = os.path.join(mydir, "tmp")
while True:
    assert not os.path.exists(d)
    os.mkdir(d)
    for f in range(10):
        with open(os.path.join(d, "file%s.txt" % f), "w+") as f:
            f.write("Some long contents "* 1000)
    rmdir(d)
    assert not os.path.exists(d)
```

I launch the script then launch an antivirus scan of the temp folder and it fails in one of the ``assert not os.path.exists(d)``
This Windows is very annoying. Lets think about what can be done to minimize this.

**Comment by memsharded** [comment] 2020-07-06 16:59
This issue is connected to:
- https://github.com/conan-io/conan/issues/2593
- https://github.com/conan-io/conan/pull/5639

**Comment by prince-chrismc** [comment] 2020-07-06 19:31
> I launch the script then launch an antivirus scan of the temp folder and it fails in one of the `assert not os.path.exists(d)`
> This Windows is very annoying. Lets think about what can be done to minimize this.

This is a nightmare on windows... We solved the issue with a retry, our discussion ended with "keep it stupidly simple" there's no new bugs that seem to stem from this issue.

Thank you for looking into the issue :smile:

**Comment by memsharded** [comment] 2020-07-06 22:46
Routine question, just to double check: Are you sure you have excluded your cache folder ''C:\\Users\\chris\\.conan'' both from the Antivirus and the Windows search indexer ``Windows Search Settings``?

**Comment by prince-chrismc** [comment] 2020-07-07 04:49
I had never heard of the windows search indexer, I saw it in the issues you linked and shared it with my team to investigate. The anti-virus sadly is cooperate wide and we do not have control over it so it's safe to safe it can grab files in the cache

**Comment by memsharded** [comment] 2024-01-23 10:00
Closing as inactive

**Closed as not planned by memsharded** 2024-01-23 10:00 UTC
Labels: type: bug, type: look into, stage: triaging
