### ISSUE TITLE
[question] Can you install the pc files in a different directory other than the builddir?

### ISSUE THREAD

**Issue by Makogan** [conan-io/conan#9496] opened 2021-08-29 04:24 UTC
When following the guides on conan as is, all .pc files will be created in the same directory where the main executable lives.
If a project has a large number of dependencies you end up with dozens of pc files and it becomes challenging for a human to quickly see what is on the directory. 

This is important for debugging and for using tools such as renderdoc where one may want to look for a specific file using a UI.

Is it possible to instruct conan to separate pc files form the executable's builddir?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-08-29 20:42
Hi @Makogan 

Yes, with the new ``layout()`` functionality, and the ``self.folders.generators`` (https://docs.conan.io/en/latest/developing_packages/package_layout.html#self-folders), you can define where the generated files will be located.

Just beware that legacy build system integrations will not directly understand this layout and might need some manual adaption, only the new integrations in ``conan.tools`` will use the layout automatically: https://docs.conan.io/en/latest/reference/conanfile/tools.html

**Comment by Makogan** [comment] 2021-08-30 03:25
Hello,

Thank you for your reply, I am still a bit lost.

From the documentation is seems it should be enough to add the following to the conan.py file:

```
def layout(self):
        self.folders.build = "cmake-build-{}".format(str(self.settings.build_type).lower())
        self.folders.generators = os.path.join(self.folders.build, "generators")
        self.folders.imports = self.folders.build
        self.folders.source = "src"
```

And then run:

`conan install . -if=my_install -s build_type=Debug`

The docs say:

> This will write the toolchains and generator files from the dependencies to the ``cmake-build-debug/generators``

From that I would expect a `cmake-build-debug` to be generated either on the project root or under my_install and then inside of its `generators` subfolder, all the pc files. But what I see is all the pc files under my_install and no `cmake-build-debug` directory. 

I am on conan 1.39 under linux and the docs say this feature is available from conan 1.37. Am I doing something wrong?

**Comment by memsharded** [comment] 2021-08-30 10:22
Hi @Makogan 

The ``-if=myinstall`` is a legacy from the previous mode, that is not possible to remove it yet, it is used to generate the ``conaninfo.txt`` and ``conanbuildinfo.txt`` that are needed for some local commands. But the new layouts ignore that argument. The reason is that if the layout now depends on an unknown, non-modelled command line argument, it is very difficult to achieve the reproducibility and portability of the layout.

Can you please make sure you are using the ``PkgConfigDeps`` generator? This is the modern one that should be following the layout and put the .pc files in the ``generators`` folder.

**Comment by Makogan** [comment] 2021-08-30 17:02
@memsharded How can I check which generator I am using? 

This is how I declared the generator:

`generators = "pkg_config"`

**Comment by memsharded** [comment] 2021-08-30 17:03
Yes, please use:

```python
generators = "PkgConfigDeps"
```

you can get more info in this reference page: https://docs.conan.io/en/latest/reference/conanfile/tools.html

**Comment by Makogan** [comment] 2021-08-30 17:29
Now I get this error:

```
ERROR: Error in generator 'PkgConfigDeps': {'ref': expat/unknown@unknown/unknown, 'build': False, 'direct': True, 'test': False}
```

I also tried changing things to use:
```
 def generate(self):
        pc = PkgConfigDeps(self)
        pc.generate()
```

Instead, but I get the same error.

**Comment by memsharded** [comment] 2021-08-30 17:35
Just to make sure, which Conan version are you using? 
Also, what kind of requirement is ``expat``, a regular ``requires``?

**Comment by Makogan** [comment] 2021-08-30 18:17
This is what I see in the terminal:
`Conan version 1.39.0`

expat is not explicitly required it might be a dependency of the explicit dependencies:

```
requires = [
        "libffi/3.4.2", # Not sure why but without this wayland causes a conflict.
        "wayland/1.19.0",
        "glfw/3.3.4",
        "shaderc/2019.0",
        "freetype/2.10.4",
        "harfbuzz/2.8.2",
        "vulkan-memory-allocator/2.3.0",
        "gtest/1.10.0",
        "benchmark/1.5.3",
        "tinygltf/2.5.0",
        "stb/20200203",
        "vulkan-headers/1.2.182",
        "vulkan-validationlayers/1.2.182",
    ]
```

**Comment by memsharded** [comment] 2021-08-31 11:31
Hi @Makogan 

Sorry for the confusion. I have realized this is working in our develop branch, but is a bug that is still existing in Conan 1.39 and is being fixed in Conan 1.40 (to be released next Monday most likely).

This is the PR that fixed it: https://github.com/conan-io/conan/pull/9341

**Comment by memsharded** [comment] 2021-08-31 11:42
Verified that this works with the layout() above and the new ``PkgConfigDeps`` in 1.40, so this can be closed as solved, keep tuned to the release.

Please do not hesitate to report or ask any other question you might have. Thanks!

**Closed as completed by memsharded** 2021-08-31 11:42 UTC
Labels: type: bug, type: question

**Comment by Makogan** [comment] 2021-08-31 19:22
Thank you very much James, I will check the feature out when the next version comes out.
