### ISSUE TITLE
tools.run_in_windows_bash(self, cmd, 'relative') does not run in cwd relative to build directory

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan#1940] opened 2017-10-25 15:31 UTC
When you are in `build()`, `self.run(cwd='relative')` runs in a cwd relative to the `build` directory, but `tools.run_in_windows_bash(self, cmd, 'relative')` runs in a cwd relative to the directory that you ran the `conan` command in.  Note: `tools.run_in_windows_bash(self, cmd)` _does_ run in the `build` directory.  It would be good for it to be consistent.

This was seen in Conan 0.27 and is somewhat related to #1281.

**Comment by lasote** [comment] 2017-11-20 10:53
Cannot reproduce the error, I've added a test and the current folder inside the `bash` is the build folder and the relative folder I've specified.
Which bash are you using? from mingw?

**Comment by lasote** [comment] 2017-12-01 14:16
PR #2047 updated, fixed and added test using path.

**Comment by memsharded** [comment] 2017-12-14 00:08
Released in 0.30, please upgrade, and report if necessary. Thanks!

**Closed by memsharded** 2017-12-14 00:08 UTC
Labels: bug, fixed
