### ISSUE TITLE
[question] Does Conan take any step regarding the 'compiler' setting with CMake helper

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#5930] opened 2019-10-17 13:13 UTC
We have a simple library, whose build is managed by CMake.

After adding a Conan test package, we are now observing surprising behaviours when calling `conan create -s compiler=clang` with a compiler setting that is not the value in the default profile (gcc):

```
CMake Error at build/22a957f739c44641d9703aa35ab1d4431991e8cf/conanbuildinfo.cmake:585 (message):
  Incorrect 'clang', is not the one detected by CMake: 'GNU'
```
Which raises the question: when providing a `compiler` setting, does the CMake build helper take any measure to use said compiler? If not, what is the best practice for the recipe implementers to forward this setting to the CMake helper?

**Comment by jgsogo** [comment] 2019-10-24 16:18
May we close this issue?

**Comment by Adnn** [comment] 2019-10-28 09:07
Yes, thank you for the concrete solutions and the pointer to the toolchain POC!
(Out of curiosity, do you plan a "toolchain introduction" in a blog-post or the doc? I must admit it feels I am missing some fondamentals when following discussions in #5737)

**Comment by jgsogo** [comment] 2019-10-28 10:35
Yes, sure, we will write about it and document the feature exhaustively. Anyway, we will be here to answer any doubt.

**Comment by Adnn** [comment] 2019-11-28 15:27
We have been giving this point a bit more thoughts, while revisiting the fundamentals of our Conan recipes.

As we understand the current situation, currently the compiler (as well as its version) are usual `settings` for most recipes, so they correctly change the resulting package `ID`. Yet, there is no canonical way to write a Conan recipe that will force CMake to use such compiler at the moment?

Since the recommended approach is to set environment variables in the profile, it means it becomes a responsibility of the recipe's consumers -not the implementer- to have these environment settings correctly set-up on its machine.

So, the following scenario is possible: a consumer could for example set the compiler setting to `clang`, thus retrieve a dependency built with clang from Conan center, and locally build another missing dependency, but CMake might very well built it with gcc and the final artifact is linked together with dependencies built on different compilers.

Is that correct?
If so, would not it be better for the recipe implementer to provide the `CMAKE_<LANG>_COMPILER` variables? (yet, it could probably not specify the actual compiler version...)

**Comment by jgsogo** [comment] 2019-11-28 17:24
The problem is trusting the recipe creator, the one providing the binaries. If a package ID matches the setting `gcc` then it should have been compiled with GCC. Same for the consumer, if the setting is `gcc` it should use GCC to compile. So the final artifact will have binaries built with the same compiler. This is what our build helpers do, they translate the settings into the proper compiler and flags... but the recipe implementer is free to write his own build helper or to tweak the `package_id` function.

What happens when you are not using a toolchain is that CMake detects a compiler based on the environment, and then Conan passes many variables from the command line (like the compiler) and, **if those don't match the error is raised, so the binary is not generated**, so there won't be a package compiled with GCC (detected by CMake) whose package ID corresponds to `clang` (used by Conan). That check is performed in the `conan_check_compiler` function that is called from `conan_basic_setup()`.

With the toolchain, CMake will use **the information in the toolchain for the detection too**, those _" -- Checking for working compiler...."_ in the CMake output will use the compiler declared in it.

Right now, as the toolchain and the cross-building PR are not ready yet, the _only way_ to do it with Conan is to use environment variables, it's up to **the profile to define a set of settings that matches the compiler and options in the environment variables**: they have to match, otherwise the consumer will get wrong binaries, or the consumer will use a wrong compiler when building.

**Comment by Adnn** [comment] 2019-11-29 09:11
Once again, thank you very much @jgsogo for the detailed and pragmatic explanations!

We did not realize some checks were actually in place via `conan_basic_setup`, because we are currently entirely relying on the [cmake_paths](https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_paths_generator.html) generator

**Comment by jgsogo** [comment] 2019-11-29 10:49
Thanks a lot! 😊 

With the effort in #5919 CMake integration in Conan should be easier to handle:
 * the toolchain will take care of the compiler, flags,...
 * the toolchain, via CMAKE_PROJECT_INCLUDE, will adjust some flags (like VS runtime)
 * the information about dependencies will be consumed using a generator like `find_package` or `find_package_multi`,... or even `cmake_paths` if you just want the paths.

Decoupling the settings from the dependencies will make it more clear.

**Comment by memsharded** [comment] 2023-12-22 00:43
This ticket was using the old generators (legacy in 1.X, removed in 2.0), that have been superseded some time ago by new ones. Closing as outdated, please check the new ones and don't hesitate to open new tickets as necessary for any further question.

**Closed by memsharded** 2023-12-22 00:43 UTC
Labels: type: question, stage: triaging
