### ISSUE TITLE
Conan upload command with a non-existing recipe will not produce an error/implying message

### ISSUE THREAD

**Issue by andreikom** [conan-io/conan#855] opened 2017-01-11 10:39 UTC
Try to use:

$ conan upload <nonExistentRecipeName> -r <remote>

No implying message will be returned.

Although using an existing recipe will upload the recipe correctly:

$ conan upload Pkg/0.1@username/stable -r <remote> --all

Uploading Pkg/0.1@username/stable
Uploading conanmanifest.txt
...

**Comment by memsharded** [comment] 2017-01-11 20:46
It is not a bug (it is a feature ;) , as the parameter is a pattern, it doesn't match any existing packages in the local cache, it does nothing. Just submitted the PR #857, as an enhancement over this behavior. Thanks very much for raising this issue.

**Comment by memsharded** [comment] 2017-01-31 15:07
Fixed and released in 0.19

**Closed by memsharded** 2017-01-31 15:07 UTC
Labels: enhancement, fixed
