### ISSUE TITLE
No Registry Entry and ARP Entry for Conan Package Manager 2.8.0

### ISSUE THREAD

**Issue by metaad** [conan-io/conan#17088] opened 2024-10-01 07:17 UTC
### Describe the bug

While installing Conan Package manager 2.8.0, files are getting installed in C:\Program Files\Conan. But no registry entry and Add & Remove Programs entry is observed.

![image](https://github.com/user-attachments/assets/7b4ed18d-da9d-4806-99b3-dbee0f90b938)

While Upgrading from 2.7.1 to 2.8.0, files are getting upgraded but Registry entry and Add & Remove Programs entry remains same as of 2.7.1

![image](https://github.com/user-attachments/assets/a1458836-99d5-44bb-91bf-3436c56fd6db)
![image](https://github.com/user-attachments/assets/1f40eb45-6dc9-410a-aca0-d583f13fc183)

Same behavior has been observed in 64 and 32 bit binary.

https://github.com/conan-io/conan/releases/download/2.8.0/conan-2.8.0-windows-x86_64-installer.exe
https://github.com/conan-io/conan/releases/download/2.8.0/conan-2.8.0-windows-i686-installer.exe

Environment Details - 

OS - Win 10  x64/x32 & Win 11 x64

### How to reproduce it

1. Install 

https://github.com/conan-io/conan/releases/download/2.8.0/conan-2.8.0-windows-x86_64-installer.exe
https://github.com/conan-io/conan/releases/download/2.8.0/conan-2.8.0-windows-i686-installer.exe

2. Go to Control Panel --> Add & Remove Programs and no entry for Conan Package manager 2.8.0

3. No entry in Registry Editor.

**Comment by czoido** [comment] 2024-10-01 07:29
Hi @metaad,
Thanks a lot for reporting, I'm afraid this is the result of the changes introduced to solve this: https://github.com/conan-io/conan/issues/16979
We will have a look and fix as soon as possible.

**Comment by czoido** [comment] 2024-10-01 12:08
Hi @metaad,
I have been checking and I think the problem is having the previous version installed and over it use the new installer. Could you please try to uninstall the old version first, then install 2.8.0 and check that it appears in the "Add or remove" programs?
Thanks a lot!

**Comment by metaad** [comment] 2024-10-01 12:15
Hi @czoido,

We have tried above scenario. 

While Uninstalling 2.7.1 and installing 2.8.0, Still no ARP as well as regitsry entry comes up.

Also, Installing 2.8.0 without any previous version installed, the same issue persists.

**Comment by czoido** [comment] 2024-10-01 12:40
Hi @metaad,
I have been doing several tests but I can't reproduce the issue. This is what I did:

- Install Conan 2.6.0, it appears in ARP
- Then install 2.8.0, It won't appear in ARP, and 2.6.0 is the one that appears, but it does appear in the registry (screenshot)
![image](https://github.com/user-attachments/assets/74e9b50c-4212-4576-8d64-415fe4aa5302)
- Uninstall 2.6.0, then is 2.8.0 the one that appears in ARP

So you can't even see the key in the registry after installing under the same conditions?

**Comment by metaad** [comment] 2024-10-03 03:25
Hi @czoido,

The registry entry you are getting is for a particular user.

We are installing the application for all users and not able to see any registry in HLKM Hive.

Reproducing the above mentioned scenario with 2.7.1 and 2.8.0, the registry entry we are getting is 

![image](https://github.com/user-attachments/assets/bc9b7a48-cd96-4b6f-a9a8-5e6aaef5489d)

Instead, we want it for 2.8.0 version as 2.8.0 is upgrading the files for 2.7.1 --> we want registry entry and ARP entry to be appeared for 2.8.0

**Comment by czoido** [comment] 2024-10-03 05:46
Hi @metaad,
Thanks for the info, now it makes sense. It's an issue related with permissions to modify the registry when you try to install for all users. We will try to fix that, thanks for the feedback.

**Comment by czoido** [comment] 2024-10-03 07:58
One question @metaad,
I assume that if you run the installer as administrator (which is equivalent to run as it used to run before 2.8.0) the issue does not happen any more and you can install and uninstall 2.8.0 version? (with previous 2.7.1 uninstall)

**Comment by metaad** [comment] 2024-10-03 08:43
Yes, we do not face any issue while running installer as administrator.

But we are installing application silently in system context with the command line - 

conan-2.8.0-windows-x86_64-installer.exe /SP- /VERYSILENT /NORESTART /SUPPRESSMSGBOXES 

We have been using same approach for previous releases as well and did not face anything like this.

**Comment by czoido** [comment] 2024-10-07 14:13
Hi @metaad,
I have made some changes for the installer generation that would allow overriding the default permissions adding the `/ALLUSERS` argument to your command line. That would be fixed in 2.9.0 or in a potential 2.8.1 that would go before that one.

**Comment by metaad** [comment] 2024-10-08 03:45
Thanks for assisting @czoido

**Comment by czoido** [comment] 2024-10-17 08:58
I am closing this as we are releasing today Conan 2.8.1 that includes the option to allow overriding the default permissions adding the `/ALLUSERS` argument to the command line.
Please @metaad ping us if you have any problems with it after releasing (it will be out in a couple of hours)

**Closed as completed by czoido** 2024-10-17 08:58 UTC
