### ISSUE TITLE
[bug] Reported versioning docs don't match behavior

### ISSUE THREAD

**Issue by zlacelle** [conan-io/conan#12065] opened 2022-09-08 13:24 UTC
Conan uses Python's node-semver to handle version ranges. In the [Conan docs for 1.52 (latest)](https://docs.conan.io/en/1.52/versioning/version_ranges.html#version-ranges), the following comment is made:
```
[>1.1 <2.1]                # In such range
[2.8]                      # equivalent to =2.8
[~3.0]                     # compatible, according to semver
[>1.1 || 0.8]              # conditions can be OR'ed
[1.2.7 || >=1.2.9 <2.0.0]  # This range would match the versions 1.2.7, 1.2.9, and 1.4.6, but not the versions 1.2.8 or 2.0.0.
```
According to [SEMVER 2.0](https://semver.org/), Major version changes are breaking, but Minor changes are compatible.

So, `[~3.0]` should match everything in the 3.x.x range (and `[~3.1.0]` would match everything >=3.1.0 but <4.0.0).

This is not what actually happens. What actually happens is that Tilde notation is "Major and Minor" match, and the undocumented-in-Conan Carat notation is "Major" match. I found this by going to the node-semver Github page here: [node-semver](https://github.com/isaacs/node-semver)

After much churning, I'd recommend that Conan update its docs to make it very clear how versioning works.

- Change the tilde docs to make it clear that ~ matches Major and Minor
- Add a carat doc showing that carat matches Major

### Environment Details (include every applicable attribute)
  * Ubuntu 22.04LTS
  * GCC 9.4
  * Conan 1.52.0
  * Python 3.8.10

### Steps to reproduce (Include if Applicable)

N/A

### Logs (Executed commands with output) (Include/Attach if Applicable)

N/A

**Comment by kambala-decapitator** [comment] 2022-10-15 11:08
this is a bug in https://github.com/podhmo/python-node-semver, at least in the version used by conan.

I found a workaround for this specific case `~1.1`: use `^1.1` instead.

`~1.1.0` works correctly though: matches only `1.1.x`. Btw `1.1.x` is also a valid range, and `1.x` is the same as `~1.0`.

**Comment by kambala-decapitator** [comment] 2022-10-15 11:21
or maybe "it's a feature, not a bug"... https://jubianchi.github.io/semver-check/#/~1.1/1.2

**Comment by AbrilRBS** [comment] 2023-12-24 00:15
This won't be changed in Conan 1, and Conan 2 has implemented a custom version solution to move away from relying on third party sources, closing as solved in v2, thanks a lot for your time :)

**Closed as not planned by AbrilRBS** 2023-12-24 00:15 UTC
