### ISSUE TITLE
[bug] CMake generator specifies wrong CONAN_LINK_RUNTIME

### ISSUE THREAD

**Issue by nick-schultz** [conan-io/conan#12858] opened 2023-01-06 02:24 UTC
### Environment details

* Operating System+version: Windows
* Compiler+version: msvc 19.28
* Conan version: 1.56

### Steps to reproduce

What is the correct way of using the compiler.runtime option  with `msvc`  and the CMake helper?

I can see that the `compiler.runtime` option is used verbatim as a compiler switch,  and `/dynamic` is not a msvc option.

build profile:
```
[settings]
os=Windows
arch=x86_64
compiler=msvc
compiler.runtime=dynamic
compiler.runtime_type=Release
compiler.version=192
compiler.cppstd=14
build_type=Release

[build_requires]
cmake/3.24.2
ninja/1.11.1

[env]
CMAKE_GENERATOR=Ninja
CMAKE_BUILD_TYPE=Release
```

build recipe:
```
    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.install()
```

in `conans/client/build/cmake_flags.py`, we can see that runtime is used verbatim.
```
def runtime_definition(runtime):
    return {runtime_definition_var_name: "/%s" % runtime} if runtime else {}
```

In the resulting generated build files:

CMakeCache.txt:
```
//No help, variable specified on the command line.
CONAN_LINK_RUNTIME:UNINITIALIZED=/dynamic
```

build.ninja
```
build foo.obj: CXX_COMPILER__foo_Release C$:\Users\nschultz\.conan\data\foo\2.21.1\_\_\build\aa0b2eec1220ffba6f90dea50c53c31cc623ec42\foo.cpp || cmake_object_order_depends_target_foolib
  DEFINES = ...
  FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc   /dynamic /O2 /Ob2 /DNDEBUG  -D_NOEXCEPT=noexcept -std:c++14
```

During the build,  I get the warning:
```
cl : Command line warning D9002 : ignoring unknown option '/dynamic'
```

## Workarounds

If I add `MD` to my `settings.yml` under `compiler/msvc/runtime`, and update my profile to use it,  then it works.

Alternatively, in my recipe, I can override the cmake definition:
```
    def __fixup_cmake_runtime(self, cmake):
        from conans.client.build.cmake_flags import runtime_definition_var_name 
        msvc_runtimes = {
            "dynamic:Debug": "/MDd",
            "dynamic:Release": "/MD",
            "static:Debug": "/MTd",
            "static:Release": "/MT"        
        }

        if self.settings.compiler == "msvc":
            cmake.definitions[runtime_definition_var_name] = msvc_runtimes[f"{self.settings.compiler.runtime}:{self.settings.compiler.runtime_type}"]
        

    def build(self):
        cmake = CMake(self)
        self.__fixup_cmake_runtime(cmake)
        cmake.configure()
        cmake.build()
        cmake.install()
```

However, this won't fix my build profile with other recipes.

**Comment by memsharded** [comment] 2023-01-07 21:23
Hi @nick-schultz 

Thanks for your question. I think this is not a bug, but expected behavior:

- The ``msvc`` new definition of compiler (instead of ``Visual Studio``), is implemented in the new generators, the ones ready for 2.0 (``from conan.tools.cmake import CMake, CMakeDeps, CMakeToolchain``
- That way of defining environment is legacy, and you should be using ``[buildenv]`` to work with the new generators.
Furthermore, the new generators like CMakeDeps do not listen to env-vars anymore, and instead they use new ``conf`` items. In that regard, it is totally expected that the new generators do not deinf CONAN_LINK_RUNTIME at all.
- ``from conans.client.build.cmake_flags import runtime_definition_var_name`` shouldn't be used
- It seems you are using the legacy ``from conans import CMake``, instead of the new ``from conan.tools.cmake import CMake`` one?

Please check:
- https://docs.conan.io/en/latest/reference/conanfile/tools.html
- https://docs.conan.io/en/latest/conan_v2.html

**Comment by Sil3ntStorm** [comment] 2023-01-19 20:43
So basically, if you use CCI recipes you're SOL if you want to use the new msvc style, which I am currently trying to use for its better compatibility with other compilers (e.g. clang / gcc) and to not have to do a bunch of special casing for Windows. At least until all the recipes one uses are transformed to 2.0 compat on CCI.
Guessing the only reason conan 1.x even knows about "msvc" and its options is so it doesn't trip when processing 2.0 ready recipes?

**Comment by memsharded** [comment] 2024-11-11 22:36
Closing this ticket as outdated/solved in Conan 2, that no longer use CONAN_LINK_RUNTIME.

Please create new tickets for any further question or issue against the latest Conan 2.X. Thanks for your feedback.

**Closed as completed by memsharded** 2024-11-11 22:36 UTC
Labels: stage: triaging
