### ISSUE TITLE
adding installed package to short_paths.conf not really possible

### ISSUE THREAD

**Issue by arnemertz** [conan-io/conan#379] opened 2016-07-21 15:52 UTC
Consider this example:

- I have Boost installed and built (or downloaded the binaries) in one or two configurations.
- I see that my `/home` partiton can't take all those GB any more
- I add Boost to `short_paths.conf`, e.g. at `/conan-boost` (with the needed access rights)

I now get missing directory errors trying to run `conan install`. It seems that Conan knows that I already have Boost but of course doesn't know where, because `short_paths.conf` is a lie.

To fix this I have to remove the entry in `short_paths.conf`, then `conan remove` Boost all those binaries, add the entry to `short_paths` again and build/download all those binaries again. This can take quite an amount of time, but it's still less work and less error prone than manually moving all that stuff to the new location, shortening the directory names etc.

**Feature request**: provide an option to _move_ packages. Preferred solution: add a new command, e.g.

    conan move Boost/1.60.0@lasote/stable /conan-boost

Adds the entry to `short_paths.conf`, moves the files, shortening the directory names etc.

**Comment by lasote** [comment] 2016-07-25 08:09
Thanks for notice the error. If it's a disk free space issue (and not an issue with short paths) I recommend you to move all the storage using the [storage] section in your conan.conf.

The short_paths feature has design for workaround the damn windows limitations with path length, but this feature has an opened issue, if you upload packages to a server it can't be retrieved because conan upload the packages with the shorted SHA. The problem is that it has no easy fix...

**Comment by memsharded** [comment] 2016-08-04 09:25
Conan 0.11 has been released with a new solution to the windows path length limit: http://docs.conan.io/en/latest/reference/conanfile.html#windows-path-length-limit

Just add short_paths=True to the conanfile.py.

The short_paths.conf is no longer used, so this issue should be gone. Please upgrade to conan 0.11 and re-open if necessary. Thank you!

**Closed by memsharded** 2016-08-04 09:25 UTC
Labels: bug, fixed

**Comment by Luisa456** [comment] 2016-09-13 04:46
Long Path Tool is the perfect utility that can solve all the long path issues. Download this software online.
