### ISSUE TITLE
[question] Conan 1.45.0 does not add root folders to `CMAKE_PREFIX_PATH`

### ISSUE THREAD

**Issue by KerstinKeller** [conan-io/conan#10648] opened 2022-02-23 17:58 UTC
I just read the following in the documentation for `CMakeToolchain`:

> 
> Note
> 
> In Conan 1.45 the CMakeToolchain doesn’t append the root package folder of the dependencies (declared in the cpp_info.builddirs) to the CMAKE_PREFIX_PATH variable. That interfered with the find_file, find_path and find_program, making, for example, impossible to locate only the executables from the build context. In Conan 2.0, the cppinfo.builddirs won’t contain by default the '' entry (root package).

I am running conan 1.45.0, and this behavior inteferes highly with the possibility to locate `<deps>Config.cmake` files.
CMake has the following behavior:
`Find<Dep>.cmake` are located in `CMAKE_MODULE_PATH`, while `<Dep>Config.cmake` files are searched for in certain subfolders of `CMAKE_PREFIX_PATH`.

I am not sure, if the problem you are describing will explicitly be solved by not setting the `CMAKE_PREFIX_PATH`.
In general, for cross compile scenarios, you control cmake variables like `CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` and [`CMAKE_FIND_ROOT_PATH_MODE_LIBRARY`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH_MODE_LIBRARY.html#:~:text=CMAKE_FIND_ROOT_PATH_MODE_LIBRARY%20%C2%B6%20This%20variable%20controls%20whether%20the%20CMAKE_FIND_ROOT_PATH,only%20the%20roots%20in%20CMAKE_FIND_ROOT_PATH%20will%20be%20searched.) to customize the find_library behavior.

I guess Conan knows, what packages are build requirements, and which ones regular requirements, and thus can control the build.
However, not setting the `CMAKE_PREFIX_PATH` will certainly break our workflow.

**Comment by memsharded** [comment] 2022-02-23 18:06
I think the intention is that this is addressed by explicitly defining ``self.cpp_info.builddirs = ["."]`` in the recipes, because the problem was adding always the root folder. But I am not fully sure, don't recall the details, better ask for feedback to @lasote @SpaceIm

**Comment by SpaceIm** [comment] 2022-02-23 19:30
Yes, since https://github.com/conan-io/conan/pull/10186 root package folder of requirements is excluded from `CMAKE_PREFIX_PATH` in toolchain file generated by `CMakeToolchain`, because it would break discovery of programs with `find_program()` when a recipe having this program is in requirements and build requirements.
It comes from:
-  the fact that, unfortunately, paths in `CMAKE_PREFIX_PATH` have precedence over paths in `CMAKE_PROGRAM_PATH`.
- recommendation of conan to package executables and libs in the same recipe (so a recipe can be both a requirement and a build requirement).

It could also break several cross-build scenario depending on `CMAKE_FIND_ROOT_PATH_MODE_*` values.
If you want to make CMake config files bundled in a package discoverable, there is no other choice than adding their folders to `cpp_info.builddirs`, something like `self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "<libname>"))` in `package_info()` (`find_package()` tries many subfolders under paths of `CMAKE_PREFIX_PATH`, and base path is one of them).

**Comment by KerstinKeller** [comment] 2022-02-23 21:55
Ok, so I guess your concern is about packages e.g. like protobuf, which package protoc, but of course the build system protoc (as then required as build_requirement) needs to be found by a `find_program` call.

Cross compile scenarios are hardly ever easy.
But with that in mind, is it safe to say that that `find_program` calls of a consumer should only find programs located in root folders of `build_requires`, not `requires` themselves.

So in theory we have two different usecases (and Conan can generate different toolchain files):

### Standard compilation (pr build == pr host):
toolchain sets
`CMAKE_PREFIX_PATH` for everything

### Crosscompilation: (pr build != pr host)
Toolchain sets 
`CMAKE_FIND_ROOT_PATH` to all dependency roots
`CMAKE_PREFIX_PATH` to all build dependency roots (in build context, otherwise also `CMAKE_FIND_ROOT_PATH`)
`CMAKE_FIND_ROOT_PATH_MODE_PROGRAM` to  `NEVER`
`CMAKE_FIND_ROOT_PATH_MODE_LIBRARY` to `ONLY`
`CMAKE_FIND_ROOT_PATH_MODE_INCLUDE` to `ONLY`

Wouldn't that handle the described usecases?

However, if Conan does not define the `FIND_ROOT_PATH_MODE_...` variables but lets the users define them (maybe differently), things will tend to get really, really messy. In most cases, any other definition of the `FIND_ROOT_PATH_MODE_...` variables hint at a quite fragile system setup. 😕 

Anyways, we might just define our own toolchain block to get the old behavior back 😄

**Comment by SpaceIm** [comment] 2022-02-23 22:45
standard compilation:
If an executable is both in requirements & build_requirements, `find_program()` would find executable from requirements, and it may break users expectations. Specifically if user expects to inject env vars from build requires with `VirtualBuildEnv`, or if executable in requirements depends on shared libs and executable in build requirements does not, or if version is different in build requirements & requirements.

**Comment by memsharded** [comment] 2022-02-23 23:04
There are several situations where build==host will not work:

- The version of the build_requirement is different to the requirement one. This is a real possibility, even if we don't love it and think it shouldn't happen, for sure there will be users out there doing this.
- The variant of the build_requirement is different than the requirement one. Like the build one could be a Release, linked statically, and the host one could be a Debug linked dynamically.

In both cases, any CMake ``find_xxx``, will most likely produce unexpected behavior if the wrong one is found. Does this make sense?

**Comment by lasote** [comment] 2022-02-24 07:41
> If you want to make CMake config files bundled in a package discoverable, there is no other choice than adding their folders to cpp_info.builddirs, something like self.cpp_info.builddirs.append(os.path.join("lib", "cmake", "<libname>")) in package_info() (find_package() tries many subfolders under paths of CMAKE_PREFIX_PATH, and base path is one of them).

@SpaceIm is right. Conan 1.X, the CMakeToolchain is explicitly removing the root package folders, even if you adjust the "." folder. So there is no other choice than re-packaging these files in another folder and declaring the `cpp_info.builddirs` accordingly. 
At Conan 2.0 we control this by excluding the "." as the default of `self.cpp_info.builddirs`.  So in 2.0 you might recover (at your own risk, because it is not recommended) the `self.cpp_info.builddirs=["."]` but this is not possible in 1.X

**Comment by KerstinKeller** [comment] 2022-02-24 13:00
I totally understand your concerns. You strive for the behavior that CMake finds programs in `build_requires` first, while libraries are found in `requires`.
I feel like the approach you're now following is a best effort to achieve this behavior.

However we're coming from a `cmake_path` generator use, and want to move to `CMakeToolchain` without `CMakeDeps`.
Packages either provide their regular `<Dep>Config.cmake` or package a `Find<Dep>.cmake`.
Therefore we (and I guess other devs migrating from `cmake_path`) will need setting the `CMAKE_PREFIX_PATH` variable.

I guess the way straight forward for us is really the custom toolchain block approach.

**Comment by lasote** [comment] 2022-04-12 11:32
So, I think the proposal would be, whether to move the cmake modules to a different `builddir` as suggested (`self.cpp_info.builddirs.append(os.path.join("lib", "cmake"))`) or customizing the `CMakeToolchain` as you are doing, I'm not sure we can/should do anything else, the cmake modules in the root of the packages have side effects and should be avoided so I don't see even an opt-in for that behavior. 
I'm closing this. 
Thanks everyone for the help and feedback!

**Closed as completed by lasote** 2022-04-12 11:32 UTC
Labels: stage: triaging

**Comment by SpaceIm** [comment] 2022-04-12 11:39
Yes, the workaround for recipes packaging CMake config files is to add `self.cpp_info.builddirs.append(<config_file_dirname>)` in `package_info()` (no need to move config files, unless they are packaged in root package folder which is quite unusual).

**Comment by KerstinKeller** [comment] 2022-04-12 11:58
I guess it's ok and we can live with the current approach 😄

**Comment by lpapp** [comment] 2022-04-14 11:42
I also agree that I would not switch to CMakeToolchain if I cannot get the CMAKE_PREFIX_PATH set automatically. It would be a no no.

**Comment by lasote** [comment] 2022-04-19 08:19
@lpapp Just to clarify, the `CMakeToolchain` sets the `CMAKE_PREFIX_PATH`, both to the `generators folder` to locate any `XXXConfig.cmake` file there and to the`cpp_info.builddirs` declared at the dependencies. 

Said that, there is a difference between Conan 1.X and Conan 2. In Conan 1.X even if `["."]` (root of the package) is declared at the `cpp_info.builddirs` of the dependencies, it will be skipped, (because the `["."]` is the default). In Conan 2, the default of `cpp_info.builddirs` will be empty, but if it is explicitly filled with the `["."]` it will set the `CMAKE_PREFIX_PATH` to the root of the packages.

**Comment by lpapp** [comment] 2022-04-19 08:23
Does that mean with conan 2, we would need an extra step that we have not needed with conan 1? If so, I feel that that would need to be properly justified as one extra step is typically not a good UX. But there may be a good reason for it.

**Comment by lasote** [comment] 2022-04-19 08:27
yes, I think there is a good reason, explained here https://github.com/conan-io/conan/issues/10648#issuecomment-1049137758
The recommended way is to set the ".cmake" files that want to be located into a subfolder and declare it. e.g `self.cpp_info.builddirs = ["cmake"]`.

**Comment by thejohnfreeman** [comment] 2023-02-01 16:21
> @lpapp Just to clarify, the `CMakeToolchain` sets the `CMAKE_PREFIX_PATH`, both to the `generators folder` to locate any `XXXConfig.cmake` file there and to the`cpp_info.builddirs` declared at the dependencies.
> 
> Said that, there is a difference between Conan 1.X and Conan 2. In Conan 1.X even if `["."]` (root of the package) is declared at the `cpp_info.builddirs` of the dependencies, it will be skipped, (because the `["."]` is the default). In Conan 2, the default of `cpp_info.builddirs` will be empty, but if it is explicitly filled with the `["."]` it will set the `CMAKE_PREFIX_PATH` to the root of the packages.

@lasote It appears this is no longer true? I'm setting `self.cpp_info.builddirs = ['xyz']`, and I see `~/.conan/data/.../package/.../xyz` prepended to `CMAKE_MODULE_PATH` by the `CMakeToolchain` generator, but nothing I do can change the line that touches `CMAKE_PREFIX_PATH`:

```cmake
# Definition of CMAKE_PREFIX_PATH, CMAKE_XXXXX_PATH
# The Conan local "generators" folder, where this toolchain is saved.
list(PREPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR} )
```
