### ISSUE TITLE
[bug] `conan build` interface regression: `--configure`, `--build`, and `--test` do nothing

### ISSUE THREAD

**Issue by samuel-emrys** [conan-io/conan#12865] opened 2023-01-08 01:28 UTC
### Environment details

* Operating System+version: Arch linux
* Compiler+version: Clang 14.0.6
* Conan version: 1.56.0
* Python version: 3.11.0

### Steps to reproduce

1. `conan new foo/0.1.0 --template=cmake_lib`
2. `conan install .`
3. `conan build --configure .`

This will run the `configure`, `build` and `test` phases of the `conan build` command, not just the `configure` stage (see logs below). This seems like a regression, since
```
$ conan build --help
usage: conan build [-h] [-b] [-bf BUILD_FOLDER] [-c] [-i] [-t] [-if INSTALL_FOLDER] [-pf PACKAGE_FOLDER] [-sf SOURCE_FOLDER] path

Calls your local conanfile.py 'build()' method.

The recipe will be built in the local directory specified by
--build-folder, reading the sources from --source-folder. If you are
using a build helper, like CMake(), the --package-folder will be
configured as the destination folder for the install step.

positional arguments:
  path                  Path to a folder containing a conanfile.py or to a recipe file e.g., my_folder/conanfile.py

options:
  -h, --help            show this help message and exit
  -b, --build           Execute the build step (variable should_build=True). When specified, configure/install/test won't run unless --configure/--install/--test specified
  -bf BUILD_FOLDER, --build-folder BUILD_FOLDER
                        Directory for the build process. Defaulted to the current directory. A relative path to the current directory can also be specified
  -c, --configure       Execute the configuration step (variable should_configure=True). When specified, build/install/test won't run unless --build/--install/--test specified
  -i, --install         Execute the install step (variable should_install=True). When specified, configure/build/test won't run unless --configure/--build/--test specified
  -t, --test            Execute the test step (variable should_test=True). When specified, configure/build/install won't run unless --configure/--build/--install specified
  -if INSTALL_FOLDER, --install-folder INSTALL_FOLDER
                        Directory containing the conaninfo.txt and conanbuildinfo.txt files (from previous 'conan install'). Defaulted to --build-folder
  -pf PACKAGE_FOLDER, --package-folder PACKAGE_FOLDER
                        Directory to install the package (when the build system or build() method does it). Defaulted to the '{build_folder}/package' folder. A relative path can be specified, relative to the current folder. Also an absolute path is allowed.
  -sf SOURCE_FOLDER, --source-folder SOURCE_FOLDER
                        Directory containing the sources. Defaulted to the conanfile's directory. A relative path to the current directory can also be specified
```
is pretty explicit about being able to specify `--configure`, `--build`, `--test` or `--install`.

I've also realised that `conan build` is suspiciously absent from https://docs.conan.io/en/2.0/reference/commands.html - is this being removed in conan 2.0? I really hope not - this is our preferred workflow to invoke cmake, and these selectors are really quite useful in separating out the stages of a build for debugging purposes.

### Logs

```
$ conan new foo/0.1.0 --template=cmake_lib
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: include/foo.h
File saved: src/foo.cpp
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp
$ conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=clang
compiler.libcxx=libstdc++11
compiler.version=14
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
CC=/usr/bin/clang
CXX=/usr/bin/clang++
[conf]
tools.build:skip_test=False

conanfile.py (foo/0.1.0): Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py (foo/0.1.0): Generator txt created conanbuildinfo.txt
conanfile.py (foo/0.1.0): Calling generate()
conanfile.py (foo/0.1.0): WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
conanfile.py (foo/0.1.0): Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
conanfile.py (foo/0.1.0): If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/home/user/projects/irc/conan-build-example/build/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
conanfile.py (foo/0.1.0): Aggregating env generators
conanfile.py (foo/0.1.0): Generated conaninfo.txt
conanfile.py (foo/0.1.0): Generated graphinfo
$ conan build --configure .
Using lockfile: '/home/user/projects/irc/conan-build-example/conan.lock'
Using cached profile from lockfile
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK. 'fPIC' option found and apparently well managed
[HOOK - conan-center.py] pre_build(): [FPIC MANAGEMENT (KB-H007)] OK
conanfile.py (foo/0.1.0): Calling build()
conanfile.py (foo/0.1.0): CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/home/user/projects/irc/conan-build-example/build/generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/home/user/projects/irc/conan-build-example/."
-- Using Conan toolchain: /home/user/projects/irc/conan-build-example/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- The CXX compiler identification is Clang 14.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_POLICY_DEFAULT_CMP0091


-- Build files have been written to: /home/user/projects/irc/conan-build-example/build/Release
conanfile.py (foo/0.1.0): CMake command: cmake --build "/home/user/projects/irc/conan-build-example/build/Release" '--' '-j24'
[ 50%] Building CXX object CMakeFiles/foo.dir/src/foo.cpp.o
[100%] Linking CXX static library libfoo.a
[100%] Built target foo
```

**Comment by memsharded** [comment] 2023-01-08 16:16
Hi @samuel-emrys 

Thanks for your report.
This wouldn't be a regression, but this is by design and intended. The new tools do not aim to support those arguments, as they are being removed in 2.0. 
This is because the main intended dev flow is ``conan install`` + ``cmake ...`` (or other build system), while the ``conan build`` command should be rarely used. Most of the new integrations design criteria is to allow a transparent integration with the build system, so Conan commands for building are not necessary, but using the native build system.

If some custom behavior is desired to control a specific method, it will be implemented via ``conf`` and not custom args. There is already a ``tools.build:skip_test`` conf that can be used to skip tests (and ``cmake.test()`` already checks it).

**Comment by SSE4** [comment] 2023-01-09 04:49
I would say this is a kinda tedious flow to automate, e.g. I can perfectly run `conan install` + `conan build` for an arbitrary package and it will work flawlessly. while without `conan build` I first need to know if given recipe uses `cmake`, `meson`, `autotools` or whatever, and then execute a build-system specific command. and if a given recipe uses a custom build system (= bunch of `self.run` commands), it's ever impossible to machine parse and execute...

**Comment by samuel-emrys** [comment] 2023-01-09 07:12
Thanks for the response @memsharded. This should probably be removed from the cli help if it was intended to be removed.

To clarify your statement, are you suggesting that the preferable workflow from the conan team perspective would be the following?

```bash
$ conan install . --build=missing
$ cmake -S . -B build/Release -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=build/generators/conan_toolchain.cmake
$ cmake --build build/Release
$ ctest --test-dir build/Release
```
or, perhaps equivalently depending on the constraints
```bash
$ conan install . --build=missing
$ cmake --preset release
$ ctest --test-dir build/Release
```

A couple of things to note about this approach:
1. It's absolutely vital that it's supported - many users will want this approach and you're right that it's more transparent. It will also facilitate IDE integration much more easily than the conan interface which is great
2. This duplicates the logic that's already present in the conanfile, and will get tedious to enumerate manually all the time. In all likelihood, if this is the intended approach, we would end up with a `build.{sh|py}` file in the root of the repository that we would invoke to simplify the invocation of this. This is a bit redundant because all of this is already specified in the conanfile - `conan build` is ideal in this case.
3. For projects with build systems other than CMake, which I'm not familiar with, I'm now required to develop an understanding of them and how they integrate with conan just so that I can invoke logic that's already captured within the conanfile. One of the big selling points for us is the ability to abstract the build system away to some extent and just deal with the conan interface, which knows how to communicate with each of the build systems individually. As @SSE4 has indicated, for projects with custom build systems this becomes untenable pretty quickly.
4. It doesn't allow a user to test individual components of the recipe for the purposes of debugging the package. Invoking CMake manually completes the operations in principle, but it doesn't exercise the recipe code that contributes to a `conan create` call. I've found this to be a very useful feature when creating/debugging recipes in the past.

I'd encourage you to think more about the `conan install . && conan build .` workflow as playing a more impactful role than one that should be rarely used. This is very much our preferred workflow and we would hate to see it abandoned or unsupported. We would love to see this treated as a completely viable, alternate developer workflow.

> If some custom behavior is desired to control a specific method, it will be implemented via `conf` and not custom args. There is already a `tools.build:skip_test` conf that can be used to skip tests (and `cmake.test()` already checks it).

Is the implication of this that you expect to see `tools.build:skip_{configure,build,install}` functions so that one could invoke the following?
```bash
$ conan install . --build=missing
$ conan build . -c:b tools.build:skip_build=True -c:b tools.build:skip_install=True -c:b tools.build.skip_test=True
```

**Comment by memsharded** [comment] 2023-01-09 08:38
To be clear: ``conan build`` is not going away. It is still there and can be perfectly used to abstract the build.
Also the tests can already be skipped with that ``skip_test`` conf.
The ``install`` step do not belong to the ``build()`` method, but to the ``package()`` method, so it shouldn't be an issue.

So that leaves only with the configure and build step separation. If you are a developer and you intend to build manually, then it is likely that calling configure with the build system approach is the expected way. Why should conan only do half of the work with a syntax that is ``conan build, but do not really build, only configure``, instead of using the build system idiomatic way to configure? And if you want to build, of course ``conan build`` is perfectly valid. It is possible that in the future conan gets a ``configure_build()`` method to separate configuration from real build, but at the moment this is only speculation.

> Thanks for the response @memsharded. This should probably be removed from the cli help if it was intended to be removed.

It cannot be removed from the cli, as it would be breaking, and it is still valid for the legacy integrations.

> It's absolutely vital that it's supported - many users will want this approach and you're right that it's more transparent. It will also facilitate IDE integration much more easily than the conan interface which is great

This is the final goal, to have one way of doing things. If this is the vital thing to be supported, and what the community has been pushing for, this will be the way of splitting the configure and build steps. Having another alternative Conan syntax to do exactly what is intended to be done with the build system (a ``conan build --skip_build`` for ``configure`` step, etc) can be even confusing.

**Comment by samuel-emrys** [comment] 2023-01-09 09:38
> To be clear: conan build is not going away. It is still there and can be perfectly used to abstract the build.

Excellent.

> If you are a developer and you intend to build manually, then it is likely that calling configure with the build system approach is the expected way. Why should conan only do half of the work with a syntax that is `conan build, but do not really build, only configure`, instead of using the build system idiomatic way to configure?

Fair enough. My primary concern in my previous reply was about the future of `conan build` generally, so if it has a long future ahead of it I can live without the granularity. Since most of the complexity previously associated with `cmake.configure()` has been offloaded to the `generate()` step when a toolchain is produced, there probably isn't a huge concern about not being able to isolate `configure()` through the command line - worst comes to worst, one can always comment the `cmake.build()` invocation out to debug.

> It cannot be removed from the cli, as it would be breaking, and it is still valid for the legacy integrations.

Ah, I think I misunderstood. I'd interpreted this removal of functionality as removal of functionality from the `conan build` interface, not just the `conan.tools.cmake.CMake` helper. If this change has just been to the new helper then that makes sense.

> This is the final goal, to have one way of doing things.

I realise that you've just clarified your previous statement and indicated that `conan build` won't be going away - this phrasing makes that confusing though (`conan build` is a second way, "one way" implies its removal). Whilst I agree that it's vital to support this way of integrating with conan, I think `conan build` provides a lot of value over and above the transparent invocation and shouldn't be sacrificed on the alter of the cmake community. I think there should remain two ways of doing things because it's not just the cmake community that need to be considered here.

To be clear - I'm making this statement outside of the context of this issue in which one can or can't split the `build` call out in to `configure` and `build` - only in the context of `conan build`'s existence generally. Though, I can see that you might only mean this "one way of doing things" in the context of splitting out `conan build`s functionality. If so, as above, that's fine I can live with that.

I think that we're on the same page here - I just wanted to be explicit to avoid miscommunication. Text based communication can be hard sometimes :)

**Comment by jjATL** [comment] 2024-03-07 08:20
I am currently learning conan by following the documentation and pretty much had the same question: Why is `conan build . --configure` not working as described in the [conan build](https://docs.conan.io/1/reference/commands/development/build.html) and the [should_* attributes](https://docs.conan.io/1/reference/conanfile/attributes.html#should-configure-should-build-should-install-should-test) documentation.

Your argumentation here in this issue makes sense, but could you please make sure this is also reflected in the documentation?

As I was following the documentation I created my project using the  `cmake_lib` template, i.e. calling the command `conan new hello/0.1 --template=cmake_lib` as described in the [Getting Started](https://docs.conan.io/en/1.60/creating_packages/getting_started.html) section.

If you just start working with python and conan it is pretty tricky to see that the import of the **CMake** module is different in the [conan build](https://docs.conan.io/1/reference/commands/development/build.html) documentation: `from conans import ConanFile, CMake, tools` and in the `conanfile.py` automatically generated via the `cmake_lib` template: `from conan.tools.cmake import CMakeToolchain, CMake, cmake_layout`.

I think this difference should be highlighted a bit better in the documentation.

**Comment by jjATL** [comment] 2024-03-07 08:51
One more addition: I am all in favor of a new`configure_build()` phase. For me it is not an option to run cmake directly.

I am currently working on a batch file, with which one can generate the project files for different conan profiles in order to develop the project, i.e. something like this:

```
@echo off
SETLOCAL ENABLEDELAYEDEXPANSION

REM ==========================================================================
REM Setup
REM ==========================================================================
REM Paths.
set installFolder=build
set profileFolder=tools\conan\profiles
REM Profiles to use.
REM Comma separated list with possible values, e.g. "vs2019_amd64_release,vs2019_amd64_debug"
set "listOfProfiles=vs2019_amd64_release,vs2019_amd64_debug"

REM ==========================================================================
REM Create Project Files
REM ==========================================================================

REM Create the project files for the different profiles.
for %%a in ("%listOfProfiles:,=" "%") do (
	set "profile=%%~a"

	REM Prepare folder structure and get all dependencies.
	REM Build missing dependencies.
	conan install . --install-folder=%installFolder%\!profile! --output-folder=%installFolder%\!profile! -pr=%profileFolder%\!profile! -pr:b=%profileFolder%\!profile! --update --build=missing

	REM Run the configure phase.
	conan build . --configure --install-folder=%installFolder%\!profile! --build-folder=%installFolder%\!profile!
	
	echo ==========================================================================
	echo Done creating project files in the subfolder '%installFolder%\!profile!'.
	echo ==========================================================================
)
```

In that way I do not need to know the CMake generator to use, it is already coded in the conan profiles. What if I wanted to add a new profile for e.g. a CLion or VisualStudioCode project? 

Calling the concrete `cmake` command:

 ```
cmake -S . -B %installFolder%/!profile! -G "<CMAKE_GENERATOR>" -DCMAKE_TOOLCHAIN_FILE=%installFolder%/!profile!/generators/conan_toolchain.cmake
```
would be more tedious since I would have to somehow find out what `<CMAKE_GENERATOR>' to use.

Calling the entire `conan build` phase would take long in a large project and is unnecessary at that point. Maybe the user only wants to change and rebuild a small submodule and not the entire project.

I will see whether it is more sensible to change my CMake import to `conans` as opposed to `conan.tools.cmake`, or whether I will add my own

```
def build(self):
    if self.should_configure:
        cmake.configure()
    if self.should_build:
        cmake.build()
    if self.should_install: # If my build has install, otherwise use package()
        cmake.install()
    if self.should_test:
        cmake.test()
```

logic in the `conanfile.py`.

**Comment by memsharded** [comment] 2024-03-07 09:08
> As I was following the documentation I created my project using the cmake_lib template, i.e. calling the command conan new hello/0.1 --template=cmake_lib as described in the [Getting Started](https://docs.conan.io/en/1.60/creating_packages/getting_started.html) section.

Yes, that is true, thanks for the feedback.
The reality is that Conan 2 was released now more than 1 year ago, so even if Conan 1.X is still supported and we keep doing releases, the efforts on improving documentation are mostly focused on Conan 2 documentation, there are no infinite resources, so Conan 1 docs don't usually get enough priority


> One more addition: I am all in favor of a new configure_build()

Yes, this could be a good addition.
However, it is also true that with the continuous improvements in the generation of the CMakePresets, the experience is now much better, the user doesn't have to recall anything, just a simple ``cmake --preset conan-default`` and that is it. Furthermore, some of the recent Conan 2.1 improvements have added support for environment ``env`` and ``cmakeExecutable`` in the generated presets, so it is also able to inject ``tool_requires`` in the ``cmake`` build without users having to activate the environment. 

This flow also works great with some integrations like the cmake-tools integration for VSCode, that directly takes presets, so mostly a ``conan install`` is all what is needed, and then the configure and build steps are doing from the IDE with the presets.

Even better, the ``cmake_layout()`` and ``CMakeToolchain`` generation of presets have capabilities beyond the standard CMake flows, like defining ``build_folder_vars``, it can automatically add support for presets for multiple compiler versions, architectures, shared/static, etc, without having to leave the IDE. Just ``conan install`` the configuration you want, and a new ``gcc_11_shared_armv8_release`` preset will be added to your existing presets, and you can build it.

**Comment by jjATL** [comment] 2024-03-07 14:50
> The reality is that Conan 2 was released now more than 1 year ago

Unfortunately in my company we are still using v1.60.1. It is understandable that the v1.x documentation cannot be maintained perfectly anymore. I do not know anything about Conan 2.x yet, but maybe the suggested change in the documentation is also applicable there?!

Anyways, I tried the CMake presets functionality, which is new to me. 
The problem is I cannot simply run `cmake --preset conan-default` (actually `cmake --preset default`, a profile `conan-default` does not exist in my build), because when installing the second conan profile `vs2019_amd64_debug`, the same preset name `default` is used, and then there is a name conflict:

> CMake Error: Could not read presets from <PROJECT_PATH>: Duplicate presets

So I added the line
```
[conf]
tools.cmake.cmake_layout:build_folder_vars=['settings.compiler', 'settings.compiler.version', 'settings.build_type', 'settings.arch', 'options.shared'] 
```
to the base conan profile `vs2019_amd64` both the `vs2019_amd64_debug` and `vs2019_amd64_release` profiles inherit.

Having done that, I could run both presets by calling
```bash
cmake --preset "visual studio-16-release-x86_64-shared_false"
cmake --preset "visual studio-16-debug-x86_64-shared_false"
```
but then in my batch-file I mentioned above, I would need to know how the presets will be named in order to build up the correct command, which again is similar to needing to know the correct `<CMAKE_GENERATOR>` to use.
Actually it would be easier to have a dedicated batch file only for Visual Studio 2019 projects and hardcoding the `<CMAKE_GENERATOR>`.
For other profiles I would need to create a separate batch file. But I would loose a lot of flexibility, since I could not simply extend the `listOfProfiles` batch variable by more conan profiles.

Currently I think it is more elegant to call `conan build . --configure` and extend the `build()` method in the `conanfile.py` to interpret the `self.should_*` attributes correctly and deactivate the CMake presets alltogether via `tc.user_presets_path = False`:
```python
def generate(self):
    tc = CMakeToolchain(self)
    tc.user_presets_path = False # Deactivate CMake presets.
    tc.generate()
```
which would also have the benefit of my source folder not being polluted by the automatically generated `CMakeUserPresets.json` file.
I also prefer the resulting folder structure `<PROJECT_FOLDER>\build\<CONAN_PROFILE_NAME>\build`.

My problem would be solved if one could define the CMake preset name in the conan profile, instead of having to use `build_folder_vars`, which defines both the folder structure and the CMake preset name. 

Something like this would be nice:
```
[conf]
# This should only define the folder structure, not the the CMake preset name.
#tools.cmake.cmake_layout:build_folder_vars=['settings.compiler', 'settings.compiler.version', 'settings.build_type', 'settings.arch', 'options.shared']

# This would be a nice feature:
tools.cmake.cmaketoolchain.presets:name='vs2019_amd64_release'
```

**Comment by memsharded** [comment] 2024-03-07 15:26
> Unfortunately in my company we are still using v1.60.1. It is understandable that the v1.x documentation cannot be maintained perfectly anymore. I do not know anything about Conan 2.x yet, but maybe the suggested change in the documentation is also applicable there?!

No, it doesn't apply in 2.X anymore the ``--configure`` doesn't even exist and ``should_xxx`` don't exist either.

If you are in in VS, it is most likely that your builds are multi-configuration. Then you don't need to add ``settings.build_type`` to your ``build_folder_vars``, and you will have a single ``vs2019_amd64`` "configure" preset that is valid both for Debug and Release (and then you will have the ``vs2019_amd64_release/debug`` "build" presets. But "configure" you should only have one.

> but then in my batch-file I mentioned above, I would need to know how the presets will be named in order to build up the correct command, which again is similar to needing to know the correct <CMAKE_GENERATOR> to use.

Except IDEs like VSCode can directly read the presets file and show the presets names in the IDE interface, so users only have to select it, not necessarily typing it

> Actually it would be easier to have a dedicated batch file only for Visual Studio 2019 projects and hardcoding the <CMAKE_GENERATOR>.

If we are talking about Release/Debug, then this is what I meant above, the default would be to use only 1 configure preset for it. 
If we are talking about other aspects like architecture, shared/static, etc, then that is impossible. CMake generator of Visual Studio projects limit multi-configuration to ``build_type`` mostly, or otherwise requires handcrafting custom configurations, but that is beyond what Conan can do.

**Comment by jjATL** [comment] 2024-03-07 17:12
I think I got it to run like you suggested. These are my conan profiles:

**vs2019_amd64**
```
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=16
compiler.cppstd=17

[conf]
tools.cmake.cmake_layout:build_folder_vars=['settings.compiler', 'settings.compiler.version', 'settings.compiler.runtime', 'settings.arch', 'options.shared']
```

**vs2019_amd64_shared**
```
include(vs2019_amd64)

[options]
shared=True
```

**vs2019_amd64_shared_md**
```
include(vs2019_amd64_shared)

[settings]
build_type=Release
```

**vs2019_amd64_shared_mdd**
```
include(vs2019_amd64_shared)

[settings]
compiler.runtime=MDd
build_type=Debug
```

**vs2019_amd64_static_md**
```
include(vs2019_amd64)

[settings]
build_type=Release
```

**vs2019_amd64_static_mdd**
```
include(vs2019_amd64)

[settings]
compiler.runtime=MDd
build_type=Debug
```

And I copied all profiles replacing all occurences of `amd64` and `x86_64` in the file names and the content, to get profiles for the `arch=x86` target architecture.

I noticed I had to define a `build_type` even though all calls to `cmake --preset` will generate a multi-config VS2019 project file (solution). Omitting it would yield the error `CMake Error: Could not read presets from <PROJECT_FOLDER>: Invalid preset`

The ugly thing I do not like, is the folder structure, which now is for example: `<PROJECT_FOLDER>\build\vs2019_amd64_shared_md\build\visual studio-16-md-x86_64-shared_true`. So all build characteristics are doubled in the folder structure.

Also the way I have to call `cmake --preset` from within my .BAT file is rather complicated, as opposed to the `conan build --configure` one-liner, which is commented in the shown excerpt:

```bat
REM Run the configure phase.
REM conan build . --configure --install-folder=%installFolder%\!profile! --build-folder=%installFolder%\!profile!

REM Run cmake --preset instead of conan build . --configure.
if "!profile!"=="vs2019_x86_shared_mdd" (
	cmake --preset "visual studio-16-mdd-x86-shared_true"
) else (
if "!profile!"=="vs2019_x86_shared_md" (
	cmake --preset "visual studio-16-md-x86-shared_true"
) else (	
if "!profile!"=="vs2019_x86_static_md" (
	cmake --preset "visual studio-16-md-x86-shared_false"
) else (	
if "!profile!"=="vs2019_x86_static_mdd" (
	cmake --preset "visual studio-16-mdd-x86-shared_false"
) else (
if "!profile!"=="vs2019_amd64_shared_md" (
	cmake --preset "visual studio-16-md-x86_64-shared_true"
) else (	
if "!profile!"=="vs2019_amd64_shared_mdd" (
	cmake --preset "visual studio-16-mdd-x86_64-shared_true"
) else (	
if "!profile!"=="vs2019_amd64_static_mdd" (
	cmake --preset "visual studio-16-mdd-x86_64-shared_false"
) else (
if "!profile!"=="vs2019_amd64_static_md" (
	cmake --preset "visual studio-16-md-x86_64-shared_false"
)
))))))))

```

**Comment by memsharded** [comment] 2024-05-01 11:53
Closing this ticket, Conan 2 does not implement ``--configure, --build, and --test`` and it is not planned to add them.
The flows based on ``conan install`` + ``cmake --preset`` seems to be great so far, that would be the recommended approach.

**Closed as not planned by memsharded** 2024-05-01 11:53 UTC
Labels: type: question
