### ISSUE TITLE
[question] set_version & set_name aren't being called

### ISSUE THREAD

**Issue by wils93** [conan-io/conan#11771] opened 2022-08-03 16:21 UTC
Hi,

I'm using conan version 1.19 - I know it's very old - but it's currently a limitation and can't directly update to the latest version.
I have this demo conanrecipe.py however when I run `conan create` I get `ERROR: Specify the 'name' and the 'version'`

    from conans import ConanFile

    class DemoPkg(ConanFile):

        def set_name(self):
            import pdb; pdb.set_trace()

        def set_version(self):
            import pdb; pdb.set_trace()

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment] 2022-08-04 06:10
Hi @wils93,

The problem is that `set_name` and set_version methods were introduced in [Conan 1.20](https://github.com/conan-io/conan/pull/5881), so that's why they are not called.

Thanks a lot for your question.

**Comment by wils93** [comment] 2022-08-04 06:58
Hi @czoido,

Oh really! I was checking documentation of version 1.19 and it was there, that's why I was confused.
Thank you for clarifying ✌️

**Comment by czoido** [comment] 2022-08-04 07:44
Hi @wils93,

You are right, I think we accidentally merged documentation from 1.20 to 1.19 when releasing one patch version, sorry for the confusion.

**Comment by czoido** [comment] 2022-08-04 07:45
I'm closing this issue, but please feel free to reopen or open another issue if you have more questions. 
Thanks!

**Closed as completed by czoido** 2022-08-04 07:45 UTC
Labels: type: question
