### ISSUE TITLE
[bug] CMake CMP0091 policy not applied by CMakeToolchain

### ISSUE THREAD

**Issue by freakinpenguin** [conan-io/conan#12458] opened 2022-11-03 13:32 UTC
I'm currently trying to build a conan package of the eigen3 library. I started with the conan file from conancenter, but I keep getting errors, that the CMake policy CMP0091 must be set to ´NEW´, but it's empty.

I'm aware that in v1.53 https://github.com/conan-io/conan/issues/10239 was fixed to introduce it, but to me it looks as the default policy settings is somehow not recognized by cmake. I can see it in the CMake command, but nevertheless it enters the if-case in the generated conan_toolchain.cmake. See output below.

### Environment Details (include every applicable attribute)
(I tested with two systems: first / second)
  * Operating System+version: Windows 10 / 11
  * Compiler+version: Visual Studio 2015 / Visual Studio 2019
  * Conan version: 1.53
  * Python version: 3.10 / 3.11
  * CMake version: 3.24

### Steps to reproduce (Include if Applicable)
1. Download attached conanfile.zip and extract
2. Run `conan create .`

### Logs (Executed commands with output) (Include/Attach if Applicable)

`cmake -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE="C:/Users/XXXXXXXXX/.conan/data/eigen/3.3.7/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/XXXXXXXXX/.conan/data/eigen/3.3.7/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" -DBUILD_TESTING="OFF" -DEIGEN_TEST_NOQT="ON" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "C:\Users\XXXXXXXXX\.conan\data\eigen\3.3.7\_\_\build\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\eigen-3.3.7"

-- Using Conan toolchain: C:/Users/Thomy/.conan/data/eigen/3.3.7/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake
CMake Error at C:/Users/Thomy/.conan/data/eigen/3.3.7/_/_/build/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/conan_toolchain.cmake:29 (message):
  The CMake policy CMP0091 must be NEW, but is ''
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeDetermineSystem.cmake:124 (include)
  CMakeLists.txt:1 (project)`

#### Full output
[output.txt](https://github.com/conan-io/conan/files/9929574/output.txt)
[conanfile.zip](https://github.com/conan-io/conan/files/9929584/conanfile.zip)

**Comment by franramirez688** [comment] 2022-11-03 16:51
Hi @freakinpenguin 

I'm not able to reproduce the issue, so let's try something easier. Let's use the hello-world-example in an empty folder only to be sure that it's also not working:

```bash
$ conan new hello/1.0 -m cmake_lib
$ conan create .
```
Is it working fine? Or is it appearing the same error?

**Comment by SpaceIm** [comment] 2022-11-03 18:29
It's a recipe issue in a sense. CMakeLists of eigen is illformed before 3.4.0 (`project()` before `cmake_minimum_required()`, so it breaks policies), but because c3i doesn't test build of header only libraries on all plaforms (it tests the build on Linux, and test package on all supported platforms), this issue was missed.

https://github.com/conan-io/conan-center-index/pull/14003 will fix this issue.

**Comment by franramirez688** [comment] 2022-11-04 07:41
Thank @SpaceIm for the info!

Then, I think that we can close this issue.

**Closed as completed by franramirez688** 2022-11-04 07:41 UTC
Labels: stage: triaging

**Comment by freakinpenguin** [comment] 2022-11-04 08:26
> It's a recipe issue in a sense. CMakeLists of eigen is illformed before 3.4.0 (`project()` before `cmake_minimum_required()`, so it breaks policies), but because c3i doesn't test build of header only libraries on all plaforms (it tests the build on Linux, and test package on all supported platforms), this issue was missed.
> 
> [conan-io/conan-center-index#14003](https://github.com/conan-io/conan-center-index/pull/14003) will fix this issue.

That makes sense. Thanks for pointing it out.
