### ISSUE TITLE
[feature] python_requires can use "normal" requires

### ISSUE THREAD

**Issue by blackliner** [conan-io/conan#8930] opened 2021-05-06 19:46 UTC
I would like to be able to define `def requirements(self):` methods for packages that are used via `python_requires`.

Reason: I am writing a `python_requires` packages, that will provide code quality related tools, like running `gcov` instrumented tests, collecting the coverage data with `gcovr`, run `clang-tidy`, upload data to SonarQube etc. For some of those steps, binaries are required, and I would like to define them as conan packages as well.

https://docs.conan.io/en/latest/extending/python_requires.html#resolution-of-python-requires

I do not know if there are any other sorts of conan packages that would fulfill such a design (maybe something like tool-packages?), but with the current solution, I can add the whole quality pipeline to any existing conan package by adding those few lines:
```python
class ConanPackage(ConanFile):
...
    python_requires = "quality_pipeline/1.0.0@"
    python_requires_extend = "quality_pipeline.QualityPipeline"
    # python_requires_extend  is required for class inheritance, so I can access the helper methods through self
...
    # this adds the option with_quality_pipeline from the BaseClass to this ConanFile,
    # which is used by the helper methods and set by the quality_profile
    def init(self):
        quality_pipeline = self.python_requires["quality_pipeline"].module.QualityPipeline
        self.options = {**self.options, **quality_pipeline.options}
        self.default_options = {**self.default_options, **quality_pipeline.default_options}
...
    def build(self):
        # instead of 
        cmake.build()
        #use 
        self.build_wrapped()
        self.run_quality_pipeline()
```

All you now need to do is calling `conan create my_package/1.2.3@ --profile quality_profile`,
with `quality_profile` having the following two extras:
```
[options]
*:with_quality_pipeline=True

[env]
CONAN_CMAKE_TOOLCHAIN_FILE=$PROFILE_DIR/../../cmake/toolchains/quality_pipeline.cmake
```
`quality_pipeline.cmake`
```
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g -fprofile-arcs -ftest-coverage")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -fprofile-arcs -ftest-coverage")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
```

So without this feature, the target package not only has to add the stuff above, but also add conan packages via `self.requires()`, which should be considered private impl. details of that quality package.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-05-10 12:29
Hi @blackliner 

I didn't fully understood how you implemented your setup, let me describe some of the rationale first:

> Reason: I am writing a python_requires packages, that will provide code quality related tools, like running gcov instrumented tests, collecting the coverage data with gcovr, run clang-tidy, upload data to SonarQube etc. For some of those steps, binaries are required, and I would like to define them as conan packages as well.

The intended mechanism for this is the ``build_requires``. Anything that is kind of a binary thing, that runs at build time, in the build machine, for example, ``cmake`` should be a ``build_requires``. Because with this way they can have their own settings, different binaries for different configurations/platforms, and the right binary will be used depending on the profile (and specially when using profile:build and profile:host)

On the other hand ``python_requires`` is a mechanism that by definition cannot have binaries. ``python_requires`` need to be resolved and recipe load time, which happens when the dependency graph is being computed. This happens before the settings or options are defined. Then, ``python_requires`` will never be able to have a configuration to pass to other "normal" requires.

I think the approach that would make sense is something like this:

```python
class ConanPackage(ConanFile):
...
    python_requires = "quality_pipeline/1.0.0"  # This contain your recipe code
    build_requires = "gcov/2.0", "clang-tidy/3.0" # or your own "mybuildtools/1.0" that bundle all of them
```

The ``build_requires`` packages contain the tools binaries, while your ``python_requires`` contains the custom Conan recipe logic to use those tools in the recipes. Both should probably be very decoupled:
- The ``python-requires`` code to use gcov or clang-tidy, could probably work as well if those tools were located in the system, and not in a conan package
- The ``build-requires`` packages could probably be used without the custom ``python_requires`` code, for example, if some CMake build scripts already assumed those were available and used them in CMake directly.


Please let us know what you think.

**Comment by blackliner** [comment] 2021-05-10 14:11
Hi @memsharded

thanks for getting back to me. I already assumed that `python_requires` is something very special, in the sense that it has to run at a very early stage, for all the python language specific things that are happening, like deriving from a class etc.

I am already using `build_requires` for those special binaries (custom recipes for SonarQubes analyzsers), but the magic trick in the end was to leverage the derived classes methods being called (see code below). This way I can stick with my main design goal for all of this, to have none/as few as possible of the design details, chosen by the `quality_pipeline`, to show up in the recipes that want to use it.

In the `quality_pipeline`, I define `build_requirements`
```python
def build_requirements(self):
    if self.options.with_quality_pipeline:
        self.build_requires("sonarqube_build_wrapper/1.0.0")
        self.build_requires("sonarqube_scanner_cli/4.6.0")
```
This way, if there are no `build_requires` by the using recipe, it just works out of the box. If they want to define their own `build_requirements(self)`, they need to call `super().build_requirements(self)`. Same for `def build(self):`. `init(self):` also went to the `quality_pipeline`:
```python
def init(self):
    self.options["with_quality_pipeline"] = [True, False]
    self.default_options["with_quality_pipeline"] = False
```

**Comment by memsharded** [comment] 2021-05-11 11:16
Hi @blackliner 

Oh, I start to understand a bit better: it seems you want to inherit the ``build_requirements()`` method defined in the base class of the ``python_requires``? And the problem is that this is not working, is the ``build_requirements()`` method of the base class being ignored?

Maybe it is better to try to put it as a test. This one passes ok:

```python
def test_inherit_build_requirements():
    # https://github.com/conan-io/conan/issues/8930
    client = TestClient()
    mypytool = textwrap.dedent("""
        from conans import ConanFile

        class BaseClass:
            def build_requirements(self):
                self.build_requires("cmake/1.0")

        class Pkg(ConanFile):
            pass
        """)
    consumer = textwrap.dedent("""
          from conans import ConanFile
          class BaseClass(ConanFile):
              python_requires = "mypytool/1.0"
              python_requires_extend = "mypytool.BaseClass"
          """)
    client.save({"cmake/conanfile.py": GenConanfile(),
                 "mypytool/conanfile.py": mypytool,
                 "consumer/conanfile.py": consumer})

    client.run("create cmake cmake/1.0@")
    client.run("export mypytool mypytool/1.0@")
    client.run("create consumer consumer/1.0@")
    assert "cmake/1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9" in client.out
    assert "consumer/1.0: Applying build-requirement: cmake/1.0" in client.out
```

**Comment by blackliner** [comment] 2021-05-11 15:40
Nono, it works now the way I described it in my second post. Initially I was trying to define the methods in the unused Conanfile of the `mypytool` (the one that starts with the line `class Pkg(ConanFile)`). But since that, I moved to define the methods in the python package, which will be either called automatically, or if the user overwrites them in their recipe, via `super().method()`

I think this issue can be closed. The only open question for me is if this is actually the right way to solve this problem, or if conan has other means for that (that being code quality related tools for production usage).

Also, I really like how easy it is to write such tests, awesome work!

**Comment by memsharded** [comment] 2021-05-11 16:17
> Nono, it works now the way I described it in my second post. Initially I was trying to define the methods in the unused Conanfile of the mypytool (the one that starts with the line class Pkg(ConanFile)). But since that, I moved to define the methods in the python package, which will be either called automatically, or if the user overwrites them in their recipe, via super().method()

> The only open question for me is if this is actually the right way to solve this problem, or if conan has other means for that (that being code quality related tools for production usage).

Understood now. Yes, this seems to be the right approach. In the previous implementation of python_requires, it was kind of possible to inherit from the "main" ConanFile of the recipe, but we realized that that produced a lot of confusion and unexpected behaviors. Making it explicit, and moving the base class to extend to something independent to the current python_requires one defining the package name and version seems to be working fine. It is not really pythonic, but this extensibility mechanism from packages that are still not even in the filesystem is quite special and particular of Conan package management, so I think this is good given the constraints of the problem being addressed.

> Also, I really like how easy it is to write such tests, awesome work!

Thanks! I recommend it to try it when debugging or checking things, it can really save a lot of time, and it makes easier to step and debug from the IDE if you use one.

Cool then, closing it, thanks for all the feedback!

**Closed as completed by memsharded** 2021-05-11 16:17 UTC
