### ISSUE TITLE
CMAKE_BUILD_TYPE not set for multi-config generators

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan#5448] opened 2019-07-04 12:54 UTC
`CMAKE_BUILD_TYPE` is not set for multi_config generators, even when explicitly set in the `CMake` constructor, as per the docs:

> build_type (Optional, Defaulted to None): Force the build type instead of taking the value from the settings. Note this will also make the CMAKE_BUILD_TYPE to be declared for multi configuration generators.

Conan Version: 1.15.0
CMake Generator: Visual Studio 15 2017 Win64

## Steps to reproduce:

1. Instantiate the `CMake` build helper, explicitly setting the build type
    ```.py
    cmake = CMake(self, build_type=self.settings.build_type)
    self.output.info(cmake.command_line)
    ```

2. Run a conan command that exercises the above code with a valid build_type and a multi configuration generator.

## Expected output

The cmake command should contain `-DCMAKE_BUILD_TYPE=<build_type>`

## Actual output

The `-DCMAKE_BUILD_TYPE` definition is missing from the command line.

I'm not sure what the actual behaviour should be, but the docs at least should be accurate. I came across this when building a package for a third-party library that automatically sets CMAKE_BUILD_TYPE to `Release` if it isn't set, and so all hell broke loose when I attempted to build a debug variant (The test package wouldn't link due to VS Debug Runtime linking errors)

**Comment by czoido** [comment] 2019-07-05 07:40
Hi @planetmarshall.
I think that the documentation has a mistake because `CMAKE_BUILD_TYPE ` will never be set
for CMake _multi-configuration_ generators such as Visual Studio or XCode as it would not have effect.
So the expected behaviour is that it only will be set if your CMake generator is _single-configuration_ such
as Ninja or Makefile Generator.
I hope this helps :) Thanks a lot for the observation

**Comment by planetmarshall** [comment] 2019-07-05 09:14
Yes this is fine by me - I think the package I was trying to build had an issue unrelated to Conan so I don't think there's any problem other than the documentation being incorrect.

**Comment by czoido** [comment] 2019-07-05 09:20
Thanks a lot. Closing the issue then.

**Closed by czoido** 2019-07-05 09:20 UTC
Labels: stage: triaging
