### ISSUE TITLE
Segmentation fault with conan 0.15.0 on a clean Windows system

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#704] opened 2016-11-28 10:51 UTC
When installing conan 0.15.0 on a clean Windows system (no prior conan install, no python environment, etc.), running `conan install` leads to a segmentation fault. Happened on two different (clean) systems.

**Comment by memsharded** [comment] 2016-11-28 12:12
Yes, seems very related, or even partly the same of https://github.com/conan-io/conan/issues/683

It seems to be something from the Win installer, still haven't found the issue, has we haven't been able to replicate it :( So no idea what it could be. Could you  please provide more detail about your clean Windows system? Windows 10? Native or as guest in a Virtual Machine? 64 bits?

We are strongly suggesting using python and the pip package. Installing it should only take a few minutes and everything is much smoother and more robust. Would it be possible for you?

**Comment by memsharded** [comment] 2016-11-28 16:40
Finally been able to reproduce it, something was broken in the machine that generated such installer. Conan 0.16 will be released tomorrow, with this (hopefully) fixed.

**Comment by Blubbz0r** [comment] 2016-11-29 08:28
Sorry for not responding, was a little busy yesterday. Sure, using the pip package is possible. However, as long as a Windows installer is provided, people will probably use it by default and expect it to work 😉

**Comment by memsharded** [comment] 2016-11-29 08:48
No worries! Yes, we try our best to fix issues and make it work. Today release conan 0.16 installer should work. I think we should re-arrange the downloads page to make it even clearer.
In any case, thanks very much for reporting!

**Comment by memsharded** [comment] 2016-11-29 10:42
Ran a few tests with the 0.16 win installer, everything seems fine now, but please reopen the issue if necessary, thanks!

**Closed by memsharded** 2016-11-29 10:42 UTC
Labels: fixed
