### ISSUE TITLE
[bug] Clang-12 support

### ISSUE THREAD

**Issue by Quincunx271** [conan-io/conan#8139] opened 2020-12-02 06:16 UTC
### Environment Details
  * Operating System+version: Ubuntu 18.04
  * Compiler+version: Clang 12
  * Conan version: 1.31.2
  * Python version: 3.9.0

### Steps to reproduce

 * Add LLVM apt repository: https://apt.llvm.org/
 * Run `sudo apt-get install clang-12`
 * Try to use conan when specifying clang version 12

### Logs

Running `conan install . -s compiler.version=12`

```
ERROR: Invalid setting '12' is not a valid 'settings.compiler.version' value.
Possible values are ['10', '11', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '4.0', '5.0', '6.0', '7.0', '7.1', '8', '9']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"
```

### Expected behavior

Clang 12 should be supported. Actually, I don't see why we need a max cap on the version number. Why can't we just allow future versions (perhaps just the next release) rather than having to make the change here in conan every time a new compiler version is released?

**Comment by memsharded** [comment] 2020-12-02 08:35
Because Clang12 has not been officially released yet: https://releases.llvm.org/download.html, and binary compatibility might change if the compiler version is not officially released, and that will break the Conan binary model. For example, the compiler default C++ standard might change (not that it happens that often, but it happens). Also compiler vendors might decide to change the versioning scheme, also affecting the default binary compatibility, as this has happened in the past with both gcc and clang.


What conan allows is to easily maintain your own settings.yml. You can add the version that you want to a copy of ``settings.yml``, and then manage it with ``conan config install``.

**Comment by memsharded** [comment] 2020-12-02 08:36
This would be a duplicate of https://github.com/conan-io/conan/issues/8033, so I think it can be closed, and tracked there. The moment Clang 12 is officially released, we will add it to our default settings. Thanks for reporting!

**Closed as completed by memsharded** 2020-12-02 08:36 UTC
Labels: type: question
