### ISSUE TITLE
[bug] tools.get(...) broken symlinks when extracting zip files

### ISSUE THREAD

**Issue by dmn-star** [conan-io/conan#9469] opened 2021-08-24 08:14 UTC
cc: @a4z 

The NDK r23 zip file contains the symlinks now. 
>lrwxr-xr-x  1 enh  primarygroup         8 Aug 23 12:47 clang -> clang-12
lrwxr-xr-x  1 enh  primarygroup         5 Aug 23 12:47 clang++ -> clang
-rwxr-xr-x  1 enh  primarygroup  75426096 Jul 30 17:06 clang-12

After unzipping we have two text files clang und clang++.
<img width="628" alt="symlinks" src="https://user-images.githubusercontent.com/52277783/130581648-a956ec08-2900-4d9e-805f-c69be6cb139a.png">

### Environment Details (include every applicable attribute)
  * Operating System+version: macOS Catalina 10.15.7
  * Conan version: 1.39
  * Python version: 3.9.1

### Steps to reproduce (Include if Applicable)

1) conan install android-ndk/r23@
2) $ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ --version
<img width="762" alt="ndk23_failed" src="https://user-images.githubusercontent.com/52277783/130581236-f2760798-ef47-4b18-954f-6f05cda3a1bf.png">

**Comment by a4z** [comment] 2021-08-24 10:31
History of how that got detected, starting from that comment on https://github.com/android/ndk/issues/1563#issuecomment-904013031 and below

**Comment by SSE4** [comment] 2021-08-26 14:28
the fix is: #8100

**Comment by dmn-star** [comment] 2021-08-28 07:08
As I see it correctly it should be fixed first in Conan v2. https://github.com/conan-io/conan/projects/30#card-34273494
/cc @jgsogo https://github.com/conan-io/conan/issues/6588

**Comment by a4z** [comment] 2021-10-03 20:10
There is a android-ndk on cci but it is unusable due to this bug 

What an user experience, coming back to conan after some month, updating some recipes, and things that used to work are broken, and conan is unusable for building for Android. 

please fix that bug , @uilianries @jgsogo @SSE4 , what's wrong you did not do it, do you hate your users that using that android-ndk via cci ?

**Comment by SSE4** [comment] 2021-10-04 06:03
@a4z as I have stated previously, the necessary fixes were already made like a year ago:
https://github.com/conan-io/conan/pull/8100
https://github.com/conan-io/conan/pull/8099
https://github.com/conan-io/conan/pull/8180
I've tried to reach several times to @memsharded, @tapia and @jgsogo to get them merged, but seems like there is no interest in these fixes
maybe because of other more important fixes, maybe because of conan 2.0 development, I don't know
maybe the fact that the bug breaks some packages (e.g. `android-ndk`) will help to realize their importance

**Comment by tapia** [comment] 2021-10-04 08:52
@a4z I'm sorry if this issue is frustrating to you, but I'm going to have to ask you to address the Conan team in a more respectful way. Of course there's nothing wrong with us, and of course we don't hate our users. We are working hard trying to make Conan better every day for everyone, as we've been doing for years. And, most of all, we are trying to make Conan a welcoming community and a pleasant workspace, and the tone you are using is the opposite of that.

If you don't like how we develop Conan, or you have some request or proposal, we are of course open to discuss (as we've always been), but rudeness and disrespect will not be tolerated, and that is not open for discussion.

Back to the issue at hand, the proposed changes are complex and extremely dangerous. They will break things in a lot of environments, and that would potentially affect thousands of users and hundreds of companies that are using Conan everyday. We are not rejecting the proposal (that's why we didn't close the related issues an PRs), but we must review this very carefully, study this and (most likely) other alternatives, and that takes a lot of time and we didn't have the time to do it yet.

**Comment by a4z** [comment] 2021-10-04 09:22
@tapia , I apologies for my clumsy usage of the English language, please keep in mind that this is not my first language.

On the ticket:

Are you telling me that Conan is not usable for things where you have to pack something like the NDK.
That a package with a link to a binary can not be used in general with conan? 

Are you telling me that you better do not use Conan, because you might end up with things breaking, and you will be on your own ? 

Are you respecting your users that have workflow that break, and it looks like you do not care? 
Because that is how it looks with that ticket.

The android-ndk is broken since r23, that is now several months, 
and users that have a workflow with conan and android ndk are screwed.
Is this welcoming?  

Do you know which stress that can create, in a time limited situation? 
Maybe not, because if you would, you might focus more on helping finding a solution rather than picking on me using English in a stupid way in such a stress situation.

 
So what is the summary at the moment?
The ticket is now 6 weeks old, and there is no official statement on how it will proceed. 
So what is the statement.
Continuation of silence that might be interpreted as ignoring the issue, that the NDK can not be packed?
Won'f fix, sorry , dear user you are screwed? And the recipe on the CCI is there just for fun and it looks nice, but don't use it because it will not work.

Or is there some hope that will be targeted in a reasonable time.

**Comment by a4z** [comment] 2021-10-04 14:20
@uilianries @jgsogo @SSE4 , I apologize for using inappropriate words when pinging you, my impression was you are in the power of moving that issue forward, but now I have been told you are not. I am sorry about that.
If you have nay idea how that could be solved, or at least a clear statement is there (like, please use an external ndk and point to it in your profile) I would be very thankful. 

PS: I would also like to mention that the translation of what I wrote, (do you hate your users) is in the city I come from, translagted word for word,  not hostile but more something you use with a blink in the eye )

**Comment by lasote** [comment] 2021-10-05 07:57
>  I apologize for using inappropriate words when pinging you, my impression was you are in the power of moving that issue forward, but now I have been told you are not. I am sorry about that.

Are you saying that the people with "power of moving that issue forward" deserve that language? 

Look, WE DO care about your issue, we talked about the symlinks issue several times, we reviewed the @SSE4 approach and we know it is very dangerous and potentially breaks many users. You can see the number of open issues we have in the repository. Have you considered that could be even more important issues there than the Android NDK package? We will attend to this issue, according to our planning, but bullying and pushing non politely is not the way to do it. So please, stop it. We are not spending more time giving explanations about our planning and schedule.

I would like to link the code of conduct of the repository we wrote a long time ago, I will propose today to update it to include specific actions in case of recurrent non-proper behaviors, which will include banning people from the repository.

https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md#code-of-conduct

**Comment by a4z** [comment] 2021-10-05 10:01
> Are you saying that the people with "power of moving that issue forward" deserve that language?

no, and it would be more productive if you would focus on the other part I added to the text, explaining how it was meant (blink in the eye and a translation problem). 
It is remarkable that you do not and continue try to put me in a bad spotlight. But also shows where bad intend is, for sure not on my site.

No worries, I will take some distance anyway since the last thing I need is people try to insinuate something for my enthusiasm.
And sorry for highlighting a bug in conan that is know for years and not mentioned in the docs,  where the symlinks docs of the self.copy call is just wrong.

**Comment by dmn-star** [comment] 2021-10-06 08:57
> Have you considered that could be even more important issues there than the Android NDK package? 

Don't get me wrong but there really is hardly anything more important than a working CI, especially when you are just about to release your soft. And without the android-ndk recipe, you simply can't build and publish anything for Android without major modifications.

**Comment by lasote** [comment] 2021-10-06 12:36
@dmn-star I agree if you were targeting Android (low percentage of users of Conan) and especially the Android NDK conan-center recipe. There were always different alternatives like setup the NDK in the CI machine and just write a profile. That is especially easy with the new toolchains model we are developing for Conan 2.0, but I know companies doing that for years with 1.X versions. The usage of Conan is huge and Conan is much more than conan-center. So, a working CI is almost the most important, indeed I agree! but a bug affecting how a zip is extracted when native python code doesn't even support symlinks in a zip file... is not, even more, when there are workarounds.

**Comment by memsharded** [comment] 2021-10-06 13:55
@dmn-star I would also like to add: It is not that Conan client did change something and broke something that was working. That would be a regression, and a different level of priority. The recipe should keep working for previous AndroidNDK releases. The issue is that Android changed the way they are zipping new releases, and the Conan client cannot easily support that new way without a high risk of breaking other CI of other users. To add a bit more data to the above, private CIs, users using privately maintained recipes (own recipes, forks of conan-center-index), is way larger than users directly depending on ConanCenter, by more than 80%.

**Comment by a4z** [comment] 2021-10-06 15:08
> .... To add a bit more data to the above, private CIs, users using privately maintained recipes (own recipes, forks of conan-center-index), is way larger than users directly depending on ConanCenter, by more than 80%.

And the reason for that is simply explained:

Its fast to take a CCI recipe and add it to some private place, maybe with some adoptions so it works for the current use case.
And then copy from time to time required updates.

Contributing back to CCI can eat very very many hours, sometimes even with painful review processes, and delayed over days if not longer and you always need to pick up (for you done) old working contexts.
This is nothing companies want to pay for and/or want to go through.  Copy , adopt, works for me, done - is the usual company use case.
(And this is btw why nearly all I ever contributed upstream to CCI happened on my private time account)

But I would be aware of playing  down the role of CCI, especially also for those that just copy from it, or take it as inspiration for their private recipes. That could create the impression the whole picture is not seen here.

For the issue, the fix provided now, [I would possible not have been able to do that within days](https://github.com/conan-io/conan-center-index/pull/7552) ... , since it's not covered in any docs and I am just a user, depending on conan. 
And I can well imagine that that change will be transferred into the one or other private place that make up the 80% also.

**Comment by memsharded** [comment] 2024-09-15 01:03
Closing as outdated

**Closed as completed by memsharded** 2024-09-15 01:03 UTC
