### ISSUE TITLE
[bug] export-pkg doesnt invoke package_info

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#9403] opened 2021-08-09 16:15 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: -
  * Conan version: 1.39
  * Python version: 3.9.5

### Steps to reproduce (Include if Applicable)
```
class HelloConan(ConanFile):
    name = "hello"
    version = "0.1"
    settings = "os", "compiler", "build_type", "arch"

    def package(self):
        print("nothing")

    def package_info(self):
        raise Exception("broken")
        self.cpp_info.libs = self.collect_libs()
```

Run above conanfile with
`conan export-pkg "path\to\file.py" --force`

Exception is not thrown, if I use create instead of export-pkg it is thrown.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
Exporting package recipe
hello/0.1: A new conanfile.py version was exported
hello/0.1: Folder: C:\Users\AU000M8R\.conan\data\hello\0.1\_\_\export
hello/0.1: Using the exported files summary hash as the recipe revision: d69d63773c80125db5477f41b0f8e075
hello/0.1: Removing the local binary packages from different recipe revisions
hello/0.1: Exported revision: d69d63773c80125db5477f41b0f8e075
hello/0.1: Forced build from source
Packaging to db1f521f32800c87175a09b83ba17cc52143a109
hello/0.1: Generating the package
hello/0.1: Package folder C:\Users\AU000M8R\.conan\data\hello\0.1\_\_\package\db1f521f32800c87175a09b83ba17cc52143a109
hello/0.1: Calling package()
nothing
hello/0.1 package(): WARN: No files in this package!
hello/0.1: Package 'db1f521f32800c87175a09b83ba17cc52143a109' created
hello/0.1: Created package revision 42f5237ab686b20baf2742947ead729b
```

**Comment by memsharded** [comment] 2021-08-09 18:33
Hi @GitHubAre 

This is not a bug. The ``package_info()`` method is information exclusively for the consumers. When calling ``conan export-pkg`` there are no consumers, so it is not necessary to call this method at all. The case is different from the ``conan create``, which will call the ``package_info()`` method, because the information for consumers is necessary in case there is a ``test_package/conanfile.py`` consumer that will test the package. I guess it is possible to even optimize that call, and make ``conan create`` not call ``package_info()`` if there is no test_package, but that is extra work probably not worth the effort.

So this is not a bug, this is by design, you shouldn't rely on ``package_info()`` being called in ``export-pkg`` command, it won't be called because it is useless, it won't have any effect.

**Comment by memsharded** [comment] 2021-08-09 18:35
Sorry, wrong button, I didn't intend to close it. Please let us know if the above makes sense, thanks!

**Comment by ghost** [comment] 2021-08-09 20:12
Hello @memsharded 

There is a documentation link https://docs.conan.io/en/latest/creating_packages/existing_binaries.html
I also agree with the documentation and it actually is something user might want to use.
Documentation mentions `package_info `together with `export-pkg`

My use case is that I package binaries that we build on server and we use conan to store multiple binary packages. I wanted to use `user_info `object to smugle in several properties and consume them on the other side. Instead I had to fallback to storing some json that I read on the consuming side.

**Comment by memsharded** [comment] 2021-08-10 08:53
Yes, the ``package_info()`` is totally necessary! The documentation is describing it, to make it clear that the package will not work unless this method is correct. That doesn't imply that it will be called when the ``conan export-pkg`` is done, but later, when the package is used. Most likely there were some issues with users reporting that their packages created with ``export-pkg`` didn't work when they tried to use them.

Your use case seems legit, and the flow seems also correct. This is for example the flow that some of the new features like the ``CMakeFileAPI`` (recently added, still not documented) would be doing: ``build()`` and ``package()`` which are called at "creation" time (conan create, conan export-pkg) can serialize any file or information that define what the package contains. Later, at "consumption" time, the ``package_info()`` method can load this file to provide this information to consumers. This is a perfect flow, decoupling the package creation and the package consumption, which is very necessary for binary reusing.

**Closed as completed** 2021-08-10 16:05 UTC
Labels: type: question, stage: triaging
