### ISSUE TITLE
[bug] `self.deps_cpp_info` of build_requirements is discarded when using a build profile

### ISSUE THREAD

**Issue by max-ag** [conan-io/conan#9499] opened 2021-08-30 13:56 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 20.04
  * Compiler+version: N/A
  * Conan version: 1.39.0
  * Python version: 3.8.10

### Steps to reproduce (Include if Applicable)

I'm trying to package a toolchain with Conan, specifying the `cpp_info.sysroot` in the `package_info` method.
When specifying the toolchain as a `build-requires` in a profile, and using the profile with `-pr:h <profile>` when building a consumer package, the `deps_cpp_fin.sysroot` in the consumer package contains the expected value. However, when specifying both a host and a  build profile, the `deps_cpp_fin.sysroot` is empty. Is this a bug, or am I misunderstanding how this is supposed to work ?

```python
# package1/conanfile.py

from conans import ConanFile

class Package1(ConanFile):
    name = "package1"
    version = "1.0"

    def package_info(self):
        self.cpp_info.sysroot = "/path/to/sysroot"
        self.env_info.SYSROOT = "/path/to/sysroot"
```

```python
# package2/conanfile.py

from conans import ConanFile

class Package2(ConanFile):
    name = "package2"
    version = "1.0"

    def build(self):
        print("sysroot={}".format(self.deps_cpp_info.sysroot))
        print("SYSROOT={}".format(self.deps_env_info.SYSROOT))
```

```
# myprofile

[settings]
os=Linux
arch=armv7
compiler=gcc
compiler.version=9
compiler.libcxx=libstdc++11
build_type=Release

[build_requires]
package1/1.0
```

When only using the host profile

```bash
 $ conan create . -pr:h myprofile

[...]
sysroot=/path/to/sysroot
SYSROOT=/path/to/sysroot
```

When using both the host and build profile

```bash
 $ conan create . -pr:h myprofile -pr:b default

[...]
sysroot=
SYSROOT=/path/to/sysroot
```

**Comment by memsharded** [comment] 2021-08-30 15:04
Hi @max-ag 

Thanks for your detailed report. This is expected behavior. Maybe it needs to be written more evidently but in https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-build-requires, it explains how the environment is propagated to the consumer of the build require. The ``cpp_info`` is not propagated, because a build_requires in the build context is not supposed to have includedirs/libdirs/libs, etc, otherwise it wouldn't be a build_require, but a regular require.

Also, when using the 2 profiles, it would be recommended to start using the new integrations in https://docs.conan.io/en/latest/reference/conanfile/tools.html, that will implement support for the cross-compile scenarios with the 2 profiles fully. 

The way to access dependencies information is also changing:
- Recommended to use the ``generate()`` method to collect necessary information from the build and generate build files.
- Recommended to use the ``dependencies`` model, https://docs.conan.io/en/latest/reference/conanfile/dependencies.html, from the ``generate()`` method to access the dependencies information.

**Comment by max-ag** [comment] 2021-08-30 15:18
@memsharded, Thanks for the quick reply.

The example to package a toolchain in https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#using-build-requires sets the SYSROOT environment variable, which is what I was originally doing. It works fine with most projects.

However, trying to cross-compile projects that use the `AutoToolsBuildEnvironment` fail because the `AutoToolsBuildEnvironment` uses `self.deps_cpp_info.sysroot` to pass the `--sysroot` command line argument to the compiler.

**Comment by memsharded** [comment] 2021-08-30 15:38
Yes, that is possible, the legacy generators as ``AutoToolsBuildEnvironment`` use information only from ``deps_cpp_info``, and they rely on the fact that the environment will be defined. If some autotools build scripts do not read and use the ``SYSROOT`` env-var, to avoid overwriting it with its local information, it is possible that it is not fully working. 

These issues might be difficult to change without breaking, this is the reason we are starting to recommend to try and report on new integrations, like ``AutotoolsDeps``. I think ``AutotoolsDeps`` do not support sysroot either, but in this case it would be easier to define the correct behavior and fix things, without fear of regressions.

**Comment by max-ag** [comment] 2021-08-30 15:43
Makes sense. I'll have a look at the new integrations. Thanks.

**Comment by memsharded** [comment] 2023-02-07 22:23
Closing this, new integrations now use ``self.dependencies``, and ``self.deps_cpp_info`` is deprecated.

**Closed as completed by memsharded** 2023-02-07 22:23 UTC
Labels: type: question
