### ISSUE TITLE
Feature Requests: Multiple Versions per Recipe

### ISSUE THREAD

**Issue by Lnk2past** [conan-io/conan#3734] opened 2018-10-11 20:19 UTC
What I am about to request for consideration are inspired by the [Spack package manager](https://spack.io/). So far I have not found great ways to do what I want; I have messed around with some work-arounds, but they are undesirable solutions.

My motivation for the request is that I want to be able to manage a single recipe for multiple versions of the same library.

### Multiple Versions

Add a new attribute for listing the versions the recipe supports. Right now we do the following for pretty much all of our recipes:

```
    def source(self):
        checksums = {
            '3.6.0': '1532154addf85080330fdd037949d4653dfce16550df5c70ea0cd212d8aff3af',
            '3.6.1': 'fd65488e618032ac924879a3a94fa68550b3b5bcb445b93b7ddf3c925b1a351f'
        }
        source_url = 'https://github.com/google/protobuf/releases/download/v{0}/protobuf-all-{0}.tar.gz'.format(self.version)
        tools.get(source_url, sha256=checksums.get(self.version, ''))
```

Then as versions have specific recipe requirements we insert the necessary conditionals. This list of versions (and their hashes) should be an attribute of the class that Conan recognizes and can report on (e.g. report on these versions from a ```conan info```).

### Default Version

I would like to be able to omit the version and use whatever is in the ```conanfile``` as well as be able to override that version with a new one.

```
conan create . foo/1.0@lnk2past/stable
conan create . foo/2.0@lnk2past/stable
conan create . foo/3.0@lnk2past/stable
conan create . lnk2past/stable
```

Right now it is either one or the other, specify the version every time or use what is specified in the ```conanfile```. I would like the existing ```version``` attribute in the ```conanfile``` to act as a default version. Right now specifying a version that does not match results in an error. I can make all of the versions in my recipes equal to 'default' and adjust the version dynamically, but that is clunky and pretty error prone in the long run.

In the long run I think these two features would go a long way to improve the Conan experience, for both package maintainers and consumers.

**Comment by danimtb** [comment] 2018-10-12 08:56
Hi @Lnk2past,

Your request seems doable even right now as you pointed out. I think it will be doable with something like:

```
from conans import ConanFile, CMake, tools

class SociConan(ConanFile):
    name = "soci"
    version = ("myversion", "otherversion")
    license = "Boost Software License"
```

Then you could benefit from the new `conan inspect` command to get the versions and create the one you want:

```
$ conan inspect .
name: soci
version: ('myversion', 'otherversion')
url: https://github.com/SOCI/soci
...

$ conan create . soci/myversion@danimtb/testing
...
```

Currently the last step does not work.

Thanks for the proposal!

**Comment by lasote** [comment] 2018-10-15 08:30
I don't like the idea of having an attribute `version: ('myversion', 'otherversion')`.
I think it could be better to:

- Have a `default_version` attribute (in case the version is not specified exporting it will use it when available)
- Have a `versions` attribute (the exported version will be checked against the valid list of versions). It can be inspected with `conan inspect` command.

**Comment by lasote** [comment] 2018-10-15 08:35
The implementation could be quite simple (missing tests and documentation): https://github.com/conan-io/conan/compare/develop...lasote:feature/poc_versions?expand=1

Feedback is welcome @memsharded @danimtb @jgsogo

**Comment by jgsogo** [comment] 2018-10-15 09:28
I think both ``default_version`` and ``versions`` make sense, but I have some doubts. On one hand, I like the idea of reusing the same ``conanfile.py`` as much as possible; on the other hand, I like recipes to be as straightforward, clean and clear as possible. ...and if you give the option, people are not force to do it, but will 😄

**Comment by Lnk2past** [comment] 2018-10-15 17:30
Most minor and patch versions will use the same exact recipe, whereas major versions will likely need new logic in place (or old logic removed). I agree that opening this up could make recipes blow up, but I would rather have 1 recipe with varying sets of logic than a new recipe for every minor or patch version released.

Spack provides a convenient version utility for comparing versions to versions, while also supplying a wildcard syntax for limited ranges, maybe Conan can adopt something similar.

**Comment by jgsogo** [comment] 2018-10-16 08:43
I agree, it makes sense to use some kind of wildcards. I don't want an endless list of versions in the ``versions`` attribute to match any patch version. 

Avoid ``versions = "1.1", "1.1.1", "1.1.2", "1.1.3",... "1.1.34"`` in favor of ``versions = "1.1", "1.1.*"`` or even better ``versions = "1.1"`` matching every ``1.1[.x]`` (if not ``1.1.x`` is given explicitly).

(Just thinking in loud voice 🤔 )

**Comment by Aalmann** [comment] 2018-10-16 09:50
Hi @All

I just want to give you my point of view and probably some (missing) thoughts. 

This feature can only be used when having recipes in a separate repo than the source code. It is definitely useful but should be handled with care. If the recipe is in source repo it is not required (IMHO there is no use case due to "auto-copy/-existence" of recipe in each branch/tag/release).

We (my team) currently use the same approach of having the recipes in one single repo as a single entry point and separated from source and copy the recipes for each new version (btw. we will move the recipes to the source repos as soon as possible, but that's not the point of this issue). 
Within each version recipe we have the scm-reference (branch / commit / tag) as option set to be able to build different packages for different feature branches (`resulting package count = 1 * platform count * feature branch count * other options`). This works well as long as the dependencies / requirements do not change from branch to branch (e.g. using / updating to a newer version of a library). If so, this has to be handled in the recipe by evaluating the scm-reference option and changed in the recipe (within the recipe repo) after merge of feature branch (within the source repo). This is a bit error prone but one can handle it.

With the version list there will be a new dimension of complexity, because one has to handle the different requirements for different versions and probably (temporary) for different feature branches.

Another point is the (missing) ability to reproduce old versions. Changing the "multi-version-recipe" will always result in a different recipe-hash (md5/sha1/sha256). Rebuilding an older version from recipe in recipe-scm-repo will / may cause different packages than the old ones (already released and published years ago). The only way to exactly reproduce them is to build from recipe in Artifactory / Bintray / Conan server (assuming the scm source reference in old recipe points to the exact same version). 


And there is still another "dimension": If python_requires or other Python helper packages are used within the recipe one will use one version of it for the first recipe/module/product version in version list (and probably also for the next 2 or 30 recipe/product/module versions). But one time there will be a need to update this reference to a newer version (e.g. using "newer" conan features like `should_build` which could be part of a helper or python_requires package [just as an example to illustrate] or because of bug fixes). Then there are only two ways to handle it:

1. Create a new recipe with a new version list which uses the newer helper / python_requires. Then one will have at least two (different) recipes for each range of versions. Questions here: How to name the recipes or the folders where they are stored? Folder-`1.0.0_1.2.3` (which contains one conanfile.py for version list 1.0.0 to 1.2.3) and folder-`1.3.0_latest` (which contains one conanfile.py for version list 1.3.0 to latest version which could be 1.9.4)? And how could this be handled in a good and reliable way in CI/CD environments? And how to handle if there is another helper version required (renaming folder-`1.3.0_latest` to folder-`1.3.0_1.9.5` and creating a new folder-`1.10.0_latest`? (possible but hard to do)
2. Still using one single recipe with a lot of `if` and `else` and a really big complexity ("non-human-readable") 


But the problem with the rebuild of / ability to reproduce older version is still present. So IMHO if the current recipe can't be "reused" to (re-)build the older versions, because the result is different, the complete approach of this feature should be discussed and not the implementation details.

Again: This is just something to think about. I'm fine if this feature will be implemented in one of the next conan versions, but then it should be very good documented (use cases, do's and don'ts, etc.).

Best Aalmann

**Comment by bobeff** [comment] 2018-10-16 16:32
@lasote But maybe some way to declare the supported range of versions for a given recipe is also a good thing to have?

**Comment by lasote** [comment] 2018-10-17 10:58
I don't know, probably changing the recipe just to declare that we support a new version when the recipe already supported the new version without any change is not a good idea. But let's keep this open to get more feedback.

**Comment by Lnk2past** [comment] 2018-10-17 18:00
honestly, I would be very OK with Conan just not erroring out when the supplied version does not match the version encoded in the recipe.

**Comment by Aalmann** [comment] 2018-10-17 18:08
@lasote
What's about `version = "auto"` like in scm feature?
This could be replaced by version given in `conan export` or `conan create` command by the given command line reference.

**Comment by Aalmann** [comment] 2018-10-17 19:48
@Lnk2past and @lasote 
Something like this should fit the use cases:
```python
...
version = "auto" # will be "hard" replaced at export time and assigned with default_version value if not given at command line
default_version = "1.2.3" #only used when no version is set from command (like "conan install .")

# and a dict for version to checksum mapping
version_checksums = {
    "1.2.0": "1234567890abcdef...",
    "1.2.1": "0987654321fedcba...",
    ...
}

def source(self):
   chksum = self.version_checksum(self.version) # at this point version is NOT "auto"
```

**Use case 1:** _Use recipe for development_
`conan install .` will set version to `default_version` at initialization of ConanFile. Recipe is left unchanged (because it is not exported).

**Use case 2:** _creating a package just with user name and channel_
`conan create . user/channel` exports the recipe, replaces `"auto"` with value of `default_version` in exported recipe (like scm feature).
Point to be discussed: Throw an error if `default_version`is not set or use `"auto"` as version string?

**Use case 3:** _creating a package with full reference_
`conan create . name/1.2.3@user/channel` exports the recipe, replaces  `"auto"` with the version in reference in exported recipe (like scm feature) and `default_version` is ignored.

Anything missing?

Best Aalmann

**Comment by jgsogo** [comment] 2018-10-23 08:46
> Is there a particular reason to enforce that versions on the commandline and in the recipe match?

The uploaded recipe (version written in `conanfile.py`) has to match the uploaded package; so, if Conan lets you override the version declared in the recipe, it should substitute it before exporting it to the cache (this is what we do in the _scm feature_ with the keyword `"auto"`).

**Comment by Lnk2past** [comment] 2018-10-23 11:10
>... it should substitute it before exporting it to the cache

@jgsogo it seems like a trivial modification to Conan's behavior. If it is already done with the _scm feature_'s ```auto``` keyword then I imagine the same handling can be done for the ```version``` attribute.

**Comment by Lnk2past** [comment] 2018-10-30 18:33
@lasote, any more thoughts on this?

**Comment by lasote** [comment] 2018-11-23 08:05
Not really, I think it adds more complexity and implicit behavior than the benefit.

**Comment by melMass** [comment] 2021-04-17 22:36
This kind of solves this issue no?
https://github.com/conan-io/conan/issues/3741#issuecomment-429731992

**Comment by memsharded** [comment] 2023-03-03 16:59
Creating multiple versions per recipe is the approach that we are doing in ConanCenter: https://github.com/conan-io/conan-center-index. The key for this is a hook that trims the unwanted versions (all except the one being created) from ``conandata.yml``

It works pretty well for third-parties (source code not under development, but static, and out-of-source recipes), but will hardly work for in-source recipes for your own packages that are under active development and evolution. Closing this ticket as solved.

**Closed by memsharded** 2023-03-03 16:59 UTC
Labels: priority: low, type: feature, Feedback please!, stage: queue, complex: medium

**Comment by Corristo** [comment] 2023-03-12 15:57
@memsharded Could you please go into more details on how this works? I failed to find said hook in the conan-center-index repository, but I'd also be interested in setting up my recipes in the same way conan-center-index does.

**Comment by memsharded** [comment] 2023-03-12 21:26
The Conan center hooks are in the "hooks" repo, together with other hooks, you can find them here: https://github.com/conan-io/hooks/blob/master/hooks/conan-center.py

A note about your recipes. The ConanCenter approach works well for third-party sources. For packaging your own sources (source that you write yourself), it can be much better having the recipes in the source repo.
If you are interested in that, you might be interested in some current effort in the ``conan-extensions`` repo, where custom commands to help managing a repo like conan-center-index are being added: https://github.com/conan-io/conan-extensions/pulls

**Comment by Corristo** [comment] 2023-03-18 22:59
Thanks for the pointers. I've managed to make it work by using a slightly modified version of the disabled conan v2 conan-center hook from the hooks repo and a custom command to export all versions of the recipes based on the cmd_list_v2_ready.py command from the conan-extensions repo.
