### ISSUE TITLE
Can't build the package. And conan won't look in alternative repos.

### ISSUE THREAD

**Issue by kentkost** [conan-io/conan#3813] opened 2018-10-20 11:29 UTC
Tools used: Conan 1.8.4, Windows 10, Visual Studio, compiler.version=14, jenkins, personal artifactory remote.

Sitting with a project that requires boost_spirit. Which is added via the conanfile.py  using the requires attribute. It gets it from this remote:

https://bintray.com/bincrafters/public-conan/boost_spirit%3Abincrafters/1.66.0%3Astable, we'll call it it bincrafters

After the build is done it uploads the build package and all boost packages that got downloaded from bincrafters. Now the problem is that when I go to do a second build with different settings (ie. different architecture or build_type) it tries to get the packages from my personal remote. Which is fine - I want to use my remote as a kind of caching. However when it fails to find the packages for the build it will try to build the package itself from what it already has in my remote instead of searching the additional remote(ie. finding the correct package from bincrafters).

It doesn't matter if I set -_-build=missing_ or not. If it is set it will try to build the package from whatever information it can get from my remote it will fail(missing .jam files) and I doubt it is avoidable. If _--build_ is not set conan will complain about missing packages and recommend that I try setting building the packages. 

Now I understand in registry.txt we can't just have all hashes for a package point to a remote. But it would really be beneficial if it kept looking for the package in other remote when _--build_ is not set.

**Post Conan 1.9**
This works now. Without saying that the build is missing conan will look in other remtoes for the packages and download them. This issue can now be closed.

**Comment by lasote** [comment] 2018-10-20 11:42
was this working with conan 1.7 or haven't check?

**Comment by lasote** [comment] 2018-10-20 11:45
By the way, the registry for binary packages will be introduced in Conan 1.9. it is already merged to develop branch.

**Comment by kentkost** [comment] 2018-10-20 11:53
Haven't checked with 1.7.

Any chance of getting conan 1.9 early?

**Comment by danimtb** [comment] 2018-10-22 15:04
We have no fixed deadline for 1.9

You can always run Conan from source in editable mode using the develop branch: https://github.com/conan-io/conan#from-source

Regarding your issue: If you explicitly indicate the remote in the command line it will only search in that remote. This could be the reason.

Could you share the steps you followed to reproduce this behavior?

**Comment by lasote** [comment] 2018-10-26 07:11
Assigning to 1.10 to make sure that it has been solved when we release 1.9

**Comment by kentkost** [comment] 2018-10-31 10:39
Installed conan 1.9.

and created my packages without "--build=missing"

This worked wonderfully. This issue can now be closed.

**Closed** 2018-11-05 14:12 UTC
