### ISSUE TITLE
Hash collision (CMake lib / lib64)

### ISSUE THREAD

**Issue by guyguy333** [conan-io/conan#2910] opened 2018-05-18 13:03 UTC
Hello,

I'm packaging a private project A using CMake. This project installs the library in `lib` or `lib64` depending of the OS (various Linux distributions). It is default behavior using `GNUInstallDirs`. Let's suppose I build my package on CentOS 7 and Ubuntu 14.04. Both have GCC 4.8, are Linux, etc... So the resulting hash is the same for both packages.

```
self.cpp_info.libdirs = ['lib', 'lib64']
```

However, there is a deal. With CentOS 7, the library is installed in `lib64` whereas with Ubuntu 14.04, the library is installed in `lib`. So, when I push my package to my Conan server, as the hash is the same, the second upload overwrites the first one even if the tar archive is different.

Now, let's suppose a project using my package A. Depending of the package really available on the server (Ubuntu 14.04 or CentOS 7), CMake is unable to find the `Config.cmake` file because in one case it is in `lib64` whereas the OS expects it to find it in `lib`. Indeed, CMake will not search in `lib64` if the OS uses `lib`. See last paragraph https://cmake.org/cmake/help/v3.0/command/find_library.html for more informations.

Maybe Conan should produce packages with different hashes even if libraries are ABI compatible. Or Conan could change CMAKE prefix path adding what's in `cpp_info.libdirs`.

Thanks

- Conan version : 1.3.3
- OS : Various Linux distributions

**Comment by danimtb** [comment] 2018-05-18 14:20
HI @guyguy333,

I think when you say "hash" you are talking about the package ID to define the ABI compatibility. AFAIK, binaries for Ubuntu are ABI compatible with CentOS ones, so Conan is doing it well creating the same package ID (as settings would be the same -Linux-, as you pointed).

I suposse you are consuming upstream packages for package A via CMake's find_package() -not using *conanbuildinfo.cmake* file-. So what  I think you are highliting here is the different behaviour of CMake when looking for packages in Ubuntu and in CentOS, which has less to do with the way Conan computes the IDs than the way things are modeled inside you recipe or the way CMake `find_package()` works.

For the latest, there some ongoing efforts in #2875 to provide a easy ussage of CMake and its `find_package() `feature (mostly for consumers) with two new conan generators that would probably address your issue.

In the meantime, I guess you could  generate those *Config.cmake* files in both *lib* and *lib64* inside your recipe and point them to the paths to the right folders.

**Comment by guyguy333** [comment] 2018-05-18 15:14
Thanks @danimtb,

> I think when you say "hash" you are talking about the package ID to define the ABI compatibility. AFAIK, binaries for Ubuntu are ABI compatible with CentOS ones, so Conan is doing it well creating the same package ID (as settings would be the same -Linux-, as you pointed).

I agree

> I suposse you are consuming upstream packages for package A via CMake's find_package() -not using conanbuildinfo.cmake file-. So what I think you are highliting here is the different behaviour of CMake when looking for packages in Ubuntu and in CentOS, which has less to do with the way Conan computes the IDs than the way things are modeled inside you recipe or the way CMake find_package() works.

Exactly, we're using `find_package`.

> In the meantime, I guess you could generate those Config.cmake files in both lib and lib64 inside your recipe and point them to the paths to the right folders.

I would prefer to avoid to change CMake files in the project. Instead, I prefer to do some files copy inside `conanfile.py` (what I just did). However, it looks like this issue applies to all Conan packages packing existing CMake projects. Every time someone will package an existing project using CMake, it will have to copy *Config.cmake* files. Maybe there should be helpers in Conan ?

**Comment by danimtb** [comment] 2018-05-18 15:40
Thanks for the clear answer. Please have a look at what PR #2875 is proposing, I think that is exactly your use case.

**Comment by memsharded** [comment] 2018-05-19 07:46
I think the issue here is that it would be necessary to customize the settings.yml for the use case. So the options would be:

- Make the package recipe to package things to "lib" always, not to "lib64", no matter which distro. This might be achieved adjusting the ``self.copy()`` patterns. The idea is that if the package ID is the same, the package must be the same, otherwise the package recipe is not correct.
- Introduce a "distro" or the like custom settings into settings.yml (distribute it to your team with ``conan config install`` command). Could be a subsetting of the "Linux" OS settings. With this new setting, packages will automatically get a different ID for different distros.

Please tell if this clarifies the issue. Thanks!

**Comment by danimtb** [comment] 2018-12-05 12:38
This was also caused by the variability on the output directories in CentOS vs Ubuntu that we fixed in #3599  and the proposed solutions above should also fit your use case.

I am closing this but please feel free to reopen or comment if needed. Thanks!

**Closed by danimtb** 2018-12-05 12:38 UTC
