### ISSUE TITLE
Using version ranges unexpectedly fails to find package in remote

### ISSUE THREAD

**Issue by keithrob91** [conan-io/conan#3113] opened 2018-06-26 14:37 UTC
conan version 1.4.5

We have a recipe that states:
requires = "Foo/[>2.1.0,<2.2.0]@dev/testing"

And in a artifactory "testing" remote we have 1 version of Foo:
Foo/2.1.3@dev/testing

And in a artifactory "release" remote we have 1 version of Foo:
Foo/2.2.0@dev/testing

conan remote list:
release: ...
testing: ...

So, we want our recipe to use 2.1.3 not 2.2.0. But we get the error "ERROR: The version in '>2.1.0,<2.2.0' from requirement 'Foo/[>2.1.0,<2.2.0]@dev/testing' could not be resolved"

Now if we remove Foo/2.2.0@dev/testing from "release" it works and the "testing" version is resolved

However, if we use (no version range):
requires = "Foo/2.1.3@dev/testing"

and put Foo/2.2.0@dev/testing back into "release" it works, and the "testing" version is resolved.

i.e. With version ranges the incompatible Foo within the "release" remote _blocks_ the compatible one in the "testing" remote. But using version string syntax it resolves to the version in "testing" as expected.

**Comment by memsharded** [comment] 2018-06-26 14:52
Just to be clear, this is not a regression, is it? Does it work in previous versions of conan?

**Comment by keithrob91** [comment] 2018-06-26 14:55
We're trialling Conan and only just found this while experimenting with version ranges. So, I have no idea if it is a regression I'm afraid.

**Comment by memsharded** [comment] 2018-06-26 15:04
I am having a look and this seems no regression. The version ranges are not resolved against all possible remotes, they are evaluated until the Foo reference is found, and once the first occurence is found, it doesn't keep searching. Indeed only related to version ranges, exact versions shouldn't behave like this. We need to have a deeper look at this, thanks very much for raising this issue.

However, it sounds a bit problematic trying to resolve the same package from different remotes. It is ok to have remotes testing/release, but looks to me like they shouldn't be used at the same time! :) Do you want to deploy by mistake testing packages? It is also ok to use different remotes for different purposes and use packages from them, for example from the company main repo (very common libraries) and from the project repo.

**Comment by keithrob91** [comment] 2018-06-26 15:38
Being honest, we found this issue by mistake, we didn't realise Foo was also in the release remote!

However, we do see a scenario where the same package is in both release and testing, **but**, the user/channel would be different not just the version, e.g.:

release: Foo/2.2.0@release/stable
testing: Foo/1.1.1@dev/testing (maybe a maintenance release)

So, in this case I'm guessing the issue would not show up, and packages requiring Foo would want either release/stable or dev/testing and they would get the right one?

**Comment by memsharded** [comment] 2018-06-26 15:44
Yes, your analysis is good, and this is probably the reason this hasn't shown up so far. Yes, the version ranges are resolved doing a search with the pattern ``Foo/*@release/stable``, so it will work as expected in that case.

**Comment by d70-t** [comment] 2019-07-25 18:59
I'm having a similar issue and it looks like a regression.

When using conan 1.12.3, I could have a dependency to `"yaml-cpp/[>=0.6.0]@mim/stable"` in my conanfile.py
Issuing a `conan install .. ` in my build folder correctly figured out that `"yaml-cpp/0.6.0@mim/stable"` is available from the remote `mim`, downloaded it and installed it correctly.

Now, in conan 1.17.2, the same `conan install ..` fails with:

> ERROR: Version range '>=0.6.0' from requirement 'yaml-cpp/[>=0.6.0]@mim/stable' required by 'conanfile.py (rayli/0.0.5@None/None)' could not be resolved in local cache

After running `conan install 'yaml-cpp/0.6.0@mim/stable'`, the exact same `conan install ..` runs flawlessly.

Both tests have been conducted from a fresh ubuntu image inside a docker container using:
```bash
#!/bin/bash
apt-get update
apt-get install -y git gcc libtool cmake python python-pip autoconf
#pip install "conan==1.12.3"
pip install "conan==1.17.2"
conan remote add mim <some internal remote>
conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan True
conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz True
mkdir build
cd build
conan install ..
```

**Comment by memsharded** [comment] 2019-07-25 21:44
Hi @d70-t 

Just to rule out other possible things, could you please try using a package from ``conan-center`` repo? That way we could reproduce exactly the same situation, and know it is a client thing, and not something in the server side. Also, just to make sure, the conanfile to reproduce, even if it is simple conanfile.txt with a single requirement. Also, it the issue can be reproduced directly with ``conan install pkg_name/[version-range]@user/channel``

Please let us know and we will try to help. Thanks!

**Comment by d70-t** [comment] 2019-07-26 00:03
Hi @memsharded,

thanks for the quick reply. Unfortunately, currently I can not reproduce this behavior on packages from `conan-center`.

Regarding your other comments:

For version 1.17.2, `conan install "yaml-cpp/[>=0.6.0]@mim/stable"` results in:

> ERROR: Version range '>=0.6.0' from requirement 'yaml-cpp/[>=0.6.0]@mim/stable' required by 'virtual' could not be resolved in local cache

While under conan 1.12.3, the same command is again working as expected.

For the conanfile, a conanfile.txt with this content is sufficient to trigger the behavior:
```
[requires]
yaml-cpp/[>=0.6.0]@mim/stable
```

The internal server which has been used for the `mim` remote is the `conan_server` which comes with the pip installation of `conan==1.17.2` in both test cases.

While looking through conan-center, I found that yaml-cpp caught up there as well, so I replaced my requirements with `"yaml-cpp/[>=0.6.0]@bincrafters/stable"` to see what happens. The good thing is that my software is happy with the bincrafters version as well. The interesting thing is that there are still requirements to `netcdf-cxx/[>=4.3]@mim/stable` and `TCLAP/[>=1.2.2]@mim/stable` in my conanfile, which don't cause any problems. However, these packages are not available on conan-center. Is it possible, that having a package with the same name but different user on separate remotes causes this kind of problem?

**Comment by RemySphere** [comment] 2019-08-28 16:30
Hi, allow me to add my two cents:
We've been having the same issue with a package of our own that happens to be on 2 of our remotes.  
Remote A does not have a version that satisfies semver >=1.4.2 with the "testing" channel while remote B does.

Under Conan 1.18.1, this fails:
`conan install "SomePackage/[>=1.4.2]@user/testing"`

But this works:
`conan install "SomePackage/1.4.2@user/testing"`
`conan install "SomePackage/[>=1.4.2]@user/testing" -r remote-b`

I used CONAN_TRACE_LOG to maybe figure out what's happening, and interestingly enough it reads 2 rest api calls on remote A (the one without a qualifying package) : a ping and a search, then it yields the ConanException. Remote B does not seem to be probed at all.

**Comment by jasal82** [comment] 2021-07-22 12:31
This issue is still a problem in 1.38.0. Any chance that we can get a fix for it? Ping @memsharded

**Comment by jasal82** [comment] 2021-08-02 13:06
A bit of context on the problem: Each organizational unit in our company uses its own Conan repo (to simplify user management). All repos are added as remotes. Package names are always prefixed with the repo name to avoid ambiguity. For each of these repos there is another (read-only) release repository to guarantee the immutability of releases. Release repositories are always listed before the default repos in remotes.json, so resolving of release channel works fine. The order of the organizational units repositories is random though. If a fork of a project originating in unit A is created by unit B, the CI builds have to be adjusted to publish the packages into the repo of unit B. If now no further change is made to the combination pkgname/version@user/channel, there will inevitably be errors in the resolution, because Conan currently stops in the repo where the first matching package is located. This could be fixed by changing either the package name prefix or the user/channel for example but all of these methods require changes on the consumer side.

**Comment by Carsten87** [comment] 2022-03-21 15:00
@memsharded we ran into the same problem. We have a setup very similar to @jasal82:

- during development we push packages to a `staging` repository
- once a component is released we promote it to a `production` repository
- `production` has a higher priority than `staging`

Now let's assume the following packages are present:

- staging
    - pkg/1.0.0@user/channel
    - pkg/1.0.1@user/channel
    - pkg/1.1.0@user/channel
    - pkg/1.1.1@user/channel
    - pkg/1.1.2@user/channel
    - pkg/1.2.0@user/channel
    - pkg/1.2.1@user/channel
 - production
     - pkg/1.0.1@user/channel (this build has been released as 1.0)
     - pkg/1.1.2@user/channel (this build has been released as 1.1)

What this means is that version 1.2 of pkg is under active development, it has not yet been released and therefore is not yet available in `production`.
The problem now is that `conan install pkg/[~1.2]@user/channel` will fail with `ERROR: Version range '~1.2' from requirement 'pkg/[~1.2]@user/channel' required by 'virtual' could not be resolved in remote 'production'`. `conan install pkg/1.2.1@user/channel` will work as expected.

How can this be handled?

**Comment by DavidKeller** [comment] 2022-06-17 11:40
The surprising behavior seems to be caused by the following code

https://github.com/conan-io/conan/blob/f230bf104842c160be6ea377497151fe1ea64c38/conans/client/graph/range_resolver.py#L150

1. The first remote containing a recipe with the same name is selected
2. Then the version of this recipe is checked

A possible implementation would be to:

1. Save all recipes with a matching name, along side there associated remote, sorted by remote priority
2. On these recipes, select the first one with a matching version

Or:

1. For each remote
    1. Retrieve the recipes with a matching name
    2. Check the version of these recipes
    3. Return the recipe with current remote if version qualifies

**Comment by memsharded** [comment] 2022-06-17 11:53
Hi all

This was very difficult to resolve in Conan 1.X without breaking, but it has been already addressed in Conan 2.0

Installation of packages, and ``--update`` of packages will now iterate in the different defined remote repositories to define which one is the latest satisfying the range, not just the first one, and there is no association between cache recipes and remotes.

I am closing this as solved in 2.0, the first beta is going to be released most likely next Monday, so please keep tuned and looking forward your feedback when you can try it. Thanks!

**Closed by memsharded** 2022-06-17 11:53 UTC
Labels: type: look into

**Comment by MTomBosch** [comment] 2022-06-27 07:50
@memsharded When you say "This was very difficult to resolve in Conan 1.X without breaking" it is resolved in the most current version of Conan? In which specific version is it resolved?

**Comment by memsharded** [comment] 2022-06-27 08:46
In Conan 2.0-beta.1 it is resolved, if you want to try it and give feedback, that will be very useful.

**Comment by MTomBosch** [comment] 2022-07-13 11:00
> The surprising behavior seems to be caused by the following code
> 
> https://github.com/conan-io/conan/blob/f230bf104842c160be6ea377497151fe1ea64c38/conans/client/graph/range_resolver.py#L150
> 
>     1. The first remote containing a recipe with the same name is selected
> 
>     2. Then the version of this recipe is checked
> 
> 
> A possible implementation would be to:
> 
>     1. Save all recipes with a matching name, along side there associated remote, sorted by remote priority
> 
>     2. On these recipes, select the first one with a matching version
> 
> 
> Or:
> 
>     1. For each remote
>        
>        1. Retrieve the recipes with a matching name
>        2. Check the version of these recipes
>        3. Return the recipe with current remote if version qualifies

@DavidKeller: When you mean "name" you mean the package name or also the user and channel?
We cannot move to Conan 2.0.0 yet but I am wondering if using different channels for release/staging would resolve this issue?

**Comment by memsharded** [comment] 2022-07-13 11:20
> we cannot move to Conan 2.0.0 yet but I am wondering if using different channels for release/staging would resolve this issue?

No, please, do not do this. user/channel shouldn't be used anymore as "stage" indicator. Conan 2.0 has removed the ``conan copy`` command, and has declared packages immutable. The recommended approach is to do promotions (copying packages) from one server repo (lets call it "staging") to another server repo ("release"). But the packages should be called exactly the same.

**Comment by DavidKeller** [comment] 2022-07-13 12:33
@MTomBosch Just the name, not the reference.

That is `<NAME>` component of reference `<NAME>@<USER>/<CHANNEL> `

**Comment by MTomBosch** [comment] 2022-07-13 12:40
> @MTomBosch Just the name, not the reference.
> 
> That is `<NAME>` component of reference `<NAME>@<USER>/<CHANNEL> `

OK. Thanks for the quick reply. 

But that makes the usage of version ranges in our pre Conan 2.0 setup challenging.

**Comment by MTomBosch** [comment] 2022-07-18 13:26
@memsharded  We were still playing around with this issue and we might have found a solution that could be interesting to other people. But it would be very cool if you could confirm our workaround.

We did create a virtual repo that contained the multiple local repos (snapshot and release repo). Now the resolution of the version range specific package was working fine when using the conan install command with the -u -r<virtual repo> cli options.

Can you confirm that this works?

**Comment by memsharded** [comment] 2022-07-18 17:41
Yes, @MTomBosch, that could be a valid approach, up to my knowledge, this is how virtual repositories are intended to work. Sorry, I should have possibly mentioned this possibility.
Just a couple of clarifications for other users:
- Using virtual repos in Artifactory requires enabling revisions
- Virtual repos work as an aggregation of the other server repositories they are proxying. 
- As they use revisions, they can implement an iterative aggregation from remotes, in a similar way the above described behavior for Conan 2.0 in the client does (because Conan 2.0 is always using revisions too)

**Comment by sandeshhardikar** [comment] 2023-03-31 13:41
Quoting @MTomBosch 
> We were still playing around with this issue and we might have found a solution that could be interesting to other people. But it would be very cool if you could confirm our workaround.
We did create a virtual repo that contained the multiple local repos (snapshot and release repo). Now the resolution of the version range specific package was working fine when using the conan install command with the -u -r cli options.

Hello @MTomBosch ,

I hit the same problem and tried using the virtual repo , but the error still seems to appear for me (i.e conan doesnt seem to query any of the remotes) . The virtual repo that i have contains a remote repo and not the actual repository , do you think that makes a difference ? conan version used `1.54.0`  

Quoting @memsharded 
>In Conan 2.0-beta.1 it is resolved, if you want to try it and give feedback, that will be very useful.

Hello @memsharded 

I tried to work with conan version `2.0.2` though our recipes are not supported and I did not manage to get it working there as well , the only improvement i could spot was it was searching for all the remotes

 ```
conan search "package1/[>=0.37.0]@user/channel"

  remote1
  ERROR: Recipe 'package1/[>=0.37.0]@user/channel' not found

  remote 2
  ERROR: Recipe 'package1/[>=0.37.0]@user/channel' not found
```
But if i try to do a search of a package with pinned version it searches and lists in all the remotes found

```
conan search "package1/0.37.0@user/channel"
remote1
  package1
    package1/0.37.0@user/channel
remote2
  package1
    package1/0.37.0@user/channel
```

**Comment by memsharded** [comment] 2023-03-31 17:03
Yes, ``conan search`` and ``conan list`` in Conan 2.0 are pattern-matching expressions, not version-ranges expressions. You can do something like ``conan search package1/0.37.*``

**Comment by sandeshhardikar** [comment] 2023-04-03 04:37
ok Thank you :) , I can even confirm that with `conan 2.0` the version ranges were working properly when same packages were placed in 2 different remotes and also with the `--update` flag it was checking for the latest in all the remotes . But we still have a long way to go to migrate our project to `conan 2.0`
