### ISSUE TITLE
[bug] Targets defined by CMakeDeps generator have incorrect target libraries

### ISSUE THREAD

**Issue by andranik3949** [conan-io/conan#11852] opened 2022-08-11 20:12 UTC
After updating to conan 1.51.2, I started getting link errors when trying to build my project in Visual Studio. This affected all configurations except for Debug. 

After some investigation I noticed that all configurations of some of the dependencies were present in additional dependencies list. (e.g. both `spdlog.lib` and `spdlogd.lib` were present in the project dependencies for Release configuration)

Looking further into it I found that this happens when dependencies have different lib names based on the configuration (e.g. `spdlog.lib` for Release and `spdlogd.lib` for Debug)

The bug is caused by not using generator expressions for `<pkg_name>_LIBRARIES_TARGETS` when defining `INTERFACE_LINK_LIBRARIES` target property in generated CMake files.

This has also been fixed by [this](https://github.com/conan-io/conan/commit/307bb66ba5bb816cdd5768288ea4e277ba7a6388) commit, and then immediately broken by [this](https://github.com/conan-io/conan/commit/91933762620e55e54bb9a9576983a162ae645f13) refactoring commit

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 19.33.31629.0
  * Conan version: 1.51.2
  * Python version: 3.8.5

**Comment by andranik3949** [comment] 2022-08-11 20:13
I'm also willing to contribute a fix for this issue :)

**Comment by lasote** [comment] 2022-08-12 08:13
Hi, I've reproduced it in a test, I think (further investigation needed) the bug is not in the lines you mention because the `_LIBRARIES_TARGETS` is indeed multi config but there is a bug there generating the IMPORTED libraries. Thanks for reporting, I'll report ASAP and will open a new release process with the fix.

**Comment by lasote** [comment] 2022-08-16 08:20
The fix has been merged and it will be released at 1.51.3

**Closed as completed by lasote** 2022-08-16 08:20 UTC
