### ISSUE TITLE
Remove directory on Windows sometimes does not work

### ISSUE THREAD

**Issue by tonka3000** [conan-io/conan#2593] opened 2018-03-11 22:05 UTC
Hey,

I have troubles when i try to remove directories with conan. The problem happens f.e. with conan remove or anything which trigger the rmdir function. This does only happens to me on Windows, on Linux and Mac everything works fine. I already know this problem from my python projects and i create my own function to make it "smoother" to remove. BTW: It only happens with python, with any other tool (Explorer, cygwin, rmdir, etc.) it works absolutely fine, so it seems to be a python specific problem.

I use multiple windows machine and it happen on all of them, not always, but when it is non removable (from conan) forever.
I use Windows 7 x64, use python (x64) 3.4, 3.5, 3.6 and conan 1.1.1 and conan develop head. My biggest problem is that i can not reproduce it when i want, so it is really hard to write a unit test for it.

I've changed the following code in `conans/utils/files.py` to get rid of my problems.
```.py
def _win_rmtree(top):
    if not os.path.exists(top):
        return
    from time import sleep
    def __rmdir(folder):
        tries = 10
        for i in range(10): # try up to 10 times because sometimes the directory is not already empty
            try:
                os.rmdir(folder)
                break
            except BaseException as ex:
                if i >= tries -1:
                    raise
                sleep(2)

    for root, dirs, files in os.walk(top, topdown=False):
        for name in files:
            filename = os.path.join(root, name)
            if os.path.exists(filename):
                os.chmod(filename, stat.S_IWUSR)
                os.remove(filename)
        for name in dirs:
            filename = os.path.join(root, name)
            if os.path.exists(filename):
                os.chmod(filename, stat.S_IWUSR)
                __rmdir(filename)

    __rmdir(top)

def rmdir(path):
    try:
        if platform.system() == "Windows":
            _win_rmtree(path)
        else:
            shutil.rmtree(path, onerror=_change_permissions)
    except OSError as err:
        if err.errno == ENOENT:
            return
        raise

```

Greetings  
Tonka

**Comment by memsharded** [comment] 2018-03-11 22:21
Yes, we are party aware of the issue. See this in our **testing** code: https://github.com/conan-io/conan/blob/develop/conans/test/utils/test_files.py#L14

So it is something that might happen from time to time, for example if the Windows indexer is not disabled for the affected folders. We strongly recommend to disable the indexer, specially for the conan local cache.

Disabling the indexer, it seems the problem is orders of magnitude less frequent, please try. We have been reluctant to introduce this kind of hacks for this so far, but if more users provide more feedback, we might reconsider. Thanks for the feedback!

**Comment by tonka3000** [comment] 2018-03-12 13:53
Here is a [link](https://github.com/python/cpython/blob/d4d79bc1ff91b04625c312f0219c89aabcd19ce4/Lib/shutil.py#L450) to the python impl. . I found there impl. strange

**Comment by memsharded** [comment] 2018-05-07 08:40
Hi @tonka3000 

Sure, can you share that recipe or at least a stripped version of the recipe that can reproduce this behavior? That would be very useful! Many thanks.

**Comment by tonka3000** [comment] 2018-05-08 08:49
I will prepare a recipe next week because I'm out of office this week.

**Comment by petermbauer** [comment] 2019-01-03 13:17
This seems to have caused the issues i described in #4187. `conan remove` failed ~10 times though the respective folder was empty.
Maybe reconsider `shutil.rmtree()` with `ignore_errors=True` ...?

**Comment by hatl** [comment] 2019-01-03 14:11
I can reproduce the same issue under Windows 10 x64 with conan 1.8.2 and python 3.6.5

**Comment by tonka3000** [comment] 2019-01-03 16:00
The problem is the python implementation of `shutil.rmtree` as far as I know.

I generally have the directory remove problems in any python project on Windows.

@lasote would it be possible to add a custom rmtree function for some conan commands/features on windows activateable via env-var (commands would be the same as before)? With that it would be easier to test different implementations without affecting other users.

**Comment by lasote** [comment] 2019-01-04 07:12
Hi @tonka3000, we received similar feature requests for copying files, in that case, to call system functions. It could be a good idea to consider it for the plugins system (still under definition). Thanks.

**Comment by memsharded** [comment] 2023-02-22 22:23
Conan 2.0 had finally implemented in all codebase the following:

```python
if platform.system() == "Windows":
    def rmdir(path):
        if not os.path.isdir(path):
            return

        retries = 3
        delay = 0.5
        for i in range(retries):
            try:
                shutil.rmtree(path, onerror=_change_permissions)
                break
            except OSError as err:
                if i == retries - 1:
                    raise ConanException(f"Couldn't remove folder: {path}\n{str(err)}\n"
                                         "Folder might be busy or open. "
                                         "Close any app using it and retry.")
                time.sleep(delay)
```
All ``rmdir`` goes over that. It should be pretty resilient now to the reported failures, so closing this ticket as resolved, feedback welcome!

**Closed by memsharded** 2023-02-22 22:23 UTC
Labels: type: look into, priority: low, stage: queue, complex: medium

**Comment by dheyden** [comment] 2023-03-17 20:19
A posteriori, a possible explanation is that the full pathname of one of the files in the directory was longer than 260 characters (the infamous `MAX_PATH` limit in the Windows API). It seems that on Windows, `shutil.rmtree()` is very much likely to fail when encountering such files.

Starting in Windows 10 version 1607, there is a workaround: by setting the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` registry key to 1, the maximum path length limit is increased to 32767.

Alternatively, long paths may be prefixed with "`\\?\`".

For the details, see https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
