### ISSUE TITLE
[question] conan search from conanfile.py

### ISSUE THREAD

**Issue by raphael-grimm** [conan-io/conan#10119] opened 2021-12-02 16:01 UTC
I have a locally build conan package A that is not always available.
In the `conanfile.py` of project B, I am calling `conan search A/version@ -q "..."` (I omitted the long query) via pythons `subprocess.run`. This always results in A not being found, even if it is in the local cache. Executing the command in a terminal successfully manages to find A.
This probably happens since the environment inside of ` conan create` differs from the normal terminal.
My questions: Is there some way to successfully query for A from the `conanfile.py` of project B?
Also, is there a better way than calling `subprocess.run` to achieve this?

**Comment by memsharded** [comment] 2021-12-02 16:17
Hi @raphael-grimm 

Trying to guess if there is package available or not in that way sounds like an anti-pattern. If you want to control whether a consumer uses or not a package, then you could for example add an ``option`` to the recipe to conditionally ``require`` that package or not. But once the user (via conan arguments), activate that option, the package must be found or Conan will error.

The problem is that if something doesn't work correctly, for example the ``package_a`` was not correctly uploaded to the server by the last CI run, then the consumers code will silently skip using ``package_a``, because they couldn't successfully find it on the cache or in the server. This is a known anti-pattern in package management (I think I saw it in a CppCon talk about package management in general, not only Conan).

In any case, please take in mind:

- Calling ``conan`` as a subprocess from a Conan recipe is not allowed, and it can result in undefined and unexpected behavior.
- Calling any private or not documented Python code from Conan recipes is not allowed either, it can break anytime and result in unexpected behaviors.

**Comment by AbrilRBS** [comment] 2024-03-13 11:46
Closing as solved as we didn't hear back from you, anyone can feel free to reopen/open a new issue should similar questions come up, thanks!

**Closed as completed by AbrilRBS** 2024-03-13 11:46 UTC
Labels: type: question, stage: triaging
