### ISSUE TITLE
mingw builds freeze

### ISSUE THREAD

**Issue by sigmoidal** [conan-io/conan#2267] opened 2018-01-07 18:04 UTC
Some builds freeze mid-way while compiling with the mingw toolchain (using `mingw/1.0@conan/stable`) under the MSYS2 subsystem via the `msys2_installer/latest@bincrafters/stable`). Note there is no error or a crash. The build just "freezes" somewhere and no further output is generated or progress is made.

I have been having these freezing issues with MinGW builds since 0.29.x up to now 1.0.0b4. this is on Win10 64-bit.

I think it has something to do with console/terminal buffering and I recall seeing some post by @lasote regarding this issue (can't remember where). The issue goes away if I do either of the following:

a) I set `run_to_file=False`  in `conan.conf`
b) I replace `self.run` with `os.system` when executing the `make` command.

This seems to affect only mingw builds and hasn't occurred during MSVC.
It is quite consistent for me and I can replicate it on my system, but I don't know if it happens on other Windows machines.

I experienced this with ICU and OpenSSL builds. 

Is it just my system or others are having the same issue?

**Comment by memsharded** [comment] 2018-01-07 22:27
Not recently, but yes, I have seen that behavior when capturing processes output in python. Not only in Windows, also in others OSs. Easy to reproduce by just having a process doing large outputs and a few lines of python trying to capture it. I don't remember a robust workaround other than not capturing the output.


Is it deterministic, or it can halt in different parts of the build?

It would be a good idea if you could try with different python versions. Are you running with py2 or with py3? 32 (typical in Windows), or 64 bits? (I am assuming you are installing with ``pip``, but please tell otherwise.

**Comment by sigmoidal** [comment] 2018-01-08 00:02
It is deterministic when it occurs, i.e. it always gets stuck at the same place of a particular build. I use:
`Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32`

I can try to change python versions if I am the only one experiencing this. 

The real pain isn't coming from my own recipes, because there I can change (as I did with ICU) upfront. The most time consuming one is when I need to use a dependency and the builds are missing (see mingw openssl with various gcc compilers and options), in which case I have to rely on a recipe that gets my build stuck along the way and I have to cancel, fetch the recipes, change and build locally in the cache.  

Can you shed some light on what advantages we have when using self.run instead of os.system to execute a build process ? 
Can I switch on/off the `run_to_file=False` on the fly/programmatically?
Is there another way I could mitigate it somehow that you can think off?

thanks.

**Comment by memsharded** [comment] 2018-01-08 00:41
> self.run instead of os.system

self.run is mainly intended to capture process output. This process output can be analyzed by the user, to checks for results, by providing their own output stream to the call. And is also typically captured by conan to store build results in log files (some users are packaging the build logs, for reference, in packages).

> Can I switch on/off the run_to_file=False on the fly/programmatically?

What do you mean? From a recipe? Like another argument to ``self.run()``? 

The only mitigation I can think of right now is ``run_to_file=False`` in the conan.conf file.

If you are experiencing it right now with some OpenSSL recipe there in Bintray that we can use, please tell me which version and the steps & configuration you are using and at least we will try to reproduce here, to know if it depends on the machine. Thanks!

**Comment by sigmoidal** [comment] 2018-01-08 01:09
>> Can I switch on/off the run_to_file=False on the fly/programmatically?
> 
> What do you mean? From a recipe? Like another argument to self.run()?

yes, a way i.e. access to the global variable that could programmatically switch off/on before/after the problematic builds (although it defeats the purpose of self.run :(

I do have a test case yes, with @lasote's openssl recipe.

```
git clone https://github.com/lasote/conan-openssl
cd conan-openssl
conan create -k . bincrafters/testing -pr mingw-msys -o *:shared=True`

conan profile show mingw-msys
Configuration for profile mingw-msys:

[settings]
    os: Windows
    arch: x86_64
    compiler: gcc
    compiler.version: 6.3
    compiler.libcxx: libstdc++11
    compiler.exception: sjlj
    compiler.threads: posix
    build_type: Release
[options]
[build_requires]
    *: msys2_installer/latest@bincrafters/stable, mingw_installer/1.0@conan/stable
[env]
```

If run_to_file=True it gets stuck on this file every time I try to build:

```
D:/opensource/.conan-data/mingw_installer/1.0/conan/stable/package/f330c6e11d0f0eae51bf7ec65bd703d3f2a72f7f/bin/gcc.exe -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include -I/d/opensource/.conan-data/zlib/1.2.11/conan/stable/package/e69ab408e3915e18fe71837187e0f4e027397ee3/include -D_WINDLL -DOPENSSL_PIC -DOPENSSL_THREADS -D_MT -DDSO_WIN32 -DL_ENDIAN -O3 -Wall -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o b_sock.o b_sock.c
```

If I set it to run_to_file=True it compiles no problem.

**Comment by memsharded** [comment] 2018-01-08 09:24
I have been able to reproduce the issue:
- Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
- Conan from sources
- Win10, cmder, codepage 850

Exactly in the same point: ``b_sock.o b_sock.c``

Will try to debug it.

**Comment by memsharded** [comment] 2018-01-08 10:29
Interesting blog post: http://tanin.nanakorn.com/blogs/373

I am seeing that behavior, even with much smaller sizes (aprox >4000)

**Comment by memsharded** [comment] 2018-01-08 16:48
Finally, I manage to workaround it sending stderr to STDOUT pipe, because it fact, both are merged anyway in the output stream. It has been merged to beta.5 that will be released soon.

**Closed** 2018-01-08 20:04 UTC
Labels: bug, fixed
