### ISSUE TITLE
How to configure Squish coco codecoverage with Conan+Cmake build

### ISSUE THREAD

**Issue by Prasaddiwalkar** [conan-io/conan#7446] opened 2020-07-29 06:40 UTC
I want to configure Squish codo codecoverage with Conan+CMake+gTest build system.

Can you please help me in finding documentation URL for right configuration to achieve it for enterprise level application.

Thanks,
Prasad

**Comment by Prasaddiwalkar** [comment] 2020-07-31 11:46
@memsharded

can you please help me here

**Comment by memsharded** [comment] 2024-12-30 00:24
Sorry this was not responded back then @Prasaddiwalkar 

The issue is that such a tool seems outside of the scope of Conan. It seems more related to CMake as build system, but Conan doesn't play a role at all with code coverage. You  might of course store the results of a code coverage for example in Conan metadata files: https://blog.conan.io/2023/10/24/Conan-launches-metadata-files.html. But otherwise, I am afraid that we cannot help with this, we haven't used such tool and we have no idea how it works.

Closing this ticket, if you have any further questions about Conan specifics, please re-open or create new tickets. Thanks for your feedback.

**Closed as completed by memsharded** 2024-12-30 00:24 UTC
