### ISSUE TITLE
Finding the correct revision without hardcoding it.

### ISSUE THREAD

**Issue by OreCB** [conan-io/conan#13616] opened 2023-04-04 21:19 UTC
### What is your question?

Hi. After I upgraded to Conan 2, I’m having issues resolving the correct package configuration for different Operating Systems.

Is there a way to tell Conan to upload all the different packages under the same revision? 
Or tell the consuming recipe to search all the different revisions of the same package name for the configuration I need, without having to specify a revision number?

For example. I’m running a pipeline that has two jobs: 
-	A Linux job that creates one Linux package and uploads it to my Conan server.
-	A Windows job that creates one Windows package and uploads it to my Conan server.

Before upgrading to Conan 2, the two packages will be storage like this: 

- [ ] Package-Name
   -  Revision: 0
       - Package
		        -   Windows-configuration
	                -  Linux-configuration

When I needed to consume it, I just put the Package-Name as a requirement in my recipe and Conan will find the correct configuration, based in the OS I was calling it from.

After the upgrade to Conan 2, the two packages will be storage like this:

- [ ] Package-Name
    - Revision-Linux-hash
       - Package
	         - Linux-configuration
   - Revision-Windows-hash
      - Package
	              -  Windows-configuration

Let’s say, for example that Windows finish the latest. 
When I consume it in a recipe in a Linux OS, it will download just the latest revision (Windows) and it will not find a Linux configuration in it.

I have played with it, changing the default “Revision_Mode” to “scm” and it is an option, but sometimes I need to modify the source, so I cannot use it.

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-04-04 23:54
Hi @OreCB 

Thanks for your question.
I think what you are seeing is not specific of Conan 2.0, but it is an expected result of activating the revisions (the revisions have been in Conan 1.X for several years now, and can be activated with ``general.revisions_enabled=True`` config).

> Is there a way to tell Conan to upload all the different packages under the same revision?

Every binary package belongs to its recipe revision. If a recipe gets changes, in the ``conanfile.py``, or any of the sources it will produce a new recipe revision. And a new recipe revision will have its own binaries, as the previous binaries wouldn't be valid, as they were produced with different inputs. This is a critical element for reproducibility and traceability, if this doesn't happen, it can result in package binaries that cannot ever be rebuilt again from sources, because they were created from different sources and a different conanfile.py that has been overwritten and completely lost forever.

Conan 2.0 is more safe and consistent than 1.X, and it has much better reproducibility and traceability guarantees, so it doesn't allow to erase and decouple the recipe revision information from the package binaries.
That already happens in the Conan cache, even before uploading. The upload will retain the separation in the cache.

> Or tell the consuming recipe to search all the different revisions of the same package name for the configuration I need, without having to specify a revision number?

This would be a discouraged practice, but in any case this is not possible. This problem would be an NP-hard problem and intractable in practice, taking too much time to solve.


The general idea is that package binaries is a product of the input sources, and the sources are the "truth". If the sources get a new version (or a new revision, which is a version, just implicit and automatic), then the binaries for those new sources need to be rebuild. Having binaries that cannot be traced to the original sources is very problematic. And in the same spirit, you just released "mypkg/1.2" with a few important bugfixes, but for some reason, the package binary for Windows/Release was not uploaded to the server, and then it happens that when you build your products for your customers, they will still use the buggy "mypkg/1.1". This is bad, if "mypkg/1.2" was released, it should be used, and if for some reason it is missing the binaries you need, that is a pipeline error that should be fixed, creating the binaries that the rest need. There are other recommended practices to do this too.

**Comment by OreCB** [comment] 2023-04-06 20:53
Hi,
Thanks a lot for the prompt replay.
It looks like all the issues I was having with the different OS were related to the Line Endings in Git.
That is why my sources were different and generated different Revisions.
It was already documented in the Conan 1 docs:
![image](https://user-images.githubusercontent.com/100802977/230490749-5a3dab3f-053e-46b8-8c64-761d445b2ef6.png)
Thanks again for your help.

**Comment by memsharded** [comment] 2023-04-06 21:05
No prob, very glad to help.
To be honest, Windows can be super annoying with all its quirks, a lot of code in Conan codebase is dedicated to handle Windows specific things. Fortunately this CRLF thing seems nowadays a thing of the past, and we can move all to standardize to files with LF only, and everything works fine with modern editors in Windows too, without needing Git to change it.

**Comment by AbrilRBS** [comment] 2023-12-25 01:52
Closing as solved, thanks a lot for your question :)

**Closed as completed by AbrilRBS** 2023-12-25 01:52 UTC
Labels: type: question
