### ISSUE TITLE
[bug] Windows installer package is missing python modules (site / pefile)

### ISSUE THREAD

**Issue by lucabonifacio** [conan-io/conan#10998] opened 2022-04-08 12:01 UTC
The Windows installer package is broken since probably version 1.44.0. It doesn't include the full Python standard library anymore and produces the following error message:

```
ModuleNotFoundError: No module named 'site'
ModuleNotFoundError: No module named 'pefile'
```

This bug seems to be related to #10386.

### Environment Details (include every applicable attribute)
Operating System+version: Windows 10 20H2
Compiler+version: not relevant
Conan version: 1.47.0
Python version: not relevant since the windows installer package is used

### Steps to reproduce (Include if Applicable)

Create a simple conanfile.py:

```
from conans import ConanFile
import site  # comment out 'site' to test import pefile
#import pefile

class DemoConan(ConanFile):
    name = "demo"
    version = "1.0.0"
    settings = "os", "build_type", "compiler", "arch"

```

Run any conan command with the conanfile. For example `conan info conanfile.py`.

### Logs (Executed commands with output) (Include/Attach if Applicable)
```
C:\Temp\demo>conan info .
ERROR: Error loading conanfile at 'C:\Temp\demo\conanfile.py': Unable to load conanfile in C:\Temp\demo\conanfile.py
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Temp\demo\conanfile.py", line 2, in <module>
    import site
ModuleNotFoundError: No module named 'site'
```

**Comment by memsharded** [comment] 2022-04-08 12:32
Hi @lucabonifacio 

This is expected, and by design (design of the pyinstaller tool we are using to create this executable). 
The creation of self-contained executables with pyinstaller do not bundle the whole Python standard library, only the things needed for the executable. 

For installations needing the whole Python interpreter and standard library a standard Python installation is necessary (typically with virtualenvs)

**Comment by memsharded** [comment] 2024-07-19 08:14
Closing this as not a bug, but expected in the self-contained executables, the recommended solution is to use the python installation, thanks for the feedback.

**Closed as completed by memsharded** 2024-07-19 08:14 UTC
Labels: stage: triaging
