### ISSUE TITLE
[bug] CMakeToolchain: don't set CMAKE_GENERATOR_PLATFORM if Visual Studio xx yyyy arch

### ISSUE THREAD

**Issue by SpaceIm** [conan-io/conan#9761] opened 2021-10-08 02:54 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio 2017
  * Conan version: 1.41.0
  * Python version: 3.9.7

### Steps to reproduce (Include if Applicable)

- Call conan install with `CMakeToolchain` generator and `Visual Studio 15 2017 Win64` cmake generator.
- give this toolchain in a cmake command line with `Visual Studio 15 2017 Win64` generator.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
CMake Error at CMakeLists.txt:5 (project):
  Generator

    Visual Studio 15 2017 Win64

  does not support platform specification, but platform

    x64

  was specified.
```

Actually, I don't have Windows currently to confirm this error log, issue comes from https://cpplang.slack.com/archives/C41CWV9HA/p1633648840443400

The solution would be to not set `CMAKE_GENERATOR_PLATFORM` when some characters have been specified after the year in the Visual Studio generator. So I guess more test here: https://github.com/conan-io/conan/blob/d81f5a15ce058cb8f57433d352022242735029f1/conans/client/build/cmake_flags.py#L90-L91

See https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2015%202017.html#platform-selection (but also previous Visual Studio versions, Win64 & ARM are not the only cases in those old versions).

**Comment by kenfred** [comment] 2021-10-08 15:22
I have tried to work around this in a couple ways:

- In the `build` method, set the `generator` argument of the `CMake` object: `cmake = CMake(self, generator="Visual Studio 15 2017")`. This does not fix the problem. It doesn't seem to override the generator as expected.
- In the `generate` method, take out the offending cache variable: `tools.replace_in_file("conan_toolchain.cmake", "CMAKE_GENERATOR_PLATFORM", "CMAKE_GENERATOR_PLATFORM_FIX_ME", strict=False)`. This works, but obviously isn't a permanent solution.

**Comment by memsharded** [comment] 2021-10-08 18:15
the thing is that when ``conan install`` is called it generates a ``conan_toolchain.cmake``. When ``compiler=VIsual Studio`` and ``arch=x86_64`` there are 2 alternatives here:

- The ``conan_toolchain.cmake`` contains the CMAKE_GENERATOR_PLATFORM = x64 , and then it is not necessary to pass the ``Win64`` or other platform especification to ``cmake ...`` command line
- The ``conan_toolchain.cmake`` does not contain CMAKE_GENERATOR_PLATFORM, and it relies on the user passing later ``Win64``.

The first one is robust against architecture mismatches, at install time the dependencies architecture is already defined, and cannot be changed later at ``cmake install``. The second alternative allows a possible error of architecture mismatch that will be noted much later, probably at link time, with weird link error. 

The decision balanced towards the safest approach, the first one, the con is that the developer cannot define the platform in ``cmake`` command line. In both cases, the Visual Studio can still have a version mismatch, but that is impossible to define at the toolchain level.

I don't think this is a bug, but a feature, unless the majority agree that we should go for the second because it is more developer ergonomic. Or am I missing something?

**Comment by SpaceIm** [comment] 2021-10-08 19:03
I say that conan should trust what consumer gave in `tools.cmake.cmaketoolchain:generator`, because it's what consumer expects to use.

I think that conan should follow this precedence to deduce the generator for the logic in the file generated by `CMakeToolchain`:
- `tools.cmake.cmaketoolchain:generator` (in command line or hardcoded in `conanfile.py`)
- `cmake_generator` in `conan.conf`
- a default generator depending on the compiler

If the generator given to conan is `Visual Studio 15 2017 Win64` (or `Visual Studio 15 2017 ARM` etc), `CMAKE_GENERATOR_PLATFORM` should not be set in the toolchain file.

**Comment by memsharded** [comment] 2021-10-11 09:18
the problem is that the profile defines 2 things:

```
[settings]
arch=x86

[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 16 Win64
```

The ``settings`` is one of the most important things there, the dependencies will be installed for ``x86`` 32bits architecture, much before the ``CMakeToolchain`` genererator kicks in. Actually, it is completely possible that the ``generate()`` method could have a conditional based on the OS and only uses ``CMakeToolchain`` for some specific configuration and not for others. What is clear is that the dependencies cannot be installed for x86_64, disregarding the ``settings`` configuration, because that ``[conf]`` said a different thing.

Now, once the dependencies have been installed for 32 bits, the ``Win64`` generator is no longer valid, it will not work and will generate architecture conflicts at link time if Conan doesn't error early.

**Comment by kenfred** [comment] 2021-10-12 04:34
> I don't think this is a bug, but a feature

@memsharded I understand your point about not giving the user the ability to specify conflicting arch and cmake generators. However, in my case, I did not specify the generator, only the architecture. The `CMake` helper in the `build` method chose the generator of "Visual Studio 15 2017 Win64" based on arch = x86_64, which CMake errors out on when `CMAKE_GENERATOR_PLATFORM` is defined as "x64", ala the `CMakeToolchain` generator.

So the default `CMake` helper is incompatible with the current `CMakeToolchain` generator. Is this not a bug?

One way I attempted to fix the solution was by overriding the generator in the CMake helper. As you pointed out, it's actually dangerous for me to attempt to force the CMake generator: I should rely on conan to pick the right one for me based on the settings.

When that fix didn't work, I was forced to edit `conan_toolchain.cmake` after it is generated to remove `CMAKE_GENERATOR_PLATFORM`.

**Comment by memsharded** [comment] 2021-10-12 08:21
> So the default CMake helper is incompatible with the current CMakeToolchain generator. Is this not a bug?

Which one do you mean? Because the previous, legacy ``CMake`` cannot be used with ``CMakeToolchain``, the new one from ``from conan.tools.cmake import CMake`` is the one that must be used together with ``CMakeToolchain``.


By the way, the above:
```
[settings]
arch=x86

[conf]
tools.cmake.cmaketoolchain:generator=Visual Studio 16 Win64
```
Is unnecessary, as the Visual will be the default generator selected from the settings. Defining the ``tools.cmake.cmaketoolchain:generator`` conf is only necessary to select the Ninja or other generator.

**Comment by kenfred** [comment] 2021-10-12 14:04
Oh! I didn't realize there were two cmake helpers. So currently we have a cmake generator, the cmake helper in `conans`, and the cmake helper in `conan.tools.cmake`. It is now my understanding that the two former will be deprecated and the cmake helper in `conan.tools.cmake`, in conjunction with `CMakeDeps` and `CMakeToolchain`, is the way forward. Is that correct?

**Comment by memsharded** [comment] 2021-10-12 16:56
> Oh! I didn't realize there were two cmake helpers. So currently we have a cmake generator, the cmake helper in conans, and the cmake helper in conan.tools.cmake. It is now my understanding that the two former will be deprecated and the cmake helper in conan.tools.cmake, in conjunction with CMakeDeps and CMakeToolchain, is the way forward. Is that correct?

Yes, exactly! Only things from ``conan.tools`` will be usable from recipes, all other imports will be deprecated, including the ``from conans import CMake`` (we still need to move the base ConanFile too). The new CMake integration, that should be used together and shouldn't be mixed with the legacy lives all in ``conan.tools.cmake``, yes.

**Comment by tapia** [comment] 2021-10-14 13:45
@kenfred did @memsharded's answer solve your problem? Please close this issue if it did.

**Comment by kenfred** [comment] 2021-10-14 13:54
It resolves my issue - I was using the legacy cmake helper.

However, @SpaceIm was commenting on a behavior of the current helper.
@SpaceIm can close, if they are satisfied with the explanation.

Thanks!

**Comment by tapia** [comment] 2021-10-20 10:30
I'm closing this, because the OP solved his issue. @SpaceIm feel free to reopen it if you think it's necessary.

**Closed as completed by tapia** 2021-10-20 10:30 UTC
