### ISSUE TITLE
Packages installed as editable should warn when building dependents in Conan cache

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4278] opened 2019-01-11 09:35 UTC
When a package `A` is linked as editable to a local directory, every other package that requires it will use the local sources/libs/... to compile and link, and it will generate a package that depends on these local resources, which are not in the cache, which are not uploaded, so it will be an invalid package.

We must block building in the cache (using `conan create ` or `conan install --build `) any package that contains an editable one upstreams in its graph. The user should mark it as editable too and generate the lib/bin in a local folder.

**Comment by lasote** [comment] 2019-01-11 09:40
What about not blocking it but tagging them to block an upload if it comes?
It would be similar to a recipe with SCM and `scm_folder.txt` with local changes in the repository? We talked about maybe adding a field in the metadata.
Indeed, for me, it is not a `priority:high`, and maybe not even a bug, but it is a bit in the limit.

**Comment by danimtb** [comment] 2019-01-11 09:45
I'd say this is responsibility of the user and we should not block the build or upload. I think we should provide information in the case of a conan create/install --build to let user now he/she is using an editable package in the requirements (I'd say it would be marked as "editable" in the graph resolution) and make a warning.

In the case of the upload I see no point for this as currently we don't have a command to upload a package and all its requirements, so the user should be the one uploading all the packages required properly unlinking and creating the needed one in the cache.

**Comment by memsharded** [comment] 2019-01-11 09:47
I am fine blocking builds in the local cache that depend on editable packages, that could be at least weird, and likely error prone. But this is not a bug in conan, it is a "protection" measure against misuses, kind of UX. So the priority should also be lower.

**Comment by jgsogo** [comment] 2019-01-11 10:47
The problem is that you will get a `openssl` compiled against something that is not in your cache, that you may not upload,... you will get a broken package for `openssl` and eventually you can upload it and it will fail and it is impossible to trace back that error.

I'm lowering its criticality, but I would like to revisit this issue before releasing the editable feature.

**Comment by jgsogo** [comment] 2019-01-11 10:50
Alternate solutions that come to my mind:
 * if the `package_id` holds this information (it has being compiled with a local/non-pristine version of the requirement), this won't be an issue, as the consumer won't get the same binary id and won't try to use it.
 * if the artifacts of packages that depend on editable ones are stored outside the cache (another _PackageLayout_) this won't be an issue.

**Comment by lasote** [comment] 2019-04-02 09:27
We still think we have to block it after our latests conversations?

**Comment by jgsogo** [comment] 2019-04-02 09:52
What about a warning and opt-in error?

**Comment by memsharded** [comment] 2019-04-02 10:19
Yes, I think we should not completely block it. I would be fine with error & opt-out too.

**Closed** 2023-03-08 22:07 UTC
Labels: stage: queue, priority: medium, complex: medium, component: ux, component: graph
