### ISSUE TITLE
[bug] Conan crashes during imports() in Qt when LD_LIBRARY_PATH is set

### ISSUE THREAD

**Issue by Taresmajic** [conan-io/conan#12575] opened 2022-11-21 13:22 UTC
I'm having an issue with Conan in Qt Creator. I'm using Ubuntu 20.04, Qt 5.12. I'm using qmake as a build tool, and in the build steps I have a custom step that runs Conan. The issue occurs during the `imports()` step, where Conan crashes while importing (copying) libraries. This issue doesn't occur if LD_LIBRARY_PATH environment variable isn't set. I can't reproduce the problem from the command line. 

The only way I can build the project again is if I delete the destination directory where the Conan imports are being copied. 

### Environment Details
  * Operating System+version: Ubuntu+20.04
  * Compiler+version: g++ 9.4.0
  * Conan version: 1.54
  * Python version: 3.8.10
  *  Qt 5.12.11

**Comment by memsharded** [comment] 2022-11-21 13:38
Hi @Taresmajic 

I am afraid we don't have enough information to know what could be happening. We would need something that we could reproduce, or at least more details, like the ``imports()`` method implementation, the exact commands being used, the full terminal output, etc.

**Comment by Taresmajic** [comment] 2022-11-21 13:44
```
def imports(self):
    self.copy("*", dst="bin", src="bin")
    self.copy("*.so*", dst="lib", src="lib")

```

I also managed to reproduce the crash in command line, segmentation fault.
`export LD_LIBRARY_PATH=/path/to/build-debug/lib`
`conan install --install-folder ../build-debug ../project-directory -s build_type=Debug`

For some reason Conan crashes if I have the LD_LIBRARY_PATH set and the destination directory is not empty.

**Comment by Taresmajic** [comment] 2022-11-21 13:50
```
conan install --install-folder ../build-debug ../project-directory -s build_type=Debug -pr=linux_profile
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[build_requires]
[env]

conanfile.py: Installing package
Requirements
    zlib/1.2.11-linux@custom/build
Packages
    zlib/1.2.11-linux@custom/build:4db1be536558d833e52e862fd84d64d75c2b3656 - Cache

Installing (downloading, building) binaries...
zlib/1.2.11-linux@custom/build: Already installed!
conanfile.py: Generator qmake created conanbuildinfo.pri
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Aggregating env generators
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
conanfile.py imports(): Copied 1 '.11' file: libz.so.1.2.11
[1]    39123 segmentation fault (core dumped)  conan install --install-folder ../build-debug ../project-directory -s build_type=Debug 
```

**Comment by Taresmajic** [comment] 2022-11-21 14:25
Steps to reproduce
conanfile.txt
```
[requires]
zlib/1.2.11

[options]
zlib:shared = True

[imports]
lib, *.so* -> ./lib
bin, * -> ./bin
```

Run:
1. export LD_LIBRARY_PATH=/path/to/current/dir/lib (have this path point to the lib where conan will copy libraries)
2.  conan install .
3.  conan install .

On the second Conan install run it should seg fault.

I hope this helps @memsharded

**Comment by memsharded** [comment] 2022-11-21 14:50
Yes, this really helped, thanks very much, I managed to reproduce.

I am having a look, this is definitely super weird. This is my understanding:

- The Python interpreter is loading the libz.so that is inside the ``lib`` folder with the imported file
- When the second invocation of Conan tries to overwrite the libz.so, as it is being used, it cannot do it, and it crashes

I think that there is very little we can do from the Conan side, as it seems to be more of a system issue. The key to avoid it is that LD_LIBRARY_PATH shouldn't be active while running python and Conan, and only be activated to run the application using the imported files.

**Comment by Taresmajic** [comment] 2022-11-21 14:57
Thank you @memsharded for the explanation and the solution. This is going to be a bit hard to incorporate in the Qt Creator way of building, but I do know where to look, and what to do. Best of luck to you

**Comment by memsharded** [comment] 2024-01-14 17:21
The ``imports()`` method has been made legacy in Conan 1.X by explicit ``copy()`` in ``generate()`` and removed in Conan 2.0. Closing this ticket, please create new tickets as necessary, thanks!

**Closed as not planned by memsharded** 2024-01-14 17:21 UTC
Labels: stage: triaging
