### ISSUE TITLE
[question] create/upload package without sources

### ISSUE THREAD

**Issue by maciuh** [conan-io/conan#3411] opened 2018-08-28 09:53 UTC
Hi.
I’ve been trying out conan and artifactory for the last couple of days and I really like it.
I was wondering if there is possibility to create packages and upload them to Artifactory without sources? I want to build them locally from sources and upload only includes and binaries (parts of generated package defined in conanfile.py).
From what I checked during package creation there are options to keep source and keep build. Even if those options are not set, sources and build are kept in local cache and sources are uploaded to Artifactory.
Do you have any suggestions?

**Comment by memsharded** [comment] 2018-08-28 10:01
Yes, there are several approaches:

- You can use an external recipe, put the "conanfile.py" in its own repo, and use the ``source()`` method to fetch the sources to build when necessary. This doesn't store the sources in the package. From what I understood, you would like to have the conanfile.py recipe in the source repo, so this might not be the approach you need.
- You can do an external build, i.e. build in your user space (also using the conan local development flow conan install + build), and then use the ``conan export-pkg`` command, to create a package from the includes and binaries you have in user space. This works well, but it is not as automated as the ``conan create`` command. This is the flow intended more for development, working while changing the source code of the package
- You can use the SCM feature: https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-from-git-scm-experimental It is new, still experimental, but it is working well. This captures the git commit from the current repo, but doesn't upload the source code to Artifactory. Using the SCM data, it is able to re-build from sources if necessary (as long as the one re-building has read acccess to the location to which the SCM is pointing). I think this could be the approach you need.

**Comment by maciuh** [comment] 2018-08-28 10:03
I will try it out. Thanks.

**Comment by maciuh** [comment] 2018-08-28 10:53
I went with second option (conan export-pkg) with this script and it does the job just fine.

> #!/bin/sh
> conan source . --source-folder=tmp/source
> conan install . --install-folder=tmp/source/
> conan build . --build-folder=tmp/source
> conan export-pkg tmp/source/ demo/testing

and then upload.
Thanks for advice.

**Comment by memsharded** [comment] 2018-08-28 11:02
If you don't have a ``source()`` method, then you probably can skip the first step, and use the current folder as the source folder

Also take into account that this approach is not reproducible, or consumers of the package cannot re-build from sources (with ``conan install --build=missing``, for example), if they need (even if they have read access to the source code, even yourself, if you need it). Just recall about the SCM feature in the future if you need it.

Otherwise, happy to know that it worked :) Closing the issue, but please re-open or comment if necessary. Cheers!

**Closed by memsharded** 2018-08-28 11:02 UTC
Labels: question
