### ISSUE TITLE
[bug] install --update does not update a locally cached package

### ISSUE THREAD

**Issue by thx-1113** [conan-io/conan#7436] opened 2020-07-28 09:44 UTC
I have a package in a remote repository that has multiple recipe revisions. If I have an old revision installed locally in the Conan cache, running `conan install -r <remote> --update <reference>` is not updating it with the latest revision available from the remote.

I have `revisions_enabled = 1` set in `conan.conf`

### Environment Details (include every applicable attribute)
  * Operating System+version: Ubuntu 18.04
  * Compiler+version:
  * Conan version: 1.27.1
  * Python version: Python 3.6.9

### Steps to reproduce (Include if Applicable)

List all revisions available remotely - `conan search -r <remote> package/1.0.0@user/channel -rev`
Install an old revision - `conan install -r <remote> package/1.0.0@user/channel#<old-revision-hash>`
Verify the locally installed version - `conan search package/1.0.0@user/channel -rev`
Attempt to update the local version - `conan install -r <remote> --update package/1.0.0@user/channel`

The newer revision is not downloaded and the old one is still in the local cache

**Comment by memsharded** [comment] 2020-07-28 12:23
I am trying to reproduce this issue. 
So far this test passes:

```python
@unittest.skipUnless(get_env("TESTING_REVISIONS_ENABLED", False), "Only revisions")
    def update_revisions_test(self):
        # https://github.com/conan-io/conan/issues/7436
        client = TestClient(default_server_user=True)
        client.save({"conanfile.py": GenConanfile()})
        client.run("create . pkg/0.1@")
        client.run("upload * --all --confirm")
        client.save({"conanfile.py": GenConanfile().with_build_msg("Revisioned")})
        time.sleep(1)
        client.run("create . pkg/0.1@")
        client.run("upload * --all --confirm")
        client.run("remove * -f")
        client.run("search -r default pkg/0.1@ -rev")
        self.assertIn("b24271e554165a0958a59a2b00587257", client.out)
        self.assertIn("f3367e0e7d170aa12abccb175fee5f97", client.out)
        client.run("install -r default pkg/0.1@#f3367e0e7d170aa12abccb175fee5f97")
        self.assertIn("pkg/0.1: Downloaded recipe revision f3367e0e7d170aa12abccb175fee5f97",
                      client.out)
        client.run("install -r default pkg/0.1@ --update")
        self.assertIn("pkg/0.1: Downloaded recipe revision b24271e554165a0958a59a2b00587257",
                      client.out)
```

I am checking the source code, and the origin could be a timestamp difference. If the machines that are creating the packages have different times, it could introduce some inconsistencies that would skip the updates. 

We will have a look and investigate this (will try in next 1.29 iteration), but please try to have a look at the times of the machines uploading those revisions to the server, and sync them.

**Comment by thx-1113** [comment] 2020-07-28 14:56
Thanks for the quick response. I've dug deeper and may have identified what is going on. 

In a nutshell, our workflow allows for a recipe revision to change (based on the commit hash of the repository the recipe is in) without the recipe itself having changed (ie: the conanfile.py is exactly the same).

It looks as if when a `--update` is performed, Conan is inspecting `conanmanifest.txt` in the newest revision on the remote but only doing the update if the hash of `conanfile.py` within the manifest has changed. Which I suppose is understandable, but means that we are not detecting changes.

I've verified that when installing a very old version that has differences in `conanfile.py`, the behaviour of `--install` is as expected.

**Comment by memsharded** [comment] 2020-07-28 16:58
> It looks as if when a --update is performed, Conan is inspecting conanmanifest.txt in the newest revision on the remote but only doing the update if the hash of conanfile.py within the manifest has changed. Which I suppose is understandable, but means that we are not detecting changes.

Yes, this is pretty accurate, but the revision is not only the ``conanfile.py`` but any other file in the manifest. In order to change the revision, it is necessary to change some other exported file, the ``conandata.yml`` or something. Otherwise, you will get exactly the same revision. Unless you are using the ``revision_mode = "scm"``, is this the case? We certainly need to revisit the comparison of the manifests in case of using revisions.

**Comment by thx-1113** [comment] 2020-07-28 18:42
Yes, we are using `revision_mode = "scm"` so I think that's where the discrepancy in expectations is happening. We are definitely getting new revisions created when the git commit hash changes, as we would expect, but those revisions are not being 'recognised' as different when doing something like `--update`

Most normal usage is working fine, and we can install specific revisions on demand. It's just that the expected behaviour of being able to use the update flag to ensure we have the very latest revision isn't working in this scenario

I suppose that we may be able to get round it by changing something in the manifest when we update the scm repository as you suggest. 

Thanks for the speedy help.

**Comment by memsharded** [comment] 2020-07-28 22:43
I have created a failing test in a branch: https://github.com/conan-io/conan/compare/develop...memsharded:test/update_revisions?expand=1

Now trying to understand the issue, and possible solutions. It is indeed a bit counter-intuitive, because it also makes sense to not upgrade if there are no changes to upgrade, and the final resulting contents will still be the same.

This make take a while, seems especially difficult to change something there and not break existing behavior. Actually it seems that we might need to design the Conan 2.0 update and upload flows based on revisions without involving the manifests at all.

It seems that what you suggested could be a valid workaround, to make sure some file actually change in the recipe. Please let us know how it goes, and if you have any other question. Thanks!

**Comment by memsharded** [comment] 2023-09-07 12:17
The --update flow was completely re-designed in Conan 2.0, to use revisions natively, instead of comparing manifests timestamps, so this problem should be gone now in 2.0, I am closing this ticket as solved. Please create a new ticket if there are some issues with the Conan 2.0 behavior for --update

**Closed as completed by memsharded** 2023-09-07 12:17 UTC
Labels: type: bug, type: look into
