### ISSUE TITLE
[bug] Breaking change between 2.0.14 and 2.0.15 causes "Compatible package ID ... equal to the default package ID: Skipping it."

### ISSUE THREAD

**Issue by robindegen** [conan-io/conan#15318] opened 2023-12-21 01:06 UTC
### Environment details

* Operating System+version: Windows
* Compiler+version: Visual Studio 2022
* Conan version: 2.0.15
* Python version: Github Windows runner (not sure about the exact version here)

I originally posted this as a response on #15293 but I realise that this issue is likely unrelated. Hence the new issue:

Conan 2.0.15 introduces a breaking change. I'm not sure if this is a bug or a bugfix but I wouldn't really expect such a breaking change in a small point release either way. Maybe I'm missing something in the way the package revisions are calculated.

With Conan 2.0.14 this package worked on windows, linux and macos. With Conan 2.0.15 I get the following message:

Conan 2.0.15 (https://github.com/aleya-dev/libaeon/actions/runs/7282180560/job/19844092808):
```
asio/1.29.0@aleya/public: Compatible package ID da39a3ee5e6b4b0d3255bfef95601890afd80709 equal to the default package ID: Skipping it.
```

I ran a build of the exact same thing on conan 2.0.14 (https://github.com/aleya-dev/libaeon/actions/runs/7282554627/job/19845101294):
```
asio/1.29.0@aleya/public#bafe0390378ec0f1c1782cff24ab63c0:cb836a521fc8494ecf80498fd71e4aa2dc66157d#5117d4e3cc2c109e5a78b21adf7ee89c - Download (aleya)
```

Why is the computed hash different? Did something change in Conan 2.0.15 in the way these hashes are computed?

Artifactory with package:
https://artifactory.aleya.dev/ui/repos/tree/General/aleya/aleya/asio

Package itself:
https://github.com/aleya-dev/mirror-package-asio

The change to make the build green:
https://github.com/aleya-dev/libaeon/compare/master...check_conan

**Comment by memsharded** [comment] 2023-12-21 01:12
Hi @robindegen 

Thanks for your report.
It seems you are seeing the effects of https://github.com/conan-io/conan/pull/15285, which is a bug fix.

The explanation is that Conan 2.0.15 did a bug fix in the computation of ``package_id`` of header-only libraries that could be wrongly affected by ``python-requires`` and ``tool-requires`` in some cases, while it shouldn't. This hadn't been detected before because it is quite unusual to use ``python_requires`` for header-only libraries, as they are so simple they rarely need such python-requires.

I apologize for the inconvenience, but we thought this bug had to be fixed, otherwise we would be keeping this wrong behavior forever, and even the scenario is not that likely, it will have sooner or later the opposite concerning effect (some ``python-requires`` change, and suddenly a ``header-only`` library no longer have a package for it, and then confusion is guaranteed to users as well, because they won't understand easily why a header-only library package binary is no valid.

**Comment by robindegen** [comment] 2023-12-21 01:13
If I understand you correctly, I should rebuild+deploy the asio package with 2.0.15 and it will get the proper hash? Or is there still also another issue that would need fixing for this?

**Comment by memsharded** [comment] 2023-12-21 01:25
> If I understand you correctly, I should rebuild+deploy the asio package with 2.0.15 and it will get the proper hash? Or is there still also another issue that would need fixing for this?

No, I think that should solve the issue.

**Comment by robindegen** [comment] 2023-12-21 01:31
Ill update all my infra and test that tomorrow. Thanks

**Comment by robindegen** [comment] 2023-12-21 18:55
@memsharded Looks like this indeed has worked.

**Comment by memsharded** [comment] 2023-12-21 23:57
> @memsharded Looks like this indeed has worked.

Fantastic, thanks for following up and reporting.
Sorry again for the inconvenience caused by this.

**Comment by memsharded** [comment] 2024-07-29 22:54
Closing this as solved/outdated, thanks for the feedback.

**Closed as completed by memsharded** 2024-07-29 22:54 UTC
