### ISSUE TITLE
Remote lookup in offline mode 

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#2924] opened 2018-05-22 09:00 UTC
Hello,

Following up the small issue that I had during my demo at swampUP:

I was trying to create a package for which I had every build requirement recipe already exported and thus available.

I was expecting to get an error:

>no such package with current options/settings: **build requirement package**

However, it seems that Conan did try to check this package in remotes (with no internet access, it failed). The expected behavior would be for Conan to check the local cache after remotes.

Passing `--build missing` to `conan create` did not fix the issue.

Using Conan v1.3.3

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment] 2018-05-24 08:08
Well, it could be problematic. If you have remotes configured, and Conan can't connect with the remotes, for me it is not an automatic thing to do to continue as no packages had been found, because something not expected happened.

I'm not suggesting to do it, but in these cases, some explicit user intervention like activating an "offline mode" could be valid, but without user intervention, your suggestion could be dangerous for a CI server, where you expect the build to fail if internet fails.

By the way, many thanks for your talk in swampup, it was amazing, we really appreciate your effort and long travel! 👍

**Comment by remleduff** [comment] 2019-03-30 23:54
The bigger issue is that there's no output telling you which dependency is causing conan to go out and search on a remote in the first place.

Assuming you have the conan recipes for your dependencies available locally, it becomes a guessing game to figure out what you need to go and build.

The alternative is to remove the remote entirely, so at least you are told which dependency can't be found.

**Comment by lasote** [comment] 2019-03-31 07:46
@remleduff Thanks for reporting.
Do you have a recent trace (console output) to help? Something should be printed telling you what is trying to download and not being found.

**Comment by remleduff** [comment] 2019-03-31 18:50
The situation is a little more complicated than I realized. I believe that the missing output only happens if you have the recipe in your cash, but don't have the package for the correct build type.

Reproduce by:
1) conan remove <dependency>
2) disableNetwork && conan create . user/channel -s buildType=Release
    > This will fail with a useful error message
3) enableNetwork && conan install <dependency> -s buildType=Debug
4) disableNetwork && conan create . user/channel -s buildType=Release
   > This will fail with an unhelpful error message

Transcript follows:
[output.txt](https://github.com/conan-io/conan/files/3027017/output.txt)

**Comment by remleduff** [comment] 2019-04-02 04:21
Same problem in slack:

https://cpplang.slack.com/archives/C41CWV9HA/p1554172467257200

Actually, this is the same issue with worse symptoms. If the remote is down but your internet is up, you would expect to be able to build other versions of the package, because you have the recipe in your cache.

**Comment by lasote** [comment] 2019-04-02 06:38
Hi, I added this PR to the next release with a better message in case something unexpected occurs when trying to download a binary package. I think that is the only we can do in this case.

**Comment by memsharded** [comment] 2019-04-02 10:28
Merged. Will be released next Conan 1.15

**Closed** 2019-04-02 10:28 UTC
Labels: complex: low, priority: low, stage: review, type: ux

**Comment by mjvk** [comment] 2020-03-16 09:32
I'm still confused how to use conan offline. I work in an industry where internet is not always available (on ships) and sometimes stuff just fails (VPN + corona virus = overload). Now I can only do conan remote clean to perform a conan install without errors correct? This does effect me when internet does come online again right?

**Comment by memsharded** [comment] 2020-03-16 09:38
Hi @mjvk 

No, you don't need to remove ``conan remote remove <remote>`` the remotes if you don't want. If you want you can do ``conan remote disable <remote>`` to temporarily disable them. They will not be accessed, but not removed from the config.

**Comment by mjvk** [comment] 2020-03-16 13:43
Hmm I'll try again, but upon disabling the remote I got errors saying that I disabled a remote. The only thing that worked for me was ```conan remote clean``` as it also disassociates the recipes from a remote. I'll try again as soon as I can access our server again.

**Comment by mjvankampen** [comment] 2020-05-14 09:08
@memsharded I tried again. Say I use cppzmq/4.6.0 in package foo/0.1 as a requirement. If I run conan install and build for the first time (with remote available) everything is fine. 

If I repeat it but with conan remote disable X I get the error:

``` 
ERROR: Failed requirement 'cppzmq/4.6.0' from 'conanfile.py (foo/0.1)'
ERROR: Remote 'X' is disabled
```

I would expect that I could choose between this error, or getting a warning saying something like cannot update package using existing version.

For example today the artifactory server went down. This meant local builds and CI would get hard failures that you cannot circumvent except by using conan remote clean (which is quite drastic as it is permanent I believe). I work in remote locations without internet every now and then, I would run into the same issue.

Do you have any suggestions?

**Comment by mjvankampen** [comment] 2020-07-09 09:25
@memsharded any clues?
