### ISSUE TITLE
[question] Artifactory incorrect header check

### ISSUE THREAD

**Issue by witanswer** [conan-io/conan#6995] opened 2020-05-11 19:07 UTC
I seem to be having an artifactory issue?
other packages are able to download fine, but this one seems to have issues

```$ conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=7
os=Linux
os_build=Linux
[options]
[build_requires]
[env]
cmakebase/0.0.1@NCBI/toolkit: Not found in local cache, looking in remotes...
cmakebase/0.0.1@NCBI/toolkit: Trying with 'artifactory_internal'...
Downloading conanmanifest.txt completed [0.11k]                                          
Continuing download of conanmanifest.txt:   0%|          | 0.00/111 [00:00<?, ?B/s]ERROR: Download failed, check server, possibly try again
Download failed, check server, possibly try again
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
Waiting 0 seconds to retry...
Downloading conanmanifest.txt completed [0.11k]                                          
Continuing download of conanmanifest.txt:   0%|          | 0.00/111 [00:00<?, ?B/s]ERROR: Download failed, check server, possibly try again
Download failed, check server, possibly try again
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
Waiting 0 seconds to retry...
Downloading conanmanifest.txt completed [0.11k]                                          
Continuing download of conanmanifest.txt:   0%|          | 0.00/111 [00:00<?, ?B/s]ERROR: Download failed, check server, possibly try again
Download failed, check server, possibly try again
('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check')). [Remote: artifactory_internal]```




conan log looks like this:
```{"_action": "REST_API_CALL", "duration": 0.02453923225402832, "headers": {"User-Agent": "Conan/1.25.0 (Python 3.8.1) python-requests/2.23.0"}, "method": "GET", "time": 1589216491.5452385, "url": "https://<server_url>/artifactory/api/conan/EXP-DO-CXX-DEP-MNG/v1/files/NCBI/cmakebase/0.0.1/toolkit/0/export/conanmanifest.txt"}
{"_action": "REST_API_CALL", "duration": 0.024364233016967773, "headers": {"User-Agent": "Conan/1.25.0 (Python 3.8.1) python-requests/2.23.0", "range": "bytes=108-"}, "method": "GET", "time": 1589216491.577143, "url": "https://<server_url>/artifactory/api/conan/EXP-DO-CXX-DEP-MNG/v1/files/NCBI/cmakebase/0.0.1/toolkit/0/export/conanmanifest.txt"}
{"_action": "EXCEPTION", "class": "ConanConnectionError", "message": "Download failed, check server, possibly try again\nDownload failed, check server, possibly try again\n('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check')). [Remote: artifactory_internal]", "time": 1589216491.5907307}```

i can curl the file just fine
```$ curl -L --compressed https://<test url>/artifactory/api/conan/EXP-DO-CXX-DEP-MNG/v1/files/NCBI/cmakebase/0.0.1/toolkit/0/export/conanmanifest.txt    1589214069
cmakebase.cmake: b68a764e53a7990c6498671efa09b026
conanfile.py: 0a6584ecf98fab8a5e879713c6c852d8```

python test works in same venv
```$ cat gettest.py 
import requests
requests.get("https://<test url>/artifactory/api/conan/EXP-DO-CXX-DEP-MNG/v1/files/NCBI/cmakebase/0.0.1/toolkit/0/export/conanmanifest.txt")

```

am i looking at the right url in the logs?

**Comment by memsharded** [comment] 2020-05-11 21:24
Hi @witanswer 

Can you please detail:

- Conan version
- Artifactory version (and edition: community edition, etc). Where are you running it? is it behind some proxy or corporate VPN or front-end?
- Is this new, was it working with previous versions of Conan?

**Comment by memsharded** [comment] 2020-05-12 09:13
Hi @witanswer 

There was a bug in Conan 1.25, related to gzip and resumable downloads. We are going to release a patch 1.25.1 asap, it would be good to know if that was a regression on your side. It is weird that it is only failing for that specific package and not all of them, would be good to have more info. Thanks!

**Comment by witanswer** [comment] 2020-05-12 12:54
conan version: 1.25.0
artifactory version: 6.18.1 (enterprise)
this has been previously working, and we can't determine anything that we have done that may have caused this. user issue reports started coming in on monday, not sure when it started or when we may have upgraded to 1.25

**Comment by witanswer** [comment] 2020-05-12 14:00
we just reverted to 1.24.0 which fixed our issue

**Comment by witanswer** [comment] 2020-05-12 16:18
worth noting, this package was a cmake file only

conanfile.py:
```
from conans import ConanFile, tools

class CmakeBase(ConanFile):
    name = "cmakebase"
    #settings = #no settings for this lib, nothing is compiled 
    description = "base includes for cmake package"
    url = "None"
    license = "Public Domain"
    author = "NCBI"
    topics = None
    exports = "cmakebase.cmake"

    def package(self):
        self.copy("*")
        return
```

cmakebase.cmake:
```
message("######################## CMAKE BASE INCLUDED ####################################")
include( CTest )
```

**Comment by flashdagger** [comment] 2020-05-13 04:47
That also seems to be related to #6984. The second request uses a false "range" which leads to the server's error response. @memsharded already provided a fix which comes with release 1.25.1

**Comment by memsharded** [comment] 2020-05-15 16:43
Hi @witanswer 

We have released 1.25.1 that solves some issues with the headers (resumable downloads). Could you please update and check again? Thanks!

**Comment by memsharded** [comment] 2020-05-27 14:50
Please upgrade to Conan 1.25.2 and check if the issue is solved. Thanks!

**Comment by memsharded** [comment] 2020-06-01 20:45
This doesn't seem an issue anymore, closing it, but please re-open if this happens again. Thanks!

**Closed as completed by memsharded** 2020-06-01 20:45 UTC
Labels: type: question
