### ISSUE TITLE
[bug] CMake Error in the generated conan_provider.cmake

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [conan-io/conan#14891] opened 2023-10-07 18:48 UTC
closed by: https://github.com/conan-io/conan-center-index/pull/20448

### Environment details

* Operating System+version: Version 22H2 OS Build 22621.2361
* Compiler+version: GCC 13.0 / MinGW w64 11.0
* Conan version: 2.0.13
* Python version: 3.12

### Steps to reproduce

1. Open CLion
2. Create a new C17 C Program
3. Add libcurl with the Conan Plugin
4. Add the required stuff to the CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.26)
project(ai_cli_meal C)

set(CMAKE_C_STANDARD 17)

find_package(CURL REQUIRED)

add_executable(ai_cli_meal main.c)

target_link_libraries(ai_cli_meal CURL::libcurl)
```
5. Build the program

### Logs

C:\Users\jakob\AppData\Local\Programs\CLion\bin\cmake\win\x64\bin\cmake.exe -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:/Users/jakob/AppData/Local/Programs/CLion/bin/ninja/win/x64/ninja.exe -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=conan_provider.cmake -G Ninja -S "F:\Programming projects\ai-cli-meal" -B "F:\Programming projects\ai-cli-meal\cmake-build-debug"
-- CMake-Conan: first find_package() found. Installing dependencies with Conan
-- CMake-Conan: Checking if a default profile exists
C:\Users\jakob\.conan2\profiles\default
-- CMake-Conan: cmake_system_name=Windows
-- CMake-Conan: cmake_system_processor=x86_64
-- CMake-Conan: CMake compiler=GNU
-- CMake-Conan: CMake compiler version=13.1.0
CMake Error at conan_provider.cmake:229 (string):
  string sub-command REPLACE requires at least four arguments.
Call Stack (most recent call first):
  conan_provider.cmake:282 (detect_compiler)
  conan_provider.cmake:470 (detect_host_profile)
  CMakeLists.txt:6 (find_package)

-- CMake-Conan: [settings] compiler=gcc
-- CMake-Conan: [settings] compiler.version=NOTFOUND
CMake Warning at conan_provider.cmake:269 (message):
  CMake-Conan: The C++ compiler is not defined.  Please define
  CMAKE_CXX_COMPILER or enable the C++ language.
Call Stack (most recent call first):
  conan_provider.cmake:339 (append_compiler_executables_configuration)
  conan_provider.cmake:470 (detect_host_profile)
  CMakeLists.txt:6 (find_package)

-- CMake-Conan: Creating profile F:/Programming projects/ai-cli-meal/cmake-build-debug/conan_host_profile
-- CMake-Conan: Profile: 
[settings]
arch=x86_64
os=Windows
compiler=gcc
build_type=Debug
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={"c":"C:/Users/jakob/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe",}

-- CMake-Conan: Installing single configuration Debug
-- CMake-Conan: conan install F:/Programming projects/ai-cli-meal -of=F:/Programming projects/ai-cli-meal/cmake-build-debug/conan --profile:host=default;--profile:host=F:/Programming projects/ai-cli-meal/cmake-build-debug/conan_host_profile;--profile:build=default;--build=missing;-g;CMakeDeps

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={'c': 'C:/Users/jakob/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe'}

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Windows

======== Computing dependency graph ========
Graph root
    conanfile.py: F:/Programming projects/ai-cli-meal\conanfile.py
Requirements
    libcurl/8.2.1#38190730f9424d073aa22f8a7a160c98 - Cache
    openssl/3.1.3#35e30a39a89ee3ae98929377ebe78913 - Cache
    zlib/1.3#06023034579559bb64357db3a53f88a4 - Cache
Build requirements
    autoconf/2.71#53be95d228b2dcb30dc199cb84262d8f - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50 - Cache
    gnu-config/cci.20210814#15c3bf7dfdb743977b84d0321534ad90 - Cache
    libtool/2.4.7#d55a3c2435c19e830fa77aa5c6c19350 - Cache
    m4/1.4.19#5be46f515185a510cd64fa785860749f - Cache
    meson/1.2.1#8b99e6cc4f6908b594c33d1b85cfa5bd - Cache
    msys2/cci.latest#567331f1604f3c584f04feade960f06e - Cache
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262 - Cache
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21 - Cache
    pkgconf/2.0.2#17d6b373de66a5ca46b34c36dd72e3bb - Cache
    strawberryperl/5.32.1.1#8f83d05a60363a422f9033e52d106b47 - Cache
Resolved version ranges
    openssl/[>=1.1 <4]: openssl/3.1.3
    zlib/[>=1.2.11 <2]: zlib/1.3

======== Computing necessary packages ========
Requirements
    libcurl/8.2.1#38190730f9424d073aa22f8a7a160c98:8fab80bbde1da5c3fc5977be2c96cb3fa64277c5 - Build
    openssl/3.1.3#35e30a39a89ee3ae98929377ebe78913:2b708c6e2e6a9f9c0b5079d720ff403abc8ccea0 - Build
    zlib/1.3#06023034579559bb64357db3a53f88a4:f60e50a74ab05a616895712be87aa8c9377863ad - Build
Build requirements
    autoconf/2.71#53be95d228b2dcb30dc199cb84262d8f:da39a3ee5e6b4b0d3255bfef95601890afd80709#ecdedaa05db7f162580f145df740c73b - Cache
    automake/1.16.5#058bda3e21c36c9aa8425daf3c1faf50:ebec3dc6d7f6b907b3ada0c3d3cdc83613a2b715#07094da42a0b39fd4b34760c5f1f3e7d - Cache
    gnu-config/cci.20210814#15c3bf7dfdb743977b84d0321534ad90:da39a3ee5e6b4b0d3255bfef95601890afd80709#22618e30bd9e326eb95e824dc90cc860 - Cache
    libtool/2.4.7#d55a3c2435c19e830fa77aa5c6c19350:74fce2c720f804facc619f996bab77ff99796c4d - Build
    m4/1.4.19#5be46f515185a510cd64fa785860749f:723257509aee8a72faf021920c2874abc738e029#a7c292926dcd97fd097bc89307567656 - Cache
    meson/1.2.1#8b99e6cc4f6908b594c33d1b85cfa5bd:da39a3ee5e6b4b0d3255bfef95601890afd80709#51dbda0520bc1033fd5d946750e9890f - Cache
    msys2/cci.latest#567331f1604f3c584f04feade960f06e:956a88975bda9dfcc485e2861d71e74bd7e2b9a5#ce3addef73068ed1ad9ca9976b2d50c1 - Cache
    nasm/2.15.05#ca1c14c2060af0ec151048b54ced9262:723257509aee8a72faf021920c2874abc738e029#88d82c8b5a0298a070ca691f347e6c05 - Cache
    ninja/1.11.1#77587f8c8318662ac8e5a7867eb4be21:723257509aee8a72faf021920c2874abc738e029#74ebd8f35f54015dcbf2b18a6adbd023 - Cache
    pkgconf/2.0.2#17d6b373de66a5ca46b34c36dd72e3bb:43771b8671ac44479c188dd72670e2eb2d7918a6 - Build
Skipped binaries
    strawberryperl/5.32.1.1

======== Installing packages ========
gnu-config/cci.20210814: Already installed! (1 of 13)
msys2/cci.latest: Already installed! (2 of 13)
ninja/1.11.1: Already installed! (3 of 13)

-------- Installing package zlib/1.3 (4 of 13) --------
zlib/1.3: Building from source
zlib/1.3: Package zlib/1.3:f60e50a74ab05a616895712be87aa8c9377863ad
zlib/1.3: Copying sources to build folder
zlib/1.3: Building your package in C:\Users\jakob\.conan2\p\b\zliba2ae364dd69ae\b
zlib/1.3: Calling generate()
zlib/1.3: Generators folder: C:\Users\jakob\.conan2\p\b\zliba2ae364dd69ae\b\build\Debug\generators
zlib/1.3: CMakeToolchain generated: conan_toolchain.cmake
zlib/1.3: CMakeToolchain generated: CMakePresets.json
zlib/1.3: CMakeToolchain generated: ..\..\..\src\CMakeUserPresets.json
zlib/1.3: Generating aggregated env files
zlib/1.3: Generated aggregated env files: ['conanbuild.bat', 'conanrun.bat']
zlib/1.3: Calling build()
zlib/1.3: Apply patch (conan): separate static/shared builds, disable debug suffix, disable building examples
zlib/1.3: Running CMake.configure()
zlib/1.3: RUN: cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="C:/Users/jakob/.conan2/p/b/zliba2ae364dd69ae/b/build/Debug/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="C:/Users/jakob/.conan2/p/b/zliba2ae364dd69ae/p" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Debug" "C:\Users\jakob\.conan2\p\b\zliba2ae364dd69ae\b\src"
'cmake' is not recognized as an internal or external command,
operable program or batch file.

zlib/1.3: ERROR: 
Package 'f60e50a74ab05a616895712be87aa8c9377863ad' build failed
zlib/1.3: WARN: Build folder C:\Users\jakob\.conan2\p\b\zliba2ae364dd69ae\b\build\Debug
*********************************************************
Recipe 'zlib/1.3' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: zlib/1.3: Error in build() method, line 84
	cmake.configure()
	ConanException: Error 1 while executing
CMake Error at conan_provider.cmake:386 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  conan_provider.cmake:477 (conan_install)
  CMakeLists.txt:6 (find_package)

-- Configuring incomplete, errors occurred!

[Failed to reload]

**Comment by memsharded** [comment] 2023-10-07 20:26
Hi @FleetAdmiralJakob 

Thanks for your report.

There are a couple of issues there:

- First, the warnings you see in the messages of the cmake-conan integration (this is not part of Conan client, but from the cmake-conan integration, it has its own repo, if it makes sense, we can move this ticket there), is about not having the CXX compiler defined. This can be problematic, because many dependencies do build in C++, and need CXX compiler defined in your CMake build. Take that into account, in case some of your dependencies build fail because of this.
- The error that you are seeing seems because ``cmake`` is not in the system path. It seems that you might be using some CMake in the first place that is not the system one, but the dependencies when they are built, they might need CMake as well, and if they cannot find CMake in the system path to execute, they will fail. Please try adding CMake to your system path. Another possible approach is adding a ``[tool_requires]`` to ``cmake/[>=3.25 <4]`` to your profile, and inject the profile via the new customization profiles (read https://github.com/conan-io/cmake-conan/tree/develop2)


Also, take into account that MinGW builds are not done in ConanCenter, but it uses MSVC compiler in Windows for building the packages and testing. That means that some recipes might not build cleanly with MinGW. We plan to add some more builds to ConanCenter in the future to improve this, but at the moment it is recommended to use MSVC in Windows if using ConanCenter packages (in any case if some dependency fails to build in MinGW, it would be great to know it, reporting an issue in https://github.com/conan-io/conan-center-index

Please let me know if adding cmake to the path or as tool-requires help and you can move forward. Thanks!

**Comment by FleetAdmiralJakob** [comment] 2023-10-07 21:08
Hi @memsharded, thank you so much for your answer! I had already worked on that problem for so long and couldn't move on. But with your help, I was able to remove some of the errors. So now the C++ errors are gone. Only the very last error is still there, saying that zlib is not able to build its binary.

**Comment by memsharded** [comment] 2023-10-07 21:12
Next time don't wait that long! We are sometimes overwhelmed, but we always try to help, so don't hesitate to open tickets the moment you have questions :)

Let me know how it goes with the zlib binary not building, if cmake in the path solves it or not, or if not, if you get any new output messages, please share them.

**Comment by FleetAdmiralJakob** [comment] 2023-10-07 21:36
Finally, I was able to build the zlib binary but now the openssl binary is not working. I removed the cmake-build-debug folder and tried it again but got the same error.

<details>
<summary>Part of the Logs</summary>

```
	apps/libapps.a -lssl -lcrypto -lz -lws2_32 -lgdi32 -lcrypt32 
make[1]: Leaving directory '/c/Users/jakob/.conan2/p/b/opensc5ad9e4d91590/b/src'

openssl/3.1.3: RUN: perl C:\Users\jakob\.conan2\p\b\opensc5ad9e4d91590\b\src/configdata.pm --dump
Can't open perl script "C:Usersjakob.conan2pbopensc5ad9e4d91590bsrc/configdata.pm": No such file or directory

openssl/3.1.3: ERROR: 
Package '2b708c6e2e6a9f9c0b5079d720ff403abc8ccea0' build failed
openssl/3.1.3: WARN: Build folder C:\Users\jakob\.conan2\p\b\opensc5ad9e4d91590\b\build-debug
*********************************************************
Recipe 'openssl/3.1.3' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter, report it at https://github.com/conan-io/conan-center-index/issues
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: openssl/3.1.3: Error in build() method, line 520
	self.run(f"{self._perl} {self.source_folder}/configdata.pm --dump")
	ConanException: Error 2 while executing
CMake Error at conan_provider.cmake:386 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  conan_provider.cmake:477 (conan_install)
  CMakeLists.txt:9 (find_package)


-- Configuring incomplete, errors occurred!

[Failed to reload]
```

</details>

**Comment by memsharded** [comment] 2023-10-07 23:19
Thanks for the feedback.

```
"C:Usersjakob.conan2pbopensc5ad9e4d91590bsrc/configdata.pm"
```
This seems an issue of the openssl recipe building under mingw. The openssl build system is very complicated, using perl. It is totally possible that it doesn't build correctly in MinGW. Most of the package in ConanCenter that requires some autotools support use ``msys2``, are you using MinGW from it or an independent one.

The next step would be to check openssl recipe, and if it builds cleanly with mingw or not, I'll give it a try, but if you want to try it:
```
conan install --requires=openssl/3.1.3 --build=missing -pr=mymingwprofile
```
with profile obtained from the above:
```
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Windows
[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={'c': 'C:/Users/jakob/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe'}
```
Also note that for the "build" profile, it is possible to use a more standard profile with msvc, so the ``tool-requires`` maybe can be used from pre-compiled binaries, instead of requiring to build them from source with mingw too.

**Comment by memsharded** [comment] 2023-10-07 23:46
I have managed to reproduce down to that error, after a bunch of building, with the above command. At least we can reproduce, lets see if I can come up with a fix for the recipe.

**Comment by FleetAdmiralJakob** [comment] 2023-10-08 07:51
Currently I'm a starter in the world of C so I really don't know anything about `msys2` but this is my CLion Setup:
![image](https://github.com/conan-io/conan/assets/77451351/29251546-aa2f-45d4-b799-2ec5ffc2f83d)

**Comment by FleetAdmiralJakob** [comment] 2023-10-08 07:54
And I ran the profile command from above, but it seems that I don't have a `mymingwprofile`
So, what should I do @memsharded?

**Comment by memsharded** [comment] 2023-10-08 23:40
The profile should be saved in a file called ``mymingwprofile`` (or as you want).

I managed to finally get the OpenSSL recipe building with MinGW, and I have submitted a fix in https://github.com/conan-io/conan-center-index/pull/20448, as you can see it was the subtle detail that MinGW do no like windows backslashes. I managed to build it with the profile:
```
[settings]
arch=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Windows

[conf]
tools.cmake.cmaketoolchain:generator=Ninja
tools.build:compiler_executables={'c': 'C:/ws/msys64/mingw64/bin/gcc.exe','cpp': 'C:/ws/msys64/mingw64/bin/g++.exe'}

[tool_requires]
ninja/[*]

[buildenv]
PATH+=(path)C:/ws/msys64/mingw64/bin
```
That means that it is necessary to have MinGW in the path, beyond that ``tools.build:compiler_executables``, which I think it might already be in your CLion setup, but better check it.

Lets wait until https://github.com/conan-io/conan-center-index/pull/20448 is merged, and then lets try again.

**Comment by FleetAdmiralJakob** [comment] 2023-10-09 18:23
Yeah, I will not try it out because I switched to Visual Studio and now it works

**Comment by memsharded** [comment] 2023-10-09 18:32
> Yeah, I will not try it out because I switched to Visual Studio and now it works

Ok, great. Yes, the robustness when using VS as compiler is expected to be higher than MinGW. 
In any case your feedback was valuable, https://github.com/conan-io/conan-center-index/pull/20448 will fix openssl recipe to also work in MinGW now. If you later need to work with MinGW, don't hesitate to create new tickets and report and we will try to help with that.

Then, if things work now, should we consider this ticket solved and close it? (you can always create new tickets for any further issue that you might have) Thanks again for your feedback!

**Comment by FleetAdmiralJakob** [comment] 2023-10-09 18:42
Yes, I think when this PR is merged I will close this ticket

**Comment by memsharded** [comment] 2023-10-11 21:05
https://github.com/conan-io/conan-center-index/pull/20448 has been merged, the conflict should be gone, could you please check and if things work now close the ticket? Thanks!

**Closed as completed** 2023-10-12 14:14 UTC
Labels: stage: triaging

**Comment by gl0522** [comment] 2025-02-12 10:07
1. Using cmake to build nmos cpp source code in Ubuntu 22.04 system yields the following error message:


CMake Error: CMAKE_PROJECT_TOP_LEVEL_INCLUDES file does not exist: third_party/cmake/conan_provider.cmake
CMake Error at Development/third_party/cmake/conan_provider.cmake:590 (cmake_language):
  cmake_language Dependency providers can only be set as part of the first
  call to project().  More specifically,
  cmake_language(SET_DEPENDENCY_PROVIDER) can only be called while the first
  project() command processes files listed in
  CMAKE_PROJECT_TOP_LEVEL_INCLUDES.
Call Stack (most recent call first):
  CMakeLists.txt:25 (include)

2. The configuration files used by cmake are as follows:

# the injection point may be used to configure conan, but that requires CMake 3.24 or higher
# so avoid confusion and reject invocations which attempt to use it on lower versions
# see https://cmake.org/cmake/help/v3.24/variable/CMAKE_PROJECT_TOP_LEVEL_INCLUDES.html
# the alternative is to run conan install first instead
#cmake_minimum_required(VERSION 3.22)

# Ensure the build directory is clean
cmake_minimum_required(VERSION 3.24.2)

project(nmos-cpp)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/Development/cmake")

set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES "${CMAKE_BINARY_DIR}/third_party/cmake/conan_provider.cmake")

#if(CMAKE_PROJECT_TOP_LEVEL_INCLUDES)
#  cmake_minimum_required(VERSION 3.24 FATAL_ERROR)
#    else()
#       cmake_minimum_required(VERSION 3.17 FATAL_ERROR)
#    endif()
    #cmake_minimum_required(VERSION 3.17 FATAL_ERROR)
# project name
if(CMAKE_PROJECT_TOP_LEVEL_INCLUDES)
        #Include the specified file for Conan configuration or other setup
                        include(${CMAKE_PROJECT_TOP_LEVEL_INCLUDES})
                endif()

#project(nmos-cpp)

enable_language(CXX)
# enable or disable the example applications
set(NMOS_CPP_BUILD_EXAMPLES ON CACHE BOOL "Build example applications")

# the injection point may be used to configure conan, but that requires CMake 3.24 or higher
# so avoid confusion and reject invocations which attempt to use it on lower versions
# see https://cmake.org/cmake/help/v3.24/variable/CMAKE_PROJECT_TOP_LEVEL_INCLUDES.html
# the alternative is to run conan install first instead
#cmake_minimum_required(VERSION 3.22)

# Ensure the build directory is clean
cmake_minimum_required(VERSION 3.24.2)

project(nmos-cpp)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/Development/cmake")

set(CMAKE_PROJECT_TOP_LEVEL_INCLUDES "${CMAKE_BINARY_DIR}/third_party/cmake/conan_provider.cmake")

#if(CMAKE_PROJECT_TOP_LEVEL_INCLUDES)
#  cmake_minimum_required(VERSION 3.24 FATAL_ERROR)
#    else()
#       cmake_minimum_required(VERSION 3.17 FATAL_ERROR)
#    endif()
    #cmake_minimum_required(VERSION 3.17 FATAL_ERROR)
# project name
if(CMAKE_PROJECT_TOP_LEVEL_INCLUDES)
        #Include the specified file for Conan configuration or other setup
                        include(${CMAKE_PROJECT_TOP_LEVEL_INCLUDES})
                endif()

#project(nmos-cpp)

enable_language(CXX)
# enable or disable the example applications
set(NMOS_CPP_BUILD_EXAMPLES ON CACHE BOOL "Build example applications")

# enable or disable the unit test suite
set(NMOS_CPP_BUILD_TESTS ON CACHE BOOL "Build test suite application")

# enable or disable the LLDP support library (lldp)
# and its additional dependencies
set(NMOS_CPP_BUILD_LLDP OFF CACHE BOOL "Build LLDP support library")
mark_as_advanced(FORCE NMOS_CPP_BUILD_LLDP)

# common config
include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppCommon.cmake)

# nmos-cpp dependencies
include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppDependencies.cmake)

# nmos-cpp libraries
include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppLibraries.cmake)

if(NMOS_CPP_BUILD_EXAMPLES)
    # nmos-cpp-node executable
    include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppNode.cmake)

    # nmos-cpp-registry executable
    include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppRegistry.cmake)
endif()

if(NMOS_CPP_BUILD_TESTS)
    # nmos-cpp-test executable
    include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppTest.cmake)
endif()

# export the config-file package
include(${CMAKE_SOURCE_DIR}/Development/cmake/NmosCppExports.cmake)



3.May I ask what the problem is?

**Comment by memsharded** [comment] 2025-02-12 11:02
Hi @gl0522 

This is a closed issue, please create a new ticket instead.

If this is a question about ``cmake-conan``, better create it in the ``cmake-conan`` repository, not this one.

Please try to format the ticket correctly, the above comment is practically unreadable, check how github comment syntax work. Many thanks for your feedback.
