### ISSUE TITLE
Package name for dependencies while resolving/calling find_package()

### ISSUE THREAD

**Issue by vithalsm** [conan-io/conan#14896] opened 2023-10-09 04:27 UTC
### What is your question?

Here is the scenario.
A conan lib package with name 'nanopb' exists.  Also provides FindNanopb.cmake (MODULE mode).

When it's included as dependent library and searched using find_package(Nanopb), able to find 'FindNanopb.cmake' and rest works fine.  Assume this library as libabc

  Now, when 'libabc' is included as dependent lib in another conan repo (say xyz), things fail.  Reason being it tries to look for 'Find**nanopb**.cmake' (Please note the spelling) and fails.

Further analysis shows that, first dependency list is built for libabc which includes the names as 'nanopb' in this case.  Then, libabc-config.cmake tries to find the module for each of the names in the dependency list i.e. triggers module find for 'nanopb' and hence tries to search Findnanopb.cmake.  But expected, this file doesn't exists (FindNanopb.cmake exists).

foreach(_DEPENDENCY ${libabc_FIND_DEPENDENCY_NAMES} )
     22     # Check that we have not already called a find_package with the transitive dependency
     23     if(NOT ${_DEPENDENCY}_FOUND)
     24         find_dependency(${_DEPENDENCY} REQUIRED ${${_DEPENDENCY}_FIND_MODE})     >>>>>>>>>
     25     endif()
     26 endforeach(

One the ways is to keep the name of package and Findxxx same i.e. nanopb in this case.  

But, just wondering if conan provides a way to address such scenarios where behavior is different when find_package() is called directly or indirectly via another package.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-10-09 07:56
Hi @vithalsm 

Thanks for your question.
Yes, conan has a way to adapt the cases when different names are used, without patching.

The filename is defined by the ``cmake_file_name`` property. It is defined for recipes for all consumers, when the filename is different from the package name(lowercase).

Consumers can do something like:
```python
def generate(self):
     deps = CMakeDeps(self)
     deps.set_property("nanopb", "cmake_file_name", "NanoPBNewName")
     deps.set_property("nanopb", "cmake_find_mode", "module")
     deps.generate()
```
It can also control if it generates a module file or a config file (config files always recommended instead of modules)

**Comment by vithalsm** [comment] 2023-10-12 14:38
Thanks.  Trying with that.
Facing another problem, if you can help.
For nanopb target nanopb::protobuf-nanopb-static STATIC IMPORTED library is created (nanopb-targets.cmake).  No GLOBAL option present.
But target_link_library(xyz nanopb::protobuf-nanopb-static) doesnt exceed and gets error as target nanopb::protobuf-nanopb-static is not found.
Any specific directories to be included?

**Comment by memsharded** [comment] 2023-10-12 19:36
Hi @vithalsm 

Sorry, the issue is not very clear. It would be great to have actual code, that we can reproduce, or have the full files, commands, and output logs to understand what is the issue. For example, when CMake find the ``xxx-config.cmake`` files generated by Conan, they will print the names of the targets that they create, and that can be useful to understand what is happening.

**Comment by vithalsm** [comment] 2023-10-13 05:16
Sorry for not being clear enough @memsharded.

Downloaded conan recipe for nanopb (0.3.9.9) in local conan-center-index and building it.

Mode is enforced to MODULE and able to find FindNanopb.cmake provided with the package and nanopb itself builds fine.

I could see that, it generates IMPORTED target with the name nanopb::protobuf-nanopb-static

----------------------------
Generated file: ~/.conan2/p/nanop87f9ef409c1e4/p/lib/cmake/nanopb/nanopb-targets.cmake
# Create imported target nanopb::protobuf-nanopb-static

add_library(nanopb::protobuf-nanopb-static STATIC IMPORTED)   >>>>>>>>>> Doesn't have GLOBAL
set_target_properties(nanopb::protobuf-nanopb-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "PB_FIELD_32BIT"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

----------------------------

Now, added a test_package for nanopb to test linking with the nanopb.

find_package(Nanopb REQUIRED)   >>>>>>>>  Detects FindNanopb.cmake file n location properly
include_directories(${NANOPB_INCLUDE_DIRS})
include_directories(${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(test-pkg, nanopb::protobuf-nanopb-static)  >>>>>> This throws error stating target lib nanopb:: not found.

------------------------------
CMake Error at CMakeLists.txt:22 (target_link_libraries):
  Target "test_package" links to:

    nanopb::protobuf-nanopb-static

    but the target was not found.  Possible reasons include:
  
------------------------------

**Comment by memsharded** [comment] 2023-10-13 10:17
Hi again,

Sorry I am a bit lost here:

> Downloaded conan recipe for nanopb (0.3.9.9) in local conan-center-index and building it.

The ``nanopb`` package does not exist in ConanCenter, I cannot find it in https://conan.io/center or in the source https://github.com/conan-io/conan-center-index

Without having the package it is quite challenging to understand what could be happening. Could you please clarify?

**Comment by memsharded** [comment] 2024-10-18 21:32
Closing this ticket as staled, please re-open or create a new ticket if there are any further questions or issues, thanks for the feedback.

**Closed as not planned by memsharded** 2024-10-18 21:32 UTC
Labels: type: question
