### ISSUE TITLE
conan remove asks to remove unrelated recipe

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#369] opened 2016-07-14 11:44 UTC
I have the following three recipes locally:

* zlib/1.2.8@habrich/testing
* dcmtk/3.6.1_20131114@habrich/testing
* Qt/5.7.0@habrich/testing

When I run `conan remove zlib/1.2.8@habrich/testing`, conan asks me if I want to delete 'zlib/1.2.8@habrich/testing' as well as 'Qt/5.7.0@habrich/testing'. The same happens when I run `conan remove dcmtk/3.6.1_20131114@habrich/testing`. Conan asks me if I want to delete 'Qt/5.7.0@habrich/testing' in addition to the matching recipe.

Just a little annoying, nothing really critical though.

**Comment by Blubbz0r** [comment] 2016-07-15 08:02
It's possible that this is already fixed with version 0.10.1. I was still running 0.10.0 while experiencing this issue. After an update I did not see any incorrect deletion inquiries any more. If no one else can reproduce this with 4.10.1 or if there is an obvious fix in that version, than this issue can be closed.

**Comment by memsharded** [comment] 2016-07-15 08:05
I am trying to reproduce it without success. I will try to revert to 0.10.0, to check if it was already fixed.

**Comment by memsharded** [comment] 2016-07-15 08:18
Sorry, I have reverted both to 0.10.0 and 0.9.3, and not able to reproduce this error. Not sure about what could happen, but if it is not a problem anymore, let's close the issue, please reopen if something happens again. Thanks for reporting!

**Closed by memsharded** 2016-07-15 08:18 UTC
Labels: bug
