### ISSUE TITLE
How to modify `conan upload` timeout?

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#6006] opened 2019-10-31 01:06 UTC
It looks like with larger artifacts the default 60s timeout is too short. How can it be modified?

Seeing this:

ERROR: HTTPSConnectionPool(host='conan.ci.eng.myserver.com', port=443): Max retries exceeded with url: /artifactory/api/conan/conan-local/v1/files/myserve/MyProject/1.0.3119+a0b58e64/branch_myBranch/package/c5e32a619a6c12e5573fc7cb3dfed53f4ae48cde/conan_package.tgz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='conan.ci.eng.myserver.com', port=443): Read timed out. (read timeout=60.0)",))

On the Artifactory side, all seems valid, with the client aborting the connection exactly 60s after it began.

**Comment by memsharded** [comment] 2019-10-31 08:49
Hi @w3sip 

No, Conan can upload artifacts very large, that will take much longer than 60 seconds.
That timeout is a timeout that the server does not respond at all during 60 seconds. During transfers of big artifacts, the server will be responding continuously during the upload. In most cases I wouldn't advise to increase its value.

If you still want to modify it, you have the value in conan.conf: https://docs.conan.io/en/latest/reference/config_files/conan.conf.html

**Comment by w3sip** [comment] 2019-11-01 16:29
I'm not so confident this is accurate. We had a very large (>3GB) artifacts consistently failing with the above timeout; once the package size had been reduced, the consistently succeed.

Another problem uploading large artifacts has been observed on Windows:

Uploading conan_package.tgz                                           
ERROR: long int too large to convert to int
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conan_package.tgz, 'long int too large to convert to int'

Quick search shows this has been reported (and I assume fixed?) two years ago, did it resurface again recently?

**Comment by memsharded** [comment] 2019-11-01 22:08
I think the error might be related to other things, rather than the limit. There are some very occasional reports of download of huge packages that fail, still not clear the reasons. But sure, modify the limit in conan.conf, and please report the results.

Otherwise, if still failing, tell us about the context: the versions used of everything, the OSs running, for python, also the version of python and if it is 32 or 64 bits python.

**Comment by w3sip** [comment] 2019-11-02 04:33
Yep, still failing even after modifying the timeout.

Last running Conan 1.18.0 (tried to downgrade from 1.19.3, to no avail). Client side runs on Appveyor Windows instance, Artifactory server v6.5.2.

Initially ran with 32-bit Python 2.7, which was the reason for the error above. After switching to 64-bit Python 3.5, the error message no longer occurs (e.g. the upload is actually attempted). However, the only output seen on the client side is as follows:

conan upload --force -r company --all --confirm %CONAN_REF%
Uploading to remote 'company':
Uploading Installer/1.0.3117+689074f1@company/branch_feat_mybranch to remote 'company'
Compressing recipe...
Uploading conanfile.py                                                
..
Uploading conanmanifest.txt                                           
..
Uploaded conan recipe 'Installer/1.0.3117+689074f1@company/branch_feat_mybranch' to 'company': *****
Uploading package 1/1: a80b74a5307becb3ce91637987aae71ea5d4873e to 'company'
Compressing package...
[==================================================]
Requesting upload urls...Done!                                        
Uploading conan_package.tgz                                           
...........................

Note that progress is actually updated up until the failure, and no reason for failure is show -- the text above is the end of output.

On the server side, seeing the following in the logs:

Artifactory.log
2019-11-02 03:57:47,928 [http-nio-8081-exec-46] [INFO ] (o.a.e.UploadServiceImpl:376) - Deploy to 'conan-local:company/Installer/1.0.3117+689074f1/branch_feat_mybranch/package/a80b74a5307becb3ce91637987aae71ea5d4873e/conan_package.tgz' Content-Length: 0

Request.log
20191102035738|269|REQUEST|67.225.164.53|ci|GET|/api/conan/conan-local/v1/conans/Installer/1.0.3117+689074f1/company/branch_feat_mybranch/packages/a80b74a5307becb3ce91637987aae71ea5d4873e|HTTP/1.1|200|0
20191102035738|4|REQUEST|67.225.164.53|ci|POST|/api/conan/conan-local/v1/conans/Installer/1.0.3117+689074f1/company/branch_feat_mybranch/packages/a80b74a5307becb3ce91637987aae71ea5d4873e/upload_urls|HTTP/1.1|200|84
20191102035747|31|REQUEST|67.225.164.53|ci|PUT|/api/conan/conan-local/v1/files/company/Installer/1.0.3117+689074f1/branch_feat_mybranch/package/a80b74a5307becb3ce91637987aae71ea5d4873e/conan_package.tgz|HTTP/1.1|404|0

Nothing for this build in access.log

Obviously, that "Content-Length: 0" is wrong -- and not quite sure what is causing it. Haven't been able to reproduce from a local Windows client manually invoking `conan upload`.

Would appreciate any tips on how to further troubleshoot it.

**Comment by memsharded** [comment] 2019-11-02 21:37
Now that I recall, this is the second time some problem similar in the Windows OS, with same problems to reproduce in other machines, like it only happens in very specific machines. It was not for uploads, only for downloads: https://github.com/conan-io/conan/issues/5708. We tried to reproduce locally without success. Once the package is uploaded (from other machine), are you able to download it correctly in those failing machines? Could you try it, please?

Is the failure at least deterministic? Does it fail always the same way in the same (appveyor) machine? Is it a public appveyor build, could we have access to what is being uploaded and in which context? That might help to try to investigate what is happening.

**Comment by w3sip** [comment] 2019-11-02 22:04
Unfortunately, the build isn't public, but I'll try to reproduce with a public github repo. It's definitely deterministic in the context of this particular project, and I believe it has to do with the artifact size. Gut feeling, max int32 is the max artifact size for successful completion: the largest artifact we've uploaded from Windows so far is around 1.3GB, and it's the first time they are above 2.1GB.

I'm not in a position to try it until Monday, but I believe a conanfile creating artifact based on something that won't compress very well (say, a 3-4GB video file), will reproduce it, at least in the Appveyor environment.

**Comment by w3sip** [comment] 2019-11-03 01:52
Looks like it is an Appveyor problem after all. It is killing the job based on an implicit outgoing traffic limit. Explains why I could not reproduce it locally.
Sorry for the false alarm (I guess it began as sort of real until switching to 64-bit Python ;) ). Thanks for your help!

**Comment by tsondergaard** [comment] 2022-07-05 22:03
Just now ran into a problem uploading a 3 GiB qt package (with qtwebengine/chromium enabled) to artifactory-ce using the derby database. The problem was persistent in at least five consecutive upload attempts. `conan config set general.request_timeout=180` fixed it.

**Comment by memsharded** [comment] 2022-07-05 22:15
Correct. 

For readers awareness, in Conan 2.0, it will be the ``core.net.http:timeout`` config in ``global.conf`` file.

**Comment by johan-boule** [comment] 2022-09-24 11:19
When using conan as a server, aren't there timeouts to tune on its side too ?

Looking at conans/server/conf/default_server_conf.py, I see:

```
default_server_conf = """[server]

# Authorize timeout are seconds the client has to upload/download files until authorization expires
authorize_timeout: 1800

# Just for disk storage adapter
# updown_secret is the key used to generate the upload/download authorization token
disk_authorize_timeout: 1800
```

I can systematically reproduce a disconnection after 15mins, but that doesn't match with 1800 seconds.

```
Uploading conan_package.tgz :  19%|#9        | 32.5M/171M [15:03<1:10:49, 134.1kB/s]
ERROR: HTTPConnectionPool(host='xxxxxx', port=xxxxx): Max retries exceeded with url:
/v2/conans/openjdk/16.0.1/_/_/revisions/7bbf2b1543f342aac68057e8f9ddd683/packages/ca33edce272a279b24f87dc0d4cf5bbdcffbc187/revisions/96dd9f98f5695daea61b90d5ac2df07a/files/conan_package.tgz
(Caused by ProtocolError('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None)))
```

Perhaps our conan server doesn't have the default configuration, but I can't check it. It was installed some years ago, so maybe the default config used to be 900 seconds some years ago ? I tried to check the history of this github repo, but the initial commit only starts in 2015 and it was already 1800 seconds at that time.

**Comment by memsharded** [comment] 2022-09-24 12:03
@johan-boule Maybe you also have some env-vars like CONAN_AUTHORIZE_TIMEOUT configured in the server machine? they will have precedence over the conf file.

In any case, I'd highly recommend using ArtifactoryCE, it is much faster and scale much better, it is completely free to use, it has a WebUI, it is relatively easy to setup and maintain, and many other improvements.

**Comment by memsharded** [comment] 2023-12-30 23:27
Closing as solved

**Closed by memsharded** 2023-12-30 23:27 UTC
Labels: type: question, stage: triaging
