### ISSUE TITLE
[bug] Unable to connect to https://center.conan.io using conan

### ISSUE THREAD

**Issue by antaljanosbenjamin** [conan-io/conan#11603] opened 2022-07-10 16:53 UTC
I cannot connect to `center.conan.io` using conan. From my browser I can reach the address and download a text file which redirects me to `https://conan.io/center/`, but I am not sure how relevant is that. I started to experience this today.

### Environment Details (include every applicable attribute)
  * Operating System+version: Linux Mint 20.3 (based on Ubuntu 20.04)
  * Compiler+version: GCC 9.3.0 and Clang 12, but not relevant
  * Conan version: 1.50.0
  * Python version: 3.8.10

But the same thing happens also on [Github hosted runners](https://github.com/antaljanosbenjamin/miscellaneous/runs/7271709063?check_suite_focus=true#step:7:81).
### Steps to reproduce (Include if Applicable)
```
conan search "openssl/*" -r=conancenter
```

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ReadTimeoutError("HTTPSConnectionPool(host='center.conan.io', port=443): Read timed out. (read timeout=60.0)"))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

Logs from Github hosted runners where conan is call from CMake:
```
robin-hood-hashing/3.11.5: Not found in local cache, looking in remotes...
robin-hood-hashing/3.11.5: Trying with 'conancenter'...
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by ReadTimeoutError("HTTPSConnectionPool(host='center.conan.io', port=443): Read timed out. (read timeout=60.0)"))
Unable to connect to conancenter=https://center.conan.io/
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
CMake Error at build/conan.cmake:544 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:886 (old_conan_cmake_install)
  CMake/External.cmake:44 (conan_cmake_run)
  CMakeLists.txt:30 (run_conan)
-- Configuring incomplete, errors occurred!
See also "/home/runner/work/miscellaneous/miscellaneous/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ssrobins** [comment] 2022-07-10 17:07
Yup, same here. I couldn't find any website that gives any statement about downtime or an incident.

**Comment by loachfish** [comment] 2022-07-10 17:33
I got this too.

**Comment by ilyamt-tandemg** [comment] 2022-07-10 17:33
Duplicate of: https://github.com/conan-io/conan/issues/11602

**Comment by antaljanosbenjamin** [comment] 2022-07-10 18:39
Indeed, the issue is a duplicate one. Please feel free to close this one.

**Comment by memsharded** [comment] 2022-07-10 19:23
Thanks all for reporting. We are having a look, sorry for the inconvenience.
There is already a pinned issue for others to find easily, closing this.

**Closed as completed by memsharded** 2022-07-10 19:24 UTC

**Comment by memsharded** [comment] 2022-07-10 20:07
Please track the pinned issue: https://github.com/conan-io/conan/issues/11604

**Comment by memsharded** [comment] 2022-07-10 23:29
Check https://github.com/conan-io/conan/issues/11604, service should be back to normal now. Thanks again for reporting!
