### ISSUE TITLE
Specifying link order of a conan package

### ISSUE THREAD

**Issue by kevswims** [conan-io/conan#1983] opened 2017-11-02 18:18 UTC
I have a conan package that includes a set of prebuilt binaries. ie. liba.a and libb.a. When calling
`target_link_libraries(nameOfSharedLibrary CONAN_PKG::PackageName)`
 the libraries are linked to in the wrong order (libb.a liba.a). To work around this I am linking to these I am calling 
`target_link_libraries(nameOfSharedLibrary ${CONAN_LIB_DIRS_PACKAGENAME}/liba.a ${CONAN_LIB_DIRS_PACKAGENAME}/libb.b)`. 

Is there a way to specify what this link order should be for a package? Either when creating the package or from the consuming project?

**Comment by memsharded** [comment] 2017-11-02 18:30
I think the libraries should be in the order they are declared in the ``package_info()`` method, like:

```python
def package_info(self):
    self.cpp_info.libs = ["a", "b"]
```
Can you please check your ``package_info()``? If not maybe it is a bug and should be fixed.

**Comment by kevswims** [comment] 2017-11-02 19:55
Looks like I was using `self.cpp_info.libs = self.collect_libs()` I will try explicitly setting them. Does `self.collect_libs() `sort by alphabetic order?

**Comment by memsharded** [comment] 2017-11-02 20:58
Nop, under the hood ``collect_libs()`` is using a ``os.listdir`` call, which does not guarantee the result order. And enforcing an alphabetic order on them in conan code is also quite arbitrary. I suggest going for the explicit definition, it should be more robust than the collects_libs one.

**Comment by danimtb** [comment] 2017-12-23 11:07
There is an issue about this to add a warning in the docs https://github.com/conan-io/docs/issues/443 due to the same issue here https://github.com/conan-io/conan/issues/2201

**Comment by r-darwish** [comment] 2018-03-13 20:46
I'm replying here as a followup for [this issue](https://github.com/bincrafters/community/issues/176). This issue is a bug in the package itself. However, due to the arbitrary order of `os.listdir` this bug was hard to reproduce and track down. It occurred on some machines, and on some didn't. 

I agree that sorting the libraries alphabetically won't magically solve the dependency graph, and that it is up to the package maintainer to maintain the correct order. However, making `tools.collect_libs`'s order deterministic will help spotting such issues.

**Comment by danimtb** [comment] 2018-03-14 13:12
Hi @r-darwish 

There is no bug in the behavior of `tools.collect_libs()` as there is a warning regarding the order in the documentation. However, I see your point and maybe it should follow the same alphabetically order in all OS to be mor consistent.

Would you like to contribute with that enhancement? 😄

**Comment by danimtb** [comment] 2018-06-20 12:41
I thinks this could be closed due to lack of activity. Please open a new issue with info updated for `tools.collect_libs()` enhancements if needed.

**Closed by danimtb** 2018-06-20 12:41 UTC
Labels: question
