### ISSUE TITLE
"Permission denied" when running `conan install . ` second time and imported symlink already exists

### ISSUE THREAD

**Issue by Talkless** [conan-io/conan#5831] opened 2019-09-27 05:54 UTC
To help us debug your issue please explain:

- [x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [ x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x ] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Debian 9 (stretch) amd64
Conan 1.18.5
Python 3.5.4

Let's have this `conanfile.txt`:
```
[requires]
OpenSSL/1.0.2s@conan/stable

[options]
OpenSSL:shared=True
OpenSSL:no_zlib=True

[imports]
lib, libss* -> .
lib, libcrypto* -> .
```

Let's run `conan install . ` first time (fine):
```
conan install . -if=install
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    OpenSSL/1.0.2s@conan/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.0.2s@conan/stable:b2a09ca1ad3b8c8a33d398a8b1748e063194b54e - Cache

OpenSSL/1.0.2s@conan/stable: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
conanfile.txt imports(): Copied 2 '.0' files: libssl.so.1.0.0, libcrypto.so.1.0.0
conanfile.txt imports(): Copied 2 '.a' files: libssl.a, libcrypto.a
conanfile.txt imports(): Copied 2 '.so' files: libcrypto.so, libssl.so
```

Run second time:
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=6
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

conanfile.txt: Installing package
Requirements
    OpenSSL/1.0.2s@conan/stable from 'conan-center' - Cache
Packages
    OpenSSL/1.0.2s@conan/stable:b2a09ca1ad3b8c8a33d398a8b1748e063194b54e - Cache

OpenSSL/1.0.2s@conan/stable: Already installed!
conanfile.txt: Generator txt created conanbuildinfo.txt
conanfile.txt: Generated conaninfo.txt
conanfile.txt: Generated graphinfo
Traceback (most recent call last):
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/command.py", line 1859, in run
    method(args[0][1:])
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/command.py", line 471, in install
    lockfile=args.lockfile)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/conan_api.py", line 78, in wrapper
    return f(*args, **kwargs)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/conan_api.py", line 577, in install
    no_imports=no_imports)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/manager.py", line 114, in install
    run_imports(conanfile, install_folder)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/importer.py", line 82, in run_imports
    conanfile.imports()
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/loader_txt.py", line 108, in imports
    conan_file.copy(*import_params)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/importer.py", line 160, in __call__
    excludes=excludes, keep_path=keep_path)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/file_copier.py", line 75, in __call__
    keep_path, excluded_folders=excluded)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/file_copier.py", line 93, in _copy
    copied_files = self._copy_files(files_to_copy, src, dst, keep_path, symlinks)
  File "/tmp/conantest/_python_3.5.3_venv_conan_1.18.4/lib/python3.5/site-packages/conans/client/file_copier.py", line 221, in _copy_files
    shutil.copy2(abs_src_name, abs_dst_name)
  File "/usr/lib/python3.5/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/tmp/conantest/install/libssl.so.1.0.0'

ERROR: [Errno 13] Permission denied: '/tmp/conantest/install/libssl.so.1.0.0'
```

**Comment by czoido** [comment] 2019-09-27 16:58
Hello @Talkless,
I think that the issue is not related to symlinks but to the permissions that are set in the building process by OpenSSL for the library files. 
Have you tried to do the same with another version like for example `OpenSSL/1.1.1@conan/stable`?
Please, let me know what you think about that and thanks a lot for your feedback :)

**Comment by Talkless** [comment] 2019-09-29 08:35
@czoido 
>I think that the issue is not related to symlinks but to the permissions that are set in the building process of that version of OpenSSL for the library files.

Right, permissions for the symlink does not allow anyone to write:
```
$ stat --format %A install/libssl.so.1.0.0
-r-xr-xr-x
```
>Have you tried the same with another version such as OpenSSL/1.1.1c@conan/stable that has symlinks imported as well?

1.1.1 works fine. I'll check if there's build option for 1.0.x to disable setting permissions, and see if I can write a patch for the package.

**Comment by czoido** [comment] 2019-09-30 08:45
As the solution seems clear I'm closing the issue. Thanks for the feedback

**Closed by czoido** 2019-09-30 08:45 UTC
Labels: stage: triaging
