### ISSUE TITLE
[question] tools.replace_in_file does not work in package()

### ISSUE THREAD

**Issue by braindevices** [conan-io/conan#7071] opened 2020-05-22 22:05 UTC
During `package()` I want to replace some string in the files in package folder. But when I do `tools.replace_in_file('bin/some.sh', '@somepath@', self.package_folder)` It always said cannot find target file. But if I use `os.path.join(self.package_folder, 'bin/some.sh')` it works. From the document it seems only modify the files in source folder. However, I did not find any code actually limit the `tools.replace_in_file` to only work in source folder. What did I miss here? Should we make the replace_in_file works with relative path in most of the scenarios: source, build, package, deploy? 

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2020-05-23 17:08
The issue is that the cwd for the ``package()`` method is the ``build_folder``, not the package folder. You package from the build folder to a new place. So the first argument you should use the ``os.path.join(self.build_folder, "bin/some.sh"))``.

Besides that, a word of caution: this ``package()`` method works at package creation time. The ``self.package_folder`` will be an absolute path in the machine that is building this package. When you upload this package to a server and then install from another machine, the absolute path will be invalid, and not exist in the new machine. So I would strongly discourage this approach, unless I am missing something.

**Closed as completed** 2024-03-05 07:25 UTC
Labels: stage: triaging
