### ISSUE TITLE
[question] export-pkg: specify the 'user' and the 'channel' or neither of them

### ISSUE THREAD

**Issue by pdigiglio** [conan-io/conan#10913] opened 2022-03-28 21:01 UTC
I'm developing a conan package for my own header-only library and I get this error:

```sh
$ conan export-pkg . -sf ./tmp/src -bf ./tmp/build
ERROR: Specify the 'user' and the 'channel' or neither of them
```

I tried to explicitly pass the reference to `export-pkg` as:

 * `demo/testing`;
 * `bitmask_enum/0.0.1@`;
 * `bitmask_enum/0.0.1@demo/testing`;
 * `bitmask_enum/0.0.1@/`.

None of the above worked.

I'm running version 1.46.2 on Windows 10 Pro, installed through the windows installer (did not try `pip`).
I get the same error both with:
 * mintty 3.5.3 (x86_64-pc-msys) [Windows 19042];
 * Power Shell.

The full script I run to test my conan package is the following:

```sh
#!/bin/sh

typeset -r conan_root=tmp
typeset -r src_folder=${conan_root}/src
typeset -r inst_folder=${conan_root}/instal
typeset -r build_folder=${conan_root}/build
typeset -r pkg_folder=${conan_root}/pkg

rm -rvf tmp/*

echo "> conan source"
conan source  . \
    --source-folder "$src_folder" \
    || exit 1

echo "> conan install"
conan install . \
    --install-folder "$inst_folder" \
    || exit 1

echo "> conan build"
conan build . \
    --install-folder "$inst_folder" \
    --build-folder "$build_folder" \
    || exit 1

echo "> conan package"
conan package . \
    --source-folder "$src_folder" \
    --install-folder "$inst_folder" \
    --build-folder "$build_folder" \
    --package-folder "$pkg_folder" \
    || exit 1

echo "> conan export-pkg"
conan export-pkg . \
    --source-folder "$src_folder" \
    --build-folder "$build_folder" \
    || exit 1

echo "> conan test"
cnonan test test_package bitmask_enum/0.0.1@ \
    || exit 1
```

My configuration is:

```
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]
```

I've read through issues #7568 and #479 but neither seems relevant to my case.
The only post I found on [stackoveflow](https://stackoverflow.com/questions/71285659/why-conan-shows-me-error-specify-the-user-and-the-channel-or-neither-of-th) recommends upgrading conan: upgrading it did not solve my issue.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-03-28 23:23
Hi @pdigiglio 

I am not sure what you are doing, but I just re-tried, just in case, and it seems to work correctly. For example:

```bash
$ conan new hello/0.1 -m=cmake_lib
$ conan install .
$ conan export-pkg . myuser/mychannel  # you can append other arguments
```

Can you please post the exact commands that you are trying? Just in case, Python argparse requires sometimes the positional arguments to go first, before the ``--optional-args``.

**Comment by pdigiglio** [comment] 2022-03-29 10:55
Hi @memsharded,


> I am not sure what you are doing,

I was trying to develop my conan package as explained [here](https://docs.conan.io/en/latest/developing_packages/package_dev_flow.html).

My first attempt was:

```sh
$ ls . 
... conanfile.py ...

$ conan create .
ERROR: Specify the 'user' and the 'channel' or neither of them
```

I also tried:

```sh
$ conan create . demo/testing
ERROR: Specify the 'user' and the 'channel' or neither of them

$ conan create . bitmask_enum/0.0.1@demo/testing
ERROR: Specify the 'user' and the 'channel' or neither of them

$ conan create . bitmask_enum/0.0.1@/
ERROR: Specify the 'user' and the 'channel' or neither of them
```

Then I broke it down into the single steps as recommended in the help page.


> Can you please post the exact commands that you are trying?

The commands I try are the ones I posted above. In MinTTY, I can run them as a script; in PowerShell, I run them manually. I could never get to executing `conan test` as `conan export-pkg` always fails.

I tried changing that line into:

 * `conan export-pkg . --source-folder "$src_folder" --build-folder "$build_folder"`
 * `conan export-pkg . bitmask_enum/0.0.1@demo/testing --source-folder "$src_folder" --build-folder "$build_folder"`
 * `conan export-pkg . bitmask_enum/0.0.1@/ --source-folder "$src_folder" --build-folder "$build_folder"`
 * `conan export-pkg . bitmask_enum/0.0.1@ --source-folder "$src_folder" --build-folder "$build_folder"`

I even tried to set `user` and `channel` at the beginning of my conanfile.py, which I post here:

```python
from conans import ConanFile, CMake


class BitmaskEnumConan(ConanFile):
    #user = "demo"
    #channel = "testing"
    name = "bitmask_enum"
    version = "0.0.1"
    license = ""
    author = "Paolo Di Giglio"
    url = "https://bitbucket.org/p-dg/bitmask_enum"
    description = "Header-only library to provide bitwise enum operators"
    topics = ("conan", "bitmask", "flag", "enum", "header-only", "cplusplus")
    settings = "os", "compiler", "arch", "build_type"
    exports_sources = "CMakeLists.txt", "bitmask_enum.h", "main.cpp", "support_macros.h.in"
    no_copy_source = True

    def build(self):
        # This is not building the library, just performing the tests.
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
        cmake.test()

    def package(self):
        self.copy("bitmask_enum.h", dst="include", src=self.install_folder)
        self.copy("support_macros.h", dst="include", src=f"{self.build_folder}/GeneratedFiles")

    def package_info(self):
        self.info.header_only()
```


> Just in case, Python argparse requires sometimes the positional arguments to go first, before the --optional-args.

I'm not really sure what this means. It may be useful to know the version of python I'm using:

```sh

$ python.exe --version
Python 3.9.11

$ which python.exe
/mingw64/bin/python.exe
```

Please let me know if you need more information about my python environment.

Thanks for your time.

**Comment by memsharded** [comment] 2022-03-29 11:17
Weird, so if we can do:

```
$ ls . 
... conanfile.py ...

$ conan create .
ERROR: Specify the 'user' and the 'channel' or neither of them
```
Then, there could be some hidden bug there. Can you please start reducing the recipe ``conanfile.py`` while keeping the error happening? Then share the exact ``conanfile.py`` you are using. Then maybe you have some env-var defined? CONAN_USER, CONAN_CHANNEL or something similar?

**Comment by pdigiglio** [comment] 2022-03-30 07:03
> Can you please start reducing the recipe conanfile.py while keeping the error happening? Then share the exact conanfile.py you are using

I've reduced the conanfile.py up to its bare minimum: 

```python
from conans import ConanFile, CMake


class BitmaskEnumConan(ConanFile):
    name = "bitmask_enum"
    version = "0.0.1"
```

The error keeps happening.

If I specify the package name and version on the command line as an argument to `conan export-pkg`, I can reproduce the error even with this:

```python
from conans import ConanFile, CMake


class BitmaskEnumConan(ConanFile):
    pass
```

It's probably worth mentioning I'm no longer able to run conan packages I wrote (and successfully run) in the past for other projects. So this error doesn't seem to be related to the specific content of the conanfile.py.

> Then maybe you have some env-var defined? CONAN_USER, CONAN_CHANNEL or something similar?

It looks like they're not set:

```sh
$ echo $CONAN_USER

$ echo $CONAN_CHANNEL

$ [[ -v CONAN_USER ]] && echo "set" || echo "not set"
not set
$ [[ -v CONAN_CHANNEL ]] && echo "set" || echo "not set"
not set
```

I also tried setting the above variables before calling my test script:

```sh
$ CONAN_USER="demo" CONAN_CHANNEL="testing" sh conan_test.sh
```

Still, `conan export-pkg` fails with the same error message.

Is there any other relevant environment variable I should check?

**Comment by memsharded** [comment] 2022-03-30 09:58
This is really weird, no idea what could be happening. Some checks that could help:

- I guess it will not happen on another fresh machine? Or does it happen in other computers too?
- Have you tried to wipe your cache? You can try removing the ``<username>/.conan`` folder, and repeat. Maybe something is corrupted in the cache or in the cache configuration (if you plan to do this, it would be good to do a backup of the .conan folder, for later inspection if needed)
- Instead of wiping your cache, you can also try to temporarily define a new one with ``CONAN_USER_HOME`` env-var pointing to another location.
- Any idea of any recent incident with the Conan cache that you recall? do you manipulate directly the files in teh cache? Is the cache shared with other processes, users?

**Comment by pdigiglio** [comment] 2022-03-30 16:25
> Have you tried to wipe your cache? You can try removing the `<username>/.conan` folder, and repeat. Maybe something is corrupted in the cache or in the cache configuration (if you plan to do this, it would be good to do a backup of the `.conan` folder, for later inspection if needed)

That was the solution, thanks a lot. I would have never thought about this myself. After renaming my cache folder, I ran `conan create .` and everything works.

By comparing the newly created `<username>/.conan` with the old one, I realized the problem is setting `storage.path` in `conan.conf`. I had changed it since I was exhausting my `C:\` drive:

```cfg
# File: <username>/.conan/conan.conf

# ...

[storage]
# (default) Relative path to a folder in C:\
#path = ./data

# Absolute path to a folder in D:\
path = D:\conan_packages
```

If I restore `path = ./data`, both `conan create` and `conan export-pkg` work as expected. 

The issue seems to be due to specifying a `storage.path` that's a top-level folder of drive `D:\`. I tried all of these:

```cfg
[storage]
## This fails
#path = D:\conan_packages

## This fails
#path = D:/conan_packages

## This fails
#path = D:\\conan_packages

# This works
path = D:\test\conan
```

This is kind of weird to me as I've been able to create my own packages in `D:\conan_packages` in the past.

If you consider this to be a bug that's worth investigating, I can provide more information. As far as I'm concerned, I can carry on with changing my `storage.path` to a non top-level folder of `D:\`.

Thanks a lot for your help.

**Comment by memsharded** [comment] 2022-03-30 16:35
Thanks @pdigiglio for following up. Happy to know that you found the root cause, and it is possible to fix it.

I think it is probably not worth investigating at this point, as we are already in 2.0-alpha.6, we will move to beta very soon, and the cache in 2.0 is completely new, the configuration is also new, so this shouldn't happen anymore there. 

So if you are fine with it, lets close this issue. Don't hesitate to re-open or create a new one if you have any further issue. Thanks!

**Closed as completed by memsharded** 2022-03-30 16:35 UTC
Labels: stage: triaging

**Comment by pustekuchen91** [comment] 2022-04-21 07:08
Today i've got the same Problem: `Specify the 'user' and the 'channel' or neither of them`

Wipe the conan data folder fixed the problem.

**Comment by wooleyra** [comment] 2022-05-17 16:59
Ran into this bug as well. We use "C:\conan" for storing packages in order to keep the path short and consistent among all machines. The workaround seems to work but means we would need to change our storage path on all machines in order to run the latest Conan (including build machines). 

It would be nice to see a fix for this before 2.0, especially since it is something that broke recently.

**Comment by UtkarshVerma37051** [comment] 2022-07-20 09:01
Well I was also facing the same error (ERROR: Specify the 'user' and the 'channel' or neither of them) when I was trying to run **conan search** , **conan create .** etc.

At first look, this error seems to be redundant w.r.t. these commands (after specifying user and channel) but after looking into my conan cache I found out the exact reason . In my conan cache I had a folder representing the channel of a package whose user was null.

In the attached picture it can be seen that there is a channel name **cmake** inside the user **_** (which ideally means null) and it seems conan doesn't support that case (atleast this can be concluded by the error message provided) .

Removing the cmake folder and create a seperate user for that (or deleting it ) or renaming the other two **_** to some other name would solve the issue.


![image](https://user-images.githubusercontent.com/72651896/179941763-5502d2ed-02cf-4ae6-858f-26ab92e0a715.png)

**Comment by memsharded** [comment] 2022-07-20 09:47
Thanks for the feedback @UtkarshVerma37051. 
Just a couple of notes:
- Conan 2.0 actually allows to define only the user, but not the channel
- Conan 2.0 will not have this issue, as the cache will have a different layout.
- Please be aware that renaming user/channel is not a good practice anymore. Conan 2.0 has removed the ``conan copy`` command that allowed this, and trying to manually rename packages renaming folders will not be possible either.
