### ISSUE TITLE
[bug] intelliSense cannot find `conans` module with Conan installed by Windows Installer.

### ISSUE THREAD

**Issue by hwhsu1231** [conan-io/conan#11332] opened 2022-05-26 03:39 UTC
### Environment Details

  * Operating System+version: **Windows 11**
  * VSCode version: **VSCode 1.67.2**
  * Conan version: **Conan 1.48.1** (by Windows Installer)
  * Python version: **Python 3.9.2**

### Problem Description

For those who don't want to use `pip` to install Conan on Windows, the alternative way is to download the [binaries installer](https://github.com/conan-io/conan/releases/tag/1.48.1). Or we can use Package Manager [`winget`](https://winget.run/pkg/JFrog/Conan) or [`choco`](https://community.chocolatey.org/packages/conan) to install Conan. 

However, I noticed that if we use one of the above-mentioned methods to install Conan, intelliSense of VSCode **CANNOT** find `conans` module in the recipe `conanfile.py`. Although `conan.exe` can **SUCCESSFULLY** work with `conanfile.py`, the message of intelliSense is quite **ANNOYING**.

### Suggestion

How about do the following things:

1. Pacakge `python.exe` or `python3.exe` into Installer.
2. Pacakge the directory of `conans` module into Installer.
3. Append the directory of `conans` module into `PYTHONPATH` env.

So that our `python.exe` can find `conans` module through `PYTHONPATH` env.

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/170410991-97174b0d-08ff-4c83-825f-509f6590329b.png)

**Comment by hwhsu1231** [comment] 2022-05-26 03:49
It seems to work after I do the **"Suggestion"** Steps.

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/170412084-90d3b679-7d5d-42bc-bf64-d7d26927a69d.png)
![image](https://user-images.githubusercontent.com/71438617/170411935-e077806b-1f8d-4a9b-83a9-ab8c4ed1c181.png)
![image](https://user-images.githubusercontent.com/71438617/170411783-b0709d18-39bd-4780-b42f-b0382ec06a9a.png)

**Comment by memsharded** [comment] 2022-05-26 08:03
Hi @hwhsu1231 

This is a side effect of creating a self contained executable, that the ``conans`` source code is not that available.

The proposed changes could have potential side effects, once you introduce the extra source copy, the one not processed and bundled by the ``pyinstaller`` and put it in the PYTHONPATH, the bundled interpreter, that does not work exactly as the standard one, as it is stripped, and it also does some extra management of some env-vars, could get confused. That is, the bundled app will have 2 interpreters and 2 copies of the code, that might have subtle differences, and it would be a nightmare to debug and know which one. Other side effects would be users getting an extra python interpreter around (which they probably don't want, and that is one of the major reasons to use the binary installer). I think this could be very problematic and not worth the risk for the value.

**Comment by hwhsu1231** [comment] 2022-05-26 09:43
Excuse me @memsharded 

So, are you saying that there is no proper solution about this situation? For now? Forever?

**Comment by hwhsu1231** [comment] 2022-05-26 09:56
How about developing a **"vscode-plugin"**, which will do intelliSense of **`conans`** module for **`conanfile.py`** no matter whether there exists **`conans`** module in the search path?

**Comment by jcar87** [comment] 2022-05-26 11:09
Hi @hwhsu1231, thanks for reporting this and for using the conan windows binary installer.

There are 3 different factors at play here:
1. How to install conan to consume it as an executable (the `conan` command)
2. How to install conan to consume the python modules (being able to do `import conans`)
3. How Visual Studio Code is configured for IntelliSense to work with Python


The Windows binary installer as provided [here](https://github.com/conan-io/conan/releases/tag/1.48.1) is generated with [PyInstaller ](https://pyinstaller.org/en/stable/operating-mode.html) and generates a standalone bundle (with the conan python code) such that `conan.exe` can be executed independently from other python distributions. So the goal of the installer is to satisfy case 1 above where the `conan` command is available and executable, but does _not_ cover the use case of bundling libraries that can be imported or inspected as text (case 2 above), since `conan.exe` is mostly self-contained.

For IntelliSense inside Visual Studio code, VSCode needs to locate an interpreter (docs [here](https://code.visualstudio.com/docs/languages/python#_environments)), and it searches for an interpreter in pre-defined locations as specified [here ](https://code.visualstudio.com/docs/python/environments#_where-the-extension-looks-for-environments) - it also allows specifying custom locations and can be overridden per workspace.

I believe the reason your workaround is working is because VSCode is finding a _different_ interpreter elsewhere in the system, but finding the `conans` folder via the `PYTHONPATH` environment variable. I would be cautious about this since that environment variable defined at the system level will be picked up by all invocations of _any_ python interpreter and may conflict with the dependency resolution of those interpreters and their environments. On top of this, the `conans` folder is not sufficient: this may be okay for intellisense to resolve the `conans.ConanFile` class, but conan itself has imports from modules provided by other packages, and thus the IntelliSense experience may be "incomplete" in this regard.

You are reporting that you are using Python version 3.9.2 - however, the python version built into the binaries provided by the conan windows installer is 3.6.

If you want to avoid having conan installed globally via pip, my advice would be to:
* using an existing interpreter (e.g. 3.9.2) - create a virtual environment in an arbitrary location and install conan into it
* if you want to be able to invoke `conan` globally, add the `bin` folder inside this virtual environment to the `PATH` environment variable (this is what the binary installer does) 
* if you want VSCode to be able to resolve intellisense, select the python interpreter inside this virtual environment as the active interpreter


the latter two steps will guarantee that the conan executable matches the same version of conan that IntelliSense is finding, with the same interpreter.

**Comment by memsharded** [comment] 2024-07-19 08:03
Closing this as not a bug, this is expected for the self-contained executables, the solution has been pointed by @jcar87, using a python virtual environment.

**Closed as completed by memsharded** 2024-07-19 08:03 UTC
Labels: stage: triaging
