### ISSUE TITLE
[bug] Incompatible versions ranges overriden

### ISSUE THREAD

**Issue by at185190** [conan-io/conan#8504] opened 2021-02-15 09:34 UTC
Playing around with versions ranges, seeing it if was possibly to remove endless yellow warning of versions being overridden.
I thought to my self surely if A requires B and C and B requires C if A requires static version of  C and B requires range of C they would use the same in the end and warnings would be gone. 

But alas that is not the case, parent just straight up takes precedence over anything, there might as well not be  B requiring C as no consideration is given there. 

Not only warnings are still there, its very likely versions between two won't match and one will override the other, which in most case is fine as B has a range requirement for C, but it would be nice if it just used same version that A decided to use instead of being straight overridden with a warning.

The problem arises from this thought 

WARN: B/2.1.0@xxx/stable: requirement C/[>2.1.0 <2.1.3]@xx/stable overridden by A/2.1.0@xx/stable to C/2.1.4@ncraero/stable

As you can see B accepts C versions 2.1.0 to 2.1.2, yet A requires 2.1.4, and B range is completely ignored. Package was created and no error was generated.

Am I doing something wrong here?

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: N/A
  * Conan version: 1.32
  * Python version:3.85

### Steps to reproduce (Include if Applicable)

Create tree projects, A requires B and C , B requires C.
A requires static version of C that is higher than range allowed by B.

I just tested this with B requiring higher major version of C than A and still package was created with just simple warning of version override.

**Comment by at185190** [comment] 2021-02-19 10:45
Bump, isnt this quite a major bug?

**Comment by memsharded** [comment] 2021-02-22 09:52
Hi @at185190 

This doesn't seem a bug, but it is this way by design. Version ranges resolution in Conan is not doing a full compatible range evaluation, it is a greedy algorithm in which the consumers (we call it root of the graph) always has precedence. If the consumer says a given version is going to be used, that version will be propagated and overwritten in the whole graph upstream. Some validation might be done if the downstream consumer also declares a version range, but still the version that is computed downstream will be the one used.

There are reasons for this design, historical reasons. For example, version overriding is possible with fixed versions. You can have B declare C/1.0, but if A declares C/2.0 it will be overwritten and C/2.0 will be used everywhere. It is the only way to resolve a version conflict. So if this is possible with a "fixed" version, which conceptually is a version range that constraint to exactly one version, why would the behavior be different for a version range and why it should raise even if the overriden requirement is outside of the range. This is one of the design criteria of Conan, the user (or root consumer) can always define, configure, control and override as much as possible in the graph and dependencies.  But it is also a computational cost issue, as recipes need to be evaluated to expand the graph, every range mismatch would require backtracking, and this will make times explode very easily. We might try to improve the UX in Conan 2.0 (like more validations), this needs to be discussed, but at the moment I would say this is not a bug, it is this way by design.

**Comment by at185190** [comment] 2021-02-22 15:22
It's tad weird to know that component management system doesn't really bother with dependency version incompatibilities.
On another note I just encountered another obscure behaviour:

ERROR: xxx.log/2.1.0.1@yy/yy: Incompatible requirements obtained in different evaluations of 'requirements'
    Previous requirements: [xxx.headers/3.0.0.1@yy/yy, xx.foundation/3.0.0.1@yy/yy, xx.configuration/2.1.0.1@yy/yy]
    New requirements: [xx.headers/3.0.0.1@yy/yy, xx.foundation/3.0.0.1@yy/yy, xx.configuration/2.1.0.0@yy/yy]

Previously I was able to override requirement of 1.0 with 2.0 as if nothing happened or other way around, but now I get an error because of 2.1.0.0 is overwriting 2.1.0.1, also shouldn't higher version always override?

**Comment by memsharded** [comment] 2021-02-22 15:54
It was ultimately the users that wanted to have control, and be able to force dependencies versions overrides upstream, mainly because many times semver is not used in C++ packages, and it is necessary to override whatever is found upstream, irrespective of any range that could be defined, because sometimes it is not possible to define such range. Projects like ``openssl`` that doesn't follow semver, or many other projects that doesn't do releases at all, makes version range applicability limited. And being able to override something like ``openssl`` version upstream was a must for many Conan users since the early beginnings, so this was the behavior that was implemented.

>  also shouldn't higher version always override?

No, again, there is not any kind of evaluation of version, which is higher or which is lower. It is the one that is defined downstream that prevails, it can be higher or lower. Those conflicts happens when there are diamonds and ranges do not agree on the final version, again the solution should be do define which ``xx.configuration`` version you want in your root consumer.

**Comment by at185190** [comment] 2021-02-22 16:21
So in this case its two downstream projects clashing, which causes this issue, would version ranges solve that?

Also I just noticed that if A has log 2.1.0.1
and it also has b 2.1.0.0 and b has log as a requirement 2.1.0.0
This will cause b binaries not be found because a has overwritten b requirements and it is now looking for b 2.1.0.0 that contains log 2.1.0.1.

Log is shared component so as such it is perfectly compatible, if version ranges were added, would that fix the issue, how does that affect package_id hash?

**Comment by solvingj** [comment] 2021-02-22 18:12
> Log is shared component so as such it is perfectly compatible, if version ranges were added, would that fix the issue, how does that affect package_id hash?

`package_id` is always calculated on the resolved value, not the declared (and potentially dynamic) value.

**Comment by solvingj** [comment] 2021-02-22 18:21
> It's tad weird to know that component management system doesn't really bother with dependency version incompatibilities.

> ERROR: xxx.log/2.1.0.1@yy/yy: Incompatible requirements obtained in different evaluations of 'requirements'

I understand where you're coming from in the first quote above, but as you can see in the second quote, Conan actually does a lot of different work in the way of handling dependency version conflicts and resolution.  That's not to say it can't/shouldn't do more in the future, but it's not a matter of lack of consideration. 

In terms of potential improvements, it seems reasonable to me that, for the original case described in this ticket, that a new Conan configuration item could be introduce which makes it possible to make such dependency range violations a fatal error.  This would be an opt-in setting for multiple reasons, but for teams who are dealing with a lot of version ranges in their tree, and a lot of conflicting overrides, this could be very valuable indeed.  

@memsharded In the meantime, or even as an alternative to a Conan configuration item, could a `hook` potentially be written to detect and print such conditions out as a warnings?  Or, maybe even a fatal error?

**Comment by memsharded** [comment] 2023-02-11 22:48
Conan 2.0 changed the way the graph is resolved, including some aspects of version-range resolution:
- The overall algorithm is still greedy not a full SAT solver (NP hard, would make dependency resolution much much slower (minutes, or hours)).
- Some partial joint compatibility is achieved in diamond structures, this has been an improvement wrt 1.X
- Unnecessary warnings have been dropped
- Better summary of version ranges is done
- Better graph information, including when there are version conflicts, has been made possible.
- Implicit overrides are an error by default, except if the explicit ``override=True`` or ``force=True`` trait is defined
- The ``package_id`` computation is still a decoupled problem, that only happens after the full graph of versions has been computed. Trying to backtrack over existence of binaries only makes the above SAT problem much worse, making it fully intractable in practice.

Closing this ticket as solved, thanks for the feedback.

**Closed as completed by memsharded** 2023-02-11 22:48 UTC
Labels: stage: triaging, component: ux
