### ISSUE TITLE
Unable to find "conan_cmake_configure" command in CMake

### ISSUE THREAD

**Issue by alLiucb** [conan-io/conan#14470] opened 2023-08-13 03:30 UTC
### What is your question?

I am using Ubuntu 20.04, Conan 1.60, and CMake 3.19.6.
In my CMake project, I am attempting to configure Conan dependencies using conan.cmake. However, when I run CMake, I encounter the following error:

-- Downloading conan.cmake from https://github.com/conan-io/cmake-conan
CMake Error at cmake/BuildExternalDeps.cmake:22 (conan_cmake_configure):
Unknown CMake command "conan_cmake_configure".
Call Stack (most recent call first):
CMakeLists.txt:39 (include)

Relevant Part of My CMake Script:
conan_cmake_configure(
REQUIRES zstd/1.5.0
zlib/1.2.11
doctest/2.4.6
pybind11/2.6.2
jsoncpp/1.9.4
nlohmann_json/3.10.2
eigen/3.3.9
# boost/1.71.0
cxxopts/2.2.1
# glew/2.1.0
# glfw/3.3.2
glm/0.9.9.8
# opencv/3.4.12
tinyply/2.3.2
qhullcpp/8.0.2@sxsong1207/stable
# cgal/5.0.3
openmesh/8.1
openvolumemesh/2.1@sxsong1207/stable
fmt/8.0.1
spdlog/1.9.2
GENERATORS cmake_find_package)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-08-13 21:44
This is a duplicate of https://github.com/conan-io/cmake-conan/issues/546, and it is about cmake-conan, not Conan itself, closing this, follow in https://github.com/conan-io/cmake-conan/issues/546

**Closed as not planned by memsharded** 2023-08-13 21:44 UTC
Labels: duplicate
