### ISSUE TITLE
[question] Conan in a production environment

### ISSUE THREAD

**Issue by cjserio** [conan-io/conan#17114] opened 2024-10-04 01:49 UTC
### What is your question?

I have actually read the docs....many times! :) I still feel like this question is Conan 101 and is too dumb to ask but:

I think my team has competing goals. We have an artifactory server where we have been uploading build artifacts and recipes to speed up build times for our developers and CI/CD. We have a custom Conan command that allows us to easily script conan to run with our cmake regardless of which of our 5 platforms we're on.

We want adding dependencies to be as easy as "edit the conanfile.py and rebuild the project" and currently it IS this easy. We use conan-center and our artifactory remote. So if the artifacts are in artifactory, we get quick fulfillment, if they're not, we get the recipe from conan-center and burn a few more CPU cycles to build it ourselves (and then upload it to the artifactory).

So far so good....but the problem is the community updates recipes......a lot. And in the last month alone we've had our pipelines break 4 times from it. This is our fault right? The system's doing what it should and we shouldn't be doing things this way!

Sounds like I should use a lockfile? The problem is they seem tedious for our use case because they're different for each dependency graph. We have 5 platforms and about 6 different build configs so they'd all have to be merged into a single lockfile each time we make a change which would require the graph to be generated on each platform. Not all of our developers have all platforms so it'd have to be in a CI/CD pipeline. Unless I've completely misunderstood things here.

What I'd really like to do is have our own fork of conan-center as a GIT repo where recipes never change unless we manually update the fork. If that's the case then we don't have to mess with lock files because every recipe would remain stable. Our team could easily add/modify recipes there as well.

I just don't see a way to do this? It seems that while conan-center-index is on GitHub, the actual "remote" is something else.

Have i misunderstood things completely?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by andrey-zherikov** [comment] 2024-10-04 11:48
Just wanna share with you what I did for us. I created a "fork" of conan-center-index on our private github enterprise server ("fork" because GHE is not able to maintain fork relationship with repo from another server).
This fork allows me to pull changes when I want and when I'm ready to upgrade packages. Moreover I cleaned it up by removing everything except the recipes that I'm interested in. 
Then I created a CI pipeline that contains a list of package/version to publish to our artifactory. This CI actually checks whether a package/version was already published so it doesn't publish the same version multiple times.

**Comment by memsharded** [comment] 2024-10-04 11:52
Hi @cjserio 

You are totally right about the two different opposing forces while using ConanCenter, and you haven't misunderstood anything:

- The desire for stability and not breaking builds
- Wanting to use the very latest versions with the most updated recipes revisions with possible recipe fixes

Indeed ``conan-center-index`` is the source for recipes, but the actual built binaries are in a Conan server (not a git repo), which is the ``https://center.conan.io`` remote that you can list with ``conan remote list``

In general, for production usage we are recommending https://docs.conan.io/2/devops/using_conancenter.html:

- use at least lockfiles to keep your builds using always fixed versions and revisions from ConanCenter
- even better, use your own server repository that host your own binaries built from you from ``conan-center-index`` repo.

In that way, the update to newest changes from upstream ``conan-center-index`` becomes a controlled thing:

- Make a branch in your fork of ``conan-center-index``, get upstream changes with a pull or merge
- Try to build package binaries for that branch, but do not put them in your main "production" repo in server, but put them in a secondary repo, like "staging"
- Now, launch a build of your products and own pipeline using the ``staging`` repo, to see if everything ok.
- If things good, then you can copy the packages from staging->production repo. If things are broken, then investigate what changed, understand new versions of dependencies that might have broken something (but with the relax, because your main builds are not broken)

Please let me know if this makes sense.

**Comment by cjserio** [comment] 2024-10-04 12:05
I think I understand the process you're describing but it makes use of lockfiles to keep things stable. As I said, we're avoiding using lockfiles because (if I understand them correctly) they're good at creating stability but they require each developer to understand how they work in order to get work done, and they're tedious to make because they require the dependency graphs of numerous platforms merged together which is not something that can be done locally. Our current Conan setup is completely transparent to our developers. All they need to know is their dependencies go in conanfile.py with a name and version and "the rest is magic" and I'd like to keep it that way for simplicity.

Instead I just want to use a forked conan-center-index as the source for recipes. One that I can take changes from at our leisure. Is there no way to accomplish this? If "conan-center" as a remote is not "the github repo" then is the path to the github repo hardcoded into conan and not something we can redirect?

**Comment by memsharded** [comment] 2024-10-04 12:18
> I think I understand the process you're describing but it makes use of lockfiles to keep things stable. As I said, we're avoiding using lockfiles because (if I understand them correctly) they're good at creating stability but they require each developer to understand how they work in order to get work done, and they're tedious to make because they require the dependency graphs of numerous platforms merged together which is not something that can be done locally. Our current Conan setup is completely transparent to our developers. All they need to know is their dependencies go in conanfile.py with a name and version and "the rest is magic" and I'd like to keep it that way for simplicity.

For that goal, having them resolve against your own controlled server that contains a copy of the dependencies you want, would be the best approach.

> Instead I just want to use a forked conan-center-index as the source for recipes. One that I can take changes from at our leisure. Is there no way to accomplish this? If "conan-center" as a remote is not "the github repo" then is the path to the github repo hardcoded into conan and not something we can redirect?

Not sure what you mean. Of course this is possible and recommended, as described in the docs: https://docs.conan.io/2/devops/conancenter/hosting_binaries.html, with relatively small CI you can publish your own binaries to your own server repo, and then you have that remote configured instead of ConanCenter (for this the ``conan config install`` is recommended, so you can keep all developers and CI using the same configuration, including remotes)

**Comment by andrey-zherikov** [comment] 2024-10-04 12:37
We have almost exactly what @memsharded is saying: our own conan config repo with our own artifactory remote. This is a workspace for developers. As a separate workflow, we have fork of conan-center-index that is not listed as remote in our config repo and it's used only in CI that publishes new packages to our artifactory.

**Comment by memsharded** [comment] 2024-10-04 12:41
Great, thanks for your feedback @andrey-zherikov !

**Comment by cjserio** [comment] 2024-10-04 12:47
I must be missing something fundamental or I'm making a false assumption somewhere so let me try a simple example:

Consider a completely stock install of Conan with no remotes other than the default "conan-center":
If I run `conan install --requires=zlib/1.2.13` my assumption/understanding is that the recipe to build zlib will come from the conan-center-index, correct?

What I'm asking is what needs to change about that Conan instance in order for it to get the recipe from a fork of conan-center-index instead? I understand that I can populate an artifactory server with recipes by doing a bunch of "conan export" and "conan upload" calls over a list of dependencies. The problem with that is if a developer needs to use libpng for example, they can't do it locally. They'd need to get the recipe manually and push it to the server or trigger CI to do it.

So is there a way to have our own conan-center-index that contains ALL of the recipes, but forked so that they don't change?

**Comment by memsharded** [comment] 2024-10-04 12:52
> Consider a completely stock install of Conan with no remotes other than the default "conan-center":
If I run conan install --requires=zlib/1.2.13 my assumption/understanding is that the recipe to build zlib will come from the conan-center-index, correct?

No, it comes from ConanCenter, a Conan-server remote that contains both recipes and binaries. The recipe that is downloaded comes from ``conan-center-index``, it was ``conan create`` + ``conan upload`` to ConanCenter server to get it there, this happens in ``conan-center-index`` CI for contributors PRs.


If you are looking for a way that developers can work with a fork of ``conan-center-index``, then it is not necessary to upload anything, developers can do a local ``conan export`` or ``conan create`` and put that in their local cache, so making it available. Furthermore they have the https://docs.conan.io/2/devops/devops_local_recipes_index.html "local-recipes-index" which can streamline this flow too, avoiding the ``conan export``, just use them as regular requires.


> So is there a way to have our own conan-center-index that contains ALL of the recipes, but forked so that they don't change?

That is the recommended way, a fork of ``conan-center-index``, and you create the packages from your fork, not from ``conan-center-index``. I think I might be missing something too 🙂

**Comment by cjserio** [comment] 2024-10-04 13:00
Ok I think you've found my false assumption. I thought Conan was accessing conan-center-index directly. And that's why I've been struggling to try and find a way to use the fork DIRECTLY. In my head that's the holy grail because it already HAS all of the recipes and doesn't require them to be pushed there manually or by CI process.

Instead it seems like conan-center-index is just raw materials (recipe SOURCE) that go into the creation of a populated conan server.

**Comment by memsharded** [comment] 2024-10-04 13:58
> Ok I think you've found my false assumption. I thought Conan was accessing conan-center-index directly. And that's why I've been struggling to try and find a way to use the fork DIRECTLY. In my head that's the holy grail because it already HAS all of the recipes and doesn't require them to be pushed there manually or by CI process.


That is the ``local-recipes-index`` feature, you can use it directly from the repo. But this has limitations, of course, like not being able to use binaries, or not being able to go back in time (full reproducibility), using previous ``recipe-revisions`` for the different packages. Plus it only works well for third-party packages, for your own code, having the ``conanfile.py`` together in the source repo is the recommended approach. And the actual package servers, which is the recommended approach, is the thing that decouples the origin (it is basically the same a third-party package that your own private package created from your own source code) from the consumers of the packages.


> Instead it seems like conan-center-index is just raw materials (recipe SOURCE) that go into the creation of a populated conan server.

It is basically the same as other central servers like PyPI, MavenCentral, or NPM, they contain the packages, but the source code that created those packages is not directly connected to it, things resolve directly against the server packages and only the server packages.

**Comment by cjserio** [comment] 2024-10-04 14:16
> That is the local-recipes-index feature, you can use it directly from the repo.

Almost! The disadvantage there is the "local" part of it. I was hoping there was an equivalent of "remote-recipe-index".

In any case, I think with my flawed logic corrected, I can look all of this over with a fresh set of eyes and try and solve our issues. Thanks!

**Comment by sykhro** [comment] 2024-10-04 16:28
> Our current Conan setup is completely transparent to our developers. All they need to know is their dependencies go in conanfile.py with a name and version and "the rest is magic" and I'd like to keep it that way for simplicity.

Out of curiosity, how well is this working out? Do you ever get someone needing to add a dependency that doesn't exist in conan-center? Debugging (and maybe patching) package sources? Needing to add support for a new platform? I find that's impossible to do these when having 0 knowledge of the system

**Comment by memsharded** [comment] 2024-10-04 16:46
> Out of curiosity, how well is this working out? Do you ever get someone needing to add a dependency that doesn't exist in conan-center? Debugging (and maybe patching) package sources? Needing to add support for a new platform? I find that's impossible to do these when having 0 knowledge of the system

I can give feedback about https://docs.conan.io/2/devops/using_conancenter.html, and general user adoption and feedback. We wrote that section of the docs when we learned that users that were already doing this were way happier, and the extra effort needed to set it up was really worth it. Since we wrote those docs there have been other users that have adopted the approach, and the feedback is still very consistently positive.

Note in many cases it is not even necessary to do changes to the recipes in ConanCenter, it can be just a matter of merging the upstream, building, testing if everything is ok, and if not, also reporting to ConanCenter. Reported things like conflicts for example tend to get attention and get fixed with relatively priority, so it might be possible that a new merge in a few days becomes successful. The key is having the control about when things are updated (for that reason lockfiles are the other possibility). 

Then, building things from source from a fork has the added benefit that if at some point a customization is necessary, all the setup is already done, and it is just a matter of coding that customization. But users that almost no customize recipes do still enjoy this flow.

**Comment by cjserio** [comment] 2024-10-05 00:47
> > Our current Conan setup is completely transparent to our developers. All they need to know is their dependencies go in conanfile.py with a name and version and "the rest is magic" and I'd like to keep it that way for simplicity.
> 
> Out of curiosity, how well is this working out? Do you ever get someone needing to add a dependency that doesn't exist in conan-center? Debugging (and maybe patching) package sources? Needing to add support for a new platform? I find that's impossible to do these when having 0 knowledge of the system

We have developers of varying backgrounds. Most have no issues learning about the build system but some are more academic and development environments just get in their way. For that reason I've tried to hide as much of this as i can. When they need dependencies it's a task that's handed to other people. It's actually one of the original reasons I wanted to move us to Conan. We used to build everything by hand and needing changes in a dependency was a time consuming task that would impact schedule.

**Comment by cjserio** [comment] 2024-10-08 13:30
@memsharded Ok I've now got a script that runs around what is essentially `conan inspect` to get the requirements from my recipe. Then adds our forked conan-center-index git repo as a local-recipes-index remote called "local_remote". My plan was to iterate over the requirements and do a `conan install --requires=<each_requirement> -r=local_remote` on each. I think the -r is important here to make sure I know that the recipes are coming from my fork ONLY. Would this flow be correct so far?

This seems to work however there's one issue. We have had to modify some public recipes in our fork. So for example, some of our requirement versions are libabc/1.2.3@company. We added @company to the version as a memory aid to ourselves that we had to patch or modify libabc and that it varies from the official package. It seems like if i just do `conan install --requires=libabc/1.2.3@company -r=local_remote` it will install libabc/1.2.3 but it doesn't add the @company to the name.

What's the proper way to preserve this? Do my hacked recipes need to include the user in the conanfile? Does the `conan install` command need to manually specify the user?

**Comment by cjserio** [comment] 2024-10-11 16:03
@memsharded just hoping for some clarity on this before I go too far into the weeds again. Thanks!

**Comment by memsharded** [comment] 2024-10-11 18:23
Sorry for the delays, thanks for the ping! It really helps to re-surface things when our backlog buries them!

> My plan was to iterate over the requirements and do a conan install --requires=<each_requirement> -r=local_remote on each. I think the -r is important here to make sure I know that the recipes are coming from my fork ONLY. Would this flow be correct so far?

You can also use the ``conan remote --allowed-packages`` feature as an extra guarantee to define which packages can come from which remotes. It requires knowing those packages in advance, but it might help in some situations to avoid some issues.

You might also need the ``--build=missing`` to build things from source when necessary, but the overall idea is correct, iterate the packages you want from ConanCenter, ``conan install --build=missing`` them, then upload them.

But in general the ``-r=local_remote`` might not be the optimal thing. If you already had those packages built and uploaded to your binary server, defining just the local remote will not check if those binaries already exist, then the ``--build=missing`` will re-build them from source, instead of skipping that (which happens if the operation is done and there are no changes in that package since the last time the package was built)

> This seems to work however there's one issue. We have had to modify some public recipes in our fork. So for example, some of our requirement versions are libabc/1.2.3@company. We added https://github.com/Company to the version as a memory aid to ourselves that we had to patch or modify libabc and that it varies from the official package. It seems like if i just do conan install --requires=libabc/1.2.3@company -r=local_remote it will install libabc/1.2.3 but it doesn't add the https://github.com/Company to the name.

The recommendation for all packages built from the fork is to keep them without the ``@user``, and keep them with the original ``pkg/name`` naming. This way, it is not necessary to change ``requires()`` of other packages in ``conan-center-index`` to that package.

Knowing what diverges from the upstream would be more of a source problem, that is, doing a ``git diff`` can easily get what changes are done between your fork and  the upstream. Furthermore, doing summaries with ``--stat`` is easy, and also writing a small script that does the ``diff`` and collect (by folder name) the changes is also very easy.

So our recommendation would be the one in our docs, do not add any ``@company`` user name to packages build from ConanCenter (from a ``conan-center-index`` fork).

The ``@company`` might be ok for your own packages built from your own sources, where you typically put the conanfile.py together in the same repo as the source code, and not with a conan-center-index repo layout.

**Comment by cjserio** [comment] 2024-10-12 13:08
Thanks for the help! I think I've got this sorted now and have automation to run. Whenever someone touches our product's recipe it'll automatically pull from our git repo, cache the recipe, build it then upload everything to our artifactory.

**Comment by memsharded** [comment] 2024-10-16 22:09
Sounds great. 
I am closing then this ticket as solved now, don't hesitate to re-open or create new tickets for any further question or issue.

Thanks very much for your feedback!

**Closed as completed by memsharded** 2024-10-16 22:09 UTC
