### ISSUE TITLE
[maintenance] ERROR: Exceeded 30 redirects.. [Remote: conan-center]

### ISSUE THREAD

**Issue by solvingj** [conan-io/conan#8850] opened 2021-04-22 14:38 UTC
Scheduled maintenance is currently in progress. We will provide updates as necessary.
Apr 22, 14:00 UTC - 18:00 UTC
Scheduled - Detail: The DNS record http://conan.bintray.com will be routed to the new ConanCenter repository.
Impact: Temporary instability, none lasting.

If you receive this error, it is related to this maintenance:

```
ERROR: Exceeded 30 redirects.. [Remote: conan-center]
```

Please do not open another Github issue.  We will close this issue when the issues from the maintenance are thought to be resolved.  If this issue is closed, and you are still receiving this error, please do open a new issue.

**Comment by azias** [comment] 2021-04-22 15:26
same for me

**Comment by pgeler** [comment] 2021-04-22 15:54
same but then turned to ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by m-hilgendorf** [comment] 2021-04-22 15:56
Is there a mirror of conan center available so we can workaround during the outage?

**Comment by blackliner** [comment] 2021-04-22 16:01
![image](https://user-images.githubusercontent.com/23190927/115746644-c75a4000-a394-11eb-950c-55de9273dc40.png)

**Comment by Vhab** [comment] 2021-04-22 16:27
> Scheduled maintenance is currently in progress. We will provide updates as necessary.
> Apr 22, 14:00 UTC - 18:00 UTC
> Scheduled - Detail: The DNS record http://conan.bintray.com will be routed to the new ConanCenter repository.
> Impact: Temporary instability, none lasting.

Where was this announced?
There's nothing on https://status.bintray.com/ https://conan.io/center/ or https://blog.conan.io/

It's quite inconvenient to find out about this after the maintenance has started.

**Comment by memsharded** [comment] 2021-04-22 16:41
https://status.conan.io/

**Comment by Vhab** [comment] 2021-04-22 16:44
> https://status.conan.io/

Thank you. I guess this may have had an ahead of time announcement?
Is there a reason this wasn't announced on the blog along with the other notable dates in: https://blog.conan.io/2021/03/31/Bintray-sunset-timeline.html ?

**Comment by memsharded** [comment] 2021-04-22 16:48
Yes, this was clearly a mistake on our side. The blog post should have added this. I sincerely apologize for this.

**Comment by MBraedley** [comment] 2021-04-22 16:49
> It's quite inconvenient to find out about this after the maintenance has started.

"Inconvenient" is a nice way of putting it.  As far as I'm concerned, this is downright unacceptable.  If your maintenance plans allow for disruptions to business users that last more than 5-15 minutes, you need better maintenance plans.  Please consider performing this kind of maintenance on the weekend in the future in order to limit disruptions.

**Comment by memsharded** [comment] 2021-04-22 17:06
We are reverting and closing this maintenance asap.

**Comment by memsharded** [comment] 2021-04-22 17:15
Things should be back to normal now (minus some DNS propagation delay issues)

**Comment by solvingj** [comment] 2021-04-22 17:50
Closing issue as explained, because it is believed that all issues should be resolved at this time.

**Closed as completed** 2021-04-22 17:50 UTC

**Comment by solvingj** [comment] 2021-04-24 12:06
For future reference, to be notified of scheduled maintenances in-advance,  users can subscribe to notifications here:
https://status.conan.io/

For the Bintray-related maintenance, users can also check this blog post:
https://blog.conan.io/2021/03/31/Bintray-sunset-timeline.html
