### ISSUE TITLE
[bug] Public compiler flags on CMake targets do not properly get propagated to the consumer of a package.

### ISSUE THREAD

**Issue by tjwrona** [conan-io/conan#7479] opened 2020-08-02 21:44 UTC
I am trying to package a library I created with Conan. The library requires C++17 so when creating the CMake target for the library the following is used:

`target_compile_features(dsp PUBLIC cxx_std_17)`

Since this compile feature is `PUBLIC` it will automatically be propagated to the user when the CMake target is consumed. However this doesn't seem to work when I use Conan. When I try to link to the library using `CONAN_PKG::cpp-dsp` the compiler flag that enables C++17 is lost and the compilation fails.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Microsoft Visual Studio Community 2019 Preview Version 16.7.0 Preview 6.0
  * Conan version: 1.27.1
  * Python version: 3.7.1

### Steps to reproduce (Include if Applicable)
Clone and attempt to run `conan-create` on the following project: https://github.com/tnt-coders/cpp-dsp

### Logs (Executed commands with output) (Include/Attach if Applicable)

This is the error produced by the section of `conan-create` that tries to build and run the "test_package":

```
cpp-dsp/0.0.0 (test package): Calling build()
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The CXX compiler identification is MSVC 19.27.29109.0
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.27.29109/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Preview/VC/Tools/MSVC/14.27.29109/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: called by CMake conan helper
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Library dsp found C:/Users/tjwro/.conan/data/cpp-dsp/0.0.0/_/_/package/f6174d7b6d1e15add78f56718c9429d1e4d66e2a/lib/dsp.lib
-- Library gmock_main found C:/Users/tjwro/.conan/data/gtest/1.8.1/bincrafters/stable/package/5ad274d83035c78ba2b205e6cf4f1b317aee8e05/lib/gmock_main.lib
-- Library gmock found C:/Users/tjwro/.conan/data/gtest/1.8.1/bincrafters/stable/package/5ad274d83035c78ba2b205e6cf4f1b317aee8e05/lib/gmock.lib
-- Library gtest found C:/Users/tjwro/.conan/data/gtest/1.8.1/bincrafters/stable/package/5ad274d83035c78ba2b205e6cf4f1b317aee8e05/lib/gtest.lib
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


-- Build files have been written to: C:/Users/tjwro/Documents/GitHub/cpp-dsp/test_package/build/ecbfb49a4e2ea8618319be5f9e02c8e0621391fb
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/tjwro/Documents/GitHub/cpp-dsp/test_package/CMakeLists.txt
  main.cpp
C:\Users\tjwro\.conan\data\cpp-dsp\0.0.0\_\_\package\f6174d7b6d1e15add78f56718c9429d1e4d66e2a\include\tnt/dsp/analysis.hpp(7,1): error C2429: language feature 'nested-namespace-definition' requires compiler flag '/std:c++17' [C:\Users\tjwro\Documents\GitHub\cpp-dsp\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb\dsp_package_test.vcxproj]
ERROR: cpp-dsp/0.0.0 (test package): Error in build() method, line 14
        cmake.build()
        ConanException: Error 1 while executing cmake --build C:\Users\tjwro\Documents\GitHub\cpp-dsp\test_package\build\ecbfb49a4e2ea8618319be5f9e02c8e0621391fb --config Release -- /m:8 /verbosity:minimal
```

**Comment by memsharded** [comment] 2020-08-03 12:31
Hi @tjwrona1992 

This is expected, as Conan is not a build system, but a package manager. Conan isolates each package from the other packages build systems, and it is possible, and actually very common to have dependency graphs in which packages uses different build systems.

The fact that your package ``CMakeLists.txt`` is declaring ``target_compile_features(dsp PUBLIC cxx_std_17)``, doesn't mean that this gets automatically propagated to consumers. Specially, because those consumers might not be using CMake at all. Whatever is done by the build system is private and isolated in that package. When a package is retrieved and installed as precompiled binary (the default behavior in Conan), the CMakeLists.txt with that definition does not even exists, and is not called.

On the consumer side, Conan can generate CMake information, or MSBuild information, or Autotools information, as specified by the user. The information that is generated in the consumer side is gathered from the packages ``package_info()`` method: 

- https://docs.conan.io/en/latest/creating_packages/package_information.html
- https://docs.conan.io/en/latest/reference/conanfile/methods.html#method-package-info

So it would be possible to add such a definition like:

```python
def package_info(self):
    self.cpp_info.cxxflags = ["-std=c++17"]
```

Note, however, that this might not be a nice imposition on the consumer, that could want to use c++20 and things should probably work too, and now it is being injected a c++17 flag that could conflict, be ignored...

There are some open issues like https://github.com/conan-io/conan/issues/6157 to discuss better modeling of the ``cppstd``, and having the possibility of ``info`` defining a "min cppstd" requirement would be a nice thing. I am labeling this as a feature request (not a bug, Conan is not supposed to propagate this automatically)

**Comment by tjwrona** [comment] 2020-08-03 19:33
Hi @memsharded,

That makes sense. Looking at the CMake documentation it looks like using `target_compile_options` with a specified language standard does in fact still allow users to use a higher level of the standard (such as C++20) if they so choose and it won't result in a conflict.

https://cmake.org/cmake/help/latest/manual/cmake-compile-features.7.html#requiring-language-standards

Conan really should have a way of doing the same thing so you don't need to force the user to either manually specify it themselves or lock them into a specific version:
______

I'm honestly fine with requiring any consumers of the package to use CMake since I will likely be the only one using it and plan to use CMake with all of my projects. In an attempt to solve the problem I tried using the `cmake_paths` generator and having it use `find_package` to find my library directly that way I can pull in the _REAL_ CMake target that is aware of the compiler flag but even after doing that and including `${CMAKE_BINARY_DIR}/conan_paths.cmake` the `find_package` command fails to find my library.

Using the `cmake_paths` generator and then linking to the _REAL_ CMake target should at least in theory solve this problem, right?

**Comment by memsharded** [comment] 2020-08-03 20:37
> Using the cmake_paths generator and then linking to the REAL CMake target should at least in theory solve this problem, right?

Yes, that is true. If you use the generated find_package() by CMake, it will contain that standard definition, and it will work. This would be a very nice approach and we would make it the default, if it wasn't because of these important CMake limitations:

- As commented above, this only works for the case the consumers are using CMake too. It is important for Conan to be as build-system agnostic as possible, so this approach will be broken for consumers not using CMake, and this is one of the main reasons we cannot make this the default.
- The standard find cmake scripts generated by CMake very often do not handle transitivity correctly, and this is a big problem, resulting in those scripts using libraries from the system (older versions) instead of the ones from Conan packages.
- The standard find cmake scripts cannot handle packages for different configurations in different locations, as they do not work with generator expressions, neither can find different binaries in more than 1 location. This is not a big issue if you don't want to use multi-config environments like Visual Studio.

The first one is not an issue if it is for your own packages and you control and consume them, but beware of the other two issues.

**Comment by tjwrona** [comment] 2020-08-04 17:10
Hi @memsharded ,

Regarding the 3rd bullet point you mentioned above. I converted my library to use the `cmake_paths` generator to fetch the `GTest` library using `find_package` instead of the `CONAN_PKG::gtest` package and it seems like I actually am able to change build configurations and get two different packages for `GTest` based on the configuration.

I am using a multi-config environment (Visual Studio) and if I change from a debug build to a release build it does rebuild `GTest` in release mode and links to that instead. Your comment above seems to suggest that this would not work. Is this not expected?

**Comment by memsharded** [comment] 2020-08-04 21:52
> I am using a multi-config environment (Visual Studio) and if I change from a debug build to a release build it does rebuild GTest in release mode and links to that instead. Your comment above seems to suggest that this would not work. Is this not expected?

Can you depend on a third party library, install both debug and release packages, and then switch in the Visual Studio IDE from Debug to Release and it will work without re-building and installing the dependency?

**Comment by tjwrona** [comment] 2020-08-05 00:36
@memsharded, yes as far as I can tell it is doing exactly what you describe when I use `GTest`. It seems to get two separate packages, one for "debug" builds and another for "release" builds, but once I fetch and build each one once I don't need to fetch and build them again. I have pushed an updated version of the library that works this way to https://github.com/tnt-coders/cpp-dsp/commit/b7b52e389567f80533b18e6e9d4342c31b04b493.

You are welcome to clone it and give it a try. I am using the latest Visual Studio (Visual Studio Community 2019 Preview Version 16.7.0 Preview 6.0).

Note that this project uses the [cmake-conan](https://github.com/conan-io/cmake-conan) functions so there is no need to run `conan install` up-front. You can just run CMake and then build the library as described in the README or you can open it in Visual Studio and simply use the "build" button without worrying about Conan. I think it may be the "cmake-conan" tool that is making switching configurations possible.

---

I am still having one issue with the `test_package` folder but I will dig a bit further into it and may end up asking a question later. It seems like the test executable is being put in a "Release" folder instead of a "bin" folder like the conanfile expects. (This probably has something to do with using Visual Studio as my compiler.)

**Comment by tjwrona** [comment] 2020-08-10 15:54
Hi @memsharded, let me know if you get a chance to try this out. I'm curious if it really is working correctly for a multi-config environment or if I am missing something.

**Comment by memsharded** [comment] 2023-12-22 00:46
This ticket was using the old generators (legacy in 1.X, removed in 2.0), that have been superseded some time ago by new ones. Closing as outdated, please check the new ones and don't hesitate to open new tickets as necessary for any further question.

**Closed as not planned by memsharded** 2023-12-22 00:46 UTC
Labels: priority: low, stage: queue, complex: medium, component: Build, component: graph
