### ISSUE TITLE
Differences in local and remote cause uploads to fail.

### ISSUE THREAD

**Issue by mdegel** [conan-io/conan#3473] opened 2018-09-04 09:16 UTC
**Environment:**
Conan Version: 1.7.1
CI: Jenkins
OS: Windows 10 / Ubuntu 18.04

**Issue:**
When using conan in our CI while building different variants of packages, uploading conan packages will fail.

**Example Use Case:**
- We have a project wrapping the gtest library into conan packages
- CI Builds Package Variants (Windows/Ubuntu) on different Slaves
- Since the packages are created for a stable channel, we do not allow overriding packages by using an upload command like this "conan upload 'some_package' -r some_remote --all -c --no-overwrite all"
- Ubuntu Slave uploads first, thus specifying the conan exports in artifactory without any issues
- Windows attempts to upload next, but fails with error "ERROR: Local recipe is different from the remote recipe. Forbidden overwrite. [Remote: some_remote]"

**Problem:**
- Conanfile is the same for both linux and windows
- Conanmanifest is the same for both linux and windows, except for its timestring
- The conan_sources.tgz created on windows/linux differs in its checksum
- The content in conan_sources seems to be exactly the same when looking at the internal checksums. Based on this information I would rule out issues caused by differences in line feeds.
- The only occurence for this error seems to be in https://github.com/conan-io/conan/blob/43a765a38a4d08b7cbc5d507235d7268e9321cf4/conans/client/rest/rest_client_v1.py#L227 
- Interestingly enough, replacing the conan_sources.tgz from linux in the windows build dir will allow uploading the package, however this ofc isn't the a suitable way

Judging from the source of the error occurence I'm not quite sure what could cause this error to appear in the first place. Are there any issues when uploading conan packages from multiple sources based on the same repo (overriding disabled)?

**Comment by danimtb** [comment] 2018-09-04 09:29
Hi @mdegel,

This could be related to different line endings in your conanfile. This is a known problem and we recommend to use same ending for bot Windows and Linux to avoid this kind os issues.

Have a look at this: https://docs.conan.io/en/latest/faq/using.html#packages-got-outdated-when-uploading-an-unchanged-recipe-from-a-different-machine

**Comment by memsharded** [comment] 2018-09-04 09:38
> The conan_sources.tgz created on windows/linux differs in its checksum

The cause could be a difference in the permissions, that make the ``conan_sources.tgz`` have a different checksum. This is a known issue, we introduced a mask for some bits recently, but might not be enough for all cases (docker and WSL specially), and we are investigating ways to mitigate it.

As a workaround, I would try to check if you have very different permissions on the Windows and Linux machines, check what would be the masks of the files that are being exported, and try a chmod if possible.

**Comment by mdegel** [comment] 2018-09-04 09:39
@danimtb Like I already mentioned in my post ahead, I have checked for the tgz's contents as well as for the conanfile.py and conanmanifest.txt. Considering they have the exact same checksums, except for the specified differences, different line endings don't seem to be the problem here.

**Comment by mdegel** [comment] 2018-09-04 09:42
@memsharded I'm currently binary diffing both tgz files. Some of the (rather few) differences seem to be indeed permission differences.

For further reference if anyone else is interested, these are the two problematic files.
[diff.zip](https://github.com/conan-io/conan/files/2348079/diff.zip)

**Comment by mdegel** [comment] 2018-09-04 09:49
@memsharded Since you are talking about Docker and WSL.

Some more information about the build process on my side.
- Jenkins checks out the repo and creates some dirs
- Jenkins stashes current workspace
- Jenkins unstashes workspace. Builds and uploads Linux Packages from within a docker container
- Jenkins unstashes workspace. Builds and uploads Windows Packages from a designated slave

**Comment by memsharded** [comment] 2018-09-04 09:53
> Jenkins unstashes workspace. Builds and uploads Linux Packages from within a docker container

yes, this docker could be definitely the one introducing different file permissions. We need to think about it, will try to address it for 1.8

**Comment by memsharded** [comment] 2018-09-17 09:08
The changes done in https://github.com/conan-io/conan/pull/3480, that will be released in 1.8, would be a solution for this issue. The check for changes will be done based in the manifest, not in the .tgz checksum. 

It would be great if you could test it works in your cases, running from sources in the "develop" branch, prior to the release of 1.8. Many thanks!

**Closed by memsharded** 2018-09-17 09:08 UTC
Labels: look into

**Comment by mdegel** [comment] 2018-10-10 12:58
Haven't had much time in the last month, so I just got to test this now.
As of version 1.8.0 the issue seems fixed to me, since our Jenkins Jobs are now fully capable of uploading both variants (Windows/Linux) without any issues while `--no-overwrite all. is enabled`

**Comment by memsharded** [comment] 2018-10-11 07:50
Perfect, thanks @mdegel for the feedback!
