### ISSUE TITLE
[bug] build fails if build folder is only partially cleaned.

### ISSUE THREAD

**Issue by rasjani** [conan-io/conan#8012] opened 2020-11-05 11:37 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 
  * Conan version: 1.28.0 
  * Python version:  3.7 latest windows cpython

### Steps to reproduce (Include if Applicable)

This is not critical but it feels still a bit like a bug:

1. build a binary package that that uses deeply nested directory structure.
2. clean the build folder with windows rmdir from the console. Because of "windows" rmdir in our case resulted in state where build directory was cleaned only partially. Eg, directory like `/d/conan_build_root/spdlog/1.5.0/vendor/stable/build/479e5c321685f6e20cbbf93c38ae334c54ade580` still existed and it had a directory in it with few sub directories and bunch of files there still .. 
3. re-build the package again.
4. build fails with exception.

First off, our use of rmdir was easily fixed so this is definitely not a blocker but i feel like there's some logic issue somewhere within conan that doesn't trigger the cleanup  (because only the build folder with its subs exists, everything else is gone!) during the build and then fails when build directory is being created .. 

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
Traceback (most recent call last):
File "J:\j\workspace\vendor-spdlog-pipeline\spdlog\spdlog_venv\lib\site-packages\conans\client\installer.py", line 113, in _prepare_sources
shutil.copytree(source_folder, build_folder, symlinks=True)
File "C:\python3\lib\shutil.py", line 324, in copytree
os.makedirs(dst)
File "C:\python3\lib\os.py", line 221, in makedirs
mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\conan_build_root\\spdlog\\1.5.0\\vendor\\stable\\build\\479e5c321685f6e20cbbf93c38ae334c54ade580'
```

**Comment by jgsogo** [comment] 2020-11-05 12:58
This is totally unexpected failure. A couple of lines before we try to remove that ``build_folder`` and raise if something goes wrong:

https://github.com/conan-io/conan/blob/release/1.28/conans/client/installer.py#L104

I can't figure out how to pass that line without an exception and raise then with an error saying that the folder already extis 🤔

**Comment by rasjani** [comment] 2020-11-05 13:52
I'll try to give a filesytem snapshot or script that generates the issue. And yeah, i knew it was tried to be wiped but cuz many times i have shell open in the build folder and that fails. 

Now, windows shell `rmdir` does fail with error "The system cannot find the path specified." ..   Maybe this if clause happens: https://github.com/conan-io/conan/blob/release/1.28/conans/util/files.py#L25 and while rmdir indeed gets hit with the exception, it gets hidden because python most likely gets the same error (eg, ENOENT error).

**Comment by memsharded** [comment] 2024-12-30 00:30
Closing this ticket as not followed up.
Most likely not reproducible anymore in Conan2, because many things changed since then.

**Closed as completed by memsharded** 2024-12-30 00:30 UTC
Labels: stage: triaging
