### ISSUE TITLE
Removing all packages from a bintray channel fails silently

### ISSUE THREAD

**Issue by MarcoKoch** [conan-io/conan#1467] opened 2017-07-02 19:01 UTC
After I made some changes to the options accepted by a recipe, I wanted to clean the old binary packages out of my Bintray repository. I tried to do so with `conan remove <name> -r <remote> -p`.
The command runs without error, requesting whether i'm sure to delete all packages. Afterwards, the packages are still listed under the 'Files' section on Bintray, though. Listing each individual package after `-p` works as intended and deletes all packages.

**Comment by memsharded** [comment] 2017-07-02 19:34
Yes, could be a bug, not sure if client side or bintray side, we'll have a look.

In the meantime, I think you are  mostly fine running ``conan remove <name> -r=<remote>``. It will also remove the recipe, but no big issue, it will be re-uploaded next time.

Thanks for reporting!

**Comment by lasote** [comment] 2017-08-17 11:27
I've confirmed that it's not a conan client bug. Will try to identify the error in the Bintray/Artifactory backend and report.

**Comment by memsharded** [comment] 2017-12-28 20:58
I have hit this issue today again, in Bintray.

**Comment by danimtb** [comment] 2019-07-10 16:40
Confirmed the bug is still there but I am not sure if `conan remove <name> -r <remote> -p` (w/o package id) is a "legal" command.

Well, I have tested it in the cache and it removed the packages, so the behavior should be the same for remotes although the help for that command does not indicate `-p` can be used without package id argument.

**Comment by danimtb** [comment] 2019-07-15 16:16
Looks like this issue happens also in Artifactory and it is a duplicate of #1314. Closing this. Please continue the conversation there. Thanks!

**Closed by danimtb** 2019-07-15 16:16 UTC
Labels: complex: high, component: bintray, priority: low, stage: queue, type: bug
