### ISSUE TITLE
[bug] conan v2 package hash calculation is different from conan v1?

### ISSUE THREAD

**Issue by maksim-petukhou** [conan-io/conan#16097] opened 2024-04-17 11:54 UTC
### Describe the bug

Let me show you an example.
There is a msys2 package in conan-center (https://conan.io/center/recipes/msys2?version=cci.latest) and we can see the options that are taken into account for package id:
```
packages: base-devel,binutils,gcc
exclude_files: */link.exe
```
And it lacks `additional_packages=None` option (https://github.com/conan-io/conan-center-index/blob/3264e15a2117e10f4d286d033876d4bc800e47ff/recipes/msys2/all/conanfile.py#L55). It is not deleted in `package_id` function and I don't see any reason why it should not be taken into account. Moreover conan v1 takes it into account as far as I can tell from our Artifactory:
![image](https://github.com/conan-io/conan/assets/6967052/bfe3d06b-a058-431a-9cfe-51152eec040c)

This behavior prevents me from using old binaries of msys2 (because the hash is different) and I really need this because new msys2 binaries doesn't work in our environment.

**Comment by memsharded** [comment] 2024-04-17 13:58
Hi @maksim-petukhov 

Thanks for your feedback.

This is not a bug, this is a feature. The ``package_id`` of Conan 2 are completely different to those of Conan 1, because the computation and the model has changed a lot, and this also enable the possibility of using the same server repo simultaneously for Conan 1 and Conan 2 packages.

You need to create the binaries with Conan 2, it is not intended to reuse the same binaries in Conan 1 and Conan 2, it is only the recipes that are common to both versions.

**Comment by memsharded** [comment] 2024-04-23 08:37
Hi @maksim-petukhov 

Any further question? If not, maybe we can close this ticket? Thanks!

**Closed as completed** 2024-04-23 08:38 UTC
Labels: type: question
