### ISSUE TITLE
Bintray fails for package with '+' symbol (search, install)

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan#4677] opened 2019-03-06 13:17 UTC
If the ConanFileReference contains a `+` symbol the package can be uploaded, but not installed/searched (tested in Bintray).

Search with wildcard returns the packages:

```
Existing package recipes:

name+plus/version@issue/test
name/version+plus@issue/test
name/version@issue+plus/test
name/version@issue/test+plus
```

but trying to access directly any of those packages doesn't return anything

```
⇒  conan search name+plus/version@issue/test -r jgsogo
ERROR: Recipe not found: issue/name+plus/version/test. [Remote: jgsogo]
```

```
⇒  conan install name+plus/version@issue/test -r jgsogo
Configuration:
...

name+plus/version@issue/test: Retrieving from server 'jgsogo' 
name+plus/version@issue/test: Trying with 'jgsogo'...
...
ERROR: name+plus/version@issue/test was not found in remote 'jgsogo'
```

It looks like an error in the Bintray side, as `requests` module is already quoting the URL.

**Comment by memsharded** [comment] 2019-03-06 13:34
What is the behavior of Artifactory and conan_server?

**Comment by danimtb** [comment] 2019-03-06 15:12
Working fine under Artifactory Community Edition for C/C++ 6.8.3 rev 60803900

**Comment by jgsogo** [comment] 2019-03-06 15:12
* conan_server (`develop`, `v1`) works
 * Artifactory works

**Comment by bdegreve** [comment] 2019-03-16 13:23
I had the same issue last week, contacted bintray support, and it seems to be fixed now.

**Comment by danimtb** [comment] 2019-03-18 11:41
Confirmed as fixed with a Bintray repo:

```
$ conan search libB/1.2.3@user+r/test+plus -r public
Existing packages for recipe libB/1.2.3@user+r/test+plus:

Existing recipe in remote 'public':

    Package_ID: f1fc64edd1a6c2fb7d41b78ecf5972a0e7a85df8
        Outdated from recipe: False
```

**Closed** 2019-03-18 11:42 UTC
Labels: component: bintray, type: bug
