### ISSUE TITLE
[bug] MesonToolchain should convert "os=baremetal" to "system=none"

### ISSUE THREAD

**Issue by jhol** [conan-io/conan#16903] opened 2024-08-28 23:38 UTC
### Describe the bug

When cross-compiling, when the Conan `os` setting is set to `baremetal`, `MesonToolchain` passes this value through to Meson with the `system=baremetal` setting. `baremetal` is not a value recognized by Meson. The value should be set to `none`.

**Comment by memsharded** [comment] 2024-09-03 09:38
Closed by https://github.com/conan-io/conan/pull/16904 for next Conan 2.8

**Comment by memsharded** [comment] 2024-09-03 09:44
Please check comments from https://github.com/conan-io/conan/pull/16904#issuecomment-2326075996

**Comment by memsharded** [comment] 2024-09-04 07:30
Closing as not a bug, being reverted in https://github.com/conan-io/conan/pull/16929

**Closed as completed by memsharded** 2024-09-04 07:30 UTC
