### ISSUE TITLE
[question] How to use Custom Generators

### ISSUE THREAD

**Issue by GRyzer** [conan-io/conan#16189] opened 2024-05-01 05:35 UTC
### What is your question?

Hi,

We develop our packages for several platforms. Only for a certain platform we need an additional piece of code that writes certain information (include paths, which we talked about in #16168) into a .project file.
I was thinking of a custom generator that only runs on Windows, for example. I have seen two approaches at [custom_generators](https://docs.conan.io/2/reference/extensions/custom_generators.html).

1. python_requires
2. global custom generator

I rejected the first one because `python_requires` is a class variable and that would be required for every platform, which does not correspond to my use case.

With the second variant, I saw that the documentation provides the following information: `Then you can use them by name in the recipes or in the command line using the -g argument.` Unfortunately, I am not aware of how I can use my generator without using an include. 
If my generator is in `[CONAN_HOME]/extensions/generators/my_generator.py`, I would have assumed that I would need such an include in my `conanfile.py` files.

My questions would be:

1. Is my generator approach the right one to generate project files?
2. How can I include my generator in a package?

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-05-01 11:03
Hi @GRyzer 

Thanks for your question.

> I rejected the first one because python_requires is a class variable and that would be required for every platform, which does not correspond to my use case.

It can be "imported", in the same way a python import or a C++ header can be included, but that doesn't mean it needs to be used for all platforms. The ``python_requires`` is relatively cheap, as it is fetching just some python code, it won't add any overhead compared with all the other heavier operations. Then  you decide to call or not the functionality in the ``python_requires`` conditionally on the platform in the ``generate()`` method, it is not compulsory to extend them, a python-requires can contain just a function that you can call from your ``generate()``. I wouldn't reject this approach, using ``python_requires`` can be quite useful for this purpose and in general if you maintain multiple packages for your own code.

> If my generator is in [CONAN_HOME]/extensions/generators/my_generator.py, I would have assumed that I would need such an include in my conanfile.py files.

It means that you need to do:
```python
generators = "MyGenerator"
```
in your ``conanfile.py``, and it will be called in the same way as other built-ins.

This approach is inferior to the previous one, because global generators are not versioned, it is more difficult to track and reproduce builds using them, they do not have any effect on the ``package_ids``, they are not self-contained (automatically resolved), they are more difficult to upgrade, specially if at some point you need to do some breaking changes.

I'd probably strongly recommend ``python_requires`` approach for most cases.

**Comment by GRyzer** [comment] 2024-05-02 04:55
So Conan implicitly finds my generator. Would have expected me to need an `import conan.extensions.generator.my_generator` or something similar. I'm not quite happy with the solution yet, because both use class variables. This means I can't call a `python_requires` in the `requirements(self)` method to use `self.settings.os`. 

I understand the point of `python_requires` and why I should prefer it. My issue is that it affects the `package_id`, which I don't want in this case. In my usecase I create a file that will be different from user to user and is basically an IDE file (for the indexer, to find some header files if i click on an include), which has no influence on a src or header file, and therefore should have no influence on the `package_id`.

**Comment by memsharded** [comment] 2024-05-02 15:24
> So Conan implicitly finds my generator. Would have expected me to need an import conan.extensions.generator.my_generator or something similar. I'm not quite happy with the solution yet, because both use class variables. 

If this is an IDE file, then most likely the best approach is this one, global custom generators, called in the command line with ``-g MyCustomGenerator`` (by name), when desired to generate for the IDE. But not from the recipe, because no need to add it to all recipes, because that would still be required and used even when not using the IDE, like in CI, that doesn't sound good.

> This means I can't call a python_requires in the requirements(self) method to use self.settings.os.

Yes, you can define any function in a ``python-requires`` and then call it from the consumer with something like ``my_generator_function(self)`` or ``my_generator_function(self.settings)`` and pass whatever information it needs from the consumer data.

> I understand the point of python_requires and why I should prefer it. My issue is that it affects the package_id, which I don't want in this case. In my usecase I create a file that will be different from user to user and is basically an IDE file (for the indexer, to find some header files if i click on an include), which has no influence on a src or header file, and therefore should have no influence on the package_id.

Agree. It is also possible to define independence from the ``python_requires``, so it doesn't affect the ``package_id``, but as commented above, I agree that for this use case a global generator is better.

**Comment by GRyzer** [comment] 2024-05-03 09:08
Is there documentation what i have to do that `python_requires` does not affect my `package_id`?

The other point is resolved for me. I managed to do what i tried to achieve. Thanks a lot

**Comment by memsharded** [comment] 2024-05-03 09:46
This section about the "modes" here might help: https://docs.conan.io/2/reference/conanfile/attributes.html#package-id-embed-non-embed-python-unknown-mode

Also https://docs.conan.io/2/reference/extensions/python_requires.html#effect-in-package-id

Then I think we can close this question as solved, don't hesitate to open new tickets for any further question. Thanks for the feedback!

**Closed as completed by memsharded** 2024-05-03 09:46 UTC
Labels: type: question
