### ISSUE TITLE
[bug] Lock file generated with the `--base` option cannot be used for install

### ISSUE THREAD

**Issue by FnGyula** [conan-io/conan#8144] opened 2020-12-02 14:44 UTC
### Environment Details (include every applicable attribute)
  * OSs: Win/Mac/Linux:
  * Compiler: VS2017/AppleClang 10.3/gcc 6.3.1:
  * Conan version: 1.31.4
  * Python version: 3.7.7

### Steps to reproduce (Include if Applicable)

1. `conan lock create --base --lockfile-out conan.lock conanfile.py`
2.a. `conan install -l conan.lock .`

or

2.b. `conan install -pr default -l conan.lock .`

### Logs (Executed commands with output) (Include/Attach if Applicable)

For 2.a:
```
ERROR: Lockfiles with --base do not contain profile information, cannot be used. Create a full lockfile
```

For 2.b:
```
ERROR: Cannot use profile, settings, options or env 'host' when using lockfile
```

### Summary

It looks like that the conan.lock files generated with the `--base` option are not useful at all, it leads to a catch 22. On one hand, conan expects profile data provided because the 'base' lock files do not have full binary information, but if one provided, conan refuses to do anything, because it's not allowed to provide profile information if lock files are in use.

The 'base' lock files are generally very desirable, because with revisions, I expected that I could the base lock files to prevent auto opt in for newer revision of a package that might not be complete just yet, or well tested. I would rather keep the revisions out of the conanfile itself, because it lends itself to some serious pain to update. But up to this point, there don't seem to be any other solution and I think this might a really difficult situation with revisions: the only way to lock something to a revision and for nothing else is to peg it in the recipe itself. A full lock file is per platform and per configuration etc. Which means that it gets really difficult to manage them in a version control settings.

The 'base' lock file in my mind is a simple dictionary: if the recipe request anything, it would look up if that recipe is locked within the 'base' lock file and if it is, it's straightforward. But if the dependency is missing from the lock file, it would just do the default thing, resolve the version and the revision in the usual way.

In some way it's surprising that the lock files also not particularly human readable, in the sense there's an extra indirection bu indexing, which makes it not trivial to track changes to it.

**Comment by memsharded** [comment] 2020-12-02 14:55
Hi @FnGyula 

This is not a bug, this is by design.
You need to derive a configuration specific lockfile from the base one in order to be able to install it.

Please read carefully https://docs.conan.io/en/latest/versioning/lockfiles/configurations.html#base-lockfiles, there it explains how to do it, in short:

```bash
$ conan lock create conanfile.py --user=user --channel=testing --lockfile=locks/pkgb_base.lock --lockfile-out=locks/pkgb_deps_debug.lock -s build_type=Debug
$ conan lock create conanfile.py --user=user --channel=testing --lockfile=locks/pkgb_base.lock --lockfile-out=locks/pkgb_deps_release.lock
```

**Comment by FnGyula** [comment] 2020-12-02 16:48
Ok, that kind of makes sense, thank you.

I just wonder if we could merge this functionality into install, because this will add an extra command for every dev trying to use the system. From a user experience point of view, not being part of the install command while it looks very much like the install command makes it largely redundant and difficult to remember. And if that's the case, now I have to roll an extra (cross-platform!) script to run to wrap conan. I would advise to do this as a default in the conan install when base lock file is specified. Install does create a lock file, and the -u updates that lock file, so from my perspective, I would rather have this as an implicit behaviour.

**Comment by memsharded** [comment] 2020-12-02 18:15
Hi @FnGyula 

I understand the use case, let me explain the current state and how we got here, and lets see if it is possible to evolve from here or not:

We had more or less that behavior in the previous versions, and we decided to change it because it was very problematic. Having ``conan install`` being capable of modifying the structure and the values of the lockfiles was breaking in practice the locking guarantees you want to get from a lockfile. It was very buggy, inconsistent and confusing.

So we changed it to a more strict model: all operations using lockfiles, install, create, info: 
1. Cannot change the structure or topology of the graph stored in the lockfile
2. Cannot modify any of the values captured in the lockfile
3. It can only add new data that was not locked before.

The problem with "base" lockfiles is that they are not always complete. If you have a conditional requirement depending on the OS, the base file will need to mutate on other OSs different to the one used to capture the lockfile. Limiting the mutation to the ``conan lock create`` command, (and it is not a mutation, it is creating a new lockfile), clearly captures the concept that ``conan install`` cannot, even partially, change the structure of a lockfile.

As an example: if there is a conditional requirement to a "windep/0.1" that only works on Windows, and the base lockfile is captured in Linux, then the result of doing the following in Windows is problematic:

```bash
$ conan install . --lockfile=mybaselockfile.lock
# Now someone creates a new revision of "windep/0.1"
$ conan install . --lockfile=mybaselockfile.lock # Different result! "windep/0.1" is not locked!
```
The same command, passing exactly the same lockfile, and you got 2 different dependency graphs as a result. Some users could consider this a bug.

I suggest considering this idea as a new feature, and lets investigate if it is technically feasible, and what other implications it could have.

**Comment by kaihowl** [comment] 2020-12-04 17:28
Could we add a `--base-lockfile` option that would allow to get the previous behavior back? I.e., takes the base lockfile and derives a full lockfile under the hood from it that is then used for the install command?

**Comment by memsharded** [comment] 2020-12-04 18:16
Hi @kaihowl 

Could you clarify?

> Could we add a --base-lockfile option that would allow to get the previous behavior back?

Base lockfiles were never used for ``conan install``, since the release they were introduced. The previous behavior was ``conan install`` ignoring the locked information (incorrectly/bug). Or is there something that I am missing? I would like to understand if we have introduced any regression of "base" lockfiles.

Otherwise, yes, I am not saying this cannot be done, and probably what you are suggesting, a explicit opt-in to define that the lockfile is a base one could be good. Still seems a new feature, not a bugfix, lets label it and lets try to see if possible and investigate what would be the best UX (without compromising consistency)

**Comment by kaihowl** [comment] 2020-12-05 12:04
> We had more or less that behavior in the previous versions, and we decided to change it because it was very problematic. Having conan install being capable of modifying the structure and the values of the lockfiles was breaking in practice the locking guarantees you want to get from a lockfile. It was very buggy, inconsistent and confusing.

This lead me to believe that this behavior was there in previous versions: Using a base lockfile with install internally triggers a `conan lock create` with the same settings, profile, and options.

Hence, my comment to "get the previous behavior back". Apologies if that was not the case.

The concrete proposal is therefore:
```
conan install -pr default -l conan.lock .
```
given that `conan.lock` is a base lock file shall be equivalent to
```
conan lock create --lockfile conan.lock --lockfile-out conan.full.lock conanfile.py
conan install -l conan.full.lock .
```

**Comment by memsharded** [comment] 2021-01-28 00:41
Hi @kaihowl @FnGyula 

I have been trying in https://github.com/conan-io/conan/compare/develop...memsharded:feature/lock_install_base?expand=1 to implement this feature. And so far I have failed, I don't see a consistent way to do this.

The problem is that ``conan install --base-lockfile`` (or passing a base lockfile to --lockfile) can, and many times will have a different base or reference than the ``conan lock create``, rendering the rest of the functionality related to lockfiles broken.  The above equivalence only holds valid for when the reference is the same, but one very important use case of the lockfiles look like:

```bash
# Assume app -> libc -> libb -> liba
conan lock create --reference=app/1.0@ --base --lockfile-out app_base.lock
conan lock create --reference=app/1.0@ --lockfile=app_base.lock --profile=Windows --lockfile-out=app_windows.lock
conan lock build-order app_windows.lock
> [liba/1.0, libb/2.0, ....] build order
conan install liba/1.0@ --build=liba/1.0@ --lockfile=app_windows.lock --lockfile-out=app_windows.lock
conan install libb/1.0@ --build=libb/1.0@ --lockfile=app_windows.lock --lockfile-out=app_windows.lock
```

The last ``conan install`` completely preserves the structure of the graph. No packages will be removed or added to the lockfile, and it just adds package revision of the package being built, which allows to keep using it down the graph building packages.

Allowing a base lockfile into ``conan install`` means that it should be able to mutate the graph. Then the final ``app_windows.lock`` after the first ``conan install liba/1.0@...`` will only contain only ``liba/1.0`` and will be broken downstream. I can see many users being confused about this and requiring support and clarifications.

So at the moment, I think it might be better to keep this separated into 2 commands, even if apparently not that convenient, it is more consistent. What do you think? cc @solvingj

**Comment by solvingj** [comment] 2021-01-29 22:51
Unfortunately, I don't have any personal experience with the `--base` flag yet, so I don't have much intuition about what is possible with it.  My understanding was that it was conceived and designed to support one case: capturing recipe revisions at a single point in time and generating multiple per-configuration lockfiles from it.  Maybe what @kaihowl is trying to do seems reasonable on the surface.  However, if @memsharded agreed, tested it, and found it impossible or infeasible to support, then I have complete faith that he's correct and it's effectively an invalid use case for future reference.

One thing I'll add is something that I've learned about lockfiles is this:

> Any creative and undocumented usage patterns with lockfiles should be assumed impossible and invalid unless proven otherwise. 

Unlike most experimental features in Conan, extreme time and effort has been invested into making lockfiles rigid.  Not intentionally rigid just for the purpose of being rigid, but rigid in order to provide a STRONG foundation of guarantees surrounding the validity of graph operations (essentially CRUD operations).  This rigidity can seem extra frustrating because users definitely do not appreciate the domain complexity which lies behind the lockfiles, such as the vast diversity of corner-cases which can exist, and which render "seemingly simple feature requests" invalid.

**Comment by kaihowl** [comment] 2021-02-02 06:23
@memsharded Thank you for having tried the implementation out. My use case is very narrow compared to what lockfile support seems to support. Since this was just an improvement, I can certainly live with having to issue two instead of one command.

**Comment by jgallucci32** [comment] 2021-06-04 23:12
This might be a new feature available in a recent release, but I got the desired outcome with Conan/1.37 using the `conan lock create` command. This creates a full lockfile from a partial one.
```
conan lock create conanfile.txt --base --lockfile-out=partial.lock
mkdir build && cd build
conan lock create ../conanfile.txt --lockfile ../partial.lock
conan install ..
```

**Comment by p-groarke** [comment] 2022-09-03 18:07
Not my intention to revive an old thread, but we are currently bumping into this issue.

What we are seeing is, anything pulled from conancenter breaking on a weekly/bi-weekly basis due to the recipes updating to new conan features. We lock our conan version internally.

In particular, we'd like to create something equivalent to `--base` locks, but only for recipe revisions. As I understand it, creating a base lockfile on a system that has `RREVs` enabled already does this, maybe? It sure looks like it here :)

Now, platform or option dependent dependencies is problematic as you mentioned (`if bla : self.requires(...)`). To fix this, I believe conan needs to be aware of *all* dependencies, for all platforms and all configurations at the moment of `lock create`. One way I can think of achieving that is with conditional predicates. A user would register all requirements, but pass in a predicate to enable/disable said requirement.

For ex,
```python
# Please bear with me, I am not a python dev :]
self.requires_if("LibA/1.0@user/chan", lambda me: me.options.abi_version == 1)
self.requires_if("LibA/2.0@user/chan", lambda me: me.options.abi_version == 2)
```

The details of how this would be implemented are irrelevant to me, the snippet is just to illustrate. Bottom-line is, for something like a `RREV` lockfile to truly work well, conan must be aware of *all* requirements at the moment of generation, regardless of platform. Then it should be possible to create a fully set-in-stone lockfile.

I do understand some of the "non currently consumed" `RREVs` may be problematic, but imho that is a user / ci problem. I'm expecting to create a revision lockfile this way, push to CI, then tweak all platform `RREVs` until it's green, for ex. I would also expect an error if a given recipe is encountered which isn't listed in the `revision lockfile`. This means it wasn't registered using the expected system, so conan should fail; user error.

Just a fyi, we currently specify the RREVs in our `requires`. Ex, `self.requires("LibA/1.0.0@user/chan#45d46b6180d9775a2efe4a2837308f59")`. This is quite tedious, also less flexible than lockfiles. Problems come from packages we don't maintain.

My 2 cents, hope we can discuss this in person soon, cheers :)

**Comment by memsharded** [comment] 2022-09-03 21:00
Hi @p-groarke 

I did like at least 2 attempts at this in 1.X. Unfortunately it doesn't seem possible, it is just too complex. One of the complications is the way the dependencies are resolved, which is not deterministic, and that is the reason the lockfiles in 1.X store the full graph.

This is also the reason we did a big effort in the new 2.0 lockfiles. If you haven't tried them yet it would be great if you could give them a try and give some feedback.

**Comment by p-groarke** [comment] 2022-09-03 21:48
Hey @memsharded, I'm just getting up to speed with lockfiles. Reading the proposal for 2.0, the new lockfiles seem much more aligned with what we want. A simple way to lock RREVs (and just RREVs). Well done!

**Comment by memsharded** [comment] 2023-12-01 13:30
Closing this ticket as outdated, lockfiles in 2.0 solve this issue.

**Closed as completed by memsharded** 2023-12-01 13:30 UTC
Labels: type: look into, type: feature
