### ISSUE TITLE
Use `conan config install` to disable [proxies]-section in conan.conf

### ISSUE THREAD

**Issue by monsdar** [conan-io/conan#4678] opened 2019-03-06 13:17 UTC
Currently the default conan.conf contains a `[proxies]` section like the following:

```
[proxies]
# Empty section will try to use system proxies.
# If don't want proxy at all, remove section [proxies]
# As documented in http://docs.python-requests.org/en/latest/user/advanced/#proxies
# http = http://user:pass@10.10.1.10:3128/
# http = http://10.10.1.10:3128
# https = http://10.10.1.10:1080
# You can skip the proxy for the matching (fnmatch) urls (comma-separated)
# no_proxy_match = *bintray.com*, https://myserver.*
```

I would like to not use proxy at all, so I uncomment the section by hand: `#[proxies]`. Now I also would like to install this type of config via `conan config install ...`. The issue here is that this only merges the configuration. As `[proxies]` is uncommented it will not merge this into the conan.conf.

Any ideas on how to achieve this with the current Conan version? Or would this be something that needs to be implemented?

**Comment by danimtb** [comment] 2019-03-06 15:48
Do you mean you want to disable anything in `[proxies]` to whoever had a customize `[proxies]` section already in *settings.yaml*? Like deactivating settings from ``conan config install``?

**Comment by memsharded** [comment] 2019-03-06 16:05
Yes, I am afraid this is not possible right now, as ``conan.conf`` is merged, but no removal of sections is possible. So it should be implemented. But I don't know exactly how, without very complicated 3-way-merge logic. Maybe some ``conan_swap.conf`` file or some name convention that means "just overwrite the file, dont merge it".

**Comment by danimtb** [comment] 2019-03-06 16:09
Actually, the proxies section comes unpopulated so a fresh install of Conan and then a ``conan config install`` will do it.

Could you explain a little bit more your use case @monsdar ?

**Comment by monsdar** [comment] 2019-03-07 10:01
@danimtb: Conan knows three ways to configure your proxy:

1. Use the system proxy. This is the default way, you do this by simply having an empty `[proxies]` section within your conan.conf
2. Specify your own proxy. You can do this by adding custom `http`, `https` and `no_proxy_match` configuration within the `[proxies]` section.
3. Use no proxy at all. For this to work you need to have a `conan.conf` without a `[proxies]` section at all.

In my environment I'd like to use approach 3 - no proxy at all. For this I'd need to change the default `conan.conf` and comment/remove the `[proxies]` section. This is not possible with `conan config install`, as it is only merging the config.

I'm not sure if @memsharded s ideas would work really well... Adding a 3-way-merge would certainly add a lot of complexity for a mechanism that should be easy to handle. Using `conan_swap.conf` would work in that case, but what if I don't want to overwrite other parts of the config?

My idea would be to add a new optional option under the `proxies` section:

```
[proxies]
use_system_proxy = False
```

This way it would be explicitly configured in a way that the system-proxy should (not) be used. To not break any existing installations it could default to `True` when this setting is not set or something similar.

For my specific case I was able to work around it by adding `no_proxy_match` for our internal server - but this is probably not a solution that would work for everyone in every case.

**Comment by memsharded** [comment] 2019-03-07 12:07
Yes, that would make more sense than relying on the [proxies] section to not be there.
I think we could try to implement that (and then deprecate the old behavior in Conan 2.0)

**Comment by lasote** [comment] 2019-10-21 08:06
@monsdar I need you to confirm if removing the section disables the system proxies. It seems that according to @SSE4 investigations that is not true, and then the issue is a different one.

**Comment by monsdar** [comment] 2019-10-22 13:34
I'm not in an environment where I can test this easily right now. Will do so asap and let you know.

**Comment by lasote** [comment] 2019-10-28 10:49
Everything points out that removing the entire section doesn't help with system proxies. So I think this issue is no longer valid. @monsdar unless you check and it works.
I will open a new issue to track if we could disable from Conan the system proxies but after the investigations of @SSE4 I don't see we should try without a better and explicit mechanism provided by the requests library, so I see it difficult.

**Closed by lasote** 2019-10-28 10:49 UTC
Labels: complex: low, priority: medium, stage: queue, type: feature

**Comment by monsdar** [comment] 2019-10-29 10:14
I'm very sorry for the late response to this. I just checked the behaviour and it seems as if it has changed.

* No `[proxies]` section at all: Conan uses system proxy
* Empty `[proxies]` section (just the header): Conan uses system proxy 
* `[proxies]` that only contains `no_proxy_match`: Conan uses system proxy by default, but ignores it for the addresses that are configured
* Full configured `[proxies]` section: Conan uses whatever is configured

Tested with
* Conan 1.19.2
* Windows 10
* Python 3.7.3
* requests 2.22.0

**Comment by SSE4** [comment] 2019-10-29 10:36
@monsdar thanks for the information. so, to summarize:
1. there is no behavior difference between no `[proxies]` and empty `[proxies]` section
2. there is no way to disable usage of system proxies in conan
