### ISSUE TITLE
[bug] g++ clang frontend on Windows (mingw) not supported by CMake build helper

### ISSUE THREAD

**Issue by mbeier21** [conan-io/conan#8555] opened 2021-02-25 09:47 UTC
In our project we want to use the clang compiler with g++ front end on Windows.
My toolchain is based on [llvm-mingw](https://github.com/mstorsjo/llvm-mingw), which I built manually and created a conan package afterwards. This package is then used as build requirement in a new build profile "mingw_clang110_x64" :

```
include(_win_x64)

[settings]
compiler=clang
compiler.version=11
compiler.cppstd=14
compiler.libcxx=libc++
compiler.runtime=MD
compiler.driver=g++

[env]
CC=clang.exe
CFLAGS= --target=x86_64-pc-windows-gnu
CXX=clang++.exe
CXXFLAGS= --target=x86_64-pc-windows-gnu -std=c++14 -stdlib=libc++ -lc++abi
RC=windres.exe

CONAN_MAKE_PROGRAM=ninja
CONAN_CMAKE_GENERATOR="Ninja"

[build_requires]
ninja/1.10.2@local/testing
llvm-mingw/11.0.0@local/testing
```

Please note that we prefer packaged tools over locally installed tools. This is the reason why we have the "ninja" and "llvm-mingw" packages here.

So far this approach went very well. But on your CI server I've got a ConanException at `cmake.configure()` in the build method of conanfile.py in any module I want to build.

```
    def build(self):
        cmake = conans.CMake(self)
        cmake.configure()
        cmake.build()
```

After a search in the Internet and a look into the conan sources, I figured out that the [CMake class](https://github.com/conan-io/conan/blob/develop/conans/client/build/cmake.py) tries to open a vc shell if clang is detected. (This matches the difference between my development computer and the CI server, where I don't have Visual Studio installed.)

The root cause of this problem is the clang detection in the CMake class, which does not take into account, that clang can be used with mingw too. In this case the front end is g++ and the vc shell is not needed.

To solve this issue, one can utilize the "driver" setting introduced by https://github.com/conan-io/conan/pull/5705.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10, 64 bit
  * Compiler+version: clang 11.0 [llvm-mingw](https://github.com/mstorsjo/llvm-mingw)
  * Conan version: 1.16.1 (all versions from 1.16.1 to the latest are affected)
  * Python version: 3.7.2

### Steps to reproduce (Include if Applicable)
call `conan create . user/channel -pr mingw_clang110_x64`

### Logs (Executed commands with output) (Include/Attach if Applicable)

> ERROR: SomeModule/1.0.0@user/channel: Error in build() method, line xx
> cmake.configure()
> ConanException: compiler.version setting required for vcvars not defined

**Comment by jgsogo** [comment] 2021-02-26 15:02
Hi, @mbeier21 . It is perfectly possible that the helpers we are providing don't work with all the combinations of the different tools out there. Sometimes it is because we don't know or we didn't have time to reproduce a working scenario where we can develop the feature and figure out how to add it to our tests.

We are moving forward on our way to Conan 2, and we've started to add new helpers and a new paradigm that will likely be the default for Conan v2, but we are introducing in Conan v1.x so the migration is easier for all our users. These new helpers are the place for this new functionality and integrations. [Here](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake.html?highlight=cmaketoolchain) you can start reading about them.

We would like to try this scenario with this new Conan approach and implement the feature. I'm not a Windows user, so it's hard for me to evaluate how hard it can be to configure all those tools to work together. Is there any easy _how to_ we can follow to configure the _canonical_ setup for this kind of compilation, so we can start to try and test it? Thanks!

**Comment by gsantner** [comment] 2024-05-19 09:33
Qt nowdays support LLVM based MinGW nowadays too ( <https://www.qt.io/blog/qt-6.7-released> ). Prebuilts are available for both the compiler toolchain as well Qt built with it.  
**Unfortunatley Conan can't be used with it in conjunction as it not supports LLVM-MinGW (dependencies can't be added/won't be compatible).**

Is there any chance this gets supported anytime soon? LLVM-MinGW also means possible support of Chromium and thus non-msvc (Chromium based ) QtWebEngine on Windows.

**Comment by gsantner** [comment] 2024-05-19 09:34
Qt supports LLVM based MinGW nowadays too ( <https://www.qt.io/blog/qt-6.7-released> ). Prebuilts are available for both the compiler toolchain as well Qt built with it.  
**Unfortunatley Conan can't be used with it in conjunction as it not supports LLVM-MinGW (dependencies can't be added/won't be compatible from GCC-MinGW/not compiles).**

Is there any chance this gets supported anytime soon?

**Comment by memsharded** [comment] 2024-05-19 21:17
Hi @gsantner 

I think this ticket was quite outdated, and lots of things have changed since then.
The build system integrations described ago are legacy in Conan 1.X and have been removed in Conan 2.

This updated blog https://blog.conan.io/2022/10/13/Different-flavors-Clang-compiler-Windows.html describes how different flavors of LLVM are supported including ``Msys2 MinGW Clang`` one.

So I am going to close this ticket as resolved, if there is something failing, then it would need a new, updated ticket. 
Also note that the issues could be in different places, if it is a bug in Conan client, it should be reported with a simpler recipe, like the one with ``conan new cmake_lib`` template. It is possible that it would be a limitation of the Qt recipe in ConanCenter, in that case it should be better reported in ``conan-center-index`` repo (though please take into account that the activity there is very high, like 6000 PRs in 2023 alone, so it is difficult to follow up with everything)

Thanks for your feedback!

**Closed as completed by memsharded** 2024-05-19 21:17 UTC
Labels: priority: low, type: feature, stage: queue, complex: medium, component: Build
