### ISSUE TITLE
[bug] MSBuild.build() definitions values are checked against False instead of None.

### ISSUE THREAD

**Issue by JeremyGola** [conan-io/conan#6728] opened 2020-03-24 16:36 UTC
In the [format_macro](https://github.com/conan-io/conan/blob/f88d55a80a3acaaa3aec9ff1f1c985895c9445a2/conans/client/build/msbuild.py#L197) function in conans/client/build/msbuild.py, the line `return "%s=%s" % (name, value) if value else name` is at odds with the [documented behavior](https://docs.conan.io/en/latest/reference/build_helpers/visual_studio.html#methods): 

> definitions (Optional, Defaulted to None): Dictionary with additional compiler definitions to be applied during the build. **Use a dictionary with the desired key and its value set to None to set a compiler definition with no value**.

### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10 x64 Pro
  * Compiler+version: Visual Studio 16
  * Conan version: 1.21
  * Python version: Python 2.7.15

### Steps to reproduce (Include if Applicable)
Set a dictionary value to integer value 0 (e.g. d = {"foo": 0})
Pass dictionary into MSBuild.build() via definitions parameter.
Key will be passed on as a define without a value.

**Comment by memsharded** [comment] 2020-03-24 23:09
Hi @JeremyGola 

You are totally right, this is a bug. Thanks very much for investigating the cause too, you were just 1 test away of a Pull Request :) 

I have submitted the PR https://github.com/conan-io/conan/pull/6730, this will be merged and released in Conan 1.24 next week.

Thanks again for reporting and investigating

**Closed** 2020-03-25 08:35 UTC
Labels: type: bug
