### ISSUE TITLE
Missing of the artifacts' repo path for the buildInfo in Artifactory

### ISSUE THREAD

**Issue by NIICKK** [conan-io/conan#5628] opened 2019-08-14 19:52 UTC
conan version: 1.14.4
I tried to upload the buildInfo for my conan package using the way described in the conan official page: https://docs.conan.io/en/latest/howtos/generic_ci_artifactory.html
The problem I have is that, for the package I published to artifactory, its buildInfo doesn't have the corresponding repo path. 
<img width="498" alt="Screen Shot 2019-08-14 at 12 15 56 PM" src="https://user-images.githubusercontent.com/16881951/63051165-aac0f180-beaa-11e9-91b5-9a4cf421e6e4.png">
This path is critical for doing the promotion using jfrog cli.

**Comment by jgsogo** [comment] 2019-08-15 09:17
Hi, @NIICKK, besides following those docs, I would recommend you to use the Artifactory plugin for Jenkins, it would help you with your Jenkinsfile. Also, you can find more information on this issue (https://github.com/conan-io/conan/issues/5553) and following the links provided in it.

Please, let me know if it is ok for you to use the plugin, if not let me know and I will try to reproduce your use case in one of my _Jenkinsfiles_ and investigate what it is happening there.

Thanks!

**Comment by jgsogo** [comment] 2019-09-09 13:55
Hi! Confirmed, something is not working properly with the _Repo path_ for the build info. I'm investigating the issue.

**Comment by chrismathis** [comment] 2023-01-19 15:51
Hi, this still seems to be a problem with conan 1.57.0 and Artifactory 7.49.5 and while using the Artifactory plugin.
Is there any workaround to generate a buildInfo that works for build-promotion in artifactory with jfrog cli?

**Comment by memsharded** [comment] 2023-11-29 22:33
The artifactory extensions commands for Conan 2.0 (https://github.com/conan-io/conan-extensions/tree/main/extensions/commands/art) creates a buildInfo, but it is true that the promotions don't work great with buildInfo, and the recommended way nowadays by Artifactory is to use release-bundles. We are also working with some other Conan custom command extensions in https://github.com/conan-io/conan-extensions to be able to run promotions directly with Conan ``package lists``.

I am closing this ticket here, if there are questions about the new buildInfo, please report in https://github.com/conan-io/conan-extensions. Thanks!

**Closed by memsharded** 2023-11-29 22:33 UTC
Labels: type: bug, type: look into, component: artifactory, priority: medium, component: Jenkins plugin
