### ISSUE TITLE
Rebuilt package considered up to date - upload rejected

### ISSUE THREAD

**Issue by lewie-donckers** [conan-io/conan#1879] opened 2017-10-12 11:25 UTC
Consider the following scenario. Several internal libraries under active development are built by the build server using the following ref pattern: `<libname>/latest@shuttle/ci`. So, the version name, username and channel are all fixed. On the build server we use `conan create` to (re)build all libraries before uploading them to the Conan server.

A few days ago we updated library libA which is a header only library. Another library (libB) depends on that library and some of libA's functions are compiled into its library files.

What we noticed is that the new libA did get uploaded to the Conan server but that the new libB did not get uploaded. The logs show that Conan considered both the existing recipe and the existing packages for libB to be up to date. This basically causes libB on our Conan server to be incorrect (because it is out of date). This was not what we expected. 

I took a look at the [ABI compatibility howto](http://conanio.readthedocs.io/en/latest/howtos/define_abi_compatibility.html) and the [upload --force option](http://conanio.readthedocs.io/en/latest/reference/commands/upload.html) but both did not seem to be able to fix this.

Are we doing something wrong? Did we stumble upon a bug?

**Comment by lasote** [comment] 2017-10-12 14:44
If you are rebuilding all the libraries in the CI with `conan create` and then uploading them to a conan server it should work. If libB has changed it should be uploaded to the server, because it has changed. Please ensure that libB was re-built and that libB required the re-built version of libA. 

The ABI compatibility howto can't help you with it, because if you don't change anything in the reference of libA, libB can't know (even customozing it with the package_id() method) if has to be rebuilt.

I wouldn't say that you are doing something wrong, if the libraries are in a very heavy development state and you don't need package versioning or traceability in this point this is ok. Some users are using git commit shas to bump the versions, other using `conan alias` to point to the latest, others use version ranges... but I insisit, your workflow should work, in some point something is not working as expected.

**Comment by memsharded** [comment] 2017-10-12 20:55
Could you please check the conanmanifest.txt of LibB, before and after the re-build? The upload (overwriting the previous version) is only skipped if the checksum of the files are identical, which shouldn't be the case. If you could also  please copy (or send us by email if private) the full output, it might help. Thanks!

**Comment by lewie-donckers** [comment] 2017-10-13 07:07
I will but I'll be out of the office for a couple of days. I'll get back to you on Wednesday.

**Comment by lewie-donckers** [comment] 2017-10-18 11:09
So, I've done a couple of tests and I think this problem might be related to #1841. Before the tests I removed all related libraries from my Conan cache and from our Conan server.

libA = lmsdds.dds
libB = lmsdds.discovery

First I used `conan create` to create all libraries. The manifests of lmsdds.discovery:
[export_manifest.txt](https://github.com/conan-io/conan/files/1394333/export_manifest.txt)
[package_manifest.txt](https://github.com/conan-io/conan/files/1394334/package_manifest.txt)

I then changed a header file in lmsdds.dds (one that is compiled into the lib of lmsdds.discovery) and used `conan create` again. The manifests of lmsdds.discovery however did not change:
[export_manifest.txt](https://github.com/conan-io/conan/files/1394336/export_manifest.txt)
[package_manifest.txt](https://github.com/conan-io/conan/files/1394337/package_manifest.txt)

So, it seems that the old header files of lmsdds.dds were used to build lmsdds.discovery.

I then cleared my Conan cache and ran `conan create` again. This time, the manifests of lmsdds.discovery had changed:
[export_manifest.txt](https://github.com/conan-io/conan/files/1394339/export_manifest.txt)
[package_manifest.txt](https://github.com/conan-io/conan/files/1394340/package_manifest.txt)

What do you think?

**Comment by memsharded** [comment] 2017-10-18 12:05
Thanks for the detailed info.
Yes, I think this could be an effect of: https://github.com/conan-io/conan/issues/1841. 

Are you able to run from sources? In that case, you could try running from the develop branch, and verify that both issues are fixed. Otherwise, please stay tuned for 0.28 release.

**Comment by lewie-donckers** [comment] 2017-10-23 06:56
I might be able to run from sources later this week. I'll post my findings if/when I do.

**Comment by lewie-donckers** [comment] 2017-10-24 14:08
I just tried running from sources but that didn't help. I've been examining logs and when I do the second `conan create` for lmsdds.discovery (libB) it seems to skip the build of the library on only builds the test package.

```
Executing in D:\dev\lmsdds.core:
        conan create --cwd discovery -u --build=outdated --set build_type=Release --set compiler=Visual Studio --set compiler.runtime=MT demo/testing


lmsdds.discovery/latest@demo/testing: Exporting package recipe
lmsdds.discovery/latest@demo/testing export: Copied 5 '.cpp' files
lmsdds.discovery/latest@demo/testing export: Copied 1 '.txt' files: CMakeLists.txt
lmsdds.discovery/latest@demo/testing export: Copied 8 '.h' files
lmsdds.discovery/latest@demo/testing: The stored package has not changed
...
```

Strictly speaking the package has not changed but one of its dependencies has. Is this by design? If so, how can I work around this?

**Comment by lewie-donckers** [comment] 2017-10-24 14:29
When I add `--build=lmsdds.discovery` the library is rebuilt. I did not think this would be required because your documentation states that:

> conan create demo/testing is equivalent to:
>
> $ conan export demo/testing
> $ conan install Hello/0.1@demo/testing --build=Hello
> $ conan test_package demo/testing --test-only

But this does not seem to be correct in that I had to explicitly tell Conan to rebuild the package. Your thoughts?

**Comment by memsharded** [comment] 2017-10-24 16:57
Yes, if that is the case, it might be a bug. But are you sure it doesn't build it? I have been trying locally, and not able to reproduce. Can you please paste the whole output of your ``conan create``? Including lines after ``lmsdds.discovery/latest@demo/testing: The stored package has not changed``. That message is mostly related to the source code, that it doesn't need to retrieve again if the recipe didnt change, but in any case, it should rebuild from sources.

Workaround could be of course ``conan remove Pkg/0.1@user/channel -f`` before the create, but I would prefer to understand and fix what could be happening here.

**Comment by lewie-donckers** [comment] 2017-10-25 08:36
OK, I gathered some logs. I removed all relevant libraries from my Conan cache (`*@demo/*`). I then did a `conan create` of all libraries. (There are more than two.) The output can be found in the following file:

[build.0.txt](https://github.com/conan-io/conan/files/1413823/build.0.txt)

I then updated a header from lmsdds.dds and ran `conan create` for lmsdds.dds and lmsdds.discovery. The output can be found in the following file:

[build.1.txt](https://github.com/conan-io/conan/files/1413825/build.1.txt)

I think it shows that lmsdds.discovery is not being rebuilt.

**Comment by memsharded** [comment] 2017-10-25 09:35
Oh, yes, I think I know what the issue is now.

The thing is that you are defining ``--build=outdated``. This overwrites the default ``conan create`` behavior, that is to specify ``--build=Pkg``, being Pkg the package being created. So if you specify the ``--build=outdated``, you also have to specify ``--build=<your-pkg-name>``, to force its re-building. 

The reason for this behavior is that if we left the ``--build=Pkg`` it would be impossible to really define the ``outdated`` behavior if you wanted it.

Please try to add ``--build=<your-pkg-name>`` to your command line, and tell me if this is what you need. Thanks again for your detailed feedback and running from sources to report.

**Comment by lewie-donckers** [comment] 2017-10-25 12:48
Yes, that does work. I just didn't expect the `--build=outdated` to override the `--build=Pkg`. If you do a `conan create`, wouldn't you always want a fresh build?

Anyway, I have updated my build scripts, so it's no longer an issue for me.

**Comment by memsharded** [comment] 2017-10-25 12:59
Yes, some users may want only the build if the binary is outdated, otherwise they don't want to fully re-build. Plus ``conan create`` does other things as running ``test_package``, so some users find patterns like ``--build=missing`` useful.

Ok, then I guess we can close this issue. Thanks very much!

**Closed by memsharded** 2017-10-25 12:59 UTC
