### ISSUE TITLE
[bug] 'Copying sources to build folder' fails on WSL

### ISSUE THREAD

**Issue by Nekto89** [conan-io/conan#6777] opened 2020-04-01 15:07 UTC
### Environment Details
  * Operating System+version: Debian under Windows 10.0.18363.720
  * Compiler+version: gcc 8.3.0
  * Conan version: 1.24.0
  * Python version: 3.7.3

### Steps to reproduce (Include if Applicable)
conanfile.txt
```
[generators]
cmake

[requires]
cryptopp/8.2.0@bincrafters/stable

[options]

[imports]
```
`~/.local/bin/conan install . -s build_type=RelWithDebInfo -s compiler=gcc -s compiler.version=8 -s compiler.libcxx=libstdc++11 -s compiler.cppstd=17 -g=cmake --build=missing`

### Logs (Executed commands with output)

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=RelWithDebInfo
compiler=gcc
compiler.cppstd=17
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

cryptopp/8.2.0@bincrafters/stable: WARN: Package is corrupted, removing folder: /mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/package/e057d6535368819b51ca06d43e536f86b92dd7f1
conanfile.txt: Installing package
Requirements
    cryptopp/8.2.0@bincrafters/stable from 'conan-center' - Cache
Packages
    cryptopp/8.2.0@bincrafters/stable:e057d6535368819b51ca06d43e536f86b92dd7f1 - Build

Installing (downloading, building) binaries...
cryptopp/8.2.0@bincrafters/stable: WARN: Build folder is dirty, removing it: /mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1
cryptopp/8.2.0@bincrafters/stable: Copying sources to build folder
ERROR: [('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source/source_subfolder/.github', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/.github', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/.github'"), ('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source/source_subfolder/TestData', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestData', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestData'"), ('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source/source_subfolder/TestPrograms', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestPrograms', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestPrograms'"), ('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source/source_subfolder/TestScripts', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestScripts', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestScripts'"), ('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source/source_subfolder/TestVectors', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestVectors', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder/TestVectors'"), ('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source/source_subfolder', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1/source_subfolder'"), ('/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/source', '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1', "[Errno 13] Permission denied: '/mnt/d/conan/.conan/data/cryptopp/8.2.0/bincrafters/stable/build/e057d6535368819b51ca06d43e536f86b92dd7f1'")]
Error copying sources to build folder
```

Workaround in https://bugs.python.org/issue38633 has helped locally

**Comment by jgsogo** [comment] 2020-04-02 08:04
Hi, @Nekto89 

Thanks a lot for the report and for the link to the workaround. If you feel like, you can create a PR: we usually create a helper function somewhere in the `conans.utils` module and try to use the workaround only for the specific scenario (so some `if-else` detecting the WSL to apply the workaround), then we call that function instead of the `shutil.copytree` where it is necessary.

Thanks!

PS.- We should monitor the issue linked, I suppose that at some moment they will add a patch to Python itself.

**Comment by memsharded** [comment] 2020-04-08 22:05
Had a look, it seems it is not a matter of calling another function there, but the workaround in https://bugs.python.org/issue38633 is about monkey patching the python stdlib. Was applying that patch enough to make it work, or something else?

**Comment by Nekto89** [comment] 2020-04-09 11:12
> 
> 
> Had a look, it seems it is not a matter of calling another function there, but the workaround in https://bugs.python.org/issue38633 is about monkey patching the python stdlib. Was applying that patch enough to make it work, or something else?

I've just copy-pasted workaround to beginning of ~/.local/bin/conan to make it work but it doesn't look like a good idea for production.

**Comment by memsharded** [comment] 2020-04-09 11:23
> I've just copy-pasted workaround to beginning of ~/.local/bin/conan to make it work but it doesn't look like a good idea for production.

Yeah, I wouldn't be very excited about this. But I don't see any other way, it is kind of core Python bug, and needs to be patched. To my understanding that is the best Conan can do, I don't see any other way. So we might declare this as "not-a-bug" in Conan or "non-fix", if the monkey-patch is too much to be included in our production code, and delegate to users to patch their pythons... not sure what to do, honestly.

**Comment by memsharded** [comment] 2024-05-14 14:30
This still doesn't look something that can be fixed on Conan side, closing.

Working directly inside WSL with Conan in non-mounted Windows folders works well, and it is not recommended to share the cache among different platforms either. Conan 2 also has the ``conan cache save/restore`` that could help move the packages from one system to another if necessary.

Closing as not a bug in Conan, but in Python (and seems it might be getting a fix https://github.com/python/cpython/issues/82814#issuecomment-1606813982)

**Closed as not planned by memsharded** 2024-05-14 14:30 UTC
Labels: type: bug, good first issue, stage: queue, priority: medium, complex: medium
