### ISSUE TITLE
[bug] CMakeToolChain.generate + Conan 1.53 changed functionality

### ISSUE THREAD

**Issue by harsszegi** [conan-io/conan#12277] opened 2022-10-10 08:47 UTC
Hi,
after upgrading Conan 1.53 CMakeToolChain.generate functionality appears to be changed.
Suddenly a "CMakeUserPresets.json" file started to appear in the package's source folder, which practically breaks Conan lifecycle, as the .git repo becames dirty, "conan export" doesn't update the "scm" "auto" attributes, and surely it is not possible to do "conan upload" anymore. 

Any suggestion?
Thanks,

**Comment by memsharded** [comment] 2022-10-10 09:00
Hi @harsszegi 

We need details to reproduce this. Please explain how this happen, conanfile.py and commands to reproduce. Thanks!

**Comment by harsszegi** [comment] 2022-10-10 09:39
It's nothing extra actually.

from conans import ConanFile
from conan.tools.cmake import CMakeToolchain

class FooConan(ConanFile):
  name = "foo"

  scm = {
    "type": "git",
    "url": "auto",
    "revision": "auto"
  }

  def generate(self):
    tc = CMakeToolchain(self)
    tc.generate()
    
Add an empty CMakeLists.txt next to the conanfile.py

Then you do a

conan install . -pr xxx -if build

and this will generate the "extra" CMakeUserPresets.json next to conanfile.py + CMakeLists.txt in source_folder

**Comment by memsharded** [comment] 2022-10-10 10:03
The ``CMakePresets`` from ``CMakeToolchain`` might rely on modern features like you probably need to declare ``layout()``, possibly ``cmake_layout``, in order to get the file in a different location

Also, please be aware that the ``scm`` feature is deprecated in Conan 2.0, to be replaced by ``def export()`` method, you can migrate to it already in 1.X to be ready.

**Comment by harsszegi** [comment] 2022-10-10 10:31
presets.py has this in save_cmake_user_presets:

user_presets_path = os.path.join(conanfile.source_folder, "CMakeUserPresets.json")

so unless I'm mistaken it forcefully saves this to the repo of the package.
Btw how come that calling "write_cmake_presets" from CMakeToolchain.generate is not optional? Why is it mandatory to have CMakePresets.json + CMakeUserPresets.json generated automatically?

**Comment by memsharded** [comment] 2022-10-10 11:33
git blame gives me that specific line has been there since ``2022-04-28``, so this is not something new from this release. This was this way since the presets were added some time ago. Having this generated or not would be another discussion, but this file has been generated previously too.

**Comment by harsszegi** [comment] 2022-10-10 11:36
Then something else had to change. I can easily reproduce that if I "python -m pip install conan==1.52.0", then "conan install . -pr xxx -if build" will not produce "CMakeUserPresets.json", then if I do a "python -m pip install --upgrade conan" and redo the same "conan install . -pr xxx -if build" the "CMakeUserPresets.json" file appears in the source folder.

**Comment by harsszegi** [comment] 2022-10-10 11:39
Ooooh cr@p. self.source_folder is None in 1.52, but it is not in 1.53 :(
I'm talking about this line:

if conanfile.source_folder and conanfile.source_folder != conanfile.generators_folder:

in save_cmake_user_presets

**Comment by jcar87** [comment] 2022-10-27 08:51
A `CMakeUserPresets.json` is generated by Conan as that provides handy features when invoking CMake to configure your project, although it requires a recent version of CMake.

The CMake [documentation](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#introduction) specifies that it needs to be next to be in the project's _root_ directory, but also advises that `CMakeUserPresets.json` should be added to `.gitignore`.

**Comment by harsszegi** [comment] 2022-10-27 08:53
I'm not saying that the current behaviour is invalid, I'm just stating that it simply broke compatibility with earlier releases (regardless that the background reason is that "suddenly it just started to work"). Althought I have to state that I don't quite understand why it is a must to generate the user preset, why can't the user decide whether he/she needs this to be generated in the first place.

**Comment by jcar87** [comment] 2022-11-29 11:11
> why can't the user decide whether he/she needs this to be generated in the first place.

Hi @harsszegi  - thanks for your feedback.

As of https://github.com/conan-io/conan/pull/11917, which will be part of the upcoming 1.55 to be released this week, there is a way to suppress the generation of this file:

```
                    def generate(self):
                        t = CMakeToolchain(self)
                        t.user_presets_path = {}
                        t.generate()
```

**Comment by czoido** [comment] 2022-11-29 11:18
Closing this as should be solved by https://github.com/conan-io/conan/pull/11917
Please @harsszegi feel free to reopen in case you have any more questions.

**Closed as completed by czoido** 2022-11-29 11:18 UTC
Labels: stage: triaging

**Comment by harsszegi** [comment] 2022-11-29 11:43
Awesome, thank you very much!
