### ISSUE TITLE
tools.vcvars_command bug ERROR: Invalid setting '15' is not a valid 'settings.compiler.version' value.

### ISSUE THREAD

**Issue by newcools** [conan-io/conan#1197] opened 2017-04-11 03:18 UTC
Not sure how to describe this but when calling tools.vcvars_command

there is a line of code #181 of tools.py like this
        if settings.compiler.version != "15":
            command = ('call "%s../../VC/vcvarsall.bat" %s' % (vs_path, param))

which always cause an error something like this
ERROR: Invalid setting '15' is not a valid 'settings.compiler.version' value.
Possible values are ['10']
Read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-invalid-setting"

i am not an expert in python but I reckon the reason is that 
comparing  settings.compiler.version with a string "15" will always causing an exception

changing the code to this will fix the problem
if settings.compiler.version.**value** != "15":

i don't have permission to submit change so leave it to you guys

**Comment by memsharded** [comment] 2017-04-11 07:56
Thanks very much for reporting. Will try to fix it for next release. In the meantime, you can avoid it by adding "15" to your ``<userhome>/.conan/settings.yml`` Visual Studio versions (in fact, I think that if running latest versions of conan, it should have done a migration of that file and it should be included)

**Comment by memsharded** [comment] 2017-04-11 11:39
Submitted fix, it will be included in next release (but please check the above workaround in the meantime). Finally, I decided to decouple it from the conan model and used ``if env_var != "vs150comntools":``
Cheers!

**Comment by newcools** [comment] 2017-04-11 11:44
Adding 15 to settings won't solve the problem, as a matter of fact, 15 is
there by default. I am very sure it's a bug because underneath it actually
have triggered an exception

**Comment by memsharded** [comment] 2017-04-11 12:05
I think there is something different, I couldn't reproduce the issue here. 
Is it possible that the recipe calling ``vcvars`` is actually constraining the ``settings`` in its attributes?

In any case, yes, you are right it is a bug, a patch is already submitted and will be released in next conan 0.22. Just want to help to find a workaround in the meantime.

**Comment by lasote** [comment] 2017-04-18 07:34
Reading this "http://help.appveyor.com/discussions/kb/48-vs2017" it seems that this command will set the variable, my question is, who tells us where to find the VsDevCmd.bat:

``C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat``

We should take a look.

**Comment by lasote** [comment] 2017-04-18 10:15
I'm moving it to 0.23 to see if we can still improve it a little more.

**Comment by sunxfancy** [comment] 2017-04-25 11:30
@lasote , I am facing this problem, and after changing the image to 2017, VsDevCmd.bat can be used.

```yml
image:
  - Visual Studio 2017
```

The path `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat` is right. However, there is another problem, the vs14 build error.

```yml
conans.errors.ConanException: Error, Visual environment already set to 15
Current settings visual version: 14
```
Here is my [AppVeyor link](https://ci.appveyor.com/project/sunxfancy/conan-dlib/build/1.0.20/job/vseh0ufwrc1p3mgx#L155) , would you like to have a look?

**Comment by lasote** [comment] 2017-05-16 10:30
Yes, you are right, when you set the variables for Visual 15 and conan package tools to reach the Visual 14 builds, it fails for preventing errors. I didn't realize that it will fail, sorry.

We recommend not to call the `VsDevCmd.bat` but manually declare the `VS150COMNTOOLS` variable to your Visual 2017.

**Closed by lasote** 2017-05-16 10:30 UTC
Labels: bug
