### ISSUE TITLE
[question] conan fails to download when python_requires dependency is not on default repo

### ISSUE THREAD

**Issue by daniel88ferreira** [conan-io/conan#9548] opened 2021-09-07 10:29 UTC
Hello,

We are using the python_requires feature in conan 1.30.2 in some of our projects. But we noticed that `conan download` only searches for `python_requires` dependency from default repo (or the specified by `-r`) instead of scanning in all configured. This fails if `python requires` is on a different repo than the original packages -- something that happens a lot in our case.

Currently what we do is: first download the `python_requires` dependency and then download the package we want.

Is this expected behaviour? Is there a plan to make `conan download` able to look in all configured repos (eg: `conan download <ref> -r all`) ?

Thanks!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment] 2021-09-15 11:14
Hi @daniel88ferreira,

Could you please give us more details on your workflow?
`conan download` does not search for dependencies in the graph. It only downloads the package that it receives as argument, so if you have a require of a package, even if that's in the same repo it should not be downloaded. That would happen if you were using a `conan install` command, for example.
If you provide more details on what you are trying to do and how maybe we can help.
Thanks a lot!

**Comment by daniel88ferreira** [comment] 2021-09-15 11:38
Hi @czoido,

So packageA has a [python_requires](https://docs.conan.io/en/latest/extending/python_requires.html#python-requires) dependency on packageB that comes from a different repository.

When I do `conan download packageA`, conan errors out saying that it could not find Package B.

I understand that `conan download` command should only download the requested package (I believe that's what happens with a regular dependency) and, with `python_requires`, I was expecting the same behaviour, but instead conan errors out.

Thanks in advance!

**Comment by czoido** [comment] 2021-09-15 12:28
Hi @daniel88ferreira,
Sorry, you are right, the python_requires are downloaded if found in the server because when you download a package Conan tries to load the conanfile.py and that's not possible if the python_requires are not downloaded. But iterating remotes is not possible with the `conan download` command. Maybe you could try using `conan install`? Like `conan install packageA/1.0@` it should iterate the remotes until it finds the python_requires in another server

**Comment by daniel88ferreira** [comment] 2021-09-15 16:41
hi @czoido,

I can try something with `conan install`, but I think the expectation is that `conan download` behaves the same no matter if the packages are in different repos or not (given that both repos are configured 🙂 )

So, this question is more to get your feedback on whether the current behaviour is intended by design or should there be a fix for it?

Thanks!

**Comment by czoido** [comment] 2021-09-16 07:28
Hi @daniel88ferreira,
I think this is the intended behaviour. We may consider different approaches for Conan 2.0 I don't think it's something that will change for now.
Anyway, I'll add this as something to look into so we can consider this suggestion in the future.
Thanks for the suggestion.

**Comment by memsharded** [comment] 2022-07-09 21:51
Hi @daniel88ferreira 

We have been considering this, and testing if something better was possible in PR #11493, and these are our thoughts:

- ``conan download`` is intended to download exclusively 1 package, from 1 specific repository. It does not download transitive dependencies, and it will not download the package from another repository
- Adding more than one remote to the command, like ``conan download -r=remote1 -r=remote2`` doesn't have clear semantics, will that download the package from the second remote if it cannot find in the first remote? What if the revision is not specified and the latest revision is different in the two remotes?
- Making an exception just for the ``python_requires`` (allowing to be retrieved from any remote, even if not specified in command line) would introduce the opposite problem in ``conan install`` and ``conan create`` commands, users will be surprised by Conan retrieving python-requires from other repositories not specified in the command line. It doesn't sound great to have a different remote.

So we think the only possibility that sounds consistent is forcing to make a ``conan download`` of the ``python_require`` package first if it is necessary. Then, we can close this question as resolved.

In any case, I would recommend reconsidering the approach and not necessarily separating packages based on some functional categorization. Packages are better split in different server repositories based on maturity. If the ``python_requires`` is necessary for that package to be installed, it should live in the same repository as its consumers. When packages are promoted (copied) from one "testing" repo to a "production" repo, for example, the ``python_requires`` should also be promoted together. Most likely the dependencies, have to be promoted too. Recall that doing copies of packages in servers like Artifactory do not use extra storage space, as they implement de-duplication of files.

**Comment by franramirez688** [comment] 2022-07-11 10:07
Closed by https://github.com/conan-io/conan/pull/11493

**Closed as completed by franramirez688** 2022-07-11 10:07 UTC
Labels: type: look into
