### ISSUE TITLE
[question] How to get LOCATION of a cmake target

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan#12300] opened 2022-10-13 07:57 UTC
Hi conan community,

I have an existing project using conan and cmake that I try to migrate to CMakeToolChain+CMakeDeps.
The existing CMakeLists.txt reads LOCATION target property, which was working before but no more works with CMakeToolChain+CMakeDeps.

I reproduce with https://github.com/EstebanDugueperoux2/qt5Example project.
When invoking "conan create . " I get "_target_location: _target_location-NOTFOUND",
while when invoking "cmake ." I get "_target_location: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.12.8"

Do you have an idea of the issue?

Regards.

**Comment by jcar87** [comment] 2022-10-13 14:55
Hi @EstebanDugueperoux2, thanks for raising this issue and providing a reproducible example.


While the new `CMakeToolchain` and `CMakeDeps` generators and the recipes in Conan Center aim to be compatible with the following workflow:
```
find_package(Qt5)
target_link_libraries(xxx Qt5::Widgets)
```

The interface enables the same usage at the target level with `target_link_libraries`, however, the Conan-generated CMake files set up targets differently - they will still result in the correct linker flags being propagated when you link your own libraries or applications, but may not necessarily expose the same properties in the same ways. The Conan-generated files do provide some internal variables that have this information, but I would discourage using them since these are undocumented and the names may change.

However, we would be very interested on the use cases that motivate querying properties of imported targets - if we have a better understanding we may be able to provide assistance with the existing implementation, or add a feature on our end.

**Comment by EstebanDugueperoux2** [comment] 2022-10-13 15:25
Hi @jcar87,

Thanks for your help.
My use case is to install automatically all transitive shared librairies of dependencies aside built target.
We have a generic cmake macro doing that based on target properties.

Regards.

**Comment by jcar87** [comment] 2022-10-17 16:37
Hi @EstebanDugueperoux2, thanks for providing more details.

> install automatically all **transitive** shared librairies 

Interesting use case! I'm familiar with this approach. What I would be interested in learning about, is how do you recursively resolve the transitive dependencies?
That is, if I'm not mistaken, `Qt5::Widgets` also depends on `Qt5::Core`, and perhaps some others (Im not 100% sure) - so while we obviously would need the location of `Qt5::Widgets` if we want to get the transitive shared dependencies of our built target, we would also need the location of every (shared) library `Qt5::Widgets` depends on. How do you resolve that? Or do you simply hardcode the assumption that Widgets also carries a dependency on Core? The reason I'm asking this is because I believe there may be a way in CMake to do this correctly with both the cmake files coming from Qt5, but also the cmake files generated by the `CMakeDeps` generator.

**Comment by EstebanDugueperoux2** [comment] 2022-10-18 08:32
Hi @jcar87,

This is the code snippet to do the staf:

```
# Install the shared library file associated with the given target to the given destination.
# This results in an install command to install the libs to the "runtime" component
# Optionally the COMPONENT parameter followed by the component name may be specified to install
# to a different component
function(target_install_libs tgt destination)
    # Check for the optional COMPONENT function parameter
    set(options "")
    set(oneValueArgs COMPONENT)
    set(multiValueArgs "")
    cmake_parse_arguments(TARGET_INSTALL_LIBS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )
    # Default to the "runtime" component if a custom component not specified
    if (NOT TARGET_INSTALL_LIBS_COMPONENT)
        set(TARGET_INSTALL_LIBS_COMPONENT runtime)
    endif()
    
    get_target_property(_location ${tgt} LOCATION)
    get_filename_component(_realpath ${_location} REALPATH)
    get_filename_component(_extension ${_location} EXT)
    
    if(WIN32)
        # On Windows, the location points to the 'lib' file.
        get_filename_component(_extension ${_location} EXT)
        if("${_extension}" STREQUAL ".dll")
            get_filename_component(_realpath ${_location} REALPATH)
        else()
            get_filename_component(_directory ${_location} DIRECTORY)
            get_filename_component(_lib_root ${_directory} DIRECTORY)
            get_filename_component(_no_ext_path ${_location} NAME_WE)
            if(EXISTS "${_directory}/${_no_ext_path}.dll")
                set(_realpath "${_directory}/${_no_ext_path}.dll")
            elseif(EXISTS "${_lib_root}/bin/${_no_ext_path}.dll")
                set(_realpath "${_lib_root}/bin/${_no_ext_path}.dll")
            else()
                set(_realpath "")
            endif()
        endif()
    endif()
    if("${_realpath}" STREQUAL "" OR "${_extension}" STREQUAL ".a" OR _location MATCHES ".*-NOTFOUND")
        message("${tgt} does not have shared library file: ${_location}")
    else()
        message("asked to install ${location} (${_realpath}) to ${destination}")
        install(FILES ${_realpath}
            DESTINATION ${destination}
            COMPONENT ${TARGET_INSTALL_LIBS_COMPONENT}
        )
    endif()
    if(UNIX)
        install(CODE "execute_process(COMMAND /sbin/ldconfig -n ${CMAKE_INSTALL_PREFIX}/${destination})")
    endif(UNIX)
endfunction(target_install_libs)


# Function to install external dynamic libraries

function(install_shared_libs tgt destination)
    # Check for the optional COMPONENT function parameter
    set(options "")
    set(oneValueArgs COMPONENT)
    set(multiValueArgs "")
    cmake_parse_arguments(INSTALL_SHARED_LIBS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )
    # Default to the "runtime" component if a custom component not specified
    if (NOT INSTALL_SHARED_LIBS_COMPONENT)
        set(INSTALL_SHARED_LIBS_COMPONENT runtime)
    endif()

    message(STATUS "Installing shared libs for ${tgt}")
    get_target_property(_target_libraries ${tgt} INTERFACE_LINK_LIBRARIES)
    message("${tgt}: ${_target_libraries}")
    foreach (_dep ${_target_libraries})
        if(TARGET "${_dep}")
            get_target_property(_type ${_dep} TYPE)
            message("${_dep}: ${_type}")
            if("${_type}" STREQUAL "SHARED_LIBRARY" OR "${_type}" STREQUAL "UNKNOWN_LIBRARY")
                target_install_libs(${_dep} ${destination} COMPONENT ${INSTALL_SHARED_LIBS_COMPONENT})
                install_shared_libs(${_dep} ${destination} COMPONENT ${INSTALL_SHARED_LIBS_COMPONENT})
            else()
                install_shared_libs(${_dep} ${destination} COMPONENT ${INSTALL_SHARED_LIBS_COMPONENT})
            endif()
        endif()
    endforeach(_dep)
endfunction(install_shared_libs)
```

It is mainly based on INTERFACE_LINK_LIBRARIES and LOCATION target properties.

Regards.

**Comment by jpfeuffer** [comment] 2022-10-19 17:20
Related to #12266

I would say it is a very very common use case to access the location of library targets. Especially on Windows you often want to copy them to your build bin folder to make executables work without altering PATHs etc.

**Comment by jpfeuffer** [comment] 2022-10-19 17:27
You will also struggle with the target TYPE which is also not set by conan which has even greater consequences, since CMake internally makes use of the TYPE.

**Comment by jpfeuffer** [comment] 2022-10-19 17:33
https://cmake.org/cmake/help/latest/command/add_library.html#imported-libraries

**Comment by jwillikers** [comment] 2022-12-01 20:04
@jcar87 What @jpfeuffer says is absolutely correct. The `LOCATION` target property of an imported target should point to the DLL library. When both an import library, i.e. `.lib`, and `.dll` are provided, the `.lib` should be set through the `IMPORTED_IMPLIB` target property instead.

I'm attempting to install a DLL using the `LOCATION` target property, but instead of the path to the DLL it is the path to a `.lib` import library provided with the DLL.

**Comment by jcar87** [comment] 2022-12-05 12:36
Related: https://github.com/conan-io/conan/issues/12654

**Comment by johannes-wolf** [comment] 2024-03-03 16:43
Is there any way to work around this issue and get the location of the *.so or *.dll in current Conan + CMake?

**Comment by memsharded** [comment] 2024-03-03 19:54
Conan has the information to ``self.dependencies["mydep"].cpp_info.bindirs``, so it is able to:

- Collect all shared libraries from dependencies, and copy them (see for example this wip https://github.com/conan-io/conan/pull/15382). 
- The access to dependencies and gathering shared libs can be done in recipes in the ``generate()`` method, or externally in ``deployers``
- Conan ``generate()`` can also create any extra files with the information of the ``bindirs`` locations

**Comment by johannes-wolf** [comment] 2024-03-03 20:19
Thank you, but access from the conanfile.py does not help me, because I need to pass a target to a CMake function, which expects it to have a valid `$<TARGET_FILE:...>`. But the Conan generated targets are neither a library nor a binary and therefore have no `TARGET_FILE`, which is a bit annoying.

**Comment by memsharded** [comment] 2024-03-03 21:09
If accessing via CMake is the only way, then following the package targets (that are interface targets), to the internal ``CONAN_LIB::${package_name}_${_LIBRARY_NAME}${config_suffix}`` targets would be the imported libraries. These imported libraries might be unknown, shared or static, depending on different conditions, this is the thing that is pending a new ``CMakeDeps`` integration with new targets definition.

**Comment by memsharded** [comment] 2024-03-04 10:15
> If accessing via CMake is the only way, then following the package targets (that are interface targets), to the internal CONAN_LIB::${package_name}_${_LIBRARY_NAME}${config_suffix} targets would be the imported libraries. These imported libraries might be unknown, shared or static, depending on different conditions, this is the thing that is pending a new CMakeDeps integration with new targets definition.

Just to clarify, this is just a hacky workaround, it wouldn't be a recommended solution for production. Those targets are really undocumented and internal implementation detail, so they might change any time, breaking code that explicitly rely on it.

**Comment by memsharded** [comment] 2024-11-11 22:29
The new ``CMakeDeps`` generator introduced in https://github.com/conan-io/conan/pull/16964 defines the correct LOCATION for targets, in Conan 2.9

It is for dev-testing, behind a ``-c tools.cmake.cmakedeps:new=will_break_next`` flag to activate it and allow to iterate it safely.

I am closing this ticket as solved with it, please give it a try and open new tickets for any further issue or question with the new ``CMakeDeps`` generator. Thanks very much for your feedback.

**Closed as completed by memsharded** 2024-11-11 22:29 UTC
Labels: stage: triaging
