### ISSUE TITLE
[bug] Conan upload times out when package with same name and version number already exists

### ISSUE THREAD

**Issue by skoolkid** [conan-io/conan#10295] opened 2022-01-10 12:48 UTC
### Environment Details
  * Operating System+version: Windows Server 2019 (GitHub runner)
  * Compiler+version: n/a
  * Conan version: 1.44.0
  * Python version: 3.9.9
  * Artifactory version: 7.29.8 (JFrog Cloud)

### Steps to reproduce
  * Build a package with the same name and version number as one that already exists in Artifactory.
  * With revisions NOT enabled, run 'conan upload' to upload the package.
  * Expected: An error message explaining that a package with the same name and version number already exists in Artifactory, and revisions are not enabled.
  * Actual: The 'conan upload' command repeatedly tries to upload files, times out on each one (see logs below), and eventually aborts.

### Logs
Uploading freerdp/2.4.1@X/stable to remote 'Xartifactory'                
Recipe is up to date, upload skipped

Uploading package 1/1: f93997606a45cdf1b9e0562f54590877d83ca354 to 'Xartifactory'       
Compressing package...
Uploading conan_package.tgz -> freerdp/2.4.1@X/stable:f939
ERROR: HTTPSConnectionPool(host='X.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/third-party-conan-local/v1/files/X/freerdp/2.4.1/stable/0/package/f93997606a45cdf1b9e0562f54590877d83ca354/0/conan_package.tgz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='X.jfrog.io', port=443): Read timed out. (read timeout=60.0)"))
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conan_package.tgz, 'HTTPSConnectionPool(host='X.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/third-party-conan-local/v1/files/X/freerdp/2.4.1/stable/0/package/f93997606a45cdf1b9e0562f54590877d83ca354/0/conan_package.tgz (Caused by ReadTimeoutError("HTTPSConnectionPool(host='X.jfrog.io', port=443): Read timed out. (read timeout=60.0)"))'
Uploading conaninfo.txt -> freerdp/2.4.1@X/stable:f939
Uploading conanmanifest.txt -> freerdp/2.4.1@X/stable:f939
ERROR: HTTPSConnectionPool(host='X.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/third-party-conan-local/v1/files/X/freerdp/2.4.1/stable/0/package/f93997606a45cdf1b9e0562f54590877d83ca354/0/conanmanifest.txt (Caused by ReadTimeoutError("HTTPSConnectionPool(host='X.jfrog.io', port=443): Read timed out. (read timeout=60.0)"))
Waiting 5 seconds to retry...
ERROR: 
Error uploading file: conanmanifest.txt, 'HTTPSConnectionPool(host='X.jfrog.io', port=443): Max retries exceeded with url: /artifactory/api/conan/third-party-conan-local/v1/files/X/freerdp/2.4.1/stable/0/package/f93997606a45cdf1b9e0562f54590877d83ca354/0/conanmanifest.txt (Caused by ReadTimeoutError("HTTPSConnectionPool(host='X.jfrog.io', port=443): Read timed out. (read timeout=60.0)"))'
ERROR: freerdp/2.4.1@X/stable:f93997606a45cdf1b9e0562f54590877d83ca354: Upload package to 'Xartifactory' failed: Execute upload again to retry upload the failed files: conan_package.tgz, conanmanifest.txt. [Remote: Xartifactory]

**Comment by memsharded** [comment] 2022-01-10 13:52
I have just tested to do this upload against an Artifactory instance in the cloud, with revisions disabled, and I am perfectly able to overwrite existing artifacts (with same name and version), no timeouts.

I think this is not a Conan client bug, but some issue with the current permissions configuration in your server. If you want to be able to overwrite an existing artifact in the server, overwrite permissions (delete) are required. If you have removed some permissions, this might happen.

**Comment by skoolkid** [comment] 2022-01-10 13:58
Yeah, I wasn't sure whether this was a conan issue or an Artifactory issue.

In any case, if the conan user doesn't have delete/overwrite permission, shouldn't there be an error message stating that, instead of a timeout that gives no clue as to what's going wrong?

**Comment by memsharded** [comment] 2022-01-10 17:57
> In any case, if the conan user doesn't have delete/overwrite permission, shouldn't there be an error message stating that, instead of a timeout that gives no clue as to what's going wrong?

That depends on how the server decides to respond, and I think this can be also configured in the server. (from Conan this is not a bug, there is nothing in the client side we can do to change a server timeout). A typical security configuration, up to my knowledge, is to not respond (for POST/PUT operations) or respond 404 on resources that do not exist (for GET operations, that might not be good for uploads). This way, possible attackers don't know if they are accessing a valid resource, just lacking credentials, or if it is an invalid resource.

**Comment by skoolkid** [comment] 2022-01-10 18:29
OK, thanks. I will see if I can get someone to look at our Artifactory server configuration.

**Comment by skoolkid** [comment] 2022-01-12 19:15
Just got confirmation that the conan user I'm using does not have DELETE permission, which means 'conan upload' is doomed to fail in this situation. I'll look into logging a bug with JFrog about the inappropriate timeout error triggered by Artifactory.

Thanks for your help!

**Comment by memsharded** [comment] 2022-01-13 09:04
Great, I think we can close this ticket then, as not something in the Conan client.

>  I'll look into logging a bug with JFrog about the inappropriate timeout error triggered by Artifactory.

Sure, but there is a possibility they might say this is a security policy, when there are not enough permissions, it is more safe to not respond (or do 404 for GET requests, which is not the case for the upload), than responding something that evidences that there is a real resource there. Interested in knowing their response, if you recall to comment here if they respond, that would be appreciated. Many thanks!

**Closed as completed by memsharded** 2022-01-13 09:04 UTC
Labels: stage: triaging

**Comment by skoolkid** [comment] 2022-01-13 12:24
> Interested in knowing their response, if you recall to comment here if they respond, that would be appreciated.

I'll try to remember! In contrast to 'conan upload', when I use 'jfrog rt docker-push' to push a docker image to a folder in the same Artifactory instance for which my user does not have DELETE permission, I get an appropriate error message:

unauthorized: The client does not have permission for manifest: Not enough permissions to delete/overwrite artifact 'eng-docker-dev-local:app/oraclelinux7/latest/manifest.json' (user: 'token:token:github-actions-builder' needs DELETE permission).

So perhaps this has something to do with Artifactory's handling of the conan repository in particular.
