### ISSUE TITLE
Profiles composition is calculated incorrectly (chaotic/incomplete settings calculation)

### ISSUE THREAD

**Issue by ezaiakinsc** [conan-io/conan#5141] opened 2019-05-15 01:16 UTC
It looks like problem does not depend on conan version, both 1.14 and 1.15 misbehaving same way here. Sorry for long example: I had shorter ones days ago, but deleted them, since conan failed with such a profile composition, and I was in a hurry.

Conan breaks settings in case of non-trivial profile composition with include(), for example, let's imagine such a (working) layout of profiles:
profile: droid32 (one we are using as "leaf element", so fully usable profile)
```
include(android/ndk-r18b)
include(android/gradle/arch_selector_armeabi-v7a)
```
profile: android/ndk-r18b (infrastructure one)
```
# ndk r18b profile
include(default)
include(android/settings-only-ndk-r18b)

[build_requires]
nlo-android-toolchain/r18b@xxx/stable
```
profile: android/settings-only-ndk-r18b  (infrastructure one)
```
[settings]
os=Android
os.link_libcxx=static
compiler=clang
compiler.version=7.0
compiler.libcxx=libc++
```
profile: android/gradle/arch_selector_armeabi-v7a  (infrastructure one)
```
[settings]
os.api_level=19
arch=armv7
```
This example still works as expected: when using profile "droid32", default profile seems to be applied first, then "android/ndk-r18b" includes "android/settings-only-ndk-r18b" and switches target os to Android. Finally "android/gradle/arch_selector_armeabi-v7a" is able to set os.api_level, since conan knows, os is already Android.

Now, lets make a minor change: let's include "default" profile directly in "droid32" profile:
```
include(default)
include(android/ndk-r18b)
include(android/gradle/arch_selector_armeabi-v7a)
```
and remove that line from "android/ndk-r18b" profile
```
include(android/settings-only-ndk-r18b)

[build_requires]
nlo-android-toolchain/r18b@xxx/stable
```
Note: we have not changed order: we expect default profile to be applied first (because it is 1st line in droid32 profile, then we expected "android/settings-only-ndk-r18b" to switch platform to Android and so on. Unfortunately, conan goes crazy:
```
ERROR: 'settings.os.api_level' doesn't exist for 'Macos'
'settings.os' possible configurations are ['version']
```
So, apparently conan's settings calculation order depends on some chaotic factors. We've seen even more weird results with inlcluded profiles, for example, sometime arch_build becomes undefined etc.

Overall settings application order seems to be unreliable right now. I also found no unit-tests checking complex profiles compositions using inlcude(), so cannot even validate if we did something wrong to get chaotic results.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment] 2019-05-16 07:08
Hi @ezaiakinsc, I'm trying to reproduce your reported behavior in a test, have a look at https://github.com/jgsogo/conan/commit/dcd4c98a7c37e12bd25e7c50b060c7a233bad510, but I'm not able to reproduce the failure.

Check the `droid32` profile with the `include(defaut)` in first place:

```
        save(os.path.join(self.cache.profiles_path, "droid32"),
             textwrap.dedent("""
                include(default)
                include(android/ndk-r18b)
                include(android/gradle/arch_selector_armeabi-v7a)
             """))
```

Can you help me to reproduce the issue? If the profile composition is not working as expected it would be a bug.

Thanks!

**Comment by ezaiakinsc** [comment] 2019-05-16 22:33
Hi @jgsogo - I do understand your issues with reproducibility of this one, for us it's also chaotic. 

I am not sure I got where exactly can I put this "save(" code snippet you've presented - it can be used only in unit testing, right? Nothing I can run immediately on a system where settings calculation just failed?  

Some updates: it looks like "chaos" factor might be affected by file name as well. We got 2 profiles, that are almost 100% identical - droid32 and droid64, and they differ only by last line: droid32 uses include(android/gradle/arch_selector_armeabi-v7a) subprofile, and droid64 uses include(android/gradle/arch_selector_arm64-v8a) subprofile. Everything else it the same, but today droid32 profile resulted this error twice:
`ERROR: nlo-cmake-installer/3.14.1@xxx/stable: 'settings.arch_build' value not defined`. 

Unfortunately, right now I cannot reproduce it on the same computer, so the only thing I can imagine - maybe during calculation of the complex profile setttings, some kind of unordered python container is used (dict? set?). Those can demonstrate "kinda stable" behavior for some data sets on some python versions, but aren't really stable. 

I will try to find/recall profile combination, that glitches more often than my first example, and will text it here, but cannot promise exact timing, very sorry.

**Comment by jgsogo** [comment] 2019-05-17 08:51
Yes, the snippet I share with you (and the linked commit) are unittests trying to reproduce the behavior you reported.

All the code related to profile parsing is in the [`conans/client/profile_loader.py` file](https://github.com/conan-io/conan/blob/develop/conans/client/profile_loader.py), and I think there are no problems with inconsistent ordering:
 1. Profiles are read line by line: data is stored in an `OrderedDict` and includes are appended to a list.
 2. Includes are parsed in order from the list (recursively) and the data is `updated`.

I would really like to reproduce the error, it would be a real bug and something to fix asap.

Thanks!

**Comment by memsharded** [comment] 2024-04-12 12:49
Closing as staled.

**Closed by memsharded** 2024-04-12 12:49 UTC
Labels: stage: triaging
