### ISSUE TITLE
[question] conan graph solver algorithm

### ISSUE THREAD

**Issue by sin-diesel** [conan-io/conan#14741] opened 2023-09-14 20:27 UTC
### What is your question?

Hello! I am currently interested in understanding how conan graph solver works. I searched the source code a few times to get a proper understanding of it, but so far was unable to figure it out and find the responsible code. In particular I searched `conans/client/graph` folder. I know that deep explanation requires a lot of effort (but still is very appreciated). I suppose I need some sort of a brief review of conan's solver and some code snippets/locations where I can dig deeper and find out more about how solver behaves and which algorithm it uses. Thanks in advance!

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-09-14 21:45
Hi @sin-diesel 

Thanks for your question.
I am afraid that from the solver algorithm point of view, Conan is not that interesting for research purposes.
The algorithm is pretty simple, it contains version-ranges resolution but not a full sat-solver, because most of the complexities of the problem is around the model of C++ dependencies (like shared, static, header-only libraries), and how they propagate in the graph, and how they are applied later to different build systems like MSBuild, CMake, Meson, Autotools, etc. There are often conditional dependencies, and modifications of recipes for packages also create internal versions that would be the combinatoric explosion intractable in practice.

**Comment by sin-diesel** [comment] 2023-09-14 21:52
Thanks for your answer! I was wondering if there is any field for conan's simple solver optimization, I would be glad to participate in contributing to the project, and this would greatly help me finish the algorithms course in my university. What do you think?

**Comment by memsharded** [comment] 2023-09-14 22:57
The bottleneck in Conan graph resolution is not the algorithm per-se, but that for evaluating every hypothesis/node (every unique recipe-revision) in the graph it is necessary:
- To download the conanfile.py + conan_export.tgz files from server
- Unzip conan_export.tgz, extract conandata.yml file
- Parse both ``conanfile.py`` and ``conandata.yml``
- Evaluate the ``conanfile.py``, injecting its settings, options, conf, then evaluate the ``requirements()`` and ``build_requirements()``

In practice that means a few seconds for each one. Given that a single recipe can have multiple revisions (and it is very common that they have multiple revisions), and every recipe revision will easily have different dependencies versions, because they have been bumped over time, and also even new conditionals, new optional dependencies, etc., the search space becomes quickly intractable. 

There are also other practical SW engineering issues, like for example, anything that involves modifying the server side can easily take many months, might need to version the APIs, etc, it can be a major engineering effort that span over more than one year, as there are also multiple vendors providing Conan servers, so this has to be slow.

I am afraid that we have at this moment tons of higher priorities, if you check the conan-center-index repo, more than 5000 PRs are processed there per-year, and now there are more than 500 open PRs, mostly for the Conan 1.X -> 2.0 migration. Future optimizations involved the ``compatibility.py`` plugin speed resolution, or making the Conan cache concurrent, that now it is not. These things will have at this moment way more impact on Conan users than improvements in the algorithm.

**Comment by memsharded** [comment] 2023-11-05 16:35
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.

**Closed as completed by memsharded** 2023-11-05 16:35 UTC
Labels: type: question
