### ISSUE TITLE
[feature] Streamline using system dependencies in package

### ISSUE THREAD

**Issue by stevenwdv** [conan-io/conan#15321] opened 2023-12-21 11:17 UTC
### What is your suggestion?

This issue builds on #1330.

**Situation:** Our package requires [`sqlite_orm`](https://conan.io/center/recipes/sqlite_orm), which has `sqlite3` as dependency, but I want that one to be installed via my system package manager (e.g. apt) where possible (not on Windows). (Another example is my package requiring zlib while a dependency also, does, which means that I cannot install it via apt because then it would be installed both via apt and via Conan center.)

**Potential current solution:** (since Conan v2.0.15)
- Write a wrapper recipe with `Apt(self).install('libsqlite3-dev')`
- Execute `conan create` on this
- Add a `[replace_requires]` (#15136) to my Conan profile for e.g. `sqlite3/*: sqlite3/*@mine`

**Problem:** This involves a lot more steps and maintenance than I would like, and requires changes in the profile. I understand the reason for a wrapper recipe, because in some cases package options could be interpreted to install the right system dependencies, but it makes it almost impossible to use system dependencies, as wrapper recipes would need to be created, maintained, loaded by Conan, and added to the profile, for all such dependencies. Alternatively, some community repository of wrapper packages supporting the options of the original package could be maintained.

I think there ought to be simpler way to do this, maybe to just directly specify the apt packages that I want to substitute. I think it would also be useful to be able to specify for which packages I want to use system dependencies in package conanfile instead of per profile, although I see why it is useful to be able to specify it in the profile as well. (I this case, the package is not a library but just executables.)

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-12-21 12:10
Hi @stevenwdv 

Thanks for your suggestion.
The way this ``[replace_requires]`` feature is designed is in conjunction with the ``[platform_requires]`` feature:

- If you want a full replacement of a dependency by a system one, but without needing to write your own ``conanfile.py`` to replace it, then you should use the ``[platform_requires]`` feature, and it will do exactly that
- If you don't want a full replacement of a dependency by a system one, but you want to add extra logic, like automating the installation of the system one (with ``system_requirements()`` method), or defining some information for the consumer via ``package_info()``, then the ``[replace_requires]`` is the intended one
- You can use both together, you can first ``[replace_requires]`` to force some dependencies to change their requirement, then use a ``[platform_requires]`` to define that such replacements are not in a Conan recipe but directly in the system, without requiring extra recipe.

What is not considered as a possible feature is try to automate internally the installation of system packages based on system-package names, as the ``system_requirements()`` method is doing. There is simply too much of variability and possible customization there, that would end in a complicated profile custom syntax to poorly implement what is already possible and elegant in a ``conanfile.py``.

So please have a look to ``[platform_requires]`` and let us know.

**Comment by stevenwdv** [comment] 2023-12-21 12:20
Hi @memsharded, thanks for responding!

Is it possible to use the `[platform_requires]` approach to make sure packages are not installed from Conan center, but to also still install the corresponding system packages via e.g. apt like with `system_requirements()` (I understand that I would have to specify which system package(s) correspond to the Conan package for the specified package options), or at least check that these packages are installed?

Ideally I would just `conan build ./ --build=missing` on our package and it would just fetch everything that is necessary (ideally without specifying packages in the profile).

**Comment by memsharded** [comment] 2023-12-21 12:32
> Is it possible to use the [platform_requires] approach to make sure packages are not installed from Conan center, 

``[platform_requires]`` forces requirements satisfied by that system version to use the system dependency. But it will not install anything, it assumes the package is already installed in the system.

> to also still install the corresponding system packages via e.g. apt like with system_requirements() (I understand that I would have to specify which system package(s) correspond to the Conan package for the specified package options), or at least check that these packages are installed?

This is exactly the problem that is solved by writing your ``conanfile.py`` and using ``[replace_requires]``. At the end of the day this logic needs to be somewhere, it requires full Python syntax to be able to represent the high variability in system requirements. Trying to move this logic to just a profile + builtin inside Conan will not work, it will be poor and problematic for both users and maintainers.

> Ideally I would just conan build ./ --build=missing on our package and it would just fetch everything that is necessary (ideally without specifying packages in the profile).

I am a bit confused. It seems that you don't want to create conanfile for the replacements, but also don't want to define anything in the profile. I am not sure how Conan would be able to implement this 😅 . Probably you want just some good-old recipes with conditional requirements like ``if self.settings.os.distro="raspberrypi": self.requires(...``

**Comment by stevenwdv** [comment] 2023-12-21 12:45
@memsharded I guess that what I'm requesting could be in its simplest form a way to replace Conan packages by system packages in my package conanfile.py, where I specify that `sqlite3` should be replaced by `libsqlite3-dev` for apt, for example, without modifying the profile or creating extra wrapper packages.

**Comment by memsharded** [comment] 2023-12-21 12:52
> I guess that what I'm requesting could be in its simplest form a way to replace Conan packages by system packages in my package conanfile.py, where I specify that sqlite3 should be replaced by libsqlite3-dev for apt, for example, without modifying the profile or creating extra wrapper packages.

What would be the condition to decide to replace the Conan packages by system packages?

**Comment by stevenwdv** [comment] 2023-12-21 12:57
@memsharded I thought either something like `os == linux` or (maybe better actually) detecting that the package manager (or even indicated system package(s)) is available for the system.

Note that this would be less useful for library packages, more for executable packages.

**Comment by memsharded** [comment] 2023-12-21 13:07
> I thought either something like os == linux 

Using a condition:
```python
def requirements(self):
    if self.settings.os != "Linux":
          self.requires("sqlite3...)

def system_requirements(self):
    Apt(self).install("sqlite3-dev")  # only executes in Linux
```
This way you can basically achieve what you want?

> (maybe better actually) detecting that the package manager (or even indicated system package(s)) is available for the system.

We have experience with this approach, and it is strongly discouraged. Conan will not do it. You can see that Conan 2.0 has also become more "imperative". The user should decide what needs to be done, and then Conan will do it or fail. Having this kind of trying to be smart decisions based on system auto-detection are very problematic, painful to debug, will come and bite in the worst moment. An anti-pattern in our experience.

Isn't the above what you are looking for? I am still a bit confused about the use case.

**Comment by stevenwdv** [comment] 2023-12-21 13:56
Thanks for thinking along!

> This way you can basically achieve what you want?
I don't think so, because this only works for direct dependencies and does not impact transitive dependencies (e.g. `sqlite_orm` -> `sqlite3`, as mentioned).

> We have experience with this approach, and it is strongly discouraged. Conan will not do it.
I see. I can understand this but specifying a lot of things manually also takes effort. Btw, Conan already only uses the package manager of the system for `system_requirements()`, right?

An alternative would be a script that installs apt packages in our CI, passing a profile to Conan with `[platform_requires]`, and hoping that all dependencies are indeed installed and consistent. Or we could drop apt altogether and use Conan center for everything, bundling all dependencies in the executables (resulting in larger executables and longer build times).

**Comment by memsharded** [comment] 2023-12-21 14:23
> An alternative would be a script that installs apt packages in our CI, passing a profile to Conan with [platform_requires], and hoping that all dependencies are indeed installed and consistent. Or we could drop apt altogether and use Conan center for everything, bundling all dependencies in the executables (resulting in larger executables and longer build times).

You might be able to leverage the Conan 2.0 ``profile.py`` plugin, that could at least check if the ``plaform_requires`` you are defining are installed in the system or not.

> An alternative would be a script that installs apt packages in our CI

Overall, I think that if I had to do it, I'll probably go with creating my own ``conanfile.py`` recipes that model and encapsulate that. They are like easier to maintain, more evident to the different users to debug, change or fix them, can enjoy some testing, are nicely represented in the dependency graph, etc. Not saying that they require high maintenance, typically the opposite. Because having a script that does that means:
- Where the script lives
- How developers get access to that script
- What is the interface to call it, arguments, etc
- How it models variability over different distros or OSs
Which looks a lot of repeating things that Conan already manage automatically


If still a script that does something is desired, then I'd recommend the Conan custom commands framework, which makes them very easy to create, distribute (via ``conan config install``), etc.

**Comment by stevenwdv** [comment] 2023-12-22 09:00
Thanks for the info! I didn't know about profile.py or custom commands.

So to be clear, you don't see a use in something like the following?

```py
def requirements(self):
    self.requires('sqlite_orm/[^1.8.2]')
def system_requirements(self):
    # Replace (transitive) dependencies if apt is the system package manager
    Apt(self).replace('sqlite3/*', ['libsqlite3-dev'])
```

I think this could actually nicely fix the problem that https://github.com/conan-io/conan/issues/15321#issuecomment-1866213529 has with transitive dependencies.

**Comment by memsharded** [comment] 2023-12-22 09:50
> So to be clear, you don't see a use in something like the following?
> Apt(self).replace('sqlite3/*', ['libsqlite3-dev'])

But can't you implement this already? Something like:
```python
def requirements(self):
    if Apt(self)._active_tool != "apt":
         self.requires('sqlite_orm/[^1.8.2]')

def system_requirements(self):
    Apt(self).install(['libsqlite3-dev'])
```

Maybe this solves the issue? The idea is to condition the requirement to the existence/activation of ``apt``, isn't this the behavior you intend? The interface now is not public, but it would be quite easy to make something public if that helps.

**Comment by stevenwdv** [comment] 2023-12-22 12:19
@memsharded Wait, maybe I'm misunderstanding. Doesn't `sqlite_orm` having `sqlite3` is dependency mean that on Linux (with apt) *both* the Conan center `sqlite3` and apt's `libsqlite3-dev` will be downloaded?

**Comment by memsharded** [comment] 2023-12-22 12:42
> Doesn't sqlite_orm having sqlite3 is dependency mean that on Linux (with apt) both the Conan center sqlite3 and apt's libsqlite3-dev will be downloaded?

Not sure what you mean. If the ``requirements()`` method detects that ``apt`` is enabled/active in the current system, then it will not require at all ``sqlite_orm`` or any of its transitive dependencies. They will simply not be part of the dependency graph, and the current package recipe should be able to use the dependency directly from the system (as installed by ``system_requirements()``. Isn't this the logic that you want?

**Comment by stevenwdv** [comment] 2023-12-22 13:57
Ah, but I do need `sqlite_orm` (it's a OOP-based header-only wrapper around sqlite3), but would like it to use the system's `libsqlite3-dev` where possible. So then the transitive dependency `sqlite3` would be replaced by `libsqlite3-dev` and installed by apt, while `sqlite_orm` is still fetched from Conan center.

**Comment by memsharded** [comment] 2023-12-22 14:05
> Ah, but I do need sqlite_orm (it's a OOP-based header-only wrapper around sqlite3), but would like it to use the system's libsqlite3-dev where possible. So then the transitive dependency sqlite3 would be replaced by libsqlite3-dev and installed by apt, while sqlite_orm is still fetched from Conan center.

Then it seems you want to move the logic to the ``sqlite_orm`` package, like, and conditioning the ``requires`` to ``sqlite3``:
```python
def requirements(self):
    if Apt(self)._active_tool != "apt":
         self.requires('sqlite3/[^1.8.2]')

def system_requirements(self):
    Apt(self).install(['libsqlite3-dev'])
````
So, you always require ``sqlite_orm``, and that package will decide to use the system ``libsqlite3-dev`` if ``apt`` is in the system or the Conan ``sqlite3`` package if not. Is this correct?

**Comment by stevenwdv** [comment] 2023-12-22 14:11
That would work in theory, but I don't own the `sqlite_orm` package, since it is part of Conan center: https://conan.io/center/recipes/sqlite_orm. (Btw: `sqlite_orm` is not the only case, just an example. E.g. many packages specify `zlib` as dependency, which could also be installed via apt.)

**Comment by memsharded** [comment] 2023-12-22 14:36
I see.  Then I think these would be different possible approaches:

- https://docs.conan.io/2/devops/using_conancenter.html, taking ownership of your fork of conancenter, to customize things at will, and implement the above conditional requirements.
- Manage yourself the installation of ``libsqlite3-dev`` when you want, and use ``[platform_requires]`` over the ``sqlite3`` package when desired
- Use a replacement recipe for ``sqlite3`` package that contains the ``system_requirements()`` with the ``Apt().install()`` for automation, and rely on ``[replace_requires]`` to replace and inject it.

I don't think there could be a better way, because the main thing is that this logic cannot be hardcoded or builtin inside Conan, because we know it doesn't work. If the upstream ConanCenter recipes cannot be modified to customize that, then it is necessary to define the logic somewhere, and leveraging the existing ``conanfile.py`` with ``system_requirements()`` is already a much better approach than any other possible "magic" we could try to invent for this purpose.

If the cause is that ConanCenter recipes cannot be customized for this specific use case, then working with a fork of ConanCenter would be the solution, but that is also typically a larger investment (not saying that it doesn't pay off, it is typically a very good and recommended investment for production). But these new features ``[replace_requires]`` and ``[platform_requires]`` were designed so this is not necessary, at the cost of having to maintain a very simple ``conanfile``, that is typically just a few lines long and doesn't require much maintenance. I'd recommend giving this approach a try.

**Comment by stevenwdv** [comment] 2023-12-22 14:44
> I don't think there could be a better way

But what about integrating `[replace_requires]`-with-apt-package-wrapper as `Apt.replace` in the bottom consuming conanfile like I proposed above (https://github.com/conan-io/conan/issues/15321#issuecomment-1867422078)? That would require no modifications or voo-doo in existing packages and would avoid profile modifications, wrapper recipes, and extra `conan create` calls.

**Comment by stevenwdv** [comment] 2024-01-17 10:27
Hey, sorry for bumping this, hope you had a good new year's!
Do you get what I'm proposing (see last comment)? To be clear, this would apply only to packages which are not intended to be published (e.g. no libraries). If you do get it but are really against it then I think that is unfortunate but feel free to close the issue as _not planned_.

**Comment by memsharded** [comment] 2024-01-17 11:04
> Hey, sorry for bumping this, hope you had a good new year's!

Happy new year to you too! 🙂 

> Do you get what I'm proposing (see last comment)? To be clear, this would apply only to packages which are not intended to be published (e.g. no libraries). If you do get it but are really against it then I think that is unfortunate but feel free to close the issue as not planned.

Yes, I am afraid that this is a no-go, even if the packages are not to be published in ConanCenter, that is not the issue at all, let me elaborate a bit on your previous comment: 

> But what about integrating [replace_requires]-with-apt-package-wrapper as Apt.replace in the bottom consuming conanfile like I proposed above (https://github.com/conan-io/conan/issues/15321#issuecomment-1867422078)? That would require no modifications or voo-doo in existing packages and would avoid profile modifications, wrapper recipes, and extra conan create calls.

This is what seems convenient and a good idea for users, but really kill us as maintainers. Trying to embed this kind of smart functionality in Conan codebase as built-in ends up with a myriad of follow up issues, feature requests, bug reports, variants, etc. Because there are quite a bunch of different cases, and we know it even from the explicit ``Apt()`` and others system wrappers usage.

The problem is trying to make Conan codebase to maintain mappings between package names and distros packages. It is mostly a mapping between many hundreds of Conan/library names and the equivalent distro packages, which is not always straightforward. And of course, things doesn't end in ``Apt``, as there are users that will want their mappings for other distros package managers. And then we factor cross-building and other architecture packages, some of them can have alternative versions... this is too much to be in the Conan codebase, the only way this can be managed is with customized wrapper recipes by the users, which would be just a couple of lines for them, easy to maintain and evolve.

I am closing as not planned, thanks very much for the feedback!

**Closed as not planned by memsharded** 2024-01-17 11:04 UTC

**Comment by stevenwdv** [comment] 2024-01-17 11:08
Hi! Sorry, just to be clear, I didn't mean that Conan would have to maintain these mappings, I could do this myself in the proposed `Apt.replace`, like this: `Apt.replace('conan-package', ['apt-package'])`, but yeah maybe there would be other issues that would follow.

**Comment by memsharded** [comment] 2024-01-17 11:18
Ok, yes, that makes more sense.

Still, Conan would need to "invent" a new syntax that allows to specify the mappings between different packages and their distro equivalents: this mapping:
- Should probably allow conditionals: ``if this architecture => use better this other package``
- Should probably support multiple versions alternatives ``for distro>xxx need to use apt-package1, else use apt-package2``
- Should support different distros package managers
- Should support mappings between conan package versions and apt versions (``if conan pkg version > xxx => apt-packageY``)
- The mapping itself should be versioned, as it evolves with projects too

As you can see this might quickly evolve in a complicated syntax, will require conditionals, maybe some mechanisms like dictionaries, etc, so most likely it should be Python. This is where we know that something that looks simple in the surface like ``Apt.replace('conan-package', ['apt-package'])`` will quickly evolve into something way more complicated to support, maintain and evolve. At this point is when we see ``conanfile.py`` recipes the best mechanism to support this, well known, documented, supported, allows all the above, etc.

**Comment by stevenwdv** [comment] 2024-01-17 15:12
Ah I see, thanks for your reasoning.
