### ISSUE TITLE
Provide mechanism to add custom project variables into generated conanbuildinfo.* file

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#1100] opened 2017-03-14 00:13 UTC
I did not find how to pass a custom project variable into the generated conanbuildinfo.* file.

I have a library that builds DLLs with a suffix (based on version and some other info) like 'file_1_22xyz.dll'.
It will be handy to define in a conanfile.py some variables that will be passed into a 'conanbuildinfo'. For instance:
```
# conanfile.py
class MyLibConan(ConanFile):
    def package_info(self):
        self.project_info.vars = [ 'MYLIB_SUFFIX=1_22xyz' ]

# conanbuildinfo.pri
MYLIB_SUFFIX = 1_22xyz
```

**Comment by lasote** [comment] 2017-03-14 08:12
Hi @DmitrySokolov,

The library name should be declared in the `cpp_info.libs` list directly:

```
def package_info(self):
    self.cpp_info.libs = ["file_1_22xyz"]
```

Why is it handy to define the prefix in a variable? Please elaborate the idea to know if I'm missing something.

**Comment by memsharded** [comment] 2017-03-14 08:24
The problem with "generic" variables is that they require the consumer to know specific details, and not all build_systems can deal with it. For example, how would you use such lib suffix variable in the ``visual_studio`` generator?

If the problem is that you have many libraries and it is annoying to add the prefix to all of them, just do it in code:

```def package_info(self):
      ... # definition of self.cpp_info.libs wo suffix
      suffix = "1_22xyz"
      self.cpp_info.libs = [ lib + suffix for lib in self.cpp_info.libs]
```

**Comment by DmitrySokolov** [comment] 2017-03-14 13:30
I need to know DLLs suffix on the project level to include them into the deployment script. I can not use a file mask like `*.dll` because not all DLLs are deployed.

There is no problem to include `file_1_22xyz.lib` into `self.cpp_info.libs`, I just do so. But DLLs do not participate in the link stage.

Visual Studio allows to use custom project variables:
```xml
<!-- Project.vcxproj -->
<Project ...>

  <PropertyGroup Label="UserMacros">
    <LibXVersion>1_22xyz</LibXVersion>
  </PropertyGroup>

  <PostBuildEvent>
    <Command>call copyDLLs.cmd "file_$(LibXVersion).dll" ...</Command>
  </PostBuildEvent>
</Project>
```

The only workaround I found (I think it will work):
```python
# conanfile.py
class MyLibConan(ConanFile):
    export = 'package_vars.pri', 'package_vars.props', ...

    def build(self):
        # create package_vars.* here and fill in
```

**Comment by DmitrySokolov** [comment] 2017-03-14 13:35
conan uses `short_paths` flag only for Windows, so I see no problem to use project variables only for generators that support it.

**Comment by memsharded** [comment] 2017-03-14 14:02
I think the issue might be that we are not understanding the full picture. It seems that there is a different use case that what we are thinking, more related to deploy than to building. As it is designed, ``cpp_info`` is intended for C/C++ build information, but as you said, this is information just for the DLLs, and that sounds weird.

Have you check the environment info? http://docs.conan.io/en/latest/howtos/migrate_to_new_environment_management.html

You can define you own custom variables in any package, and they will be translated to their own files, so typically they can be used at runtime, like adding to the PATH.

Maybe this gives some hint. Otherwise, if you could explain a bit further what is your deployment script and flow, we might think about possible solutions. Indeed what you are suggesting about generating your own file with vars is possible.
Indeed what you are suggesting about generating your own file with vars is possible.

**Comment by DmitrySokolov** [comment] 2017-03-14 15:24
Taken from http://docs.conan.io/en/latest/integrations/qmake.html
```qmake
# conanbuildinfo.pri
CONAN_INCLUDEPATH += /home/username/.conan/data/Catch/1.3.2/maintainer/master/package/0692fb2bd888ba708ca65670557c56d2e16851ed/include \
    /home/username/.conan/data/hellolibrary/0.1/maintainer/master/package/0692fb2bd888ba708ca65670557c56d2e16851ed/include
...
CONAN_INCLUDEPATH_xxx += ...
```

`CONAN_INCLUDEPATH` is a project variable (in terms of qmake). It is generated from `self.cpp_info.includedirs` of all libraries in `requires`. Besides, for each library in `requires` a project variable `CONAN_INCLUDEPATH_xxx` is generated.
So, I can use either `CONAN_INCLUDEPATH` to get all libraries include dirs or `CONAN_INCLUDEPATH_xxx` to get a separate library includes.

What I want is to generate somehow `CONAN_xxx_MY_CUSTOM_VAR` for each library in `requires`.
A conan package when it is consumed provides `CONAN_DEFINES` - a list of variables (macros) that is intended for a compiler. But there is no such list of variables that is intended for a build tool (make, qmake, msbuild, ninja, etc.)

Using `env_info` is not handy at all. As I understand, I need to
1. create `conanfile.txt` with `qmake` generator
2. install package `conan install`
3. create `conanfile.txt` with `virtualenv` generator
4. install? again to get activate/deactivate script
5. run activate script to get env vars from a package
6. run QtCreator to build an app

steps 5-6 should be performed for each working session.

Compare to
1. create `conanfile.txt` with `qmake` generator
2. install package `conan install`
3. run QtCreator

**Comment by memsharded** [comment] 2017-03-14 15:52
You can add many generators:

```
[generators]
qmake
virtualenv
````

Also in conanfile.py:
```python
     generators = "cmake", "qmake", "virtualenv"
```

You can also specify them at command line:
```bash
$ conan install . -g cmake -g qmake -g virtualenv
```

This release a new ``virtualrunenv`` generator will be added to add all "bin" dirs to the PATH, so it is not necessary to ``imports`` dlls to user space to run apps.

The workflow would be more like:

1. create ``conanfile.txt`` with ``qmake`` and ``virtualrunenv`` generator (or without and specify in command line)
2. install package ``conan install``
3. activate_run.bat
4. run QtCreator

From my point of view, this flow would be much more convenient that having my build system having a variable for the suffix, then my build system having to compose it to the library names to get the real names, and then apply it to the PATH, or load them. Actually, as they are in runtime, I am not fully sure why the specific library names is required. This is the step that I am missing from the picture, how do you finally consume those DLLs.

To be clear, I am not opposed to having such variables "per se", I just want to make sure that I fully understand the use case, so conan can provide the more general and wide solution to the issue.

**Comment by DmitrySokolov** [comment] 2017-03-14 18:07
I have a project file (no matters qmake's `.pro`, msbuild's `.vcxproj`, etc.). A project can be configured by running `configure --no-make-xxx`, or by editing `config.pri` (`config.props`, etc.) file. So a project file contains the complete information about what features of an app will be turned on during the compile stage, what libraries will be an app linked with (and so what DLLs will be used in run time). Since a project file already contains the final list of used features and DLLs, it can pass all this stuff to a deployment script that will make a package, installer (.msi), etc. I see no reason to recreate (duplicate) the configuration process (what features/DLLs should be included) for a deployment script.
Some libraries build DLLs (+ correspondent .lib files) with suffixes. I can create conan package for that library and put into `self.cpp_info.libs` any .lib they built (all info included in the suffix is available in `conanfile.py`). But I still have to keep the suffix defined as a var in a project file (to make a DLL's filename and to pass it to a deployment script). Any update of a library (consumed as conan package) will also require to modify a project file. As for me, it will be handy if conan package will provide all info to a project to build and deploy an app. So when I update a package I need only to rebuild a project, and no need to modify project files.

**Comment by memsharded** [comment] 2017-04-07 17:18
That is interesting. The thing with MSBuild (VS) is that the only thing it can provide (up to my knowledge) is the path for Debug/running, so it will find DLLs there. But the list of specific DLLs required by the app, I think it is not possible. Does MSVC has built-in support for generating such MSI installers? How do they define the list of resources to bundle and redistribute in the installer? From the project?

I know it is not optimal, but another idea, valid only for a specific build system is to directly generate a file for that build system at ``build()`` time, so it can be read and used from the final "package" folder.

In any case, I don't see important downsides to having arbitrary variables into ``cpp_info``, just maybe they should be prepended automatically with ``CONAN_<PKG>_`` for an ordered output. Lets suggest it for next 0.23, at least to consider and discuss about it.

**Comment by DmitrySokolov** [comment] 2017-04-07 23:33
MSVC has not built-in support for generation .msi installers. You need to install [WiX Toolset](wixtoolset.org) that will add MSBuild targets and VS extension. WiX project is a kind of VS project that also contains the list of resources.
Usually I create a post-build event that copies files to the StageDir (the final app image). And WiX gets files from that StageDir.

**Comment by memsharded** [comment] 2017-05-17 09:33
Had a look to implementing this feature. No big complexities, but it will require to modify all generators, and testing for those is not fully automated, so it will take some time. So I am moving this feature to 0.24, so we can release 0.23 RC soon.

**Comment by lasote** [comment] 2017-07-04 15:04
#1477 for now, txt and cmake generators will be available.

**Comment by memsharded** [comment] 2017-07-17 12:16
#1477 implements ``user_info_vars`` that provides this functionality. Will be in 0.25

**Closed** 2017-07-19 16:24 UTC
Labels: fixed
