### ISSUE TITLE
[question] [Conan+Artifactory] upload built package binaries to repository from which a recipe was used

### ISSUE THREAD

**Issue by dornbirndevelops** [conan-io/conan#10579] opened 2022-02-15 07:01 UTC
In Artifactory I use virtual repositories to bundle other repositories that I need together into one (like in screenshot below).

![image](https://user-images.githubusercontent.com/25949821/154008071-639d12af-a453-4f6b-b065-acf5f001a471.png)

In this example Conan is configured to have only one remote `virtual 1`.
Furthermore, I have a package recipe called `myapp` in `local 1` that has a dependency to `mylib` located in `local shared`.
To get to a working binary of `myapp`, I use the additional `--build=missing` option to build possibly missing dependencies for my configuration.
If I now upload the package binaries using `conan upload * --all`, how are the binaries distributed between the repositories?
Does each binary end up in the location from which the recipe was downloaded from?
If that does not happen, what is a scalable way to do it (assuming you have built 50+ packages from different repositories)?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-02-15 08:42
> If I now upload the package binaries using conan upload * --all, how are the binaries distributed between the repositories?
Does each binary end up in the location from which the recipe was downloaded from?

At the moment (Conan 1.X) conan will try to upload to the repository that it downloaded the recipe from, if not specified.

But this feature was also confusing, problematic and fragile, it has been removed in 2.0, and all the uploads will need to be explicit: ``conan upload ... -r=myremote``. I don't know what would be the best way for your use case, I'd need to understand it better. One possibility is that there is some "logic" in the process about the packages, that allows an easy selection of what needs to be uploaded where (for example, packages with different "user" name, because they belong to different "teams" in different repos). If that is not the case, then, in 2.0 the interface to the install data will be more available for automation, it will be easier to get the graph information (as json, for example), so you will directly know which package comes from which remote when they are installed from the server.

**Comment by dornbirndevelops** [comment] 2022-02-15 13:46
I will try and see if I can find some common identification feature to group those packages into respective repositories.
Nevertheless I am looking forward to this origin information, thank you @memsharded !

**Comment by dornbirndevelops** [comment] 2022-03-03 08:11
Hi @memsharded, I just tested the approach and discovered a unintentional behavior.

Let's consider two remotes:
- `internal` is supposed to have packages with package user and channel set (like this: `name/version@user/channel`).
- `opensource` is supposed to have packages without user and channel set (like this: `boost/1.78.0@`).

The package upload patterns I've chose for the respective remote:¨
- `conan upload "*/*@user/channel" -r internal` works as expected
- `conan upload "*/*@" -r opensource` also considers packages with package suffix, which is unexpected.

Is there a way to tell the pattern that the matching must stop after the `@` (similar to `^` and `$` in regular expressions)?
FTR: I also tried it with `conan upload "*/*@_/_" -r opensource` but this unfortunately did not match any package.

**Comment by memsharded** [comment] 2022-03-03 11:55
Hi @dornbirndevelops 

You are right, I have tried this, and it doesn't work. It does work with references like ``pkg/version@``, that will not upload ``pkg/version@user/channel``, but when using patterns it matches the whole of it.

This would also likely affect to ``conan search <pattern>`` itself, it seems there is no way to search packages without user and channel only.

We need to have a look at this, and understand if it is possible to change it in the 1.X without breaking or needs to wait for 2.0, lets try to have a look in next iteration.

**Comment by memsharded** [comment] 2022-03-03 11:57
The test to reproduce:

```python
    def test_upload_only_without_user_channel(self):
        """
        check that we can upload only the packages without user and channel
        https://github.com/conan-io/conan/issues/10579
        """
        server = TestServer(users={"user": "password"}, write_permissions=[("*/*@*/*", "*")])
        client = TestClient(servers={"default": server}, users={"default": [("user", "password")]})

        client.save({"conanfile.py": GenConanfile("lib", "1.0")})
        client.run('create .')
        client.run("create . user/channel")
        client.run("search ")
        assert "lib/1.0@user/channel" in client.out

        client.run('upload */*@ -c')
        assert "Uploading lib/1.0 to remote" in client.out  # FAILS!
        assert "lib/1.0@user/channel" not in client.out
        client.run("search -r=default")
        assert "lib/1.0" in client.out
        assert "lib/1.0@user/channel" not in client.out

        client.run('upload */*@user/channel -c')
        assert "Uploading lib/1.0@user/channel to remote" in client.out
        client.run("search -r=default")
        assert "lib/1.0@user/channel" in client.out
```

**Comment by memsharded** [comment] 2022-03-30 16:42
Being thinking about this, didn't come with any reasonable solution. I also tried in Conan 2.0 with this test:

```python
def test_upload_only_without_user_channel():
    """
    check that we can upload only the packages without user and channel
    https://github.com/conan-io/conan/issues/10579
    """
    c = TestClient(default_server_user=True)

    c.save({"conanfile.py": GenConanfile("lib", "1.0")})
    c.run('create .')
    c.run("create . --user=user --channel=channel")
    c.run("list recipes *")
    assert "lib/1.0@user/channel" in c.out

    c.run('upload */* -c -r=default')
    assert "Uploading lib/1.0" in c.out  # FAILS!
    assert "lib/1.0@user/channel" not in c.out
    c.run("search * -r=default")
    assert "lib/1.0" in c.out
    assert "lib/1.0@user/channel" not in c.out

    c.run('upload */*@user/channel -c -r=default')
    assert "Uploading lib/1.0@user/channel to remote" in c.out
    c.run("search -r=default")
    assert "lib/1.0@user/channel" in c.out
```

Still the same. The challenge is that it is not possible to differentiate via a fnmatch the absence of user/channel part. I will try to bring this to the team for some brainstorming in next release.

**Comment by lasote** [comment] 2022-04-19 13:07
Let's enable the pattern `foo*/1.2@` (ended with @) both in upload and remove to specify "no user no channel".

**Comment by lasote** [comment] 2022-04-20 10:17
I checked and it is very risky to fix this in 1.X it will change the behavior too much and we would break some users.
I'll take a look for 2.0

**Comment by memsharded** [comment] 2022-04-20 22:58
The possibility of defining patterns (for upload, remove, etc) without user/channel has been made possible for 2.0 (to be released in next alpha.7) in https://github.com/conan-io/conan/pull/11060. It was not possible in 1.X, as it was too risky of breaking, complicated.

**Closed as completed by memsharded** 2022-04-20 22:58 UTC
Labels: type: look into
