### ISSUE TITLE
[suggestion] conan get command support for binary file retrieval

### ISSUE THREAD

**Issue by brentd42** [conan-io/conan#5286] opened 2019-06-03 21:05 UTC
This is a follow up to closed issue #3925.

It would be useful if the `conan get` command supported retrieval of binary files.

We have a need to obtain an archive of the source files associated with certain packages (e.g., LGPL licensed components).  The `conan_sources.tgz` file would be ideal for this if it could be obtained via `conan get`.  `conan download` is less than ideal as (1) it also requires retrieval of a package, and (2) would require re-tarring of the untar'd source.

This isn't a critical need, but does provide another use case in addition to the one identified in issue #3925.

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x]  I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by lasote** [comment] 2019-06-04 07:51
> would require re-tarring of the untar'd source

What you mean? Would you need to modify the `conan_sources.tgz`?

**Comment by brentd42** [comment] 2019-06-04 12:51
@lasote `conan download` both downloads _and decompresses_ `conan_sources.tgz` (into the export_source folder).  We want an actual .tgz file for this content, so would need to recreate one.  No modifications required.

**Comment by dpar39** [comment] 2022-03-30 13:56
Sometimes the user just wants to download and extract binaries to current directory. Right now there's no way to download and extract a conan_package.tgz directly into user space from a full reference, forcing a download to the local cache, then finding the package folder in the cache and copying/symlinking the binaries out of it for use.

**Comment by memsharded** [comment] 2022-03-30 14:51
Hi @dpar39 

This has been implemented in Conan 2.0 via ``deployers``, that can be passed to ``conan install ...  --deploy=deployer`` that would do it in one step, and allows user customization of the deployer. It will be used for ``conan install``, but not for ``conan download`` command. Would you like to use deployers while ``conan download`` a specific package_id?

**Comment by dpar39** [comment] 2022-03-30 17:42
As I understand Conan 2.0 is still pre-release, right? 
"Would you like to use deployers while conan download a specific package_id?" - Yes, I think that will satisfy my use case once I move to Conan V2.
Right now I can get the reference/package ID via search with query string, but once I download the package to the cache, there's no way to get the local conan cache paths without passing profile/settings/options in `conan info --paths`. I can of course convert the full reference to the path, but that will break as soon as you decide to use a different storage layout within the local cache.

**Comment by memsharded** [comment] 2022-03-30 17:47
> Right now I can get the reference/package ID via search with query string, but once I download the package to the cache, there's no way to get the local conan cache paths without passing profile/settings/options in conan info --paths. I can of course convert the full reference to the path, but that will break as soon as you decide to use a different storage layout within the local cache.

If you are already mapping your settings/options with a query string to a ``search``, then probably it doesn't make sense to go that way (search with query + download), but a simple ``conan install --requires=mypkg/version --deploy=direct_deploy`` could make it (the ``direct_deploy`` is a built-in, that does a copy of the mypkg/version binaries to your local folder)

**Comment by dpar39** [comment] 2022-03-30 18:04
My problem is that I'm just interested in just running the static binaries I have in a package I create with a CI job. I don't want to have a full profile system setup for just downloading something I can locate on the remote via search with query.
This is what I have ended up creating, ugly and fragile, but I don't see another way around it without profiles.
```
reference_id, packages = self.search_builds(project_name, query)
package_id = packages[0]["id"]
full_reference = f"{reference_id}:{package_id}"
self.conan.run(["download", full_reference, "-r", "origin"])
home_data = self.conan.run_json_response(["config", "home"])
full_path = os.path.join(home_data["home"], "data", reference_id.replace("@", "/"), "package", package_id)
# Will copy from this location
```

**Comment by dpar39** [comment] 2022-03-30 18:10
If you guys only add `--output FILE` to `conan get` we could fetch the `conan_package.tgz` directly and untar ourselves, but that's not possible because you are writing to stdout in a way that it seems to be decoding arbitrary bytes to UTF string and invalid codes are thrown out.

**Comment by memsharded** [comment] 2022-03-30 18:35
``conan get`` has already been removed in 2.0. We will probably add other ways to get paths to the Conan cache (something like ``conan cache-get-path <pkg-reference>``), or we will re-evaluate, but ``conan get`` and ``conan inspect`` were a bit problematic (like assuming everything is text) and have been removed at the moment.

**Comment by dpar39** [comment] 2022-04-02 11:36
I don't understand why you guys decided to remove `conan get` instead of fixing it. I'm not a python expert but accounting for binary streams I know shouldn't have been a reason to remove the functionality of copying package data to user space. 
You guys should still consider the use case where people are using conan to just download binaries from a remote to consume without needing full profiles for that.

**Comment by brentd42** [comment] 2022-04-02 12:20
+1

**Comment by memsharded** [comment] 2022-04-03 09:50
Fixing ``conan get`` that shows in terminal the contents of text files to do copies of binary files to user space is the typical abused evolution we have struggled in the past, because it ends in very poor UX and a few rough edges.

We are not saying that we will not provide means to achieve that. In fact the Conan 2.0 ``deployers`` functionality is one order of magnitude better of what we had in the past, it even allows to do copies of files to user space AND to make the generators like ``CMakeDeps`` to point to that user space copy instead to the cache. 

Instead of ``conan get``, if we provide a ``conan cache path`` that gives you the path to the cache folder, doing a copy exactly like you want, opening it in a text editor, etc, is totally straightforward. The expected behavior is also way more evident, and that reduces many UX issues.

**Comment by lasote** [comment] 2022-04-25 12:17
This [PR](https://github.com/conan-io/conan/pull/11017) was merged and a new "conan cache path" command will be available at alpha7 to locate the paths to the cache.

**Closed by lasote** 2022-04-25 12:17 UTC
Labels: type: look into, stage: triaging
