### ISSUE TITLE
Problem to upload package on Artifactory

### ISSUE THREAD

**Issue by Ti-R** [conan-io/conan#5706] opened 2019-09-04 15:05 UTC
Hello,

I got a problem to upload package on Artifactory.

First I compile 2 package with some commands lines -> it worked well. 
~~~
conan create . ix/stable -s build_type=Debug -s compiler.version=15
conan create . ix/stable -s build_type=Release -s compiler.version=15
~~~

Second I compile 4 package with other commands lines with the same receipe -> It failed on uploading package.
~~~
conan create . ix/stable -s compiler.version=15 -s arch=x86 -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime="MDd"
conan create . ix/stable -s compiler.version=15 -s arch=x86_64 -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime="MDd"
conan create . ix/stable -s compiler.version=15 -s arch=x86 -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime="MD"
conan create . ix/stable -s compiler.version=15 -s arch=x86_64 -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime="MD"
~~~

On upload it give me:

~~~
conan upload '*Minizip*' --all -r artix -c --no-overwrite all
Uploading to remote 'artix':
Uploading Minizip/1.2@ix/stable to remote 'artix'
Recipe is up to date, upload skipped
Uploading package 1/4: 009a50ddeb47afbc9361cbc63650560c127e1234 to 'artix'
Compressing package...
[==================================================]
ERROR: Local package is different from the remote package. Forbidden overwrite.
~~~

If I test without `--no-overwrite` flag.
~~~
conan upload '*Minizip*' --all -r artix -c
~~~

The error is 
~~~
Uploading to remote 'artix':
Uploading Minizip/1.2@ix/stable to remote 'artix'
Recipe is up to date, upload skipped
Uploading package 1/4: 009a50ddeb47afbc9361cbc63650560c127e1234 to 'artix'
Requesting upload urls...Done!
Uploading conan_package.tgz: 100%|##########| 125k/125k [00:00<00:00, 18.8MB/s]
ERROR: 500 Server Error: Internal Server Error for url: https://binaries.ixblue.com/artifactory/api/conan/conan-public/v1/files/ix/Minizip/1.2/stable/0/package/009a50ddeb47afbc9361cbc63650560c127e1234/0/conan_package.tgz
Waiting 5 seconds to retry...
~~~

On artifactory server, the user don't have any rights to DELETE packages.

The "conanfile.py" is the same as the first time executed, but the commands to compile the package are not the sames.

It always fail on the first package and never upload the missing packages.

~~~
Conan: version 1.8.2
Operating System: Windows 7 SP1
Compiler: Visual Studio 2017

Artifactory Internal Server: Version 6.10.0
~~~

They seems to be related to :
https://github.com/conan-io/conan/issues/3473
https://github.com/conan-io/conan/issues/3732

But these issues are fixed (and seems to be inside the version of conan used)

----

To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by danimtb** [comment] 2019-09-05 07:24
Hi @Ti-R,

Probably this is failing due to not having delete permissions as the packages seem to be already uploaded and Conan is trying to overwrite it on the server.

Anyway, the error message doesn't look very helpful 😕

**Comment by Ti-R** [comment] 2019-09-05 08:14
Yes but I forget to precise I know the package are already uploaded.
But only 2 on 4 packages.
I would like to upload the missing package.
And because the command failed on first package the 2 other one are not uploaded.

**Comment by danimtb** [comment] 2019-09-05 08:48
I was able to reproduce your issue:

```
$ conan upload fmt* -r art-local --force --all
Are you sure you want to upload 'fmt/5.0.0' to 'art-local'? (yes/no): y
Uploading to remote 'art-local':
Uploading fmt/5.0.0 to remote 'art-local'
Uploading conanfile.py: 100%|##########| 3.03k/3.03k [00:00<00:00, 3.10MB/s]
ERROR: 500 Server Error: Internal Server Error for url: http://localhost:8081/artifactory/api/conan/art-local/v1/files/_/fmt/5.0.0/_/0/export/conanfile.py
Waiting 5 seconds to retry...
```

I'd say this is a current limitation of Conan that could be improved. 😞 
Meanwhile, the workaround would be to upload with ``--query`` indicating the configurations to upload or just indicating the package ids you want to upload.

**Comment by Ti-R** [comment] 2019-09-05 09:12
I did already try with `--query`.
But because I'm using Jenkins to build automatically though a pipeline with stage.
If it detect an error, it stop the steps and finally I can't get my 2 other package.

**Comment by Ti-R** [comment] 2019-09-05 09:15
I think `--no-overwrite all` could be improve with a force flag to skip all duplicate and upload the missing package.

**Comment by danimtb** [comment] 2019-09-05 09:22
Yes, I think we definitely have to consider this scenario and add a flag to the upload command

**Comment by memsharded** [comment] 2024-05-02 22:47
Closing this ticket as outdated. Conan 2 has completely revamped the upload to the server, based on revisions, no overwrites should happen. Please create new tickets if necessary.

**Closed by memsharded** 2024-05-02 22:47 UTC
Labels: priority: low, type: feature, stage: queue, complex: medium
