### ISSUE TITLE
[feature] build_system_requirements

### ISSUE THREAD

**Issue by Yuri6037** [conan-io/conan#7504] opened 2020-08-05 13:11 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

I'm currently building a lightweight version of SDL2 in order to only use in Core Context, DX11-12 and VK. In order to achieve that I figure that it is unacceptable to have all developpers install dev dependencies like libwayland-dev and/or xord-dev when building apps which would only use SDL2 common APIs (no low-level stuff).
I request the creation of a build_system_requirements function which works the same as system_requirements but only checks when building the package.

**Comment by uilianries** [comment] 2020-08-05 17:00
You can use `self.develop` to filter it: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#develop

```python
def system_requirements(self):
    if self.develop:
        installer = SystemPackageTool()
        installer.install("foobar")
```

**Comment by Yuri6037** [comment] 2020-08-05 17:54
Right now I'm testing a hack which involves creating a separate package which conatains all system requirements and I'll reference it in build_requirements

**Comment by uilianries** [comment] 2020-08-05 19:11
I see, that's what we are using in CCI, [opengl](https://github.com/conan-io/conan-center-index/blob/a4369f6040157dfc749d98564d202eb2e20a8f99/recipes/opengl/all/conanfile.py) for instance. So you can:

```python
def build_requirements(self):
    self.build_requires("opengl/system")
```

**Comment by Yuri6037** [comment] 2020-08-05 19:29
Yeah in that case we should ask bincrafters why they refuse to do that and why I'm forced to do the work that they are apparently unable to do...
EDIT: At least fiunally by hack worked: I can run github actions to build the SDL2 lightweight package and receive the binarries over here: https://bintray.com/yuri6037/bp3d

**Comment by uilianries** [comment] 2020-08-05 21:58
> Yeah in that case we should ask bincrafters why they refuse to do that and why I'm forced to do the work that they are apparently unable to do...

I'm part of Bincrafters too, so I can say we trying to move all packages to CCI, before trying a new adventure with system requirements. We only decided to use proxy many months afters creating CCI, before that was a hell to track any change related to system packages, as they can't provide a reliable package id.

Being more specific, we made an effort pushing SDL2 into CCI, but as you should know, it requires a lot of requirements first, which are system dependent. For further info read the PR https://github.com/conan-io/conan-center-index/pull/223. You are interested in help us with SDL2, you can comment here: https://github.com/conan-io/conan-center-index/issues/2343

**Comment by ericLemanissier** [comment] 2020-08-06 07:51
AFAIK, package A uses build_requirements("B/***") when B has to be present only when compiling A, and when B is not used at all when linking something with A. @uilianries are there packages on CCI using build_requirements when B is also needed to link with A ? opengl and xorg are always used as `requires`.
In the case of SDL2 using `build_requires("xorg/system")`, it is not a good choice because xorg system libraries are needed also when linking to SDL2: Think about the case where SDL2 is built as a static library, and uses static version of x11 et al: The linking of your application would fail because the static libraries of x11 are brought by all the system ***-dev packages, which were not installed because you did not compile SDL2, and you get no clue from conan of what you should do. This is a regression on the usability (and there is nothing specific to SDL here), and the benefit is quite small: avoiding to install some system **-dev packages, when the non -dev version of said packages are still needed, and have to be installed manually.

**Comment by uilianries** [comment] 2020-08-06 13:19
> are there packages on CCI using build_requirements when B is also needed to link with A ? opengl and xorg are always used as requires.

@ericLemanissier only as build requirement? No.

Indeed is a big problem, because we can't track system packages, if they are available as shared or static.

**Comment by bb010g** [comment] 2020-08-20 20:46
@uilianries Unless you want to merge these into one tracking issue, conan-io/conan-center-index#2343 was meant to cover SDL1, not SDL2. One issue for both is fine by me though, if that's what you all would prefer; let me know and I can edit up the title & body for that.

**Comment by SpaceIm** [comment] 2020-12-17 16:50
AFAIK, trying to simulate public/private dependencies with a mix of `requirements()` and `build_requirements()` is bad. It might work in some cases, but it's fragile.
I mean something like:
- if lib is static, private dependencies are in `requirement()`
- if lib is shared, private dependencies are in `build_requirements()`.

Here are some reasons I see to not use this pattern:
- It very likely breaks on the fly with cross-build.
- It might break downstream recipes, since some magic inside conan could not take into account informations from build requirements in conan generators or build helpers (for example add lib paths of build requirements in LD_LIBRARY_PATH).
- I guess it might break with any new conan versions, since build requirements are for dependencies on **the build machine** (not the target machine) required at build time only.
- shared private dependencies are required at runtime (only .dll/.so/.dylib, but conan packages provide public header files and static/shared libs all together).

The best to expect is waiting that conan implements some public/private/interface property for dependencies. Honestly, I don't expect this kind of improvement before conan 2.0 (not even sure it's planned for this new major version), since it probably requires a major refactoring of dependency graph resolution and propagation of dependencies in conan generators and build helpers, not even talking about how it would fit with components granularity.

**Comment by memsharded** [comment] 2024-12-19 23:54
There is a new ticket for this, that would be a duplicate. 
I am closing this ticket, please follow up on https://github.com/conan-io/conan/issues/16625 for progress on that, it is assigned to the 2.X roadmap, so it is supposed to happen not immediately, but in the mid term. Thanks for your feedback!

**Closed as completed by memsharded** 2024-12-19 23:54 UTC
