### ISSUE TITLE
[bug] very slow download using artifactory virtual repository 

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#9616] opened 2021-09-16 08:55 UTC
We are using artifactory as conan server which used to work hyper smoothly.
Our setup consist of three repositories:
- conan-internal-dev
- conan-internal-prod
- conan-internal-thirdparty

Recently, we switched to use one virtual artifactory repository which encapsulate the three repos above. (conan-internal). 
Virtual repository require conan revision to be enabled, so we did that as documented [https://docs.conan.io/en/latest/versioning/revisions.html#how-to-activate-the-revisions](url) 

But since we did this, we noticed that conan download become veryyyy slow and it get stuck many time for several minutes. 
 
Artifactory virtual repo does not support package indexing for conan. Could it be the reason or maybe this is because of conan revisions ? 
We are not sure if this is a conan or an artifactory issue!

Any clue ? 

Best,
Walid

### Environment Details (include every applicable attribute)
  * Operating System+version: windows
  * Compiler+version: visual studio 2019
  * Conan version: 1.39.0
  * Python version: python3

**Comment by czoido** [comment] 2021-09-16 09:09
Hi @boussaffawalid,
Could that be because you have a Conan Center **remote** repository added as well in the virtual repository and the search in the Conan Center remote is slowing down all the conan commands?
Please check if you have a remote repository besides your other local repositories and if it's there test removing it.

**Comment by boussaffawalid** [comment] 2021-09-16 09:11
@czoido nope, we only use our own local repositories we build everything in house.

**Comment by czoido** [comment] 2021-09-16 09:34
Hi @boussaffawalid,
I have been doing some basic testing with a virtual repository with three local repos added and I could not reproduce the issue. Some questions to see if we can come up with something:

- Do you know which Artifactory version you are using?
- What's the approximate size in number of packages and artifacts you are managing in your repos?
- Which kind of operations have slowed down? Is `conan install` also very slow? Is it only the `conan search` that slowed down? Maybe `conan search` with patterns like "*"?

**Comment by boussaffawalid** [comment] 2021-09-16 09:54
* We use artifactory cloud enterprise version 7.23.3
* Artifacts Size: 910.02 GB
* Artifactory Artifacts Count (The total number of artifacts pointing to the physical binaries stored on your system.
):  107,480
* Artifactory items Count(The total number of items (both files and folders) in your system):  251,926
* Artifactory Total number of conan packages: 7001  (get it using conan search "*"   -r=conan-internal| wc -l)
* Conan install command is what is very slow. 
* Conan search is almost immediate.
* We use artifactory almost exclusively for conan.

**Comment by czoido** [comment] 2021-09-16 10:01
Hi @boussaffawalid,
Thanks a lot for the detailed info. 
One more question: are you using version ranges in your packages?

**Comment by boussaffawalid** [comment] 2021-09-16 10:02
nope, we only use exact versions.

**Comment by czoido** [comment] 2021-09-16 10:10
Hi @boussaffawalid,
Do you think you could paste here some [logs](https://docs.conan.io/en/latest/mastering/logging.html) of the slow operations? 
You can generate them defining `CONAN_TRACE_FILE` like `export CONAN_TRACE_FILE=/tmp/conan_trace.log`

**Comment by boussaffawalid** [comment] 2021-09-16 10:33
@czoido I will try to generate one, it may take some time for me todo that

**Comment by boussaffawalid** [comment] 2021-09-20 12:01
@czoido sorry for the noise! issue is gone. it seems to be a temporarily artifactory glitch.

**Comment by czoido** [comment] 2021-09-20 15:45
> @czoido sorry for the noise! issue is gone. it seems to be a temporarily artifactory glitch.

No problem! It's great to hear that's not happening any more. I'm closing this issue then.

**Closed as completed by czoido** 2021-09-20 15:45 UTC
Labels: type: question
