### ISSUE TITLE
[bug] conan info returns Package_ID_unknown for some profiles

### ISSUE THREAD

**Issue by SSE4** [conan-io/conan#10704] opened 2022-03-03 05:29 UTC
from https://github.com/conan-io/conan-center-index/pull/9565

### Environment Details (include every applicable attribute)
  * Operating System+version: `Ubuntu 19.10` (docker image `conanio/gcc9:1.44.1` or `conanio/gcc9:1.45.0`)
  * Compiler+version: `gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008`
  * Conan version: `Conan version 1.44.1` or `Conan version 1.45.0`
  * Python version: `Python 3.7.5`

### Steps to reproduce (Include if Applicable)

clone the repository:
```
$ git clone --depth 1 --branch package-enjincppsdk git@github.com:SSE4/conan-center-index.git
```
create the profile:
```
$ cat profile1
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux
[options]
enjincppsdk:shared=True
```
run conan client to export:
```
$ cd conan-center-index/recipes/enjincppsdk/all
$ conan export . enjincppsdk/1.0.0-alpha.3@
```
run conan client to compute package ID:
```
$ conan info enjincppsdk/1.0.0-alpha.3@ -pr profile1 --dry-build
```
it returns `Package_ID_unknown`. as `Package_ID_unknown` is not documented, I assume it's a bug. in the CCI case, it fails later on the upload step.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
fmt/7.1.3: Forced build from source
rapidjson/1.1.0: Forced build from source
spdlog/1.8.2: Forced build from source
enjincppsdk/1.0.0-alpha.3
    ID: Package_ID_unknown
    BuildID: None
    Context: host
    Remote: None
    URL: https://github.com/conan-io/conan-center-index
    Homepage: https://github.com/enjin/enjin-cpp-sdk
    License: Apache-2.0
    Description: A C++ SDK for development on the Enjin blockchain platform.
    Topics: enjin, sdk, blockchain
    Provides: enjincppsdk
    Recipe: Cache
    Binary: Unknown
    Binary remote: None
    Creation date: 2022-03-03 05:21:36 UTC
    Requires:
        rapidjson/1.1.0
        spdlog/1.8.2
fmt/7.1.3
    ID: db123017807f5c094e7ffe64463018510e127133
    BuildID: None
    Context: host
    Remote: conancenter=https://center.conan.io
    URL: https://github.com/conan-io/conan-center-index
    Homepage: https://github.com/fmtlib/fmt
    License: MIT
    Description: A safe and fast alternative to printf and IOStreams.
    Topics: fmt, format, iostream, printf
    Provides: fmt
    Recipe: Cache
    Binary: Build
    Binary remote: None
    Creation date: 2022-02-17 11:59:23 UTC
    Required by:
        spdlog/1.8.2
rapidjson/1.1.0
    ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    BuildID: None
    Context: host
    Remote: conancenter=https://center.conan.io
    URL: https://github.com/conan-io/conan-center-index
    Homepage: http://rapidjson.org
    License: MIT
    Description: A fast JSON parser/generator for C++ with both SAX/DOM style API
    Topics: conan, rapidjson, json, parser, generator
    Provides: rapidjson
    Recipe: Cache
    Binary: Build
    Binary remote: None
    Creation date: 2021-06-17 14:15:35 UTC
    Required by:
        enjincppsdk/1.0.0-alpha.3
spdlog/1.8.2
    ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    BuildID: None
    Context: host
    Remote: conancenter=https://center.conan.io
    URL: https://github.com/conan-io/conan-center-index
    Homepage: https://github.com/gabime/spdlog
    License: MIT
    Description: Fast C++ logging library
    Topics: spdlog, logging, header-only
    Provides: spdlog
    Recipe: Cache
    Binary: Build
    Binary remote: None
    Creation date: 2021-12-15 20:54:32 UTC
    Required by:
        enjincppsdk/1.0.0-alpha.3
    Requires:
        fmt/7.1.3
```

**Comment by SSE4** [comment] 2022-03-03 06:07
it is returned from:
https://github.com/conan-io/conan/blob/1.45.0/conans/model/info.py#L554
because `require.sha` is `None`.
returned earlier from:
https://github.com/conan-io/conan/blob/1.45.0/conans/model/info.py#L224
seems llike data is missing for `rapidjson/1.1.0#0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9`
which is returned from:
https://github.com/conan-io/conan/blob/1.45.0/conans/model/info.py#L69
hitting the condition `self.package_revision == PREV_UNKNOWN`
and `PREV_UNKNOWN` seems to be assigned from:
https://github.com/conan-io/conan/blob/1.45.0/conans/model/info.py#L162
as `package_revision_mode` is called from inside the `shared_library_package_id`:
https://github.com/conan-io/conan/blob/1.45.0/conans/model/info.py#L662

**Comment by SSE4** [comment] 2022-03-03 06:33
for the record, lockfile created also looks corrupted:
```
$ conan lock create --reference enjincppsdk/1.0.0-alpha.3@ -pr profile1  --build
...
Generated lockfile: /host/bincrafters/conan-center-index/recipes/enjincppsdk/all/conan.lock
conan@6e38f816f390:/host/bc/conan-center-index/recipes/enjincppsdk/all$ cat conan.lock
{
 "graph_lock": {
  "nodes": {
   "1": {
    "ref": "enjincppsdk/1.0.0-alpha.3",
    "options": "shared=True\nwith_default_http_client=False\nwith_default_ws_client=False\nspdlog:header_only=True\nspdlog:no_exceptions=False\nspdlog:wchar_filenames=False\nspdlog:wchar_support=False",
    "package_id": "Package_ID_unknown",
    "requires": [
     "2",
     "3"
    ],
    "context": "host"
   },
   "2": {
    "ref": "rapidjson/1.1.0",
    "options": "",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "context": "host"
   },
   "3": {
    "ref": "spdlog/1.8.2",
    "options": "header_only=True\nno_exceptions=False\nwchar_filenames=False\nwchar_support=False\nfmt:fPIC=True\nfmt:header_only=False\nfmt:shared=False\nfmt:with_fmt_alias=False\nfmt:with_os_api=True",
    "package_id": "5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9",
    "requires": [
     "4"
    ],
    "context": "host"
   },
   "4": {
    "ref": "fmt/7.1.3",
    "options": "fPIC=True\nheader_only=False\nshared=False\nwith_fmt_alias=False\nwith_os_api=True",
    "package_id": "db123017807f5c094e7ffe64463018510e127133",
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\nbuild_type=Release\ncompiler=gcc\ncompiler.libcxx=libstdc++11\ncompiler.version=9\nos=Linux\n[options]\nenjincppsdk:shared=True\n[build_requires]\n[env]\n"
```

**Comment by memsharded** [comment] 2022-03-03 09:26
This is expected behavior when you use ``package_revision_mode()``, that you are using in your recipe, via the ``shared_library_package_id()`` helper. 

Maybe the exact value of ``Package_ID_unknown`` is not documented, but the fact that the package_id of your package cannot be computed for that mode when the upstream package does not exist yet (and it doesn't exist, because you are doing a "build=all"), is correct.

**Comment by SSE4** [comment] 2022-03-03 09:44
> Maybe the exact value of `Package_ID_unknown` is not documented, but the fact that the package_id of your package cannot be computed for that mode when the upstream package does not exist yet (and it doesn't exist, because you are doing a "build=all"), is correct.

so, does it mean what package ID (in generic case) is different depending on `--build=xxx` arguments?
in other words, once I decide to rebuild some of my dependencies, my package ID could be different?
in this case, it's going to be chicken and egg problem for CI system - we need to known package IDs before the build, but it's only can be computed (in generic case) after the build?

**Comment by memsharded** [comment] 2023-05-31 14:54
Package_ID_unknown no longer an issue in Conan 2.0, it has been dropped (strongly discouraged to use ``package_revision_mode`` in Conan 1.X. Closing the issue.

**Closed as completed by memsharded** 2023-05-31 14:54 UTC
