### ISSUE TITLE
[question] Governance policies for conan-center-index

### ISSUE THREAD

**Issue by michaelmaguire** [conan-io/conan#8606] opened 2021-03-04 18:46 UTC
In light of recent hacks such as:

https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610 "Dependency Confusion: How I Hacked Into Apple, Microsoft and Dozens of Other Companies"

and older related ones such as:

https://snyk.io/blog/malicious-packages-found-to-be-typo-squatting-in-pypi/

Is there any kind of set of governance policy in place for subdirectory names in https://github.com/conan-io/conan-center-index/tree/master/recipes ?

e.g. can concerned organization 'reserve' a subdirectory or a set of name prefixes?

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-03-04 19:57
Hi @michaelmaguire 

ConanCenter has some of the strongest policies to get something into it:

- Only pull requests from registered users are built
- Registered users are activated with delay, and human supervision
- Every pull request needs to pass a thorough CI with tons of tests and build in multiple configurations
- Every pull request requires at least 3 human approvals, at least 1 from the maintainers
- Nobody except our build service upload anything to ConanCenter
- The size of the repo (this is general for C/C++) is orders of magnitude smaller than those of PyPI or NPM, due to the nature of the ecosystem

Also, contrary to other package managers, we encourage the usage of your own private repositories, and not depend on ConanCenter in production, and building packages from source instead of using pre-compiled binaries from ConanCenter is done by a large majority of our users.

Regarding the governance policy for subdirectories, the names there are library names, not organization names, so seems difficult to reserve an organization prefix or namespace. 

Does this address some of those concerns?

**Comment by michaelmaguire** [comment] 2021-03-05 11:03
Thank you!  Relaying that message back now.

**Comment by memsharded** [comment] 2021-07-30 01:06
Seems this was satisfactorily responded, so closing it, but please tell otherwise. Thanks!

**Closed as completed by memsharded** 2021-07-30 01:06 UTC
Labels: type: question, stage: triaging

**Comment by eirikb** [comment] 2021-11-16 07:41
Sorry for the necrobump.

Wouldn't the attack vector described in the article be sufficiently limited by simply placing new remotes at the top of the list?

**Comment by memsharded** [comment] 2021-11-16 08:42
@eirikb Problem of adding new remotes is that if a package is not found in that remote it will be looked for in the next one. If a user does a typo and rquires an opensssl (3 s) package and there is a malicious one in ConanCenter, even if it is the last remote, the package will be found there and not in the first remotes and be fetched. However, for the reasons above, it seems less unlikely for this to happen in ConanCenter because the described policies and processes.

**Comment by eirikb** [comment] 2021-11-16 09:00
The problem is not typos.
An attacker would try to upload a package with the same name and version to ConanCenter, as an internal package stored on local Artifactory.

The default order now, after adding a new remote is:
  1. Local cache
  1. ConanCenter
  1. New remote

If the package is not found in local cache then ConanCenter will be queried.  
By placing the new remote above ConanCenter the malicious package would not (normally) be fetched.

**Comment by memsharded** [comment] 2021-11-16 09:08
Yes, the exact name match is not a problem. I was commenting about another different problem known as typo-squatting, that this approach wouldn't solve, just for completeness.

**Comment by eirikb** [comment] 2021-11-16 09:18
Yes there are several different issues, e.g., if the local Artifactory is unavailable the hack would still succeed. But if the attacker know the local remote by default is on top they might be demotivated from even trying.

I'm not saying changing the default order will solve everything, but I believe it will help against the specific attack outlined in the article. A small change to increase security. Do you think it would break a lot of existing setups?

**Comment by memsharded** [comment] 2021-11-16 09:22
> Yes there are several different issues, e.g., if the local Artifactory is unavailable the hack would still succeed. But if the attacker know the local remote by default is on top they might be demotivated from even trying.

Well, this is one of the reasons that when a remote is not available Conan will error. We don't want to have a silent fallback because a temporary network or server issue. If it is unavailable, then users can ``conan remote disable`` it, but this will not be skipped.

Yes, indeed adding your own remote as a first one will further reduce the risks. This is already common practice by tons of Conan users, it shouldn't break any setup. Or you mean to change how ``conan remote add`` works? Yes, that would be breaking, and cannot be done. Users can use ``--insert`` to do it. In any case, in practice the recommended approach is to use ``conan config install`` to configure your clients, not manage remotes manually.

**Comment by eirikb** [comment] 2021-11-16 09:32
Changing the default was my idea, yes.
I'm aware it is possible to change by flags, and we follow the practice of disabling/removing conancenter (it's proxied in Artifactory), which solves the issue as well.

However I feel that how-to is not the correct solution for mitigating an attack.  
But if a breaking change can't be done then it can't be done. 

Thank you for the discussion :slightly_smiling_face:  :+1:
