### ISSUE TITLE
"conan export" fails with `short_paths` and `exports` when recipe and conan are on different drives

### ISSUE THREAD

**Issue by guban** [conan-io/conan#6197] opened 2019-12-08 02:55 UTC
"conan export" fails with `short_paths` and `exports` when recipe and conan use different drives

 * OS: Windows 10 x64
 * conan version: 1.20.5 
 * python version: 3.7.3 x64

Steps to reproduce:

I have a recipe that enables `short_paths` and `exports` a folder with several files alongside the recipe file. The recipe and the files are on drive `C:`, and my conan data folder is configured to be on drive `D:` (which is slower but larger than `C:`). When I export this recipe by running `conan export`, the command always fails with `ERROR: path is on mount D:, start on mount C:`. When I move the recipe to drive `D:` the same export command succeedes. Expected behavior: the export command should succeed regardless of the drive.

The output of the failed `conan export` command:

	Exporting package recipe
	Traceback (most recent call last):
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\command.py", line 1938, in run
	    method(args[0][1:])
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\command.py", line 995, in export
	    ignore_dirty=args.ignore_dirty)
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\conan_api.py", line 81, in wrapper
	    return f(api, *args, **kwargs)
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\conan_api.py", line 753, in export
	    graph_lock=graph_lock, ignore_dirty=ignore_dirty)
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\cmd\export.py", line 120, in cmd_export
	    export_recipe(conanfile, origin_folder, package_layout.export())
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\cmd\export.py", line 431, in export_recipe
	    copier(pattern, links=True, excludes=excluded_exports)
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\file_copier.py", line 81, in __call__
	    keep_path, excluded_folders=excluded)
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\file_copier.py", line 100, in _copy
	    self.link_folders(src, dst, link_folders)
	  File "C:\Programs\Python37_x64\lib\site-packages\conans\client\file_copier.py", line 178, in link_folders
	    link = os.path.relpath(link, os.path.dirname(src_link))
	  File "C:\Programs\Python37_x64\lib\ntpath.py", line 562, in relpath
	    path_drive, start_drive))
	ValueError: path is on mount 'D:', start on mount 'C:'
	
	ERROR: path is on mount 'D:', start on mount 'C:'

**Comment by memsharded** [comment] 2019-12-08 18:26
Hi @guban 

Doing a quick inspection to the code and your error trace, it seems that the problem is not in the drive, but on the fact that you have symlinks, and in Windows those symlinks cannot be relativized between different drives.

Do you really intend to have symlinks in Windows? In the first place, having symlinks in the exported files is typically not a good idea, it makes things more complicated and error prone. In all platforms, but specially in Windows. What would be your use case?

**Comment by guban** [comment] 2019-12-08 21:43
Indeed, in a subfolder next to `conanfile.py` there is a directory symlink that points to drive `D:` (it took some time to find it as I created that symlink long ago for purposes not related to conan). The thing is, I do not export that symlink (and, of course, I do not intend to do so).

Here is a minimal example that reproduces the bug:

File `c:/work/conanfile.py`:

	from conans import ConanFile
	class cccConan(ConanFile):
	    name = "ccc"
	    settings = "os", "compiler", "build_type", "arch"
	    exports = 'a.txt'	

File `c:/work/a.txt` is a tiny text file; its content is irrelevant.

Folder `c:/work/my_link` is a symlink pointing to folder `d:/work`.

I export this recipe using this command:

	conan export . 1.0.0@me/repr

With this, I get the `path is on mount 'D:', start on mount 'C:'` error. This error disappears if I remove the line `exports = 'a.txt'` from the recipe, or if I remove the symlink, or if I change the symlink to point to a folder on drive `C:`.

The bug is reproducible without `short_paths=True`. Most likely, the fact that my conan storage is on drive `D:` is irrelevant, too.

**Comment by memsharded** [comment] 2019-12-09 22:36
Yes, I think you are right, the ``short_paths`` is irrelevant here, it is all about the symlinks.

I have been inspecting the code, and I am still not sure how to improve this without a horrible hack for this Windows specific behavior.

I think there is a workaround excluding that folder from the exports, like:
```python
exports = 'a.txt', '!my_link'
```
With this you don't need to remove your exports, or your symlink.  Please tell me if this helps.

I would also like to suggest to have a look to the "SCM" feature, to use git as the origin of sources instead of exporting the sources together with the recipe.

**Comment by memsharded** [comment] 2019-12-09 23:20
I have been able to skip the symlink crash with this PR: https://github.com/conan-io/conan/pull/6201. 

Not guarantee it will be merged, it is just a way to avoid the error and almost impossible to test automatically. And it is probably not bad that the error is there in the first place, as it seems an unusual thing, maybe change it with another error message (the solution would be then to avoid ``exports`` it``)

**Comment by guban** [comment] 2019-12-10 03:07
The `exports = 'a.txt', '!my_link'` workaround did not help. Then, I realized that in my case, I have to export too many files, so I finally decided to replace `exports` with fetching the files from a git repo.

Yes, it is good to see an error message, especially if the user attempts to export the symlink. However, those who end up in this unusual situation inadvertently will have a hard time finding the culprit. Maybe, an optimal solution is to always fail with an error, but mention the path of the symlink in the error message.

Thank you for your help!

**Comment by memsharded** [comment] 2019-12-10 08:31
> The exports = 'a.txt', '!my_link' workaround did not help.

I would like to know a bit more if possible, I tried it in my machine and it worked fine.

> Then, I realized that in my case, I have to export too many files, so I finally decided to replace exports with fetching the files from a git repo.

If you have the recipe besides the source code, please have a look to the SCM mechanism, it is intended to capture the url/commit, so builds can be reproduced. If your recipe is in another repo, then fetching the sources yourself is ok.

> Yes, it is good to see an error message, especially if the user attempts to export the symlink. However, those who end up in this unusual situation inadvertently will have a hard time finding the culprit. Maybe, an optimal solution is to always fail with an error, but mention the path of the symlink in the error message.

Yes, maybe better to fail with a more informative error. Waiting for feedback on my PR.

Thanks for the feedback!

**Comment by guban** [comment] 2019-12-10 14:52
> I would like to know a bit more if possible, I tried it in my machine and it worked fine.

Attached [ddd.zip](https://github.com/conan-io/conan/files/3945229/ddd.zip) has the complete example that reproduces the problem on my machine. Unzip it to drive `c:`, create folder `d:/work`, and run `reproduce.cmd`. I upgraded to conan 1.21.0, and the problem is still reproducible. If you need some other information, please let me know.

> If you have the recipe besides the source code, please have a look to the SCM mechanism

Yes, my recipe and files are in the same repository, but I decided not to use SCM mechanism because it is still marked as an experimental feature.

> Waiting for feedback on my PR.

I've added a comment to the PR.

**Comment by memsharded** [comment] 2019-12-10 15:07
> I upgraded to conan 1.21.0, and the problem is still reproducible. If you need some other information, please let me know.

Yes, the PR https://github.com/conan-io/conan/pull/6201 hasn't been merged in 1.21, it is scheduled for review in 1.22.. Thanks for the zip!

> Yes, my recipe and files are in the same repository, but I decided not to use SCM mechanism because it is still marked as an experimental feature.

Understood. However, note that SCM has been there for quite a while, so it is extremely unlikely it will be drastically modified, just minor breaking things, if any.

**Closed** 2020-01-14 23:34 UTC
Labels: stage: triaging

**Comment by memsharded** [comment] 2020-01-14 23:38
https://github.com/conan-io/conan/pull/6201 was merged, so the new error message for this scenario will be available in Conan 1.22. Still, it is just raising an error, as it is not possible to compute relative paths between different units in Windows.
