### ISSUE TITLE
[feature] Provide a 'premake_multi' generator

### ISSUE THREAD

**Issue by Zeenobit** [conan-io/conan#6634] opened 2020-03-06 04:26 UTC
I'm trying to use the new experimental premake generator with premake5 based on these guides:
https://docs.conan.io/en/latest/reference/generators/premake.html
https://docs.conan.io/en/latest/integrations/build_system/premake.html#premake

But I can't figure out how to hook up multiple configurations in premake.

If I use `conan install . -s built_type=Debug -if ./debug` to install Debug/Release builds into separate directories, then I end up with two `conanbuildinfo.premake.lua` files in two separate directories (debug and release).

If I then have this in premake5.lua:
```
include "debug/conanbuildinfo.premake.lua"
```

That'll include the debug configuration. But then what about the release configuration?

If I do this:

```
include "debug/conanbuildinfo.premake.lua"
include "release/conanbuildinfo.premake.lua"
```

Then I'm just loading two different tables on top of each other. Is this just not supported on premake, or am I doing something wrong?
Any help on this would be appreciated.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by czoido** [comment] 2020-03-06 15:08
Hi @Zeenobit,
I think that the premake generator is not prepared for multiconfiguration, maybe declaring the `include` directive inside the `filter` for each configuration in the premake file could be a valid workaround? 
Any ideas about this @SSE4 ?

**Comment by memsharded** [comment] 2020-03-06 15:29
> I think that the premake generator is not prepared for multiconfiguration,

Yes, this generator is intended for single-config only, need two or more separate build folders, each one with its own independent configuration and build.

**Comment by Zeenobit** [comment] 2020-03-06 16:01
> Hi @Zeenobit,
> I think that the premake generator is not prepared for multiconfiguration, maybe declaring the `include` directive inside the `filter` for each configuration in the premake file could be a valid workaround?

You can't really do that, cause `include` just runs the Lua script at the time of premake generation. `filter` can't prevent the next line of script to be executed while the script is being executed.

It may be possible to work around it by loading the scripts into separate tables, but it'd be super hacky. We could scan the global Lua table for all keys that start with `conan_*` and copy them to a separate table, then load the release config. Maybe. I'll post solution if this works.

**Comment by Zeenobit** [comment] 2020-03-06 23:03
I managed to get this working using a simple function in Lua. Instead of using `include`, use `conan_include`:

```lua
local function include_conan(filename)
    include(filename)
    local buildinfo = { }
    local prefix = 'conan_'
    for k, v in pairs(_G) do
        if k:sub(1, #prefix) == prefix then
            buildinfo[k:sub(#prefix + 1)] = v
        end
    end
    return buildinfo
end
```

Then, use the following to install Conan files into separate directories:

```
conan install .. -if ./conan_debug   -s build_type=Debug
conan install .. -if ./conan_release
```

And then call `conan_include` at the beginning of your premake script:

```lua
conan_debug   = include_conan "conan_debug/conanbuildinfo.premake.lua"
conan_release = include_conan "conan_release/conanbuildinfo.premake.lua"
```

Projects can reference Conan variables like so:

```lua
        libdirs {
            conan_debug.libdirs
        }
```

It's not the most elegant solution, but it's working for me so far. Not sure if I should close the issue.

**Comment by SSE4** [comment] 2020-03-07 06:35
I think **premake** generator was designed as a single configuration. it should be possible to build **premake_multi** on top of it (just like **cmake_multi** or **visual_studio_multi**).

**Comment by memsharded** [comment] 2020-03-08 23:01
Yes, what @Zeenobit exposed above is more or less what the ``xxx_multi`` generators are doing internally, so seems indeed possible. Actually, for ``xxx_multi`` generators, it might be possible that in Conan 2.0 they become the default (and only?) ones. If this functionality is important to you @Zeenobit, would you like to try to contribute such ``premake_multi`` generator to Conan? It seems a valid issue, but our backlog is huge, so contributions would be appreciated here.

**Comment by memsharded** [comment] 2024-12-29 23:55
The ``PremakeDeps`` generator in Conan 2 aims to be a "multi-config" generator.  Still needs some maturing and iteration, but the generator is there: https://docs.conan.io/2/integrations/premake.html
Closing this ticket, please create new tickets against the new generator if necessary. Thanks for your feedback.

**Closed by memsharded** 2024-12-29 23:55 UTC
Labels: priority: low, type: feature, stage: queue, complex: medium, component: Build
