### ISSUE TITLE
Block [requires] of conaninfo.txt file is not handled

### ISSUE THREAD

**Issue by cvignol** [conan-io/conan#8325] opened 2021-01-12 15:31 UTC
### Environment Details
  * Operating System+version: ubuntu16 64bits
  * Conan version: 1.28.0
  * Python version: 3.5

### Steps to reproduce

- Module A depends on Module B with version in minor_mode
  - Module A -> conanfile.py -> package_id() -> self.info.requires["Module B"].minor_mode
  - package generated for Module A -> conaninfo.txt contains [requires] block with Module A/1.1.Z -> that's right :-)
- Module C depends on Module A
  - Module C want to use pre-packaged Module A
    - Module C don't know that Module A depends on Module B and version compatibility constraints
  - Dependency resolution fails for Module A because the package_id calculated for Module A not match :-(
    - the reason is the block [requires] of Module A conaninfo.txt is not taken into account and the minor_mode info is ignored
    - **method loads() of ConanInfo use hard coded "semver_direct_mode" instead of information coming form [requires] block**

**Comment by memsharded** [comment] 2021-01-13 01:30
Hi @cvignol 

I am not sure I fully understand the issue. The ``package_id_modes`` that are defined in the recipes ``package_id()`` are not transitive. What you declare in ``ModuleB`` applies only to ``ModuleB``, but indeed any consumer of ModuleB would have the default ``semver_direct_mode`` unless they change it.

This test is working:

```python
def test_transitive_mode():
    # https://github.com/conan-io/conan/issues/8325
    client = TestClient()
    client.save({"conanfile.py": GenConanfile()})
    client.run("create . pkga/1.0@")
    pkgb = GenConanfile().with_requires("pkga/1.0")\
                         .with_package_id('self.info.requires["pkga"].minor_mode')
    client.save({"conanfile.py": pkgb})
    client.run("create . pkgb/1.0@")
    client.save({"conanfile.py": GenConanfile().with_requires("pkgb/1.0")})
    client.run("create . pkgc/1.0@")
```

We would need something that we can reproduce, please have a look at the test, and try to provide with recipes and exact commands to reproduce the issue. Many thanks!

**Comment by cvignol** [comment] 2021-01-13 07:53
Hi @memsharded and thanks for this quick reply

Il will try to fulfill your test sample to be able to produce the problem (I'm not fully aware about python, I'm using conan via CMake module able to install and export pkg)

For the moment I can add a precision regarding your test sample
The problem will occur if you export binaries built from pkgb and when you try to install pkgc, the requires on pkgb will not be resolved since pkgb depends on pkga in minor_mode
To fix it I need to explicitely add 'self.info.requires["pkga"].minor_mode' also for pkgc, despite this information is into the conaninfo.txt of pkgb ([requires] block)

**Comment by memsharded** [comment] 2021-01-13 10:40
Hi @cvignol 

It would be great if you could explicit what you mean in ``if you export binaries built from pkgb and when you try to install pkgc``.

Is is "export binaries" a ``conan export-pkg`` command? Are you executing a ``conan install .`` for pkgc instead of creating a package (in that case, the ``package_id()`` of pkgc is irrelevant, because a package is not being created.

If you don't know much python, it is fine don't worry about it, but you can paste here the actual conanfile.py that you are using, plus the exact commands you are using to get that error, and I will code that into a test for you.

**Comment by cvignol** [comment] 2021-01-13 11:17
Yes, I confirm
pkgb "export binaries" means `conan export-pkg` (as for pkga)
pkgc use `conan install` of pkgb

**Comment by memsharded** [comment] 2021-01-13 11:32
Ok, I have incorporated that into the test, still passing fine, this is the current test:

```python
def test_transitive_mode():
    # https://github.com/conan-io/conan/issues/8325
    client = TestClient()
    client.save({"conanfile.py": GenConanfile()})
    client.run("export-pkg . pkga/1.0@")
    pkgb = GenConanfile().with_requires("pkga/1.0")\
                         .with_package_id('self.info.requires["pkga"].minor_mode')
    client.save({"conanfile.py": pkgb})
    client.run("export-pkg . pkgb/1.0@")
    client.save({"conanfile.py": GenConanfile().with_requires("pkgb/1.0")})
    client.run("install .")
    print(client.out)
```
Outputs:
```
conanfile.py: Installing package
Requirements
    pkga/1.0 from local cache - Cache
    pkgb/1.0 from local cache - Cache
Packages
    pkga/1.0:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
    pkgb/1.0:7a295e38f67ab11f20e4d00c956ccbf105042b5d - Cache

Installing (downloading, building) binaries...
pkga/1.0: Already installed!
pkgb/1.0: Already installed!
```

Still need more details to reproduce the issue. When you say "pkgc use conan install of pkgb", I understand you are running ``conan install .`` in your terminal when you have the conanfile.py of pkgc in the current folder, isn't it?

**Comment by cvignol** [comment] 2021-01-14 11:13
Yes it is.

I will probably be clearer if I explain the real case

Package A is OpenSSL
- local conanfile.py for OpenSSL
  - contains `package_id()` without any specific option regarding the version
- build OpenSSL for my platform
- export OpenSSL package (`conan export-pkg`)
- store it on the server (`conan upload`)

Package B is POCO
- local conanfile.py for POCO
  - contains OpenSSL requires
  - contains `package_id()` with minor version restrictiction for OpenSSL (`self.info.requires["OpenSSL"].minor_mode()`)
- `conan install "local conanfile.py"` ok
- build POCO for my platform
- export POCO package (`conan export-pkg`)
  - the package_id of POCO is calculated with the OpenSSL minor_mode "option"
- store it on the server (`conan upload`)

Package C is a functional package
- local conanfile.py for PkgC
  - contains POCO requires
  - contains `package_id()` without any specific option regarding versions mode
- `conan install "local conanfile.py"` **fails for POCO**
  - because the package_id calculated for POCO requires at this moment not handle the OpenSSL minor_mode "option"

To solve it I need to add `self.info.requires["OpenSSL"].minor_mode()` in the PkgC conanfile.py `package_id()` that is wrong from my point of view because PkgC don't know that POCO depends on OpenSSL and the OpenSSL minor_mode information is stored into the [requires] block of conaninfo.txt file stored on the server for POCO package ( [requires] block contains OpenSSL/1.1.Z )

And more precisely my question is why the line
`result.requires = RequirementsInfo(result.full_requires, "semver_direct_mode")`
of `ConanInfo::loads()` is not
`result.requires = RequirementsInfo(result.full_requires, parser.requires)`
(for sure we need to modify the source code of `RequirementsInfo` )

**Comment by memsharded** [comment] 2021-01-14 11:57
I still cannot reproduce the problem, so it is very difficult to know. The scenario that you are describing above is what I have implemented in my test, and it is behaving ok. Is it possible that you are not passing to ``conan export-pkg`` the same input configuration (profile, settings, options) you are using for the ``conan install``?

The problem should be reproducible with dummy recipes, containing just the lines of the ``package_id()`` method, and having the full install and export-pkg commands (including all arguments), as well as the output logs might help to identify some missing detail that we are missing.

The lines that you are describing doesn't seem connected, changes in consumer package_id() are not related on how the intermediate node package_id is computed. We really need to reproduce the failure with a test first. Thanks for all the feedback!

Edit: For the record, this is the current test:

```python
def test_transitive_mode():
    # https://github.com/conan-io/conan/issues/8325
    client = TestClient()
    client.save({"conanfile.py": GenConanfile()})
    client.run("install .")
    client.run("build .")
    client.run("export-pkg . openssl/1.0@")
    poco = GenConanfile().with_require_plain("openssl/1.0")\
                         .with_package_id('self.info.requires["openssl"].minor_mode')

    client.save({"conanfile.py": poco})
    client.run("install .")
    client.run("build .")
    client.run("export-pkg . poco/1.0@")
    client.save({"conanfile.py": GenConanfile().with_require_plain("poco/1.0")})
    client.run("install .")
    print(client.out)
```

**Comment by cvignol** [comment] 2021-01-15 13:20
I have made a lot of changes in my project and I am not able to reproduce the problem again :-(
I think that it will be occur again and at that moment I would record all the elements necessary for its analysis.
Sorry to bother you for this false problem.

I have a quick additional question regarding package_id calculation
If I export the package **PkgC** that depends on **Poco 1.9.0** (with `self.info.requires["openssl"].minor_mode`), that depends on **OpenSSL 1.0.2h**
**I have the same package_id** as
If I export the package **PkgC** that depends on **Poco 1.9.4** (with `self.info.requires["openssl"].minor_mode`), that depends on **OpenSSL 1.1.1i**
Is it normal ? Due to the default 'semver_direct_mode' ?

**Comment by memsharded** [comment] 2021-01-15 15:47
> I have made a lot of changes in my project and I am not able to reproduce the problem again :-(
I think that it will be occur again and at that moment I would record all the elements necessary for its analysis.
Sorry to bother you for this false problem.

No problem, glad to help. Sure, if it happens again, please try to capture recipes, exact command and full output, that helps a lot to reproduce.

Regarding your question, yes, exactly because default ``pkgc`` mode is ``semver_direct_mode``, which means that its binary will only be affected by the major version of its inmmediate dependencies, but not the transitive ones. In this case, it will be hashing only ``poco/1.Y.Z`` in both cases, resulting in the same package_id for 1.9.0 and 1.9.4.

This default was stablished a long time ago, and following the official semver specification made a lot of sense, in which the only breaking versions are the major ones. Then later we realized that for native C and C++ binaries it doesn't hold, but it was not possible to change that default without breaking, so we implemented the global ``default_package_id_mode``. It is likely that Conan 2.0 will change this default.

**Comment by memsharded** [comment] 2024-12-20 00:17
Closing as resolved back then, also Conan 2 changed a lot of these things, so this is outdated too.

**Closed as completed by memsharded** 2024-12-20 00:17 UTC
Labels: stage: triaging
