### ISSUE TITLE
build_requires not considered in build-order

### ISSUE THREAD

**Issue by fourbft** [conan-io/conan#5474] opened 2019-07-11 15:03 UTC
I've noticed a conan behavior, that I would consider a bug. This should apply to all OSes.
When a package "build_requires" another package, this does not seem to be considered in the "conan info --build-order" output.
Simple example: I have a CA package and a CB package that "build_requires( CA)".
When I then create a conanfile.txt that requires both, CA and CB and ask for the build order with "conan info conanfile.txt --build-order=ALL", conan sais:
[CA/1.0.0@user/testing, CB/2.0.0@user/testing]
i. e. both packages in one stage, so according to this I could build them in parallel, which does not make much sense, because CB needs CA as a build requirement.

For comparison, when CB requires CA (not build_requires), then "conan info conanfile.txt --build-order=ALL", of course, sais:
[CA/1.0.0@user/testing], [CB/2.0.0@user/testing]

I understand that build_requires() are "private" requirements, but for a build-order, where private requirements are present in the build-order list, they should be placed correctly, in my opinion.

To help us debug your issue please explain:

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [X] I've specified the Conan version, operating system version and any tool that can be relevant.
- [X] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by jgsogo** [comment] 2019-07-18 09:53
Hi, @fourbft! I'm not able to reproduce the issue you reported (with the current `develop` branch). Can you provide a minimal reproducible example? Thanks!

**Comment by fourbft** [comment] 2019-08-13 14:51
Sorry, was away for some time. Below I attach a tar-archive with an example to reproduce the bug.
[20190813-conan_bug_demo-build_order_with_build_requires.tar.gz](https://github.com/conan-io/conan/files/3497504/20190813-conan_bug_demo-build_order_with_build_requires.tar.gz)

**Comment by jgsogo** [comment] 2019-08-13 15:44
PR #5619 should reproduce the issue. I'm waiting for the CI to confirm and I will label this accordingly.

Thanks a lot! 😊

**Comment by fourbft** [comment] 2019-08-14 11:46
> PR #5619 should reproduce the issue. I'm waiting for the CI to confirm and I will label this accordingly.

Yes, looks good! Thanks a lot for addressing the issue!

**Comment by memsharded** [comment] 2019-10-16 10:06
Hi @fourbft 

I have been checking this issue and the test in https://github.com/conan-io/conan/pull/5619.

``conan info`` is hardcoding ``--build=missing`` internally, as long as the packages have binaries, the build requires are not resolved and not taking into account for the order, this is why that order.

``conan info --build-order`` is almost considered deprecated, and will be removed in Conan 2.0.

Have you tried the new lockfiles functionality? This work fines and return the correct build order:

```bash
$ conan graph lock conanfile.txt --build
$ conan graph build-order . --build
```

This command also have a json output if wanted.

This new command has also very big advantages:
- It can correctly process the ``--build`` logic, and will output the nodes that really need to be rebuilt, according to the ``package_id()`` and the ``default_package_id_mode``
- The locking mechanism actually guarantees reproducibility in different machines, even if new packages are uploaded to servers

Please have a look and check if it works for your case. Thanks!

**Comment by memsharded** [comment] 2019-10-16 10:25
Test that demos the order is correct with the new command: https://github.com/conan-io/conan/pull/5916

**Comment by jgsogo** [comment] 2019-10-23 16:42
#5916 has been merged, shall we add a deprecation notice to the `conan info --build-order` command? We need some extra action to attend this issue.

**Closed** 2019-10-25 13:56 UTC
Labels: complex: medium, component: graph, priority: high, stage: queue, type: bug
