### ISSUE TITLE
Build in Docker container - conan module

### ISSUE THREAD

**Issue by madpipeline** [conan-io/conan#1626] opened 2017-08-17 18:55 UTC
Here's an idea: Have a conan module, a build helper, if you will (naming not clear), that will allow to run the `build()` step inside a Docker container.

The purpose of this is to ensure that the profile settings are true, and the environment is exactly that. This would ensure that the build is done with the exact compiler desired, using the right gLibC, and the exact environment.

----

Here's a draft of how this would work:

In the default `settings.yml` to have under `os:` another entry `Docker:` with a child `image: ANY`. Or under `Linux:` to have a `dockerimage: ANY`. I'm not sure which is better. The image can be a **Linux** or a **Windows** image. So it may be useful to have it on it's own, or as a child of each.

Via profile files or command line argument, this can be set to use any Docker image, and the recipe can treat it if specified.

This module is to be imported, and would be used something like this:
```
from conans import Docker
...
build(self):
    cmake = CMake(self)
    if self.settings.os.docker:
        container = Docker(self)
        container.loadCMakeConfig(cmake)
        volumes = ["some/path"]
        container.mountVolumes(volumes)
        container.runCommand("cmake hello %s" % cmake.command_line)
        container.runCommand("cmake --build %s" % cmake.build_config)
    else:
        cmake.configure()
        cmake.build()
```

The container would be started with the following:

Paths to be mounted:
* self.source_folder
* self.build_folder
* self.package_folder
* CONAN_USER_HOME

Environment variables set:
* CONAN_USER_HOME

Other arguments:
* `--tty`
* `--interactive`
* `--rm`
* `"--user %s:%s" % (os.getuid(), os.getgid())`
* `--network host`

What do you think?

**Comment by lasote** [comment] 2017-08-18 06:03
My first thoughts:

- The idea of a Docker() helper could be interesting, but not coupled to any settings change, at least in the conan base code, any user is free to customize the **settings.yml**, but for me, it is not clear enough that we should consider a docker image as a setting.
- The volumes are sometimes a nightmare sharing files because of the permissions, in the conan_package_tools I've workaround the problem hacking some default user IDs, but it's far from being optimal.
- I'm not sure that it fixes your concerns about the wrong profiles and the glibc. If the users try to reuse the conan packages built in a Docker container in the native computer maybe they will have ABI incompatibilities if they have outdated/different operating system versions and they do not specify the right profile. So the problem will be the same. If you only want to ensure that the generated packages match the settings, why don't you run Conan inside a docker container? (That's what conan package tools does)
- Maybe we don't need a Conan helper, you could install this and play: https://docker-py.readthedocs.io/en/stable/

**Comment by memsharded** [comment] 2017-08-18 23:53
I agree with:
- it doesn't fully address the wrong profiles concerns
- not necessary to add it to the default settings.yml, as it is basically useless for a wider community, unless the docker images where referenced by their public URLs

The point that sharing files, permissions, etc, is complicated, might be a good reason for this feature, so a helper can manage these issues. Also I would like to learn about the reasons for not just running conan inside the container. Maybe that approach, or some automation to simplify that approach would be useful.

**Comment by lasote** [comment] 2017-08-19 08:00
> The point that sharing files, permissions, etc, is complicated, might be a good reason for this feature, so a helper can manage these issues. 

The problem is that those things are not improved with a helper, you have to hack the docker images that you are going to use.

**Comment by memsharded** [comment] 2023-05-31 10:08
The usage of Conan running inside docker has stablished as the way to use conan + docker, it seems this ticket is very outdated, closing it as not planned, thanks!

**Closed by memsharded** 2023-05-31 10:08 UTC
