### ISSUE TITLE
CMake generator passes include directories to gcc command line via -isystem when conan_basic_setup(TARGETS) macro is used, and CONAN_SYSTEM_INCLUDES has no affect

### ISSUE THREAD

**Issue by omicronns** [conan-io/conan#1318] opened 2017-05-23 13:53 UTC
When using target based approach for linking dependent libraries, CMake invokes build command with include paths passed via ```-isystem``` instead ```-I``` option, regardless of ```CONAN_SYSTEM_INCLUDES``` variable. #272 pull request solves this issue for non target approach.

**Comment by memsharded** [comment] 2017-05-23 14:24
For the targets approach, it is doing a ``set_property`` of ``INTERFACE_INCLUDE_DIRECTORIES``. It doesn't seem possible to add ``SYSTEM`` to that property definition, I can't find any documentation or example about it. Is it possible?

**Comment by omicronns** [comment] 2017-05-23 16:58
I couldn't find a way to disable this behaviour either. But it makes impossible to use C++ templates from packages linked using targets approach, because ```-isystem``` is default in this case.

**Comment by omicronns** [comment] 2017-05-23 17:04
The issue title wasn't accurate, so I corrected it.

**Comment by memsharded** [comment] 2017-05-23 18:29
Had another look, still no idea how to fix it, it seems something in CMake internals. Some cmake expert there that could help?

**Comment by sixten-hilborn** [comment] 2017-05-23 20:41
I'm no expert but I just found this: https://cmake.org/cmake/help/v3.8/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html

So default behavior for CMake is to use `-isystem` with GCC for imported targets, _unless_ `CMAKE_NO_SYSTEM_FROM_IMPORTED` is true or property `NO_SYSTEM_FROM_IMPORTED` is set explicitly on the _importing_ target.
It's not possible to set the `NO_SYSTEM_FROM_IMPORTED` property on an "imported interface" target in CMake before [3.8.0](https://gitlab.kitware.com/cmake/cmake/merge_requests/270). So until 3.8.0 the consumer needs to set `NO_SYSTEM_FROM_IMPORTED` themself since the purpose of `conan_basic_setup(TARGETS)` is to avoid global settings like `CMAKE_NO_SYSTEM_FROM_IMPORTED`.
Note that using `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES` will force `-isystem` even if `NO_SYSTEM_FROM_IMPORTED` has been set.

**Comment by sixten-hilborn** [comment] 2017-05-23 20:46
Based on these facts I'm not convinced that `CONAN_SYSTEM_INCLUDES` should be used/allowed for `TARGETS`. If `CONAN_SYSTEM_INCLUDES` is set a helpful message about `NO_SYSTEM_FROM_IMPORTED` and SYSTEM being default can be displayed.

**Comment by blastrock** [comment] 2018-04-04 19:26
I have this exact problem too, I am hit by #269 .

Since I am cross-compiling, I have a toolchain recipe which sets up a cmake toolchain file through CONAN_CMAKE_TOOLCHAIN_FILE. My compiler is broken, so I might as well disable -isystem on all targets compiled with this toolchain, and I am ok with defining `CMAKE_NO_SYSTEM_FROM_IMPORTED` in my toolchain recipe.

Could we have a `self.env_info.CONAN_CMAKE_NO_SYSTEM_FROM_IMPORTED` that could be passed to cmake, like `CONAN_CMAKE_TOOLCHAIN_FILE`?

Moreover, I don't know if there is already a discussion about that, but could we have a generic way to pass cmake options from environment variable (or anything else that I can write in a conan recipe)?

**Comment by memsharded** [comment] 2018-04-04 21:49
Thanks for the new feedback @blastrock 

Regarding this issue, I think this is actually a duplicate of https://github.com/conan-io/conan/issues/2629, which has some more modern feedback, and is right now labelled as "good first issue" which means it is approved feature. If it is the same, maybe this issue could be marked as duplicate and follow conversation there, please check. Also it is not fully clear why to define another CMAKE_NO_SYSTEM_FROM_IMPORTED  variable, and not using the already existing CONAN_SYSTEM_INCLUDES, but make it affect the targets too.

The issue for cmake from environment variables indeed deserves its own issue. Right now there is no out of the box way to do it. Not sure about the scope, but definitely worth investigating and discussing. Please open a dedicated issue for it. 

Many thanks!

**Comment by memsharded** [comment] 2022-08-25 22:52
This integration is legacy, closing.
The new CMakeDeps should be used, please report against it.

**Closed by memsharded** 2022-08-25 22:52 UTC
Labels: help wanted, Feedback please!
