### ISSUE TITLE
[question] How to filter files/folders using SCM feature

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#8214] opened 2020-12-15 23:17 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

Trying to use [SCM feature](https://docs.conan.io/en/latest/creating_packages/package_repo.html#capturing-the-remote-and-commit-scm) and value of entry `url`, and `revision` both set to `auto`.

Then during export, it copies local source folder, but copies **everything** in this folder. How to exclude files and folders from this local-folder copy that happens during the SCM "Getting sources from folder" phase?

In the normal `export_sources` use-case, one can define _include_ and _exclude_ filters. I would like to define the same style of filters for the SCM feature when it copies local folder to the cache. Maybe always applying this filtering even after the SCM source checkout as well.
Is this currently possible? I cannot find documentation about this.

Also looking at the code  https://github.com/conan-io/conan/blob/ddf9cca9ea45879986adec8b0308a0519226bbac/conans/client/cmd/export.py#L443-L444 I can see that some files are added to the exclusion list, but this is internal and not accessible to package creators.

**Comment by memsharded** [comment] 2020-12-21 22:29
Hi @SeanSnyders 

The local copy of the folder will exclude the ``.gitignore``d files. The idea is to reproduce what will happen when the repo is cloned. When at some point the package needs to be build from source in the cache, it will do a ``git clone``, that will get the files except the gitignored ones. 

If you want to avoid copying some files or filtering them, have you tried adding the files you want to filter to the ``.gitignore`` file?

**Comment by SeanSnyders** [comment] 2020-12-21 23:19
Cloning the repo is fine and I understand that intent, but what if not all the files in the repo are destined to be considered "source" to be copied to the cache location? So not using git for filtering, but a Conan mechanism similar to `export_sources`? Also sounds very git specific.

**Comment by memsharded** [comment] 2020-12-22 00:11
It doesn't matter if all files in the repo are intended to be used or not. When using the ``scm`` mechanism, only the coordinates (url, commit) of the repo will be stored, but not the files. When the ``git clone`` is executed in the cache to get the sources, it will result in something. The local copy of the sources is an optimization, to avoid doing a clone of the local repository (and requiring a commit for every change), but the files that end in the cache, should be the same in either case (git clone from the remote, or copying files from the local checkout in user folder), to achieve reproducibility. 

This is "scm" specific, indeed, it will work for the implemented scms, that is, both git and svn.  

Please let me know if this clarifies something.

**Comment by SeanSnyders** [comment] 2020-12-22 20:43
I understand your further explanation, thanks.

Nonetheless, I'd still advocate for the ability to filter the contents of the repo **post clone**. This is an ability that is possible via `export_sources`, which is a route that can be used in conjunction with SCM as a backend as well, so not sure why the `scm` feature would not allow native filtering in similar fashion.
Allowing filtering post clone would not negate reproducibility, as the filtering is indeed specified in the recipe and always executed for local source copy or scm clone routes.

**Comment by solvingj** [comment] 2021-02-11 16:06
@SeanSnyders you make a valid point and you are not alone. Multiple enterprise users are trying to implement SCM feaure and sharing your issue. First, many repositories have subdirectories with large/numerous files that they don't want to export.  Second, and equally important, is that they don't want `README` or `Jenkinsfile` changes resulting in a new Conan `RREV`. Seems like two common situations, and a clear area where one might suggest change to SCM feature. 

Unfortunately, the technical details of the current implementation make it far more challenging to imagine any kind of change than one might expect. More importantly, any suggestions to decouple the "sources used by Conan" from the "sources in the SCM revision" run counter to the nature of the SCM feature. They're tightly coupled by design, and that design provides a number of important guarantees to the current users. 

Instead, I think `exports_sources` is far closer to being what you need. Take a moment and consider why you want to move to SCM in the first place.  

What many people (myself and others I've talked to) like about SCM and want from it is actually quite simple. It can capture and store the SCM URL and revision with the package so that it could conceivably be recovered and used later to perform a "restore" of the original workspace it was created from.  That's it. Many just want `exports_sources` with a native, declarative mechanism for also capturing and storing the SCM metadata along with the package. 

As I said, there are many users who use the current SCM feature and rely on a bunch of it's assumptions, guarantees, and features it provides. I think it's good, and I don't think it's worth it to add complexity to that feature. 

Instead, please think about what minimum functionality you actually want from SCM feature (beyond what `exports_sources` provides) for your case and elaborate if you can.  If it's similar to what I've described, maybe we'll put in a feature request for an enhancement to exports_sources, to somehow add scm metadata to it.

**Comment by SeanSnyders** [comment] 2021-02-21 20:35
Thank you for the considered response.

With the current implementation of the SCM feature of Conan, it prescribes a certain use of a repo: all code therein is destined for the Conan package. I do not believe this to be the best and most flexible way and inherently makes assumptions about a team/project's use of a repo.

A repo can contain a multitude of resources, all that form part of the project but not necessarily something that is targeted to be used in generating a package. Maybe there are even more than one package being built from the same repo - they are project related, but are versioned and packaged independently. Just giving examples to support my statement in the previous paragraph.

What I want from the SCM feature is:
- SCM url
- commit hash

This gives me metadata about what exact commit was used as a basis for the package.

What I want from the `exports_sources` feature is:
- filtering

This is taken as a post step on top of the SCM commit hash, and thus delivers the specific subset of sources that are used for the package, and thus creates the revision.
If the filtering changes, the revision should change.

**Comment by solvingj** [comment] 2021-02-22 14:34
Thank you for sharing your use case. This confirms it is similar to what many people want.

Can you also confirm that the following is true for your case:

If there are multiple commits in a row for which neither the `conanfile.py` or any of the sources change, and thus hash of the exports directory is the same, that Conan would produce the same revision?  For example, README changes would not require a rebuild.  

One of the subtle "guarantees" of the SCM feature was that each unique GIT Commit is guaranteed to produce a unique Conan revision, regardless of what changed.  Even an empty commit or a merge commit would result in a new Conan revision.   This one-to-one relationship has appeal to some users, so they can deterministically identify "this Conan revision maps to one (and only one) GIT revision".  

One of the implications of what we're saying here is that, one Conan revision could no longer be mapped to a single GIT revision. Instead, many GIT revisions could produce the same Conan revision. This has appeal to other users for other reasons.  Many users don't care that there is a 1-to-1 relationship, just that users can analyze a given package and detect precisely which GIT commit it was actually built from.  This would still be possible if Conan could simply "capture/tag" the package with the SCM revision at the time of creation.  It does not need to tightly couple it into the hash as it currently does.  I just want to confirm that you were aware of this implication, and this would be expected/acceptable behavior.

**Comment by SeanSnyders** [comment] 2021-03-01 08:42
Yes, I believe what you mention is congruent with what I would expect.

No changes (hash) based off the git sha and filters should produce the same conan revision.

Many to 1 relationship.

**Comment by n00b42** [comment] 2021-10-28 08:30
@memsharded Should the .gitignored files already be ignored? (At least did not work for me. SCM gitignore seems to be tracked by #6617 )

**Comment by memsharded** [comment] 2023-03-15 23:38
``scm`` deprecated in 1.X, removed in 2.0, closing this ticket as outdated.

**Closed as not planned by memsharded** 2023-03-15 23:38 UTC
Labels: stage: triaging
