### ISSUE TITLE
How to handle "Filename too long" when unzipping source archive

### ISSUE THREAD

**Issue by Blubbz0r** [conan-io/conan#341] opened 2016-06-21 13:00 UTC
I'm currently trying to do a simple Qt build using conan, however, I'm facing the issue that some of the file paths in the default .zip package provided by Qt are extremely long (e.g. %conan_source_dir%\qt-everywhere-opensource-src-5.7.0\qtwebengine\src\3rdparty\chromium\third_party\WebKit\Source\core\css\resolver\StyleResolverParentScope.cpp).

In conans/tools.py, the file name is limited to 200, which is easily exceeded. What would your recommandation be in this case?

Also: Wouldn't it make sense to fail fast in unzip in case of such an error?

**Comment by memsharded** [comment] 2016-06-21 14:37
Hi! I think this is almost a duplicate of #311, would you mind to add there you comment? Thanks very much!

**Closed by memsharded** 2016-06-21 14:37 UTC

**Comment by Blubbz0r** [comment] 2016-06-21 15:16
Thanks for the info. osechet's comment already summarizes the problem very well, no need to duplicate it with my comment in my opinion. What about the "fast failing of unzip" bit? Don't think that it would make too much sense to put it into the other issue. Should it be put into a separate issue to discuss it?

**Comment by memsharded** [comment] 2016-06-21 15:49
Thanks for the feedback. Not totally sure about fail fast. I think that e.g. the Boost package build fails to unzip some docs due to this limit, but the build is still fine.
Also, this would be a small UI improvement, though the limit issue has to be solved for projects as Qt, so it makes sense to spend the efforts in that big feature. I have some ideas for it, but still not time to implement them. It will not make into next release 0.10, which will be very soon, but will try for 0.11.
