### ISSUE TITLE
[question] 'build_modules' of `build_requires` are not included when building consumers with build/host profiles

### ISSUE THREAD

**Issue by DukeOfKirkcaldy** [conan-io/conan#7719] opened 2020-09-17 14:30 UTC
I'm experimenting with the build and host context profiles and many of my builds are breaking due to the changes in how `build_requires` are handled.  So I'm just trying to understand if this is intentional and whether I need to update my recipes.

For example, I have a tool which is used to generate source code from .xml files in the consumer's repository.  The sources are then compiled into a static library and packaged.  Since consumers only need this tool when building from sources, they have it defined as a `build_requires`.  (Though since the code generator version can have an affect on the code, I'm wondering if it should actually be a normal `requires`? )

To simplify it's usage for consumers, the tool package provides functions to consumers through a `build_module`.  But now it seems that `build_module`s of `build_requires` dependencies are not included by _conan_basic_setup()_.

My current workaround is to `force_host_context=true` for these dependencies, but I'm not sure if this is the correct way to go about it.

**Comment by memsharded** [comment] 2020-09-17 22:46
Hi @GordonJess 

In theory, if that tool is an executable that is running in the current build machine, then it should be in the build context, not the host context.

You are right, it seems you hit some missing functionality. So far, the ``build_modules`` feature only works without contexts. When using contexts, the ``cpp_info`` is propagated only through the "host" context, but not the "build" one.

We already separated ``settings_build`` and ``settings_target``, it seems that we should keep extending the model for this use case. Having a first look, doesn't look immediate or obvious, we need to investigate what could be the best solution.

**Comment by jgsogo** [comment] 2020-09-18 09:50
Hi @GordonJess 

We are still polishing this feature and we are learning a lot from all these issues and your use-cases, so nothing is written in stone. Said that, this is how I see this scenario:

 * `build_modules` are included by default in the files that are consumed by the build-system, these `build_modules` usually contain information about the package being included in the build: path to libraries, includes, definitions,... so it makes sense that only those from the _host_ context are available and included by default.

 * your tool, like any other source generator, is a perfect example for a `build_requires`, it runs in the _build_ machine and it needs to take the settings from the `--profile:build` while generating the consumer's library. It will be executed in the `build()` method of the Conan recipe, using `self.run("your-tool")` or inside the build-system scripts. Conan will add the path to your executable to the `PATH` and the tool should run without any problem.

And now there are two important things that deserve more attention:

 * **how your tool affects the packageID**: I would say that the XML files your tool uses to generate source files should be contained in the library itself, it is like a `.proto` definition (from protocol buffers): the file that describes the message is inside the library and the `protoc` tool used to generate the actual `.h/.cpp` files is a `build_requires`. 

   In your case, if those XML files are stored together with the rest of the `.cpp/.h` files from your library, then it is clear how to manage them, like any other source file.

   If those XML files are stored together with the tool, then it belongs to a broader discussion about `build_requires`: if they should or not affect the packageID, if it is configurable,... 

 * let's say **your tool provides something** that the build-system is going to consume (probably the most typical scenario here is a compiler that provides a toolchain). This is still an open question and there are different approaches:

   + some packages takes advantage of one environment variable Conan is using: `CONAN_CMAKE_EXECUTABLE`, they populate this variable to their own CMake wrapper and use it to inject the toolchain. You can find this approach working in the [Android NDK recipe by bincrafters](https://github.com/bincrafters/conan-android_ndk_installer). I really don't like this approach, it is coupling the tool with the environment variable and it doesn't scale (it works only for CMake).

   + other packages have moved this file/functions to a `requires`, like the `protobuf` package in ConanCenter. This approach works because the recipe consuming it will **always** require and build-require the `protobuf` package. You need the tool `protoc` and you need to link with the `libprotobuf` library, both of them are inside the `protobuf` package.

   + a more flexible alternative is provided via the `user_info` attribute. The tool can add the path to the assets/resources/files it is providing in the [`package_info()` method](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=user_info#user-info), and consumers can take that information from the [`self.user_info_build` attribute](https://docs.conan.io/en/latest/reference/conanfile/attributes.html?highlight=user_info#user-info-build).

----

I know this is not an answer, I'm just enumerating alternatives, but without further information about your exact use-case I really don't know which one fits better with your libraries and your tool. Feel free to ask more details about any of these approaches, and share the challenges or alternatives you face in your way, I'll be pleased to help (...be patient, I won't be available next week).

Thanks!

**Comment by DukeOfKirkcaldy** [comment] 2020-09-23 09:24
The thing I most liked about `build_modules` is that consumers automatically got access to any variables/functions provided by their `build_requires` dependencies without having to worry about checking certain attributes and passing them into cmake myself.  I'm not sure that I agree that these should only be for dependencies in the `host` context.  Something like the [FindDoxygen](https://cmake.org/cmake/help/latest/module/FindDoxygen.html) module for example is only providing helper-functions for a tool run on the build machine - much like my use case.

> Feel free to ask more details about any of these approaches, and share the challenges or alternatives you face in your way

Thanks!  I've opened some issues  (#7737, #7742) for the other problems I've come across so far using build/host profile.  I've not yet found any workaround for these yet to be able to have something usable, but feels like it's almost there!

**Comment by jgsogo** [comment] 2020-10-29 13:03
`FindDoxygen` is a really good example where CMake relies on the functionality of the `find_package` to get information about tools, basically, any code-generator tool is inside this category and we are suffering the problem with all of them: `protobuf (protoc)` probably is the other big player here.

Here are my thoughts, and I really don't know how to solve the situation without transferring all the responsibility to the user. For example, `doxygen` depends on `zlib`, we agree that the project you are generating can depend on `zlib` too. Conan generates all the `FindXXXX.cmake` files for all the dependencies in your _host_ context, so your project can find the `zlib` packages and link with it. 

Your `CMakeLists.txt` contains something like this:

```cmake
# Get components for some tools
find_package(Doxygen)

# These are your actual dependencies and project
find_package(zlib)
...
target_link_libraries(yourlib PUBLIC zlib:zlib)
```

...but in the filesystem we can have only one file named `FindZLIB.cmake`, if we were running the generators for the packages in the _build_ context, we will override the `zlib` one.

Can we generate only `FindDoxygen.cmake` and forget about the dependencies? It could be a solution, but it won't work with the `protobuf` use case, here the package is the same for the library and the executable, both would generate `FindProtobuf.cmake`, each of them with different/incompatible content.

---

I really think this is a limitation in CMake, and there are some questions asking how they can work around this situation. CMake needs some kind of `find_tool` macro to disambiguate this scenario, that macro would return only tools like `tool::doxygen`, `tool::protoc` and not components you can link with.... and it should use a different `FindToolXXXX.cmake` file (very naïve proposal).

Being a limitation of CMake I wonder if we should totally forget about it and generate all the files, some will override others and the build will fail, but it is the consumer's responsibility to take it into account and take the actions needed to bypass the problem. 

---

For `protobuf` we were able to work around the limitation because the package in the _host_ context contains the functionality to detect `protoc` and return the executable that is already available in the PATH. But this situation doesn't hold for Doxygen, here we are not generating any `FindDoxygen.cmake` file (no `doxygen` package in the _host_ context) that could do the trick.

**Comment by ghost** [comment] 2020-12-22 09:31
Hi, I think I'm struggling with the same issue when trying to crosscompile. I want to use x86 `protoc` binary , my `conanfile.txt` looks something along the lines of: 
```
[build_requires]
protobuf/3.11.4

[requires]
protobuf/3.11.4

[generators]
make

[options]
```
From what I can tell, there is no way to access the `protoc` binary programatically after running:
`conan install . --profile:host .conan/profiles/arm --profile:build .conan/profiles/x86_64`. 

I tried adding this to the conan file, but the copied `protoc` is an arm version from the `requires` section and not from the `build_requires` one
```
[imports]
bin, *-> ./bin
```
 Any thoughts? Am I missing here something?

**Comment by jgsogo** [comment] 2020-12-22 10:09
Hi, @tomerlevv 

Build requires in your example (with a `conanfile.txt` and using two-profiles) should be considered as tools provided by the environment like the `cmake`, `gcc`,... that you can already run using them from the command line (they are already in the PATH).

Conan provides some generators to get the information from those build-requires and provide you with a couple of files to activate and deactivate them, use `-g virtualenv` (or add it to your generators):

```
conan install . --profile:host .conan/profiles/arm --profile:build .conan/profiles/x86_64 -g virtualenv
```

Conan will generate files `activate.sh/bat/ps1` and `deactivate.sh/bat/ps1` that will _activate_ an environment with all the environment variables (and PATH) provided by your build-requires.

With this, you can add to your environment the executables for `protoc` (build machine) or any other build-require you might want to use in your build process, like a different CMake version or the compiler itself.

**Comment by ghost** [comment] 2020-12-23 13:52
Thank you @jgsogo , It seems to be the direction I should take. Currently I am invoking `conan install` from my Makefile, generating a `conan.mak` file. In order to make the suggested solution work I would have to write my own generator which I think I'll pass for now. 

Thanks anyway!

**Comment by jgsogo** [comment] 2021-01-11 16:36
Back to the original question in this issue. Copying here the comment in https://github.com/conan-io/conan/issues/8303#issuecomment-757894304

> We've been talking about this issue (and related ones) and the path will be as follows:
> 
> * Conan will (1.34?) generate a file with all the information from `cpp_info` in plain CMake format. This file will contain the information as plain as possible. It will be hard to define the name of all the variables, but the file will contain information from all the packages in _host_ and _build_ context that are needed to build the package. (Note.- Maybe it is not only one file, but one per requirement, TBD).
> * This file will be accessible only if using generator `CMakeDeps` (in fact, this generator will use that file/s to populate the targets). Generator `CMakeDeps` will be the recommended (only?) one in Conan 2.0 and we encourage everyone to try it and start using it to smooth the migration.
> * User can `include` that file from their `CMakeLists.txt` and will have access to all these variables.
> * Eventually, Conan will provide some abstraction layers on top of this file to provide targets for the components coming from the _build_ context (protoc, doxygen,...). And some convenient CMake functions (`find_package_build`) or overrides (new definition of `find_package`) that will help with these scenarios and make it possible some transparent integration of Conan with existing CMake files.

With this approach, build-modules of packages coming from _build_ context will be available in that file. Those build-modules from the _build_ context won't (probably) be automatically included, but the paths to those build-modules will be available in a CMake variable.

**Comment by DoDoENT** [comment] 2021-03-02 14:41
In our case we avoided the above protobuf issue by splitting protobuf into two packages: `libprotobuf/<version>@company/stable`, containing only the static libraries (libprotobuf) and `protoc/<version>@company/stable`, containing only the `protoc` executable and cmake helper that consumers can use to simply use `protoc` executable to convert their `proto` files into source/header pairs and compile them.

Then, we add `libprotobuf` to the `requires` and `protoc` to `build_requires`.

This works pretty well - the only issue is that `protoc` package still needs to use the old `arch_build/os_build` mechanism in order for the cmake helper to be available for usage in cross-compile scenario. I've reported this bug [here](https://github.com/conan-io/conan/issues/8488) and also provided a simple example that reproduces the issue.

**Comment by DoDoENT** [comment] 2021-03-02 15:08
Regarding the affection of `package_id` by `build_requires` - maybe the package should tell for itself whether it can influence other packages' ID?

For example, a conan package containing tools like `cmake` or `doxygen` would not alter ID of the package that `build_requires` it.
On the other hand, a conan package containing the toolchain, like `android-ndk` or `emscripten` would alter ID of the package that `build_requires` it (it's not the same if you build your package with NDK r22 or NDK r21). However, such packages would also need to have the ability to impose settings on the build graph and maybe influence the package ID in that way.
This is exactly what I proposed [here](https://github.com/conan-io/conan/issues/8274).

**Comment by SeanSnyders** [comment] 2021-04-26 23:40
Here is another repo logged: #8839

**Comment by memsharded** [comment] 2021-05-26 15:04
Hi all,

The new CMakeDeps feature will allow to include find_package() from build_requires, that also could bring their own build_modules, with the syntax:

```python
deps = CMakeDeps(self)
deps.build_context_build_modules = ["foo"]
```

This applies when the 2 build and host profiles are used, and build_requires live in the "build" context. The feature is experimental, but at the moment seem the way to go. It is not possible to provide this in the previous generators, as it would be very challenging to introduce it without breaking.

Please check https://github.com/conan-io/conan/pull/8985 and its documentation, and when it is released, looking forward your feedback. Thanks!

**Closed as completed by memsharded** 2021-05-26 15:04 UTC
Labels: type: look into, type: feature, complex: medium
