### ISSUE TITLE
[python_requires] nested python_requires not working with Conan V1.10.0 anymore

### ISSUE THREAD

**Issue by ahauan4** [conan-io/conan#4087] opened 2018-12-07 15:33 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan 1.10.0
Python: 3.6
OS: Windows 7

Hello,

we use python_requires in a nested way which worked well until Conan 1.9.2 but does not work anymore since Conan 1.10.0.

See the following attachment with a simplified example of what we are doing: [nested_python_requires_not_working_with_conan_1_10_0.zip](https://github.com/conan-io/conan/files/2657758/nested_python_requires_not_working_with_conan_1_10_0.zip)

When you call the following 3 conan commands to build the 3 packages this works well with Conan 1.9.2.

`conan export base user/channel && conan export tooling user/channel && conan create module user/channel`

But with Conan 1.10.0 the following exception is raised:
```
D:\>conan export base user/channel && conan export tooling user/channel && conan create module user/channel
Exporting package recipe
base/version@user/channel: The stored package has not changed
Exporting package recipe
tooling/version@user/channel: The stored package has not changed
Exporting package recipe
module/version@user/channel: The stored package has not changed
Configuration:
[settings]
os_build=Windows
arch_build=x86_64
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=10
build_type=Release
[options]
[build_requires]
[env]

module/version@user/channel: WARN: Forced build from source
ERROR: Traceback (most recent call last):
  File "D:\Python3\lib\site-packages\conans\errors.py", line 24, in conanfile_exception_formatter
    yield
  File "D:\Python3\lib\site-packages\conans\client\graph\graph_manager.py", line 143, in _get_recipe_build_requires
    conanfile.build_requirements()
  File "D:\.conan\data\module\version\user\channel\export\conanfile.py", line 10, in build_requirements
    base.default_build_requirements(self)
  File "D:\.conan\data\base\version\user\channel\export\conanfile.py", line 8, in default_build_requirements
    tooling = conans.python_requires("tooling/version@user/channel")
  File "D:\Python3\lib\site-packages\conans\client\graph\python_requires.py", line 53, in __call__
    self._requires.append(python_req)
AttributeError: 'NoneType' object has no attribute 'append'
```

Could you help us to get Conan 1.10.0 running with our nested python_requires. Until now we are stuck at Conan version 1.9.2.

Thank you!

**Comment by memsharded** [comment] 2018-12-07 18:55
Well, if the use is:

```python
def source(self):
        base = conans.python_requires("MyConanfileBase/1.0@lasote/testing")
```
That usage was forbidden by design, and protected with an override of ``python_requires`` which will fail if used liked that. 
It seems that you avoided that protection by using it directly from ``conans.python_requires``.
The documentation should have commented this behavior, we thought it was not necessary as the protection in code was there.

Could you please comment why are you importing the python_requires there, and not in the global scope, as described in the documentation? There are a few reasons why this is the way python_requires is designed that way. Thanks for the feedback!

**Comment by memsharded** [comment] 2018-12-10 09:03
Hi @ahauan4 

We are considering a PR to be released in the next minor that also activates raising an error for local ``conans.python_requires()`` calls, as said, it is problematic. Please check, thanks.

**Comment by ahauan4** [comment] 2018-12-10 09:50
Hello @memsharded,

the reason for us to import the "tooling" package with python_requires in the "default_build_requirements" function in the "base" package is that we call this function only from modules which call build_requirements. Note all packages need this function and therefore not the "tooling" package. A second reason is, that we use other functions from our base package like "get_version_from_scm", which is also used by the "tooling" package itself. If we would define python_requires("tooling") always at top of the "base" package python file, we could not use the "base" package from the "tooling" package (where we need "get_version_info"). Otherwise we would have a circle dependency.

**Comment by memsharded** [comment] 2018-12-10 10:07
Hi @ahauan4 

The problem is that you really have a circular dependency, which cannot be managed by Conan, by design (and up to my knowledge, other package managers in other languages and systems, can't do it either), and it will never will. 

The circular dependency is there, but you are workarounding it via local imports, and that is one of the reasons the protection was put in place, to clearly avoid this problem, but you also workarounded the protection 😅  

I am sorry, but it is very important that those circular dependencies are untangled. I'd suggest extracting the conflicting thing to its own python_require package to break the loop. Or just put everything in a single python-requires. It is likely that it will be much simple to manage, and the impact on speed, etc, is almost None.

**Comment by memsharded** [comment] 2020-08-03 08:48
Hi @ahauan4 

python_requires have been completely re-designed since then, and now are declared with class attribute syntax. Please have a look at https://docs.conan.io/en/latest/extending/python_requires.html. The new syntax supports nested python_requires.

I think this issue can be closed now, but please re-open or submit a new issue if you have any question about this. Thanks!

**Closed by memsharded** 2020-08-03 08:48 UTC
Labels: type: question
