### ISSUE TITLE
[feature] Suggestion: MSDeps Builder should use %UserProfile% variable in vars.props

### ISSUE THREAD

**Issue by Maju-Ketchup** [conan-io/conan#17182] opened 2024-10-17 08:58 UTC
### What is your suggestion?

Currently the from MSBuildDeps generated property files include the Home-Path directly (e.g. `C:\Users\XXXX\.conan2`).

When cooperating on a VS Project via GIT this leads to Problems that everyone needs to generate these files again.
This is not possible with the extention whten these property files are deleted and since they are linked in the solution starting a build process is impossible.
Another Issue which this suggestion solves is that when you push the code to the repo, your username is not included in the code.

There are two possible solutions to this issue:

1.) Instead of using (`C:\Users\XXXX`) you could use the `%UserProfile% `Variable already available from Windows
2.) Create a system (or User) Variable during the installation of Conan (e.g. `%ConanHome%`) and use this in the  property files.

### Have you read the CONTRIBUTING guide?

- [x]  I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-10-17 09:00
Hi @Maju-Ketchup 

Thanks for your feedback, moved the ticket to Conan repo.

**Comment by memsharded** [comment] 2024-10-17 09:01
I think this might be a duplicate of https://github.com/conan-io/conan/issues/15606, please check it, read the discussion there.
If duplicate, lets close this one and follow up in the other ticket.

**Comment by Maju-Ketchup** [comment] 2024-10-18 05:47
Indeed it is a duplicate! Did the search before. But wrote the title after the post, so that I had not used the correct Keywords.

**Comment by memsharded** [comment] 2024-10-18 11:23
Great, then lets close this ticket as duplicate and follow up in the other one.
As you can see, there is a discussion there, about the non-relocatability of the generated files and how it is necessary to re-generate them anyway, rendering the UserProfile pointless. Please read the discussion and comment there. Thanks for your feedback!

**Closed as not planned by memsharded** 2024-10-18 11:23 UTC
Labels: duplicate
