### ISSUE TITLE
[bug] `<host_version>` ignores `@user/channel`

### ISSUE THREAD

**Issue by DoDoENT** [conan-io/conan#15292] opened 2023-12-18 12:01 UTC
### Environment details

* Operating System+version: MacOS 14.2
* Compiler+version: apple-clang 15.0.0
* Conan version: 2.0.14
* Python version: 3.11.5

### Steps to reproduce

Let's just use the example from the [official documentation](https://docs.conan.io/2/reference/conanfile/methods/build_requirements.html#host-version).

Simply, change the override in the app's conanfile to the internal company version of protobuf, e.g.

```python
from conan import ConanFile

class myappRecipe(ConanFile):
    name = "myapp"
    version = "0.1"
    def requirements(self):
        self.requires("mylib/0.1")
        self.requires("protobuf/3.21.9.1@company/stable", override=True)
```

The override and conan installation will fail because _mylib_ will tool-require `protobuf/3.21.9.1` (which does not exist) instead of `protobuf/3.21.9.1@company/stable`.

I guess the `<host_version>` placeholder should contain both the version and `@user/channel` in that case.

However, I'll be also OK with the solution with multiple placeholders, e.g. `protobuf/<host_version>@<host_user>/<host_channel>`, but I think the former should be simpler to use and implement.

**Comment by AbrilRBS** [comment] 2023-12-18 17:09
Hi @DoDoENT thanks a lot for your report.

We have just merged an extension to ``<host_version>``, and checked this. This doesn't seem a bug, but expected behavior.

The ``<host_version>`` mechanism is a versioning  mechanism. Similar to version ranges. It is explicitly designed to get the version of the "build" context requires, but not the user and channel.

So the possibility would be the multiple placeholders as a feature request, which I don't think that's the right way move forward, but I can discuss with the team in case they have a different opinion.

For versions it's different because its variability comes from the version ranges having dynamic behaviour in the graph based on the current state of the environment, which is not predecible beforehand while on the other hand, variability over the user/channel is something we have been strongly advising against for some time now

Let me know if this helps :)

(Note that up until https://github.com/conan-io/conan/pull/15287, the v1 version did behave something like this and found _any_ matching reference regardless of user/channel, but that's a bug)

**Comment by DoDoENT** [comment] 2023-12-18 17:19
How do you then propose moving forward in the scenario where downstream overrides protobuf with a `user/testing` version and conan must ensure that the same version is also used in the build context to correctly generate the code?

I'm using `protobuf` just like an example, but in a real-world case I have a similar proprietary tool/lib that behaves very similar to `protobuf`, and the compiler (in the build context) must exactly match the lib in the host context. Sometimes downstream users simply want to override the version of the tool/lib with a custom, usually testing, version.

The current workaround is to export "testing" packages in the "company/stable" user/channel, which causes a lot of friction as packages in the developer's cache (or that are in editable mode) are then easily confused with "stable" packages from our internal Artifactory.

We deliberately want to use user/channel for our internal packages to clearly distinguish them from upstream packages obtained from conan-center.

**Comment by AbrilRBS** [comment] 2023-12-18 17:25
I see, thanks for the extra feedback, really appreciated - I'll bring it up with the team tomorrow :)

**Comment by memsharded** [comment] 2023-12-18 20:45
Some feedback: It is perfectly fine to use user/channel for your own packages.

What Conan 2.0 strongly discourages is to use user/channel as a reference variable dimension. Overrides of dependencies shouldn't be done over the user/channel, only the version. If the user/channel is to be used, then it should be changed in the recipes, but that would change both host and build requires. ``overrides`` is just a temporary mechanism to temporarily avoid some version conflicts. It is not an injection mechanism, and specially not intended to be able to override user/channel.

From the "core guidelines" in https://docs.conan.io/2/knowledge/guidelines.html

> Avoid ‘force’ and ‘override’ traits as a versioning mechanism. The force and override traits to solve conflicts are not recommended as a general versioning solution, just as a temporary workaround to solve a version conflict. Its usage should be avoided whenever possible, and updating versions or version ranges in the graph to avoid the conflicts without overrides and forces is the recommended approach.

For the "temporary" case, it is also possible to override the tool_requires via ``profile`` ``[tool_requires]`` section.

**Comment by DoDoENT** [comment] 2023-12-18 23:33
> Overrides of dependencies shouldn't be done over the user/channel, only the version. If the user/channel is to be used, then it should be changed in the recipes, but that would change both host and build requires. 

That's sad.

I understand that this is discouraged for production packages, but we usually have the use case where I want to put my "protobuf-like" package into an editable mode in some `user/testing` user/channel and then override that in some downstream package to test the package against my "protobuf-like" package in editable mode. Conan v2 has a nice property of changing the package ID of everything "in-between" if the user/channel is changed, so that makes it easy to quickly test the "very downstream" package against the change. The good part of it is that the downstream package will have this `user/testing` override in its `conanfile.py` that will be obvious on code review so that this cannot be accidentally merged into the main branch (even CI can reject that).

What we currently need to do to achieve the same is to use the "protobuf-like" package in `company/stable` editable mode and "invent" package version number high enough to make conan rebuild "everything in between", but still "low enough" to satisfy the version range checks of "all packages in-between".

For example, let's say that I have `protobuf-like/1.1.0@company/stable` on my company's Artifactory. Then, `mypackage/1.0.0@company/stable` is using `protobuf-like/[~1]@company/stable` as `requires` and `protobuf-like/<host_version>@company/stable` as `tool_requires`. The `mypackage/[~1.0]@company/stable` is used by the end application.

Then, the application developer reports a bug for which I have a hunch that could be in a `protobuf-like` package. To debug this, I put the `protobuf-like/1.1.0@company/stable` into an editable mode, `conan install` the application,  and start debugging. Then, I find a possible bug and fix it, however, the fix breaks the ABI and I need `mypackage` to be rebuilt against the change. So, I change the version and put `protobuf-like/1.2.0@company/stable` into an editable mode (problem 1, see below) and re-run `conan install` for the application, which causes Conan to rebuild `mypackage`. I test the app and decide that the bug is fixed now, so I can now publish the fix. To do this, I go back to the repository of the `protobuf-like` package, do some test code cleanups, such as better naming and more logical parameter ordering (problem 2), add regression test for the issue, commit everything, push and let the CI build the updated package.

Keep in mind that in this story I forgot to put `protobuf-like/1.1.0@company/stable` and `protobuf-like/1.2.0@company/stable`  out of editable modes (problem 1), and what's even worse, I did some code cleanup such as better naming and changed parameter ordering before which changed the ABI of `protobuf-like` again. However, my local `mypackage/1.0.0` is still built against `protobuf-like/1.2.0@company/stable` as it was in editable mode _before my cleanup changes_. The same is true for my local build of application.

Several days pass and the application developer now asks me about some weird behavior in the application and wonders if that behavior is due to my changes in `protobuf-like`. I checkout their commit in the application repository, run `conan install` and try to reproduce the issue, however, now I'm getting some totally different behavior - nothing like the developer reported. In my case the app barely works - it crashes at random and shows behavior that has nobody yet seen. Even the application developer doesn't understand what is going on. Several hours later after a tedious debugging session, I remember that I'm still having `protobuf-like/1.2.0@company/stable` in editable mode with different ABI than the one published on Artifactory, and `mypackage/1.0.0@company/stable` in local cache built against the editable version of `protobuf-like`. After cleaning the cache and putting all packages out of editable mode, I can finally start working on analyzing the "weird behavior" that the developer has reported.

Now, if I used `protobuf-like/1.2.0@user/testing` as my editable package during the fixing of the first bug, that would not happen even if I forget to pull it out of editable mode - the `protobuf-like/1.2.0@company/stable` would be only built on the CI and I would obtain it from the Artifactory when debugging the application after several days. Even better, I would see dirty git in the application repository with changes to `conanfile.py` stating override to `protobuf-like/1.2.0@user/testing`, instead of "difficult-to-spot" change in the application's `conan.lock` (only the recipe has would be missing, but the version, user, and channel would be same).

Unfortunately, this is currently not possible because if I do so, the `mypackage/1.0.0@company/stable` then gets incorrectly rebuilt - it then uses `protobuf-like/1.2.0@user/testing` in host and `protobuf-like/1.2.0@company/stable` in build context, causing corrupt build, if any (`protobuf-like/1.2.0@company/stable` does not yet even exist at the time of override).

Now, what would you recommend me to do in scenarios like this, besides telling me to _be more careful next time_ 😛? This scenario actually happened to me just yesterday, even though I know I need to be careful and check my editables regularly and make sure that my local cache doesn't have "incorrectly locally built packages". When you work as a staff engineer on multiple projects and need to help lots of people tackling C++ builds, package management issues, explaining API/ABI to juniors and mids, and still work on architectures of at least two moderately complex projects, it's easy to miss a thing.

I'm mostly asking for this as a _safety feature_, not as something that should regularly be used in production packages (if ever).

**Comment by memsharded** [comment] 2023-12-19 09:02
> I understand that this is discouraged for production packages, but we usually have the use case where I want to put my "protobuf-like" package into an editable mode in some user/testing user/channel and then override that in some downstream package to test the package against my "protobuf-like" package in editable mode.

This is useful and actionable feedback, thanks for sharing your use case. Let me think about it and I'll get back soon.

**Comment by memsharded** [comment] 2023-12-19 09:32
Ok, I think this can help. This is a use case that we had in mind when we added the ``--build=editable`` value, but never got to completely test it and validate it. Please check the test in https://github.com/conan-io/conan/pull/15300

The idea is that Conan 2.0 should allow more explicit ways to define what you want. There are two ``--build`` flags related to this:
- ``--build=editable``: build the editable packages. Note that this is an incremental build in the user space, so if everything is already built and synced with code, it is almost a no-op
- ``--build=cascade``: force the build of the packages that depend on another package that is being built from source. 

This is the gap that was missing, and "cascade" was not checking for "editable-build" mode, only for "build". Fixing this results in:

```bash
$ conan install app --build=editable --build=cascade
```

This should allow full control of when you want to build the dependencies in the cache that depends on your editable packages, without having to change any version number, user, channel or similar.

**Comment by DoDoENT** [comment] 2023-12-19 09:56
> This should allow full control of when you want to build the dependencies in the cache that depends on your editable packages, without having to change any version number, user, channel or similar.

If I understood correctly, this only fixes the issue of "editable mode package being up-to-date" and "all packages in-between", but it still won't protect me from scenario where I accidentally leave package in editable mode and later think it's not _just because_ it's in the same `user/channel`.

Anyway, next time I'll need to work with editables in a scenario like yesterday's, I'll give this a try, although I still think it won't solve the easy-of-usability problem I described above.

**Comment by memsharded** [comment] 2023-12-19 10:13
> but it still won't protect me from scenario where I accidentally leave package in editable mode and later think it's not just because it's in the same user/channel.

That could be another problem, but that is not that related to the ``user/channel`` discussion, isn't it?

Regarding this "forgetting scenario", we could consider other possibilities, but I'd say that this user story isn't managed either by other package managers that support this "editable" concept, this is something that it is up to the users to manage. The editables are reported in every ``conan install`` as such, if developers forget to remove the editables, it is the same as if they forget to switch git branches, there is little that can be done. The good dev practices would recommend to immediately remove the editable after finishing with it (before even submitting the code to CI), but it is very challenging, not to say impossible that Conan could have some mechanism to handle this (what it would be "expirable" editables?) . If this is something to explore, it would be better to create a dedicated ticket to discuss it.

> Anyway, next time I'll need to work with editables in a scenario like yesterday's, I'll give this a try, although I still think it won't solve the easy-of-usability problem I described above.

I still not fully understand how defining a package in other user/channel, then having to add an ``override`` in the conanfile to override to that user/channel (with the right version too) can be better than just telling it in the command line ``--build=cascade`` that is very explicit and manageable about the intention and can control when to build or not at will without having to further modify any version in the conanfile, but looking forward your feedback when you give it a try.

**Comment by DoDoENT** [comment] 2023-12-19 10:49
> That could be another problem, but that is not that related to the user/channel discussion, isn't it?

I agree. Your example correctly explains it - some thing simply cannot be solved automatically.

> I still not fully understand how defining a package in other user/channel, then having to add an override in the conanfile to override to that user/channel (with the right version too) can be better than just telling it in the command line --build=cascade that is very explicit and manageable about the intention and can control when to build or not at will without having to further modify any version in the conanfile, but looking forward your feedback when you give it a try.

Let me explain with the user story from above: if you do that, `mypackage/1.0.0@company/stable` gets rebuilt against the editable version of `protobuf-like/1.2.0@company/stable` and this is OK. But, then after I fix the bug I make some cleanups that accidentally change the ABI again and push that to the CI. _Even if I_ remove the `protobuf-like/1.2.0@company/stable` from editable mode, the `mypackage/1.0.0@company/stable` in my local cache is still built against the editable version of `protobuf-like/1.2.0@company/stable` that had _a different ABI_ than the "official" version built by the CI after I made final code cleanups that changed the ABI (but not the API, as the `mypackage` could be rebuilt without code changes).

This then results with my local application misbehaving even if I correctly remembered to remove `protobuf-like` from editables - the next `conan install` for the app will download the new `protobuf-like/1.2.0@company/stable` from the Artifactory where it was put by the CI, but `mypackage/1.0.0@company/stable` will still remain in my local cache under the same package ID, because conan does not calculate different package ID for `mypackage/1.0.0@company/stable` built against editable version of `protobuf-like/1.2.0@company/stable` and for `mypackage/1.0.0@company/stable` built against non-editable (i.e. production) version of `protobuf-like/1.2.0@company/stable`, which means that my locally used `mypackage` in my application will use incorrectly built version of `mypackage`.

By using `protobuf-like/1.2.0@user/testing`, the package ID of `mypackage/1.0.0@company/stable` built against it will be different than package ID of `mypackage/1.0.0@company/stable` built against `protobuf-like/1.2.0@company/stable`, regardless of `protobuf-like` being in editable mode or not. Thus, after finishing the work on `probuf-like` and having the CI build the `protobuf-like/1.2.0@company/stable`, and `conan install`-ing the application later will ensure that the correct package binary of `mypackage/1.0.0@company/stable` is used. This is currently never possible without manually cleaning the local cache after every such editable-with-ABI-change operation.

I don't know how `--build=cascade` would help in that case.

**Comment by memsharded** [comment] 2023-12-19 14:40
> Let me explain with the user story from above: if you do that, mypackage/1.0.0@company/stable gets rebuilt against the editable version of protobuf-like/1.2.0@company/stable and this is OK. But, then after I fix the bug I make some cleanups that accidentally change the ABI again and push that to the CI. 

> Even if I remove the protobuf-like/1.2.0@company/stable from editable mode, the mypackage/1.0.0@company/stable in my local cache is still built against the editable version of protobuf-like/1.2.0@company/stable that had a different ABI than the "official" version built by the CI after I made final code cleanups that changed the ABI (but not the API, as the mypackage could be rebuilt without code changes).

I have extended the test a little bit, removing the ``editable``:
```python
    # Changes in pkga are good, we export it
    c.run("export pkga")
    # Now we remove the editable
    c.run("editable remove pkga")
    c.run("install app", assert_error=True)
    assert "ERROR: Missing prebuilt package for 'pkga/1.0'" in c.out
```
As you can see, the ``app`` does no longer work or install with the outdated ``editable`` package. It detects there is a new revision, and then it knows it should be re-built from source to include the new revision of ``pkga``. Not necessary to clean the cache, what is necessary is either of:
- User do a ``conan export`` or ``conan create`` of ``pkga``. This is in any case very strongly recommended to do, before sending the code to CI, to check that things working locally, similarly as it is recommended to run some local tests before committing and uploading changes to the CI 
- Or if the user doesn't ``export`` or ``create``, and it is the CI creating a new binary for ``pkga``, then a simple ``conan install --update`` will manage to get the new revision from the server, and force the re-build from source of ``app``

Any of those strategies require manually cleaning the cache.

**Comment by DoDoENT** [comment] 2023-12-19 15:22
> I have extended the test a little bit, removing the editable:

I think the test should also assert that in the end there are two distinct package IDs also for `pkgb` and `pkgc` - the original one, before running `--build=editable --build=cascade`, and the one after that. Thus, after `pkga` is removed from editables, the `pkgb` and `pkgc` should again use the "old" binaries, not the ones built against `pkga` while it has been in editable mode.

**Comment by memsharded** [comment] 2023-12-26 10:15
> I think the test should also assert that in the end there are two distinct package IDs also for pkgb and pkgc - the original one, before running --build=editable --build=cascade, and the one after that. 

This is not really considered in that PR, but this could make sense, but it might need to introduce a new mode, not sure about the complexity, I will have a look.

Also, I think that part of your issues above is due to the fact of not having yet the ``workspace`` feature in Conan 2.0. It is planned for the 2.X roadmap, so hopefully we can resume working on it soon.

**Comment by memsharded** [comment] 2023-12-26 10:31
I have added a new test to cover this use case in https://github.com/conan-io/conan/pull/15300.

It seems that it works pretty good:
- When editables are activated they have no revision (empty revision), because the revision cannot be computed
- When consumer packages of that editable depend on the revision, like shared->static they will use the empty revision for computation, resulting in a new ``package_id`` for them. A ``package_id`` that is only valid for artifacts in editable mode, so it won't be valid for other cases, which is perfect
- When the editable mode is deactivated, then the ``package_id`` of the consumers will use the new ``recipe-revision`` with changes resulting in a new package-id again, requiring building from source with the new changes in the cache package.

I think that with this flow, plus the future workspace feature, this scenario would be nicely covered.

**Closed as completed** 2023-12-26 22:57 UTC
Labels: type: question
