### ISSUE TITLE
[bug] Packages with components and bare cmake_layout fail to build in editable mode.

### ISSUE THREAD

**Issue by SamsonBox** [conan-io/conan#13400] opened 2023-03-09 17:09 UTC
### Environment details

* Operating System+version: any
* Compiler+version: any
* Conan version: 1.59
* Python version: 3.8.9

I'm trying to debug the fmt package, by putting it into the editable mode. When I try to build the consuming package I get the following error:
```
CMake Error at build/cmakedeps_macros.cmake:39 (message):
  Library 'fmtd' not found in package.  If 'fmtd' is a system library,
  declare it with 'cpp_info.system_libs' property
Call Stack (most recent call first):
  build/fmt-Target-debug.cmake:24 (conan_package_library_targets)
  build/fmtTargets.cmake:26 (include)
  build/fmt-config.cmake:16 (include)
  CMakeLists.txt:5 (find_package)
```

After debugging a little bit, I found out, that the problem arises, because the correctly set `cpp.build.bindirs`, `cpp.build.libdirs` and `cpp.source.includedirs`  values are not transferred into the generated cmake-files. This in turn is caused by the `_fmt`  component, defined in the fmt package. To fix the issue I need to add the following lines in the recipe after generating the `cmake_layout`:
```
self.cpp.source.components["_fmt"].includedirs = self.cpp.source.includedirs
self.cpp.build.components["_fmt"].bindirs = self.cpp.build.bindirs
self.cpp.build.components["_fmt"].libdirs = self.cpp.build.libdirs
```

Now I'm not quiet sure if this is expected. In my understanding the `self.cpp.build.components[xyz].bindirs`, `self.cpp.build.components[xyz].libdirs` and `self.cpp.source.components[xyz].includedirs` values should be populated by default with the corresponding `self.cpp.build` and `self.cpp.source` values. If the package build the individual components into different folders, these values need to be overridden in the recipe explicitly.

### Steps to reproduce

conan install <path_to _conan_file> fmt/9.1.0@user/channel
conan source <path_to _conan_file>
conan build <path_to _conan_file>
conan editable add <path_to _conan_file> fmt/9.1.0@user/channel

**Comment by memsharded** [comment] 2023-03-09 17:47
Hi @SamsonBox 

Thanks for your report.
I think you found the reason, and this wouldn't be a but in Conan, but an issue in the recipe.
Most recipes in ConanCenter are not developed to be put in ``editable`` mode (because that is intended when you are a developer of the library, editable is not that necessary unless you are developing the C++ code, which is not a case for ConanCenter as it only packages third parties).

And the solution is that recipes that have components, to be able to put in editable mode, they need to define the components in the ``layout()`` method, otherwise it is impossible to locate those components when in editable:
```python
def layout(self):
     self.cpp.source.components["_fmt"].includedirs = ["include"]
     self.cpp.build.components["_fmt"].bindirs = ["bin"]
     self.cpp.build.components["_fmt"].libdirs = ["lib"]
```

Another question is why the ``fmt`` recipe uses components, as it only has 1 component ``self.cpp_info.components["_fmt"]``, which completely defeats the reason of using components, not having more than 1 component would be a flaw in the recipe.

**Comment by SamsonBox** [comment] 2023-03-09 17:55
Ok. Now I'm a little bit confused. I opened the identical issue and a pull request in the CCI repo. @SpaceIm stated, that this kind of boilerplate code should not be added in every recipe and I should open a issue here :-)

**Comment by memsharded** [comment] 2023-03-09 17:57
I am afraid that this is not correct @SpaceIm 

If we want recipes in ConanCenter to be able to put in editable mode, the only way to achieve that is defining components in the ``layout()``.

Another thing is that we want to explicitly say that for the sake of simplicity, recipes in ConanCenter won't be compatible with "editable" mode.

I'll bring the topic to discuss with the team tomorrow, thanks for the feedback!

**Comment by SamsonBox** [comment] 2023-03-09 18:07
Just two words about the background. We have a larger project consuming a couple of open source libraries via conan. The editable feature would provide a quick and easy way to debug or contribute to open source packages. From our point of view we would appreciate if CCI packets would offer the editable mode.

**Comment by memsharded** [comment] 2023-03-09 18:17
For CCI packages, we will be consider in the mid-future (this year) other possible alternatives to improve the contributor experience. Editable might be overkill for the purpose of contributing recipes, it is more intended for developing C++ code, not recipe code. Thanks for the the background info.

**Comment by SpaceIm** [comment] 2023-03-09 18:29
> Another question is why the `fmt` recipe uses components, as it only has 1 component `self.cpp_info.components["_fmt"]`, which completely defeats the reason of using components, not having more than 1 component would be a flaw in the recipe.

Short answer: legacy generators support.

Recipes may have to use components even if there is only 1 lib, due to design flaws of cmake_find_package/cmake_find_package_multi & cpp_info.names. It's the only way to properly provide targets like `foo::bar` in these generators.

**Comment by memsharded** [comment] 2023-03-14 11:02
Hi @SamsonBox 

We have been thinking about this with the team, and this would be our recommendation:

- Recipes in ConanCenter won't need to support the ``editable`` mode. It would be too much of added code, complexity, for a very niche use case, too of extra burden for contributors (1500 recipes in ConanCenter, it is extremely likely that +95% of them will never be really put in editable mode)
- The recommended approach for working with recipes in ConanCenter would be the local flow. This allows incremental compilation without needing changes, that is, ``conan install`` + ``conan source`` + ``conan build`` + ``conan export-pkg`` + ``conan test``. Please read for more details: https://docs.conan.io/2/tutorial/developing_packages/local_package_development_flow.html
- ``Editable`` mode would be recommended when developers are modifying the C++ code, and for exceptional cases that they want to be doing those edits while linking that package from some other consumer packages (in the normal case, using the local test suite of the library should be enough, without needing consumer packages to validate changes)

I am closing this as this is not a bug in Conan, and we will be adding some clarification in ``conan-center-index`` repo about this. 
Thanks very much for the feedback!

**Closed as completed by memsharded** 2023-03-14 11:02 UTC
Labels: type: look into, stage: triaging
