### ISSUE TITLE
[bug] Generated CMake files for macOS universal binaries not compatible with Ninja

### ISSUE THREAD

**Issue by phlipsi** [conan-io/conan#17009] opened 2024-09-17 16:38 UTC
### Describe the bug

Using generated CMake files for macOS universal binaries aren't compatible with Ninja. For example:
```
# conanfile.txt
[requires]
zlib/1.3.1

[generators]
CMakeToolchain
CMakeDeps
```

```
# CMakeLists.txt
cmake_minimum_required(VERSION 3.18)
project(ninjatest CXX)

find_package(ZLIB CONFIG REQUIRED)
```

Please run the following commands:
```
$ conan install . -s arch="armv8|x86_64" -b missing -of build
$ cd build
$ cmake .. -GNinja \
    -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
    -DCMAKE_POLICY_DEFAULT_CMP0091=NEW \
    -DCMAKE_BUILD_TYPE=Release
```

Then you'll get something like
```
CMake Error:
  Running

   'ninja' '-C' '.../build' '-t' 'cleandead'

  failed with:

   ninja: error: build.ninja:81: expected newline, got '|'

```

The reason for this error is the phony target which refreshes the CMake cache
```
build ../CMakeLists.txt ... ZLIB-release-armv8|x86_64-data.cmake ...
```
which uses a filename with the non-escaped reserved symbol `|` in Ninja syntax.

Of course, one could argue that CMake should escape the referenced files in the generated `build.ninja` file correctly. On the other hand, it seems that Ninja doesn't support any escape sequence for the pipe character. So CMake got its hands tied in this matter. What is your take on this issue?

**Comment by memsharded** [comment] 2024-09-18 23:24
Hi @phlipsi 

Thanks for the report.

Just to make sure, is this happening if using the ``Unix Makefiles`` CMake generator instead of the Ninja one?

> ZLIB-release-armv8|x86_64-data.cmake

This seems the cause, I am now a bit surprised that this doesn't generate issues with other generators. I guess that we could do a replace of the ``|`` character too for the file names? cc @czoido

**Comment by czoido** [comment] 2024-09-19 05:33
> Just to make sure, is this happening if using the `Unix Makefiles` CMake generator instead of the Ninja one?

I think the reason why it only fails in Ninja is because `|` is a reserved character in Ninja files and when making reference to files that have that character in the filename Ninja interprets them incorrectly, that's why it does not fail with `Unix Makefiles`.

> This seems the cause, I am now a bit surprised that this doesn't generate issues with other generators. I guess that we could do a replace of the `|` character too for the file names? cc @czoido

 Yes, I think the only solution we can bring would be to do a replace of the character `|` in the filenames. Let's check that solution.

**Comment by memsharded** [comment] 2024-09-22 17:37
This has been fixed by https://github.com/conan-io/conan/pull/17024, so it will be in next Conan 2.8.

Thanks again for the feedback!

**Closed as completed** 2024-09-22 17:36 UTC
Labels: stage: triaging
