### ISSUE TITLE
Remote error: .  (dot)

### ISSUE THREAD

**Issue by Croydon** [conan-io/conan#2410] opened 2018-01-31 12:52 UTC
It seems to randomly happening that a remote produces an error, with the message `.`
 (a single dot).

Example:
`libpng/1.6.34@bincrafters/stable: WARN: Forced build from source`   
 
`ERROR: . [Remote: inexor]`

https://travis-ci.org/inexorgame/ci-prebuilds/jobs/331799441#L7810

I don't know yet how to reproduce this, but it seems to happen sometimes (i.e. not an one-time thing). Also another user did report such a problem a few days ago. (with some other recipe and configs I don't know).

Since I don't know the cause of this error I don't know if there needs to be fixed something underneath, but the error message definitely needs to get "a little" more specific 😄

**Comment by memsharded** [comment] 2018-01-31 22:37
I think this is a duplicate of: https://github.com/conan-io/conan/issues/2323

**Comment by memsharded** [comment] 2018-01-31 22:39
Yes, it seems the same issue, could you please close this one and follow the previous one.
The bad news is that we haven't been able to reproduce it yet, so we don't know how to fix it, but we are aware this is a real issue.

**Closed** 2018-01-31 22:41 UTC
