### ISSUE TITLE
Consider improving package installation integrity

### ISSUE THREAD

**Issue by tru** [conan-io/conan#1003] opened 2017-02-17 08:01 UTC
We have seen a couple of times on our CI that when a job is aborted mid installation of a package it ends up leaving that package in a broken state, to mitigate we would have to manually delete the local cache on that machine. Conan thinks it's installed but it's not usable. Ideally some kind of verification that the package was correctly installed should be executed last in the chain of adding package so it won't end up in a broken state.

**Comment by memsharded** [comment] 2018-02-23 15:39
To be considered and planned in 1.3, to develop in 1.4-1.5

**Comment by progician** [comment] 2018-04-09 17:40
I'm having the same issue. Sometimes I've got the lock, which is (sort of) nice, because at least there is a notification that something is wrong with the cache. Explicit errors are easier to deal with.

However, I used pkill python to kill of conan while it's running at various stages (download and extraction), and I ended up with a state where conan said all is good, and then the build fails for missing stuff.

I vaguely rememberred that there is some verification flag that can check the consistency of a package, but the install -v flag doesn't seem to be the one. The interesting part however, is that when I look at the manifest file, it has entries that didn't get extracted, so there should be a way for conan to tell me that this package is bad, and, more importantly, it should be in the position to be forcefully recreate the package.

Trying with conan 1.2.1

**Comment by progician** [comment] 2018-04-10 09:08
To elaborate more on what I see, it looks like as if when the untarring is on-going I do not have any locks left behind. Is there any way to force the package verification during the install command?

The `--verify` argument doesn't seem to do what I would expect it to do. While the argument list says that the VERIFY argument is optional, which I would intuitively think that it checks for every single package, it drops me an argument parsing error. So it looks like that the verify argument is designed to work with a single conan_manifest file, probably for singular install mode.

What strikes me as odd, as it is possibly one of the bug, is that when there is a silent interrupted installation of a package, the next time I install it reports that the package is installed and basically that's it. It doesn't seemed to be bothered by the fact that there are files missing from the package that are in the manifest file of the package.

**Comment by memsharded** [comment] 2018-04-10 18:52
There are different aspects here.
One would be the package integrity, that should be irrespective of the arguments of verification "--verify". If something fails or is interrupted, the conan cache should try to be as consistent as possible. 
We introduced a new package cleaning in conan 1.2. 

So, is there some reproducible way you can obtain a wrong cache state? Maybe a recipe with some sleep() and killing it with Ctrl+C? Please tell.

A different thing is that ``verify`` is failing. Do you also have an example, or sequence of commands that produce such "argument error"?

Thanks for the feedback!

**Comment by progician** [comment] 2018-04-12 08:06
I can 100% reproduce the problem by killing the python process when a package is in the extraction phase (passed the download). Take a bigger package with a lot of files, and you will get missing files, but when next time I install, conan doesn't tell me that this is the case. The files were in the conanmanifest.txt.

**Comment by memsharded** [comment] 2018-04-12 22:26
You told above you were using ``pkill`` to kill it right? With which signal? Could you please copy here the output when you do so? In theory conan now should be capturing exceptions and removing the package folder, so I will try to further debug this when possible.

**Comment by memsharded** [comment] 2018-04-23 10:09
This should be solved by: https://github.com/conan-io/conan/pull/2771:

- dirty flags for packages
- command ``conan remove --locks`` to remove stalled locks

It will be released in 1.3, so I am considering this solved, but please re-open or comment if necessary. Testing from the develop branch is appreciated. Thanks!

**Closed by memsharded** 2018-04-23 10:09 UTC
Labels: in review
