### ISSUE TITLE
[bug] conan create is faulty on windows

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#10473] opened 2022-02-01 09:47 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVC 2019
  * Conan version: 1.44.1

### Steps to reproduce (Include if Applicable)
a recipe does not really matter
cd ... conan-center-index\recipes\yasm\all
conan create . yasm/1.3.0@ --build missing

### Logs (Executed commands with output) (Include/Attach if Applicable)

> conan create . yasm/1.3.0@ --build missing
ERROR: Package 00dfe7 has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash

**Comment by AndreyMlashkin** [comment] 2022-02-01 09:47
relates to https://github.com/conan-io/conan-center-index/issues/9209

**Comment by AndreyMlashkin** [comment] 2022-02-01 10:06
I have removed my whole local cache in order to get rid of this error, then it works again

**Comment by memsharded** [comment] 2022-02-01 16:52
> I have removed my whole local cache in order to get rid of this error, then it works again

Then I understand it is not possible to reproduce it anymore? If that is the case, probably the best is to close the issue and create a new one if it happens again, as it will be very challenging to try to reproduce it.

**Comment by AndreyMlashkin** [comment] 2022-02-01 18:29
It happens for me from time to time.
Actually, almost every time I want to use conan create

**Comment by memsharded** [comment] 2022-02-01 18:35
The above steps are basically the standard ones, I cannot make it fail here.

Can you reproduce with the following steps?

```
conan new hello/0.1 --template=cmake_lib
conan create hello/0.1@ --build missing
```

I also see you are using ``CONAN_USE_ALWAYS_SHORT_PATHS=True``, please try to not define it too and see what happens.

**Comment by AndreyMlashkin** [comment] 2022-02-14 10:51
I still have that problem...

conan remove "zlib" -f
ERROR: Package 0040ce has an invalid version number: '1'. Valid names MUST begin with a letter, number or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash

**Comment by AndreyMlashkin** [comment] 2022-02-14 10:51
And I have unset CONAN_USE_ALWAYS_SHORT_PATHS

**Comment by zjg** [comment] 2022-02-15 21:41
I am seeing a similar problem. It appears that Conan doesn't realize that the "short paths" folders in my .conan directory, are not packages themselves.

```
PS Q:\ws> conan search qt
ERROR: Package 01ea7a has an invalid version number: '1'. Valid names MUST begin with a letter, number 
or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```
The "package" `01ea7a` is a "short paths" folder for boost/1.76.0:
```
PS Q:\ws> cat Q:\.conan\01ea7a\real_path.txt
Q:\.conan\boost\1.76.0\_\_\build\e633f7328c4c0f4367bedc6146934dd4ac3e357c
```

I upgraded this machine from Conan version 1.41.0 to version 1.45.0, and then this started happening.

If I move all the "short paths" folders out of the .conan folder, it works again. But that will mean that I need to re-compile all the packages that I had there.

**Comment by zjg** [comment] 2022-02-15 21:46
Attempting to create a new `hello` package:
```

PS Q:\ws\tmp> conan new hello/0.1 --template=cmake_lib
File saved: CMakeLists.txt
File saved: conanfile.py
File saved: src/hello.cpp
File saved: src/hello.h
File saved: test_package/CMakeLists.txt
File saved: test_package/conanfile.py
File saved: test_package/src/example.cpp

PS Q:\ws\tmp> conan create . --build missing
ERROR: Package 01ea7a has an invalid version number: '1'. Valid names MUST begin with a letter, number 
or underscore, have between 2-51 chars, including letters, numbers, underscore, dot and dash
```

**Comment by AndreyMlashkin** [comment] 2022-02-17 12:40
To reproduce this error, you need to override conan.conf file to:

[storage]
path = C:\.conan\

**Comment by memsharded** [comment] 2022-02-17 13:23
@AndreyMlashkin can't reproduce. If I use 
```
[storage]
path = C:.conan\
```
Then the error message obtained is:
```
(conan36) λ conan create .
Error in Conan initialization: Conan storage path has to be an absolute path
```
If you changed it with 
```
path = C:/.myconan
```
It should work.

And if you keep the ``path = C:/.conan`` that is conflicting with the default ``short-paths`` folder. You need to put it somewhere else or make 100% sure that such folder doesn't exist in the same place, and that no other Conan recipe or process in the machine is using short paths in any way, or if they do, they use a different folder (via ``CONAN_USER_HOME_SHORT`` or changing ``general.user_home_short`` in conf file)

**Comment by AndreyMlashkin** [comment] 2022-02-17 13:45
Oh, I haven't noticed, there should be a backslash for sure
[storage]
path = C:\.conan\

**Comment by AndreyMlashkin** [comment] 2022-02-17 13:47
Having conan cache folder and short-paths folder in the same directory was working before and started to be problematic after one of the conan updates. It would be great to have it back or at least have some more meanful error message

**Comment by memsharded** [comment] 2022-02-17 14:49
> Having conan cache folder and short-paths folder in the same directory was working before and started to be problematic after one of the conan updates. It would be great to have it back or at least have some more meanful error message

Define before. I have just tested it with Conan 1.24, which is from 2 years ago, and I have been able to reproduce this same issue. It seems this has been there forever, maybe you were lucky and didn't hit you before, but we cannot have it back, it was never this way and it was not broken by a recent update.

**Comment by zjg** [comment] 2022-02-17 16:20
> And if you keep the `path = C:/.conan` that is conflicting with the default short-paths folder. 

My conan.conf file has this:
```
[storage]
path = Q:\.conan
```
(`Q:` is just my fast NVME drive, that also contains my code workspaces)

I set this up when I started working with Conan in spring/summer of 2021. Things worked fine then; conan was happily creating short-path folders adjacent to the normal package folders under `Q:\.conan`.

> maybe you were lucky and didn't hit you before

Yes, this may be the case. I do know that my conan setup was working fine like this when I last used it, in late 2021, using conan-1.41. When I updated to 1.45 recently, I started getting the error message previously mentioned.

It seems that placing the conan directory at a root `.conan` folder is a common enough thing that people want to do. If this explicitly will not work (due to conflict with the default short-paths folder), maybe the solution is to add a check for this case and toss up a warning/error?
Ah, looks like this was already added in #5755, so maybe we are running into a case where this warning isn't catching the problem.

---

It might also be good to add some documentation around the `storage.path` setting to mention that it cannot be the same as the short-paths folder. I see now that this is in the `user_home_short` docs:
> Setting this variable equal to, or to a subdirectory of, the local conan cache (e.g. ~/.conan) would result in an invalid cache configuration and is therefore disallowed.

But since I was only modifying my `storage.path`, I didn't think to read the docs for `user_home_short`. :(

**Comment by memsharded** [comment] 2022-02-17 16:28
Yes ``path = Q:\.conan`` shouldn't be an issue. The problem is ``C:\.conan`` or if you also have the regular Conan cache in ``Q`` too. Using any ``.conan`` folder that is not the "short paths" cache shouldn't be an issue.

One of the possibilities is that no package was using ``short_paths`` feature, or it was correctly disabled in conf. But at some point, someone introduced a ``short_paths = True`` somewhere (maybe copy & paste from a recipe from ConanCenter?), or some configuration was disabled temporarily, then some package slipped into the C:/.conan cache, and now the different layouts between the regular cache and the short-paths cache are raising the issue.


Conan 2.0 has already removed the short-paths cache completely, this shouldn't be an issue anymore soon.

**Comment by zjg** [comment] 2022-02-17 16:44
> One of the possibilities is that no package was using short_paths feature, or it was correctly disabled in conf

No, my downstream project was definitely pulling in conan packages that were using short paths under `Q:\.conan` (ex: here is a snippet of the `PATH` variable that conan-1.41 had generated for my project's deps: `Q:\.conan\zlib\1.2.11\_\_\package\63da998e3642b50bee33f4449826b2d623661505\lib;Q:\.conan\fa0234\1\lib;Q:\.conan\fa0234\1\bin;Q:\.conan\e0fe86\1\lib;Q:\.conan\e0fe86\1\bin;Q:\.conan\assimp\5.0.0\_\_\package\04e54a47a575b5e30afeed70f28eaeaf392ba7ee\bin;Q:\.conan\libtiff\4.3.0\_\_\package\373a211d246cc755c919dd67256708da571f0c4c\bin;Q:\.conan\sqlite3\3.36.0\_\_\package\cf0d11a8e3998d424115ee2c285b84ea3da499fa\bin` -- notice the short-paths in the same `Q:\.conan` folder as the other named packages).

I have never used conan on this machine without `storage.path = Q:\.conan`, so there is no `C:\.conan` directory at all.

**Comment by Chandranshu27** [comment] 2024-09-12 09:53
> I have removed my whole local cache in order to get rid of this error, then it works again

Same!!! It is so annoying as it kills an hour or more in my case... No concrete solution is available :(

**Comment by memsharded** [comment] 2024-09-12 13:25
Hi all and @Chandranshu27 

This ticket is outdated, it refers to legacy Conan 1.X that was superseded by the new Conan 2, more than 1 year and half ago, it is already in version 2.7 after a few tenths of minor and patch releases. Conan 1.X is still available, but it is not under development anymore. Furthermore, ConanCenter packages will soon stop getting updates for Conan 1.X (it will freeze, not break, but not get updates, new packages, new version or any package fixes).

I am closing this ticket as solved in Conan 2. Thanks for the feedback.

**Closed as completed by memsharded** 2024-09-12 13:25 UTC
