### ISSUE TITLE
[bug] build_requires packages can't be forced to build from sources by providing a pattern

### ISSUE THREAD

**Issue by ghost** [conan-io/conan#6725] opened 2020-03-24 15:27 UTC
### Problem Statement
When using gtest for unit tests in my library it makes sense to put it in "build_requires", since it is not needed by the clients of the lib. Everything is fine until I need to build a configuration for which gtest binaries in conan-center are not present. Adding "--build gtest" fails. It seems that the pattern matching is done only vs "requires" and not vs "build_requires". I can still force gtest to compile from sources by adding "--build=missing" or "--build" without any pattern. Probably  "--build=missing" is actually the way to go anyway, but still - I think this is a bug.

### Environment Details
  * Operating System+version: Win10
  * Compiler+version: VS2019
  * Conan version: 1.22.2
  * Python version: 3.8

### Steps to reproduce
  * Create a simple project utilizing gtest as a build_require (build_requires = "gtest/1.10.0")
  * conan create . xxx/yyy@zzz/www --build gtest

### Logs
ERROR: No package matching 'gtest' pattern

**Comment by memsharded** [comment] 2020-03-25 00:01
I think this is not a bug, but expected behavior. The key here is that when you specify ``--build=gtest``, this will only be built if you really need to build some package that has ``gtest`` as a build-require. If you have a binary for your package, then, it will be skipped.

I have just tried, for a "hello" package:
```bash
conan create . --build=gtest --build=hello
```

And it did build gtest from sources.

The rationale for this behavior is that there were use cases when users wanted to run the ``test_package`` functionality only, without needing to build the package again. We will probably change this default in Conan 2.0, but right now it cannot be changed as it would be breaking behavior.

Please check if the above works and tell us. Thanks!

**Comment by apolon81** [comment] 2020-03-26 08:47
Correct, `conan create . --build=gtest --build=hello` will build hello and `gtest` build-requirement from sources. But the explanation does not stand I think. If I haven't compiled `hello` yet, then it is going to be built from sources right? But even on the first try you will get `'ERROR: No package matching 'gtest' pattern'` upon calling `conan create . --build=gtest`.

**Comment by memsharded** [comment] 2020-03-26 09:42
> 'ERROR: No package matching 'gtest' pattern' upon calling conan create . --build=gtest

Yes, if you specify ``conan create . --build=gtest`` this is not telling to build the "hello" package at all. It assumes the ``hello`` package binary is there, and you only want to execute the ``test_package``. If the ``hello`` package is not being built from sources, it doesn't have the ``gtest`` build-requirement at all, it is not even in the graph, and then there is nothing in the graph that matches ``gtest``.

**Comment by apolon81** [comment] 2020-03-26 14:29
I get what you're saying, but if hello hasn't been ever built yet, I guess it will end up int the graph. So is it a matter of ordering? I mean `--build=gtest` fails cause the pattern matching is done before `hello` is placed into the graph?

**Comment by memsharded** [comment] 2020-03-26 14:52
> I get what you're saying, but if hello hasn't been ever built yet, I guess it will end up int the graph. So is it a matter of ordering? I mean --build=gtest fails cause the pattern matching is done before hello is placed into the graph?

No, even if it hasn't been built yet, unless you specify ``--build=hello`` it will not build from sources, and it will not have requires. The logic is:
- Internally ``conan create`` uses ``--build=<current-pkg>`` as default.
- If the user introduces any ``--build`` argument, that overwrites the above.
- If the user introduces ``--build=gtest`` only, the ``hello`` package will not be commanded to build from source
- If the ``hello`` package is not being built from source, the ``gtest`` package is not in the graph at all. The ``build_requires`` are only expanded in the graph if the package that requires them is built from sources.

**Comment by apolon81** [comment] 2020-03-26 15:44
Thanks! Those steps you pointed out made it clear for me now. I wonder if conan could give a "better" advice though? Basically it said: "hey, I can't find gtest flavor you ordered, use --buil gtest", and when I did, it failed :).

**Comment by memsharded** [comment] 2020-03-26 15:51
> Thanks! Those steps you pointed out made it clear for me now. I wonder if conan could give a "better" advice though? Basically it said: "hey, I can't find gtest flavor you ordered, use --buil gtest", and when I did, it failed :).

Well, the fact is that the logic of having ``build_requires`` in the graph is complicated to grasp. The issue is not in the first "package binary missing", which is correct, but the fact that later the dependency graph changes while the packages being built change. The first error message is common code, it would be difficult there to put a customized message for this combination of create+build_requires. 

We are very aware of these issues, and are aiming to simplify this, by having the ``build_requires`` always expanded in the graph. This would be breaking too, so it is planned for Conan 2.0. (Really looking forward to Conan 2.0 😄)

Thanks very much for your feedback!

**Comment by memsharded** [comment] 2024-03-17 23:07
This was solved in Conan 2, closing this ticket, please open new ones referencing Conan 2, thanks!

**Closed by memsharded** 2024-03-17 23:07 UTC
Labels: type: question
