### ISSUE TITLE
About version conflicts for dependencies

### ISSUE THREAD

**Issue by alLiucb** [conan-io/conan#13647] opened 2023-04-07 11:32 UTC
### What is your question?

the conan version I’m using is 1.58.0
![image](https://user-images.githubusercontent.com/100983632/230600820-e4c118b6-0182-437d-9e76-761af8867bda.png)
cmake version is 3.26.2
![image](https://user-images.githubusercontent.com/100983632/230600858-6995e96e-1cc4-4b88-963a-cc67e4dd880e.png)
my [conanfile.txt] reads as flows：

[requires]
eigen/3.4.0
openssl/1.1.1n
zlib/1.2.12
sqlite3/3.36.0
qt/5.15.3
gdal/3.1.0
[generators]
cmake_find_package
[options]
qt:shared=True 

after I ran the command：conan install . --build=missing
it showed one error：

 WARN: qt/5.15.3: requirement openssl/1.1.1q overridden by your conanfile to openssl/1.1.1n 
WARN: qt/5.15.3: requirement sqlite3/3.39.2 overridden by your conanfile to sqlite3/3.36.0 
WARN: pcre2/10.40: requirement zlib/1.2.13 overridden by qt/5.15.3 to zlib/1.2.12 
WARN: freetype/2.12.1: requirement libpng/1.6.39 overridden by qt/5.15.3 to libpng/1.6.37 
WARN: freetype/2.12.1: requirement zlib/1.2.13 overridden by qt/5.15.3 to zlib/1.2.12 
WARN: libpng/1.6.37: requirement zlib/1.2.13 overridden by freetype/2.12.1 to zlib/1.2.12 
WARN: gdal/3.1.0: requirement zlib/1.2.11 overridden by your conanfile to zlib/1.2.12 
WARN: libgeotiff/1.7.0: requirement libtiff/4.4.0 overridden by gdal/3.1.0 to libtiff/4.3.0 
WARN: libgeotiff/1.7.0: requirement proj/9.1.1 overridden by gdal/3.1.0 to proj/8.1.1 
WARN: libtiff/4.3.0: requirement zlib/1.2.13 overridden by libgeotiff/1.7.0 to zlib/1.2.12 
WARN: libtiff/4.3.0: requirement libjpeg/9e overridden by libgeotiff/1.7.0 to libjpeg/9d 
ERROR: Conflict in libtiff/4.3.0:
    'libtiff/4.3.0' requires 'zstd/1.5.4' while 'qt/5.15.3' requires 'zstd/1.5.2'.
    To fix this conflict you need to override the package 'zstd' in your root package.
CMake Error at cmake-build-debug/conan.cmake:653 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/deps.cmake:52 (conan_cmake_install)
  CMakeLists.txt:23 (include)
---------------------------------------------------------------------------------------------------------
I tried modifying my file like this：
[requires]
eigen/3.4.0
openssl/1.1.1n
zlib/1.2.12
sqlite3/3.36.0
qt/5.15.3
ztsd/1.5.4
gdal/3.1.0
[generators]
cmake_find_package
[options]
qt:shared=True 

but it didn't worked.

Could someone help me？

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-04-07 17:23
This seems a duplicate of https://github.com/conan-io/conan/issues/13648, isn't it?
I am closing it as duplicate, lets follow in the other one.

**Closed as not planned by memsharded** 2023-04-07 17:23 UTC
Labels: duplicate
