### ISSUE TITLE
conan server: [CRITICAL] WORKER TIMEOUT

### ISSUE THREAD

**Issue by DmitrySokolov** [conan-io/conan#1205] opened 2017-04-12 12:47 UTC
When uploading large packages (>1GiB) progress ends with 100% and process freezes (nothing happens a day or more).

I added more timeout `gunicorn -w 4 -t 300 ...` but still can not upload very large packages (>4GiB). I think I can add even more timeout, but 
> https://github.com/benoitc/gunicorn/issues/1440
> when a worker timeout it means that it didn't notified the arbiter in time that it was alive

**Comment by lasote** [comment] 2017-04-12 14:21
I'm not sure if it's a conan server issue then. Any other clue?

**Comment by memsharded** [comment] 2017-04-17 20:10
I have no idea how to start investigating this, I also think it could be something not conan related. A couple of questions:
- Which process freezes, the server or the client. Does the client end gracefully? If the server freezes, I guess all the workers stop working, right? 
- In which OS and version are you running the server? Enough memory?
- Did the transfer finish? Can you manually verify the integrity of the package in .conan_server? are the tgz files there and readable?

As a side issue, maybe 4Gb (tgz, already zipped), are really huge packages, even if they could be transferred, could they be an operational issue? Couldn't you use any strategy to split it into smaller components? I am sure you already thought about it, but curious about the use case.

**Comment by DmitrySokolov** [comment] 2017-04-17 22:31
Client starts to upload a big package. Progress ends at 100%. Nothing happens. No errors.

Attached:
[Test.zip](https://github.com/conan-io/conan/files/926804/Test.zip)

**Comment by DmitrySokolov** [comment] 2017-04-17 22:36
conan uses $TEMP dir during uploading, so server's $TEMP dir should be able to keep an appropriate archive file. I think it should be mentioned in docs.

**Comment by DmitrySokolov** [comment] 2017-04-17 22:39
> Couldn't you use any strategy to split it into smaller components? I am sure you already thought about it, but curious about the use case.

It's Qt for iOS (2 arch * 2 config).

**Comment by DmitrySokolov** [comment] 2017-04-17 22:41
Logs & server config will be later.

**Comment by memsharded** [comment] 2017-04-17 22:50
> conan uses $TEMP dir during uploading, so server's $TEMP dir should...

Right now, I don't think that conan is doing that explicitely, maybe some used third party library (requests?) could be doing that.

We'll try to run some checks when possible (looking forward your config too). Thanks for the test code!

**Comment by DmitrySokolov** [comment] 2017-04-20 13:18
The following config works for me.

**gunicorn:**
```
bind = "unix:/var/run/gunicorn/gunicorn.sock"
workers = numCPUs() * 2 + 2
timeout = 3600
tmp_upload_dir = "/home/gunicorn/.conan_server/upload"
worker_tmp_dir = "/home/gunicorn/.conan_server/tmp"
```
**nginx:**
```
server {
    listen       80;
    server_name ...;
    return         301 https://$server_name$request_uri;
}
server {
    listen       443 ssl;
    server_name ...;
    client_max_body_size 6G;

    keepalive_timeout 360;

    ssl                  on;
    ssl_certificate      ...crt;
    ssl_certificate_key  ...key;
    ssl_session_timeout  5m;
    ssl_prefer_server_ciphers   on;
    ssl_session_cache shared:SSL:10m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_dhparam /etc/ssl/certs/dhparam.pem;
    ssl_ciphers "EECDH+AES256:kEECDH:!kEDH:-3DES:kRSA+AES256:kEDH+3DES:DES-CBC3-SHA:!RC4:!aNULL:!eNULL:!MD5:!EXPORT:!LOW:!SEED:!CAMELLIA:!IDEA:!PSK:!SRP:!SSLv2";
    ssl_stapling            on;
    add_header Strict-Transport-Security 'max-age=31536000;includeSubDomains';
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy-Report-Only "default-src https:; script-src https: 'unsafe-eval' 'unsafe-inline'; style-src      https: 'unsafe-inline'; img-src https: data:; font-src https: data:; report-uri /csp-report";

    location / {
        try_files $uri @proxy_to_app;
    }
    location @proxy_to_app {
        proxy_set_header Connection "";
        proxy_http_version 1.1;
       proxy_buffering off;
        proxy_redirect off;
        proxy_pass http://app_server;
       proxy_send_timeout          600;
       proxy_read_timeout          600;
        send_timeout                600;
    }
}
user  nginx;
worker_processes  1;
error_log  /var/log/nginx/error.log debug;
pid        /var/run/nginx.pid;
events {
    worker_connections  1024;
    accept_mutex off;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile on;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    log_format upstream_time '$remote_addr - $remote_user [$time_local] '
                             '"$request" $status $body_bytes_sent '
                             '"$http_referer" "$http_user_agent"'
                             'rt=$request_time uct="$upstream_connect_time" uht="$upstream_header_time" urt="$upstream_response_time"';
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
    access_log /var/log/nginx/access.log upstream_time;
    upstream app_server {
        server unix:/var/run/gunicorn/gunicorn.sock fail_timeout=0;
        keepalive 360;
    }
    include /etc/nginx/conf.d/*.conf;
}
```

I think, the problem was in timeouts from `location @proxy_to_app {}` section.

**Comment by memsharded** [comment] 2017-04-20 13:52
Ok, great, so it was then a Nginx configuration issue, and not gunicorn configuration. Could this issue be closed then?

**Comment by DmitrySokolov** [comment] 2017-04-20 14:21
As you wish.
But I think it's not only nginx issue. The last one can not get response from gunicorn during default timeout. Looks like conan server (`ConanFileUpload`?) does not send "keepalive" or something.

**Comment by lasote** [comment] 2018-06-29 12:31
Now we have the Artifactory community edition for C/C++ totally free check it out. We are keeping the conan server as the open source MIT reference implementation of the conan server protocol, but we recommend to use Artifactory because it is much more advanced. I'm sure this kind of problems is not present with Artifactory.

We didn't receive more feedback about this, so I'm closing the issue, we haven't been able to reproduce it and we tried it hard.

**Closed by lasote** 2018-06-29 12:31 UTC
Labels: Feedback please!, server
