### ISSUE TITLE
[bug] regression where cross-compiling abseil generates invalid syntax in CMake toolchain file

### ISSUE THREAD

**Issue by mologie** [conan-io/conan#15785] opened 2024-02-29 15:06 UTC
### Environment details

* Operating System+version: macOS 14.3.1 (irrelevant though, it's a template bug on any platform)
* Compiler+version: Android NDK r26c (irrelevant though, compiler never runs) 
* Conan version: 2.1.0
* Python version: 3.12.2

### Steps to reproduce

Abseil will [append data to the CMake toolchain](https://github.com/conan-io/conan-center-index/blob/8096433/recipes/abseil/all/conanfile.py#L101) when cross-compiling. However, Conan's generated CMake toolchain does not end in a new line. The resulting toolchain is syntactically invalid:

```cmake
# [...]
# Preprocessor definitions
# Preprocessor definitions per configuration


if(CMAKE_POLICY_DEFAULT_CMP0091)  # Avoid unused and not-initialized warnings
endif()if(NOT CMAKE_SYSTEM_PROCESSOR)
    set(CMAKE_SYSTEM_PROCESSOR armv7)
endif()
```

Note the `endif()if` on the same line. The build thus never passes the configure phase.

**Specific steps to reproduce:** Build abseil with tool_requires `android-ndk/r26b` (or any other Android NDK).

The change made by the abseil recipe is imo reasonable given CMake's quirks, and I suspect that this silently broke at some point when Jinja or Conan was changed to no longer emit a final new line for templates.

I'd like to address this in a pull-request by restoring the trailing new line in generated toolchain files, and adding a test to ensure this does not silently break again.

**Comment by memsharded** [comment] 2024-02-29 16:32
Hi @mologie 

Thanks for your report.

I am not sure that the approach in the abseil recipe is the recommended one. Patching a generated file sounds not great, specially when the ``CMakeToolchain`` has a powerful extensitibility mechanism: https://docs.conan.io/2/reference/tools/cmake/cmaketoolchain.html#customizing-the-content-blocks

The correct approach for this would be to inject the necessary behavior in ``CMakeToolchain`` in the ``generate()`` method, not to patch the generated ``conan_toolchain.cmake`` file, specifically because this generated file contains as first lines:
```cmake
# Conan automatically generated toolchain file
# DO NOT EDIT MANUALLY, it will be overwritten
```

Said that, I am not opposed to have the ``conan_toolchain.cmake`` file always ending in ``\n``, this is generally recommended and good.
But I think I'd prefer a simpler solution than having to propagate the environment, I can have a look into that too.

I'd also like to understand first the version introducing the regression. Was this working in Conan 2.0.17? I cannot find the related changes that could have broken this. This would be important to understand the scope and extend, maybe we want to do a 2.1.1 release asap.

**Comment by mologie** [comment] 2024-02-29 17:09
Hi @memsharded, thank you for the comment and review. I wholeheartedly agree it's an odd approach chosen by the author and it's good to know it's not necessary, but I recall it was working before so I gave fixing it in Conan a shot.

I can confirm it's also broken with 2.0.17, so it /probably/ broke with 2.X.

Regarding my PR #15786 it might be possible to simplify this indeed; I tried to keep the original environment exactly as-is so that this PR does one thing only (which is adding a new line to the toolchain file).

**Comment by memsharded** [comment] 2024-02-29 17:13
Ok, if it is not a Conan 2.0 client regression, then it is not that urgent, we can work in parallel for an improvement to next 2.2, and also recommend a fix in the ConanCenter recipe. I'll have a quick look to the code and try to recommend something.

I'll try to follow up with the team to see why this apparently didn't fail in ConanCenter CI, and create a ticket there if necessary.

**Comment by memsharded** [comment] 2024-02-29 18:51
I am proposing this: https://github.com/conan-io/conan/pull/15788

I had to get rid of the ``cmake_value`` because it was failing with the ``keep_trailing_newline``. Totally unrelated and unexpected, but as I wanted to get rid of that ``cmake_value`` as it was very ugly injected via ``Blocks`` code, I have taken the chance.

**Comment by mologie** [comment] 2024-02-29 19:11
`cmake_value` was failing with `keep_trailing_newline` because writing to `template.environment` in the removed blocks.py line 51 **corrupts global state**, and you get different global state when you change to different constructor args.

Adding keep_trailing_newline got you a different environment instance. That is not transparent at all and a huge footgun in Jinja.

This was the entire reason why I construct an environment that is properly isolated and inherit it in my PR. It looks a lot cleaner w/o `cmake_value` though, the function was unnecessary.

**Comment by memsharded** [comment] 2024-02-29 19:16
> Adding keep_trailing_newline got you a different environment instance. That is not transparent at all and a huge footgun in Jinja.

Definitely, I was shocked when I realized that ``cmake_value`` was defined elsewhere and repeatedly. Better remove it completely.

**Comment by memsharded** [comment] 2024-03-01 10:35
Closed by https://github.com/conan-io/conan/pull/15788 for next 2.2

**Closed as completed** 2024-03-01 10:35 UTC
