### ISSUE TITLE
[question (bug?)] How to control the build folder used by `cmake_paths` generator, with a layout file?

### ISSUE THREAD

**Issue by Adnn** [conan-io/conan#9231] opened 2021-07-07 15:46 UTC
We are trying to enhance our local development workflow, and we wanted to try the [packages in editable mode.](https://docs.conan.io/en/latest/developing_packages/editable_packages.html#editable-packages)

Let's say we have two CMake based repositories, `Up`, and `Down` (which depends upon `Up`), and we try to develop both in parallel. So we set `Up` in editable mode:

    conan editable add --layout=layout.ini ${UP_FOLDER}/conan/ up/0.0.0

Now, `Down` locates `Up` through the output of the `cmake_paths`. Everything worked fine when `Up` was found in the local Conan cache. But now it breaks when `Up` is in editable mode. In the generated `conan_paths.cmake`, we now see:

    set(CMAKE_MODULE_PATH 	
        "/actual/path/to/up/conan/" 
        ...)

The problem is that the path output by the generator for `Up` is the path where the `conanfile.py` for `Up` is located, not the build folder where the needed files are.

---

Reading the [doc for `cmake_paths`](https://docs.conan.io/en/1.36/reference/generators/cmake_paths.html), we see that we should be able to control this path with `self.cpp_info.builddirs`.

Sadly, we cannot find a way to actually control it via the layout file provided above (`layout.ini`).
If we set `layout.ini` to:

    [build_folder]
    /build/up

The generated `conan_paths.cmake` remains unchanged.

Just to try, if we were to extend `up/conanfile.py` with

    def package_info(self):
        if not self.in_local_cache:
            self.cpp_info.builddirs = ["/build/up"]

Then `conan_paths.cmake` does change as expected, with new content being:

    set(CMAKE_MODULE_PATH 	
        "/build/up/" 
        ...)

---

How to achieve the same effect via the layout file?

**Comment by Adnn** [comment] 2021-07-07 16:10
As a Hail Mary before trashing the test folder, we tried to replace the content of our `layout.ini` with:

    [builddirs]
    ../../manualbuild/build_up

(so, `builddirs` instead of `build_folder`)

And it worked!

As far as we can tell, this `[builddirs]` entry never appears in the documentation for layout files (such as [here ](https://docs.conan.io/en/latest/reference/config_files/editable_layout.html#editable-layout) or [here](https://docs.conan.io/en/latest/developing_packages/editable_packages.html#layout-external-files)).

Which raises a bonus question: is it a supported section which could be added to the doc?

**Comment by memsharded** [comment] 2021-07-07 16:12
Quick heads up: Conan 1.38 introduced a new, more powerful, built-in in recipes ``layout()`` method that can be more easily used to implement editables.

**Comment by Adnn** [comment] 2021-07-07 16:16
@memsharded : Hi, and thank you for the heads up! 

In our situation, we want to leave each developer free to build the _editable_ recipes wherever they want (on the local filesystem). So we need to allow each developer to control the build folder path, and it seems almost impossible to achieve if the folder were to be commited with the recipe.

**Comment by memsharded** [comment] 2021-07-07 22:19
> In our situation, we want to leave each developer free to build the editable recipes wherever they want (on the local filesystem). So we need to allow each developer to control the build folder path, and it seems almost impossible to achieve if the folder were to be commited with the recipe.

I understand that, but I would strongly suggest to reconsider this policy. Of course, developers can clone the source code of the repo containing the editable package code wherever they want, the layout only define where the build folder is located with respect to the conanfile. This has several advantages:
- The relative path in the user space and when the package is built in the cache remains the same. This greatly simplifies the recipe code, and make easier to debug and compare things in the cache when something fails.
- All developers get the same build folder, with the same name and relative location, which helps to avoid issues, collaborate together more easily, etc.
- Editable packages work out of the box, for every developer, in all platforms. No need to fiddle with local layout files to adapt things.

Conan 2.0 will remove the template file for the layout, and use always the ``layout()`` method. If something, we might evolve the feature, and maybe add the possibility to override some things, like the build folder, via ``[conf]``, for example. As commented above, this is probably not a great idea, but we will see. Trying to implement an ``editable`` feature, in which each individual developer can have a custom layout of the project is simply too much. All other programming languages do enforce the project layout for similar features. We did try with these layout files, but this approach has failed. Very few users really use it, because it is complex to learn and it has too many rough edges, it is buggy (because its implementation is also complex) and incomplete.

**Comment by Adnn** [comment] 2021-07-08 06:46
Thank you for your detailed response!

We agree that adhering to a predefined layout comes with different advantages as you pointed out.

At the same time, in our organization is that some people are feeling strongly against any change is "the[ir] old ways of building code", and are still complaining any chance they get about Conan (and CMake, and CI, and anything that introduces change really). And it seems that this is not an exception, but the reality for many (most?) organizations. 
That being said, we were able to introduce Conan here because it is optional in the build flow, and we were able to adapt it to a lot of different situations to try and keep the complaints level as low as possible.

On the other hand, maybe imposing the same build layout for everyone is an opiniated decision, that goes against the initial principles which allowed us to pick Conan. Maybe enforcing a common folder layout is objectively a better decision for a build infrastucture: yet this would be making a decision on behalf of users, instead of allowing them to use the better approach **if they can**.

--- 

> We did try with these layout files, but this approach has failed. Very few users really use it, because it is complex to learn and it has too many rough edges, it is buggy (because its implementation is also complex) and incomplete.

This might also be the other way around. If the feature as rough edges, is buggy and incomplete (and has a [big orange warning in the doc saying it is experimental](https://docs.conan.io/en/latest/developing_packages/package_layout.html)), maybe this the reason why very few users use it: the approach did not fail, it was never really given the opportunity to succeed ; )

**Comment by memsharded** [comment] 2023-06-19 21:29
> On the other hand, maybe imposing the same build layout for everyone is an opiniated decision, that goes against the initial principles which allowed us to pick Conan. Maybe enforcing a common folder layout is objectively a better decision for a build infrastucture: yet this would be making a decision on behalf of users, instead of allowing them to use the better approach if they can.

We did some improvements to this, it is possible to have simpler layouts, and use the ``--output-folder`` to control the output. But in any case, this has proven to be a good approach, very convenient for developers too (reproducibility, common practices, etc), while achieving very transparent integration.

I am closing this ticket because it is 2 years old, and it is about ``cmake_paths`` which has been removed in Conan 2.0, but please don't hesitate to create new tickets for further discussion or questions. Thanks!

**Closed as completed by memsharded** 2023-06-19 21:29 UTC
