### ISSUE TITLE
[bug] Editable conan package can't export additional  include paths 

### ISSUE THREAD

**Issue by purplefishies** [conan-io/conan#11636] opened 2022-07-13 19:37 UTC
Starting with the conan examples from https://github.com/conan-io/examples.git  , I made one modification to try to mimic my own projects hierarchy where the "include" directory is under src instead of by itself at the top of the project (say) . I can't get the conan tools to understand this tiny change.

### Environment Details (include every applicable attribute)
```
(venv:conan) Prescott build (myfix |+2…) uname -a
Linux Prescott 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
(venv:conan) Prescott build (myfix |+2…) gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(venv:conan) Prescott build (myfix |+2…) conan -v
Conan version 1.50.0
(venv:conan) Prescott build (myfix |+2…) python -v
(venv:conan) Prescott build (myfix |+2…) python --version
Python 3.8.10
```

### Steps to reproduce (Include if Applicable)

I did a 
```
git clone https://github.com/conan-io/examples.git
cd examples/features/editable/cmake/say
git mv include src/
# Now update the CMakeLists.txt 
perl -i -ne 's/\binclude/src\/include/g;print;' CMakeLists.txt
perl -i -ne 's/\binclude/src\/include/g;print;'  conanfile.py
# Now do the build over
cd ..
./build.sh
```
### Logs (Executed commands with output) (Include/Attach if Applicable)

Conan Output ( I skipped the building of "say" since it's successful )

```
+ cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../generators/conan_toolchain.cmake
-- Using Conan toolchain: /home/jimi_damon/Downloads/examples/features/editable/cmake/hello/build/generators/conan_toolchain.cmake
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: Target declared 'say::say'
-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "say::say" includes non-existent path

    "/home/jimi_damon/Downloads/examples/features/editable/cmake/say/./include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.``
```

ONe key thing is that I can't ever get the file Release/conanbuildinfo.txt to ever change the "includedirs" section

It looks like

Release/conanbuildinfo.txt
```
[includedirs]
/home/jimi_damon/Downloads/examples/features/editable/cmake/say/./include

[libdirs]
/home/jimi_damon/Downloads/examples/features/editable/cmake/say/build/Release/.

[bindirs]
/home/jimi_damon/Downloads/examples/features/editable/cmake/say/build/Release/.

[resdirs]


[builddirs]


[libs]
say

[system_libs]

```

[conanbuildinfo.txt](https://github.com/conan-io/conan/files/9105363/conanbuildinfo.txt)

Any thoughts on how to add new include directories for consumption by the next project .

THanks

**Comment by memsharded** [comment] 2022-07-13 21:15
Hi @purplefishies 

I think this is not a bug, but expected. The ``say`` package is defining a ``cmake_layout(self)``, which encodes the default proposed layout, that includes the default public headers in the ``include`` directory. If you want to use another one, you can specify it, this is not tested, but I think this might work:

```python
# say/conanfile.py
def layout(self):
     cmake_layout(self):
     self.cpp.source.includedirs = ["src/include"]
```

Please give it a try, and let me know:

**Comment by memsharded** [comment] 2023-11-05 16:59
I am closing this question as responded, but please don't hesitate to open new issues for any further follow up or question you might have. Thanks!

**Closed as completed by memsharded** 2023-11-05 16:59 UTC
Labels: type: question, stage: triaging
