### ISSUE TITLE
[bug] I can no longer define random variables on the profiles after 2.0

### ISSUE THREAD

**Issue by ericriff** [conan-io/conan#13317] opened 2023-03-03 15:04 UTC
### Environment details

* Operating System+version: Ubuntu 20.04
* Compiler+version:
* Conan version: 2.0.1
* Python version: 3.8

### Steps to reproduce

We set an `SDK_VERSION` variable on the very top of our profiles since we consume that info in two places. That way we can edit it in a single line and be sure to have both fields in sync. This is no longer possible with 2.0? Or is this a bug?
```
# See this conan issue for a description of how this works to ensure that packages are rebuilt when
# the SDK is changed: https://github.com/conan-io/conan/issues/5722
SDK_VERSION=SDKaarch64/2.1@eriff/stable

[settings]
os_build=Linux
arch_build=x86_64
os=Linux
arch=aarch64
compiler=gcc
compiler.version=11
compiler.libcxx=libstdc++11
compiler.sdkversion=$SDK_VERSION
build_type=Release

[options]
[tool_requires]
$SDK_VERSION
```

### Logs

```
ERROR: Error reading 'aarch64' profile: Error while parsing line 2: 'SDK_VERSION=SDKaarch64/2.1@eriff/stable'
```

**Comment by memsharded** [comment] 2023-03-03 15:12
Hi @ericriff 

Thanks for your report.
This is not a bug, but the variable text replacement has been removed in 2.0, replaced by jinja templates variables.
There were two different mechanisms to do the same thing, one was an invented, less flexible custom DSL, so we decided to converge to the most common and "standard" (and more powerful) jinja template syntax. You can find the docs in https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering

**Comment by SpaceIm** [comment] 2023-03-03 15:22
@memsharded I think some explanations are missing in https://docs.conan.io/2/whatsnew.html and/or https://docs.conan.io/1/conan_v2.html. This syntax was quite common for host profiles using a cross-compile, and while migrating to v2 client I'm not sure https://docs.conan.io/2/reference/config_files/profiles.html#profile-rendering will be the first place where users will try to find how to migrate.

**Comment by memsharded** [comment] 2023-03-03 15:30
Sure, lets add some notes in the migration guide

**Comment by ericriff** [comment] 2023-03-03 15:53
Is this new way of defining variables backwards compatible? We're still using 1.59 and we won't be ready for 2.0 for a while.

**Comment by AbrilRBS** [comment] 2023-03-03 16:08
Yes, jinja2 templates in profiles have been available since Conan 1.38 :)

**Comment by memsharded** [comment] 2023-03-03 16:27
Did PR in https://github.com/conan-io/docs/pull/3055 to clarify this.

**Comment by AbrilRBS** [comment] 2023-12-23 21:35
Closing as solved, forgot to do so in the linked PR, thanks everyone!

**Closed as completed by AbrilRBS** 2023-12-23 21:35 UTC
Labels: type: question
