### ISSUE TITLE
conan install -u should remove CMakeCache.txt (when using a cmake generator)

### ISSUE THREAD

**Issue by sigiesec** [conan-io/conan#3650] opened 2018-10-01 12:44 UTC
When using a cmake generator, running conan install -u, and there are changes in the dependencies, the CMakeCache.txt file must be deleted. Otherwise a subsequent conan build call will continue to use the outdated dependencies, since their folders are stored in the CMakeCache.txt file, and will not be reevaluated by cmake. This should be done by conan install, if necessary (during the conan install call it should be known if any dependencies changed).

I am not completely sure if this might also happen without passing -u.

**Comment by memsharded** [comment] 2018-10-01 14:17
But changes in the included ``conanbuildinfo.cmake`` fire a project reconfiguration and updating the cached values by cmake, not sure why an explicit removal of CMakeCache.txt would be necessary.

**Comment by sigiesec** [comment] 2018-10-01 14:34
I think that's the way CMake works: https://stackoverflow.com/a/42160304/2019765

Cached entries are not overridden when cmake rebuilds. 

And there are entries in the CMakeCache.txt such as:
```
//The directory containing a CMake configuration file for MyDependency.
MyDependency_DIR:PATH=C:/.conan/lghmtmd2/1
```

I am not sure if conan's cmake generator could be changed to prevent such entries to be cached. But I think there might be other CMake internal variables, such as  CMAKE_CONFIGURATION_TYPES that are always cached. These might also change when running conan install.

**Comment by memsharded** [comment] 2018-10-02 08:00
From that thread:

> use set without CACHE to set non-cache variables. Non-cache variables take precedence over cache variables of the same name.

I don't think any variable set in generated ``conanbuildinfo.cmake`` uses CACHE. So changes in the ``conanbuildinfo.cmake``, after a ``conan install``, should correctly modify the values, and point to the right location. I have done a simple check, bumping the version of a requirement, doing a ``conan install`` and rebuilding with CMake (without cleaning the cache or regenerating the project), and it correctly uses the right version, so it is changing the cached values. I am not seeing any var in the CMakeCache like your reported one ``MyDependency_DIR:PATH=C:/.conan/lghmtmd2/1``

**Comment by sigiesec** [comment] 2018-10-02 08:14
I am using conan_basic_setup(TARGETS), maybe that makes a difference? I can try to set up a minimal repro.

**Comment by memsharded** [comment] 2018-10-02 21:32
Yes, please, try to setup a minimal repro. I have just tried with TARGETS too, still working ok, no such variables in the CMakeCache.txt, and everything updates and works fine when updating dependencies.

**Comment by sigiesec** [comment] 2018-10-16 14:13
@memsharded Sorry it took some time, but I now created a test case. You can find it in https://github.com/sigiesec/conan-test-issue-3650

Running run.sh builds fine under Windows with Visual Studio, but you see that there is such a mentioned entry in the CMakeCache.txt. The conanfile.py probably contain some extra stuff that is not strictly necessary.

**Comment by sigiesec** [comment] 2018-10-17 09:34
Just to clarify the source of these CMake cache entries: they are created by the find_package command: https://github.com/Kitware/CMake/blob/349f8bfb25349892fb2c4e5a9942e4bd63f86f49/Source/cmFindPackageCommand.cxx#L967

**Comment by sigiesec** [comment] 2018-10-17 09:41
Actually, for this kind of usage, the simpler cmake_paths generator is sufficient, but it the problem is the same. I made a modified version of the example using the cmake_paths generator here: https://github.com/sigiesec/conan-test-issue-3650/tree/use-cmake-paths-generator

**Comment by jgsogo** [comment] 2018-10-24 10:09
Hi! I'm investigation this.

I'm able to reproduce the issue and, in fact, in the [docs for CMake/find_package](https://cmake.org/cmake/help/v3.0/command/find_package.html) it is said:

> If no module is found and the MODULE option is not given the command proceeds to Config mode.

> Config mode attempts to locate a configuration file provided by the package to be found. A cache entry called <package>_DIR is created to hold the directory containing the file.

> Once one of the calls succeeds the result variable will be set and stored in the cache so that no call will search again.

We can take the following actions:

1. It's up to the user to handle `CMakeCache.txt` 😕 
1. Each time `conan_basic_setup` is run, we can unset all the `${pkg_name}_DIR` variables from the cache.
1. After running `conan install` (if something has changed), remove from the cache every variable that contains a path to `CONAN_USER_HOME` or `CONAN_USER_HOME_SHORT`.

**Comment by jgsogo** [comment] 2018-10-24 11:54
Using the `cmake_paths` generator we can also unset certain variables (`${package_name}_DIR`), to use this file you should be including it in your toolchain or making an `include` from your CMakeLists.txt, so the same solutions as before are available

**Comment by jgsogo** [comment] 2018-10-25 08:42
@memsharded, what's your opinion about

> Each time conan_basic_setup is run, we can unset all the ${pkg_name}_DIR variables from the cache.

[This is a POC](https://github.com/conan-io/conan/compare/develop...jgsogo:issue/3827-cmake-cache?expand=1) of this behavior for `cmake` generator with targets (a similar one can be implemented for `cmake_paths`). I'm adding a line to the generated `.cmake` file.

--- 

I'm not saying this should be the solution, I'm just exploring different alternatives.

**Comment by sigiesec** [comment] 2018-10-25 14:12
Just an addition on how this might be implemented: cmake has the -U option for undefining cache entries from the command line. This might be called by the cmake* generators rather than editing the CMakeCache.txt file itself. The argument can be a globbing expression.

**Comment by onnodb** [comment] 2019-04-16 11:30
While I see @memsharded 's point that clearing out the entire cache is not a solution, the underlying issue is a bit of a nasty one. The problem is really an unfortunate interaction between CMake's `find_package` mechanism and Conan. Since `find_package` is a widely used mechanism for importing libraries into a CMake-based consumer project, it may be worth pushing a bit harder for some kind of solution.

My summary of the problem would be:
* Imagine a consumer project *proj* depending on a library *mylib*. *mylib*'s Conan package features a `mylib-config.cmake` file, to allow the consumer project to use `find_package` to import its targets.
* When running `conan install` & CMake the first time, CMake stores a cache variable `mylib_DIR` to the location of the `mylib-config.cmake` file.
* Now *proj* updates its `conanfile` to a new release of `mylib`.
* Re-running `conan install` & CMake now causes a problem: *proj*'s call to `find_package` will keep sticking to the **old** release's `mylib-config.cmake` file, unless the `mylib_DIR` variable is manually cleared from the CMake cache.

Including the suggestions from @jgsogo, I would see the following solutions:
* Tell *proj* developers to clear their CMake cache whenever they update the dependencies. This is easy to forget, and tends to be hard to troubleshoot.
* Have something clear out the `_DIR` variables from the CMake cache whenever dependencies are updated. I agree with @memsharded that this would need to be done selectively and carefully.
* Hack it: in *proj*, add a line `unset(mylib_DIR)` before the call to `find_package`.

-----

(Final point: is it OK for me to bump this old issue? Would you prefer me opening a new one? Or do you keep it closed?)

**Comment by jgsogo** [comment] 2019-04-23 10:19
Pinging @lasote for him to be aware of this old issue related to CMake.

I think that **only if some of the dependencies change it is ok to regenerate CMake project**, isn't it? For me, this should be the use-case we have to cover. 
 1. When can it change? Whenever a new **version** of the package is available in the Conan cache and some version_range resolves to it, but also when a different **revision** of the package is used.
 1. How can we monitor it? The file `graph_info.json` should be exactly the same if nothing changes, I think that this file could be our sentinel.
 1. What to do? If the file `graph_info.json` changes, we can trigger some actions, from just warning the user to some build_system's cache invalidation.

@memsharded, what do you think about using file `graph_info.json` for this purpose? We can implement the warning easily and then think about some kind of cache invalidation if it makes sense.

**Comment by memsharded** [comment] 2024-01-03 11:00
Closing this issue as outdated, mostly talking about legacy and deprecated generators in Conan 1.X and removed in 2.0.

Furthermore Conan also has new features like ``build_folder_vars`` conf and ``self.folders`` attribute that allows creating different folders for different settings and options too. In any case it doesn't seem the responsibility of Conan to clear the local CMake (or other build system) caches.

Please open new tickets if necessary about the new generators and integrations, thanks!

**Closed by memsharded** 2024-01-03 11:00 UTC
Labels: type: look into, priority: low, type: feature, stage: queue, complex: high
