### ISSUE TITLE
[bug] Deploy generator is not working well with symlinks

### ISSUE THREAD

**Issue by tru** [conan-io/conan#6792] opened 2020-04-04 08:43 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Linux
  * Compiler+version: clang
  * Conan version: 1.23.0
  * Python version: 3.6.4

### Steps to reproduce (Include if Applicable)

* Create a package with symlinks 
* install package with the deploy generator
* see that the symlinks are broken

**Comment by memsharded** [comment] 2020-04-04 09:53
Hi @tru 

I think this is a duplicate of https://github.com/conan-io/conan/issues/6628 (planned for 1.25).

**Closed as completed** 2023-12-31 00:05 UTC
Labels: duplicate
