### ISSUE TITLE
Conan 1.15: editable package with python_requires crashes conan

### ISSUE THREAD

**Issue by ezaiakinsc** [conan-io/conan#5140] opened 2019-05-15 00:25 UTC
After upgrading to conan 1.15, we are experiencing conan crashes when trying to put any package, that has python_requires() call, into editable mode. For example, this package:
```python
from conans import CMake, python_requires
nlo = python_requires("nlo-cmake-pythonlib/1.0@xxx/stable")

class ProxyLib(nlo.NloBasicCmakeConanFile):
    name = "ProxyLib"
    version = "1.0"
    generators = ("nlo_cmake_link", "json")
    exports_sources = ["CMakeLists.txt", "src/*", "nlo-android/*"]
    options = {"isDemo": [False, True]}
    default_options = {"isDemo": False}

    def requirements(self):
        self.requires("AsyncTaskFlow/1.0@xxx/stable")
        self.requires("MoreJava/1.0@xxx/stable")

    def build(self):
        self.simple_cmake_build()
        self.android_gradle_build(src="nlo-android")
```
crashes when being put into editable mode with this command line:
```
   conan editable add ~/Repos/NloSanbox/ProxyLib/ ProxyLib/1.0@xxx/stable
```

with following output:
```
ERROR: Error loading conanfile at '/Users/xxx/Repos/NloSanbox/ProxyLib/conanfile.py': Unable to load conanfile in /Users/xxx/Repos/NloSanbox/ProxyLib/conanfile.py
KeyError: 'nlo-cmake-pythonlib/1.0@xxx/stable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/conans/client/loader.py", line 269, in _parse_conanfile
    loaded = imp.load_source(module_id, conan_file_path)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/xxx/Repos/NloSanbox/ProxyLib/conanfile.py", line 2, in <module>
    nlo = python_requires("nlo-cmake-pythonlib/1.0@xxx/stable")
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/python_requires.py", line 75, in __call__
    python_req = self._look_for_require(require)
  File "/usr/local/lib/python3.7/site-packages/conans/client/graph/python_requires.py", line 49, in _look_for_require
    remotes=self._remotes)
AttributeError: 'ConanPythonRequire' object has no attribute '_remotes'
```
Please note: all mentioned packages do exists, and on conan 1.14.x we never had this crash. Package, mentioned in python_requires is not in editable mode, just a normal package from cache.

For us, editable mode is crucial feature, so we had to force all conan users to downgrade to 1.14.4, even if we were really waiting features from 1.15 :-(

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment] 2019-05-15 12:07
Yes, this is a bug. In conan 1.15 we introduced the feature that python_requires can be fetched and updated from remotes too. It seems that the editable command need to pass those remotes too, and it was not completely covered by test. Lets try to fix it asap and maybe add it to conan 1.15.1.

Thanks very much for reporting @ezaiakinsc

**Comment by lasote** [comment] 2019-05-16 06:30
Merged to 1.15.1, it will be released ASAP.

**Closed by lasote** 2019-05-16 06:30 UTC
Labels: complex: low, priority: high, stage: review, type: bug

**Comment by Johnnyxy** [comment] 2019-05-23 13:03
hi there,
I am using Conan 1.15.1 on Ubuntu with Python 3.5 and it still has some kind of problem with a similar error output.

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.5/site-packages/conans/client/loader.py", line 269, in _parse_conanfile
    loaded = imp.load_source(module_id, conan_file_path)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/user/RMS/RMS_AdapterLib/adapterlib/conanfile.py", line 10, in <module>
    _my_reference = python_requires(_gg_reference)
  File "/home/user/.local/lib/python3.5/site-packages/conans/client/graph/python_requires.py", line 75, in __call__
    python_req = self._look_for_require(require)
  File "/home/user/.local/lib/python3.5/site-packages/conans/client/graph/python_requires.py", line 49, in _look_for_require
    remotes=self._remotes)
AttributeError: 'ConanPythonRequire' object has no attribute '_remotes'
```

**Comment by memsharded** [comment] 2019-05-23 13:36
@Johnnyxy Could you please tell which command are you using to fire that error?

**Comment by Johnnyxy** [comment] 2019-05-23 13:42
I am executing it with the conan-package-tools but this just executes ```conan create```.

**Comment by memsharded** [comment] 2019-05-23 13:49
Can't see how this happens, checking the source code in ``create`` I find:

```python
            remotes = self._cache.registry.load_remotes()
            remotes.select(remote_name)
            self.python_requires.enable_remotes(update=update, remotes=remotes)
```

Any short example you could share with instructions to reproduce? Maybe it happens in ``conan-package-tools`` even before hitting ``conan create``?

**Comment by Johnnyxy** [comment] 2019-05-23 14:07
The problem is that the member variable ```_remotes``` gets requested of the class ```ConanPythonRequire```.
This occurs in the member function ```_look_for_require```: https://github.com/conan-io/conan/blob/6c8473ba0ffe8dd0c68dfd5782d1faf12afcb573/conans/client/graph/python_requires.py#L49
The problem is that at this point the class member ```_remotes``` does not exist, it is not declared in the ```__init``` function ([here](https://github.com/conan-io/conan/blob/6c8473ba0ffe8dd0c68dfd5782d1faf12afcb573/conans/client/graph/python_requires.py#L15)).

The only place where it is defined and implicitly declared is in the member function ```enable_remotes```: https://github.com/conan-io/conan/blob/6c8473ba0ffe8dd0c68dfd5782d1faf12afcb573/conans/client/graph/python_requires.py#L28

This means if the member function ```enable_remotes``` has not been called at anytime before then no class member ```_remotes``` exists. Or I did overlook something :).

I do not know without further investigation if that is the case that ```enable_remotes``` is called anytime prior.

**Comment by memsharded** [comment] 2019-05-23 14:15
Yes, yes, that is exactly what is happening. So the above lines are necessary basically at the beginning of every conan_api call that needs to read a conanfile with python_requires. The ``conan create`` has it, so that is the reason I don't know where it could be failing.

We are half-way to a refactor that will force the load of the remotes for every conan_api call, so it will be impossible to forget about it, but at this moment it would be great to know where it is missing to quickly add it.

**Comment by Johnnyxy** [comment] 2019-05-23 14:16
Ok, I will look into making a minimal example. Give me a couple of minutes :),

**Comment by Johnnyxy** [comment] 2019-05-23 14:53
Ok, no minimal example. :O

I have reinstalled the conan package with pip (uninstall/install) and now everything runs fine. I have no idea what went wrong as I was installing conan with ```pip install``` in the first place too.

Now I tried the same recipe again and it runs without any problem.

**Comment by memsharded** [comment] 2019-05-23 15:17
Ok, that is a good thing, no bug 😅 

It could be that last conan version installation update was not as clean as it should be in your system, and something was stalled. Glad to know that it is gone!
