### ISSUE TITLE
[question] Header-only package in editable mode

### ISSUE THREAD

**Issue by onnodb** [conan-io/conan#4749] opened 2019-03-15 08:22 UTC
We've been really excited about the local editing workflow introduced in Conan 1.12, and the enhancements made in 1.13. One issue we ran into is the following, and I was wondering if I could pick your brains about a possible solution?

We have a package — let's call it `H` — that provides a header-only C++ library. We also have a consumer project `C`.

If we install `H` in editable mode, and compile `C`, all is good. If then one of the header files in `H` gets modified, compiling `C` again does not pick up the changes just made: a full rebuild is necessary.

Context: CMake + MSVC on Windows, as well as CMake + Clang 7 on Linux.

Our current solution is to use Conan workspaces, as having everything together in one CMake project fixes this dependency check. Would you agree? Would it then make sense to point this out in the documentation somewhere? (I'd be happy to provide a PR for such a documentation change.)

**Comment by lasote** [comment] 2019-03-15 11:59
When you said ` If then one of the header files in H gets modified, compiling C again does not pick up the changes just made: a full rebuild is necessary`.  How exactly are you building your project? Directly with the build_system? CMake? I think the build system should be able to detect a change in a header of a dependency. In other words, which is the difference between a "build" and a "full rebuild" for you?

Yes, I agree that using workspaces you can manage it nicely. About the docs, yes, I'm sure it could be mentioned somewhere.

**Comment by onnodb** [comment] 2019-03-15 12:38
Thanks for the response, Luis!

> How exactly are you building your project? Directly with the build_system? CMake?

Sorry for missing some of the details here in my original explanation.

The consumer project, configured to use the `cmake` generator, is built by running `cmake --build`. For some reason, it never picks up on modified header files in `H` (we tested both on MSVC/Windows and on Clang/Linux).

It's no big deal, but it might be something to be aware of when promoting the "editable package" workflow. For us, it makes the workspace feature preferred over just editable packages.

**Comment by Lawrencemm** [comment] 2019-03-19 09:36
Interesting. 
My guess is that since the headers from `H` aren't a part of any CMake target, CMake isn't rebuilding when they change because I believe this functionality is dependent on having the changed files a part of a target that your project depends on.

A possible solution might be for conan install's generated build files to define a target for files in the include dirs if the dependency is not in the cache, and then add that target to the link libraries list or something like that.

**Comment by danimtb** [comment] 2019-04-16 14:34
This is the expected behavior of packages in editable mode. Any consumer package will have to be rebuilt even those that do not build with CMake

**Comment by danimtb** [comment] 2019-04-16 14:35
The approach suggested by @Lawrencemm is inlined with the concept we have about the new approach for build helpers and generators

**Comment by jgsogo** [comment] 2019-06-25 11:28
Hi! I've made a little example to reproduce the behavior and it is happening as all of you describe: the consumer is not able to detect the modification in the header file of the editable package (consumed as an imported target) and no build is triggered.

The problem here is that there is nothing to build in the editable package, there is no library the consumer could detect as modified, we cannot request (as we do for a library) to change the file in the editable and then build so those changes are compiled into a library.

So I think that the best we can do is to document it (#4749). Although some fix along the lines that @Lawrencemm suggest could work, it would be only useful for this particular use case when the header only is consumed as editable, maybe it is too much for this.

BTW, _workspaces_, using the actual target, doesn't have this behavior.

**Comment by memsharded** [comment] 2023-06-25 22:18
These tools and integrations deprecated long time ago, closing ticket as outdated

**Closed by memsharded** 2023-06-25 22:18 UTC
Labels: type: question, stage: triaging
