### ISSUE TITLE
[question] Feedback on 2.0 tool requirements

### ISSUE THREAD

**Issue by theodelrieu** [conan-io/conan#10317] opened 2022-01-11 16:00 UTC
(Didn't really know where it belonged, so I chose "question")

Hello,

After playing around with tool requirements in 2.0, I'd like to give a bit of feedback.

First, here's some context.

## libcxx in Conan 1.x 

We're packaging our own `libcxx`, mostly to be able to use latest C++ features without any hassle.
This package exposes header files, libraries, and compiler flags. Still we use it as a `build requirement`.

There are two main reasons for that:

1. Adding `libcxx` as a requirement in every recipe/CMakeLists.txt is very tedious (and not upstream-able)
2. It has to expose env variables for non-CMake build helpers

## libcxx in Conan 2.0.0a2

Almost everything changed in 2.0, so I tried my best to adapt the recipe:

* Use the new `CMakeToolchain` generator (Apple-specific flags are handled here)
* Use the `generate` function to "configure" CMake
* Remove every env variable from `package_info`

## Problems

A few issues arose:

1. Flags defined in `cpp_info` were not forwarded to consumers
2. The `os` / `arch` of `libcxx` were the one of the build profile, not the host profile

The latter simply means that you get a linker error when creating a consumer package, which is a bit annoying.

So I figured I had to go back to what I was doing in 1.x, i.e. populating the environment.
But I also had to workaround the fact that the build profile architecture was chosen, and not the host one.

In the end, I had to do a bit like the Android NDK, and build every variant I want (os + sdk + arch) and bundle everything in a single package.

To do that, I had to redefine some of the CMake cross-building vars, and get rid of the CMake build helper. It works, but feels very brittle for a future 2.0.

I've attached both versions of the recipe for 1.x and 2.0 + associated profiles.

Looking forward to seeing your comments!

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

[libcxx_1.x.zip](https://github.com/conan-io/conan/files/7848007/libcxx_1.x.zip)
[libcxx_2.0.zip](https://github.com/conan-io/conan/files/7848009/libcxx_2.0.zip)
[profiles.zip](https://github.com/conan-io/conan/files/7848011/profiles.zip)

**Comment by memsharded** [comment] 2022-01-13 11:04
Thanks for the very detailed feedback and code.

I think the main issue arises because ``libcxx`` is, at most effects, a library, and not a "tool" like "cmake" could be. Then, using the ``tool_requires`` is definitely not the way to go.

As you have figured, the only way to define "library" dependencies or regular requires, is in the recipes, you cannot magically inject a package dependency to all packages there magically from profiles.

We need to discuss this use case, and think what could make sense. It seems so far to be a valid use case, but we need to carefully consider implications, possible approaches, etc. Lets work on this.

**Comment by theodelrieu** [comment] 2022-01-13 13:42
>Then, using the tool_requires is definitely not the way to go.

Agreed. I think there is a missing puzzle piece here.

In the past years, we talked several times about introducing a "toolchain" concept.
I think it's time to seriously think about it.

I don't have a very defined idea of what to do, but here's what I'd like to have 😛.
A toolchain should be able to expose:

* tools (e.g. compiler)
* env vars
* compiler flags
* libraries to globally link against

I've got two use-cases in mind: `libcxx` and `android-ndk`.

The latter exposes a compiler so it's easier to imagine it as a toolchain. The former only exposes a lib, but it's the standard lib, and is supposed to be compiled and linked against globally.

Just like you never care about how you find the standard library headers + libs on your own system, consumer recipes should not have to either.

Let me know what you think about this, then we can start going into the dirty details 😄

**Comment by memsharded** [comment] 2022-01-15 15:07
I have started to work on https://github.com/conan-io/conan/pull/10347, the idea is to capture the use cases in tests correctly. The first important bit to correctly address is the creation (correct package-ids and settings) and usage (correct package_ids and info)

**Comment by maikelvdh** [comment] 2022-05-02 18:02
@memsharded is there any plan to get this still in place for Conan 2? I do think this is actually quite relevant also in relation to new lockfiles proposal as this type of "toolchain" packages are quite relevant to be captured as part of locked state.

**Comment by memsharded** [comment] 2022-05-02 20:28
@maikelvdh Yes, it is part of the next alpha7, to provide the right support to be able to model this kind of packages ``package_id`` correctly, which is the first important building block.

Regarding your comment about the lockfiles, I don't think it is very relevant, because the dependency graph is always evaluated complete in 2.0, so absolutely all dependencies, no matter if ``requires`` or ``tool_requires`` will be always part of the dependency graph, and consequently they will always be part of the generated lockfile from that graph.

**Comment by gpxricky** [comment] 2022-05-03 11:39
Is there already a plan (e.g. in your mind) how such toolchain packages may look like and how to name them?

Internally, I would consider them to be a `tool_requires` except the fact that they should be part of the `package_id`.
Handling them as special kind of `requires` has the drawback that the dependency is downloaded even if a prebuilt binary package is available - which is, at least in our environment, just waste of time and disk space (an SDK may be very large).

In case a good name is found for such packages, then a fourth kind of requirement besides `requires`, `tool_requires` and `test_requires` may be useful. However, I think the name is really important and should immediately indicate what's the difference to a `tool_requires`.

**Comment by gpxricky** [comment] 2022-05-04 07:05
I don't know the Android NDK to be honest, but I know the QNX SDP and I guess it is quite similar. Something that is a little bit difficult for me is to decide which kind of profile to use for a toolchain package.

E.g. the QNX SDP is available for different platforms, but let's assume I'm using one that is running on Linux and provides tools, libraries and header files for different target architectures (ARM7, etc.).

So how to build the toolchain package for this QNX SDP? Using a linux host profile as the SDP is running on Linux OS in the scenario above? Or splitting it into multiple QNX SDP packages (one for each target architecture) and using an ARM7 (or whatever the target architecture is) profile?

Maybe I'm the only one that is confused which profile to choose. But it would be a good help if Conan points to some direction here.

For simplicitly I would say to use a Linux host profile when building the QNX SDP package.
For correctness I would say to use a Linux host profile but also introduce something like a `target` profile - however, another type of profile is too complicated IMO.

**Comment by gpxricky** [comment] 2022-05-04 07:20
I've just seen this in the documentation: https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#conan-v1-24-and-newer.

From my understanding this is a very clear recommendation how to handle and solve my profile confusion - sorry that I haven't seen it before.

Let me check if I'm right. The idea is quite similar to one of my ideas above with the exception that the `target` profile isn't a profile but an option of the Conan package.

This means, I'll create a Conan package for the QNX SDP using a Linux host profile and explicitly set the `target` option to `arm7`. When this Conan package is now used as a tool requirement (not tool in tool), then the `target` option may be implicitly set to the `arch` setting of the consumer's host profile. This way, I can offer multiple Conan packages (e.g. one per target architecture) but still use the Linux profile as host profile when building the packages.

So the only missing point is whether toolchain packages shall influence the `package id` (which I prefer) or not.

**Comment by memsharded** [comment] 2022-05-09 16:26
https://github.com/conan-io/conan/pull/10347 implemented the necessary ``package_id`` changes to model ``toolchain`` packages:

- ``build_requires`` can be made part of the ``package_id`` of consumers, by default they are not, but either the ``package_id()`` of consumer recipes or by ``conf``, it is possible to do it
- The ``settings_target`` can be made part of the ``toolchain`` package, to model different toolchain binaries for different targets if necessary.

This is the first necessary stage to model ``toolchain`` packages. It is possible that some further work is necessary in the build system integrations, looking forward to getting feedback for this, because it is not fully clear how information needs to be propagated:
- For a toolchain like ``gcc`` compiler, or possibly different compilers, that could contain a ``libcxx`` binary, it really seems that a ``find_package(libcxx)`` is not desired at all. So we are good with the ``tool_requires`` default of not adding ``find_package()`` things for their contents.

Moving forward this ticket to 2.0-beta.1, please feedback! :)

**Comment by memsharded** [comment] 2022-05-10 20:50
@gpxricky 

> Let me check if I'm right. The idea is quite similar to one of my ideas above with the exception that the target profile isn't a profile but an option of the Conan package.

Not an ``option``. Packages in the "build" context can get a ``settings_target`` attribute with the values from the "host" context when cross-building

**Comment by lasote** [comment] 2022-06-06 08:08
After reviewing the current proposal, I only have found one "theoretical" limitation. If you have a `tool_require` in a profile and you want the consumers to link with some library or include some header, you cannot, because the current generators like `CMakeDeps` discard them (because of the requirement traits, that indicate `libs=False` and `include=False`). 

In case this is a real use case (usually the toolchains adjust a sysroot so you don't directly declare includedirs/libdirs), we would need something to model the traits or define a different section in the profile, but I think we are ok. 

Note that you can always from the consumer to access the `self.dependencies` and get the libdirs etc so you could operate manually. I would postpone this until we have a more solid use case.

**Comment by memsharded** [comment] 2022-06-13 17:14
> In case this is a real use case (usually the toolchains adjust a sysroot so you don't directly declare includedirs/libdirs), we would need something to model the traits or define a different section in the profile, but I think we are ok.

The traits can always be modeled directly, like a ``tool_requires()`` that also contains libraries and headers would be:
```python
self.requires(ref, build=True, run=True, headers=True, libs=True)
```

**Comment by sobczyk** [comment] 2022-07-01 06:05
I use libcxx with conan 1
I use `python_requires_extend` to inject libcxx requirement (with `private=True`, to be able to use stdc++ too)
I did not want to hack in python too much, so it's still required from my recipes that `requirements()` to be called in the conanfile proper. Or additions to cmake flags (like adding libcxx flags to `*_INIT` cmake variables)
I've hit a problem with this approach though, as `dependencies` property is not available in test_package for some reason.

libcxx is a standartd library, so the problem is that it should be added implicitly to packages, not requiring much patching.
(like adding -isystem, -stdlib=libc++ etc.)

`-stdlib=libc++` flag is abvailable since gcc 10 or 11 along clang btw. but it adds hardcoded flags, so for conan adding `-isystem` and `-L` is needed

**Comment by lasote** [comment] 2022-07-04 10:25
About

> I've hit a problem with this approach though, as dependencies property is not available in test_package for some reason.

The `self.dependencies` is only available in the `generate()` method, if you need to read something from the deps and use it later, you can write it to a file. I would say `self.dependencies` is available in the `build()` method too in Conan 2 but the "processing" of the dependencies to "prepare" the build is meant to be done in the `generate()`.

**Comment by memsharded** [comment] 2024-09-03 09:51
Closing as outdated/solved in Conan 2. Please create new tickets to discuss any further question or issue, thanks!

**Closed as completed by memsharded** 2024-09-03 09:51 UTC
Labels: type: look into, whiteboard
