### ISSUE TITLE
[bug] vcvars_dict gives keys with inconsistent case

### ISSUE THREAD

**Issue by BrianSipos** [conan-io/conan#7358] opened 2020-07-14 20:03 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: MSVS 2015
  * Conan version: 1.25.1
  * Python version: 2.7.17 on the host, but conan is installed as MSI via Chocolatey

### Steps to reproduce (Include if Applicable)
1. Within the `build` function call `vcvars = tools.vcvars_dict(self.settings)`.
1. Log the keys in the returned dictionary.
1. Observe that the keys contains non-standard case similar to "Path" in the following:
``
vcvars keys: "CommandPromptType", "Framework40Version", "FrameworkDIR64", "FrameworkDir", "FrameworkVersion", "FrameworkVersion64", "INCLUDE", "LIB", "LIBPATH", "NETFXSDKDir", "PROMPT", "Path", "Platform", "UCRTVersion", "UniversalCRTSdkDir", "VCINSTALLDIR", "VSINSTALLDIR", "VisualStudioVersion", "WindowsLibPath", "WindowsSDKLibVersion", "WindowsSDKVersion", "WindowsSDK_ExecutablePath_x64", "WindowsSDK_ExecutablePath_x86", "WindowsSdkDir"
``
1. See later on when the dictionary is modified that `vcvars` use is inconsistent because `vcvars.get("PATH")` returns None instead of the expected path list.

This issue is occurring on multiple recipes on the same host, but earlier builds on the same recipes (with different settings) used the canonical key "PATH" instead of "Path". Even a workaround would be acceptable to me, if I could correlate when this fails and when it works.

**Comment by memsharded** [comment] 2020-07-14 21:37
Hi @BSipos-RKF 

I am not sure if I understood the issue correctly. Why do you say the vars are ``non-standard``? It is not like Conan is doing any manipulation on them, if you do in the terminal in Windows:

```bash
$ set
...
Path=C:/...
```

Do you mean that in the previous Conan versions, ``tools.vcvars_dict()``, it was returning the dict with PATH uppercased? I have checked the changelogs, and I cannot see any change related to this.

**Comment by BrianSipos** [comment] 2020-07-14 21:51
The strange thing to me is that I did not upgrade conan version in a very long time (months) but also very rarely rebuild large packages. The strange thing was that a build earlier in the day with different settings _did_ set the "PATH" variable while my most recent build attempts are now setting the "Path" variable. I even tried opening a completely new powershell (with default environment) to do the build and see the mixed-case version.

My meaning of the word "standard" comes from looking at the specific environment names in the [tools documentation](https://docs.conan.io/en/1.25/reference/tools.html#tools-vcvars-dict), of which "PATH" is one.

And my concern here is not necessarily to fix anything wrong in conan but to get some insight into what may be causing this and possibly get a workaround.

**Comment by memsharded** [comment] 2020-07-14 23:37
Thanks for clarifying!

> And my concern here is not necessarily to fix anything wrong in conan but to get some insight into what may be causing this and possibly get a workaround.

Yes, agree, I am also trying to understand if this is a regression or if something has changed in Windows or what is happening. I honestly don't have a clue of what it is, please let us know if you find something else that could give us a hint. 

The thing is that ``os.environ`` in Windows is case insensitive, it is an special dict, but what is returned from ``vcvars_dict`` is a regular dict, maybe we should change it to a case insensitive dict too? What do you think @jgsogo?

**Comment by jgsogo** [comment] 2020-07-15 07:30
Conan does modify the casing of environment variables in Windows after using some environment tools: https://github.com/conan-io/conan/issues/1706. I'm not sure if something in the implementation around `vcvars_dict` has changed and it is no longer using those tools (so now returns the proper casing), or maybe it is the recipe the one that has changed.

**Comment by BrianSipos** [comment] 2020-07-15 12:41
Another thing for reference; what I'm doing currently is similar to the following (but for all of the 'standard' variables).
```
        env = tools.vcvars_dict(self.settings)
        env['PATH'] = (
            [ ... ]
            + self.deps_cpp_info.bin_paths
            + env.get('PATH')
        )
```

I could write my own function to merge a dictionary value case-insensitively but would prefer not to need to do so. 

It may also be worth mentioning in the documentation (linked above) about the name cases potentially being different than the all-uppercase names listed in the docs.

**Comment by puetzk** [comment] 2021-11-18 20:40
We hit this too, though ultimately decided windows had case-insensitive names, and conan wasn't wrong, so we didn't file a bug.

The issue arises because of https://github.com/conan-io/conan/blob/1.31.2/conans/model/env_info.py#L202

So if conan has not made *any* change to the environment, you see the case as it initially existed. But if conan has manipulated the environment at all, then when it re-set the resulting combined environment, it force `PATH` to upper-case, which it might not initially have been (e.g. windows uses `Path` as the spelling by default).

**Comment by memsharded** [comment] 2022-08-25 22:56
The management of environment now is done with new tools (https://docs.conan.io/en/latest/reference/conanfile/tools/env.html), vcvars_dict is deprecated, closing this as legacy

**Closed as not planned by memsharded** 2022-08-25 22:56 UTC
Labels: stage: triaging
