### ISSUE TITLE
[feature] Default for --build

### ISSUE THREAD

**Issue by lukester1975** [conan-io/conan#14698] opened 2023-09-07 16:40 UTC
### What is your suggestion?

Apologies in advance, I'm pretty sure I read a similar issue to this asking about `core.package_id:default_build_mode` where it was pointed out that that only applies to the package itself, not its deps, but I can't find it now. I don't think #14222 is it...

Anyway: a way to specify `--build=missing` as default behaviour (to save typing again...), but I can't see a way.

I have a feeling wherever I read a similar request concluded with it not being something that was going to be implemented, but thought I'd ask.

If not currently possible and viable, I'm happy to have a go. Quick initial hack https://github.com/lukester1975/conan/commit/24e3248195d53d5795bbb7dc732793a2d781eb09 but aside from the factoring out, probably needs thought about it being a list (or maybe the conf option should just support one value).

Thanks

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by lukester1975** [comment] 2023-09-09 16:34
Ah `build_policy` and #14500 was it.

The explanation in #14500 makes sense, but I would really like a way to be able to default `--build=missing` on my dev box. I know what I'm doing (may not be true) 😀

**Comment by memsharded** [comment] 2023-09-10 09:41
Hi @lukester1975 

Thanks for your suggestion.

This is one of the decisions that were pretty deliberate (though we are always fine to reconsider with users feedback). The ``--build=missing`` as default is a dangerous thing, it hides the lack of missing binary, produces unnecessary rebuilds from sources over and over again because developers don't upload the built binaries to the server (they shouldn't, as they shouldn't have permissions), and putting it in a ``conf`` has the risk of propagating it with ``conan config install`` easily, producing the same behavior in CI servers too. 

So we always believed that a very few characters, typing ``--build=missing`` is the right thing to do.

> I know what I'm doing (may not be true

That is true :) and we have always tried to provide as much power to the users as possible. But when we make things easier to abuse or to produce unexpected behavior or side issues, it is us that we have to do the support, debugging, and maintenance with the affected users, and that can have a large impact on the team and productivity.

Said that, I will check and discuss with the team, tagging this as "look into" for that. Thanks!

**Comment by lukester1975** [comment] 2023-09-10 09:52
OK, thanks for tagging it. I see your point about config propagation, that would be unfortunate! I guess supporting non-`conan config install`able config is going a bit far...

I think the best I can do for now is a custom command; something like

```py
from conan.cli.formatters.graph import format_graph_json
from conan.cli.command import conan_command
from conan.cli.commands.install import install


@conan_command(group="Consumer", formatters={"json": format_graph_json})
def dev(conan_api, parser, *args):
    """
    Runs: install --build=missing ...
    """

    set_option = True
    for arg in args[0]:
        if arg.startswith("--build"):
            set_option = False
            break

    if set_option:
        args[0].append("--build=missing")

    return install._method(conan_api, parser, *args)
```

has been working OK, if ugly (I'm sure there's some python one line magic to get rid of that for loop, but I don't do enough python to remember it, if I ever knew...).

Thanks

**Comment by memsharded** [comment] 2023-09-11 06:28
I think you can do something like:
```python
if not any(arg.startswith("--build") for arg in args[0]):
      args[0].append("--build=missing")
```

**Comment by lukester1975** [comment] 2023-09-12 10:59
Simple when you know how! Thanks.

**Comment by memsharded** [comment] 2024-03-05 10:44
We have been reviewing this, and at the moment this won't be planned.
The only place that it would make sense is to change the ``conan create`` default so it doesn't forcefully re-build the package if it already exists, but that would be too breaking behavior, so something to consider for future breaking 3.0 (not planned at the moment either).

So I am closing this, thanks very much for the feedback!

**Closed as not planned by memsharded** 2024-03-05 10:44 UTC
Labels: type: look into
