### ISSUE TITLE
[feature] Extend EnVars API for custom generators

### ISSUE THREAD

**Issue by rettenbs** [conan-io/conan#12427] opened 2022-10-31 08:53 UTC
We are building a customizable generator for CMake presets. The generator uses the `VirtualBuildEnv` to define the environment variables in the presets. However, the public API of `EnvVars` does not support custom placeholders.

Our current workaround:
```python
vars = VirtualBuildEnv(conanfile).vars()
env = {
    # Double escape "{}"
    name: value.get_str(f'$penv{{{{{name}}}}}', vars._subsystem, vars._pathsep) for name, value in vars._values.items()
}
```

Possible API:
```python
env = VirtualBuildEnv(conanfile).vars().items(placeholder='$penv{{{name}}}')
```

Note: The included presets generator is not suitable for us. We need a presets file where developers can switch between presets (e.g. debug, release, tests, ...) without rerunning `conan install`.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2022-10-31 10:37
Hi @rettenbs 

This is possibly something to discuss with the team, as we know that needing to activate the environment is an extra step, that if could be avoided it would be great. But it has some challenges, because supported CMake version is 3.16, so we can't rely on this either for core-implementation, and having multiple, competing ways to do the same thing is very problematic.


I think if you want to operate on the environment, you need to get it explicitly, not the ``vars()``, but ``VirtualBuildEnv(conanfile).environment()``. That environment object you can manipulate, get environment in an abstract way, then when you are done, you can get the ``vars()`` from it?


> Note: The included presets generator is not suitable for us. We need a presets file where developers can switch between presets (e.g. debug, release, tests, ...) without rerunning conan install.

This is totally possible. This can be done by running first ``conan install ... -s build_type=Release`` and ``conan install ... -s build_type=Debug``. Conan will append to CMakePresets, and developers can switch configurations from the presets without running Conan again. This is true also while not using presets and only ``conan_toolchain.cmake``, or for other generators like ``MSBuildDeps`` that are also multi-config.

**Comment by rettenbs** [comment] 2022-10-31 11:49
Hi @memsharded
Thank you for the fast feedback.

> This is possibly something to discuss with the team, as we know that needing to activate the environment is an extra step, that if could be avoided it would be great. But it has some challenges, because supported CMake version is 3.16, so we can't rely on this either for core-implementation, and having multiple, competing ways to do the same thing is very problematic.

It it okay that our CMake presets generator does not make it into the core-implementation. We are happy to maintain the generator for ourselves.

Maybe we can publish a Conan package for others to use. At the moment the generator use some assumptions about our build environment. Hence, at the current stage I doubt that it is very useful to others.

However, it would be very helpful if the generator is based on a stable public API from the core-implementation.

> I think if you want to operate on the environment, you need to get it explicitly, not the `vars()`, but `VirtualBuildEnv(conanfile).environment()`. That environment object you can manipulate, get environment in an abstract way, then when you are done, you can get the `vars()` from it?

I checked the `Environment` API. There is no function to access a value. Actually, the complete class `_EnvValue` is marked private. If there is a way to do this with an existing API, please let me know.

> This is totally possible. This can be done by running first `conan install ... -s build_type=Release` and `conan install ... -s build_type=Debug`. Conan will append to CMakePresets, and developers can switch configurations from the presets without running Conan again. This is true also while not using presets and only `conan_toolchain.cmake`, or for other generators like `MSBuildDeps` that are also multi-config.

The setup should be as simple possible for the developers, i.e. running `conan install` once and then continuing in the IDE. All the magic has to happen in the `conanfile.py`.

**Comment by rettenbs** [comment] 2022-10-31 11:57
Actually, the API would be useful for any custom generator that requires the environment variables in one or another way.

**Comment by memsharded** [comment] 2022-10-31 23:05
> I checked the Environment API. There is no function to access a value. Actually, the complete class _EnvValue is marked private. If there is a way to do this with an existing API, please let me know.

Ok, I see, I thought that you wanted to do some modification to the environment, but it is not what you want? I don't know what is the correct syntax for env-vars in CMakePresets, maybe a bit of clarification would help to understand the final goal, beyond specific tool APIs or approaches.

> The setup should be as simple possible for the developers, i.e. running conan install once and then continuing in the IDE. All the magic has to happen in the conanfile.py.

This we have learned that it really doesn't scale. Installations need to be per-configuration, and then repeat them for the different configurations. Because it is not only Debug & Release. Many users will want other configurations, like RelWithDebInfo. Others will want different variants, like shared/static, and the dependency graph will also be different in many situations for different configurations. It is not possible that a ``conanfile.py`` allows to define that variability, and any attempt to install more that one configuration with a single ``conan install`` will be probably at the very least challenging, even trying with custom generators, but in many cases it might be broken. So packages should always be single-config, the installation happens for every configuration instantiating a different dependency graph, and multiple configurations must be collected as the result of running multiple ``conan install``.

If the issue is running more than one command, then this has different solutions. For example in Conan 2.0 you will have the new Conan custom commands that you can define your own ``conan install`` command that iterates different configurations to achieve what you want. In 1.X you might achieve the same with a simple script in the root of the repo.

**Comment by rettenbs** [comment] 2022-11-02 08:13
> Ok, I see, I thought that you wanted to do some modification to the environment, but it is not what you want? I don't know what is the correct syntax for env-vars in CMakePresets, maybe a bit of clarification would help to understand the final goal, beyond specific tool APIs or approaches.

We would like to extend the environment API. Here is a simplified example how our `conanfile.py` could look:

```python
class CMakePresetConfig:
    """A CMake configuration preset."""

    def __init__(self, compiler, buildTypes=['Debug', 'Release']):
        self.compiler = compiler
        self.buildTypes = buildTypes


class CMakePresetsGenerator:
    """Generates a CMakePreset.json for all the selected compilers.

    The generated presets requires CMake 3.21.0 or later.
    """

    def __init__(self, conanfile, config: list):
        self.conanfile = conanfile
        self.config = config

    def _configurePresets(self, config):
        """Generate configure presets for a specific compiler."""
        # Get environment variables
        envVars = self.env.vars(self.conanfile)

        def preset(buildType):
            p = {
                'name': f'{config.compiler}-{buildType.lower()}',
                'displayName': f'{config.compiler} {buildType}',
                'description': f'Build {buildType} using Ninja generator and {config.compiler}',
                'generator': 'Ninja',
                'binaryDir': f'${{sourceDir}}/build/{config.compiler}-{buildType.lower()}',
                'cacheVariables': {'CMAKE_BUILD_TYPE': buildType},
                'environment': {
                    # Here is the ugly line:
                    name: value.get_str(f'$penv{{{{{name}}}}}', envVars._subsystem, envVars._pathsep) for name, value in envVars._values.items()
                }
            }

            if self.cmakeExecutable:
                p['cmakeExecutable'] = self.cmakeExecutable

            return p

        return [preset(buildType) for buildType in config.buildTypes]

    def _buildPresets(self, config):
        """Generate build presets for a specific compiler."""

        def preset(buildType):
            return {
                "name": f"{config.compiler}-{buildType.lower()}",
                "displayName": f"{config.compiler} {buildType}",
                "configurePreset": f"{config.compiler}-{buildType.lower()}",
                "inheritConfigureEnvironment": True
            }

        return [preset(buildType) for buildType in config.buildTypes]

    @property
    def content(self):
        # Generate build environment
        self.env = VirtualBuildEnv(self.conanfile).environment()

        # Check for CMake executable in environment
        if not getattr(self, 'cmakeExecutable', None):
            with self.env.vars(self.conanfile).apply():
                self.cmakeExecutable = shutil.which('cmake')

        # Generate content
        return json.dumps({
            "version": 3,
            "cmakeMinimumRequired": {
                "major": 3,
                "minor": 21,
                "patch": 0
            },
            "configurePresets": [preset for config in self.config for preset in self._configurePresets(config)],
            "buildPresets": [preset for config in self.config for preset in self._buildPresets(config)]
        }, indent=4)

    @property
    def filename(self):
        return os.path.join(self.conanfile.recipe_folder, "CMakePresets.json")

    def generate(self):
        filename = self.filename
        save(self, filename, self.content)
        self.conanfile.output.info(f"Generator CMakePresets created {filename}")


class Project(ConanFile):
    tool_requires = "cmake/3.24.2", "ninja/1.11.0", "gcc/12.2.0"
    settings = "os"

    def generate(self):
        generator = CMakePresetsGenerator(
            self,
            [CMakePresetConfig('gcc')]
        )
        generator.generate()
```

Note: We use conan only to to setup our development toolchain. Building and packaging is not done with conan.

**Comment by memsharded** [comment] 2022-11-02 08:54
A few minor Python things:
- Do not use default args values that are mutable, like `` def __init__(self, compiler, buildTypes=['Debug', 'Release']):``. That ``buildTypes`` can be broken in Python. It is necessary to do something like ``build_types=None``, then internally to the method ``build_types = ["Debug", "Release"] if build_types is None else build_types``
- Do not use attributes like ``self.env`` to pass information to other methods, better pass it explicitly to ``self._configure_presets(config, env)``.
- Also, recommended to use Python convention of ``configure_presets`` and avoid camelCase

Some Conan questions:
- If you are using the ``cmake/3.24.2`` Conan package, the ``self.cmakeExecutable = shutil.which('cmake')`` doesn't make much sense. You already know the ``cmake`` package, no need to do a ``which`` to find it? The asymmetry that you don't need to do it for ``ninja`` is also some evidence that it wouldn't be necessary

The approach that you have there still do not implement fetching multiple Conan package configurations, Release and Debug packages. Only the default ``Release`` packages will be installed for cmake, ninja and gcc, and then you will be generating Release and Debug Presets with exactly the same information about the toolchain locations. What I was commenting above was related to the installation of different Conan package configurations, but yes, we are good here, this is not the case.

I think the main thing is still the ugly line:
```python
'environment': {
                    # Here is the ugly line:
                    name: value.get_str(f'$penv{{{{{name}}}}}', envVars._subsystem, envVars._pathsep) for name, value in envVars._values.items()
                }
```
and understanding what CMakePresets expects there (which is the bit of knowledge that I dont have):

- Is the ``$penv{]`` syntax a CMakePresets specific placeholder?
- Is it the same for all OSs?
- Is it the same for all subsystems (like Msys2 in Windows)?
- Is it case sensitive? In all OSs?
- If the presets are generated basically directly before usage and no other environment is changed (this is the main reason of this generator I guess), is it not good to just let Conan replace the placeholder for the value?

**Comment by rettenbs** [comment] 2022-11-02 09:51
Thank you for the comments regarding the Python. We will look into these issues.

**Regarding `cmake/3.24.2` and `shutil.which('cmake')`:**
You can specify the path to the cmake executable in presets. This is not used by cmake itself and is intended for IDEs that support presets out-of-the-box (e.g. Visual Studio Code).

**About your questions:**
> Is the $penv{] syntax a CMakePresets specific placeholder?

Yes, it is CMakePresets specific and will be replaced by the variables from the "parent" environment, i.e. the environment that is set when calling cmake.

> Is it the same for all OSs?

Yes.

> Is it the same for all subsystems (like Msys2 in Windows)?

Not tested, but I assume yes.

> Is it case sensitive? In all OSs?

From cmake documentation:
>> Note that while Windows environment variable names are case-insensitive, variable names within a preset are still case-sensitive. This may lead to unexpected results when using inconsistent casing. For best results, keep the casing of environment variable names consistent.

I assume as long as you do not mix `$penv{PATH}` and `$penv{path}` in the presets file, you should be fine.

> If the presets are generated basically directly before usage and no other environment is changed (this is the main reason of this generator I guess), is it not good to just let Conan replace the placeholder for the value?

We are discussing this solution as well. It has some disadvantages for your uses cases. Hence, it is not the preferred solution.

**Comment by memsharded** [comment] 2022-11-02 10:32
> You can specify the path to the cmake executable in presets. This is not used by cmake itself and is intended for IDEs that support presets out-of-the-box (e.g. Visual Studio Code).

I meant that you might access directly the folder with ``self.dependencies["cmake"].cpp_info.bindir``, so no need to use a ``which`` to get it, Conan knows the folder already. Then you can pass it to Presets.

Thanks for the feedback, adding a ``look-into`` label to discuss with the team this potential feature

**Comment by rettenbs** [comment] 2022-11-02 11:05
> I meant that you might access directly the folder with `self.dependencies["cmake"].cpp_info.bindir`, so no need to use a `which` to get it, Conan knows the folder already. Then you can pass it to Presets.

That is possible, yes. We might need to distinguish between Linux (`cmake`) and Windows (`cmake.exe`) for the exact path to the executable in this case.

> Thanks for the feedback, adding a `look-into` label to discuss with the team this potential feature

Thank you very much. I am looking forward to the result of the discussion.

**Comment by memsharded** [comment] 2022-11-15 13:50
Implemented in https://github.com/conan-io/conan/pull/12517, will be in next 1.55. Thanks for all the feedback!

**Closed as completed** 2022-11-15 13:49 UTC
Labels: type: look into, stage: triaging

**Comment by rettenbs** [comment] 2022-11-15 15:25
Nice, this should work for our use cases.
