### ISSUE TITLE
[bug] When cross-compiling with android-ndk, CMake cache_variables are not set in the CMakeCache.txt every other run

### ISSUE THREAD

**Issue by bemehiser** [conan-io/conan#16960] opened 2024-09-09 14:20 UTC
### Describe the bug

When running with Android NDK the CMake cache_variables aren't set in the CMakeCache.txt every-other time conan is run. This bug appeared in conan 2.7.0, and 2.6.0 does not have the bug.

In this error output, you can see that a version cache_variable was not set, and causes a CMake error. Manual inspection of the CMakeCache.txt shows that the environment variable was never set by conan.
```
[root@caacb8c5e579 sdk]# conan build --build missing --profile:host profiles/android-armv8 --profile:build default --settings build_type=Release .

======== Input profiles ========
Profile host:
[settings]
arch=armv8
build_type=Release
compiler=clang
compiler.cppstd=gnu17
compiler.libcxx=c++_static
compiler.version=13
os=Android
os.api_level=21
[tool_requires]
*: cmake/3.30.1, android-ndk/r27
[conf]
tools.build:skip_test=True

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu17
compiler.libcxx=libstdc++11
compiler.version=13
os=Linux


======== Computing dependency graph ========
Graph root
    conanfile.py (sdk/1.0.0): /sdk/conanfile.py
Build requirements
    android-ndk/r27#3fd58ec1d8ff51f0aa717227b4404d17 - Cache
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb - Cache

======== Computing necessary packages ========
Build requirements
    android-ndk/r27#3fd58ec1d8ff51f0aa717227b4404d17:63fead0844576fc02943e16909f08fcdddd6f44b#fbd2d8eaf905d9079b1b6ce862b5cf66 - Cache
    cmake/3.30.1#6d832cf2d46f6ec969ca5ed5b41f91eb:63fead0844576fc02943e16909f08fcdddd6f44b#041a38980949bccd356d9142f4e0a2bf - Cache

======== Installing packages ========

======== Installing packages ========
android-ndk/r27: Already installed! (1 of 2)
cmake/3.30.1: Already installed! (2 of 2)
cmake/3.30.1: Appending PATH environment variable: /sdk/.conan2/p/cmakefaa1321642d5b/p/bin
WARN: deprecated: Usage of deprecated Conan 1.X features that will be removed in Conan 2.X:
WARN: deprecated:     'env_info' used in: cmake/3.30.1

======== Finalizing install (deploy, generators) ========
conanfile.py (sdk/1.0.0): Writing generators to /sdk/build/android-armv8/Release/generators
conanfile.py (sdk/1.0.0): Generator 'CMakeDeps' calling 'generate()'
conanfile.py (sdk/1.0.0): Generator 'VirtualBuildEnv' calling 'generate()'
conanfile.py (sdk/1.0.0): Calling generate()
conanfile.py (sdk/1.0.0): Generators folder: /sdk/build/android-armv8/Release/generators
conanfile.py (sdk/1.0.0): CMakeToolchain generated: conan_toolchain.cmake
conanfile.py (sdk/1.0.0): CMakeToolchain: Preset 'conan-android-armv8-release' added to CMakePresets.json.
    (cmake>=3.23) cmake --preset conan-android-armv8-release
    (cmake<3.23) cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake  -DSDK_VERSION=1.0.0 -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/sdk/.conan2/p/androaa54feb99bd15/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang -DCMAKE_CXX_COMPILER=/sdk/.conan2/p/androaa54feb99bd15/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
conanfile.py (sdk/1.0.0): CMakeToolchain generated: /sdk/build/android-armv8/Release/generators/CMakePresets.json
conanfile.py (sdk/1.0.0): CMakeToolchain generated: /sdk/CMakeUserPresets.json
conanfile.py (sdk/1.0.0): Generating aggregated env files
conanfile.py (sdk/1.0.0): Generated aggregated env files: ['conanbuild.sh', 'conanrun.sh']

======== Calling build() ========
conanfile.py (sdk/1.0.0): Calling build()
conanfile.py (sdk/1.0.0): Running CMake.configure()
conanfile.py (sdk/1.0.0): RUN: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/sdk" -DSDK_VERSION="1.0.0" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DBUILD_TESTING="OFF" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_COMPILER="/sdk/.conan2/p/androaa54feb99bd15/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" -DCMAKE_CXX_COMPILER="/sdk/.conan2/p/androaa54feb99bd15/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++" "/sdk"
-- Using Conan toolchain: /sdk/build/android-armv8/Release/generators/conan_toolchain.cmake
-- Conan toolchain: Setting Android platform: android-21
-- Conan toolchain: Setting Android stl: c++_static
-- Conan toolchain: Setting Android abi: arm64-v8a
-- Conan toolchain: C++ Standard 17 with extensions ON
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
-- Configuring done (0.0s)
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_C_COMPILER= /sdk/.conan2/p/androaa54feb99bd15/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
CMAKE_CXX_COMPILER= /sdk/.conan2/p/androaa54feb99bd15/p/bin/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++

CMake Error at CMakeLists.txt:9 (project):
  VERSION ".0" format invalid.


-- Configuring incomplete, errors occurred!

ERROR: conanfile.py (sdk/1.0.0): Error in build() method, line 34
	cmake.configure()
	ConanException: Error 1 while executing

```

### How to reproduce it

I have attached a .tar.gz with a basic docker-container reproduction (install docker on x86_64, run a few commands, and you have a repro.)
[repro.tar.gz](https://github.com/user-attachments/files/16931831/repro.tar.gz)

```
# Download repro.tar.gz and extract the reproduction
tar xzvf repro.tar.gz

# On an x86_64 machine, run the following command to create the environment.
docker compose run dev

# Inside the dev machine, run this command to reproduce the issue.
# The issue will reproduce ON THE SECOND RUN. The first command run will work perfectly.
conan build --build missing --profile:host profiles/android-armv8 --profile:build default --settings build_type=Release .
```

This error reproduction is inside a docker container, but it has appeared on bare-metal machines etc. It's not caused by docker.

**Comment by memsharded** [comment] 2024-09-09 19:23
Thanks for your report @bemehiser, and thanks specially for providing code to reproduce.

I have checked the diff between release/2.6 and release/2.7 and at first sight I don't see anything evident that could be introducing this regression.
Does your code above can be used for both Conan versions and how? Thanks!

**Comment by czoido** [comment] 2024-09-10 09:23
Hi @bemehiser,

Thanks a lot for reporting. I could reproduce the issue and I suspect that it's related to these changes: https://github.com/conan-io/conan/pull/16762 and how CMake behaves when cross-compiling. Looks related with the fact that we pass now `-DCMAKE_CXX_COMPILER=` with a value different from the one that CMake stored in the CMake cache and CMake deletes all set variables after considering that it has to re-configure. 
I'm assigning to the 2.8 milestone to investigate the issue in more depth.

**Comment by czoido** [comment] 2024-09-10 17:21
Hi @bemehiser, we have finally decided to revert https://github.com/conan-io/conan/pull/16762 and release Conan 2.7.1 that will probably be released tomorrow.
Thanks a lot for reporting and sorry for the inconvenience.

**Comment by czoido** [comment] 2024-09-11 09:36
Closed by https://github.com/conan-io/conan/pull/16971
Test added in https://github.com/conan-io/conan/pull/16974
Thanks a lot @bemehiser for reporting

**Closed as completed by czoido** 2024-09-11 09:36 UTC

**Comment by petwu** [comment] 2024-09-12 11:10
I did some more investigation on this issue and here are my findings:

**Why does it happen?**  
First, I found it weird that my PR #16762 could change the `conan build` behavior, because I assumed conan did not use the generated presets file, but as it turns out the cache variables from the generated preset are used as to construct the command line arguments for the configure call ([here](https://github.com/conan-io/conan/blob/release/2.7/conan/tools/cmake/cmake.py#L50)). Therefore, the changes introduced by #16762 cause the `-DCMAKE_<LANG>_COMPILER=...` arguments to be passed to the cmake call. This is not a problem in most cases, where the value of the command line argument and the value set by the toolchain are identical. But for NDK, these values differ, e.g. `-DCMAKE_C_COMPILER=.../aarch64-linux-android21-clang` is passed, but the toolchain overrides this with `CMAKE_C_COMPILER=.../clang`, which ends up in the cache and causes a conflict every other run. The override is done either by NDK [here](https://android.googlesource.com/platform/ndk/+/refs/tags/ndk-r27/build/cmake/android-legacy.toolchain.cmake#600) if `ANDROID_USE_LEGACY_TOOLCHAIN_FILE` is unset or true, or otherwise directly by CMake [here](https://github.com/Kitware/CMake/blob/v3.30.3/Modules/Platform/Android/Determine-Compiler.cmake#L78). As far as I can tell, this holds for NDK >=r19.

**Possible Solution**  
The easiest solution to implement #16762 and prevent this bug is IMO to exclude all `CMAKE_<LANG>_COMPILER` variables from being passed as arguments to cmake in `CMake.configure()`. Something like this:
```diff
diff --git a/conan/tools/cmake/cmake.py b/conan/tools/cmake/cmake.py
index 2efa8f37a..65857a194 100644
--- a/conan/tools/cmake/cmake.py
+++ b/conan/tools/cmake/cmake.py
@@ -1,4 +1,5 @@
 import os
+import re
 
 from conan.tools.build import build_jobs, cmd_args_to_string
 from conan.tools.cmake.presets import load_cmake_presets
@@ -103,6 +104,12 @@ class CMake:
         if not variables:
             variables = {}
         self._cache_variables.update(variables)
+        # Don't pass compiler variables via the command line, because the toolchain might override
+        # them (e.g. Android NDK), which would lead to a cache mismatch every other configuration.
+        # See https://github.com/conan-io/conan/issues/16960.
+        self._cache_variables = {
+            k: v for k, v in self._cache_variables.items() if not re.match(r"CMAKE_\w+_COMPILER", k)
+        }
 
         arg_list.extend(['-D{}="{}"'.format(k, v) for k, v in self._cache_variables.items()])
         arg_list.append('"{}"'.format(cmakelist_folder))
```
This way, only the presets are affected and the old behavior is not changed. Passing the compiler paths directly via `-D` is redundant anyway, because the toolchain sets them anyway.

@czoido What do you think?

**Comment by memsharded** [comment] 2024-09-25 21:34
I am having a look to see how that PR can be back for Conan 2.8, without breaking.

I am a bit confusing about the ``android-ndk`` recipe defining the ``compiler_executables`` in https://github.com/conan-io/conan-center-index/blob/0ef08b7b2f6aba47639a5dfeddfd19a4fdce0601/recipes/android-ndk/all/conanfile.py#L296

It seems that defining such path for CMake consumers is actually incorrect? I see it might help for other tools like Autootools or Meson, but for CMake, as it seems CMake or the AndroidNDK.cmake toolchain themselves will be defining and changing this?
