### ISSUE TITLE
[question] Dynamic package version gives lockfile error

### ISSUE THREAD

**Issue by SeanSnyders** [conan-io/conan#8646] opened 2021-03-15 02:40 UTC
- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

```
conan install . -o shared=True -s build_type=Debug -if=cmake-build-debug -e CONAN_RUN_TESTS=1
```

```
conan build . -c -b -bf cmake-build-debug
```

Gives error:
```
Using lockfile: '<repo_root>/cmake-build-debug/conan.lock'
Using cached profile from lockfile
ERROR: Package recipe with version 0.1.0!=0.0.0
```

Not sure if this a bug, as I can successfully build into the local cache via the `conan export ....` and `conan install --build=MyProject ...` command.
I always want to dynamically use the version in the `version.txt` file.

------

`version.txt`

```
0.1.0
```

`conanfile.py`

```python
class MyProjectConan(ConanFile):
    name = "MyProject"
    version = "0.0.0"

    def set_version(self):
            content = tools.load(os.path.join(self.recipe_folder, "version.txt"))
            self.version = content.strip()

    ....
    ...
    .
```

`<repo_root>/cmake-build-debug/conan.lock`

```json
{
 "graph_lock": {
  "nodes": {
   "0": {
    "ref": "MyProject/0.1.0",
    "options": "shared=True",
    "build_requires": [
     "1",
     "3"
    ],
    "path": "../conanfile.py",
    "context": "host"
   },
   "1": {
    "ref": "cmake/3.19.4",
    "options": "with_openssl=True\nopenssl:386=False\nopenssl:fPIC=True\nopenssl:no_aria=False\nopenssl:no_asm=False\nopenssl:no_async=False\nopenssl:no_bf=False\nopenssl:no_blake2=False\nopenssl:no_camellia=False\nopenssl:no_cast=False\nopenssl:no_chacha=False\nopenssl:no_cms=False\nopenssl:no_comp=False\nopenssl:no_ct=False\nopenssl:no_deprecated=False\nopenssl:no_des=False\nopenssl:no_dgram=False\nopenssl:no_dh=False\nopenssl:no_dsa=False\nopenssl:no_dso=False\nopenssl:no_engine=False\nopenssl:no_filenames=False\nopenssl:no_gost=False\nopenssl:no_hmac=False\nopenssl:no_idea=False\nopenssl:no_md4=False\nopenssl:no_md5=False\nopenssl:no_mdc2=False\nopenssl:no_ocsp=False\nopenssl:no_pinshared=False\nopenssl:no_rc2=False\nopenssl:no_rmd160=False\nopenssl:no_rsa=False\nopenssl:no_sha=False\nopenssl:no_sm2=False\nopenssl:no_sm3=False\nopenssl:no_sm4=False\nopenssl:no_srp=False\nopenssl:no_srtp=False\nopenssl:no_sse2=False\nopenssl:no_ssl=False\nopenssl:no_threads=False\nopenssl:no_ts=False\nopenssl:no_whirlpool=False\nopenssl:openssldir=None\nopenssl:shared=False",
    "package_id": "cf36af68367ac960cc1360ef3ea3c735fa475414",
    "prev": "0",
    "requires": [
     "2"
    ],
    "context": "host"
   },
   "2": {
    "ref": "openssl/1.1.1i",
    "options": "386=False\nfPIC=True\nno_aria=False\nno_asm=False\nno_async=False\nno_bf=False\nno_blake2=False\nno_camellia=False\nno_cast=False\nno_chacha=False\nno_cms=False\nno_comp=False\nno_ct=False\nno_deprecated=False\nno_des=False\nno_dgram=False\nno_dh=False\nno_dsa=False\nno_dso=False\nno_engine=False\nno_filenames=False\nno_gost=False\nno_hmac=False\nno_idea=False\nno_md4=False\nno_md5=False\nno_mdc2=False\nno_ocsp=False\nno_pinshared=False\nno_rc2=False\nno_rmd160=False\nno_rsa=False\nno_sha=False\nno_sm2=False\nno_sm3=False\nno_sm4=False\nno_srp=False\nno_srtp=False\nno_sse2=False\nno_ssl=False\nno_threads=False\nno_ts=False\nno_whirlpool=False\nopenssldir=None\nshared=False",
    "package_id": "647afeb69d3b0a2d3d316e80b24d38c714cc6900",
    "prev": "0",
    "context": "host"
   },
   "3": {
    "ref": "gtest/1.10.0",
    "options": "build_gmock=True\nfPIC=True\nhide_symbols=False\nno_main=False\nshared=False",
    "package_id": "9e8e90672d7a216fdaac8d6a37a0bbd4a25f56a6",
    "prev": "0",
    "context": "host"
   }
  },
  "revisions_enabled": false
 },
 "version": "0.4",
 "profile_host": "[settings]\narch=x86_64\narch_build=x86_64\nbuild_type=Release\ncompiler=apple-clang\ncompiler.libcxx=libc++\ncompiler.version=12.0\nos=Macos\nos_build=Macos\n[options]\n[build_requires]\n[env]\n"
}
```

**Comment by solvingj** [comment] 2021-03-15 16:50
We had a similar situation with `options` and `configure()`/`config_options()` documented here:

https://github.com/conan-io/conan/issues/7991

It was fixed in a subsequent PR. 

It's similar in that, it relates to the timing of enforcement, when there are dynamic methods which can change values.  In this case, you have a `version` attribute, and then a `set_version` method, and clearly the lockfile enforcement is happening before the `set_version` method.  Hopefully, this means it's a simple bug, and will be straightforward to fix.

@memsharded should I change this to bug and add it to 1.35 milestone?

**Comment by SeanSnyders** [comment] 2021-03-15 20:49
Fiddling some more with this, if I set the version to `None` in the package class, then it seems to not give me the error:

`conanfile.py`

```python
class MyProjectConan(ConanFile):
    name = "MyProject"
    version = None

    def set_version(self):
            content = tools.load(os.path.join(self.recipe_folder, "version.txt"))
            self.version = content.strip()

    ....
    ...
    .
```

**Comment by solvingj** [comment] 2021-03-15 21:17
I was wondering about that. Is it a reasonable workaround for you? It probably won't change the outcome of the ticket, but might change the priority/timeline.

**Comment by SeanSnyders** [comment] 2021-03-15 21:25
Yes, the workaround is fine for us, thanks.

**Comment by memsharded** [comment] 2021-03-15 21:58
I have been checking the code, and it seems that by design, when the version or the name are set in ``set_version`` or ``set_name``, they shouldn't be declared too as a recipe attribute, only inside the method, which makes sense to avoid confusing about possible priorities and conflicts. Maybe https://docs.conan.io/en/latest/reference/conanfile/methods.html#set-name-set-version is not enough clear, I think that adding a note there could be enough.

**Comment by solvingj** [comment] 2021-03-16 13:58
Good idea. PR submitted.

**Comment by memsharded** [comment] 2021-03-16 17:46
Closed by https://github.com/conan-io/docs/pull/2043

**Closed as completed by memsharded** 2021-03-16 17:46 UTC
