### ISSUE TITLE
[question] conan create with template rendering

### ISSUE THREAD

**Issue by ericjameszimmerman** [conan-io/conan#6663] opened 2020-03-11 17:32 UTC
We are using python-based build scripts which call conan commands (e.g. creating all package versions for a specific library, etc.)

As part of that, we are using jinja to render a .h file which includes version / build info from our CI server. When I call `conan create`, it fails to find the header since it doesn't exist within the conan directory structure.

1. Has anyone done this before?
2. What is the appropriate way to add include paths during packaging or placing the include file within the proper path? ... I looked briefly at exporting that file, but not sure whether I know where it would end up.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2020-03-11 18:05
Quick question: the header is created before calling ``conan create``, that is, at user space? In that case, it seems that yes, ``exports`` or ``exports_sources`` is the way to go. What method are you using to manage the sources, "exports", "scm" or do you have the recipe in another repository?

**Comment by ericjameszimmerman** [comment] 2020-03-11 18:11
yes, header was created in user space before calling `conan create` ... I am open to rendering from the conanfile if there is an alternative way.

I am using 'scm' with 'auto' method, which has worked the best to date.
The recipe is in the same repo as the source.

**Comment by memsharded** [comment] 2020-03-11 18:35
Ok, so the problem is that you are running something after "git clone" and "conan create" that generate that header? In that case, I see the issue, that will only work when locally creating the package, but if that package is created later from the recipe and the SCM information, then that file will not be available. Could you please outline a bit more your overall process? Wouldn't it be possible to automate the generation of the header file in the conanfile.py recipe? That would make it reproducible in all contexts.

**Comment by memsharded** [comment] 2023-12-31 00:10
Closing the ticket as staled. Also tons of things have changed since then with the ``layout()`` method, ``scm`` was removed, etc.
Please open new tickets if necessary, thanks!

**Closed by memsharded** 2023-12-31 00:10 UTC
Labels: type: question, stage: triaging
