### ISSUE TITLE
Very large packages (>2GB?) cannot be uploaded to Artifactory

### ISSUE THREAD

**Issue by mpdelbuono** [conan-io/conan#2184] opened 2017-12-20 01:42 UTC
The package successfully gets created, but during `conan upload` the upload fails:
```
Error uploading file: conan_sources.tgz, 'long int too large to convert to int'
```

To be clear - this is a very large package (2.5 GB sources; I'm not sure what it is compressed). I'm assuming this is hitting the 2^31 limit and then failing.

I have ways to work around this, so maybe it's not a serious issue, however I was hoping not to use `source()` here (and I'm also not certain I wouldn't just hit the same problem at the package stage, instead of the source stage). I also assume I'm not going to be the last person to hit this case, even though the use case is unusual (there probably aren't many packages out there that need to fit this much stuff together).

I'm having trouble determining if this is an Artifactory error or a conan error; there is nothing in my Artifactory logs to suggest it's an error in Artifactory, but the way conan reacts suggests that it was an error code reported by Artifactory.

**Comment by mpdelbuono** [comment] 2017-12-20 01:45
Sorry - I should include that this is tested on conan 0.28.1 with Artifactory 5.6.2. I would use a later version of conan but unfortunately a few incompatibilities are holding us back from 0.30 until we fix up our conan files, and the VS9 CMake defect prevents us from going to 0.29. However, I think that there hasn't been any significant changes in this area between 0.28 and 0.30 that would fix it.

**Comment by lasote** [comment] 2017-12-20 08:17
I'll perform some tests with big files, no errors reported so far related to this. Will report soon.

**Comment by lasote** [comment] 2017-12-20 08:54
Python version? Operating system? 32 or 64? Conan installed from pip?
I'm not able to reproduce the error so far, more than 4gb in `conan_sources.tgz` uploaded ok.

**Comment by mpdelbuono** [comment] 2017-12-20 19:45
Looks like I have tracked this down to the 32-bit vs 64-bit distinction in Python.

While Python on the client in question was a 64-bit version of Python, conan was installed via the Windows installer. The Windows installer is packaged with a 32-bit version of Python (tested by creating a conanfile that outputs `sys.maxsize` and `platform.architecture()`).

I also opened Wireshark and noticed that the request to Artifactory is to PUT the file with content-length set to 0 (which Artifactory refuses, with good reason).

I installed conan via pip and could no longer reproduce the issue, presumably because it was now on a 64-bit version of Python. When going back to the Windows installer version, I can reproduce the issue again. However, pip is not a good mechanism for us to install because all of our build servers are on a segregated network, so they can't access that repository. But that's my problem, not yours  :)

So... I guess this can be closed with no action since the answer is "run on Python 64-bit". However, I wonder if a 32-bit vs 64-bit installer for Windows can be created, since pip may be inconvenient for some users.

**Comment by memsharded** [comment] 2017-12-20 22:51
Indeed the recommended way to use conan is with the ``pip`` installed package. The windows .exe installer (and other installers), are created with pyinstaller, which generally works great, but has some limitations. 

Have you tried installing the pip package from Artifactory? I guess you should have access to it in your network, right? That could be a good way, because you also control the conan version, and don't get unexpected upgrades.

**Comment by mpdelbuono** [comment] 2017-12-21 00:55
I hadn't considered creating a proxy pypi repository. That solution works well, and so we're now holding onto conan and the various dependencies in there. That is a good solution; thanks for the suggestion.

At this point we can probably close the issue as related to Python version rather than conan (unless a fix for making it work on 32-bit Python is really desirable).

**Comment by memsharded** [comment] 2017-12-21 23:05
> I hadn't considered creating a proxy pypi repository. That solution works well, and so we're now holding onto conan and the various dependencies in there. That is a good solution; thanks for the suggestion.

Excellent! Happy to help.

> At this point we can probably close the issue as related to Python version rather than conan (unless a fix for making it work on 32-bit Python is really desirable)

I think that is a limitation of python 32bits, (https://stackoverflow.com/questions/18282867/python-32-bit-memory-limits-on-64bit-windows), and the solution seems re-building python itself with some special flags, and cross-fingers... basically they recommended moving to 64bits python. I think it is not something we can fix, so I am closing the issue at the moment :)
Thanks for all your feedback!

**Closed by memsharded** 2017-12-21 23:05 UTC

**Comment by mmatrosov** [comment] 2017-12-22 09:15
> basically they recommended moving to 64bits python. I think it is not something we can fix, so I am closing the issue at the moment :)

What do you mean by "moving to 64bits python"? We can already install conan to 64-bit python and it works great. Can't we create an installer from this setup?

**Comment by memsharded** [comment] 2017-12-22 09:30
The distributed installers in the conan download page are based on the system defaults, an in Windows it is the 32bits. If you install conan in python 64 bits with ``pip install``, then it is good on the  memory limit. Otherwise current ".exe" installers are 32bits and will be limited, they are not using any python in the system, they embed a 32bits python interpreter. Maybe we could create installers for Win64 bits, but for that we need to setup some infrastructure, so it might take time, and one more piece to maintain. I'll discuss this with the team.

**Comment by mmatrosov** [comment] 2017-12-22 10:58
> The distributed installers in the conan download page are based on the system defaults, an in Windows it is the 32bits.

Not sure I understood correctly. I've just tried using PyInstaller for my 64-bit Python 3.6 with conan installed in it, and it produced 64-bit conan.exe.

**Comment by memsharded** [comment] 2017-12-22 11:33
> Not sure I understood correctly. I've just tried using PyInstaller for my 64-bit Python 3.6 with conan installed in it, and it produced 64-bit conan.exe.

Yes, that is totally right. I meant the self-extracting conan-win-version.exe installer that you can download from https://www.conan.io/downloads, this is the one that was created with Python 32 bits. If you are going to  automate the installation, you should be better with just the generated exe from pyinstaller, instead of having to fiddle with the self-extracting installer.

**Comment by mmatrosov** [comment] 2017-12-22 11:37
So there is no obstacle preventing you from distributing 64-bit installers, it is simply not done yet, correct?

**Comment by memsharded** [comment] 2017-12-22 12:09
Yes. We will probably soon be moving our infrastructure for generating the installers, I will have a look and try to generate the 64 bits one.

**Comment by mmatrosov** [comment] 2017-12-22 12:35
Ok, great, looking forward to it!
