### ISSUE TITLE
[feature] copy package contents into user space

### ISSUE THREAD

**Issue by PengolodhGoedath** [conan-io/conan#8858] opened 2021-04-24 13:22 UTC
# Problem

For context: I'm currently trying to collect files from a given package reference in an automated environment. The files to collect are unit test reports, and I only have the package reference to access them - no `settings` or `options` - but the package reference includes at the very least a package id, and possibly revisions as well.

It would make my work much easier if there was a conan command, which would just dump all files from a given package reference into the current working directory.

This feature could also be interesting outside of automated environments, e.g. to allow QA or developer to check out specific package id results.

# Tried solutions

I have tried (and found) some solutions, which might achieve the given goal. Here's my experience so far:

1. `conan install` with `deploy()`: Sadly, this one doesn't work, as there is no way to call `conan install` on a reference which includes a package id. As a possible workaround, I have looked for means to extract the used `settings`, `options` etc. from the reference, and `conan get ${reference}` is able to do that, just requiring parsing of the INI-style conaninfo.txt. I am not sure how maintainable this approach is going to be, and it also requires a specific `deploy()` implementation.
2. `conan get`: This should have been my first starting point. Recursing through the directories inside the package kinda works, but it is hard to tell directory listings apart from file contents, since the output differs only in the first line (and that is banking on the fact no text file is starting with the line `"Listing directory '${relativePath}':"`). It somewhat works, but has to go through some hoops to achieve results, with the danger of maliciously prepared text files pretending to be directory listings.
3. `conan download` and `conan info`: Use `conan download` to download the reference into the local cache, then use `conan info --paths` and retrieve the `package_folder`. Copy files from there. Simplest solution so far, but might break in case the local cache gets changed or the reference format gets changed (need to strip package id for calling `conan info`). I'm not sure how maintainable accessing the local cache directly will be.

# Proposed feature

Of all listed commands `conan get` seems most in line with the spirit of this request. Maybe an option `--dump-files pattern` or similar could be added to copy the files into the current working directory (instead of writing them on stdout)? If it is too much of a stretch for `conan get`, it could also possibly get its own subcommand (`conan unpackage`?).

Alternatively, a `conan deploy reference` command might achieve the intended result of calling `conan install reference` when said reference includes a package id (and possibly revisions).

**Comment by memsharded** [comment] 2021-04-24 17:46
Hi @PengolodhGoedath 

Certainly, this is not possible right now with Conan, at least directly. All commands are designed to use the input profile (settings, options), and compute the package_id internally.

We will work for better "deploy" support in Conan 2.0, meanwhile I'd say your third option is the closest:
- But it uses the ``conan info``. The ``conan info`` command already needs profile/settings/options. If you have them, then you could use the imports or deploy functionality easily directly. 
- So you can access the folder directly. The layout of the cache is not complicated at the moment, doing a ``cp -R ~/.conan/data/mypkg/myversion/myuser/mychannel/package/<package-id> .`` will do it. No much need to do ``conan info``, if you don't have settings/options. If it happens to be a "short-paths" folder, you will have there a file with the real folder containing it. The cache layout is not likely to change until Conan 2.0.

In any case, I would really like to know why you don't have access to settings/options. Actually it should be a profile file, with a name, not bare settings and options. Profiles are really recommended to manage configurations. Packages are managed with profiles (or lockfiles), because copying a given <package-id> is typically non-informative, you typically want to copy the "windows,msvc,16,cppstd14,MT..." package, which internally will map to a <package-id>. 

Could you please clarify your use case? That could be useful information to design the new deploy functionality in Conan 2.0.

**Comment by PengolodhGoedath** [comment] 2021-04-24 21:28
Oh, thanks for clarifying the `conan info` workings, I mostly just assumed (after a quick test when writing this proposal) that it would list all packages for a given package (name/version). This seems to be false (I guess it uses the default profile instead.)

---

The reason I don't care about profiles (or combinations of `settings`, `options` etc.) is that I'm working with already created packages. For one, I have to uniquely identify each package revision, and as far as I know, that is only possible using the long reference format `name/version@user/channel#RREV:PACKAGEID#PREV`. Using profiles doesn't get me to a specific package revision.

And I need the contents of that specific revision, not any other.

In my case, after each build in the CI I am left with a list of package revisions that were built, and I'm aggregating the test reports from these package revisions in order to further process them. I can't really do that during the package creation step for multiple reasons, some of which are that 1) I cannot write a generic consumer recipe (like a test package, but producing a package itself), 2) a recipe cannot require multiple different configurations of the same package and 3) builds of different configurations are distributed (so I can't just write the results somewhere in a common location). However, I can record the package revisions created and process them in another step/pipeline, so that is what I am doing.

---

Another use case would be to explicitly checkout specific package revisions, e.g. to track down a bug. Currently that would require some manual overhead, especially since the local cache cannot hold multiple revisions of a specific package id. It would be nice to use conan to manage package revisions, not just packages.

**Comment by memsharded** [comment] 2021-04-24 22:35
Thanks for clarifying, now I understand a bit better.

Just a note, because in general, for debugging, and retrieving exactly one revision for a given build, you might want to have a look to lockfiles, if you haven't yet. They capture a snapshot of the exact build including dependencies, and the host and build profiles, it is the most complete information to reproduce a dependency graph. Because retrieving a specific package to user space, in isolation many times is not useful without the dependencies. 

> 1) I cannot write a generic consumer recipe (like a test package, but producing a package itself), 2) a recipe cannot require multiple different configurations of the same package and 3) builds of different configurations are distributed (so I can't just write the results somewhere in a common location). However, I can record the package revisions created and process them in another step/pipeline, so that is what I am doing.

I would say that recording the lockfiles of each build, and creating a lockfile bundle for all different configurations might be useful for your use case. Then, if later you want to reproduce or collect to user space some files, you could do imports/deploy over such lockfiles.

I am not saying that we will not consider this for the new deploy functionalities for Conan 2.0, just some pointers that could help in case you haven't considered them yet. Thanks for the feedback!

**Comment by memsharded** [comment] 2022-03-07 23:20
We have implemented and released in 2.0-alpha the new "deployers", which fulfill exactly this requirement and provides the necessary user flexibility to cover different use cases. Documentation ongoing.

**Closed as completed by memsharded** 2022-03-07 23:20 UTC
Labels: stage: triaging
