### ISSUE TITLE
Building Linux (WSL) and Windows package from single folder different hash due to permissions

### ISSUE THREAD

**Issue by holybrake** [conan-io/conan#3067] opened 2018-06-18 15:14 UTC
Conan Version: 1.2.3 ; 1.3.1. ; 1.4.4

1)  creating recipe with export_sources 
2)  building and uploading under windows
3)  Running WSL , building under Linux **in the same folder**
4) Trying to upload => the local recipe differs from server one

The source of trouble is executable bits, that setted to windows filesystem 

Seems we need some kind of UMASK option for export_sources files

**Comment by lasote** [comment] 2018-06-18 16:04
Just to be sure, the issue is not because of using the same folder, right? it is happening EVEN using the same folder, correct?

**Comment by holybrake** [comment] 2018-06-18 16:35
Yes, the issue is because using windows volume inside WSL

**Comment by lasote** [comment] 2018-07-09 08:55
@memsharded I know. That is why I labeled as "look into" and not as "feature approved". It is not clear that we can/should do anything about it yet.

**Comment by memsharded** [comment] 2018-07-13 11:03
@holybrake 

Any feedback regarding the permissions? Could you please have a look? 1.6 is approaching, and we would like to know a bit more to evaluate what could be done. Thanks!

**Comment by holybrake** [comment] 2018-07-13 12:38
@memsharded  Sorry for delay, this is it:
`$tar -tavf ~/.conan/data/bzip2/1.0.6-2/test/t34/export/conan_sources.tgz
-rwxr-xr-x 0/0             439 1970-01-01 03:00 CMakeLists.txt
$ tar -tavf /mnt/e/packages/bzip2/1.0.6-2/test/t34/export/conan_sources.tgz
-rw-r--r-- 0/0             439 1970-01-01 03:00 CMakeLists.txt
h`

as you see we have execute bits setted inside wsl

**Comment by holybrake** [comment] 2018-07-26 12:42
@memsharded 
Basically, Windows has no executable bits, so WSL volume detection will be enough to strip them.
Another similar case is Windows folder mounted to Docker container, it has execute bits set also.

Workaround approach is to add --umask  argument to Conan's 'upload' command.

**Comment by memsharded** [comment] 2018-08-28 11:54
I have been checking this, but the ``--umask`` seems to much of a workaround to be implemented, and it could have other side effects (for example, the .tgz created is cached, so subsequent calls with different ``--umask`` might have the wrong behavior).

I am thinking that maybe it is necessary to review the checks that are done on upload, and re-consider to use the manifest of the contents instead of the md5 of the .tgz file. This could be related to ongoing work on an v2 API with the server. Moving this issue forward to discuss it in 1.8.

**Comment by memsharded** [comment] 2018-09-17 09:10
This should be fixed by: https://github.com/conan-io/conan/issues/3067

Those changes do the diff based on the manifests, not in the checksum of the .tgz, so the permissions and mask shouldn't be an issue anymore. It will be released in conan 1.8, but if you could try it running from sources "develop" branch, that would help a lot. Many thanks!

**Closed by memsharded** 2018-09-17 09:10 UTC
Labels: Feedback please!, help wanted, look into
