### ISSUE TITLE
conans module not available from python package

### ISSUE THREAD

**Issue by Manu343726** [conan-io/conan#3019] opened 2018-06-10 11:33 UTC
*Tested with conan 1.4.3*

Hi,

I'm trying to write a python package with tools for my recipes. I would like to write default `source()`, `build()`, and `package()` methods with the patterns I follow, so I have python modules in my python package with functions like:

``` python
# build.py module
from conans import CMake

def parallel_build(conanfile):
    if debugging build etc etc return false

def cmake(conanfile):
    cmake = CMake(conanfile, parallel=parallel_build(conanfile))
    ...
```

but when one of my recipes use the functionallity, I get import errors:

``` python
class LibFoo(ConanFile):
    requires = 'recipes/0.1@...'

    def build(self):
        from build import cmake # Error from here: Cannot import conans
        cmake(conanfile) 
```

As you can see, it seems that the conans package is not available from inside the the python package modules.

I'm not sure this is the intended behavior or that if this feature (common recipe scripts in python packages) is still wip.

Thanks.

**Comment by memsharded** [comment] 2018-06-10 20:49
How did you install conan? From pip? Same error in all OSs? Which OSs? Which python versions?

I think this should work if everything is setup correctly, but even though, might not be a good approach, specially if you are working on recipes for public OSS packages. If they are for your own internal usage, then it could be enough (until python_requires are released, yes, they are still WIP)

**Comment by lasote** [comment] 2018-06-11 06:29
You are creating a circular dependency between the recipe and the `build.py` that's why it fails.

**Comment by memsharded** [comment] 2018-06-11 08:17
Even if the import is local?
Note:
```python
def build(self):
        from build import cmake # Error from here: Cannot import conans
        cmake(conanfile) 
```

**Comment by lasote** [comment] 2018-06-11 09:45
You are right, it should work and actually works. I've tried it: https://github.com/lasote/remove_this

**Comment by Manu343726** [comment] 2018-06-25 06:19
No, in my case the python module is packaged into a conan python package, and required by the recipe.

**Comment by memsharded** [comment] 2018-06-25 16:49
Hi @Manu343726 

We still cannot reproduce. Is it a package in PyPI? Could we use it? Could you please define accurate reproducible steps to see this issue? Many thanks

**Comment by memsharded** [comment] 2018-08-31 20:40
This would be resolved by the new ``python_requires()`` feature: https://docs.conan.io/en/latest/mastering/python_requires.html

Please try it and report if necessary. Thanks!

**Closed by memsharded** 2018-08-31 20:40 UTC
