### ISSUE TITLE
Support for per-package-settings with requires

### ISSUE THREAD

**Issue by dewhisna** [conan-io/conan#3000] opened 2018-06-05 23:12 UTC
We have a package that does not include build_type in its package_id, because it uses ActiveX which is a cross-language ABI making release/debug/etc not matter for the consumer.  However, the implementation is using dependencies like zlib, libxml2, etc, that do.  This package always wants Release builds of these requirements, even if the consumer is being built for RelWithDebInfo, Debug, etc.

It's possible to specify these setting specifics when calling `conan install` on the command line, using something like: `-s build_type=RelWithDebInfo -s zlib:build_type=Release`.  This can also be done with the `[settings]` in a profile.  Similar things can be done for options by having `default_options` in the `conanfile.py`, such as `default_options="zlib:shared=True"`.

But, I can't figure out how to have our library's package `conanfile.py` set the default settings for its requirements without the consumer needing to know about the entire dependency graph and provide it on the install line, etc.

Am I missing something or is this a new feature request?

**Comment by memsharded** [comment] 2018-06-05 23:30
I think that if you want to install the Release dependencies, then the command you are looking for is ``conan install -s build_type=Release``. 

There is no way to specify the dependencies settings, and we think it is better not to do it, it is an antipattern that easily produces problems, like incompatibilities and conflicts. Explicitly specifying things in a profile is the best way to go.

What would be the use case of the consumers of that package? You want to consume such package with RelWithDebInfo, never Release? If your zlib, libxml2 dependencies will never be Debug or anything different, why not just removing their ``build_type``?

**Comment by dewhisna** [comment] 2018-06-06 03:21
Well, to answer the last question first, some consumers of the zlib, libxml2, etc, dependencies will care about their `build_type`.  These same packages are linked with other consumers in either the same or sibling projects, for example building a minizip package, which isn't an ActiveX component, but also consuming the same set of zlib packages from the same repository, would care about the `build_type` for the zlib it requires.  So just removing that property from those package ids in our repository in general would be a wrong choice.

The problem is when there's a consumer that's linking the ActiveX package and that ActiveX package in turn requires a package like zlib, libxml2, etc., as a secondary dependency.  The main consumer application knows it needs the ActiveX based package, but doesn't necessarily know all of the additional dependencies that the ActiveX based package needs.  The ActiveX package itself doesn't include `build_type` in its package id, since it doesn't matter for its consumers since it's an ActiveX-based package, but it specifies the zlib, libxml2, etc, packages as `requires` because they will be required dependencies that need to be brought into the build tree.

The problem is that the `build_type` of the outer consuming application gets passed all the way down to the zlib, etc, includes, which is fine if the outer application happens to be Release, but if it's Debug or even RelWithDebInfo, it forces the zlib, libxml2, etc, packages being consumed by the intermediate ActiveX-based package to have to be of the same `build_type` as the outer consumer.  Ideally, the ActiveX based package should be able to say that the things it requires should be of a certain `build_type`, like Release, at least by default.  But, there's no way for it to do that.

Now the outer application could specify settings for every dependency and their subdependencies, etc, during its install operation with something like the `conan install -s build_type=RelWithDebInfo -s zlib:build_type=Release` I mentioned in my first post, but then it would have to know the entire hierarchy of every single dependency and every one of their dependencies and every one of their dependencies, on down the line.

What makes this case somewhat special is how an ActiveX component is loaded and used.  It isn't linked as a typical shared library.  Instead, its data gets marshalled across threads and such, and so its `build_type` need not match that of the outer consuming application.  Plus it's very likely that these component packages may be built from third-party source for which only a Release variant even exists.  And so anything they depend on should be of their Release `build_type`, not the outer consuming application's `build_type`.

And where it gets even more tricky, and this might be what you are eluding to in your reference to incompatibilities and conflicts, is when the outer consuming package also needs a package that's a dependency of this subpackage.  In other words, the ActiveX-based package requires zlib and so does the outer consuming application and so does the minizip package the outer application is also including.  Who wins?  Maybe just letting the outer application's cmake build files sort it all out is the best answer?  I don't know.

**Comment by memsharded** [comment] 2018-06-06 07:58
Hi @dewhisna 

Thanks for the detailed feedback. Now I understand your use case. Still, it is not clear how a recipe would be defining upstream dependencies settings without causing more new issues and problems that solving things.

Lets keep this open, looking for other users feedback and thinking about this. In the meantime I'd suggest the following workarounds:

- Use profiles. Using profiles is the strongly recommended approach anyways, so identifying the ActiveX dependencies dependencies and specifying them as ``zlib:build_type=Release``, etc in the profile is a couple of minutes effort, it works very well without problems, and allows any future configuration and change very easily.

- Isolate the ActiveX package. Make it ``build_require`` zlib and the other dependencies, build the package with ``build_type=Release`` as the first step. Then you can depend on the ActiveX package, and its transitive dependencies won't be pulled at all.

- Build RelWithDebInfo packages for zlib and other transitive dependencies.

- Make the zlib and transitive dependencies to have a single package for both Release and RelWithDebInfo, but respecting the Debug one (assuming that when sometimes you want other configuration of those transitive dependencies, you want the Debug). You can do it with the ``package_id()`` method in the recipes of those dependencies (and make sure the creation of the package is done with build_type=Release:
```python
# in zlib recipe
def package_id(self):
     if self.settings.build_type == "RelWithDebInfo":
          self.info.settings.build_type = "Release"
```

**Comment by Johnnyxy** [comment] 2018-07-17 14:12
Hi there,
I have a similar case.

Situation
--------------------------
I have a prebuilt third-party library, let's call it "pre-lib".
Pre-lib comes in debug and release variants for a limited set of architectures and compilers.
I have created a recipe that provides me the appropriate pre-lib files as packages depending on the given settings.

Following that I link against those pre-lib files with my software. My software has a recipe too.
Everything works fine as long as I use Release and Debug "build_type" on my software's recipe.

But when I try to build my piece of software with RelWithDebInfo then I have the problem that I have to choose "debug" or "release" build_type of pre-lib. For that I have put the following line into my software recipe:
``` python
def configure(self):
    if (str(build_type) == "RelWithDebInfo"):            
        self.settings["pre-lib"].build_type = "Release"
```
Now I get an exception from python that the Settings object is not subscritable.
This way is convenient and only needs the recipe because only the recipe knows what to do.

Profile way
--------------------------
As you (@memsharded) suggested (https://github.com/conan-io/conan/issues/3000#issuecomment-394977612) I tested the same thing with a profile.
``` ini
[settings]
os=Windows
os_build=Windows
arch=x86_64
arch_build=x86_64
compiler=Visual Studio
compiler.version=14
build_type=RelWithDebInfo
pre-lib:build_type=Release
```

Now it works and compiles. But it is slightly redundant.
First: I have to provide a profile file. How to distribute a profile file with the recipe?
Second: Now I have to write my dependencies in the recipe and in the profile if I have to dynamically decide about dependencies. The profile way does not allow dynamic decisions like the function 
``` python
def build_requirements(self):
```
allows me to do.


Idea
--------------------------
As I understand it is easier to read a static profile file or static members of recipe classes and that is propably why Conan is implemented that way. But as always with static descriptions (like Attributes in .Net, Java, etc.) one cannot change/define them dynamically in a corner case.
If that is the case then I would propose some kind of "dependency description" object for the build_requirements function, so that a recipe can dynamically decide what it needs. This object can be read out afterwards to build the dependency tree. This would not break the current code relying on "settings" to be not changable.



Best regards

**Comment by HunterZ** [comment] 2019-06-06 19:40
My project depends on Boost. The person who provides Boost packages in our Artifactory has two builds of Boost under the exact same Conan package release ("boost-1.68.0/0.2.0@some.server/production"), with the only difference being that one variant has "self.settings.compiler.libcxx=libstdc++11" and the other has "self.settings.compiler.libcxx=libstdc++". I *need* to use the latter in order for my code to compile successfully, but I have no idea how to tell Conan about this.

I do ****NOT**** want to force the libcxx option into my own project, because it's bad enough that the Boost package has it.

**Comment by memsharded** [comment] 2019-06-06 22:08
> First: I have to provide a profile file. How to distribute a profile file with the recipe?

Profiles are not distributed with the recipe, that is the point. You can have multiple profiles for the same recipe, and every profile is typically used also for many recipes. Profiles are distributed with ``conan config install``.

Trying to hardcode settings like you are trying with ``self.settings["pre-lib"].build_type = "Release"`` is not possible right now. But I would say it is not a recommended approach. First you completely lose the capability of using the whole dependency graph to be of type ``RelWithDebInfo``, and if you need ``pre-lib`` at some point to be that type to have the Debug info for something, you won't be able, because it is hardcoded in the consumer. Also, it introduces a new range of conflicts, now not only versions and package options can conflict, but also settings, as they can be given different values in downstream nodes of a diamond graph. 

Even if expressing it in the profile might seem a bit redundant it is not. Not specifying it is the default behavior (the whole graph in ``RelWithDebInfo`` mode), and that is a good thing. It is the end consumer, the project that decides that wants to use ``pre-lib`` in Release mode, there is nothing intrinsic to the consumer library to require to link only with the ``Release`` version of its dependency. That is a particular configuration of a particular build of that graph. I really think that a small redundancy in the profile is much better and nicely explicit and configurable, than enabling that possibility in recipes that opens the door to a new range of problems (been there with options), development and maintenance problems due to increased complexity.

It is just my opinion, maybe it is worth to discuss with the team too.

Many thanks!

**Comment by puetzk** [comment] 2019-06-07 03:46
Well, we (I work with @dewhisna) still have a lot of cases of needing mixed settings. We understood your concerns and have implemented your suggestion from last June; many of our consumer packages now have a conanprofile.txt file sitting next to the conanfile.txt, and it's often the case that the recipe more or less requires you use it.

The most common driver is that we build everything we can with build_type=RelWithDebInfo to enable with profiling and interpreting crash dumps, but when we use an existing recipe (particularly one with a non-CMake build system), many don't implement RelWithDebInfo, and so have to be overridden to just use the Release build since it's what can be available.

The root cause here is really inadequate recipes in conan-center, though: it's quite possible for an msbuild recipe to implement RelWithDebInfo with something like the following:

```python
if self.settings.build_type == 'RelWithDebInfo':
     msbuild.build_env.cxx_flags += ['/Zi']
     msbuild.build_env.link_flags += ['/OPT:ref', '/DEBUG']
     msbuild.build("foo.sln", build_type = 'Release')
```

It's just that few recipes do, even bincrafters packages that are otherwise pretty thorough. Maybe the solution **is** just to go to the each such package and make a feature request for code like the above, though.

Or (just thinking about duplication) maybe it would make sense to add capability in the MSBuild helper analagious to the the `platforms={...}` kwarg that translates x86->Win32, for mapping build_type into supplemental flags. Maybe this new map could even have defaults to implement all the build_type values in conan's default settings.yml against with a the "Release" and "Debug" configurations of a default visual studio solution?

---

A secondary case for needing to override settings is packages which are being required in as build_requires, or in requires that won't be linked to, but will have files copied by an `[import]` to repackage for use at runtime. We have cases where such utilities might be built with a different compiler (e.g. mingw vs msvc, or compiler.libcxx) or even a different os (since we have a few cases of winelib libraries whose build or tests want to make use of a windows utility, which the build system can in fact run via wine).

Using a profile for these to choose the alternate settings for something like this does seem reasonable; the biggest shortcoming is that it requires the top-level consumer's profile to also individually hardcode settings for each sub-requirement, since `foo:setting=value` doesn't have any effect on additional recipes introduced by requirements in foo (that the top-level project would have no other reason to know exist).

My preference here would be that profile settings with no scope (-s foo=bar) are applied to the top-level, nodes mentioned with a scope (-s node:foo=baz) get that value, and everything else gets the value from the parent(s) which required them (which must all agree; mismatches in a diamond tree where there are multiple parents who do not agree on the value are fatal errors which must be fixed by explicitly listing conflicted node in the profile). Which is, I'm sure, your concern that "it introduces a new range of conflicts".

The conflicts really exist either way, but today they're not diagnosed, just silently resolved by choosing the top-level (non-scoped value), and you find (or not) the new node that needs to be listed in the profile when the mismatched binaries malfunction.

**Comment by zabereer** [comment] 2020-12-14 12:54
I have a similar issue but with `build_requires` - I always want to use build_type=Release for the tools needed to build my package. So any way to force the `build_type` of dependencies (build or otherwise) would be highly appreciated. I hope I am not missing a trick somewhere.

**Comment by Johnnyxy** [comment] 2020-12-14 13:09
Hi @zabereer 
you can override the ```build_type``` of dependencies via command line or via profile.

Command Line
----------------
```
conan install ... -s my_dependency_1:build_type=Release -s my_dependency_2:build_type=RelWithDebInfo
```

Profile
------
```
[settings]
...
my_dependency_1:build_type=Release
my_dependency_2:build_type=RelWithDebInfo
...

[options]
...
```

**Comment by zabereer** [comment] 2020-12-14 14:00
@Johnnyxy THANK YOU! I did not realise!

**Comment by n00b42** [comment] 2021-10-14 08:51
We have a package that is used by some others in our project and that depends on some external packages (e.g. fmt ..).
While we want to offer a Debug build of our package to our colleagues, we do not want to use Debug builds of the dependencies.

- In our environment, we can be quite sure that no one needs Debug builds of the dependencies.
- Debug builds of the dependencies would need to be build as well, as they are not available for our target architectures
- More Debug builds bloat our target, i.e. even though it is "for debugging" does not mean we have more space available.

Therefore, I think it is a justified usecase to have our own libs as Debug builds but not their dependencies.
While this can be achieved "manually" as dexcribed before, this would push the burden on the user of the library, that in the optimal case does not even know about the required (transitive) dependency and only "wants to use" our library.

**Comment by Johnnyxy** [comment] 2021-10-14 10:20
@n00b42 
It is generally not advisable to mix build_types. But one can do this in certain scenarios where you definitely know that there is no different API / ABI or behaviour between the build_types.

But you can do this only at invocation time. As Conan calculates the dependency graph with the given settings which are hardcoded at Conan runtime.

### Profile
Via Profile.
```
[settings]
...
DEPENDENCY_NAME:build_type=Release
...
```
This leads to the commandline: ```conan install ... -pr PROFILE_FILENAME ...```

### Commandline
As specific parameters.
```
conan install ... -s DEPENDENCY_NAME_0:build_type=Release -s DEPENDENCY_NAME_1:build_type=Release ...
```

### Hacky
There is another scenario. If you are hiding the dependencies because they are static and your users do not need the dependencies then it is possible to pre-build your library binary. All pre-built binaries of your lib are ```requiring``` the dependencies with the ```private``` parameter ([see docs here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#requirements)). This is definitely not recommended. As the Conan devs already stated in the docs and on several occations here in the issue tracker.

Another way to hide dependencies (at the moment) is to ```build_requiring``` them ([see docs here](https://docs.conan.io/en/latest/reference/conanfile/methods.html#build-requirements)). This is also not recommended as it could or will be changed in the future.

These two approaches remove the dependencies from the dependency graph (maybe not literally) when users are requiring your lib in which way the users only see your prebuilt library and do not have to provide any other settings/options for dependencies.

**Comment by KristianJerpetjon** [comment] 2022-01-05 10:51
I agree that this feature would be nice to have especially in embedded systems where the whole binary in debug might be to large for the overall memory

**Comment by AlexanderRevo** [comment] 2022-09-01 11:55
Just wanna say that this is very nice to have for cross-compilation.

We're slowly transitioning to having tools like CMake in our `build_requires` because it simplifies the builder/CI runner setup. Especially on Windows runners, it's much easier to use the CMake conan package to make sure you get the required CMake version on whatever runs your pipelines, as opposed to manually updating it on a fleet of runners (or even updating the docker images). Basically, this allows us to only have to setup python and a compiler on a pipeline runner/docker image, and then we can get conan via requirements.txt and all the other tools and libraries via conanfile.py.

In the above scenario we want CMake and other tools configuration to match the builder environment (in our case, a Release build for Windows), and the rest of build-only requirements (like testing frameworks) should match the target platform.

We're currently using profiles for this (like in https://github.com/conan-io/conan/issues/3000#issuecomment-744428546), but it could also be useful to be able to set it up in the conanfile itself.

**Comment by memsharded** [comment] 2023-10-08 00:32
Hi all,

I am going to close this ticket at the moment as defining dependencies settings in recipes will not be implemented.
We have learned the lessons of doing this with ``options``, and it has been really painful. Conflicts, unexpected behaviors confusing users, lots of support tickets, etc. We are not going to do the same errors with settings.

Some of the above cases can be relatively easily do with profiles and command line, like defining dependencies in release, while the current project is debug, can be done with ``-s build_type=Release -s &:build_type=Debug``. Also profiles have gain more power, like now in 2.0 they are jinja profiles by default, there is a new ``profile.py`` plugin, etc. Using profiles is the recommended approach for specifying different settings for different packages if necessary. Thanks all for the feedback!

**Closed by memsharded** 2023-10-08 00:32 UTC
Labels: type: look into
