### ISSUE TITLE
[bug] source_folder is re-used even when settings differ

### ISSUE THREAD

**Issue by smoofra** [conan-io/conan#10986] opened 2022-04-06 16:52 UTC
The [documentation](https://docs.conan.io/en/1.47/reference/commands/development/source.html) says that a conanfile's source method can use settings: 

> The `source()` method might use (optional) settings, options and environment variables from the specified profile and 
> dependencies information from the declared `deps_XXX_info` objects in the conanfile requirements.

But when you build the same package with different settings, conan re-uses the source folder, which will cause the wrong sources to be used if source contents do depend on settings.

### Environment Details 
  * Operating System+version: Mac OS 12.3.1 
  * Conan version: 1.47.0
  * Python version: 3.9.12

#### `lol/conanfile.py`
```
import os
from conans import ConanFile, tools
from typing import *

class LolConan(ConanFile):
    
    name = "lol"
    version = "1.0"
    settings: Any = "os"

    @property
    def src_filename(self):
        return os.path.join(self.source_folder, str(self.settings.os))

    def source(self):
        self.run(f"touch {self.src_filename}")

    def build(self):
        assert os.path.exists(self.src_filename)
```

```
$ conan create  lol -s os=Linux   # this works

$ conan create  lol -s os=Windows # this fails with AssertionError

$ conan remove lol  -s -f      
$ conan create lol -s os=Windows # now it works
```

**Comment by memsharded** [comment] 2022-04-06 21:46
Hi @smoofra 

This is not a bug, this is the documentation of the ``conan source`` command being a bit outdated. If you navigate to the ``source()`` method docs (https://docs.conan.io/en/1.47/reference/conanfile/methods.html#methods) you will see:

> It is very important to recall that the source() method will be executed just once, and the source code will be shared for all the package builds. So it is not a good idea to conditionally use settings or options to make changes or patches on the source code. Maybe the only setting that makes sense is the OS self.settings.os, if not doing cross-building, for example to retrieve different sources:

And it will explicitly recommend to use the ``build()`` method for that: 

> If you need to patch the source code or build scripts differently for different variants of your packages, you can do it in the build() method, which uses a different folder and source code copy for each variant.

Please try that, thanks for reporting! 
(I am closing this as question solved, the docs are being now rewritten from scratch for Conan 2.0, so this will be hopefully improved there)

**Closed as completed by memsharded** 2022-04-06 21:46 UTC
Labels: type: question

**Comment by smoofra** [comment] 2022-04-06 21:52
ok, thanks.
