### ISSUE TITLE
[bug] conan remove outdated failed

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan#10169] opened 2021-12-13 14:04 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: Windows 10
  * Compiler+version: Visual Studio
  * Conan version: 1.43.0

### Steps to reproduce (Include if Applicable)
 conan remove "*" -o -f

### Logs (Executed commands with output) (Include/Attach if Applicable)

WARN: No matching packages to remove for automake/1.16.2
WARN: No matching packages to remove for backward-cpp/1.5
WARN: No matching packages to remove for backward-cpp/1.6
WARN: No matching packages to remove for brotli/1.0.9
WARN: No matching packages to remove for bzip2/1.0.8
WARN: No matching packages to remove for ceres-solver/2.0.0
WARN: No matching packages to remove for cmake/3.20.2
WARN: No matching packages to remove for cmake/3.20.4
WARN: No matching packages to remove for cmake/3.21.3
WARN: No matching packages to remove for coin-lemon/1.3.1
WARN: No matching packages to remove for core_builder_windows_image/v2.0.5-3-ga3a92e1cb@gitlab/testing
WARN: No matching packages to remove for core_builder_windows_image/v2.0.6-1-g3fa21d705@gitlab/release
WARN: No matching packages to remove for core_builder_windows_image/v2.0.6-2-gccbf28f7c@gitlab/testing
WARN: No matching packages to remove for core_builder_windows_image/v2.0.7@gitlab/release
WARN: No matching packages to remove for core_builder_windows_image/v2.0.8@gitlab/release
WARN: No matching packages to remove for core_builder_windows_image/v2.0.8-2-g85f4976a3@gitlab/testing
ERROR :search.py      [151]: There is no ConanInfo: D:\.conan\cfc0e1\1\conaninfo.txt [2021-12-13 14:56:27,845]
WARN: No matching packages to remove for diligent-core/ca661f5@gitlab/release
WARN: No matching packages to remove for diligent-core/2.5.1@andrei/test
WARN: No matching packages to remove for diligent-engine/d72a87fa@gitlab/release
WARN: No matching packages to remove for dirent/1.23.2
WARN: No matching packages to remove for draco/1.3.6
WARN: No matching packages to remove for draco/1.4.3
WARN: No matching packages to remove for easyexif/1.0
WARN: No matching packages to remove for eigen/3.3.8
WARN: No matching packages to remove for eigen/3.3.9
WARN: No matching packages to remove for embree3/3.12.0
WARN: No matching packages to remove for expat/2.4.1
WARN: No matching packages to remove for freetype/2.10.4
WARN: No matching packages to remove for freetype/2.11.0
WARN: No matching packages to remove for gflags/2.2.2
WARN: No matching packages to remove for glew/2.1.0
WARN: No matching packages to remove for glew/2.2.0
WARN: No matching packages to remove for glib/2.68.1
WARN: No matching packages to remove for glib/2.68.3
ERROR :search.py      [151]: There is no ConanInfo: D:\.conan\23f3a8\1\conaninfo.txt [2021-12-13 14:56:52,182]
WARN: No matching packages to remove for glib/2.69.1
WARN: No matching packages to remove for glib/2.69.2
ERROR :search.py      [151]: There is no ConanInfo: D:\.conan\8fddad\1\conaninfo.txt [2021-12-13 14:56:54,231]
WARN: No matching packages to remove for glib/2.70.0
WARN: No matching packages to remove for glib/2.70.1
WARN: No matching packages to remove for glm/0.9.9.8
WARN: No matching packages to remove for glog/0.4.0
WARN: No matching packages to remove for glslang/8.13.3559
Traceback (most recent call last):
  File "conans\client\command.py", line 2232, in run
  File "conans\client\command.py", line 1199, in remove
  File "conans\client\conan_api.py", line 93, in wrapper
  File "conans\client\conan_api.py", line 884, in remove
  File "conans\client\remover.py", line 201, in remove
  File "conans\paths\package_layouts\package_cache_layout.py", line 187, in recipe_manifest
  File "conans\model\manifest.py", line 91, in load
  File "conans\util\files.py", line 232, in load
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\.conan\\data\\glslang\\11.7.0\\_\\_\\export\\conanmanifest.txt'

ERROR: [Errno 2] No such file or directory: 'D:\\.conan\\data\\glslang\\11.7.0\\_\\_\\export\\conanmanifest.txt'

**Comment by memsharded** [comment] 2021-12-13 17:13
Hi @AndreyMlashkin 

This is difficult to reproduce, this is not failing on my side, and I don't see how to reproduce it. It would seem there are a couple of your packages that are corrupted or something on your side, with missing files like the manifest or the conaninfo.txt (maybe as a result of an interrupted/killed process or crash?)

If you have any suggestion of how we could reproduce it, that would be helpful, thanks.

**Comment by AndreyMlashkin** [comment] 2021-12-14 08:46
Yes, most probably I have stopped a remove command some time ago.
Have you tried removing a manifest manually?

**Comment by memsharded** [comment] 2021-12-14 09:38
Yes, sure, removing a manifest manually will cause this behavior. It is by design, packages should have a manifest, if they don't they are corrupted, it is expected that it will not be possible to install them, or manage them with normal Conan commands. There are protection mechanisms like marking things like ``.dirty`` in the cache to protect against broken things, but if the manifest is removed manually, bypassing the .dirty mechanism, things will fail.

**Comment by AndreyMlashkin** [comment] 2021-12-14 09:50
Maybe delete procedure should be changed and manifest should be deleted the last?

**Comment by memsharded** [comment] 2021-12-14 10:30
Deletion in the local cache is with ``rmdir``, it would be too much to do it at the file level, and in any case ``rmdir`` should work fast enough to greatly reduce this.

**Comment by AndreyMlashkin** [comment] 2021-12-14 12:40
it would be better, if while calling
'conan remove "*" -o'  -f, 
invalid packages are also deleted, as well as outdated, no need to throw an exception

**Comment by memsharded** [comment] 2021-12-14 21:21
In any case, I'd like to highlight that the ``--outdated`` thing no longer makes sense with revisions enabled, as using revisions it is not possible to have outdated binaries from recipes. The ``--outdated`` has then already been removed from Conan 2.0 (alpha2 released today).

**Comment by AbrilRBS** [comment] 2024-04-23 08:53
Closing now that Conan 2 has been going for a while and the recommendation has been to run Conan 1 with revisions for a long while now

**Closed as not planned by AbrilRBS** 2024-04-23 08:53 UTC
Labels: stage: triaging
