### ISSUE TITLE
[bug] XCode 12 completely broken

### ISSUE THREAD

**Issue by Yuri6037** [conan-io/conan#8022] opened 2020-11-06 18:25 UTC
### Environment Details (include every applicable attribute)
  * Operating System+version: GitHub Actions OSX
  * Compiler+version: XCode 12
  * Conan version: 1.31.0
  * Python version: 3.9.0

### Steps to reproduce (Include if Applicable)
Using conan to download and build a static version of ZLib under OSX XCode 12 running from GitHub Actions CI.

### Logs (Executed commands with output) (Include/Attach if Applicable)

```
-- Conan: Using cmake-multi generator
-- Conan: Automatic detection of conan settings from cmake
In file included from <stdin>:1:
In file included from /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:504:
In file included from /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string_view:175:
In file included from /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:57:
In file included from /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:641:
In file included from /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstring:60:
/Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string.h:60:15: fatal error: 'string.h' file not found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
-- Conan: Settings= -s;build_type=Release;-s;compiler=apple-clang;-s;compiler.version=12.0;-s;compiler.libcxx=libc++
-- Conan: checking conan executable
-- Conan: Found program /Users/runner/hostedtoolcache/Python/3.9.0/x64/bin/conan
-- Conan: Version found Conan version 1.31.0

-- Conan executing: /Users/runner/hostedtoolcache/Python/3.9.0/x64/bin/conan install . -s build_type=Release -s compiler=apple-clang -s compiler.version=12.0 -s compiler.libcxx=libc++ -g=cmake_multi --build=missing
Auto detecting your dev setup to initialize the default profile (/Users/runner/.conan/profiles/default)
CC and CXX: /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc, /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
Default settings
	os=Macos
ERROR: Not able to automatically detect '/Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' version
ERROR: Unable to find a working compiler
	os_build=Macos
	arch=x86_64
	arch_build=x86_64
	build_type=Release
*** You can change them in /Users/runner/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /Users/runner/.conan/remotes.json
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

zlib/1.2.11@conan/stable: Not found in local cache, looking in remotes...
zlib/1.2.11@conan/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.11@conan/stable: Downloaded recipe revision 0
conanfile.txt: Installing package
Requirements
    zlib/1.2.11@conan/stable from 'conan-center' - Downloaded
Packages
    zlib/1.2.11@conan/stable:647afeb69d3b0a2d3d316e80b24d38c714cc6900 - Build

Installing (downloading, building) binaries...
Downloading conan_sources.tgz
zlib/1.2.11@conan/stable: Configuring sources in /Users/runner/.conan/data/zlib/1.2.11/conan/stable/source

zlib/1.2.11@conan/stable: Copying sources to build folder
zlib/1.2.11@conan/stable: Building your package in /Users/runner/.conan/data/zlib/1.2.11/conan/stable/build/647afeb69d3b0a2d3d316e80b24d38c714cc6900
zlib/1.2.11@conan/stable: Generator cmake created conanbuildinfo.cmake
zlib/1.2.11@conan/stable: Calling build()
zlib/1.2.11@conan/stable: Calling:
 > ../configure '--prefix=/Users/runner/.conan/data/zlib/1.2.11/conan/stable/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
Checking for shared library support...
Building shared library libz.1.2.11.dylib with /Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc.
Checking for size_t... No.
Checking for long long... Yes.
Failed to find a pointer-size integer type.
** ../configure aborting.
zlib/1.2.11@conan/stable: ERROR: Package '647afeb69d3b0a2d3d316e80b24d38c714cc6900' build failed
zlib/1.2.11@conan/stable: 
zlib/1.2.11@conan/stable: WARN: Build folder /Users/runner/.conan/data/zlib/1.2.11/conan/stable/build/647afeb69d3b0a2d3d316e80b24d38c714cc6900
ERROR: zlib/1.2.11@conan/stable: Error in build() method, line 59
	self._build_zlib()
while calling '_build_zlib', line 108
	self._build_zlib_autotools()
while calling '_build_zlib_autotools', line 80
	env_build.configure("../", build=False, host=False, target=False)
	ConanException: Error 1 while executing ../configure '--prefix=/Users/runner/.conan/data/zlib/1.2.11/conan/stable/package/647afeb69d3b0a2d3d316e80b24d38c714cc6900' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' 
CMake Error at CMakes/conan.cmake:403 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  CMakes/conan.cmake:493 (conan_cmake_install)
  Compression/CMakeLists.txt:8 (conan_cmake_run)
```

**Comment by memsharded** [comment] 2020-11-06 18:51
Hi @Yuri6037 

There could be different reasons for this, we should first analyze what is happening:

- It could be that zlib simply doesn't build with XCode12, unless without some patching. This might require improving the zlib recipe in conan-center-index. Something like: https://github.com/conan-io/conan-center-index/issues/3008
- Then there is something failing with the auto-detection of the compiler version, and this is happening: `` Not able to automatically detect '/Applications/Xcode_12.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' version``. As you are using cmake-conan and apparently providing the compiler.version=12, this doesn't seem an issue, and the correct profile is being used. Still, we would like to understand what is failing there, might be something we need to fix.

I would try to do:

```
conan install zlib/1.2.11@ -r=conan-center --build -s compiler=apple-clang -s compiler.version=12 -s compiler.libcxx=libc++
```
without running it from cmake-conan, just to rule out there is some interaction there causing a problem.

Then, a nice thing would be to create a simple hello package, something like:
```
conan new hello/0.1 -s -t
conan create .  -s compiler=apple-clang -s compiler.version=12 -s compiler.libcxx=libc++
```
To see if this works for a simple use case. If this works, but the previous zlib build failed, the best would be to move this issue to conan-center-index repo to check the recipe there.

Please @uilianries @SSE4 have a look when possible.

**Comment by Yuri6037** [comment] 2020-11-06 21:09
Unfortunatly I do not have a Mac with XCode 12 on me. I only have GitHub Actions CI which does not have interactive SSH.
EDIT: I just found https://github.com/mxschmitt/action-tmate. I will try to see if I can run this action on my GitHub free plan.

**Comment by SSE4** [comment] 2020-11-11 18:33
I will update Xcode tomorrow to 12.1 and let you know. it's 11.3 Gb, I am on slow internet right now.

**Comment by SSE4** [comment] 2020-11-12 13:00
for me works with Xcode 12.1 locally. seems to be some misconfiguration on GitHub actions?

**Comment by SSE4** [comment] 2020-11-12 13:08
there are quite a few similar issues:
https://discourse.brew.sh/t/solved-scan-build-from-llvm-7-0-seems-broken-on-macos-mojave/3151/12
https://github.com/pocoproject/poco/issues/2107
https://donatstudios.com/MojaveMissingHeaderFiles

the solved by running:
```
$ xcode-select --install
$ open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

not sure, probably GitHub Actions should also install headers components?

**Comment by Yuri6037** [comment] 2020-11-12 13:10
If that is the problem why did it used to work before XCode 12?

This is not the first time I have issues with Conan. I had many issues with Conan in the past including issues with certain customers who are reluctant at install Python on their computers.
Due to all the integration problems there are in Conan with CMake, these package compilation issues and other problems, I have decided to replace Conan with a custom package manager written in Rust to address all these issues (https://github.com/BlockProject3D/fpkg).

If you need any further information please ask me or check the complete build log: https://github.com/BlockProject3D/Framework/actions/runs/349978767

**Comment by horusxnetworks** [comment] 2020-11-26 11:05
This issue can be resolved by force Conan to create default profile:
`conan profile new default --detect --force`

**Comment by Yuri6037** [comment] 2020-11-26 11:16
> This issue can be resolved by force Conan to create default profile:
> `conan profile new default --detect --force`

This is the kind of reason I started my own package manager: it is unacceptable that the user must type an additional command before installing packages. There should a single command (like npm install) which resolves all packages and has little chance of failure! This is what I call simplicity!

**Comment by SSE4** [comment] 2020-12-25 14:14
the issue was most likely the same as #8113, and #8118 should fix that particular case
I am going to set up simple GitHub actions project to reproduce and test the fix
update: zlib builds just fine: https://github.com/SSE4/ghactions_test/runs/1608826504?check_suite_focus=true

**Closed as completed** 2021-01-13 19:28 UTC
Labels: type: bug
