### ISSUE TITLE
[develop2][bug] CMakeToolchain preprocessor_definitions type lost

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#11998] opened 2022-08-31 21:51 UTC
```python
class gameRecipe(ConanFile):
    name = "game"
    version = "1.1.2.3"
    package_type = "application"

    requires = "engine/[>=1.0 <2]"

    # Binary configuration
    settings = "os", "compiler", "build_type", "arch"

    # Sources are located in the same place as this recipe, copy them to the recipe
    exports_sources = "CMakeLists.txt", "src/*"

    def generate(self):
        tc = CMakeToolchain(self)
        tc.preprocessor_definitions["PKG_VERSION"] = str(self.version)
        tc.generate()
        deps = CMakeDeps(self)
        deps.generate()
```
and
```cpp
#include <iostream>
#include "game.h"
#include "engine.h"

void game(){
    engine();
    #ifdef NDEBUG
    std::cout << "game/" << PKG_VERSION << ":fun game (Release)!\n";
    #else
    std::cout << "game/" << PKG_VERSION << ":fun game (Debug)!\n";
    #endif
}
```
Will end in error, because PKG_VRRSION is not a float. If version is 1.0, it will be rounded to 1, and if 1.1 it will be rendered correctly (as float), in the toolchain is generated as:
```cmake
# Preprocessor definitions
add_compile_definitions("PKG_VERSION=1.1.2.3")
```
I think the value should be quoted.

**Comment by lasote** [comment] 2022-09-08 08:09
After fighting with CMake I think this is the expected behavior, I'll try to explain it.
C/C++ `#defines` are just literal "strings" for substitutions, if you try to print the `PKG_VERSION` that way, the preprocessor will replace it with just `1.1.2.3` and that is of course nothing valid in `C++` syntax.
So if you manage to quote the values when they are strings in python, the literal string will contain the quotes, that will work for your print but only circumstantially because it might happen that a user doesn't expect the values to be quoted.

In these cases, people use macros to "stringify" the values, let's see an example and check if I can convince you.

```cpp
// main.cpp
#include <iostream>

// These are commonly used, you can search for them
#define xstr(s) str(s)
#define str(s) #s //

#define FOO 1.2.3
#define BAR "1.2.3"
#define OTHER ""1.2.3
#define NUMBER 23.1

int main() {
    // This will fail because 1.2.3 is not a number and either a string and not a valid identifier etc...
    //std::cout << FOO << std::endl;

    // This works and prints 1.2.3 as a string
    std::cout << xstr(FOO) << std::endl;

    // This works and makes your point, why I cannot avoid ugly macros to print a string if Conan knows it is a string?
    std::cout << BAR << std::endl;

    // On the other hand, this will output "1.2.3" with quotes, and maybe that is unexpected for a user, 1.2.3 is 1.2.3 not "1.2.3"
    std::cout << xstr(BAR) << std::endl;

    // This fails also because that string is nothing in C++ syntax
    //std::cout << OTHER << std::endl;

    // But we can of course stringify, take into account here that a define with ""1.2.3 is perfectly valid and literal.
    std::cout << xstr(OTHER) << std::endl;

    // NUMBER is a valid number so we can use it
    std::cout << NUMBER + 1  << std::endl;
} 

```

Output:

```text
1.2.3
1.2.3
"1.2.3"
""1.2.3
24.1

```

**Comment by czoido** [comment] 2022-09-09 10:30
Closing as this is solved and opening an issue in the docs in case we can clarify how the preprocessor_definitions in the recipes translate to the generators.

**Closed as completed by czoido** 2022-09-09 10:30 UTC
