### ISSUE TITLE
How to avoid rebuilding current package when not needed

### ISSUE THREAD

**Issue by gsemet** [conan-io/conan#14093] opened 2023-06-15 11:24 UTC
### What is your question?

Hello, 

Sorry for the stupid question if it is, but is there a way in conan to avoid rebuilding the current package if there is already a version of the repository that would that matches exactly the same result.

It is possible to do so for dependencies, obviously, but for the current package? The building of some of my package is quite time consumming, and if the result package would have exactly the same content as a package already published on artifactory, I would like to find a way to avoid a costly rebuild and replace by a conan install

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-06-15 11:39
Hi @gsemet 

Thanks for your question.

I think the ``conan create . --build=missing`` does exactly that. It will not force the build from source if it can find a valid existing binary. Is this what you are looking for?

**Comment by gsemet** [comment] 2023-06-15 11:44
I may have an issue with my recipes, it does indeed avoid recompilation of all "*requires" dependencies, but the current package is still compile (basically I have to call conan build because I do not know whether a package already exist of the current recipe). How does conan might know it?

**Comment by memsharded** [comment] 2023-06-15 11:53
> still compile (basically I have to call conan build because I do not know whether a package already exist of the current recipe). How does conan might know it?

It is not fully clear what you mean. If you have local changes, and those changes produce a different ``recipe revision``, then it will require to build new binaries. If the recipe revision that results when exporting the current recipe to the cache, exists in the server or in the cache, then the ``--build=missing`` should be able to reuse it without building from source.

So maybe the issue is that you are creating new revisions?

It is also not clear what you mean when ``I have to call conan build``. The ``conan build`` is a local command, it does an incremental build in the developer folder, so it is not a Conan package at all, so that cannot be avoided, because there is not package, it is just a developer really wanting to build it from source?

**Comment by gsemet** [comment] 2023-06-15 12:17
My use case is: I have a CI that generate the conan package. We can trigger several times the pipeline on the same git commit. In this case the built package locally is expected to be the same than the one already published on artifactory, and I would like to replace the compilation by a simple download of this existing package.

**Comment by memsharded** [comment] 2023-06-15 12:41
You cannot know directly with the default if a local build with ``conan build`` or ``conan install + cmake `` will have the same result or not of a previous compilation or not. You can definitely know it with ``conan create --build=missing``, isn't this what you are doing in CI to create the packages? The local flow with ``conan build`` is mostly intended for developers, but not necessarily for CI package creation.

That assumes that the default ``recipe revision`` is the hash of the contents of the recipe. That is a good default, for example, if you change just the README of the repo, even if the commit changes, the Conan recipe revision will still be exactly the same, and it knows how to skip the build with ``conan create --build=missing``. 

If you change the default and use ``revision_mode = "scm"`` instead, which means taking the commit of the repo as the recipe revision, then you could do a ``conan install --requires=mypkg/myversion#mycommit``, to try to install it (or ``conan graph info`` to query for it without really installing).

**Comment by gsemet** [comment] 2023-06-15 13:13
Indeed, we use conan install + conan build + conan export, and so if in the CI we replace by `conan create --build=missing` it may work. But using revision_mode=scm is not applicable, because there are cases where we no local files changes on the same commit, but cases where some files MAY change (pre-merge engineering build) and in this case we want to rebuild anyway.

So from what I understand, if the revision_id is set to derivate from the local source files + depedencies + profile and so on, then `conan create --build=missing` would skip rebuild like I am looking for. Thanks for this answer, we'll try it !

**Comment by memsharded** [comment] 2023-06-15 13:25
> So from what I understand, if the revision_id is set to derivate from the local source files + depedencies + profile and so on, then conan create --build=missing would skip rebuild like I am looking for. Thanks for this answer, we'll try it !

Yes, exactly. 
Furthermore, for CI pipelines that you want to guarantee that only that package is built if missing, but transitive dependencies binaries must exist (a good default for CI) otherwise it should error, in Conan 2, there is the new ``--build=missing:<pkgpattern>`` that allows to build those packages or package that matches the pattern, so ``--build=missing:currentpkg/*`` would achieve that behavior too.

If the answer looks good, I am closing the issue as responded, but please re-open and comment or create a new ticket if you have any further question or feedback. Thanks!

**Comment by gsemet** [comment] 2023-06-15 13:39
thanks for your fast answer, will try it !

**Comment by lmahe** [comment] 2023-06-26 07:22
Hello,

this is a follow-up question (I work with https://github.com/gsemet)

As per your answer to our previous question, we used "conan create . --build=missing" to generate the package in question in our CI, and then uploaded it to an artifactory instance.

We tried to launch the job again. Given that the package now exist in artifactory, if we understand the previous answer correctly, we expect conan to find this package and not build it again. We even took precaution to ensure the package revision stays the same by not includeing files which content may change between builds (log with timestamps)

In both jobs we have the same ids
project/0.0.0@dev/testing: Package 'e66bdcb90c0a03873be8bc5b7a21d83ebb88baae' created
project/0.0.0@dev/testing: Created package revision 2776bbdd4e42cf1be0c4eef989969aaf

but the build step is still done. Does the "--build=missing" only works on requirements as we suspect?

**Comment by memsharded** [comment] 2023-06-26 07:30
Hi @lmahe 

No, the ``conan create . --build=missing`` is also able to skip the build of the current package being created, not only ``requires``.

Maybe the issue is that the ``recipe revision`` must be the same, not the ``package revision``? Can you please share or check the 2 jobs logs, the first part that prints the recipe revision and check that it is the same?

**Comment by lmahe** [comment] 2023-06-26 09:11
The recipe revision appears to be the same in both builds. I cannot share the whole log but I tried to extract the relevant lines:

```
Exporting package recipe
device-cm-acceptance-sysdesc/0.0.0@dev/testing exports: File 'conandata.yml' found. Exporting it...
device-cm-acceptance-sysdesc/0.0.0@dev/testing exports: Copied 1 '.yml' file: conandata.yml
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Calling export_sources()
...
device-cm-acceptance-sysdesc/0.0.0@dev/testing: A new conanfile.py version was exported
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Folder: /???/device-cm-acceptance/env/.conan/data/device-cm-acceptance-sysdesc/0.0.0/dev/testing/export
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Using the exported files summary hash as the recipe revision: 4592e9e6683a607824d66e3d458123bc 
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Exported revision: 4592e9e6683a607824d66e3d458123bc
...
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Loading requirements from 'conandata.yml'
...
Installing package: device-cm-acceptance-sysdesc/0.0.0@dev/testing
Requirements
...
Installing (downloading, building) binaries...
...
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Configuring sources in /???/device-cm-acceptance/env/.conan/data/device-cm-acceptance-sysdesc/0.0.0/dev/testing/source
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Copying sources to build folder
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Building your package in /???/device-cm-acceptance/env/.conan/data/device-cm-acceptance-sysdesc/0.0.0/dev/testing/build/e66bdcb90c0a03873be8bc5b7a21d83ebb88baae
...
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Calling build()
...
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Package 'e66bdcb90c0a03873be8bc5b7a21d83ebb88baae' created
device-cm-acceptance-sysdesc/0.0.0@dev/testing: Created package revision 2776bbdd4e42cf1be0c4eef989969aaf
```

it's the same in both builds, the build() is called. I learned that there is no shared local conan cache between our runners so the build do not rely on the package existing locally.
I would also like to know when this operation (computing the recipe id and checking if it exists remotely) is done in https://docs.conan.io/1/reference/commands/creator/create.html#methods-execution-order.
Let me know if I can provide more information and thank you for your help

**Comment by memsharded** [comment] 2023-06-26 10:23
The conditions to avoid the building should be:

- The recipe revision is the same, so this line ``device-cm-acceptance-sysdesc/0.0.0@dev/testing: Exported revision: 4592e9e6683a607824d66e3d458123bc`` should be the same revision
- The ``package_id`` is the same (same configuration, same dependencies). The "same dependencies" means that if the packages are using version ranges, or there are revisions and builds depending on the revisions (like a shared library linking a static library, or an executable linking a static library), and a new version or a new revision was uploaded to the server between the builds, then the dependencies will change, and the ``package_id`` can be different, naturally requiring a build from sources. The solution to this would be using lockfiles
- The pre-compiled binary for that ``recipe revision`` and that ``package_id`` exists in the server, and the ``remote`` in the Conan client is configured to point to that server repo.

> I learned that there is no shared local conan cache between our runners so the build do not rely on the package existing locally.
Yes, that shouldn't be an issue, if the remote server contains the binary and it is accessible it shouldn't build from sources.


I just ran a quick check, doing:
```bash
$ cd conan-center-index/recipes/zlib/all
$ conan create . 1.2.13@ --build=missing -s compiler.version=16
```
In Conan 1.X does not build from source, but download the existing binary for ``zlib/1.2.13`` from the server


If you can please double check that the above conditions hold for your 2 builds, that would help.

**Comment by lmahe** [comment] 2023-06-27 14:42
We had an issue where only the recipe where uploaded and not the packages It works now, thank you for your help!
Regards

**Comment by memsharded** [comment] 2023-06-27 17:42
Ok, thanks for telling, I am closing this ticket now as solved, but don't hesitate to create new tickets for any further question. Thanks!

**Closed as completed by memsharded** 2023-06-27 17:42 UTC
Labels: type: question
