### ISSUE TITLE
Cannot override conflicting subdependency options specified in dependencies' conanfiles

### ISSUE THREAD

**Issue by happy-monk** [conan-io/conan#5183] opened 2019-05-20 13:27 UTC
Lets suppose that we have Conan-based project depending on packages PkgA and PkgB.

PkgA and PkgB both depend on Boost and both specify options for their dependencies. For example, skip_lib_rename for Boost.

In PkgA/conanfile.py:

    def configure(self):
        self.options["boost"].skip_lib_rename = True

In PkgB/conanfile.py:

    def configure(self):
        self.options["boost"].skip_lib_rename = True

In this case Conan rightfully reports conflict:

    ERROR: boost/1.67.0@conan/stable: PkgB/1.0@test/stable tried to change boost/1.67.0@conan/stable option skip_lib_rename to False
    but it was already assigned to True by PkgA/1.0@test/stable

We then try to override this option in root conanfile as `self.options["boost"].skip_lib_rename = True`, but we still get the same error message!

The full example can be seen in the following gist: https://gist.github.com/happy-monk/351a078d7026fdca577aa0bdd4e5d09d

Tested on Conan 1.15.1

P.S. If PkgA and PkgB both declare options through `default_options`, this seem to resolve problem, but it is not always possible to enforce that. Also the issue behaves erratically: sometimes it can be solved just by rearranging the requirements list, but not in every case.

**Comment by lasote** [comment] 2019-05-20 14:00
That is the expected behavior. If you want to be able to override from the consumer you have to use `default_options`. And yes, the requirements order matter to calculate the package that "wins" declaring the option.
In which cases is not possible to just use default options?

**Comment by happy-monk** [comment] 2019-05-29 11:39
`default_options` can't be used to declare options conditionally, as far as I can tell. In my case PkgA and PkgB is fairly large in-house packages. They are projects in their own right, they use many dependencies and they use conditional options very extensively.

Even beside this I don't have direct control over PkgA and PkgB, and over third-party packages I have even less. I can only persuade developers of this packages to change the way they declare options. As alternative, of course, I could make fork of their package, but this is less convenient and becomes even less so for in-house packages since they release minor versions very often. So it would be much more convenient to have the ability to override subdependency options the same way it works for requirements now without the need to depend on other package's readiness to cooperate.

Anyway, the most flexible way to do subdep options I can figure out for now is to use `default_options` where possible and use `sels.options` assignment for conditional options, but cover it with `if self.develop` to disable them completely when using package as dependency.

**Comment by lasote** [comment] 2019-06-04 12:52
I understand. But if `PkgA or PkgB` want to conditionally adjust an option of `boost` it is not a "default" anymore, it is because they WANT to work like that. So the conflict is justified, and you cannot override it because the recipe is telling you that it has to be like that.

So, if the option adjusted in boost works anyway for  `PkgA and PkgB` they should use the `default_options` mechanism so you can override downstream.

**Comment by AbrilRBS** [comment] 2024-06-28 22:49
Closing as solved in Conan, which introduced the notion of [`important!`](https://docs.conan.io/2/reference/conanfile/attributes.html#default-options) options, which have precedence over normal option declarations, but should be used with extreme caution :)

**Closed by AbrilRBS** 2024-06-28 22:49 UTC
Labels: stage: triaging
