### ISSUE TITLE
[feature] [editables] Layout files need and additional path as input (recipes out-of-sources)

### ISSUE THREAD

**Issue by cguldner** [conan-io/conan#6896] opened 2020-04-23 14:32 UTC
Hello.

I am hoping to use Conan's editable package mechanism to enable building multiple repositories simultaneously . In the environment I'm in, we pull down several repositories to build the code, so they are all very interdependent. Thus, the editable package scheme (and workspaces) is an attractive option for me.

I am exploring using Conan to reduce build times and make things easier to manage, and in the current scheme that we are using, we're thinking we will have all of our recipes in a single repo, and build out of that repo. From what I've seen, the Conan editable package scheme doesn't currently support this.

Say I have this layout, where repo1.py and repo2.py are my conanfiles.

```
devkit
└─recipes
│   │   repo1.py
│   │   repo2.py

repo1
└─say.cpp

repo2
└─hello.cpp
```

Suppose repo2.py depends on repo1.py. I want to be able to run `conan editable add devkit/recipes/repo1.py repo1/1.0@user/channel`, and have a way for it to know that the source is actually in repo1/. But then when I go to install repo1, which is required for me to build repo2 so that the files are deployed to the spot that repo2 is expecting them, I get

> ERROR: Error loading conanfile at 'devkit/recipes/conanfile.py': devkit/recipes/conanfile.py not found!

So clearly it is expecting my recipe to be in the same repo as the source. I've tried adding a layout file to point at the source, but I get the same error.

- [X] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by jgsogo** [comment] 2020-04-23 16:15
Hi @cguldner!


## **Short answer:** 

Yes, that's a limitation, headers and built artifacts are expected to be _close_ to the conanfile.py. While reproducing this issue I found a couple of things that are worth commenting here

## **Long answer:**

I think this is a scenario it is worth to reproduce so we can test on our own. There can be many details here. I've prepared several repos trying to reproduce your scenario:
 * devkit --> `https://github.com/jgsogo/conan-issue6896-1`
 * repo1 --> `https://github.com/jgsogo/conan-issue6896-2`
 * repo2 --> `https://github.com/jgsogo/conan-issue6896-3`

You can clone and run:

```
conan remove -f say/version@user/testing &&  conan create conan-issue6896-1/recipes/repo1.py say/version@user/testing
conan remove -f hello/version@user/testing &&  conan create conan-issue6896-1/recipes/repo2.py hello/version@user/testing
```

It is working so far (I'm removing before because of the way I'm using SCM feature, the recipe doesn't change, but sources changes... recipe should point to the snapshot of the sources, but it is not related to this issue right now).

---

Now, let's go for the editable part: first of all I need a working copy  of `repo1` in my machine:

```
cd conan-issue6896-2
mkdir _build && cd _build
conan install ../../conan-issue6896-1/recipes/repo1.py 
cmake .. -DCMAKE_MODULE_PATH=$(pwd) && cmake --build .
```

we do need a layout file because these directories don't look like the ones Conan creates in the cache (`include`, `lib`,  `bin`), and **the problem is that paths in layout files are relative to the folder where the Conan file is located**. So, the only approach that could work is:

```
conan editable add say/version@user/testing create conan-issue6896-1/recipes/repo1.py -l layout_file
```

And the layout file needs full paths to the folders

```ini
[includedirs]
/Users/jgsogo/dev/conan/tmp/6896/layout/conan-issue6896-2/

[libdirs]
/Users/jgsogo/dev/conan/tmp/6896/layout/conan-issue6896-2/_build/lib
```

Then, we should be able to run:

```
cd conan-issue6896-3 
mkdir _build && cd _build 
conan install ../../conan-issue6896-1/recipes/repo2.py 
```

.... but it fails 😞 

---

There are two issues here:
 * [bug] path to the `conanfile` for editable packages doesn't store the actual file with the recipe, but the path to the folder and assumes that its names will be `conanfile.py` 🐛 
 * [discussion] Typically the layout for each user would be different, but we all know that in a company it is useful to share it because all the developers will clone and compile using the same tools and the same folders. If the layout needs the full path to the working copy, we cannot share it if it includes the "home" of the user (`/Users/jgsogo` won't be your home). It looks like we need an additional chunk of information to make this work:
    + opt1: every user passes an additional argument to the `rootfolder` to prepend to the relative paths in the layout (information to be stored in `editable_packages.json` file.
    + opt2: Conan passes to the `layout` file the path where that file is located (only if it is not in the cache), then the layout file can compose the relative paths (jinja2 syntax). In this scenario, the `layout` file would be stored in the repository together with the sources.

**Comment by cguldner** [comment] 2020-04-24 13:21
@jgsogo Thanks for the detailed response, and for creating a test case!

> we do need a layout file because these directories don't look like the ones Conan creates in the cache (include, lib, bin), and the problem is that paths in layout files are relative to the folder where the Conan file is located

I'm wondering why you can't just specify the location of the source files relatively, so in this case, why couldn't I do

```
[libdirs]
../repo1/_build
```

>path to the conanfile for editable packages doesn't store the actual file with the recipe, but the path to the folder and assumes that its names will be conanfile.py

You could even possibly point the layout file to where the conanfile is, so then it would be the one source for all of the information about editable packages, though I'd think this functionality should probably just be baked in when you run `conan editable` to store the path to the recipe used to create the editable package

**Comment by jgsogo** [comment] 2020-04-24 13:42
On our first approach to this feature, we expected the layout files to be stored in the cache or being created by the user for a very specific package. With issues like this one probably that assumption was no longer valid for all scenarios.

We also thought that the best way to go was to compute the paths relative to the conanfile, not to the place where the layout file was (it didn't make sense if these files were going to be stored in the cache).

**Comment by cguldner** [comment] 2020-04-24 15:58
@jgsogo It sounds like the only problem is that there isn't a way for Conan to know that my recipe is not stored with my source as "conanfile". If that problem could get resolved, then I think I could just give a relative path to my source files, right

**Comment by cguldner** [comment] 2020-04-24 20:43
@jgsogo Is it true that I should be able to specify where the library/build/include files are from my layout file as relative paths?

If so, then I believe this issue should close because you created the bug issue, correct?

**Comment by jgsogo** [comment] 2020-05-12 10:48
Not really, there is a pending _feature request_ here:

> [discussion] Typically the layout for each user would be different, but we all know that in a company it is useful to share it because all the developers will clone and compile using the same tools and the same folders. If the layout needs the full path to the working copy, we cannot share it if it includes the "home" of the user (/Users/jgsogo won't be your home). It looks like we need an additional chunk of information to make this work:
> * opt1: every user passes an additional argument to the rootfolder to prepend to the relative paths in the layout (information to be stored in editable_packages.json file.
> * opt2: Conan passes to the layout file the path where that file is located (only if it is not in the cache), then the layout file can compose the relative paths (jinja2 syntax). In this scenario, the layout file would be stored in the repository together with the sources.

**Comment by cguldner** [comment] 2020-05-12 13:08
@jgsogo At least for our use case, we would store the layout files and the conanfiles in the same repo, so it would be fine for us to just pass the path relative to the conanfile. But it would be a good feature to be able to have the paths be relative from the layout file instead

**Comment by jgsogo** [comment] 2020-06-10 07:10
Related? https://github.com/conan-io/conan/issues/4840

**Comment by memsharded** [comment] 2023-12-31 00:21
Deprecated time ago by the ``layout()`` method, closing as outdated

**Closed as completed by memsharded** 2023-12-31 00:21 UTC
Labels: type: feature, stage: queue, priority: medium, complex: low
