### ISSUE TITLE
[feature] `validate()` should work for `conan install`

### ISSUE THREAD

**Issue by mpusz** [conan-io/conan#10723] opened 2022-03-05 21:39 UTC
`validate()` was advertised as a new solution that should replace configuration verification that was previously handled in the `configure()` method. However, it turns up that even though `configure()` properly triggers an error during `conan install`, `validate()` is not checked at all at this stage.

I personally think that such behavior is highly misleading and if possible `validate()` should be used to validate the configuration for all workflows (both package creation and package consumption).

Otherwise, the documentation should be very clear that `configure()` is the only possible way to verify a configuration error in the package consumption workflow.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by samuel-emrys** [comment] 2022-03-06 01:04
Duplicate of https://github.com/conan-io/conan/issues/10602 - looks like this is slated for 1.47.0

**Comment by memsharded** [comment] 2022-03-07 00:37
Thats right, lets continue on https://github.com/conan-io/conan/issues/10602

**Closed as completed by memsharded** 2022-03-07 00:37 UTC
