### ISSUE TITLE
Managing dependencies for a large Visual Studio solution 

### ISSUE THREAD

**Issue by birsoyo** [conan-io/conan#1338] opened 2017-05-31 15:11 UTC
I have a visual studio solution with lots of projects (>100).  Every project depends a different subset of the  the dependencies listed in the conanfile.txt. 

In order to properly manage the dependencies I do the following,
I create a separate conanfile.txt file for each dependency (like conanfile_FreeImage.txt, conafile_Boost.txt).  Then I generate their .props files with a script (i.e run conan install for each conanfile_*.txt). Now I have a separate props files for each dependency, my projects can add the required props files as needed.

Is there a feature in conan that I missed that will solve this problem for visual studio (and xcode) generators (something like cmake's targets approach)?

Note: I am planning to work on a custom generator for visual studio and xcode, that generates multiple xcconfig and props files per dependency, but before starting the project I wanted to make sure I didn't miss a feature that would help.

Thanks.

**Comment by memsharded** [comment] 2017-05-31 15:39
Have you been able to read the blog post about VS projects? The idea there is to actually modularize development for each subproject, being each one a separate package. Have a look at: http://blog.conan.io/2017/05/11/C-C++-Binary-Package-Management-for-Visual-Studio.html

The issue with a different ``conanfile.txt`` for each dependency is that some of them might have conflicting transitive dependencies that might pass unnoticed. Why not a conanfile.txt for each subproject? Each subproject will list its own dependencies. It is important to know if some of the subprojects could use a different version of the same library. Is it possible that one subproject uses zlib/1.2.8, while other uses zlib/1.2.11, for example?

Also, do you want to manage the dependencies between subprojects with conan? Or will they be managed directly by the solution, and you want to manage only external dependencies?

There is nothing builtin in conan that does such generation of multiple props files, one per dependency, but I guess it shouldn't be difficult to implement. I have some questions: how would you manage to achieve coherent behavior? Would each subproject have to manually add the corresponding property files? IMHO it seems more logical to have a property file always called the same, but one per subproject.

Please tell me, lets see if we can figure out together the best approach for your problem. Thanks!

**Comment by birsoyo** [comment] 2017-05-31 20:27
> Why not a conanfile.txt for each subproject?

I thought this would be a maintenance problem since when there is a new version of some low level library that (almost) everyone depends (i.e. like boost), I have to *correctly* update all >100 conanfile.txt files. Not that I discarded "conanfile.txt for each subproject" solution, I currently think "conanfile.txt for each dependency" has less disadvantages.

> It is important to know if some of the subprojects could use a different version of the same library. Is it possible that one subproject uses zlib/1.2.8, while other uses zlib/1.2.11, for example?

This is one of the problems I would like to avoid with help from conan. Historically this happened (funny enough with zlib), but not by choice (i.e. nobody noticed until something went wrong). Note that I would also develop my own third party conan recipes. I think maintaining consistency would be easier this way.

> Also, do you want to manage the dependencies between subprojects with conan? 

Yes. That is actually the ultimate goal which will span multiple years to achieve. I would like to separate this >100 project solution into smaller *products* with their own release cycles different that the main product which will use conan to pick and choose the *internal* dependencies as well as the external ones. I just started the project with external third party libraries first.

> There is nothing builtin in conan that does such generation of multiple props files, one per dependency, but I guess it shouldn't be difficult to implement.

I already have something going. I will publish my custom visual studio generator through github upcoming days to share with you for discussion.

> how would you manage to achieve coherent behavior?

That's why I don't like separate conanfile.txt solutions (neither per dependency nor per subproject). If there is one master conanfile.txt, a custom generator can easily check for inconsistent transitive dependencies and produce warnings/errors.

> Would each subproject have to manually add the corresponding property files? 

This is what I am doing now with separate conanfile.txt per dependency approach.  But as I said I don't particularly like this solution either. Current script processes each conanfile_*.txt file and after the conan generates the props (and xcconfig) files, it renames them to match the original input (i.e. conanbuildinfo_FreeImage.props). Different names for props files make it easier to distinguish them in the VS Property Manager window, otherwise they all would be listed as "conanbuildinfo" in the VS UI.

I also have this *crazy* idea to maintain coherent behavior which I haven't tried yet. I would like to create a conan recipe just to pull transitive dependencies and give it a version. Something like the following.
```
class ExternalDependenciesConan(ConanFile):
  name = "ExternalDependencies"
  version = '42'
  [etc]
  requires = 'boost/1.64.0@orhun/testing', 'zlib/1.2.11@orhun/testing', [etc]
  def source(self):
    pass
  def build(self):
   pass
 [etc]
```
So now my internal project can bring in this, already tested (i.e. consistent etc), dependency in one line. For example,
```
[requires]
ExternalDependencies/42@orhun/testing

# now I need a way to tell conan this project only needs zlib from the above transitive dependencies.
# Can I use "Scopes"? (http://conanio.readthedocs.io/en/latest/mastering/scopes.html) 
# Probably needs to be py instead of txt.
```
Sorry for the long post...

**Comment by memsharded** [comment] 2017-05-31 20:57
No apologies! Your post is plenty of clear, interesting and valuable feedback of a very real use case.

I think I start to understand the issue. I agree with the roadmap of doing first the third parties, then modularize common parts of the solution. The problem is of course the transitory state. 

Conan is able to deal with the dependency overriding and detect conflicts (yeah, I know by experience that this unlucky problems many times do not show while building but later in production, and are a nightmare to debug), when it maintains the whole dependency graph. 

So your latest idea could be good, just gave me another, probably it is a crazy idea, but could make sense: define one conanfile.py per subproject, with dependencies between subprojects also defined, to compute the full dependency graph. These conanfile.py do not need to be full package recipes, just declare the dependencies, no need to really create packages from them. Make each one use the visual studio generator to generate the correct props file, then collect all of them at install. It is more work, but it is one-shot, and can be done in a few hours, no need a large investment.
In this way you would have kind of half-way setup, not complete but real and useful for your long-term goal, and could more easily maintain coherence and automation. Just and idea, need more work to know if it is possible. What do you think? 
Thanks again for your feedback!

**Comment by dibben-jsol** [comment] 2017-06-05 14:16
We have a similar situation; a large number of projects all using a slightly different set of common libraries. In our case they are not all VisualStudio projects, some use qmake for the build. The projects are built independently so it might be hard to use a common per-dependency conanfile. This is not something I had thought of. 

What I have been considering is a per-project conan file + a script to update all the conanfiles. What we would do is use version ranges in the conan file for the trunk development version of the projects so they would automatically get the latest version of the dependencies. When  we create a release version of a project we create a branch in the source control for that project. We would then run the script to go through each of the conanfiles in the release branches fixing the versions to the specific current version of the dependency. So the specific version dependency would be fixed in the source control giving a repeatable build. 

That is, I had thought to  solve the problem of updating a large number of conan files (we have about 170 modules) by automating it.  We are still in the process of setting all this up, but I have a test version of the update script that seems to work.

**Comment by memsharded** [comment] 2017-06-05 15:48
Thanks for the feedback on this issue @dibben-jsol 

Just one personal opinion: even if you have hundreds of conanfiles, one per sub-project, it is not a big issue to update a specific version for all of them. Lets say that you have a very common dependency to ``Boost/1.59@team/stable`` in many of them. Upgrading to next Boost version, is just a search & replace with ``Boost/1.60@team/stable``, that can be done in seconds. Verifying there are no left Boost/1.59 is a simple search that can be done in seconds.

I usually prefer model consistency over operational consistency, as the later can be very easily automated, but quirks in the model lead to confusion, bugs and pain in the long term. Following this rule, it is better to have each project lists its dependencies, than having one conanfile per dependency. My 2 cents :)

**Comment by birsoyo** [comment] 2017-06-05 16:11
I have created a conan generator for visual studio which let's you select individual dependencies within [Visual Studio UI (Property pages)](https://github.com/birsoyo/conan-visualstudio/blob/e7c26ed9cc4f2553bb4e789bf79e154b0b74f5a7/images/conan-property-pages.png), while maintaining a single conanfile.txt.

It is shared [here](https://github.com/birsoyo/conan-visualstudio). Note that it is really in an experimental state.

It has 2 components.
 * Conan.props: 
   - It [imports](https://github.com/birsoyo/conan-visualstudio/blob/e7c26ed9cc4f2553bb4e789bf79e154b0b74f5a7/Conan.props#L53) the conanbuildinfo.props file such that one can open the solution even if the one didn't run `conan install` yet. VS won't open a project if an imported props file doesn't exists.
   - It [adds](https://github.com/birsoyo/conan-visualstudio/blob/e7c26ed9cc4f2553bb4e789bf79e154b0b74f5a7/Conan.props#L57) the solution level conanfile.txt to all projects it was added to, so it shows up in UI.
   - It also adds a [custom build](https://github.com/birsoyo/conan-visualstudio/blob/e7c26ed9cc4f2553bb4e789bf79e154b0b74f5a7/Conan.props#L61) to the conanfile.txt to run `conan install` with the correct parameters. 
   - Note that since conan generator can only create one file, my generator generates a python script which in turn generates the required files (conanbuildinfo.props and conanbuildinfo.xml). The xml is the file that provides the Visual Studio UI.
   - Conan.props file also [runs](https://github.com/birsoyo/conan-visualstudio/blob/e7c26ed9cc4f2553bb4e789bf79e154b0b74f5a7/Conan.props#L62) this python script.

 * advancedvisualstudiogenerator.py which generates conanbuildinfo.props and xml:
   - conanbuildinfo.props file defines 3 variables 
     - USES_[DependencyName]_BINARIES
     - USES_[DependencyName]_COMPILE
     - USES_[DependencyName]_LINK
     - These variables adds conan variables to their msbuild counterparts conditionally.
     - Otherwise it should be very similar to what conan generates in its default visual studio generator. If it isn't it is my mistake.
   - conanbuildinfo.xml file enables the UI and lets the individual project change the *USES* variables for its needs. 
   - *USES* variable changes will be stored within the project's vxproj file.

**Comment by memsharded** [comment] 2017-06-06 10:10
Good job. I am having a look, it seems there are very good ideas here, and you have good knowledge of VS solutions. When this stabilizes, maybe we want to incorporate some ideas into the existing generator, or maybe add a new built-in generator, if it can be useful for other VS users.

One question, why the ``python advancedvisualstudiogenerator.py``, why not directly generating the two files, so no necessary that step? You can make generators output several files, simply returning a dict from the ``contents`` method, like the cmake_multi generator does:

```python
    @property
    def content(self):
        build_type = str(self.conanfile.settings.build_type).lower()
        result = {"conanbuildinfo_%s.cmake" % build_type: self._content_type(build_type),
                       "conanbuildinfo_multi.cmake": self._content_multi}
        return result

    @property
    def filename(self):
        pass
```

**Comment by birsoyo** [comment] 2017-06-06 14:27
> One question, why the python advancedvisualstudiogenerator.py, why not directly generating the two files, so no necessary that step?

I knew I missed something. I'll fix it as soon as possible.

**Comment by memsharded** [comment] 2017-06-06 14:44
Any time you feel something is not good/clear enough, please ask. Either there is something already, or it might be a potential improvement, so good to know in any case!

**Comment by memsharded** [comment] 2021-12-04 15:54
Hi @birsoyo @dibben-jsol 

This has been implemented some time ago in the ``MSBuildDeps`` generator, inspired by all your feedback:

- It generates a .props file per dependency
- It correctly manage transitive dependencies, so including only the direct ones is ok
- It is multi-config, it knows to handle Release/Debug
- It allows customization, including custom configurations
- It will be the canonical MSBuild integration in 2.0

It is becoming quite stable since 1.40 (it was introduced in 1.32, 1 year ago), so even if still experimental, I recommend it.

Please have a look at: https://docs.conan.io/en/latest/reference/conanfile/tools/microsoft.html, any feedback welcome. 
(Closing this as implemented)

**Closed by memsharded** 2021-12-04 15:54 UTC
