### ISSUE TITLE
[bug] Wrong library order when using Components

### ISSUE THREAD

**Issue by gouriano** [conan-io/conan#8758] opened 2021-04-02 17:32 UTC
Hello,

We at NCBI (https://www.ncbi.nlm.nih.gov) are experimenting with Conan trying to adapt our C++ Toolkit to it.
We have discovered what we believe is a bug in how Conan is ordering libraries described with the help of Components.

Here is the problem.
We have 58 libraries. We describe their dependencies and create Conan package. Then, we are trying to build an application which uses these libraries and it fails to compile - because library order is wrong. There are "undefined references". We change the order in which Components are described - only the order! - and the build succeeds. The application builds fine. The library order has changed.
We believe library order should not depend on the order in which Components are described
We understand that "58 libraries" is a bit too much and tried to come up with a smaller example, but failed.

Environment: Linux, Python v3.8.1, Conan v1.35.0
Compiler is GCC 7.3.0.

We have two Conan recipes here: 
ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/MISC/TEST/Conan
conanfile-bad.py produces wrong library order
conanfile-good.py produces correct library order

The only difference between these two is the order in which components are described.
The exact generated order can be found inside the files.

We can give you the source code, but not sure this is needed.
We believe there should be a way for you to test library ordering mechanism without actually compiling anything.

Thanks

**Comment by solvingj** [comment] 2021-04-06 00:51
This definitely sounds like a bug to me, thank you for reporting it.  I think your description demonstrates the problem clearly and simply, but for the record, it's possible there will be some un-intuitive nuance and significant complexity to the way in which it might have to be solved. 

In the naïve and simple case, I suppose the simple description of the solution is to make the ordering of the libraries be based upon the resolved component-dependency-graph rather than declaration order. However, there are cases where no components depend on each other, in which case declaration order is the most sensible behavior.  Also, there are cases where multiple packages depend on different components within a single package, and then when those components have a dependency between them.  There are likely even more caveats.  Thus, this will definitely require someone to re-evaluate the "final linker order" in the context of components, and write some significant unit tests to ensure that we get the appropriate results in all cases.  I have set the milestone for the next release, but it may turn out to be too complex to achieve in the time available, so that is subject to change.

**Comment by vakatov** [comment] 2021-04-06 01:13
Great, thanks much @solvingj ! We have this big (500+ libraries and maybe 1,500 apps; with some code generated on the fly; and depending on dozens of 3rd-party libs) multi-platform biotech software toolkit that we are moving to use CMake and Conan. It can really try the boundaries of various tools. Canon looks very promising, and the "components" feature in particular seems to be just what the doctor prescribed!

**Comment by memsharded** [comment] 2021-04-26 12:34
Hi @vakatov 

> We have 58 libraries. We describe their dependencies and create Conan package. Then, we are trying to build an application which uses these libraries and it fails to compile - because library order is wrong. There are "undefined references". We change the order in which Components are described - only the order! - and the build succeeds. The application builds fine. The library order has changed.

Ok, this will point to a problem in the definition of dependencies, but I have not enough information to reproduce, so it is difficult to fix it.

The thing is that the ``requires`` between components will induce an order in the link step. But if there are some not fully determined order, for example, 2 completely independent components, then the declaration order is what is followed. In your case, it is possible that there is missing some internal dependency between components, that would force a relative order between them.

Of course what would really help is a reproducible case, but if that is not possible, if you could post here your ``package_info()`` method, both for the working and not working cases, together with the final effective linker command lines, that would help to try to debug what is happening. Thanks!

**Comment by gouriano** [comment] 2021-04-26 12:55
Earlier I gave you a link to two recipes
ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/MISC/TEST/Conan
these are full working recipes, with package_info() methods.
They also contain definitions of CONAN_LIBS_NCBICXXTEST, as generated by "conan install"
I do not really understand what is missing here.

**Comment by memsharded** [comment] 2021-04-26 14:19
Oh! Sorry, I didn't see that ftp link because not being highlighted as link, my bad for reading too fast.
I will check that ftp files

**Comment by memsharded** [comment] 2021-04-26 18:40
Sorry, I am having some issues with the ftp, it seems to require login/password. 
```
User (ftp.wip.ncbi.nlm.nih.gov:(none)): none
331 Password required for none
Password:
530 Login incorrect.
```

Could you please copy those files and post them directly here in this issue? Thanks!

**Comment by gouriano** [comment] 2021-04-26 19:47
Oh, sorry, I did not check that.
I have just tried this FTP link from home Windows PC
Firefox open them no question asked. Edge, Chrome, Opera do not open. Nobody asks any password.
Ok, I attach them here
[conanfile-good.py.txt](https://github.com/conan-io/conan/files/6379838/conanfile-good.py.txt)
[conanfile-bad.py.txt](https://github.com/conan-io/conan/files/6379839/conanfile-bad.py.txt)

**Comment by memsharded** [comment] 2021-04-26 20:55
Good, thanks!

So far I have been able to reproduce something similar, and apparently the issue might be in the ``cmake`` generator.
If you use the more modern ``cmake_find_package``, ``cmake_find_package_multi`` or the newer experimental ``CMakeDeps``, you might not encounter this issue. You might be interested in having a look at those.

I will have a look to the ``cmake`` generator, to see what could be the issue.

**Comment by gouriano** [comment] 2021-04-26 21:08
If I do not use Conan, everything works just fine,

**Comment by memsharded** [comment] 2021-04-26 22:21
I am checking your definition of components, I think there is a bug there:

```python
self.cpp_info.components["xhtml"].libs = ["xutil"]
```

Could you please double check it? Having an incorrect definition of the components could be creating this issue. Thanks!

**Comment by gouriano** [comment] 2021-04-27 14:30
Apparently, now I can only apologize for wasting your time... I have fixed this and it works fine now...
This is probably why I could not reproduce it in other scenarios.
I am awfully sorry.
"not a bug"

**Comment by memsharded** [comment] 2021-04-27 14:34
> Apparently, now I can only apologize for wasting your time... I have fixed this and it works fine now...
This is probably why I could not reproduce it in other scenarios.
I am awfully sorry.
"not a bug"

Don't worry, no need to apologize! 😄 

These things happen to all, and we are happy to help as much as we can, glad that the issue is solved. Closing this now, but don't hesitate to open new issues if you have any other question or need help with something. Cheers!

**Closed as completed by memsharded** 2021-04-27 14:34 UTC
Labels: type: bug, stage: triaging
