### ISSUE TITLE
[question] Clarifications re: local-repo index vs. binary artifacts…

### ISSUE THREAD

**Issue by ArdGitUser1** [conan-io/conan#16804] opened 2024-08-08 15:35 UTC
### What is your question?

Hello!  I have been reviewing the options for remote package repositories - i.e., Conan-Center vs. local-recipes index.  

Trying to understand the major differences between these two ‘options’ and wanted to run my analysis by the ‘experts’:
  - A private org could take their ‘required’ dependencies (including all transitive dep’s) and host them from a SCM (such as GitHub, or BitBucket) // local-recipes index.
  - Source (for a given recipe) whether 3rd-party or local pkg/lib can be hosted or captured ‘elsewhere’ - e.g. in a separate git repo from the recipe - whether conan-center on conan.io _or_ local-recipes index. Conan ‘source’ can fetch the actual source as shown in the examples.
  - Conan’s local development flow works in _either_ mode - i.e., conan-center on conan.io if the software developer has publicly available ‘recipes’ stored, and is enhancing them locally OR completely private - based on local-recipes index if a pkg/lib not freely available.
  - My ‘hope’ is the conan dir-structure (local-recipes index) is not completely ‘defined’ or mandated below the ‘closed-source’ library - e.g. repo / recipes / hello / <down here>.  As noted [here](https://github.com/gto406/conanTst), we have adopted a slightly ‘different’ structure - which works (nicely) with conan (conan-center on conan.io).  I would assume we could ‘clone’ or ‘fetch’ conanTst directly underneath ‘hello’ without any impacts to the operation of conan - except perhaps ‘conan test’ which relies on a separate/distinct CMakeLists.txt for the unit-test(s).

I had some other questions re: CI/CD, however unsure if this is the best venue to ask these.  Likely need to reach out to the JFrog folks. 8^)

### Have you read the CONTRIBUTING guide?

- [x] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-08-08 16:08
Hi @ArdGitUser1 

Thanks for your questions.

>  i.e., Conan-Center vs. local-recipes index.

I think the best way to understand it is by differentiating between source repositories and real package repositories.

ConanCenter in ``https://center.conan.io`` is a real full package repository. It contains recipes and packages and all the utilities to be able to fully reproduce dependencies (like using lockfiles locking different recipe-revisions).

On the other hand, a ``local-recipes-index`` repository is a "source" repository. It only contains the recipes, but not real packages, and as described in the documentation, it has some limitations, for example it cannot fully reproduce a dependency graph with lockfiles, because it cannot go back in time to any arbitrary recipe revision. It must be understood as a development and package-creation convenience for organizations that need their special customization of recipes in ConanCenter, or to host some third parties that are not yet in ConanCenter. But it shouldn't be understood or used as a full repository, for example, to host first-party packages. 
Even when using a ``local-recipes-index`` the recommendation for production usage is to use a full package server like the free ArtifactoryCE, to put there the packages built from the ``local-recipes-index`` repo.

So to clarify your questions:

> A private org could take their ‘required’ dependencies (including all transitive dep’s) and host them from a SCM (such as GitHub, or BitBucket) // local-recipes index.

No, this is not hosting the dependencies, including transitive dependencies. A local-recipes-index only hosts the source recipes for third party (and only for third party) dependencies, but it is not the same. The repo can create dependencies on the fly, but it does not host dependencies (thus some of the limitations listed above as reproducibility with lockfiles).

> Source (for a given recipe) whether 3rd-party or local pkg/lib can be hosted or captured ‘elsewhere’ - e.g. in a separate git repo from the recipe - whether conan-center on conan.io or local-recipes index. Conan ‘source’ can fetch the actual source as shown in the examples.

The approach doesn't work for first party, because for first party it is expected that devs can ``git clone`` the repo containing the first party, and then ``conan install`` its dependencies to be able to develop that package code. Separating the source and the conanfile.py recipe doesn't scale for first-party code.

The approach in https://github.com/gto406/conanTst is kind of standard for first-party code, just put the ``conanfile.py`` together with the source. But this is not related at all with the ``local-recipes-index`` feature, this is the normal approach for first-party package creation.


Please let me know if this clarifies a bit.

**Comment by gto406** [comment] 2024-08-08 21:29
Many thanks for your 'speedy' reply James! 

If I understand you correctly - the purpose of **center.conan.io** is to:
   - Host recipe 'sources' to reproduce any packages (3rd-parties) supported by conan.io - e.g., `fmt` or `nlohmann_json` to name 2
   - The recipes captured inside of **center.conan.io** can be utilized 'out of the box' to reproduce a pkg/lib in the local cache
   - If I am developing a first party library (e.g., my own), I fetch/commit the source making up the library using my SCM (e.g., GitHub) - based on a repository that lies completely outside the scope of local-recipes index.  
   - A first party library that is conan compatible (i.e., has a recipe) provides its own `conanfile.py` - similar to [conanTst](https://github.com/gto406/conanTst) example.
   - I would utilize a **local-recipes index** if I wanted to e.g., customize the generally available `fmt` pkg/lib for my org. 

Does my understanding -align with the conan.io view, so far?

Continuing on...
  - when you say 'separating the source & the conanfile.py recipe doesn't scale for first-party code.' - I am confused.  If I look at for example `fmt`pkg/lib at **center.conan.io** there exists in the recipe, a `conandata.yaml` file, with references (URL, sha) to an external repository - presumably where the `fmt` library itself hosted.  Does this mean that first party pkg/libs are different from third-party packages added to **center.conan.io**?  

Notes on Artifactory:
I was attempting to try and 'stand up' ArtifactoryCE (C/C++) the other day - based on Azure VM's (Debian) - however was having issues getting Azure end-point/firewall rules to play nice with Tomcat.  

Appreciate your time, trying to help me better understand and leverage this powerful package manager! 8^)

**Comment by memsharded** [comment] 2024-08-11 16:03
> Host recipe 'sources' to reproduce any packages (3rd-parties) supported by conan.io - e.g., fmt or nlohmann_json to name 2

To be accurate, the purpose of ``center.conan.io`` is to host "packages" that is, both recipe and package binaries built from those recipes, for some mainstream configurations.

> The recipes captured inside of center.conan.io can be utilized 'out of the box' to reproduce a pkg/lib in the local cache

Yes, in  many cases, even if the pre-compiled binary doesn't exist in ConanCenter for some configuration, it might be possible to build it from source in the local cache with ``--build=missing``. Note it is also possible that some configuration not well tested (e.g. webassembly, QNX, etc) might not build correctly if the recipe in ConanCenter didn't provision for it.

> If I am developing a first party library (e.g., my own), I fetch/commit the source making up the library using my SCM (e.g., GitHub) - based on a repository that lies completely outside the scope of local-recipes index.


Yes, lets say the "canonical" first party approach is the one described in https://docs.conan.io/2/tutorial/creating_packages/create_your_first_package.html, with the ``conanfile.py`` in the same repo as the source, being it a regular repo, not a "local-recipes-index" repo.

> A first party library that is conan compatible (i.e., has a recipe) provides its own conanfile.py - similar to [conanTst](https://github.com/gto406/conanTst) example.


Yes, if we are talking about usage within an organization. This ``conanfile.py`` is intended for developers that ``git clone`` the repo and can use it to ``conan install`` its dependencies, and to create the package to upload it to a full package server. This ``conanfile.py`` is not really intended for consumers/users of the package. 

> I would utilize a local-recipes index if I wanted to e.g., customize the generally available fmt pkg/lib for my org.


Yes, exactly, or maybe to add a new version (newer or older) that doesn't exist in ConanCenter, to do your modifications, or even to add a recipe that doesn't exist in ConanCenter at all, but it is a third party for you and you want to handle it in the same way as other ConanCenter dependencies.

> Does my understanding -align with the conan.io view, so far?

Yes :)


> when you say 'separating the source & the conanfile.py recipe doesn't scale for first-party code.' - I am confused. If I look at for example fmtpkg/lib at center.conan.io there exists in the recipe, a conandata.yaml file, with references (URL, sha) to an external repository - presumably where the fmt library itself hosted. Does this mean that first party pkg/libs are different from third-party packages added to center.conan.io?

Yes, they are different, and they also have different development flows. You will very rarely (or never) modify the source code of one of your third parties like ``fmt``, ``boost``, ``zlib`` or ``openssl``. And if you do it, it is likely that you will maintain a fork of the original source for that third party. So the "work" to be done is mostly crafting the recipe, making sure that the package creates correctly (which can take some effort if the library has a complicated build system that you are not an expert). On the other hand, developing first party code repos is quite different. Writing a recipe is relatively easy, because you master the build system it is your own build scripts. But you will be modifying the C or C++ code frequently, creating new versions or revisions, etc. So it is very convenient to be able to ``git clone`` your source repository (your normal git repo, not a "local-recipes-index" repo), then do ``conan install`` there and start evolving your C++ code, without needing to go to another repo that will handle this C++ code as external download, as this makes it very inconvenient to work on the C++ code. Based on the C++ changes, you might also decide to bump the patch, minor or major version of the ``conanfile.py`` within the repo, that relates to the code changes, and it will be visible in the same commit/diff/PR.


> I was attempting to try and 'stand up' ArtifactoryCE (C/C++) the other day - based on Azure VM's (Debian) - however was having issues getting Azure end-point/firewall rules to play nice with Tomcat.

I hope you managed to solve those issues. I know little about Azure, so I am afraid I cannot help much there.


> Appreciate your time, trying to help me better understand and leverage this powerful package manager! 8^)

Happy to help, just let me know if you have any further question. Thanks for the feedback! :)

**Comment by memsharded** [comment] 2024-08-17 16:58
Any further feedback here? If not, we can close it as responded, you can always open new tickets for any further question. Thanks!

**Comment by gto406** [comment] 2024-08-17 20:49
My apologies!  Thank you for your note - I will try & close this (having issues closing this) - perhaps ‘responded’ is closed state for a Question.

Thank you James!

**Closed as completed** 2024-08-18 10:10 UTC
Labels: type: question, answered
