### ISSUE TITLE
[bug] Set gcc's libcxx according to the compiler's default

### ISSUE THREAD

**Issue by a-teammate** [conan-io/conan#2434] opened 2018-02-05 19:04 UTC
To help us debug your issue please explain:

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

Conan version: 1.0.4
Gcc version: 5.4
Conan settings: default

I see that #2423 is actually about a slightly different problem, so I open this issue here to clarify stuff and not hijack that other issue any more.

### Reproduce the error

* Install a vanilla conan
* Install gcc > 4
* Create a minimal project with
   * one dependency, which uses the stdlib in its interface
       * let's say a logging library which accepts `std::string`
       * of course as a conan package
   * a totally empty CMake project, just the title and using the one dependency
* Execute `conan install .. --build` and afterwards `cmake .. && make`

### What happens?
It will fail with linker errors.
it will look for symbols with `std::string[cxx11]` while the Logging library has just symbols with `std::string`.

This is because conan builds that dependency with a gcc switch which makes the dependency binary incompatible with a normal gcc build.
A switch which sets the ABI of gcc to a legacy ABI (a "compatibility ABI")

### How to workaround it?

There are three options:
- Append the same gcc switch to the project's compiler flags
- Build your project with `conan build`
    * which then uses a build helper, in this case the CMake one.
    * The build helper will apply the gcc flag in question when building the project as well
- Change your conan settings (`libstdc++` -> `libstdc++11`)

### Why do I find the workarounds problematic?

Because everyone using a gcc > 4 and wanting to build a project with a C++ dependency would need to either modify their build flags, or the conan settings.

### How to fix it

If gcc is > 4, make the default setting for libcxx: libstdc++11 (and not libstdc++)

### Why?

Because that is what gcc does by default.([chap 6 gcc manual](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)
Conan does override that switch, because it somehow needs to apply this "libcxx" flag (which is a good thing to have!). And it does it correctly: If libcxx is set to libstdc++ it should add a compiler flag to switch back to the legacy ABI when using gcc > 4.  
It just should not do so by default, because people building with gcc > 4 almost always want the default ABI and not the legacy ABI (and hence `libstdc++11` and not `libstdc++`)

To give a little background here:

The legacy ABI switch does provide compatibility. But no kind of compatibility a casual Conan user will be interested in:  
the compatibility between binaries built with different gcc versions. And more precisely the compatibility to link a dependency built with gcc < 5 with a project built with gcc >= 5. (since the ABI was stable before gcc 5 and it is stable and compatible since gcc 5)

Btw, the "cxx11" does not mean it has anything to do with using c++11 or using c++03! That is just the appendix of the symbols since the ABI break was because of features needed for getting the stdlib C++11 ready.
(See first paragraph here: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)

**Comment by lasote** [comment] 2018-02-06 08:21
Hi, I think this is a duplicate of: https://github.com/conan-io/conan/issues/2340

**Closed by lasote** 2018-02-06 08:21 UTC
