### ISSUE TITLE
[bug] [Conan 2.0.4] Meson generator can't find Ninja

### ISSUE THREAD

**Issue by ymiroshnyk** [conan-io/conan#13772] opened 2023-04-26 11:35 UTC
### Environment details

* Operating System+version: Mint 20.3
* Compiler+version: any
* Conan version: 2.0.4
* Python version:
$ python --version
Python 2.7.18
$ python3 --version
Python 3.8.10

### Steps to reproduce

```
conan install --requires=wayland/1.21.0 -b missing
```

### Logs

```
$ conan install --requires=wayland/1.21.0 -b missing

======== Input profiles ========
Profile host:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux

Profile build:
[settings]
arch=x86_64
build_type=Release
compiler=gcc
compiler.cppstd=gnu14
compiler.libcxx=libstdc++11
compiler.version=9
os=Linux


======== Computing dependency graph ========
Graph root
    cli
Requirements
    expat/2.5.0#7fde619c77c77a50ca72364bc92c4907 - Cache
    libffi/3.4.3#13786fb93785ed2662ca35a93cdb1c55 - Cache
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335 - Cache
    libxml2/2.10.3#1cbaf81341e07fcb0e61dadee882a193 - Cache
    wayland/1.21.0#19b20330f8177672377bd400c0990833 - Cache
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f - Cache
Build requirements
    meson/1.0.0#15586c0ac6f682805875ef903dbe7ee2 - Cache
    ninja/1.11.1#63bca91350508f335754f5f9e17ec989 - Cache
    pkgconf/1.9.3#a920b5c7f8d04f22b9fe03db91a864dd - Cache

======== Computing necessary packages ========
Requirements
    expat/2.5.0#7fde619c77c77a50ca72364bc92c4907:37315dae4d4905caf236519a9d4ebff8e85ea626#c7f354cdf718745f29bf64bbdba81735 - Cache
    libffi/3.4.3#13786fb93785ed2662ca35a93cdb1c55:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a#d2a019b46b7eea9369bff9a82bb42c76 - Cache
    libiconv/1.17#fa54397801cd96911a8294bc5fc76335:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a#c27bbb9ccc072c076fc39b59ead72ecb - Cache
    libxml2/2.10.3#1cbaf81341e07fcb0e61dadee882a193:4e176649c414ba5921c444094b5479299e55bcf8#275069b47f71609e6f95fd3080fcc01d - Cache
    wayland/1.21.0#19b20330f8177672377bd400c0990833:854bc6fb2d56bdc97efbca3345e4186c092b0354 - Build
    zlib/1.2.13#13c96f538b52e1600c40b88994de240f:72c852c5f0ae27ca0b1741e5fd7c8b8be91a590a#fb120a7b86e5f96bfd748644b07988a3 - Cache
Build requirements
    meson/1.0.0#15586c0ac6f682805875ef903dbe7ee2:da39a3ee5e6b4b0d3255bfef95601890afd80709#5c8fd51fc33f12e26519674d99afd0e5 - Skip
    ninja/1.11.1#63bca91350508f335754f5f9e17ec989:3593751651824fb813502c69c971267624ced41a#a53f170b60a46aef75ead8658bdeae05 - Skip
    pkgconf/1.9.3#a920b5c7f8d04f22b9fe03db91a864dd:c0b621fd4b3199fe05075171573398833dba85f4#a231c33e360d8be4e90467b36b88f027 - Cache

======== Installing packages ========
expat/2.5.0: Already installed! (1 of 9)
libffi/3.4.3: Already installed! (2 of 9)
libiconv/1.17: Already installed! (3 of 9)
ninja/1.11.1: Already installed! (4 of 9)
zlib/1.2.13: Already installed! (5 of 9)
pkgconf/1.9.3: Already installed! (6 of 9)
pkgconf/1.9.3: Appending PATH env var: /home/glaz/.conan2/p/pkgcod729a37c3fef7/p/bin
pkgconf/1.9.3: Setting PKG_CONFIG env var: /home/glaz/.conan2/p/pkgcod729a37c3fef7/p/bin/pkgconf
pkgconf/1.9.3: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
pkgconf/1.9.3: Appending AUTOMAKE_CONAN_INCLUDES env var: /home/glaz/.conan2/p/pkgcod729a37c3fef7/p/bin/aclocal
meson/1.0.0: Already installed! (7 of 9)
libxml2/2.10.3: Already installed! (8 of 9)
libxml2/2.10.3: Appending PATH environment variable: /home/glaz/.conan2/p/libxm2826b2c227e53/p/bin

-------- Installing package wayland/1.21.0 (9 of 9) --------
wayland/1.21.0: Building from source
wayland/1.21.0: Package wayland/1.21.0:854bc6fb2d56bdc97efbca3345e4186c092b0354
wayland/1.21.0: Copying sources to build folder
wayland/1.21.0: Building your package in /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b
wayland/1.21.0: Calling generate()
wayland/1.21.0: Generators folder: /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release/conan
wayland/1.21.0: Generating aggregated env files
wayland/1.21.0: Generated aggregated env files: ['conanbuild.sh']
wayland/1.21.0: Calling build()
wayland/1.21.0: Meson configure cmd: meson setup --native-file "/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release/conan/conan_meson_native.ini" "/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release" "/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/src" -Dprefix="/home/glaz/.conan2/p/t/wayla66f3b7e99896c/p"
wayland/1.21.0: RUN: meson setup --native-file "/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release/conan/conan_meson_native.ini" "/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release" "/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/src" -Dprefix="/home/glaz/.conan2/p/t/wayla66f3b7e99896c/p"
The Meson build system
Version: 1.0.0
Source dir: /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/src
Build dir: /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release
Build type: native build
Project name: wayland
Project version: 1.21.0
C compiler for the host machine: gcc (gcc 9.4.0 "gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0")
C linker for the host machine: gcc ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Has header "sys/prctl.h" : YES 
Has header "sys/procctl.h" : NO 
Has header "sys/ucred.h" : NO 
Checking for function "accept4" : YES 
Checking for function "mkostemp" : YES 
Checking for function "posix_fallocate" : YES 
Checking for function "prctl" : YES 
Checking for function "memfd_create" : YES 
Checking for function "mremap" : YES 
Checking for function "strndup" : YES 
Checking whether type "struct xucred" has member "cr_pid" : NO 
Found pkg-config: /home/glaz/.conan2/p/pkgcod729a37c3fef7/p/bin/pkgconf (1.9.3)
Run-time dependency libffi found: YES 3.4.3
Header "sys/signalfd.h" has symbol "SFD_CLOEXEC" : YES 
Header "sys/timerfd.h" has symbol "TFD_CLOEXEC" : YES 
Header "time.h" has symbol "CLOCK_MONOTONIC" : YES 
Checking for function "clock_gettime" : NO 
Library rt found: YES
Checking for function "clock_gettime" with dependency -lrt: YES 
Configuring config.h using configuration
Configuring wayland-version.h using configuration
Run-time dependency expat found: YES 2.5.0
Run-time dependency libxml-2.0 found: YES 2.10.3
Program embed.py found: YES (/usr/bin/python3 /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/src/src/embed.py)
Library m found: YES
Run-time dependency threads found: YES
Program nm found: YES (/usr/bin/nm)
Program wayland-egl-symbols-check found: YES (/home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/src/egl/wayland-egl-symbols-check)
Build targets in project: 14
NOTICE: Future-deprecated features used:
 * 0.62.0: {'pkgconfig.generate variable for builtin directories'}

wayland 1.21.0

  User defined options
    Native files: /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release/conan/conan_meson_native.ini
    prefix      : /home/glaz/.conan2/p/t/wayla66f3b7e99896c/p


ERROR: Could not detect Ninja v1.8.2 or newer

A full log can be found at /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release/meson-logs/meson-log.txt

wayland/1.21.0: ERROR: 
Package '854bc6fb2d56bdc97efbca3345e4186c092b0354' build failed
wayland/1.21.0: WARN: Build folder /home/glaz/.conan2/p/t/wayla66f3b7e99896c/b/build-release
*********************************************************
Recipe 'wayland/1.21.0' cannot build its binary
It is possible that this recipe is not Conan 2.0 ready
If the recipe comes from ConanCenter check: https://conan.io/cci-v2.html
If it is your recipe, check if it is updated to 2.0
*********************************************************

ERROR: wayland/1.21.0: Error in build() method, line 103
	meson.configure()
	ConanException: Error 1 while executing

```

It seems that `meson` can't find `ninja`.
Having both installed via `apt` or via `pip` doesn't make any difference.

**Comment by memsharded** [comment] 2023-04-26 13:03
Hi @ymiroshnyk 

Thanks for your report.
This is probably not related to Conan itself, but it might be a recipe issue (maybe ``ninja`` package is not that ready for 2.0?)

Installing things in the system shouldn't make a difference, ninja is a Conan package transitive dependency. If you have ninja 1.11.1 in your system you might try the new experimental 
```
[system_tools]
ninja/1.11.1
```
in your profile, to try to replace the Conan package with the system one.

We need to check this, lets have a look.

**Comment by ymiroshnyk** [comment] 2023-04-26 13:15
Yes, it works! Thank you very much.

**Comment by memsharded** [comment] 2023-04-26 13:52
I am trying to reproduce with a simpler recipe:

```
$ conan new meson_lib -d name=pkg -d version=0.1
```
My profile:
```
include(default)

[tool_requires]
meson/1.1.0
#pkgconf/1.9.3  uncomment in Windows
```
Then
```bash
$ conan build . -pr=profile
```
Seems to be working fine both in Windows and Linux, using the Ninja 1.11 from Conan package.

Could you please try these steps, just in case?

**Comment by memsharded** [comment] 2023-04-26 14:04
The ``conan install --requires=wayland/1.21.0`` also worked on my machine:

```
Found ninja-1.11.1 at /home/conan/.conan2/p/ninja4af6fda871d23/p/bin/ninja
```

No idea why it could be different on your system (I tested it in one ubuntu docker image)

**Comment by Tobulus** [comment] 2023-05-02 18:53
Probably fixed by this: https://github.com/conan-io/conan-center-index/pull/17135

**Comment by memsharded** [comment] 2023-05-03 21:23
Seems fixed then, it seems we can close this issue, please re-open or create a new ticket if necessary. Thanks!

**Closed as completed by memsharded** 2023-05-03 21:23 UTC
Labels: stage: triaging

**Comment by SpaceIm** [comment] 2023-05-07 14:17
The problem doesn't come from ninja recipe itself, nor conan client, but from glibc version ninja pre-built packages are linking against.

In v1 pipeline of c3i, it was solved by always building with gcc5 "application" recipes which remove settings.compiler in their package_id.
In v2 pipeline, this detail seems to have been forgotten, and these packages are built with gcc11, leading to glibc issues depending on your distro. The solution is to build ninja from source instead of relying on pre-built packages of conancenter.
