### ISSUE TITLE
[question] different CMake builds in one conanfile

### ISSUE THREAD

**Issue by andiwand** [conan-io/conan#10220] opened 2021-12-21 09:16 UTC
Hello - I hope this is the right place to ask this question!

I am currently trying to build and package [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX) to consume it later in [my CMake project](https://github.com/opendocument-app/OpenDocument.core) as a dependency for mobile and desktop.

pdf2htmlEX depends on poppler and fontforge but not in a usual way. It also wants to access "private" headers which are not exported in a packaged poppler version.

So I wondered if it might be easier to build those dependencies in my conanfile as a pre-build step for pdf2htmlEX.

My question is then: Has this been done before and is there a standard way for doing that?
Or do you see any other solution that would not result in a big change of pdf2htmlEX?

Thank you!

**Comment by memsharded** [comment] 2021-12-21 10:24
Hi @andiwand 

Yes, it is totally possible to vendor sub-libraries in a Conan package. Many projects out there vendor the libraries they use internally, and even manage to do the build automatically and transparently for the user. If that is the case, packaging that project is almost as easy as it didn't have any dependency. 

So it depends on how the original project manages that. I see https://github.com/pdf2htmlEX/pdf2htmlEX/tree/master/pdf2htmlEX/3rdparty, but it doesn't seem to contain the poppler, but instead it assumes that the source is relative to it: https://github.com/pdf2htmlEX/pdf2htmlEX/blob/7c9086b958e3da3ace34feb7306d7ed7e589bc9e/pdf2htmlEX/CMakeLists.txt#L31. So maybe it is enough to download the poppler sources in the ``source()`` or ``build()`` method too (besides the sources of the project).

The only thing that could be complicated is getting this accepted for the public ConanCenter. To create the package and put it in your own server, no problem, but to contribute back to ConanCenter, the reviewers will probably ask why this way (instead of depending on another Conan package), and these specifics will need to be discussed there, and see if this would be the best way for the wider community.

**Comment by andiwand** [comment] 2021-12-21 10:45
Thank you @memsharded !

As far as I can tell pdf2htmlEX expects poppler and fontforge to be cloned in the root. So what I did so far is download the 3 sources in `source()`.

But then I got a little confused when or where would be the best spot to call the build of these sub-libraries. `build()` seems to be fine since the configuration of pdf2htmlEX seems not dependent on the build of these sub-libraries.

Here is what I sketeched so far https://github.com/andiwand/conan-center-index/blob/pdf2htmlEX/recipes/pdf2htmlEX/all/conanfile.py#L73. I used `CMake(self)` for the sub-libraries too in hope they will get to know their dependencies I defined in `requires` of pdf2htmlEX.

It didn't work out of the box. Maybe there is a package that does something similar so I can take a look there?

> The only thing that could be complicated is getting this accepted for the public ConanCenter. To create the package and put it in your own server, no problem, but to contribute back to ConanCenter, the reviewers will probably ask why this way (instead of depending on another Conan package), and these specifics will need to be discussed there, and see if this would be the best way for the wider community.

Thank you for that insight! As a first step I will just put it on a custom server and try to get everything up and running.

Besides the problematic build pdf2htmlEX only builds into an executable which needs to be adopted. I will need to build a little library out of it which means I have to fork. Looking at the activity of the repository on GitHub it looks unlikely that my changes will be merged. So I would have to submit a fork of a fork to the ConanCenter which does not sound quite appealing :smile:

**Comment by memsharded** [comment] 2021-12-21 12:38
Maybe the ``CMake`` helper might not be the best approach, because it assumes 1 single build (including location of folders, etc). I think I would try to define my own wrapper CMakeLists.txt that ``add_subdirectory()`` the different folders, and try to have a relatively Conan independent build of the project (assuming the layout of the sources). In this way the package-creation and the build specifics keep decoupled.

Another approach that you might try is divide&conquer, to create your own package for poppler and fontforge, each one focused on building them exactly how you want, and packaging the headers that you need for consuming them with pdf2htmlEX. In this way you can cleanly separate the requires of each one, and develop and debug them separately, which can also be nice avoiding many unnecessary rebuilds from source of a part that already works. The thing is that ``poppler`` itself might need some patches and other stuff to be able to build it correctly and requiring ``"freetype/2.10.4", "fontconfig/2.13.93", "cairo/1.17.2", "libjpeg/9d", "libpng/1.6.37", "boost/1.76.0", "zlib/1.2.11",``, so all of this is better handled in its own place.

> Thank you for that insight! As a first step I will just put it on a custom server and try to get everything up and running.

Yes, that sounds the best approach atm. :)

**Comment by memsharded** [comment] 2021-12-21 12:42
Oh, furthermore, I realize that you already have ``poppler`` in conan-center-index. In that sense, it might be easier to tweak it, for example, adding an option ``package_private_for_pdf2`` (just the idea 😅 of the name), and making sure it gets packaged as you need for easy consumption in the other package. This might also increase the chances of future contribution of it to ConanCenter (still challenging, but way easier compared with the vendored approach)

**Comment by andiwand** [comment] 2021-12-21 14:14
@memsharded thank you for the suggestions!

The `CMake` approach sounds most viable for me right now since I will have to adopt the `CMake` anyway.

Separating the packages would be cleaner from the dependency perspective but I am worried about the include paths. I would have to stay consistent with the given structure of the source directory if I don't want to rewrite the `#include` directives. So I have to make sure the absolute includes and relative includes still work correctly.
In the best case I could export the internal headers into something like `somewhere/include/poppler/internal` which can then be added to the include path.

**Comment by memsharded** [comment] 2021-12-21 18:00
> The CMake approach sounds most viable for me right now since I will have to adopt the CMake anyway.

Adopting CMake doesnt really necessarily mean to do a single build of the project + vendored poppler and fontforge. You might adopt CMake for the builds, but still have separated packages (and connect them via CMake find_package() for example)

> Separating the packages would be cleaner from the dependency perspective but I am worried about the include paths. I would have to stay consistent with the given structure of the source directory if I don't want to rewrite the #include directives. So I have to make sure the absolute includes and relative includes still work correctly.
In the best case I could export the internal headers into something like somewhere/include/poppler/internal which can then be added to the include path.

Yes, there are several alternatives to approach this (not touching the #includes):

- Apply a patch if necessary to the pdf2 package CMakeLists to "add_include" the right locations for headers
- Do an ``imports()`` in the pdf2 recipe, so it does a local copy of the poppler headers from the package to put them in the right location close to the build (this is what you meant with the export internal headers?)

So if you do like this approach, it might be worth trying. Please let me know how it goes and if you have further questions.

**Comment by andiwand** [comment] 2021-12-21 23:52
@memsharded I just successfully built `pdf2htmlEX` with conan :tada: 

I took your approach and separated the builds into their own packages. I modifies the CMakeLists of `pdf2htmlEX` to work correctly instead of copying the files for now.

For poppler and fontforge I just used `copy` in `package` to grad all the "private" header files and add them to the package.

At the end I had to fight `glib` a little because I was facing a linkage error caused by `libmount` which I removed as a dependency now.

I am just a bit scared by the size of the executable which is 20MB right now. But maybe I can cut it down by disabling unnecessary features.

As a next step I will create a small library in `pdf2htmlEX` that I can package and consume in my original project.

Afterwards I will try to build `pdf2htmlEX` for Android and iOS which will definitely be tricky.

Thank you for your help so far!

**Comment by memsharded** [comment] 2021-12-22 00:20
> @memsharded I just successfully built pdf2htmlEX with conan 🎉

So happy to hear that! 🎉 😃 

> As a next step I will create a small library in pdf2htmlEX that I can package and consume in my original project.

> Afterwards I will try to build pdf2htmlEX for Android and iOS which will definitely be tricky.

Yes, but at least it might be easier to approach this one dependency at a time. The recipes from ConanCenter are using the previous integrations, but the future ones, like ``CMakeToolchain``, that will be the ones in 2.0, contains some better built-in integration for Android, for example, and the idea is that it also does for iOS. Might be worth keeping an eye on it.


If the original question has been addressed (it seems so if you were successful), I think this issue can be closed. Don't hesitate to open new issues for any further questions. Thanks!

**Comment by s-geiger-si** [comment] 2024-11-11 20:33
I have exactly this use case. I would like to be able to build code that is being generated with the OpenAPI generator which I invoke via Conan. The issue is that the `openapi-generator` produces a folder tree that contains a pretty-much self contained CMake project. While we can add it via `add_subdirectory` to the main project, this has a couple of issues and I feel its not the cleanest approach to do this. A better solution would be to configure and build the openapi generated code as a separate step, install it into a `CMAKE_PREFIX_PATH` and then use `find_package` from the main project to resolve it. The openapi generated code only produces static libraries which are being consumed in the main project, so I do not need to create a Conan package from them. Currently I have not found a way to do this, because `CMakeToolchain`, and `CMake` assume that a single build is happening.

What I would like to do is:

1. Install conan dependencies
2. Generate OpenAPI stubs with the openapi-generator
3. Build each of the generated folders and install them via a separate CMake build tree (which can be private to conan)
4. Configure the main project and add the install tree to the `CMAKE_PREFIX_PATH`
5. Build the main project and proceed to install/package it.

Further background can be found here: https://stackoverflow.com/questions/78361333/integrate-openapi-generate-with-conan-2-and-cmake-with-proper-caching

**Comment by memsharded** [comment] 2024-11-11 21:01
Hi @s-geiger-si and @andiwand 

First it seems this issue should have been closed back then

> If the original question has been addressed (it seems so if you were successful), I think this issue can be closed. Don't hesitate to open new issues for any further questions. Thanks!

Also, I'd like to update, because many things have changed since then, including Conan 2, and it has new functionalities like the ``vendor=True``, see https://blog.conan.io/2024/07/09/Introducing-vendoring-packages.html, which can really help in the approach @andiwand was describing above using different packages.


> Currently I have not found a way to do this, because CMakeToolchain, and CMake assume that a single build is happening.

@s-geiger-si it would be good to understand why a different toolchain would be necessary. How this would be managed without Conan? Isn't it possible to do it with CMake only then?

Have you tried just calling ``self.run("cmake .... )`` directly for the subprojects? The ``CMake(self)`` is a relatively thin wrapper, and regarding the toolchain, still need to understand what toolchain would be use to build these libraries, why the same toolchain wouldn't be the right one.

As this ticket should have been closed, as the OP succesfully managed to do what they wanted, this could be a different use case (as it seems that using different packages is not a possibility in your case), I think it would be better to close this ticket and open a new, fresh ticket with the details.

**Comment by andiwand** [comment] 2024-11-13 18:08
From my side this can be closed - Thanks again @memsharded !

**Comment by memsharded** [comment] 2024-11-13 19:31
Sounds good, thanks for the feedback @andiwand!

Closing the ticket then, and we can follow up the other idea for @s-geiger-si in https://github.com/conan-io/conan/issues/17303

**Closed as completed by memsharded** 2024-11-13 19:31 UTC
Labels: type: question
