### ISSUE TITLE
Using conan with ninja results in strange link errors

### ISSUE THREAD

**Issue by mcraveiro** [conan-io/conan#56] opened 2015-12-22 22:59 UTC
Hi,

Thanks very much for all your work with conan. I am using it on Linux (debian testing x64). I've successfully updated my project to use conan[1] but for some reason I'm unable to build using ninja[2]. I'm wondering if I've done something wrong.

The steps to reproduce using my project are as follows (assuming you have libxml dev headers):

```
$ git clone https://github.com/DomainDrivenConsulting/dogen.git
$ cd dogen/build
$ mkdir output
$ cd output
$ conan install ../..
$ cmake ../.. -G Ninja
$ ninja -j5
<snip>
$ ninja: error: '~/.conan/data/Boost/1.60.0/lasote/stable/package/ebdc9c0c0164b54c29125127c75297f6607946c5/lib/libboost_system.so', needed by 'stage/bin/dogen_utility_spec', missing and no known rule to make it
```

This error is rather puzzling because I can see boost system in the filesystem and it looks perfectly fine. I can use ninja without conan, but unfortunately I have boost 1.59 on my system, so it's not a perfect comparison. Also, when using GNU make with exactly the same conan settings, the project compiles and runs fine.

The error appears to be some kind of weird interaction between conan, cmake and ninja, but not quite sure who to blame. It could be something as simple as the library path not being passed in all the way to ninja, I guess. When I get more time I will try to create a small program that triggers this behaviour.

In the meantime, any ideas on how to debug this problem are welcome. 

Cheers

Marco

[1] http://mcraveiro.blogspot.co.uk/2015/12/nerd-food-dogen-package-management-saga.html
[2] https://ninja-build.org/manual.html

**Comment by memsharded** [comment] 2015-12-23 18:51
Hi Marco,

The truth is that we have still not tested the system with Ninja, and I have no idea why it could be failing, but Ninja is a great tool, so I'll have a look when possible, thanks for reporting the issue.

**Comment by memsharded** [comment] 2015-12-24 01:23
First try of pet project (both package and consumer), consumer with Ninja generated with CMake 3.4, gcc 4.8, in win7, works fine. Just wanted to try things in win first (it is the computer I have right now, I'll have my linux box from 26th, will check your project then)

**Comment by memsharded** [comment] 2015-12-29 00:30
I have been able to reproduce the failure in Ubuntu 14.04. I have tried to build the project with Make, but got build error:

```
/home/memsharded/dogen/projects/yarn.dia/src/types/grapher.cpp:90:63:   required from here
/usr/include/c++/4.9/ext/new_allocator.h:120:4: error: use of deleted function ‘boost::detail::stored_edge_property<long unsigned int, boost::no_property>::stored_edge_property(const boost::detail::stored_edge_property<long unsigned int, boost::no_property>&)’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /home/memsharded/.conan/data/Boost/1.60.0/lasote/stable/package/61e9701d8417a95a3264062633f910fdd015d633/include/boost/graph/adjacency_list.hpp:246:0,
                 from /home/memsharded/dogen/projects/yarn.dia/include/dogen/yarn.dia/types/grapher.hpp:31,
                 from /home/memsharded/dogen/projects/yarn.dia/src/types/grapher.cpp:29:
/home/memsharded/.conan/data/Boost/1.60.0/lasote/stable/package/61e9701d8417a95a3264062633f910fdd015d633/include/boost/graph/detail/adjacency_list.hpp:290:11: note: ‘boost::detail::stored_edge_property<long unsigned int, boost::no_property>::stored_edge_property(const boost::detail::stored_edge_property<long unsigned int, boost::no_property>&)’ is implicitly declared as deleted because ‘boost::detail::stored_edge_property<long unsigned int, boost::no_property>’ declares a move constructor or move assignment operator
     class stored_edge_property : public stored_edge<Vertex> {
           ^
make[2]: *** [projects/yarn.dia/src/CMakeFiles/yarn_dia.dir/types/grapher.cpp.o] Error 1
```

I am building with cmake 3.4.1, gcc 4.9.3, conan 0.5 (and Boost 1.60, as required in the cloned repo). I'd like to be able to build it properly using make, to be able to isolate the problem, any idea about this failure would be great.

**Comment by mcraveiro** [comment] 2015-12-29 19:20
Thanks very much for your effort. The reason why it fails to build is, unfortunately, due to a bug in Boost Graph :-( You can find details about it on my blog post[1] but the TL;DR of it is that you need to apply the patch we carry[2] to the conan checkout of boost. This is done on our travis CI in a somewhat hacky way but seems to do the trick[3]. Here's the useful parts of that file:

```
 - conan install ${GIT_REPO}
  - hash=`ls ~/.conan/data/Boost/1.60.0/lasote/stable/package/`
  - cd ~/.conan/data/Boost/1.60.0/lasote/stable/package/${hash}/include/
  - sudo patch -p0 < ${GIT_REPO}/patches/boost_1_59_graph.patch  
  # FIXME: ninja borked with conan for some reason.
  # - cmake ${GIT_REPO} -DWITH_MINIMAL_PACKAGING=on -G Ninja
  # - ninja -j2 package run_all_specs
  - cmake ${GIT_REPO} -DWITH_MINIMAL_PACKAGING=on
  - make -j2 run_all_specs
```

The patch says 1.59 but it works out of the box for 1.60 too. Let me know if there is a more idiomatic way to do this in conan (finding the conan directory, the hash directory, etc).

Cheers

marco

[1] http://mcraveiro.blogspot.co.uk/
[2] https://github.com/DomainDrivenConsulting/dogen/blob/master/patches/boost_1_59_graph.patch
[3] https://github.com/DomainDrivenConsulting/dogen/blob/master/.travis.yml

**Comment by memsharded** [comment] 2016-01-07 12:10
Just to keep you updated, I have been working on it, tried many things, but still nothing. It is something really weird, it seems could be related to libs ordering, but really no real clue. I keep trying.

**Comment by mcraveiro** [comment] 2016-01-07 22:45
No problems. Thanks for the hard work!

**Comment by memsharded** [comment] 2016-11-06 22:59
Hi Marco,
We have recently addressed some other Ninja related issues in #556, and we have been reported some other users successfully using Ninja too since this issue was opened. Is this still an issue? Could you please try it again for your use case with the latest conan and report? Thanks for the feedback!

**Comment by mcraveiro** [comment] 2016-11-06 23:43
Hi @memsharded,

will give that a spin tomorrow and report.

Cheers

**Comment by mcraveiro** [comment] 2016-11-07 10:02
Actually @memsharded, I just realised that a while ago I ran into some problems with Boost on Conan - can't quite remember the details; but the long and short of it was that I ended up removing Conan for my Linux build because I didn't have the time to look into the issues properly :-( so I am only using Conan on Windows with VS - i.e. no make/Ninja. I'm not sure when I will have the time to reactivate Conan on Linux, but when I do I will look into using Ninja.

**Comment by memsharded** [comment] 2016-11-07 10:27
Ok, no worries. I will close this issue then, until we have further actionable insights, please re-open it or comment the minute you want to resume conan usage on Linux or need any help regarding this potential issue. Thanks!

**Closed by memsharded** 2016-11-07 10:27 UTC

**Comment by dyu** [comment] 2017-02-21 15:51
I can confirm using ```conan + cmake -GNinja ``` on linux works (following http://docs.conan.io/en/latest/getting_started.html)

But ```conan + cmake -GNinja``` on windows does not work.
Only ```-G "Visual Studio 14 Win64"``` works.  Is this a known limitation?

**Comment by memsharded** [comment] 2017-02-21 16:38
I guess it is something related to the environment, which compiler will use the Ninja build system? How do you specify it? What are your settings?

Basically, conan does not do magic with the build system. The ``CMake`` helper is just a thin layer that helps to translate from conan settings to cmake variables, but you can directly invoke it or add arguments as needed. 

If you have a test project, I can try to have a look.

**Comment by dyu** [comment] 2017-02-21 17:31
On windows:
```
git clone https://github.com/memsharded/example-poco-timer.git mytimer
cd mytimer
mkdir build
cd build
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
conan install ..
cmake -GNinja ..
ninja
```
That fails.

Replace the last 2 lines with:
```
cmake .. -G "Visual Studio 14 Win64"
cmake --build . --config Release
```
This works.

Note that I've tested ninja using the same VS 14 compiler on [other](https://github.com/jimporter/bfg9000) ninja-based build systems and it worked well.

**Comment by memsharded** [comment] 2017-02-21 17:58
You might need to specify Ninja the build type:

```bash
cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release
```
Otherwise Ninja will assume debug. Note that Ninja is more like Make, is a single-configuration build system, and you have to specify it that way (to match the installed dependencies).

I have tried in my machine and this worked, please try and tell me. Thanks for your feedback!

**Comment by dyu** [comment] 2017-02-21 18:13
That works :+1: 
Any particular reason why non-release build does not work?

Thanks for the quick turnaround!

**Comment by dyu** [comment] 2017-02-21 18:17
For what its worth, ```cmake --build .``` also fails.
As well as ```cmake --build . --config Debug```

**Comment by memsharded** [comment] 2017-02-21 18:20
You should install the debug packages for the dependencies:
```bash
$ conan install -s compiler="Visual Studio" -s compiler.runtime=MDd -s build_type=Debug
```

**Comment by dyu** [comment] 2017-02-21 18:27
Thanks again!  I appreciate your help.
