### ISSUE TITLE
Rebuilding and creation of dependent Conan packages downstream?

### ISSUE THREAD

**Issue by mkjkec2005** [conan-io/conan#12950] opened 2023-01-23 12:48 UTC
### What is your question?

Consider the use case where we change the logger component, which is a commonly used library,
It will trigger a rebuild of multiple packages downstream. How do we achieve this rebuild? i.e. how the framework will know 
which all downstream packages are dependent on Logger?

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-01-23 13:09
Hi @mkjkec2005 

You can find some hints about how this problem can be approached with a package manager in: https://docs.conan.io/en/latest/versioning/lockfiles/ci.html

The first important bit is that a package manager is not a build system, and it doesn't handle a monolithic build of a product. Then the important bits are:

- Building a package when something changes is relatively easy: ``conan create`` for the different configurations, upload packages to server, done. We call this the "package pipeline".
- The inverse dependency problem, lets say "who is consuming a given package" is an intractable problem in practice. Often, packages are in different server repositories, for example, it is normal to have a "third-party" repo for all the open source third-party, and your own "develop" server repo to store your own binaries for your own code. These repo might be even geographically distributed, the third-parties might be serving to the whole company from one location, while your own "develop" one is probably closer to your own team location.
- Not only because server side or infrastructure, but also because exponential explosion of consumers. Lets say that we have ``pkga/1.0#rev1``, a very stable base library that many of my other packages depend on. So in the last month I created ``pkgb/1.0``, ``pkgb/1.1``, ``pkgb/1.2``, ....``pkgb/1.13``, and similarly for others ``pkgc``, and ``pkgd``. Now we have a final application that evolves rapidly, integrating changes from the different ``pkgb``, ``pkgc`` and ``pkgd``, and it creates many ``app/1.0.1``-``app/1.0.24``, and ``app/1.1.1``-``app/1.1.18``. Now you have tons of packages that depend on the same ``pkga/1.0#rev1``. Asking "who are the consumers of ``pkga/1.0#rev1``" is useless, because we are most likely not interested not even capable of rebuilding all the consumers that depend on it.
- Saying: "just the latest versions" of the consumers is also not enough, it is very common that several versions of ``app`` has to be maintained for customers, and also that there are versions of the different packages ``pkgb-d`` that haven't been integrated yet into the final ``app``.
- So the problem is basically defining what are the important product versions that we want to maintain and integrate changes, this is the "products pipeline". The products pipeline builds the dependency graph from a given set of final products versions, and those dependency graph contains all the information necessary to know what needs to be built and what not, and in what order.

Note: this process will be very improved in Conan 2.0 with some better commands and interfaces, and also with very simplified lockfiles. Still, the overall approach is similar, and the "products pipeline" is the right approach to the problem.

**Comment by memsharded** [comment] 2023-11-05 16:44
Closing this question as responded. Please do not hesitate to open new issues for any further follow up or question you might have.

**Closed as completed by memsharded** 2023-11-05 16:44 UTC
Labels: type: question
