### ISSUE TITLE
[question] How to best package internal dependencies for use by external developers

### ISSUE THREAD

**Issue by creiter64** [conan-io/conan#14769] opened 2023-09-18 14:05 UTC
### What is your question?

Hi everybody,

We're using conan and Artifactory for internal software development. We now want to outsource some of the work and need a way to distribute the dependencies from our internal Artifactory instance in a way that is compatible with the existing build scripts built around conan.

I'm now looking for a way to transfer the build dependencies of our main application in binary form to our external developers so that they can further develop the main application.

### I can't

- Make the Artifactory server available to the external team
- Share the source code of the dependencies of our main application

Mostly because of concerns around security/intellectual property.

### I can
- Modify the conan packages as needed
- Share the source code of the main application with the external team

### What I'm looking for is

- A way to use conan to combine all dependencies and transistive dependencies of a given build configuration into an archive (e.g. zip file)
- Share this archive with our external team (E.g. USB-Stick, E-Mail, FTP)
- A command that lets the external team import the dependencies and build the main application from source

Can I just move the content of my fresh conan home to the external team to achieve this effect?
Does anyone have any other idea how I could achieve that?

### Notes
It seems that https://github.com/conan-io/conan/issues/2197 was also going in that direction, but was closed due to resource constraints. In my case the dependencies are only a few MB so I don't think that's problematic at all.

Currently my projects are at conan 1.6, but it shouldn't be a problem to move to 2.0 if it's easier to get that working there.

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-09-18 15:32
Hi @creiter64 

Thanks for your question

> A way to use conan to combine all dependencies and transistive dependencies of a given build configuration into an archive (e.g. zip file)
Share this archive with our external team (E.g. USB-Stick, E-Mail, FTP)

At the moment there is no way to do this in this way, but there are some possibilities planned for the 2.X roadmap, like this https://github.com/conan-io/conan/issues/10740. Being in the 2.X roadmap it means that we will start prioritizing this once the 2.0.X stabilization finishes.

I'd like to still ask why there are no other options possible, like that the external team having their own server (recall that ArtifactoryCE is free, they could host an instance, give you permission, and you could upload directly to their server). That would be extremely beneficial in all regards, convenience, security, possibility to do updates easily, etc. Setting your own server, separated to the main production one, and give them read access is also possible. At the end of the day, doing this will be way more maintainable and secure than transferring them over an FTP or USB stick

> Share the source code of the dependencies of our main application

Sharing the source code shouldn't be an issue, it is possible to do it. The ``scm`` approach can give full reproducibility, but you fully control who has access to your git repos.

**Comment by creiter64** [comment] 2023-09-19 06:38
https://github.com/conan-io/conan/issues/10740 is going in a similar direction what I think would be good.

> I'd like to still ask why there are no other options possible, like that the external team having their own server (recall that ArtifactoryCE is free, they could host an instance, give you permission, and you could upload directly to their server). That would be extremely beneficial in all regards, convenience, security, possibility to do updates easily, etc. Setting your own server, separated to the main production one, and give them read access is also possible. At the end of the day, doing this will be way more maintainable and secure than transferring them over an FTP or USB stick

It mostly boils down to overhead of setting up and running the servers you suggest in a secure way. Nobody in the external team has the skills to do it. Think of the external team as a small contractors with 2-3 people, who are experts at embedded systems, but not in running servers, neither are we. They handle the occassional workpackage for 2-3 months and then we might choose a different one for the next work package.

> At the end of the day, doing this will be way more maintainable and secure than transferring them over an FTP or USB stick

I agree if that would be long term setups, but as outlined above, the situation is a bit different and what matters to us in this case is a simple setup, where we don't have to do much explaining.

I think conan would be the tool best suited to implement such a thing, because it knows exactly what dependencies are needed to transfer and already comes with sort of a local "repository". The only thing I'm missing is to explicitly access that.

As a work around for now, what do you think about sharing the local cache?

**Comment by memsharded** [comment] 2023-09-19 07:28
> As a work around for now, what do you think about sharing the local cache?

This wouldn't be a recommended practice. For example, the local cache has one DB that contains the server JWT auth tokens, so you need to be sure that you are clearing those tokens, at the very least, and also that you are not leaking any other package or source code that could be in the cache as a result of building.

Otherwise, I have done a quick test (in Conan 2.0) to copy the cache to another location and use it, and overall it seems it works. The internal package DB is implemented with relative paths, so this shouldn't be an issue. So maybe you can give it a try (without any guarantee of being supported or that it wouldn't break in the future, for example in one of the next 2.0.X version we will apply a migration to the DB to add a new column, so it will be important to sync the Conan client version).

I haven't tested with 1.X, but it might be possible too. In any case, I'd recommend prioritizing the upgrade to 2.0, as I will also increase the priority over #10740, it might take a while still, but the upgrade to 2.0 can take some time too, so the sooner to start the better.

Thanks for the feedback! (If the cache copy works, lets close this issue, and we can follow up in #10740 )

**Comment by creiter64** [comment] 2023-09-19 07:39
Thank you for your support, I'll report back if the cache copy solution works out for us.

**Comment by memsharded** [comment] 2024-07-29 23:21
I think this can be of interest in this thread: https://blog.conan.io/2024/07/09/Introducing-vendoring-packages.html

Also, Conan learned since then the ``conan cache save/restore`` to move packages into air-gapped environments and similar use cases.

So I think a lot of things have changed since then, and this ticket can be closed as outdated.
Please create new tickets for any further question that you might have. Thanks for the feedback.

**Closed as completed by memsharded** 2024-07-29 23:21 UTC
Labels: stage: triaging
