### ISSUE TITLE
[feature] Project Root folder as default

### ISSUE THREAD

**Issue by divad1196** [conan-io/conan#8962] opened 2021-05-15 21:13 UTC
This opinion is based on my usage of other tools.
I have been searching multiple times and for many hours if those features exists, are planned or exists on issues.
I am sorry if it's already a duplicate.

There are a lot a file created by and for conan. Wouldn't it be better to bundle them in a `conan` folder?

Most commands need to know the path to a file, so i specify my project's root folder.
It would be nice to be able to use by default the root project as for git which goes up the file-tree to find a .git folder.

The package installation works great but all packages are installed globally under `~/.conan/{package}/{version}`.
As python has venv, or npm/yarn use .node_modules folders, I think it should be possible to install it in the project folder

It would be nice to have the `--save` option of npm/yarn to automaticly edit the conanfile.txt

Finally, having a quickstart command that would, given a default generator, create the base structure of the project (CmakeLists.txt with content, conan files, maybe basic gitignore, ...)

Thank you for reading.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-05-17 19:28
Hi @divad1196 

Thanks for the feedback! Let me answer each suggestion

> There are a lot a file created by and for conan. Wouldn't it be better to bundle them in a conan folder?

Yes. In the next conan version, the ``generators_folder`` will be introduced. This will allow specifying where to output files, which can easily be a "conan" subfolder.

Also, some files that are generated now, like conaninfo.txt and conanbuildinfo.txt, that were necessary in the past for some commands, will not longer be generated in Conan 2.0, so less files to clutter the user folder too.

> Most commands need to know the path to a file, so i specify my project's root folder.
It would be nice to be able to use by default the root project as for git which goes up the file-tree to find a .git folder.

We had considered the possibility in the past, but in the end we preferred the python "better explicit than implicit", and provide always the path (not only for the ``install``, but for all commands). As always, this has been a trade-off. The issue is that we have had a bunch of UX issues in the past because of Conan trying to be smart in similar ways, and guess about this kind of things. In this case, for example, users some times have different conanfiles in their hierarchy, a common example is the conanfile in ``test_package/conanfile.py``, and it seems that commands inside that folder will still want to refer to the parent conanfile.py, not that one, as that one is invalid without the parent. So that would be a confusing case. There are also users that put their conanfiles not in the root of the project, but in a subfolder, so for them, it will not work that way. It is also possible to use custom filenames, like ``myconanfile.txt``, yet another case that will not work. So at the moment we prefer the uniformity of all commands having explicit paths to the conanfiles.

> The package installation works great but all packages are installed globally under ~/.conan/{package}/{version}.
As python has venv, or npm/yarn use .node_modules folders, I think it should be possible to install it in the project folder

You can define your packages cache to point to whatever location you want, including a "deps" folder for example in your current project, with the CONAN_USER_HOME env-var. In fact this is very recommended, practically mandatory in CI servers, as the cache is not designed for concurrency, and different CI parallel jobs sharing the same cache will be problematic.

> It would be nice to have the --save option of npm/yarn to automaticly edit the conanfile.txt

Yes, yet another UX trade-off that was discarded, the ``conanfile.txt`` is used in a reduced number of cases, and users quickly evolve to conanfile.py, which we certainly will not be editing automatically. So that functionality will only be partial. We specially don't want to define features that quickly go down the rabbit hole. Once you have that ``--save`` for a ``[requires]``, then we probably will need to have UI command line switches to save [options], [build_requires], and other stuff, automatically in the ``conanfile.txt``, but also only in some cases, so maybe ``--save-requires``, ``--save-options``, etc. Those command line switches will add to the ``conan install`` cli, that already has a bunch of them. Here we also adhere to the "have only one way to do things". As the canonical, necessary flow is to edit the ``conanfile.txt`` manually and then ``conan install``, we are certainly not providing a set of extra command line options to edit a text file in its different options.  We already did that in some cases, like profiles and config, and some of that might be deprecated in Conan 2.0.

> Finally, having a quickstart command that would, given a default generator, create the base structure of the project (CmakeLists.txt with content, conan files, maybe basic gitignore, ...)

Have you tried the ``new`` command? Just try:

```bash
conan new hello/0.1 -s -t
conan create .
```

Or using modern (experimental) integrations:
```bash
conan new hello/0.1  -m=v2_cmake
conan create .
```
The ``new`` command has a lot of options, and it can also be templatized, using arguments, and the templates can be shared with your team with ``conan config install`` command (which is also recommended to share profiles, remotes and configs)

**Comment by divad1196** [comment] 2021-05-17 21:30
Hi @memsharded and thanks for the quick and complete response!

I first need to apology for the new command that i probably missed. I was certain i had tried all current features of the cli.

I understand the "explicit" and "freedom" advantage of always having to precise the path. This is the way C++ has always worked. But don't you think this can be a burden too?

My thought was that the biggest problem with C++ was the desparity of project handling: many tools because of many ways of doing things. So having no defaults enforce this disparity.

As an example, i never saw someone complaing for .git in their project root folder. When using submodules i can still use -C option or even loop over submodules.

Conan can handle multiple things, and i agree that it shouldn't try to edit a python file, but it could edit an ini/json/yaml file which could be used together with the python file. In addition to completion and search, this help not to reinvent the wheel. We don't need to provide a command for everything: if the installation is standardized and the dependencies respected, wouldn't a mere ini file (as the pip requirement.txt) be enough to save the dependencies? We wouldn't need this option to be supported in the python file.

I am pretty sure you already considered those points, i just wanted to express my concern about the fact that, IMHO, the problems we are facing exist because we don't want a default, and thus we loose lot of other tools' beloved features.

I think this issue can be closed, i am looking forward for future changes.
Thank you for you consideration.

Also, i saw other issue about completion and that you are using argparse for your cli. I was using it too but switched to python click then typer which is a superset of click. It easily provides cross-shell completions and features.

Have a nice day.

**Comment by memsharded** [comment] 2024-03-17 23:24
Conan new features, like ``layout()``, the removal of generation of files, etc might improve over this.
Closing this as solved.

**Closed as completed by memsharded** 2024-03-17 23:24 UTC
Labels: type: question, stage: triaging
