### ISSUE TITLE
Report warnings for conflicting versions of build_requires and regular requires

### ISSUE THREAD

**Issue by memsharded** [conan-io/conan#3949] opened 2018-11-16 13:26 UTC
It is possible that:

- A -> (build_requires) -> B -> C1.0
- A -> (requires) -> C2.0

A ``deps_cpp_info`` will be collecting information from two different versions of C, C2.0 and C1.0 that are conflicting, one might overwrite the other in ``deps_cpp_info``. The build_requires one (in this case, the C1.0 one) is the one that is getting selected (applied latest). At least, it should output a warning of this conflict.

cc/ @dodoent

**Comment by sunj1** [comment] 2018-11-19 05:14
This is the same behavior as mentioned in #3900 which I had reported.

**Comment by DoDoENT** [comment] 2018-11-20 19:33
Here is the project that demonstrates the issue: 
[build_requires.zip](https://github.com/conan-io/conan/files/2601201/build_requires.zip)


The `Aaa` is a utility library (let's say it's a threading library) that is used both by `Bbb`, which serves as a testing framework and `Ccc`, which is a library that uses `Aaa` directly and also uses `Bbb` for its unit testing.

Therefore, `Ccc` has `build_requires` to `Bbb` and `requires` to `Aaa`. However, since `Bbb` requires older version of `Aaa` than `Ccc` and is within `build_requires` clause, it overwrites `Ccc's` `Aaa`, causing it to use wrong version.

### Reproducing

- unzip the attached file
- `cd Aaa`
- update `conanfile.py` to use `version = 1.0.0` and create package with `conan create . user/testing`
- update `conanfile.py` to use `version = 1.1.0` and create package with `conan create . user/testing`
- `cd ../Bbb`
- `conan create . user/testing`
- create a new build folder
- `conan install /path/to/Ccc'
- `cmake /path/to/Ccc`
- `cmake --build /path/to/Ccc`
- run `/path/to/build/folder/bin/Ccc_Test`

### Expected

Printouts `This is Aaa version 1.1.0`.

### Actual

Printouts `This is Aaa version 1.0.0`.


I understand that there are use cases when observed behaviour is desired, however in this case `Ccc` gets `Aaa v1.0.0`, although it explicitly stated that it wants v1.1.0 in its conanfile. This is very confusing, especially to developers that are less experienced with conan.

When performing `conan install /path/to/Ccc`, I would at least expect a gentle warning that there is a conflict in versions of `Aaa` library between `build_requires` and `requires` graph. Ideally, that should be an error just like in the case of conflict within the `requires` graph, which would need to be resolved with something like `build_requires = ('Aaa/1.1.0@user/testing', 'override')`, just like in the case of `requires` graph.

The main problem here is actually that a testing framework `Bbb` is used within `build_requires` clause of the `Ccc` conanfile, but this requirement is required only when actually building unit tests for `Ccc`, but not for the `Ccc` itself. Therefore, when some hypothetical `Ddd` package needs to build `Ccc` by dependency, it does not need to fetch `Bbb` nor build `Ccc's` unit test.

**Comment by memsharded** [comment] 2019-02-26 12:48
We have analyzed this and it is not only a bug, but also a very important bug which could have bad effects that pass unnoticed and then they are later much more difficult to debug.

So in https://github.com/conan-io/conan/pull/4514 we are proposing a new, more complete and thorough graph resolution for build requires and private dependencies

**Comment by DoDoENT** [comment] 2019-02-26 13:35
> We have analyzed this and it is not only a bug, but also a very important bug which could have bad effects that pass unnoticed and then they are later much more difficult to debug.

This is basically what my colleague and I were trying to explain to you in person on Meeting C++ in Berlin. Thank you for taking care of this.

I also hope that you will come to the same conclusion also for [this issue](https://github.com/conan-io/conan/issues/4038) - it makes our life painful as much as this issue does.

**Closed** 2019-03-06 11:49 UTC
Labels: complex: high, priority: high, stage: review, type: bug

**Comment by memsharded** [comment] 2019-03-06 12:26
Hi @DoDoENT 

This has been merged, so it will be released in Conan 1.13. Looking forward your feedback.

An important thing to notice is that conflicts in build_requires now also raise an error, a "conflicting" error. It is not allowed that 2 different versions or configurations of the same package end in the same ``deps_cpp_info`` structure (one overwriting the other), so if this happens, an error will be raised.

The logical way to define the dependencies when this happens and the transitive dependencies of the ``build_requires`` shouldn't affect the consumer package is to also convert those transitive dependencies to ``build_requires`` themselves.

For #4038, indeed we will carefully consider it, but that one seems more difficult without breaking something, so might need to wait until Conan 2.0.

**Comment by DoDoENT** [comment] 2019-03-06 13:27
Thank you @memsharded. I am looking forward to Conan 1.13.

**Comment by DoDoENT** [comment] 2019-03-15 16:23
Although reporting the conflicting error is required, we also need a way to resolve the conflict, but that does not seem possible with conan v1.13.1. I've reported a new issue as #4753.
