### ISSUE TITLE
[feature] Make it possible to install Conan if not running elevated

### ISSUE THREAD

**Issue by exoosh** [conan-io/conan#16979] opened 2024-09-11 15:39 UTC
### What is your suggestion?

Hi, I tried installing Conan via `winget` with `--scope user`, but it fails.

It would be great it — when run as unprivileged user or without elevation — the installer simply would install the program into `%LOCALAPPDATA%\Programs`.

Examples of programs that do it this way include Python itself or VSCodium and (I think) VSCode.

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2024-09-11 23:13
Hi @exoosh 

Thanks for your suggestion.
The problem is that we are not creating or maintaining the ``winget`` Conan installer, so I am afraid we cannot do any changes to it, maybe this is something to request in other place?

**Comment by exoosh** [comment] 2024-09-12 07:21
Hi @memsharded , but you are 😉

You may mistake it for Scoop which indeed rolls its own wrappers/modifications for installers. WinGet only ever takes the installers from the download area of whatever the respective vendor provides (here GitHub release page) and makes it available. In fact I was the one to create the [PR for Conan 2.7.0](https://github.com/microsoft/winget-pkgs/pull/171158), although I intend to automate this subsequently so hopefully the process can be automated some time in the future.

So I am talking about the installers you provide [here](https://github.com/conan-io/conan/releases). No changes. Verbatim.

If you could give me some pointers how it gets created, I'll be happy to have a look around. I found some mentions of PyInstaller, but am unsure if that's what essentially bundles up the `conan.exe` and `_internal` directory you release — whereas Conan when installed by `pip` uses the respective Python instance — or whether (as the name suggests) it's the actual installer that it also creates.

PS: just also created ~~[the PR for Conan 2.7.1](https://github.com/microsoft/winget-pkgs/pull/172970)~~ (replaced by [this PR](https://github.com/microsoft/winget-pkgs/pull/172997))

**Comment by memsharded** [comment] 2024-09-12 12:53
Oh, I see, thanks for the clarification @exoosh I didn't know that winget directly use our installers.
@czoido will follow up, thanks.

**Comment by czoido** [comment] 2024-09-12 12:54
Hi @exoosh,

Thanks for reporting. I'm assigning this to 2.8.0 for this release we will try to create an installer that does not require elevation. That will probably be in the end of the month. I'll keep you updated.

**Comment by exoosh** [comment] 2024-09-12 13:37
If there is anything I can lend a hand with, let me know.

**Comment by czoido** [comment] 2024-09-13 04:57
Hi @exoosh,
I have been doing some tests and can confirm that the new Windows installers that we are generating for Conan 2.8.0 do not require an elevated or privileged user. 
I'm closing this, but please feel free to reopen or open a new issue if you find any problems with the installers once we release 2.8.0.
Thanks a lot!

**Closed as completed by czoido** 2024-09-13 04:57 UTC
Labels: type: feature

**Comment by exoosh** [comment] 2024-09-13 09:04
@czoido thanks so much!

**Comment by czoido** [comment] 2024-09-30 14:53
Hi @exoosh, we have just released [Conan 2.8.0](https://github.com/conan-io/conan/releases/tag/2.8.0) with the changes applied to the Windows Installer, please have a look if that's working fine for you. Thanks!

**Comment by exoosh** [comment] 2024-10-07 09:30
I'll have a look, thanks.

**Comment by exoosh** [comment] 2024-10-07 10:47
@czoido I tested it from non-elevated context and it worked like a charm. [The PR for `winget-pkgs`](https://github.com/microsoft/winget-pkgs/pull/179052) is also pending.
