### ISSUE TITLE
new feature request: tools.unzip support .7z file

### ISSUE THREAD

**Issue by zhongpan** [conan-io/conan#3287] opened 2018-07-28 08:51 UTC
ATT.Thanks.

**Comment by Croydon** [comment] 2018-07-29 20:39
Duplicate of #52

**Comment by lasote** [comment] 2018-07-30 07:38
7z is proprietary and doesn't have adequate python support.
Since Conan 1.6, xz files are supported but only with Python 3 & lzma support enabled. Python 2 raise an error (and Python 2 will be deprecated anyway)

**Closed** 2018-07-30 07:38 UTC
Labels: wontfix

**Comment by rconde01** [comment] 2021-12-14 20:36
If the recipe won't go on CCI, then here's a potential solution:
```
from conans import ConanFile, tools
import os

class MyPkgConan(ConanFile):
    name="pkg"
    version = "1.0"

    def system_requirements(self):
        import pip
        pip.main(["install","py7zr"])

    def source(self):
        import py7zr
        tools.download("https://somewhere.com/some_file.7z","some_file.7z")
        with py7zr.SevenZipFile("./some_file.7z", mode='r') as z:
            z.extractall()
        os.unlink("./some_file.7z")

```

**Comment by memsharded** [comment] 2021-12-14 21:23
But @rconde01, 7zip has already been in ConanCenter for a while: https://conan.io/center/7zip, and I think there are already other packages in ConanCenter that use it as build-require

**Comment by rconde01** [comment] 2021-12-14 21:25
fair - it's probably the better way.
