### ISSUE TITLE
[question] Native build

### ISSUE THREAD

**Issue by w3sip** [conan-io/conan#9901] opened 2021-10-28 19:48 UTC
Would you consider

```conan create . Proj/1.0@org/local -pr profile```

and 

```conan create . Proj/1.0@org/local -pr:h profile -pr:b profile```

identical commands? I'm seeing differences in behavior, and wonder if it is by design, or a bug.

- [x] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by memsharded** [comment] 2021-10-28 21:24
It is completely by design. Specifying the "build" profile is the opt-in we have defined to activate a new graph resolution that defines the "build" and "host" contexts, and indeed, the resulting graph can be different, the propagated information will be different. This was necessary to avoid breaking, as this is changing behavior

Conan 2.0 will also use the new mode by default, when you don't pass the 2 profiles it will use the default one for both build and host profiles.

**Comment by memsharded** [comment] 2024-10-06 21:23
Conan 2 implemented the 2 profiles by default, now ``conan create . Proj/1.0@org/local -pr profile`` and ``conan create . Proj/1.0@org/local -pr profile -pr:b=default`` are identical behavior.

Closing as responded back then, but please don't hesitate to create new tickets if you have any further question. Thanks for your feedback.

**Closed as completed by memsharded** 2024-10-06 21:23 UTC
Labels: type: question
