### ISSUE TITLE
[question] do not save username and password in exported scm object

### ISSUE THREAD

**Issue by boussaffawalid** [conan-io/conan#6275] opened 2019-12-25 19:33 UTC
We are used the scm object as bellow:
```
scm = {
        'type': 'git',
        'url': 'auto',
        'revision': 'auto',
        'username': tools.get_env("GIT_USERNAME", None),
        'password': tools.get_env("GIT_PASSWORD", None)
}
```

In CI we set the env var GIT_USERNAME and GIT_PASSWORD, however we noticed that the actual username and password got replaced and exported as part of the recipe.
This is not convenient at all as everyone now have access to the CI git credentials. 

Any suggestion on how to deal with this ? 
Ideally, username and password should be only read from env var if defined.

Thanks,
Walid
 

- [ ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by danimtb** [comment] 2019-12-26 10:49
This is done to make the recipe reproducible whenever you want to create a new package using that recipe. However, if you are managing the permissions to the source repo for each user you can always omit the username and password fields and set them in git in a previous step to the `conan create` command with something like:

```
git config credential.https://github.com.username $GIT_USER
```

**Comment by memsharded** [comment] 2019-12-29 23:21
I think this is an issue, at least it should be documented and warned that this is happening, otherwise user/password from packages will be captured in plain text in recipes.

I would also agree that once you need to rely on some external definition of credentials, like an env-var GIT_USERNAME, then it might make more sense to use some git "native" solution. What do you think @boussaffawalid ?

**Comment by boussaffawalid** [comment] 2019-12-30 08:23
Honestly, I was paranoid when I realised that some of our critical credentials are saved in plain text in artifactory.

@memsharded  I dont really agree, from my perspective the env variables GIT_USERNAME should be evaluated when building the package instead of caching the user/password.

Something like:
* If the env variables are defined, use them.
* if not, just default to git native". In other words if there are some saved credentials in the machine, git will use them otherwise git will prompt the user to provide user/password.

**Comment by niosHD** [comment] 2020-01-07 10:19
For reference, I stumbled across the same issue (#3183, old POC for `expand` idea: #3255) when I started to use the scm feature. However, I eventually gave up and went with the git native solution for authentication.

To be perfectly honest, I am still not really sure if rewriting the recipe, like it is done for the scm field, is a good idea at all. Furthermore, fwiw, if rewriting is really desired, I am convinced that scm is only a special case that should be replaced by a more generic approach for capturing data (#3338).

**Comment by jgsogo** [comment] 2020-01-10 10:57
Hello, everyone. Here it is the proposal:

We are going to introduce an **opt-in for Conan v1.22** (it could be the default behavior for Conan v2) following these directions:
 * If not set, the behavior will be the same as it is now (Conan v1), all SCM fields will be evaluated and written to the recipe.
 * If set:
   + the recipe won't be modified, it will be exported as it is, no substitution.
   + all the evaluated fields (except `username` and `password`) will be stored in the [`conandata.yml` file](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html?highlight=conandata%20yml). Conan will perform this action during `export`, it will create a new file or modify/append to it if it's already available. Note.- This action will be done only if one of the fields evaluates to `"auto"` which is the keyword that is currently triggering the substitution.
   + when using the recipe, Conan will load the `conanfile.py` (it evaluates all the source code in the recipe) and update the SCM fields with those read from `conandata.yml`

The file `conandata.yml` is taken into account to compute the recipe revision and it is sent to the server in the `conan_export.tgz` file together with those declared in the [`export` field](https://docs.conan.io/en/latest/reference/config_files/conandata.yml.html?highlight=conandata%20yml).

**Comment by niosHD** [comment] 2020-01-13 15:29
Thank you @jgsogo for working on this! I wasn't even aware that `conandata.yml` already exists. Apparently I missed it in the change logs.

Am I correct in assuming that currently the user has to provide `conandata.yml` manually and that the `conan_data` attribute is a read-only view on that file? Do you guys plan to extend that support for writing to the attribute as well?

The proposal itself sounds interesting and definitely improves on the status quo by providing an escape hatch. However, I am not sure if the resulting behavior is too confusing for users. In particular, when reading a `conanfile.py`, there is no distinction between fields that get captured implicitly and fields that are not. The user has to be aware of the special behavior for certain fields (which requires reading the documentation), in addition to the current configuration in `conan.conf`, to figure out what is happening.

To a certain degree, we already have this confusing situation with the `auto` values for the `revision` and `url` fields as well as the dirty repositories but I fear that, over time, more and more special cases come up that lead to a usability nightmare. Also teaching conan to novice users will get harder because of the corner cases that have to be discussed.

If I have to dream something up, for me, the ideal solution (maybe for conan 2) would be to have a generic and builtin way to capture arbitrary data at export time (e.g., by assigning values to an `exported_values` attribute map). What gets exported should be obvious from reading the recipe alone and reusing values should be easy too.

I hope that feedback helps and makes sense. Anyway, keep up the good work.

Best,
Mario

**Comment by jgsogo** [comment] 2020-01-13 16:19
Thanks, @niosHD ! We are really interested in gather feedback from the community, we are about to start thinking in Conan 2.0 and we need to share all these suggestions and different approaches with all you [around the campfire during Conan Days](https://conandays.conan.io/), so the more you elaborate your suggestion, the better for us all (feel free to open a new issue with your proposal to get a dedicated thread, as it is more than `scm`)

---

For this feature, `conandata.yml` can be already present or not. Some recipes (like those in `conan-center-index`) list in that file the sources for each version of the library. If the file is not present and there is something to store from the `scm` field (currently this is the first field doing this), Conan will create the file, and append a structure like this one:

```yml
---
(existing content, or new file)

.conan:
    scm_data:
        type: git
        url: http://mygitserver.com/repo.git
        ... all fields but username and password
```

As this file is created in the cache, and the cache layout and files in it are implementation details, the user shouldn't notice about this change, the user doesn't need to know if the data is stored in the modified `conanfile.py` or in an additional file and the recipe is not modified. The important thing is to **realize that those fields in `scm` assigned to `auto` will get the actual url/commit-sha values** when installing the recipe, and that works now as it was before.

Is this confusing? Is it just a matter of improving the docs or is it really confusing? 

---

#### Alternative implementation 

A different approach has been proposed before (cannot find the issue): a syntax to declare data that will be stored into a file during the export phase and will be read from that storage during recipe install. Something explicit like:

```conan
class Recipe(ConanFile):
    scm = {'type': 'git',
                 'username': os.environ["USERNAME"],
                 'url': ${{ scm_url: tools.get_repo_url() }},
                 ....
```

That special syntax, with the `${{ }}`, could mean: during _export_ evaluate the expression and save the value in the variable with the given name. At other stages, don't evaluate and take the value from the storage. Something like this could be implemented, but it would require a preprocessing before loading the file as Python sources....

If you feel like, make your proposal, we will be really interested in reading it. Open an issue and detail it as much as possible.

Thank you very much for your feedback!

**Closed** 2020-01-15 12:09 UTC
Labels: complex: medium, component: scm, priority: high, stage: queue, type: feature
