### ISSUE TITLE
Missing MSVC version checks in conanbuildinfo.cmake

### ISSUE THREAD

**Issue by dutow** [conan-io/conan#1838] opened 2017-10-02 09:55 UTC
The following version checks are generated for Visual Studio in `conanbuildinfo.cmake`:

```
if( (CONAN_COMPILER_VERSION STREQUAL "14" AND NOT VERSION_MAJOR STREQUAL "19") OR
            (CONAN_COMPILER_VERSION STREQUAL "12" AND NOT VERSION_MAJOR STREQUAL "18") OR
            (CONAN_COMPILER_VERSION STREQUAL "11" AND NOT VERSION_MAJOR STREQUAL "17") OR
            (CONAN_COMPILER_VERSION STREQUAL "10" AND NOT VERSION_MAJOR STREQUAL "16") OR
            (CONAN_COMPILER_VERSION STREQUAL "9" AND NOT VERSION_MAJOR STREQUAL "15") OR
            (CONAN_COMPILER_VERSION STREQUAL "8" AND NOT VERSION_MAJOR STREQUAL "14") OR
            (CONAN_COMPILER_VERSION STREQUAL "7" AND NOT VERSION_MAJOR STREQUAL "13") OR
            (CONAN_COMPILER_VERSION STREQUAL "6" AND NOT VERSION_MAJOR STREQUAL "12") )
            conan_error_compiler_version()
        endif()
```

There are several bugs here:

1. It has no entry for Visual Studio 2017 (major 19 minor 11)
2. It doesn't check the minor version for Visual Studio 2015, and thus would also accept VS 2017 (which should be okay according to Microsoft - but it's not the way conan behaves for other otherwise compatible compilers)
3. It accepts any Visual Studio version not known by conan (for example, CONAN_COMPILER_VERSION "15", which is used for VS 2017)

(I found where these lines are written out, and considered submitting a pull request, but I wasn't sure how the second problem should be handled)

**Comment by memsharded** [comment] 2017-10-02 11:18
Yes, this is true. 
These lines are here for an extra-check about consistency of settings, so the guideline is: "only fail if you are quite sure it is an error". Otherwise, let it pass. 

So the idea is working fine: It allows building for VS2017, even if there is no check for it. So point 3 is quite on purpose, it worked fine. We really don't want to block legit uses because of a bug in the version checker.

A PR would be great, indeed. Regarding the minor (point 2), I think you might use ``VERSION_MINOR`` as well. If it doesn't work, no problem, just add the major, it would be an improvement.

Thanks!

**Comment by uilianries** [comment] 2019-06-28 17:05
@SSE4 could we close this one?

**Comment by SSE4** [comment] 2019-06-28 21:04
okay

**Comment by danimtb** [comment] 2019-07-10 16:34
Confirmed as fixed by this PR https://github.com/conan-io/conan/pull/5041 Thanks!

**Closed** 2019-07-10 16:34 UTC
Labels: complex: low, good first issue, to do, type: bug
