### ISSUE TITLE
Support .tar or .tar.xz files in unzip() function so I don't have to write stupid code

### ISSUE THREAD

**Issue by tru** [conan-io/conan#446] opened 2016-08-31 12:40 UTC
This is probably the dumbest `source` function I have had to write: https://gist.github.com/tru/0e5fe868a874e1a61b50651795a80917

:-)

.xz decompression is included by default in Python3 so that doesn't help me that much, but there are backported modules that can be used. Don't know if we want to depend on that as a requirement for conan? I am "ok" with just unzip being able to take a .tar, that removes the need for the really stupid code above. But still, would be nice if Conan supported .xz compressed files somehow.

**Comment by lasote** [comment] 2016-08-31 13:54
We want to keep the python2 compatibility. It can be used with pyliblzma dependency but not sure if it works well on windows.

**Comment by memsharded** [comment] 2016-08-31 14:47
Yes, the issue is to create a working conan in every platform with python2 compatibility, as in windows for example last time I checked it was difficult to integrate.

**Comment by tru** [comment] 2016-08-31 15:06
Can we at least make unzip() function take a .tar file instead of require it to be compressed?

**Comment by memsharded** [comment] 2016-09-07 11:56
So now, it is possible to extract .tar files in ``unzip()``, PR merged.

Providing .xz unzipping in a portable 2.7/3.X python in all OSs will be a nightmare for devops, so I'd say it is not worth to do it in conan, unless it was a partial implementation only working in Py3 and failing otherwise (but I am not sure about this approach, because user will complain about conan, instead of certain package limitation).

Is it possible to mark this issue as fixed then, and close it when it is released?

**Comment by tru** [comment] 2016-09-07 13:05
Yeah, That's fine!

**Comment by memsharded** [comment] 2016-09-13 22:04
Released in 0.12, (only the .tar management, the .xz decompression conan native support for python 2.7 would be too much by now)

**Closed by memsharded** 2016-09-13 22:04 UTC
Labels: enhancement, fixed

**Comment by Manu343726** [comment] 2018-05-29 09:46
I see that the lzma module is available in backports. It is possible that conan could depend on [`backports.lzma`](https://pypi.org/project/backports.lzma/) ?

**Comment by memsharded** [comment] 2018-05-29 09:52
@Manu343726 as you can see there, such backport also depends on the system xz, which is not available in all platforms, as Windows. So it is not possible, redistributing xz binaries for all platforms is not feasible.

**Comment by Manu343726** [comment] 2018-05-29 09:55
I see. Thanks for pointing out.
