### ISSUE TITLE
Unable to connect to conan-center

### ISSUE THREAD

**Issue by DominikDeak** [conan-io/conan#7573] opened 2020-08-21 00:39 UTC
When running `conan search "boost/*" -r=all`, or trying to run `conan install [...] --update` commands, I get errors like these:
```
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10399b0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
```

It seems that `conan.bintray.com` and `api.bintray.com` are down. External checks (21/8/2020) seems to confirm this:

https://downforeveryoneorjustme.com/conan.bintray.com

Screenshot:

![Screen Shot 2020-08-21 at 10 31 58 am](https://user-images.githubusercontent.com/1121604/90838941-97881200-e399-11ea-98c8-10b303589d71.png)

Traceroute to `api.bintray.com`: 

```
traceroute to bintray.com (108.168.194.93), 64 hops max, 52 byte packets
 1  * * *
 2  43.245.162.233 (43.245.162.233)  38.573 ms  41.687 ms  45.970 ms
 3  csw02-01.core.sy4.nsw.as133480.net.au (103.77.232.241)  44.212 ms
    csw01-01.core.sy4.nsw.as133480.net.au (103.77.232.245)  30.039 ms
    csw02-01.core.sy4.nsw.as133480.net.au (103.77.232.241)  37.511 ms
 4  103.77.232.253 (103.77.232.253)  40.577 ms  37.762 ms  39.549 ms
 5  as36351.nsw.ix.asn.au (218.100.52.100)  36.713 ms  61.699 ms  48.161 ms
 6  ae7.bbr01.eq01.syd02.networklayer.com (50.97.19.60)  39.131 ms  42.855 ms  32.763 ms
 7  ae3.bbr01.cs01.lax01.networklayer.com (50.97.19.192)  186.413 ms  189.110 ms  195.935 ms
 8  * ae5.cbs01.cs01.lax01.networklayer.com (50.97.17.62)  194.437 ms *
 9  * * ae2.cbs01.dr01.dal04.networklayer.com (169.45.18.6)  214.061 ms
10  ae8.cbs01.eq01.dal03.networklayer.com (169.45.18.70)  222.344 ms  229.100 ms *
11  ae33.bbr02.eq01.dal03.networklayer.com (50.97.17.55)  229.313 ms  219.948 ms
    ae33.bbr01.eq01.dal03.networklayer.com (50.97.17.53)  227.145 ms
12  ae6.dar01.dal05.networklayer.com (50.97.18.195)  235.103 ms  220.568 ms  223.185 ms
13  po2.fcr03.sr03.dal05.networklayer.com (173.192.118.145)  204.808 ms *  226.868 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  *^C
```

My `~/.conan/remotes.json` file:

```json
{
 "remotes": [
  {
   "name": "conan-center",
   "url": "https://conan.bintray.com",
   "verify_ssl": true
  },
  {
   "name": "bincrafters",
   "url": "https://api.bintray.com/conan/bincrafters/public-conan",
   "verify_ssl": true
  },
  {
   "name": "conan-community",
   "url": "https://api.bintray.com/conan/conan-community/conan",
   "verify_ssl": true
  }
 ]
}
```
### Environment Details (include every applicable attribute)
  * Operating System+version: macOS 10.15.4 
  * Compiler+version: apple-clang 12.0 (xcode 12 beta 5 build environment)
  * Conan version: 1.28.1
  * Python version: 2.7.16 and 3.8.5

**Comment by richard-viney** [comment] 2020-08-21 05:35
I've just started getting `ERROR: 502: Bad Gateway. [Remote: conan-center]` when running `conan install` from inside GitHub Actions. Might be related?

Does anyone know what the approximate uptime of Conan is? Today is my first time ever using it so I'm not sure if running into this is just bad luck or whether these outages are a known hazard.

Thanks.

**Comment by richard-viney** [comment] 2020-08-21 05:46
It started working again but then broke down part-way through. The output was:

```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

boost/1.71.0: Not found in local cache, looking in remotes...
boost/1.71.0: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
boost/1.71.0: Downloaded recipe revision 0
zlib/1.2.11: Not found in local cache, looking in remotes...
zlib/1.2.11: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
zlib/1.2.11: Downloaded recipe revision 0
bzip2/1.0.8: Not found in local cache, looking in remotes...
bzip2/1.0.8: Trying with 'conan-center'...
Downloading conanmanifest.txt
Downloading conanfile.py
Waiting 0 seconds to retry...
Waiting 0 seconds to retry...
WARN: Remotes registry file missing, creating default one in C:\Users\runneradmin\.conan\remotes.json
ERROR: Error 502 downloading file https://api.bintray.com/conan/conan/conan-center/v1/files/_/bzip2/1.0.8/_/d4a5c7144832d75fc3f349c5346160b0/export/conanfile.py
ERROR: Error 502 downloading file https://api.bintray.com/conan/conan/conan-center/v1/files/_/bzip2/1.0.8/_/d4a5c7144832d75fc3f349c5346160b0/export/conanfile.py
ERROR: Failed requirement 'bzip2/1.0.8' from 'boost/1.71.0'
ERROR: Error 502 downloading file https://api.bintray.com/conan/conan/conan-center/v1/files/_/bzip2/1.0.8/_/d4a5c7144832d75fc3f349c5346160b0/export/conanfile.py. [Remote: conan-center]
```

**Comment by jgsogo** [comment] 2020-08-21 07:30
Hi! I think it was bad luck. We are experiencing some issues, but it is the exception: https://status.bintray.com/  Hope it will be fixed soon.

**Comment by memsharded** [comment] 2020-08-23 20:23
Hi @richard-viney 

This issue should be gone now, bintray was fixed a couple of days ago. Please let us know if the issue persist, or close the issue otherwise. Thanks!

**Comment by richard-viney** [comment] 2020-08-23 22:11
Seems to have resolved, but I wasn’t the one who opened the issue originally so @DominikDeak would have to close it.

**Comment by DominikDeak** [comment] 2020-08-27 15:14
Unfortunately, I'm forced to reopen this issue as conan-center seems to be down again. Running the command `conan search "boost/*" -r=all` produces the same error as shown below. This seems to be a recurring problem.

```
ERROR: HTTPSConnectionPool(host='conan.bintray.com', port=443): Max retries exceeded with url: /v1/conans/search?q=boost%2F%2A (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10399b0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

Unable to connect to conan-center=https://conan.bintray.com
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.

```

**Comment by memsharded** [comment] 2020-08-27 15:33
Hi @DominikDeak 

Can you please try to install some package from CnanCenter?
Like ``conan install zlib/1.2.11@ -r=conan-center``? Seems to work here. The search can have some problems and timeouts, this is a known issue and we recommend searching in the frontend: https://conan.io/center.

**Comment by memsharded** [comment] 2020-08-27 15:43
Update, it is failing a bit randomly. We have reported the issue to the bintray team. Thanks for reporting.

**Comment by DominikDeak** [comment] 2020-08-28 03:32
> Can you please try to install some package from CnanCenter?
Like conan install zlib/1.2.11@ -r=conan-center? Seems to work here. The search can have some problems and timeouts, this is a known issue and we recommend searching in the frontend: https://conan.io/center.

That seems to works fine.

 I think the issue appears to present itself when I search with wild cards in the package version.  For example:
`conan search "boost/*" -r=all` 
produces the aforementioned error, but when I specify a version number:
`conan search "boost/1.73.0" -r=all` 
the search succeeds.

**Comment by jgsogo** [comment] 2020-08-28 07:47
cc/ @czoido  

Searching with patterns looks like much slower indeed, not only in Bintray (https://github.com/conan-io/conan/issues/5432). We applied a workaround in the Conan client (#5433). Now with so many packages in ConanCenter this pain is much bigger and we are trying to allocate some time from other development teams to work on it.

Thanks for reporting, it is important for us to know and prioritize.

**Comment by SignalWhisperer** [comment] 2020-08-29 16:11
I was also searching for "boost", and either it took 3 minutes to get results, or I got a read timeout after 4 minutes. As my first experience with Conan, I must say it's a bit scary to see I can't even search for my favorite package. For now I guess I'll have to use the web interface instead of the command line. Don't you use the same API for both?

**Comment by memsharded** [comment] 2020-08-30 08:30
Hi @TehWan 

Yes, we are aware of this annoying situation. The thing is that they use different infrastructure, ConanCenter frontend uses a ElasticSearch designed for this web UI, but Conan client connects via the Conan api, and it was not designed in the Bintray backend for that scale. It might take a while, but it is on the roadmap to improve this.

**Comment by alexanderwwagner** [comment] 2021-09-30 15:23
Hello,
since today I have the same problem which is mentioned here.
Within my github action the build fails.
A few days ago there was no problem.
Are there at the moment any maintenance work?

Thank you!

`ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))
#30 7.021 
#30 7.021 Unable to connect to conancenter=https://center.conan.io
#30 7.021 1. Make sure the remote is reachable or,
#30 7.021 2. Disable it by using conan remote disable,
#30 7.021 Then try again.`

**Comment by memsharded** [comment] 2021-09-30 15:24
@alexanderwwagner please track: https://github.com/conan-io/conan/issues/9695

**Comment by jgsogo** [comment] 2021-10-11 14:28
This issue is about Bintray remote which has been deprecated for months... New issues might be related to the new infrastructure. Let's close this one, better not to mix them.

**Closed as completed by jgsogo** 2021-10-11 14:28 UTC
Labels: stage: triaging
