### ISSUE TITLE
[question] How to install Conan package with original versions of dependencies?

### ISSUE THREAD

**Issue by stevn** [conan-io/conan#15328] opened 2023-12-22 08:12 UTC
### What is your question?

I have a Conan package in JFrog Artifactory which I want to install on my system. It is available as a precompiled binary package on the server, including all of its dependencies. However, this package recipe uses **version ranges**, and that breaks the install process sometimes.

In this case, in one of the newer versions of the dependencies something is broken, so currently the `conan install` command fails.

But actually I **do not want to use the newer versions of the dependencies** anyway. I would much prefer to use the dependency tree that was used at build time.

I can query that build information via:

    conan get -r remote myapp/1.0.0@user/channel:pkgid conaninfo.txt > conaninfo.txt

(I am still using Conan 1.x.)

This `conaninfo.txt` now lists the original build-time versions of the dependencies. These are the ones that I would like to install. However I cannot find a way to get Conan to install these original versions instead of the newer versions.

I could install these of course based on a lockfile, but the problem is that I do not have that lockfile. And lockfiles are tricky to manage consistently anyway. Ideally they should be uploaded to JFrog together with the Conan package, and stored there in a simple query-able state. But thats another topic I guess.

It seems like there's no way to convert a `conaninfo.txt` to a lockfile? So I'm actually kind of stuck.

One workaround might be to convert the `conaninfo.txt` to a temporary `conanfile.txt` using a custom script, since they seem pretty similar. I could then use `conan lock create` to create a lockfile from the `conanfile.txt` and then run `conan install`:

    conan install -r remote --lockfile tmp.lock myapp/1.0.0@user/channel

But that seems a bit fragile / clumsy.

Another workaround might be to parse the `conaninfo.txt` and generate a list of `--require-override` command line options and append these to the `conan install` command like this:

    conan install -r remote --require-override mydep1/1.0.0@user/channel --require-override mydep2/1.0.0@user/channel myapp/1.0.0@user/channel

But that's also not very user friendly.

Do you have any recommendations how to solve this?

Is there really no way to run `conan install` based on the original versions of dependencies used at build time? I would think that something like this should be feasible:

    conan install -r remote --require-original-versions myapp/1.0.0@user/channel:pkgid

### Have you read the CONTRIBUTING guide?

- [X] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-12-22 09:25
Hi @stevn 

Thanks for your question

> I could install these of course based on a lockfile, but the problem is that I do not have that lockfile. And lockfiles are tricky to manage consistently anyway. Ideally they should be uploaded to JFrog together with the Conan package, and stored there in a simple query-able state. But thats another topic I guess.

Yes, the solution is a lockfile, this is a standard solution accross different package manager for different languages. It is necessary to capture the lockfile when the package is built, and store it.

> It seems like there's no way to convert a conaninfo.txt to a lockfile? So I'm actually kind of stuck.

Yes, the ``conaninfo.txt`` does not contain enough information to reproduce the dependency graph that it was used at build time, because it models the ``package_id`` variability, not the whole graph.

> Is there really no way to run conan install based on the original versions of dependencies used at build time? I would think that something like this should be feasible:

Not at the moment, but it is planned, and we already have a PR open for it. One of the major challenges is that lockfiles in Conan 1.X were challenging and fragile. It was not possible to implement such a feature on top of it. So the recommended way to move this forward is:

- First, update to Conan 2.0. Lockfiles in 2.0 are way more powerful and simpler to manage
- Initially, store the lockfile (1 for all configurations is possible in 2.0), either in the repo itself (works well for consumer packages like applications). Note that you also can use that lockfile and apply it to the whole dependency graph, any package in the middle of the graph, and it will respect its locked dependencies.
- Finally, track https://github.com/conan-io/conan/pull/10261, give feedback when it starts to move forward, test it and contribute with your feedback to make it the behavior you need.

More info about lockfiles in 2.0:

- https://docs.conan.io/2/tutorial/consuming_packages/intro_to_versioning.html
- https://docs.conan.io/2/tutorial/versioning/lockfiles.html

**Comment by stevn** [comment] 2024-01-07 14:18
@memsharded Thanks for your detailed explanation! I understand the need to upgrade to Conan 2 and use lockfiles, which will solve this scenario properly.

However, I was able to solve my immediate problem with a small script. It first gets the versions of the dependencies of the package to be installed with `conan get`. Then it runs `conan install` with `--require-override` to prevent the Conan client pulling newer versions due to the usage of version ranges.

This is not guaranteed to work in every case, but was helpful for me. Maybe something like this would be helpful for others as well, so might be interesting as a new feature for a future Conan client release.

You can find the script here:

[install.py](https://github.com/stevn/conan_scripts/blob/main/install.py)

**Comment by memsharded** [comment] 2024-01-07 20:59
> However, I was able to solve my immediate problem with a small script. It first gets the versions of the dependencies of the package to be installed with conan get. Then it runs conan install with --require-override to prevent the Conan client pulling newer versions due to the usage of version ranges.

I see. It is possible to achieve the same by doing a ``conan download`` too, and it might be possible that the ``--require-override`` is not fully necessary if you don't use the ``--update``, Conan resolves first in the cache, so if you downloaded the right versions/revisions to the local cache, then those will be prioritized instead of the remotes one.

I think that the future is either using explicit lockfiles or automatically stored lockfiles like in https://github.com/conan-io/conan/pull/10261, so if your question is solved and your workaround is good for now while you are in 1.X, then I think we can close this ticket. Thanks!

**Closed as completed** 2024-01-07 21:23 UTC
