### ISSUE TITLE
Gettting import error while running build with conan 

### ISSUE THREAD

**Issue by mkjkec2005** [conan-io/conan#14142] opened 2023-06-21 10:51 UTC
### What is your question?

Please find the error details below:

-- PACKAGE_NAME = dbiclient; PACKAGE_DESCRIPTION = dbiclient; CONTROL_SOURCE_DIR = /home/mkrishan/conan_issue/issue@2/build_sim_frcug3x/src/external-repos/dbiclient
-- VERSION_INFO 6.1.0.1
-- PACKAGE_NAME = profiles; PACKAGE_DESCRIPTION = Profile pkg; CONTROL_SOURCE_DIR = /home/mkrishan/conan_issue/issue@2/src/application/profiles
-- VERSION_INFO 7.0.0.10
-- curl-cmake: Arch is=x86_64, TAR_FILE=
-- Conan: checking conan executable
-- Conan: Found program /home/mkrishan/.local/bin/conan
-- Conan: Version found Conan version 1.53.0
-- Conan executing: /home/mkrishan/.local/bin/conan install . --remote conan-infn --settings build_type=Debug OFF --settings compiler=gcc --settings compiler.version=8 --settings compiler.libcxx=libstdc++11 --settings compiler.cppstd=14
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug OFF
compiler=gcc
compiler.cppstd=14
compiler.libcxx=libstdc++11
compiler.version=8
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

ERROR: Invalid imports line: lib, * -> /home/mkrishan/conan_issue/issue@2/build_sim_frcug3x/src/external-repos/curl/
EX: OpenCV/lib, * -> ./lib
Wrong imports argument '2/build_sim_frcug3x/src/external-repos/curl/'. Need a 'arg=value' pair.
CMake Error at build_sim_frcug3x/conan_utils/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  src/external-repos/curl/CMakeLists.txt:19 (conan_cmake_install)

-- Configuring incomplete, errors occurred!

### Have you read the CONTRIBUTING guide?

- [ ] I've read the CONTRIBUTING guide

**Comment by memsharded** [comment] 2023-06-21 16:54
Hi @mkjkec2005 

It seems that there would be missing some information here. Do you have a ``conanfile`` anywhere with an ``imports``? Is it being defined in ``cmake-conan`` wrapper? Can we see the ``CMakeLists.txt`` defining the Conan stuff?

**Comment by mkjkec2005** [comment] 2023-07-13 02:17
Hi, 

Please find the CMake file snippet below for your reference:

project(curl)
    message(STATUS "curl-cmake: Arch is=${ARCH}, TAR_FILE=${CURL_TAR_FILE}")
    set(CURL_LIB_FILE libcurl.so.4.7.0)
    set(CURL_BIN_FILE curl)

    set(CONAN_REPO conan-infn)
    include(${CMAKE_BINARY_DIR}/conan_utils/conan.cmake)

    conan_cmake_configure(REQUIRES libcurl/1.1.4 GENERATORS cmake_find_package IMPORTS "lib, * -> ${CMAKE_CURRENT_BINARY_DIR}/")

    conan_cmake_autodetect(settings)


if (ARCH STREQUAL "arm64")
    conan_cmake_install(PATH_OR_REFERENCE .
                           REMOTE ${CONAN_REPO}
                           PROFILE G30ARM)
else()
    conan_cmake_install(PATH_OR_REFERENCE .
                           REMOTE ${CONAN_REPO}
                           SETTINGS ${settings})
endif()


    file(COPY ${CMAKE_CURRENT_BINARY_DIR}/${CURL_LIB_FILE} DESTINATION ${CMAKE_BINARY_DIR}/lib)
    file(COPY ${CMAKE_CURRENT_BINARY_DIR}/${CURL_BIN_FILE} DESTINATION ${CMAKE_BINARY_DIR}/bin)
    
    add_library(bullseyecurl INTERFACE)
    target_link_libraries(bullseyecurl INTERFACE ${CMAKE_BINARY_DIR}/lib/${CURL_LIB_FILE})

Regards,
Mohan

**Comment by memsharded** [comment] 2023-07-13 07:50
I think the problem is the line ``IMPORTS "lib, * -> ${CMAKE_CURRENT_BINARY_DIR}/"``

I think this is generating a wrong ``conanfile.txt``. Maybe you can check that file and copy it here? It should be in your CMAKE_CURRENT_BINARY_DIR.


As a side note, please recall that you are using the legacy ``cmake_find_package`` generators, legacy imports, etc (all of that deprecated, and replaced in Conan 1.X for new alternatives), it would be important to know that it is necessary to upgrade those.

**Comment by memsharded** [comment] 2024-09-13 04:46
Closing as outdated.
``imports`` have been removed in Conan 2, now explicit ``copy()`` should be done.

**Closed as not planned by memsharded** 2024-09-13 04:46 UTC
Labels: stage: triaging
