### ISSUE TITLE
[bug] exported sources are not verified when downloading a package from remote.

### ISSUE THREAD

**Issue by mhabibav** [conan-io/conan#14313] opened 2023-07-17 10:25 UTC
### Environment details

* Operating System+version: _Irrelevant_
* Compiler+version: _Irrelevant_
* Conan version: **2.0.6**
* Python version: **3.11.4**

### Steps to reproduce

1. Create a `sign.py` file as in this tutorial: https://docs.conan.io/2/reference/extensions/package_signing.html
2. Add code to sign each file in `artifacts_folder` and create a corresponding signature file in `signature_folder`. 
3. Make sure to print the names of signed files.
4. Upload any package to any remote and observe the output of your sign code.
5. Add code to verify each file in `artifacts_folder` against the corresponding signature file in `signature_folder`.
6. Make sure to print the names of the files you verify.
7. Download the same package from the remote and observe the output of the verify code.
8. Notice that the `conan_sources.tgz` file is signed but not verified.

I think the file responsible is `conans/client/remote_manager.py`. In the `RemoteManager` class, the `get_recipe` and `_get_package` methods include a call to `self._signer.verify` while `get_recipe_sources` doesn't.

**Comment by memsharded** [comment] 2023-07-17 12:54
Hi @mhval70 

Thanks for the feedback!
It seems you are right, the ``get_recipe_sources()`` should include a ``verify()`` too. Let's double check, and add it, assigning it for next 2.0.9

**Comment by memsharded** [comment] 2023-07-19 11:14
I am submitting PR https://github.com/conan-io/conan/pull/14331 to fix this.
The problem is that it requires a new ``files`` argument, so it will be necessary to modify existing plugin code. As this is in ``preview`` status, I think this change makes sense and it is worth this small break of the interface.

I will also make sure to document the implementation of the plugin with an extra ``**kwargs`` to avoid potential further breakings in the future.

What do you think?

**Closed as completed** 2023-07-19 11:46 UTC
Labels: stage: triaging

**Comment by memsharded** [comment] 2023-07-19 11:52
https://github.com/conan-io/conan/pull/14331 has been merged to be part of 2.0.9, so this issue was closed automatically, but please let me know.

**Comment by mhabibav** [comment] 2023-07-19 15:27
Looks great. Thanks for the quick fix.
But I'd suggest passing the files as a list rather than a dictionary.

**Comment by memsharded** [comment] 2023-07-19 15:31
> But I'd suggest passing the files as a list rather than a dictionary.

It is an iterable, so users can do ``for f in files``, I have documented it as an iterable not as a dict, it shouldn't be a big problem. The idea is that users had the full path already there if they wanted, but I guess they can also compose it with the artifacts_folder.

**Comment by mhabibav** [comment] 2023-07-19 15:48
Oh I see now. I haven't looked deeply into the datatype but that makes sense. Thanks again for your effort.
