### ISSUE TITLE
Install doesn't always try all remotes

### ISSUE THREAD

**Issue by sztomi** [conan-io/conan#2604] opened 2018-03-13 12:55 UTC
**conan version**: 1.0.4

This issue seems to manifest in a couple of situations but the following flow is one that will reproduce it:

1. On client1 and client2, set up two remotes: `Argon` and `Boron` (in this order)
1. Upload `libfoo/1.0` to `Boron` (from CI, i.e. a client other than client1 and client2)
1. On client1 **export** a `libfoo/1.1`
1. On client2 **upload** a `libfoo/1.1` to `Boron`
1. On client1 try to install `libfoo/1.1`

**Expected result**: conan tries to install from local cache, then `Argon`, then `Boron`. It finds the package in `Boron` and installs it.

**Actual result**: conan tries to install from local cache, then `Argon`. `Boron` is never hit (Artifactory logs exclude an entry for access) and the installation fails.

**Workaround**: adding `-r Boron` to the install command will make conan try that remote and install the package successfully.

- [x] I've read the [CONTRIBUTING guide](https://raw.githubusercontent.com/conan-io/conan/develop/.github/CONTRIBUTING.md).
- [x] I've specified the Conan version, operating system version and any tool that can be relevant.
- [x] I've explained the steps to reproduce the error or the motivation/use case of the question/suggestion.

**Comment by memsharded** [comment] 2018-03-13 13:58
It seems the confusion could be that the error message:

```
Pkg/0.1@lasote/testing: Installing package
Requirements
    Pkg/0.1@lasote/testing from local cache
Packages
    Pkg/0.1@lasote/testing:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

Pkg/0.1@lasote/testing: WARN: Can't find a 'Pkg/0.1@lasote/testing' package for the specified options and settings:
- Settings: 
- Options: 
- Package ID: 5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9

ERROR: Missing prebuilt package for 'Pkg/0.1@lasote/testing'
Try to build it from sources with "--build Pkg"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

Is not clear that it only used the local cache to look for binaries. Would the solution be to explicitly add something in the last lines to highlight that this is a local-cache package?

**Comment by sztomi** [comment] 2018-03-13 15:58
That would be one part of the solution IMO. We actively use two remotes (one for packages, one for toolchains). Our tooling can append one of the two remotes in order to force conan looking at it. I think a more complete solution would be to add an option to install: `--try-remotes`, which would cause conan to try local, remote1, remote2 etc. In case this would overwrite a local package a warning could be issued.

**Comment by vadixidav** [comment] 2018-03-20 20:01
I am not sure if it is the exact same as this issue, but I have an instance where an internal repository holds a build for OpenSSL from conan/stable that doesn't exist in conan-center, but since conan-center was where the OpenSSL package ref was originally obtained from, it says this: `OpenSSL/1.0.2l@conan/stable from conan-center`. It then proceeds to only check conan-center for builds in the future even though the build was added to our internal repository which is at index 0 (inserted with `conan remote add -i 0`) and therefore checked first, not the internal repository. Removing `conan-center` caused it to suddenly start working because it now says `OpenSSL/1.0.2l@conan/stable from local`. This causes it to check all the remotes for builds. In conclusion, if a package is fetched from a particular remote, until that remote is removed from the remotes Conan will only check for builds of that ref from the remote it was fetched from or from the local cache, but not from any other remote. This is not the functionality I expected, and it does make it necessary to remove conan-center from our CI machine's remotes and will likely complicate matters in the future if we have multiple internal repositories because we will have to specify in revision control which remote to use using the `-r` flag for our CI testing (we don't currently have multiple internal repositories) and every dependency of any given project will have to live on that remote to avoid any sort of conflicts, which means everything would need to be duplicated across every remote (but not necessarily the builds, which take up the most space).

I am fairly certain this is not the intended behavior because it makes it so removing a remote can cause something to start working, which is highly unintuitive. For my needs, just checking if a build exists on all remotes, rather than the one originally installed from, is fine.

**Comment by memsharded** [comment] 2018-03-20 22:27
HI @vadixidav 

Yes, you are right, the logic is:
- Once a package has been installed from a remote, it keeps the reference to that remote.
- It doesn't matter that you insert a new remote, as git branches, they will keep tracking the previous remote.
- You don't need to remove a remote, you can always re-assign remotes per package with ``conan remote update_ref <pkg-ref> <remote>``
- If you remove that previously assigned remote, the packages retrieved from them become "orphan", without any remote, i.e., just living in the local cache. Then, the standard behavior of looking in remotes for this reference is fired.

I think this follows the principle of least surprise, in the same way you don't want to have git change the remote a branch is currently tracking because you added another git remote. I would need to understand your whole flow. Actually I don't think directly using conan-center from your CI is a good practice, specially if you are going to have your own builds from those packages too. Also, adding, removing remotes in the middle of some CI build might not be good practice either. Typically all you want to do when starting a CI build is some ``conan config install`` to get your reproducible configuration and work from there.

The thing with ``--try-remotes`` feature is that it could bring a new set of potential problems, for example, what happens if there is a build in other remote for that package, but the recipe for that package in tha other remote is different to the installed one. Should that be an error? A warning and continue looking for it in other remotes? I am not saying that we will not do it, but that we have to carefully study it and analyze implications. I'll bring it to discuss with the team, thanks very much for the feedback.

**Comment by steve-white** [comment] 2019-02-28 10:28
It'd be great if this logic was explained a bit better in the documentation e.g under: https://docs.conan.io/en/latest/reference/commands/misc/remote.html

**Comment by memsharded** [comment] 2023-10-08 00:00
Install behavior has been reviewed in 2.0, now iterating all remotes for binaries if necessary (but not always checking all, unless ``--update`` is provided, for efficiency). I think we can close this issue, please create new ones for any further questions or comments.

**Closed by memsharded** 2023-10-08 00:00 UTC
Labels: type: look into, type: feature
